// 28.1 Prefunding quality control program (selection, review scope, reverifications, defect handling before closing, reporting)
// spec/sections/28-quality-control-hmda-and-fraud-aml-reporting/28-1-prefunding-quality-control-program-selection-review-scope-re.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("28.1-T1: Given the refinance fixture reaches `ptd_cleared` Tue Oct 27, 2026 and the Oct 28 06:00 MST draw selects it, then a `qc_reviews{kind=prefunding, selection_basis=random}` row exists, `production_hold_applied = true`, 23.3's checklist item `qc_prefunding` fails, and `SM_QC_PREFUNDING_REVIEW_SLA_2BD` is due Fri Oct 30, 2026.", { todo: true });
test("28.1-T2: Given the review closes `no_defect` Thu Oct 29 10:42 MST with no severity \u2264 2 findings and the review is not in the officer sample, then `hold_released_at` is set by the agent, `qc.review.closed` is emitted and 23.3 can issue CTC Fri Oct 30.", { todo: true });
test("28.1-T3: Given the purchase fixture is selected Mon Nov 9, 2026 by `du_red_flag_message` and `gift_funds_pct > 50%`, then `review_type = full_file`, and a severity-1 finding cannot reach `released` without a `qc_officer` decision (`SM_QC_OFFICER_FINDING_SLA_1BD` due Thu Nov 12 because Wed Nov 11 is a holiday).", { todo: true });
test("28.1-T4: Given findings F1 (sev 2) and F2 (sev 1) are released Tue Nov 10 09:41, then 23.3 reopens conditions within the same transaction, `applications.qc_prefunding_status = defect_open`, and `assertGateOpen(FNMA_D1_2_01_PREFUNDING_PRIOR_TO_CLOSING_GATE)` returns closed until both findings are `corrected`.", { todo: true });
test("28.1-T5: Given F2 is corrected Fri Nov 13 08:10 and the review closes `defect_corrected`, then CTC may issue and the CD delivered Fri Nov 13 supports consummation Wed Nov 18 (three Reg Z specific business days: Nov 14, 16, 17).", { todo: true });
test("28.1-T6: Given a production agent run attempts `closeReview` or a QC agent run attempts `clearCondition`, then both are refused by role and identity checks and logged as sev 2 to `compliance-sentinel`.", { todo: true });
test("28.1-T7: Given the DU request payload of Oct 22 shows monthly income $14,850.00 but the recomputation from the paystubs yields $13,900.00 (\u22126.4%), then a `data_integrity/du_input_variance` finding of severity 1 is drafted with both values and the evidence refs, and the loan cannot close until a DU resubmission (23.1) resolves it.", { todo: true });
test("28.1-T8: Given a closing consummated Fri Nov 6 while a prefunding review is `in_review`, then `qc.breach.closed_with_open_review` fires at sev 1, the review continues as `post_closing_discretionary`, and 29.3's delivery gate reads the sustained-finding state.", { todo: true });
test("28.1-T9: Given the October 2026 sample's last review closes Fri Oct 30, then `FNMA_D1_1_03_PREFUNDING_REPORT_30` is due Sun Nov 29 and the report is issued and signed by Fri Nov 27 with a three-month trend (Aug\u2013Oct) and the sample description (33 of 118 eligible; 28.0%).", { todo: true });
test("28.1-T10: Given the same defect code appears in 3 loans in one month, then the report contains a corrective-action plan with owner, expected resolution and due date, and `compliance-sentinel` tracks its completion.", { todo: true });
test("28.1-T11: Given the officer's concurrence rate for a month is 85%, then 31.2 receives a model-review escalation and the officer sample rate for the next month is 20%.", { todo: true });
test("28.1-T12: Given a reverification request sent Mon Nov 9 with no response by Thu Nov 12 (+3 BD) and Mon Nov 16 (+5 BD), then a second request is logged and the officer decides `unable_to_complete` or keeps the hold; the file records both request dates.", { todo: true });
test("28.1-T13: Given any QC review, then its `agent_decisions` row contains `rule_set_versions`, `model_version`, `prompt_version`, `inputs_hash`, per-test evidence refs, and no field derived from `applicant_demographics` (access log shows zero reads by `qc-audit`).", { todo: true });
