// 28.2 Post-closing QC program, Fannie Mae QC reviews (Loan Quality Connect), self-reporting, defect rates, and remedies/appeals
// spec/sections/28-quality-control-hmda-and-fraud-aml-reporting/28-2-post-closing-qc-program-fannie-mae-qc-reviews-loan-quality-c.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("28.2-T1: Given loans disbursed in November 2026, then `qc_cycles.cycle_due_on = 2027-02-28` and the population includes the refinance (disbursed Nov 12) and the purchase (funded Nov 18/19) fixtures; a loan consummated Nov 30 and disbursed Dec 3 is in the December cycle (due Mar 31, 2027).", { todo: true });
test("28.2-T2: Given a population of 118, then the `ten_percent` method selects 12 random loans stratified across every product/transaction/occupancy/channel present, and discretionary selections are tagged separately and excluded from the random defect-rate denominator.", { todo: true });
test("28.2-T3: Given the refinance fixture with DU-validated income/employment closed Nov 6 before the Close by Date Dec 7 and vendor-verified assets, then `review_scope` marks income, employment and assets as exempt, `credit_refresh_required = true`, `occupancy_required = true`, and no transcripts are ordered (no tax returns relied upon).", { todo: true });
test("28.2-T4: Given a self-employed borrower whose transcripts show 2025 net profit $61,200 versus $78,900 used, then a severity-1 finding is released, `reunderwrite_required = true`, the shadow re-underwrite yields DTI 54.1% and `eligible_as_delivered = false`, and after the officer's confirmation on Wed Jan 20, 2027 the self-report is due Fri Feb 19, 2027 and is submitted once via LQC with category/sub-category/defect and documents.", { todo: true });
test("28.2-T5: Given an LQC file request notified Wed Dec 16, 2026, then `FNMA_D2_1_LQC_RESPONSE_30` is due Fri Jan 15, 2027; the package hash is frozen before the operator escalation; and the timer is satisfied only by an operator-confirmed `submitted_at` with an LQC reference.", { todo: true });
test("28.2-T6: Given a repurchase demand received Mon May 3, 2027, then `FNMA_A2_3_2_01_REMEDY_PAYMENT_60` and `FNMA_A2_3_2_03_APPEAL1_60` are both due Fri Jul 2, 2027; filing appeal 1 on Thu Jun 10 suspends the payment timer; a denial received Mon Aug 9 makes appeal 2 due Tue Aug 24, 2027 and the console refuses an appeal-2 draft without a \"new information\" attachment.", { todo: true });
test("28.2-T7: Given the November 2026 cycle is not `reported` by Sun Feb 28, 2027, then `FNMA_D1_3_QC_CYCLE_90` breaches at sev 1; if still not reported by Tue Mar 30, 2027 (+30), then `FNMA_D1_3_01_QC_ARREARS_NOTICE` requires the officer's written notice to the QC Specialist and the agent has a draft ready.", { todo: true });
test("28.2-T8: Given 12 random reviews with 2 initial severity-1 findings and 1 corrected, then the report shows gross 16.7%, net 8.3%, a three-month trend, the quarterly comparison to the 3% target, the compliance-vs-underwriting split, the sample description (12 of 118 random = 10.2%) and a corrective-action plan.", { todo: true });
test("28.2-T9: Given the partner performs no 10% re-review within 15 days of `qc.cycle.completed`, then `FNMA_D1_1_02_VENDOR_REVIEW_10PCT_MONTHLY` breaches at sev 1 to the partner `officer` and the monthly report states the gap.", { todo: true });
test("28.2-T10: Given the refinance fixture purchased Nov 19, 2026 with first payment Jan 1, 2027, then `rep_warrant_relief{payment_history_36}.target_36th_due_on = 2029-12-01`; a third 30-day delinquency sets `at_risk = true`; `status = confirmed_by_fnma` is set only from a parsed Fannie Mae relief report.", { todo: true });
test("28.2-T11: Given a soft tri-merge in QC shows an $18,400 auto loan opened Nov 20, 2026 (after the Nov 6 note date), then the liability reconciliation records it as post-closing with no finding; an auto loan opened Oct 28 would trigger a DTI recomputation and, if outside B3-2-10 tolerance, `reunderwrite_required`.", { todo: true });
test("28.2-T12: Given the QC agent attempts to submit an LQC self-report or to pay a demand, then the action is refused; only an `fnma_portal_operator` escalation (submission) or a partner `officer` decision (payment) can satisfy the timers.", { todo: true });
test("28.2-T13: Given a CU score of 2.5 on a one-unit appraisal with relief conditions met, then comparables are not reverified but property eligibility, unacceptable-practice checks and CU message reconciliation still run; with CU 3.4 the comparables are reverified and a desk review is ordered only if the assessment cannot be completed.", { todo: true });
