// 28.3 HMDA data capture, ULI generation, rate-spread and other derived fields, LAR editing, annual/quarterly submission, and public disclosure obligations
// spec/sections/28-quality-control-hmda-and-fraud-aml-reporting/28-3-hmda-data-capture-uli-generation-rate-spread-and-other-deriv.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("28.3-T1: Given `application.received` on Mon Oct 5, 2026 for the refinance fixture, then a `hmda_records` row exists within the same transaction with `uli = 549300SMPARTNER00155A26R00010149`, `check_digit = 49`, `application_date = 2026-10-05`, `loan_purpose = 31`, and the FFIEC validate call returns `isValid = true`.", { todo: true });
test("28.3-T2: Given the FFIEC example loan ID `EILKZAIZF6TX4HB8ZDX33H`, when the check digit is computed, then it equals `54`; given the ULI `549300SMPARTNER00155A260R0010149` (transposed), then validation fails (remainder 60).", { todo: true });
test("28.3-T3: Given APR 6.159% (25.1's fixture result), APOR 6.020% for the week containing Wed Oct 7, 2026, a 30-year fixed loan and action 1, then `rate_spread = 0.139` locally and the FFIEC API response is `\"0.139\"`; given a relock on Mon Nov 2, 2026, then `rate_set_date = 2026-11-02` and the APOR of that week is used.", { todo: true });
test("28.3-T4: Given the loan funds Thu Nov 12, 2026 after rescission expires Tue Nov 10, then `action_taken = 1` and `action_taken_date = 2026-11-06`; given a rescission on Mon Nov 9, then `action_taken = 2`.", { todo: true });
test("28.3-T5: Given the loan is purchased by Fannie Mae Thu Nov 19, 2026, then `purchaser_type = 1`; given no sale by Dec 31, 2026, then the Jan 1, 2027 job sets `purchaser_type = 0`.", { todo: true });
test("28.3-T6: Given the denied application (notice Tue Oct 27, 2026) with reasons DTI and credit history, then `action_taken = 3`, `action_taken_date = 2026-10-27`, `denial_reasons = {1, 3}`, `rate_spread = NA`, money fields NA, `aus_1 = 1`, `aus_result_1 = 5`.", { todo: true });
test("28.3-T7: Given final action in Q4 2026, then `HMDA_1003_4F_LAR_ENTRY_Q30` is due Sat Jan 30, 2027 and the daily job marks the record `complete` no later than that date; a record still incomplete on Jan 31 raises `hmda.completeness.failed` at sev 2.", { todo: true });
test("28.3-T8: Given `applications.score_model = vantagescore_4`, then `applicant_score_model = 15`; given Classic FICO with the middle score from Experian, then `2`; a borrower with no score \u2192 score `8888`, model `9`.", { todo: true });
test("28.3-T9: Given the annual file for 2026 uploaded Tue Jan 5, 2027 with one validity edit, then the record is corrected at source, a new submission sequence is created, and status 14 is reached only after quality and macro edits are verified with stored explanations; the `/sign` call succeeds only under the officer's token and stores a receipt; `HMDA_1003_5_ANNUAL_0301` (Mon Mar 1, 2027) is satisfied.", { todo: true });
test("28.3-T10: Given a partner with 0 closed-end originations in 2024 and 900 in 2025, then `hmda_coverage_tests{2026}.covered = false`, no filing timer is armed for 2026 data, and every record is still captured and edit-checked; given 310 and 1,140, then `covered = true`.", { todo: true });
test("28.3-T11: Given a telephone/internet application where the applicant declines to provide demographics, then ethnicity `3`, race `6`, sex `3`, observed flags `3`, and no `visual_observation_used = true` is possible (constraint violation if attempted).", { todo: true });
test("28.3-T12: Given a discount-point amount of $0 on the final CD, then the LAR field is blank (not `0`, not `NA`); given Total Loan Costs of $1,245.00, then `1245.00`; given origination charges $0, then `0`.", { todo: true });
test("28.3-T13: Given the FFIEC disclosure-statement notice is received Wed Jun 16, 2027, then the (b)(2) written notice is available at the home office and MSA branches by Mon Jun 21, 2027 (3 business days) with `available_until = 2032-06-21`.", { todo: true });
test("28.3-T14: Given any `hmda` agent run, then the access log shows reads of `applicant_demographics` only by the `hmda` agent identity and 31.2, and no production agent.", { todo: true });
