// 28.4 Fraud, misrepresentation, AML/SAR, OFAC, and Fannie Mae fraud reporting
// spec/sections/28-quality-control-hmda-and-fraud-aml-reporting/28-4-fraud-misrepresentation-aml-sar-ofac-and-fannie-mae-fraud-re.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("28.4-T1: Given `fraud.suspicious.determined` with `initial_detection_at = 2026-10-19` and a subject identified, then `BSA_1029_320_SAR_30` is due Wed Nov 18, 2026 and is satisfied only by an officer-executed `sar.filed`; the `fraud-risk` agent's attempt to call the filing tool is refused.", { todo: true });
test("28.4-T2: Given `subject_identified = false` on the same date, then `BSA_1029_320_SAR_60_NO_SUBJECT` is due Fri Dec 18, 2026; when a subject is identified Tue Nov 24, the SAR is filed no later than Wed Nov 25 (policy: next business day) and never after Dec 18.", { todo: true });
test("28.4-T3: Given a case opened Mon Oct 19, 2026 with no triage decision by Thu Oct 29, then `SM_FRAUD_TRIAGE_SLA_10` breaches at sev 1 to the `bsa_officer`, who must record `suspicious_determined` or `not_suspicious` with a rationale.", { todo: true });
test("28.4-T4: Given property blocked Thu Nov 12, 2026, then `OFAC_501_603_BLOCKED_REPORT_10BD` is due Fri Nov 27, 2026 (Thanksgiving excluded); given a rejected transaction Fri Oct 9, 2026, then the report is due Mon Oct 26, 2026 (Columbus Day excluded); the rejected-transaction record is retained until Oct 9, 2036, and the blocked-property record for as long as the property stays blocked plus 10 years after the unblocking date (`retention_until` is set only when `ofac.report.submitted{unblocking}` is recorded).", { todo: true });
test("28.4-T5: Given `fnma.fraud.reasonable_basis` on Wed Nov 25, 2026 for a delivered loan, then `FNMA_A3_4_03_FRAUD_SELF_REPORT_30` is due Fri Dec 25, 2026, the LQC self-report is submitted by Thu Dec 24 by the `fnma_portal_operator` after partner `officer` approval, and the LQC reference is stored; a submission on Mon Dec 28 is a breach.", { todo: true });
test("28.4-T6: Given a SAR filed Wed Nov 18, 2026 and activity continuing, then a 90-day review is scheduled to Tue Feb 16, 2027 and `BSA_1029_320_SAR_CONTINUING_120` is due Thu Mar 18, 2027.", { todo: true });
test("28.4-T7: Given a denial caused by a fraud case, then the 21.6 notice contains only taxonomy reasons (\"Unable to verify income\"/\"Unable to verify employment\"/\"Unable to verify identity\") and no string from the SAR compartment; a content scan of the notice for \"SAR,\" \"suspicious,\" \"FinCEN\" or \"investigation\" returns nothing.", { todo: true });
test("28.4-T8: Given a user outside `sar_confidentiality_acl` (a production agent, a QC reviewer, or the other organization's staff without a joint filing) queries `sars`, then access is denied and logged; given a subpoena for SAR material, then the workflow produces a \"decline to produce\" response and a FinCEN notification task for the `bsa_officer`.", { todo: true });
test("28.4-T9: Given a verified \u00a7609(e) request received Mon Nov 2, 2026 with a police report, then the application and transaction records are provided without charge by Wed Dec 2, 2026 or a documented (e)(5) decline is recorded.", { todo: true });
test("28.4-T10: Given the daily OFAC list refresh fails on Thu Nov 12, 2026, then `SM_OFAC_CLEAR_BEFORE_FUNDING_GATE` stays closed for every disbursement that day until a successful screen dated within 1 day exists; the funder cannot bypass the gate.", { todo: true });
test("28.4-T11: Given the independent test for 2026 is performed by the compliance officer, then the record is rejected (`independent_of_officer = false`) and `BSA_1029_210_INDEPENDENT_TEST` remains unsatisfied.", { todo: true });
test("28.4-T12: Given a new appraiser onboarded Mon Oct 26, 2026 who appears on the FHFA SCP list, then the onboarding is blocked, `red_flag_events`/case records are created as applicable, and the A3-4-03 screening record shows the list version checked.", { todo: true });
test("28.4-T13: Given any `fraud-risk` agent decision record, then it contains investigation steps with evidence refs, `rule_set_versions`, `model_version`, `prompt_version`, `inputs_hash`, the officer review, and no `applicant_demographics` reads; 31.2 receives the monthly fraud-flag rate by channel and product.", { todo: true });
test("28.4-T14: Given the FinCEN April 10, 2026 NPRM is finalized with a compliance date, then `bsa_program` shows a risk assessment dated within 12 months and board approval, and only the version and compliance-date fields change.", { todo: true });
