/**
 * §28.1 timer overrides (process-owned; applied after every section's so they win the merge — see
 * src/domain/bankruptcy/timers-14-1.ts for the pattern). One `reg.override(code, { trigger?, satisfied | evaluator,
 * anchorField?, offset?, why })` per 28.1 registry row whose trigger/satisfied column names an event the platform
 * spells differently or a condition the column grammar drops; `why` quotes the spec. A code the servicing spec
 * (sections 1–19) owns is never overridden here — reference it. Wired by src/domain/timer-overrides.ts.
 *
 * Every application-scoped 28.1 event carries `applicationId` (ops-28-1.ts emit) and the program-level ones
 * (`schedule.tick`, `qc.sample.*`, `qc.report.*`) carry `source: "origination"`, so the rows arm only under origination
 * context (src/kernel/timers/engine.ts isOriginationContext). Referenced, not overridden: 22.3's
 * `FNMA_B3_3_1_04_VVOE_10BD` (the VVOE window the (d) check reads), 21.6's `REGB_1002_9_DECISION_30` (the compliance
 * snapshot reads its satisfaction), 28.4's fraud timers (start on 28.4's detection rules, not on the QC finding).
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_28_1(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  o("SM_QC_PREFUNDING_SELECTION_DAILY", { trigger: "`schedule.tick{cadence=daily, job=qc_prefunding_selection}`", offset: "daily", satisfied: "`qc.sample.planned`",
    why: "§28.1 timer table: recurring on 'schedule' — '06:00 partner TZ, every calendar day'; ops-28-1.ts dailySelectionTick appends `schedule.tick{cadence=daily, at=06:00, job=qc_prefunding_selection, source=origination}` at 06:00 in the partner's zone; 'daily; `calendar_days`'; satisfied by 'selection run completed (`qc.sample.planned` actuals updated)' — ops-28-1.ts recordSelectionRun re-emits `qc.sample.planned{actuals}` at the end of every run (planSample emits the month's first); breach: missed run → sev 2 to `compliance-sentinel`; catch-up run." });
  o("SM_QC_PREFUNDING_REVIEW_SLA_2BD", { trigger: "`qc.review.selected`", anchorField: "selected_at", offset: "+2 business_days_creditor", satisfied: "`qc.review.completed`",
    why: "§28.1 timer table: deadline on `qc.review.selected` (ops-28-1.ts selectLoan) anchored at `selected_at` (+2 `business_days_creditor`: selected Wed Oct 28 → due Fri Oct 30, T1); satisfied by '`review_completed_at` set (findings drafted or no defect)' — ops-28-1.ts completeReview appends `qc.review.completed{review_completed_at}` (closeReview sets it too when the review closes straight from in_review); breach: sev 2 → `qc_officer`; closing date at risk notice to 26.1 (`closing.at_risk{reason=qc}`)." });
  o("SM_QC_REVERIFICATION_RESPONSE_3BD", { trigger: "`qc.reverification.requested`", anchorField: "requested_at", offset: "+3 business_days_creditor", satisfied: "`qc.reverification.received`",
    why: "§28.1 timer table: deadline on `qc.reverification.requested` (ops-28-1.ts orderReverification; a second request is the same event with `attempt=2`) anchored at `requested_at` (+3 `business_days_creditor`); satisfied by `qc.reverification.received` (receiveReverification); breach: second request; at +5 BD the `qc_officer` decides `unable_to_complete` vs hold (reverificationFollowUp / officerDecideReverification)." });
  o("SM_QC_OFFICER_FINDING_SLA_1BD", { trigger: "`qc.review.routed_to_officer`", anchorField: "routed_at", offset: "+1 business_days_creditor", satisfied: "`qc.finding.officer_decided{decision∈{released, withdrawn}}`",
    why: "§28.1 timer table: deadline on '`status → officer_review`' — ops-28-1.ts routeToOfficer appends `qc.review.routed_to_officer{routed_at}` at the transition (Tue Nov 10 09:30 → +1 `business_days_creditor` = Thu Nov 12 because Wed Nov 11 is Veterans Day, T3); satisfied by 'officer decision (`released` or `withdrawn`)' — officerDecideFinding appends `qc.finding.officer_decided{decision}`; breach: sev 2 → partner `officer`; hold persists." });
  o("SM_QC_REBUTTAL_WINDOW_1BD", { trigger: "`qc.finding.released`", anchorField: "released_at", offset: "+1 business_days_creditor", satisfied: "`qc.finding.resolved{resolution∈{condition_reopened, data_corrected}}`",
    why: "§28.1 timer table: deadline (production side) on `qc.finding.released` (ops-28-1.ts releaseFindings) anchored at `released_at` (+1 `business_days_creditor`); satisfied by '`qc.finding.rebutted` or `qc.finding.resolved{condition_reopened|data_corrected}`' — the engine takes one pattern: production's reaction (23.3 `condition.reopened` / a DU resubmission) is recorded by recordFindingResolution as `qc.finding.resolved{resolution}`; a rebuttal (recordRebuttal `qc.finding.rebutted`) is evaluated by evaluateRebuttal into `withdrawn` or `sustained`; breach: the finding is sustained by default (rebuttalWindowExpired); hold persists." });
  o("FNMA_D1_2_01_PREFUNDING_PRIOR_TO_CLOSING_GATE", { trigger: "`qc.review.opened{kind=prefunding}`", evaluator: "23.3.prefundingQcGate", satisfied: "`qc.review.closed`",
    why: "§28.1 timer table (owned here; 23.3 references it as the CTC hold — its `ctc_checklists` item `SM_QC_PREFUNDING_HOLD` is a checklist item, not a second timer code): not_before_gate on `qc.review.opened{kind=prefunding}` (ops-28-1.ts selectLoan); 'open iff `qc_reviews.status ∈ {closed{no_defect, defect_corrected}, unable_to_complete}`' — ops-28-1.ts reviewGateStatus / assertGateOpen state it in 23.3's vocabulary and the shared evaluator 23.3.prefundingQcGate asserts it before `clear_to_close`, `consummate` (25.3/26.x) and `disburse` (26.3); satisfied by `qc.review.closed` (closeReview; `outcome`, `defects_open` on the payload); breach: block; `closing.consummated` with the gate closed → `qc.breach.closed_with_open_review` sev 1 → `qc_officer` + partner `officer` (consummatedWithOpenReview); the review continues as post-closing discretionary (28.2)." });
  o("FNMA_D1_1_03_PREFUNDING_REPORT_30", { trigger: "`qc.sample.completed{kind=prefunding}`", anchorField: "completion_date", offset: "+30 calendar_days", satisfied: "`qc.report.signed{kind=prefunding_monthly}`",
    why: "§28.1 timer table: deadline on 'last review of the month's sample closed (`sample_plan` period end + all reviews terminal)' — ops-28-1.ts sampleCompletion appends `qc.sample.completed{kind=prefunding, completion_date}` when every review of the plan is terminal; anchor '`completion_date` = max(`closed_at`) for the period' (+30 `calendar_days`: Fri Oct 30 → Sun Nov 29, rule 8); satisfied by '`qc.report.issued{prefunding_monthly}` and `qc.report.signed`' — the signature (signReport `qc.report.signed{kind=prefunding_monthly}`) is the later of the two and closes the row (draftMonthlyReport appends the `qc.report.issued` first); breach: sev 1 → partner `officer`; report issued immediately with the gap noted." });
  o("SM_QC_REPORT_SIGNOFF_SLA_3BD", { trigger: "`qc.report.issued`", anchorField: "issued_at", offset: "+3 business_days_creditor", satisfied: "`qc.report.signed`",
    why: "§28.1 timer table: deadline on `qc.report.issued` (ops-28-1.ts draftMonthlyReport / issueAnnualAuditReport) anchored at `issued_at` (+3 `business_days_creditor`); satisfied by '`signed_by_qc_officer_at`' — signReport appends `qc.report.signed`; breach: sev 2 → partner `officer`." });
  o("FNMA_D1_1_01_QC_AUDIT_ANNUAL", { trigger: "`schedule.tick{cadence=annual, job=qc_process_audit}`", offset: "annual", satisfied: "`qc.report.issued{kind=qc_audit_annual}`",
    why: "§28.1 timer table: recurring on 'schedule' — 'each Jan 15 (policy)'; ops-28-1.ts annualAuditTick appends `schedule.tick{cadence=annual, job=qc_process_audit, source=origination}` on Jan 15; 'annual; `calendar_days`'; satisfied by '`qc.report.issued{qc_audit_annual}` distributed to management' — issueAnnualAuditReport appends `qc.report.issued{kind=qc_audit_annual}` (D1-1-01 'an audit process'; frequency unstated — 28.1-Q7 default annual, results to partner management by Jan 31); breach: sev 2 → partner `officer`." });
}
