/**
 * §28.2 timer overrides (process-owned; applied after every section's so they win the merge — see
 * src/domain/bankruptcy/timers-14-1.ts for the pattern). One `reg.override(code, { trigger?, satisfied | evaluator,
 * anchorField?, offset?, why })` per 28.2 registry row whose trigger/satisfied column names an event the platform
 * spells differently or a condition the column grammar drops; `why` quotes the spec. A code the servicing spec
 * (sections 1–19) owns is never overridden here — reference it. Wired by src/domain/timer-overrides.ts.
 *
 * Every 28.2 row is an origination row (src/kernel/timers/engine.ts isOriginationContext): the events ops-28-2.ts
 * appends carry `applicationId` (loan-level reviews, cases, remedies, self-reports) or `payload.source = "origination"`
 * (cycle aggregates, the scheduler's ticks, compliance breaches). Every trigger and satisfying event named here is
 * appended by a real ops-28-2.ts code path — buildCyclePopulation / selectCycle / completeCycle / startArrearsTracking /
 * sendArrearsNotice (cycle), reviewSelected inside selectCycle / selectEpd, closeReview / confirmIneligibleAsDelivered,
 * releaseFinding / evaluateRebuttal, issueCycleReport / issueQuarterlyTargetSection / recordVendorReview,
 * postClosingScheduleTicks, openFnmaCase / confirmSubmission / resolveResolutionRequest, receiveDemand / fileAppeal /
 * ingestAppealResponse / declareImpasse / concludeImpasse / fileManagementEscalation / recordManagementEscalationDecision /
 * initiateIdr / payRemedy, submitSelfReport, confirmComplianceBreach — and 28-2.spec.test.ts drives each row through the
 * real TimerEngine from those events. `FNMA_A2_3_2_02_RELIEF_36_PAYMENTS` arms on the tracker's own opening record (29.4's `loan.purchased`
 * carries no 36th-due-date anchor) and `rep_warrant_relief.confirmed` (29.4's name, emitted here by confirmReliefFromReport) satisfies it;
 * `FNMA_A3_4_03_FRAUD_SELF_REPORT_30` is 28.4's — referenced, never overridden.
 *
 * Every Fannie Mae clock is in calendar days ("days" without qualification); a due date on a weekend/holiday is met on
 * the prior business day by policy (ops-28-2.ts policySubmitBy), never the next — the registry offsets stay verbatim.
 * `TimerRegistry.override` re-parses `anchorField` from the raw anchor column unless passed, so every row passes it.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_28_2(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // ---- the monthly cycle (D1-3-01) -------------------------------------------------------------
  o("FNMA_D1_3_01_QC_SELECT_MONTHLY", { trigger: "`schedule.tick{cadence=monthly, job=qc_post_closing_select, source=origination}`", anchorField: "select_by", offset: "0", satisfied: "`qc.cycle.selected`",
    why: "§28.2 timer table: recurring, trigger 'schedule', anchor '1st business day of each month (`business_days_creditor`)', offset 'monthly; selection to be complete by the 10th calendar day (policy)', satisfied by `qc.cycle.selected`; breach sev 2 → `qc_officer`, the 90-day clock unaffected. The scheduler's tick on the 1st creditor business day (ops-28-2.ts postClosingScheduleTicks, `job=qc_post_closing_select`) carries `select_by` = the 10th calendar day of M+1 (selectionDueOn), so the row is due on that policy date (offset 0) rather than a month after the tick; `selectCycle` emits `qc.cycle.selected{random_count, discretionary_count, select_by}` with the following month's 10th so the kernel's recurring re-arm lands on the next selection date (18.1's cycle_clock_opens_on pattern)." });
  o("FNMA_D1_3_QC_CYCLE_90", { anchorField: "production_month_end", satisfied: "`qc.cycle.completed`",
    why: "§28.2 timer table: `qc.cycle.planned` → anchor 'last calendar day of `production_month`' + 90 calendar_days, satisfied by `qc.cycle.completed` (reviews, rebuttals and the management report done); breach sev 1 → `qc_officer` + partner `officer`, arrears tracking starts. D1-3-01: 'The entire QC cycle (selection, review, rebuttal, and reporting) must be completed within 90 days from the month of the disbursement date'. `buildCyclePopulation` stamps `production_month_end` (the month's last day) on `qc.cycle.planned` — the anchor column's `production_month` is a YYYY-MM, not a date — so November 2026 is due Sun Feb 28, 2027 (rule 1); `completeCycle` refuses until the signed report is issued (the QC FAQs' final step) and every review is closed." });
  o("FNMA_D1_3_01_QC_ARREARS_NOTICE", { trigger: "`qc.cycle.in_arrears`", anchorField: "cycle_due_on", offset: "+30 calendar_days", satisfied: "`qc.arrears_notice.sent{sent_by_role=officer}`",
    why: "§28.2 timer table: trigger '`FNMA_D1_3_QC_CYCLE_90` breached', anchor `cycle_due_on`, +30 calendar_days (one 30-day cycle), satisfied by 'written notice to the Fannie Mae customer account team/QC Specialist sent by the partner `officer` (`arrears_notice_sent_at`)'; breach sev 1, notice drafted by the agent and sent by the officer immediately. The kernel's `timer.breached{code=FNMA_D1_3_QC_CYCLE_90}` is consumed by ops-28-2.ts startArrearsTracking, which appends `qc.cycle.in_arrears{cycle_due_on, arrears_notice_due_on}` on the cycle (the 90-day row's breach column: 'arrears tracking starts') — the anchor the breach event itself does not carry; `sendArrearsNotice` emits `qc.arrears_notice.sent{sent_by_role=officer, arrears_notice_sent_at}` only for the partner officer (D1-3-01: 'If the lender's QC cycle is in arrears more than one 30-day cycle, the lender must provide written notice'); T7: Feb 28 + 30 = Tue Mar 30, 2027." });
  o("SM_QC_POST_CLOSING_REVIEW_SLA_45", { trigger: "`qc.review.selected{kind∈{post_closing_random, post_closing_discretionary, epd}}`", anchorField: "selected_at", satisfied: "`qc.review.closed{review_completed_at present}`",
    why: "§28.2 timer table (internal deadline): `qc.review.selected` → `selected_at` + 45 calendar_days, satisfied by `review_completed_at`; breach sev 2 → `qc_officer` (protects the 90-day cycle). The post-closing kinds (data model `qc_reviews.kind ∈ {post_closing_random, post_closing_discretionary, epd, fnma_lqc}`) keep 28.1's prefunding selections on their own 2-BD SLA; ops-28-2.ts selectCycle / selectEpd emit `qc.review.selected{kind, selected_at}`, and closeReview / confirmIneligibleAsDelivered emit 18.x's `qc.review.closed` carrying `review_completed_at`." });
  o("SM_QC_REBUTTAL_WINDOW_10", { trigger: "`qc.finding.released{rebuttal_due_on present}`", anchorField: "released_at", satisfied: "`qc.finding.rebutted`",
    why: "§28.2 timer table (production side): `qc.finding.released` → `released_at` + 10 calendar_days, satisfied by 'rebuttal or correction recorded'; breach: finding sustained by default. ops-28-2.ts releaseFinding (severity ≤ 2 only on the qc_officer's approval) stamps `released_at`/`rebuttal_due_on`; evaluateRebuttal records the production side's rebuttal or correction as 28.1's `qc.finding.rebutted{outcome, final_severity}` (worked example 1: released Jan 8 → window to Jan 18; the cash-out loan corrected → final severity 3); sustainByDefault records `outcome=sustained_by_default` at the breach. 28.1's `qc.finding.released` (no `rebuttal_due_on`) arms its own 1-BD window, not this one." });
  // ---- reporting (D1-1-03) and the partner's re-review (D1-1-02) ------------------------------
  o("FNMA_D1_1_03_POST_CLOSING_REPORT_MONTHLY", { trigger: "`schedule.tick{cadence=monthly, job=qc_post_closing_report, source=origination}`", anchorField: "report_due_on", offset: "0", satisfied: "`qc.report.issued{kind=post_closing_monthly, signed_by_role=qc_officer}`",
    why: "§28.2 timer table: recurring, trigger 'schedule', 'each month; the cycle report is part of `qc.cycle.completed`', satisfied by `qc.report.issued{post_closing_monthly}` signed by the `qc_officer`; breach sev 1 → partner `officer`. D1-1-03: reports 'in writing and shared with management monthly'. The scheduler's monthly tick (postClosingScheduleTicks, `job=qc_post_closing_report`) carries `report_due_on` = that month's last day (offset 0); `issueCycleReport` emits `qc.report.issued{kind=post_closing_monthly, signed_by_role=qc_officer, report_due_on=<next month-end>}` only for the qc_officer, so the recurring re-arm lands on the following month." });
  o("FNMA_D1_1_03_TARGET_RATE_QUARTERLY", { trigger: "`schedule.tick{cadence=quarterly, job=qc_target_rate, source=origination}`", anchorField: "quarter_end", offset: "+30 calendar_days", satisfied: "`qc.report.issued{kind=post_closing_quarterly}`",
    why: "§28.2 timer table: recurring, trigger 'schedule', anchor 'quarter-end + 30 calendar days (policy)', satisfied by 'report section \"highest severity defect rate vs target\" issued'; breach sev 2. D1-1-03: 'data for the highest severity classification defect rate, benchmarked against its defined target rate, at least quarterly'. The quarter-end tick (postClosingScheduleTicks, `job=qc_target_rate`) carries `quarter_end`; `issueQuarterlyTargetSection` emits `qc.report.issued{kind=post_closing_quarterly, section, highest_severity_rate_pct, target_pct}` for the qc_officer with `quarter_end` = the next quarter-end for the re-arm." });
  o("FNMA_D1_1_02_VENDOR_REVIEW_10PCT_MONTHLY", { trigger: "`qc.cycle.completed`", anchorField: "vendor_review_clock_from", offset: "+15 calendar_days", satisfied: "`qc.report.issued{kind=vendor_review_monthly, performed_by=partner, coverage_met=true}`",
    why: "§28.2 timer table: recurring, trigger `qc.cycle.completed`, anchor 'cycle completion', offset 'within the same month (policy: +15 calendar_days)', satisfied by 'partner-performed re-review of ≥ 10% of the cycle's post-closing reviews with concurrence recorded (`qc_reports{vendor_review_monthly}`)'; breach sev 1 → partner `officer` (D1-1-02: 'must perform a monthly review of at least 10% of the post-closing QC sample reviewed by the vendor … performed by the lender itself and may not be contracted out'). `completeCycle` stamps `vendor_review_clock_from` = the completion date; `recordVendorReview` refuses `performed_by ≠ partner`, computes coverage against ceil(10 % of the cycle's reviews) and emits `qc.report.issued{kind=vendor_review_monthly, performed_by=partner, coverage_met}` — a short review does not satisfy; it also retires the kernel's re-arm from the satisfying event because the next cycle's own completion arms its row (T9: no re-review within 15 days → breach sev 1 and the monthly report states the gap, vendorReviewGapStatement)." });
  // ---- Loan Quality Connect (D2-1; portal-only) ------------------------------------------------
  o("FNMA_D2_1_LQC_RESPONSE_30", { trigger: "`fnma.qc.case.opened{case_type∈{file_request, data_validation, missing_documents}}`", anchorField: "notified_on", satisfied: "`fnma.qc.package.submitted{case_type∈{file_request, data_validation, missing_documents}, submitted_by_role=fnma_portal_operator, lqc_reference present}`",
    why: "§28.2 timer table: `fnma.qc.case.opened{file_request|data_validation}` → `notified_at` date + 30 calendar_days, satisfied by `fnma.qc.package.submitted` (operator-confirmed upload, LQC reference captured); breach sev 1 → partner `officer` + `fnma_portal_operator`, D2-1-02 exposure. D2-1-02: 'Lenders must send the requested documentation … within 30 days after Fannie Mae notifies the lender'. The registry cell's `{file_request|data_validation}` is the data model's `case_type` (the `|` splits the markdown row — verification report item 37), so the trigger conditions on `case_type`; `openFnmaCase` stamps `notified_on` (the LQC/e-mail notification's Eastern civil date) and a child missing-documents notice keeps its own 30-day expectation (edge cases); `confirmSubmission` emits the satisfying event only for the `fnma_portal_operator` with an LQC reference (T5: notified Wed Dec 16, 2026 → due Fri Jan 15, 2027; T12: the agent is refused)." });
  o("FNMA_D2_1_NOPD_DOC_UPLOAD_30", { trigger: "`fnma.qc.case.opened{case_type=nopd}`", anchorField: "notified_on", satisfied: "`fnma.qc.package.submitted{case_type=nopd, submitted_by_role=fnma_portal_operator}`",
    why: "§28.2 timer table: `fnma.qc.case.opened{nopd}` → `notified_at` date + 30 calendar_days (LQC job aid 'Respond to a Notice of Potential Defect': '30 calendar days to make your case to correct the defect'), satisfied by 'corrective documents uploaded and confirmed'; breach sev 1, Resolution Request expected. `case_type=nopd` is the data-model column the bare `{nopd}` selector names; the corrective documents (draftNopdResponse) are uploaded by the operator and confirmed through `confirmSubmission` on the NOPD case (worked example 2: NOPD Fri Jan 29, 2027 → due Sun Feb 28 → policy Fri Feb 26; uploaded Tue Feb 2)." });
  o("FNMA_D2_1_RESOLUTION_REQUEST_60", { trigger: "`fnma.qc.case.opened{case_type=resolution_request}`", anchorField: "notified_on", satisfied: "`fnma.qc.case.resolved{case_type=resolution_request, resolution∈{correction_accepted, alternative_remedy_agreed, appeal_1_filed}}`",
    why: "§28.2 timer table: `fnma.qc.case.opened{resolution_request}` → `notified_at` date + 60 calendar_days (the Resolution Request is the demand: A2-3.2-01 'within 60 days after receipt of the demand'; A2-3.2-03 first appeal within 60 days of receipt), satisfied by 'correction accepted, alternative remedy agreed, or first appeal filed'; breach sev 1 → partner `officer`. `resolveResolutionRequest` records which of the three closed it as `fnma.qc.case.resolved{resolution}` (an alternative remedy or an appeal only on the partner officer's decision); worked example 2: Resolution Request Mon Mar 1, 2027 → Fri Apr 30." });
  // ---- the remedies ladder (A2-3.2-01 / A2-3.2-03) ---------------------------------------------
  o("FNMA_A2_3_2_01_REMEDY_PAYMENT_60", { anchorField: "demand_received_on", satisfied: "`remedy.paid{paid_by_role=officer}`",
    why: "§28.2 timer table: `remedy.demand.received` → `demand_received_at` date + 60 calendar_days, satisfied by `remedy.paid` or `remedy.appeal.filed{appeal_1}` (suspends); breach sev 1 → partner `officer`, Lender Contract breach exposure. A2-3.2-01: 'pay Fannie Mae the funds that are due … within 60 days after receipt of the demand … unless an appeal is made'. `receiveDemand` stamps `demand_received_on`; `payRemedy` emits `remedy.paid{paid_by_role=officer}` only for the partner officer (T12: the agent is refused); the suspension is not a satisfaction — `fileAppeal{appeal_1}` retires the armed instance for that demand with the reason on record and marks `remedy_ledger.payment_timer = suspended` (T6: demand Mon May 3, 2027 → due Fri Jul 2; appeal 1 filed Thu Jun 10 suspends)." });
  o("FNMA_A2_3_2_03_APPEAL1_60", { anchorField: "demand_received_on", satisfied: "`remedy.appeal.filed{stage=appeal_1}`",
    why: "§28.2 timer table: `remedy.demand.received` → `demand_received_at` date + 60 calendar_days, satisfied by `remedy.appeal.filed{appeal_1}`; breach: window lost, payment timer governs. A2-3.2-03: 'The lender must submit an appeal in writing within 60 days of receiving a demand'. The bare `{appeal_1}` selector is the appeal record's `stage` (data model appeal ladder `appeal_1_filed → …`); `fileAppeal` emits `remedy.appeal.filed{stage=appeal_1, filed_on}` for the partner officer (T6: both clocks due Fri Jul 2, 2027)." });
  o("FNMA_A2_3_2_03_FNMA_RESPONSE_60", { anchorField: "filed_on", satisfied: "`remedy.appeal.responded`",
    why: "§28.2 timer table (Fannie Mae's expectation): `remedy.appeal.filed` → filing date + 60 calendar_days, satisfied by 'Fannie Mae response ingested'; follow-up by the operator, no breach by the partner. A2-3.2-03: 'Fannie Mae must respond in writing … within 60 days of its receipt'. `fileAppeal` stamps `filed_on`; `ingestAppealResponse` records the written response as `remedy.appeal.responded{stage, outcome, notified_on}` (worked example 2: filed Thu Jun 10 → expected by Mon Aug 9, 2027)." });
  o("FNMA_A2_3_2_03_APPEAL2_15", { trigger: "`remedy.appeal.responded{stage=appeal_1, outcome=denied}`", anchorField: "notified_on", satisfied: "`remedy.appeal.filed{stage=appeal_2, new_information=true}`",
    why: "§28.2 timer table: trigger 'appeal-1 denial received', anchor `notified_at` date, +15 calendar_days, satisfied by `remedy.appeal.filed{appeal_2}` (new information only); breach: window lost. A2-3.2-03: 'second appeal in writing within 15 days of receiving a denial of the first appeal' — the denial is `ingestAppealResponse`'s `remedy.appeal.responded{stage=appeal_1, outcome=denied, notified_on}`; `draftAppeal`/`fileAppeal` refuse an appeal-2 without a flagged new-information attachment (APPEAL2_NEW_INFORMATION_REQUIRED), so the satisfying event always carries `new_information=true` (T6: denial Mon Aug 9 → appeal 2 by Tue Aug 24, 2027)." });
  o("FNMA_A2_3_2_03_IMPASSE_15", { trigger: "`remedy.appeal.responded{stage=appeal_2, outcome=denied}`", anchorField: "notified_on", satisfied: "`remedy.impasse.declared`",
    why: "§28.2 timer table: trigger 'appeal-2 denial received', anchor `notified_at` date, +15 calendar_days, satisfied by 'impasse declared in LQC'; breach: window lost. A2-3.2-03: 'initiate the impasse process in writing within 15 days of receiving Fannie Mae's denial'. The second denial is `remedy.appeal.responded{stage=appeal_2, outcome=denied}`; `declareImpasse` (partner officer) emits `remedy.impasse.declared{declared_on, resolve_by}` (rule 9: second denial Mon Aug 16 → impasse by Tue Aug 31)." });
  o("FNMA_A2_3_2_03_IMPASSE_RESOLVE_30", { trigger: "`remedy.impasse.declared`", anchorField: "declared_on", satisfied: "`remedy.impasse.concluded{outcome∈{resolved, expired}}`",
    why: "§28.2 timer table (window): trigger 'impasse declared', anchor 'declaration date', +30 calendar_days, satisfied by 'resolution or expiry'; then the management-escalation window opens. A2-3.2-03: '30 days in which to attempt to resolve the dispute'. `declareImpasse` stamps `declared_on`; `concludeImpasse` records `remedy.impasse.concluded{outcome, concluded_on, management_escalation_by}` (rule 9: Aug 31 → Thu Sep 30)." });
  o("FNMA_A2_3_2_03_MGMT_ESCALATION_15", { trigger: "`remedy.impasse.concluded{outcome=expired}`", anchorField: "concluded_on", satisfied: "`remedy.management_escalation.filed`",
    why: "§28.2 timer table: trigger 'impasse window expired unresolved', anchor 'expiry date', +15 calendar_days, satisfied by 'escalation filed'; breach: window lost. A2-3.2-03: 'initiate the management escalation process in writing within 15 days of conclusion of the impasse process'. An impasse that expires unresolved is `remedy.impasse.concluded{outcome=expired, concluded_on}`; `fileManagementEscalation` (partner officer) emits `remedy.management_escalation.filed{filed_on, fnma_review_by}` (rule 9: Sep 30 → Fri Oct 15; Fannie Mae's officer review within 30 days)." });
  o("FNMA_A2_3_2_03_IDR_15", { trigger: "`remedy.management_escalation.decided{outcome=upheld}`", anchorField: "notified_on", satisfied: "`remedy.idr.initiated`",
    why: "§28.2 timer table: trigger 'management-escalation decision received', anchor `notified_at` date, +15 calendar_days, satisfied by 'IDR initiated'; breach: window lost, payment due. A2-3.2-03: 'the lender will have 15 days to initiate the IDR'. `recordManagementEscalationDecision` records Fannie Mae's decision as `remedy.management_escalation.decided{notified_on, outcome}` (a withdrawn demand needs no IDR); `initiateIdr` (partner officer) emits `remedy.idr.initiated{initiated_on}`." });
  // ---- self-reports (D1-1-01, A3-2-01) ---------------------------------------------------------
  o("FNMA_D1_1_01_QC_SELF_REPORT_30", { trigger: "`qc.review.closed{eligible_as_delivered=false, confirmed_by_role=qc_officer, self_report_required=true}`", anchorField: "confirmed_on", satisfied: "`qc.self_report.submitted{report_type=qc_findings, submitted_by_role=fnma_portal_operator, lqc_reference present}`",
    why: "§28.2 timer table: trigger '`qc_self_reports.confirmed_at` (officer sustains an ineligible-as-delivered finding)', anchor `confirmed_at` date, +30 calendar_days, satisfied by `qc.self_report.submitted` (operator-confirmed LQC submission); breach sev 1 → partner `officer`. D1-1-01: notify Fannie Mae within 30 days of confirming defects affecting loan eligibility 'using the self-report functionality in Loan Quality Connect'. Open question 6: the `qc_officer`'s sustain decision is the confirmation — `confirmIneligibleAsDelivered` (qc_officer only) closes the review as 18.x's `qc.review.closed{eligible_as_delivered=false, confirmed_by_role=qc_officer, confirmed_on, self_report_required}` (the state machine's `closed{eligible_as_delivered=false} → self_report_required`; a loan not sold to Fannie Mae carries `self_report_required=false` and arms nothing); `submitSelfReport` emits the satisfying event only for the `fnma_portal_operator`, after the partner officer's approval, once per loan (T4: confirmed Wed Jan 20, 2027 → due Fri Feb 19; T12: the agent is refused)." });
  o("FNMA_A3_2_01_COMPLIANCE_SELF_REPORT_60", { trigger: "`compliance.breach.confirmed{fnma_reporting_category∈{category_1, category_2}}`", anchorField: "self_report_clock_from", satisfied: "`qc.self_report.submitted{report_type=compliance_with_laws}`",
    why: "§28.2 timer table: trigger 'compliance breach confirmed (after due diligence) either above the A3-2-01 Reporting Category 1 threshold (lesser of 500 loans or 1% of prior-year deliveries, same calendar quarter) or, at any volume, where the breach could warrant a repurchase demand and has not been remedied or will not be remedied within 60 days (Reporting Category 2)', anchor 'Category 1: later of quarter-end of delivery and discovery date; Category 2: the confirmation (discovery) date', +60 calendar_days, satisfied by `qc.self_report.submitted{compliance_with_laws}` (Category 2 also by `remedy.paid` within the 60 days — the Guide waives notice when the breach 'has been remedied or will be remedied within 60 days'); breach sev 1. ops-28-2.ts complianceSelfReportClock derives the category and `self_report_clock_from`; `confirmComplianceBreach` emits `compliance.breach.confirmed` only when notice is required (a breach remedied within 60 days never arms — the remedy path is the no-notice branch, so the one satisfying pattern is the LQC 'Self Report of Compliance with Laws' submission the operator confirms through submitSelfReport)." });
  // ---- relief tracking (A2-3.2-02) --------------------------------------------------------------
  o("FNMA_A2_3_2_02_RELIEF_36_PAYMENTS", { trigger: "`rep_warrant_relief.tracking_opened{component=payment_history_36}`", anchorField: "target_36th_due_on", satisfied: "`rep_warrant_relief.confirmed{component=payment_history_36}`",
    why: "§28.2 timer table (tracking, informational): trigger `loan.purchased` (29.4; 23.3 opens the ledger row), anchor `target_36th_due_on` (36th monthly due date after acquisition), '0 calendar_days, then await Fannie Mae's relief report', satisfied by `rep_warrant_relief.confirmed` from the report; no breach — `at_risk` on the 3rd 30-day or any 60-day delinquency. A2-3.2-02: relief 'upon payment by the borrower of the first 36 monthly payments due following the loan acquisition date'; 'Fannie Mae will provide lenders with reports listing those loans that met the eligibility requirements'. 29.4's `loan.purchased` carries no first-payment date and the engine reads only flat payload fields, so the platform's reaction to it — ops-28-2.ts openReliefTracking, `rep_warrant_relief.tracking_opened{target_36th_due_on}` with the purchase event as causation (rule 10: first_payment_due + 35 months; T10: purchased Nov 19, 2026, first payment Jan 1, 2027 → Sat Dec 1, 2029) — is the arming event; `confirmReliefFromReport` emits 29.4's `rep_warrant_relief.confirmed{component, fnma_report_id}` only from a parsed Fannie Mae relief report listing the loan, never from the platform's own 36-payment count." });
  // ---- EPD monitor ---------------------------------------------------------------------------
  o("SM_QC_EPD_MONITOR_MONTHLY", { trigger: "`schedule.tick{cadence=monthly, job=qc_epd_monitor, source=origination}`", anchorField: "month_end", satisfied: "`qc.epd_selections.created`",
    why: "§28.2 timer table: recurring, trigger 'schedule', anchor 'month-end delinquency snapshot', offset 'monthly', satisfied by 'EPD selections created'; breach sev 2. The month-end tick (postClosingScheduleTicks, `job=qc_epd_monitor`) carries `month_end`; `selectEpd` consumes 30.4's `epd.flag.raised{definition=sm_qc_p1_6_60}` through its qcSelectionFromEpd (rule 3: 60+ days delinquent within the first six scheduled payments — policy, [UNVERIFIED as Fannie Mae's definition]), opens each as an `epd` review outside the monthly draw and emits `qc.epd_selections.created{month_end, count}` carrying the snapshot month-end so the recurring re-arm is the next month-end." });
}
