// 20.1 Portfolio rate monitoring and refinance-opportunity detection on the subserviced book (self-improving-mortgage trigger)
// spec/sections/20-refinance-triggers-solicitation-lead-intake-and-pricing/20-1-portfolio-rate-monitoring-and-refinance-opportunity-detectio.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("20.1-T1: Given the worked-example-1 loan and rate sheet on Thu Oct 1, 2026, when the run executes, then `candidate_terms.note_rate = 0.06125`, `pi_cents = 340262`, `rate_delta_bps = 87.5`, `pi_delta_cents = 35634`, `npv_cents = 2429278`, `lifetime_interest_delta_cents = -4496095`, status `offer_ready`, `SM_REFI_OFFER_SLA_2BD.due_at = 2026-10-05`.", { todo: true });
test("20.1-T2: Given the same loan with third-party costs $4,300, then 6.125% nets $4,200 < $4,300 and 6.250% nets $7,000 \u2265 $4,300 \u2192 `note_rate = 0.06250`, `pi_cents = 340262 + (P&I at 6.250% \u2212 P&I at 6.125%)` recomputed by formula, `rate_delta_bps = 75`.", { todo: true });
test("20.1-T3: Given a loan whose `fnma_purchase_date = 2026-08-20`, when the run executes on 2026-10-01, then status `suppressed{reason=premium_recapture_window}` and `FNMA_C1_1_01_PREMIUM_RECAPTURE_120.due_at = 2026-12-18`; a borrower request on 2026-10-05 creates `requested` with an `officer` escalation.", { todo: true });
test("20.1-T4: Given a cash-out request on 2026-10-05 for an existing loan with note date 2025-11-20, then `FNMA_B2_1_3_03_CASHOUT_NOTE_SEASONING_12M` reports earliest new note date 2026-11-20, the cash-out candidate is not offered for a 2026-11-06 consummation, and an LCOR candidate with cash back \u2264 $5,600 is offered instead.", { todo: true });
test("20.1-T5: Given the rule set references column `investor_id` (injected in a test build), then the static check fails and the run cannot start; given a `partner_programs.kind` whose product owner is SM, then `loadUniverse` refuses with `glba_use_violation`.", { todo: true });
test("20.1-T6: Given a MA property with existing consummation 2023-02-06 and candidate consummation 2026-11-06, when `pi_delta_cents = 35634` and `borrower_paid_costs = 0`, then `MA_183_28C_BORROWER_INTEREST_60M` is satisfied with factors `[payment_reduction, rate_reduction]`; given instead `pi_delta_cents = 0` and no other factor, then the gate blocks and no offer issues.", { todo: true });
test("20.1-T7: Given a loan `declined` on 2026-10-09, then proactive detection on 2026-12-15 is suppressed (`cooldown` until 2027-01-07) and a borrower request on 2026-12-15 proceeds.", { todo: true });
test("20.1-T8: Given `lifetime_interest_delta_cents > 0` for the 30-year candidate but the same-remaining-term candidate has `npv > 0`, then `offer_ready` with `present_same_term_first=true`; given both \u2264 0, then no offer.", { todo: true });
test("20.1-T9: Given LTV estimate 0.9620 on a 1-unit principal residence, then `requires_fnma_ownership_check=true`, no Loan Lookup call before `engaged`, and a Loan Lookup call after `engaged` records `fnma_owned` without altering any earlier selection.", { todo: true });
test("20.1-T10: Given two runs on the same `as_of_date`, then exactly one `refi_opportunities` row per loan exists (idempotency) and the fair-lending extract is written once.", { todo: true });
test("20.1-T11: Given the fixture $560,000 at 6.125%, then the engine's P&I is $3,402.62 and a test asserting $3,402.63 fails with the formula trace.", { todo: true });
