// 20.2 Solicitation, marketing, and consent compliance for outbound refinance offers and organic acquisition
// spec/sections/20-refinance-triggers-solicitation-lead-intake-and-pricing/20-2-solicitation-marketing-and-consent-compliance-for-outbound-r.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("20.2-T1: Given a cell number with informational `tcpa_voice` consent only, when an `ai_voice` marketing touch is queued on 2026-10-02, then `TCPA_64_1200_A2_PEWC_GATE` fails, the touch is `suppressed{no_pewc}`, and a `human_voice` click-to-dial touch is scheduled at 10:30 America/Phoenix.", { todo: true });
test("20.2-T2: Given PEWC captured 2026-10-03 08:12 MST with disclosure v2.1 (both (f)(9) elements true, seller \"[Partner]\", number as entered), when an AI-voice touch is queued 2026-10-05 09:30 MST, then the gate passes, the (b) identification plays first, and the opt-out mechanism is offered within 2 s.", { todo: true });
test("20.2-T3: Given a scrub obtained 2026-09-28, then `valid_until = 2026-10-29`; when no new scrub exists at 2026-10-30 00:00, then all `ai_voice`/`human_voice` solicitations are refused with `dnc_scrub_expired` until `dnc.scrub.completed`.", { todo: true });
test("20.2-T4: Given a number on the national registry and `ebr_basis=transaction_18m` (last payment 2026-10-01), then `TCPA_64_1200_C2_NATIONAL_DNC_GATE` passes; given the same number after a company DNC request on 2026-10-06, then the gate fails (EBR terminated) and `honor_until = 2031-10-06`.", { todo: true });
test("20.2-T5: Given an inbound \"STOP\" at 2026-10-06 13:02, then `consent.revoked{tcpa_sms}` is committed within 60 s, exactly one confirmation text is sent within 5 minutes with no marketing content, and no further SMS is sent to that number.", { todo: true });
test("20.2-T6: Given an email opt-out received 2026-10-06, then `CANSPAM_7704_A4_OPTOUT_10BD.due_at = 2026-10-20` and `marketing_suppressions{email_optout}` is recorded the same day; an email queued 2026-10-07 is suppressed.", { todo: true });
test("20.2-T7: Given a creative stating \"$3,402.62/month\" without an APR, when `runContentChecklist` executes, then `trigger_terms_present=true` and `d2_disclosures_present=false` \u2192 creative cannot be approved; adding \"6.155% APR, 360 monthly payments, fixed\" and the taxes-and-insurance statement makes it pass.", { todo: true });
test("20.2-T8: Given a template variable `investor_name` (injected), then the schema check rejects the template; given rendered text containing \"Fannie Mae\", then `no_investor_reference=false` and the touch is suppressed.", { todo: true });
test("20.2-T9: Given called-party tz America/New_York and 20:30 local, then the AI-voice touch is refused (policy window ends 20:00) and rescheduled to 09:00 next permitted day; given 07:45 local, refused (rule floor 08:00).", { todo: true });
test("20.2-T10: Given a creative last disseminated 2026-10-02 and superseded 2026-10-15, then `REGN_1014_5_RECORDS_24M.due_at = 2028-10-02` and the archive contains the rendered variants, the voice prompt version and the product list in force.", { todo: true });
test("20.2-T11: Given `marketing.prescreen_enabled=false`, when a campaign of kind `prescreen` is created, then approval is refused with `feature_disabled`; given the flag on, a written solicitation without the 12 CFR 1022.54(c) short notice fails `FCRA_615D_PRESCREEN_NOTICE_GATE`.", { todo: true });
test("20.2-T12: Given a `voice_recording_interim` consent captured 2026-10-05 14:00 without written confirmation by 2026-10-06 14:00, then status `expired` and no AI-voice marketing call is placed under it.", { todo: true });
