// 20.3 Lead intake, identity, E-SIGN/TCPA consents, and the pre-qualification interview (pre-application boundary)
// spec/sections/20-refinance-triggers-solicitation-lead-intake-and-pricing/20-3-lead-intake-identity-e-sign-tcpa-consents-and-the-pre-qualif.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("20.3-T1: Given a new chat lead on 2026-10-05 08:41 MST, when the first substantive question is asked before `deliverDisclosure`, then `SM_AI_INTERACTION_DISCLOSURE_GATE` blocks the answer and the disclosure is delivered first; `consents(kind=ai_disclosure_ack)` is written with version 1.2.", { todo: true });
test("20.3-T2: Given an unauthenticated caller claiming to be a subserviced borrower, when the AI is asked \"what's my rate?\", then `SM_LEAD_AUTH_BEFORE_DISCLOSURE_GATE` withholds the on-file rate until L2; after portal login the rate is provided.", { todo: true });
test("20.3-T3: Given no `credit_authorizations{soft_prequal}`, when `orderSoftPull` is called, then `FCRA_1681B_A3_SOFT_PULL_PURPOSE_GATE` refuses; given an authorization captured 08:47 with `end_user=partner`, then the pull proceeds and the report is linked to the authorization.", { todo: true });
test("20.3-T4: Given the fixture sequence, when income is stated at 09:31 MST on 2026-10-05 with the other five items present, then `trid_application_at = 2026-10-05T09:31-07:00`, `application.trid_received` is emitted once, 21.2's LE timer anchor is 2026-10-05 and due 2026-10-08, and 21.6's decision timer is due 2026-11-04.", { todo: true });
test("20.3-T5: Given a purchase lead with income, SSN, name, value and amount but no property address, then `trid_items.property_address.present=false`, no `application.trid_received`, a prequal letter may issue, and no `hmda_records` row is created; when an address is provided 2026-10-19 09:30 ET, then `application.trid_received` fires and the LE is due 2026-10-22.", { todo: true });
test("20.3-T6: Given the model drafts \"you would not qualify,\" then the classifier blocks it, `prequalifications.regb_decline_risk_flag` stays false, the rewritten criteria text is delivered, and no `application.received` is emitted; given the consumer then asks for a decision, then `application.received` is emitted and 21.6 is invoked.", { todo: true });
test("20.3-T7: Given `terms.presentation.requested` at 08:50 MST, then `SM_MLO_PREAPP_TERMS_REVIEW_1BH.due_at = 09:50 MST`; the personalized quote is not shown before `mlo.review.completed`; general rate-sheet ranges are still available; after approval the presentation carries the MLO name and NMLSR ID.", { todo: true });
test("20.3-T8: Given an E-SIGN \"yes\" spoken on a voice call, then no `consents(kind=esign)` row becomes `active`; given the link + PDF token completed 09:38, then `active` with scope `origination_disclosures` and 21.2 may e-deliver the LE.", { todo: true });
test("20.3-T9: Given `consumer_state=CO` on 2027-01-05, when the session starts, then the pre-use notice line is delivered before any pricing output and 21.6's `CO_SB26_189_1704_PREUSE_NOTICE_GATE` is satisfied (`co_admt.preuse_notice.delivered`); given 2026-11-06, then the line is delivered (policy) but no gate exists.", { todo: true });
test("20.3-T10: Given a lead with last activity 2026-10-05 and no application, then `SM_LEAD_INACTIVITY_EXPIRY_90.due_at = 2027-01-03`; on expiry the soft-pull report is deleted and the authorization hash retained.", { todo: true });
test("20.3-T11: Given a Utah consumer asks \"am I talking to a real person?\", then the answer is \"No \u2014 I'm [Partner]'s automated assistant\u2026\" and the disclosure is re-logged.", { todo: true });
test("20.3-T12: Given a request for \u00a71002.13 demographic information during prequalification (injected prompt), then the tool is unavailable at lead stage and the request is refused; the request exists only in 21.1.", { todo: true });
