/**
 * §20.2 timer overrides (process-owned; applied after every section's so they win the merge — see
 * src/domain/bankruptcy/timers-14-1.ts for the pattern). One `reg.override(code, { trigger?, satisfied | evaluator,
 * anchorField?, offset?, why })` per 20.2 registry row whose trigger/satisfied column names an event the platform
 * spells differently or a condition the column grammar drops; `why` quotes the spec. Wired by src/domain/timer-overrides.ts.
 *
 * Emitters live in src/domain/leads-pricing/ops-20-2.ts (the `intake` agent's rules; every payload carries
 * `origination: true` so the origination rows arm): `marketing.touch.queued{channel, line_class, campaign_kind}`
 * (queueTouch) → `marketing.touch.scheduled` (decideTouch — "send permitted") or `marketing.touch.suppressed{reason}`;
 * `dnc.scrub.completed{obtained_on, valid_until}` (completeDncScrub); `marketing.ebr.evaluated{basis, anchor_on,
 * lapses_on}` (recordEbr / planChannels / recordResponse); `marketing.suppression.requested{kind}` and
 * `.recorded{kind, honor_until}` (recordSuppression) and `.expired{kind=company_dnc}` (expireSuppression);
 * `creative.superseded{last_disseminated_on, archive_until}` (supersedeCreative) / `campaign.ended` (endCampaign) and
 * `marketing.archive.verified{complete}` (verifyMapArchive).
 * Referenced, never redefined: `TCPA_64_1200_A1_CELL_CONSENT_GATE` and `TCPA_64_1200_A10_REVOCATION_HONOR_10BD` (11.1 —
 * receiveSmsStop reuses ingestInboundSms, which emits their `consent.revoked` / `consent.revocation.honored`),
 * `ESIGN_7001C_CONSENT_GATE` (7.4), `SM_LICENSE_STATE_GATE` (31.1 — checkGates carries its record), `SM_REFI_OFFER_SLA_2BD`
 * (20.1 — satisfied by `marketing.touch.sent`, which sendTouch emits with `opportunity_id`).
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_20_2(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // Timer table row 1 / rule 3 / T1, T2, T12: the PEWC gate is condition-shaped (a consent record, not a clock); "send permitted" is the scheduled touch.
  o("TCPA_64_1200_A2_PEWC_GATE", { trigger: "`marketing.touch.queued{channel∈{ai_voice, sms}, line_class∈{cellular, unknown}}`", evaluator: "20.2.pewcGate", satisfied: "`marketing.touch.scheduled`",
    why: "§20.2 timer table: not_before_gate on `marketing.touch.queued{channel ∈ ai_voice, sms}` to a cellular/paging/charged line, offset 'requires `consents(kind ∈ tcpa_voice/tcpa_sms, purpose=marketing, written_consent=true, status=active, pewc_elements complete, seller_named=partner)` for the destination number', satisfied by 'send permitted', breach '`suppressed{reason=no_pewc}`; alternative channel' — 47 CFR 64.1200(a)(2)/(f)(9); queueTouch carries `line_class` (mobile/voip/unknown → charged-for, conservative), evaluators-20-2.ts pewcGate applies rule 3 over the party's consents (findPewc), decideTouch appends `marketing.touch.scheduled` when every gate passes or `marketing.touch.suppressed{reason=no_pewc}` (planChannels then offers the human click-to-dial alternative — T1)." });
  // Timer table row 2 / worked example 4: artificial-voice marketing to a residential landline needs the same PEWC ((a)(3)).
  o("TCPA_64_1200_A3_LANDLINE_PEWC_GATE", { trigger: "`marketing.touch.queued{channel=ai_voice, line_class=residential_landline}`", evaluator: "20.2.landlinePewcGate", satisfied: "`marketing.touch.scheduled`",
    why: "§20.2 timer table: not_before_gate on `marketing.touch.queued{channel=ai_voice}` to a residential landline, offset 'requires PEWC as above', satisfied 'permitted', breach 'suppressed; human click-to-dial offered' — 47 CFR 64.1200(a)(3): no artificial or prerecorded voice telemarketing to a residential line 'without the prior express written consent of the called party'; queueTouch sets `line_class=residential_landline` from phone_numbers.line_type=landline (11.1); the landlinePewcGate evaluator is the same rule-3 check." });
  // Timer table row 3 / worked example 3 / T3: the recurring safe-harbor clock anchors on the registry version's obtained date; the next scrub re-satisfies and re-arms it on the registry subject.
  o("TCPA_64_1200_C2_DNC_SCRUB_31", { anchorField: "obtained_on",
    why: "§20.2 timer table: recurring (safe harbor) on `dnc.scrub.completed`, anchor `registry_version_obtained_at`, offset '+31 calendar_days validity (TSR §310.4(b)(3)(iv) identical)', satisfied by 'next `dnc.scrub.completed`', breach 'all telephone solicitations blocked at expiry; sev 2' — 47 CFR 64.1200(c)(2)(i)(D) 'no more than 31 days prior to the date any call is made'; completeDncScrub appends the event on the `dnc_registry` aggregate with `obtained_on` (the version's civil date) and `valid_until = obtained_on + 31` (worked example 3: Sept 28 → Oct 29), and checkGates refuses every ai_voice/human_voice touch with `dnc_scrub_expired` once no version is in force (scrubInForce)." });
  // Timer table row 4 / T4: not on the registry, or an EBR (18 m transaction / 3 m inquiry; a company DNC terminates it), or signed written permission.
  o("TCPA_64_1200_C2_NATIONAL_DNC_GATE", { evaluator: "20.2.nationalDncGate", satisfied: "`marketing.touch.scheduled`",
    why: "§20.2 timer table: not_before_gate on `marketing.touch.queued{channel ∈ ai_voice, human_voice}`, offset 'number not on the national registry, or `ebr_basis ∈ {transaction_18m, inquiry_3m}`, or `national_dnc_written_permission=true`', satisfied 'permitted', breach 'suppressed' — 47 CFR 64.1200(c)(2), (c)(2)(ii), (f)(5), (f)(15); evaluators-20-2.ts nationalDncGate composes ebrBasis (rule 2: a company DNC sets `none`) with the written-permission flag captured on the PEWC; decideTouch appends `marketing.touch.scheduled` or `marketing.touch.suppressed{reason=national_dnc}`." });
  // Timer table row 5 / rule 2: the transaction EBR is a window the platform evaluates on the party (a servicing `payment.received` carries no origination context, so the window is recorded from the transaction date it names).
  o("TCPA_64_1200_F5_EBR_TRANSACTION_18M", { trigger: "`marketing.ebr.evaluated{basis=transaction_18m}`", anchorField: "anchor_on", evaluator: "20.2.ebrTransactionWindow",
    why: "§20.2 timer table: not_before_gate (window) on 'last `payment.received` or loan transaction with the partner', anchor 'transaction date', offset 'window 18 months (TSR: 540 days)', breach 'EBR lapses → national DNC applies' — 47 CFR 64.1200(f)(5) 'purchase or transaction with the entity within the eighteen (18) months immediately preceding the date of the telephone call'; recordEbr (planChannels) appends `marketing.ebr.evaluated{basis=transaction_18m, anchor_on=<last payment.received date>, lapses_on=anchor_on + 18 months}` on the party from the servicing payment history, and the ebrTransactionWindow evaluator is open while as_of < lapses_on and no company DNC request exists (rule 2)." });
  // Timer table row 6 / worked example 1: the inquiry EBR starts at the consumer's reply (`marketing.response.received` → recordResponse records the window; 20.3's `lead.created` follows).
  o("TCPA_64_1200_F5_EBR_INQUIRY_3M", { trigger: "`marketing.ebr.evaluated{basis=inquiry_3m}`", anchorField: "anchor_on", evaluator: "20.2.ebrInquiryWindow",
    why: "§20.2 timer table: not_before_gate (window) on '`lead.created`/`marketing.response.received` (consumer inquiry)', anchor 'inquiry date', offset 'window 3 months (TSR: 90 days)', breach 'as above' — 47 CFR 64.1200(f)(5) 'inquiry or application regarding products or services offered by the entity within the three months immediately preceding the date of the call'; recordResponse appends `marketing.response.received{inquiry=true}` and then `marketing.ebr.evaluated{basis=inquiry_3m, anchor_on=received_on, lapses_on=+3 months}` (worked example 1: Oct 5, 2026 → through Jan 5, 2027); the ebrInquiryWindow evaluator is open while as_of < lapses_on." });
  // Timer table row 7 / T4: the company-specific request is honored 5 years from the request date; the lapse after five years is the platform's own record.
  o("TCPA_64_1200_D_COMPANY_DNC_5Y", { anchorField: "requested_on", satisfied: "`marketing.suppression.expired{kind=company_dnc}`",
    why: "§20.2 timer table: not_before_gate (window) on `marketing.suppression.recorded{kind=company_dnc}`, anchor requested_at, offset '+5 years (calendar)', breach 'no telephone solicitation to the number; terminates EBR ((f)(5))' — 47 CFR 64.1200(d)(6) 'A do-not-call request must be honored for 5 years from the time the request is made'; recordSuppression appends the recorded event with `requested_on` and `honor_until = requested_on + 5 years` (T4: 2026-10-06 → 2031-10-06) and checkGates refuses voice/SMS touches with `company_dnc` while it is in force (activeSuppressions); expireSuppression appends `marketing.suppression.expired{kind=company_dnc}` once the honor period has run." });
  // Timer table row 8 / worked example 2: the consumer's request as received starts the 10-business-day ceiling; the commit (policy: immediate) closes it.
  o("TCPA_64_1200_D3_DNC_REQUEST_10BD", { trigger: "`marketing.suppression.requested{kind=company_dnc}`", anchorField: "requested_on", satisfied: "`marketing.suppression.recorded{kind=company_dnc}`",
    why: "§20.2 timer table: deadline on `marketing.suppression.requested{company_dnc}`, anchor 'receipt', offset '+10 business_days_servicer (policy target: immediate at commit)', satisfied by `marketing.suppression.recorded`, breach 'sev 1' — 47 CFR 64.1200(d)(3) 'may not exceed ten (10) business days from the receipt of such request'; recordSuppression appends `marketing.suppression.requested{kind=company_dnc, requested_on}` and, at commit, `marketing.suppression.recorded{kind=company_dnc, honor_until}` on the same suppression subject (worked example 2: received Tue Oct 6, 2026, processed 13:05)." });
  // Timer table row 9 / T6: CAN-SPAM's 10-business-day ceiling on the e-mail opt-out; recorded the same day by policy.
  o("CANSPAM_7704_A4_OPTOUT_10BD", { trigger: "`marketing.suppression.requested{kind=email_optout}`", anchorField: "requested_on", satisfied: "`marketing.suppression.recorded{kind=email_optout}`",
    why: "§20.2 timer table: deadline on `marketing.suppression.requested{email_optout}`, anchor 'receipt', offset '+10 business_days_servicer (policy: immediate)', satisfied by `marketing.suppression.recorded`, breach 'sev 1' — 15 U.S.C. 7704(a)(4)(A): unlawful to transmit 'more than 10 business days after the receipt of such request'; recordSuppression appends the requested and recorded events with `kind=email_optout` and `requested_on` (T6: received 2026-10-06; the servicer calendar closes Columbus Day, so the engine's ceiling is Wed Oct 21 — the spec's 'Oct 20' repeats the off-by-one the verification report corrected for the TCPA ceiling); every later e-mail to the address is suppressed (activeSuppressions)." });
  // Timer table row 10 / rule 5 / T9: called-party local time in the stricter tz; the policy window inside the rule; a refusal reschedules to the next window.
  o("TCPA_64_1200_C1_QUIET_HOURS_GATE", { evaluator: "20.2.quietHoursGate", satisfied: "`marketing.touch.scheduled`",
    why: "§20.2 timer table: not_before_gate (time window) on `marketing.touch.queued{channel ∈ ai_voice, human_voice, sms}`, anchor 'called party's local time (tz from area code and property/mailing address; stricter of the two)', offset 'outside 08:00–21:00 refused; policy window 09:00–20:00; state overrides', breach 'rescheduled to the next window' — 47 CFR 64.1200(c)(1) 'before the hour of 8 a.m. or after 9 p.m. (local time at the called party's location)', TSR §310.4(c); quietHoursCheck evaluates every candidate tz (all must pass), refuses Sundays and federal holidays by policy, and decideTouch appends `marketing.touch.scheduled{rescheduled=true, scheduled_for=<next permitted day 09:00>}` (T9: 20:30 ET → 09:00 next permitted day; 07:45 → rule floor)." });
  // Timer table row 11 / rule 4, 7 / T7, T8: the creative must be approved, unsuperseded, checklist-clean, on the current sheet and investor-blind at render.
  o("SM_CAMPAIGN_CREATIVE_APPROVAL_GATE", { evaluator: "20.2.creativeApprovalGate", satisfied: "`marketing.touch.scheduled`",
    why: "§20.2 timer table: not_before_gate on `marketing.touch.queued`, offset '`marketing_creatives.status=approved` and all checklist items true and `rate_sheet_id` current', breach 'suppressed' — rule 4 (Reg Z §1026.24 content), rule 7 (B2-1.3-04: `no_investor_reference` machine-checked by regex on the rendered output), rule 9; creativeApprovalGate (evaluators-20-2.ts) reads the creative's status, its runContentChecklist result (T7) and the rendered text (T8 → `marketing.touch.suppressed{reason=investor_reference}`); approveCreative is the partner `officer`'s act." });
  // Timer table row 12 / rule 8 / T10: the MAP retention deadline runs from the last dissemination; the archive job's verification is the record that the set is retained.
  o("REGN_1014_5_RECORDS_24M", { anchorField: "last_disseminated_on", satisfied: "`marketing.archive.verified{complete=true}`",
    why: "§20.2 timer table: deadline (retention) on `creative.superseded`/`campaign.ended`, anchor 'last dissemination', offset '+24 months', satisfied by 'archive retained', breach 'legal hold; sev 2 if purged early' — 12 CFR 1014.5(a) 'twenty-four months from the last date the person made or disseminated the applicable commercial communication'; supersedeCreative / endCampaign append the trigger with `last_disseminated_on` and `archive_until` (T10: 2026-10-02 → 2028-10-02), and verifyMapArchive appends `marketing.archive.verified{complete=true, retained_through}` once every rendered variant (content hash), the voice/chat prompt version and the product list in force are held through the due date." });
  // Timer table row 13 / rule 9 / T11: flag-gated; a written prescreened solicitation needs the Reg V short and long notices, frozen firm-offer criteria and the 25-month retention.
  o("FCRA_615D_PRESCREEN_NOTICE_GATE", { trigger: "`marketing.touch.queued{campaign_kind=prescreen}`", evaluator: "20.2.prescreenNoticeGate", satisfied: "`marketing.touch.scheduled`",
    why: "§20.2 timer table: not_before_gate (flag `marketing.prescreen_enabled`) on `marketing.touch.queued{campaign.kind=prescreen}`, offset 'short and long notices present (12 CFR 1022.54(c)–(d), Reg V — the identical 16 CFR 642.3 applies only to motor vehicle dealers, §642.1(b)); firm-offer criteria frozen; `REGB_1002_12` 25-month retention set', breach 'suppressed' — 15 U.S.C. 1681m(d), 12 CFR 1022.54(c)–(d), Reg B §1002.12(b)(7); queueTouch carries `campaign_kind`; prescreenNoticeGate refuses `feature_disabled` while the flag is off (approveCampaign refuses the campaign the same way — T11) and names the missing notice/criteria/retention item when it is on." });
}
