/**
 * §20.3 timer overrides (process-owned; applied after every section's so they win the merge — see
 * src/domain/bankruptcy/timers-14-1.ts for the pattern). One `reg.override(code, { trigger?, satisfied | evaluator,
 * anchorField?, offset?, why })` per 20.3 registry row whose trigger/satisfied column names an event the platform
 * spells differently or a condition the column grammar drops; `why` quotes the spec. A code the servicing spec
 * (sections 1–19) owns is never overridden here — reference it. Wired by src/domain/timer-overrides.ts.
 *
 * Emitters live in src/domain/leads-pricing/ops-20-3.ts (the `intake` agent's rules; every payload carries
 * `origination: true` so the origination rows arm): `lead.created{last_activity_on}` (createLead), `lead.interaction.started{ai}`
 * (startInteraction), `lead.disclosure.delivered` (deliverDisclosure / answerAreYouHuman), `lead.onfile_data.requested`
 * (requestOnFileData), `lead.authenticated{level}` (authenticate), `credit.softpull.requested` (orderSoftPull),
 * `credit.softpull.received` (receiveSoftPull), `lead.decline.attempted` (communicateDecline), `mlo.review.completed{outcome}`
 * (completeMloReview), `consent.granted{kind, covers_origination_disclosures}` (completeEsignDemonstration), `lead.qualified`
 * (convertToApplication). Referenced, never redefined: `REGZ_1026_19E1_LE_3BD` (20.3's registry row is the owner; 21.2 supplies
 * the satisfier `disclosure.le.issued` — timers-21-2.ts), `REGB_1002_9_DECISION_30` (21.6 supplies `decision.issued` — timers-21-6.ts),
 * `CO_SB26_189_1704_PREUSE_NOTICE_GATE` (21.6 owns; 20.3's deliverCoPreuseNotice emits its satisfier through 21.6's
 * recordPreuseNoticeDelivered). Registry order applies 20.x before 21.x, so nothing here touches those three codes.
 * 20.4's `terms.presentation.requested` (requestTermsReview) triggers SM_MLO_PREAPP_TERMS_REVIEW_1BH; 21.1's
 * `application.received` / `application.trid_received` (receiveApplication / detectSixItems) close and trigger the Reg B / E-SIGN gates.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_20_3(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // Rule 1 / T1: condition-shaped — the offset column is the disclosure duty in prose; the gate is asserted by aiDisclosureGate over {ai, disclosure_delivered} and closed by the delivery event.
  o("SM_AI_INTERACTION_DISCLOSURE_GATE", { trigger: "`lead.interaction.started{ai=true}`", evaluator: "20.3.aiDisclosureGate", satisfied: "`lead.disclosure.delivered`",
    why: "§20.3 timer table: not_before_gate, trigger '`lead.interaction.started{ai=true}`', offset 'disclosure (`NTC_SM_AI_INTERACTION_DISCLOSURE`, state variant) delivered and logged before any substantive exchange; UT: at the outset and repeated after 20 minutes or on channel change; CA/CO variants', satisfied by '`lead.disclosure.delivered`', breach 'conversation limited to \"how to reach a person\"; sev 2'. startInteraction emits the trigger with `ai`; answerQuestion asserts evaluators-20-3 aiDisclosureGate (T1: the first substantive question at 08:41 MST is blocked); deliverDisclosure emits `lead.disclosure.delivered{version=1.2, state_variant}` and the `consents(kind=ai_disclosure_ack)` row (`consent.granted{kind=ai_disclosure_ack}`)." });
  // Rule 2 / T2: the trigger column is prose ('any tool call that would reveal on-file loan/servicing data') — requestOnFileData logs that call; the gate is the assurance-level condition and closes on the L2 authentication.
  o("SM_LEAD_AUTH_BEFORE_DISCLOSURE_GATE", { trigger: "`lead.onfile_data.requested`", evaluator: "20.3.authBeforeDisclosureGate", satisfied: "`lead.authenticated{level=L2}`",
    why: "§20.3 timer table: not_before_gate, trigger 'any tool call that would reveal on-file loan/servicing data', offset '`assurance_level ≥ L2` for existing borrowers (portal login or 4.x authentication script); L1 for prospects' own entered data', satisfied '—', breach 'data withheld; sev 2 if bypassed'. requestOnFileData / getBenefit emit `lead.onfile_data.requested{what, assurance_level, withheld}` and refuse below L2 (T2: \"what's my rate?\" is withheld until the portal login); authenticate emits `lead.authenticated{level=L2, assurance_level=L2_account_authenticated}` for portal_login / auth_script_4x (L1 for OTP)." });
  // Rule 2 / 9 / T3: the satisfied cell 'pull permitted' is the vendor's report keyed by the authorization; the offset column is the permissible-purpose condition (evaluator).
  o("FCRA_1681B_A3_SOFT_PULL_PURPOSE_GATE", { trigger: "`credit.softpull.requested`", evaluator: "20.3.softPullPurposeGate", satisfied: "`credit.softpull.received`",
    why: "§20.3 timer table: not_before_gate, trigger '`credit.softpull.requested`', offset 'requires `credit_authorizations(kind=soft_prequal)` captured by the consumer, `assurance_level ≥ L1`, consumer-initiated request logged, `end_user=partner`', satisfied 'pull permitted', breach 'pull refused; sev 1 if bypassed' (15 U.S.C. 1681b(a)(3)(A); verification report item 15). orderSoftPull asserts softPullPurposeGate and emits `credit.softpull.requested{authorization_id, end_user, permissible_purpose}` only when it is open (T3: refused without the authorization; the 08:47 authorization with end_user=partner lets the pull proceed); receiveSoftPull emits `credit.softpull.received{report_id, authorization_id}` — the report linked to the authorization." });
  // Rule 3 / T6: the trigger column names the `communicateDecline` tool invocation — communicateDecline logs it as `lead.decline.attempted` and fails; the gate opens only on 21.1's `application.received`, which is also its satisfier (then 21.6 governs).
  o("REGB_1002_2F_NO_PREQUAL_DECLINE_GATE", { trigger: "`lead.decline.attempted`", evaluator: "20.3.noPrequalDeclineGate", satisfied: "`application.received`",
    why: "§20.3 timer table: not_before_gate, trigger '`communicateDecline` tool invocation', offset 'requires `application.received` for the lead (then 21.6 governs)', satisfied '—', breach 'tool refused; output rewritten as criteria explanation; if the consumer requests a decision → conversion' (comment 2(f)-3: whether an inquiry becomes an application 'depends on how the creditor responds'; verification report item 16). communicateDecline emits `lead.decline.attempted{application_received}` and throws; screenUtterance rewrites a blocked draft as the criteria statement (worked example 3: 97% of $600,000 = $582,000) with `regb_decline_risk_flag=false`; requestDecision → convertToApplication → 21.1's receiveApplication emits `application.received{application_date}` (the satisfier) and 21.6's REGB_1002_9_DECISION_30 arms (Wed Oct 7 → Fri Nov 6)." });
  // Rule 7 / T7: '+1 business hour' is prose to the offset grammar — the engine clock is +1 hour from `requested_at` (08:50 → 09:50 MST); mloReviewDueAt carries the 08:00–20:00 MLO-local window on the payload for requests outside it. 20.4's requestTermsReview emits the trigger; 20.4's row references this code (its breach cell reads '20.3').
  o("SM_MLO_PREAPP_TERMS_REVIEW_1BH", { trigger: "`terms.presentation.requested`", anchorField: "requested_at", offset: "+1 hours", satisfied: "`mlo.review.completed{outcome∈{approved, returned}}`",
    why: "§20.3 timer table: deadline (escalation SLA), trigger '`terms.presentation.requested`', anchor `requested_at`, offset '+1 business hour (`business_days_servicer`, 08:00–20:00 local of the MLO)', satisfied by '`mlo.review.completed`', breach 'sev 3; consumer told a licensed loan officer will follow up; general rate-sheet info still available' (SAFE Act / Reg H App. A: presenting particular loan terms is the mlo_of_record's act; open question 3 default `origination.ai_mlo_intake=assisted`, 1-business-hour SLA). ops-20-4 requestTermsReview appends `terms.presentation.requested{quote_id, requested_at, mlo_of_record_id, origination=true}` on the pricing quote (T7: 08:50 MST → due 09:50 MST); completeMloReview (the mlo_of_record's act) appends `mlo.review.completed{outcome, quote_id, mlo_name, nmlsr_id}` on the same quote; presentTerms names the MLO ('reviewed by J. Rivera, NMLSR ID 123456') and 20.4's presentQuote refuses without the approval." });
  // Rule 8 / T8: policy gate over 7.4's mechanism — condition-shaped (every applicant's active origination_disclosures consent) and closed by the baseline `consent.granted{kind=esign}` the demonstration test emits with the covering scope.
  o("SM_ESIGN_BEFORE_LE_GATE", { trigger: "`application.trid_received`", evaluator: "20.3.esignBeforeLeGate", satisfied: "`consent.granted{kind=esign, covers_origination_disclosures=true}`",
    why: "§20.3 timer table: not_before_gate (policy; the legal gate is 7.4's `ESIGN_7001C_CONSENT_GATE`), trigger '`application.trid_received`', offset '`consents(kind=esign, scope ∋ origination_disclosures, status=active)` for every applicant before 21.2 chooses electronic delivery', satisfied '—', breach '21.2 mails the LE (mailbox rule; no breach)'. 21.1's detectSixItems emits the trigger; esignBeforeLeGate is asserted over the lead's consents; captureEsignConsent refuses a spoken 'yes' (7001(c)(6)) and completeEsignDemonstration (link + PDF token, T8: 09:38) appends 7.4's `consent.esign.active` and the baseline `consent.granted{kind=esign, scope, status=active, covers_origination_disclosures=true}` — the satisfier." });
  // Rule 9 / T10: `lead.created` carries the lead-local civil date of the last activity (the anchor column names `last_activity_at`; an instant would anchor on its Eastern date); the 'conversion' satisfier is the hand-off event `lead.qualified`.
  o("SM_LEAD_INACTIVITY_EXPIRY_90", { trigger: "`lead.created`", anchorField: "last_activity_on", offset: "+90 calendar_days", satisfied: "`lead.qualified`",
    why: "§20.3 timer table: deadline, trigger '`lead.created` / each consumer activity', anchor `last_activity_at`, offset '+90 calendar_days', satisfied by 'conversion', breach 'lead `expired`; soft-pull data purged to `regb_25m` only if an application existed, else deleted (rule 9)' (open question 6 default: 90-day inactivity expiry; consents and authorizations retained per 7.4). createLead emits `lead.created{last_activity_at, last_activity_on, expires_on}` (T10: 2026-10-05 → 2027-01-03); every consumer activity re-anchors `expires_on` on the lead (touched); convertToApplication emits `lead.qualified{application_id}` — the conversion; expireLead deletes the soft-pull report and retains the authorization hash." });
}
