/**
 * §20.1 timer overrides (process-owned; applied after every section's so they win the merge — see
 * src/domain/bankruptcy/timers-14-1.ts for the pattern). One `reg.override(code, { trigger?, satisfied | evaluator,
 * anchorField?, offset?, why })` per 20.1 registry row whose trigger/satisfied column names an event the platform
 * spells differently or a condition the column grammar drops; `why` quotes the spec. Wired by src/domain/timer-overrides.ts.
 *
 * Emitters live in src/domain/leads-pricing/ops-20-1.ts (the `intake` agent's rules; every payload carries
 * `origination: true` so the origination rows arm): `refi.opportunity.detected{transaction_type, property_state,
 * borrower_interest_rule_applies}` (evaluateLoan / runTrigger), `refi.opportunity.suppressed{reason}`,
 * `refi.borrower_interest.determined{pass, factors}` (evaluateLoan), `refi.opportunity.offer_ready{detected_at}`
 * (markOfferReady), `refi.opportunity.offered{offered_at}` (recordOffered, on 20.2's `marketing.touch.sent{opportunity_id}`),
 * `refi.opportunity.engaged{lead_id}` (engageOpportunity, on 20.3's `lead.created{opportunity_id}`),
 * `refi.opportunity.declined{declined_at}` (declineOpportunity), `refi.trigger.run_completed` (runTrigger),
 * `premium_recapture.assessed{window_closed_on}` (assessPremiumRecapture — the event 27.2 also emits when it releases
 * `recapture_exposure_cents`). Referenced, never redefined: `TCPA_64_1200_A1_CELL_CONSENT_GATE`,
 * `TCPA_64_1200_A10_REVOCATION_HONOR_10BD` (11.1), `ESIGN_7001C_CONSENT_GATE` (7.4); `rate_sheet.published` is 20.4's.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_20_1(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // Timer table row 1: the daily run is a recurring clock re-armed by each publish; one run per partner program per day.
  o("SM_REFI_TRIGGER_DAILY", { anchorField: "published_on", offset: "+1 calendar_days, 06:30 ET", subject: "global",
    why: "§20.1 timer table: recurring on '`rate_sheet.published` (first of day)', anchor '06:30 America/New_York', offset '1 calendar_days', satisfied by `refi.trigger.run_completed`, breach 'sev 3 → `compliance-sentinel` daily report' — 20.4's publishRateSheet appends `rate_sheet.published{published_on, origination=true}` (06:35 ET daily; intra-day on a ≥ 12.5 bps move → ad-hoc run, edge cases); ops-20-1.ts runTrigger appends `refi.trigger.run_completed` on the sheet aggregate (inputs: 'Schedule: `SM_REFI_TRIGGER_DAILY` at 06:30 ET after the rate-sheet snapshot `rate_sheet.published` (20.4) — one run per partner program per day'). '(first of day)' and 'one run per … per day' make it the DAY's clock, not a sheet's: it is armed on the global subject (subject: \"global\") by the first publish of a day — a later publish the same day finds it armed and leaves it — satisfied by that day's `refi.trigger.run_completed` whichever sheet the run priced with, and re-armed for the next day; src/runtime/refi-daily.ts publishes the day's sheet and runs the trigger at/after 06:30 ET before the sweep's breach pass." });
  // Timer table row 2 / T1: two servicer business days from detection to the first touch (Thu Oct 1 → Mon Oct 5, 2026).
  o("SM_REFI_OFFER_SLA_2BD", { anchorField: "detected_at",
    why: "§20.1 timer table: deadline (policy) on `refi.opportunity.offer_ready`, anchor detected_at, '+2 business_days_servicer', satisfied by '`marketing.touch.sent` (20.2) or `refi.opportunity.suppressed`', breach 'sev 3 → ops' — markOfferReady appends `refi.opportunity.offer_ready{detected_at}` (worked example 1: offer_ready 06:41 ET Oct 1; 'due Mon Oct 5 (Fri Oct 2 is BD1, Mon Oct 5 BD2)'); 20.2's `marketing.touch.sent{opportunity_id}` confirms the first touch and recordOffered consumes it to write `refi.opportunity.offered{offered_at}` (state machine: offer_ready → offered)." });
  // Timer table row 3: 30 calendar days from the first touch; a linked lead (20.3) closes it, otherwise `expired` (re-detection allowed next run).
  o("SM_REFI_OPPORTUNITY_EXPIRY_30", { anchorField: "offered_at", satisfied: "`lead.created{opportunity_id present}`",
    why: "§20.1 timer table: deadline on `refi.opportunity.offered`, anchor offered_at, '+30 calendar_days', satisfied by '`lead.created` linked', breach 'status `expired` (re-detection allowed next run)' — recordOffered appends `refi.opportunity.offered{offered_at}` ('written when 20.2's `marketing.touch.sent{opportunity_id}` confirms the first touch; anchors `SM_REFI_OPPORTUNITY_EXPIRY_30`'); 'linked' is the lead carrying the opportunity id: 20.3's `lead.created{opportunity_id}` (engageOpportunity consumes it → `refi.opportunity.engaged{lead_id}`); expireOpportunity applies the breach action." });
  // Timer table row 4 / T7: a not-before gate with no satisfying event ('gate opens') — condition-shaped over declined_on + 90 days.
  o("SM_REFI_RESOLICIT_COOLDOWN_90", { anchorField: "declined_on", evaluator: "20.1.resolicitCooldownGate",
    why: "§20.1 timer table: not_before_gate (policy) on `refi.opportunity.declined`, anchor declined_at, '+90 calendar_days', satisfied 'gate opens', breach 'proactive solicitation refused; borrower-request path unaffected' — declineOpportunity appends `refi.opportunity.declined{declined_at, declined_on, cooldown_until}` (T7: declined Oct 9, 2026 → cooldown until Jan 7, 2027; detection Dec 15 suppressed `cooldown`, a borrower request Dec 15 proceeds); evaluators-20-1.ts resolicitCooldownGate opens once as_of ≥ declined_on + 90 (loadUniverse applies it on the proactive path only, rule 9)." });
  // Timer table row 5 / worked example 4 / T3: the Fannie Mae premium-recapture window from 29.4's purchase event; 27.2 references the code and emits the closing event from the gain-on-sale record.
  o("FNMA_C1_1_01_PREMIUM_RECAPTURE_120", { trigger: "`loan.purchased`", anchorField: "purchase_date", offset: "+120 calendar_days", satisfied: "`premium_recapture.assessed`",
    why: "§20.1 timer table: not_before_gate (policy, Fannie Mae economics) on '`loan.purchased` (29.4)', anchor `fnma_purchase_date`, '+120 calendar_days', satisfied 'gate opens', breach 'proactive solicitation suppressed (`reason=premium_recapture_window`); borrower-request path allowed with `officer` acknowledgment of the recapture cost' — C1-1-01: recapture 'with respect to any loan that pays off within 120 days from the whole loan purchase date or the MBS issue date'; 29.4's DeliveryService appends `loan.purchased{purchase_date, acquisition_date, fnma_loan_number, fnma_purchase_date}` (purchase_date = the whole-loan purchase / MBS issue date the spec calls fnma_purchase_date; verification report item 1); the gate opens at purchase_date + 120 (T3: Aug 20, 2026 → due Dec 18, 2026) and the opening is recorded as `premium_recapture.assessed{window_closed_on}` — 27.2 emits it when it releases `recapture_exposure_cents` from the gain-on-sale record, ops-20-1.ts assessPremiumRecapture appends the same platform record when a loan's proactive suppression lifts; premiumRecaptureGate suppresses inside the window (loadUniverse, proactive path) and requestOpportunity opens the `officer` escalation with the modelled recapture on the request path." });
  // Timer table row 6 / worked example 2 / T4: note-to-note seasoning for a cash-out — condition-shaped (the earliest eligible new note date), armed by the cash-out request's detection.
  o("FNMA_B2_1_3_03_CASHOUT_NOTE_SEASONING_12M", { anchorField: "note_date", evaluator: "20.1.cashoutNoteSeasoningGate",
    why: "§20.1 timer table: not_before_gate on `refi.opportunity.detected{transaction_type=cash_out}`, anchor 'existing first-mortgage `note_date`', '+12 months (calendar; new note date ≥ anchor + 12 months; does not apply to subordinate liens being paid off through the transaction or to a co-owner buyout pursuant to a legal agreement — B2-1.3-03)', satisfied 'gate opens on the earliest eligible new note date', breach 'cash-out candidate replaced by LCOR or deferred; referenced by 23.2/25.1' — B2-1.3-03: the existing first mortgage 'must be at least 12 months old … as measured by the note date of the existing loan to the note date of the new loan'; 'This requirement does not apply to any existing subordinate liens being paid off through the transaction, or when buying out a co-owner pursuant to a legal agreement' (the two exceptions open the gate; only the first mortgage's note date is ever the anchor); evaluateLoan appends `refi.opportunity.detected{transaction_type, note_date}` and cashoutNoteSeasoningGate (evaluators-20-1.ts) reports the earliest new note date (worked example 2: Nov 20, 2025 → Fri Nov 20, 2026; a Nov 6 consummation is 351 days → closed, LCOR substituted; rescission under §1026.2(a)(6) counts Sat Nov 21, Mon Nov 23, Tue Nov 24 → disbursement Wed Nov 25 earliest)." });
  // Timer table row 6a (B2-1.3-04, added by the 2026-09 verification amendments) / T4: the 30-day cash-out-to-LCOR rule — condition-shaped over the existing cash-out's note date and the application date; the column grammar drops 'where the existing loan is a cash-out refinance', so the trigger names the detection's `loan_purpose`.
  o("FNMA_B2_1_3_04_CASHOUT_TO_LCOR_30D", { trigger: "`refi.opportunity.detected{transaction_type=limited_cash_out, loan_purpose=cash_out}`", anchorField: "note_date", evaluator: "20.1.cashoutToLcorGate",
    why: "§20.1 timer table: not_before_gate on '`refi.opportunity.detected{transaction_type=limited_cash_out}` where the existing loan is a cash-out refinance', anchor 'existing cash-out first-mortgage `note_date`', '+31 calendar days measured to the new application date (an application dated 30 days or less after the cash-out note date is not eligible as LCOR — B2-1.3-04; the due date is the first eligible application date)', satisfied 'gate opens on day 31, the first eligible application date', breach 'LCOR candidate re-priced/treated as cash-out or deferred' — Selling Guide B2-1.3-04 (p.203): 'A transaction is not eligible as a limited cash-out refinance if the borrower completed a cash-out refinance transaction with a note date 30 days or less prior to the application date of a new refinance secured by the same property'; evaluateLoan appends `refi.opportunity.detected{transaction_type, loan_purpose, note_date}` (loan_purpose = the existing loan's transaction type from `loan_terms`, so the row arms only for an LCOR candidate on an existing cash-out); cashoutToLcorGate (evaluators-20-1.ts) opens once the application date (the run / request date is the earliest one) ≥ note_date + 31 — day 30 is still ineligible; buildCandidate records `eligibility_prescreen.seasoning_ok=false` with the reason while closed and evaluateLoan defers the LCOR (`suppressed{reason=cashout_to_lcor_30d, opens_on}`), never re-labelling it a cash-out without a borrower's cash-out request (rule 2)." });
  // Timer table row 7: the title-seasoning companion row (same trigger as the 12-month row) — armed by the same cash-out detection, anchored on the title date.
  o("FNMA_B2_1_3_03_TITLE_SEASONING_6M", { trigger: "`refi.opportunity.detected{transaction_type=cash_out}`", anchorField: "title_date", evaluator: "20.1.titleSeasoningGate",
    why: "§20.1 timer table: not_before_gate, trigger '`refi.opportunity.detected{transaction_type=cash_out}` (same as the 12-month row)', anchor 'date at least one borrower took title', '+6 months (calendar; measured to the new loan's disbursement date)', satisfied 'gate opens', breach 'as above; inheritance/legal-award/delayed-financing exceptions recorded in `eligibility_prescreen`' — B2-1.3-03: 'At least one borrower must have been on title for at least six months prior to the disbursement date of the new loan'; evaluateLoan's detection carries `title_date`; titleSeasoningGate (evaluators-20-1.ts) opens at title_date + 6 months measured to the disbursement date (worked example 2: title Nov 2025 → six months elapsed Wed May 20, 2026)." });
  // Timer table row 8 / worked example 3 / T6: the Massachusetts borrower's-interest window — jurisdiction-conditioned trigger, condition-shaped offset, satisfied by the recorded determination.
  o("MA_183_28C_BORROWER_INTEREST_60M", { trigger: "`refi.opportunity.detected{property_state=MA, borrower_interest_rule_applies=true}`", anchorField: "consummation_date", evaluator: "20.1.borrowerInterestGate", satisfied: "`refi.borrower_interest.determined{pass=true}`",
    why: "§20.1 timer table: not_before_gate (jurisdiction MA) on '`refi.opportunity.detected` where property state = MA and existing loan consummated < 60 months before the candidate consummation date', anchor 'existing loan consummation date', offset 'window 60 months', satisfied by '`refi.borrower_interest.determined{pass=true}` recorded with factors', breach 'offer refused; `licensed_specialist`/partner counsel escalation if the borrower insists' — M.G.L. c.183 §28C: no home loan that pays off one 'consummated within the prior 60 months … unless the refinancing is in the borrower's interest'; evaluateLoan appends the detection with `property_state` and `borrower_interest_rule_applies` (jurisdiction_rules.refi_borrower_interest_rule set and < 60 months) and `refi.borrower_interest.determined{pass, factors}` (T6: Feb 6, 2023 → Nov 6, 2026 = 45 months; pi_delta $356.34 with $0 costs and 87.5 bps → factors [payment_reduction, rate_reduction]; pi_delta 0 and no other factor → blocked, no offer)." });
  // Timer table row 9: the rolling 12-month offer cap — no clock, a count over the offer history.
  o("SM_REFI_OFFER_FREQUENCY_CAP", { anchorField: "offered_at", evaluator: "20.1.offerFrequencyCapGate",
    why: "§20.1 timer table: not_before_gate (policy) on `refi.opportunity.offered`, anchor offered_at, offset 'max `max_offers_per_loan_per_12m` per rolling 12 months', satisfied '—', breach 'suppressed (`reason=frequency_cap`)' — recordOffered appends `refi.opportunity.offered{offered_at}`; offerFrequencyCapGate (evaluators-20-1.ts) counts offers in the trailing 12 months against `partner_programs.max_offers_per_loan_per_12m` (default 2) and loadUniverse suppresses `frequency_cap` on the proactive path (rule 9)." });
}
