// 33.3 Refinance readiness: what a refinance needs, what is on file, what is asked for
// spec/sections/33-partner-book/33-3-refinance-readiness-what-is-on-file-and-what-is-asked-for.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("33.3-T1: Given loan 1 a `candidate` on the day's review and no application, when the sweep passes at 07:15 ET, then one `readiness_checks` row exists for the loan with `ready = false`, `contact`, `account` (after the homeowner's first sign-in) and `value` present, `identity`, `ssn`, `credit`, `income`, `assets`, `esign` and `credit_authorization` missing, no vendor order, no card and no consumer report, `partner_book.readiness.checked` logged and `SM_PARTNER_BOOK_READINESS_DAILY` satisfied and re-armed.", { todo: true });
test("33.3-T2: Given the homeowner of loan 1 taps Yes on the OfferCard, then `refi.open` creates one application with `channel = refi_trigger`, `prior_loan_id` = the loan, the party linked on `application_borrowers`, the property with the facts' value, 20.3's conversion, `refi.opportunity.converted` and `partner_book.refinance.opened` logged, the identity, payroll and assets connector cards and the six-item cards on the rail, and a second Yes creates nothing more.", { todo: true });
test("33.3-T3: Given the open refinance application, when the homeowner completes the FAKE identity scan, types the SSN, connects Truv and Plaid on the FAKE and confirms the six items, then the readiness row is recomputed on each event, the missing list shrinks in order, `ready = true` once credit, income, assets, identity, ssn, esign and the hard-pull authorization are present, and 32.18's DU moment has run (`du.findings.received` on the application).", { todo: true });
test("33.3-T4: Given an identity verified on an earlier application with `valid_until` before the projected note date, then `identity` reads `stale` and the scan card is asked again; given a standing payroll connection, then `income` is refreshed by 22.3's order and no payroll card is asked.", { todo: true });
test("33.3-T5: Given the homeowner asks what is still needed, then the turn's situation carries `readiness{ready, missing}` and the reply names only the missing items in the copy library's words and points at the current card; given `ready = true`, then the reply says underwriting has what it needs and points at the checklist.", { todo: true });
test("33.3-T6: Given a loan not a candidate, then no readiness row is written for it; given a funded refinance, then no further rows are written for that loan and the monitored loan reads `paid_off`.", { todo: true });
