// 25.1 Compliance testing engine (APR/finance charge, TRID tolerances, QM/ATR, HPML, HOEPA, state high-cost, fee reasonableness, RESPA §8, LO compensation and steering, licensing/NMLSR, E-SIGN, fair-lending pricing exceptions, TCPA) and the compliance gates
// spec/sections/25-compliance-testing-the-closing-disclosure-rescission-and-clo/25-1-compliance-testing-engine-apr-finance-charge-trid-tolerances.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("25.1-T1: Given the fixture (loan $560,000.00, 6.125%, 360, disbursement Thu Nov 12, 2026, first payment Fri Jan 1, 2027, PFC $3,849.95 incl. prepaid interest $1,785.43 per 26.3's `365_rounded_per_diem` convention), when `computeApr(method=appendix_j_exact)` runs, then `odd_days = 19`, `odd_fraction = 0.6333333333`, `amount_financed_cents = 55615005`, `finance_charge_cents = 66879315`, `apr = 6.159363`, `apr_disclosed = 6.159`, `tip_pct = 119.059`, and P&I in the stream is `340262` cents.", { todo: true });
test("25.1-T2: Given the same inputs with `method=appendix_j_disregard_17c4`, then `apr_disclosed = 6.190` and the two methods differ by less than 0.125, and the engine records `first_period_longer_by_days = 19 \u2264 32`.", { todo: true });
test("25.1-T3: Given PFC = $0 and `odd_days = 0`, when `computeApr` runs, then `apr = 6.125000` (equals the note rate) \u2014 the Appendix J equivalence check.", { todo: true });
test("25.1-T4: Given a delivered CD with APR 6.159 and a consummation-day recomputation of 6.290, when `APR_1026_22_ACCURACY` runs, then `result = fail`, `apr_variance = 0.131`, `tolerance_applied = eighth`, and `compliance.gate.blocked{gate=consummation}` is emitted with the cure plan \"corrected CD + new 3-business-day waiting period (25.2)\".", { todo: true });
test("25.1-T5: Given a delivered CD with finance charge $668,793.15 / APR 6.159 and an actual finance charge of $668,853.15 (understated by $60.00) with the APR resulting from the disclosed finance charge, then `FC_1026_38O2_ACCURACY = pass` and `APR_1026_22_ACCURACY = pass` with `accuracy_basis = a4`.", { todo: true });
test("25.1-T6: Given a 30-year fixed with an irregular first period only, then `tolerance_applied = eighth`; given a construction-to-permanent style multiple-advance stream (out of scope but used as a negative test), then `tolerance_applied = quarter`.", { todo: true });
test("25.1-T7: Given the partner's Arizona license record in `license_checks` with `status = expired` on Mon Oct 5, 2026, when `assertGateOpen(SM_O61_COMPLIANCE_PASS_LE_GATE)` runs, then the gate is blocked, `issueLE` is refused, and an `escalation` to `officer` opens with `SM_O61_BLOCKING_FAILURE_REVIEW_1BD` due Tue Oct 6, 2026 (`business_days_creditor`).", { todo: true });
test("25.1-T8: Given a lock request on Wed Oct 7, 2026 with no `loan_options_presented` record, then `STEERING_1026_36E_OPTIONS = fail` and `lock` is refused; given the record with the three options and the consumer's choice, then the test passes.", { todo: true });
test("25.1-T9: Given a locked price 0.125 better than the rate sheet with no `pricing_exception_reviews` row, then `FAIR_LENDING_PRICING_EXCEPTION = fail`; given a row with `reason_code = tolerance_cure` and `discretionary = false`, then it passes; an attempt to write `discretionary = true` is rejected by the schema.", { todo: true });
test("25.1-T10: Given the property state NY with loan $560,000 (\u2264 conforming limit) and points and fees of 5.2% of the total loan amount, then `STATE_HIGH_COST_NY = fail` (points-and-fees trigger \"five percent\") even though `HOEPA_1026_32 = false`, and the CD gate is blocked.", { todo: true });
test("25.1-T11: Given a title agent that is an affiliate of the partner and no `disclosures{kind=afba}` row, then `RESPA_8_AFBA_DISCLOSURE = fail` at the CD gate; given the AfBA delivered at application (Mon Oct 5, 2026), then it passes and the fee's tolerance class in `fee_items` is `zero`.", { todo: true });
test("25.1-T12: Given an E-SIGN consent withdrawn on Sun Nov 1, 2026 and an `issueCD` request for e-delivery on Mon Nov 2, then `ESIGN_7001C_CONSENT = fail`, the gate blocks e-delivery, and the `disclosure` agent is instructed to deliver on paper with the mailbox rule.", { todo: true });
test("25.1-T13: Given the APOR table for the week of Wed Oct 7, 2026 missing, when the CD gate runs, then `QM_1026_43 = error`, the gate blocks, and no waiver can be attached (`waivable = false`).", { todo: true });
test("25.1-T14: Given a `compliance_waivers` request on `APR_1026_22_ACCURACY`, then the request is rejected (legal test); given one on `FEE_REASONABLENESS` (warning) approved by `officer`, then the gate re-derives to open.", { todo: true });
