// 25.2 Closing Disclosure: preparation, delivery and receipt evidence, the three-business-day waiting period, redisclosure, post-consummation corrections, the seller's CD, and UCD generation/submission
// spec/sections/25-compliance-testing-the-closing-disclosure-rescission-and-clo/25-2-closing-disclosure-preparation-delivery-and-receipt-evidence.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("25.2-T1: Given CD v1 e-delivered Mon Nov 2, 2026 and both borrowers' e-sign acknowledgements the same day, when `computeEarliestConsummation` runs, then `earliest_consummation_date = 2026-11-05` and `consummate` on Fri Nov 6 passes `REGZ_1026_19F1_CD_3SBD_GATE`.", { todo: true });
test("25.2-T2: Given CD v1 placed in the mail Mon Nov 2 with no acknowledgement, then `presumed_receipt_date = 2026-11-05`, `earliest_consummation_date = 2026-11-09`, and `consummate` on Fri Nov 6 is refused.", { todo: true });
test("25.2-T3: Given receipt Mon Nov 9, 2026, then `earliest_consummation_date = 2026-11-13` (Veterans Day excluded); given receipt Tue Nov 10, then `2026-11-14` (Saturday counts).", { todo: true });
test("25.2-T4: Given the purchase fixture closing Wed Nov 18, 2026 and a mailed CD, when the agent schedules delivery, then the mailing date is no later than Tue Nov 10 and `SM_O62_CD_TARGET_4SBD` targets e-delivery by Fri Nov 13.", { todo: true });
test("25.2-T5: Given CD v1 APR 6.159 and a Wed Nov 4 rate change producing actual APR 5.979, when `evaluateRedisclosure` runs, then `new_wait = true` with trigger `(f)(2)(ii)(A)`, `NTC_REGZ_1026_38_CD_CORRECTED` is delivered, and after same-day e-sign `earliest_consummation_date = 2026-11-07`.", { todo: true });
test("25.2-T6: Given a recording-fee increase of $12 on Thu Nov 5 with no APR or product change, then `new_wait = false`, `cd_reason = pre_consummation_no_wait`, and the corrected CD is delivered for receipt at or before the Fri Nov 6 consummation; `runToleranceTest` is invoked.", { todo: true });
test("25.2-T7: Given consummation Fri Nov 6 and recording-fee information received Mon Nov 16, then `REGZ_1026_19F2_CORRECTED_CD_30` is due Wed Dec 16, 2026 and is satisfied by a corrected CD mailed Tue Nov 17; given a clerical name error, `REGZ_1026_19F2_CLERICAL_CD_60` is due Tue Jan 5, 2027.", { todo: true });
test("25.2-T8: Given a purchase closing Wed Nov 18 and no seller CD copy received by end of day Nov 18, then `REGZ_1026_19F4_SELLER_CD_GATE` breaches, an escalation to `settlement_agent` opens, and the delivery package is marked incomplete.", { todo: true });
test("25.2-T9: Given a consumer waiver typed into a pre-filled template, then `cd_waivers` creation is rejected (\"printed forms prohibited\"); given a consumer-authored dated signed statement accepted by `officer` on Thu Nov 5, then `earliest_consummation_date = 2026-11-05` (not earlier than receipt).", { todo: true });
test("25.2-T10: Given the final CD v2 and a UCD v2.0 submission returning two critical-edit failures, then `FNMA_UCD_ACCEPTED_GATE` stays closed and `submitDelivery` is refused; after regeneration with `critical_edit_failures = 0`, the gate opens and `deliveries.ucd_casefile_id` is populated.", { todo: true });
test("25.2-T11: Given a corrected CD delivered Tue Nov 17 before Loan Delivery on Mon Nov 16 is moved to Wed Nov 18, then `SM_O62_UCD_RESUBMIT_ON_CORRECTION` requires a new accepted UCD by Thu Nov 19 (2 `business_days_fannie_et`) with `embedded_cd_disclosure_id` = v3 and `is_final = true`.", { todo: true });
test("25.2-T12: Given `cd_consistency_checks` with `CD_NOTE_PI` mismatch (CD $3,402.63 vs note $3,402.62), then 26.1's `generateClosingDocuments` is blocked until the CD is corrected.", { todo: true });
test("25.2-T13: Given three required recipients (two borrowers and a non-borrower spouse on title, refinance), when only two have receipts, then the CD version stays `delivered` (not `received`) and the gate remains closed.", { todo: true });
test("25.2-T14: Given any fee item labeled \"CD preparation fee\" or \"disclosure delivery fee\", then `renderCd` fails validation ((f)(5)).", { todo: true });
