// 25.3 Right of rescission (refinances of principal dwellings): notice, period computation, waiver, confirmation of non-rescission, effect on funding, and rescission processing
// spec/sections/25-compliance-testing-the-closing-disclosure-rescission-and-clo/25-3-right-of-rescission-refinances-of-principal-dwellings-notice.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("25.3-T1: Given consummation Fri Nov 6, 2026 with H-8 copies delivered to both consumers at signing and CD v1 received Mon Nov 2, when `computeRescissionPeriod` runs, then `period_start_date = 2026-11-06`, `expires_at = 2026-11-10T24:00 MST`, `fundings.rescission_expires_at` matches, and `disburse` on Tue Nov 10 is refused.", { todo: true });
test("25.3-T2: Given T1 and a channel sweep on Wed Nov 11 08:00 MST finding nothing, then `reasonably_satisfied_at` is set, `REGZ_1026_23_RESCISSION_3SBD_GATE` opens, and the `funder` schedules the wire for Thu Nov 12 (Fedwire closed Nov 11); no Reg Z violation is recorded for the Nov 11 gap.", { todo: true });
test("25.3-T3: Given consummation Wed Nov 25, 2026, then `expires_at = 2026-11-30T24:00` (Thanksgiving Thu Nov 26 and Sun Nov 29 excluded; Sat Nov 28 counted) and disbursement is scheduled Tue Dec 1, 2026.", { todo: true });
test("25.3-T4: Given consummation Mon Nov 9, 2026, then `expires_at = 2026-11-13T24:00` (Veterans Day excluded) and disbursement is scheduled Mon Nov 16 (weekend).", { todo: true });
test("25.3-T5: Given the non-borrower spouse's copies delivered Mon Nov 9 (courier receipt) after a Fri Nov 6 consummation, then her `period_start_date = 2026-11-09`, the loan `expires_at = 2026-11-13T24:00`, and funding moves to Mon Nov 16; given no delivery evidence for her at all, then `status = extended_3y` with `extended_expires_at = 2029-11-06` and `loans.rescission_extended_until` is set at boarding.", { todo: true });
test("25.3-T6: Given a partner-originated existing loan with UPB $548,200.00, earned unpaid interest $2,100.55, refinancing costs $7,950.00 and amount financed $556,150.00, then `rescindable_amount_cents = -210055`, `applicability = exempt_same_creditor_no_new_money`, no notice is generated and `disburse` is not gated by rescission; given UPB $544,000.00, then `rescindable_amount_cents = 209945`, `form = h9`, and the H-9 states the increase of $2,099.45.", { todo: true });
test("25.3-T7: Given a refinance of a second home (occupancy = second_home for every owner), then `applicability = not_principal_dwelling` and no notice or gate exists; given a purchase, `exempt_purchase_money`.", { todo: true });
test("25.3-T8: Given a consumer statement typed into a template with pre-printed waiver language, then `rescission_waivers` creation is rejected; given a dated, consumer-written, signed statement by both consumers accepted by `officer` on Sat Nov 7, then `status = waived` and `disburse` is permitted on Mon Nov 9 (Fedwire).", { todo: true });
test("25.3-T9: Given a rescission notice postmarked Tue Nov 10 received Fri Nov 13 after a Thu Nov 12 disbursement, then `valid = true`, `refund_due_at = 2026-12-03`, an unwind checklist opens, and `REGZ_1026_23D2_RESCISSION_REFUND_20` breaches on Dec 4 if `rescission.unwind.completed` has not fired.", { todo: true });
test("25.3-T10: Given the CD's finance charge understated by $2,900.00 on the fixture (> $2,800.00 = 0.5% of $560,000), then `material_disclosures_accurate = false`, the period does not start until an accurate corrected CD is received, and the notice's printed expiry date is regenerated.", { todo: true });
test("25.3-T11: Given an e-delivered H-8 under a valid E-SIGN consent, then the platform still records two copies per consumer (policy) and the compliance test accepts either 1 or 2; given paper delivery of one copy only, then `SM_O63_NOTICE_AT_SIGNING_GATE` blocks `consummate`.", { todo: true });
test("25.3-T12: Given a phone call on day 3 at 23:30 saying \"I want to cancel\", then the call is logged as a rescission candidate, the consumer is sent the form and instructions within 5 minutes, and funding is held through the 2-day mail allowance.", { todo: true });
