// 25.4 Other closing-time and immediate post-closing consumer notices: initial escrow statement delivery, escrow elections and state escrow-waiver disclosures, the §1026.39 notice of ownership transfer (Fannie Mae's practice), GLBA privacy gate, first-payment letter and autopay enrollment, HPA and flood cross-references, state post-closing notices, IRS Form 1098 seeding, and the closing-day notice run
// spec/sections/25-compliance-testing-the-closing-disclosure-rescission-and-clo/25-4-other-closing-time-and-immediate-post-closing-consumer-notic.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("25.4-T1: Given the refinance fixture with 30.3's initial analysis approved Wed Nov 4, 2026 (monthly escrow $525.00, cushion $1,050.00, initial deposit $1,875.00), when `composeClosingPackage` runs for the Fri Nov 6 closing, then the package contains the initial escrow statement, `escrow_accounts.initial_statement_delivered_at = 2026-11-06` after the signing manifest is captured, and servicing 3.1's evidence check returns `satisfied_by_originator`.", { todo: true });
test("25.4-T2: Given the same fixture but the analysis approved only on Fri Nov 6 at 08:00, then the statement is not in the package, `SM_O64_INITIAL_ESCROW_STMT_AT_SETTLEMENT` records `deferred`, and 3.1's `REGX_1024_17G_INITIAL_STMT_45` is due Mon Dec 21, 2026.", { todo: true });
test("25.4-T3: Given the CD shows \"Initial Escrow Payment at Closing\" $1,875.00 and monthly escrow $525.00 but 30.3's approved analysis yields $1,900.00 / $525.00, when the consistency check runs, then `CD_ESCROW_VS_O11_3 = mismatch`, `SM_O64_CLOSING_PACKAGE_NOTICES_GATE` blocks, and 25.2 issues a corrected CD with `cd_reason = pre_consummation_no_wait`.", { todo: true });
test("25.4-T4: Given `loan.purchased` on Thu Nov 19, 2026 with `date_basis = acquirer_books`, when `evaluateOwnershipTransfer` runs, then `ownership_transfer_notices.due_date = 2026-12-19`, `sender = covered_person_direct`, `status = expected`, no notice is rendered, and `SM_O64_FNMA_1026_39_EVIDENCE_45` is due Sun Jan 3, 2027; given a written Fannie Mae instruction on file, then `sender = servicer_on_behalf` and `REGZ_1026_39_OWNERSHIP_NOTICE_30` is satisfied by a mailing on Fri Dec 18 and breached by a mailing on Mon Dec 21.", { todo: true });
test("25.4-T5: Given purchase on Wed Nov 25, 2026, then `due_date = 2026-12-25` (no holiday adjustment); given the warehouse facility takes an assignment at funding on Thu Nov 12 and the loan is purchased Nov 19, then `covered_person = sm_warehouse_assignee` with `status = exception_c1`; given the loan is still unsold on Sat Dec 12, then `REGZ_1026_39_OWNERSHIP_NOTICE_30` requires `NTC_REGZ_1026_39_OWNERSHIP_TRANSFER` sent by that day with (d)(4) \"has not been recorded in public records\" and (d)(5) alternative (ii).", { todo: true });
test("25.4-T6: Given the privacy notice evidenced Mon Oct 5, 2026 for both borrowers, then `GLBA_1016_4_INITIAL_PRIVACY_GATE` is open; given no evidence for the co-borrower, then the gate blocks until `NTC_GLBA_1016_4_PRIVACY_INITIAL` is added to the package and acknowledged at signing on Nov 6.", { todo: true });
test("25.4-T7: Given funding Thu Nov 12, 2026 and first payment Fri Jan 1, 2027, then `SM_O64_FIRST_PAYMENT_LETTER_5BD` is due Thu Nov 19 and `SM_O64_FIRST_PAYMENT_LETTER_PREDUE_20` on Sat Dec 12; given the purchase fixture funded Thu Nov 19, then the 5-day timer is due Fri Nov 27 (Thanksgiving excluded); a letter template that pre-checks autopay or states enrollment is required fails validation (\u00a71005.10(e)(1)).", { todo: true });
test("25.4-T8: Given a Utah property, escrow requested waived, LTV 70%, when the package is composed, then `NTC_UT_7_17_4_RESERVE_OPTIONS` (both options; \"a reserve account is not required by the lender\"; borrower responsible for taxes and insurance) is delivered at or before closing and `UT_7_17_4_RESERVE_OPTIONS_NOTICE_GATE` opens only when `escrow_elections.elected_at \u2264 consummation_at`; given the borrower elects a reserve account at 70% LTV, then `interest_on_escrow_required = true` (7-17-3).", { todo: true });
test("25.4-T9: Given a California single-family owner-occupied purchase at 85% LTV where the borrower elects an impound account, then `NTC_CA_CIV_2954_IMPOUND_STMT` (not required as a condition; interest statement) is required and `CA_CIV_2954_IMPOUND_STMT_GATE` blocks without it; given 90% LTV, then the account may be required under \u00a72954(a)(1) and the notice is still generated as policy.", { todo: true });
test("25.4-T10: Given the purchase fixture with BPMI, when the borrower requests an escrow waiver, then `evaluateEscrowWaiver` returns `waivable = false` with reason `bpmi` (B2-1.5-04) and `escrow_elections.election = escrow_full`; given an HPML result from 23.4, reason `hpml`.", { todo: true });
test("25.4-T11: Given boarding on Thu Nov 12, 2026 for the refinance fixture, then `tax_reporting_seeds` = {origination_date 2026-11-06, principal 56000000, prepaid_interest 178548, points 0, mi_at_closing 0, acquisition_date null} and `SM_O64_1098_SEEDS_AT_BOARDING_GATE` opens; servicing 7.1-A produces a 2026 Form 1098 with Box 1 $1,785.48; given the purchase fixture with 0.500 borrower-paid points on $412,000, then `points_paid_cents = 206000` and prepaid interest $863.51.", { todo: true });
test("25.4-T12: Given a partner that names its own payee address at closing, then `loans.payment_address_named_at_closing = false`, servicing 1.3's combined MS-2 notice is included in the package with `delivered_at_settlement = true`, and `REGX_1024_33B3_COMBINED_15` is recorded satisfied at settlement.", { todo: true });
test("25.4-T13: Given an Illinois property, when `composeClosingPackage` runs, then it refuses with `jurisdiction_rules.escrow_election_notice[IL].verified_at = null` and opens an escalation to `officer` (31.1 verification required).", { todo: true });
test("25.4-T14: Given a borrower call on Mon Dec 14, 2026 reporting \"a letter from Fannie Mae says they own my loan\", then the agent records `ownership_transfer.notice.evidenced` with `evidence = borrower_report`, explains that payments continue to Supermortgage, and no misdirected-payment case is opened unless a payment was sent to Fannie Mae.", { todo: true });
