/**
 * §25.4 timer overrides (process-owned; applied after every section's so they win the merge — see
 * src/domain/bankruptcy/timers-14-1.ts for the pattern). One `reg.override(code, { trigger?, satisfied | evaluator,
 * anchorField?, offset?, why })` per 25.4 registry row whose trigger/satisfied column names an event the platform
 * spells differently or a condition the column grammar drops; `why` quotes the spec. A code the servicing spec
 * (sections 1–19) owns is never overridden here — reference it (`REGX_1024_17G_INITIAL_STMT_45` 3.1,
 * `REGX_1024_33B3_COMBINED_15` 1.3). Wired by src/domain/timer-overrides.ts.
 *
 * Grammar conventions (src/kernel/events/match.ts holds ONE dotted pattern per column):
 * - every event ops-25-4.ts appends carries `applicationId` (+ `application_id`, `source=origination`), so the rows arm
 *   only under origination context (src/kernel/timers/engine.ts isOriginationContext);
 * - the four not-before gates are condition-shaped and evaluator-backed (evaluators-25-4.ts), each also satisfied by the
 *   evaluation event the composer / evidence step appends with `result=open`;
 * - "disclosures{kind=state:UT_7_17_4}" is a table predicate, not an event: the composer's `escrow.state_notice.gate.evaluated{state, result}`
 *   carries the delivered/elected facts (values may not contain ':' in the pattern grammar, hence `state=UT`);
 * - the seam rows keep the satisfiers the other processes emit: 30.2's `notice.sent{template=NTC_SM_FIRST_PAYMENT_LETTER}`
 *   (both letter clocks — the registry's "same"), 30.3's `escrow.statement.sent{statement_type=initial, channel=closing_package}`
 *   (written here through 30.3's deliverStatementAtSettlement from the package evidence), 30.4's / 25.4's
 *   `ownership_transfer.notice.evidenced`, and 25.4's `tax_reporting.seeds.handed_off`;
 * - `loan.purchased{purchase_date}` (30.1) anchors the §1026.39 rows on `purchase_date` — the acquirer's books date, which is
 *   `ownership_transfer_notices.date_of_transfer` under the default `date_basis=acquirer_books` (§1026.39(b)(2); the
 *   transferor-books alternative is computed on the row by evaluateOwnershipTransfer).
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_25_4(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // ---- consummation gates (closing.scheduled → consummation) — condition-shaped, evaluator-backed
  o("GLBA_1016_4_INITIAL_PRIVACY_GATE", { anchorField: "consummation_at", evaluator: "25.4.privacyGateOpen", satisfied: "`privacy.gate.evaluated{result=open}`",
    why: "§25.4 timer table: not_before_gate on `closing.scheduled`, anchor consummation, offset '0 — `disclosures{kind=privacy}.delivered_at ≤ consummation_at` for every borrower', satisfied by '21.3 delivery evidence, or `NTC_GLBA_1016_4_PRIVACY_INITIAL` included in the closing package with receipt' — §1016.4(a)(1) 'not later than when you establish a customer relationship' ((c)(3)(i): the consumer obtains credit). ops-25-4.ts `checkPrivacyNotice` evaluates every customer borrower (a non-borrower spouse is not a customer) and the composer / `recordPackageEvidence` append `privacy.gate.evaluated{result}` (T6: evidenced Mon Oct 5, 2026 for both → open; no co-borrower evidence → blocked until the notice is in the package and acknowledged at signing Nov 6); breach: `consummate` refused." });
  o("SM_O64_CLOSING_PACKAGE_NOTICES_GATE", { anchorField: "scheduled_at", evaluator: "25.4.closingPackageGateOpen", satisfied: "`notice.closing_package.composed{status=gated}`",
    why: "§25.4 timer table: not_before_gate on `closing.scheduled`, anchor 'signing start' (26.2's event carries `scheduled_at`), offset '0 — every `required` item in `closing_notice_runs{kind=closing_package}` rendered from the `consummation_ready` CD version', satisfied by '`notice.closing_package.composed` with `status=gated`' — ops-25-4.ts `composeClosingPackage` appends the event with `status=gated` only when the CD-escrow consistency check matches and every gate is open (T3: `CD_ESCROW_VS_O11_3 = mismatch` blocks; 25.2 issues the corrected CD with `cd_reason=pre_consummation_no_wait`); breach: `consummate` refused; escalation to the `disclosure` agent lead then `officer`." });
  o("SM_O64_INITIAL_ESCROW_STMT_AT_SETTLEMENT", { anchorField: "scheduled_at",
    why: "§25.4 timer table: policy target on `closing.scheduled` (escrowed loan), anchor consummation (26.2's `scheduled_at`), offset '0 — statement in the package when 30.3's initial analysis is approved ≥ 1 `business_days_creditor` before consummation', satisfied by '`escrow.statement.sent{statement_type=initial, channel=closing_package}` (3.1's event; recorded here from the package evidence)' — 30.3's `packageLead` decides (worked example 1: approved Wed Nov 4 ≤ Thu Nov 5 → in the package Fri Nov 6; T2: approved Fri Nov 6 08:00 → `deferred`), `recordPackageEvidence` writes the satisfier through 30.3's `deliverStatementAtSettlement` on the signing-manifest evidence; breach: fall back to servicing 3.1's `REGX_1024_17G_INITIAL_STMT_45` (settlement + 45 calendar days = Mon Dec 21, 2026; referenced, never redefined)." });
  o("UT_7_17_4_RESERVE_OPTIONS_NOTICE_GATE", { anchorField: "consummation_at", evaluator: "25.4.utReserveOptionsGateOpen", satisfied: "`escrow.state_notice.gate.evaluated{state=UT, result=open}`",
    why: "§25.4 timer table: not_before_gate on `closing.scheduled` (property state UT), anchor consummation, offset '0 — notice delivered \"at or prior to the closing\" and the election captured at closing', satisfied by '`disclosures{kind=state:UT_7_17_4}` + `escrow_elections.elected_at ≤ consummation_at`' — Utah Code §7-17-4: written notice of the two options 'at or prior to the closing of the loan'; 'the borrower shall select one of the options at the closing'. Condition-shaped (`utReserveOptionsGate`); the composer appends `escrow.state_notice.gate.evaluated{state=UT, result}` (a table predicate is not an event; ':' is not allowed in a pattern value, so the state code carries the kind); breach: `consummate` refused." });
  o("CA_CIV_2954_IMPOUND_STMT_GATE", { anchorField: "consummation_at", evaluator: "25.4.caImpoundStmtGateOpen", satisfied: "`escrow.state_notice.gate.evaluated{state=CA, result=open}`",
    why: "§25.4 timer table: not_before_gate on `closing.scheduled` (property state CA, escrow elected, single-family owner-occupied, outside §2954(a)(1) exceptions), anchor consummation, offset '0 — written statement (not required as a condition; interest yes/no) delivered before or with the election', satisfied by '`disclosures{kind=state:CA_CIV_2954}`' — Civ. Code §2954(a): the account 'shall not be required as a condition' and the statement says 'whether or not interest will be paid'. Condition-shaped (`caImpoundStmtGate`; T9: 85% LTV impound elected → required, gate blocks without it; 90% → the account may be required under (a)(1) and the notice still issues as policy); breach: `consummate` refused." });
  // ---- funding clocks (loan.funded — 30.2 emits it with disbursement_date and first_payment_date)
  o("SM_O64_FIRST_PAYMENT_LETTER_5BD", { anchorField: "disbursement_date",
    why: "§25.4 timer table: deadline on `loan.funded`, anchor `disbursement_date`, offset '+5 `business_days_servicer`', satisfied by '`notice.sent{template=NTC_SM_FIRST_PAYMENT_LETTER}` (30.2)' — worked example 1: Nov 12 + 5 = Thu Nov 19, 2026; purchase fixture Nov 19 + 5 = Fri Nov 27 (Thanksgiving excluded). 30.2's `sendFirstPaymentLetter` appends the satisfier, rendering through the Notice Registry once 25.4's authored NTC_SM_FIRST_PAYMENT_LETTER version is published; breach: sev 2 → `boarding` agent lead; auto-send." });
  o("SM_O64_FIRST_PAYMENT_LETTER_PREDUE_20", { anchorField: "first_payment_date", satisfied: "`notice.sent{template=NTC_SM_FIRST_PAYMENT_LETTER}`",
    why: "§25.4 timer table: deadline on `loan.funded`, anchor `first_payment_date`, offset '−20 `calendar_days`', satisfied by 'same' (= `notice.sent{template=NTC_SM_FIRST_PAYMENT_LETTER}`, 30.2) — worked example 1: Jan 1, 2027 − 20 = Sat Dec 12, 2026; the 7.1 first periodic statement still issues on its own clock; breach: sev 1 → `officer`." });
  o("SM_O64_POST_CLOSING_NOTICE_RUN_2BD", { anchorField: "disbursement_date",
    why: "§25.4 timer table: deadline on `loan.funded`, anchor `disbursement_date`, offset '+2 `business_days_servicer`', satisfied by '`notice.post_closing_run.completed` (welcome letter, first-payment letter, any state post-closing notice, initial escrow statement if not at settlement)' — worked example 1: Fri Nov 13 (1), Mon Nov 16 (2) → Mon Nov 16, 2026. ops-25-4.ts `schedulePostClosingRun` plans the run and `completePostClosingRun` appends the satisfier once every required item has a mailing/e-delivery manifest; breach: sev 3; retry." });
  // ---- §1026.39 (loan.purchased — 30.1; purchase_date = the acquirer's books date = date_of_transfer)
  o("REGZ_1026_39_OWNERSHIP_NOTICE_30", { anchorField: "purchase_date",
    why: "§25.4 timer table: deadline on '`loan.purchased` (Fannie Mae acquires legal title)', anchor `date_of_transfer`, offset '+30 `calendar_days` (\"on or before the 30th calendar day following the date of transfer\")', satisfied by '`ownership_transfer.notice.sent` when `sender = servicer_on_behalf` or `covered_person = sm_warehouse_assignee`; otherwise informational (Fannie Mae sends) — status `expected`' — 30.1's `loan.purchased{purchase_date}` carries the purchase-advice date, which is `ownership_transfer_notices.date_of_transfer` under `date_basis=acquirer_books` (§1026.39(b)(2); worked example 1: Nov 19 → Sat Dec 19, 2026; example 2: Nov 25 → Fri Dec 25 — calendar days, Christmas Day changes nothing). `evaluateOwnershipTransfer` records the expectation; `sendOwnershipNotice` appends the satisfier in the two sending branches (T4: mailed Fri Dec 18 satisfies, Mon Dec 21 breaches); the `warehouse.advance.funded` assignment branch is inactive under `origination.warehouse_legal_form = secured_loan_to_partner`; breach: when SM is the sender sev 1 → `officer`; when Fannie Mae sends: none." });
  o("SM_O64_FNMA_1026_39_EVIDENCE_45", { anchorField: "purchase_date",
    why: "§25.4 timer table: policy deadline on `loan.purchased`, anchor `purchase_date`, offset '+45 `calendar_days`', satisfied by '`ownership_transfer.notice.evidenced` (copy of the Fannie Mae letter from the borrower/portal, or Fannie Mae confirmation)' — worked example 1: Nov 19 + 45 = Sun Jan 3, 2027. 30.4's `fnmaLetterEvidenced{kind=fnma_loan_purchase_letter}` and 25.4's `recordBorrowerReport{evidence=borrower_report}` (T14) both append the satisfier; breach: status `overdue_unconfirmed`; inquiry to Fannie Mae's account team; no consumer action." });
  // ---- boarding gate (loan.boarded — 30.2)
  o("SM_O64_1098_SEEDS_AT_BOARDING_GATE", { anchorField: "boarded_at",
    why: "§25.4 timer table: not_before_gate on `loan.boarded`, anchor boarding (30.2's event carries `boarded_at`), offset '0 — `tax_reporting_seeds` row complete', satisfied by '`tax_reporting.seeds.handed_off`' — ops-25-4.ts `handoffTaxReportingSeeds` appends it with the complete row (worked example 1: origination_date 2026-11-06, principal 56000000, prepaid_interest 178548, points 0, mi_at_closing 0, acquisition_date null); breach: boarding checklist item fails (30.2; 30.4's HO-008)." });
}
