/**
 * §25.2 timer overrides (process-owned; applied after every section's so they win the merge — see
 * src/domain/bankruptcy/timers-14-1.ts for the pattern). One `reg.override(code, { trigger?, satisfied | evaluator,
 * anchorField?, offset?, why })` per 25.2 registry row whose trigger/satisfied column names an event the platform
 * spells differently or a condition the column grammar drops; `why` quotes the spec. A code the servicing spec
 * (sections 1–19) owns is never overridden here — reference it. Wired by src/domain/timer-overrides.ts.
 *
 * Grammar conventions (src/kernel/events/match.ts holds ONE dotted pattern per column):
 * - every event ops-25-2.ts appends carries `applicationId` (+ `application_id`, `source=origination`), so the rows arm
 *   only under origination context (src/kernel/timers/engine.ts isOriginationContext);
 * - the two gates (3-SBD, UCD) are condition-shaped and evaluator-backed (evaluators-25-2.ts), like 21.2's 7-SBD gate;
 * - "(latest required consumer)" is the `all_required=true` flag on `disclosure.cd.received`; "(purchase)" is
 *   `transaction_type=purchase` on 26.2's `closing.scheduled`; the post-consummation regimes are the `regime` field on
 *   `disclosure.cd.correction.required`; "after consummation and before loan.purchased" is `post_consummation=true,
 *   before_purchase=true` on `disclosure.cd.corrected`.
 * `REGZ_1026_19F2V_TOLERANCE_REFUND_60` is 21.5's — this process only emits the `disclosure.cd.corrected{reason=tolerance_refund}`
 * half of its satisfaction; never redefined here.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_25_2(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  o("REGZ_1026_19F1_CD_3SBD_GATE", { trigger: "`disclosure.cd.received{all_required=true}`", anchorField: "effective_receipt_date", evaluator: "25.2.cd3sbdGateOpen", satisfied: "`disclosure.cd.consummated`",
    why: "§25.2 timer table: not_before_gate, trigger '`disclosure.cd.received` (latest required consumer)', anchor `effective_receipt_date`, offset '+3 `business_days_regz_specific` → `earliest_consummation_date` (consummation may occur on that day)', satisfied by '`consummate` command date ≥ `earliest_consummation_date` (or accepted waiver)' — §1026.19(f)(1)(ii)(A) 'no later than three business days before consummation' on the §1026.2(a)(6) specific calendar (Saturdays count; worked example 1: received Mon Nov 2 → Tue 3, Wed 4, Thu 5 → earliest Thu Nov 5, 2026). Condition-shaped: ops-25-2.ts emits `disclosure.cd.received{all_required=true}` once every required consumer (§1026.17(d); platform policy: every borrower) has an effective receipt date; `consummate` asserts the gate through `cd3sbdGate` (a `cd_waivers` row accepted by officer moves it to consummation_ready) and appends `disclosure.cd.consummated{version}`; breach: `consummate` refused (CdGateClosed); closing rescheduled." });
  o("REGZ_1026_19F1III_CD_MAILBOX_3SBD", { trigger: "`disclosure.cd.delivered{in_person=false}`", anchorField: "delivered_on", offset: "+3 business_days_regz_specific", satisfied: "`disclosure.cd.received`",
    why: "§25.2 timer table: presumption on '`disclosure.cd.delivered{channel ≠ in_person}`', anchor '`mailed_at`/`delivered_at`', offset '+3 `business_days_regz_specific` → `presumed_receipt_date`', satisfied by 'earlier `actual_receipt_at` evidence (rebuts)' — §1026.19(f)(1)(iii) 'considered to have received the disclosures three business days after they are delivered or placed in the mail' (worked example 2: mailed Mon Nov 2 → presumed Thu Nov 5). ops-25-2.ts `deliver` appends the event with `in_person` and the civil `delivered_on`; `recordReceipt` (e-sign / portal acknowledgement / courier signature — decision 25.2-Q2: never an e-mail 'opened' event or a phone call) and the `deemReceived` sweep on the presumed date both append `disclosure.cd.received{evidence}`; breach: none (a presumption) — it feeds the gate." });
  o("SM_O62_CD_TARGET_4SBD", { anchorField: "scheduled_at",
    why: "§25.2 timer table: policy deadline on `closing.scheduled` (26.2), anchor 'scheduled consummation date' — the event's `scheduled_at` (its civil date), offset '−4 `business_days_regz_specific`' (worked example 4: closing Wed Nov 18, 2026 → Tue 17, Mon 16, Sat 14, Fri 13 → e-delivery target Fri Nov 13), satisfied by `disclosure.cd.delivered` (ops-25-2.ts `deliver`); breach: warning to the `disclosure` agent; reschedule proposal (`scheduleDelivery`)." });
  o("SM_O62_SETTLEMENT_FIGURES_5SBD", { anchorField: "scheduled_at", satisfied: "`cd.figure_source.reconciled{party=settlement_agent}`",
    why: "§25.2 timer table: policy deadline on `closing.scheduled` (26.2), anchor 'scheduled consummation date' (the event's `scheduled_at`), offset '−5 `business_days_regz_specific`' (worked example 4: five specific business days before Wed Nov 18 = Tue 17, Mon 16, Sat 14, Fri 13, Thu 12 → due Thu Nov 12), satisfied by '`cd_figure_sources{party=settlement_agent, reconciled=true}`' — ops-25-2.ts `reconcileFigureSources` appends `cd.figure_source.reconciled{party, version}` for every reconciled inbound version; breach: escalation to `settlement_agent` with SLA 1 `business_days_creditor` (`onSettlementFiguresBreached`)." });
  o("REGZ_1026_19F2_CORRECTED_CD_30", { trigger: "`disclosure.cd.correction.required{regime=post_consummation_event}`", anchorField: "info_received_on", offset: "+30 calendar_days", satisfied: "`disclosure.cd.corrected{reason=post_consummation_event}`",
    why: "§25.2 timer table: deadline on 'post-consummation event information received (event within 30 `calendar_days` after `consummation_at`)', anchor `info_received_at`, offset '+30 `calendar_days`', satisfied by '`disclosure.cd.corrected{reason=post_consummation_event}` delivered or placed in the mail' — §1026.19(f)(2)(iii) 'not later than 30 days after receiving information sufficient to establish that such event has occurred' (worked example 7: recording fee +$12.00 learned Mon Nov 16, 2026 → due Wed Dec 16; issued Tue Nov 17). ops-25-2.ts `recordCorrectionEvent` classifies the regime and appends `disclosure.cd.correction.required{regime, info_received_on}`; `scheduleCorrectedCd` appends the satisfying event on delivery/mailing; breach: sev 1 → `officer` (`onCorrectionClockBreached`)." });
  o("REGZ_1026_19F2_CLERICAL_CD_60", { trigger: "`disclosure.cd.correction.required{regime=clerical}`", anchorField: "consummation_on", offset: "+60 calendar_days", satisfied: "`disclosure.cd.corrected{reason=clerical}`",
    why: "§25.2 timer table: deadline on 'clerical error identified', anchor `consummation_at`, offset '+60 `calendar_days`', satisfied by 'corrected CD delivered/mailed' — §1026.19(f)(2)(iv) 'no later than 60 days after consummation' (worked example 8: consummation Fri Nov 6, 2026 → due Tue Jan 5, 2027). The identification is `disclosure.cd.correction.required{regime=clerical, consummation_on}` (ops-25-2.ts `recordCorrectionEvent`); `scheduleCorrectedCd` appends `disclosure.cd.corrected{reason=clerical}`; breach: sev 2 → `officer`." });
  o("REGZ_1026_19F4_SELLER_CD_GATE", { trigger: "`closing.scheduled{transaction_type=purchase}`", anchorField: "scheduled_at",
    why: "§25.2 timer table: deadline on '`closing.scheduled` (purchase)' (26.2's event with `transaction_type=purchase`), anchor 'consummation date' (the event's `scheduled_at`), offset '0 (no later than the day of consummation)', satisfied by '`disclosure.seller_cd.received` (settlement agent's seller CD and creditor copy per (f)(4)(iv))' — §1026.19(f)(4)(ii) 'no later than the day of consummation'; ops-25-2.ts `recordSellerCd` appends the event; breach (T8: purchase closing Wed Nov 18, 2026 with no copy by end of day): escalation to `settlement_agent`, `delivery.package.incomplete{reason=seller_cd_missing}` until received (`onSellerCdGateBreached`)." });
  o("FNMA_UCD_ACCEPTED_GATE", { trigger: "`disclosure.cd.consummated`", anchorField: "consummation_on", evaluator: "25.2.ucdAcceptedGateOpen", satisfied: "`ucd.accepted{is_final=true}`",
    why: "§25.2 timer table: not_before_gate on 'final CD (`consummated`, and any pre-delivery correction)', condition 'UCD `accepted`/`accepted_with_warnings` with `critical_edit_failures = 0` for the CD version embedded', consumed by '`submitDelivery` (29.3 composes)' — GSE UCD FAQ: 'The UCD in the XML file format with the Closing Disclosure PDF embedded must be successfully submitted prior to loan delivery'; 'the most recent version of the CD must be included'. Arms on ops-25-2.ts `consummate` (`disclosure.cd.consummated{version}`); condition-shaped, asserted by `assertUcdGateOpen` through `ucdAcceptedGate`; `submitUcd` appends `ucd.accepted{casefile_id_ucd, critical_edit_failures, is_final}` (is_final=true iff the embedded CD is the version in force) and copies the casefile ID to `deliveries.ucd_casefile_id`; breach: `submitDelivery` refused (UcdGateClosed)." });
  o("SM_O62_UCD_RESUBMIT_ON_CORRECTION", { trigger: "`disclosure.cd.corrected{post_consummation=true, before_purchase=true}`", anchorField: "delivered_on", satisfied: "`ucd.accepted{is_final=true}`",
    why: "§25.2 timer table: deadline on '`disclosure.cd.corrected` after consummation and before `loan.purchased`', anchor 'correction delivered', offset '+2 `business_days_fannie_et`', satisfied by 'new `ucd_submissions` row `accepted` with `is_final`' — GSE UCD FAQ: 'If the loan has closed, but has not been delivered to a GSE, and a revised CD was provided to the borrower, the most recent version of the CD must be included in the updated UCD XML file submission' (T11: corrected CD delivered Tue Nov 17, 2026 → new accepted UCD by Thu Nov 19). ops-25-2.ts `scheduleCorrectedCd` appends the trigger with `post_consummation`, `before_purchase` and the civil `delivered_on`; `submitUcd` appends `ucd.accepted{is_final=true}` when the embedded CD is the corrected version; breach: delivery gate re-blocks (`ucdAcceptedGate` sees no accepted submission for the final CD)." });
}
