/**
 * §25.3 timer overrides (process-owned; applied after every section's so they win the merge — see
 * src/domain/bankruptcy/timers-14-1.ts for the pattern). One `reg.override(code, { trigger?, satisfied | evaluator,
 * anchorField?, offset?, why })` per 25.3 registry row whose trigger/satisfied column names an event the platform
 * spells differently or a condition the column grammar drops; `why` quotes the spec. A code the servicing spec
 * (sections 1–19) owns is never overridden here — reference it. Wired by src/domain/timer-overrides.ts.
 *
 * The two gates are condition-shaped and backed by evaluators-25-3.ts (`25.3.rescissionGateOpen`, `25.3.noticeAtSigningOpen`);
 * the clocks anchor on the LOCAL dates ops-25-3.ts puts on its events (`expires_on`, `received_on`, `consummation_date_local`)
 * — an ISO `expires_at` of 07:00Z would resolve to the wrong Eastern civil date. Every 25.3 event carries `applicationId`
 * (origination context). `REGZ_1026_19F1_CD_3SBD_GATE` is 25.2's — referenced ("must also be open"), never redefined.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_25_3(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  o("REGZ_1026_23_RESCISSION_3SBD_GATE", { anchorField: "period_start_date", evaluator: "25.3.rescissionGateOpen", satisfied: "`rescission.confirmed_not_rescinded`",
    why: "§25.3 timer table: not_before_gate on `rescission.period.started` (ops-25-3.ts startPeriod), anchor `period_start_date`, '+3 `business_days_regz_specific`, expiring at local midnight ending day 3 → `expires_at`; `disburse` allowed only when `now > expires_at` and `reasonably_satisfied_at` is set (or an accepted waiver exists)' — a gate asserted by domain code (rescissionGate), not a deadline that breaches; satisfied by '`rescission.confirmed_not_rescinded` or `rescission.waiver.accepted`' — confirmNotRescinded appends the first after the sweep and acceptRescissionWaiver appends it too (satisfaction_basis=waiver_accepted) so either path closes the row; breach: `disburse` refused (assertDisburseAllowed throws REGZ_1026_23_RESCISSION_3SBD_GATE); any attempted wire before expiry is a sev 1 incident to `officer`." });
  o("SM_O63_SATISFACTION_SWEEP", { anchorField: "expires_on", satisfied: "`rescission.sweep.completed`",
    why: "§25.3 timer table: deadline (policy) on `rescission.period.expired` (expirePeriod, occurredAt = the expiry instant), anchor `expires_at`, '+8 hours (08:00 local on the following day)' — the fixture's 2026-11-11T07:00:00Z + 8 h = 08:00 MST Wed Nov 11; satisfied by 'sweep of all inbound channels for notices given on or before `expires_at` (postmark rule) → `reasonably_satisfied_at`' — sweepChannels + confirmNotRescinded append `rescission.sweep.completed{channels_checked, candidates, satisfied}` (and `rescission.confirmed_not_rescinded` when nothing was given in time); breach: funding held until the sweep completes." });
  o("SM_O63_MAILED_NOTICE_ALLOWANCE_2", { anchorField: "expires_on", satisfied: "`rescission.mail_allowance.closed`",
    why: "§25.3 timer table: policy window on `rescission.period.expired`, anchor `expires_at` (local date `expires_on`), '+2 `calendar_days`' (fixture: Nov 10 → Thu Nov 12); satisfied by 'a mailed rescission notice postmarked on or before `expires_at` that arrives within the window reverses a not-yet-disbursed funding without incident; after disbursement it is processed as a valid exercise' — the window closes with `rescission.mail_allowance.closed{notices_received}` (closeMailAllowance, called by the sweep at the end of the allowance or by the funder before release); a notice that arrives inside it goes through recordExercise (`rescission.notice.received{valid=true}`)." });
  o("REGZ_1026_23D2_RESCISSION_REFUND_20", { trigger: "`rescission.notice.received{valid=true}`", anchorField: "received_on", satisfied: "`rescission.unwind.completed`",
    why: "§25.3 timer table: deadline on '`rescission.notice.received` (valid)' (recordExercise appends it with `valid`), anchor `received_at` (its local civil date `received_on`), '+20 `calendar_days`' (§1026.23(d)(2); T9: received Fri Nov 13, 2026 → due Thu Dec 3, breaches Dec 4); satisfied by '`rescission.unwind.completed` (money returned; security interest terminated: release/reconveyance recorded or eNote/MIN voided)' — completeUnwind appends it under officer sign-off; breach: sev 1 → `officer`; legal referral." });
  o("REGZ_1026_23_EXTENDED_RIGHT_3Y", { anchorField: "consummation_date_local", satisfied: "`rescission.extended_right.lapsed`",
    why: "§25.3 timer table: monitor on `rescission.extended_right.flagged` (flagExtendedRight — a consumer whose notice or material disclosures were never delivered, or a (g)-inaccurate CD found at post-closing review), anchor `consummation_date_local`, '+3 years' (T5: Fri Nov 6, 2026 → Tue Nov 6, 2029; lapses earlier on transfer of all interest or sale); satisfied by 'lapse event or cure (re-delivery of a compliant notice and disclosures restarts a 3-business-day period — decision 25.3-Q4)' — lapseExtendedRight appends `rescission.extended_right.lapsed{reason∈{expired_3y, transfer_of_all_interest, sale, cured}}` (servicing 9.x/16.x call it on sale/transfer; the cure path after the fresh period expires unexercised); breach: flag stays on `loans.rescission_extended_until` for servicing; every payoff/servicing action checks it." });
  o("SM_O63_NOTICE_AT_SIGNING_GATE", { evaluator: "25.3.noticeAtSigningOpen", satisfied: "`rescission.signing_package.verified`",
    why: "§25.3 timer table: not_before_gate on `closing.scheduled` (26.2), anchor 'signing start', offset 0 — a gate over the signing package: 'every consumer's notice copies (2 paper / 1 electronic) and material disclosures in the signing package with per-consumer receipt capture' (noticeAtSigningCheck; T11: paper delivery of one copy blocks `consummate`, an e-delivered H-8 under a valid E-SIGN consent passes with 1 or 2 copies); satisfied by `rescission.signing_package.verified{copies_complete=true}` (verifySigningPackage); breach: `consummate` refused." });
}
