// 29.1 Committing and pricing execution (best efforts and mandatory PE–Whole Loan commitments, commitment terms, LLPAs, servicing fee and buy-up/buy-down, pair-off/extension, over/under delivery tolerance)
// spec/sections/29-secondary-marketing-and-delivery-to-fannie-mae-whole-loan-se/29-1-committing-and-pricing-execution-best-efforts-and-mandatory.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("29.1-T1: Given `lock.executed` Wed Oct 7, 2026 12:19 p.m. ET for the refinance fixture with a DU Approve/Eligible dated Oct 6, when the `secondary` agent runs, then a Loan Pricing quote and a Loan Committing confirmation exist by 12:30 p.m. ET, `commitments.expires_on = 2026-12-07`, `commitment_period_days = 61`, `pass_through_rate = 5.8750`, `commitment_price = 101.375`, `net_price_forecast = 101.250`, `proceeds_forecast_cents = 56,700,000`, and 21.4 records `lock.commitment.linked`.", { todo: true });
test("29.1-T2: Given a lock executed Wed Oct 7, 2026 at 6:30 p.m. ET with `secondary.after_hours_commit=false`, then no commit call is made; the request is queued; 29.2's 7:00 a.m. ET position shows the lock as `locked_uncommitted`; the commit executes at 8:15 a.m. ET Thu Oct 8 and `execution_variance_cents` records the overnight price change.", { todo: true });
test("29.1-T3: Given the purchase-fixture commitment and a loan-amount change to $409,500 at 2:10 p.m. ET Thu Nov 5, 2026, then `FNMA_C2_1_2_03_KEY_DATA_CHANGE_1BD` is due Fri Nov 6, 2026 5:00 p.m. ET; a modification filed at 2:31 p.m. ET Nov 5 satisfies it with `amount_cents = 40,950,000` and `max_amount_cents = 41,200,000`; if no modification exists at 5:00 p.m. ET Nov 6 the timer breaches sev 2 and an `officer` escalation opens.", { todo: true });
test("29.1-T4: Given a note-rate change from 6.125% to 6.250% on the refinance commitment when the live price for the new terms is 101.750, then `commitment_modifications.repriced=true`, `new_commitment_price = 101.375` (worse case), `worst_case_applied=true`.", { todo: true });
test("29.1-T5: Given `lock.cancelled{lender_declination}` Fri Oct 23, 2026, then the commitment moves to `fallout` the same day with `pair_off_expected=false` and `dpa_exposure_until = 2026-11-22`; a `commitBestEfforts` request for the same borrower and property on Tue Nov 10 is refused with `reason='dpa_window'` unless `dpa_acknowledged=true`; the same request on Mon Nov 23 succeeds.", { todo: true });
test("29.1-T6: Given `loan.funded` Thu Nov 12, 2026 3:40 p.m. ET, then `FNMA_PEWL_CLOSED_STATUS_1BD` is due Fri Nov 13 5:00 p.m. ET; `setClosedStatus` at 4:05 p.m. ET Nov 12 satisfies it and `commitments.status='closed'`; consummation on Nov 6 does not start the timer.", { todo: true });
test("29.1-T7: Given a closed refinance commitment (max amount $560,000, PTR 5.875%, price 101.375) and a live price of 102.125 on Mon Nov 30, 2026, when a lender-requested pair-off is prepared, then `fee_cents = 420,000` ($4,200.00), an `officer_pair_off_approval` escalation is opened (fee > $2,500), and the package states the alternative carry of $5,483.33 for 60 days; with a live price of 100.500 the fee is $0.00 and `cash_back_cents = 0`.", { todo: true });
test("29.1-T8: Given an 8-day manual extension requested while `committed`, then `per_diem_cents = 9,138.89` ($560,000 \u00d7 0.05875 / 360) and `fee_cents = 73,111` ($731.11); a further extension that would bring cumulative manual extensions to 31 days is refused by `FNMA_C2_1_2_02_BE_EXTENSION_CAP_30`.", { todo: true });
test("29.1-T9: Given a closed commitment with `original_expires_on = 2026-12-07` and no purchase, then `FNMA_C2_1_2_02_BE_CLOSED_AUTOEXT_CAP_60` is anchored at Fri Feb 5, 2027; an `officer` escalation opens no later than Fri Jan 29, 2027; if unresolved, the automatic pair-off is recorded from the fee draft with `kind='automatic'`.", { todo: true });
test("29.1-T10: Given a DU Approve/Eligible dated Sat Aug 1, 2026 and a lock on Wed Oct 7, 2026 (67 days), then `commitBestEfforts` with `underwriting_method='du'` is refused by `FNMA_C2_1_2_03_DU_APPROVE_60_GATE`; after an 23.1 resubmission on Oct 7 the commit succeeds.", { todo: true });
test("29.1-T11: Given `execution.mandatory_enabled=false`, when 29.2 requests a $5,000,000 mandatory commitment, then `prepareMandatoryPackage` is refused; with the flag true and an approved `officer_mandatory_authorization`, the operator package shows `tolerance_low_cents = 487,500,000`, `tolerance_high_cents = 512,500,000`, `over_delivery_cap_cents = 125,000,000`, five PTRs 5.625\u20136.125%, `expires_on = 2026-12-07`.", { todo: true });
test("29.1-T12: Given a mandatory commitment (price 101.250) with $4,600,000 purchased on Fri Dec 4, 2026 and a live price of 100.750, then a partial pair-off of $275,000 yields `cash_back_cents = 137,500`; with a live price of 101.750 it yields `fee_cents = 137,500`; a 10-day extension of the $400,000 remaining balance at the lowest PTR 5.625% costs `fee_cents = 62,500`.", { todo: true });
test("29.1-T13: Given a Fee Draft Notification of $731.11 for the extension in T8, then `committing_fee_drafts.status='matched'` and the ledger posts `committing_fee_expense` $731.11 (payer SM); a notification of $760.00 produces `status='exception'` and an `officer` task.", { todo: true });
test("29.1-T14: Given a requested expiration of Fri Dec 25, 2026 (SIFMA full close), then the adapter rolls to Mon Dec 28, 2026 before calling the API; a requested Sun Dec 6 rolls to Mon Dec 7; a requested Fri Nov 27 (early close) is accepted as a business day with the expiring-day sweep at 12:30 p.m. ET.", { todo: true });
test("29.1-T15: Given the day's executed commitments total $199,600,000 and a new $560,000 request, then `FNMA_C2_1_1_03_DAILY_LIMIT_200M_GATE` refuses the commit, queues it, and opens an `officer` escalation to contact the Sales Desk.", { todo: true });
test("29.1-T16: Given a VantageScore 4.0 tri-merge (771) instead of Classic FICO on the refinance fixture, then `llpa_forecast_pct = 0.250`, `net_price_forecast = 101.125`, `proceeds_forecast_cents = 56,630,000`, and SFC 067 is staged for 29.3.", { todo: true });
