// 29.2 Pipeline and interest-rate-risk management (fallout/pull-through, hedge for mandatory execution, mark-to-market, best-efforts operations)
// spec/sections/29-secondary-marketing-and-delivery-to-fannie-mae-whole-loan-se/29-2-pipeline-and-interest-rate-risk-management-fallout-pull-thro.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("29.2-T1: Given best-efforts mode and three locks executed after 5:00 p.m. ET Wed Oct 7, 2026 totaling $1,500,000, when the 7:00 a.m. ET snapshot runs Thu Oct 8, then `locked_uncommitted_cents = 150,000,000`, the +25 bp shock shows \u2212$15,000 (duration 4.0), and the 12:00 p.m. snapshot after 29.1's commits shows `locked_uncommitted_cents = 0`.", { todo: true });
test("29.2-T2: Given the fixture loan committed at 101.375 with a borrower base price of 100.875, stage `locked` (p = 0.80), servicing multiple 4.5\u00d7, then the Oct 7 mark reports `irlc_sale_price_component_cents = 224,000` and `irlc_servicing_component_cents = 504,000` separately, `irlc_fv_cents = 728,000`.", { todo: true });
test("29.2-T3: Given mandatory mode with $5,000,000 of locks at p = 0.80 and duration factor 1.00, then `target_hedge_face_cents = 400,000,000` and a trade package \"sell $4,000,000 UMBS 30-yr 6.0 Dec\" is opened as an `officer` escalation; no trade is recorded until a confirmation document is attached.", { todo: true });
test("29.2-T4: Given the $4,000,000 short at 100.500 and a Nov 2 mark of 101.500 with p falling to 0.72, then `hedge_fv_cents = \u22124,000,000`, `coverage_ratio = 1.1111`, `SM_HEDGE_COVERAGE_BAND_GATE` breaches the 1.10 band, and a rebalance package to buy back $400,000 is issued the same day with `realized_pl_cents = \u2212400,000` after execution at 101.500.", { todo: true });
test("29.2-T5: Given a Dec 2026 Class A TBA position, then `roll_due_on = 2026-12-03` (three business days before the Dec 8 notification) and `SIFMA_TBA_ROLL_GATE_3BD` breaches at 12:00 p.m. ET Dec 3 if the position is still open; a January position computes `roll_due_on = 2027-01-07` (Jan 11, Jan 8, Jan 7 before the Jan 12 notification).", { todo: true });
test("29.2-T6: Given a dealer margin call of $15,000 received Mon Nov 2, 2026 3:10 p.m. ET under a margin annex with a next-business-day due time, then `FINRA_4210_VARIATION_MARGIN_1BD` is due Tue Nov 3 close of business; a wire released at 11:30 a.m. ET Nov 3 under `funding_approver` dual control satisfies it; a call received Tue Nov 10 is due Thu Nov 12 (Wed Nov 11 Veterans Day is a SIFMA close).", { todo: true });
test("29.2-T7: Given the Nov 2 position, when the rate-shock report runs, then the \u2212100 bp row shows hedge \u2212$144,000, pipeline +$115,200 (p = 0.64 on $3,600,000 short), projected margin call $104,000 net of margin already posted, and the row is compared to `rate_shock_limit_cents`; the +100 bp row shows an $800,000 under-hedge and \u2212$14,400 net.", { todo: true });
test("29.2-T8: Given a Fannie Mae mandatory commitment of $4,000,000 at 101.250 expiring Mon Dec 7, 2026 with $3,600,000 expected deliverable and a live price of 102.250 on Fri Dec 4, then the package prices a $300,000 partial pair-off at `fee_cents = 300,000` and a 10-day extension of $400,000 at `fee_cents = 62,500`, recommends the extension when both late loans are at stage `cd_delivered`, and requires an `officer` decision before 5:00 p.m. ET Dec 7; with a live price of 100.250 the pair-off row shows `cash_back_cents = 300,000`.", { todo: true });
test("29.2-T9: Given the September cohort of 118 locks with 21 fallouts, when the monthly review runs on the 3rd business day of October (Mon Oct 5, 2026), then realized pull-through 82.2% is compared with the predicted 80.5%, no recalibration is proposed, and the fallout reasons are published to 21.4; given a cohort realized at 68% against 80.5%, a recalibration proposal opens an `officer` escalation and 31.2 review, and hedge ratios move to the conservative band edge until approved.", { todo: true });
test("29.2-T10: Given `execution.mandatory_enabled=false`, when any tool attempts `prepareTradePackage` or `requestMandatoryCommitment`, then the call is refused and logged; the daily position and MTM still run.", { todo: true });
test("29.2-T11: Given a lock executed Wed Oct 7, 2026 that remains uncommitted (PE\u2013WL outage), then `SM_UNCOMMITTED_POSITION_5BD` is due Wed Oct 14, 2026 (Oct 8, 9, 13, 14 \u2014 Mon Oct 12 Columbus Day is a SIFMA close) and breaches sev 2 to the `officer` if still uncommitted.", { todo: true });
test("29.2-T12: Given the 5:00 p.m. ET mark completes at 5:20 p.m. ET Mon Nov 2, then the GL export file for the partner exists by 7:00 p.m. ET with `irlc_fv`, `hfs_fv`, `hedge_fv`, `net_fv`, `day_change` and the price sources; a rerun with the same snapshot and price ids reproduces identical numbers.", { todo: true });
test("29.2-T13: Given the partner's `hedge_policies.review_due_on = 2027-10-01` and no new version by then, then `SM_HEDGE_POLICY_REVIEW_1Y` breaches and new locks are excluded from the hedge program (committed best efforts) until a version is approved.", { todo: true });
