// 29.3 Delivery data preparation and pre-delivery validation (ULDD, Special Feature Codes, UCD/UCDP/DU identifiers, MI data, EarlyCheck)
// spec/sections/29-secondary-marketing-and-delivery-to-fannie-mae-whole-loan-se/29-3-delivery-data-preparation-and-pre-delivery-validation-uldd-s.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("29.3-T1: Given the refinance fixture funded Thu Nov 12, 2026 with every prerequisite present, when the `secondary` agent runs, then a ULDD Phase 5 (5.2.0) file is built Fri Nov 13 with SID 322 = the final DU casefile ID, SID 82 a 10-character Doc File ID beginning with \"2\", SID 376 blank, SID 429 = `NoMIBasedOnOriginalLTV`, SID 311 = 2026-10-07, SID 642 = the SM payee code, SID 650.1 = SM's warehouse-lender identifier, SFCs {127, 007, 861, 180}, and `SM_O103_ULDD_BUILD_SLA_1BD` is satisfied.", { todo: true });
test("29.3-T2: Given build 1 returns an EarlyCheck fatal edit on SID 429, when the agent derives `NoMIBasedOnOriginalLTV` from `mi_certificates` (no row) and base LTV 70.00%, then build 2 is created, EarlyCheck run 2 is `clean = true`, both runs are retained, and `delivery_packages.uldd_sha256` equals the SHA-256 of build 2's bytes.", { todo: true });
test("29.3-T3: Given `ucd_submissions.casefile_id_ucd` \u2260 `du_casefiles.casefile_id` (UCD submitted before the DU casefile existed and UCD assigned its own ID), then `FNMA_ULDD_IDENTIFIER_CONSISTENCY_GATE` fails with `delivery.identifier.mismatch.detected{identifier=casefile}`, no ULDD is built, and 25.2 receives a resubmission request.", { todo: true });
test("29.3-T4: Given `applications.score_model = vantagescore_4` for both borrowers, then SFC 067 is included and SID 251.1 reflects the VantageScore 4.0 category; given `score_model` differs between borrowers, then `FNMA_LL_2026_06_SFC_067_CONSISTENCY_GATE` refuses the build.", { todo: true });
test("29.3-T5: Given a value-acceptance loan with the DU offer dated Wed Jul 8, 2026 and note date Fri Nov 6, 2026 (offer 3 months 29 days old), then SID 376 = `ValueAcceptance`, SFC 801 is included, SID 82 is blank and the gate opens; given the offer dated Mon Jul 6, 2026 (four months exceeded on Nov 6), then `FNMA_B4_1_4_10_VALUE_ACCEPTANCE_SFC_GATE` fails and 24.1 is notified.", { todo: true });
test("29.3-T6: Given an eNote closing (RON) registered on the eRegistry within one business day, then `enote_indicator = true`, SFC 508 and SFC 861 are included, SID 401 carries the MIN, and the package freezes without any custodian FIN dependency for the note (29.4 handles the eVault path).", { todo: true });
test("29.3-T7: Given twelve candidate SFCs, then `FNMA_C1_2_02_SFC_COMPLETENESS_GATE` fails, an `officer` escalation is opened with the candidate list and rule references, and no code is dropped automatically.", { todo: true });
test("29.3-T8: Given a package frozen Fri Nov 13 and a corrected CD delivered Tue Nov 17 before the operator import, then `delivery.package.superseded{reason=cd_corrected}` fires, 29.4's operator task is cancelled, and a new package is frozen only after `ucd.accepted{is_final}` for CD v3.", { todo: true });
test("29.3-T9: Given the EarlyCheck DI endpoint returns no result within 60 minutes, then a `fnma_portal_operator` task is opened with the same file (hash shown), the UI export is attached as `channel = ui`, and the gate evaluates the hash of the file actually run.", { todo: true });
test("29.3-T10: Given the purchase fixture (Columbus) with MI activation confirmed Thu Nov 19, 2026 09:10 ET, then SID 412 = `4812093` (no leading zeros), coverage 25.00, SID 429 blank, SFC 900 present, and the freeze is timestamped after `mi.activated`.", { todo: true });
test("29.3-T11: Given a warning edit on the standardized address, when the agent accepts EarlyCheck's standardized output, then `properties` is updated with a `source = earlycheck_standardization` audit row and the `delivery_edits.resolution = data_corrected`; given the warning is a DU Compare value difference of $5,000, then the resolution must be `source_corrected_upstream` via 23.1 \u2014 a bypass is refused.", { todo: true });
test("29.3-T12: Given a lock extended on Mon Nov 2 without a rate change, then SID 311 remains 2026-10-07 and equals UCD 3.038; given the extension changed the rate, then both carry 2026-11-02 (25.2 must have submitted the UCD with that date).", { todo: true });
