// 29.4 Loan Delivery submission, custodian certification, purchase, purchase advice reconciliation, and post-delivery corrections/remedies
// spec/sections/29-secondary-marketing-and-delivery-to-fannie-mae-whole-loan-se/29-4-loan-delivery-submission-custodian-certification-purchase-pu.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("29.4-T1: Given the refinance fixture package frozen Fri Nov 13, 2026 10:05 MST, then an `import_and_submit` task is opened with `sla_due_at` = Mon Nov 16, 2026 15:00 MT, the instruction sheet shows the commitment number, payee code, Receiver Type \"Warehouse Lender\", Letter Type \"Bailee\" and Bailee Letter Name, and the task cannot be marked complete without the four evidence items and `hash_confirmed = true`.", { todo: true });
test("29.4-T2: Given the operator submits Mon Nov 16 13:31 ET and the carrier receives the package 15:40 MT the same day, then `delivery.submitted{fnma_loan_number}` is recorded with `submit_before_2100_et = true`, `FNMA_C2_2_02_SHIP_SAME_DAY_AS_SUBMIT` is satisfied, `expected_certification_date` = Tue Nov 17 and `expected_purchase_date` = Wed Nov 18.", { todo: true });
test("29.4-T3: Given the package is delivered Tue Nov 17 17:05 ET, then `received_by_0730_et = false`, the expectations are recomputed to certification Wed Nov 18 and purchase Thu Nov 19; given the custodian certifies Wed Nov 18 07:15 ET, then `purchase_ready_at = 2026-11-18`; given the Purchase Advice dated Thu Nov 19 arrives via the API on Fri Nov 20, then `purchase_date = 2026-11-19`, `acquisition_date = 2026-11-19`, `loan.purchased` is emitted once, and 27.2's `FNMA_C2_2_05_PPA_REQUEST_30` is due Sat Dec 19, 2026 (platform due-at Fri Dec 18).", { todo: true });
test("29.4-T4: Given first payment due Fri Jan 1, 2027 and no payment posted, then `lpi_due_date = 2026-12-01`, `FNMA_C2_2_DELIVERY_LPI_45` is due Fri Jan 15, 2027, `FNMA_B2_1_5_02_LOAN_AGE_6M_PURCHASE_READY` is due Wed Jun 30, 2027 (a Purchase Ready date of Thu Jul 1, 2027 breaches it) and `FNMA_B2_1_5_02_SEASONED_1Y_FLAG` fires Sat Jan 1, 2028 if unsold; given the Jan 1 installment posts on Mon Dec 28, 2026, then the LPI window moves to Mon Feb 15, 2027.", { todo: true });
test("29.4-T5: Given a commitment expiring Mon Dec 7, 2026, then `FNMA_C2_2_01_CUSTODIAN_RECEIPT_BEFORE_EXPIRY` is anchored on Sun Dec 6 and due Fri Dec 4 07:30 ET (rolled backward \u2014 no first-morning delivery on Sunday); given the package is delivered Tue Nov 17, the timer is satisfied; given instead a commitment expiring Fri Nov 20 (due Thu Nov 19 07:30 ET) and a freeze on Wed Nov 18 with expected receipt Fri Nov 20, then the agent requests an 29.1 extension before opening the operator task.", { todo: true });
test("29.4-T6: Given the custodian proposes a data revision (P&I 3,402.62 \u2192 3,420.62) and the signed note reads 3,402.62, then the agent prepares a **decline** with the note page reference within `SM_LD_DATA_REVISION_RESPONSE_1BD`; given the note reads 3,420.62 (ULDD wrong), then the agent prepares an **accept** (Qualified Cert), emits `delivery.edit.observed` to 29.3, and opens an 25.2/26.1 review of the CD/note consistency.", { todo: true });
test("29.4-T7: Given SM's warehouse org enters \"Supermortgage Warehouse Lending LLC\" while the bailee letterhead reads \"SUPERMORTGAGE WAREHOUSE LENDING, LLC\", then the platform's pre-check (byte comparison of `bailee_letter_name` to `bailee_letters.letterhead_text`) blocks the approval task; after correction the custodian's validation passes.", { todo: true });
test("29.4-T8: Given the eNote fixture (Columbus) with eDelivery at 11:02 ET and a Transfer of Control and Location request with `effective_date = 2026-11-19`, then `FNMA_C1_2_04_ENOTE_TRANSFER_SAME_DAY_GATE` opens, submission is permitted, auto-certification is observed the same day, and `expected_purchase_date` = Fri Nov 20, 2026; given a request with `effective_date = 2026-11-20`, the gate stays closed.", { todo: true });
test("29.4-T9: Given a Purchase Advice with net proceeds $564,503.33 and the platform's expected range $564,503.33\u2013$564,518.36 (day-count uncertainty), then the advice reconciles automatically and 27.2 receives `purchase_advice.reconciled{variance_cents=0}`; given net proceeds $563,803.33, then a component decomposition identifies an unexpected 0.125% LLPA line and the `officer` receives an adjustment-request package by Fri Nov 27, 2026 (within 30 days).", { todo: true });
test("29.4-T10: Given a fatal 3000-series commitment edit at import (commitment amount mismatch after a pair-off), then the operator task is returned `blocked{reason=commitment_edit}`, `delivery.edit.observed{fatal, prefix=numeric}` is emitted, 29.1 is notified, and no rebuild occurs in 29.3.", { todo: true });
test("29.4-T11: Given a post-purchase discovery on Mon Mar 8, 2027 that the delivered representative score should be 754 rather than 762, then a `post_purchase_adjustments` row is opened with `repricing_eligible = true` (acquisition Nov 19, 2026 + 18 months = May 19, 2028), the PPA .csv and evidence are prepared, and processing is expected by Mon Mar 22, 2027 (10 `business_days_fannie_et` from Mar 9); given an LLPA delta of \u2212$50, no draft is expected ($100 minimum).", { todo: true });
test("29.4-T12: Given the loan is delivered with SFC 127, SID 322 populated, the final DU findings showing income and employment validated with close-by date Mon Dec 7, 2026 and consummation Fri Nov 6, then `rep_warrant_relief{limited_waiver_du, income_validated, employment_validated}.delivered_with_conditions_met = true` and `status = eligible`; given Fannie Mae's relief report lists the loan, then `confirmed_by_fnma` with `fnma_report_id`; given a Fannie Mae QC finding of undisclosed employment change, then `lost` (28.2).", { todo: true });
test("29.4-T13: Given a repurchase demand paid by the partner on Thu Apr 15, 2027 (within 60 days of a Mon Feb 22 demand), then 29.4 requests the note release (Form 2009-equivalent) or the eNote Transfer of Control from Fannie Mae, and servicing 5.6 reports LAR action code 65 on the removal clock; the platform blocks any 27.1 re-advance unless the facility flag `warehouse.repurchase_advance` is on.", { todo: true });
test("29.4-T14: Given the Purchase Advice Sellers API returns no advice for two consecutive business days after `purchase_ready`, then a `fnma_portal_operator` task to download the Fannie Mae Connect Whole Loan Purchase Advice report is opened and `FNMA_C2_2_04_PURCHASE_EXPECTED_1BD` breach handling verifies payee code and commitment status.", { todo: true });
