/**
 * §29.4 timer overrides (process-owned; applied after every section's so they win the merge — see
 * src/domain/bankruptcy/timers-14-1.ts for the pattern). One `reg.override(code, { trigger?, satisfied | evaluator,
 * anchorField?, offset?, why })` per 29.4 registry row whose trigger/satisfied column names an event the platform
 * spells differently or a condition the column grammar drops; `why` quotes the spec. A code the servicing spec
 * (sections 1–19) owns is never overridden here — reference it. Wired by src/domain/timer-overrides.ts.
 *
 * The events named here are appended by src/domain/secondary/ops-29-4.ts (DeliveryService), 29.3's ops-29-3.ts
 * (`delivery.package.frozen{package_id, sha256, enote_indicator}`), 21.4's ops-21-4.ts (`lock.commitment.linked{expires_on}`),
 * 29.1's ops-29-1.ts (`commitment.closed_status.set{loan_age_due_on}`), 26.3/30.2 (`loan.funded{first_payment_date, lpi_due_date}`)
 * and 27.1's ops-27-1.ts (`warehouse.bailee_letter.released` / `warehouse.secured_party.released`). 27.2's
 * `FNMA_C2_2_05_PPA_REQUEST_30` and 29.1's `FNMA_C2_2_DELIVERY_COMMITMENT_EXPIRY` are referenced, never redefined; 27.2's
 * `ppa.requested{channel=lsdu}` / `ppa.resolved` spellings are emitted by ops-29-4.ts as the platform record until 27.2 lands.
 * Every 29.4 event carries `loanId` + `applicationId` and `source: "origination"`, so the rows arm only under origination context.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_29_4(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // Worked example A: freeze Fri Nov 13 10:05 MST → task due Mon Nov 16 15:00 MT (one business_days_creditor; the 15:00 MT clock lives in the parenthetical the grammar drops); the submit evidence closes it.
  o("SM_LOAN_DELIVERY_OPERATOR_SLA_1BD", { anchorField: "frozen_at", offset: "+1 business_days_creditor, 15:00 MT", satisfied: "`delivery.submitted`",
    why: "§29.4 timer table: deadline (internal) on `delivery.package.frozen` (29.3), anchor `frozen_at`, '+1 `business_days_creditor` (task due 15:00 MT so that the 9:00 p.m. ET data cutoff and same-day carrier pickup are met)', satisfied by `delivery.submitted` (DeliveryService.recordSubmission); breach 'sev 2 to ops lead; sev 1 if `FNMA_C2_2_01_CUSTODIAN_RECEIPT_BEFORE_EXPIRY` is within 2 BD'." });
  // R1: `loan.funded{lpi_due_date}` anchors the 45-day window (first payment − 1 month while nothing is posted: Dec 1, 2026 → Fri Jan 15, 2027); a posting re-anchors through DeliveryService.onPaymentPosted (`delivery.lpi.reanchored`).
  o("FNMA_C2_2_DELIVERY_LPI_45", { anchorField: "lpi_due_date", offset: "+45 calendar_days", satisfied: "`loan.purchased`",
    why: "§29.4 timer table: deadline on `loan.funded` ('re-anchored on every `payment.posted` before purchase'), anchor '`lpi_due_date` (= first payment date − 1 month while no payment has been made — see R1)', '+45 `calendar_days`' (C2-2-03: 'up to 45 days from the due date of the reported last paid installment'), satisfied by `loan.purchased` (DeliveryService.ingestPurchaseAdvice emits it once per loan); breach 'day 30: sev 2 `secondary` agent + 29.1; day 45: sev 1 `officer`'." });
  // B2-1.5-02 (29.4 owns; 29.1 references and arms it on its closed-status event with `loan_age_due_on` = last day of the sixth month counting the first-payment month as month one — Jan 1, 2027 → Wed Jun 30, 2027). Kept compatible with 29.1's override: same trigger and anchor; satisfied by the Purchase Ready observation (`purchase_ready_at ≤ due` — a Jul 1, 2027 Purchase Ready breaches).
  o("FNMA_B2_1_5_02_LOAN_AGE_6M_PURCHASE_READY", { trigger: "`commitment.closed_status.set`", anchorField: "loan_age_due_on", offset: "same day, 17:00 ET", satisfied: "`delivery.status.observed{loan_delivery_status=purchase_ready}`",
    why: "§29.4 timer table (governing definition): deadline on `loan.funded`, anchor `first_payment_date`, '+6 `calendar_months` minus one day = the last day of the sixth month counting the first-payment month as month one (B2-1.5-02: a whole loan in Purchase Ready status in May 2023 needs a first payment date no earlier than December 1, 2022)', satisfied by '`purchase_ready_at ≤ due`' = the `delivery.status.observed{loan_delivery_status=purchase_ready}` DeliveryService.recordCertification appends; the grammar has no 'minus one day', so the row anchors on the `loan_age_due_on` 29.1's `commitment.closed_status.set` computes from `loan.funded{first_payment_date}` (ops-29-1.ts loanAgeDueOn); breach 'ineligible on a flow basis → `officer`; 29.1 negotiated/bulk path' (recordCertification opens the sev 1 officer escalation)." });
  // B2-1.5-02 seasoned definition: the first-payment anniversary (Jan 1, 2027 → Sat Jan 1, 2028) — a flag, satisfied by a purchase before it.
  o("FNMA_B2_1_5_02_SEASONED_1Y_FLAG", { anchorField: "first_payment_date", offset: "+1 years", satisfied: "`loan.purchased`",
    why: "§29.4 timer table: deadline (flag) on `loan.funded`, anchor `first_payment_date`, '+1 year (`calendar_days` to the anniversary)' ('Seasoned loans are loans that are more than one year old from the first payment date to the loan purchase date'), satisfied by '`loan.purchased` before the anniversary'; breach 'loan is seasoned: B2-1.5-02 conditions (12-month delinquency test, value ≥ original value) must be evidenced before any later delivery' (seasonedCheck)." });
  // C2-2-01 / verification report item 14: `expires_on` − 1 business_days_fannie_et at first-morning delivery 07:30 ET (Mon Dec 7 → Fri Dec 4, 2026; the calendar-day anchor Sun Dec 6 cannot receive); 21.4's link event carries `expires_on`; the carrier delivery (or eDelivery's stand-in receipt) closes it.
  o("FNMA_C2_2_01_CUSTODIAN_RECEIPT_BEFORE_EXPIRY", { anchorField: "expires_on", offset: "−1 business_days_fannie_et, 07:30 ET", satisfied: "`custody.package.received`",
    why: "§29.4 timer table: deadline on `lock.commitment.linked` (21.4, on 29.1's `commitment.executed`), anchor `commitments.expires_on` (the event's `expires_on`), '−1 `business_days_fannie_et`, at first-morning delivery (platform target 07:30 ET) — C2-2-01 says the day prior to the expiration date; because the custodian cannot receive on a non-business day, the prior business day is the operative (earlier) reading', satisfied by '`custody.package.received` (or `custody_mode = pre_positioned_at_fcc` / eNote eDelivery)' — DeliveryService.recordReceipt / recordSubmission (eNote); breach 'sev 1 `officer`; 29.1 extension request' (receiptPlan requests the extension before the task opens)." });
  // C2-2-02: same calendar day as the data submission, carrier pickup 16:30 MT (open question 8); the tender with first-morning service closes it.
  o("FNMA_C2_2_02_SHIP_SAME_DAY_AS_SUBMIT", { anchorField: "submitted_at", offset: "0, 16:30 MT", satisfied: "`custody.package.shipped{first_morning_service=true}`",
    why: "§29.4 timer table: deadline on `delivery.submitted`, anchor '`submitted_at::date` (ET)', 'same calendar day, carrier pickup cutoff' (C2-2-02: the package 'submitted to its overnight carrier (with instructions for first morning delivery) the same day that the seller submits the loan data'), satisfied by '`custody.package.shipped{first_morning_service=true}` or pre-positioned evidence' (DeliveryService.recordShipment); breach 'sev 1 ops; expected purchase re-planned'." });
  // User Guide p. 64: receipt by 7:30 a.m. ET on the business day following an error-free (before 9:00 p.m. ET) transmission — an expectation, not an obligation.
  o("FNMA_LD_UG_CUSTODIAN_0730_ET_EXPECTATION", { anchorField: "data_day", offset: "next business_days_fannie_et at 07:30 ET", satisfied: "`custody.package.received{by_0730_et=true}`",
    why: "§29.4 timer table: deadline (expectation) on `delivery.submitted{submit_before_2100_et=true}`, anchor 'next `business_days_fannie_et` at 07:30 ET' after the data day the submission carries, offset 0, satisfied by `custody.package.received{by_0730_et=true}` (recordReceipt); breach 'not an obligation: `expected_purchase_date` recomputed as BD after actual receipt/certification; carrier claim logged' (recomputeOnReceipt; the received event carries carrier_claim)." });
  // Custodian cash SLA 4:00 p.m. EST: the receipt event carries the recomputed `expected_certification_date` (same business day if received by the cutoff, else the next) — the grammar has no conditional, so the row anchors on that field.
  o("FNMA_C2_2_04_CERTIFICATION_EXPECTED_1BD", { anchorField: "expected_certification_date", offset: "0, 16:00 ET", satisfied: "`custody.certified`",
    why: "§29.4 timer table: deadline (expectation) on `custody.package.received`, anchor 'receipt date', 'end of the same `business_days_fannie_et` if received by the custodian's cutoff, else +1 (custodian SLA 4:00 p.m. EST for cash)' — recomputeOnReceipt writes `expected_certification_date` on the received event (Tue Nov 17 17:05 ET → Wed Nov 18), satisfied by `custody.certified` (recordCertification); breach 'sev 2 `post-closing` agent contacts the custodian; document/data exception workflow'." });
  // C2-2-04 / User Guide p. 64: purchase on the business day following certification (Wed Nov 18 → Thu Nov 19).
  o("FNMA_C2_2_04_PURCHASE_EXPECTED_1BD", { anchorField: "certified_on", offset: "+1 business_days_fannie_et", satisfied: "`loan.purchased`",
    why: "§29.4 timer table: deadline (expectation) on `custody.certified`, anchor 'certification date' (`certified_on`), '+1 `business_days_fannie_et`', satisfied by `loan.purchased` (ingestPurchaseAdvice); breach 'sev 2: verify payee code active, no `purchase_error`, commitment valid; `fnma_portal_operator` check task' (DeliveryService.adviceLag opens purchase_expected_check and the Connect report download task — T14)." });
  // User Guide p. 42: 'Once error is resolved, 2nd submit required' — the second submit evidence is a `delivery.submitted{resubmit=true}`.
  o("SM_LD_PURCHASE_ERROR_RESUBMIT_1BD", { offset: "+1 business_days_creditor", satisfied: "`delivery.submitted{resubmit=true}`",
    why: "§29.4 timer table: deadline on `delivery.purchase_error.observed`, anchor 'observation', '+1 `business_days_creditor`', satisfied by 'second submit evidence' = `delivery.submitted{resubmit=true}` (recordSubmission with resubmit); breach 'sev 1'." });
  // R4: the custodian's revision notice opens the clock; the operator's accept/decline (prepared by the agent with the note page) closes it.
  o("SM_LD_DATA_REVISION_RESPONSE_1BD", { offset: "+1 business_days_creditor", satisfied: "`delivery.data_revision.responded`",
    why: "§29.4 timer table: deadline on `delivery.data_revision.received`, anchor 'receipt', '+1 `business_days_creditor`', satisfied by `delivery.data_revision.responded` (recordDataRevisionResponse); breach 'sev 2; certification stalls in Pending'." });
  // Warehouse Lender User Guide p. 9: 'A notification is sent to a warehouse lender each time a lender lists such warehouse lender in their wire instructions' — parsed into `wire.instruction.listed` (integrations); the SM-org approval with the Letter Name closes it.
  o("SM_WAREHOUSE_WIRE_APPROVAL_SLA_1BD", { trigger: "`wire.instruction.listed`", offset: "+1 business_days_creditor", satisfied: "`wire.instruction.approved`",
    why: "§29.4 timer table: deadline (internal; SM warehouse org) on 'warehouse-lender notification (listed in wire instructions)' = `wire.instruction.listed` (DeliveryService.wireListed — integrations: 'notifications by e-mail (parsed into `wire.instruction.listed` events)'), anchor 'notification', '+1 `business_days_creditor`', satisfied by '`wire.instruction.approved` with `bailee_letter_name`' (approveWarehouseWire); breach 'sev 1 — submission blocked'." });
  // C2-2-07: Form 482 changes take Fannie Mae 'three business days'; the code is active when the confirmation call-back and the Loan Delivery status say so.
  o("FNMA_C2_2_07_PAYEE_CODE_CHANGE_3BD", { trigger: "`form_482.submitted`", offset: "+3 business_days_fannie_et", satisfied: "`payee_code.activated`",
    why: "§29.4 timer table: deadline (expectation) on 'Form 482 submitted' = `form_482.submitted` (DeliveryService.form482), anchor 'submission', '+3 `business_days_fannie_et`' (C2-2-07: 'make the requested change within three business days'), satisfied by 'payee code active in Loan Delivery' = `payee_code.activated`; breach 'escalate to the Fannie Mae contact; no submission with an inactive code' (wireGate)." });
  // C2-2-03 (verification report item 15): telephone notice immediately, written confirmation 'within 24 hours of the breach' (clock hours) — the written confirmation closes the row.
  o("FNMA_C2_2_03_SECURITY_BREACH_CONFIRM_24H", { offset: "+24 hours", satisfied: "`fnma.breach.confirmed{written=true}`",
    why: "§29.4 timer table: deadline on `payee.security_breach.detected`, anchor 'detection time (ET)', 'immediate telephone notice to Fannie Mae Asset Acquisitions, and written confirmation of the call within 24 hours of the breach (clock hours)', satisfied by '`fnma.breach.notified{telephone}` and `fnma.breach.confirmed{written}`' — DeliveryService.securityBreach emits both; the written confirmation is the later, closing one; breach 'sev 1 → `officer` immediately; C2-2-03 makes the lender solely liable for transfers'." });
  // C2-2-03: a gate on accepting `loan.purchased` — SM's release effective no later than the purchase date; 27.2 emits the bailee release on proceeds receipt (27.1 defines it; eNote path `warehouse.secured_party.released`).
  o("FNMA_C2_2_03_WAREHOUSE_RELEASE_BY_ACQUISITION_GATE", { evaluator: "29.4.warehouseReleaseByAcquisition", satisfied: "`warehouse.bailee_letter.released`",
    why: "§29.4 timer table: not_before_gate on `loan.purchased` acceptance, trigger `delivery.submitted`, 'SM's release (bailee terms / Form 2004A / eNote Secured Party release and Transfer of Control) effective no later than `purchase_date`' (C2-2-03: 'any interest held by a warehouse lender must be released no later than the date Fannie Mae acquires the note'), satisfied by '`warehouse.bailee_letter.released` (paper; 27.1-defined, 27.2 emits) or `warehouse.secured_party.released` (eNote; 27.1) with `effective ≤ purchase_date`' — ops-29-4.ts warehouseReleaseGate; breach 'sev 1: the partner's rep would be breached — SM's `warehouse` agent releases on proceeds receipt the same day'." });
  // C1-2-04: eDelivery done and a Transfer of Control and Location request whose effective date is the request date (Master Servicer = SM Org ID); the request event closes the gate.
  o("FNMA_C1_2_04_ENOTE_TRANSFER_SAME_DAY_GATE", { evaluator: "29.4.enoteTransferSameDay", satisfied: "`enote.transfer_of_control.requested`",
    why: "§29.4 timer table: not_before_gate on `delivery.submitted` (eNote), trigger `delivery.package.frozen{enote_indicator=true}` (29.3), 'eDelivery completed; Transfer of Control and Location request with `effective_date = request_date`; Master Servicer field = SM Org ID' (C1-2-04: 'The transfer request must include an Effective Date of the same day as the request'), satisfied by `enote.transfer_of_control.requested` (DeliveryService.requestEnoteTransfer); breach 'submission held; eVault/eRegistry error handling' (recordSubmission refuses while the gate is closed — T8)." });
  // Document Certification transmits the Fannie Mae loan number; the custodian record evidencing it is captured as `custody.loan_number.recorded`.
  o("FNMA_C1_2_02_FNMA_LOAN_NUMBER_TO_CUSTODIAN_30", { anchorField: "certified_on", offset: "+30 calendar_days", satisfied: "`custody.loan_number.recorded`",
    why: "§29.4 timer table: deadline on `custody.certified`, anchor 'certification date', '+30 `calendar_days`', satisfied by 'custodian record shows the Fannie Mae loan number (Document Certification transmits it; evidence captured)' = `custody.loan_number.recorded` (DeliveryService.custodianLoanNumber); breach 'sev 2 `post-closing` agent sends the number'." });
  o("FNMA_C1_2_02_CUSTODIAN_LOAN_NUMBER_REQUEST_3BD", { trigger: "`custody.loan_number.requested`", offset: "+3 business_days_fannie_et", satisfied: "`custody.loan_number.responded`",
    why: "§29.4 timer table: deadline on 'custodian request received' = `custody.loan_number.requested` (the custodian's request for the Fannie Mae loan number, parsed from the notice), anchor 'request date', '+3 `business_days_fannie_et`', satisfied by 'response sent' = `custody.loan_number.responded`; breach 'sev 1'." });
  // C1-2-02: 18 months from the acquisition date (Nov 19, 2026 → May 19, 2028); an LLPA-relevant PPA filed before then keeps repricing.
  o("FNMA_C1_2_02_PPA_LLPA_REPRICING_18M", { anchorField: "acquisition_date", offset: "+18 months", satisfied: "`ppa.requested{llpa_relevant=true}`",
    why: "§29.4 timer table: deadline on `loan.purchased`, anchor `acquisition_date`, '+18 `calendar_months`' (C1-2-02: 'must submit data corrections within 18 months of the loan's acquisition date to be considered for repricing of loan-level price adjustments'), satisfied by 'any LLPA-relevant correction submitted before due' = `ppa.requested{llpa_relevant=true}` (DeliveryService.ppaStatus op=submitted, 27.2's spelling); breach 'corrections still required (no lookback for data) but repricing is lost — `officer` informed'." });
  // PPA Job Aid (4.29.26): 'standard processing 10 business days from initial submission through data correction'; the Connect notification report resolves it.
  o("FNMA_PPA_PROCESSING_10BD", { anchorField: "submitted_on", offset: "+10 business_days_fannie_et", satisfied: "`ppa.resolved`",
    why: "§29.4 timer table: deadline (expectation) on `ppa.requested{channel=lsdu}` (27.2's event; emitted by ops-29-4.ts ppaStatus as the platform record), anchor 'submission', '+10 `business_days_fannie_et` (LLPA draft/refund typically +5 BD)', satisfied by `ppa.resolved` (27.2; ppaStatus op=processed from the Post-Purchase Adjustment Notification report); breach 'follow-up with Fannie Mae; 27.2 accrual'." });
  // D2-1-02: 30 days after Fannie Mae notifies the lender of the data-validation selection (an earlier date on the LQC request wins — the request event carries `response_due_on`).
  o("FNMA_LQC_DATA_VALIDATION_RESPONSE_30", { trigger: "`lqc.data_validation.requested`", anchorField: "notified_on", offset: "+30 calendar_days", satisfied: "`lqc.data_validation.responded`",
    why: "§29.4 timer table: deadline on 'LQC data-validation request (Fannie Mae-initiated PPA)' = `lqc.data_validation.requested` (DeliveryService.lqc; 28.2 owns the case), anchor 'notification date', '+30 `calendar_days` — D2-1-02: documentation for an underwriting, servicing, or data validation review within 30 days after Fannie Mae notifies the lender', satisfied by 'response uploaded in LQC' = `lqc.data_validation.responded`; breach 'sev 1 `officer`; 28.2 case'." });
}
