/**
 * §29.1 timer overrides (process-owned; applied after every section's so they win the merge — see
 * src/domain/bankruptcy/timers-14-1.ts for the pattern). One `reg.override(code, { trigger?, satisfied | evaluator,
 * anchorField?, offset?, why })` per 29.1 registry row whose trigger/satisfied column names an event the platform
 * spells differently or a condition the column grammar drops; `why` quotes the spec. A code the servicing spec
 * (sections 1–19) owns is never overridden here — reference it. Wired by src/domain/timer-overrides.ts.
 *
 * The events named here are appended by src/domain/secondary/ops-29-1.ts (CommitmentService), 21.4's ops
 * (`lock.relocked`), 23.1 (`du.findings.received`), 26.3/30.2 (`loan.funded`), 29.4/30.1 (`loan.purchased`) and
 * src/app/escalations.ts (`escalation.created`). Every 29.1 event carries `applicationId` (best efforts) or a
 * `commitment` aggregate with `source: "origination"` (mandatory), so the rows arm only under origination context.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_29_1(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // Rule 7: 21.4 supplied the trigger spelling (`lock.relocked` is the key-data event it emits; renegotiation versions and float-downs go through the same
  // CommitmentService.keyDataChange); the row's anchor is the change instant's ET civil date, +1 Fannie Mae business day at 5:00 p.m. ET.
  o("FNMA_C2_1_2_03_KEY_DATA_CHANGE_1BD", { trigger: "`lock.relocked`", offset: "+1 business_days_fannie_et, 17:00 ET", satisfied: "`commitment.modified`",
    why: "§29.1 timer table (owned here; 21.4 references): trigger 'any change to loan amount, product, note rate, units, seller loan number or borrower/address on a committed/closed best-efforts commitment (`lock.relocked`, `lock.float_down.applied`, renegotiation version, 23.1/26.1 data changes)', anchor 'change timestamp converted to ET', '+1 `business_days_fannie_et`, due 5:00 p.m. ET (end of the standard committing window)', satisfied by '`commitment.modified` (API or UI)' — ops-29-1.ts modifyCommitment emits it; breach: sev 2 → partner `officer` and `compliance-sentinel` (CommitmentService.handleBreach)." });
  // Rule 2 / C2-1.2-03: the expiry instant is `expires_on` 5:00 p.m. ET; only the acquisition (`loan.purchased`) satisfies it — closed status leads to the auto-extension path (recordAutoExtension re-anchors on the new `expires_on`).
  o("FNMA_C2_1_2_02_BE_COMMITMENT_EXPIRY", { trigger: "`commitment.executed{type=best_efforts}`", anchorField: "expires_on", offset: "0 calendar_days, 17:00 ET", satisfied: "`loan.purchased`",
    why: "§29.1 timer table: deadline on `commitment.executed` (best efforts), anchor '`expires_on` 5:00 p.m. ET (as extended)', offset 0, satisfied by '`loan.purchased` before expiry; or `closed` status (→ auto-extension path); or an approved manual extension' — C2-1.2-03: 'the acquisition date is on or before the date upon which the commitment expires'; breach: not closed → `expired` (fallout; `dpa_exposure_until = expires_on + 30`), closed → PE–WL auto-extends 5 days (`commitment.extended{auto_5d}`) — CommitmentService.expire." });
  // Rule 10: a cap, not a clock — the evaluator refuses a manual extension that would bring cumulative manual days above 30 while the loan is not closed; closed status ends the cap's relevance (the 60-day auto-extension cap takes over).
  o("FNMA_C2_1_2_02_BE_EXTENSION_CAP_30", { trigger: "`commitment.executed{type=best_efforts}`", evaluator: "29.1.beExtensionCap", satisfied: "`commitment.closed_status.set`",
    why: "§29.1 timer table: not_before_gate (cap) on `commitment.executed`, anchor `original_expires_on`, 'manual extensions cumulative ≤ 30 `calendar_days` while not closed' (C2-1.2-02: 'up to a maximum of 30 days for a fee'); breach: '`requestExtension` refused beyond the cap' — ops-29-1.ts requestExtension throws FNMA_C2_1_2_02_BE_EXTENSION_CAP_30 (T8); the row closes when the loan is placed in closed status." });
  // Rule 10 / C2-1.2-02: `original_expires_on + 60 calendar_days` (Dec 7, 2026 → Fri Feb 5, 2027); the pair-off decision is escalated 5 business days earlier by the expiring sweep.
  o("FNMA_C2_1_2_02_BE_CLOSED_AUTOEXT_CAP_60", { trigger: "`commitment.closed_status.set`", anchorField: "original_expires_on", offset: "+60 calendar_days, 17:00 ET", satisfied: "`loan.purchased`",
    why: "§29.1 timer table: deadline on `commitment.closed_status.set`, anchor `original_expires_on`, '+60 `calendar_days`' ('a maximum of 60 calendar days from the original expiration date'), satisfied by `loan.purchased`; breach: 'PE–WL auto pair-off with fee; `commitment.paired_off{automatic}`; sev 1 → `officer`; 27.2/27.1 informed' — recordPairOff(kind=automatic) from the fee draft; handleBreach opens the sev 1 officer escalation." });
  // Rule 9: the disbursement (not consummation) starts the clock — `loan.funded{disbursement_date}` (26.3/30.2); +1 Fannie Mae business day at 5:00 p.m. ET (Thu Nov 12 → Fri Nov 13, 2026).
  o("FNMA_PEWL_CLOSED_STATUS_1BD", { trigger: "`loan.funded`", anchorField: "disbursement_date", offset: "+1 business_days_fannie_et, 17:00 ET", satisfied: "`commitment.closed_status.set`",
    why: "§29.1 timer table: deadline on `loan.funded` (26.3; disbursement), anchor `disbursement_date`, '+1 `business_days_fannie_et`, 5:00 p.m. ET' (PE–WL FAQ: 'place a loan into closed status within one business day of the borrower(s) receiving loan funding'), satisfied by `commitment.closed_status.set` (ops-29-1.ts setClosedStatus); breach: 'sev 2; operator task; the loan cannot appear in Loan Delivery until closed' (handleBreach)." });
  // C2-1.2-03: a window gate — the commit under `du` must execute ≤ 60 calendar days after the Approve/Eligible (23.1's `du.findings.received{recommendation=approve_eligible}` anchors it); the evaluator refuses the stale casefile (T10).
  o("FNMA_C2_1_2_03_DU_APPROVE_60_GATE", { trigger: "`du.findings.received{recommendation=approve_eligible}`", anchorField: "last_updated_at", evaluator: "29.1.duApproveWindow", satisfied: "`commitment.executed{underwriting_method=du}`",
    why: "§29.1 timer table: not_before_gate (window) on `du.findings.received{approve_eligible}`, anchor `du_recommendation_at`, 'commitment must execute ≤ 60 `calendar_days` after it (`underwriting_method=du`)' (C2-1.2-03: 'no earlier than 60 days prior to commitment'), satisfied by '`commitment.executed` inside the window'; breach: 'commit refused under `du`; agent resubmits DU (23.1) or commits with `other`' — ops-29-1.ts duApproveWindow / CommitmentService.guard." });
  // Rule 8: the 30-day duplicate window opens on fallout (or expiry — `expire` emits `commitment.expired` with the same fields); the evaluator refuses a recommit for the same borrower + property inside it unless `dpa_acknowledged=true` (T5).
  o("FNMA_PEWL_DPA_WINDOW_30", { trigger: "`commitment.fallout.recorded`", anchorField: "fallout_on", evaluator: "29.1.dpaWindow", satisfied: "`commitment.executed`",
    why: "§29.1 timer table: not_before_gate (window) on `commitment.fallout.recorded` / `commitment.expired`, anchor 'fallout or expiration date (the earlier)', '+30 `calendar_days`', 'window elapses'; breach: 'a recommit for the same borrower + property inside the window is refused unless `dpa_acknowledged=true` with the DPA/worse-case price accepted … and `officer` approval above threshold' (C2-1.2-02 duplicate commitment price adjustment) — ops-29-1.ts dpaWindowGate; a later `commitment.executed` on the lineage closes the window row." });
  // Rule 4: never commit on a stale price — the API quote's `expires_at` (FNMA_PEWL_QUOTE_ID_WINDOW, 20.4) or the 60-second UI acceptance window; the evaluator asserts it at the commit call.
  o("FNMA_PEWL_COMMIT_ACCEPT_60S", { trigger: "`commitment.priced`", anchorField: "quoted_at", evaluator: "29.1.commitAcceptWindow", satisfied: "`commitment.executed`",
    why: "§29.1 timer table: not_before_gate (window) on 'price returned (API quote / UI price)' = `commitment.priced{quote_id_fnma, price, expires_at}` (ops-29-1.ts priceForCommitment), anchor 'quote timestamp', '60 seconds (UI) / `FNMA_PEWL_QUOTE_ID_WINDOW` (API)', satisfied by `commitment.executed`; breach: 're-price; never commit on a stale price' — commitAcceptWindowGate; CommitmentService.commitBestEfforts rejects `quote_expired`." });
  // Rule 14: the $200M day limit is a gate over the ET-day aggregate carried on `commitment.requested{executed_today_cents, amount_cents}`; the refused commit is queued and the officer contacts the Sales Desk (T15).
  o("FNMA_C2_1_1_03_DAILY_LIMIT_200M_GATE", { trigger: "`commitment.requested`", evaluator: "29.1.dailyLimit", satisfied: "`commitment.executed`",
    why: "§29.1 timer table: not_before_gate on 'every `commitment.requested`', anchor 'aggregate `amount_cents` executed today (ET) across the partner's seller number', '≤ $200,000,000 (ET day)' (C2-1.1-03: 'may not exceed $200 million in aggregate commitment volume per day'); breach: 'queue to next day or `officer` contacts the Sales Desk for approval' — ops-29-1.ts dailyLimitCheck / CommitmentService.guard." });
  // Rule 12: mandatory expiry at 5:00 p.m. ET on `expires_on`; fulfilled when the purchased amount lands inside the tolerance band (`commitment.fulfilled`), or a manual pair-off/extension is requested before the cut-off.
  o("FNMA_C2_1_1_03_MAND_COMMITMENT_EXPIRY", { trigger: "`commitment.executed{type=mandatory}`", anchorField: "expires_on", offset: "0 calendar_days, 17:00 ET", satisfied: "`commitment.fulfilled`",
    why: "§29.1 timer table: deadline on mandatory `commitment.executed`, anchor '`expires_on` 5:00 p.m. ET', offset 0, satisfied by 'purchased amount within tolerance before expiry, or manual pair-off/extension requested before 5:00 p.m. ET on the expiration date' (PE–WL Mandatory Committing: 'All pair-offs and extensions should be requested no later than … 5:00 p.m. ET on the commitment expiration date') — recordPurchase emits `commitment.fulfilled` inside the band; breach: 'PE–WL auto 1-day/5-day extension (fee) or auto pair-off (fee); sev 1 → `officer`; 29.2 position updated' (handleBreach)." });
  // C2-1.1-04: ≤ 30 cumulative days of extensions on a mandatory commitment — a cap evaluated at `requestExtension`.
  o("FNMA_C2_1_1_04_MAND_EXTENSION_CAP_30", { trigger: "`commitment.executed{type=mandatory}`", evaluator: "29.1.mandExtensionCap", satisfied: "`commitment.fulfilled`",
    why: "§29.1 timer table: not_before_gate (cap) on mandatory `commitment.executed`, anchor `original_expires_on`, '≤ 30 `calendar_days` cumulative' (C2-1.1-04: 'as long as the total extension period is no longer than 30 days'); breach: 'extension refused; pair-off economics run (29.2)' — ops-29-1.ts requestExtension throws FNMA_C2_1_1_04_MAND_EXTENSION_CAP_30." });
  // C2-2-01 good delivery: [original − max($10,000, 2.5%), original + max($10,000, 2.5%)], over-delivery ≤ 25% — evaluated over `original_amount_cents` / `purchased_cents`.
  o("FNMA_PEWL_MAND_TOLERANCE_GATE", { trigger: "`commitment.executed{type=mandatory}`", anchorField: "original_amount_cents", evaluator: "29.1.mandToleranceGate", satisfied: "`commitment.fulfilled`",
    why: "§29.1 timer table: not_before_gate on 'mandatory delivery planning (29.2/29.4)' — armed with the mandatory `commitment.executed{original_amount_cents, tolerance_low_cents, tolerance_high_cents}`, 'good delivery within [original − max($10,000, 2.5%), original + max($10,000, 2.5%)]; over-delivery ≤ 25% of original' (C2-2-01 'Whole Loan Good Delivery Amounts'), satisfied by 'purchased amount inside the band at expiry' = `commitment.fulfilled`; breach: 'shortfall → pair-off request before expiry (fee/cash back); over-delivery request (fee/cash back)' — mandatoryTolerance / preparePairOffPackage / recordOverDelivery." });
  // Every UI-only step is a `fnma_portal_operator` escalation: `escalation.created{kind=human_portal_task, task=fnma_portal_commitment_task}` (src/app/escalations.ts spreads the payload); +4 clock hours; the confirmation the operator attaches closes it (`commitment.operator_task.completed`).
  o("SM_PORTAL_OPERATOR_COMMITMENT_TASK_4H", { trigger: "`escalation.created{kind=human_portal_task, task=fnma_portal_commitment_task}`", offset: "+4 hours", satisfied: "`commitment.operator_task.completed`",
    why: "§29.1 timer table: deadline (escalation SLA) on '`escalation.opened{fnma_portal_commitment_task}`' — the platform spells it `escalation.created{kind=human_portal_task, task=fnma_portal_commitment_task}` (CommitmentService.operatorTask), anchor `opened_at`, '+4 clock hours inside PE–WL hours; expiring-today tasks +1 hour' (the package carries `sla_hours`), satisfied by 'task completed with confirmation attached' = `commitment.operator_task.completed` (recordOperatorConfirmation); breach: 're-queue to the backup operator; sev 2; expiring-today tasks page the partner `officer`' (handleBreach)." });
  // Reference to 29.4's loan-age rule (B2-1.5-02): the last day of the sixth month counting the first-payment month as month one — `commitment.closed_status.set{first_payment_date, loan_age_due_on}` carries the computed date (ops-29-1.ts loanAgeDueOn: Jan 1, 2027 → Wed Jun 30, 2027); 29.4's own override, applied after this one, governs once built.
  o("FNMA_B2_1_5_02_LOAN_AGE_6M_PURCHASE_READY", { trigger: "`commitment.closed_status.set`", anchorField: "loan_age_due_on", offset: "same day, 17:00 ET", satisfied: "`loan.purchased`",
    why: "§29.1 timer table (owned by 29.4; reference): trigger `loan.funded`, anchor `first_payment_date`, 'per 29.4 (+6 `calendar_months` minus one day — the last day of the sixth month counting the first-payment month as month one, per B2-1.5-02's example; Purchase Ready ≤ due)'; the grammar has no 'minus one day', so the row anchors on `loan_age_due_on` that 29.1's closed-status event computes from `loan.funded{first_payment_date}`; satisfied by `loan.purchased` (a whole loan purchased is Purchase Ready ≤ due); breach: 'commitment planning never sets `expires_on` beyond this date; flow ineligibility → `officer`' (commitmentExpiration caps at the date)." });
  // The composite delivery gate 29.3/29.4 consult before `freezePackage` / `submitDelivery`: open while today < expires_on and the custodian can still receive by the first morning delivery of expires_on − 1 business day (C2-2-01).
  o("FNMA_C2_2_DELIVERY_COMMITMENT_EXPIRY", { trigger: "`commitment.executed`", anchorField: "expires_on", evaluator: "29.1.deliveryCommitmentGate", satisfied: "`loan.purchased`",
    why: "§29.1 timer table: not_before_gate (composite) on `commitment.executed`, anchor 'the open commitment's current `expires_on`', 'open while `today_et < expires_on` and the custodian can still receive documents by the first morning delivery of `expires_on − 1 business_days_fannie_et` (C2-2-01; 29.4 computes the shipping cut-off)', satisfied by `loan.purchased`; breach: 'gate closed → 29.4 may not submit against this commitment; `secondary` extends (≤ caps) or re-commits; sev 2 → `officer`' — ops-29-1.ts deliveryCommitmentGate; handleBreach." });
}
