/**
 * §15.3 timer overrides: for every 15.3 registry row whose trigger / "Satisfied by" column is prose, a
 * `reg.override(code, { trigger?, anchorField?, offset?, satisfied | evaluator, why })` (pattern: src/domain/foreclosure/timers.ts).
 * Called from this section's timers.ts after the section-level overrides, so these win the merge.
 *
 * Who emits what — every event below is appended by a 15.3 code path (src/app/tools/section15-3.ts over src/domain/reo/ops-15-3.ts):
 *   routeMiClaim         mi_claims.opened{claim_anchor_date, claim_filing_deadline, late_deny_at, supplemental_due_at} (the liquidation fact opens the
 *                        claim before the identity check) · mi_claims.data_mismatch.detected{detection_date} · mi_claims.data_correction.submitted ·
 *                        mi_claims.routed{route, claim_filing_deadline, claim_anchor_date, direct_file_anchor_date} · claim.milestone.reached{mi_insured=true,
 *                        milestone_date} (the F-1-06 expense anchor when it moves to the redemption expiry / docket entry — 15.2's FNMA_F106_MI_EXPENSE_FINAL_30 row)
 *   assembleMiPackage    mi_claims.package.assembled · mi.claim.supplemental.closed{result=none_needed}
 *   openPortalTask       (op=record_result) mi_claims.package.uploaded{route, kind, mandatory_complete} · mi.claim.supplemental.closed{result=filed} ·
 *                        micp.document_request.fulfilled · mi.claim.appeal.filed · micp.message.replied
 *   fileDirectClaim      mi.claim.filed{route=servicer_direct, followup_from} · mi.claim.acknowledged{route} · mi.claim.followup.logged{route, followup_from} ·
 *                        mi.claim.insurer_response.logged · mi.claim.perfected{perfected_at}
 *   trackDocRequests     micp.document_request.observed{micp_due_at} · micp.document_request.fulfilled · mi.claim.filed{route=fnma_micp} · mi.claim.perfected
 *   reconcileEob         mi.claim.eob_received · mi.claim.decision.received{outcome, notice_date} · mi.claim.benefit_received{payee, received_on} ·
 *                        remittance.special.drafted{kind=mi_benefit, code} · (op=record_remittance) remittance.special.settled{code, kind=mi_benefit}
 *   scoreCurtailmentRisk mi.default.started{first_unpaid_due_date, second_missed_payment_due, report_due_on} (the daily monitor observing the second
 *                        consecutive missed payment unpaid — master policy §53) · mi.default_report.accepted{kind∈{nod, monthly_status}, report_due_on}
 *                        (ingestion of the insurer's default-report acceptances) · foreclosure.sale.scheduled{mi_insured=true, scheduled_sale_date}
 *                        (ingestion of 13.x's scheduled sale for an MI-insured loan) · mi_curtailment_risk.projected
 *   draftAppeal          mi.claim.appeal.filed · attributeShortfall mi.claim.shortfall.attributed
 *
 * Recurring rows (SM_MI_SETTLEMENT_FOLLOWUP_7, MI_MP_STATUS_MONTHLY_25TH): the kernel engine re-arms a recurring row inside the loop that
 * satisfies it (src/kernel/timers/engine.ts onEvent — the re-armed instance is visited in the same pass, matches the same event and re-arms
 * again without end), so the 15.3 tools close the open instance themselves before appending the satisfying event and re-arm the next cycle
 * from it explicitly (the pattern src/app/tools/section19-3.ts uses). The patterns below are what those events carry.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_15_3(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // ---- routing / data accuracy (E-4.5-01) — routeMiClaim
  o("FNMA_E4501_MICP_DATA_CORRECTION_1BD", { trigger: "`mi_claims.data_mismatch.detected`", anchorField: "detection_date", offset: "+1 business_days_fannie_et", satisfied: "`mi_claims.data_correction.submitted`", why: "§15.3 timer table: MICP/REOgram MI data mismatch detected (routeMiClaim's three-way identity check) → 'correction message/edit submitted' within 1 BD — routeMiClaim{correction_submitted_on} emits it and re-evaluates the routing (E-4.5-01; T11: found Oct 7 → correction by Oct 8, 2027)." });
  // ---- documents to MICP (F-1-06 'no later than 10 business days prior to the required claim filing deadline') — openPortalTask{op=record_result}
  o("FNMA_F106_MICP_DOCS_10BD", { trigger: "`mi_claims.routed{route=fnma_micp}`", anchorField: "claim_filing_deadline", satisfied: "`mi_claims.package.uploaded{route=fnma_micp, kind=initial, mandatory_complete=true}`", why: "§15.3 timer table: `mi_claims.routed = fnma_micp` → 'all mandatory mi_claim_documents uploaded' — the operator's upload result recorded by openPortalTask{op=record_result, task_type=micp.docs.upload} for the initial package with every mandatory kind present; a supplemental upload (kind=supplemental) does not close it (F-1-06; T1: Nov 19, 2027)." });
  o("SM_MICP_DOCS_TARGET_15", { trigger: "`mi_claims.routed{route=fnma_micp}`", anchorField: "claim_anchor_date", satisfied: "`mi_claims.package.uploaded{route=fnma_micp, kind=initial}`", why: "§15.3 timer table: 'package uploaded' — the internal 15-day target closes on the same recorded initial-package upload; it is meaningful only on the MICP route, so it arms with the fnma_micp routing rather than the bare liquidation fact (T1: Oct 20, 2027)." });
  o("SM_MICP_DOC_REQUEST_DUE", { trigger: "`micp.document_request.observed`", anchorField: "micp_due_at", offset: "0", satisfied: "`micp.document_request.fulfilled`", why: "§15.3 timer table: MICP document request observed (trackDocRequests, anchor = earlier of the Due Date and 5 BD) → 'uploaded and submitted' — trackDocRequests / openPortalTask{op=record_result, task_type=micp.doc_request.respond} record the upload against the request id; a late upload satisfies late and keeps the sev-1 (T6)." });
  // ---- direct filing (non-participants; F-1-06) — fileDirectClaim
  o("FNMA_F106_MI_DIRECT_FILE_30", { trigger: "`mi_claims.routed{route=servicer_direct}`", anchorField: "direct_file_anchor_date", satisfied: "`mi.claim.acknowledged{route=servicer_direct}`", why: "§15.3 timer table: 'insurer acknowledgment' of the Claim for Loss within 30 days of the settlement / 311-357 remittance / redemption expiry / docket entry — the adapter's acknowledgment or the operator's result recorded by fileDirectClaim{op=record_acknowledgment} (F-1-06; T2 Nov 4, 2027; T3 May 5, 2028 — the anchor moves, the master-policy deadline does not)." });
  o("SM_MI_SETTLEMENT_FOLLOWUP_7", { trigger: "`mi.claim.filed{route=servicer_direct}`", anchorField: "followup_from", offset: "every 7 calendar_days", satisfied: "`mi.claim.followup.logged{route=servicer_direct}`", why: "§15.3 timer table: filed (direct) → 'follow-up logged' every 7 calendar days until paid — fileDirectClaim{op=followup} closes the open instance as satisfied, appends the log (followup_from = the log date) and re-arms the next cycle from it; reconcileEob cancels the open cycle when the benefit is received ('until paid'; F-1-06 'Ensuring Timely Settlement'; T2). The engine's own recurring re-arm is not used — see the file header." });
  // ---- master-policy clocks from the liquidation fact (§64(b): 'regardless of' confirmation; §65; §62(f)) — routeMiClaim opens the claim before the identity check, so a T11 hold does not stop them
  o("MI_MP_CLAIM_FILE_60", { trigger: "`mi_claims.opened`", anchorField: "claim_filing_deadline", offset: "0", satisfied: "`mi.claim.filed`", why: "§15.3 timer table: liquidation fact → `claim_filing_days` calendar days (60 default, per `mi_master_policy_terms`) from `claim_anchor_date` — `mi_claims.opened` carries the computed deadline; 'mi.claim.filed observed' on either route (fileDirectClaim on the insurer's acknowledgment; trackDocRequests when filed_by_fnma is observed in MICP) closes it (master policy §64(b); T1: Dec 4, 2027)." });
  o("MI_MP_LATE_DENY_120", { trigger: "`mi_claims.opened`", anchorField: "late_deny_at", offset: "0", satisfied: "`mi.claim.filed`", why: "§15.3 timer table: not_after claim_anchor_date + `late_deny_days` (120 default, per terms) — `mi_claims.opened` carries `late_deny_at`; no satisfying event in the spec ('—'): a claim filed before it cannot be denied as late (master policy §65), so the filing observed on either route closes the watch; past it → `officer`." });
  o("MI_MP_SUPPLEMENTAL_90", { trigger: "`mi_claims.opened`", anchorField: "supplemental_due_at", offset: "0", satisfied: "`mi.claim.supplemental.closed{result∈{filed, none_needed}}`", why: "§15.3 timer table: liquidation fact → 'supplemental filed (or none needed)' within `supplemental_days` (90 default, per terms) of the anchor — the recorded supplemental upload (openPortalTask{op=record_result}) or assembleMiPackage{kind=supplemental} finding no post-claim advance once the advances ledger is swept through upload-by (master policy §62(f); T10 — upload by supplemental_due_at − 10 BD)." });
  o("MI_MP_SETTLEMENT_60", { trigger: "`mi.claim.perfected`", anchorField: "perfected_at", offset: "+60 calendar_days", satisfied: "`mi.claim.benefit_received{payee∈{fnma, servicer}}`", why: "§15.3 timer table: `perfected_at` (fileDirectClaim{op=record_response} / trackDocRequests record the perfection) → 'benefit paid' within the Claim Settlement Period — reconcileEob emits the receipt for either payee (Fannie Mae: record the EOB and close; servicer: remit); unpaid at settlement_due_at → officer with the perfected date, follow-up log and insurer responses (T8; A1-3-02)." });
  // ---- default reporting to the insurer (master policy §53) and the 36-month cap — the daily curtailment monitor (scoreCurtailmentRisk) is the 15.3 code path
  o("MI_MP_NOD_25TH", { trigger: "`mi.default.started`", anchorField: "second_missed_payment_due", offset: "25th", satisfied: "`mi.default_report.accepted{kind=nod}`", why: "§15.3 timer table: 'second consecutive missed payment unpaid' → insurer NOD accepted by the 25th of that month (master policy §53). The platform spells the trigger `mi.default.started`: the daily monitor appends it when it first observes the second consecutive missed payment unpaid on an MI-insured loan (no process emits a `loan.delinquency.day_reached` fact; 11.1's window events carry no missed-payment count); the insurer's acceptance record ingested by the same monitor satisfies it — late → satisfied_late, sev-1, and the interest between the 25th and the acceptance is projected as excluded (T4: Jan 30 vs Jan 25 → 5 days, servicer_caused)." });
  o("MI_MP_STATUS_MONTHLY_25TH", { trigger: "`mi.default.started`", anchorField: "report_due_on", offset: "monthly", satisfied: "`mi.default_report.accepted{kind=monthly_status}`", why: "§15.3 timer table: loan in default → 'status report accepted' monthly by the 25th (master policy §53 monthly updates). Anchored on the NOD's due date (`report_due_on`) so the first update falls due one month later; each accepted monthly status carries its own `report_due_on` and the monitor re-arms the next cycle from it (see the file header on recurring rows), cancelling instead when the loan leaves default; a missing report for the current cycle raises the curtailment score (rule 5 'monthly status gaps')." });
  o("MI_MP_INTEREST_CAP_36M", { trigger: "`mi.default.started`", anchorField: "first_unpaid_due_date", evaluator: "15.3.interestWithinCap", why: "§15.3 timer table: not_after, default date → first unpaid due date + 36 months, 'Satisfied by —' (no event closes it; interest keeps accruing through a redemption period — edge cases). Evaluator-backed like 15.2's FNMA_F105_ESCROW_ADV_CUTOFF_14: computeShadowClaim asserts `15.3.interestWithinCap` on the claim's interest-to date and scoreCurtailmentRisk on the accrual as of the run; past it every month is an uninsured loss and the officer briefing is raised at 30 months (T12)." });
  o("SM_MI_PREMIUM_PAID_THROUGH_GATE", { trigger: "`foreclosure.sale.scheduled{mi_insured=true}`", evaluator: "15.3.premiumPaidThroughLiquidationMonth", why: "§15.3 timer table: not_before_gate on the scheduled sale (13.x) — `mi_policies.premium_paid_through ≥ liquidation month`. The daily monitor ingests 13.x's scheduled sale for an MI-insured loan (`foreclosure_timelines` input) as `foreclosure.sale.scheduled{mi_insured=true, scheduled_sale_date, premium_paid_through}` and asserts the gate: closed → the sale package is flagged to `pmi` and the premium advanced (Section 10; F-1-05), premium_gap raises the curtailment score." });
  // ---- proceeds and appeals
  o("SM_MI_PROCEEDS_REMIT_2BD", { trigger: "`mi.claim.benefit_received{payee=servicer}`", anchorField: "received_on", satisfied: "`remittance.special.settled{code=316}`", why: "§15.3 timer table: benefit paid to the servicer (reconcileEob{paid_to=servicer}, which books Dr custodial clearing / Cr fnma_remittance_payable and drafts the special remittance) → 'CRS special remittance settled' within 2 fannie_et BD. The platform's settlement event carries the CRS `code` (15.2's reconciliation emits `remittance.special.settled{code}`; reconcileEob{op=record_remittance} ingests the CRS confirmation for a misdirected MI benefit with the same shape) — code per SF CPM, UNVERIFIED (316 candidate) as the spec row says; T9: Jan 5 → Jan 7, 2028; never netted against advances." });
  o("SM_MI_APPEAL_WINDOW", { trigger: "`mi.claim.decision.received{outcome∈{curtailment, denial, rescission}}`", anchorField: "notice_date", offset: "+30 calendar_days", satisfied: "`mi.claim.appeal.filed`", why: "§15.3 timer table: curtailment/denial/rescission notice (reconcileEob records the insurer's decision) → 'appeal filed' within the insurer's appeal_days (UNVERIFIED; default 30 calendar days) — draftAppeal{submit | op=file} or the operator's MICP appeal result, each gated by the human_agent approval over $10,000 (T7)." });
  // FNMA_F106_MI_EXPENSE_FINAL_30 is 15.2's row (final 571 submitted) — timers-15-2.ts owns its satisfaction; 15.3 emits the milestone that arms it when the F-1-06 anchor moves (T3).
}
