/**
 * §15.4 timer overrides: for every 15.4 registry row whose trigger / "Satisfied by" column is prose, a
 * `reg.override(code, { trigger?, anchorField?, satisfied | evaluator, why })` (see src/domain/foreclosure/timers.ts
 * applyForeclosureSatisfiedOverrides for the pattern). Called from this section's timers.ts after the section-level
 * overrides, so these win the merge.
 *
 * Every event named here is one the 15.4 tools (src/app/tools/section15-4.ts) emit: `setRecoveryExpectation` emits
 * `advance_position.expectation_set{expected_recovery_event, accepted_on, remittance_type, advances_outstanding}` when the
 * exit transaction (liquidation LAR / reclass PA / deferral acceptance / payoff / repurchase) or the S/A month-4 period end
 * is accepted — the process's own record of the spec's trigger, anchored on the exit event; `recomputeAdvancePosition`
 * writes the day's `delinquency_advance_positions` row; `postRecoveryEntries` books `advance_recoveries` (with a report-line
 * reference, the LAR 96 ack for the S/A recovery), emits `advances.reimbursed_by_fnma{all_outstanding=true}` when a Fannie Mae
 * reimbursement leaves nothing outstanding, and closes the position only then. The rows the spec's table reuses from 5.3/5.4
 * keep those sections' patterns and get their emitters here: `setRecoveryExpectation` emits `liquidation_facts.processed`
 * (stage=processed), `foreclosure.sale.scheduled{mbs_regular_servicing}` (event=pre_fcl_removal) and `sda_status.exited{reason,
 * exited_on}` on an accepted exit of a Stop Advance loan; `recomputeAdvancePosition` emits the daily 00:30 sweep tick.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_15_4(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  o("SM_DELADV_POSITION_DAILY", { trigger: "`schedule.tick{cadence=daily, at=00:30, job=deladv-position-sweep}`", satisfied: "`delinquency_advance_positions.written`", why: "§15.4 timer table: 'any delinquent S/S or S/A loan', anchor '00:30 loan-calendar', daily — the sweep's own tick (`recomputeAdvancePosition` → ops-15-4 `positionSweepTick`, emitted per delinquent loan whose daily clock is not already open; 'Schedules: daily position recompute (post `timer-sweep`)') arms the recurring row; 'position row written' — the recompute (rule 2) writes one `delinquency_advance_positions` row, which satisfies it and re-arms it for the next day." });
  o("SM_SDA_REIMBURSEMENT_MATCH_2_CYCLES", { trigger: "`sda_status.exited{reason∈{liquidation, reclass, deferral}}`", anchorField: "exited_on", why: "§15.4 timer table: 'exit by liquidation LAR acceptance / reclass / deferral', anchor 'exit event', '2 S/S draft cycles (18th or preceding BD)' — `setRecoveryExpectation` emits `sda_status.exited{reason, exited_on}` on the accepted exit transaction of a Stop Advance loan (F-1-20 exit table); a payoff/repurchase exit arms nothing here because Fannie Mae reimburses nothing on it (rule 3); satisfied '`advances.status = reimbursed_by_fnma` for all outstanding' — `postRecoveryEntries` emits `advances.reimbursed_by_fnma{all_outstanding=true}` (as 5.4's `matchAdjustments` does) when the reimbursement leaves nothing outstanding." });
  o("FNMA_IRM_PD_ADV_REIMB_4BD", { trigger: "`advance_position.expectation_set{expected_recovery_event=deferral_acceptance}`", anchorField: "accepted_on", satisfied: "`advance_recoveries.booked{source=fnma_deferral_reimb}`", why: "§15.4 timer table: 'payment deferral accepted in Fannie Mae's investor reporting system' → `setRecoveryExpectation(deferral_acceptance)` records the acceptance (anchor `accepted_on`); 'reimbursement line matched' — the deferral reimbursement (IRM p. 35: three to four business days after acceptance) booked as `advance_recoveries.source = fnma_deferral_reimb`." });
  o("FNMA_A1306_RECLASS_REIMB_PA", { trigger: "`advance_position.expectation_set{expected_recovery_event=reclass_pa}`", anchorField: "accepted_on", satisfied: "`advance_recoveries.booked{source=fnma_reclass_pa}`", why: "§15.4 timer table: 'reclass purchase advice received' → `setRecoveryExpectation(reclass_pa)` on the PA date (anchor `accepted_on` = PA date); 'reimbursement matched on the PA' — the purchase advice line booked as `advance_recoveries.source = fnma_reclass_pa` (A1-3-06; IRM p. 37)." });
  o("FNMA_IRM_SA_MONTH4_NEG_INTEREST", { trigger: "`advance_position.expectation_set{expected_recovery_event=sa_month4}`", anchorField: "period_end", satisfied: "`advance_recoveries.booked{source=sa_negative_interest_lar}`", why: "§15.4 timer table: 'portfolio S/A loan becomes four months delinquent (period end)' → `setRecoveryExpectation(sa_month4)` at the period end (anchor `period_end`, offset BD2 of the following month per the 5.1 clock); 'LAR 96 with negative interest accepted' — the accepted LAR 96 (its ack is the report-line reference) booked as `advance_recoveries.source = sa_negative_interest_lar` against the `delinquency_interest_sa` rows (IRM p. 26)." });
  o("FNMA_IRM_SA_LIQ_INTEREST_REIMB", { trigger: "`advance_position.expectation_set{expected_recovery_event=liquidation_lar, remittance_type=SA}`", anchorField: "accepted_on", satisfied: "`advance_recoveries.booked{source=fnma_liquidation_reimb, kind=delinquency_interest_sa}`", why: "§15.4 timer table: 'S/A liquidation LAR 70/71/72 accepted' → `setRecoveryExpectation(liquidation_lar)` on an S/A loan (anchor `accepted_on`); 'fourth-month interest reimbursement matched' after the LAR (IRM pp. 26–27), booked against the `delinquency_interest_sa` advance." });
  o("FNMA_E3501_MBS_REMOVAL_BEFORE_FCL", { evaluator: "15.4.mbsRemovedBeforeSale", satisfied: "`advance_position.expectation_set{expected_recovery_event∈{reclass_pa, repurchase}}`", why: "§15.4 timer table: not_before_gate — 'regular servicing option MBS loan scheduled for sale (13.x)' → `setRecoveryExpectation(pre_fcl_removal)` ingests the scheduled sale as `foreclosure.sale.scheduled{mbs_regular_servicing, sale_at}`; 'repurchase/reclass accepted before the sale' (E-3.5-01) → the accepted reclass purchase advice / repurchase recorded by `setRecoveryExpectation(reclass_pa | repurchase)` lifts it; while closed (or while the servicing option is unknown) it blocks the sale-package release and opens an `officer` escalation (T7)." });
  o("SM_DELADV_UNRECOVERED_60", { trigger: "`advance_position.expectation_set{expected_recovery_event∈{liquidation_lar, reclass_pa, deferral_acceptance, payoff, repurchase}, advances_outstanding=true}`", anchorField: "accepted_on", satisfied: "`advance_position.closed{reason∈{recovered, written_off}}`", why: "§15.4 timer table: 'any delinquency advance unreimbursed after the exit event' — armed by `setRecoveryExpectation` on any F-1-20 exit (liquidation LAR / reclass / deferral / paid off / repurchased, whether the loan was `accruing` or `sda_active`) with advances outstanding, anchored on the exit event; 'recovered or written off with `officer` approval' — the position closes when every delinquency advance is reimbursed/recovered, or on an officer-approved write-off (rule 4)." });
  o("SM_PAYOFF_ADV_RECOVERY_SAME_DAY", { trigger: "`advance_position.expectation_set{expected_recovery_event∈{payoff, repurchase}, advances_outstanding=true}`", anchorField: "accepted_on", satisfied: "`advance_recoveries.booked{source∈{payoff_proceeds, repurchase_price}}`", why: "§15.4 timer table: '`payoff.funds.cleared` / `repurchase.approved` on a loan with outstanding advances' → `setRecoveryExpectation(payoff|repurchase)` on the posting date (anchor `accepted_on`); '`advance_recoveries` from proceeds booked' on the payoff/repurchase posting (rule 3: our advances recover from the borrower's/seller's delinquent P&I; Fannie Mae drafts its own receivable)." });
}
