/**
 * §15.1 timer overrides: for every 15.1 registry row whose "Trigger" or "Satisfied by" column is prose,
 * a `reg.override(code, { trigger?, anchorField?, offset?, satisfied | evaluator, why })` (see
 * src/domain/foreclosure/timers.ts applyForeclosureSatisfiedOverrides for the pattern). Called from this
 * section's timers.ts after the section-level overrides, so these win the merge. Every triggering and
 * satisfying event named here is emitted by a 15.1 tool (src/app/tools/section15-1.ts) — Section 13 emits no
 * sale event, so the post-sale clocks key on `openReoCase`'s `reo.case.opened` / `tps.case.opened` and the
 * receipts, remittances and handoffs the process records itself — or is the upstream event the spec names
 * (`investor_events.accepted{event_type, accepted_at}` from 5.1's parsed LSDU / Servicing Platform feedback —
 * ops-5-1 `acceptEvent`; `liquidation_facts.processed{processed_at, action_code}` from 15.4's
 * `setRecoveryExpectation{event=liquidation_lar, stage=processed}` — ops-15-4 `liquidationProcessed`).
 * `reg.override` re-derives `anchorField` from the anchor column, so an override that names an anchor
 * restates it.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_15_1(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // ---- REOgram / Property 360 --------------------------------------------------------
  o("SM_REOGRAM_CASE_EXPECTED_1BD", { trigger: "`investor_events.accepted{event_type∈{removal.liquidation.uninsured, removal.liquidation.insured}}`", anchorField: "accepted_at", satisfied: "`p360.case.observed{kind=reogram}`", why: "§15.1 timer table: 'LAR 70/72 accepted' — 5.1's parsed LSDU / Servicing Platform feedback (ops-5-1 `acceptEvent`, `ingestLarFeedback` / `ingestServicingEventResponses`) emits `investor_events.accepted{event_id, event_type, family, accepted_at, …}` with no action code: LAR 70 is `event_type=removal.liquidation.uninsured`, LAR 72 `removal.liquidation.insured` (types.ts ACTION_CODE; 71 opens a TPS case, not a REOgram), anchored on `accepted_at` — the same shape 5.3's FNMA_IRM_LIQ_AC70_72_NEXTBD_2000 is satisfied by; 'P360 case observed' within 1 BD — `parseP360Notification` emits `p360.case.observed{kind=reogram}` for every case the daily notification e-mail lists (Potential/Exception/Confirmed queues); else ask npdc_reogram@fanniemae.com (the DRA sale event is the firm's entry, not an event of ours)." });
  o("FNMA_P360_REOGRAM_EDIT_WINDOW_5BD", { evaluator: "15.1.reogramEditWindowOpen", why: "§15.1 timer table: not_before_gate (closing) — confirmed-case fields editable for 5 BD after `reogram.confirmed`; edits after close go to SF CPM through a human (P360 REOgram User Guide 06/24/2026)." });
  // ---- deed and title (E-4.2-01) — armed by the case the sale opens ---------------------
  o("FNMA_E4201_DEED_RECORD_NEXT_DAY", { trigger: "`reo.case.opened{foreclosed_in_name_of∈{servicer, mers_assignee}}`", anchorField: "legal_date", satisfied: "`deed.submitted_for_recording`", why: "§15.1 timer table: 'sale held with title vested in servicer' → `openReoCase` opens `reo_cases` on `foreclosure.sale.held` (Section 13 emits no sale event of its own) and emits `reo.case.opened{foreclosed_in_name_of}` anchored on the sale (`legal_date`); +1 calendar day rolled to the next servicer business day when the recorder is closed; satisfied by the firm's e-recording confirmation — `scheduleHandoffTasks{op=complete, kind=deed_record}` emits `deed.submitted_for_recording` (E-4.2-01)." });
  o("SM_TITLE_MARKETABLE_30", { trigger: "`reo.case.opened`", anchorField: "legal_date", satisfied: "`deed.recorded{title_curative_clear=true}`", why: "§15.1 timer table: 'sale held' → `reo.case.opened` anchored on `legal_date`; '`deed.recorded` + title curative clear' — `scheduleHandoffTasks{op=complete, kind=title_curative}` records the recorded deed copy with the curative items cleared (E-4.2-01 'good and marketable title in a timely manner')." });
  // ---- third-party sales (E-3.5-02, F-1-08, F-1-20) ----------------------------------
  o("FNMA_E3502_TPS_PROCEEDS_5BD", { trigger: "`tps.proceeds.received{kind=final_payment}`", anchorField: "receipt", satisfied: "`remittance.special.settled{code∈{311, 351}}`", why: "§15.1 timer table: 'final payment received from bidder' — the spec's inbound `tps.proceeds.received` (§Inputs), recorded on the TPS case by `openReoCase{op=proceeds_received, kind=final_payment}` with the receipt date; 'CRS 311/351 instructed and settled' within 5 `business_days_fannie_et` — `buildCrsBatch` drafts the lines and `buildCrsBatch{op=settled}` records the CRS settlement (`remittance.special.settled{code, kind}`; 15.2's ACH reconciliation emits the same event) (E-3.5-02; F-1-20)." });
  o("FNMA_E3502_TPS_FAILED_DEPOSIT_5BD", { satisfied: "`remittance.special.settled{code=311, kind=tps_deposit}`", why: "§15.1 timer table: 'deposit remitted' — `openReoCase{op=sale_failed}` records the discovery (`sale.failed_to_finalize`), `buildCrsBatch{kind=tps_deposit}` drafts the bidder's initial deposit as code 311 and `buildCrsBatch{op=settled}` emits `remittance.special.settled{code=311, kind=tps_deposit}` from the batch's own kind within 5 BD (E-3.5-02; rule 9)." });
  o("FNMA_E3502_TPS_INSURANCE_CANCEL_14", { trigger: "`tps.proceeds.received{kind=final_payment}`", anchorField: "completion_date", satisfied: "`insurance.cancellation.requested`", why: "§15.1 timer table: 'TPS completed / court confirmation' — the sale completes with the bidder's final payment (court confirmation date supplied as `completion_date` in judicial states), recorded by `openReoCase{op=proceeds_received}`; 'cancellation requested' within 14 calendar days — `requestInsuranceCancellation` emits the request (9.5 flow) (E-3.5-02)." });
  o("FNMA_F108_TPS_CLOSING_STMT_SAME_DAY", { trigger: "`remittance.special.settled{code=311, kind=tps_proceeds}`", anchorField: "settled_on", satisfied: "`closing_statement.sent{recipient=sf_cpm}`", why: "§15.1 timer table: '311 remitted' → `buildCrsBatch{op=settled}` records the 311 settlement on its remittance date (`settled_on`); 'closing statement sent to SF CPM' the same day with the principal/interest/fees/advances breakdown — `draftClosingStatement{op=send}` emits it (F-1-08)." });
  o("SM_TPS_P360_DOCS_5BD", { satisfied: "`human_portal_task.completed{task=p360.tps.update_upload}`", why: "§15.1 timer table: 'documents uploaded, fields updated' — `openPortalTask{op=complete}` completes the `p360.tps.update_upload` escalation with the evidence capture and emits `human_portal_task.completed{task=…}` (P360 Liquidation Reconciliation User Guide)." });
  // ---- post-sale handoff (E-4.3, E-4.4) — armed by reo_cases creation (rule 6) ---------
  o("FNMA_E4401_HAZARD_CANCEL_14", { trigger: "`reo.case.opened{acquirer=fannie_mae}`", anchorField: "legal_date", satisfied: "`insurance.cancellation.requested`", why: "§15.1 timer table: 'sale held / Mortgage Release accepted' → `openReoCase` opens `reo_cases` (acquisition_type fcl_sale on `foreclosure.sale.held`, mortgage_release on `dil.deed.recorded`) and emits `reo.case.opened{acquirer=fannie_mae}` anchored on `legal_date`; '`insurance.cancellation.requested` (or mortgagee-removal request)' within 14 calendar days — `requestInsuranceCancellation` (E-4.4-01)." });
  o("FNMA_E4403_FLOOD_CANCEL_14", { trigger: "`reo.case.opened{acquirer=fannie_mae}`", anchorField: "legal_date", satisfied: "`flood.cancellation.requested`", why: "§15.1 timer table: 'same' as FNMA_E4401_HAZARD_CANCEL_14 → `reo.case.opened{acquirer=fannie_mae}` anchored on `legal_date`; `flood.cancellation.requested` within 14 calendar days — `requestInsuranceCancellation{policy_kind=flood}` (E-4.4-03)." });
  o("FNMA_E4301_PRESERVATION_STOP", { trigger: "`reo.case.opened{acquirer=fannie_mae}`", anchorField: "legal_date", evaluator: "15.1.postSalePreservationAllowed", why: "§15.1 timer table / rule 6: not_before_gate (closing) — 'On `reo_cases` creation the gate closes 9.9 work orders' → `reo.case.opened{acquirer=fannie_mae}` at the legal date, regardless of title transfer; exception: TPS until completion; emergency orders only on SF CPM direction, non-reimbursable by default (`scheduleHandoffTasks{op=order_preservation}` guardrail NO_POST_SALE_PRESERVATION) (E-4.3-01)." });
  o("FNMA_E4304_EVICTION_DOCS_3BD", { satisfied: "`fnma.request.fulfilled{kind=eviction_documents}`", why: "§15.1 timer table: 'documents delivered' — `scheduleHandoffTasks{op=request, requested_kind=eviction_docs}` records the request (`fnma.request.received{kind=eviction_documents}`) and `scheduleHandoffTasks{op=complete, kind=eviction_docs}` returns the notice-to-vacate documentation to Fannie Mae / eviction counsel (firm within 3 BD, servicer ASAP) (E-4.3-04)." });
  o("FNMA_E4401_RECOVERY_FIRM_INFO_3BD", { satisfied: "`fnma.request.fulfilled{kind=property_recovery}`", why: "§15.1 timer table: 'documents delivered' — `scheduleHandoffTasks{op=request, requested_kind=recovery_firm_info}` records the request (`fnma.request.received{kind=property_recovery}`) and `scheduleHandoffTasks{op=complete, kind=recovery_firm_info}` delivers policy and inspection information to the property recovery firm within 3 BD of its request (E-4.4-01)." });
  // ---- eliminations / rescissions (E-4.1-02) ------------------------------------------
  o("FNMA_E4102_ELIM_RESCISSION_REQUEST_5", { satisfied: "`elimination_rescission.request.submitted`", why: "§15.1 timer table: 'template submitted' — `draftEliminationTemplate` opens the `fnma_portal_operator` task and `openPortalTask{op=complete, task=elimination_rescission.submit}` emits the submission when the Excel template is e-mailed within five days of identification (E-4.1-02; rule 10)." });
  o("FNMA_E4102_REINTEGRATE_24H", { satisfied: "`loan.reactivated`", why: "§15.1 timer table: 'loan re-activated in servicing' within 24 hours of the approval notification — `draftEliminationTemplate{op=reactivated}` records the re-add: `loan.reactivated` (sda_status, escrow and statements resume in 5.4/3.x/7.x off the event), `delinquency.case.reopened` / `foreclosure.case.reopened`, the REO case parked in `rescinded`, and the 5.x re-add e-mail task to readd_requests@fanniemae.com when the LAR removal was accepted (E-4.1-02)." });
  o("FNMA_E4102_TITLE_RESTORE_2", { satisfied: "`attorney.instruction.sent{kind=TITLE_RESTORATION}`", why: "§15.1 timer table: 'title-restoration step initiated' — `draftEliminationTemplate{op=approved}` arms the clock and opens the `attorney` escalation; the instruction itself is a later act, `draftEliminationTemplate{op=instruct_counsel}`, which emits `attorney.instruction.sent{kind=TITLE_RESTORATION}` when counsel has been instructed — within two days of the approval notification or the clock breaches to the attorney (E-4.1-02)." });
  // ---- tenants (PTFA) and the LL-2026-05 rail -------------------------------------------
  o("PTFA_TENANT_NOTICE_90", { trigger: "`property.tenant.identified{bona_fide=true, post_acquisition=true, path=servicer_counsel}`", anchorField: "vacate_date", satisfied: "`tenant.notice.served{kind=ptfa_90_day}`", why: "§15.1 timer table: 'deadline (servicer-counsel path only)' on 'bona fide tenant identified post-acquisition' — `scheduleHandoffTasks{op=tenant_identified}` emits `property.tenant.identified{bona_fide, post_acquisition=true, path, vacate_date}`; only the servicer-counsel path arms the clock (Fannie Mae's eviction counsel runs its own on vendor-managed property); the −90 calendar-day clock anchors on `vacate_date`; 'notice served; lease honored' — the 90-day notice to vacate served by servicer-retained counsel, logged by `scheduleHandoffTasks{op=complete, kind=eviction_docs, ptfa_notice_served_on}` (PTFA, 12 U.S.C. §5220 note)." });
  o("FNMA_LL202605_LIQ_EVENT_NEXTBD", { anchorField: "processed_at", satisfied: "`fnma.liquidation_event.accepted`", why: "§15.1 timer table / rule 12: 'liquidation processed' is `liquidation_facts.processed{fact_id, processed_at, action_code, event_type}` (anchor `processed_at`) — the 5.3 row's trigger, emitted on this platform by 15.4's `setRecoveryExpectation{event=liquidation_lar, stage=processed}` (ops-15-4 `liquidationProcessed`; no 5.3 tool emits it); the REO / TPS / Government Conveyance event is projected to `api-clve` by `openReoCase{op=liquidation_rail}` (`fnma.liquidation_event.projected`, the rail state persisted on `reo_cases.liquidation_rail`) and 'P360 liquidation event accepted' by the next BD 03:00 ET is recorded by `openReoCase{op=liquidation_event_accepted}` from the `fnma-servicing-events` acknowledgment, emitting `fnma.liquidation_event.accepted` (LL-2026-05)." });
}
