/**
 * §15.2 timer satisfaction overrides: for every 15.2 registry row whose "Satisfied by"
 * column is prose, a `reg.override(code, { satisfied | evaluator, trigger?, offset?, anchorField?, why })`
 * (see src/domain/foreclosure/timers.ts applyForeclosureSatisfiedOverrides for the pattern).
 * Called from this section's timers.ts after the section-level overrides. `TimerRegistry.override` re-parses the raw
 * anchor column, so every override here restates the section-level `anchorField` it would otherwise drop; where the
 * section-level trigger names a fact no producer emits, the trigger is restated to the 15.2 tool's own fact.
 *
 * Every event named here is emitted by the 15.2 tools in src/app/tools/section15-2.ts (the actors the state
 * machine names act through them):
 *   claim.milestone.reached{kind, mi_insured, legal_date}   sweepClaimCandidates op=candidates (milestone events from 12.x/13.x/15.1/16.x; kind = MilestoneKind:
 *                                                           workout_completed | shortsale_closed | deferral_completed | tps_completed | reinstatement | payoff | reo_disposition | mortgage_release | foreclosure_sale | govt_claim_proceeds)
 *   expense_claim.status_changed{status}                    assembleClaim (validated/draft), buildBulkPackage (package_ready, submitted)
 *   claim.final.preparing{hazard_refund_expected}           assembleClaim (non-interim claim) — arms the E-4.4-02 gate
 *   p360.claim.submitted{kind=final|interim, milestone_kind} buildBulkPackage op=build (API accepted) / op=record_upload (fnma_portal_operator)
 *   p360.claim.status_refreshed / p360.claim.status_changed{status, psa_at, paid_at}  sweepClaimCandidates op=status_poll (weekly; PSA past its countdown → status=denied, auto_denied)
 *   p360.inquiry.response_received                          sweepClaimCandidates op=status_poll (IRT Repository export)
 *   p360.psa.responded / irt.inquiry.filed / irt.inquiry.responded{by=submitter}  buildBulkPackage op=psa_response / irt_inquiry / irt_response (operator)
 *   p360.payment.ach_matched / remittance.special.settled{code}  sweepClaimCandidates op=reconcile (bank feed + FMConnect reconciliation report)
 *   advance_recovery.repayment_scheduled{fnma_reimbursed_advances=true, completion_date}  sweepClaimCandidates op=recoveries (`scheduleRepayment`, rule 8)
 *   workout_incentive.repayment_scheduled{re_entered_within_30=false, cancellation_date}  sweepClaimCandidates op=incentive_repayment (F-1-05 cancelled workout incentive)
 *   expense_claim.credit.received{remit_code, fnma_reimbursed_premium, received_at}     sweepClaimCandidates op=credit (rule 7; 10.5 / 9.5 refunds against the stored claim)
 *   preservation.condition.discovered{over_allowable=true, discovered_on}  assembleClaim — a preservation line over its PPM cap with no bid id (9.9's FNMA_PPM_OVER_ALLOWABLE_BID_15, reused)
 *   preservation.bid.submitted / preservation.bid.decided{outcome, decided_on}  sweepClaimCandidates op=hometracker (the HomeTracker bid feed, validated per record)
 *   preservation.bid.reconsideration_submitted               buildBulkPackage op=bid_reconsideration (FNMA_PPM_BID_RECONSIDER_7, reused)
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_15_2(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  o("FNMA_E501_EXPENSE_FINAL_60", { trigger: "`claim.milestone.reached{kind∈{workout_completed, shortsale_closed, deferral_completed, tps_completed, reinstatement, payoff, reo_disposition, govt_claim_proceeds}}`", anchorField: "milestone_date", satisfied: "`p360.claim.submitted{kind=final}`", why: "§15.2 timer table: 'final claim `submitted`' — the non-interim claim reaches P360 Submitted (API accepted, or the operator records the bulk upload) within 60 calendar days of the E-5-01 milestone. Trigger restated to the kinds the sweep emits: E-5-01 names 'the completion of a workout option (including a mortgage loan modification or short sale)' (shortsale_closed, deferral_completed, workout_completed), the TPS, reinstatement/payoff, the government claim proceeds, and 'Fannie Mae disposes of a property acquired through foreclosure sale or a Fannie Mae Mortgage Release' — so a foreclosure sale or Mortgage Release arms it at the disposition (reo_disposition), never at the sale (rule 3)." });
  o("FNMA_F106_MI_EXPENSE_FINAL_30", { anchorField: "milestone_date", satisfied: "`p360.claim.submitted{kind=final}`", why: "§15.2 timer table: 'final claim `submitted`' — MI-insured liquidations file the final request within 30 days of settlement / redemption expiry (F-1-06); 15.3 does not override this code (timers-15-3.ts) — it emits the milestone that arms it when the F-1-06 anchor moves to the redemption expiry / docket entry (15.3-T3); this file owns its satisfaction." });
  o("SM_EXPENSE_CLAIM_TARGET_20", { anchorField: "milestone_date", satisfied: "`expense_claim.status_changed{status=package_ready}`", why: "§15.2 timer table: 'claim `package_ready`' — the bulk ZIP/API payload is built (buildBulkPackage) within 20 calendar days of the milestone." });
  o("FNMA_F105_PD_EXPENSE_60", { trigger: "`claim.milestone.reached{kind=deferral_completed}`", anchorField: "completion_date", satisfied: "`p360.claim.submitted{milestone_kind=deferral_completed}`", why: "§15.2 timer table: `lossmit.deferral.completed` → 'claim submitted' — deferral-related expenses claimed within 60 days of the completed payment deferral (F-1-05). Trigger restated to the fact the nightly sweep records from 12.x's `lossmit.deferral.completed` (Inputs: the milestone events that start the final-claim clock), carrying `completion_date`." });
  o("FNMA_F105_RECOVERABLE_REPAY_60", { trigger: "`advance_recovery.repayment_scheduled{fnma_reimbursed_advances=true}`", anchorField: "completion_date", satisfied: "`remittance.special.settled{code∈{353, 352, 571}}`", why: "§15.2 timer table: 'reinstatement/retention workout completed on a loan where Fannie Mae already reimbursed advances' → 'CRS 353/352/571 remittance settled' within 60 calendar days (F-1-05). Trigger restated to the 15.2 fact: only this process knows which advances Fannie Mae reimbursed, so sweepClaimCandidates op=recoveries (`scheduleRepayment`, rule 8) books the `advance_recoveries` batch FIFO by advance and emits the scheduled repayment with `completion_date`; the monthly reconciliation (FMConnect report / CRS settlement) satisfies it — same vocabulary as §15.1's 311/351 settlements." });
  o("FNMA_F105_MI_REFUND_336_30", { trigger: "`expense_claim.credit.received{fnma_reimbursed_premium=true, remit_code=336}`", anchorField: "received_at", satisfied: "`remittance.special.settled{code=336}`", why: "§15.2 timer table: 'MI premium refund received after Fannie Mae reimbursed the premium' → 'CRS 336 settled' within 30 calendar days (F-1-05). Trigger restated to the 15.2 fact: 10.5's `mi.insurer.refund_received` carries no reimbursement flag — sweepClaimCandidates op=credit (rule 7) matches the refund to the stored claim and emits the credit with `fnma_reimbursed_premium` set from the Paid claim's MI premium line and `remit_code=336`; a refund before payment is a `claim_credits` netting instead." });
  o("FNMA_F105_INCENTIVE_REPAY_60", { trigger: "`workout_incentive.repayment_scheduled{re_entered_within_30=false}`", anchorField: "cancellation_date", satisfied: "`remittance.special.settled{code=350}`", why: "§15.2 timer table: 'modification/deferral cancelled and not re-entered within 30 days' → 'incentive repaid (CRS 350)' within 60 calendar days of the cancellation (F-1-05). Trigger restated to the 15.2 fact: sweepClaimCandidates op=incentive_repayment applies the 30-day re-entry test to 12.x's cancellation and emits the scheduled repayment with `cancellation_date`; the settled 350 satisfies it." });
  o("FNMA_F105_ESCROW_ADV_CUTOFF_14", { trigger: "`claim.milestone.reached{kind∈{foreclosure_sale, mortgage_release, shortsale_closed, tps_completed}}`", anchorField: "legal_date", evaluator: "15.2.escrowAdvanceWithinCutoff", why: "§15.2 timer table: not_after gate, 'sale/Mortgage Release/short-sale close/TPS completion', 'Satisfied by —' — an insurance/HOA advance is claimable only through the legal date + 14 calendar days; later advances are tagged `post_sale_nonreimbursable` and excluded from the claim (F-1-05; rule 4; 15.2-T4). Trigger restated to the kinds the sweep emits (`foreclosure_sale`, `shortsale_closed`, …); the evaluator is applied by validateLine152 to every hazard/flood/HOA line on `{advance_kind, legal_date, paid_on}`." });
  o("FNMA_P360_PSA_RESPONSE_60", { anchorField: "psa_at", satisfied: "`p360.psa.responded`", why: "§15.2 timer table: 'PSA response submitted' — the operator records the documentation uploaded as an attachment/comment before P360's 60-day auto-denial countdown ends; past it the weekly poll records the auto-denial (status=denied, sev-1) and the engine breaches this row." });
  o("SM_P360_PSA_INTERNAL_10", { anchorField: "psa_at", satisfied: "`p360.psa.responded`", why: "§15.2 timer table: 'response submitted' — the internal 10-day target closes on the same PSA response." });
  o("FNMA_IRT_RESPONSE_7", { anchorField: "response_at", satisfied: "`irt.inquiry.responded{by=submitter}`", why: "§15.2 timer table: 'submitter response posted' — the submitter has seven calendar days to respond or the inquiry auto-Completes (IRT Submitter User Manual)." });
  o("SM_P360_STATUS_POLL_7", { anchorField: "submitted_at", satisfied: "`p360.claim.status_refreshed`", why: "§15.2 timer table: 'status refreshed' — the weekly poll (API/B2B or operator export) re-reads the P360 status." });
  o("SM_P360_PROCESSING_30", { anchorField: "submitted_at", satisfied: "`p360.claim.status_changed{status∈{approved, psa, paid, partially_paid, denied, curtailed, rejected, void}}`", why: "§15.2 timer table: 'status ≠ Submitted' — P360 generally processes within 30 days; Hold is grouped with Submitted (state machine: `submitted` = P360 Submitted/Hold) so it does not close the watch; still Submitted/Hold at day 30 → Expense Pending inquiry." });
  o("SM_P360_ACH_MATCH_3BD", { anchorField: "paid_at", satisfied: "`p360.payment.ach_matched`", why: "§15.2 timer table: 'ACH credit matched' — the reconciliation matches the bank-feed credit to the Paid claim within 3 `business_days_fannie_et` (+2 BD tolerance); unmatched → package to FannieMae_REO_Disbursements@fanniemae.com." });
  // 9.9's rows reused by the 15.2 timer table ("defined in 9.9; reused here"): the trigger/satisfied patterns are 9.9's (src/domain/insurance/timers.ts); only the anchor column ("discovery" / "decision") is restated to the date field the 15.2 facts carry.
  o("FNMA_PPM_OVER_ALLOWABLE_BID_15", { anchorField: "discovered_on", why: "§15.2 timer table: 'over-allowable condition discovered' → anchor 'discovery' → `preservation.bid.submitted` within 15 calendar days; 'claim lines above allowables without a bid id fail validation' — assembleClaim discovers the condition on a preservation line over its PPM cap with no hometracker_bid_id and dates it `discovered_on`; the HomeTracker feed's bid (sweepClaimCandidates op=hometracker) satisfies it." });
  o("FNMA_PPM_BID_RECONSIDER_7", { anchorField: "decided_on", why: "§15.2 timer table: 'Fannie Mae bid decision (denied/modified)' → anchor 'decision' → 'reconsideration submitted or accepted' within 7 calendar days; 'unreconsidered denials reduce the claimable amount' — the feed's `preservation.bid.decided{outcome, decided_on}` arms it and buildBulkPackage op=bid_reconsideration's `preservation.bid.reconsideration_submitted` satisfies it; without one the line stays at the PPM cap." });
}
