/**
 * Registry overrides for Section 15 (post-sale, claims, MI claims, advances)
 * timers whose spec rows are prose.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applyReoTimerOverrides(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // ---- 15.1 post-sale ------------------------------------------------------
  o("FNMA_E3502_TPS_FAILED_DEPOSIT_5BD", { trigger: "`sale.failed_to_finalize`", why: "§15.1 timer table: sale failure discovered → deposit remitted within 5 BD (E-3.5-02)." });
  o("FNMA_E3502_TPS_INSURANCE_CANCEL_14", { trigger: "`sale.completed{kind=third_party}`", anchorField: "completion_date", why: "§15.1 timer table: TPS completed / court confirmation → insurance cancellation requested within 14 calendar days (E-3.5-02)." });
  o("FNMA_E3502_TPS_PROCEEDS_5BD", { trigger: "`sale_results.final_payment_received`", why: "§15.1 timer table: final payment received from bidder → CRS 311/351 instructed and settled within 5 `business_days_fannie_et` (E-3.5-02)." });
  o("FNMA_E4101_REOGRAM_EXCEPTION_3BD", { trigger: "`reogram.exception.raised`", anchorField: "raised_at", why: "§15.1 timer table: P360 exception raised → resolved within 3 `business_days_fannie_et` (E-4.1-01)." });
  o("FNMA_E4102_ELIM_RESCISSION_REQUEST_5", { trigger: "`sale.rescission_issue.identified`", why: "§15.1 timer table: issue identified → rescission request template within 5 calendar days (E-4.1-02 'five days' — calendar assumed)." });
  o("FNMA_E4102_REINTEGRATE_24H", { trigger: "`sale.rescission.approved`", why: "§15.1 timer table: approval notification → loan re-activated in servicing within 24 hours (E-4.1-02)." });
  o("FNMA_E4102_TITLE_RESTORE_2", { trigger: "`sale.rescission.approved`", why: "§15.1 timer table: approval notification → title-restoration step initiated within 2 calendar days (E-4.1-02)." });
  o("FNMA_E4201_DEED_RECORD_NEXT_DAY", { trigger: "`sale.completed{title_vested_in=servicer}`", anchorField: "sale_date", offset: "+1 calendar_days (rolled to the next servicer business day)", why: "§15.1 timer table: sale held with title vested in servicer → deed submitted for recording next day (next BD if recorder closed) (E-4.2-01)." });
  o("FNMA_E4301_PRESERVATION_STOP", { trigger: "`sale.completed{acquirer=fannie_mae}`", anchorField: "legal_date", why: "§15.1 timer table: sale held / court-order vesting (Fannie Mae acquiring) → servicer preservation stops on legal date (E-4.3-01)." });
  o("FNMA_E4304_EVICTION_DOCS_3BD", { trigger: "`fnma.request.received{kind=eviction_documents}`", offset: "+3 business_days_servicer", why: "§15.1 timer table: Fannie Mae/eviction counsel document request → delivered within 3 BD (firm) / ASAP (servicer) (E-4.3-04)." });
  o("FNMA_E4401_HAZARD_CANCEL_14", { trigger: "`sale.completed{acquirer=fannie_mae}`", anchorField: "legal_date", why: "§15.1 timer table: sale held / Mortgage Release accepted → hazard cancellation requested within 14 calendar days (E-4.4-01); `dil.accepted` arms the same code." });
  o("FNMA_E4401_RECOVERY_FIRM_INFO_3BD", { trigger: "`fnma.request.received{kind=property_recovery}`", offset: "+3 business_days_servicer", why: "§15.1 timer table: property recovery firm request → documents delivered within 3 BD (E-4.4-01)." });
  o("FNMA_F108_TPS_CLOSING_STMT_SAME_DAY", { trigger: "`remittance.instructed{code=311}`", why: "§15.1 timer table: 311 remitted → closing statement to SF CPM the same day (F-1-08)." });
  o("FNMA_LL202605_LIQ_EVENT_NEXTBD", { trigger: "`liquidation_facts.processed`", offset: "next business_days_fannie_et at 03:00 ET", why: "§15.1 timer table: liquidation processed → P360 liquidation event next BD (03:00 ET event standard) (LL-2026-05)." });
  o("PTFA_TENANT_NOTICE_90", { trigger: "`property.tenant.identified{bona_fide=true, post_acquisition=true}`", anchorField: "vacate_date", offset: "−90 calendar_days", why: "§15.1 timer table: bona fide tenant identified post-acquisition → notice served ≥90 calendar days before vacate date; lease honored (PTFA)." });
  o("SM_REOGRAM_CASE_EXPECTED_1BD", { trigger: "`investor_events.accepted{action_code∈{70, 72}}`", why: "§15.1 timer table: LAR 70/72 accepted or DRA sale event → P360 case observed within 1 BD." });
  o("SM_TITLE_MARKETABLE_30", { trigger: "`sale.completed`", anchorField: "sale_date", why: "§15.1 timer table: sale held → deed recorded + title curative clear within 30 calendar days." });
  o("SM_TPS_P360_DOCS_5BD", { trigger: "`p360.case.observed{kind=third_party_sale}`", why: "§15.1 timer table: TPS case observed in P360 → documents uploaded, fields updated within 5 BD." });
  // ---- 15.2 expense claims -------------------------------------------------
  o("FNMA_E4402_REFUND_CREDIT_ON_FINAL", { trigger: "`claim.final.preparing{hazard_refund_expected=true}`", evaluator: "15.2.refundCreditLinePresent", why: "§15.2 timer table: hazard refund expected → credit line present or refusal comment on the final claim (E-4.4-02)." });
  o("FNMA_E501_EXPENSE_FINAL_60", { trigger: "`claim.milestone.reached{kind∈{workout_completed, tps_completed, reinstatement, payoff, reo_disposition, govt_claim_proceeds}}`", why: "§15.2 timer table: milestone event → final claim `submitted` within 60 calendar days (E-5-01)." });
  o("FNMA_F105_ESCROW_ADV_CUTOFF_14", { trigger: "`claim.milestone.reached{kind∈{sale, mortgage_release, shortsale_close, tps_completed}}`", anchorField: "legal_date", why: "§15.2 timer table: sale/Mortgage Release/short-sale close/TPS completion → escrow advances claimable only through legal date +14 calendar days (F-1-05)." });
  o("FNMA_F105_INCENTIVE_REPAY_60", { trigger: "`lossmit.workout.cancelled{re_entered_within_30=false}`", anchorField: "cancellation_date", why: "§15.2 timer table: modification/deferral cancelled and not re-entered within 30 days → incentive repaid (CRS 350) within 60 calendar days (F-1-05)." });
  o("FNMA_F105_MI_REFUND_336_30", { trigger: "`mi.insurer.refund_received{fnma_reimbursed_premium=true}`", why: "§15.2 timer table: MI premium refund received after Fannie Mae reimbursed the premium → CRS 336 settled within 30 calendar days (F-1-05)." });
  o("FNMA_F105_RECOVERABLE_REPAY_60", { trigger: "`lossmit.workout.completed{fnma_reimbursed_advances=true}`", anchorField: "completion_date", why: "§15.2 timer table: reinstatement/retention workout completed where Fannie Mae already reimbursed advances → CRS 353/352/571 within 60 calendar days (F-1-05)." });
  o("FNMA_F106_MI_EXPENSE_FINAL_30", { trigger: "`claim.milestone.reached{mi_insured=true}`", anchorField: "milestone_date", why: "§15.2 timer table: MI-insured: settlement / TPS or short-sale settlement / redemption expiry or docket entry → final claim within 30 calendar days (F-1-06)." });
  o("FNMA_IRT_RESPONSE_7", { trigger: "`p360.inquiry.response_received`", anchorField: "response_at", why: "§15.2 timer table: Fannie Mae analyst response on an inquiry → submitter response within 7 calendar days (IRT)." });
  o("FNMA_P360_PSA_RESPONSE_60", { trigger: "`p360.claim.status_changed{status=psa}`", anchorField: "psa_at", why: "§15.2 timer table: claim enters PSA → response within 60 calendar days (P360 countdown)." });
  o("SM_P360_PROCESSING_30", { trigger: "`p360.claim.submitted`", anchorField: "submitted_at", why: "§15.2 timer table: claim submitted → status ≠ Submitted expected within 30 calendar days." });
  o("SM_P360_STATUS_POLL_7", { trigger: "`p360.claim.submitted`", anchorField: "submitted_at", offset: "every 7 calendar_days", why: "§15.2 timer table: claim submitted → status refreshed every 7 calendar days." });
  // ---- 15.3 MI claims ------------------------------------------------------
  o("FNMA_E4501_MICP_DATA_CORRECTION_1BD", { trigger: "`mi_claims.data_mismatch.detected`", why: "§15.3 timer table: MICP/REOgram MI data mismatch detected → correction within 1 BD (E-4.5-01)." });
  o("FNMA_F106_MI_DIRECT_FILE_30", { trigger: "`mi_claims.routed{route=servicer_direct}`", anchorField: "claim_anchor_date", why: "§15.3 timer table: `routed = servicer_direct` → insurer acknowledgment within 30 calendar days of settlement / remittance / redemption expiry (F-1-06)." });
  o("FNMA_F106_MICP_DOCS_10BD", { trigger: "`mi_claims.routed{route=fnma_micp}`", anchorField: "claim_filing_deadline", why: "§15.3 timer table: `mi_claims.routed = fnma_micp` → all mandatory documents uploaded −10 `business_days_fannie_et` before `claim_filing_deadline` (F-1-06)." });
  o("MI_MP_CLAIM_FILE_60", { trigger: "`liquidation_facts.processed{mi_insured=true}`", anchorField: "claim_filing_deadline", offset: "0", why: "§15.3 timer table: `claim_filing_days` calendar days (60 default) from `claim_anchor_date` — computed per master policy by `15.3.claimFilingDeadline`." });
  o("MI_MP_INTEREST_CAP_36M", { trigger: "`mi.default.started`", anchorField: "first_unpaid_due_date", why: "§15.3 timer table: default date → claimable interest capped at 36 months from first unpaid due date (master policy)." });
  o("MI_MP_NOD_25TH", { trigger: "`loan.delinquency.day_reached{missed_payments=2}`", offset: "25th", why: "§15.3 timer table: second consecutive missed payment unpaid → insurer NOD accepted by the 25th of that month (master policy)." });
  o("MI_MP_SETTLEMENT_60", { anchorField: "perfected_at", offset: "+60 calendar_days", why: "§15.3 timer table: `settlement_days` calendar days from perfection (master policy default 60)." });
  o("MI_MP_STATUS_MONTHLY_25TH", { trigger: "`mi.default.started`", offset: "monthly", why: "§15.3 timer table: loan in default → monthly status report accepted by the 25th (master policy)." });
  o("MI_MP_SUPPLEMENTAL_90", { trigger: "`liquidation_facts.processed{mi_insured=true}`", anchorField: "claim_anchor_date", why: "§15.3 timer table: liquidation fact → supplemental claim (or none needed) within 90 calendar days of `claim_anchor_date`." });
  o("SM_MI_APPEAL_WINDOW", { trigger: "`mi.claim.decision.received{outcome∈{curtailment, denial, rescission}}`", offset: "+30 calendar_days", why: "§15.3 timer table: `appeal_days` per insurer (UNVERIFIED); default 30 calendar days." });
  o("SM_MI_PREMIUM_PAID_THROUGH_GATE", { trigger: "`foreclosure.sale.scheduled{mi_insured=true}`", evaluator: "15.3.premiumPaidThroughLiquidationMonth", why: "§15.3 timer table: `mi_policies.premium_paid_through ≥ liquidation month` before sale." });
  o("SM_MI_PROCEEDS_REMIT_2BD", { trigger: "`mi.claim.benefit_received{payee=servicer}`", why: "§15.3 timer table: benefit paid to the servicer instead of Fannie Mae → CRS special remittance settled within 2 `business_days_fannie_et`." });
  o("SM_MI_SETTLEMENT_FOLLOWUP_7", { trigger: "`mi.claim.filed{route=servicer_direct}`", anchorField: "filed_at", offset: "every 7 calendar_days", why: "§15.3 timer table: filed (direct) → follow-up every 7 calendar days until paid." });
  o("SM_MICP_DOC_REQUEST_DUE", { trigger: "`micp.document_request.observed`", anchorField: "micp_due_at", offset: "0", why: "§15.3 timer table: earlier of MICP Due Date and 5 BD — computed anchor via `15.3.micpDocRequestDue`." });
  o("SM_MICP_DOCS_TARGET_15", { trigger: "`liquidation_facts.processed{mi_insured=true, route=fnma_micp}`", anchorField: "claim_anchor_date", why: "§15.3 timer table: liquidation fact → MICP package uploaded within 15 calendar days of `claim_anchor_date`." });
  // ---- 15.4 delinquency advances ------------------------------------------
  o("FNMA_A1306_RECLASS_REIMB_PA", { trigger: "`fnma.purchase_advice.received{kind=reclass}`", anchorField: "purchase_advice_date", why: "§15.4 timer table: reclass purchase advice received → reimbursement matched on the PA date (A1-3-06)." });
  o("FNMA_E3501_MBS_REMOVAL_BEFORE_FCL", { trigger: "`foreclosure.sale.scheduled{mbs_regular_servicing=true}`", anchorField: "sale_at", offset: "−1 calendar_days", why: "§15.4 timer table: regular servicing option MBS loan scheduled for sale → repurchase/reclass accepted before the sale (E-3.5-01)." });
  o("FNMA_IRM_PD_ADV_REIMB_4BD", { trigger: "`payment_deferral.accepted{fnma_reporting=true}`", why: "§15.4 timer table: payment deferral accepted in Fannie Mae's investor reporting system → reimbursement line matched within 4 `business_days_fannie_et`." });
  o("FNMA_IRM_SA_LIQ_INTEREST_REIMB", { trigger: "`investor_events.accepted{action_code∈{70, 71, 72}, remittance_type=sa}`", offset: "20th of the month after next (preceding fannie_et BD)", why: "§15.4 timer table: S/A liquidation LAR 70/71/72 accepted → fourth-month interest reimbursement matched within 2 draft cycles (CD20 drafts)." });
  o("FNMA_IRM_SA_MONTH4_NEG_INTEREST", { trigger: "`period.month_end{remittance_type=sa, portfolio=true, months_delinquent=4}`", offset: "BD2 17:00 ET", why: "§15.4 timer table: portfolio S/A loan four months delinquent at period end → LAR 96 with negative interest by the period reporting clock (5.1)." });
  o("SM_DELADV_POSITION_DAILY", { trigger: "`schedule.tick{cadence=daily, at=00:30}`", offset: "daily", why: "§15.4 timer table: any delinquent S/S or S/A loan → position row written daily at 00:30 loan-calendar." });
  o("SM_DELADV_UNRECOVERED_60", { trigger: "`sda_status.exited{advances_outstanding=true}`", why: "§15.4 timer table: delinquency advance unreimbursed after the exit event → recovered or written off with `officer` approval within 60 calendar days." });
  // ---- pseudo-trigger rows -----------------------------------------------------
  o("FNMA_E4403_FLOOD_CANCEL_14", { trigger: "`sale.completed{acquirer=fannie_mae}`", anchorField: "legal_date", why: "§15.1 timer table: 'same' as FNMA_E4401_HAZARD_CANCEL_14 → sale held / Mortgage Release accepted; flood cancellation within 14 calendar days (E-4.4-03)." });
  o("SM_EXPENSE_CLAIM_TARGET_20", { trigger: "`claim.milestone.reached`", why: "§15.2 timer table: milestone → internal expense claim target 20 calendar days." });
  o("SM_P360_PSA_INTERNAL_10", { trigger: "`p360.claim.status_changed{status=psa}`", anchorField: "psa_at", why: "§15.2 timer table: PSA → internal response target 10 calendar days." });
  o("SM_P360_ACH_MATCH_3BD", { trigger: "`p360.claim.status_changed{status=paid}`", anchorField: "paid_at", why: "§15.2 timer table: claim `Paid` → ACH matched within 3 `business_days_fannie_et` (+2 BD tolerance)." });
  o("MI_MP_LATE_DENY_120", { trigger: "`liquidation_facts.processed{mi_insured=true}`", anchorField: "claim_anchor_date", why: "§15.3 timer table: claim_anchor_date + 120 calendar days → insurer may deny late claims (master policy)." });
  o("MI_MP_SETTLEMENT_60", { trigger: "`mi.claim.perfected`", anchorField: "perfected_at", offset: "+60 calendar_days", why: "§15.3 timer table: `perfected_at` → `settlement_days` calendar days (master policy default 60)." });
}
