/**
 * Registry overrides for Section 10 (mortgage insurance) timers whose spec
 * rows are prose, name a template the column grammar drops, list alternative
 * events (the pattern grammar has no `or`), or anchor on a payload field the
 * row names differently from the event.
 *
 * Event vocabulary the §10 tools emit for these rows (src/app/tools/section10.ts):
 *   `mi.coverage.ended{kind∈{cancelled, terminated}, effective, premium_stop_from, escrowed}` — companion of the
 *     canonical `mi.cancelled` / `mi.terminated` events (10.2 R4 "On `mi.terminated`/`mi.cancelled` with effective
 *     date E"), so the rows written "`mi.terminated` / `mi.cancelled`" arm on either.
 *   `mi.auto_termination.resolved{trigger, outcome∈{terminated, deferred_not_current, not_applicable}}` — the sweep's
 *     decision (10.2 state machine `auto_status`), the row's "`mi.terminated` or `mi.auto.deferred_not_current`".
 *   `mi.ny_premium_gate.resolved{outcome∈{terminated, premium_borne_by_servicer}}` — the row's "`mi.terminated` or
 *     `mi.premium.borne_by_servicer`" (N.Y. Ins. Law §6503(d); 10.2-Q2).
 *   `notice.sent{template=…}` — the Notice Registry's send event (src/notices/service.ts carries the code as `template`).
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

const ANNUAL_VARIANTS = "template∈{NTC_HPA_4903A3_ANNUAL, NTC_HPA_4903A3_ANNUAL_MN, NTC_HPA_4903A3_ANNUAL_CA, NTC_HPA_4903B_ANNUAL_LEGACY, NTC_FNMA_MI_ANNUAL_INFO}";

export function applyPmiTimerOverrides(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // ---- 10.1 borrower-requested cancellation ----------------------------------
  o("HPA_4904B_DENIAL_NOTICE_30", { anchorField: "received_at", satisfied: "`notice.sent{template∈{NTC_HPA_4904B_DENIAL, NTC_HPA_4904A_CANCELLED}}`", why: "§10.1/10.6 timer tables: anchor 'later of received_at, evidence-satisfied date' (re-anchoring on borrower evidence is computed by `decisionDue`); satisfied by '`notice.sent` (`NTC_HPA_4904B_DENIAL` or `NTC_HPA_4904A_CANCELLED`)' — 10.1-T1 'satisfied by the cancellation notice', 10.1-T2 'satisfied on send' (12 U.S.C. 4904(b))." });
  o("HPA_4902A4_EVIDENCE_DISCLOSURE_2BD", { satisfied: "`notice.sent{template=NTC_HPA_4902A_ACK_EVIDENCE}`", why: "§10.1 timer table: '`notice.sent` (`NTC_HPA_4902A_ACK_EVIDENCE`)' (12 U.S.C. 4902(a)(4)(A) 'promptly upon receipt')." });
  o("HPA_4902E_STOP_PREMIUM_30", { trigger: "`mi.coverage.ended`", anchorField: "premium_stop_from", satisfied: "`mi.premium.collection.stopped{mi_line_closed=true}`", why: "§10.1 timer table: trigger `mi.cancelled`, §10.2: `mi.terminated` — both publish `mi.coverage.ended`; anchor 'later of received_at, evidence-satisfied date' (4902(e)(1)) or the effective date (4902(e)(2)) carried as `premium_stop_from`; satisfied '`escrow.line.closed` (MI) ∧ `mi.premium.collection.stopped`' — the stop event is emitted after the MI line closes and carries `mi_line_closed=true`." });
  o("FNMA_F102_VALUATION_FEE_GATE", { satisfied: "`mi.evidence.received{kind=fee}`", why: "§10.1 timer table: the gate holds `smdu.valuation.order` until the borrower-paid fee is posted (F-1-02); the fee receipt opens it." });
  o("SM_MI_FEE_WAIT_60", { satisfied: "`mi.evidence.received{kind=fee}`", why: "§10.1 timer table: '`mi.evidence.received` (fee)' — only the valuation fee ends the wait; the case expires otherwise." });
  o("FNMA_SMDU_DATA_CORRECTION_30", { trigger: "`mi.evaluation.completed{servicer_overridden=true}`", satisfied: "`investor_events.acked{type=mi_data_correction}`", why: "§10.1 timer table: trigger '`mi.evaluation.completed` with servicer-overridden data' (SMDU FAQ: corrections reported within 30 days; 10.1-T11); satisfied '`investor_event.acked` (data correction)' in Section 5.1's `investor_events.acked{type=…}` vocabulary." });
  o("FNMA_B8104_DENIAL_NOTICE_30", { anchorField: "delivered_at", satisfied: "`notice.sent{template=NTC_HPA_4904B_DENIAL}`", why: "§10.1/10.6 timer tables: anchor 'later of received_at, delivered_at' (delivery is always the later); satisfied '`notice.sent` (`NTC_HPA_4904B_DENIAL`)' (B-8.1-04 current-value denial within 30 days of the valuation)." });
  o("MN_47_207_RESPONSE_30", { trigger: "`mi.cancel.requested{state=MN, owner_occupied=true}`", satisfied: "`notice.sent{template∈{NTC_HPA_4904A_CANCELLED, NTC_MI_INFO_REQUEST, NTC_HPA_4904B_DENIAL}}`", why: "§10.1/10.6 timer tables: kind 'jurisdiction override, state MN, owner-occupied' — armed only for MN owner-occupied requests; 'approve / request-info / deny notice sent' within 30 days of receipt (Minn. Stat. §47.207 subd. 4); 10.6-T6 'the MN timer is satisfied' by `NTC_MI_INFO_REQUEST`." });
  o("MI_INSURER_CANCEL_NOTICE_45", { trigger: "`mi.coverage.ended`", anchorField: "effective", satisfied: "`integration_messages.acked{kind=insurer_cancel}`", why: "§10.1 timer table: trigger `mi.cancelled`, §10.2 'as 10.1' on `mi.terminated` — both publish `mi.coverage.ended`; anchor 'effective date'; satisfied '`integration_messages.acked` (insurer cancel)' — `mi_insurer.cancel` emits it on the insurer's acceptance (MGIC 45-day refund look-back)." });
  o("SM_MI_INSURER_CANCEL_TARGET_2BD", { trigger: "`mi.coverage.ended`", anchorField: "effective", satisfied: "`integration_messages.acked{kind=insurer_cancel}`", why: "§10.1 timer table: 'same' as MI_INSURER_CANCEL_NOTICE_45 — the insurer's cancellation ack within 2 BD of the effective date (policy)." });
  // ---- 10.2 / 10.3 automatic termination ---------------------------------------
  o("HPA_4902B_AUTO_TERMINATE_0", { trigger: "`mi.schedule.updated{rule_78_applies=true, bpmi=true}`", satisfied: "`mi.auto_termination.resolved{outcome∈{terminated, deferred_not_current, not_applicable}}`", why: "§10.2 timer table: trigger 'schedule computed (`mi.schedule.updated`)' for loans the 78% rule reaches (R1; 10.2-T5 midpoint-only loans get no 78% clock; LPMI gets the 4905(c)(2) notice instead); satisfied '`mi.terminated` or `mi.auto.deferred_not_current`' — the sweep's resolution event carries the `auto_status` outcome (state machine: cancelled earlier by 10.1/10.3/insurer → `not_applicable`)." });
  o("HPA_4904B2B_AUTO_NOT_CURRENT_NOTICE_30", { anchorField: "scheduled_date", satisfied: "`notice.sent{template=NTC_HPA_4904B_AUTO_NOT_CURRENT}`", why: "§10.2/10.3/10.6 timer tables: anchor 'scheduled termination date' / `midpoint_termination_date` (the sweep's `scheduled_date`); satisfied '`notice.sent` (`NTC_HPA_4904B_AUTO_NOT_CURRENT`)' (12 U.S.C. 4904(b)(2))." });
  o("HPA_4904A_TERMINATION_NOTICE_30", { trigger: "`mi.coverage.ended`", anchorField: "effective", satisfied: "`notice.sent{template=NTC_HPA_4904A_CANCELLED}`", why: "§10.2 timer table: trigger '`mi.terminated` / `mi.cancelled`' (both publish `mi.coverage.ended`); anchor 'effective date'; satisfied '`notice.sent` (`NTC_HPA_4904A_CANCELLED`)' (12 U.S.C. 4904(a))." });
  o("HPA_4902F1_REFUND_45", { trigger: "`mi.coverage.ended`", anchorField: "effective", satisfied: "`mi.refund.paid{payee=borrower}`", why: "§10.2/10.5 timer tables: trigger '`mi.terminated` / `mi.cancelled`' (both publish `mi.coverage.ended`); anchor 'effective date'; satisfied '`mi.refund.paid` (all legs with amount > 0)' — `disbursements.issue` emits it only for a completed borrower disbursement (credited ACH or mailed check; 10.5-T8) (12 U.S.C. 4902(f)(1))." });
  o("SM_MI_LAR89_INTERNAL_TARGET_NEXTBD_2000", { trigger: "`mi.coverage.ended`", anchorField: "effective", satisfied: "`investor_events.queued{legacy_record=89}`", why: "§10.2 timer table: trigger '`mi.terminated` / `mi.cancelled`' (both publish `mi.coverage.ended`); 'LAR 89 queued to fnma-lsdu' — `investor_events.emit` queues the LAR 89 as `investor_events.queued` (Section 5.1 vocabulary; policy buffer, never a Fannie Mae deadline)." });
  o("HPA_4905C2_LPMI_OPTIONS_NOTICE_30", { trigger: "`mi.lpmi_equivalent_termination_date.reached`", anchorField: "equivalent_termination_on", satisfied: "`notice.sent{template=NTC_HPA_4905C2_LPMI_OPTIONS}`", why: "§10.2 timer table: `lpmi_equiv_termination_date` reached (the sweep emits it for LPMI policies) → options notice within 30 calendar days of 'that date' (12 U.S.C. §4905(c)(2)); satisfied '`notice.sent` (`NTC_HPA_4905C2_LPMI_OPTIONS`)'." });
  o("NY_INS_6503D_STOP_PREMIUM_75", { trigger: "`mi.ltv_snapshot{state=NY, ltv_bps<=7500}`", anchorField: "snapshot_date", satisfied: "`mi.ny_premium_gate.resolved{outcome∈{terminated, premium_borne_by_servicer}}`", why: "§10.2 timer table: nightly LTV snapshot with actual UPB ≤ 75% × original appraised value → stop premium (N.Y. Ins. Law §6503(d)); satisfied '`mi.terminated` or `mi.premium.borne_by_servicer`' — the gate's resolution event (10.2-Q2: carry at corporate expense until 10.1 terminates)." });
  o("HPA_4902C_MIDPOINT_TERMINATE_0", { trigger: "`mi.schedule.updated{bpmi=true}`", satisfied: "`mi.auto_termination.resolved{outcome∈{terminated, deferred_not_current, not_applicable}}`", why: "§10.3 timer table: `mi.schedule.updated` anchored on `midpoint_termination_date` for borrower-paid policies (4905(b): LPMI is outside 4902); satisfied '`mi.terminated` or `mi.auto.deferred_not_current`' — the sweep's resolution event." });
  o("SM_MI_MIDPOINT_PREVIEW_90", { trigger: "`mi.schedule.updated`", anchorField: "midpoint_termination_date", offset: "−90 calendar_days", why: "§10.3 timer table: preview 90 days before `midpoint_termination_date` (data completeness check)." });
  o("SM_MI_ORIGINAL_VALUE_MISSING_60", { satisfied: "`mi.original_value.set`", why: "§10.2 timer table: '`mi.original_value.set`' — `pmi.*` set_original_value emits it with the evidence document (alongside the 10.1 data-model `mi.original_value.corrected`)." });
  // ---- 10.4 annual disclosure ----------------------------------------------------
  o("HPA_4903A3_ANNUAL_DISCLOSURE_12M", { satisfied: `\`notice.sent{${ANNUAL_VARIANTS}}\``, why: "§10.4 timer table: '`notice.sent` (`NTC_HPA_4903A3_ANNUAL` or legacy/state variant)' — a periodic statement or any other notice on the loan does not satisfy the 12-month clock (12 U.S.C. 4903(a)(3))." });
  o("SM_MI_FIRST_DISCLOSURE_POST_BOARDING_60", { satisfied: `\`notice.sent{${ANNUAL_VARIANTS}}\``, why: "§10.4 timer table: '`notice.sent`' of the first annual disclosure (any HPA/state/Fannie Mae variant) within 60 days of boarding (10.4-T8)." });
  o("MN_47_207_ANNUAL_NOTICE_12M", { trigger: "`mi_policy.activated{state=MN}`", satisfied: "`notice.sent{template=NTC_HPA_4903A3_ANNUAL_MN}`", why: "§10.4 timer table: 'same as HPA timer' — MN-variant annual notice every 12 months; satisfied 'MN-variant notice sent' (Minn. Stat. §47.207 subd. 3)." });
  o("SM_MI_DISCLOSURE_COMPOSE_LEAD_30", { trigger: "`mi.disclosure.due_approaching{elapsed_pct>=70}`", anchorField: "disclosure_due_on", offset: "−30 calendar_days", why: "§10.4 timer table: recurring timer at 70% elapsed → compose 30 calendar days before due." });
  o("CA_2954_6_NOTICE_WITH_STATEMENT", { satisfied: "`notice.sent{template=NTC_HPA_4903A3_ANNUAL_CA}`", why: "§10.4 timer table: 'CA-variant PMI notice attached' — the CA variant is sent with the §2954.2 statement through the Notice Registry (Cal. Civ. Code §2954.6)." });
  // ---- 10.5 refund -----------------------------------------------------------------
  o("HPA_4902F2_INSURER_REFUND_30", { anchorField: "notified_on", satisfied: "`mi.insurer.refund_received`", why: "§10.5 timer table: anchor 'notification date' (`mi_insurer.cancel` carries `notified_on`); satisfied `mi.insurer.refund_received` — `custodial.match` emits it when the insurer's credit matches the refund case (12 U.S.C. 4902(f)(2))." });
  o("SM_MI_REFUND_ADVANCE_40", { trigger: "`mi.coverage.ended`", anchorField: "effective", satisfied: "`mi.refund.paid{payee=borrower}`", why: "§10.5 timer table: trigger '`mi.terminated` with insurer funds not received' (armed with the coverage end; the borrower payment satisfies it whether funded by the insurer or a corporate advance); anchor 'effective date'." });
  o("SM_MI_REFUND_VARIANCE_5BD", { trigger: "`mi.insurer.refund_received{variance_exceeds_tolerance=true}`", anchorField: "received_at", satisfied: "`mi.refund.variance_resolved`", why: "§10.5 timer table: trigger '`mi.insurer.refund_received` with variance > $1.00' (R2 tolerance); satisfied 'variance resolved' — `mi_insurer.refund_status` resolve_variance emits it." });
  o("SM_MI_ESCROW_INTERIM_ANALYSIS_10BD", { trigger: "`mi.coverage.ended{escrowed=true}`", anchorField: "effective", satisfied: "`escrow.analysis.completed{kind=interim}`", why: "§10.5 timer table: trigger '`mi.terminated` (escrowed loan)'; satisfied '`escrow.analysis.completed` (interim)' — `escrow.interim_analysis.request` emits it with the analysis date (R6)." });
  o("LL_2026_05_ESCROW_EVENT_3AM", { trigger: "`mi.refund.posted{escrow_event=true}`", anchorField: "posted_on", offset: "next business_days_fannie_et at 03:00 ET", satisfied: "`escrow.event.accepted`", why: "§10.5 timer table: refund deposit/disbursement posted (from Dec. 1, 2026 — `refundEscrowEvents`) → escrow event acked next `business_days_fannie_et` 03:00 ET (LL-2026-05); satisfied in Section 3.7/5's `escrow.event.accepted` vocabulary." });
  // ---- 10.6 denial ------------------------------------------------------------------
  o("SM_MI_DENIAL_SEND_5BD", { trigger: "`mi.evaluation.completed{result=ineligible}`", satisfied: "`notice.sent{template=NTC_HPA_4904B_DENIAL}`", why: "§10.6 timer table: trigger '`mi.evaluation.completed` (ineligible)' anchored on `determined_at`; satisfied 'notice sent' (`NTC_HPA_4904B_DENIAL`)." });
}

/** Kept for callers that only need the satisfaction overrides; `applyPmiTimerOverrides` applies everything. */
export function applyPmiSatisfiedOverrides(reg: TimerRegistry): void { applyPmiTimerOverrides(reg); }
