// 27.1 Warehouse facility mechanics: advance requests, wet/dry funding limits, collateral control (bailee letters, interim funder, UCC), aging and curtailments, interest/fees, kick-outs and repurchases, borrowing-base and covenant monitoring
// spec/sections/27-warehouse-funding-and-settlement-economics-supermortgage-as/27-1-warehouse-facility-mechanics-advance-requests-wet-dry-fundin.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("27.1-T1: Given the fixture refinance with `funding.authorized` at 08:12 ET Thu Nov 12, 2026, all hard criteria passing and Secured Party confirmed Nov 9, when the `warehouse` agent evaluates, then the advance is approved within 2 business hours with `advance_cents = 54,880,000`, `partner_contribution_cents = 844,957`, `collateral_status = secured_control`, and the wire is released only after `funding_approver` approval.", { todo: true });
test("27.1-T2: Given the same request but `compliance.gate.opened{gate=disbursement}` absent, then the advance is rejected with reason `disbursement_gate_closed` and no wire is prepared; given `wire_verifications.match_result = changed`, then rejected with `wire_verification_failed`.", { todo: true });
test("27.1-T3: Given the fixture advance funded Nov 12 with SOFR 4.30% and spread 2.50%, when 7 daily accruals run, then postings are 103.66, 103.66, 103.67, 103.66, 103.66, 103.66, 103.67 cents\u00d7100 and `interest_accrued_cents = 72,564` on Nov 19 before repayment; a per-diem-rounding implementation (72,562) fails.", { todo: true });
test("27.1-T4: Given the purchase fixture funded wet on Wed Nov 18, 2026 with a paper note, then `SM_WH_WET_NOTE_DELIVERY_5BD.due_at` = Wed Nov 25, 2026 (Thanksgiving excluded); a trust receipt on Fri Nov 20 satisfies it and sets `secured_possession`; no receipt by Nov 25 sets `wet_overdue`, +100 bps from Nov 26, and a full-repayment curtailment due at day 10.", { todo: true });
test("27.1-T5: Given a wet-state paper advance with the MIN registered without SM's Interim Funder Org ID, then `SM_WH_INTERIM_FUNDER_DESIGNATION_7` breaches at note date + 7 calendar days, the advance is marked ineligible in the next borrowing-base snapshot, and an escalation to `post-closing` and `signing_officer{partner}` is opened.", { todo: true });
test("27.1-T6: Given a bailee letter whose `letter_name` differs from `warehouse_facilities.bailee_letter_name` by one character, when `issueBaileeLetter` runs, then rendering is refused; given a letter whose `wire_instructions_hash` \u2260 the partner's Form 482 payee-code hash for SM, then refused with `form_482_mismatch`.", { todo: true });
test("27.1-T7: Given the fixture advance unpurchased at day 45 (Sun Dec 27, 2026), then a curtailment of $54,880.00 is due Mon Dec 28, the step-up applies from Dec 28 (day 46), and the payoff computed for a Tue Jan 5, 2027 purchase is $499,514.71; unpaid at day 60 (Mon Jan 11, 2027), then a repurchase demand of $500,115.64 is issued with `SM_WH_REPURCHASE_PAYMENT_5BD.due_at` = Tue Jan 19, 2027.", { todo: true });
test("27.1-T8: Given an eNote advance where the partner initiates the Transfer of Control and Location to Fannie Mae on Nov 17, when SM confirms as Secured Party and the registry accepts, then `collateral_status = transferred_pending_payment`, `enotes.secured_party_released_at` is set from the registry notification, and the advance remains in the borrowing base (Funding Agreement); when Fannie Mae later returns Control, then `secured_control` again and a defect is recorded.", { todo: true });
test("27.1-T9: Given facility limit $50,000,000, wet sublimit 40%, wet outstanding $19,800,000, when a $403,760 wet advance is requested, then it is rejected for `wet_sublimit_exceeded` while an eNote advance with Secured Party confirmed of the same size is approved.", { todo: true });
test("27.1-T10: Given a best-efforts commitment re-priced to 99.500 for a pledged loan with outstanding $548,800, when the borrowing base runs, then `collateral_value_cents` = 98% \u00d7 99.5% \u00d7 $560,000 = $546,056.00, a margin call of $2,744.00 is issued, and `SM_WH_MARGIN_CALL_1BD` is opened.", { todo: true });
test("27.1-T11: Given the partner's quarterly package arrives 50 days after quarter end, then `SM_WH_COVENANT_QUARTERLY_45` breaches, `warehouse.covenant.breached{reporting}` fires, the facility is `suspended` for new advances, and existing advances continue to accrue and repay normally.", { todo: true });
test("27.1-T12: Given any attempt by the `warehouse` agent to call the bank wire API without a `funding_approver` approval record, or to issue a kick-out without an `officer{sm}` acknowledgment, then the platform refuses the call and logs a guardrail violation.", { todo: true });
