// 27.2 Purchase-proceeds settlement, warehouse payoff, gain-on-sale computation and the borrower rate pass-through (Grander economics), MSR accounting hand-off to the partner
// spec/sections/27-warehouse-funding-and-settlement-economics-supermortgage-as/27-2-purchase-proceeds-settlement-warehouse-payoff-gain-on-sale-c.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("27.2-T1: Given the fixture loan delivered Nov 16, certified Nov 18 and the Sellers API advice dated Thu Nov 19, 2026 showing gross $567,700.00, LLPA $700.00 and interest due Fannie Mae $1,096.67, when the bank credits $565,903.33 with value date Nov 19, then the three-way match succeeds with `variance_cents = 0`, `interest_convention_observed = a_30_360`, and `SM_WH_PROCEEDS_MATCH_SAME_DAY` is satisfied.", { todo: true });
test("27.2-T2: Given the same advice but the credited amount $565,918.36, when matching runs with `fnma_interest_convention = unresolved`, then the variance $15.03 is classified `convention_cents` and the match is `matched_with_variance` with convention B recorded; given the partner is already locked to A, then `exception{convention_changed}` and an `officer{sm}` escalation.", { todo: true });
test("27.2-T3: Given the matched receipt of $565,903.33 and the 27.1 payoff statement $549,550.64, when the waterfall posts, then SM cost recovery = $3,485.00, SM retained = $2,815.00, partner residual = $10,052.69, `warehouse.advance.repaid{repaid_from=purchase_proceeds}` is emitted with repaid_at = Nov 19, and the residual wire is scheduled for Fri Nov 20 pending `funding_approver` approval.", { todo: true });
test("27.2-T4: Given the purchase fixture purchased Wed Dec 2, 2026 with LPI Dec 1, then the forecast interest is +$70.10 (due lender, convention A) and net $416,190.10; the partner residual is $7,732.38; `SM_WH_BAILEE_RELEASE_SAME_DAY.due_at` = Dec 2 and `SM_WH_INTERIM_FUNDER_RELEASE_2BD.due_at` = Fri Dec 4, 2026.", { todo: true });
test("27.2-T5: Given an advice with LLPA $1,400.00 against a forecast of $700.00, then `proceeds.exception{kind=llpa}` is raised, the warehouse is still repaid in full, the partner residual is reduced by $700.00, `ppa_requests{kind=data_correction, channel=lsdu}` is prepared for `fnma_portal_operator{party=partner}`, and `FNMA_C2_2_05_PPA_REQUEST_30.due_at` = Sat Dec 19, 2026 (no business-day roll; the platform targets Fri Dec 18).", { todo: true });
test("27.2-T6: Given a discount execution netting $542,103.33 against a payoff of $549,550.64, then `shortfall_cents = 744,731`, `SM_WH_SHORTFALL_DRAFT_2BD.due_at` = Mon Nov 23, 2026, SM's cost recovery becomes a partner receivable, and no partner residual wire is created.", { todo: true });
test("27.2-T7: Given example A settled Nov 19, when `SM_GOS_POST_1BD` runs, then `gain_on_sale_computations.actual.partner_origination_result_cents = \u22126,188`, `rate_passthrough_reconciliations.surplus_cents = 0`, `status = reconciled`, evidence ids include the quote solve trace, lock, final CD, note and advice; given example B (price 100.875), then the partner result is again \u2212$61.88 and `sm_retained_residual_cents = 1,500`.", { todo: true });
test("27.2-T8: Given example A, when the MSR hand-off is issued, then the payload contains exactly the rule-8 fields with UPB 56,000,000 cents, PTR 0.05875, servicing fee 25, remittance `aa`, purchase date 2026-11-19, first payment 2027-01-01, LPI 2026-12-01, P&I 340,262, platform fee 12.5 \u2014 and no valuation field.", { todo: true });
test("27.2-T9: Given purchase on Nov 19, 2026, when the monthly platform-fee accrual runs Dec 1, then November's fee is $23.33 (12/30 \u00d7 $58.33) and December's is $58.33; given the Jan 1, 2027 payment reduces UPB to $559,455.71, then February's fee is $58.28.", { todo: true });
test("27.2-T10: Given a receipt with no advice by 14:00 ET whose amount equals the forecast within $100, then a provisional match is created and confirmed when the advice arrives; given no advice by the next business day, then `proceeds.exception{kind=missing_advice}` and a Connect-report fallback task for `fnma_portal_operator`.", { todo: true });
test("27.2-T11: Given the nightly GL export at 20:00 ET, then every ledger entry created that day appears exactly once across `sm_gl` and `partner_gl` batches with balanced control totals; a re-run produces no duplicate lines.", { todo: true });
test("27.2-T12: Given a payoff of the fixture loan on Feb 15, 2027 (within 120 days of Nov 19, 2026), when Fannie Mae's recapture assessment of $7,700.00 arrives, then `premium_recapture.assessed` posts the partner-mirror reversal, `recapture_exposure_cents` closes, and SM's cost recovery is unchanged.", { todo: true });
