/**
 * Registry overrides for Section 12 (loss mitigation) timers whose spec rows
 * are prose. Eligibility criteria and plan-term caps are evaluator-backed;
 * "first of next month if sent ≤15th" style anchors are computed fields.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applyLossmitTimerOverrides(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // ---- 12.1 applications ---------------------------------------------------
  o("REGX_1024_41B1_DILIGENCE_FOLLOWUP_7", { trigger: "`lossmit.application.status_changed{status=incomplete}`", anchorField: "last_contact_on", why: "§12.1 timer table: incomplete application → follow-up every 7 calendar days from last contact (§1024.41(b)(1) reasonable diligence)." });
  o("SM_LM_DOC_STALENESS_SWEEP", { trigger: "`schedule.tick{cadence=daily}`", offset: "daily", why: "§12.1 timer table: daily sweep — income docs stale at 90 calendar days (180 disaster); `12.1.documentStale` decides per document." });
  // ---- 12.2 evaluation -----------------------------------------------------
  o("CA_CIV_2923_6E_NOD_NOS_HOLD_31", { trigger: "`notice.provided{kind=denial, state=CA}`", anchorField: "provided_at", why: "§12.2 timer table: CA denial provided → NOD/NOS hold 31 calendar days (or 15 after appeal denial / 14 after post-appeal offer declined) (Cal. Civ. Code §2923.6(e))." });
  o("FNMA_E3401_POST_NOTICE_LEGAL_DELAY_14", { trigger: "`notice.provided{kind=evaluation, principal_residence=true, in_foreclosure=true}`", why: "§12.2 timer table: Evaluation Notice provided (principal residence, in foreclosure) → no legal action for 14 calendar days (E-3.4-01)." });
  o("NY_419_7G_ACCEPT_30", { trigger: "`lossmit.offer.sent{state=NY, tier=ge_90}`", why: "§12.2 timer table: offer, NY loan, tier ge_90 → 30 calendar days to accept (3 NYCRR 419.7(g))." });
  o("REGX_1024_41E1_ACCEPT_7", { trigger: "`lossmit.offer.sent{tier=gt_37}`", why: "§12.2 timer table: offer and tier gt_37 (<90) → 7 calendar days (+ grace 3) (§1024.41(e)(1))." });
  o("REGX_1024_41E2II_TRIAL_OTHER_REQS_REASONABLE", { trigger: "`lossmit.trial.first_payment_received{acceptance_items_missing=true}`", anchorField: "payment_date", why: "§12.2 timer table: first trial payment received but other acceptance items missing → 14 calendar days (policy 'reasonable period', §1024.41(e)(2)(ii))." });
  o("REGX_1024_41F2_G_HOLD", { trigger: "`lossmit.application.facially_complete{tier∈{gt_37, ge_90}}`", why: "§12.2 timer table: facially complete / complete (tier gt_37/ge_90) → hold until (g)(1)–(3) condition; `lossmit.application.completed` arms the same code (§1024.41(f)(2), (g))." });
  o("REGX_1024_41G3_COUNSEL_INSTRUCTION_1BD", { trigger: "`foreclosure_holds.opened{in_foreclosure=true}`", why: "§12.2 timer table: hold set on a loan in foreclosure → counsel instruction acknowledged within 1 `business_days_servicer` (§1024.41(g)(3))." });
  // ---- 12.3 appeals --------------------------------------------------------
  o("CA_CIV_2923_6D_APPEAL_WINDOW_30", { trigger: "`notice.provided{kind=denial, state=CA, section_2924_15=true}`", why: "§12.3 timer table: CA §2924.15 loan denial → appeal window 30 calendar days (Cal. Civ. Code §2923.6(d))." });
  o("CA_CIV_2923_6E_POST_APPEAL_HOLD_15", { trigger: "`lossmit.appeal.decided{state=CA, outcome=denied}`", anchorField: "provided_at", why: "§12.3 timer table: CA appeal denied → hold 15 calendar days (or 14 after post-appeal offer declined) (Cal. Civ. Code §2923.6(e))." });
  o("FNMA_D2207_TPP_FIRST_DUE_15TH_RULE", { trigger: "`lossmit.appeal.decided{outcome=granted, tpp=true}`", anchorField: "tpp_first_due_date", offset: "0", why: "§12.3 timer table: first of next month if decision notice sent ≤15th; first of month after next if >15th — computed by `12.3.tppFirstDueDate` (D2-2-07)." });
  o("FNMA_E3401_APPEAL_COURT_DELAY_REQUEST_1BD", { trigger: "`lossmit.appeal.received{in_foreclosure=true}`", why: "§12.3 timer table: appeal received on a loan in foreclosure → counsel instruction within 1 `business_days_servicer` (E-3.4-01)." });
  o("NY_419_7H_APPEAL_WINDOW_14_POSTMARK", { trigger: "`notice.provided{kind=denial, state=NY}`", anchorField: "postmark_date", why: "§12.3 timer table: NY denial → appeal window 14 calendar days from postmark (3 NYCRR 419.7(h))." });
  o("REGX_1024_41H2_APPEAL_WINDOW_14", { trigger: "`notice.provided{kind=denial_modification}`", why: "§12.3 timer table: denial of modification with tier ge_90 or (f) period → 14 calendar days (§1024.41(h)(2))." });
  o("REGX_1024_41H4_ACCEPT_14", { trigger: "`notice.provided{kind=appeal_granted}`", why: "§12.3 timer table: appeal granted → 14 calendar days (+ policy grace 5) to accept (§1024.41(h)(4))." });
  o("SM_APPEAL_INDEPENDENCE_GATE", { trigger: "`lossmit.appeal.reviewer_assigned`", evaluator: "12.3.reviewerIndependent", why: "§12.3 timer table: reviewer assignment → independence check passed (§1024.41(h)(3))." });
  // ---- 12.4 forbearance ----------------------------------------------------
  o("FNMA_D23201_FORB_INCREMENT_MAX_3M", { evaluator: "12.4.incrementMax3Months", why: "§12.4 timer table: forbearance term months ≤3 per increment (D2-3.2-01)." });
  o("FNMA_D23201_FORB_MBS_MATURITY", { trigger: "`workout_plan.term.create{mbs=true}`", evaluator: "12.4.termEndBeforeLastScheduledPayment", why: "§12.4 timer table: MBS loans — term_end ≤ last scheduled payment date (D2-3.2-01)." });
  o("FNMA_D23201_FORB_PREEXPIRY_CADENCE", { trigger: "`workout_plan.expiry_approaching{days_before=30}`", offset: "every 3 calendar_days", why: "§12.4 timer table: from day −30 every 3 calendar days until QRPC or expiry (policy; D2-2-02 weekly minimum)." });
  o("FNMA_F121_STATUS_09_BD2", { trigger: "`period.month_end{workout_plan_active=true, plan_kind=forbearance}`", why: "§12.4 timer table: month-end with active plan → status 09 by BD2 (2 `business_days_fannie_et`) (F-1-21)." });
  o("FNMA_LL202601_FORB_CUMULATIVE_12M", { evaluator: "12.4.cumulativeMax12Months", why: "§12.4 timer table: cumulative forbearance ≤12 months from `initial_start_date` (LL-2026-01)." });
  o("FNMA_LL202601_FORB_DELQ_12M", { evaluator: "12.4.projectedDelinquencyMax12Months", why: "§12.4 timer table: projected `fnma_delinquency_status` at term end ≤12 months (LL-2026-01)." });
  // ---- 12.5 repayment plans -----------------------------------------------
  o("CA_CIV_2924_11D_LATE_FEE_BAR", { trigger: "`lossmit.evaluation.started{state=CA}`", evaluator: "12.5.californiaLateFeeBar", why: "§12.5 timer table: CA loan under evaluation/plan → no late fees (Cal. Civ. Code §2924.11(d)); `workout_plan.active{state=CA}` arms the same code." });
  o("FNMA_D23201_FORB_COMBINED_36M", { trigger: "`workout_plan.term.create{forbearance_component=true}`", evaluator: "12.5.combinedMax36Months", why: "§12.5 timer table: plan with forbearance component ≤36 months combined (D2-3.2-01)." });
  o("FNMA_D23202_REPAY_BRP_REQUIRED", { trigger: "`workout_plan.term.create{plan_kind=repayment}`", evaluator: "12.5.brpRequiredWhenLongOrDeep", why: "§12.5 timer table: BRP complete if `fnma_delinquency_status` >90 days or term >6 months (D2-3.2-02)." });
  o("FNMA_D23202_REPAY_PAYMENT_CAP_150", { trigger: "`workout_plan.term.create{plan_kind=repayment}`", evaluator: "12.5.paymentCap150", why: "§12.5 timer table: `expected_total ≤ 1.5 × contractual` (D2-3.2-02); modify arms the same code." });
  o("FNMA_D23202_REPAY_PAYMENT_EOM", { trigger: "`workout_plan_schedule.due_date`", offset: "last day of that month, 23:59 servicer-local", why: "§12.5 timer table: schedule row → received ≥ expected_total by last day of month 23:59 servicer-local (D2-3.2-02)." });
  o("FNMA_D23202_REPAY_TERM_MAX_12", { trigger: "`workout_plan.term.create{plan_kind=repayment}`", evaluator: "12.5.termMax12UnlessFnmaApproval", why: "§12.5 timer table: term ≤12 months unless `fnma_approval` (D2-3.2-02); extend arms the same code." });
  o("FNMA_F121_STATUS_12_BD2", { trigger: "`period.month_end{workout_plan_active=true, plan_kind=repayment}`", why: "§12.5 timer table: month-end with active plan → status 12 by BD2 (F-1-21)." });
  o("FNMA_F202_REPAY_INCENTIVE_CLAIM", { offset: "last day of next month", why: "§12.5 timer table: `workout_plan.completed` (60+ days delinquent at start) → incentive claim in the following month's cycle (F-2-02)." });
  // ---- 12.6 payment deferral ----------------------------------------------
  o("FNMA_B101_ESCROW_ANALYSIS_BEFORE_OFFER", { trigger: "`payment_deferral.offer_requested`", evaluator: "12.6.escrowAnalysisWithin30Days", why: "§12.6 timer table: offer/solicit requires analysis completed ≤30 days (policy; B-1-01)." });
  o("FNMA_D23204_CONTRACTUAL_PAYMENT_GATE", { trigger: "`payment_deferral.offer_requested{months_delinquent>=6}`", evaluator: "12.6.contractualPaymentInSolicitationMonth", why: "§12.6 timer table: 6 months delinquent at eval or cap-exceeding → full contractual payment received in solicitation/processing month (D2-3.2-04)." });
  o("FNMA_D23204_DEFERRAL_ELIGIBILITY_GATES", { trigger: "`payment_deferral.offer_requested`", evaluator: "12.6.eligibilityCriteria4to11", why: "§12.6 timer table: criteria 4–11 (delinquency 2–6 months via `fnma_delinquency_status`; seasoning ≥12; prior deferral ≥12; cumulative ≤12; maturity >36 months) (D2-3.2-04)." });
  o("FNMA_D23206_POSTDEFERRAL_FLEX_SOLICIT_75", { trigger: "`loan.delinquency.day_reached{fnma_day=60, post_deferral_within_6m=true, qrpc=false}`", anchorField: "day_60_date", offset: "+15 calendar_days", why: "§12.6 timer table: 60+ days delinquent within 6 months of deferral effective date, no QRPC → streamlined solicitation by day 75 (D2-3.2-06)." });
  o("FNMA_F202_DEFERRAL_INCENTIVE_CLAIM", { offset: "last day of next month", why: "§12.6 timer table: `smdu.case.completed` → incentive claim next claim cycle (F-2-02)." });
  o("SM_DEFERRAL_SOLICIT_ACCEPT_WINDOW", { trigger: "`solicitation_packages.sent{kind=payment_deferral}`", offset: "last day of that month", why: "§12.6 timer table: acceptance through the last day of the solicitation month (policy; ≥14 days)." });
  o("TX_50A6_DEFERRAL_NOTICE_7BD", { trigger: "`complaint.tx_50a6_defect.alleged`", why: "§12.6 timer table: borrower notice of §50(a)(6) violation (TX) → Form 20 to Fannie Mae Legal within 7 `business_days_servicer` (+60-day cure)." });
  // ---- 12.7 disaster deferral ----------------------------------------------
  o("FNMA_D23205_12M_CONTRACTUAL_PAYMENT_GATE", { trigger: "`payment_deferral.offer_requested{disaster=true, months_delinquent>=12}`", evaluator: "12.7.contractualPaymentInSolicitationMonth", why: "§12.7 timer table: 12 months delinquent at eval → full contractual payment in solicitation/processing month (D2-3.2-05)." });
  o("FNMA_D23205_AGREEMENT_SEND_5", { trigger: "`payment_deferral.accepted{disaster=true}`", anchor: "accepted_at", offset: "+5 business_days_servicer", satisfied: "`notice.sent{NTC_FNMA_D23205_DEFERRAL_AGREEMENT}`", why: "§12.7 timer table row is empty in the registry; D2-3.2-05 requires the deferral agreement be sent after acceptance — policy 5 `business_days_servicer` (documented in AUDIT-NOTES)." });
  o("FNMA_D23205_DDEFERRAL_ELIGIBILITY_GATES", { trigger: "`payment_deferral.offer_requested{disaster=true}`", evaluator: "12.7.disasterEligibility", why: "§12.7 timer table: disaster basis; current/<2 months at disaster (or approval); 1–12 months delinquent at eval; no same-event prior; maturity >36 months; no conflicting arrangements (D2-3.2-05)." });
  o("FNMA_D23205_POSTFORB_SOLICIT_15", { trigger: "`workout_plan.expired{plan_kind=disaster_forbearance, qrpc=false}`", anchorField: "term_end", why: "§12.7 timer table: disaster forbearance expired without QRPC → solicitation within 15 calendar days of `term_end` (D2-3.2-05)." });
  // ---- 12.8 Flex Modification ---------------------------------------------
  o("FNMA_B101_ESCROW_ESTABLISH_BEFORE_TRIAL", { anchorField: "first_trial_due_date", offset: "−1 calendar_days", why: "§12.8 timer table: escrow established/analysis completed before the first trial due date (B-1-01)." });
  o("FNMA_D2205_EVAL_NOTICE_TPP_5", { trigger: "`lossmit.evaluation.decided{outcome=tpp_offer}`", offset: "+5 business_days_servicer", why: "§12.8 timer table: 'as 12.2' — Evaluation Notice within 5 business days of decision (D2-2-05; REGX_1024_41C1_EVALUATE_30 bounds the complete-application leg)." });
  o("FNMA_D23102_MBS_RECLASS_BEFORE_EXECUTION", { trigger: "`tpp_completed{mbs=true}`", offset: "until smdu.case.reclassified", why: "§12.8 timer table: MBS loan `tpp_completed` → servicer execution gated until `smdu.case.reclassified` (D2-3.1-02)." });
  o("FNMA_D23206_FLEX_SOLICIT_90_105", { trigger: "`loan.delinquency.day_reached{fnma_day=90, brp_complete=false, sale_proximate=false}`", anchorField: "day_90_date", offset: "+15 calendar_days", why: "§12.8 timer table: day 90 → streamlined solicitation by day 105 (`fnma` day count) (D2-3.2-06)." });
  o("FNMA_D23206_FLEX_SOLICIT_STEP_60_75", { trigger: "`loan.delinquency.day_reached{fnma_day=60, step_rate_adjusted_within_12m=true}`", anchorField: "day_60_date", offset: "+15 calendar_days", why: "§12.8 timer table: step-rate adjusted within 12 months, 60+ days delinquent → solicit by day 75 (D2-3.2-06)." });
  o("FNMA_D23206_FORM3179_BORROWER_EXECUTE_BEFORE_EFFECTIVE", { trigger: "`lossmit.agreement.sent{form=3179}`", anchorField: "effective_date", why: "§12.8 timer table: Form 3179 sent → borrower executed and returned by effective date − 1 (D2-3.2-06)." });
  o("FNMA_D23206_FORM3179_SERVICER_EXECUTE_BEFORE_EFFECTIVE", { trigger: "`lossmit.agreement.borrower_executed{final_trial_payment_cleared=true}`", anchorField: "effective_date", why: "§12.8 timer table: borrower executed and final trial payment cleared (and reclass done for MBS) → servicer execution by effective date − 1 (D2-3.2-06)." });
  o("FNMA_D23206_SOLICIT_SALE_PROXIMITY_GATE", { trigger: "`solicitation_packages.send_requested{kind=flex_mod}`", evaluator: "12.8.noSaleWithinSolicitationWindow", why: "§12.8 timer table: no scheduled sale within 60 (`judicial`) / 30 (`non_judicial`) calendar days of evaluation (D2-3.2-06)." });
  o("FNMA_D23206_TPP_FIRST_DUE_15TH_RULE", { trigger: "`notice.provided{kind=evaluation, outcome=tpp_offer}`", anchorField: "tpp_first_due_date", offset: "0", why: "§12.8 timer table: first of next month if sent ≤15th, else first of month after next — computed by `12.8.tppFirstDueDate` (D2-3.2-06)." });
  o("FNMA_F122_TPP_PAYMENT_REPORT", { trigger: "`payment.applied{trial=true}`", why: "§12.8 timer table: each trial payment applied → SMDU TPP payment acked within 1 `business_days_fannie_et` (F-1-22)." });
  o("FNMA_F127_CUSTODIAN_25", { trigger: "`lossmit.agreement.executed_copy_received{form=3179}`", why: "§12.8 timer table: receipt of executed Form 3179 (recorded: certified copy; unrecorded: original) → custodian delivery within 25 calendar days (F-1-27)." });
  o("FNMA_F127_VALUATION_MAX_AGE_90", { trigger: "`smdu.case.submit_requested{kind=tpp}`", anchorField: "valuation_as_of", why: "§12.8 timer table: valuation `as_of` ≤90 calendar days at evaluation (F-1-27)." });
  o("FNMA_F202_FLEX_CLOSE_2M", { trigger: "`trial_plan_schedule.final_due_month_ended`", anchorField: "final_due_month_end", why: "§12.8 timer table: final trial payment due month → SMDU close with Officer Signature Date within +2 months of that month end (F-2-02)." });
  o("FNMA_IRM_MOD_LOAN_DATA_CHANGE", { trigger: "`lossmit.modification.effective`", anchorField: "effective_date", offset: "next business_days_fannie_et at 20:00 ET", why: "§12.8 timer table: per Investor Reporting Manual / 5.x — LAR 83 / loan data change by the reporting cycle (5.1 next-BD clock)." });
  // ---- 12.9 short sale / deed-in-lieu ------------------------------------
  o("CA_CIV_2924_11C_RESCIND_NOD", { trigger: "`shortsale.approved{state=CA, proof_of_funds=true}`", offset: "+5 business_days_servicer", why: "§12.9 timer table: CA short sale approved with proof of funds / permanent alternative executed → rescind NOD promptly (policy 5 BD) (Cal. Civ. Code §2924.11(c)); `lossmit.permanent_agreement.effective{state=CA}` arms the same code." });
  o("FNMA_D23301_MI_NON_DELEGATED_APPROVAL", { trigger: "`shortsale.evaluation.started{mi_delegated=false}`", evaluator: "12.9.miWrittenAgreement", why: "§12.9 timer table: non-delegated MI → written MI agreement (waive acquisition rights; settle at lesser of option/make-whole) (D2-3.3-01)." });
  o("FNMA_D23301_SS_CLOSE_60", { trigger: "`shortsale_offers.decided{decision=approved}`", why: "§12.9 timer table: approved → closing funds within 60 calendar days (D2-3.3-01)." });
  o("FNMA_D23301_SS_DECISION_30", { trigger: "`shortsale.offer.ready_for_decision`", anchorField: "later_of_brp_and_offer", why: "§12.9 timer table: complete BRP (if required) + initial offer → decision within 30 calendar days of the later (D2-3.3-01)." });
  o("FNMA_D23301_SS_LISTING_MLS_5D", { trigger: "`lossmit.shortsale.offer.received`", anchorField: "mls_active_date", evaluator: "12.9.listedFiveConsecutiveDays", why: "§12.9 timer table: ≥5 consecutive calendar days on MLS incl. Sat+Sun before offer review (D2-3.3-01)." });
  o("FNMA_D23301_SS_SETTLEMENT_REVIEW_48H", { trigger: "`shortsale.closed`", why: "§12.9 timer table: closing → settlement reviewed within 48 hours (D2-3.3-01)." });
  o("FNMA_D23302_DIL_DEED_BEFORE_SALE_30", { trigger: "`foreclosure.sale.scheduled{dil_pending=true}`", anchorField: "sale_date", offset: "−30 calendar_days", why: "§12.9 timer table: executed deed received ≥30 calendar days before scheduled sale/docket date (D2-3.3-02)." });
  o("FNMA_D23302_DIL_LIEN_RELEASE_30BD", { trigger: "`dil.accepted{vacant_secure_confirmed=true}`", why: "§12.9 timer table: acceptance + inspection confirms vacant/secure → lien release recorded within 30 `business_days_servicer` (D2-3.3-02)." });
  o("FNMA_D23302_DIL_RELOCATION_30", { trigger: "`dil.accepted{transition=false}`", why: "§12.9 timer table: executed deed accepted (non-transition) → relocation assistance disbursed within 30 calendar days (D2-3.3-02)." });
  o("FNMA_D23302_DIL_WEEKLY_UPDATE_7", { trigger: "`dil.extension.granted{beyond_60_days=true}`", why: "§12.9 timer table: extension beyond 60 days → update logged every 7 calendar days (D2-3.3-02)." });
  o("FNMA_E3401_SS_APPROVED_HOLD_60", { trigger: "`shortsale.approved`", why: "§12.9 timer table: approval / DIL acceptance → foreclosure hold 60 calendar days (+30 extension) (E-3.4-01); `dil.accepted` arms the same code." });
  o("FNMA_E3401_SS_MARKETING_HOLD", { trigger: "`lossmit.application.completed{path=short_sale, principal_residence=true, days_before_sale>=37}`", offset: "+60 calendar_days", why: "§12.9 timer table: 45-day submission window + 15-day review (E-3.4-01) = 60 calendar days marketing hold." });
  o("FNMA_F202_LIQUIDATION_INCENTIVE_CLAIM", { trigger: "`shortsale.closed`", offset: "last day of next month", why: "§12.9 timer table: closing / release → incentive claim next claim cycle; tier by delinquency days (F-2-02); `lien_release.recorded{dil=true}` arms the same code." });
  o("REGX_1024_41G3_SS_LISTING_PERFORMANCE", { trigger: "`shortsale.marketing.started{offered=true}`", why: "§1024.41(g)(3): listing period under an offered short sale → hold until listing period ends without an approved transaction." });
  // ---- pseudo-trigger rows -----------------------------------------------------
  o("FNMA_D2205_BRP_ACK_5BD", { trigger: "`lossmit.application.received`", anchorField: "received_date", why: "§12.1 timer table: 'same' as REGX_1024_41B2_LM_ACK_5 → `lossmit.application.received`; 5 `business_days_servicer` (D2-2-05)." });
  o("REGX_1024_41C4_THIRD_PARTY_HEIGHTEN_30", { trigger: "`lossmit.evaluation.started{third_party_items=true}`", anchorField: "complete_at", why: "§12.2 timer table: 'same' as REGX_1024_41C4_THIRD_PARTY_REQUEST_PROMPT; heightened diligence at 30 calendar days (§1024.41(c)(4))." });
  o("REGX_1024_41C4IIA2_SIGNIFICANT_PERIOD", { trigger: "`notice.sent{template=NTC_REGX_41C4IIB_THIRD_PARTY_DELAY}`", why: "§12.2 timer table: delay notice sent → 'significant period' 30 calendar days (policy) (§1024.41(c)(4)(ii)(A)(2))." });
  o("FNMA_D2207_APPEAL_DECIDE_30", { trigger: "`lossmit.appeal.received{eligible=true}`", why: "§12.3 timer table: 'same' as REGX_1024_41H4_APPEAL_DECIDE_30 → `lossmit.appeal.received` (eligible); 30 calendar days (D2-2-07)." });
  o("FNMA_LL202601_FORB_CUMULATIVE_12M", { trigger: "`workout_plan.term.create`", evaluator: "12.4.cumulativeMax12Months", why: "§12.4 timer table: 'same' as FNMA_D23201_FORB_INCREMENT_MAX_3M → `workout_plan.term.create` (LL-2026-01)." });
  o("FNMA_LL202601_FORB_DELQ_12M", { trigger: "`workout_plan.term.create`", evaluator: "12.4.projectedDelinquencyMax12Months", why: "§12.4 timer table: 'same' trigger (LL-2026-01)." });
  o("FNMA_D23201_FORB_EXPIRY_DISPOSITION", { trigger: "`workout_plan.term_end_reached`", why: "§12.4 timer table: `term_end` → disposition decided by expiry; executed within 15 days (D2-3.2-01)." });
  o("FNMA_D23204_PROCESSING_MONTH_ELECTION_15TH", { trigger: "`payment_deferral.evaluated`", offset: "15th", why: "§12.6 timer table: evaluation → processing-month election by the 15th of the evaluation month (D2-3.2-04)." });
  o("FNMA_D23204_CUSTODIAN_25", { trigger: "`payment_deferral.effective`", anchorField: "effective_date", why: "§12.6 timer table: `effective_date` → custodian delivery within 25 calendar days (D2-3.2-04)." });
  o("FNMA_D23205_DDEFERRAL_SMDU_ENTRY_EOM", { trigger: "`payment_deferral.accepted{disaster=true}`", offset: "last day of that month", why: "§12.7 timer table: acceptance → SMDU entry by the last day of the evaluation/processing month (D2-3.2-05)." });
  o("FNMA_B101_ESCROW_ESTABLISH_BEFORE_TRIAL", { trigger: "`lossmit.tpp.offered`", anchorField: "first_trial_due_date", offset: "−1 calendar_days", why: "§12.8 timer table: `tpp_offered` → escrow established before the first trial due date (B-1-01)." });
  o("FNMA_E3401_FC_SUSPEND_DURING_TRIAL", { trigger: "`lossmit.trial.started`", offset: "until lossmit.trial.ended", why: "§12.8 timer table: `tpp_active` → foreclosure suspended while performing (E-3.4-01)." });
  o("SM_FORM3179_SEND_BY_LAST_TRIAL_MONTH_1", { trigger: "`trial_payment.satisfied{penultimate=true}`", anchorField: "final_trial_month_start", why: "§12.8 timer table: penultimate trial payment met → Form 3179 sent by the 1st day of the final trial month (≥30 days before effective)." });
  o("FNMA_D23102_MBS_RECLASS_BEFORE_EXECUTION", { trigger: "`lossmit.trial.completed{mbs=true}`", offset: "until smdu.case.reclassified", why: "§12.8 timer table: `tpp_completed{mbs=true}` → gated until `smdu.case.reclassified` (D2-3.1-02)." });
  o("FNMA_F127_CAPITALIZATION_DATE", { trigger: "`lossmit.agreement.servicer_executed`", anchorField: "effective_date", why: "§12.8 timer table: `servicer_executed` → capitalization posted effective date − 1 month (F-1-27)." });
  o("FNMA_D23206_NO_NEW_TRIAL_12M", { trigger: "`lossmit.trial.failed`", anchorField: "failed_on", why: "§12.8 timer table: `tpp_failed` → no new trial for 12 months (D2-3.2-06)." });
  o("FNMA_F114_SS_VALUATION_MAX_AGE_90", { trigger: "`shortsale.approval_requested`", anchorField: "valuation_date", why: "§12.9 timer table: approval → valuation ≤90 calendar days old (F-1-14)." });
  applyLossmitSatisfiedOverrides(reg);
}

/** Satisfaction events / evaluators for the §12 rows whose "Satisfied by" column is prose, "same", or empty. */
export function applyLossmitSatisfiedOverrides(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // ---- 12.1 applications
  o("FNMA_D2205_BRP_ACK_5BD", { satisfied: "`notice.sent{code∈{NTC_REGX_41B2_ACK_COMPLETE, NTC_REGX_41B2_ACK_INCOMPLETE}}`", why: "§12.1 timer table: 'same notice (dual-cited template)' — the §1024.41(b)(2) acknowledgment carries the D2-2-05 BRP content." });
  o("NY_419_7D_ACK_5BD", { satisfied: "`notice.sent{code∈{NTC_REGX_41B2_ACK_COMPLETE, NTC_REGX_41B2_ACK_INCOMPLETE}, state=NY}`", why: "§12.1 timer table: 'ack notice with NY content' (3 NYCRR 419.7(d))." });
  o("REGX_1024_41B1_DILIGENCE_FOLLOWUP_7", { satisfied: "`lossmit.application.status_changed{status∈{complete, withdrawn, closed_incomplete}}`", why: "§12.1 timer table: 'status change' — follow-ups stop when the application completes, is withdrawn or is closed." });
  o("SM_LM_DOC_STALENESS_SWEEP", { evaluator: "12.1.documentStale", why: "§12.1 timer table: 're-request before staleness; stale status' — per-document evaluator (90 days income, 180 disaster)." });
  // ---- 12.2 evaluation
  o("REGX_1024_41C1_EVALUATE_NOTIFY_30", { satisfied: "`notice.provided{code∈{NTC_REGX_41C1_OFFER, NTC_REGX_41C1_DENIAL}}`", why: "§12.2 timer table: `notice.provided{NTC_REGX_41C1_OFFER | NTC_REGX_41C1_DENIAL}`." });
  o("FNMA_D2205_EVAL_NOTICE_5_AFTER_DECISION", { satisfied: "`notice.provided{code∈{NTC_REGX_41C1_OFFER, NTC_REGX_41C1_DENIAL}}`", why: "§12.2 timer table: 'same notice' as REGX_1024_41C1_EVALUATE_NOTIFY_30 (D2-2-05)." });
  o("REGX_1024_41C4_THIRD_PARTY_HEIGHTEN_30", { trigger: "`lossmit.application.completed{third_party_item_outstanding=true}`", satisfied: "`lossmit.third_party_item.received`", why: "§12.2 timer table: 'item received, or NTC_REGX_41C4IIB_THIRD_PARTY_DELAY sent + heightened-effort contact logged' — the delay-notice alternative is `ops.thirdPartyDelay` on the same clock (§1024.41(c)(4)(ii))." });
  o("REGX_1024_41C4IIA2_SIGNIFICANT_PERIOD", { trigger: "`notice.sent{code=NTC_REGX_41C4IIB_THIRD_PARTY_DELAY}`", satisfied: "`lossmit.third_party_item.received`", why: "§12.2 timer table: 'item received' (§1024.41(c)(4)(ii)(A)(2), policy 30 days)." });
  o("REGX_1024_41E1_ACCEPT_7", { trigger: "`lossmit.offer.sent{tier=lt_90}`", satisfied: "`lossmit.offer.responded{response∈{accepted, rejected}}`", why: "§12.2 timer table: 'same' — borrower acceptance or rejection of the offer (§1024.41(e)(1))." });
  o("NY_419_7G_ACCEPT_30", { satisfied: "`lossmit.offer.responded{response∈{accepted, rejected}}`", why: "§12.2 timer table: 'same' — acceptance/rejection (3 NYCRR 419.7(g))." });
  o("REGX_1024_41E2II_TRIAL_OTHER_REQS_REASONABLE", { trigger: "`lossmit.trial.first_payment_received{other_acceptance_items_missing=true}`", satisfied: "`lossmit.offer.acceptance_items.received`", why: "§12.2 timer table: 'items received' (§1024.41(e)(2)(ii); policy 14 days)." });
  o("CA_CIV_2923_6E_NOD_NOS_HOLD_31", { satisfied: "`timer.lapsed{code=CA_CIV_2923_6E_NOD_NOS_HOLD_31}`", why: "§12.2 timer table: 'timer lapse' — hold released by lapse only (Cal. Civ. Code §2923.6(e))." });
  o("FNMA_E3401_POST_NOTICE_LEGAL_DELAY_14", { satisfied: "`lossmit.offer.responded{response=accepted}`", why: "§12.2 timer table: 'lapse or acceptance' (E-3.4-01)." });
  // ---- 12.3 appeals
  o("CA_CIV_2923_6D_APPEAL_WINDOW_30", { trigger: "`notice.provided{code=NTC_REGX_41C1_DENIAL, state=CA}`", satisfied: "`lossmit.appeal.received`", why: "§12.3 timer table: 'same' as REGX_1024_41H2_APPEAL_WINDOW_14 — an appeal received in the window (Cal. Civ. Code §2923.6(d))." });
  o("NY_419_7H_APPEAL_WINDOW_14_POSTMARK", { trigger: "`notice.provided{code=NTC_REGX_41C1_DENIAL, state=NY}`", anchorField: "postmark_on", satisfied: "`lossmit.appeal.received`", why: "§12.3 timer table: 'same' — appeal received (3 NYCRR 419.7(h), postmark anchor)." });
  o("REGX_1024_41H4_APPEAL_DECIDE_30", { satisfied: "`notice.provided{code∈{NTC_REGX_41H4_APPEAL_GRANTED, NTC_REGX_41H4_APPEAL_DENIED}}`", why: "§12.3 timer table: `notice.provided{NTC_REGX_41H4_*}`." });
  o("FNMA_D2207_APPEAL_DECIDE_30", { trigger: "`lossmit.appeal.received{eligible=true}`", satisfied: "`notice.provided{code∈{NTC_REGX_41H4_APPEAL_GRANTED, NTC_REGX_41H4_APPEAL_DENIED}}`", why: "§12.3 timer table: 'same' as REGX_1024_41H4_APPEAL_DECIDE_30 (D2-2-07)." });
  o("REGX_1024_41E2III_ORIGINAL_OFFER_EXTENDED", { trigger: "`lossmit.appeal.received{original_offer_pending=true}`", anchorField: "appeal_notice_provided_on", satisfied: "`lossmit.offer.responded{response=accepted}`", why: "§12.3 timer table: 'acceptance' — the original offer stays open 14 days after the (h)(4) notice (§1024.41(e)(2)(iii))." });
  o("CA_CIV_2923_6E_POST_APPEAL_HOLD_15", { trigger: "`notice.provided{code=NTC_REGX_41H4_APPEAL_DENIED, state=CA}`", satisfied: "`timer.lapsed{code=CA_CIV_2923_6E_POST_APPEAL_HOLD_15}`", why: "§12.3 timer table: 'lapse' (Cal. Civ. Code §2923.6(e))." });
  o("FNMA_D2207_TPP_FIRST_DUE_15TH_RULE", { satisfied: "`lossmit.trial.schedule_created`", why: "§12.3 timer table: 'trial schedule created' — `12.8.tppFirstDue` computes the 15th-rule anchor (D2-2-07)." });
  // ---- 12.4 forbearance
  o("FNMA_D23201_FORB_PREEXPIRY_CONTACT_30", { satisfied: "`contact.attempted{purpose=forb_preexpiry}`", why: "§12.4 timer table: '`contact` attempt logged with `purpose=forb_preexpiry`' (D2-3.2-01)." });
  o("REGX_1024_41C2III_PERFORMANCE_HOLD", { trigger: "`workout_plan.activated`", satisfied: "`workout_plan.ended{status∈{terminated, expired, completed}}`", why: "§12.4/12.5 timer tables: '`workout_plan.terminated/expired`' (§1024.41(c)(2)(iii))." });
  o("REGX_1024_41B1_DILIGENCE_RESUME", { trigger: "`workout_plan.payment.missed`", offset: "0 calendar_days", satisfied: "`contact.attempted{purpose=lossmit_diligence}`", why: "§12.4 timer table: 'diligence contact logged' — resume immediately on a missed plan payment or assistance request (comment 41(b)(1)-4.iii)." });
  o("FNMA_F121_STATUS_09_BD2", { satisfied: "`investor.event.accepted{status_code=09}`", why: "§12.4 timer table: 'investor event accepted (5.x)' — delinquency status code 09 (F-1-21)." });
  o("FNMA_LL202601_FORB_EXCEPTION_RESPONSE", { trigger: "`fnma_exception_request.submitted`", satisfied: "`fnma_exception_request.decided`", why: "§12.4 timer table: 'decision recorded' (LL-2026-01; policy 10 BD follow-up)." });
  // ---- 12.5 repayment
  o("FNMA_D23202_REPAY_PAYMENT_EOM", { trigger: "`workout_plan_schedule.row_due`", satisfied: "`workout_plan.payment.received{covers_expected_total=true}`", why: "§12.5 timer table: '`received ≥ expected_total`' — `12.5.installmentMet` compares receipts to the schedule row (D2-3.2-02)." });
  o("FNMA_F121_STATUS_12_BD2", { satisfied: "`investor.event.accepted{status_code=12}`", why: "§12.5 timer table: 'investor event accepted (5.x)' — status code 12 (F-1-21)." });
  o("FNMA_F202_REPAY_INCENTIVE_CLAIM", { satisfied: "`investor.event.accepted{kind=incentive, workout=repayment_plan}`", why: "§12.5 timer table: '`investor_events{incentive}`' — the $500 claim in the following cycle (F-2-02)." });
  // ---- 12.6 deferral
  o("SM_DEFERRAL_SOLICIT_ACCEPT_WINDOW", { trigger: "`notice.sent{code∈{NTC_FNMA_D23204_SOLICIT_POST_FORB, NTC_FNMA_D23204_SOLICIT_POST_REPAY}}`", satisfied: "`payment_deferral.accepted`", why: "§12.6 timer table: 'acceptance' — window through the last day of the solicitation month (policy, ≥14 days)." });
  o("FNMA_F122_DEFERRAL_LAR_BEFORE_EOM_1BD", { satisfied: "`investor.event.accepted{kind=contractual_payments}`", why: "§12.6 timer table: 'contractual-payment LAR/event accepted (5.x FNMA_IRM_DEFERRAL_LAR_BEFORE_EOM_1BD)'." });
  o("FNMA_D23204_PROCESSING_MONTH_ELECTION_15TH", { trigger: "`lossmit.evaluation.decided{option=payment_deferral}`", satisfied: "`smdu.case.completed{workout=payment_deferral}`", why: "§12.6 timer table: 'completion or `processing_month=true`' — `12.6.processingMonthElected` covers the election (D2-3.2-04)." });
  o("FNMA_D23204_RECORDED_ORIGINAL_5BD", { satisfied: "`custodian.delivery.confirmed{document=recorded_original}`", why: "§12.6 timer table: 'custodian delivery of original' (D2-3.2-04 / F-1-27)." });
  o("FNMA_F202_DEFERRAL_INCENTIVE_CLAIM", { satisfied: "`investor.event.accepted{kind=incentive, workout=payment_deferral}`", why: "§12.6 timer table: '`investor_events{incentive}`' (F-2-02)." });
  // ---- 12.7 disaster deferral
  o("FNMA_D1301_DISASTER_FLEX_ROUTE", { satisfied: "`lossmit.evaluation.started{option=flex_mod, criteria=disaster}`", why: "§12.7 timer table: '12.8 evaluation started' — Flex Mod under the reduced disaster criteria (D1-3-01)." });
  // ---- 12.8 Flex Mod
  o("FNMA_D23206_FLEX_SOLICIT_STEP_60_75", { trigger: "`loan.delinquency.day_reached{day=60, step_rate_adjusted_within_12m=true}`", satisfied: "`notice.sent{code=NTC_FNMA_D23206_SOLICIT_STREAMLINED}`", why: "§12.8 timer table: 'same' as FNMA_D23206_FLEX_SOLICIT_90_105 — the streamlined solicitation letter by day 75 (D2-3.2-06)." });
  o("FNMA_F127_VALUATION_MAX_AGE_90", { evaluator: "12.8.valuationFresh90", why: "§12.8 timer table: valuation ≤90 days old at evaluation — a gate on the TPP case submission (F-1-27)." });
  o("FNMA_D23206_TPP_FIRST_DUE_15TH_RULE", { satisfied: "`lossmit.trial.schedule_created`", why: "§12.8 timer table: 'schedule created' — `12.8.tppFirstDue` computes the anchor (D2-3.2-06)." });
  o("FNMA_E3401_FC_SUSPEND_DURING_TRIAL", { trigger: "`lossmit.trial.activated`", satisfied: "`lossmit.trial.ended{status∈{failed, cancelled, converted}}`", why: "§12.8 timer table: '`lossmit.trial.failed/cancelled`' (E-3.4-01)." });
  o("FNMA_D23206_FORM3179_SERVICER_EXECUTE_BEFORE_EFFECTIVE", { trigger: "`lossmit.trial.final_payment_cleared{borrower_executed=true}`", satisfied: "`modification.servicer_executed`", why: "§12.8 timer table: '`signing_officer` execution (`officer_signature_date`)' (D2-3.2-06)." });
  o("FNMA_D23102_MBS_RECLASS_BEFORE_EXECUTION", { satisfied: "`smdu.case.reclassified`", why: "§12.8 timer table: offset is the reclassification event itself — servicer execution waits for it (D2-3.1-02)." });
  o("FNMA_F127_CAPITALIZATION_DATE", { satisfied: "`ledger.posted{rule_ref=12.8.capitalization}`", why: "§12.8 timer table: 'ledger postings' — the capitalization set balanced under rule_ref 12.8.capitalization (F-1-27)." });
  o("FNMA_F127_RECORDED_ORIGINAL_5BD", { satisfied: "`custodian.delivery.confirmed{document=recorded_original}`", why: "§12.8 timer table: 'custodian delivery' (F-1-27)." });
  o("FNMA_IRM_MOD_LOAN_DATA_CHANGE", { trigger: "`modification.effective`", satisfied: "`investor.event.accepted{kind=loan_data_change}`", why: "§12.8 timer table: '5.x ack' — LAR 83 / loan-data change accepted by the reporting cycle (Investor Reporting Manual)." });
  o("FNMA_D23206_NO_NEW_TRIAL_12M", { evaluator: "12.8.noTrialFailureWithin12Months", why: "§12.8 timer table: no new trial within 12 months of a failed TPP — a gate on solicitation/offer (D2-3.2-06)." });
  // ---- 12.9 liquidation
  o("FNMA_F114_SS_VALUATION_MAX_AGE_90", { evaluator: "12.9.valuationFresh90", why: "§12.9 timer table: valuation ≤90 days old at approval — a gate on the approval (F-1-14)." });
  o("FNMA_D23301_SS_DECISION_30", { trigger: "`liquidation.offer.received{initial=true, brp_complete=true}`", satisfied: "`notice.sent{code∈{NTC_FNMA_D23301_SS_APPROVAL, NTC_FNMA_D23301_SS_COUNTER, NTC_FNMA_D23301_SS_DECLINE}}`", why: "§12.9 timer table: '`notice.sent{approval | counter | decline}`' (D2-3.3-01)." });
  o("FNMA_D23301_SS_REVISED_OFFER_10BD", { trigger: "`liquidation.offer.received{initial=false}`", satisfied: "`notice.sent{code∈{NTC_FNMA_D23301_SS_APPROVAL, NTC_FNMA_D23301_SS_COUNTER, NTC_FNMA_D23301_SS_DECLINE}}`", why: "§12.9 timer table: 'decision notice' (D2-3.3-01)." });
  o("FNMA_E3401_SS_MARKETING_HOLD", { trigger: "`lossmit.application.completed{path=short_sale, principal_residence=true}`", offset: "60 calendar_days", satisfied: "`notice.sent{code∈{NTC_FNMA_D23301_SS_APPROVAL, NTC_FNMA_D23301_SS_COUNTER, NTC_FNMA_D23301_SS_DECLINE}}`", why: "§12.9 timer table: 'lapse/decision' — 45-day submission window + 15-day review (E-3.4-01)." });
  o("FNMA_E3401_SS_APPROVED_HOLD_60", { trigger: "`liquidation.case.approved`", satisfied: "`liquidation.case.closed`", why: "§12.9 timer table: 'closing / deed recorded' (E-3.4-01)." });
  o("REGX_1024_41G3_SS_LISTING_PERFORMANCE", { trigger: "`liquidation.listing.started`", satisfied: "`liquidation.case.status_changed{status∈{approved, closed, listing_expired}}`", why: "§12.9 timer table: '`liquidation_cases.status ∈ {approved, closed}` or expiry' (§1024.41(g)(3))." });
  o("FNMA_D23302_DIL_DOCS_60", { satisfied: "`dil.documents.complete`", why: "§12.9 timer table: 'all required items received' (D2-3.3-02)." });
  o("FNMA_D23302_DIL_WEEKLY_UPDATE_7", { trigger: "`dil.documents.extended`", satisfied: "`dil.weekly_update.logged`", why: "§12.9 timer table: 'update logged' (D2-3.3-02)." });
  o("FNMA_D23302_DIL_DEED_BEFORE_SALE_30", { trigger: "`foreclosure.sale_scheduled{dil_case_open=true}`", offset: "-30 calendar_days", satisfied: "`dil.deed.received`", why: "§12.9 timer table: executed deed received ≥30 days before the sale, else Fannie Mae prior approval (`12.9.deedTiming`) (D2-3.3-02)." });
  o("FNMA_D23302_DIL_LIEN_RELEASE_30BD", { trigger: "`dil.inspection.confirmed{vacant=true, secure=true}`", satisfied: "`lien_release.recorded`", why: "§12.9 timer table: 'lien release recorded (16.x/`signing_officer`)' (D2-3.3-02)." });
  o("FNMA_F202_LIQUIDATION_INCENTIVE_CLAIM", { satisfied: "`investor.event.accepted{kind=incentive, workout∈{short_sale, mortgage_release}}`", why: "§12.9 timer table: 'claim filed (15.2)' — tier by delinquency days (F-2-02)." });
  o("CA_CIV_2924_11C_RESCIND_NOD", { trigger: "`liquidation.case.approved{state=CA, proof_of_funds=true}`", offset: "5 business_days_servicer", satisfied: "`foreclosure.nod.rescinded`", why: "§12.9 timer table: 'rescission recorded / sale cancelled' (Cal. Civ. Code §2924.11(c); policy 5 BD)." });
}
