/**
 * §12.8 timer overrides (process-owned; the §12 section-level overrides in ./timers.ts run first and these win the
 * merge — see src/domain/bankruptcy/timers-14-1.ts for the pattern). One `reg.override(code, { trigger?, satisfied |
 * evaluator, anchorField?, offset?, why })` per 12.8 registry row whose trigger/satisfied column names an event the
 * platform spells differently or a condition the column grammar drops; `why` quotes the spec. Wired by
 * src/domain/timer-overrides.ts.
 *
 * Conventions the grammar forces (src/kernel/events/match.ts holds ONE dotted pattern per column; conditions are exact
 * string compares on payload fields):
 * - the Notice Service spells the template in `template` (`notice.sent{template=…}`); the spec's `notice.provided{…}` is
 *   Reg X's "provides" moment, i.e. that send event (the §12 convention in ./timers.ts);
 * - a trigger the spec phrases as "X with no Y and no Z" becomes one 12.8-owned event carrying the facts as fields —
 *   cashiering's (2.6) and early intervention's (11.x) events are never re-emitted with extra fields, because a second
 *   copy would re-arm their own rows; instead `FlexModService` (ops-12-8.ts) ingests them and emits the 12.8 milestone;
 * - Form 3179 is a document, not a Notice Registry template: it leaves through e-sign/print as
 *   `lossmit.agreement.sent{form=3179}` (the same vocabulary 12.6 uses for the deferral agreement).
 * Every trigger and satisfier named here is appended to the event store by a `FlexModService` method (a command, a
 * cashiering-event ingestion, or an inbound SMDU / e-sign / e-recording / custodian / investor-ack ingestion that
 * validates the record first) — never by a bare literal.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_12_8(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // ---- solicitation without a BRP (D2-3.2-06)
  o("FNMA_D23206_FLEX_SOLICIT_90_105", { trigger: "`lossmit.flex_solicitation.window_opened{basis=streamlined_90, brp_complete=false, sale_proximate=false}`", anchorField: "day_90_date", offset: "+15 calendar_days", satisfied: "`notice.sent{template=NTC_FNMA_D23206_SOLICIT_STREAMLINED}`", why: "§12.8 timer table: trigger '`loan.delinquency.day_reached{fnma_day=90}` with no complete BRP/ineligible/rejected and no sale within 60/30 days', anchor 'day 90', offset 'by day 105 (`fnma` day count)', satisfied by '`notice.sent{NTC_FNMA_D23206_SOLICIT_STREAMLINED}`' — the 11.x milestone carries neither the BRP nor the sale-proximity fact, so `FlexModService.solicit` (the solicitation command) checks both (D2-3.2-06: 'solicit between the 90th and 105th day of delinquency if no complete BRP was received before day 90'; 'no solicitation if a foreclosure sale is scheduled within 60 days (judicial) or 30 days (non-judicial)') and emits `lossmit.flex_solicitation.window_opened{basis=streamlined_90, day_90_date, brp_complete=false, sale_proximate=false, solicit_by}`; the Notice Service spells the template in `template`." });
  o("FNMA_D23206_FLEX_SOLICIT_STEP_60_75", { trigger: "`lossmit.flex_solicitation.window_opened{basis=step_rate_60, step_rate_adjusted_within_12m=true}`", anchorField: "day_60_date", offset: "+15 calendar_days", satisfied: "`notice.sent{template=NTC_FNMA_D23206_SOLICIT_STREAMLINED}`", why: "§12.8 timer table: trigger 'step-rate adjusted within 12 months, 60+ days delinquent', anchor 'day 60', offset 'by day 75', satisfied by 'same' — D2-3.2-06: 'previously modified step-rate loans with a rate adjustment within 12 months: days 60–75'; `FlexModService.solicit{basis=step_rate_60}` emits the window event with `day_60_date` and `step_rate_adjusted_within_12m=true` after the sale-proximity check." });
  // ---- evaluation and the offer
  o("FNMA_D2205_EVAL_NOTICE_TPP_5", { satisfied: "`notice.sent{template=NTC_FNMA_D23206_TPP_OFFER}`", why: "§12.8 timer table: satisfied by '`notice.provided{NTC_FNMA_D23206_TPP_OFFER}`' — Reg X's 'provides' is the Notice Service's `notice.sent{template}` (§12 convention); `FlexModService.offerTpp` renders and sends the Evaluation Notice through the Notice Registry; armed by `FlexModService.evaluate`'s `lossmit.evaluation.decided{outcome=tpp_offer, decided_on}` (D2-2-05: 'within 5 days after the decision')." });
  o("FNMA_D23206_TPP_FIRST_DUE_15TH_RULE", { trigger: "`lossmit.tpp.offered`", anchorField: "first_trial_due_date", satisfied: "`lossmit.trial.schedule_created`", why: "§12.8 timer table: trigger 'Evaluation Notice sent', anchor 'send date', offset 'first of next month if ≤15th, else first of month after next', satisfied by 'schedule created' — `flexmod.trialSchedule` computes the 15th rule from the send date ('First trial payment due the first day of the month after the Evaluation Notice if sent on or before the 15th; the month after next if sent after the 15th') and `FlexModService.offerTpp` carries the result on `lossmit.tpp.offered{notice_sent_on, first_trial_due_date}` (the Notice Service's `notice.sent` carries no computed date); `createTrialSchedule` emits `lossmit.trial.schedule_created` when the rows are handed to cashiering (2.6)." });
  o("REGX_1024_41E2II_TRIAL_OTHER_REQS_REASONABLE", { trigger: "`lossmit.trial.first_payment_received{acceptance_items_missing=true}`", anchorField: "payment_date", satisfied: "`lossmit.offer.acceptance_items.received`", why: "§12.8 timer table: trigger 'first trial payment received; other acceptance items missing', anchor 'payment date', offset '14 `calendar_days` (policy)', satisfied by 'items received' — `FlexModService` ingests cashiering's `trial_payment.received{trial_number=1}` (acceptance under D2-2-05) and emits `lossmit.trial.first_payment_received{payment_date, acceptance_items_missing}`; `recordAcceptanceItems` emits `lossmit.offer.acceptance_items.received` once nothing is outstanding (§1024.41(e)(2)(ii) 'reasonable period of time')." });
  // ---- the performing trial (E-3.4-01)
  o("FNMA_E3401_FC_SUSPEND_DURING_TRIAL", { trigger: "`lossmit.trial.first_payment_received{acceptance=true}`", satisfied: "`lossmit.trial.failed`", why: "§12.8 timer table: trigger '`tpp_active`', offset 'while performing', satisfied by '`lossmit.trial.failed/cancelled`', breach '13.x refuses motion/sale/referral (`foreclosure_holds{kind=fnma_trial_performing}`)' — state machine: '`tpp_active` (first trial payment received by its due date = acceptance)'. Cashiering's `lossmit.trial.started` is one event per schedule row on a `trial_month` aggregate with no loan subject, so the loan-scoped `lossmit.trial.failed` (2.6 month-end sweep) could never close a gate armed by it; `FlexModService.onTrialPaymentReceived` ingests `trial_payment.received{trial_number=1}` and emits the loan-scoped `lossmit.trial.first_payment_received{acceptance=true}` — the `tpp_active` transition — which the same loan's `lossmit.trial.failed` satisfies (12.8-T4 proves it on the TimerEngine)." });
  // ---- documents: Form 3179 (F-1-27; D2-3.2-06 binding conditions)
  o("SM_FORM3179_SEND_BY_LAST_TRIAL_MONTH_1", { trigger: "`lossmit.trial.penultimate_payment_met`", anchorField: "final_trial_month_start", satisfied: "`lossmit.agreement.sent{form=3179}`", why: "§12.8 timer table: trigger '`trial_plan_schedule` penultimate payment met', anchor '1st day of the final trial month', offset '0 (send with final-payment reminder; ≥30 days before the effective date)', satisfied by '`document.sent{form_3179}`' — cashiering's `trial_payment.satisfied{trial_number}` carries no 'penultimate' fact, so `FlexModService` ingests it against the trial plan and emits `lossmit.trial.penultimate_payment_met{final_trial_month_start}`; Form 3179 is a document sent by e-sign/print, spelled `lossmit.agreement.sent{form=3179, document=DOC_FNMA_FORM_3179}` by `sendForm3179` (12.6 uses the same vocabulary for its agreement)." });
  o("FNMA_D23206_FORM3179_BORROWER_EXECUTE_BEFORE_EFFECTIVE", { trigger: "`lossmit.agreement.sent{form=3179}`", anchorField: "effective_date", satisfied: "`esign.completed{form=3179}`", why: "§12.8 timer table: trigger 'Form 3179 sent', anchor 'effective date', offset '−1 `calendar_days` (executed and returned)', satisfied by '`esign.completed`/scan' — `sendForm3179` carries `effective_date`; the inbound e-sign completion (`esignCompleted`, validated against the envelope's document id) is emitted as `esign.completed{form=3179}` so a deferral agreement's e-sign cannot satisfy the Flex Mod row; a scanned mail return goes through `borrowerExecuted{basis=scan}` (the executed-copy receipt below)." });
  o("FNMA_D23206_FORM3179_SERVICER_EXECUTE_BEFORE_EFFECTIVE", { trigger: "`lossmit.modification.execution_ready{borrower_executed=true, final_trial_payment_cleared=true, reclass_pending=false}`", anchorField: "effective_date", satisfied: "`lossmit.agreement.servicer_executed{form=3179}`", why: "§12.8 timer table: trigger 'borrower executed and final trial payment cleared (and reclassification done for MBS)', anchor 'effective date', offset '−1 `calendar_days`', satisfied by '`signing_officer` execution (`officer_signature_date`)' — three conditions in either order become one readiness event `FlexModService` emits once all hold (`maybeExecutionReady`, from the borrower's executed copy, the final trial payment and the SMDU reclassification); `servicerExecute` (role `signing_officer`; D2-3.1-02 gate) emits `lossmit.agreement.servicer_executed{form=3179, officer_signature_date, effective_date}`." });
  o("FNMA_D23102_MBS_RECLASS_BEFORE_EXECUTION", { trigger: "`lossmit.tpp.completed{mbs=true}`", satisfied: "`smdu.case.reclassified`", why: "§12.8 timer table: trigger 'MBS loan `tpp_completed`', offset '`smdu.case.reclassified`', breach 'execution blocked' — cashiering's `lossmit.trial.completed` carries no MBS fact, so `FlexModService` ingests it and emits `lossmit.tpp.completed{mbs}` (state machine `tpp_completed`); the inbound SMDU reclassification (`smduReclassified`, validated against the TPP case id) is `smdu.case.reclassified` (D2-3.1-02: 'the agreement must be executed after the loan is removed from the MBS pool')." });
  o("FNMA_F127_CUSTODIAN_25", { trigger: "`lossmit.agreement.executed_copy_received{form=3179}`", anchorField: "received_on", satisfied: "`custodian.delivery.confirmed{document∈{certified_copy, executed_original}}`", why: "§12.8 timer table: trigger 'receipt of executed Form 3179 from borrower (recorded: certified copy; unrecorded: original)', anchor 'receipt', offset '25 `calendar_days`', satisfied by '`custodian.delivery.confirmed`' — `borrowerExecuted` emits the receipt with `received_on`; the custodian's confirmation (`custodianDeliveryConfirmed`, validated against the recording decision) names the copy, and only the certified copy (recorded) or the fully executed original (unrecorded) satisfies this row — the recorded original satisfies `FNMA_F127_RECORDED_ORIGINAL_5BD` (F-1-27)." });
  o("FNMA_F127_RECORDED_ORIGINAL_5BD", { anchorField: "received_on", satisfied: "`custodian.delivery.confirmed{document=recorded_original}`", why: "§12.8 timer table: trigger '`erecording.recorded_document.received`', anchor 'receipt', offset '5 `business_days_servicer`', satisfied by 'custodian delivery' — the inbound e-recording receipt (`erecordingReceived`, validated against the executed Form 3179's document id) carries `received_on`; F-1-27: 'the original within 5 business days of receipt from the recorder'." });
  // ---- reporting, conversion and the incentive (F-1-22, F-1-27, F-2-02, Investor Reporting Manual)
  o("FNMA_F122_TPP_PAYMENT_REPORT", { trigger: "`trial_payment.received`", anchorField: "received_on", why: "§12.8 timer table: trigger 'each trial payment applied', anchor 'application date', offset '1 `business_days_fannie_et`', satisfied by '`smdu.tpp_payment.acked`' — F-1-22 'report loan-level data on receipt of the first and each subsequent trial payment': cashiering (2.6) applies each receipt to the trial month and emits `trial_payment.received{case_id, trial_number, received_on}` (its `payment.applied` is the conversion-time application of held funds under C-1.1-02, not the receipt); the inbound SMDU acknowledgement of the TPP_PAYMENT report (`smduTppPaymentAcked`, validated against the TPP case) is `smdu.tpp_payment.acked`." });
  o("FNMA_IRM_MOD_LOAN_DATA_CHANGE", { trigger: "`lossmit.modification.effective`", anchorField: "effective_date", satisfied: "`investor.event.accepted{kind=loan_data_change}`", why: "§12.8 timer table: trigger '`effective`', anchor 'effective date', satisfied by '5.x ack' — Outputs: '12.8 is the producer of modification completion … `lossmit.modification.effective` fires when the modification effective date arrives' (`FlexModService.modificationEffective`, once per modification); the 5.x acknowledgement of the LAR 83 / loan-data change (`investorAckReceived`, validated against the effective event) is `investor.event.accepted{kind=loan_data_change}`." });
}
