// 23.1 DU casefile creation, submission, resubmission tolerances, versioning, and casefile lifecycle
// spec/sections/23-desktop-underwriter-and-the-credit-decision/23-1-du-casefile-creation-submission-resubmission-tolerances-vers.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("23.1-T1: Given the refinance fixture with credit received Mon Oct 5, 2026 for both borrowers, when the `underwriter` agent runs, then a `du_casefiles` row is created Tue Oct 6, 2026 with `policy_generation = 2026_09_26`, `archive_540_due_at = 2028-03-29`, and a `credit_and_underwriting` submission with `request_hash` set; `du.submitted` and `du.findings.received` are emitted within the same run.", { todo: true });
test("23.1-T2: Given baseline DTI 38.00% on $12,000.00 income, when a $450.00/month liability is added Oct 20, 2026, then `du_resubmission_checks.result = resubmission_required` with `rule_code = B3_2_10_DTI_45_OR_3PT` (dti_after 41.75, delta 3.75) and `SM_DU_RESUBMIT_SLA_1BD` due Wed Oct 21, 2026; a $300.00 liability yields `within_tolerance` (40.50, delta 2.50) and `du.resubmission.waived`.", { todo: true });
test("23.1-T3: Given a refinance loan amount of $560,000 (LTV 70.00%, LLPA column 60.01\u201370.00%), when the amount changes to $560,500, then the amount test passes (cap $500) but LTV becomes 70.0625%, which falls in the 70.01\u201375.00% LLPA column (LLPA Matrix 09.09.2026 nine LTV bands), so the check returns `resubmission_required` on the LLPA condition; when the amount changes to $565,600 the amount test fails outright (`B3_2_10_REFI_AMOUNT_500_1PCT`).", { todo: true });
test("23.1-T4: Given a refinance amount decrease from $560,000 to $532,000 (\u22125.00%), then `within_tolerance` provided no MI/LLPA/eligibility change; $531,999 \u2192 `resubmission_required` (`B3_2_10_REFI_AMOUNT_MINUS_5PCT`).", { todo: true });
test("23.1-T5: Given a purchase casefile ($412,000) whose loan amount changes by $1, then `resubmission_required` (`B3_2_10_PURCHASE_AMOUNT`) \u2014 no purchase tolerance exists.", { todo: true });
test("23.1-T6: Given \"Reserves Required to be Verified\" $8,000.00, when verified reserves are $7,300.00 then `within_tolerance`; $7,200.00 (exactly 90.00%) `within_tolerance`; $7,100.00 `resubmission_required`.", { todo: true });
test("23.1-T7: Given the note rate falls from 6.250% to 6.125% (no buydown), then `within_tolerance`; given the decrease results from a permanent buydown, then `resubmission_required` (`B3_2_10_RATE_DECREASE_BUYDOWN`).", { todo: true });
test("23.1-T8: Given recalculated DTI 50.25%, then `ineligible_change` (`B3_2_10_DTI_OVER_50`) and 23.2's restructuring loop is invoked; no submission is sent until the structure changes.", { todo: true });
test("23.1-T9: Given closing documents are requested Tue Nov 3, 2026 and the last findings (Oct 20) carry `appraised_value = $800,000` while the CD-final data carry $795,000, then `FNMA_B3_2_10_DU_FINAL_MATCH_GATE` blocks `generateClosingDocs`, a `final_closed_loan_match` submission is sent, and the gate opens only when the new findings hash matches and the recommendation is `approve_eligible`.", { todo: true });
test("23.1-T10: Given a casefile last updated Thu Nov 5, 2026 with no further activity, then `FNMA_B3_2_01_DU_ARCHIVE_270` fires the warning on Sat Jul 3, 2027 (day 240) and marks `archived` on Mon Aug 2, 2027; if the loan was purchased Nov 19, 2026, the archive event is informational only.", { todo: true });
test("23.1-T11: Given two borrowers whose reports carry different score models (one VantageScore 4.0, one Classic FICO), then `associateCredit` refuses the submission with `error_code = SCORE_MODEL_MIXED` and 22.2 is asked to re-order.", { todo: true });
test("23.1-T12: Given a borrower SSN correction after credit association, then the casefile requires a new credit association (`DU_JOBAID_IDENTITY_CHANGE`), a fraud signal is sent to 22.6, and the prior submission is marked `superseded`.", { todo: true });
test("23.1-T13: Given the DI channel returns transport errors for 30 minutes on Wed Nov 4, 2026, then an `escalation{fnma_portal_operator}` is opened with the request file attached; on manual submission the operator-uploaded findings are ingested and matched to the queued `du_submissions` row by casefile ID.", { todo: true });
test("23.1-T14: Given a request built on Dec 1, 2026 with `return_file_types` containing type 16, then the adapter rejects it before transmission (`FNMA_DU_RETURN_FILE_16_17_RETIRE`).", { todo: true });
test("23.1-T15: Given a HomeReady casefile submitted with $6,250.00 monthly qualifying income, when verified income is $6,400.00, then `du_resubmission_checks.result = resubmission_required` with `rule_code = B3_2_10_INCOME_LIMITED` (B3-2-10: \"Income is greater than the loan application indicates\") and 23.2 re-runs the AMI test; when verified income is $6,100.00 and the recalculated DTI stays under 45% with a delta below 3 points, then the income-limited rule does not fire and the result is `within_tolerance` (the DTI test alone governs the decrease).", { todo: true });
