// 23.2 DU findings interpretation, recommendation policy, and conditions generation (incl. HomeReady/AMI, homebuyer education, value acceptance offers, MI messages, red flags)
// spec/sections/23-desktop-underwriter-and-the-credit-decision/23-2-du-findings-interpretation-recommendation-policy-and-conditi.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("23.2-T1: Given findings Tue Oct 6, 2026 (refinance fixture) with 14 verification messages, 1 MI message (\"no MI\" at 70% LTV \u2192 none), 1 value-acceptance offer and 2 observations, when interpreted, then 14 PTD conditions are opened by 10:00 the same day (`SM_DU_CONDITIONS_SLA_4H` satisfied), `value_acceptance_offer = value_acceptance`, `sfc_required = {127, 007}`, and no borrower-facing text contains a DU message ID.", { todo: true });
test("23.2-T2: Given a message ID not in `du_message_rules` for release `2026-09-25`, then a `COND_DU_UNMAPPED_MESSAGE` PTD condition is opened, the triage queue receives the message, and CTC (23.3) is blocked until it is mapped or cleared by `underwriting_reviewer`.", { todo: true });
test("23.2-T3: Given the purchase fixture with qualifying income $98,400.00/year and API AMI $124,000.00, then `homeready_evaluations.eligible = true` (limit $99,200.00); with $100,800.00 it is `false` and a `remove_homeready` proposal is created whose expected DTI is 44.44%.", { todo: true });
test("23.2-T4: Given two occupying first-time homebuyers on a HomeReady purchase closing Wed Nov 18, 2026 and no certificate on file Mon Nov 16, then `FNMA_B2_2_06_HOMEOWNERSHIP_ED_GATE` blocks `clear_to_close` and an `escalation{underwriting_reviewer}` is opened (closing < 3 BD away); a HomeView certificate dated Fri Oct 30, 2026 verified Nov 16 satisfies the gate.", { todo: true });
test("23.2-T5: Given HUD-agency counseling completed Nov 10, 2025 for a closing on Nov 18, 2026, then `FNMA_B5_6_01_COUNSELING_CREDIT_12M` is not satisfied (> 12 months) and SFC 184 is not emitted; completed Nov 20, 2025 \u2192 satisfied.", { todo: true });
test("23.2-T6: Given Approve/Ineligible with an eligibility message \"loan amount exceeds the county loan limit\" ($840,000 in a baseline county, limit $832,750), then `policy_outcome = restructure_required`, a `loan_amount` proposal to $832,750 is computed, and `regb_treatment = counteroffer` requiring `underwriting_reviewer` before any borrower contact.", { todo: true });
test("23.2-T7: Given Refer with Caution on the purchase fixture at $7,000.00 income (DTI 53.32%), then the agent produces the $360,000.00 proposal (DTI 46.73%, no MI) and a decline candidate; no manual underwriting path is offered; the reviewer's approval is required for the counteroffer notice.", { todo: true });
test("23.2-T8: Given a potential red flag \"Occupancy Modified\" (investor \u2192 primary), then an `investigation.opened{kind=du_red_flag}` is created for 22.6, no condition is shown to the borrower, and CTC is blocked until the investigation closes with rationale.", { todo: true });
test("23.2-T9: Given a resubmission whose findings drop a previously-open liability message after the borrower paid the account, then the condition is superseded (status `superseded`) with the payoff evidence retained.", { todo: true });
test("23.2-T10: Given a casefile created Sept 24, 2026 that returned Approve/Eligible and a resubmission on Oct 2, 2026 returning Approve/Ineligible with no data change, then `du.recommendation.changed{cause=du_policy}` is recorded citing the June 26, 2026 release, and the outcome is `restructure_required`.", { todo: true });
test("23.2-T11: Given the refinance fixture MI message absent (LTV 70%), when 24.6 asks for coverage, then `mi_coverage_pct = null` and no MI condition exists; given a 92% LTV HomeReady loan, then `mi_coverage_pct = 25.00` (vs 30.00 standard) and `COND_DU_MI_CERT` is opened.", { todo: true });
test("23.2-T12: Given a value-acceptance offer on the Oct 6 submission but none on the final-match submission Nov 3, then `value_acceptance_offer = none` on the interpretation used for delivery and 24.1 is notified that SFC 801 may not be used.", { todo: true });
