// 23.3 The credit decision: comprehensive risk assessment, conditional approval, condition clearing (PTD/PTF), and final underwriting sign-off
// spec/sections/23-desktop-underwriter-and-the-credit-decision/23-3-the-credit-decision-comprehensive-risk-assessment-conditiona.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("23.3-T1: Given `du.findings.interpreted{proceed}` at 09:12 Tue Oct 6, 2026 and 23.4 preliminary `qm/not_high_cost`, when the agent runs, then `decision.issued{conditional_approval}` and `notice.sent{NTC_REGB_1002_9_APPROVAL}` occur by Wed Oct 7, 2026 (`SM_UW_CONDITIONAL_APPROVAL_SLA_1BD`), with `valid_until = 2026-11-21` and 14 borrower-facing conditions listed.", { todo: true });
test("23.3-T2: Given a `COND_DU_VERIFY_INCOME_BASE` condition and a paystub dated Sept 28, 2026 plus a 2025 W-2 classified Oct 8, 2026, when `evaluateClearance` runs, then the condition is `cleared` by the agent with `standard_ref = B3-3.2-01/DU:paystub_30d_w2_1y` and `age_check` passing for a Nov 6 note date; given the paystub is dated June 1, 2026 (> 4 months at note date), then it stays `satisfied_pending_review` with reason `B1_1_03_AGE`.", { todo: true });
test("23.3-T3: Given all PTD conditions cleared but an open `investigation{kind=du_red_flag}` (Occupancy Modified), then `ptd_cleared` is not emitted and `SM_UW_PTD_CLEARED_GATE` blocks `issueCD` on Mon Nov 2, 2026 with `blocking_codes = {CTC_NO_OPEN_INVESTIGATION}`.", { todo: true });
test("23.3-T4: Given the CTC checklist on Fri Oct 30, 2026 with every item `pass` except `CTC_INSURANCE_FLOOD` (declaration page missing), then no CTC; when the declaration page is classified at 09:20, then `clear_to_close.issued` at \u2264 10:20 the same day.", { todo: true });
test("23.3-T5: Given a DTI recalculated at 51.75% on Wed Nov 4, 2026 for a Fri Nov 6 consummation, then `decision.reopened` and an `escalation{underwriting_reviewer}` with same-business-day SLA; `SM_UW_CTC_GATE` blocks `consummate` until re-issued.", { todo: true });
test("23.3-T6: Given a `decline_candidate` outcome, when the agent prepares the record with reasons `[\"debt-to-income ratio of 53.32% exceeds the 50% maximum\"]`, then 21.6 is not invoked until `reviewer_action = approved`; a reason text containing \"DU\" or \"Refer with Caution\" fails validation.", { todo: true });
test("23.3-T7: Given a counteroffer notice sent Thu Oct 29, 2026 that the borrower neither accepts nor uses, then 21.6's `REGB_1002_9_COUNTEROFFER_90` expires Wed Jan 27, 2027 and `restructure_proposals.status = expired` (23.2); no second adverse-action notice is required when the combined notice was used (comment 9(a)(1)-6).", { todo: true });
test("23.3-T8: Given `qc.review.opened{kind=prefunding}` on Wed Oct 28, 2026 for the refinance fixture, then 28.1's `FNMA_D1_2_01_PREFUNDING_PRIOR_TO_CLOSING_GATE` (checklist item `SM_QC_PREFUNDING_HOLD`) blocks CTC until `qc.review.closed`; a review closed Thu Oct 29 with no defects allows CTC Fri Oct 30.", { todo: true });
test("23.3-T9: Given employment validated with close-by date Mon Dec 7, 2026 and consummation Fri Nov 6, 2026, then `rep_warrant_relief{employment_validated}.status = eligible`; given the closing slips to Tue Dec 8, 2026 without a new validation, then `lost` and a PTF VVOE condition is opened (22.3).", { todo: true });
test("23.3-T10: Given an `underwriting_reviewer` attempts to waive `COND_DU_VERIFY_ASSETS`, then the waiver is refused (`WAIVER_NOT_PERMITTED_DU_MESSAGE`); waiving an SM-added `COND_SM_LETTER_OF_EXPLANATION` succeeds with a recorded reason.", { todo: true });
test("23.3-T11: Given the loan is purchased Thu Nov 19, 2026 with first payment due Fri Jan 1, 2027, then `rep_warrant_relief{payment_history_36}` opens with a target of the 36th payment due Dec 1, 2029 and status `eligible` pending Fannie Mae's relief report (28.2/30.4).", { todo: true });
test("23.3-T12: Given any decision record, then it contains `rule_set_versions`, `model_version`, `prompt_version`, `inputs_hash` and `reasons[].source_fact`, and no field derived from `applicant_demographics` (access log shows zero reads by the `underwriter` agent).", { todo: true });
