// 23.4 ATR/QM, HPML, HOEPA, and state high-cost determinations
// spec/sections/23-desktop-underwriter-and-the-credit-decision/23-4-atr-qm-hpml-hoepa-and-state-high-cost-determinations.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("23.4-T1: Given the refinance fixture with APR 6.159% (25.1's engine result) and APOR 6.020% at `cd` stage on Mon Nov 2, 2026, then `spread = 0.139`, `apr_tier = first_lien_ge_137958`, `apr_test_pass = true`, `hpct = false`, `qm_type = general_safe_harbor`, `is_hpml = false`, `is_hoepa = false`, and `REGZ_1026_43_QM_DETERMINATION_GATE` is open for `issueCD`.", { todo: true });
test("23.4-T2: Given the refinance fixture fee set (origination $1,995.00; prepaid interest $1,785.43 per 26.3's convention; credit report $75.00; unaffiliated title $1,800.00; recording $95.00), then `amount_financed_cents = 55621957`, `total_loan_amount_cents = 55621957`, `cap_cents = 1668658`, `pf_cents = 199500`, and the excluded items carry reason codes `interest`, `bona_fide_third_party`, `reasonable_no_comp_not_affiliate`, and `not_finance_charge`.", { todo: true });
test("23.4-T3: Given the purchase fixture with the $9,800.00 itemization (including $3,010.00 to an affiliated title agency and a $2,060.00 non-bona-fide half point at undiscounted rate 8.10% vs APOR 6.020%), then `pf_cents = 980000`, `total_loan_amount_cents = 40427453`, `cap_cents = 1212824`, `qm_type = general_safe_harbor`; given the same loan with the title agency unaffiliated, then `pf_cents = 679000`.", { todo: true });
test("23.4-T4: Given 1.5 additional non-bona-fide points ($6,180.00) on the purchase fixture at `cd` stage, then `qm_type = not_qm`, `issueCD` is blocked, and a `restructure.proposed{kind=fee_change}` is emitted; given the same excess found at `post_closing` on Dec 1, 2026 for a Nov 18 consummation, then the `post_closing` row records `qm_type = not_qm`, `cure_required_cents = 385176` is queued as a remediation refund for `officer` approval, no `REGZ_1026_43_E3III_PF_CURE_210` timer is created (the (e)(3)(iii) cure is unavailable for loans consummated after Jan 10, 2021), and an 28.4 self-report evaluation is opened.", { todo: true });
test("23.4-T5: Given APR 7.550% vs APOR 6.020% on the refinance fixture, then `hpct = true`, `is_hpml = true`, `qm_type = general_rebuttable`, `escrow_required = true`, `escrow_min_cancel_date = 2031-11-06`, `appraisal_rules_apply = false`, `fnma_eligible = true`; a servicing `cancelEscrow` request dated Nov 5, 2031 is refused and one dated Nov 6, 2031 proceeds to the < 80% UPB test.", { todo: true });
test("23.4-T6: Given APR 8.400% vs APOR 6.020%, then `apr_test_pass = false`, `qm_type = not_qm`, `is_hpml = true`, `fnma_eligible = false` (spread > 2.25), and both `REGZ_1026_43_QM_DETERMINATION_GATE` and delivery are blocked.", { todo: true });
test("23.4-T7: Given APR 12.600% vs APOR 6.020% (spread 6.580 > 6.5), then `is_hoepa = true` and `REGZ_1026_32_HOEPA_GATE` blocks `issueCD`; given spread exactly 6.500, then `is_hoepa = false` on the APR test (\"more than\").", { todo: true });
test("23.4-T8: Given a $340,000 New Jersey loan with points and fees $15,640.00 (4.60%), then `state_tests[NJ].pf_test.fail = true`, `is_state_high_cost = true`, `fnma_eligible = false`, `STATE_HIGH_COST_GATE` blocks; at $15,300.00 (4.50%) the NJ test passes but the QM 3% test fails ($10,200.00 cap) \u2014 `qm_type = not_qm`.", { todo: true });
test("23.4-T9: Given a $412,000 North Carolina loan, then `state_tests[NC].applies_by_size = false` (cap $300,000) and `result = not_applicable`; given a $290,000 NC loan with points and fees 5.2%, then `fail` and Fannie Mae ineligible.", { todo: true });
test("23.4-T10: Given a lock on Wed Oct 7, 2026 and a relock on Mon Nov 2, 2026 at a new rate, then `rate_set_date = 2026-11-02` and the APOR row is re-selected from the table current on Nov 2; the Oct 7 row remains on the superseded `lock` stage record.", { todo: true });
test("23.4-T11: Given the APOR table last ingested Mon Sept 21, 2026 and a lock-stage determination requested Wed Oct 7, 2026 (16 days), then the determination is blocked with `apor_stale` until `FFIEC_APOR_TABLE_REFRESH_WEEKLY` ingests a newer table.", { todo: true });
test("23.4-T12: Given a loan amount of $137,900 (below the 2026 first tier), then `apr_threshold_pts = 3.5` and `pf_tier = usd4139_82775_137957` with `cap_cents = 413900`; given $137,958, then 2.25 and 3%.", { todo: true });
test("23.4-T13: Given an HPML first lien on a principal dwelling where the borrower elects to waive escrow, then `REGZ_1026_35B1_HPML_ESCROW_GATE` blocks consummation and 30.3 refuses the waiver.", { todo: true });
test("23.4-T14: Given a consider-and-verify map missing the \"credit history\" factor's evidence reference, then `qm_type` cannot be `general_*` and the gate blocks until 22.2's report id is linked.", { todo: true });
