/**
 * §23.4 timer overrides (process-owned; applied after every section's so they win the merge — see
 * src/domain/bankruptcy/timers-14-1.ts for the pattern). One `reg.override(code, { trigger?, satisfied | evaluator,
 * anchorField?, offset?, why })` per 23.4 registry row whose trigger/satisfied column names an event the platform
 * spells differently or a condition the column grammar drops; `why` quotes the spec. A code the servicing spec
 * (sections 1–19) owns is never overridden here — reference it. Wired by src/domain/timer-overrides.ts.
 *
 * The three determination gates are condition-shaped ("each gated command"): each arms on the determination event
 * ops-23-4.ts recordDeterminations appends for the stage, is asserted by its evaluator (evaluators-23-4.ts) whenever a
 * gated command runs, and closes on `compliance.test.passed{test=…}` for that stage. The HPML escrow rows arm on 26.2's
 * `closing.scheduled` / `closing.consummated` carrying `is_hpml=true` (ops-23-4.ts hpmlClosingPayload) and are satisfied
 * by 30.3 (`escrow.initial_analysis.approved{hpml=true}`) and servicing 3.8 (`escrow.waiver.decided`). Every 23.4 event
 * carries `applicationId`, so the rows arm only under origination context (src/kernel/timers/engine.ts).
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_23_4(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  o("REGZ_1026_43_QM_DETERMINATION_GATE", { trigger: "`compliance.qm.determined`", evaluator: "23.4.qmDeterminationGate", satisfied: "`compliance.test.passed{test=qm}`",
    why: "§23.4 timer table: gate (blocks `issueCD`, `consummate`, `authorizeFunding`, `submitDelivery`) on 'each gated command' (commands, not events — each calls evaluateGate('23.4.qmDeterminationGate') over the current-stage qm_determinations row, which `compliance.qm.determined{stage, qm_type}` records); satisfied by 'current-stage `qm_determinations.qm_type ∈ {general_safe_harbor, general_rebuttable}` with `apr_test_pass`, `pf` within cap, product tests pass, `consider_verify` complete; at `consummation` stage the row must be computed from the final CD' — ops-23-4.ts recordDeterminations appends `compliance.test.passed{test=qm}` exactly then; breach: block; 23.2 restructure loop (`restructure.proposed{kind=fee_change}`); `underwriting_reviewer` if decline." });
  o("REGZ_1026_32_HOEPA_GATE", { trigger: "`compliance.high_cost.determined`", evaluator: "23.4.hoepaGate", satisfied: "`compliance.test.passed{test=hoepa}`",
    why: "§23.4 timer table: gate (blocks `issueCD`, `consummate`) on 'each gated command'; satisfied by '`high_cost_determinations.is_hoepa = false`' — recorded as `compliance.high_cost.determined{stage, is_hoepa}` and closed by `compliance.test.passed{test=hoepa}` (ops-23-4.ts); breach: hard block; HOEPA loans are never made (B2-1.5-02 ineligible; partner policy)." });
  o("STATE_HIGH_COST_GATE", { trigger: "`compliance.high_cost.determined`", evaluator: "23.4.stateHighCostGate", satisfied: "`compliance.test.passed{test=state_high_cost}`",
    why: "§23.4 timer table: gate (blocks `issueCD`, `consummate`) on 'each gated command'; satisfied by 'every applicable `state_tests[].result ∈ {pass, not_applicable}`' — `compliance.high_cost.determined{stage, is_state_high_cost}` records the tests and `compliance.test.passed{test=state_high_cost}` closes the gate; breach: hard block where `fnma_ineligible_if_fail`; otherwise partner counsel decision (`officer` — evaluator fact `officer_accepted_state_risk`)." });
  o("REGZ_1026_35_HPML_ESCROW_5Y", { trigger: "`closing.consummated{is_hpml=true}`", anchorField: "consummation_at", satisfied: "`escrow.waiver.decided`",
    why: "§23.4 timer table: not_before gate (window) on '`closing.consummated` with `is_hpml = true`' (26.2's event carrying ops-23-4.ts hpmlClosingPayload), anchor 'consummation date' (`consummation_at`), +5 `calendar_years` (same month/day — 30.3 hpmlMinCancelDate writes `escrow_accounts.hpml_escrow_min_cancel_date`); satisfied by '`escrow_accounts` (servicing 3.8) rejects cancellation requests received before the date and enforces < 80% UPB / not delinquent thereafter' — 3.8's `escrow.waiver.decided` is that enforcement (HPML_LT_5Y before the floor; the LTV / delinquency tests after it; ops-23-4.ts cancelEscrowRequest reuses evaluateWaiver); breach: servicing 3.8 refuses `cancelEscrow`; `compliance-sentinel` alert." });
  o("REGZ_1026_35B1_HPML_ESCROW_GATE", { trigger: "`closing.scheduled{is_hpml=true}`", evaluator: "23.4.hpmlEscrowGate", satisfied: "`escrow.initial_analysis.approved{hpml=true}`",
    why: "§23.4 timer table: gate (blocks `consummate`) on '`is_hpml = true` on first-lien principal dwelling' (prose — 26.2's `closing.scheduled{is_hpml=true}` is the platform event that schedules the consummation the gate guards; 30.3's registry row names the same trigger); satisfied by '`escrow_accounts` established \"before consummation\" (30.3 setup with initial deposits on the CD; `escrow.initial_analysis.approved{hpml=true}`)' — ops-30-3.ts approveInitialAnalysis appends it with `hpml`; a borrower's waiver election on an HPML is refused (T13); breach: block consummation." });
  o("REGZ_1026_43_E3III_PF_CURE_210", { trigger: "`compliance.pf_cure.required{consummated_on_or_before_2021_01_10=true}`", anchorField: "consummation_at", offset: "+210 `calendar_days`", satisfied: "`compliance.pf_cure.paid`",
    why: "§23.4 timer table: retired — §1026.43(e)(3)(iii) opens 'For covered transactions consummated on or before January 10, 2021' (eCFR 9/8/2026); the 210-day cure clock therefore arms only for such a transaction (`compliance.pf_cure.required` carries `consummated_on_or_before_2021_01_10`, false for every loan this platform originates — no timer is created, T4), anchored at the consummation date; satisfied by '`compliance.pf_cure.paid` is a remediation refund only (excess + interest at the contract rate, `officer` approved, recorded in the cure ledger) — it does not change `qm_type`' (ops-23-4.ts recordPfCurePaid); breach: `qm_type = not_qm` recorded on a `post_closing` row; A2-2-07 / QM representation exposure → 28.4 self-report and repurchase evaluation; `officer` sev 1." });
  o("FFIEC_APOR_TABLE_REFRESH_WEEKLY", { trigger: "`apor.table.ingested`", anchorField: "table_date", satisfied: "`apor.table.ingested`",
    why: "§23.4 timer table: recurring on 'schedule' (Monday 09:00 ET; the FFIEC table is dated and effective the following Monday), anchor 'Monday 09:00 ET' → the ingested table's `table_date`, 7 `calendar_days`; satisfied by '`apor.table.ingested` for both fixed and adjustable tables' — 25.1's ingestAporTable appends `apor.table.ingested{table_date, products}` with `source=origination` (23.4 consumes it; the recurring row re-arms from each ingestion); breach: determinations use the last ingested table and are flagged `apor_stale`; `lock`-stage determinations older than 14 days are blocked (ops-23-4.ts selectApor, T11)." });
  // 24.2 owns REGZ_1026_35C_HPML_APPRAISAL_COPY_3BD (its timers-24-2.ts applies after this file and wins); its trigger is 23.4's own
  // hpml_determinations fact, so the row is made armable here from that fact until 24.2 lands its own override.
  o("REGZ_1026_35C_HPML_APPRAISAL_COPY_3BD", { trigger: "`compliance.hpml.determined{is_hpml=true, appraisal_rules_apply=true}`", evaluator: "23.4.hpmlAppraisalCopy3bd", satisfied: "`valuation.copy.delivered`",
    why: "§24.2 timer table (23.4 references it as 'owned elsewhere'): not_before_gate on `consummate`, trigger '`hpml_determinations{is_hpml, not exempt}`' — 23.4's `compliance.hpml.determined{is_hpml=true, appraisal_rules_apply=true}` (`appraisal_rules_apply = is_hpml AND qm_type = not_qm AND loan_amount > $34,200`, rule 5), anchor `consummation_at`, offset 'every written appraisal (incl. second) provided ≥ 3 `business_days_creditor` before consummation; no waiver' (evaluator 23.4.hpmlAppraisalCopy3bd over the copies' delivery dates); satisfied by '`valuation.copy.delivered` for all HPML appraisals' (24.2); breach: block `consummate`." });
}
