/**
 * §23.3 timer overrides (process-owned; applied after every section's so they win the merge — see
 * src/domain/bankruptcy/timers-14-1.ts for the pattern). One `reg.override(code, { trigger?, satisfied | evaluator,
 * anchorField?, offset?, why })` per 23.3 registry row whose trigger/satisfied column names an event the platform
 * spells differently or a condition the column grammar drops; `why` quotes the spec. A code the servicing spec
 * (sections 1–19) owns is never overridden here — reference it. Wired by src/domain/timer-overrides.ts.
 *
 * Every 23.3 event carries `applicationId` (ops-23-3.ts emit), so the rows arm only under origination context
 * (src/kernel/timers/engine.ts isOriginationContext). Referenced, not overridden: `REGB_1002_9_DECISION_30` (21.6 /
 * 20.3 own the row; the Oct 7 express approval satisfies it) and `FNMA_B3_2_02_DU_CLOSE_BY_GATE` (22.3 owns; a CTC
 * checklist item here). `FNMA_D1_2_01_PREFUNDING_PRIOR_TO_CLOSING_GATE` is 28.1's rule; the registry resolves the
 * first defining row to 23.3, so its gate shape is given here (28.1's own override, applied later, wins when it lands).
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_23_3(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  o("SM_UW_CONDITIONAL_APPROVAL_SLA_1BD", { trigger: "`du.findings.interpreted{policy_outcome=proceed}`", offset: "+1 business_days_creditor", satisfied: "`notice.sent{template=NTC_REGB_1002_9_APPROVAL}`",
    why: "§23.3 timer table: deadline (internal) on '`du.findings.interpreted{proceed}` (first Approve/Eligible)' — 23.2's interpretFindings appends `du.findings.interpreted{policy_outcome}`; anchor 'event time', '+1 `business_days_creditor`'; satisfied by '`decision.issued{conditional_approval}` + `notice.sent{NTC_REGB_1002_9_APPROVAL}`' — the letter is rendered and sent only after ops-23-3.ts issueConditionalApproval appended 21.6's `decision.issued{kind=conditional_approval}`, so the Notice Registry's `notice.sent{template=NTC_REGB_1002_9_APPROVAL}` (src/notices/service.ts) is the later of the two and closes the row; breach: sev 3 to the agent owner; sev 2 `underwriting_reviewer` after 2 BD." });
  o("SM_UW_CONDITION_CLEAR_SLA_1BD", { trigger: "`document.classified`", offset: "+1 business_days_creditor", satisfied: "`condition.cleared`",
    why: "§23.3 timer table: deadline (internal, per condition) on 'evidence received (`verification.received`/`document.classified`)' — 22.1's classifyDocument appends `document.classified` (the grammar takes one trigger; a vendor report also lands as a classified report document); anchor 'event time', '+1 `business_days_creditor`'; satisfied by '`condition.cleared` or `condition.reopened` with reason' — ops-23-3.ts clearCondition appends `condition.cleared{standard_ref, age_check}` (reopenCondition's `condition.reopened{reason}` restarts the item's clock from the next evidence); breach: sev 3; aging report." });
  o("SM_UW_PTD_CLEARED_GATE", { trigger: "`disclosure.cd.requested`", evaluator: "23.3.ptdClearedGate", satisfied: "`ptd.cleared`",
    why: "§23.3 timer table: gate (blocks `issueCD`, `generateClosingDocs`) on '`issueCD` requested (25.2)' — 25.2's CD stage opens on `disclosure.cd.requested` (ops-25-1.ts stage map); satisfied by '`ptd.cleared` and 23.1 `FNMA_B3_2_10_DU_FINAL_MATCH_GATE` open' — evaluator 23.3.ptdClearedGate over ptdStatus (every PTD condition cleared, no open red-flag investigation, no prefunding hold) and the final-match gate; ops-23-3.ts recordPtdCleared appends `ptd.cleared{blocking_codes=[]}`; breach: block; list blocking conditions (23.3-Q4: `ptd_cleared`, not full CTC, gates `issueCD`)." });
  o("SM_UW_CTC_GATE", { trigger: "`closing.scheduled`", evaluator: "23.3.ctcGate", satisfied: "`clear_to_close.issued{passed=true}`",
    why: "§23.3 timer table: gate (blocks `consummate`, `closing.scheduled` confirmation) on `closing.scheduled` (26.2 / 21.4's closing date); satisfied by '`clear_to_close.issued` with `ctc_checklists.passed`' — ops-23-3.ts issueClearToClose appends `clear_to_close.issued{checklist_id, passed=true}` only when every checklist item is pass / n/a (waived by `underwriting_reviewer`) on an `active` decision; evaluator 23.3.ctcGate re-asserts it before `consummate` (a `decision.reopened` closes it until re-issued, T5); breach: block; escalate if closing < 3 BD." });
  o("SM_UW_PTF_CLEARED_GATE", { trigger: "`closing.consummated`", evaluator: "23.3.ptfClearedGate", satisfied: "`ptf.cleared`",
    why: "§23.3 timer table: gate (blocks `authorizeFunding`, 26.3) on '`funding.requested`' — 26.3's funding request follows consummation (26.2's `closing.consummated`, the point at which the PTF items — VVOE, credit refresh, insurance effective on/before disbursement, executed documents — are determinable), which arms the gate; satisfied by `ptf.cleared` — ops-23-3.ts recordPtfCleared appends it after ptfStatus finds every PTF condition cleared; evaluator 23.3.ptfClearedGate is asserted by 26.3's authorizeFunding; breach: block; `funding_approver` cannot release." });
  o("SM_UW_DECISION_VALIDITY", { trigger: "`credit_decision.recorded{kind=conditional_approval}`", anchorField: "valid_until", satisfied: "`closing.consummated`",
    why: "§23.3 timer table: deadline on `decision.issued{conditional_approval}` anchored at `decisions.valid_until` (offset 0) — 21.6's `decision.issued` carries no validity, so ops-23-3.ts issueConditionalApproval appends `credit_decision.recorded{kind=conditional_approval, valid_until}` in the same transaction (valid_until = min(credit expiry, lock expiry, valuation expiry, DU close-by, 90 days; 23.3-Q5)); satisfied by 'consummation before `valid_until`, or decision re-issued' — 26.2's `closing.consummated` closes it; a re-issue supersedes the record (`decision.superseded`) and arms a new row from the new `credit_decision.recorded`; breach: `decision.reopened`; re-evaluate the expired component (credit / lock / valuation / close-by) — ops-23-3.ts validityExpired names it." });
  o("FNMA_D1_2_01_PREFUNDING_PRIOR_TO_CLOSING_GATE", { trigger: "`qc.review.opened{kind=prefunding}`", evaluator: "23.3.prefundingQcGate", satisfied: "`qc.review.closed`",
    why: "§23.3 timer table (28.1 owns the rule; surfaced in `ctc_checklists` as the item `SM_QC_PREFUNDING_HOLD`, a checklist item, not a second timer code): not_before_gate on `qc.review.opened{kind=prefunding}` (28.1); 'open iff `qc_reviews.status ∈ {closed{no_defect, defect_corrected}, unable_to_complete}`' — evaluator 23.3.prefundingQcGate over the review status ops-23-3.ts prefundingReviewStatus derives from 28.1's `qc.review.opened` / `qc.review.closed{outcome}` / `qc.hold.applied{kind=prefunding}` / `qc.hold.released` events; satisfied 'per 28.1' = `qc.review.closed`; breach: block CTC (\"corrections… prior to loan closing\", D1-2-01); 28.1 breach path." });
}
