/**
 * §24.6 process-owned notice versions (V(code, source, rules, sample, ruleSet, formBasis) from ./section01.ts) and
 * per-code channel/combination overrides. Spread by ../catalog.ts after the servicing files, so a version here
 * supersedes one there for the same code and effective date.
 *
 * NTC_HPA_4903_INITIAL_FIXED — 12 U.S.C. 4903(a)(1)(A): at consummation of a fixed-rate BPMI loan the mortgagee (the
 *   partner) provides "(i) a written initial amortization schedule; and (ii) written notice" that (I) the borrower may
 *   cancel on the cancellation date (scheduled 80% of original value), (II) may request cancellation earlier based
 *   solely on actual payments, (III) MI automatically terminates on the termination date (scheduled 78%), and (IV)
 *   whether the high-risk exemptions apply; §4902(a) conditions (good payment history, current, no decline in value /
 *   no subordinate liens); §4902(c) midpoint. The full initial schedule (every payment, interest half-up to cents)
 *   is embedded — the same rows 10.x boards as mi_schedules.basis = 'initial'.
 * NTC_HPA_4903_INITIAL_ARM — §4903(a)(1)(B): the cancellation date, the automatic termination date and that on the
 *   termination date the borrower is notified of the termination or that the requirement continues (not current).
 * NTC_HPA_4905_LPMI — §4905(c)(1): delivered "not later than the date on which a loan commitment is made"; LPMI may
 *   not be cancelled by the mortgagor while BPMI could be cancelable, usually results in a higher interest rate, and
 *   terminates only when the loan is refinanced, paid off or otherwise terminated; §4905(c)(2): a notice within 30
 *   days after the BPMI-equivalent termination date (servicing 10.x NTC_HPA_4905C2_LPMI_OPTIONS).
 * Short neutral sentences; every figure and date is a payload placeholder. Samples are the purchase fixture
 * ($412,000 at 6.375%/360 on an original value of $457,800 → Oct 1, 2034 / Dec 1, 2035 / Jan 1, 2042), computed by
 * the same calculators the process and the servicing side run (ops-24-6.ts → src/domain/pmi/schedule.ts).
 */
import type { ContentRule, NoticeTemplate, VersionInput } from "../registry.ts";
import { V } from "./section01.ts";
import { plainDate as D } from "../../kernel/calendar/date.ts";
import { buildInitialAmortizationSchedule, computeHpaDates } from "../../domain/property/ops-24-6.ts";

const R = (rule_id: string, citation: string, kind: ContentRule["kind"], selector: string, message: string, extra: Partial<ContentRule> = {}): ContentRule => ({ rule_id, citation, kind, selector, severity: "block", message, ...extra });

// ------------------------------------------------------------------ the purchase fixture (24.6 worked example 1 / T5)
const FIXTURE_SCHEDULE = buildInitialAmortizationSchedule({ note_amount_cents: 41_200_000n, note_rate_pct: "6.375", term_months: 360, first_payment_due: D("2027-01-01") });
const FIXTURE_DATES = computeHpaDates({ schedule: FIXTURE_SCHEDULE.schedule, original_value_cents: 45_780_000n, term_months: 360, first_payment_due: D("2027-01-01") });
const FIXTURE_PARTIES = { partner_name: "Partner Bank, N.A.", borrower_name: "Jordan Borrower", property_address: "1420 Neil Ave, Columbus, OH 43201", loan_number: "PB-2026-004127" };

// ------------------------------------------------------------------ NTC_HPA_4903_INITIAL_FIXED
export const HPA_4903_INITIAL_FIXED_SOURCE = `{{#block "heading" page=1 y=0.04 pt=14 bold}}Private Mortgage Insurance Initial Disclosure{{/block}}
{{#block "intro" page=1 y=0.1 pt=11}}Date of consummation: {{date consummation_date}}. Borrower: {{borrower_name}}. Property: {{property_address}}. Loan number: {{loan_number}}. This disclosure is provided by {{partner_name}}, the mortgagee, under the Homeowners Protection Act of 1998. Your loan has a fixed interest rate of {{note_rate_pct}}% and a term of {{term_months}} months. Your loan requires private mortgage insurance (PMI). PMI protects the lender if you do not repay the loan. The monthly premium is {{money monthly_premium_cents}}.{{/block}}
{{#block "original-value" page=1 y=0.24 pt=11}}Original value of the property: {{money original_value_cents}}. This is the lesser of the sales price and the appraised value at the time the loan was made. 80 percent of the original value is {{money threshold_80_cents}}. 78 percent of the original value is {{money threshold_78_cents}}.{{/block}}
{{#block "cancellation" page=1 y=0.32 pt=11}}Cancellation date. You may cancel the PMI requirement on {{date cancellation_date}}. That is the date on which the principal balance of your loan is first scheduled to reach 80 percent of the original value under the initial amortization schedule attached to this notice. You may request cancellation earlier than that date on the date the principal balance, based solely on your actual payments, reaches 80 percent of the original value. To cancel, send a written request to the servicer. Cancellation requires a good payment history, that you are current on the loan, and, if the servicer requires it, evidence that the value of the property has not declined below the original value and that there are no subordinate liens on the property.{{/block}}
{{#block "termination" page=1 y=0.5 pt=11}}Termination date. The requirement for PMI will automatically terminate on {{date termination_date}}. That is the date on which the principal balance is first scheduled to reach 78 percent of the original value, regardless of the outstanding balance on that date, if you are current on the loan. If you are not current on that date, PMI terminates on the first day of the first month after you become current.{{/block}}
{{#block "midpoint" page=1 y=0.62 pt=11}}Final termination. If PMI has not been cancelled or terminated earlier, it will end on {{date midpoint_termination_date}}, the first day of the month after the midpoint of the amortization period, if you are current on that date.{{/block}}
{{#block "exemptions" page=1 y=0.7 pt=11}}Exemptions. There are exemptions to the right to cancel and to automatic termination for loans the lender treats as high-risk. {{#if high_risk}}An exemption applies to your loan: PMI may continue beyond the dates above, but in no case beyond {{date midpoint_termination_date}}, the midpoint of the amortization period.{{else}}No exemption applies to your loan.{{/if}}{{/block}}
{{#block "servicer" page=1 y=0.8 pt=11}}The servicer will send you a written statement of your cancellation and termination rights each year. Questions about this notice go to the servicer named on your monthly statement. Each option above is stated as it applies to your loan; nothing in this notice changes your loan terms.{{/block}}
{{#block "schedule-heading" page=2 y=0.04 pt=12 bold}}Initial Amortization Schedule{{/block}}
{{#block "schedule-intro" page=2 y=0.08 pt=10}}Loan amount {{money note_amount_cents}} at {{note_rate_pct}}% for {{term_months}} months. Monthly principal and interest {{money pi_cents}}. First payment due {{date first_payment_due}}. {{schedule_rows}} payments are listed. Schedule reference {{schedule_hash}}.{{/block}}
{{#block "schedule" page=2 y=0.12 pt=8}}{{#each schedule}}Payment {{n}} due {{date due_date}}: payment {{money payment_cents}}, interest {{money interest_cents}}, principal {{money principal_cents}}, balance after payment {{money upb_after_cents}}.
{{/each}}{{/block}}`;

export const HPA_4903_INITIAL_FIXED_RULES: ContentRule[] = [
  R("heading-top", "12 U.S.C. 4903(a)(1)(A)(ii): written notice", "layout", "heading", "the notice heading at the top of page 1 in ≥ 12-point bold", { layout: { page: 1, maxYFraction: 0.08, minPt: 12, bold: true } }),
  R("mortgagee-named", "12 U.S.C. 4903(a)(1): 'the mortgagee shall provide'", "presence", "provided by .+, the mortgagee, under the Homeowners Protection Act of 1998", "the partner is named as mortgagee"),
  R("at-consummation", "12 U.S.C. 4903(a)(1): 'at the time at which the transaction is consummated'", "presence", "Date of consummation: [A-Z][a-z]+ \\d{1,2}, \\d{4}", "the consummation date is stated"),
  R("original-value", "12 U.S.C. 4901(12): original value", "presence", "Original value of the property: \\$[\\d,]+\\.\\d{2}\\. This is the lesser of the sales price and the appraised value", "original value and its definition"),
  R("cancellation-date-I", "12 U.S.C. 4903(a)(1)(A)(ii)(I); 4901(2)(A)(i): first scheduled to reach 80 percent", "presence", "You may cancel the PMI requirement on [A-Z][a-z]+ \\d{1,2}, \\d{4}\\. That is the date on which the principal balance of your loan is first scheduled to reach 80 percent of the original value", "the cancellation date (scheduled 80%)"),
  R("actual-payments-II", "12 U.S.C. 4903(a)(1)(A)(ii)(II); 4901(2)(A)(ii): based solely on actual payments", "presence", "You may request cancellation earlier than that date on the date the principal balance, based solely on your actual payments, reaches 80 percent", "the actual-payments alternative"),
  R("4902a-conditions", "12 U.S.C. 4902(a)(2)–(4): good payment history, current, no decline / no subordinate liens", "presence", "good payment history, that you are current on the loan, and, if the servicer requires it, evidence that the value of the property has not declined below the original value and that there are no subordinate liens", "the §4902(a) cancellation conditions"),
  R("termination-date-III", "12 U.S.C. 4903(a)(1)(A)(ii)(III); 4901(18): first scheduled to reach 78 percent, irrespective of the outstanding balance", "presence", "will automatically terminate on [A-Z][a-z]+ \\d{1,2}, \\d{4}\\. That is the date on which the principal balance is first scheduled to reach 78 percent of the original value, regardless of the outstanding balance", "the termination date (scheduled 78%)"),
  R("not-current-continues", "12 U.S.C. 4902(b)(2): termination on the first day of the first month after the mortgagor becomes current", "presence", "If you are not current on that date, PMI terminates on the first day of the first month after you become current", "the not-current rule"),
  R("midpoint", "12 U.S.C. 4902(c); 4901(7): midpoint of the amortization period", "presence", "will end on [A-Z][a-z]+ \\d{1,2}, \\d{4}, the first day of the month after the midpoint of the amortization period", "final termination at the midpoint"),
  R("exemptions-IV", "12 U.S.C. 4903(a)(1)(A)(ii)(IV): exemptions and whether they apply", "presence", "Exemptions\\. There are exemptions to the right to cancel and to automatic termination .* (No exemption applies to your loan\\.|An exemption applies to your loan)", "the high-risk exemption statement and whether it applies"),
  R("annual-statement", "12 U.S.C. 4903(a)(3): annual written statement", "presence", "written statement of your cancellation and termination rights each year", "the annual disclosure statement"),
  R("schedule-heading", "12 U.S.C. 4903(a)(1)(A)(i): a written initial amortization schedule", "layout", "schedule-heading", "the amortization schedule heading on page 2 in ≥ 12-point bold", { layout: { page: 2, minPt: 12, bold: true } }),
  R("schedule-terms", "12 U.S.C. 4901(5): initial amortization schedule from the note terms", "presence", "Loan amount \\$[\\d,]+\\.\\d{2} at \\d+\\.\\d{3}% for \\d+ months\\. Monthly principal and interest \\$[\\d,]+\\.\\d{2}\\. First payment due [A-Z][a-z]+ \\d{1,2}, \\d{4}", "the schedule states the note terms"),
  R("schedule-first-row", "12 U.S.C. 4903(a)(1)(A)(i)", "presence", "Payment 1 due [A-Z][a-z]+ \\d{1,2}, \\d{4}: payment \\$[\\d,]+\\.\\d{2}, interest \\$[\\d,]+\\.\\d{2}, principal \\$[\\d,]+\\.\\d{2}, balance after payment \\$[\\d,]+\\.\\d{2}", "the schedule lists payment 1"),
  R("schedule-complete", "12 U.S.C. 4903(a)(1)(A)(i): the full initial schedule (every payment through maturity)", "data_equality", "schedule_rows", "schedule_rows equals term_months", { predicate: { "==": [{ var: "schedule_rows" }, { var: "term_months" }] } }),
  R("schedule-hash", "24.6 audit: immutable schedule hash", "data_equality", "schedule_hash", "the schedule hash is present", { predicate: { matches: ["schedule_hash", "^[0-9a-f]{64}$"] } }),
  R("dates-distinct", "12 U.S.C. 4901(2), (18): the 78% date is a later scheduled date than the 80% date", "data_equality", "termination_date", "termination date is a date distinct from the cancellation date", { predicate: { and: [{ matches: ["termination_date", "^\\d{4}-\\d{2}-\\d{2}$"] }, { "!=": [{ var: "termination_date" }, { var: "cancellation_date" }] }] } }),
  R("protects-lender", "24.6 borrower-facing: MI protects the lender", "presence", "PMI protects the lender if you do not repay the loan", "plain statement of whom MI protects"),
  R("no-steering", "24.6 guardrails: never steering", "absence", "(we recommend|you should choose|best option)", "no steering language"),
];
export const HPA_4903_INITIAL_FIXED_SAMPLE: Record<string, unknown> = { ...FIXTURE_PARTIES, consummation_date: "2026-11-18", note_rate_pct: "6.375", term_months: 360, premium_plan: "bpmi_monthly", monthly_premium_cents: 13_047n,
  original_value_cents: 45_780_000n, threshold_80_cents: FIXTURE_DATES.threshold_80_cents, threshold_78_cents: FIXTURE_DATES.threshold_78_cents, cancellation_date: FIXTURE_DATES.cancellation_date, termination_date: FIXTURE_DATES.termination_date, midpoint_termination_date: FIXTURE_DATES.midpoint_termination_date, high_risk: false,
  note_amount_cents: 41_200_000n, pi_cents: FIXTURE_SCHEDULE.pi_cents, first_payment_due: "2027-01-01", schedule_rows: FIXTURE_SCHEDULE.schedule.rows.length, schedule_hash: FIXTURE_SCHEDULE.schedule_hash,
  schedule: FIXTURE_SCHEDULE.schedule.rows.map((r) => ({ n: r.n, due_date: r.due_date, payment_cents: r.payment_cents, interest_cents: r.interest_cents, principal_cents: r.principal_cents, upb_after_cents: r.upb_after_cents })) };

// ------------------------------------------------------------------ NTC_HPA_4903_INITIAL_ARM
export const HPA_4903_INITIAL_ARM_SOURCE = `{{#block "heading" page=1 y=0.04 pt=14 bold}}Private Mortgage Insurance Initial Disclosure (Adjustable-Rate Loan){{/block}}
{{#block "intro" page=1 y=0.1 pt=11}}Date of consummation: {{date consummation_date}}. Borrower: {{borrower_name}}. Property: {{property_address}}. Loan number: {{loan_number}}. This disclosure is provided by {{partner_name}}, the mortgagee, under the Homeowners Protection Act of 1998. Your loan has an adjustable interest rate. Your loan requires private mortgage insurance (PMI). PMI protects the lender if you do not repay the loan.{{/block}}
{{#block "original-value" page=1 y=0.22 pt=11}}Original value of the property: {{money original_value_cents}}. This is the lesser of the sales price and the appraised value at the time the loan was made.{{/block}}
{{#block "cancellation" page=1 y=0.28 pt=11}}Cancellation date. You may cancel the PMI requirement on the cancellation date. The cancellation date is the date on which the principal balance of your loan is first scheduled to reach 80 percent of the original value under the amortization schedule then in effect. Under the schedule in effect at consummation that date is {{date cancellation_date}}. Because your interest rate can change, the date can change; the servicer will tell you the current date each year. You may request cancellation earlier on the date the principal balance, based solely on your actual payments, reaches 80 percent of the original value. Cancellation requires a good payment history, that you are current on the loan, and, if the servicer requires it, evidence that the value of the property has not declined below the original value and that there are no subordinate liens on the property.{{/block}}
{{#block "termination" page=1 y=0.5 pt=11}}Termination date. The requirement for PMI will automatically terminate on the termination date. The termination date is the date on which the principal balance is first scheduled to reach 78 percent of the original value under the amortization schedule then in effect, regardless of the outstanding balance on that date. Under the schedule in effect at consummation that date is {{date termination_date}}. On the termination date you will be notified that PMI has terminated or, if you are not current on the loan on that date, that the requirement continues until you become current.{{/block}}
{{#block "midpoint" page=1 y=0.66 pt=11}}Final termination. If PMI has not been cancelled or terminated earlier, it will end on {{date midpoint_termination_date}}, the first day of the month after the midpoint of the amortization period, if you are current on that date.{{/block}}
{{#block "exemptions" page=1 y=0.74 pt=11}}Exemptions. There are exemptions to the right to cancel and to automatic termination for loans the lender treats as high-risk. {{#if high_risk}}An exemption applies to your loan: PMI may continue beyond the dates above, but in no case beyond {{date midpoint_termination_date}}, the midpoint of the amortization period.{{else}}No exemption applies to your loan.{{/if}}{{/block}}
{{#block "servicer" page=1 y=0.84 pt=11}}The servicer will send you a written statement of your cancellation and termination rights each year. Questions about this notice go to the servicer named on your monthly statement.{{/block}}`;

export const HPA_4903_INITIAL_ARM_RULES: ContentRule[] = [
  R("heading-top", "12 U.S.C. 4903(a)(1)(B): written notice", "layout", "heading", "the notice heading at the top of page 1 in ≥ 12-point bold", { layout: { page: 1, maxYFraction: 0.08, minPt: 12, bold: true } }),
  R("mortgagee-named", "12 U.S.C. 4903(a)(1)", "presence", "provided by .+, the mortgagee, under the Homeowners Protection Act of 1998", "the partner is named as mortgagee"),
  R("cancellation-then-in-effect", "12 U.S.C. 4903(a)(1)(B)(i); 4901(2)(B): amortization schedule then in effect", "presence", "first scheduled to reach 80 percent of the original value under the amortization schedule then in effect\\. Under the schedule in effect at consummation that date is [A-Z][a-z]+ \\d{1,2}, \\d{4}", "the cancellation date under the schedule then in effect"),
  R("actual-payments", "12 U.S.C. 4901(2)(A)(ii)", "presence", "based solely on your actual payments, reaches 80 percent", "the actual-payments alternative"),
  R("4902a-conditions", "12 U.S.C. 4902(a)(2)–(4)", "presence", "good payment history, that you are current on the loan", "the §4902(a) conditions"),
  R("termination-then-in-effect", "12 U.S.C. 4903(a)(1)(B)(ii); 4901(18)", "presence", "first scheduled to reach 78 percent of the original value under the amortization schedule then in effect, regardless of the outstanding balance on that date\\. Under the schedule in effect at consummation that date is [A-Z][a-z]+ \\d{1,2}, \\d{4}", "the termination date under the schedule then in effect"),
  R("notified-on-termination", "12 U.S.C. 4903(a)(1)(B)(iii): on the termination date the mortgagor will be notified of the termination or that the requirement continues", "presence", "On the termination date you will be notified that PMI has terminated or, if you are not current on the loan on that date, that the requirement continues", "the termination-date notification statement"),
  R("midpoint", "12 U.S.C. 4902(c)", "presence", "first day of the month after the midpoint of the amortization period", "final termination at the midpoint"),
  R("exemptions", "12 U.S.C. 4903(a)(1)(A)(ii)(IV), (a)(2)", "presence", "(No exemption applies to your loan\\.|An exemption applies to your loan)", "whether the high-risk exemption applies"),
  R("dates-distinct", "12 U.S.C. 4901(2), (18)", "data_equality", "termination_date", "termination date is a date distinct from the cancellation date", { predicate: { and: [{ matches: ["termination_date", "^\\d{4}-\\d{2}-\\d{2}$"] }, { "!=": [{ var: "termination_date" }, { var: "cancellation_date" }] }] } }),
  R("no-steering", "24.6 guardrails", "absence", "(we recommend|you should choose|best option)", "no steering language"),
];
export const HPA_4903_INITIAL_ARM_SAMPLE: Record<string, unknown> = { ...FIXTURE_PARTIES, consummation_date: "2026-11-18", original_value_cents: 45_780_000n, cancellation_date: FIXTURE_DATES.cancellation_date, termination_date: FIXTURE_DATES.termination_date, midpoint_termination_date: FIXTURE_DATES.midpoint_termination_date, high_risk: false };

// ------------------------------------------------------------------ NTC_HPA_4905_LPMI
export const HPA_4905_LPMI_SOURCE = `{{#block "heading" page=1 y=0.04 pt=14 bold}}Lender-Paid Mortgage Insurance Disclosure{{/block}}
{{#block "intro" page=1 y=0.1 pt=11}}Date: {{date delivered_on}}. Borrower: {{borrower_name}}. Property: {{property_address}}. This disclosure is provided by {{partner_name}} under the Homeowners Protection Act of 1998 no later than the date on which a loan commitment is made. Your loan will have lender-paid mortgage insurance. Lender-paid mortgage insurance is mortgage insurance whose premiums are paid by a person other than you, the borrower. Mortgage insurance protects the lender if you do not repay the loan.{{/block}}
{{#block "differences" page=1 y=0.24 pt=11}}Lender-paid mortgage insurance differs from borrower-paid mortgage insurance in three ways. First, lender-paid mortgage insurance may not be canceled by the mortgagor, while borrower-paid mortgage insurance could be cancelable. Second, lender-paid mortgage insurance usually results in a residential mortgage having a higher interest rate than it would in the case of borrower-paid mortgage insurance.{{#if lpmi_rate_adjustment_pct}} For this loan the interest rate includes an adjustment of {{lpmi_rate_adjustment_pct}} percentage points for the lender-paid mortgage insurance.{{/if}} Third, lender-paid mortgage insurance terminates only when the residential mortgage is refinanced, paid off, or otherwise terminated.{{/block}}
{{#block "equivalent-date" page=1 y=0.46 pt=11}}If your loan instead had borrower-paid mortgage insurance, the insurance would automatically terminate on {{date lpmi_equiv_termination_date}}, the date the principal balance is first scheduled to reach 78 percent of the original value of {{money original_value_cents}}, or by {{date midpoint_termination_date}} at the latest. No later than 30 days after {{date lpmi_equiv_termination_date}} the servicer will send you a notice stating that you may wish to review your financing options, because borrower-paid mortgage insurance would have terminated by then.{{/block}}
{{#block "closing" page=1 y=0.62 pt=11}}This disclosure does not change the terms of your loan. Keep it with your loan documents. Questions about it go to {{partner_name}} or to the servicer named on your monthly statement.{{/block}}`;

export const HPA_4905_LPMI_RULES: ContentRule[] = [
  R("heading-top", "12 U.S.C. 4905(c)(1): written notice", "layout", "heading", "the notice heading at the top of page 1 in ≥ 12-point bold", { layout: { page: 1, maxYFraction: 0.08, minPt: 12, bold: true } }),
  R("timing-commitment", "12 U.S.C. 4905(c)(1): 'not later than the date on which a loan commitment is made'", "presence", "no later than the date on which a loan commitment is made", "the commitment-timing statement"),
  R("definition", "12 U.S.C. 4905(a): payments made by a person other than the borrower", "presence", "premiums are paid by a person other than you, the borrower", "the LPMI definition"),
  R("not-cancelable-A", "12 U.S.C. 4905(c)(1)(A)", "presence", "lender-paid mortgage insurance may not be canceled by the mortgagor, while borrower-paid mortgage insurance could be cancelable", "statement (A): not cancelable"),
  R("higher-rate-B", "12 U.S.C. 4905(c)(1)(B)", "presence", "usually results in a residential mortgage having a higher interest rate than it would in the case of borrower-paid mortgage insurance", "statement (B): higher rate"),
  R("terminates-only-C", "12 U.S.C. 4905(c)(1)(C)", "presence", "terminates only when the residential mortgage is refinanced, paid off, or otherwise terminated", "statement (C): termination"),
  R("equivalent-date", "12 U.S.C. 4905(c)(2): the termination date that would apply to borrower-paid MI", "presence", "would automatically terminate on [A-Z][a-z]+ \\d{1,2}, \\d{4}, the date the principal balance is first scheduled to reach 78 percent of the original value", "the BPMI-equivalent termination date"),
  R("options-notice-30d", "12 U.S.C. 4905(c)(2): notice not later than 30 days after that date", "presence", "No later than 30 days after [A-Z][a-z]+ \\d{1,2}, \\d{4} the servicer will send you a notice stating that you may wish to review your financing options", "the 30-day options notice statement"),
  R("delivered-on-present", "12 U.S.C. 4905(c)(1) timing evidence", "data_equality", "delivered_on", "the delivery date is recorded", { predicate: { matches: ["delivered_on", "^\\d{4}-\\d{2}-\\d{2}$"] } }),
  R("no-steering", "24.6 guardrails", "absence", "(we recommend|you should choose|best option)", "no steering language"),
];
export const HPA_4905_LPMI_SAMPLE: Record<string, unknown> = { ...FIXTURE_PARTIES, delivered_on: "2026-10-26", premium_plan: "lpmi_monthly", lpmi_rate_adjustment_pct: "0.250", lpmi_equiv_termination_date: FIXTURE_DATES.lpmi_equiv_termination_date, midpoint_termination_date: FIXTURE_DATES.midpoint_termination_date, original_value_cents: 45_780_000n };

export const VERSIONS_24_6: VersionInput[] = [
  V("NTC_HPA_4903_INITIAL_FIXED", HPA_4903_INITIAL_FIXED_SOURCE, HPA_4903_INITIAL_FIXED_RULES, HPA_4903_INITIAL_FIXED_SAMPLE, "hpa.4903.2026.v1", "12 U.S.C. 4903(a)(1)(A), 4901(2)/(5)/(7)/(12)/(18), 4902(a)–(c); 24.6 worked example 1 (purchase fixture: $412,000 at 6.375%/360, original value $457,800 → Oct 1, 2034 / Dec 1, 2035 / Jan 1, 2042)"),
  V("NTC_HPA_4903_INITIAL_ARM", HPA_4903_INITIAL_ARM_SOURCE, HPA_4903_INITIAL_ARM_RULES, HPA_4903_INITIAL_ARM_SAMPLE, "hpa.4903.2026.v1", "12 U.S.C. 4903(a)(1)(B), 4901(2)(B)/(18), 4902(c); 24.6 edge case (ARM variant; 10.x recomputes the 78% date at each reset)"),
  V("NTC_HPA_4905_LPMI", HPA_4905_LPMI_SOURCE, HPA_4905_LPMI_RULES, HPA_4905_LPMI_SAMPLE, "hpa.4905.2026.v1", "12 U.S.C. 4905(a), (c)(1)(A)–(C), (c)(2); 24.6 worked example 3 (LPMI +0.250%, delivered Mon Oct 26, 2026 with the conditional approval; BPMI-equivalent termination Dec 1, 2035)"),
];
export const OVERRIDES_24_6: Record<string, Partial<NoticeTemplate>> = {
  NTC_HPA_4903_INITIAL_FIXED: { citation: "12 U.S.C. 4903(a)(1)(A) (initial amortization schedule + notice at consummation); 4902(a)–(c)", noticeClass: "closing", channelPolicy: "esign_or_mail", separateDocument: true, mayCombineWith: [], retention: "fnma_loan_file_life_plus_4y", piiLevel: "high" },
  NTC_HPA_4903_INITIAL_ARM: { citation: "12 U.S.C. 4903(a)(1)(B) (notice at consummation; schedule then in effect)", noticeClass: "closing", channelPolicy: "esign_or_mail", separateDocument: true, mayCombineWith: [], retention: "fnma_loan_file_life_plus_4y", piiLevel: "high" },
  NTC_HPA_4905_LPMI: { citation: "12 U.S.C. 4905(c)(1) (no later than the loan commitment); (c)(2)", noticeClass: "origination_decisions", channelPolicy: "esign_or_mail", separateDocument: true, mayCombineWith: ["NTC_SM_CONDITIONAL_APPROVAL"], retention: "fnma_loan_file_life_plus_4y", piiLevel: "medium" },
};
