/**
 * Authored template versions for the §4 notices: the §1024.35 NoE letters,
 * the §1024.36 RFI letters, the continuity-of-contact and CA SPOC letters,
 * the successor-in-interest letters (§1024.38(b)(1)(vi), §1024.32(c)) and
 * the complaint/remediation letters. Each carries the checklist the spec
 * states; sample payloads are the spec's worked examples.
 */
import type { ContentRule, VersionInput } from "../registry.ts";
import { V } from "./section01.ts";

const R = (rule_id: string, citation: string, kind: ContentRule["kind"], selector: string, message: string, extra: Partial<ContentRule> = {}): ContentRule => ({ rule_id, citation, kind, selector, severity: "block", message, ...extra });
const CONTACT = `{{#block "contact" page=1 y=0.85 pt=10}}Call {{servicer_phone}}. Send notices of error and requests for information to {{exclusive_address}} or through {{online_channel}}.{{/block}}`;
const BASE = { servicer_phone: "(800) 555-0100", exclusive_address: "PO Box 2, Testville TX 75001", online_channel: "the secure message center at portal.example.com", account_last4: "1234", borrower_name: "Bea Borrower" };
const ADDR_RULES: ContentRule[] = [R("exclusive-address", "§1024.35(c); comment 35(c)-2", "presence", "notices of error and requests for information to ", "exclusive address block"), R("phone", "4.1 rule 7", "presence", "Call \\(\\d{3}\\) \\d{3}-\\d{4}", "telephone number")];
const FEE_RULES: ContentRule[] = [R("no-fee", "§1024.35(h)", "absence", "fee[^.]{0,60}(for|to) (this|your|the) (notice|dispute|review|investigation)", "no fee for the notice of error"), R("no-payment-condition", "§1024.35(h)", "absence", "(bring|make) (your )?(account|loan) current[^.]{0,40}(before|to) (we|our)", "no payment as a condition")];

// ------------------------------------------------------------------ 4.1 NoE
const ADDRESS_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}To assert an error on your account or to request information about it, you must send your notice of error or request for information to this address: {{exclusive_address}}. You may also use {{online_channel}}. The same address is used for requests for information. This address is also published at {{website}}.{{/block}}
${CONTACT}`;
const ADDRESS_RULES: ContentRule[] = [R("must-use", "§1024.35(c)", "presence", "you must send your notice of error or request for information to this address", "statement that the borrower must use the address"), R("same-for-rfi", "§1024.36(b)", "presence", "same address is used for requests for information", "same address for RFIs"), R("online", "§1024.35(c)", "presence", "You may also use ", "online channel"), R("website", "4.1 checklist", "presence", "published at ", "website mention"), ...ADDR_RULES];
const ADDRESS_CHANGE_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}Effective {{date effective_from}}, the address for notices of error and requests for information changes to {{new_address}}. Until then, continue to use {{exclusive_address}}. This notice is being sent before the change takes effect.{{/block}}
${CONTACT}`;
const ADDRESS_CHANGE_RULES: ContentRule[] = [R("new-address", "§1024.35(c); 4.1 data model", "presence", "changes to ", "new address"), R("before-effective", "4.1 data model constraint", "data_range", "days_before_effective", "mailed before effective_from", { range: { min: 1 } }), ...ADDR_RULES];

const ACK_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}We received your notice of error on {{date received_on}}. As we understand it, you assert: {{#each assertions}}({{n}}) {{text}} — we will respond by {{date response_due}}; {{/each}}If it would help, you may send supporting documents, but you are not required to.{{/block}}
${CONTACT}`;
const ACK_RULES: ContentRule[] = [R("assertions", "§1024.35(d); 4.1 checklist", "presence", "As we understand it, you assert: \\(1\\)", "assertions as understood"), R("response-dates", "§1024.35(e)(3)", "presence", "we will respond by (January|February|March|April|May|June|July|August|September|October|November|December) \\d{1,2}, \\d{4}", "applicable response dates"), R("documents-optional", "§1024.35(e)(2)", "presence", "you are not required to", "supporting documents phrased as optional"), R("timing-5bd", "§1024.35(d)", "data_range", "business_days_after_receipt", "within 5 business days", { range: { max: 5 } }), ...ADDR_RULES, ...FEE_RULES];

const RESPONSE_BODY = `{{#block "body" page=1 y=0.1 pt=11}}{{borrower_name}}, loan ending {{account_last4}}. We investigated your notice of error received {{date received_on}}. {{#each assertions}}({{n}}) {{text}}: {{determination}}{{#if action}} — {{action}}, effective {{date effective_on}}{{/if}}{{#if reasons}} — {{reasons}}{{/if}}. {{/each}}{{#if additional_errors}}We also found and corrected: {{additional_errors}}.{{/if}}{{/block}}
{{#block "rights" page=1 y=0.6 pt=11}}You may request copies of the documents we relied on by writing to {{exclusive_address}} or through {{online_channel}}.{{/block}}
{{#if ny}}{{#block "ny" page=1 y=0.75 pt=10}}New York State Department of Financial Services: (800) 342-3736, www.dfs.ny.gov.{{/block}}{{/if}}
${CONTACT}`;
const RESPONSE_RULES = (kind: "correction" | "no_error" | "additional"): ContentRule[] => [
  R("identity", "4.1 rule 7", "presence", "loan ending \\d{4}", "borrower name and masked loan identifier"),
  R("each-assertion", "§1024.35(e)(1)", "presence", "\\(1\\) .*: ", "each assertion restated with its determination"),
  ...(kind === "correction" ? [R("action-effective", "§1024.35(e)(1)(i)(A)", "presence", " — .*, effective ", "the correction and its effective date")] : []),
  ...(kind === "no_error" ? [R("statement-of-reasons", "§1024.35(e)(1)(i)(B)", "presence", " — [A-Za-z][^.]{10,}", "plain-language statement of reasons")] : []),
  ...(kind === "additional" ? [R("additional-errors", "§1024.35(e)(1)(ii)", "presence", "We also found and corrected", "additional errors identified")] : []),
  R("documents-right", "§1024.35(e)(1)(i)(B); (e)(4)", "presence", "request copies of the documents we relied on", "right to request relied-upon documents and how"),
  R("ny-dfs", "3 NYCRR 419.6", "conditional", "ny", "DFS disclosure for NY", { when: { "==": [{ var: "ny" }, true] }, predicate: { present: "ny" } }),
  R("timing", "§1024.35(e)(3)", "data_range", "business_days_after_receipt", "within the applicable clock", { range: { max: 45 } }),
  ...ADDR_RULES, ...FEE_RULES,
];
const RESPONSE_SAMPLE = (kind: "correction" | "no_error" | "additional"): Record<string, unknown> => ({ ...BASE, received_on: "2026-09-04", ny: false, business_days_after_receipt: 20,
  assertions: kind === "no_error" ? [{ n: 1, text: "the late fee assessed on March 17 was not owed", determination: "no error", reasons: "your payment was received on March 17, after the 15-day grace period that ended March 16" }] : [{ n: 1, text: "your March 1 payment was applied on March 17", determination: "error corrected", action: "we re-applied the payment as of March 1 and reversed the $92.11 late fee", effective_on: "2026-03-01" }],
  additional_errors: kind === "additional" ? "the April late fee assessed on the same basis" : null });

const EXTENSION_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}We need more time to respond to your notice of error received {{date received_on}}. Reason: {{reason}}. We will respond by {{date new_due}}, 15 business days beyond the original date.{{/block}}
${CONTACT}`;
const EXTENSION_RULES: ContentRule[] = [R("reason", "§1024.35(e)(3)(ii)", "presence", "Reason: [A-Za-z]", "reasons required"), R("new-date", "§1024.35(e)(3)(ii)", "presence", "We will respond by ", "new response date"), R("before-original", "§1024.35(e)(3)(ii)", "data_range", "business_days_after_receipt", "sent before the original 30-day deadline", { range: { max: 30 } }), ...ADDR_RULES];
const DOCS_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}As you requested on {{date requested_on}}, enclosed are copies of the documents we relied on in responding to your notice of error: {{#each documents}}{{this}}; {{/each}}{{/block}}
${CONTACT}`;
const DOCS_RULES: ContentRule[] = [R("documents", "§1024.35(e)(4)", "presence", "copies of the documents we relied on", "documents provided"), R("timing-15", "§1024.35(e)(4)", "data_range", "business_days_after_request", "within 15 business days", { range: { max: 15 } }), ...ADDR_RULES];
const WITHHELD_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}In response to your request of {{date requested_on}} for the documents we relied on, we are withholding the following because they are confidential, proprietary or privileged: {{#each withheld}}{{this}}; {{/each}}The documents provided are listed separately.{{/block}}
${CONTACT}`;
const WITHHELD_RULES: ContentRule[] = [R("withheld-basis", "§1024.35(e)(4)", "presence", "confidential, proprietary or privileged", "basis for withholding"), R("timing-15", "§1024.35(e)(4)", "data_range", "business_days_after_request", "within 15 business days", { range: { max: 15 } }), ...ADDR_RULES];
const EARLY_CORRECTION_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}We received your notice of error on {{date received_on}} and have corrected the error you asserted: {{correction}}, effective {{date effective_on}}. No further response is required from you.{{/block}}
${CONTACT}`;
const EARLY_CORRECTION_RULES: ContentRule[] = [R("corrected", "§1024.35(f)(1)", "presence", "have corrected the error", "correction stated"), R("timing-5", "§1024.35(f)(1)(ii)", "data_range", "business_days_after_receipt", "within 5 business days", { range: { max: 5 } }), ...ADDR_RULES, ...FEE_RULES];
const EXCEPTION_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}We are not responding further to part of your notice of error received {{date received_on}} because it is {{basis}}: {{explanation}}. {{#if carved_out}}We investigated and answered these assertions separately: {{carved_out}}.{{/if}}{{/block}}
${CONTACT}`;
const EXCEPTION_RULES: ContentRule[] = [R("basis", "§1024.35(g)(2)", "presence", "because it is (duplicative|overbroad|untimely)", "basis stated"), R("carve-out", "§1024.35(g)(1)(ii); 4.1 rule 4", "conditional", "carved_out", "overbroad notices list what was carved out and answered", { when: { "==": [{ var: "basis" }, "overbroad"] }, predicate: { present: "carved_out" } }), R("timing-5", "§1024.35(g)(2)", "data_range", "business_days_after_determination", "within 5 business days of the determination", { range: { max: 5 } }), ...ADDR_RULES];
const PROCEDURES_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}If you believe we made an error on your account, you may send a written notice of error, and if you want information about your account, a written request for information, to {{exclusive_address}} or through {{online_channel}}. We will acknowledge it within 5 business days and respond within the time the law allows. You may also call {{servicer_phone}} to discuss your concern, but a telephone call is not a notice of error.{{/block}}
${CONTACT}`;
const PROCEDURES_RULES: ContentRule[] = [R("how-to-noe", "§1024.38(b)(5); comment 38(b)(5)-1", "presence", "send a written notice of error", "how to assert an error"), R("how-to-rfi", "§1024.38(b)(5)", "presence", "request for information", "how to request information"), R("oral-not-noe", "comment 35(a)-1", "presence", "telephone call is not a notice of error", "oral complaints are not NoEs"), ...ADDR_RULES];

// ------------------------------------------------------------------ 4.2 RFI
const RFI_ACK_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}We received your request for information on {{date received_on}}. You asked for: {{#each items}}({{n}}) {{text}} — we will respond by {{date response_due}}; {{/each}}{{/block}}
${CONTACT}`;
const RFI_ACK_RULES: ContentRule[] = [R("items", "§1024.36(c)", "presence", "You asked for: \\(1\\)", "items as understood"), R("timing-5", "§1024.36(c)", "data_range", "business_days_after_receipt", "within 5 business days", { range: { max: 5 } }), ...ADDR_RULES];
const RFI_RESPONSE_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}In response to your request received {{date received_on}}: {{#each items}}({{n}}) {{text}} — {{answer}}; {{/each}}Attachments: {{#each attachments}}{{this}}; {{/each}}{{/block}}
${CONTACT}`;
const RFI_RESPONSE_RULES: ContentRule[] = [R("answers", "§1024.36(d)(1)(i)", "presence", "\\(1\\) .* — ", "each item answered"), R("attachments-index", "4.2 outputs", "presence", "Attachments: ", "attachments index"), R("redaction", "§1024.36(d)(3)", "data_equality", "redaction_check_passed", "redaction check passed before send", { predicate: { "==": [{ var: "redaction_check_passed" }, true] } }), ...ADDR_RULES];
const NOT_AVAILABLE_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}After a reasonable search we determined that the following information is not available to us: {{#each items}}({{n}}) {{text}} — basis: {{basis}}; {{/each}}{{/block}}
${CONTACT}`;
const NOT_AVAILABLE_RULES: ContentRule[] = [R("basis", "§1024.36(d)(1)(ii); 4.2 rule 3", "presence", "basis: (not in our possession|backup or archived media|retention period|extraordinary)", "the (d)(1)(ii) basis names the records class"), R("search-log", "4.2 guardrails", "data_equality", "search_log_complete", "search log covers the mandatory classes", { predicate: { "==": [{ var: "search_log_complete" }, true] } }), ...ADDR_RULES];
const RFI_EXTENSION_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}We need more time to respond to your request received {{date received_on}}. Reason: {{reason}}. We will respond by {{date new_due}}, 15 business days beyond the original date.{{/block}}
${CONTACT}`;
const RFI_EXTENSION_RULES: ContentRule[] = [R("reason", "§1024.36(d)(2)(ii)", "presence", "Reason: [A-Za-z]", "reason stated"), R("before-original", "§1024.36(d)(2)(ii)", "data_range", "business_days_after_receipt", "sent before the original deadline", { range: { max: 30 } }), ...ADDR_RULES];
const RFI_EARLY_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}Enclosed is the information you requested on {{date received_on}}: {{#each items}}({{n}}) {{text}}; {{/each}}{{/block}}
${CONTACT}`;
const RFI_EARLY_RULES: ContentRule[] = [R("provided", "§1024.36(e)", "presence", "Enclosed is the information you requested", "information provided"), R("timing-5", "§1024.36(e)", "data_range", "business_days_after_receipt", "within 5 business days", { range: { max: 5 } }), ...ADDR_RULES];
const RFI_EXCEPTION_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}We are not providing part of the information requested on {{date received_on}}: {{#each items}}({{n}}) {{text}} — {{basis}}; {{/each}}We did provide: {{provided}}.{{/block}}
${CONTACT}`;
const RFI_EXCEPTION_RULES: ContentRule[] = [R("basis-per-item", "§1024.36(f)(2)", "presence", "\\(1\\) .* — (duplicative|confidential|proprietary|privileged|irrelevant|overbroad|unduly burdensome|untimely)", "basis per item"), R("what-was-provided", "4.2 outputs", "presence", "We did provide: ", "what was provided"), R("timing-5", "§1024.36(f)(2)", "data_range", "business_days_after_determination", "within 5 business days of the determination", { range: { max: 5 } }), ...ADDR_RULES];
const OWNER_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}The owner of your mortgage loan is {{owner_block}}. This is accurate as of {{date as_of}}; the owner may change. You may contact the owner at {{owner_address}}, {{owner_phone}}. Your servicer is Supermortgage, {{servicer_address}}.{{#if ny}} New York State Department of Financial Services: (800) 342-3736.{{/if}}{{/block}}
${CONTACT}`;
const OWNER_RULES: ContentRule[] = [R("fannie-mae-block", "comment 36(a)-2; A4-1-03", "presence", "owner of your mortgage loan is Fannie Mae( in its capacity as Trustee)?\\.", "the versioned Fannie Mae block"), R("as-of", "comment 36(a)-2", "presence", "accurate as of .*; the owner may change", "as-of sentence"), R("no-mers", "4.2 rule 2", "absence", "MERS", "MERS is never named as owner"), R("timing-10", "§1024.36(d)(2)(i)(A)", "data_range", "business_days_after_receipt", "within 10 business days", { range: { max: 10 } }), ...ADDR_RULES];
const SII_DOCS_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}You told us that {{deceased_or_transferor}} transferred an ownership interest in the property to you. To confirm your status as a successor in interest, please send: {{#each documents}}{{this}}; {{/each}}{{#if questions}}Please also tell us: {{#each questions}}{{this}} {{/each}}{{/if}}Send them to {{exclusive_address}}. Until confirmation we cannot share account information; after confirmation you may resubmit your request.{{/block}}
${CONTACT}`;
const SII_DOCS_RULES: ContentRule[] = [R("description", "§1024.36(i)(1); §1024.38(b)(1)(vi)(B)", "presence", "please send: ", "description of the documents"), R("resubmit", "§1024.36(i)(3)", "presence", "after confirmation you may resubmit your request", "resubmit-after-confirmation statement"), R("no-account-info", "§1024.36(i)", "absence", "balance|payment history|past due", "no account information before confirmation"), R("timing-30", "§1024.36(i)(3)", "data_range", "business_days_after_receipt", "within 30 business days", { range: { max: 30 } }), ...ADDR_RULES];

// ------------------------------------------------------------------ 4.3 continuity, CA SPOC
const CONTACT_ASSIGNED_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}Your loan has been assigned to {{team_name}}. Your contact is {{named_human_first_name}}, {{title}}. Call {{direct_number}} during {{hours}}; you will first reach our automated assistant and may ask for {{named_human_first_name}} at any time. Your team can tell you which loss mitigation options may be available, what you need to send us, the status of your application, and the circumstances under which we may refer your loan to foreclosure.{{/block}}
${CONTACT}`;
const CONTACT_ASSIGNED_RULES: ContentRule[] = [R("team", "§1024.40(a); comment 40(a)-2", "presence", "assigned to .*\\. Your contact is [A-Z][a-z]+, ", "team and named human"), R("direct-number", "§1024.40(a)(2)", "presence", "Call \\(\\d{3}\\) \\d{3}-\\d{4} during", "direct number and hours"), R("human-available", "4.3 rule 2", "presence", "may ask for .* at any time", "a human is reachable"), R("b1-facts", "§1024.40(b)(1)", "presence", "which loss mitigation options.*what you need to send us.*status.*foreclosure", "the (b)(1) subjects"), ...ADDR_RULES];
const CA_SPOC_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}As required by California Civil Code section 2923.7, your single point of contact is {{spoc_name}} ({{spoc_kind}}). Reach them directly at {{direct_number}} or {{direct_email}}. Your single point of contact is responsible for communicating the process for applying for a foreclosure prevention alternative, coordinating receipt of your documents, informing you of the status, and ensuring you are considered for all available options.{{/block}}
${CONTACT}`;
const CA_SPOC_RULES: ContentRule[] = [R("statute", "Cal. Civ. Code §2923.7", "presence", "California Civil Code section 2923.7", "statutory basis"), R("direct-means", "§2923.7(a)", "presence", "Reach them directly at", "direct means of communication"), R("responsibilities", "§2923.7(b)", "presence", "responsible for communicating .* coordinating .* status .* all available options", "the SPOC responsibilities"), R("human", "4.3 rule 4", "data_equality", "spoc_kind", "the SPOC is a human individual or team", { predicate: { in: [{ var: "spoc_kind" }, ["human individual", "human team"]] } }), ...ADDR_RULES];

// ------------------------------------------------------------------ 4.4 successor in interest
const SII_ADDL_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}Thank you for the documents received {{date received_on}}. To confirm your status we still need: {{#each still_required}}{{this}} — because {{why}}; {{/each}}Send them to {{exclusive_address}}.{{/block}}
${CONTACT}`;
const SII_ADDL_RULES: ContentRule[] = [R("still-required", "§1024.38(b)(1)(vi)(C)", "presence", "we still need: .* — because ", "what is still required and why"), R("timing-5", "4.4 timer table REGX_1024_38B1VI_SII_ADDL_DOCS_5", "data_range", "business_days_after_receipt", "within 5 business days", { range: { max: 5 } }), ...ADDR_RULES];
const SII_CONFIRMED_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}We have confirmed you as a successor in interest to the mortgage loan on {{property_address}} as of {{date confirmed_on}}. You may send notices of error, requests for information and payoff requests, and apply for loss mitigation. You are not personally liable on the loan unless you assume it; an assumption agreement is offered separately and you may decline it. {{#if delinquent}}Your assigned contact: {{team_name}}, {{direct_number}}.{{/if}}{{/block}}
${CONTACT}`;
const SII_CONFIRMED_RULES: ContentRule[] = [R("confirmed", "§1024.38(b)(1)(vi)(C)", "presence", "confirmed you as a successor in interest", "confirmation"), R("rights", "§1024.30(d)", "presence", "notices of error, requests for information and payoff requests", "rights summary"), R("not-obligor", "4.4 guardrails", "presence", "not personally liable on the loan unless you assume it", "non-obligor statement"), R("assumption-option", "D1-4.1-02", "presence", "assumption agreement is offered separately", "assumption option"), R("continuity", "4.3", "conditional", "delinquent", "continuity block if delinquent", { when: { "==": [{ var: "delinquent" }, true] }, predicate: { present: "direct_number" } }), ...ADDR_RULES];
const SII_NOT_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}Based on the documents received, we cannot confirm you as a successor in interest because {{reason}}. What would change this outcome: {{what_would_change}}. If you believe we made an error, you may send a notice of error to {{exclusive_address}}.{{/block}}
${CONTACT}`;
const SII_NOT_RULES: ContentRule[] = [R("reason", "§1024.38(b)(1)(vi)(C); 4.4 rule 4", "presence", "because (the transfer|you|no ownership)", "reason mapped to the definition"), R("what-would-change", "4.4 outputs", "presence", "What would change this outcome: ", "what would change the outcome"), R("noe-path", "4.4 outputs", "presence", "you may send a notice of error", "how to submit an NoE"), R("officer", "4.4 state machine", "data_equality", "officer_signoff", "officer sign-off on a not-successor determination", { predicate: { "==": [{ var: "officer_signoff" }, true] } }), ...ADDR_RULES];
const SII_ACK_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}As a confirmed successor in interest you may receive the mortgage loan's periodic statements and other disclosures. (1) You are not liable for the mortgage debt and cannot be required to use the disclosures. (2) You may receive them by signing and returning the enclosed acknowledgment. (3) You may request them by writing to {{exclusive_address}} at any time. (4) You can revoke your acknowledgment at any time. Acknowledgment: I, {{successor_name}}, acknowledge receipt of this notice and request the disclosures. Signature ____ Date ____{{/block}}
${CONTACT}`;
const SII_ACK_RULES: ContentRule[] = [R("four-statements", "§1024.32(c)(1)(i)–(iv)", "presence", "\\(1\\) You are not liable .* \\(2\\) You may receive them .* \\(3\\) You may request them .* \\(4\\) You can revoke", "the four required statements"), R("ack-form", "§1024.32(c)(1)", "presence", "Acknowledgment: I, .*, acknowledge receipt", "acknowledgment form"), ...ADDR_RULES];
const ASSUMPTION_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}As a confirmed successor in interest you may assume this mortgage loan. Fannie Mae requires an assumption agreement for {{transfer_type}} transfers (Servicing Guide D1-4.1-02). Assuming the loan makes you personally liable for it; declining does not affect your rights as a confirmed successor. No fee is charged for the assumption. To proceed, {{how_to_proceed}}.{{/block}}
${CONTACT}`;
const ASSUMPTION_RULES: ContentRule[] = [R("guide-basis", "D1-4.1-02; F-1-17", "presence", "Servicing Guide D1-4.1-02", "Fannie Mae basis"), R("may-decline", "4.4 rule 6", "presence", "declining does not affect your rights", "declining does not affect rights"), R("no-fee", "4.4 rule 7", "presence", "No fee is charged", "no assumption fee by default"), ...ADDR_RULES];

// ------------------------------------------------------------------ 4.5 complaints
const COMPLAINT_ACK_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}We received your complaint on {{date received_on}} and are reviewing it. We will respond by {{date response_by}}. {{#if ny}}Under New York regulation 3 NYCRR 419.6 you may also contact the New York State Department of Financial Services at (800) 342-3736.{{/if}}{{/block}}
${CONTACT}`;
const COMPLAINT_ACK_RULES: ContentRule[] = [R("received", "4.5 outputs", "presence", "received your complaint on", "receipt acknowledged"), R("response-date", "4.5 rule 1", "presence", "We will respond by", "response date"), R("ny-419-6", "3 NYCRR 419.6", "conditional", "ny", "NY variant carries the 419.6 disclosure", { when: { "==": [{ var: "ny" }, true] }, predicate: { present: "ny" } }), R("timing", "4.5 timer table SM_COMPLAINT_ACK_1BD / NY 5 BD", "data_range", "business_days_after_receipt", "acknowledged within the clock", { range: { max: 5 } }), ...ADDR_RULES];
const COMPLAINT_RESPONSE_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}We reviewed your complaint received {{date received_on}}. What we found: {{found}}. What we fixed and when: {{fixed}}. What you can do next: {{next_steps}}. {{#if ny}}You may also contact the New York State Department of Financial Services at (800) 342-3736.{{/if}}{{/block}}
{{#block "procedures" page=1 y=0.6 pt=11}}If you believe we made an error, you may send a written notice of error to {{exclusive_address}}; if you want information about your account, a written request for information to the same address.{{/block}}
${CONTACT}`;
const COMPLAINT_RESPONSE_RULES: ContentRule[] = [R("found-fixed-next", "4.5 rule 5", "presence", "What we found: .* What we fixed and when: .* What you can do next: ", "plain-language findings, fix and next steps"), R("procedures", "§1024.38(b)(5)", "presence", "you may send a written notice of error", "the §1024.38(b)(5) procedures paragraph"), R("no-payment-required", "4.5 guardrails", "absence", "must (pay|bring your account current) (before|to)", "never requires a payment to proceed"), R("ny-dfs", "3 NYCRR 419.6", "conditional", "ny", "DFS line for NY", { when: { "==": [{ var: "ny" }, true] }, predicate: { present: "ny" } }), ...ADDR_RULES];
const REMEDIATION_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}Our review found that a {{fee_description}} of {{money amount_cents}} assessed on {{date assessed_on}} should not have been charged. We reversed it as of {{date assessed_on}}{{#if refund_by_check}} and enclosed a refund check{{/if}}. If this affected your credit reporting, we have corrected it. No action is needed from you.{{/block}}
${CONTACT}`;
const REMEDIATION_RULES: ContentRule[] = [R("what-and-amount", "4.5 rule 3", "presence", "of \\$[\\d,]+\\.\\d{2} assessed on", "fee and amount"), R("reversed-original-date", "4.5 rule 3", "presence", "reversed it as of", "reversal as of the original assessment date"), R("credit-corrected", "8.1", "presence", "corrected it", "credit reporting correction where applicable"), ...ADDR_RULES];
const TX_CURE_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}You notified us on {{date notice_on}} of an alleged failure to comply with Texas Constitution article XVI, section 50(a)(6). Under section 50(a)(6)(Q)(x) we are curing it as follows: {{cure}}. The cure will be completed by {{date cure_by}}, within 60 days of your notice. This letter was reviewed by counsel.{{/block}}
${CONTACT}`;
const TX_CURE_RULES: ContentRule[] = [R("basis", "Tex. Const. art. XVI §50(a)(6)(Q)(x)", "presence", "section 50\\(a\\)\\(6\\)\\(Q\\)\\(x\\)", "constitutional basis"), R("cure", "§50(a)(6)(Q)(x)", "presence", "curing it as follows: ", "the cure"), R("60-days", "§50(a)(6)(Q)(x)", "data_range", "days_after_notice", "within 60 days of the notice", { range: { max: 60 } }), R("attorney-review", "4.5 outputs", "data_equality", "attorney_reviewed", "attorney review", { predicate: { "==": [{ var: "attorney_reviewed" }, true] } }), ...ADDR_RULES];

const items = [{ n: 1, text: "who owns my loan", response_due: "2026-09-21", answer: "Fannie Mae", basis: "irrelevant" }, { n: 2, text: "a complete payment history since 2019", response_due: "2026-10-20", answer: "enclosed", basis: "overbroad" }];
export const SECTION_04_VERSIONS: readonly VersionInput[] = [
  V("NTC_REGX_35C_ADDRESS", ADDRESS_SOURCE, ADDRESS_RULES, { ...BASE, website: "www.supermortgage.example/contact" }, "regx.servicing.2014", "§1024.35(c)"),
  V("NTC_REGX_35C_ADDRESS_CHANGE", ADDRESS_CHANGE_SOURCE, ADDRESS_CHANGE_RULES, { ...BASE, effective_from: "2027-01-01", new_address: "PO Box 9, Testville TX 75001", days_before_effective: 45 }, "regx.servicing.2014", "§1024.35(c)"),
  V("NTC_REGX_35D_ACK", ACK_SOURCE, ACK_RULES, { ...BASE, received_on: "2026-09-04", business_days_after_receipt: 3, assertions: [{ n: 1, text: "the late fee assessed on March 17 was not owed", response_due: "2026-10-20" }, { n: 2, text: "your payoff statement was wrong", response_due: "2026-09-16" }] }, "regx.servicing.2014", "4.1 worked example"),
  V("NTC_REGX_35E_CORRECTION", RESPONSE_BODY, RESPONSE_RULES("correction"), RESPONSE_SAMPLE("correction"), "regx.servicing.2014", "4.1 rule 7"),
  V("NTC_REGX_35E_NO_ERROR", RESPONSE_BODY, RESPONSE_RULES("no_error"), RESPONSE_SAMPLE("no_error"), "regx.servicing.2014", "4.1 rule 7"),
  V("NTC_REGX_35E_ADDITIONAL_ERRORS", RESPONSE_BODY, RESPONSE_RULES("additional"), RESPONSE_SAMPLE("additional"), "regx.servicing.2014", "§1024.35(e)(1)(ii)"),
  V("NTC_REGX_35E_EXTENSION", EXTENSION_SOURCE, EXTENSION_RULES, { ...BASE, received_on: "2026-09-04", reason: "records from the prior servicer are being retrieved", new_due: "2026-11-10", business_days_after_receipt: 28 }, "regx.servicing.2014", "§1024.35(e)(3)(ii)"),
  V("NTC_REGX_35E4_DOCS", DOCS_SOURCE, DOCS_RULES, { ...BASE, requested_on: "2026-09-04", documents: ["payment history 2026-03", "fee schedule v3"], business_days_after_request: 10 }, "regx.servicing.2014", "§1024.35(e)(4)"),
  V("NTC_REGX_35E4_WITHHELD", WITHHELD_SOURCE, WITHHELD_RULES, { ...BASE, requested_on: "2026-09-04", withheld: ["internal legal memorandum dated 2026-09-10"], business_days_after_request: 10 }, "regx.servicing.2014", "§1024.35(e)(4)"),
  V("NTC_REGX_35F1_EARLY_CORRECTION", EARLY_CORRECTION_SOURCE, EARLY_CORRECTION_RULES, { ...BASE, received_on: "2026-09-04", correction: "we re-applied your March payment as of March 1 and reversed the late fee", effective_on: "2026-03-01", business_days_after_receipt: 3 }, "regx.servicing.2014", "§1024.35(f)(1)"),
  V("NTC_REGX_35G2_EXCEPTION", EXCEPTION_SOURCE, EXCEPTION_RULES, { ...BASE, received_on: "2026-09-04", basis: "overbroad", explanation: "the 40-page letter does not identify any other specific error", carved_out: "the late-fee assertion (answered separately)", business_days_after_determination: 2 }, "regx.servicing.2014", "§1024.35(g)(2)"),
  V("NTC_REGX_38B5_PROCEDURES", PROCEDURES_SOURCE, PROCEDURES_RULES, { ...BASE }, "regx.servicing.2014", "§1024.38(b)(5)"),
  V("NTC_REGX_36C_ACK", RFI_ACK_SOURCE, RFI_ACK_RULES, { ...BASE, received_on: "2026-09-04", business_days_after_receipt: 3, items }, "regx.servicing.2014", "4.2 worked example"),
  V("NTC_REGX_36D_RESPONSE", RFI_RESPONSE_SOURCE, RFI_RESPONSE_RULES, { ...BASE, received_on: "2026-09-04", items, attachments: ["payment history 2019-2026"], redaction_check_passed: true }, "regx.servicing.2014", "§1024.36(d)"),
  V("NTC_REGX_36D_NOT_AVAILABLE", NOT_AVAILABLE_SOURCE, NOT_AVAILABLE_RULES, { ...BASE, items: [{ n: 1, text: "a recording of a 2019 call", basis: "retention period: recordings are kept 5 years" }], search_log_complete: true }, "regx.servicing.2014", "§1024.36(d)(1)(ii)"),
  V("NTC_REGX_36D_EXTENSION", RFI_EXTENSION_SOURCE, RFI_EXTENSION_RULES, { ...BASE, received_on: "2026-09-04", reason: "document custodian retrieval", new_due: "2026-11-10", business_days_after_receipt: 28 }, "regx.servicing.2014", "§1024.36(d)(2)(ii)"),
  V("NTC_REGX_36E_EARLY", RFI_EARLY_SOURCE, RFI_EARLY_RULES, { ...BASE, received_on: "2026-09-04", items: [{ n: 1, text: "a copy of your last escrow statement" }], business_days_after_receipt: 3 }, "regx.servicing.2014", "§1024.36(e)"),
  V("NTC_REGX_36F2_EXCEPTION", RFI_EXCEPTION_SOURCE, RFI_EXCEPTION_RULES, { ...BASE, received_on: "2026-09-04", items: [{ n: 1, text: "your legal analysis of my foreclosure", basis: "privileged" }], provided: "the foreclosure milestone dates", business_days_after_determination: 2 }, "regx.servicing.2014", "§1024.36(f)(2)"),
  V("NTC_REGX_36A2_OWNER_IDENTITY", OWNER_SOURCE, OWNER_RULES, { ...BASE, owner_block: "Fannie Mae", as_of: "2026-09-10", owner_address: "1100 15th Street NW, Washington DC 20005", owner_phone: "(800) 232-6643", servicer_address: "PO Box 1, Testville TX 75001", ny: false, business_days_after_receipt: 6 }, "regx.servicing.2014", "comment 36(a)-2; A4-1-03"),
  V("NTC_REGX_36I_SII_DOCS", SII_DOCS_SOURCE, SII_DOCS_RULES, { ...BASE, deceased_or_transferor: "your mother", documents: ["death certificate", "recorded deed showing your mother as owner", "letters testamentary", "the will"], questions: ["How did the deceased hold title?"], business_days_after_receipt: 4 }, "regx.servicing.2014", "§1024.36(i)"),
  V("NTC_REGX_40_CONTACT_ASSIGNED", CONTACT_ASSIGNED_SOURCE, CONTACT_ASSIGNED_RULES, { ...BASE, team_name: "Home Retention Team 4", named_human_first_name: "Dana", title: "Senior Loan Counselor", direct_number: "(800) 555-0199", hours: "8 a.m.–8 p.m. Central, Monday–Friday" }, "regx.continuity.2014", "§1024.40(a)"),
  V("NTC_CA_2923_7_SPOC", CA_SPOC_SOURCE, CA_SPOC_RULES, { ...BASE, spoc_name: "Home Retention Team 4", spoc_kind: "human team", direct_number: "(800) 555-0199", direct_email: "team4@example.com" }, "state.ca.hbor", "Cal. Civ. Code §2923.7"),
  V("NTC_REGX_38B1VI_SII_DOCS", SII_DOCS_SOURCE, SII_DOCS_RULES, { ...BASE, deceased_or_transferor: "your mother", documents: ["death certificate", "recorded deed", "letters testamentary", "the will"], questions: [], business_days_after_receipt: 4 }, "regx.servicing.2014", "§1024.38(b)(1)(vi)(B)"),
  V("NTC_REGX_38B1VI_SII_ADDL_DOCS", SII_ADDL_SOURCE, SII_ADDL_RULES, { ...BASE, received_on: "2026-10-20", still_required: [{ this: "letters testamentary", why: "the will alone does not vest title before probate in Texas" }], business_days_after_receipt: 3 }, "regx.servicing.2014", "§1024.38(b)(1)(vi)(C)"),
  V("NTC_REGX_38B1VI_SII_CONFIRMED", SII_CONFIRMED_SOURCE, SII_CONFIRMED_RULES, { ...BASE, property_address: "1 Test St, Testville TX 75001", confirmed_on: "2026-11-03", delinquent: true, team_name: "Home Retention Team 4", direct_number: "(800) 555-0199" }, "regx.servicing.2014", "4.4 worked timeline"),
  V("NTC_REGX_38B1VI_SII_NOT_SUCCESSOR", SII_NOT_SOURCE, SII_NOT_RULES, { ...BASE, reason: "the transfer was an arm's-length sale to an unrelated buyer, which is not one of the five transfer types in §1024.31", what_would_change: "a transfer within one of the five types with evidence of an ownership interest", officer_signoff: true }, "regx.servicing.2014", "4.4 rule 4"),
  V("NTC_REGX_32C_SII_ACK", SII_ACK_SOURCE, SII_ACK_RULES, { ...BASE, successor_name: "Dee Daughter" }, "regx.servicing.2014", "§1024.32(c)(1)"),
  V("NTC_FNMA_D1_4_1_02_ASSUMPTION_OFFER", ASSUMPTION_SOURCE, ASSUMPTION_RULES, { ...BASE, transfer_type: "death of a relative", how_to_proceed: "sign and return the enclosed assumption agreement" }, "fnma.guide.2026-08-12", "D1-4.1-02"),
  V("NTC_COMPLAINT_ACK", COMPLAINT_ACK_SOURCE, COMPLAINT_ACK_RULES, { ...BASE, received_on: "2026-09-10", response_by: "2026-09-25", ny: true, business_days_after_receipt: 1 }, "sm.complaints.policy", "4.5 worked dates"),
  V("NTC_COMPLAINT_RESPONSE", COMPLAINT_RESPONSE_SOURCE, COMPLAINT_RESPONSE_RULES, { ...BASE, received_on: "2026-09-10", found: "a $15.00 pay-by-phone fee was assessed on June 15 without the disclosed fee schedule for that channel", fixed: "we reversed the fee on September 12 as of June 15", next_steps: "you may send a notice of error or request for information at any time", ny: false }, "sm.complaints.policy", "4.5 rule 3"),
  V("NTC_REMEDIATION_REFUND", REMEDIATION_SOURCE, REMEDIATION_RULES, { ...BASE, fee_description: "pay-by-phone convenience fee", amount_cents: 1_500n, assessed_on: "2026-06-15", refund_by_check: true }, "sm.complaints.policy", "4.5 rule 3 population test"),
  V("NTC_TX_50A6_CURE", TX_CURE_SOURCE, TX_CURE_RULES, { ...BASE, notice_on: "2026-09-10", cure: "refunding the fee that exceeded the 2% cap with interest", cure_by: "2026-11-09", days_after_notice: 30, attorney_reviewed: true }, "state.tx.50a6", "Tex. Const. art. XVI §50(a)(6)(Q)(x)"),
];
