/**
 * §19.2 authored notice versions (V(code, source, rules, sample, ruleSet, formBasis) from ./section01.ts;
 * see ./section13.ts) and per-code channel/combination overrides. Spread by ./section19.ts.
 *
 * All nine are non-borrower notices: the Fannie Mae Supplement 36-hour incident e-mail and the
 * Form 101 notice, the partner's 24-hour contractual notice, the NYDFS 500.17(a) portal payload and
 * 500.17(c) extortion-payment notice, the FTC 314.4(j) six-element form, the NY GBL §899-aa(8)(b)
 * CRA notice, the officer's Supplement attestation for Form 582 and the NYDFS April 15 submission.
 * Every checklist carries the clock the spec names (36 h / 24 h / 72 h / 30 days / April 15) and
 * the officer-signature rule (regulatory and partner notices are `officer` acts).
 */
import type { ContentRule, NoticeTemplate, VersionInput } from "../registry.ts";
import { V } from "./section01.ts";

const R = (rule_id: string, citation: string, kind: ContentRule["kind"], selector: string, message: string, extra: Partial<ContentRule> = {}): ContentRule => ({ rule_id, citation, kind, selector, severity: "block", message, ...extra });
const DATE_RULE = R("date", "notice date", "presence", "(January|February|March|April|May|June|July|August|September|October|November|December) \\d{1,2}, \\d{4}", "date of the notice");
const OFFICER_RULE = (cite: string) => R("officer-sent", cite, "data_equality", "sent_by_role", "sent/signed by an officer", { predicate: { "==": [{ var: "sent_by_role" }, "officer"] } });
const NO_SSN = R("no-full-ssn", "19.2 guardrails: full SSNs never leave the system (tokenized)", "absence", "\\b\\d{3}-\\d{2}-\\d{4}\\b", "no full SSN");
const HOURS_RULE = (id: string, cite: string, field: string, max: number) => R(id, cite, "data_range", field, `sent within ${max} hours`, { range: { min: 0, max } });
/** A required content element: the payload field must be present (a label in the template prose proves nothing — the value does). */
const P = (id: string, cite: string, field: string, message: string) => R(id, cite, "data_equality", field, message, { predicate: { present: field } });
const LIST = (id: string, cite: string, field: string, message: string) => R(id, cite, "data_equality", field, message, { predicate: { ">": [{ var: `${field}.length` }, 0] } });
const BASE = { notice_date: "2026-10-17", servicer_name: "Supermortgage", seller_servicer_no: "SS-000000", partner_name: "Partner Bank, N.A.", incident_id: "INC-2026-0042", sent_by_name: "J. Officer", sent_by_title: "Chief Compliance Officer", sent_by_role: "officer", contact: "security@supermortgage.example, (800) 555-0142" };
const HEAD = (title: string) => `{{#block "heading" page=1 y=0.05 pt=14 bold}}${title}{{/block}}`;
const SIGN = (extra = "") => `{{#block "signature" page=1 y=0.85 pt=11}}Sent by {{sent_by_name}}, {{sent_by_title}} (officer), {{servicer_name}}, {{date notice_date}}. Contact: {{contact}}.${extra}{{/block}}`;

// ------------------------------------------------------------------ Fannie Mae Supplement 36-hour incident notice
const FNMA_36H = `${HEAD("Cybersecurity Incident notice under the Fannie Mae Information Security and Business Resiliency Supplement")}
{{#block "clock" page=1 y=0.1 pt=11}}To: {{fnma_mailbox}} (cc {{account_team_email}}). From: {{servicer_name}}, Seller/Servicer No. {{seller_servicer_no}}, subservicer for {{partner_name}}. Incident {{incident_id}} was identified, or reasonably concluded to have possibly occurred, on {{identified_at_et}}. This notice is sent {{hours_since_identification}} hours after identification — without undue delay and no later than 36 hours.{{/block}}
{{#block "content" page=1 y=0.2 pt=11}}1. Status of investigations: {{investigation_status}}. 2. Indicators of compromise: {{#each iocs}}{{this}}; {{/each}} 3. Tactics, techniques and procedures observed: {{ttps}}. 4. Fannie Mae systems affected: {{fnma_systems_affected}}. Fannie Mae Confidential Information affected: {{fnma_confidential_affected}}. 5. Incident response provider: {{ir_provider_contact}}. Law enforcement contact: {{law_enforcement_contact}}. 6. Investigation lead: {{investigation_lead}}. 7. Extent of exposure: {{extent_of_exposure}}. Category: {{category}}{{#if bec}} (business-email compromise — reportable regardless of impact){{/if}}.{{/block}}
${SIGN(" Updates will follow promptly thereafter as requested.")}`;
const FNMA_36H_RULES = [DATE_RULE, HOURS_RULE("36h", "Fannie Mae Supplement: 'no later than 36 hours after identification'", "hours_since_identification", 36),
  R("mailbox", "Fannie Mae Supplement: notice by email to privacy_office@fanniemae.com (confirm spelling at onboarding)", "data_equality", "fnma_mailbox", "Fannie Mae incident mailbox", { predicate: { matches: ["fnma_mailbox", "^privacy[-_]office@fanniemae\\.com$"] } }),
  P("identified", "Supplement: identification or reasonable conclusion", "identified_at_et", "identification time"), P("investigations", "Supplement content list: status of investigations", "investigation_status", "investigation status"), LIST("iocs", "Supplement content list: indicators of compromise", "iocs", "IOCs"), P("ttps", "Supplement content list: tactics, techniques and procedures", "ttps", "TTPs"),
  P("fnma-systems", "Supplement content list: whether Fannie Mae systems were affected", "fnma_systems_affected", "Fannie Mae systems"), P("fnma-ci", "Supplement content list: whether Confidential Information was affected", "fnma_confidential_affected", "Confidential Information"), P("ir-provider", "Supplement content list: IR provider contact", "ir_provider_contact", "IR provider"), P("law-enforcement", "Supplement content list: law-enforcement contact", "law_enforcement_contact", "law enforcement contact"),
  P("lead", "Supplement content list: investigation lead", "investigation_lead", "investigation lead"), P("exposure", "Supplement content list: extent of exposure", "extent_of_exposure", "extent of exposure"), R("updates", "Supplement: 'promptly thereafter as requested'", "presence", "Updates will follow promptly thereafter", "follow-up commitment"), OFFICER_RULE("19.2 escalations: every Fannie Mae notice is sent by an officer"), NO_SSN];
const FNMA_36H_SAMPLE = { ...BASE, fnma_mailbox: "privacy_office@fanniemae.com", account_team_email: "account.team@fanniemae.com", identified_at_et: "Friday, October 16, 2026 at 14:30 ET", hours_since_identification: 18.5, investigation_status: "forensic firm engaged 2026-10-16 17:00 ET; vendor SFTP credential revoked; log review in progress", iocs: ["203.0.113.7 (SFTP source)", "user-agent WinSCP/6.3 outside job window"], ttps: "valid-account abuse (T1078) against the print/mail vendor SFTP; bulk download of statement files", fnma_systems_affected: "none", fnma_confidential_affected: "yes — borrower statement files for 12,400 loans held on the vendor side unencrypted at rest", ir_provider_contact: "Forensic Partners LLC, (800) 555-0177", law_enforcement_contact: "FBI IC3 report 2026-10-16; case agent TBD", investigation_lead: "A. Lead, CISO", extent_of_exposure: "12,400 borrowers; 3,100 NY and 2,000 TX residents; scoping continuing", category: "credential_compromise", bec: false };

// ------------------------------------------------------------------ Form 101 notice (Subordinate Subscriber)
const FORM101 = `${HEAD("Form 101 Data Access Authorization Agreement — notice of loss or unauthorized access to or use of the Data")}
{{#block "body" page=1 y=0.12 pt=11}}To Fannie Mae ({{fnma_recipient}}) and to {{master_subscriber_name}} as Master Subscriber ({{master_subscriber_recipient}}). {{servicer_name}}, as Subordinate Subscriber, hereby notifies Fannie Mae and Master Subscriber in writing of {{incident_kind}} involving the Data accessed under {{#each applications}}{{this}}; {{/each}} Subordinate Subscriber became aware of the incident on {{aware_at_et}}; this notice is sent {{hours_since_aware}} hours after becoming aware — without undue delay and no later than 36 hours. Data affected: {{data_affected}}. Containment: {{containment}}. Incident reference: {{incident_id}}.{{/block}}
${SIGN()}`;
const FORM101_RULES = [DATE_RULE, HOURS_RULE("36h", "Form 101 (12/9/2025): 'no later than 36 hours after Subordinate Subscriber becomes aware of the incident'", "hours_since_aware", 36),
  R("both-recipients", "Form 101: 'notify Fannie Mae and Master Subscriber in writing'", "data_equality", "master_subscriber_recipient", "Fannie Mae and the Master Subscriber both addressed", { predicate: { and: [{ present: "fnma_recipient" }, { present: "master_subscriber_recipient" }, { present: "master_subscriber_name" }] } }),
  R("in-writing", "Form 101", "presence", "notifies Fannie Mae and Master Subscriber in writing", "written notice to both"), R("subordinate", "Form 101", "presence", "as Subordinate Subscriber", "capacity stated"), P("kind", "Form 101: loss or unauthorized access to or use of the Data", "incident_kind", "nature of the incident"), LIST("applications", "Form 101: the Data accessed under the authorized applications", "applications", "applications named"), P("aware", "Form 101: when Subordinate Subscriber became aware", "aware_at_et", "awareness time"), P("data", "Form 101: the Data affected", "data_affected", "data affected"), P("containment", "19.2 outputs", "containment", "containment"), OFFICER_RULE("19.2 escalations"), NO_SSN];
const FORM101_SAMPLE = { ...BASE, fnma_recipient: "Technology_Registration@fanniemae.com", master_subscriber_name: "Partner Bank, N.A.", master_subscriber_recipient: "vendor.risk@partnerbank.example", incident_kind: "unauthorized access to and download of", applications: ["Servicing Management Default Underwriter (SMDU)", "Loan Servicing Data Utility (LSDU)"], aware_at_et: "Friday, October 16, 2026 at 14:30 ET", hours_since_aware: 18.5, data_affected: "loan-level servicing data for 12,400 loans exported to the print/mail vendor", containment: "vendor SFTP credential revoked; egress blocked; forensic image taken" };

// ------------------------------------------------------------------ Partner 24-hour contractual notice
const PARTNER_24H = `${HEAD("Security incident notice to {{partner_name}} under the Subservicing Agreement")}
{{#block "body" page=1 y=0.12 pt=11}}Under §{{contract_section}} of the Subservicing Agreement (24-hour incident notice), {{servicer_name}} notifies {{partner_name}} of incident {{incident_id}}, identified on {{identified_at_et}}; this notice is sent {{hours_since_identification}} hours after identification. Summary: {{summary}}. Partner data affected: {{partner_data_affected}}. Loans potentially affected: {{loans_affected_count}}. Containment actions taken: {{containment}}. Fannie Mae notice: {{fnma_notice_status}}. Incident bridge: {{bridge}}. Next update by {{next_update_at}}.{{/block}}
${SIGN()}`;
const PARTNER_24H_RULES = [DATE_RULE, HOURS_RULE("24h", "19.2 timer table SM_PARTNER_INCIDENT_NOTICE_24H (+24 hours, contract default)", "hours_since_identification", 24), P("identified", "19.2 rule 1: identified_at", "identified_at_et", "identification time"), P("summary", "19.2 outputs: partner notice content", "summary", "summary"), P("partner-data", "19.2 outputs: partner data affected", "partner_data_affected", "partner data affected"), R("loans", "19.2 outputs: loans potentially affected", "data_range", "loans_affected_count", "loan count", { range: { min: 0 } }), P("containment", "19.2 outputs: partner notice content", "containment", "containment"), P("fnma-coord", "19.2 edge cases: coordination on the Fannie Mae notice", "fnma_notice_status", "Fannie Mae notice status"), P("bridge", "19.2 integrations: partner notice by email + phone bridge", "bridge", "bridge"), P("next-update", "19.2 integrations: shared incident channel", "next_update_at", "next update"), OFFICER_RULE("19.2 escalations: every partner notice is sent by an officer"), NO_SSN];
const PARTNER_24H_SAMPLE = { ...BASE, contract_section: "12.4", identified_at_et: "Friday, October 16, 2026 at 14:30 ET", hours_since_identification: 18.5, summary: "a print/mail vendor SFTP credential was used by an unknown party to download statement files", partner_data_affected: "yes — borrower statement files", loans_affected_count: 12400, containment: "credential revoked, egress blocked, forensic firm engaged", fnma_notice_status: "Supplement and Form 101 notices drafted; officer sending Saturday 09:00 ET (due Sunday 02:30 ET)", bridge: "+1 (800) 555-0199 PIN 4242 / shared channel #inc-2026-0042", next_update_at: "Saturday, October 17, 2026 18:00 ET" };

// ------------------------------------------------------------------ NYDFS 500.17(a) portal payload
const NYDFS_17A = `${HEAD("23 NYCRR 500.17(a) cybersecurity incident notice — DFS portal submission")}
{{#block "body" page=1 y=0.12 pt=11}}Covered entity: {{entity_name}}, New York Mortgage Loan Servicer registration {{ny_registration_no}}. Determination that a cybersecurity incident has occurred: {{determined_at_et}}. Submitted electronically in the form set forth on the department's website {{hours_since_determination}} hours after determination — as promptly as possible and in no event later than 72 hours. Basis: {{#if prong_notice_required}}(1) notice is required to a government body, self-regulatory agency or other supervisory body: {{prong1_bodies}}; {{/if}}{{#if prong_material_harm}}(2) a reasonable likelihood of materially harming a material part of normal operations; {{/if}}{{#if prong_ransomware}}(3) ransomware deployed within a material part of the information systems; {{/if}}Incident date: {{date incident_on}}. Location: {{location}}. Description: {{description}}. Information systems affected: {{systems_affected}}. Extortion payment: {{extortion_payment}}. Law enforcement notified: {{law_enforcement}}. The covered entity will promptly update the superintendent as material information becomes available.{{/block}}
${SIGN()}`;
const NYDFS_17A_RULES = [DATE_RULE, HOURS_RULE("72h", "23 NYCRR 500.17(a): 'in no event later than 72 hours after determining that a cybersecurity incident has occurred'", "hours_since_determination", 72),
  R("prong", "23 NYCRR 500.1 'cybersecurity incident' prongs (1)–(3)", "data_equality", "prong_notice_required", "at least one prong met", { predicate: { or: [{ "==": [{ var: "prong_notice_required" }, true] }, { "==": [{ var: "prong_material_harm" }, true] }, { "==": [{ var: "prong_ransomware" }, true] }] } }),
  R("prong1-bodies", "23 NYCRR 500.1(1): the government body, self-regulatory agency or supervisory body notice is required to", "conditional", "prong1_bodies", "bodies named when prong (1) is the basis", { when: { "==": [{ var: "prong_notice_required" }, true] }, predicate: { present: "prong1_bodies" } }),
  R("portal", "23 NYCRR 500.17(a): electronic form on the department's website", "presence", "in the form set forth on the department's website", "portal form"), P("determined", "23 NYCRR 500.17(a): determination time", "determined_at_et", "determination time"), P("incident-date", "23 NYCRR 500.17(a) form: incident date", "incident_on", "incident date"), P("location", "23 NYCRR 500.17(a): at the entity, an affiliate or a third-party service provider", "location", "where the incident occurred"), P("description", "23 NYCRR 500.17(a) form: description", "description", "description"), P("systems", "23 NYCRR 500.17(a) form: information systems affected", "systems_affected", "systems affected"), P("extortion", "23 NYCRR 500.17(c): extortion payment status", "extortion_payment", "extortion payment"), P("law-enforcement", "23 NYCRR 500.17(a) form: law enforcement", "law_enforcement", "law enforcement"),
  R("update", "23 NYCRR 500.17(a): continuing duty to update", "presence", "update the superintendent", "continuing update"), P("registration", "500.1 covered entity (Banking Law registration)", "ny_registration_no", "registration cited"), OFFICER_RULE("19.2 escalations: portal submissions are officer tasks"), NO_SSN];
const NYDFS_17A_SAMPLE = { ...BASE, notice_date: "2026-10-20", entity_name: "Supermortgage", ny_registration_no: "MLS-000000", determined_at_et: "Monday, October 19, 2026 at 10:00 ET", hours_since_determination: 26, prong_notice_required: true, prong1_bodies: "FTC (16 CFR 314.4(j)) and New York Attorney General (GBL §899-aa)", prong_material_harm: false, prong_ransomware: false, incident_on: "2026-10-16", location: "third-party service provider (print/mail vendor SFTP)", description: "unauthorized download of statement files for 12,400 borrowers, 3,100 New York residents", systems_affected: "vendor SFTP; no Supermortgage production systems", extortion_payment: "none", law_enforcement: "FBI IC3 report filed 2026-10-16" };

// ------------------------------------------------------------------ NYDFS 500.17(c) extortion payment notice (24 h)
const NYDFS_17C = `${HEAD("23 NYCRR 500.17(c) notice of extortion payment")}
{{#block "body" page=1 y=0.12 pt=11}}{{entity_name}} made an extortion payment in connection with cybersecurity incident {{incident_id}} on {{paid_at_et}} in the amount of {{money amount_cents}} ({{asset}}) to {{recipient_descriptor}}. This notice is submitted electronically {{hours_since_payment}} hours after the payment — within 24 hours. The payment was authorized by {{authorized_by}}; no automated agent paid or negotiated. A written description of the reasons payment was necessary, a description of alternatives to payment considered, all diligence performed to find alternatives to payment, and all diligence performed to ensure compliance with applicable rules and regulations including those of the Office of Foreign Assets Control (OFAC) will be provided within 30 days of the payment, by {{date explanation_due}}.{{/block}}
${SIGN()}`;
const NYDFS_17C_RULES = [DATE_RULE, HOURS_RULE("24h", "23 NYCRR 500.17(c)(1): notice within 24 hours of the extortion payment", "hours_since_payment", 24), R("amount", "23 NYCRR 500.17(c)", "presence", "in the amount of \\$[\\d,]+\\.\\d{2}", "payment amount"), P("paid-at", "23 NYCRR 500.17(c)(1): the payment", "paid_at_et", "payment time"), P("recipient", "23 NYCRR 500.17(c)(1)", "recipient_descriptor", "payee"), P("authorized", "19.2 escalations: extortion is a human decision", "authorized_by", "authorizer"), R("explanation-30d", "23 NYCRR 500.17(c)(2): written explanation within 30 days", "presence", "within 30 days of the payment", "30-day explanation commitment"), P("explanation-due", "23 NYCRR 500.17(c)(2)", "explanation_due", "explanation due date"), R("ofac", "23 NYCRR 500.17(c)(2): OFAC diligence", "presence", "OFAC", "OFAC diligence"),
  R("no-agent-payment", "19.2 escalations: the agent may not pay or negotiate extortion", "data_equality", "paid_by_agent", "human-authorized payment", { predicate: { "==": [{ var: "paid_by_agent" }, false] } }), OFFICER_RULE("19.2 escalations"), NO_SSN];
const NYDFS_17C_SAMPLE = { ...BASE, notice_date: "2026-10-21", entity_name: "Supermortgage", paid_at_et: "Tuesday, October 20, 2026 at 16:00 ET", amount_cents: 25_000_000n, asset: "BTC equivalent", recipient_descriptor: "threat actor wallet per forensic report FP-2026-0042", hours_since_payment: 6, authorized_by: "Chief Executive Officer with counsel and cyber insurer", paid_by_agent: false, explanation_due: "2026-11-19" };

// ------------------------------------------------------------------ FTC 314.4(j) notification (six elements)
const FTC_314_4J = `${HEAD("Notification of a notification event under 16 CFR 314.4(j) — FTC Safeguards Rule electronic form")}
{{#block "body" page=1 y=0.12 pt=11}}(1) Name and contact information of the reporting financial institution: {{institution_name}}, {{institution_contact}}. (2) Description of the types of information involved in the notification event: {{information_types}}. (3) Date or date range of the notification event: {{date_range}}. (4) Number of consumers affected or potentially affected: {{consumer_count}}. (5) General description of the notification event: {{description}}. (6) Law enforcement: {{#if law_enforcement_delay}}a law enforcement official has provided a written determination that notifying the public would impede a criminal investigation ({{law_enforcement_contact}}); public disclosure is delayed accordingly.{{else}}no law enforcement official has provided a written determination that notifying the public would impede a criminal investigation.{{/if}} The notification event was discovered on {{date discovered_on}} (the first day it was known); this notification is submitted on {{date submitted_on}}, {{days_since_discovery}} days after discovery — as soon as possible and no later than 30 days.{{/block}}
${SIGN()}`;
const FTC_RULES = [DATE_RULE, R("500", "16 CFR 314.4(j)(1): information of at least 500 consumers", "data_range", "consumer_count", "≥ 500 consumers", { range: { min: 500 } }), R("30d", "16 CFR 314.4(j)(1): no later than 30 days after discovery", "data_range", "days_since_discovery", "within 30 days of discovery", { range: { min: 0, max: 30 } }),
  R("e1", "16 CFR 314.4(j)(2)(i): name and contact information of the reporting financial institution", "data_equality", "institution_contact", "element 1", { predicate: { and: [{ present: "institution_name" }, { present: "institution_contact" }] } }), P("e2", "16 CFR 314.4(j)(2)(ii): description of the types of information involved", "information_types", "element 2"), P("e3", "16 CFR 314.4(j)(2)(iii): date or date range of the notification event", "date_range", "element 3"), P("e4", "16 CFR 314.4(j)(2)(iv): number of consumers affected or potentially affected", "consumer_count", "element 4"), P("e5", "16 CFR 314.4(j)(2)(v): general description of the notification event", "description", "element 5"),
  R("e6", "16 CFR 314.4(j)(2)(vi): whether a law enforcement official has provided a written determination that notifying the public would impede a criminal investigation", "conditional", "law_enforcement_contact", "element 6 — the official's contact when a delay is claimed", { when: { "==": [{ var: "law_enforcement_delay" }, true] }, predicate: { present: "law_enforcement_contact" } }), R("e6-stated", "16 CFR 314.4(j)(2)(vi)", "presence", "\\(6\\) Law enforcement", "element 6 stated either way"),
  R("discovery", "16 CFR 314.4(j)(1): 'treated as discovered as of the first day on which such event is known'", "data_equality", "discovered_on", "discovery basis", { predicate: { and: [{ present: "discovered_on" }, { present: "submitted_on" }] } }), OFFICER_RULE("19.2 escalations: FTC form is an officer task"), NO_SSN];
const FTC_SAMPLE = { ...BASE, notice_date: "2026-11-13", institution_name: "Supermortgage", institution_contact: "A. Lead, CISO, security@supermortgage.example, (800) 555-0142", information_types: "names, mailing addresses, loan numbers and payment amounts in periodic statements", date_range: "October 14–16, 2026", consumer_count: 12400, description: "a print/mail vendor SFTP credential was used by an unauthorized party to download statement files held unencrypted at rest on the vendor side; acquisition presumed", law_enforcement_delay: false, law_enforcement_contact: "", discovered_on: "2026-10-16", submitted_on: "2026-11-13", days_since_discovery: 28 };

// ------------------------------------------------------------------ NY GBL §899-aa(8)(b) consumer reporting agency notice
const BREACH_CRA = `${HEAD("Notice to consumer reporting agencies under N.Y. Gen. Bus. Law §899-aa(8)(b)")}
{{#block "body" page=1 y=0.12 pt=11}}{{servicer_name}} is notifying more than five thousand New York residents at one time of a breach of the security of the system (incident {{incident_id}}). Approximate number of New York residents notified: {{ny_residents}}. Timing: consumer notices mailed on {{date mailed_on}}. Content: {{content_summary}}. Distribution: {{distribution}}. Addressed to Equifax, Experian and TransUnion at the addresses in the bureau contact registry. This is a notice, not a Metro 2 submission.{{/block}}
${SIGN()}`;
const BREACH_CRA_RULES = [DATE_RULE, R("5000", "N.Y. Gen. Bus. Law §899-aa(8)(b): more than five thousand New York residents", "data_range", "ny_residents", "> 5,000 NY residents", { range: { min: 5001 } }), R("threshold-text", "§899-aa(8)(b)", "presence", "more than five thousand New York residents", "threshold statement"), P("timing", "§899-aa(8)(b): timing of the notices", "mailed_on", "timing"), P("content", "§899-aa(8)(b): content of the notices", "content_summary", "content"), P("distribution", "§899-aa(8)(b): distribution of the notices", "distribution", "distribution"), R("bureaus", "19.2 integrations: CRAs via the Section 8 bureau contacts", "presence", "Equifax, Experian and TransUnion", "three bureaus"), OFFICER_RULE("19.2 escalations"), NO_SSN];
const BREACH_CRA_SAMPLE = { ...BASE, notice_date: "2026-11-13", ny_residents: 5001, mailed_on: "2026-11-13", content_summary: "what happened, information involved, steps taken, contact points, and NY Attorney General, Department of State and FTC contacts", distribution: "first-class mail to last known mailing address; substitute notice for returned mail per §899-aa(5)" };

// ------------------------------------------------------------------ Supplement attestation (officer letter for Form 582)
const ATTESTATION = `${HEAD("Annual attestation under the Fannie Mae Information Security and Business Resiliency Supplement — for {{partner_name}}'s Form 582")}
{{#block "body" page=1 y=0.12 pt=11}}I, {{sent_by_name}}, {{sent_by_title}}, a duly authorized corporate officer of {{servicer_name}}, attest that the Information Security Program and the Business Resiliency Program of {{servicer_name}} meet the requirements of the Fannie Mae Information Security and Business Resiliency Supplement for the period {{period}}. Basis: independent security assessment of the control environment by {{assessor}} completed {{date assessment_completed_on}} ({{days_since_assessment}} days ago); independent third-party penetration test completed {{date pen_test_completed_on}} ({{days_since_pen_test}} days ago); annual access certification, BCP exercise and security-awareness training completed for the period. {{#if exceptions_open}}Open control exceptions approved by the Qualified Individual: {{exceptions_summary}}.{{else}}No control test failed without an approved exception as of {{date as_of}}.{{/if}} Delivered to {{partner_name}} on {{date notice_date}}, {{days_before_form582_due}} days before the Form 582 due date of {{date form_582_due}}.{{/block}}
${SIGN()}`;
const ATTESTATION_RULES = [DATE_RULE, R("attest", "Fannie Mae Supplement: 'written attestation executed by a duly authorized corporate officer that the Information Security Program … meet[s] the requirements of this Supplement'", "presence", "duly authorized corporate officer of .* attest that the Information Security Program and the Business Resiliency Program of .* meet the requirements of the Fannie Mae Information Security and Business Resiliency Supplement", "attestation sentence"),
  P("period", "Supplement: annual attestation period", "period", "period"), P("assessor", "Supplement: qualified independent auditor", "assessor", "assessor named"), P("assessment-date", "Supplement: independent security assessment", "assessment_completed_on", "assessment date"), P("pentest-date", "Supplement: independent third-party penetration test", "pen_test_completed_on", "pen test date"),
  R("assessment-365", "Supplement: independent security assessment at least annually", "data_range", "days_since_assessment", "assessment within 365 days", { range: { min: 0, max: 365 } }), R("pentest-365", "Supplement: independent third-party penetration test at least annually", "data_range", "days_since_pen_test", "pen test within 365 days", { range: { min: 0, max: 365 } }),
  R("exceptions", "19.2 rule 11: open exceptions approved by the Qualified Individual are disclosed", "conditional", "exceptions_summary", "exceptions summarised when any is open", { when: { "==": [{ var: "exceptions_open" }, true] }, predicate: { present: "exceptions_summary" } }), P("form582", "18.4 Form 582 due date", "form_582_due", "Form 582 due date"),
  R("form582-30d", "19.2 timer table FNMA_SUPP_ATTESTATION_ANNUAL: partner's Form 582 due date − 30 days", "data_range", "days_before_form582_due", "delivered ≥ 30 days before Form 582 is due", { range: { min: 30 } }), OFFICER_RULE("19.2 escalations: attestations are signed by an officer"), NO_SSN];
const ATTESTATION_SAMPLE = { ...BASE, notice_date: "2027-02-27", period: "calendar year 2026", assessor: "Independent Assessors LLP", assessment_completed_on: "2026-12-10", days_since_assessment: 79, pen_test_completed_on: "2026-09-15", days_since_pen_test: 165, exceptions_open: false, exceptions_summary: "", as_of: "2027-02-26", form_582_due: "2027-03-31", days_before_form582_due: 32 };

// ------------------------------------------------------------------ NYDFS 500.17(b) April 15 submission
const NYDFS_CERT = `${HEAD("23 NYCRR 500.17(b) annual submission — {{#if certification}}Certification of Material Compliance{{else}}Acknowledgment of Noncompliance{{/if}} for calendar year {{year}}")}
{{#block "body" page=1 y=0.12 pt=11}}{{#if certification}}{{entity_name}} certifies that, for calendar year {{year}}, it materially complied with the requirements of 23 NYCRR Part 500.{{else}}{{entity_name}} acknowledges that, for calendar year {{year}}, it did not materially comply with all the requirements of 23 NYCRR Part 500. Sections not materially complied with: {{#each deficient_sections}}{{this}}; {{/each}} Nature and extent of noncompliance: {{deficiency_detail}}. Remediation plan and timeline: {{remediation_plan}}.{{/if}} Supporting data and records sufficient to demonstrate the basis of this submission are maintained for five years. Signed by {{ceo_name}}, {{ceo_title}} (highest-ranking executive) and {{ciso_name}}, Chief Information Security Officer, on {{date signed_on}}, for electronic filing on the department's website by April 15, {{filing_year}} ({{days_before_apr15}} days before).{{/block}}
${SIGN()}`;
const NYDFS_CERT_RULES = [DATE_RULE, R("apr15", "23 NYCRR 500.17(b): by April 15 of each year", "data_range", "days_before_apr15", "filed on or before April 15", { range: { min: 0 } }), R("signers", "23 NYCRR 500.17(b): 'signed by the covered entity's highest-ranking executive and its CISO'", "data_equality", "ciso_name", "both signatures", { predicate: { and: [{ present: "ceo_name" }, { present: "ceo_title" }, { present: "ciso_name" }, { present: "signed_on" }] } }), R("signers-text", "23 NYCRR 500.17(b)", "presence", "\\(highest-ranking executive\\) and .*Chief Information Security Officer", "both signature lines"), R("records-5y", "23 NYCRR 500.17(b)(2): supporting records kept five years", "presence", "maintained for five years", "five-year records"),
  R("cert-clean", "19.2 rule 11: any fail without an approved exception forces an acknowledgment, not a certification", "conditional", "deficient_count", "certification only with zero unexcepted failures", { when: { "==": [{ var: "certification" }, true] }, predicate: { "==": [{ var: "deficient_count" }, 0] } }),
  R("ack-sections", "23 NYCRR 500.17(b)(1)(ii): acknowledgment identifies the sections not complied with", "conditional", "deficient_sections", "deficient sections listed", { when: { "==": [{ var: "certification" }, false] }, predicate: { and: [{ ">": [{ var: "deficient_sections.length" }, 0] }, { ">": [{ var: "deficient_count" }, 0] }] } }),
  R("ack-text", "23 NYCRR 500.17(b)(1)(ii): nature and extent of noncompliance and remediation timeline", "conditional", "deficient_sections", "acknowledgment text present", { when: { "==": [{ var: "certification" }, false] }, predicate: { and: [{ present: "remediation_plan" }, { present: "deficiency_detail" }] } }), OFFICER_RULE("19.2 escalations: certifications are officer acts"), NO_SSN];
const NYDFS_CERT_SAMPLE = { ...BASE, notice_date: "2027-04-01", entity_name: "Supermortgage", year: 2026, certification: false, deficient_sections: ["500.12 — MFA compensating control for the legacy fax gateway not reviewed within 12 months"], deficient_count: 1, deficiency_detail: "one control test (CTL-SEC-01) failed on 2027-04-01 without an approved exception", remediation_plan: "compensating control reviewed and re-approved by the CISO by 2027-04-30; gateway decommissioned by 2027-06-30", ceo_name: "C. Executive", ceo_title: "Chief Executive Officer", ciso_name: "A. Lead", signed_on: "2027-04-01", filing_year: 2027, days_before_apr15: 14 };

export const VERSIONS_19_2: VersionInput[] = [
  V("NTC_FNMA_INCIDENT_36H", FNMA_36H, FNMA_36H_RULES, FNMA_36H_SAMPLE, "fnma.supplement.2025-09", "Fannie Mae Information Security and Business Resiliency Supplement (Sept. 2, 2025) Cybersecurity Incident content list; 19.2 worked timeline"),
  V("NTC_FNMA_FORM101_INCIDENT", FORM101, FORM101_RULES, FORM101_SAMPLE, "fnma.form101.2025-12", "Form TR101 Data Access Authorization Agreement (12/9/2025): Subordinate Subscriber 36-hour notice"),
  V("NTC_PARTNER_INCIDENT_24H", PARTNER_24H, PARTNER_24H_RULES, PARTNER_24H_SAMPLE, "sm.subservicing.2026-09", "Subservicing Agreement incident-notice clause (24 h contract default); 19.2-T1"),
  V("NTC_NYDFS_500_17A", NYDFS_17A, NYDFS_17A_RULES, NYDFS_17A_SAMPLE, "nydfs.500.2023-11", "23 NYCRR 500.17(a) portal notice; 19.2-T5"),
  V("NTC_NYDFS_500_17C_EXTORTION_24H", NYDFS_17C, NYDFS_17C_RULES, NYDFS_17C_SAMPLE, "nydfs.500.2023-11", "23 NYCRR 500.17(c) extortion payment notice; 19.2-T9"),
  V("NTC_FTC_314_4J", FTC_314_4J, FTC_RULES, FTC_SAMPLE, "ftc.314.2024-05", "16 CFR 314.4(j)(2) six content elements; 19.2-T3"),
  V("NTC_BREACH_CRA", BREACH_CRA, BREACH_CRA_RULES, BREACH_CRA_SAMPLE, "state.ny.899-aa.2026", "N.Y. Gen. Bus. Law §899-aa(8)(b); 19.2-T6"),
  V("NTC_SUPPLEMENT_ATTESTATION", ATTESTATION, ATTESTATION_RULES, ATTESTATION_SAMPLE, "fnma.supplement.2025-09", "Supplement annual officer attestation (Form 582 process, 18.4)"),
  V("NTC_NYDFS_ANNUAL_CERT", NYDFS_CERT, NYDFS_CERT_RULES, NYDFS_CERT_SAMPLE, "nydfs.500.2023-11", "23 NYCRR 500.17(b) certification / acknowledgment; 19.2-T14"),
];

const NON_BORROWER = { noticeClass: "security_incident_notices", piiLevel: "low" as const, retention: "corporate_7y", separateDocument: true };
export const OVERRIDES_19_2: Record<string, Partial<NoticeTemplate>> = {
  NTC_FNMA_INCIDENT_36H: { ...NON_BORROWER, channelPolicy: "electronic_ok_without_esign", citation: "Fannie Mae Information Security and Business Resiliency Supplement (Sept. 2, 2025): Cybersecurity Incident notice no later than 36 hours, by email to privacy_office@fanniemae.com; SVC-2025-01" },
  NTC_FNMA_FORM101_INCIDENT: { ...NON_BORROWER, channelPolicy: "electronic_ok_without_esign", citation: "Form TR101 (12/9/2025): written notice to Fannie Mae and Master Subscriber no later than 36 hours" },
  NTC_PARTNER_INCIDENT_24H: { ...NON_BORROWER, channelPolicy: "electronic_ok_without_esign", citation: "Subservicing Agreement incident-notice clause (24-hour contract default; 19.2 open decision 2)" },
  NTC_NYDFS_500_17A: { ...NON_BORROWER, channelPolicy: "electronic_ok_without_esign", citation: "23 NYCRR 500.17(a): electronic notice on the DFS portal no later than 72 hours after determination" },
  NTC_NYDFS_500_17C_EXTORTION_24H: { ...NON_BORROWER, channelPolicy: "electronic_ok_without_esign", citation: "23 NYCRR 500.17(c): extortion payment notice within 24 hours; written explanation within 30 days" },
  NTC_FTC_314_4J: { ...NON_BORROWER, channelPolicy: "electronic_ok_without_esign", citation: "16 CFR 314.4(j): FTC electronic form, no later than 30 days after discovery (≥ 500 consumers)" },
  NTC_BREACH_CRA: { ...NON_BORROWER, channelPolicy: "electronic_ok_without_esign", citation: "N.Y. Gen. Bus. Law §899-aa(8)(b): consumer reporting agencies when more than 5,000 NY residents are notified at one time" },
  NTC_SUPPLEMENT_ATTESTATION: { ...NON_BORROWER, channelPolicy: "electronic_ok_without_esign", citation: "Fannie Mae Supplement: annual written attestation by a duly authorized corporate officer (Form 582 process)" },
  NTC_NYDFS_ANNUAL_CERT: { ...NON_BORROWER, retention: "nydfs_500_17b_cert_support_5y", channelPolicy: "electronic_ok_without_esign", citation: "23 NYCRR 500.17(b): April 15 certification or acknowledgment signed by the highest-ranking executive and the CISO; records kept five years" },
};
