/**
 * Authored template versions for the §11 early-intervention and collections
 * notices: the "please contact us" letter and callback confirmation (11.1),
 * the FDCPA, bankruptcy and combined early-intervention variants and the
 * Form 745 / Borrower Solicitation Package (11.2), the QRPC summary (11.3),
 * the Reg F validation notice (Model Form B-1, mortgage variant), the
 * §1006.18(e) fragment, verification, original-creditor, duplicative-dispute
 * and cease-acknowledgement letters (11.4), and the Form 182 / Reg B adverse
 * action, Colorado pre-decision and eligibility-result notices (11.5).
 */
import type { ContentRule, VersionInput } from "../registry.ts";
import { V } from "./section01.ts";

const R = (rule_id: string, citation: string, kind: ContentRule["kind"], selector: string, message: string, extra: Partial<ContentRule> = {}): ContentRule => ({ rule_id, citation, kind, selector, severity: "block", message, ...extra });
const DATE_RULE = R("date", "notice date", "presence", "(January|February|March|April|May|June|July|August|September|October|November|December) \\d{1,2}, \\d{4}", "date of the notice");
const FDCPA_SUBSEQUENT = "This communication is from a debt collector.";
const FDCPA_INITIAL = "Supermortgage is a debt collector. We are attempting to collect a debt and any information obtained will be used for that purpose.";
const BASE = { notice_date: "2026-12-14", account_last4: "1234", property_address: "1 Test St, Testville TX 75001", servicer_address: "PO Box 1, Testville TX 75001", exclusive_address: "PO Box 2, Testville TX 75001", team_phone: "(800) 555-0199", servicer_phone: "(800) 555-0100", hud_phone: "(800) 569-4287", hope_hotline: "(888) 995-4673", cfpb_counselor_url: "consumerfinance.gov/find-a-housing-counselor", hud_counselor_url: "hud.gov/counseling", upload_url: "portal.example.com/upload" };
const CONTACT_BLOCK = `{{#block "contact" page=1 y=0.15 pt=12}}Your assigned team: {{team_name}}, {{team_phone}}. Write to us at {{servicer_address}}. Notices of error and requests for information: {{exclusive_address}}.{{/block}}`;
const COUNSELING_BLOCK = `{{#block "counseling" page=1 y=0.65 pt=12}}Housing counselors: {{cfpb_counselor_url}} · {{hud_counselor_url}} · HUD {{hud_phone}} · Fannie Mae HOPE hotline {{hope_hotline}} · knowyouroptions.com{{/block}}`;
const NO_PAYMENT_REQUEST = R("no-payment-request", "§1024.39(c)(1)(iii)(B) / (d)(3)(ii)", "absence", "(amount due|you must pay|please pay|payment of \\$|pay \\$|remit)", "no request for payment");
const FDCPA_FRAGMENT_RULE = R("fdcpa-18e", "12 CFR 1006.18(e)", "presence", "communication is from a debt collector", "§1006.18(e) subsequent-communication disclosure");

// ------------------------------------------------------------------ 11.1
const CONTACT_REQ_SOURCE = `{{#block "heading" page=1 y=0.05 pt=13 bold}}Please contact us about your mortgage{{/block}}
${CONTACT_BLOCK}
{{#block "body" page=1 y=0.3 pt=12}}{{date notice_date}}. Loan number ending {{account_last4}}. Property: {{property_address}}. We have tried to reach you by telephone and have not been able to speak with you. Please call your assigned team at {{team_phone}} so we can talk about your account and any options that may help. If you are having trouble making your payments, help may be available; not all borrowers qualify.{{/block}}
${COUNSELING_BLOCK}
{{#if fdcpa_debt_collector}}{{#block "fdcpa" page=1 y=0.85 pt=10}}${FDCPA_SUBSEQUENT}{{/block}}{{/if}}`;
const CONTACT_REQ_RULES: ContentRule[] = [DATE_RULE, R("encourage", "comment 39(a)-3 (written encouragement counts toward good-faith efforts)", "presence", "Please call your assigned team at \\(\\d{3}\\) \\d{3}-\\d{4}", "encouragement to establish live contact with the assigned team's number"), R("continuity", "12 CFR 1024.40(a)", "presence", "Your assigned team: ", "assigned-contact block (4.3)"), R("exclusive-address", "comment 35(c)-2", "presence", "Notices of error and requests for information: ", "exclusive NoE/RFI address"), R("hud", "§1024.39(b)(2)(v)", "presence", "HUD \\(\\d{3}\\) \\d{3}-\\d{4}", "HUD counseling line"), R("fdcpa-when-dc", "12 CFR 1006.18(e)", "presence", "communication is from a debt collector", "§1006.18(e) fragment rendered on DC loans", { when: { "==": [{ var: "fdcpa_debt_collector" }, true] } }), R("no-threat", "12 CFR 1006.18(c)", "absence", "(legal action|foreclosure will|immediately)", "no threats")];
const CALLBACK_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}Supermortgage: thanks for speaking with us on {{date conversation_on}}. Summary: {{summary}}.{{#if promise_amount_cents}} You told us you would pay {{money promise_amount_cents}} by {{date promise_due_on}} by {{promise_method}}.{{/if}} Next step: {{next_step}}. Questions? Call {{team_phone}}.{{#if fdcpa_debt_collector}} ${FDCPA_SUBSEQUENT}{{/if}} Reply STOP to opt out of texts.{{/block}}`;
const CALLBACK_RULES: ContentRule[] = [R("summary", "11.1 outputs", "presence", "Summary: ", "what was discussed"), R("next-step", "11.1 outputs", "presence", "Next step: ", "next steps"), R("opt-out", "12 CFR 1006.6(e); TCPA", "presence", "Reply STOP to opt out", "opt-out line"), R("consented-channel", "11.1 outputs: only on consented channels", "data_equality", "channel_consent_id", "a consent id for the channel is recorded", { predicate: { present: "channel_consent_id" } }), R("no-demand", "11.1", "absence", "(you must pay|immediately)", "never a demand")];
const CALLBACK_SAMPLE = { ...BASE, conversation_on: "2026-12-11", summary: "your hardship and the options we discussed", promise_amount_cents: 416500n, promise_due_on: "2026-12-28", promise_method: "scheduled ACH", next_step: "we will confirm your payment on December 29", fdcpa_debt_collector: false, channel_consent_id: "consent-sms-1" };

// ------------------------------------------------------------------ 11.2 EI variants and solicitation
const MS4D = "This is a legally required notice. We are sending this notice to you because you are behind on your mortgage payment. We want to notify you of possible ways to avoid losing your home. We have a right to invoke foreclosure based on the terms of your mortgage contract. Please read this letter carefully.";
const BK_DISCLAIMER = "This notice is for informational purposes only and is not an attempt to collect a debt from you personally. If you are in bankruptcy or have received a discharge, this notice is not a demand for payment.";
const MS4A = "Call us today to learn more about your options and instructions for how to apply.";
const EI_BODY = `{{#block "ms4a" page=1 y=0.12 pt=12 bold}}${MS4A}{{/block}}
${CONTACT_BLOCK}
{{#block "options" page=1 y=0.3 pt=12}}If you need help, the following options may be possible (most are subject to lender approval): {{#each options}}{{this}}; {{/each}}Not all borrowers qualify.{{/block}}
{{#block "apply" page=1 y=0.5 pt=12}}Contact us for instructions on how to apply. A Mortgage Assistance Application (Form 710) is available at {{upload_url}}.{{/block}}
${COUNSELING_BLOCK}`;
const EI_FDCPA_SOURCE = `{{#block "ms4d" page=1 y=0.05 pt=12 bold}}${MS4D}{{/block}}
${EI_BODY}
{{#block "fdcpa" page=1 y=0.85 pt=11}}${FDCPA_SUBSEQUENT} This notice does not affect your right to dispute the debt.{{/block}}`;
const EI_BK_SOURCE = `{{#block "bk" page=1 y=0.05 pt=12 bold}}${BK_DISCLAIMER}{{/block}}
{{#block "addressee" page=1 y=0.1 pt=11}}{{#if counsel_name}}Sent to you c/o your bankruptcy counsel, {{counsel_name}}, as listed on the petition in case {{bk_case_number}}.{{/if}}{{/block}}
${EI_BODY}`;
const EI_BK_FDCPA_SOURCE = `{{#block "bk" page=1 y=0.05 pt=12 bold}}${BK_DISCLAIMER}{{/block}}
{{#block "ms4d" page=1 y=0.1 pt=12 bold}}${MS4D}{{/block}}
${EI_BODY}
{{#block "fdcpa" page=1 y=0.85 pt=11}}${FDCPA_SUBSEQUENT} This notice does not affect your right to dispute the debt.{{/block}}`;
const EI_COMMON: ContentRule[] = [R("i-ms4a", "§1024.39(b)(2)(i); MS-4(A)", "presence", "Call us today to learn more about your options", "the (b)(2)(i) statement encouraging the borrower to contact the servicer (MS-4(A))"), R("i-ms4a-layout", "§1024.39(b)(2)(i); MS-4(A); 11.2 rule 8", "layout", "ms4a", "MS-4(A) sentence on page 1 at 12 pt", { layout: { page: 1, minPt: 12 } }), R("ii-contact", "§1024.39(b)(2)(ii); comment 35(c)-2", "presence", "Notices of error and requests for information", "team direct number + exclusive NoE/RFI address"), R("iii-options", "§1024.39(b)(2)(iii); MS-4(B)", "presence", "Not all borrowers qualify", "generic examples with the qualifier"), R("iii-options-retention", "§1024.39(b)(2)(iii); comment 39(b)(2)(iii)-1; 11.2 data model `lossmit_examples_retention`", "presence", "(repayment plan|payment deferral|forbearance|loan modification|modify)", "at least one home-retention example (repayment plan, deferral, forbearance, modification)"), R("iii-options-disposition", "§1024.39(b)(2)(iii); comment 39(b)(2)(iii)-1; 11.2 data model `lossmit_examples_disposition`", "presence", "(short sale|deed[- ]in[- ]lieu|Mortgage Release)", "at least one example of an option that ends ownership (short sale, deed-in-lieu)"), R("iv-apply", "§1024.39(b)(2)(iv)", "presence", "Contact us for instructions on how to apply", "how to apply"), R("v-counseling", "§1024.39(b)(2)(v); MS-4(C)", "presence", "HUD \\(\\d{3}\\) \\d{3}-\\d{4}", "counselor lists and HUD number"), R("min-12pt", "11.2 rule 8", "layout", "options", "12-pt minimum", { layout: { minPt: 12 } }), NO_PAYMENT_REQUEST, R("no-overshadow", "12 CFR 1006.38(b)", "absence", "within \\d+ days", "no payment deadline language during a validation period")];
const EI_FDCPA_RULES: ContentRule[] = [R("ms4d", "§1024.39(d)(3)(i); MS-4(D)", "presence", "We have a right to invoke foreclosure based on the terms of your mortgage contract", "the MS-4(D) foreclosure statement"), R("ms4d-layout", "MS-4(D)", "layout", "ms4d", "MS-4(D) on page 1", { layout: { page: 1, minPt: 12 } }), FDCPA_FRAGMENT_RULE, ...EI_COMMON];
const EI_BK_RULES: ContentRule[] = [R("bk-disclaimer", "§1024.39(c)(1)(iii)(B); comment 39(c)-2", "presence", "not an attempt to collect a debt from you personally", "bankruptcy disclaimer"), R("counsel", "comment 39(c)-1", "presence", "c/o your bankruptcy counsel", "addressed c/o counsel named on the petition (pro se debtor: to the borrower directly, §1024.39(c)(1)(iii))", { when: { present: "counsel_name" } }), ...EI_COMMON];
const EI_BK_FDCPA_RULES: ContentRule[] = [R("bk-disclaimer", "§1024.39(c)(1)(iii)(B)", "presence", "not an attempt to collect a debt from you personally", "bankruptcy disclaimer"), R("ms4d", "§1024.39(d)(3)(i); MS-4(D)", "presence", "We have a right to invoke foreclosure", "MS-4(D) statement"), FDCPA_FRAGMENT_RULE, ...EI_COMMON];
const EI_SAMPLE = { ...BASE, team_name: "Team 7", options: ["refinance", "repayment plan", "payment deferral", "forbearance (temporarily gives you more time to pay your monthly payment)", "loan modification (Flex Modification)", "short sale", "Mortgage Release (deed-in-lieu)"], counsel_name: "A. Counsel, Esq.", bk_case_number: "27-10001" };
const F745_SOURCE = `{{#block "heading" page=1 y=0.05 pt=13 bold}}Mortgage assistance may be available — Borrower Solicitation Letter{{/block}}
{{#block "body" page=1 y=0.12 pt=12}}{{date notice_date}}. Loan number ending {{account_last4}}. Property: {{property_address}}. You may be eligible for options that could help you keep your home or leave it without foreclosure. To be considered, complete the enclosed Mortgage Assistance Application (Form 710) and return it with the documents on the checklist, or apply online at {{upload_url}}. Call {{team_phone}} with questions. Free help is available from the Homeowner's HOPE Hotline at 1-888-995-HOPE (4673).{{/block}}
${COUNSELING_BLOCK}`;
const F745_RULES: ContentRule[] = [DATE_RULE, R("hope-hotline", "D2-2-04: Form 745 must retain the HOPE hotline reference", "presence", "1-888-995-HOPE", "Homeowner's HOPE Hotline number"), R("form-710", "D2-2-04", "presence", "Mortgage Assistance Application \\(Form 710\\)", "Form 710 reference"), R("how-to-apply", "D2-2-04", "presence", "apply online at ", "application path"), R("no-solicit-lt30", "D2-1-01; 11.5 rule 9", "data_range", "regx_days_delinquent", "sent only at ≥ 30 days delinquent (or on the borrower's request)", { range: { min: 30 }, when: { "!": [{ "==": [{ var: "borrower_requested" }, true] }] } }), R("borrower-request-logged", "D2-2-04 (QRPC trigger); 11.5-T9: the request is logged as the basis", "conditional", "request_logged_at", "a borrower-requested package below 30 days delinquent carries the logged request", { when: { "==": [{ var: "borrower_requested" }, true] }, predicate: { present: "request_logged_at" } })];
const F745_SAMPLE = { ...BASE, regx_days_delinquent: 45 };
const BSP_SOURCE = `${F745_SOURCE}
{{#block "enclosures" page=2 y=0.1 pt=12}}Enclosed: Form 710 Mortgage Assistance Application; document checklist ({{#each document_list}}{{this}}; {{/each}}); return envelope; upload link {{upload_url}}{{#if includes_4506c}}; IRS Form 4506-C{{/if}}.{{/block}}`;
const BSP_RULES: ContentRule[] = [...F745_RULES, R("enclosures", "D2-2-04 (Form 745 + Form 710 + checklist)", "presence", "Enclosed: Form 710 Mortgage Assistance Application; document checklist", "the package contents"), R("return-path", "D2-2-04 delivery", "presence", "return envelope; upload link", "return envelope and upload link")];
const BSP_SAMPLE = { ...F745_SAMPLE, document_list: ["pay stubs", "bank statements", "hardship letter"], includes_4506c: false };

// ------------------------------------------------------------------ 11.3 QRPC summary
const QRPC_SUMMARY_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}Supermortgage — summary of our conversation on {{date conversation_on}}. We discussed: {{discussed}}. Next steps: {{next_steps}}.{{#if promise_amount_cents}} Your commitment: {{money promise_amount_cents}} by {{date promise_due_on}}.{{/if}} How to apply for assistance: complete Form 710 at {{upload_url}} or call {{team_phone}}.{{#if fdcpa_debt_collector}} ${FDCPA_SUBSEQUENT}{{/if}} Reply STOP to opt out of texts.{{/block}}`;
const QRPC_SUMMARY_RULES: ContentRule[] = [R("discussed", "11.3 outputs", "presence", "We discussed: ", "what was discussed"), R("next-steps", "11.3 outputs", "presence", "Next steps: ", "next steps"), R("how-to-apply", "11.3 outputs", "presence", "How to apply for assistance", "how to apply"), R("consented-channel", "11.3 outputs: consented channel", "data_equality", "channel_consent_id", "channel consent recorded", { predicate: { present: "channel_consent_id" } }), R("never-demand-in-bk-cease", "11.3 outputs: never a demand in bk/fdcpa-cease contexts", "absence", "(you must pay|immediately|demand)", "no demand")];

// ------------------------------------------------------------------ 11.4 Reg F
const B1_SOURCE = `{{#block "heading" page=1 y=0.03 pt=12 bold}}Supermortgage · {{servicer_address}} · {{servicer_phone}} · {{date notice_date}}{{/block}}
{{#block "intro" page=1 y=0.08 pt=11}}${FDCPA_INITIAL} We are trying to collect a debt that you owe to {{creditor_name}}. To: {{consumer_name}}, {{consumer_address}}. Account number ending {{account_last4}}.{{/block}}
{{#block "itemization" page=1 y=0.2 pt=11}}As of {{date itemization_date}}, you owed: {{money amount_on_itemization_cents}}. Between {{date itemization_date}} and today: you were charged this amount in interest: + {{money interest_since_cents}}; you were charged this amount in fees: + {{money fees_since_cents}}; you paid or were credited this amount toward the debt: − {{money payments_and_credits_cents}}. Total amount of the debt now: {{money current_amount_cents}}.{{#if statement_substitute}} See the enclosed periodic statement dated {{date statement_date}} for the itemization of this debt.{{/if}}{{/block}}
{{#block "dispute" page=1 y=0.45 pt=11}}How can you dispute the debt? Call or write to us by {{date validation_period_end_on}} to dispute all or part of the debt. If you do not, we will assume that our information is correct. If you write to us by {{date validation_period_end_on}}, we must stop collection on any amount you dispute until we send you information that shows you owe the debt. You may use the form below or write to us without the form. What else can you do? Write to ask for the name and address of the original creditor, if different from the current creditor. If you write by {{date validation_period_end_on}}, we must stop collection until we send you that information. Go to www.cfpb.gov/debt-collection to learn more about your rights under federal law. Contact us about your payment options.{{/block}}
{{#block "tearoff" page=1 y=0.75 pt=11}}How do you want to respond? Mail this form to {{servicer_address}}. I want to dispute the debt because I think: this is not my debt; the amount is wrong; other. I want you to send me the name and address of the original creditor. I enclosed this amount: $ ____.{{/block}}
{{#block "language" page=1 y=0.95 pt=9}}Póngase en contacto con nosotros para solicitar una copia de este formulario en español.{{/block}}`;
const B1_RULES: ContentRule[] = [DATE_RULE, R("c1-disclosure", "12 CFR 1006.34(c)(1); 1006.18(e)", "presence", "attempting to collect a debt and any information obtained will be used for that purpose", "initial-communication disclosure"), R("c2-collector-name", "§1006.34(c)(2)(i)", "presence", "Supermortgage · PO Box", "collector name and dispute address"), R("c2-consumer", "§1006.34(c)(2)(iii)", "presence", "To: .*, .*\\. Account number ending", "consumer name and address"), R("c2-creditor", "§1006.34(c)(2)(ii)/(v)", "presence", "debt that you owe to ", "creditor"), R("c2-itemization-date", "§1006.34(c)(2)(vi)", "presence", "As of (January|February|March|April|May|June|July|August|September|October|November|December) \\d{1,2}, \\d{4}, you owed: \\$", "itemization date and amount"), R("c2-itemization", "§1006.34(c)(2)(vii)", "presence", "in interest: \\+ \\$[\\d,]+\\.\\d{2}; you were charged this amount in fees: \\+ \\$[\\d,]+\\.\\d{2}; you paid or were credited this amount toward the debt: − \\$[\\d,]+\\.\\d{2}", "itemization of interest, fees, payments and credits"), R("c2-current", "§1006.34(c)(2)(viii)", "presence", "Total amount of the debt now: \\$", "current amount"), R("c3-period-end", "§1006.34(c)(3)", "presence", "dispute all or part of the debt", "validation-period end date and dispute statements"), R("c3-cfpb", "§1006.34(c)(3)(vi)", "presence", "www\\.cfpb\\.gov/debt-collection", "CFPB website"), R("c4-tearoff", "§1006.34(c)(4)", "presence", "I want to dispute the debt because I think", "consumer-response prompts"), R("c5-substitute", "§1006.34(c)(5)", "conditional", "statement_substitute", "periodic-statement substitute referenced", { when: { "==": [{ var: "statement_substitute" }, true] }, predicate: { present: "statement_date" } }), R("sum-consistent", "11.4 rule 3 (round-half-up per line; current amount is the ledger total)", "data_equality", "itemization_consistent", "lines sum to the current amount", { predicate: { "==": [{ var: "itemization_consistent" }, true] } })];
const B1_SAMPLE = { ...BASE, notice_date: "2026-10-02", creditor_name: "Fannie Mae (Federal National Mortgage Association)", consumer_name: "Test Borrower", consumer_address: "1 Test St, Testville TX 75001", itemization_date: "2026-08-17", amount_on_itemization_cents: 31254022n, interest_since_cents: 123811n, fees_since_cents: 16500n, payments_and_credits_cents: 0n, current_amount_cents: 31394333n, itemization_consistent: true, statement_substitute: false, statement_date: null, validation_period_end_on: "2026-11-08" };
const DISCLOSURE_SOURCE = `{{#block "body" page=1 y=0.9 pt=10}}{{#if initial}}${FDCPA_INITIAL}{{else}}${FDCPA_SUBSEQUENT}{{/if}}{{/block}}`;
const DISCLOSURE_RULES: ContentRule[] = [R("fragment", "12 CFR 1006.18(e)(1)/(2)", "presence", "(attempting to collect a debt and any information obtained will be used for that purpose|communication is from a debt collector)", "initial or subsequent variant present")];
const VERIFICATION_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}{{date notice_date}}. Account number ending {{account_last4}}. We received your dispute dated {{date dispute_received_on}}. Enclosed is verification of the debt: a copy of the note and security instrument, the payment history from {{date history_from}} to {{date history_to}}, and an itemization showing the total amount of {{money current_amount_cents}}. Collection activity, which was paused when we received your dispute, may resume. ${FDCPA_SUBSEQUENT} Questions: {{servicer_phone}}.{{/block}}`;
const VERIFICATION_RULES: ContentRule[] = [DATE_RULE, R("received", "12 CFR 1006.38(d)(2)", "presence", "We received your dispute dated ", "dispute reference"), R("verification", "12 CFR 1006.38(d)(2)(i)", "presence", "copy of the note and security instrument, the payment history", "verification contents"), R("amount", "11.4 rule 5", "presence", "total amount of \\$", "itemized amount"), FDCPA_FRAGMENT_RULE];
const OC_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}{{date notice_date}}. Account number ending {{account_last4}}. You asked for the name and address of the original creditor. Original creditor: {{original_creditor_name}}, {{original_creditor_address}}. Current creditor: {{creditor_name}}. ${FDCPA_SUBSEQUENT}{{/block}}`;
const OC_RULES: ContentRule[] = [DATE_RULE, R("original-creditor", "12 CFR 1006.38(c)", "presence", "Original creditor: ", "name and address of the original creditor"), FDCPA_FRAGMENT_RULE];
const DUP_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}{{date notice_date}}. Account number ending {{account_last4}}. We received your dispute dated {{date dispute_received_on}}. It is substantially the same as your earlier dispute dated {{date prior_dispute_on}}, which we answered on {{date prior_response_on}}; that response is enclosed. If you have new information, please send it to {{servicer_address}}. ${FDCPA_SUBSEQUENT}{{/block}}`;
const DUP_RULES: ContentRule[] = [DATE_RULE, R("duplicative", "12 CFR 1006.38(d)(3)", "presence", "substantially the same as your earlier dispute dated ", "identifies the prior dispute"), R("prior-response", "12 CFR 1006.38(d)(3)(ii)", "presence", "which we answered on ", "references the prior response"), FDCPA_FRAGMENT_RULE];
const CEASE_ACK_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}{{date notice_date}}. Account number ending {{account_last4}}. We received your written request dated {{date cease_received_on}} that we stop communicating with you about this debt. We will not contact you further to collect, except to send legally required notices and to tell you if we intend to take a specific action permitted by your mortgage, such as foreclosure. You may still contact us about assistance options at any time. ${FDCPA_SUBSEQUENT}{{/block}}`;
const CEASE_ACK_RULES: ContentRule[] = [DATE_RULE, R("terminated", "12 CFR 1006.6(c)(2)(i)", "presence", "We will not contact you further to collect", "efforts terminated"), R("remedies", "12 CFR 1006.6(c)(2)(ii)-(iii)", "presence", "specific action permitted by your mortgage, such as foreclosure", "specified remedies"), R("no-demand", "12 CFR 1006.6(c)", "absence", "(you must pay|please pay|amount due)", "no payment demand"), FDCPA_FRAGMENT_RULE];
const REGF_SAMPLE = { ...BASE, notice_date: "2026-11-05", dispute_received_on: "2026-10-20", history_from: "2025-01-01", history_to: "2026-11-01", current_amount_cents: 31394333n, original_creditor_name: "Test Originator Bank", original_creditor_address: "10 Bank St, Testville TX 75001", creditor_name: "Fannie Mae", prior_dispute_on: "2026-10-20", prior_response_on: "2026-11-05", cease_received_on: "2026-11-10", initial: true };

// ------------------------------------------------------------------ 11.5 adverse action, Colorado, eligibility result
const F182_SOURCE = `{{#block "heading" page=1 y=0.05 pt=13 bold}}Notice of action taken on your mortgage loan modification request{{/block}}
{{#block "body" page=1 y=0.12 pt=11}}{{date notice_date}}. Loan number ending {{account_last4}}. Property: {{property_address}}. Fannie Mae, as the owner of the mortgage loan, reviewed the mortgage loan modification request. Fannie Mae's address: Midtown Center, 1100 15th Street, NW, Washington, DC, 20005. The request was not approved for the following reason(s): {{#each reasons}}{{this}}; {{/each}}{{/block}}
{{#block "credit" page=1 y=0.4 pt=11}}{{#if cra_name}}A credit score from {{cra_name}} ({{cra_phone}}, {{cra_address}}) was used in this decision. Your score: {{credit_score}} as of {{date score_date}}; scores range from {{score_range}}. Key factors: {{score_factors}}. The credit reporting agency did not make the decision and cannot explain why it was made.{{else}}No consumer report or credit score was used to make this decision.{{/if}}{{/block}}
{{#block "ecoa" page=1 y=0.6 pt=10}}The federal Equal Credit Opportunity Act prohibits creditors from discriminating against credit applicants on the basis of race, color, religion, national origin, sex, marital status, age (provided the applicant has the capacity to enter into a binding contract); because all or part of the applicant's income derives from any public assistance program; or because the applicant has in good faith exercised any right under the Consumer Credit Protection Act. The federal agency that administers compliance with this law concerning this creditor is the Consumer Financial Protection Bureau, 1700 G Street NW, Washington, DC 20552. You have the right to a statement of specific reasons within 60 days if none is given above.{{/block}}
{{#block "appeal" page=1 y=0.85 pt=11}}You may ask us to review this decision or provide additional information within 14 days by calling {{team_phone}} or writing to {{servicer_address}}. Reviewed by: {{reviewer_id}}.{{/block}}`;
const F182_RULES: ContentRule[] = [DATE_RULE, R("fnma-reviewed", "D2-1-01 / A4-2.1-06 (Form 182)", "presence", "Fannie Mae, as the owner of the mortgage loan, reviewed the mortgage loan modification request", "the Fannie Mae-reviewed statement"), R("fnma-address", "Form 182", "presence", "Midtown Center, 1100 15th Street, NW, Washington, DC, 20005", "Fannie Mae's address"), R("reasons", "12 CFR 1002.9(a)(2); Form 182", "presence", "not approved for the following reason\\(s\\): .+; ", "reason for the decline"), R("cra", "Form 182 / FCRA §1681m", "presence", "(A credit score from .* was used in this decision|No consumer report or credit score was used)", "CRA name/contact and score disclosure when a score was used"), R("ecoa", "12 CFR 1002.9(b)(1)", "presence", "Equal Credit Opportunity Act prohibits creditors from discriminating", "ECOA notice"), R("appeal", "11.5 outputs", "presence", "You may ask us to review this decision", "appeal / right-to-reasons language"), R("reviewer", "11.5 guardrail: no adverse notice without reviewer_id", "data_equality", "reviewer_id", "reviewer recorded", { predicate: { present: "reviewer_id" } })];
const F182_SAMPLE = { ...BASE, notice_date: "2026-11-19", reasons: ["pre-modification housing expense-to-income ratio not greater than 40 percent", "fewer than two 30-day delinquencies in the preceding six months"], cra_name: "Test Bureau", cra_phone: "(800) 555-0155", cra_address: "1 Bureau Way, Testville TX 75001", credit_score: 612, score_date: "2026-10-20", score_range: "300 to 850", score_factors: "serious delinquency; proportion of balances to credit limits", reviewer_id: "reviewer-42" };
const CO_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}{{date notice_date}}. Loan number ending {{account_last4}}. Before we make a decision on your request for mortgage assistance, Colorado law requires us to tell you that an artificial intelligence system will be used to help evaluate your request. The decision itself is made by written eligibility rules and reviewed by a person. The purpose of the system is {{purpose}}. If the decision is not in your favor you will receive the principal reasons, you may correct any inaccurate personal data, and you may appeal for human review by calling {{team_phone}} or writing to {{servicer_address}}. Contact us with questions.{{/block}}`;
const CO_RULES: ContentRule[] = [DATE_RULE, R("pre-decision", "Colo. SB 24-205 §6-1-1703(4)(a)", "presence", "Before we make a decision", "pre-decision timing"), R("ai-used", "Colo. SB 24-205 §6-1-1703(4)(a)(I)", "presence", "artificial intelligence system will be used", "AI system disclosed"), R("purpose", "Colo. SB 24-205 §6-1-1703(4)(a)(II)", "presence", "The purpose of the system is ", "purpose and nature"), R("human-review", "Colo. SB 24-205 §6-1-1703(4)(b)", "presence", "appeal for human review", "appeal / human review"), R("correct-data", "Colo. SB 24-205 §6-1-1703(4)(b)", "presence", "correct any inaccurate personal data", "right to correct data")];
const CO_SAMPLE = { ...BASE, notice_date: "2026-10-20", purpose: "to classify your documents and summarize your hardship for the eligibility rules" };
const ELIG_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}{{date notice_date}}. Loan number ending {{account_last4}}. Thank you for asking us to evaluate your situation. Result of our review as of {{date evaluation_date}}: {{result_text}}. {{#if next_step}}Next step: {{next_step}}.{{/if}} This letter is informational; any offer or decision will come in a separate notice with its own terms and deadlines. Questions: {{team_phone}}.{{/block}}`;
const ELIG_RULES: ContentRule[] = [DATE_RULE, R("result", "11.5 outputs (informational)", "presence", "Result of our review as of .*: ", "the evaluation result"), R("informational", "11.5 guardrail: no terms before SMDU's decision", "absence", "(your new payment|interest rate of|will be modified to)", "no terms quoted"), R("separate-notice", "11.5 outputs", "presence", "any offer or decision will come in a separate notice", "informational framing")];
const ELIG_SAMPLE = { ...BASE, notice_date: "2026-10-21", evaluation_date: "2026-10-20", result_text: "your request meets Fannie Mae's imminent-default criteria and has been submitted for a decision", next_step: "watch for the Evaluation Notice within 30 days of your complete application" };

export const SECTION_11_VERSIONS: readonly VersionInput[] = [
  V("NTC_SM_CONTACT_REQUEST_LETTER", CONTACT_REQ_SOURCE, CONTACT_REQ_RULES, { ...EI_SAMPLE, notice_date: "2026-11-29", fdcpa_debt_collector: false }, "regx.early_intervention.2016", "comment 39(a)-3; 11.1 rule 5"),
  V("NTC_SM_CALLBACK_CONFIRMATION", CALLBACK_SOURCE, CALLBACK_RULES, CALLBACK_SAMPLE, "contact.v1", "11.1 outputs; rule 10 worked scenario"),
  V("NTC_REGX_39D_EARLY_INTERVENTION_FDCPA", EI_FDCPA_SOURCE, EI_FDCPA_RULES, { ...EI_SAMPLE, variant: "fdcpa", fdcpa_debt_collector: true }, "regx.early_intervention.2016", "§1024.39(d)(3); Appendix MS-4(D)"),
  V("NTC_REGX_39C_EARLY_INTERVENTION_BK", EI_BK_SOURCE, EI_BK_RULES, { ...EI_SAMPLE, variant: "bk" }, "regx.early_intervention.2016", "§1024.39(c)(1)(iii); 11.2 rule 5"),
  V("NTC_REGX_39CD_EARLY_INTERVENTION_BK_FDCPA", EI_BK_FDCPA_SOURCE, EI_BK_FDCPA_RULES, { ...EI_SAMPLE, variant: "bk_fdcpa", fdcpa_debt_collector: true }, "regx.early_intervention.2016", "§1024.39(c)/(d); 11.2-Q2 courtesy only"),
  V("NTC_FNMA_D2204_SOLICITATION_LETTER_745", F745_SOURCE, F745_RULES, F745_SAMPLE, "fnma.d2_2_04.2017", "Form 745 equivalent (D2-2-04)"),
  V("NTC_FNMA_D2204_SOLICITATION_PACKAGE", BSP_SOURCE, BSP_RULES, BSP_SAMPLE, "fnma.d2_2_04.2017", "Borrower Solicitation Package (D2-2-04); 11.2 rule 9"),
  V("NTC_SM_QRPC_SUMMARY", QRPC_SUMMARY_SOURCE, QRPC_SUMMARY_RULES, { ...CALLBACK_SAMPLE, discussed: "the reason for the missed payments and the options that may be available", next_steps: "complete Form 710 by December 20" }, "contact.v1", "11.3 outputs"),
  V("NTC_REGF_1006_34_VALIDATION_B1", B1_SOURCE, B1_RULES, B1_SAMPLE, "regf.2021", "Model Form B-1, mortgage variant; 11.4 rule 3 worked example"),
  V("NTC_REGF_1006_18E_DISCLOSURE", DISCLOSURE_SOURCE, DISCLOSURE_RULES, { initial: true }, "regf.2021", "12 CFR 1006.18(e) fragment"),
  V("NTC_REGF_1006_38_VERIFICATION", VERIFICATION_SOURCE, VERIFICATION_RULES, REGF_SAMPLE, "regf.2021", "12 CFR 1006.38(d)(2); 11.4-T5"),
  V("NTC_REGF_1006_38_ORIGINAL_CREDITOR", OC_SOURCE, OC_RULES, REGF_SAMPLE, "regf.2021", "12 CFR 1006.38(c)"),
  V("NTC_REGF_1006_38_DUPLICATIVE", DUP_SOURCE, DUP_RULES, REGF_SAMPLE, "regf.2021", "12 CFR 1006.38(d)(3)"),
  V("NTC_REGF_1006_6C_CEASE_ACK", CEASE_ACK_SOURCE, CEASE_ACK_RULES, REGF_SAMPLE, "regf.2021", "12 CFR 1006.6(c)(2); 11.4 rule 6"),
  V("NTC_FNMA_A42106_FORM182_ADVERSE_ACTION", F182_SOURCE, F182_RULES, F182_SAMPLE, "fnma.imminent_default.2018-12", "Form 182 + 12 CFR 1002.9 + FCRA §1681m; 11.5 rule 8"),
  V("NTC_CO_AI_ACT_PRE_DECISION", CO_SOURCE, CO_RULES, CO_SAMPLE, "state.ai.CO.2026", "Colorado SB 24-205; 11.5-T11"),
  V("NTC_SM_ID_ELIGIBILITY_RESULT", ELIG_SOURCE, ELIG_RULES, ELIG_SAMPLE, "fnma.imminent_default.2018-12", "11.5 outputs (informational)"),
];
