/**
 * Authored template versions for the §9 insurance notices: hazard tracking
 * (9.1), the force-placed reminder and renewal notices (MS-3(B)/(C)/(D),
 * 9.2–9.4), the cancellation/refund confirmation (9.5), the flood notices
 * (9.6) and the loss-draft letters (9.7). Sample payloads are the sections'
 * worked examples so the publish gate proves every template.
 */
import type { ContentRule, VersionInput } from "../registry.ts";
import { V } from "./section01.ts";

const R = (rule_id: string, citation: string, kind: ContentRule["kind"], selector: string, message: string, extra: Partial<ContentRule> = {}): ContentRule => ({ rule_id, citation, kind, selector, severity: "block", message, ...extra });
const CONTACT = `{{#block "contact" page=1 y=0.9 pt=10}}Supermortgage · {{servicer_phone}} · {{servicer_address}} · Send insurance information to {{insurance_email}} or {{servicer_address}}.{{/block}}`;
const BASE = { servicer_phone: "(800) 555-0100", servicer_address: "PO Box 1, Testville TX 75001", insurance_email: "insurance@example.com", account_last4: "1234", property_address: "1 Test St, Testville TX 75001", notice_date: "2026-11-04" };
const CONTACT_RULE = R("contact", "§1024.37(c)(2)(ii)/(x)", "presence", "Send insurance information to", "how to provide evidence and contact");
const DATE_RULE = R("date", "§1024.37(c)(2)(i)", "presence", "(January|February|March|April|May|June|July|August|September|October|November|December) \\d{1,2}, \\d{4}", "date of the notice");

// ------------------------------------------------------------------ 9.1 hazard tracking
const DEF_SOURCE = (bk: boolean) => `{{#block "heading" page=1 y=0.05 pt=14 bold}}Important notice about the insurance on your property{{/block}}
${bk ? `{{#block "bk" page=1 y=0.1 pt=10}}This notice is for informational purposes only and is not an attempt to collect a debt from you personally.{{/block}}` : ""}
{{#block "body" page=1 y=0.15 pt=11}}{{date notice_date}}. Loan number ending {{account_last4}}. Property: {{property_address}}. Policy {{policy_number}} with {{carrier_name}}: our records show the following deficiency — {{deficiency_text}}. Your loan requires {{requirement_text}}. To cure it, {{cure_options}}. If the deficiency is not cured, we may purchase insurance on your property at your expense; insurance we buy may cost significantly more than insurance you can buy yourself and may provide less coverage.{{/block}}
${CONTACT}`;
const DEF_RULES = (bk: boolean): ContentRule[] => [R("property-policy", "B-2-02", "presence", "Property: .* Policy .* with", "property and policy identified"), R("deficiency", "B-2-02 'notify the borrower of the insufficiency'", "presence", "the following deficiency — ", "the specific deficiency"), R("requirement", "B-2-02", "presence", "Your loan requires", "the requirement"), R("cure", "B-2-02", "presence", "To cure it, ", "cure options"), R("lpi-warning", "§1024.37(c)(2)(viii)", "presence", "may cost significantly more .* may provide less coverage", "LPI may follow with its cost warning"), ...(bk ? [R("bk-legend", "Section 14 overlay", "presence", "informational purposes only", "bankruptcy disclaimer"), R("no-must-pay", "9.1 edge (bankruptcy)", "absence", "you must pay", "no payment demand beyond the model form")] : []), CONTACT_RULE];
const DEF_SAMPLE = { ...BASE, policy_number: "HO-4471", carrier_name: "Test Mutual", deficiency_text: "the all-peril deductible of $12,501 exceeds 5% of the dwelling coverage", requirement_text: "a deductible of no more than 5% of the dwelling coverage (Fannie Mae B-2-01)", cure_options: "ask your carrier to lower the deductible and send us the updated declarations page" };
const REMINDER_SOURCE = `{{#block "heading" page=1 y=0.05 pt=13 bold}}Annual insurance reminder{{/block}}
{{#block "body" page=1 y=0.12 pt=11}}Your mortgage requires you to maintain property insurance on {{property_address}} for as long as the loan is outstanding. We recommend that you review your coverage with your insurance provider each year to confirm it reflects the cost to rebuild your home and that we are listed as mortgagee. Learn more at {{fnma_consumer_url}}.{{/block}}
${CONTACT}`;
const REMINDER_RULES: ContentRule[] = [R("obligation", "B-2-01", "presence", "requires you to maintain property insurance", "obligation to maintain insurance"), R("review", "B-2-01", "presence", "review your coverage with your insurance provider", "recommendation to review coverage"), R("website", "9.1 rule 7", "presence", "Learn more at ", "website pointer"), R("no-fpi-language", "9.1 rule 7 (not a §1024.37 notice)", "absence", "purchase insurance on your property at your expense", "no FPI language"), R("annual", "9.1 rule 7", "data_range", "days_since_last", "one per 12 months", { range: { min: 365 } })];
const EOI_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}Our records show the property insurance policy for {{property_address}} (policy {{policy_number}}) expires on {{date expiration_date}}. As a courtesy, please ask your insurance agent to send us the renewal declarations page showing Supermortgage as mortgagee. If you have already renewed, thank you — no further action is needed.{{/block}}
${CONTACT}`;
const EOI_RULES: ContentRule[] = [R("expiration", "9.1 (courtesy request at −30 days)", "presence", "expires on", "expiration date"), R("courtesy", "9.1", "presence", "As a courtesy", "courtesy framing"), R("no-fpi-language", "9.1: must not contain FPI language", "absence", "(purchase insurance on your property at your expense|force-placed|lender-placed)", "no §1024.37 language"), CONTACT_RULE];

// ------------------------------------------------------------------ 9.3 / 9.4 force-placed reminders (MS-3(B), MS-3(C)) and renewal (MS-3(D))
const C2_BLOCK = `Loan number ending {{account_last4}}. Our records show that your {{insurance_type}} insurance {{status_phrase}} on {{date coverage_event_date}}. You must provide us with insurance information. We will purchase insurance on your property at your expense if you do not provide evidence of {{insurance_type}} insurance. The insurance we buy may cost significantly more than insurance you can buy yourself and may provide less coverage. To provide insurance information, contact us at {{servicer_phone}} or {{servicer_address}}; you may also send it to {{insurance_email}}. Property: {{property_address}}.`;
const MS3B_SOURCE = `{{#block "heading" page=1 y=0.05 pt=14 bold}}SECOND AND FINAL NOTICE ABOUT YOUR {{upper insurance_type}} INSURANCE — PLEASE READ{{/block}}
{{#block "body" page=1 y=0.15 pt=12}}{{date notice_date}}. This is the second and final notice. ${C2_BLOCK}{{/block}}
{{#block "bold_items" page=1 y=0.55 pt=12 bold}}This is the second and final notice. The insurance we buy will cost {{money annual_premium_cents}} annually{{#if premium_is_estimate}} (an estimate){{/if}}. You must provide insurance information within 15 days.{{/block}}
${CONTACT}`;
const MS3C_SOURCE = `{{#block "heading" page=1 y=0.05 pt=14 bold}}SECOND AND FINAL NOTICE ABOUT YOUR {{upper insurance_type}} INSURANCE — PLEASE READ{{/block}}
{{#block "body" page=1 y=0.15 pt=12}}{{date notice_date}}. This is the second and final notice. Loan number ending {{account_last4}}. We received the insurance information you provided, but we have not received evidence that you had {{insurance_type}} insurance continuously in force. Please send us evidence of coverage for {{#each unverified_ranges}}{{date start}} to {{date end}}; {{/each}}You will be charged for insurance we purchased for any period we cannot verify coverage. You must provide us with insurance information. We will purchase insurance on your property at your expense if you do not provide evidence of {{insurance_type}} insurance. The insurance we buy may cost significantly more than insurance you can buy yourself and may provide less coverage. To provide insurance information, contact us at {{servicer_phone}} or {{servicer_address}}; you may also send it to {{insurance_email}}. Property: {{property_address}}.{{/block}}
{{#block "bold_items" page=1 y=0.6 pt=12 bold}}This is the second and final notice. The insurance we buy will cost {{money annual_premium_cents}} annually{{#if premium_is_estimate}} (an estimate){{/if}}.{{/block}}
${CONTACT}`;
const MS3_COMMON: ContentRule[] = [DATE_RULE, R("second-final", "§1024.37(d)(2)(i)(B)", "presence", "This is the second and final notice", "second and final notice statement"), R("cost", "§1024.37(d)(2)(i)(D)", "presence", "will cost \\$[\\d,]+\\.\\d{2} annually", "cost as an annual premium"), R("estimate-label", "§1024.37(d)(2)(i)(D) (identified as an estimate)", "conditional", "premium_is_estimate", "estimate identified", { when: { "==": [{ var: "premium_is_estimate" }, true] }, predicate: { "==": [{ var: "estimate_basis_present" }, true] } }), R("bold", "§1024.37(d)(3)", "layout", "bold_items", "statements in bold", { layout: { bold: true, page: 1 } }), R("timing", "§1024.37(d)(1)", "data_range", "days_after_first_notice", "not earlier than 30 days after the first notice", { range: { min: 30 } }), R("no-extra", "§1024.37(d)(4)", "absence", "(agent list|Spanish|enclosed brochure)", "nothing else on the notice pages"), CONTACT_RULE];
const MS3B_RULES: ContentRule[] = [...MS3_COMMON, R("c2-block", "§1024.37(d)(2)(i)(C)", "presence", "will purchase insurance on your property at your expense", "the (c)(2)(ii)–(xi) content")];
const MS3C_RULES: ContentRule[] = [...MS3_COMMON, R("received", "§1024.37(d)(2)(ii)(D)", "presence", "We received the insurance information you provided", "acknowledgment of information received"), R("ranges", "§1024.37(d)(2)(ii)(E)", "presence", "evidence of coverage for (January|February|March|April|May|June|July|August|September|October|November|December) \\d{1,2}, \\d{4} to", "request for the missing period(s)"), R("charge-unverified", "§1024.37(d)(2)(ii)(F)", "presence", "charged for insurance we purchased for any period we cannot verify coverage", "will-be-charged statement")];
const MS3_SAMPLE = { ...BASE, insurance_type: "hazard", status_phrase: "expired", coverage_event_date: "2026-10-01", annual_premium_cents: 219000n, premium_is_estimate: true, estimate_basis_present: true, days_after_first_notice: 30, unverified_ranges: [{ start: "2026-10-01", end: "2026-10-14" }] };
const MS3D_SOURCE = `{{#block "heading" page=1 y=0.05 pt=14 bold}}NOTICE ABOUT RENEWING THE INSURANCE WE PURCHASED FOR YOUR PROPERTY{{/block}}
{{#block "body" page=1 y=0.15 pt=12}}{{date notice_date}}. Loan number ending {{account_last4}}. Because we did not receive evidence of {{insurance_type}} insurance, we purchased insurance on your property effective {{date placement_effective}}, and we will renew it on {{date anniversary}} unless you provide evidence of your own insurance. The insurance we buy will cost {{money annual_premium_cents}} annually. It may cost significantly more than insurance you can buy yourself and may provide less coverage. You may buy your own insurance at any time; if you do, send the declarations page to {{insurance_email}} or {{servicer_address}} and we will cancel the insurance we bought and refund any premium for the period you were covered. Property: {{property_address}}.{{/block}}
{{#block "bold_items" page=1 y=0.55 pt=12 bold}}We will charge you for the renewed insurance. You may provide your own insurance at any time.{{/block}}
${CONTACT}`;
const MS3D_RULES: ContentRule[] = [DATE_RULE, R("renewal", "§1024.37(e)(2)(ii)–(iii)", "presence", "we will renew it on", "renewal statement with the date"), R("cost", "§1024.37(e)(2)(iv)", "presence", "will cost \\$[\\d,]+\\.\\d{2} annually", "cost as an annual premium"), R("own-insurance", "§1024.37(e)(2)(v)–(vi)", "presence", "You may buy your own insurance at any time", "the borrower may provide own insurance"), R("cancel-refund", "§1024.37(g)", "presence", "cancel the insurance we bought and refund", "cancellation and refund"), R("bold", "§1024.37(e)(3)", "layout", "bold_items", "bold items", { layout: { bold: true, page: 1 } }), R("timing", "§1024.37(e)(1)(iii)", "data_range", "days_before_anniversary", "mailed at least 45 days before the charge", { range: { min: 45 } }), R("annual", "§1024.37(e)(5)", "data_range", "days_since_last_renewal_notice", "one per year", { range: { min: 365 } }), CONTACT_RULE];
const MS3D_SAMPLE = { ...BASE, notice_date: "2027-08-02", insurance_type: "hazard", placement_effective: "2026-10-01", anniversary: "2027-10-01", annual_premium_cents: 225000n, days_before_anniversary: 60, days_since_last_renewal_notice: 400 };

// ------------------------------------------------------------------ 9.5 cancellation / refund confirmation
const CANCEL_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}{{date notice_date}}. Loan number ending {{account_last4}}. We received evidence on {{date evidence_received_on}} that you have had {{insurance_type}} insurance since {{date borrower_coverage_start}}. We cancelled the insurance we purchased effective {{date cancellation_effective}} and removed {{money removed_cents}} of charges for the {{overlap_days}} days both policies overlapped. {{#if refund_cents}}A refund of {{money refund_cents}} for the amount you paid toward those charges is being sent by {{rail}}.{{else}}No refund is due because you had not paid toward the removed charges.{{/if}} {{#if retained_cents}}Charges of {{money retained_cents}} remain for {{date gap_start}} to {{date gap_end}}, when we could not verify coverage.{{/if}}{{/block}}
${CONTACT}`;
const CANCEL_RULES: ContentRule[] = [R("cancel", "§1024.37(g)(1)", "presence", "cancelled the insurance we purchased effective", "cancellation within 15 days"), R("removed", "§1024.37(g)(2)", "presence", "removed \\$[\\d,]+\\.\\d{2} of charges for the \\d+ days", "charges removed for the overlap"), R("refund", "§1024.37(g)(2)", "presence", "(A refund of \\$[\\d,]+\\.\\d{2}|No refund is due)", "refund of premiums paid"), R("within-15", "§1024.37(g)", "data_range", "days_after_evidence", "within 15 days of evidence", { range: { max: 15 } }), CONTACT_RULE];
const CANCEL_SAMPLE = { ...BASE, notice_date: "2027-01-20", insurance_type: "hazard", evidence_received_on: "2027-01-12", borrower_coverage_start: "2026-12-15", cancellation_effective: "2026-12-15", removed_cents: 174000n, overlap_days: 290, refund_cents: 15000n, rail: "ACH credit", retained_cents: 45000n, gap_start: "2026-10-01", gap_end: "2026-12-14", days_after_evidence: 8 };

// ------------------------------------------------------------------ 9.6 flood
const FLOOD45_SOURCE = `{{#block "heading" page=1 y=0.05 pt=14 bold}}NOTICE: FLOOD INSURANCE IS REQUIRED FOR YOUR PROPERTY{{/block}}
{{#block "body" page=1 y=0.12 pt=11}}{{date notice_date}}. Loan number ending {{account_last4}}. Property: {{property_address}}. A flood zone determination shows that the building securing your loan is in a Special Flood Hazard Area (zone {{flood_zone}}, map panel {{map_panel}} effective {{date map_effective}}). Federal law requires flood insurance in at least {{money required_amount_cents}} for the remaining term of your loan. You have 45 days from the date of this notice, until {{date deadline}}, to purchase flood insurance through the National Flood Insurance Program or a qualifying private policy. If you do not, we will purchase flood insurance on behalf of the borrower and charge you the premiums and fees for coverage beginning on {{date coverage_from}}. Insurance we purchase may cost significantly more than insurance you can buy yourself and may provide less coverage. Send your declarations page to {{insurance_email}} or {{servicer_address}}.{{/block}}
${CONTACT}`;
const FLOOD45_RULES: ContentRule[] = [R("determination", "42 U.S.C. §4012a(e)(1); 9.6 rule 4", "presence", "Special Flood Hazard Area \\(zone .*, map panel .* effective", "the SFHA determination with zone, panel and date"), R("amount", "§4012a(b)", "presence", "at least \\$[\\d,]+\\.\\d{2} for the remaining term", "required amount for the remaining term"), R("45-days", "§4012a(e)(1)", "presence", "You have 45 days from the date of this notice", "45-day period"), R("on-behalf", "§4012a(e)(2)", "presence", "purchase flood insurance on behalf of the borrower and charge you the premiums and fees for coverage beginning on", "placement and charge statement"), R("cost-warning", "9.6 rule 4", "presence", "may cost significantly more", "cost warning"), R("evidence", "§4012a(e)(4)", "presence", "Send your declarations page", "declarations page acceptable"), R("separate", "RESPA §6(l)(4)", "data_equality", "separate_document", "separate paper when mailed with an MS-3(A)", { predicate: { "==": [{ var: "separate_document" }, true] } }), CONTACT_RULE];
const FLOOD_SAMPLE = { ...BASE, notice_date: "2027-02-05", flood_zone: "AE", map_panel: "48453C0445K", map_effective: "2027-02-03", required_amount_cents: 24000000n, deadline: "2027-03-22", coverage_from: "2027-02-03", separate_document: true, premium_cents: 115000n, placed_on: "2027-03-22", letter_date: "2027-05-10", refund_cents: 93890n, termination_effective: "2027-04-11", days_after_evidence: 20 };
const FLOOD_PLACED_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}{{date notice_date}}. Loan number ending {{account_last4}}. Because we did not receive evidence of flood insurance by {{date deadline}}, we purchased flood insurance of {{money required_amount_cents}} on your property on {{date placed_on}}, effective {{date coverage_from}}. The annual premium is {{money premium_cents}}, which will be charged to your account. You may replace it at any time with your own NFIP or qualifying private policy: send the declarations page to {{insurance_email}} and we will terminate the insurance we bought and refund the premium for any overlap within 30 days.{{/block}}
${CONTACT}`;
const FLOOD_PLACED_RULES: ContentRule[] = [R("bound", "9.6 rule 5", "presence", "we purchased flood insurance of \\$[\\d,]+\\.\\d{2} on your property on", "coverage bound with amount and date"), R("premium", "9.6 rule 5", "presence", "annual premium is \\$[\\d,]+\\.\\d{2}, which will be charged", "premium and charge"), R("replace", "§4012a(e)(3)", "presence", "terminate the insurance we bought and refund the premium for any overlap within 30 days", "how to replace; 30-day refund"), CONTACT_RULE];
const FLOOD_MAP_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}{{date notice_date}}. Loan number ending {{account_last4}}. FEMA revised the flood map for {{property_address}} effective {{date map_effective}}: the building securing your loan is now in zone {{flood_zone}} (map panel {{map_panel}}). {{#if coverage_required}}Flood insurance is now required; see the enclosed notice for the amount and the 45-day period.{{else}}Flood insurance is no longer required by federal law for this loan; you may keep your policy if you wish.{{/if}}{{/block}}
${CONTACT}`;
const FLOOD_MAP_RULES: ContentRule[] = [R("revision", "9.6 rule 7 / 44 CFR 61.11", "presence", "FEMA revised the flood map .* effective", "map revision with date"), R("zone", "9.6", "presence", "now in zone", "new zone"), R("consequence", "9.6", "presence", "(Flood insurance is now required|no longer required)", "consequence stated"), CONTACT_RULE];
const FLOOD_REMOVED_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}{{date notice_date}}. Loan number ending {{account_last4}}. Based on the FEMA letter/map revision dated {{date letter_date}}, the building securing your loan is no longer in a Special Flood Hazard Area. Flood insurance is no longer required for this loan. {{#if lpi_cancelled}}We cancelled the flood insurance we had purchased effective {{date letter_date}} and are refunding {{money refund_cents}} for the period after that date.{{/if}} Any NFIP policy you bought yourself is yours to keep or cancel.{{/block}}
${CONTACT}`;
const FLOOD_REMOVED_RULES: ContentRule[] = [R("no-longer", "9.6 rule 7", "presence", "no longer in a Special Flood Hazard Area", "remapped out"), R("not-required", "9.6 rule 7", "presence", "Flood insurance is no longer required", "requirement removed"), R("cancel-refund", "9.6 rule 7", "conditional", "lpi_cancelled", "LPI cancelled at the letter date with a refund", { when: { "==": [{ var: "lpi_cancelled" }, true] }, predicate: { present: "refund_cents" } }), CONTACT_RULE];
const FLOOD_TERM_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}{{date notice_date}}. Loan number ending {{account_last4}}. We received your flood insurance declarations page on {{date evidence_received_on}}. We terminated the flood insurance we purchased effective {{date termination_effective}} and are refunding {{money refund_cents}} of premiums and fees for the period both policies were in force, within 30 days of receiving your evidence.{{/block}}
${CONTACT}`;
const FLOOD_TERM_RULES: ContentRule[] = [R("terminated", "42 U.S.C. §4012a(e)(3)", "presence", "terminated the flood insurance we purchased effective", "termination"), R("refund", "§4012a(e)(3)", "presence", "refunding \\$[\\d,]+\\.\\d{2} of premiums and fees", "refund of premiums and fees for the overlap"), R("within-30", "§4012a(e)(3)", "data_range", "days_after_evidence", "within 30 days", { range: { max: 30 } }), CONTACT_RULE];

// ------------------------------------------------------------------ 9.7 loss drafts
const LD_BASE = { ...BASE, claim_number: "CLM-2026-0917", proceeds_cents: 6000000n, initial_release_cents: 4000000n, held_cents: 2000000n, release_cents: 1400000n, pct_complete: "70", cumulative_cents: 5400000n, remaining_cents: 600000n, interest_cents: 13151n, applied_cents: 6000000n, new_upb_cents: 18000000n, track: "current (fewer than 31 days delinquent)", documents: ["adjuster's estimate", "signed contractor bid", "lien waivers at each release", "receipts for prepaid items above $40,000.00"], inspection_kind: "remote photo inspection (app-captured, GPS and timestamp verified)" };
const LD_PACKAGE_SOURCE = `{{#block "heading" page=1 y=0.05 pt=14 bold}}Your insurance claim proceeds — what happens next{{/block}}
{{#block "body" page=1 y=0.12 pt=11}}{{date notice_date}}. Loan number ending {{account_last4}}. We received insurance proceeds of {{money proceeds_cents}} for claim {{claim_number}} on {{property_address}}. Your loan is {{track}}, so we will release {{money initial_release_cents}} now and hold {{money held_cents}} in an interest-bearing custodial account, releasing it as repairs are completed and inspected; interest earned on held funds is paid to you. Please send: {{#each documents}}{{this}}; {{/each}}Amounts the adjuster designated for contents or living expenses are released to you within 2 business days. Checks payable to you and to us must be endorsed by you first; we endorse under our limited power of attorney.{{/block}}
${CONTACT}`;
const LD_PACKAGE_RULES: ContentRule[] = [R("proceeds", "B-5-01", "presence", "received insurance proceeds of \\$[\\d,]+\\.\\d{2} for claim", "proceeds and claim"), R("release-schedule", "9.7 rule 2", "presence", "release \\$[\\d,]+\\.\\d{2} now and hold \\$[\\d,]+\\.\\d{2}", "initial release and held amount"), R("interest", "9.7 rule 5 (interest always paid)", "presence", "interest earned on held funds is paid to you", "interest to the borrower"), R("documents", "9.7 rule 7", "presence", "Please send: .+;", "document list"), R("contents", "9.7 rule 4", "presence", "released to you within 2 business days", "contents/ALE release"), R("endorsement", "9.7 rule 6", "presence", "endorsed by you first", "endorsement instructions"), CONTACT_RULE];
const LD_RELEASE_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}{{date notice_date}}. Loan number ending {{account_last4}}. Following the {{inspection_kind}} on {{date inspection_on}} showing repairs {{pct_complete}}% complete, we are releasing {{money release_cents}} from your claim funds (cumulative {{money cumulative_cents}} of {{money proceeds_cents}}). {{money remaining_cents}} remains held and will be released at completion after a final check.{{/block}}
${CONTACT}`;
const LD_RELEASE_RULES: ContentRule[] = [R("inspection", "9.7 rule 2 (no release without the required inspection)", "presence", "Following the .* on .* showing repairs \\d+% complete", "inspection basis"), R("amounts", "9.7 rule 2", "presence", "releasing \\$[\\d,]+\\.\\d{2} from your claim funds \\(cumulative \\$[\\d,]+\\.\\d{2} of \\$[\\d,]+\\.\\d{2}\\)", "release and cumulative amounts"), R("within-formula", "9.7 guardrail", "data_equality", "within_formula", "release within the formula limit", { predicate: { "==": [{ var: "within_formula" }, true] } }), CONTACT_RULE];
const LD_FINAL_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}{{date notice_date}}. Loan number ending {{account_last4}}. Repairs on {{property_address}} are complete. We released the final {{money remaining_cents}} of your claim funds and {{money interest_cents}} of interest earned while the funds were held. Total proceeds disbursed: {{money proceeds_cents}}. Your claim {{claim_number}} is closed.{{/block}}
${CONTACT}`;
const LD_FINAL_RULES: ContentRule[] = [R("complete", "9.7 rule 2 (final inspection / final check)", "presence", "Repairs on .* are complete", "completion"), R("final-release", "9.7", "presence", "released the final \\$[\\d,]+\\.\\d{2}", "final release"), R("interest", "9.7 rule 5", "presence", "\\$[\\d,]+\\.\\d{2} of interest earned", "interest paid"), CONTACT_RULE];
const LD_UPB_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}{{date notice_date}}. Loan number ending {{account_last4}}. Because the property cannot be rebuilt ({{reason}}), we applied the insurance proceeds of {{money applied_cents}} to your unpaid principal balance on {{date applied_on}}. Your new principal balance is {{money new_upb_cents}}; your monthly payment does not change unless your loan is re-amortized at your request. {{#if payoff}}The proceeds paid your loan in full; a payoff confirmation follows.{{/if}}{{/block}}
${CONTACT}`;
const LD_UPB_RULES: ContentRule[] = [R("reason", "9.7 rule 1 (not_rebuildable)", "presence", "cannot be rebuilt \\(", "reason"), R("applied", "9.7 rule 1", "presence", "applied the insurance proceeds of \\$[\\d,]+\\.\\d{2} to your unpaid principal balance", "curtailment"), R("new-upb", "9.7", "presence", "new principal balance is \\$[\\d,]+\\.\\d{2}", "new balance"), CONTACT_RULE];
const LD_UNINSURED_SOURCE = `{{#block "body" page=1 y=0.1 pt=11}}{{date notice_date}}. Loan number ending {{account_last4}}. We learned that {{property_address}} was damaged on {{date loss_date}} by {{peril}} and that no insurance covers the loss. We have opened a case to help: we will inspect the damage, discuss a repair plan with you, tell you about disaster-relief assistance that may be available, and review whether a payment plan or other assistance fits your situation. Call {{servicer_phone}} to discuss.{{/block}}
${CONTACT}`;
const LD_UNINSURED_RULES: ContentRule[] = [R("uninsured", "B-5-02", "presence", "no insurance covers the loss", "uninsured loss"), R("steps", "9.7 rule 11", "presence", "inspect the damage, discuss a repair plan .* disaster-relief assistance .* payment plan", "damage assessment, repair plan, relief, workout evaluation"), CONTACT_RULE];

export const SECTION_09_VERSIONS: readonly VersionInput[] = [
  V("INS_DEFICIENCY_NOTICE", DEF_SOURCE(false), DEF_RULES(false), DEF_SAMPLE, "fnma.insurance.2026-08", "B-2-02"),
  V("INS_DEFICIENCY_NOTICE_BK", DEF_SOURCE(true), DEF_RULES(true), DEF_SAMPLE, "fnma.insurance.2026-08", "B-2-02 with the Section 14 overlay"),
  V("INS_ANNUAL_REMINDER", REMINDER_SOURCE, REMINDER_RULES, { ...BASE, fnma_consumer_url: "knowyouroptions.com/insurance", days_since_last: 365 }, "fnma.insurance.2026-08", "B-2-01"),
  V("INS_EOI_REQUEST", EOI_SOURCE, EOI_RULES, { ...BASE, policy_number: "HO-4471", expiration_date: "2026-10-01" }, "fnma.insurance.2026-08", "9.1 courtesy request"),
  V("INS_FPI_REMINDER_NOINFO_MS3B", MS3B_SOURCE, MS3B_RULES, MS3_SAMPLE, "regx.force_placed.2014", "Appendix MS-3(B)"),
  V("INS_FPI_REMINDER_INSUFF_MS3C", MS3C_SOURCE, MS3C_RULES, MS3_SAMPLE, "regx.force_placed.2014", "Appendix MS-3(C)"),
  V("INS_FPI_RENEWAL_MS3D", MS3D_SOURCE, MS3D_RULES, MS3D_SAMPLE, "regx.force_placed.2014", "Appendix MS-3(D)"),
  V("INS_FPI_CANCEL_REFUND_CONFIRM", CANCEL_SOURCE, CANCEL_RULES, CANCEL_SAMPLE, "regx.force_placed.2014", "§1024.37(g); 9.5 worked example"),
  V("INS_FLOOD_FPI_NOTICE_45", FLOOD45_SOURCE, FLOOD45_RULES, FLOOD_SAMPLE, "fdpa.4012a.2026", "42 U.S.C. §4012a(e); 9.6 rule 4"),
  V("INS_FLOOD_FPI_PLACED_NOTICE", FLOOD_PLACED_SOURCE, FLOOD_PLACED_RULES, { ...FLOOD_SAMPLE, notice_date: "2027-03-23" }, "fdpa.4012a.2026", "9.6 rule 5"),
  V("INS_FLOOD_MAP_CHANGE_NOTICE", FLOOD_MAP_SOURCE, FLOOD_MAP_RULES, { ...FLOOD_SAMPLE, coverage_required: true }, "fdpa.4012a.2026", "9.6 rule 7"),
  V("INS_FLOOD_REMOVED_NOTICE", FLOOD_REMOVED_SOURCE, FLOOD_REMOVED_RULES, { ...FLOOD_SAMPLE, notice_date: "2027-05-14", lpi_cancelled: true }, "fdpa.4012a.2026", "9.6 rule 7 (LOMA)"),
  V("INS_FLOOD_TERMINATION_REFUND_CONFIRM", FLOOD_TERM_SOURCE, FLOOD_TERM_RULES, { ...FLOOD_SAMPLE, notice_date: "2027-05-04", evidence_received_on: "2027-04-14" }, "fdpa.4012a.2026", "42 U.S.C. §4012a(e)(3); 9.6 worked timeline"),
  V("INS_LOSS_DRAFT_PACKAGE", LD_PACKAGE_SOURCE, LD_PACKAGE_RULES, LD_BASE, "fnma.b5_01.2026", "B-5-01; 9.7 worked example"),
  V("INS_LOSS_DRAFT_RELEASE_LETTER", LD_RELEASE_SOURCE, LD_RELEASE_RULES, { ...LD_BASE, inspection_on: "2027-01-20", within_formula: true }, "fnma.b5_01.2026", "9.7 rule 2"),
  V("INS_LOSS_DRAFT_FINAL_LETTER", LD_FINAL_SOURCE, LD_FINAL_RULES, LD_BASE, "fnma.b5_01.2026", "9.7 rules 2 and 5"),
  V("INS_LOSS_DRAFT_UPB_APPLICATION_NOTICE", LD_UPB_SOURCE, LD_UPB_RULES, { ...LD_BASE, reason: "the county denied the rebuilding permit", applied_on: "2027-02-01", payoff: false }, "fnma.b5_01.2026", "9.7 rule 1 (not rebuildable)"),
  V("INS_UNINSURED_LOSS_LETTER", LD_UNINSURED_SOURCE, LD_UNINSURED_RULES, { ...LD_BASE, loss_date: "2026-12-10", peril: "a tornado" }, "fnma.b5_02.2026", "B-5-02; 9.7 rule 11"),
];
