/**
 * Authored template versions for the §12 loss-mitigation notices: the CA
 * per-document acknowledgment, solicitation package, late-BRP plan letter,
 * incomplete-closed, supplemental-request, short-term-terms, (c)(3) complete
 * and duplicative letters and the NPRM RFA receipt (12.1); the streamlined
 * evaluation notice, Reg B / Form 182 adverse action and third-party delay
 * letters (12.2); the appeal acknowledgment and ineligible letters (12.3);
 * the forbearance plan family (12.4); the repayment plan family (12.5); the
 * deferral and disaster-deferral offers, completions and solicitations
 * (12.6–12.7); the Flex Mod solicitation, TPP offer/reminder/failed and
 * modification-completed letters (12.8); and the short-sale / Mortgage
 * Release decision family (12.9). Every borrower-facing sentence lives here;
 * the tools never emit free text.
 */
import type { ContentRule, VersionInput } from "../registry.ts";
import { V } from "./section01.ts";

const R = (rule_id: string, citation: string, kind: ContentRule["kind"], selector: string, message: string, extra: Partial<ContentRule> = {}): ContentRule => ({ rule_id, citation, kind, selector, severity: "block", message, ...extra });
const DATE_RULE = R("date", "notice date", "presence", "(January|February|March|April|May|June|July|August|September|October|November|December) \\d{1,2}, \\d{4}", "date of the notice");
const BASE = { notice_date: "2026-10-02", account_last4: "1234", property_address: "1 Test St, Testville TX 75001", servicer_address: "PO Box 1, Testville TX 75001", team_phone: "(800) 555-0199", team_name: "Loss Mitigation Team A", upload_url: "portal.example.com/upload", hud_phone: "(800) 569-4287", cfpb_counselor_url: "consumerfinance.gov/find-a-housing-counselor", appeal_how: "writing to PO Box 1, Testville TX 75001 or uploading to portal.example.com/upload" };
const HEAD = (title: string) => `{{#block "heading" page=1 y=0.05 pt=13 bold}}${title}{{/block}}\n{{#block "ref" page=1 y=0.1 pt=11}}{{date notice_date}}. Loan number ending {{account_last4}}. Property: {{property_address}}.{{/block}}`;
const CONTACT = `{{#block "contact" page=1 y=0.85 pt=11}}Questions? Your assigned team: {{team_name}}, {{team_phone}}, {{servicer_address}}. Free housing counseling: HUD {{hud_phone}} · {{cfpb_counselor_url}}.{{/block}}`;
const CONTACT_RULE = R("continuity", "12 CFR 1024.40(a)", "presence", "Your assigned team: ", "assigned-contact block (4.3)");
const HUD_RULE = R("hud", "12 CFR 1024.41; D2-2-05", "presence", "HUD \\(\\d{3}\\) \\d{3}-\\d{4}", "HUD counseling line");
const NO_ELIGIBILITY_PROMISE = R("no-promise", "12.x guardrail: no eligibility statement outside a determination", "absence", "(you (will )?qualify|guaranteed|we will approve)", "no promise of approval");
const ECOA = `{{#block "ecoa" page=1 y=0.78 pt=10}}The Federal Equal Credit Opportunity Act prohibits creditors from discriminating against credit applicants on the basis of race, color, religion, national origin, sex, marital status, age, or because all or part of the applicant's income derives from any public assistance program. The federal agency that administers compliance with this law concerning this creditor is the Consumer Financial Protection Bureau, 1700 G Street NW, Washington, DC 20552.{{/block}}`;
const ECOA_RULE = R("ecoa", "12 CFR 1002.9(b)(1)", "presence", "Equal Credit Opportunity Act prohibits creditors", "ECOA notice on adverse action");
const APPEAL = `{{#if appeal_available}}{{#block "appeal" page=1 y=0.6 pt=11}}You may appeal the denial of a loan modification option within {{appeal_days}} days, by {{date appeal_by}}, by {{appeal_how}}. Personnel not involved in the original decision will review your appeal and we will respond within 30 days.{{/block}}{{/if}}`;
const APPEAL_RULE = R("appeal-when-available", "12 CFR 1024.41(d)(1)(iii), (h)", "conditional", "appeal_available", "appeal rights when available", { when: { "==": [{ var: "appeal_available" }, true] }, predicate: { present: "appeal_by" } });
const SOLICIT_BODY = `{{#block "options" page=1 y=0.3 pt=11}}If you are having trouble making your mortgage payments, help may be available. Options may include a repayment plan, a payment deferral, forbearance, a loan modification (Flex Modification), a short sale or a Mortgage Release (deed-in-lieu). Not all borrowers qualify.{{/block}}
{{#block "apply" page=1 y=0.5 pt=11}}To be considered, complete the enclosed Mortgage Assistance Application (Form 710) and return it with the documents listed, or upload at {{upload_url}}.{{/block}}`;
const SOLICIT_RULES = [DATE_RULE, CONTACT_RULE, HUD_RULE, R("form-710", "D2-2-04; F-1-19", "presence", "Mortgage Assistance Application \\(Form 710\\)", "Form 710 enclosed"), R("qualifier", "D2-2-04", "presence", "Not all borrowers qualify", "no promise of eligibility"), NO_ELIGIBILITY_PROMISE];

// ------------------------------------------------------------------ 12.1
const CA_ACK = `${HEAD("We received your documents")}
{{#block "body" page=1 y=0.2 pt=11}}On {{date received_on}} we received: {{#each documents}}{{this}}; {{/each}}Under California Civil Code §2924.10 we are acknowledging each submission within five business days. {{#if missing}}To complete your application we still need: {{#each missing}}{{this}}; {{/each}}please send these by {{date respond_by}}.{{/if}}{{#if complete}}Your application is complete as of {{date received_on}}.{{/if}} We will not record a notice of default or notice of sale, or conduct a sale, while a complete application is pending (Cal. Civ. Code §2923.6(c)).{{/block}}
${CONTACT}`;
const CA_ACK_RULES = [DATE_RULE, CONTACT_RULE, R("received", "Cal. Civ. Code §2924.10(a)(1)", "presence", "we received: ", "documents received listed"), R("2924.10", "Cal. Civ. Code §2924.10", "presence", "California Civil Code §2924.10", "statutory basis"), R("2923.6c", "Cal. Civ. Code §2923.6(c)", "presence", "will not record a notice of default", "dual-tracking statement"), R("missing-when-incomplete", "Cal. Civ. Code §2924.10(a)(3)", "conditional", "missing", "missing items with a respond-by date", { when: { "!=": [{ var: "complete" }, true] }, predicate: { present: "respond_by" } })];
const CA_ACK_SAMPLE = { ...BASE, received_on: "2026-10-01", documents: ["two pay stubs", "signed Form 710"], missing: ["most recent bank statement"], respond_by: "2026-10-31", complete: false };

const SOLICIT = `${HEAD("Mortgage assistance may be available")}
${SOLICIT_BODY}
${CONTACT}`;
const SOLICIT_SAMPLE = { ...BASE };

const LATE_BRP = `${HEAD("Your request for a repayment plan or forbearance")}
{{#block "body" page=1 y=0.2 pt=11}}You asked for help on {{date request_on}}. Because your loan is more than 90 days past due, Fannie Mae's guidelines require a complete Borrower Response Package before we can offer a repayment plan or a longer forbearance. Please return the Mortgage Assistance Application (Form 710) and the documents listed by {{date respond_by}}, or upload at {{upload_url}}. If you cannot, call {{team_phone}} to discuss a short forbearance while you gather them. Not all borrowers qualify.{{/block}}
${CONTACT}`;
const LATE_BRP_RULES = [DATE_RULE, CONTACT_RULE, HUD_RULE, R("brp-required", "D2-2-05; D2-3.2-02", "presence", "complete Borrower Response Package", "BRP requirement stated"), R("form-710", "F-1-19", "presence", "Mortgage Assistance Application \\(Form 710\\)", "Form 710"), NO_ELIGIBILITY_PROMISE];
const LATE_BRP_SAMPLE = { ...BASE, request_on: "2026-10-01", respond_by: "2026-10-31" };

const INCOMPLETE_CLOSED = `${HEAD("Your loss mitigation application is closed")}
{{#block "body" page=1 y=0.2 pt=11}}On {{date ack_on}} we told you which documents we needed by {{date reasonable_date}}. We did not receive: {{#each missing}}{{this}}; {{/each}}so we are unable to evaluate your application and it is now closed as incomplete. You may apply again at any time; call {{team_phone}} or upload at {{upload_url}}. Not all borrowers qualify.{{/block}}
${CONTACT}`;
const INCOMPLETE_CLOSED_RULES = [DATE_RULE, CONTACT_RULE, R("missing", "12 CFR 1024.41(b)(2)(i)(B); comment 41(c)(2)(ii)-1", "presence", "We did not receive: ", "missing items named"), R("reapply", "12 CFR 1024.41(i)", "presence", "You may apply again", "re-application invited"), R("reviewer", "12.1 rule: closure is an adverse determination approved by lossmit_reviewer", "data_equality", "reviewer_approval_id", "reviewer approval recorded", { predicate: { present: "reviewer_approval_id" } })];
const INCOMPLETE_CLOSED_SAMPLE = { ...BASE, ack_on: "2026-10-02", reasonable_date: "2026-11-01", missing: ["most recent bank statement"], reviewer_approval_id: "rev-1" };

const SUPPLEMENTAL = `${HEAD("We need one more item to complete your application")}
{{#block "body" page=1 y=0.2 pt=11}}Your application received {{date facial_on}} contained every item on our list, and we are treating it as complete as of that date. In reviewing it we found that {{item}} {{problem}}. Please send {{replacement}} by {{date respond_by}} (at least 7 days from this letter). Your protections under the federal servicing rules continue while we wait, and no foreclosure filing will be made before that date.{{/block}}
${CONTACT}`;
const SUPPLEMENTAL_RULES = [DATE_RULE, CONTACT_RULE, R("deemed-complete", "12 CFR 1024.41(c)(2)(iv)", "presence", "treating it as complete as of that date", "deemed-complete statement"), R("respond-by", "12 CFR 1024.41(c)(2)(iv)", "presence", "at least 7 days from this letter", "≥7-day request"), R("respond-by-date", "12 CFR 1024.41(c)(2)(iv)", "data_range", "respond_by", "respond_by is a date", { predicate: { matches: ["respond_by", "^\\d{4}-\\d{2}-\\d{2}$"] } })];
const SUPPLEMENTAL_SAMPLE = { ...BASE, facial_on: "2026-10-01", item: "the pay stub dated 2026-06-12", problem: "is more than 90 days old", replacement: "a pay stub from the last 30 days", respond_by: "2026-10-09" };

const SHORTTERM = `${HEAD("Your short-term {{plan_kind}} — terms")}
{{#block "body" page=1 y=0.2 pt=11}}Based on the information you gave us we are offering a {{plan_kind}} of {{duration_months}} months starting {{date start_on}}: {{#each terms}}{{this}}; {{/each}}This offer is based on an evaluation of an incomplete application. You may still complete your application by {{date reasonable_date}} to be evaluated for all options, and we will continue to work with you to complete it. Accepting this plan does not stop you from doing so.{{/block}}
${CONTACT}`;
const SHORTTERM_RULES = [DATE_RULE, CONTACT_RULE, R("terms", "12 CFR 1024.41(c)(2)(iii)", "presence", "of \\d+ months starting", "specific plan terms"), R("incomplete-basis", "12 CFR 1024.41(c)(2)(iii)", "presence", "based on an evaluation of an incomplete application", "incomplete-application basis"), R("may-complete", "12 CFR 1024.41(c)(2)(iii)", "presence", "You may still complete your application", "right to complete"), R("months-le-6", "12 CFR 1024.41(c)(2)(iii): short-term = ≤6 months", "data_range", "duration_months", "duration ≤6 months", { predicate: { "<=": [{ var: "duration_months" }, 6] } })];
const SHORTTERM_SAMPLE = { ...BASE, plan_kind: "repayment plan", duration_months: 6, start_on: "2026-11-01", terms: ["$2,900.25 each month", "your loan is current after the sixth payment"], reasonable_date: "2026-11-15" };

const C3_COMPLETE = `${HEAD("Your loss mitigation application is complete")}
{{#block "body" page=1 y=0.2 pt=11}}We received the last item on {{date complete_on}} and your application is complete as of that date. We will evaluate you for all available options and send you our written decision within 30 days, by {{date decision_by}}. While we evaluate, no foreclosure sale will be conducted and no first foreclosure filing will be made.{{/block}}
${CONTACT}`;
const C3_RULES = [DATE_RULE, CONTACT_RULE, R("complete-date", "12 CFR 1024.41(c)(3)(i)", "presence", "complete as of that date", "date of completion"), R("30-days", "12 CFR 1024.41(c)(1)(i)", "presence", "within 30 days", "evaluation timing"), R("no-sale", "12 CFR 1024.41(g)", "presence", "no foreclosure sale will be conducted", "protection statement")];
const C3_SAMPLE = { ...BASE, complete_on: "2026-10-07", decision_by: "2026-11-06" };

const DUPLICATIVE = `${HEAD("About your new loss mitigation application")}
{{#block "body" page=1 y=0.2 pt=11}}We received your application on {{date received_on}}. We previously evaluated a complete application from you on {{date prior_complete_on}} and you have not brought the loan current since then. Under the federal servicing rules we are not required to evaluate this application again, and we will not. If your circumstances have changed, call {{team_phone}}; we will consider new information under our own policy. Not all borrowers qualify.{{/block}}
${CONTACT}`;
const DUPLICATIVE_RULES = [DATE_RULE, CONTACT_RULE, R("prior", "12 CFR 1024.41(i)", "presence", "previously evaluated a complete application", "prior complete application named"), R("not-current", "12 CFR 1024.41(i)", "presence", "not brought the loan current since", "not-current statement"), R("reviewer", "12.1 rule: duplicative determination approved by lossmit_reviewer", "data_equality", "reviewer_approval_id", "reviewer approval recorded", { predicate: { present: "reviewer_approval_id" } })];
const DUPLICATIVE_SAMPLE = { ...BASE, received_on: "2026-10-01", prior_complete_on: "2026-03-10", reviewer_approval_id: "rev-2" };

const NPRM_RFA = `${HEAD("We received your request for assistance")}
{{#block "body" page=1 y=0.2 pt=11}}On {{date received_on}} you asked us about help with your mortgage. We have opened a review of your request. While we review it we will not make the first foreclosure filing, move for a judgment or order of sale, or conduct a sale. To help us, please send: {{#each requested}}{{this}}; {{/each}}or call {{team_phone}}. Not all borrowers qualify.{{/block}}
${CONTACT}`;
const NPRM_RFA_RULES = [DATE_RULE, CONTACT_RULE, R("review-opened", "2024 NPRM proposed §1024.41(f)–(g) (request for assistance)", "presence", "We have opened a review of your request", "review cycle opened"), R("protections", "2024 NPRM proposed §1024.41(f)(2)", "presence", "will not make the first foreclosure filing", "procedural safeguards"), R("regime", "12.1 rule: NPRM template only under regime 2024nprm", "data_equality", "regime", "regime is 2024nprm", { predicate: { "==": [{ var: "regime" }, "2024nprm"] } })];
const NPRM_RFA_SAMPLE = { ...BASE, received_on: "2026-10-01", requested: ["Form 710", "two months of pay stubs"], regime: "2024nprm" };

// ------------------------------------------------------------------ 12.2
const EVAL_STREAMLINED = `${HEAD("You are eligible for a Flex Modification trial period plan")}
{{#block "body" page=1 y=0.2 pt=11}}Based on our records, and without an application from you, we are offering a trial period plan under Fannie Mae's Flex Modification: three payments of {{money trial_payment_cents}} due {{#each due_dates}}{{this}}; {{/each}}Make the first payment by {{date first_due}} to accept. If all payments are made on time your loan will be permanently modified effective {{date effective}}. {{#if open_incomplete_application}}You also have a loss mitigation application on file that is incomplete; we still need {{#each missing}}{{this}}; {{/each}}and you may complete it by {{date reasonable_date}} to be evaluated for all options. This offer does not close that application.{{/if}}{{/block}}
${CONTACT}`;
const EVAL_STREAMLINED_RULES = [DATE_RULE, CONTACT_RULE, R("trial-terms", "D2-3.2-06; Evaluation Notice", "presence", "three payments of \\$[\\d,]+\\.\\d{2}", "trial payment amount"), R("first-due", "D2-3.2-06", "presence", "Make the first payment by ", "acceptance by first payment"), R("incomplete-disclosure", "12 CFR 1024.41(c)(2)(ii); 12.2-T13", "conditional", "open_incomplete_application", "incomplete-application disclosures when an application is open", { when: { "==": [{ var: "open_incomplete_application" }, true] }, predicate: { present: "reasonable_date" } }), NO_ELIGIBILITY_PROMISE];
const EVAL_STREAMLINED_SAMPLE = { ...BASE, trial_payment_cents: 181_513n, due_dates: ["2026-12-01", "2027-01-01", "2027-02-01"], first_due: "2026-12-01", effective: "2027-03-01", open_incomplete_application: true, missing: ["most recent bank statement"], reasonable_date: "2026-11-30" };

const REGB = `${HEAD("Notice of action taken on your request for mortgage assistance")}
{{#block "body" page=1 y=0.2 pt=11}}Thank you for your request received {{date received_on}}. After careful consideration we are unable to offer you {{option}}. Reason: {{principal_reason}}. This decision was made under {{investor}}'s guidelines. {{#if smdu_case_id}}(Fannie Mae case {{smdu_case_id}}){{/if}} Other options we considered: {{#each other_options}}{{name}}: {{determination}}; {{/each}}{{/block}}
${APPEAL}
${ECOA}
${CONTACT}`;
const REGB_RULES = [DATE_RULE, CONTACT_RULE, ECOA_RULE, APPEAL_RULE, R("principal-reason", "12 CFR 1002.9(a)(2), (b)(2); Form 182", "presence", "Reason: ", "principal reason stated"), R("investor", "D2-2-05; 12.2-T3", "presence", "under Fannie Mae's guidelines", "investor named"), R("other-options", "12 CFR 1024.41(d)", "presence", "Other options we considered: ", "other options determinations"), R("reviewer", "12.2 guardrail: no denial notice without reviewer approval", "data_equality", "reviewer_approval_id", "reviewer approval recorded", { predicate: { present: "reviewer_approval_id" } })];
const REGB_SAMPLE = { ...BASE, received_on: "2026-10-20", option: "a Flex Modification", principal_reason: "the loan is current and the payment is not in imminent default under Fannie Mae's criteria", investor: "Fannie Mae", smdu_case_id: "SMDU-1", other_options: [{ name: "repayment plan", determination: "not needed — loan current" }], appeal_available: false, reviewer_approval_id: "rev-3" };

const THIRD_PARTY = `${HEAD("Status of your loss mitigation application")}
{{#block "body" page=1 y=0.2 pt=11}}Your complete application was received {{date complete_on}}. We have finished evaluating you for: {{#each determined}}{{name}}: {{determination}}; {{/each}}We have not yet received {{pending_item}} from {{third_party}}, which we requested on {{date requested_on}} and have followed up on {{followups}} times. We cannot complete the {{pending_option}} determination until it arrives; we will send that decision within 5 days of receiving it. Your protections under the federal servicing rules continue.{{/block}}
${APPEAL}
${CONTACT}`;
const THIRD_PARTY_RULES = [DATE_RULE, CONTACT_RULE, APPEAL_RULE, R("determined", "12 CFR 1024.41(c)(4)(ii)(B)", "presence", "We have finished evaluating you for: ", "determinable results included"), R("pending", "12 CFR 1024.41(c)(4)(ii)(B)", "presence", "We have not yet received ", "outstanding third-party item named"), R("diligence", "12 CFR 1024.41(c)(4)(i)", "presence", "followed up on \\d+ times", "diligence described"), R("5-days", "12 CFR 1024.41(c)(4)(ii)(C)", "presence", "within 5 days of receiving it", "post-receipt timing")];
const THIRD_PARTY_SAMPLE = { ...BASE, complete_on: "2026-10-01", determined: [{ name: "repayment plan", determination: "not eligible — payment exceeds 150% cap" }], pending_item: "the broker price opinion", third_party: "the valuation vendor", requested_on: "2026-10-02", followups: 3, pending_option: "short sale", appeal_available: true, appeal_days: 14, appeal_by: "2026-11-14" };

// ------------------------------------------------------------------ 12.3
const APPEAL_ACK = `${HEAD("We received your appeal")}
{{#block "body" page=1 y=0.2 pt=11}}We received your appeal of our {{date denial_on}} decision on {{date received_on}}. Personnel who took no part in the original decision will review it, and we will tell you in writing within 30 days, by {{date decision_by}}, whether we will offer you a loan modification. {{#if original_offer_pending}}The offer we made on {{date offer_on}} stays open until 14 days after our appeal decision.{{/if}} No foreclosure sale will be held while your appeal is pending.{{/block}}
${CONTACT}`;
const APPEAL_ACK_RULES = [DATE_RULE, CONTACT_RULE, R("independent", "12 CFR 1024.41(h)(3)", "presence", "took no part in the original decision", "independent review"), R("30-days", "12 CFR 1024.41(h)(4)", "presence", "within 30 days", "decision timing"), R("offer-extended", "12 CFR 1024.41(e)(2)(iii)", "conditional", "original_offer_pending", "pending offer extended", { when: { "==": [{ var: "original_offer_pending" }, true] }, predicate: { present: "offer_on" } })];
const APPEAL_ACK_SAMPLE = { ...BASE, denial_on: "2026-10-20", received_on: "2026-10-30", decision_by: "2026-11-29", original_offer_pending: true, offer_on: "2026-10-20" };

const APPEAL_INELIGIBLE = `${HEAD("About your appeal")}
{{#block "body" page=1 y=0.2 pt=11}}We received your appeal on {{date received_on}}. Our decision letter of {{date denial_on}} explained that an appeal had to be received within {{appeal_days}} days, by {{date appeal_by}}. Because your appeal arrived after that date it is not eligible for the formal appeal process. {{#if new_information}}We are reviewing the new information you sent ({{#each new_information}}{{this}}; {{/each}}) under our own policy and will write to you about it.{{/if}} You may apply again at any time.{{/block}}
${CONTACT}`;
const APPEAL_INELIGIBLE_RULES = [DATE_RULE, CONTACT_RULE, R("window", "12 CFR 1024.41(h)(2)", "presence", "had to be received within \\d+ days", "window stated"), R("late", "12 CFR 1024.41(h)(2)", "presence", "arrived after that date", "lateness stated"), R("new-info", "12.3-T3: new information reviewed as such", "conditional", "new_information", "new information acknowledged", { when: { present: "new_information" }, predicate: { present: "new_information" } }), R("reviewer", "12.3 guardrail: no notice before the human decision", "data_equality", "reviewer_approval_id", "reviewer decision recorded", { predicate: { present: "reviewer_approval_id" } })];
const APPEAL_INELIGIBLE_SAMPLE = { ...BASE, received_on: "2026-11-20", denial_on: "2026-10-20", appeal_days: 14, appeal_by: "2026-11-03", new_information: ["two new pay stubs"], reviewer_approval_id: "rev-4" };

// ------------------------------------------------------------------ 12.4 forbearance
const FORB_PLAN = `${HEAD("Your forbearance plan")}
{{#block "body" page=1 y=0.2 pt=11}}We have approved a forbearance plan of {{duration_months}} months from {{date start_on}} through {{date end_on}}. During the plan your monthly payment is {{money reduced_payment_cents}}{{#if zero_payment}} (payments are suspended){{/if}}. Interest continues to accrue and the suspended amounts remain due at the end of the plan; no late charges will be assessed while you keep the plan. We will contact you before {{date end_on}} to discuss how to resolve the amounts that were suspended, which may include a repayment plan, a payment deferral or a loan modification. Not all borrowers qualify. This plan does not waive Fannie Mae's or our rights under your note and mortgage.{{/block}}
${CONTACT}`;
const FORB_PLAN_RULES = [DATE_RULE, CONTACT_RULE, R("term", "D2-3.2-01", "presence", "forbearance plan of \\d+ months", "term stated"), R("payment", "D2-3.2-01", "presence", "monthly payment is \\$[\\d,]+\\.\\d{2}", "reduced payment amount"), R("accrual", "D2-3.2-01", "presence", "Interest continues to accrue", "accrual disclosed"), R("no-late-charges", "D2-3.2-01", "presence", "no late charges will be assessed", "late-charge suppression"), R("term-le-12", "LL-2026-01: cumulative ≤12 months", "data_range", "duration_months", "≤12 months", { predicate: { "<=": [{ var: "duration_months" }, 12] } })];
const FORB_PLAN_SAMPLE = { ...BASE, duration_months: 3, start_on: "2026-10-01", end_on: "2026-12-31", reduced_payment_cents: 0n, zero_payment: true };

const FORB_EXTENSION = `${HEAD("Your forbearance plan has been extended")}
{{#block "body" page=1 y=0.2 pt=11}}We have extended your forbearance plan by {{extension_months}} months, through {{date new_end_on}}. Your total forbearance is now {{cumulative_months}} months. {{#if fnma_exception_id}}Fannie Mae approved this extension (reference {{fnma_exception_id}}).{{/if}} The terms of your original plan otherwise continue. We will contact you before {{date new_end_on}} about resolving the suspended payments.{{/block}}
${CONTACT}`;
const FORB_EXTENSION_RULES = [DATE_RULE, CONTACT_RULE, R("extension", "D2-3.2-01", "presence", "extended your forbearance plan by \\d+ months", "extension stated"), R("cumulative", "LL-2026-01", "presence", "total forbearance is now \\d+ months", "cumulative months stated"), R("exception-when-over-12", "LL-2026-01: >12 cumulative needs Fannie Mae exception", "conditional", "cumulative_months", "Fannie Mae exception id when cumulative >12", { when: { ">": [{ var: "cumulative_months" }, 12] }, predicate: { present: "fnma_exception_id" } })];
const FORB_EXTENSION_SAMPLE = { ...BASE, extension_months: 3, new_end_on: "2027-03-31", cumulative_months: 6 };

const FORB_EXPIRY = `${HEAD("Your forbearance plan ends soon — your options")}
{{#block "body" page=1 y=0.2 pt=11}}Your forbearance plan ends {{date end_on}}. The suspended amount is {{money suspended_cents}}. Please call {{team_phone}} before that date so we can talk about your situation. Depending on your circumstances the options may include reinstatement, a repayment plan, a payment deferral (moving the suspended amount to the end of your loan without interest), or a Flex Modification. Not all borrowers qualify. If we do not hear from you, we may still send you an offer based on our records.{{/block}}
${CONTACT}`;
const FORB_EXPIRY_RULES = [DATE_RULE, CONTACT_RULE, HUD_RULE, R("end", "D2-3.2-01: contact ≥30 days before expiry", "presence", "forbearance plan ends ", "end date"), R("suspended", "D2-3.2-01", "presence", "suspended amount is \\$[\\d,]+\\.\\d{2}", "suspended amount"), R("options", "D2-3.2-01; hierarchy", "presence", "reinstatement, a repayment plan, a payment deferral", "hierarchy options listed"), NO_ELIGIBILITY_PROMISE];
const FORB_EXPIRY_SAMPLE = { ...BASE, notice_date: "2026-12-01", end_on: "2026-12-31", suspended_cents: 630_000n };

const FORB_TERMINATION = `${HEAD("Your forbearance plan has ended")}
{{#block "body" page=1 y=0.2 pt=11}}{{#if failed}}We did not receive the reduced payment of {{money reduced_payment_cents}} due by {{date missed_by}}, and after reviewing your circumstances your forbearance plan ended on {{date terminated_on}}. Late charges may be assessed on payments due after that date only.{{/if}}{{#if expired}}Your forbearance plan ended as scheduled on {{date terminated_on}}.{{/if}} The suspended amount of {{money suspended_cents}} is now due. Please call {{team_phone}}: a repayment plan, payment deferral or loan modification may still be available. Not all borrowers qualify.{{/block}}
${CONTACT}`;
const FORB_TERMINATION_RULES = [DATE_RULE, CONTACT_RULE, R("ended", "D2-3.2-01", "presence", "forbearance plan ended", "termination stated"), R("suspended", "D2-3.2-01", "presence", "suspended amount of \\$[\\d,]+\\.\\d{2} is now due", "amount due"), R("late-charges-from-default", "12.4-T7: late charges from the default date only", "conditional", "failed", "late-charge scope when failed", { when: { "==": [{ var: "failed" }, true] }, predicate: { present: "mitigating_check_id" } }), R("reviewer", "12.4 guardrail: mitigating-circumstances check logged before termination", "conditional", "failed", "mitigating check id", { when: { "==": [{ var: "failed" }, true] }, predicate: { present: "reviewer_approval_id" } })];
const FORB_TERMINATION_SAMPLE = { ...BASE, failed: true, expired: false, reduced_payment_cents: 100_000n, missed_by: "2026-11-30", terminated_on: "2026-12-01", suspended_cents: 420_000n, mitigating_check_id: "mit-1", reviewer_approval_id: "rev-5" };

// ------------------------------------------------------------------ 12.5 repayment
const REPAY_PLAN = `${HEAD("Your repayment plan")}
{{#block "body" page=1 y=0.2 pt=11}}We have approved a repayment plan of {{duration_months}} months starting {{date start_on}}. Each month you will pay your regular payment of {{money contractual_cents}} plus {{money installment_cents}}, a total of {{money total_cents}} ({{pct_of_contractual}}% of your regular payment), by the last day of the month. The past-due amount of {{money arrears_cents}} will be paid in full with the payment due {{date cure_on}}. No late charges will be assessed while you keep the plan; if you complete it, late charges from the plan period are waived. If a payment is missed the plan ends and the remaining amount becomes due. {{#if regx_short_term}}This offer is based on an evaluation of an incomplete application; you may still complete your application to be evaluated for all options.{{/if}}{{/block}}
${CONTACT}`;
const REPAY_PLAN_RULES = [DATE_RULE, CONTACT_RULE, R("term", "D2-3.2-02", "presence", "repayment plan of \\d+ months", "term"), R("amounts", "D2-3.2-02", "presence", "a total of \\$[\\d,]+\\.\\d{2} \\(\\d+\\.\\d+% of your regular payment\\)", "expected total and percentage"), R("cap-150", "D2-3.2-02: expected total ≤150% of contractual", "data_range", "pct_of_contractual", "≤150%", { predicate: { "<=": [{ var: "pct_of_contractual" }, 150] } }), R("term-le-12", "D2-3.2-02: ≤12 months unless Fannie Mae approval", "data_range", "duration_months", "≤12 months or approval id", { predicate: { or: [{ "<=": [{ var: "duration_months" }, 12] }, { present: "fnma_approval_id" }] } }), R("late-charges", "D2-3.2-02", "presence", "late charges from the plan period are waived", "late-charge treatment"), R("incomplete-basis", "12 CFR 1024.41(c)(2)(iii)", "conditional", "regx_short_term", "incomplete-application basis on short-term plans", { when: { "==": [{ var: "regx_short_term" }, true] }, predicate: { "==": [{ var: "regx_short_term" }, true] } })];
const REPAY_PLAN_SAMPLE = { ...BASE, duration_months: 8, start_on: "2026-11-01", contractual_cents: 210_000n, installment_cents: 80_325n, total_cents: 290_325n, pct_of_contractual: "138.25", arrears_cents: 642_600n, cure_on: "2027-06-30", regx_short_term: false };

const REPAY_COMPLETED = `${HEAD("You have completed your repayment plan")}
{{#block "body" page=1 y=0.2 pt=11}}Congratulations — with your payment received {{date last_payment_on}} you completed your repayment plan and your loan is current. Late charges of {{money waived_cents}} assessed during the plan have been waived. Your regular payment of {{money contractual_cents}} is next due {{date next_due}}.{{/block}}
${CONTACT}`;
const REPAY_COMPLETED_RULES = [DATE_RULE, CONTACT_RULE, R("current", "D2-3.2-02", "presence", "your loan is current", "current status"), R("waived", "D2-3.2-02 (reason D2-3.2-02)", "presence", "Late charges of \\$[\\d,]+\\.\\d{2} .* have been waived", "waiver stated")];
const REPAY_COMPLETED_SAMPLE = { ...BASE, last_payment_on: "2027-06-28", waived_cents: 50_400n, contractual_cents: 210_000n, next_due: "2027-07-01" };

const REPAY_FAILED = `${HEAD("Your repayment plan has ended")}
{{#block "body" page=1 y=0.2 pt=11}}We did not receive the plan payment of {{money total_cents}} due by {{date missed_by}}, so your repayment plan ended on {{date ended_on}}. The remaining past-due amount of {{money remaining_cents}} is now due. Late charges may be assessed on payments due from {{date late_charges_from}} forward; none will be charged for the months you kept the plan. Please call {{team_phone}} — a payment deferral or loan modification may be available. Not all borrowers qualify.{{/block}}
${CONTACT}`;
const REPAY_FAILED_RULES = [DATE_RULE, CONTACT_RULE, R("ended", "D2-3.2-02", "presence", "repayment plan ended on ", "termination"), R("remaining", "D2-3.2-02", "presence", "remaining past-due amount of \\$[\\d,]+\\.\\d{2}", "remaining amount"), R("late-charges-forward", "12.5-T4: charges accrue from the failed month only", "presence", "none will be charged for the months you kept the plan", "late-charge scope"), R("reviewer", "12.5: failure is an adverse determination", "data_equality", "reviewer_approval_id", "reviewer approval recorded", { predicate: { present: "reviewer_approval_id" } })];
const REPAY_FAILED_SAMPLE = { ...BASE, total_cents: 290_325n, missed_by: "2027-03-31", ended_on: "2027-04-01", remaining_cents: 321_300n, late_charges_from: "2027-04-01", reviewer_approval_id: "rev-6" };

// ------------------------------------------------------------------ 12.6 deferral
const DEFERRAL_OFFER = `${HEAD("You are approved for a payment deferral")}
{{#block "body" page=1 y=0.2 pt=11}}{{#if complete_application}}We have completed our evaluation of your complete loss mitigation application received {{date complete_on}}.{{/if}} We are offering a payment deferral: {{months_deferred}} past-due payments totaling {{money deferred_cents}} (principal and interest{{#if advances_cents}} plus {{money advances_cents}} we advanced for taxes or insurance{{/if}}) will be moved to the end of your loan as a non-interest-bearing balance, due when you pay off, sell or refinance. Late charges of {{money late_charges_waived_cents}} are waived. Your loan will be current, and your new monthly payment of {{money new_payment_cents}} is due {{date first_due}}. {{#if contractual_payment_required}}To accept, make your regular payment of {{money contractual_cents}} by {{date accept_by}}.{{/if}}{{#if complete_application}}To accept, {{acceptance_steps}} by {{date accept_by}} (14 days). If you do not, we will treat the offer as rejected.{{/if}} Other options we considered: {{#each other_options}}{{name}}: {{determination}}; {{/each}}{{/block}}
${APPEAL}
${CONTACT}`;
const DEFERRAL_OFFER_RULES = [DATE_RULE, CONTACT_RULE, APPEAL_RULE, R("terms", "D2-3.2-04", "presence", "\\d+ past-due payments totaling \\$[\\d,]+\\.\\d{2}", "deferred amount"), R("nib", "D2-3.2-04", "presence", "non-interest-bearing balance", "NIB explained"), R("late-charges", "D2-3.2-04", "presence", "Late charges of \\$[\\d,]+\\.\\d{2} are waived", "late charges waived, not deferred"), R("c1-content", "12 CFR 1024.41(c)(1)(ii), (e)(1)", "conditional", "complete_application", "(c)(1) content and 14-day window on a complete application", { when: { "==": [{ var: "complete_application" }, true] }, predicate: { present: "accept_by" } }), R("months-le-12", "D2-3.2-04: cumulative ≤12", "data_range", "months_deferred", "≤12 months", { predicate: { "<=": [{ var: "months_deferred" }, 12] } })];
const DEFERRAL_OFFER_SAMPLE = { ...BASE, complete_application: true, complete_on: "2026-09-15", months_deferred: 4, deferred_cents: 737_068n, advances_cents: 105_000n, late_charges_waived_cents: 25_200n, new_payment_cents: 213_117n, first_due: "2026-10-01", contractual_payment_required: false, contractual_cents: 210_017n, acceptance_steps: "sign and return the enclosed agreement or call us", accept_by: "2026-10-16", other_options: [{ name: "repayment plan", determination: "payment deferral ranks first under the hierarchy" }], appeal_available: false };

const DEFERRAL_COMPLETED = `${HEAD("Your payment deferral is complete")}
{{#block "body" page=1 y=0.2 pt=11}}Your payment deferral is complete effective {{date effective}}. {{money deferred_cents}} is now a non-interest-bearing deferred balance on your loan; it does not accrue interest and is due when you pay off, sell or refinance. Your loan is current. Your monthly payment of {{money new_payment_cents}} is due {{date first_due}} and includes {{money shortage_monthly_cents}} per month for 60 months to repay an escrow shortage of {{money escrow_shortage_cents}}. {{#if recorded}}The agreement was recorded on {{date recorded_on}}.{{/if}}{{/block}}
${CONTACT}`;
const DEFERRAL_COMPLETED_RULES = [DATE_RULE, CONTACT_RULE, R("effective", "D2-3.2-04", "presence", "complete effective ", "effective date"), R("nib", "D2-3.2-04", "presence", "non-interest-bearing deferred balance", "NIB line"), R("shortage-excluded", "12.6 guardrail: escrow shortage is not in the NIB", "presence", "per month for 60 months to repay an escrow shortage", "60-month shortage spread"), R("payment", "D2-3.2-04", "presence", "monthly payment of \\$[\\d,]+\\.\\d{2} is due", "new payment")];
const DEFERRAL_COMPLETED_SAMPLE = { ...BASE, effective: "2026-10-01", deferred_cents: 737_068n, new_payment_cents: 213_117n, first_due: "2026-10-01", shortage_monthly_cents: 3_100n, escrow_shortage_cents: 186_000n, recorded: false };

const SOLICIT_POST_FORB = `${HEAD("Your forbearance has ended — a payment deferral is available")}
{{#block "body" page=1 y=0.2 pt=11}}Your forbearance plan ended {{date forbearance_end}} and we have not been able to reach you. Based on our records you are eligible for a payment deferral: {{months_deferred}} payments totaling {{money deferred_cents}} moved to the end of your loan without interest, and your loan brought current. To accept, {{#if contractual_payment_required}}make your regular payment of {{money contractual_cents}} and {{/if}}call {{team_phone}} or sign and return the enclosed agreement by {{date accept_by}}. If we do not hear from you we will evaluate you for a Flex Modification. Not all borrowers qualify.{{/block}}
${CONTACT}`;
const SOLICIT_POST_FORB_RULES = [DATE_RULE, CONTACT_RULE, HUD_RULE, R("forb-end", "D2-3.2-04: solicit within 15 days of forbearance expiry", "presence", "forbearance plan ended ", "trigger stated"), R("terms", "D2-3.2-04", "presence", "\\d+ payments totaling \\$[\\d,]+\\.\\d{2}", "deferral terms"), R("accept-by", "SM_DEFERRAL_SOLICIT_ACCEPT_WINDOW", "presence", "by [A-Z][a-z]+ \\d{1,2}, \\d{4}", "acceptance window"), NO_ELIGIBILITY_PROMISE];
const SOLICIT_POST_FORB_SAMPLE = { ...BASE, notice_date: "2027-01-10", forbearance_end: "2026-12-31", months_deferred: 4, deferred_cents: 632_068n, contractual_payment_required: false, contractual_cents: 210_017n, accept_by: "2027-01-31" };

const SOLICIT_POST_REPAY = SOLICIT_POST_FORB.replace("Your forbearance has ended — a payment deferral is available", "Your repayment plan has ended — a payment deferral is available").replace("Your forbearance plan ended {{date forbearance_end}}", "Your repayment plan ended {{date repayment_end}}");
const SOLICIT_POST_REPAY_RULES = SOLICIT_POST_FORB_RULES.map((r) => (r.rule_id === "forb-end" ? R("repay-end", "D2-3.2-04: solicit within 15 days of repayment failure", "presence", "repayment plan ended ", "trigger stated") : r));
const SOLICIT_POST_REPAY_SAMPLE = { ...SOLICIT_POST_FORB_SAMPLE, notice_date: "2026-12-10", repayment_end: "2026-11-30", accept_by: "2026-12-31" };

// ------------------------------------------------------------------ 12.7 disaster deferral
const DISASTER_OFFER = DEFERRAL_OFFER.replace("You are approved for a payment deferral", "You are approved for a disaster payment deferral").replace("We are offering a payment deferral:", "Because your property is in an area covered by a federal disaster declaration ({{disaster_event}}), we are offering a disaster payment deferral:");
const DISASTER_OFFER_RULES = [...DEFERRAL_OFFER_RULES, R("fema", "D2-3.2-05; 12.7 guardrail: FEMA basis from the registry", "presence", "federal disaster declaration \\(", "disaster event named"), R("event-id", "12.7 guardrail: registry match", "data_equality", "disaster_event_id", "disaster_event_id recorded", { predicate: { present: "disaster_event_id" } })];
const DISASTER_OFFER_SAMPLE = { ...DEFERRAL_OFFER_SAMPLE, complete_application: false, months_deferred: 9, deferred_cents: 1_652_153n, advances_cents: 230_000n, late_charges_waived_cents: 56_700n, new_payment_cents: 214_017n, disaster_event: "DR-4999-TX", disaster_event_id: "DR-4999-TX", appeal_available: false };
const SOLICIT_POST_DISASTER_FORB = SOLICIT_POST_FORB.replace("a payment deferral is available", "a disaster payment deferral is available").replace("you are eligible for a payment deferral:", "you are eligible for a disaster payment deferral ({{disaster_event}}):");
const SOLICIT_POST_DISASTER_FORB_RULES = [...SOLICIT_POST_FORB_RULES, R("fema", "D2-3.2-05", "presence", "disaster payment deferral \\(", "disaster event named")];
const SOLICIT_POST_DISASTER_FORB_SAMPLE = { ...SOLICIT_POST_FORB_SAMPLE, notice_date: "2026-12-10", forbearance_end: "2026-11-30", months_deferred: 9, deferred_cents: 1_652_153n, accept_by: "2026-12-31", disaster_event: "DR-4999-TX" };
const SOLICIT_POST_REPAY_DISASTER = SOLICIT_POST_REPAY.replace("a payment deferral is available", "a disaster payment deferral is available").replace("you are eligible for a payment deferral:", "you are eligible for a disaster payment deferral ({{disaster_event}}):");
const SOLICIT_POST_REPAY_DISASTER_RULES = [...SOLICIT_POST_REPAY_RULES, R("fema", "D2-3.2-05", "presence", "disaster payment deferral \\(", "disaster event named")];
const SOLICIT_POST_REPAY_DISASTER_SAMPLE = { ...SOLICIT_POST_REPAY_SAMPLE, disaster_event: "DR-4999-TX" };

// ------------------------------------------------------------------ 12.8 Flex Mod
const SOLICIT_STREAMLINED = `${HEAD("A Flex Modification trial period plan is available to you")}
{{#block "body" page=1 y=0.2 pt=11}}Your loan is {{days_delinquent}} days past due. Based on our records — without an application from you — you may be eligible for Fannie Mae's Flex Modification. Under a trial period plan you would make {{trial_count}} payments of {{money trial_payment_cents}}, the first due {{date first_due}}; if you make them on time your loan will be permanently modified with a new payment of about the same amount, effective {{date effective}}. To accept, make the first trial payment by {{date first_due}}. {{#if open_incomplete_application}}You also have a loss mitigation application on file that is incomplete; you may complete it by {{date reasonable_date}} to be evaluated for all options, and this offer does not close it.{{/if}} Not all borrowers qualify.{{/block}}
${CONTACT}`;
const SOLICIT_STREAMLINED_RULES = [DATE_RULE, CONTACT_RULE, HUD_RULE, R("window", "D2-3.2-06: solicit days 90–105 (or 60–75 step-rate)", "data_range", "days_delinquent", "day ≥60", { predicate: { ">=": [{ var: "days_delinquent" }, 60] } }), R("terms", "D2-3.2-06", "presence", "\\d payments of \\$[\\d,]+\\.\\d{2}", "trial terms from the waterfall"), R("no-sale-window", "12.8 guardrail: solicitation blocked near a sale", "data_equality", "sale_within_window", "no sale inside the proximity window", { predicate: { "!=": [{ var: "sale_within_window" }, true] } }), R("incomplete-disclosure", "12.2-T13", "conditional", "open_incomplete_application", "incomplete-application disclosures", { when: { "==": [{ var: "open_incomplete_application" }, true] }, predicate: { present: "reasonable_date" } }), NO_ELIGIBILITY_PROMISE];
const SOLICIT_STREAMLINED_SAMPLE = { ...BASE, notice_date: "2026-11-10", days_delinquent: 98, trial_count: 3, trial_payment_cents: 181_513n, first_due: "2026-12-01", effective: "2027-03-01", sale_within_window: false, open_incomplete_application: false };

const TPP_OFFER = `${HEAD("Trial period plan — Fannie Mae Flex Modification")}
{{#block "body" page=1 y=0.2 pt=11}}{{#if complete_application}}We have completed our evaluation of your complete loss mitigation application received {{date complete_on}}.{{/if}} You are approved for a trial period plan. Make {{trial_count}} trial payments of {{money trial_payment_cents}} (principal and interest {{money pi_cents}}, escrow {{money escrow_cents}}) due {{#each due_dates}}{{this}}; {{/each}}each by the last day of its month. To accept, make the first payment by {{date first_due}}{{#if complete_application}} (within 14 days of this notice){{/if}}. If you make every trial payment on time, your loan will be modified effective {{date effective}}: interest rate {{rate_pct}}%, term {{term_months}} months, interest-bearing balance {{money ib_upb_cents}}{{#if forborne_cents}}, deferred (non-interest-bearing) principal {{money forborne_cents}}{{/if}}, monthly principal and interest {{money pi_cents}}. Late charges will be waived at modification. No foreclosure sale will be held while you keep the plan. Other options we considered: {{#each other_options}}{{name}}: {{determination}}; {{/each}}{{/block}}
${APPEAL}
${CONTACT}`;
const TPP_OFFER_RULES = [DATE_RULE, CONTACT_RULE, APPEAL_RULE, R("trial", "D2-3.2-06; Evaluation Notice", "presence", "\\d trial payments of \\$[\\d,]+\\.\\d{2}", "trial amount"), R("mod-terms", "D2-3.2-06; 12.8 guardrail: terms equal the waterfall", "presence", "interest rate \\d+\\.\\d{3}%, term \\d+ months", "modification terms"), R("no-sale", "E-3.4-01; 12 CFR 1024.41(g)", "presence", "No foreclosure sale will be held while you keep the plan", "protection"), R("acceptance-window", "12 CFR 1024.41(e)(1)", "conditional", "complete_application", "14-day acceptance on a complete application", { when: { "==": [{ var: "complete_application" }, true] }, predicate: { present: "first_due" } }), R("waterfall-ref", "12.8 guardrail: terms in notices must equal the waterfall/SMDU output", "data_equality", "waterfall_run_id", "waterfall run recorded", { predicate: { present: "waterfall_run_id" } })];
const TPP_OFFER_SAMPLE = { ...BASE, notice_date: "2026-09-11", complete_application: true, complete_on: "2026-09-09", trial_count: 3, trial_payment_cents: 181_513n, pi_cents: 126_413n, escrow_cents: 55_100n, due_dates: ["2026-10-01", "2026-11-01", "2026-12-01"], first_due: "2026-10-01", effective: "2027-01-01", rate_pct: "6.500", term_months: 480, ib_upb_cents: 21_592_199n, forborne_cents: 3_548_332n, other_options: [{ name: "payment deferral", determination: "not eligible — 8 months delinquent" }], appeal_available: false, waterfall_run_id: "wf-1" };

const TPP_REMINDER = `${HEAD("Reminder: trial payment due")}
{{#block "body" page=1 y=0.2 pt=11}}Your trial payment {{payment_number}} of {{trial_count}}, {{money trial_payment_cents}}, is due {{date due_on}} and must be received by {{date last_day}}. Payments received so far: {{#each received}}{{this}}; {{/each}}Keep the plan and your loan will be modified effective {{date effective}}. Call {{team_phone}} if you cannot make the payment.{{/block}}
${CONTACT}`;
const TPP_REMINDER_RULES = [DATE_RULE, CONTACT_RULE, R("due", "D2-3.2-06: due by the last day of the month", "presence", "must be received by ", "month-end deadline"), R("amount", "D2-3.2-06", "presence", "\\$[\\d,]+\\.\\d{2}, is due", "trial amount")];
const TPP_REMINDER_SAMPLE = { ...BASE, notice_date: "2026-11-05", payment_number: 2, trial_count: 3, trial_payment_cents: 181_513n, due_on: "2026-11-01", last_day: "2026-11-30", received: ["2026-10-14 $1,815.13"], effective: "2027-01-01" };

const TPP_FAILED = `${HEAD("Your trial period plan has ended")}
{{#block "body" page=1 y=0.2 pt=11}}We did not receive trial payment {{payment_number}} of {{money trial_payment_cents}} by {{date last_day}}, so your trial period plan ended on {{date ended_on}} and the modification will not take effect. Fannie Mae's guidelines do not allow a new trial period plan within 12 months of {{date ended_on}}. Other options may still be available — a short sale or Mortgage Release, for example — and you may apply at any time; call {{team_phone}}. Not all borrowers qualify.{{/block}}
${CONTACT}`;
const TPP_FAILED_RULES = [DATE_RULE, CONTACT_RULE, HUD_RULE, R("ended", "D2-3.2-06", "presence", "trial period plan ended on ", "termination"), R("12-month", "D2-3.2-06; FNMA_D23206_NO_NEW_TRIAL_12M", "presence", "within 12 months of", "12-month bar disclosed"), R("reviewer", "12.8 guardrail: denials/failures require lossmit_reviewer", "data_equality", "reviewer_approval_id", "reviewer approval recorded", { predicate: { present: "reviewer_approval_id" } })];
const TPP_FAILED_SAMPLE = { ...BASE, notice_date: "2026-12-03", payment_number: 2, trial_payment_cents: 181_513n, last_day: "2026-11-30", ended_on: "2026-12-01", reviewer_approval_id: "rev-7" };

const MOD_COMPLETED = `${HEAD("Your loan has been modified")}
{{#block "body" page=1 y=0.2 pt=11}}Your Flex Modification is effective {{date effective}}. New terms: interest rate {{rate_pct}}%, maturity {{date maturity}}, interest-bearing balance {{money ib_upb_cents}}{{#if forborne_cents}}, deferred principal {{money forborne_cents}} (non-interest-bearing, due at payoff, sale or refinance){{/if}}. Amounts capitalized: interest {{money interest_cents}}, escrow advances {{money escrow_advances_cents}}, other advances {{money servicing_advances_cents}}. Late charges of {{money late_charges_waived_cents}} were waived. Your monthly payment of {{money payment_cents}} (principal and interest {{money pi_cents}}, escrow {{money escrow_cents}}) is due {{date first_due}}. Your loan is current. {{#if recorded}}The agreement was recorded on {{date recorded_on}}.{{/if}}{{/block}}
${CONTACT}`;
const MOD_COMPLETED_RULES = [DATE_RULE, CONTACT_RULE, R("effective", "D2-3.2-06; Form 3179", "presence", "effective ", "effective date"), R("terms", "Form 3179", "presence", "interest rate \\d+\\.\\d{3}%, maturity", "new terms"), R("capitalized", "F-1-27", "presence", "Amounts capitalized: ", "capitalization itemized"), R("late-charges", "12.8-T9", "presence", "Late charges of \\$[\\d,]+\\.\\d{2} were waived", "late charges waived")];
const MOD_COMPLETED_SAMPLE = { ...BASE, notice_date: "2027-01-05", effective: "2027-01-01", rate_pct: "6.500", maturity: "2066-12-01", ib_upb_cents: 21_592_199n, forborne_cents: 3_548_332n, interest_cents: 1_025_984n, escrow_advances_cents: 420_000n, servicing_advances_cents: 18_000n, late_charges_waived_cents: 50_568n, payment_cents: 181_513n, pi_cents: 126_413n, escrow_cents: 55_100n, first_due: "2027-01-01", recorded: true, recorded_on: "2027-01-05" };

// ------------------------------------------------------------------ 12.9 short sale / Mortgage Release
const SS_ELIGIBILITY = `${HEAD("Your request for a short sale")}
{{#block "body" page=1 y=0.2 pt=11}}We reviewed your request received {{date received_on}}. {{#if eligible}}You are eligible to pursue a short sale. Please list the property with a licensed agent, keep it listed on the MLS, and send us any purchase offer with the buyer's proof of funds and the estimated settlement statement. {{#if brp_required}}We also need a complete Borrower Response Package by {{date brp_by}}.{{/if}}{{/if}}{{#if ineligible}}We are unable to approve a short sale at this time. Reason: {{principal_reason}}. Other options we considered: {{#each other_options}}{{name}}: {{determination}}; {{/each}}{{/if}} Not all borrowers qualify.{{/block}}
${APPEAL}
{{#if ineligible}}${ECOA}{{/if}}
${CONTACT}`;
const SS_ELIGIBILITY_RULES = [DATE_RULE, CONTACT_RULE, APPEAL_RULE, R("outcome", "D2-3.3-01", "presence", "(eligible to pursue a short sale|unable to approve a short sale)", "eligibility outcome"), R("reviewer-when-ineligible", "12.9 guardrail: denials via lossmit_reviewer", "conditional", "ineligible", "reviewer approval on denial", { when: { "==": [{ var: "ineligible" }, true] }, predicate: { present: "reviewer_approval_id" } }), R("ecoa-when-ineligible", "12 CFR 1002.9", "conditional", "ineligible", "ECOA on denial", { when: { "==": [{ var: "ineligible" }, true] }, predicate: { "==": [{ var: "ineligible" }, true] } })];
const SS_ELIGIBILITY_SAMPLE = { ...BASE, received_on: "2026-10-05", eligible: true, ineligible: false, brp_required: false, appeal_available: false };

const SS_OFFER_ACK = `${HEAD("We received the purchase offer")}
{{#block "body" page=1 y=0.2 pt=11}}On {{date offer_on}} we received a purchase offer of {{money price_cents}} from {{buyer}} on {{property_address}}. We are acknowledging it within five business days as Fannie Mae requires. We have ordered a property valuation and will send you our written approval, counteroffer or decline by {{date decision_by}} (30 days from the complete package and offer). We may ask for: {{#each needed}}{{this}}; {{/each}}{{/block}}
${CONTACT}`;
const SS_OFFER_ACK_RULES = [DATE_RULE, CONTACT_RULE, R("offer", "D2-3.3-01", "presence", "purchase offer of \\$[\\d,]+\\.\\d{2}", "offer amount"), R("5bd", "D2-3.3-01: acknowledge within 5 business days", "presence", "within five business days", "ack timing"), R("30-days", "D2-3.3-01: decision within 30 days", "presence", "by [A-Z][a-z]+ \\d{1,2}, \\d{4} \\(30 days", "decision date")];
const SS_OFFER_ACK_SAMPLE = { ...BASE, notice_date: "2026-10-07", offer_on: "2026-10-05", price_cents: 27_500_000n, buyer: "J. Buyer", decision_by: "2026-11-04", needed: ["the buyer's proof of funds", "the listing history"] };

const SS_APPROVAL = `${HEAD("Short sale approval")}
{{#block "body" page=1 y=0.2 pt=11}}Fannie Mae has approved the short sale of {{property_address}} to {{buyer}} at {{money price_cents}}, with net proceeds to us of at least {{money net_proceeds_cents}}, closing by {{date close_by}}. {{#if contribution_cents}}You agreed to contribute {{money contribution_cents}} at closing.{{/if}}{{#if relocation_cents}}You will receive relocation assistance of {{money relocation_cents}} from the closing agent.{{/if}} The approval is conditioned on the settlement statement matching these terms; no other payment to you or to any party not on the statement is permitted. {{#if deficiency_waived}}We will not pursue the remaining balance after closing.{{/if}} A foreclosure sale will not be held for 60 days from this approval while you proceed to closing.{{/block}}
${CONTACT}`;
const SS_APPROVAL_RULES = [DATE_RULE, CONTACT_RULE, R("terms", "D2-3.3-01", "presence", "at \\$[\\d,]+\\.\\d{2}, with net proceeds", "price and net proceeds"), R("close-by", "D2-3.3-01: close within 60 days", "presence", "closing by ", "closing deadline"), R("no-side-payments", "12.9 guardrail: settlement anomalies → fraud review", "presence", "no other payment to you or to any party", "side-payment bar"), R("hold-60", "E-3.4-01", "presence", "will not be held for 60 days", "post-approval hold"), R("relocation-not-with-contribution", "D2-3.3-01: no relocation when a contribution is required", "data_equality", "relocation_cents", "relocation absent when contribution present", { predicate: { or: [{ "!": { present: "contribution_cents" } }, { "==": [{ var: "relocation_cents" }, 0] }] } }), R("smdu", "12.9 guardrail: approval only from SMDU / Fannie Mae", "data_equality", "smdu_decision_id", "SMDU decision recorded", { predicate: { present: "smdu_decision_id" } })];
const SS_APPROVAL_SAMPLE = { ...BASE, notice_date: "2026-10-28", buyer: "J. Buyer", price_cents: 27_500_000n, net_proceeds_cents: 25_300_000n, close_by: "2026-12-27", relocation_cents: 750_000n, deficiency_waived: true, smdu_decision_id: "SMDU-SS-1" };

const SS_COUNTER = `${HEAD("Short sale — counteroffer")}
{{#block "body" page=1 y=0.2 pt=11}}We reviewed the offer of {{money price_cents}} received {{date offer_on}}. Based on the property valuation, Fannie Mae will accept a sale that produces net proceeds of at least {{money required_net_cents}} (a price of about {{money counter_price_cents}} at the proposed costs){{#if contribution_cents}}, and a contribution from you of {{money contribution_cents}}{{/if}}. Please send the buyer's response by {{date respond_by}}; we will decide on a revised offer within 10 business days of receiving it.{{/block}}
${CONTACT}`;
const SS_COUNTER_RULES = [DATE_RULE, CONTACT_RULE, R("required-net", "D2-3.3-01", "presence", "net proceeds of at least \\$[\\d,]+\\.\\d{2}", "required net stated"), R("10bd", "D2-3.3-01: revised offers within 10 BD", "presence", "within 10 business days", "revised-offer timing"), R("smdu", "12.9 guardrail", "data_equality", "smdu_decision_id", "SMDU decision recorded", { predicate: { present: "smdu_decision_id" } })];
const SS_COUNTER_SAMPLE = { ...BASE, price_cents: 26_000_000n, offer_on: "2026-10-05", required_net_cents: 25_300_000n, counter_price_cents: 27_500_000n, respond_by: "2026-11-11", smdu_decision_id: "SMDU-SS-2" };

const SS_DECLINE = `${HEAD("Short sale — decision")}
{{#block "body" page=1 y=0.2 pt=11}}We reviewed the offer of {{money price_cents}} received {{date offer_on}}. We are unable to approve it. Reason: {{principal_reason}}. This decision was made under Fannie Mae's guidelines. You may submit another offer, and other options we considered: {{#each other_options}}{{name}}: {{determination}}; {{/each}}{{/block}}
${APPEAL}
${ECOA}
${CONTACT}`;
const SS_DECLINE_RULES = [DATE_RULE, CONTACT_RULE, ECOA_RULE, APPEAL_RULE, R("reason", "12 CFR 1002.9; D2-3.3-01", "presence", "Reason: ", "principal reason"), R("reviewer", "12.9 guardrail: denials via lossmit_reviewer", "data_equality", "reviewer_approval_id", "reviewer approval recorded", { predicate: { present: "reviewer_approval_id" } })];
const SS_DECLINE_SAMPLE = { ...BASE, price_cents: 20_000_000n, offer_on: "2026-10-05", principal_reason: "the offer's net proceeds are below the minimum Fannie Mae will accept and the buyer is a related party", other_options: [{ name: "Mortgage Release", determination: "available — see enclosed" }], appeal_available: false, reviewer_approval_id: "rev-8" };

const DIL_OFFER = `${HEAD("Mortgage Release (deed-in-lieu of foreclosure) — offer")}
{{#block "body" page=1 y=0.2 pt=11}}You are eligible for a Mortgage Release. You would transfer the property to Fannie Mae and be released from the mortgage debt. Exit options: {{#each exit_options}}{{this}}; {{/each}}{{#if relocation_cents}}Relocation assistance of {{money relocation_cents}} is available if you leave the property clean and undamaged.{{/if}} To accept, sign and return the enclosed acceptance by {{date accept_by}}. We will then order a title search and an inspection; the property must have clear, marketable title{{#if subordinate_liens}} (subordinate liens: {{subordinate_liens}}){{/if}}.{{/block}}
${CONTACT}`;
const DIL_OFFER_RULES = [DATE_RULE, CONTACT_RULE, R("release", "D2-3.3-02", "presence", "released from the mortgage debt", "release explained"), R("exit-options", "D2-3.3-02", "presence", "Exit options: ", "exit options listed"), R("title", "F-1-13", "presence", "clear, marketable title", "title condition")];
const DIL_OFFER_SAMPLE = { ...BASE, exit_options: ["immediate vacancy", "3-month transition (principal residence)"], relocation_cents: 750_000n, accept_by: "2026-11-30", subordinate_liens: "" };

const DIL_ACCEPTED = `${HEAD("Mortgage Release — accepted")}
{{#block "body" page=1 y=0.2 pt=11}}We received your acceptance on {{date accepted_on}} with the {{exit_option}} option. Please return the following within 60 days, by {{date documents_by}}: {{#each documents}}{{this}}; {{/each}}If more time is needed we may extend to {{date extended_by}} with weekly status updates. Please keep the property secured and insured until the deed is recorded. No foreclosure sale will be held while you meet these dates.{{/block}}
${CONTACT}`;
const DIL_ACCEPTED_RULES = [DATE_RULE, CONTACT_RULE, R("60-days", "D2-3.3-02", "presence", "within 60 days", "document clock"), R("extension", "D2-3.3-02", "presence", "extend to .* with weekly status updates", "90-day extension with updates"), R("hold", "E-3.4-01", "presence", "No foreclosure sale will be held", "hold stated")];
const DIL_ACCEPTED_SAMPLE = { ...BASE, accepted_on: "2026-11-15", exit_option: "3-month transition", documents_by: "2027-01-14", extended_by: "2027-02-13", documents: ["executed deed", "estoppel affidavit", "personal property release"] };

const DIL_COMPLETED = `${HEAD("Mortgage Release — complete")}
{{#block "body" page=1 y=0.2 pt=11}}The deed to {{property_address}} was recorded on {{date recorded_on}} and your Mortgage Release is complete. You are released from the mortgage debt{{#if deficiency_waived}} and we will not pursue any remaining balance{{/if}}. {{#if relocation_cents}}Relocation assistance of {{money relocation_cents}} was paid on {{date relocation_paid_on}}.{{/if}}{{#if lease}}Your {{lease}} begins {{date lease_start}}.{{/if}} The release of our lien will be recorded within 30 business days.{{/block}}
${CONTACT}`;
const DIL_COMPLETED_RULES = [DATE_RULE, CONTACT_RULE, R("recorded", "D2-3.3-02", "presence", "deed .* was recorded on ", "deed recorded"), R("release", "D2-3.3-02", "presence", "released from the mortgage debt", "release stated"), R("lien-release", "FNMA_D23302_DIL_LIEN_RELEASE_30BD", "presence", "within 30 business days", "lien release timing")];
const DIL_COMPLETED_SAMPLE = { ...BASE, notice_date: "2027-01-20", recorded_on: "2027-01-18", deficiency_waived: true, relocation_cents: 750_000n, relocation_paid_on: "2027-01-19", lease: "", lease_start: "" };

export const SECTION_12_VERSIONS: VersionInput[] = [
  V("NTC_CA_2924_10_ACK", CA_ACK, CA_ACK_RULES, CA_ACK_SAMPLE, "state.ca.2924_10.2026", "Cal. Civ. Code §2924.10; 12.1-T10"),
  V("NTC_FNMA_D2204_SOLICITATION", SOLICIT, SOLICIT_RULES, SOLICIT_SAMPLE, "fnma.d2204.2026-09", "D2-2-04 Borrower Solicitation Package; 12.1-T8"),
  V("NTC_FNMA_D2205_LATE_BRP_PLAN", LATE_BRP, LATE_BRP_RULES, LATE_BRP_SAMPLE, "fnma.d2205.2026-09", "D2-2-05 / D2-3.2-02; 12.1"),
  V("NTC_REGX_41B2_INCOMPLETE_CLOSED", INCOMPLETE_CLOSED, INCOMPLETE_CLOSED_RULES, INCOMPLETE_CLOSED_SAMPLE, "regx.lossmit.2014", "12 CFR 1024.41(b)(2), (c)(2)(ii); comment 41(c)(2)(ii)-1"),
  V("NTC_REGX_41B2_SUPPLEMENTAL_REQUEST", SUPPLEMENTAL, SUPPLEMENTAL_RULES, SUPPLEMENTAL_SAMPLE, "regx.lossmit.2014", "12 CFR 1024.41(c)(2)(iv); 12.1-T4"),
  V("NTC_REGX_41C2III_SHORTTERM_TERMS", SHORTTERM, SHORTTERM_RULES, SHORTTERM_SAMPLE, "regx.lossmit.2014", "12 CFR 1024.41(c)(2)(iii)"),
  V("NTC_REGX_41C3_COMPLETE", C3_COMPLETE, C3_RULES, C3_SAMPLE, "regx.lossmit.2014", "12 CFR 1024.41(c)(3); 12.1-T4"),
  V("NTC_REGX_41I_DUPLICATIVE", DUPLICATIVE, DUPLICATIVE_RULES, DUPLICATIVE_SAMPLE, "regx.lossmit.2014", "12 CFR 1024.41(i)"),
  V("NTC_REGX_41_NPRM_RFA_RECEIVED", NPRM_RFA, NPRM_RFA_RULES, NPRM_RFA_SAMPLE, "regx.lossmit.2024nprm", "2024 NPRM (regime 2024nprm); 12.1-T11"),
  V("NTC_FNMA_EVAL_NOTICE_STREAMLINED", EVAL_STREAMLINED, EVAL_STREAMLINED_RULES, EVAL_STREAMLINED_SAMPLE, "fnma.evaluation_notice.2026-09", "Fannie Mae Evaluation Notice (streamlined); 12.2-T13"),
  V("NTC_REGB_1002_9_LM_ADVERSE_ACTION", REGB, REGB_RULES, REGB_SAMPLE, "regb.1002_9.2026", "12 CFR 1002.9 / Form 182; 12.2-T6"),
  V("NTC_REGX_41C4IIB_THIRD_PARTY_DELAY", THIRD_PARTY, THIRD_PARTY_RULES, THIRD_PARTY_SAMPLE, "regx.lossmit.2014", "12 CFR 1024.41(c)(4)(ii)(B); 12.2-T5"),
  V("NTC_REGX_41H_APPEAL_ACK", APPEAL_ACK, APPEAL_ACK_RULES, APPEAL_ACK_SAMPLE, "regx.lossmit.2014", "12 CFR 1024.41(h); 12.3"),
  V("NTC_REGX_41H_APPEAL_INELIGIBLE", APPEAL_INELIGIBLE, APPEAL_INELIGIBLE_RULES, APPEAL_INELIGIBLE_SAMPLE, "regx.lossmit.2014", "12 CFR 1024.41(h)(2); 12.3-T3"),
  V("NTC_FNMA_D23201_FORB_PLAN", FORB_PLAN, FORB_PLAN_RULES, FORB_PLAN_SAMPLE, "fnma.d23201.2026-09", "D2-3.2-01 forbearance plan terms"),
  V("NTC_FNMA_D23201_FORB_EXTENSION", FORB_EXTENSION, FORB_EXTENSION_RULES, FORB_EXTENSION_SAMPLE, "fnma.d23201.2026-09", "D2-3.2-01 / LL-2026-01 extension"),
  V("NTC_FNMA_D23201_FORB_EXPIRY_OPTIONS", FORB_EXPIRY, FORB_EXPIRY_RULES, FORB_EXPIRY_SAMPLE, "fnma.d23201.2026-09", "D2-3.2-01 pre-expiry outreach; 12.4-T4"),
  V("NTC_FNMA_D23201_FORB_TERMINATION", FORB_TERMINATION, FORB_TERMINATION_RULES, FORB_TERMINATION_SAMPLE, "fnma.d23201.2026-09", "D2-3.2-01 termination; 12.4-T7"),
  V("NTC_FNMA_D23202_REPAY_PLAN", REPAY_PLAN, REPAY_PLAN_RULES, REPAY_PLAN_SAMPLE, "fnma.d23202.2026-09", "D2-3.2-02 repayment plan terms; 12.5 worked example"),
  V("NTC_FNMA_D23202_REPAY_COMPLETED", REPAY_COMPLETED, REPAY_COMPLETED_RULES, REPAY_COMPLETED_SAMPLE, "fnma.d23202.2026-09", "D2-3.2-02 completion; 12.5-T4"),
  V("NTC_FNMA_D23202_REPAY_FAILED", REPAY_FAILED, REPAY_FAILED_RULES, REPAY_FAILED_SAMPLE, "fnma.d23202.2026-09", "D2-3.2-02 failure; 12.5-T4/T5"),
  V("NTC_FNMA_D23204_DEFERRAL_OFFER", DEFERRAL_OFFER, DEFERRAL_OFFER_RULES, DEFERRAL_OFFER_SAMPLE, "fnma.d23204.2026-09", "D2-3.2-04 offer; 12.6-T7"),
  V("NTC_FNMA_D23204_DEFERRAL_COMPLETED", DEFERRAL_COMPLETED, DEFERRAL_COMPLETED_RULES, DEFERRAL_COMPLETED_SAMPLE, "fnma.d23204.2026-09", "D2-3.2-04 completion; 12.6-T1"),
  V("NTC_FNMA_D23204_SOLICIT_POST_FORB", SOLICIT_POST_FORB, SOLICIT_POST_FORB_RULES, SOLICIT_POST_FORB_SAMPLE, "fnma.d23204.2026-09", "D2-3.2-04 post-forbearance solicitation; 12.6-T6"),
  V("NTC_FNMA_D23204_SOLICIT_POST_REPAY", SOLICIT_POST_REPAY, SOLICIT_POST_REPAY_RULES, SOLICIT_POST_REPAY_SAMPLE, "fnma.d23204.2026-09", "D2-3.2-04 post-repayment solicitation; 12.6-T6"),
  V("NTC_FNMA_D23205_DISASTER_DEFERRAL_OFFER", DISASTER_OFFER, DISASTER_OFFER_RULES, DISASTER_OFFER_SAMPLE, "fnma.d23205.2026-09", "D2-3.2-05 offer; 12.7 worked example"),
  V("NTC_FNMA_D23205_SOLICIT_POST_DISASTER_FORB", SOLICIT_POST_DISASTER_FORB, SOLICIT_POST_DISASTER_FORB_RULES, SOLICIT_POST_DISASTER_FORB_SAMPLE, "fnma.d23205.2026-09", "D2-3.2-05 post-forbearance solicitation; 12.7-T1"),
  V("NTC_FNMA_D23205_SOLICIT_POST_REPAY", SOLICIT_POST_REPAY_DISASTER, SOLICIT_POST_REPAY_DISASTER_RULES, SOLICIT_POST_REPAY_DISASTER_SAMPLE, "fnma.d23205.2026-09", "D2-3.2-05 post-repayment solicitation"),
  V("NTC_FNMA_D23206_SOLICIT_STREAMLINED", SOLICIT_STREAMLINED, SOLICIT_STREAMLINED_RULES, SOLICIT_STREAMLINED_SAMPLE, "fnma.d23206.2026-09", "D2-3.2-06 streamlined solicitation; 12.8-T6"),
  V("NTC_FNMA_D23206_TPP_OFFER", TPP_OFFER, TPP_OFFER_RULES, TPP_OFFER_SAMPLE, "fnma.d23206.2026-09", "D2-3.2-06 Evaluation Notice / TPP; 12.8 worked example"),
  V("NTC_FNMA_D23206_TPP_REMINDER", TPP_REMINDER, TPP_REMINDER_RULES, TPP_REMINDER_SAMPLE, "fnma.d23206.2026-09", "D2-3.2-06 trial reminder"),
  V("NTC_FNMA_D23206_TPP_FAILED", TPP_FAILED, TPP_FAILED_RULES, TPP_FAILED_SAMPLE, "fnma.d23206.2026-09", "D2-3.2-06 trial failure"),
  V("NTC_FNMA_D23206_MOD_COMPLETED", MOD_COMPLETED, MOD_COMPLETED_RULES, MOD_COMPLETED_SAMPLE, "fnma.d23206.2026-09", "D2-3.2-06 / Form 3179 completion; 12.8-T9"),
  V("NTC_FNMA_D23301_SS_ELIGIBILITY", SS_ELIGIBILITY, SS_ELIGIBILITY_RULES, SS_ELIGIBILITY_SAMPLE, "fnma.d23301.2026-09", "D2-3.3-01 eligibility"),
  V("NTC_FNMA_D23301_SS_OFFER_ACK", SS_OFFER_ACK, SS_OFFER_ACK_RULES, SS_OFFER_ACK_SAMPLE, "fnma.d23301.2026-09", "D2-3.3-01 offer acknowledgment; 12.9-T1"),
  V("NTC_FNMA_D23301_SS_APPROVAL", SS_APPROVAL, SS_APPROVAL_RULES, SS_APPROVAL_SAMPLE, "fnma.d23301.2026-09", "D2-3.3-01 approval; 12.9-T10"),
  V("NTC_FNMA_D23301_SS_COUNTER", SS_COUNTER, SS_COUNTER_RULES, SS_COUNTER_SAMPLE, "fnma.d23301.2026-09", "D2-3.3-01 counteroffer"),
  V("NTC_FNMA_D23301_SS_DECLINE", SS_DECLINE, SS_DECLINE_RULES, SS_DECLINE_SAMPLE, "fnma.d23301.2026-09", "D2-3.3-01 decline"),
  V("NTC_FNMA_D23302_DIL_OFFER", DIL_OFFER, DIL_OFFER_RULES, DIL_OFFER_SAMPLE, "fnma.d23302.2026-09", "D2-3.3-02 offer"),
  V("NTC_FNMA_D23302_DIL_ACCEPTED", DIL_ACCEPTED, DIL_ACCEPTED_RULES, DIL_ACCEPTED_SAMPLE, "fnma.d23302.2026-09", "D2-3.3-02 acceptance clocks"),
  V("NTC_FNMA_D23302_DIL_COMPLETED", DIL_COMPLETED, DIL_COMPLETED_RULES, DIL_COMPLETED_SAMPLE, "fnma.d23302.2026-09", "D2-3.3-02 completion"),
];
