/**
 * Authored template versions for the §10 PMI notices: the acknowledgment
 * with the evidence list (10.1), the termination/cancellation notice, the
 * not-current and LPMI options notices (10.2/10.3), the annual disclosures
 * with the legacy, MN, CA and Fannie Mae program variants (10.4), the refund
 * advice (10.5) and the denial, information-request and case-closed letters
 * (10.6). Sample payloads are the sections' worked examples.
 */
import type { ContentRule, VersionInput } from "../registry.ts";
import { V } from "./section01.ts";

const R = (rule_id: string, citation: string, kind: ContentRule["kind"], selector: string, message: string, extra: Partial<ContentRule> = {}): ContentRule => ({ rule_id, citation, kind, selector, severity: "block", message, ...extra });
const CONTACT = `{{#block "contact" page=1 y=0.9 pt=10}}To find out whether you may cancel your private mortgage insurance, or to ask a question about this notice, call {{servicer_phone}} or write to Supermortgage, {{servicer_address}}.{{/block}}`;
const ERROR_BLOCK = `{{#block "error_resolution" page=1 y=0.85 pt=10}}If you believe we have made an error, or you want a copy of the valuation, write to {{error_resolution_address}}. Traducción al español disponible a solicitud.{{/block}}`;
const BASE = { servicer_phone: "(800) 555-0100", servicer_address: "PO Box 1, Testville TX 75001", error_resolution_address: "Supermortgage Error Resolution, PO Box 2, Testville TX 75001", account_last4: "1234", property_address: "1 Test St, Testville TX 75001", notice_date: "2027-07-14" };
const CONTACT_RULE = R("contact", "12 U.S.C. 4903(a)(3)(B)", "presence", "call \\(\\d{3}\\) \\d{3}-\\d{4} or write to Supermortgage, ", "address and telephone number");
const DATE_RULE = R("date", "notice date", "presence", "(January|February|March|April|May|June|July|August|September|October|November|December) \\d{1,2}, \\d{4}", "date of the notice");
const NO_CREDIT = R("no-credit-language", "10.6 R2", "absence", "(credit score|underwriting)", "no credit-score or underwriting rationale");
const AVM_RULE = R("avm-disclaimer", "SMDU FAQ Q6", "presence", "developed by an automated valuation model", "AVM disclaimer when a value is quoted");

// ------------------------------------------------------------------ 10.1 acknowledgment / evidence
const ACK_SOURCE = `{{#block "heading" page=1 y=0.05 pt=13 bold}}We received your request to cancel private mortgage insurance{{/block}}
{{#block "body" page=1 y=0.12 pt=11}}{{date notice_date}}. Loan number ending {{account_last4}}. Property: {{property_address}}. We received your request on {{date received_on}}. We evaluate it first under the Homeowners Protection Act (cancellation at 80 percent of the original value of your property) and under Fannie Mae's guidelines{{#if mn_overlay}}, and under Minnesota law{{/if}}. The original value on our records is {{money original_value_cents}}. Your unpaid principal balance is {{money upb_cents}}, which is {{ltv_percent}}% of the original value. To qualify you must be current, with no payment 30 or more days late in the 12 months before {{date window_end}} and no payment 60 or more days late in the 24 months before that date.{{/block}}
{{#block "evidence" page=1 y=0.45 pt=11}}Evidence we accept that the value of your property has not declined below its original value: an automated valuation obtained from Fannie Mae's servicing system at no cost to you; or, if you elect it, a broker price opinion ({{money bpo_fee_cents}}) or an appraisal ({{money appraisal_fee_cents}}) ordered by us through Fannie Mae at your expense. A valuation is valid for 120 days from delivery. We do not accept appraisals you order yourself. The automated value cannot be appealed, but you may choose to pay for a broker price opinion or appraisal instead.{{#if avm_value_cents}} The automated value of {{money avm_value_cents}} was developed by an automated valuation model and is not an appraisal.{{/if}}{{#if sub_lien_cert_required}} Please also certify that your equity is not encumbered by a subordinate lien.{{/if}}{{/block}}
{{#if mn_overlay}}{{#block "mn" page=1 y=0.7 pt=12}}Under Minnesota law (Minn. Stat. 47.207) you may also request cancellation when your unpaid principal balance is 80 percent or less of the current fair market value shown by an appraisal made within the last 90 days, at your cost, if your loan is at least 24 months old and you occupy the property.{{/block}}{{/if}}
${CONTACT}`;
const ACK_RULES: ContentRule[] = [DATE_RULE, R("received", "12 U.S.C. 4902(a)(4)(A) 'promptly upon receipt'", "presence", "We received your request on ", "request date acknowledged"), R("original-value", "12 U.S.C. 4901(12)", "presence", "The original value on our records is \\$", "original value on file"), R("ltv", "10.1 R3", "presence", "which is \\d{1,3}\\.\\d{2}% of the original value", "current UPB and LTV"), R("windows", "12 U.S.C. 4901(4)", "presence", "no payment 30 or more days late in the 12 months", "payment-history windows"), R("evidence-avm-free", "B-8.1-04 (SMDU AVM)", "presence", "at no cost to you", "the no-cost AVM"), R("evidence-fees", "F-1-02", "presence", "broker price opinion \\(\\$[\\d,]+\\.\\d{2}\\) or an appraisal \\(\\$[\\d,]+\\.\\d{2}\\)", "borrower-elected valuation fees"), R("validity", "SMDU FAQ Q9", "presence", "valid for 120 days", "120-day validity"), R("no-borrower-appraisal", "10.1-Q3", "presence", "We do not accept appraisals you order yourself", "only SMDU-ordered valuations"), AVM_RULE, R("no-solicitation", "B-8.1-04 'must not solicit'", "absence", "(we recommend|we encourage you to request)", "no solicitation of a current-value request"), CONTACT_RULE];
const ACK_SAMPLE = { ...BASE, notice_date: "2029-07-11", received_on: "2029-07-10", original_value_cents: 40000000n, upb_cents: 31995095n, ltv_percent: "79.98", window_end: "2029-07-10", bpo_fee_cents: 19000n, appraisal_fee_cents: 45000n, avm_value_cents: 45500000n, sub_lien_cert_required: false, mn_overlay: false };

// ------------------------------------------------------------------ 10.2 / 10.3 termination, not-current, LPMI options
const CANCELLED_SOURCE = `{{#block "heading" page=1 y=0.05 pt=13 bold}}Your private mortgage insurance has ended{{/block}}
{{#block "body" page=1 y=0.12 pt=11}}{{date notice_date}}. Loan number ending {{account_last4}}. Property: {{property_address}}. Your private mortgage insurance {{termination_phrase}} effective {{date effective_on}}. You no longer have private mortgage insurance on this loan, and no further premiums, payments, or other fees for private mortgage insurance shall be due. {{#if new_payment_cents}}Your new monthly payment will be {{money new_payment_cents}} beginning with the payment due {{date new_payment_effective_on}}; a revised escrow account statement follows.{{else}}Your payment does not change because the premium was financed into your loan.{{/if}} Any unearned premium will be returned to you within 45 days of {{date effective_on}}{{#if refund_estimate_cents}} (estimated {{money refund_estimate_cents}}){{/if}}.{{/block}}
${CONTACT}`;
const CANCELLED_RULES: ContentRule[] = [DATE_RULE, R("ended", "12 U.S.C. 4904(a)(1)", "presence", "private mortgage insurance (has been cancelled|terminated|has ended)", "statement that PMI has terminated or been cancelled"), R("effective", "B-8.1-04", "presence", "effective (January|February|March|April|May|June|July|August|September|October|November|December) \\d{1,2}, \\d{4}", "effective date"), R("no-further-fees", "12 U.S.C. 4904(a)(2)", "presence", "no further premiums, payments, or other fees for private mortgage insurance shall be due", "the statutory no-further-fees sentence"), R("payment", "B-8.1-04 'reduce the payment'", "presence", "(Your new monthly payment will be|Your payment does not change)", "new payment or financed-premium note"), R("refund", "12 U.S.C. 4902(f)(1)", "presence", "returned to you within 45 days", "refund timing"), CONTACT_RULE];
const CANCELLED_SAMPLE = { ...BASE, notice_date: "2035-07-05", termination_phrase: "terminated automatically because your loan balance was scheduled to reach 78 percent of the original value of your property", effective_on: "2035-07-01", new_payment_cents: 270186n, new_payment_effective_on: "2035-08-01", refund_estimate_cents: 141173n };
const NOT_CURRENT_SOURCE = `{{#block "heading" page=1 y=0.05 pt=13 bold}}Your private mortgage insurance was not terminated on {{date scheduled_termination_on}}{{/block}}
{{#block "body" page=1 y=0.12 pt=11}}{{date notice_date}}. Loan number ending {{account_last4}}. Property: {{property_address}}. Federal law ends borrower-paid private mortgage insurance on the date your loan balance is first scheduled to reach 78 percent of the original value of your property, if you are current on your payments on that date. Your insurance was not terminated on {{date scheduled_termination_on}} because {{grounds_text}}. Your private mortgage insurance will terminate on the first day of the month after you become current. Current means every payment that is due has been received. No fee is charged for termination, and no appraisal is required.{{/block}}
${CONTACT}`;
const NOT_CURRENT_RULES: ContentRule[] = [DATE_RULE, R("grounds", "12 U.S.C. 4904(b)(1); B-8.1-04", "presence", "was not terminated on .* because the (January|February|March|April|May|June|July|August|September|October|November|December) \\d{4} payment was not received by", "the specific installment unpaid at month-end"), R("cure-rule", "12 U.S.C. 4902(b)(2)", "presence", "terminate on the first day of the month after you become current", "the cure rule"), R("current-defined", "10.6 R3", "presence", "Current means", "what current means"), R("no-fee", "B-8.1-04; CFPB 2015-03", "presence", "No fee is charged", "no fee, no valuation"), R("no-collection", "10.6 edge (bankruptcy)", "absence", "(you must pay|pay immediately)", "not a collection communication"), CONTACT_RULE];
const NOT_CURRENT_SAMPLE = { ...BASE, notice_date: "2035-07-05", scheduled_termination_on: "2035-07-01", grounds_text: "the June 2035 payment was not received by 2035-06-30" };
const LPMI_SOURCE = `{{#block "heading" page=1 y=0.05 pt=13 bold}}Information about the mortgage insurance on your loan{{/block}}
{{#block "body" page=1 y=0.12 pt=11}}{{date notice_date}}. Loan number ending {{account_last4}}. Property: {{property_address}}. Your loan has lender-paid mortgage insurance. Lender-paid mortgage insurance cannot be cancelled or terminated by you, and its cost is part of your interest rate. On {{date equivalent_termination_on}} your loan reached the date on which borrower-paid mortgage insurance would have terminated under federal law. You may wish to review financing options that could eliminate the requirement for private mortgage insurance.{{/block}}
${CONTACT}`;
const LPMI_RULES: ContentRule[] = [DATE_RULE, R("lpmi", "12 U.S.C. 4905(c)(2)", "presence", "lender-paid mortgage insurance", "identifies LPMI"), R("options", "12 U.S.C. 4905(c)(2)", "presence", "may wish to review financing options that could eliminate the requirement for private mortgage insurance", "the statutory options sentence"), R("date", "12 U.S.C. 4905(c)(2)", "presence", "would have terminated", "the BPMI-equivalent date has passed"), R("no-cancel-right", "12 U.S.C. 4905(b)", "presence", "cannot be cancelled or terminated by you", "no cancellation right under LPMI"), CONTACT_RULE];
const LPMI_SAMPLE = { ...BASE, notice_date: "2035-07-10", equivalent_termination_on: "2035-07-01" };

// ------------------------------------------------------------------ 10.4 annual disclosures
const RIGHTS = `You have the right to ask us to cancel your private mortgage insurance in writing when your loan balance reaches 80 percent of the original value of your property, based on the original amortization schedule or on your actual payments, if you have a good payment history, are current, and provide evidence acceptable to the holder that the value of your property has not declined (an automated valuation at no cost to you; a broker price opinion {{money bpo_fee_cents}} or an appraisal {{money appraisal_fee_cents}}{{#if multi_unit}} or {{money appraisal_2_4_fee_cents}}{{/if}} at your expense if you elect it). Your private mortgage insurance terminates automatically when your loan balance is first scheduled to reach 78 percent of the original value if you are current, and in any case ends the first day of the month after the midpoint of your loan's amortization period if you are current. If your loan is modified, these dates are recalculated. Fannie Mae also allows cancellation based on the current value of your property after two years at your request. Based on your loan's schedule, the 80 percent date is {{date projected_80_date}}, the 78 percent date is {{date projected_78_date}} and the midpoint termination date is {{date projected_midpoint_date}}. These dates are estimates{{#if arm}} and may change when your interest rate adjusts{{/if}}. Your balance of {{money upb_cents}} is {{ltv_percent}}% of the original value of {{money original_value_cents}}.`;
const ANNUAL_SOURCE = (variant: "std" | "mn" | "ca") => `{{#block "heading" page=1 y=0.05 pt=13 bold}}Annual notice about your private mortgage insurance{{/block}}
{{#block "body" page=1 y=0.12 pt=${variant === "mn" ? 12 : 11}}}{{date notice_date}}. Loan number ending {{account_last4}}. Property: {{property_address}}. ${RIGHTS}{{/block}}
${variant === "mn" ? `{{#block "mn_statutory" page=1 y=0.7 pt=12}}You may have the right under federal law or Minnesota law to cancel the insurance. Under Minnesota law, cancellation may be possible when the principal balance of your loan is 80 percent or less of the current fair market value of the property.{{/block}}` : ""}
${variant === "ca" ? `{{#block "ca_notice" page=1 y=0.7 pt=10 bold}}Notice under California Civil Code section 2954.6, provided without cost to you: private mortgage insurance on loan ending {{account_last4}}, insured by {{insurer_name}}, certificate {{certificate_last4}}, may be cancelled when the ratio between the remaining principal balance of the loan and the original or current value of the property is 80 percent or less, subject to a good payment history; an appraisal may be necessary if the automated valuation does not support your request. To request cancellation, write to us at the address below.{{/block}}` : ""}
${CONTACT}`;
const ANNUAL_RULES = (variant: "std" | "mn" | "ca"): ContentRule[] => [DATE_RULE,
  R("right-cancel", "12 U.S.C. 4903(a)(3)(A); 4902(a)", "presence", "right to ask us to cancel your private mortgage insurance in writing when your loan balance reaches 80 percent", "cancellation right stated accurately"),
  R("auto-78", "12 U.S.C. 4902(b)", "presence", "terminates automatically when your loan balance is first scheduled to reach 78 percent", "automatic termination"),
  R("midpoint", "12 U.S.C. 4902(c)", "presence", "midpoint of your loan's amortization period", "final termination"),
  R("modification", "12 U.S.C. 4902(d)", "presence", "If your loan is modified, these dates are recalculated", "modification recalculation note"),
  R("evidence-fees", "12 U.S.C. 4902(a)(4)(A) 'established in advance'; F-1-02", "presence", "broker price opinion \\$[\\d,]+\\.\\d{2} or an appraisal \\$[\\d,]+\\.\\d{2}", "evidence types and fees"),
  R("projection", "10.4 R3", "presence", "the 78 percent date is (January|February|March|April|May|June|July|August|September|October|November|December) \\d{1,2}, \\d{4}", "projected dates"),
  R("estimate-caveat", "10.4-Q3", "presence", "These dates are estimates", "estimate caveat"),
  R("no-history", "10.4 R3 (privacy)", "absence", "days late in the last", "payment-history status is not printed"),
  R("phone", "12 U.S.C. 4903(a)(3)(B)", "presence", "\\(\\d{3}\\) \\d{3}-\\d{4}", "telephone number"), CONTACT_RULE,
  ...(variant === "mn" ? [R("mn-sentence", "Minn. Stat. 47.207 subd. 3", "presence", "may have the right under federal law or Minnesota law to cancel the insurance", "statutory sentence"), R("mn-80", "Minn. Stat. 47.207 subd. 3", "presence", "80 percent or less of the current fair market value", "MN 80% of current value"), R("mn-12pt", "Minn. Stat. 47.207 subd. 3 '12-point type or greater'", "layout", "body", "body at 12-pt or larger", { layout: { minPt: 12 } }), R("mn-12pt-statutory", "Minn. Stat. 47.207 subd. 3", "layout", "mn_statutory", "statutory sentence at 12-pt", { layout: { minPt: 12 } })] : []),
  ...(variant === "ca" ? [R("ca-ratio", "Cal. Civ. Code 2954.6(b)", "presence", "ratio between the remaining principal balance of the loan and the original or current value", "the cancellation ratio"), R("ca-appraisal", "Cal. Civ. Code 2954.6(b)", "presence", "an appraisal may be necessary", "whether an appraisal may be necessary"), R("ca-procedure", "Cal. Civ. Code 2954.6(b)", "presence", "To request cancellation, write to us", "the procedure"), R("ca-no-cost", "Cal. Civ. Code 2954.6(a)", "presence", "without cost to you", "without cost"), R("ca-10pt-bold", "Cal. Civ. Code 2954.6 '10-point bold type'", "layout", "ca_notice", "10-pt bold", { layout: { minPt: 10, bold: true } })] : [])];
const ANNUAL_SAMPLE = { ...BASE, notice_date: "2027-02-20", bpo_fee_cents: 19000n, appraisal_fee_cents: 45000n, appraisal_2_4_fee_cents: 75000n, multi_unit: false, projected_80_date: "2034-08-01", projected_78_date: "2035-07-01", projected_midpoint_date: "2039-05-01", arm: false, upb_cents: 36540000n, ltv_percent: "91.35", original_value_cents: 40000000n, insurer_name: "Test MI Co", certificate_last4: "9876" };
const LEGACY_SOURCE = `{{#block "heading" page=1 y=0.05 pt=13 bold}}Annual notice about your private mortgage insurance{{/block}}
{{#block "body" page=1 y=0.12 pt=11}}{{date notice_date}}. Loan number ending {{account_last4}}. Property: {{property_address}}. Your loan was made before July 29, 1999. The private mortgage insurance may, under certain circumstances, be canceled by the mortgagor (with the consent of the mortgagee or in accordance with applicable State law). Your loan's mortgage insurance ends no later than the first day of the month after the midpoint of its amortization period if you are current.{{/block}}
${CONTACT}`;
const LEGACY_RULES: ContentRule[] = [DATE_RULE, R("legacy-sentence", "12 U.S.C. 4903(b)", "presence", "may, under certain circumstances, be canceled by the mortgagor \\(with the consent of the mortgagee or in accordance with applicable State law\\)", "the 4903(b) sentence verbatim"), R("pre-1999", "12 U.S.C. 4903(b)", "presence", "before July 29, 1999", "identifies the pre-1999 loan"), R("phone", "12 U.S.C. 4903(b)", "presence", "\\(\\d{3}\\) \\d{3}-\\d{4}", "telephone number"), CONTACT_RULE];
const FNMA_INFO_SOURCE = `{{#block "heading" page=1 y=0.05 pt=13 bold}}Annual information about the mortgage insurance on your loan{{/block}}
{{#block "body" page=1 y=0.12 pt=11}}{{date notice_date}}. Loan number ending {{account_last4}}. Property: {{property_address}}. The federal Homeowners Protection Act does not apply to this loan because of its property type or occupancy, but under Fannie Mae's servicing guidelines you may ask us to terminate borrower-paid mortgage insurance when your loan balance reaches {{threshold_percent}} percent of the original value of your property ({{money original_value_cents}}), if you are current and have an acceptable payment record, or based on the current value of your property after two years. The insurance ends in any case on the first day of the month after the midpoint of your loan's amortization period ({{date projected_midpoint_date}}) if you are current. Your balance of {{money upb_cents}} is {{ltv_percent}}% of the original value.{{/block}}
${CONTACT}`;
const FNMA_INFO_RULES: ContentRule[] = [DATE_RULE, R("scope", "10.4-Q2", "presence", "Homeowners Protection Act does not apply to this loan", "explains the HPA scope"), R("fnma-threshold", "B-8.1-04", "presence", "reaches \\d{2} percent of the original value", "Fannie Mae threshold"), R("midpoint", "B-8.1-04", "presence", "midpoint of your loan's amortization period", "midpoint rule"), R("phone", "10.4", "presence", "\\(\\d{3}\\) \\d{3}-\\d{4}", "telephone number"), CONTACT_RULE];

// ------------------------------------------------------------------ 10.5 refund advice
const REFUND_SOURCE = `{{#block "heading" page=1 y=0.05 pt=13 bold}}Refund of unearned mortgage insurance premium{{/block}}
{{#block "body" page=1 y=0.12 pt=11}}{{date notice_date}}. Loan number ending {{account_last4}}. Property: {{property_address}}. Your private mortgage insurance ended effective {{date effective_on}}. Enclosed or credited to your account is a refund of {{money refund_cents}}. How it was computed: {{plan_text}} premium of {{money premium_cents}}; {{days_in_force}} days of coverage in force before {{date effective_on}}; the insurer's {{method_text}} method. No further mortgage insurance premiums are due.{{#if escrow_analysis_ref}} Your escrow account was re-analyzed on {{date escrow_analysis_on}} (analysis {{escrow_analysis_ref}}); any surplus is refunded separately.{{/if}}{{/block}}
${CONTACT}`;
const REFUND_RULES: ContentRule[] = [DATE_RULE, R("amount", "12 U.S.C. 4902(f)(1)", "presence", "a refund of \\$[\\d,]+\\.\\d{2}", "refund amount"), R("basis", "10.5 outputs", "presence", "How it was computed: .* premium of \\$", "computation basis"), R("days", "10.5 R2", "presence", "\\d+ days of coverage in force", "days in force"), R("no-further", "12 U.S.C. 4904(a)(2)", "presence", "No further mortgage insurance premiums are due", "no further premiums"), R("effective", "10.5", "presence", "ended effective ", "effective date"), CONTACT_RULE];
const REFUND_SAMPLE = { ...BASE, notice_date: "2031-08-13", effective_on: "2031-08-01", refund_cents: 141173n, plan_text: "annual", premium_cents: 228000n, days_in_force: 139, method_text: "days-in-force over 365", escrow_analysis_ref: "IA-2031-0806", escrow_analysis_on: "2031-08-06" };

// ------------------------------------------------------------------ 10.6 denial, information request, case closed
const DENIAL_SOURCE = `{{#block "heading" page=1 y=0.05 pt=13 bold}}Your request to cancel private mortgage insurance was not approved{{/block}}
{{#block "body" page=1 y=0.12 pt=11}}{{date notice_date}}. Loan number ending {{account_last4}}. Property: {{property_address}}. We received your request on {{date received_on}}. Grounds: {{grounds_text}} Your unpaid principal balance of {{money evaluation_upb_cents}} is {{ltv_percent}}% of the {{value_label}} of {{money value_cents}}; the threshold under the path we evaluated ({{path_text}}) is {{threshold_percent}}%.{{#if valuation_text}} {{valuation_text}}{{/if}}{{/block}}
{{#block "cure" page=1 y=0.5 pt=11}}What would make your loan eligible: {{cure_text}} You may renew your request at any time.{{/block}}
${ERROR_BLOCK}
${CONTACT}`;
const DENIAL_RULES: ContentRule[] = [DATE_RULE, R("grounds", "12 U.S.C. 4904(b)(1)", "presence", "Grounds: ", "grounds relied on"), R("numbers", "10.6 R2", "presence", "unpaid principal balance of \\$[\\d,]+\\.\\d{2} is \\d{1,3}\\.\\d{2}% of the", "the numbers used"), R("threshold", "10.6 R2", "presence", "is \\d{2}\\.\\d{2}%\\.", "the threshold"), R("cure", "10.6 R2", "presence", "What would make your loan eligible: ", "cure guidance"), R("renew", "10.6 R2", "presence", "You may renew your request at any time", "renewal right"), R("error-resolution", "12 CFR 1024.35/36", "presence", "If you believe we have made an error", "error-resolution address"), R("valuation-result", "12 U.S.C. 4904(b)(1) 'results of any appraisal'; SMDU FAQ Q6", "presence", "(automated valuation model|broker price opinion of \\$|appraisal of \\$|No valuation was used)", "valuation result or that none was used"), NO_CREDIT, CONTACT_RULE];
const DENIAL_SAMPLE = { ...BASE, notice_date: "2027-07-14", received_on: "2027-07-10", grounds_text: "your loan balance is above 80 percent of the original value of your property.", evaluation_upb_cents: 33554868n, ltv_percent: "83.88", value_label: "original value", value_cents: 40000000n, path_text: "Homeowners Protection Act and Fannie Mae original value", threshold_percent: "80.00", valuation_text: "No valuation was used to make this determination.", cure_text: "your balance is scheduled to reach 80 percent on August 1, 2034; you may qualify earlier when your balance is $320,000.00 or less, or you may ask us to evaluate the current value of your property after May 1, 2026 at a threshold of 75 percent (80 percent from May 1, 2029) with a broker price opinion at $190." };
const INFO_SOURCE = `{{#block "heading" page=1 y=0.05 pt=13 bold}}We need more information to evaluate your mortgage insurance cancellation request{{/block}}
{{#block "body" page=1 y=0.12 pt=12}}{{date notice_date}}. Loan number ending {{account_last4}}. Property: {{property_address}}. We received your request on {{date received_on}}. To evaluate it we need the following: {{#each missing}}{{item}}; {{/each}}You may provide it through the borrower portal, by mail to {{servicer_address}}, or by calling {{servicer_phone}}. If we do not receive it within 60 days of this notice, we will close the request; you may reopen it at any time.{{#if mn_overlay}} This is our response within 30 days of receipt under Minnesota Statutes section 47.207.{{/if}}{{/block}}
${CONTACT}`;
const INFO_RULES: ContentRule[] = [DATE_RULE, R("missing", "Minn. Stat. 47.207 subd. 4 'request additional information'", "presence", "we need the following: .+; ", "what is missing"), R("how", "10.6 outputs", "presence", "You may provide it through", "how to provide it"), R("sixty", "10.6 outputs", "presence", "within 60 days of this notice, we will close the request", "60-day closing rule"), CONTACT_RULE];
const INFO_SAMPLE = { ...BASE, notice_date: "2026-09-08", received_on: "2026-09-01", missing: [{ item: "confirmation that you occupy the property as your principal residence" }], mn_overlay: true };
const CLOSED_SOURCE = `{{#block "heading" page=1 y=0.05 pt=13 bold}}Your mortgage insurance cancellation request has been closed{{/block}}
{{#block "body" page=1 y=0.12 pt=11}}{{date notice_date}}. Loan number ending {{account_last4}}. Property: {{property_address}}. We closed your request received {{date received_on}} because {{closure_reason}}. This is not a denial of your rights: you may reopen the request at any time by writing to us or through the borrower portal{{#if fee_refunded_cents}}, and we have refunded the {{money fee_refunded_cents}} valuation fee you paid{{/if}}.{{/block}}
${CONTACT}`;
const CLOSED_RULES: ContentRule[] = [DATE_RULE, R("reason", "10.6 outputs", "presence", "We closed your request received .* because ", "why the case expired"), R("reopen", "10.6 outputs", "presence", "you may reopen the request at any time", "how to reopen"), R("not-denial", "10.6", "presence", "This is not a denial", "not an HPA denial"), CONTACT_RULE];
const CLOSED_SAMPLE = { ...BASE, notice_date: "2026-11-05", received_on: "2026-09-01", closure_reason: "the valuation fee was not received within 60 days of our request", fee_refunded_cents: null };

export const SECTION_10_VERSIONS: readonly VersionInput[] = [
  V("NTC_HPA_4902A_ACK_EVIDENCE", ACK_SOURCE, ACK_RULES, ACK_SAMPLE, "hpa.1998", "12 U.S.C. 4902(a)(4)(A); 10.1 worked example"),
  V("NTC_HPA_4904A_CANCELLED", CANCELLED_SOURCE, CANCELLED_RULES, CANCELLED_SAMPLE, "hpa.1998", "12 U.S.C. 4904(a); 10.2 Scenario A"),
  V("NTC_HPA_4904B_AUTO_NOT_CURRENT", NOT_CURRENT_SOURCE, NOT_CURRENT_RULES, NOT_CURRENT_SAMPLE, "hpa.1998", "12 U.S.C. 4904(b)(2); 10.2 Scenario B"),
  V("NTC_HPA_4905C2_LPMI_OPTIONS", LPMI_SOURCE, LPMI_RULES, LPMI_SAMPLE, "hpa.1998", "12 U.S.C. 4905(c)(2); 10.2 LPMI example"),
  V("NTC_HPA_4903A3_ANNUAL", ANNUAL_SOURCE("std"), ANNUAL_RULES("std"), ANNUAL_SAMPLE, "hpa.1998", "12 U.S.C. 4903(a)(3); 10.4 worked example"),
  V("NTC_HPA_4903A3_ANNUAL_MN", ANNUAL_SOURCE("mn"), ANNUAL_RULES("mn"), ANNUAL_SAMPLE, "state.pmi.MN", "Minn. Stat. 47.207 subd. 3"),
  V("NTC_HPA_4903A3_ANNUAL_CA", ANNUAL_SOURCE("ca"), ANNUAL_RULES("ca"), ANNUAL_SAMPLE, "state.pmi.CA", "Cal. Civ. Code 2954.6"),
  V("NTC_HPA_4903B_ANNUAL_LEGACY", LEGACY_SOURCE, LEGACY_RULES, { ...ANNUAL_SAMPLE }, "hpa.1998", "12 U.S.C. 4903(b)"),
  V("NTC_FNMA_MI_ANNUAL_INFO", FNMA_INFO_SOURCE, FNMA_INFO_RULES, { ...ANNUAL_SAMPLE, threshold_percent: "70" }, "fnma.mi.b8104.2019-05", "B-8.1-04; 10.4-Q2"),
  V("NTC_MI_REFUND_ADVICE", REFUND_SOURCE, REFUND_RULES, REFUND_SAMPLE, "hpa.1998", "12 U.S.C. 4902(f); 10.5 annual-plan example"),
  V("NTC_HPA_4904B_DENIAL", DENIAL_SOURCE, DENIAL_RULES, DENIAL_SAMPLE, "hpa.1998", "12 U.S.C. 4904(b)(1); 10.6 LTV worked example"),
  V("NTC_MI_INFO_REQUEST", INFO_SOURCE, INFO_RULES, INFO_SAMPLE, "state.pmi.MN", "Minn. Stat. 47.207 subd. 4; 10.6-T6"),
  V("NTC_MI_CASE_CLOSED", CLOSED_SOURCE, CLOSED_RULES, CLOSED_SAMPLE, "hpa.1998", "10.6 outputs (policy)"),
];
