/**
 * §25.2 process-owned notice versions (V(code, source, rules, sample, ruleSet, formBasis) from ./section01.ts) and
 * per-code channel/combination overrides. Spread by ../catalog.ts after the servicing files, so a version here
 * supersedes one there for the same code and effective date.
 *
 * NTC_REGZ_1026_38_CD_CORRECTED — every Closing Disclosure after version 1 (same H-25 form as 25.1's NTC_REGZ_1026_38_CD,
 * with the corrected-version metadata the spec puts on `disclosures`: `cd_version`, `cd_reason` ∈ {pre_consummation_no_wait,
 * pre_consummation_new_wait, post_consummation_event, clerical, tolerance_refund}, the (f)(2)(ii) trigger(s) and the
 * new-waiting-period statement when (A)/(B)/(C) fired). Statutory content checked: (a)(2)–(5) incl. Loan ID # and MIC #;
 * (b) loan terms; (c) projected payments with the escrow statement; (d) costs at closing; (l)(7) escrow figures from 30.3
 * (escrowed costs over year 1 = 12 × monthly); (o)(1)–(5) with the (o)(4) APR and (o)(5) TIP statements at three decimals
 * ((t)(4)); (p); (r) NMLSR IDs (§1026.36(g)); (s) confirm receipt; (f)(5) no CD-preparation / disclosure-delivery fee.
 * NTC_REGZ_1026_38_SELLER_CD — the seller's Closing Disclosure the settlement agent provides "no later than the day of
 * consummation" (§1026.19(f)(4)(i)–(ii)); offered to agents on SM's portal, the agent remains the provider; (f)(4)(iv)
 * copy to the creditor. Content: the §1026.38 items "that relate to the seller's transaction" — (a)(3) closing
 * information, the seller and property, (f)–(g) seller-paid closing costs, (k) summary of the seller's transaction
 * (sale price, seller credits, payoffs, cash to seller), (r) settlement-agent contact; no consumer financing terms.
 */
import type { ContentRule, NoticeTemplate, VersionInput } from "../registry.ts";
import { V } from "./section01.ts";

const R = (rule_id: string, citation: string, kind: ContentRule["kind"], selector: string, message: string, extra: Partial<ContentRule> = {}): ContentRule => ({ rule_id, citation, kind, selector, severity: "block", message, ...extra });
const present = (...paths: string[]): Record<string, unknown> => ({ and: paths.map((p) => ({ present: p })) });
const MONTH = "(January|February|March|April|May|June|July|August|September|October|November|December) \\d{1,2}, \\d{4}";
const CD_REASONS = ["pre_consummation_no_wait", "pre_consummation_new_wait", "post_consummation_event", "clerical", "tolerance_refund"];

const CORRECTED_CD_SOURCE = `{{#block "heading" page=1 y=0.03 pt=16 bold}}Closing Disclosure{{/block}}
{{#block "corrected_banner" page=1 y=0.055 pt=10 bold}}Corrected Closing Disclosure — version {{cd_version}} issued {{date date_issued}}, replacing the Closing Disclosure issued {{date prior_date_issued}}. Reason: {{cd_reason_text}}.{{/block}}
{{#block "purpose" page=1 y=0.08 pt=10}}This form is a statement of final loan terms and closing costs. Compare this document with your Loan Estimate.{{/block}}
{{#block "waiting_period" page=1 y=0.1 pt=10 bold}}{{#if new_waiting_period}}Because {{trigger_text}}, you must receive this corrected Closing Disclosure at least three business days before consummation; your closing may occur no earlier than {{date earliest_consummation_date}}.{{else}}This corrected Closing Disclosure does not start a new waiting period; you will receive it at or before consummation.{{/if}}{{/block}}
{{#block "closing_information" page=1 y=0.13 pt=10}}Date Issued {{date date_issued}}. Closing Date {{date closing_date}}. Disbursement Date {{date disbursement_date}}. Settlement Agent {{settlement_agent_name}}. File # {{file_number}}. Property {{property_address}}. Appraised Prop. Value {{money appraised_value_cents}}.{{/block}}
{{#block "transaction_information" page=1 y=0.18 pt=10}}Borrower {{#each borrowers}}{{this}}; {{/each}}Lender {{creditor_name}}. Loan Term {{loan_term_years}} years. Purpose {{purpose}}. Product {{product}}. Loan Type {{loan_type}}. Loan ID # {{loan_id_number}}. MIC # {{mic_number}}.{{/block}}
{{#block "loan_terms" page=1 y=0.24 pt=11 bold}}Loan Terms{{/block}}
{{#block "loan_terms_body" page=1 y=0.26 pt=10}}Loan Amount {{money loan_amount_cents}}. Can this amount increase after closing? {{#if loan_amount_can_increase}}YES{{else}}NO{{/if}}. Interest Rate {{pct interest_rate_pct}}. Can this amount increase after closing? {{#if rate_can_increase}}YES{{else}}NO{{/if}}. Monthly Principal & Interest {{money pi_cents}}. Can this amount increase after closing? {{#if pi_can_increase}}YES{{else}}NO{{/if}}. Does the loan have these features? Prepayment Penalty {{#if prepayment_penalty}}YES{{else}}NO{{/if}}. Balloon Payment {{#if balloon_payment}}YES{{else}}NO{{/if}}.{{/block}}
{{#block "projected_payments" page=1 y=0.42 pt=11 bold}}Projected Payments{{/block}}
{{#block "projected_payments_body" page=1 y=0.44 pt=10}}Payment Calculation Years 1-{{loan_term_years}}: Principal & Interest {{money pi_cents}}; Mortgage Insurance {{money mi_cents}}; Estimated Escrow {{money escrow_cents}}; Estimated Total Monthly Payment {{money total_monthly_payment_cents}}. Estimated Taxes, Insurance & Assessments {{money taxes_insurance_assessments_monthly_cents}} a month. {{#if escrow}}In escrow? YES — property taxes, homeowner's insurance.{{else}}In escrow? NO.{{/if}}{{/block}}
{{#block "costs_at_closing" page=1 y=0.57 pt=11 bold}}Costs at Closing{{/block}}
{{#block "costs_at_closing_body" page=1 y=0.59 pt=10}}Closing Costs {{money closing_costs_cents}} includes {{money loan_costs_cents}} in Loan Costs + {{money other_costs_cents}} in Other Costs − {{money lender_credits_cents}} in Lender Credits. Cash to Close {{money cash_to_close_cents}}.{{/block}}
{{#block "changes" page=1 y=0.68 pt=10}}What changed from the prior version: {{#each changes}}{{this}}; {{/each}}{{/block}}
{{#block "escrow_account" page=4 y=0.05 pt=10}}Escrow Account. {{#if escrow}}For now, your loan will have an escrow account. Escrowed Property Costs over Year 1 {{money escrowed_property_costs_year1_cents}}. Non-Escrowed Property Costs over Year 1 {{money non_escrowed_property_costs_year1_cents}}. Initial Escrow Payment {{money initial_escrow_payment_cents}}. Monthly Escrow Payment {{money escrow_cents}}.{{else}}You will not have an escrow account. Property Costs over Year 1 {{money property_costs_year1_cents}}. Escrow Waiver Fee {{money escrow_waiver_fee_cents}}.{{/if}}{{/block}}
{{#block "loan_calculations" page=5 y=0.05 pt=11 bold}}Loan Calculations{{/block}}
{{#block "loan_calculations_body" page=5 y=0.07 pt=10}}Total of Payments. Total you will have paid after you make all payments of principal, interest, mortgage insurance, and loan costs, as scheduled. {{money total_of_payments_cents}}. Finance Charge. The dollar amount the loan will cost you. {{money finance_charge_cents}}. Amount Financed. The loan amount available after paying your upfront finance charge. {{money amount_financed_cents}}.{{/block}}
{{#block "apr" page=5 y=0.15 pt=10 bold}}Annual Percentage Rate (APR). Your costs over the loan term expressed as a rate. This is not your interest rate. {{pct apr}}{{/block}}
{{#block "tip" page=5 y=0.18 pt=10 bold}}Total Interest Percentage (TIP). The total amount of interest that you will pay over the loan term as a percentage of your loan amount. {{pct tip_pct}}{{/block}}
{{#block "other_disclosures" page=5 y=0.22 pt=10}}Other Disclosures. Appraisal: If the property was appraised for your loan, your lender is required to give you a copy at no additional cost at least 3 days before closing. Contract Details: See your note and security instrument for information about nonpayment, default, any required repayment in full before the scheduled date, and the rules for making payments before they are due. Liability after Foreclosure: {{#if state_antideficiency}}state law may protect you from liability for the unpaid balance.{{else}}you may have to pay any unpaid balance after foreclosure — consult an attorney.{{/if}} Refinance: Refinancing this loan will depend on your future financial situation, the property value, and market conditions. Tax Deductions: If you borrow more than this property is worth, the interest on the loan amount above this property's fair market value is not deductible from your federal income taxes. Consult a tax advisor.{{/block}}
{{#block "questions" page=5 y=0.42 pt=10}}Questions? If you have questions about the loan terms or costs on this form, use the contact information below. To get more information or make a complaint, contact the Consumer Financial Protection Bureau at www.consumerfinance.gov/mortgage-closing.{{/block}}
{{#block "contact_information" page=5 y=0.45 pt=10}}Contact Information. Lender {{creditor_name}}, {{creditor_address}}, NMLS ID {{creditor_nmlsr_id}}, Contact {{creditor_contact_name}}, Contact NMLS ID {{mlo_nmlsr_id}}, Email {{creditor_email}}, Phone {{creditor_phone}}. Settlement Agent {{settlement_agent_name}}, {{settlement_agent_address}}, License ID {{settlement_agent_license_id}}, Contact {{settlement_agent_contact}}, Phone {{settlement_agent_phone}}.{{/block}}
{{#block "confirm_receipt" page=5 y=0.7 pt=10 bold}}Confirm Receipt. By signing, you are only confirming that you have received this form. You do not have to accept this loan because you have signed or received this form. Applicant Signature / Date. Co-Applicant Signature / Date.{{/block}}`;

const CORRECTED_CD_RULES: ContentRule[] = [
  R("heading", "§1026.38(a)(2); H-25", "layout", "heading", "the form is titled Closing Disclosure", { layout: { page: 1, bold: true, minPt: 14 } }),
  R("corrected-banner", "§1026.19(f)(2); 25.2 data model cd_version / cd_reason", "presence", `Corrected Closing Disclosure — version \\d+ issued ${MONTH}, replacing the Closing Disclosure issued ${MONTH}\\. Reason: \\S`, "the corrected version, its issue date, the prior version's date and the (f)(2) reason"),
  R("cd-version-ge-2", "25.2 data model: cd_version int (1 = initial)", "data_range", "cd_version", "a corrected CD is version 2 or later", { range: { min: 2 } }),
  R("cd-reason-enum", "25.2 data model: cd_reason enum", "data_equality", "cd_reason", "cd_reason is one of the five correction reasons", { predicate: { in: [{ var: "cd_reason" }, CD_REASONS] } }),
  R("new-wait-statement", "§1026.19(f)(2)(ii)(A)–(C); (f)(1)(ii)(A)", "conditional", "you must receive this corrected Closing Disclosure at least three business days before consummation; your closing may occur no earlier than " + MONTH, "a new waiting period is stated with the earliest consummation date when trigger (A)/(B)/(C) fired", { when: { "==": [{ var: "new_waiting_period" }, true] }, predicate: { and: [{ present: "earliest_consummation_date" }, { present: "trigger_text" }, { "==": [{ var: "cd_reason" }, "pre_consummation_new_wait"] }] } }),
  R("no-wait-statement", "§1026.19(f)(2)(i)", "conditional", "does not start a new waiting period; you will receive it at or before consummation", "without a (f)(2)(ii) trigger the corrected CD is received at or before consummation", { when: { "==": [{ var: "new_waiting_period" }, false] }, predicate: { "!=": [{ var: "cd_reason" }, "pre_consummation_new_wait"] } }),
  R("a2-purpose", "§1026.38(a)(2)", "presence", "statement of final loan terms and closing costs\\. Compare this document with your Loan Estimate", "the (a)(2) statement of purpose"),
  R("a3-closing-information", "§1026.38(a)(3)", "data_equality", "date_issued,closing_date,disbursement_date,settlement_agent_name,file_number,property_address", "date issued, closing date, disbursement date, settlement agent, file number and property", { predicate: present("date_issued", "closing_date", "disbursement_date", "settlement_agent_name", "file_number", "property_address") }),
  R("a4-a5-parties", "§1026.38(a)(4)–(5) incl. (a)(5)(v) Loan ID #, (a)(5)(vi) MIC #", "data_equality", "borrowers,creditor_name,loan_term_years,purpose,product,loan_type,loan_id_number,mic_number", "borrower(s), creditor, loan term, purpose, product, loan type, loan ID and MIC #", { predicate: present("borrowers", "creditor_name", "loan_term_years", "purpose", "product", "loan_type", "loan_id_number", "mic_number") }),
  R("b-loan-terms", "§1026.38(b); §1026.37(b)", "presence", "Loan Amount \\$[\\d,]+\\.\\d{2}\\. Can this amount increase after closing\\? (YES|NO)\\. Interest Rate \\d+\\.\\d{3}%.*Monthly Principal & Interest \\$[\\d,]+\\.\\d{2}", "loan amount, interest rate and monthly P&I with the increase questions"),
  R("b-features", "§1026.38(b); §1026.37(b)(4)", "presence", "Prepayment Penalty (YES|NO)\\. Balloon Payment (YES|NO)", "prepayment-penalty and balloon features answered"),
  R("c-projected-payments", "§1026.38(c)", "presence", "Projected Payments.*Principal & Interest \\$[\\d,]+\\.\\d{2}; Mortgage Insurance \\$[\\d,]+\\.\\d{2}; Estimated Escrow \\$[\\d,]+\\.\\d{2}; Estimated Total Monthly Payment \\$[\\d,]+\\.\\d{2}", "projected payments table"),
  R("c-escrow-statement", "§1026.38(c)(4)", "presence", "In escrow\\? (YES|NO)", "escrow statement in the projected payments"),
  R("d-costs-at-closing", "§1026.38(d)", "presence", "Closing Costs \\$[\\d,]+\\.\\d{2} includes \\$[\\d,]+\\.\\d{2} in Loan Costs \\+ \\$[\\d,]+\\.\\d{2} in Other Costs − \\$[\\d,]+\\.\\d{2} in Lender Credits\\. Cash to Close \\$[\\d,]+\\.\\d{2}", "costs at closing summary"),
  R("changes-listed", "§1026.19(f)(2) 'corrected disclosures reflecting any changed terms'", "presence", "What changed from the prior version: \\S+", "the changed terms are listed"),
  R("l7-escrow-account", "§1026.38(l)(7)", "conditional", "Escrowed Property Costs over Year 1 \\$[\\d,]+\\.\\d{2}\\. Non-Escrowed Property Costs over Year 1 \\$[\\d,]+\\.\\d{2}\\. Initial Escrow Payment \\$[\\d,]+\\.\\d{2}\\. Monthly Escrow Payment \\$[\\d,]+\\.\\d{2}", "the four (l)(7) escrow figures when an escrow account is established", { when: { "==": [{ var: "escrow" }, true] }, predicate: present("escrowed_property_costs_year1_cents", "non_escrowed_property_costs_year1_cents", "initial_escrow_payment_cents", "escrow_cents") }),
  R("l7-no-escrow", "§1026.38(l)(7)(i)(B)", "conditional", "You will not have an escrow account\\. Property Costs over Year 1 \\$[\\d,]+\\.\\d{2}\\. Escrow Waiver Fee \\$[\\d,]+\\.\\d{2}", "the no-escrow statement with property costs and any waiver fee", { when: { "==": [{ var: "escrow" }, false] }, predicate: present("property_costs_year1_cents", "escrow_waiver_fee_cents") }),
  R("o1-total-of-payments", "§1026.38(o)(1)", "presence", "Total of Payments\\. Total you will have paid after you make all payments of principal, interest, mortgage insurance, and loan costs, as scheduled\\. \\$[\\d,]+\\.\\d{2}", "total of payments with its statement"),
  R("o2-finance-charge", "§1026.38(o)(2)", "presence", "Finance Charge\\. The dollar amount the loan will cost you\\. \\$[\\d,]+\\.\\d{2}", "finance charge with its statement"),
  R("o3-amount-financed", "§1026.38(o)(3)", "presence", "Amount Financed\\. The loan amount available after paying your upfront finance charge\\. \\$[\\d,]+\\.\\d{2}", "amount financed with its statement"),
  R("o4-apr-statement", "§1026.38(o)(4); (t)(4)(ii)", "presence", "Annual Percentage Rate \\(APR\\)\\. Your costs over the loan term expressed as a rate\\. This is not your interest rate\\. \\d+\\.\\d{3}%", "APR with the (o)(4) statement, three decimals"),
  R("o5-tip-statement", "§1026.38(o)(5); (t)(4)(ii)", "presence", "Total Interest Percentage \\(TIP\\)\\. The total amount of interest that you will pay over the loan term as a percentage of your loan amount\\. \\d+\\.\\d{3}%", "TIP with the (o)(5) statement, three decimals"),
  R("o-loan-calculations-data", "§1026.38(o); 25.1 apr_calculations", "data_equality", "total_of_payments_cents,finance_charge_cents,amount_financed_cents,apr,tip_pct,apr_calculation_id", "loan calculations come from the checkpoint apr_calculations row", { predicate: { and: [{ ">": [{ var: "total_of_payments_cents" }, 0] }, { ">": [{ var: "finance_charge_cents" }, 0] }, { ">": [{ var: "amount_financed_cents" }, 0] }, { present: "apr" }, { present: "tip_pct" }, { present: "apr_calculation_id" }] } }),
  R("o-amount-financed-le-loan", "comment 18(b); §1026.38(o)(3)", "data_equality", "amount_financed_cents,loan_amount_cents", "amount financed never exceeds the loan amount", { predicate: { "<=": [{ var: "amount_financed_cents" }, { var: "loan_amount_cents" }] } }),
  R("apr-range", "§1026.22; §1026.38(t)(4)", "data_range", "apr", "APR is a percentage between 0 and 30", { range: { min: 0, max: 30 } }),
  R("apr-prominent", "§1026.38(o)(4); H-25 page 5", "layout", "apr", "APR block on page 5, bold", { layout: { page: 5, bold: true } }),
  R("p-other-disclosures", "§1026.38(p)", "presence", "Appraisal:.*Contract Details:.*Liability after Foreclosure:.*Refinance:.*Tax Deductions:", "the (p) other disclosures"),
  R("q-questions", "§1026.38(q)", "presence", "Questions\\? If you have questions about the loan terms or costs on this form, use the contact information below", "the (q) questions notice"),
  R("r-contact-nmlsr", "§1026.38(r); §1026.36(g)(2)(ii)", "data_equality", "creditor_name,creditor_nmlsr_id,creditor_contact_name,mlo_nmlsr_id", "the creditor's name and NMLSR ID and the loan originator's name and NMLSR ID", { predicate: { and: [{ present: "creditor_name" }, { matches: ["creditor_nmlsr_id", "^\\d{3,}$"] }, { present: "creditor_contact_name" }, { matches: ["mlo_nmlsr_id", "^\\d{3,}$"] }] } }),
  R("r-contact-text", "§1026.38(r)", "presence", "Lender \\S.*NMLS ID \\d{3,}, Contact \\S.*Contact NMLS ID \\d{3,}.*Settlement Agent \\S.*License ID", "contact block rendered with both NMLSR IDs and the settlement agent"),
  R("s-confirm-receipt", "§1026.38(s)", "presence", "By signing, you are only confirming that you have received this form\\. You do not have to accept this loan because you have signed or received this form", "confirm-receipt statement"),
  R("f5-no-cd-fee", "§1026.19(f)(5); 25.2-T14", "absence", "(CD preparation fee|disclosure delivery fee)", "no fee may be imposed for preparing or delivering the Closing Disclosure"),
  R("closing-not-before-disbursement", "§1026.38(a)(3)(ii)–(iii)", "data_range", "days_closing_to_disbursement", "disbursement date is on or after the closing date", { range: { min: 0 } }),
];
/** Worked example 5 (INT-O6-2): buydown on Wed Nov 4, 2026 to 5.875% with 0.750 discount points — actual APR 5.979 vs disclosed 6.159 → (f)(2)(ii)(A) → corrected CD v2 e-signed Nov 4 → earliest consummation Sat Nov 7; P&I $3,312.61. */
const CORRECTED_CD_SAMPLE: Record<string, unknown> = {
  cd_version: 2, cd_reason: "pre_consummation_new_wait", cd_reason_text: "the annual percentage rate changed by more than 1/8 of one percentage point (12 CFR 1026.19(f)(2)(ii)(A))", new_waiting_period: true, trigger_text: "the annual percentage rate became inaccurate (12 CFR 1026.22)", earliest_consummation_date: "2026-11-07", prior_date_issued: "2026-11-02",
  changes: ["Interest rate 6.125% → 5.875% (0.750 discount points $4,200.00)", "Monthly Principal & Interest $3,402.62 → $3,312.61", "APR 6.159% → 5.979%"],
  date_issued: "2026-11-04", closing_date: "2026-11-09", disbursement_date: "2026-11-13", days_closing_to_disbursement: 4, settlement_agent_name: "Desert Title Agency LLC", file_number: "DT-2026-11841", property_address: "4821 E Camelback Rd, Phoenix AZ 85018", appraised_value_cents: 80_000_000n,
  borrowers: ["Alex Rivera", "Jordan Rivera"], creditor_name: "Partner Bank, N.A.", loan_term_years: 30, purpose: "Refinance", product: "Fixed Rate", loan_type: "Conventional", loan_id_number: "APP-REFI-1", mic_number: "N/A",
  loan_amount_cents: 56_000_000n, loan_amount_can_increase: false, interest_rate_pct: "5.875", rate_can_increase: false, pi_cents: 331_261n, pi_can_increase: false, prepayment_penalty: false, balloon_payment: false,
  mi_cents: 0n, escrow_cents: 52_500n, total_monthly_payment_cents: 383_761n, taxes_insurance_assessments_monthly_cents: 52_500n, escrow: true, escrowed_property_costs_year1_cents: 630_000n, non_escrowed_property_costs_year1_cents: 0n, initial_escrow_payment_cents: 187_500n,
  closing_costs_cents: 965_452n, loan_costs_cents: 800_952n, other_costs_cents: 164_500n, lender_credits_cents: 0n, cash_to_close_cents: 965_452n,
  total_of_payments_cents: 119_253_960n, finance_charge_cents: 63_675_955n, amount_financed_cents: 55_578_005n, apr: "5.979", tip_pct: "112.971", apr_calculation_id: "APP-REFI-1:corrected_cd:appendix_j_exact:2026-11-04", state_antideficiency: true,
  creditor_address: "100 Partner Plaza, Phoenix AZ 85004", creditor_nmlsr_id: "123456", creditor_contact_name: "Jordan Lee", mlo_nmlsr_id: "987654", creditor_email: "jlee@partnerbank.example", creditor_phone: "(602) 555-0100",
  settlement_agent_address: "2 Title Way, Phoenix AZ 85012", settlement_agent_license_id: "AZ-TA-4471", settlement_agent_contact: "Sam Ortiz", settlement_agent_phone: "(602) 555-0177",
};

const SELLER_CD_SOURCE = `{{#block "heading" page=1 y=0.03 pt=16 bold}}Closing Disclosure{{/block}}
{{#block "seller_banner" page=1 y=0.06 pt=10 bold}}Seller's Closing Disclosure — provided by the settlement agent, {{settlement_agent_name}}, to the seller no later than the day of consummation (12 CFR 1026.19(f)(4)). This form shows the terms and costs that relate to the seller's transaction.{{/block}}
{{#block "closing_information" page=1 y=0.1 pt=10}}Date Issued {{date date_issued}}. Closing Date {{date closing_date}}. Disbursement Date {{date disbursement_date}}. Settlement Agent {{settlement_agent_name}}. File # {{file_number}}. Property {{property_address}}. Sale Price {{money sale_price_cents}}.{{/block}}
{{#block "transaction_information" page=1 y=0.15 pt=10}}Seller {{#each sellers}}{{this}}; {{/each}}Borrower {{#each borrowers}}{{this}}; {{/each}}Lender {{creditor_name}}.{{/block}}
{{#block "seller_paid_costs" page=2 y=0.05 pt=11 bold}}Closing Cost Details — Seller-Paid{{/block}}
{{#block "seller_paid_costs_body" page=2 y=0.07 pt=10}}{{#each seller_paid_costs}}{{description}} {{money amount_cents}} ({{timing}}); {{/each}}Total Seller-Paid Closing Costs {{money seller_paid_total_cents}}.{{/block}}
{{#block "summary_seller" page=3 y=0.05 pt=11 bold}}Summary of Seller's Transaction{{/block}}
{{#block "summary_seller_body" page=3 y=0.07 pt=10}}Due to Seller at Closing {{money due_to_seller_cents}}: Sale Price of Property {{money sale_price_cents}}{{#if personal_property_cents}}; Sale Price of Any Personal Property Included in Sale {{money personal_property_cents}}{{/if}}. Adjustments for Items Paid by Seller in Advance {{money paid_in_advance_cents}}. Due from Seller at Closing {{money due_from_seller_cents}}: Excess Deposit {{money excess_deposit_cents}}; Closing Costs Paid at Closing {{money seller_paid_total_cents}}; Payoff of First Mortgage Loan {{money payoff_first_mortgage_cents}}; Payoff of Second Mortgage Loan {{money payoff_second_mortgage_cents}}; Seller Credit {{money seller_credit_cents}}. Adjustments for Items Unpaid by Seller {{money unpaid_by_seller_cents}}. Calculation: Total Due to Seller at Closing {{money due_to_seller_cents}} − Total Due from Seller at Closing {{money due_from_seller_cents}} = Cash {{#if cash_to_seller}}To{{else}}From{{/if}} Seller {{money cash_to_from_seller_cents}}.{{/block}}
{{#block "creditor_copy" page=3 y=0.4 pt=10}}A copy of this disclosure is provided to the creditor, {{creditor_name}}, by the settlement agent (12 CFR 1026.19(f)(4)(iv)). The consumer's Closing Disclosure is provided separately; the consumer's loan terms are not shown on this form.{{/block}}
{{#block "contact_information" page=3 y=0.5 pt=10}}Contact Information. Settlement Agent {{settlement_agent_name}}, {{settlement_agent_address}}, License ID {{settlement_agent_license_id}}, Contact {{settlement_agent_contact}}, Phone {{settlement_agent_phone}}. Seller's Real Estate Broker {{seller_broker_name}}, License ID {{seller_broker_license_id}}.{{/block}}`;

const SELLER_CD_RULES: ContentRule[] = [
  R("heading", "§1026.38(a)(2); (t)(5)(v)–(vi)", "layout", "heading", "the form is titled Closing Disclosure", { layout: { page: 1, bold: true, minPt: 14 } }),
  R("f4-provider", "§1026.19(f)(4)(i)–(ii)", "presence", "Seller's Closing Disclosure — provided by the settlement agent, \\S.* to the seller no later than the day of consummation", "the settlement agent is the provider; timing no later than the day of consummation"),
  R("a3-closing-information", "§1026.38(a)(3)", "data_equality", "date_issued,closing_date,disbursement_date,settlement_agent_name,file_number,property_address,sale_price_cents", "closing information and the sale price", { predicate: present("date_issued", "closing_date", "disbursement_date", "settlement_agent_name", "file_number", "property_address", "sale_price_cents") }),
  R("a3-dates-text", "§1026.38(a)(3)(i)–(iii)", "presence", `Date Issued ${MONTH}\\. Closing Date ${MONTH}\\. Disbursement Date ${MONTH}`, "dates rendered as dates"),
  R("a4-seller", "§1026.38(a)(4); (t)(5)(v)", "data_equality", "sellers,borrowers,creditor_name", "seller(s), borrower(s) and creditor named", { predicate: { and: [{ present: "sellers" }, { present: "borrowers" }, { present: "creditor_name" }] } }),
  R("seller-paid-costs", "§1026.38(f)–(g) seller-paid columns; (t)(5)(v)", "presence", "Closing Cost Details — Seller-Paid.*Total Seller-Paid Closing Costs \\$[\\d,]+\\.\\d{2}", "seller-paid closing costs itemized with the total"),
  R("k-summary", "§1026.38(k)(1)–(3)", "presence", "Summary of Seller's Transaction.*Due to Seller at Closing \\$[\\d,]+\\.\\d{2}: Sale Price of Property \\$[\\d,]+\\.\\d{2}.*Due from Seller at Closing \\$[\\d,]+\\.\\d{2}.*Payoff of First Mortgage Loan \\$[\\d,]+\\.\\d{2}.*Seller Credit \\$[\\d,]+\\.\\d{2}", "the (k) summary: due to seller, due from seller, payoffs and seller credit"),
  R("k3-calculation", "§1026.38(k)(3)", "presence", "Calculation: Total Due to Seller at Closing \\$[\\d,]+\\.\\d{2} − Total Due from Seller at Closing \\$[\\d,]+\\.\\d{2} = Cash (To|From) Seller \\$[\\d,]+\\.\\d{2}", "the cash to/from seller calculation"),
  R("k3-arithmetic", "§1026.38(k)(3)(iii)", "data_equality", "due_to_seller_cents,due_from_seller_cents,cash_to_from_seller_cents", "cash to/from seller = due to − due from (absolute)", { predicate: { or: [{ and: [{ "==": [{ var: "cash_to_seller" }, true] }, { ">=": [{ var: "due_to_seller_cents" }, { var: "due_from_seller_cents" }] }] }, { and: [{ "==": [{ var: "cash_to_seller" }, false] }, { "<": [{ var: "due_to_seller_cents" }, { var: "due_from_seller_cents" }] }] }] } }),
  R("f4iv-creditor-copy", "§1026.19(f)(4)(iv)", "presence", "A copy of this disclosure is provided to the creditor, \\S.*by the settlement agent", "the creditor-copy statement"),
  R("no-consumer-terms", "§1026.38(t)(5)(v)–(vi): the seller's form omits the consumer's financing", "absence", "(Annual Percentage Rate|Loan Amount \\$|Monthly Principal & Interest|Finance Charge\\.)", "the consumer's loan terms and calculations are not on the seller's form"),
  R("r-settlement-agent", "§1026.38(r)", "presence", "Settlement Agent \\S.*License ID \\S.*Contact \\S.*Phone \\S.*Seller's Real Estate Broker \\S", "settlement agent and seller's broker contact information"),
  R("f5-no-cd-fee", "§1026.19(f)(5)", "absence", "(CD preparation fee|disclosure delivery fee)", "no fee for preparing or delivering the disclosure"),
];
/** Purchase fixture (Columbus, OH; closing Wed Nov 18, 2026): sale price $457,800.00, seller-paid costs and the (k) summary; cash to seller. */
const SELLER_CD_SAMPLE: Record<string, unknown> = {
  date_issued: "2026-11-18", closing_date: "2026-11-18", disbursement_date: "2026-11-19", settlement_agent_name: "Buckeye Title Agency LLC", file_number: "BT-2026-20417", property_address: "1180 Neil Ave, Columbus OH 43201", sale_price_cents: 45_780_000n, personal_property_cents: 0n,
  sellers: ["Morgan Hale"], borrowers: ["Taylor Brooks", "Casey Brooks"], creditor_name: "Partner Bank, N.A.",
  seller_paid_costs: [{ description: "Real estate commission — listing broker", amount_cents: 1_373_400n, timing: "at closing" }, { description: "Real estate commission — buyer's broker", amount_cents: 1_373_400n, timing: "at closing" }, { description: "Owner's title insurance policy", amount_cents: 165_000n, timing: "at closing" }, { description: "County conveyance fee", amount_cents: 91_560n, timing: "at closing" }],
  seller_paid_total_cents: 3_003_360n, due_to_seller_cents: 45_780_000n, paid_in_advance_cents: 0n, excess_deposit_cents: 0n, payoff_first_mortgage_cents: 21_450_000n, payoff_second_mortgage_cents: 0n, seller_credit_cents: 500_000n, unpaid_by_seller_cents: 312_500n, due_from_seller_cents: 25_265_860n, cash_to_seller: true, cash_to_from_seller_cents: 20_514_140n,
  settlement_agent_address: "88 N High St, Columbus OH 43215", settlement_agent_license_id: "OH-TA-2210", settlement_agent_contact: "Riley Chen", settlement_agent_phone: "(614) 555-0142", seller_broker_name: "Capital City Realty", seller_broker_license_id: "OH-BRK-77012",
};

export const VERSIONS_25_2: VersionInput[] = [
  V("NTC_REGZ_1026_38_CD_CORRECTED", CORRECTED_CD_SOURCE, CORRECTED_CD_RULES, CORRECTED_CD_SAMPLE, "regz.trid.2017", "12 CFR 1026.38 / form H-25 (corrected Closing Disclosure under 12 CFR 1026.19(f)(2)); 25.2 worked example 5 figures"),
  V("NTC_REGZ_1026_38_SELLER_CD", SELLER_CD_SOURCE, SELLER_CD_RULES, SELLER_CD_SAMPLE, "regz.trid.2017", "12 CFR 1026.38(t)(5)(v)–(vi) seller's Closing Disclosure; 12 CFR 1026.19(f)(4); 25.2 purchase fixture"),
];
export const OVERRIDES_25_2: Record<string, Partial<NoticeTemplate>> = {
  NTC_REGZ_1026_38_CD_CORRECTED: { name: "Corrected Closing Disclosure (H-25)", citation: "12 CFR 1026.19(f)(2); 12 CFR 1026.38; form H-25", noticeClass: "trid_disclosures", channelPolicy: "esign_or_mail", separateDocument: true, mayCombineWith: [], retention: "regz_cd_5y", piiLevel: "high" },
  NTC_REGZ_1026_38_SELLER_CD: { name: "Seller's Closing Disclosure (H-25, settlement agent)", citation: "12 CFR 1026.19(f)(4); 12 CFR 1026.38(t)(5)(v)–(vi)", noticeClass: "trid_disclosures", channelPolicy: "esign_or_mail", separateDocument: true, mayCombineWith: [], retention: "regz_cd_5y", piiLevel: "high" },
};
