/**
 * §24.5 process-owned notice versions (V(code, source, rules, sample, ruleSet, formBasis) from ./section01.ts) and
 * per-code channel/combination overrides. Spread by ../catalog.ts after the servicing files, so a version here
 * supersedes one there for the same code and effective date.
 *
 *   NTC_FDPA_4104A_FLOOD_NOTICE   "Notice of Special Flood Hazards and Availability of Federal Disaster Relief Assistance"
 *                                 (42 U.S.C. 4104a(a)(3); 12 CFR Part 22 Appendix A sample form as the model): the SFHA
 *                                 warning for the property and its community, the description of the §102(b) FDPA purchase
 *                                 requirement, NFIP and private-insurer availability (the 42 U.S.C. 4012a(b)(7) private
 *                                 policy statement), the federal disaster relief statement (participating community, or the
 *                                 non-participating warning), the escrow statement where applicable, the "reasonable time"
 *                                 statement (10 days; short-period acknowledgment), an acknowledgment block, automation.
 *                                 Delivered on every SFHA loan even though the statute reaches the non-bank partner through
 *                                 Fannie Mae (B7-3-06) — e-delivery under E-SIGN consent scope `flood_notice`, else mail.
 */
import type { ContentRule, NoticeTemplate, VersionInput } from "../registry.ts";
import { V } from "./section01.ts";

const R = (rule_id: string, citation: string, kind: ContentRule["kind"], selector: string, message: string, extra: Partial<ContentRule> = {}): ContentRule => ({ rule_id, citation, kind, selector, severity: "block", message, ...extra });
const DATE_RULE = R("date", "notice date", "presence", "(January|February|March|April|May|June|July|August|September|October|November|December) \\d{1,2}, \\d{4}", "date of the notice");
const AUTOMATION = R("automation", "baseline §8.10 / 24.5 AI agent design: the notice discloses automation", "presence", "prepared by an automated system", "automation disclosure");

// ------------------------------------------------------------------ NTC_FDPA_4104A_FLOOD_NOTICE
const FLOOD_NOTICE = `{{#block "heading" page=1 y=0.05 pt=14 bold}}Notice of Special Flood Hazards and Availability of Federal Disaster Relief Assistance{{/block}}
{{#block "parties" page=1 y=0.1 pt=11}}{{date notice_date}}. From {{partner_name}} (loan number ending {{loan_number_last4}}). To: {{#each borrower_names}}{{this}}; {{/each}}Property: {{property_address}}.{{/block}}
{{#block "warning" page=1 y=0.17 pt=11 bold}}We are giving you this notice to inform you that the building or mobile home securing the loan for which you have applied is or will be located in an area with special flood hazards. The area has been identified by the Administrator of the Federal Emergency Management Agency (FEMA) as a special flood hazard area using FEMA's Flood Insurance Rate Map or the Flood Hazard Boundary Map for the community ({{community_number}}, map panel {{map_panel}}, flood zone {{flood_zone}}; Standard Flood Hazard Determination Form {{sfhdf_form_version}}). This area has at least a one percent (1%) chance of a flood equal to or exceeding the base flood elevation (a 100-year flood) in any given year. During the life of a 30-year mortgage loan, the risk of a 100-year flood in a special flood hazard area is 26 percent (26%).{{/block}}
{{#block "purchase" page=1 y=0.38 pt=11}}Federal law allows a lender and borrower jointly to request the Administrator of FEMA to review the determination of whether the property securing the loan is located in a special flood hazard area. If you would like to make such a request, please contact us for further information. Under section 102(b) of the Flood Disaster Protection Act of 1973, flood insurance is required for the term of the loan on the building or mobile home securing the loan, in an amount at least equal to the lesser of the outstanding principal balance of the loan, the maximum amount available under the National Flood Insurance Program (NFIP), or the replacement cost of the building. Flood insurance coverage under the NFIP may be purchased through an insurance agent who will obtain the policy either directly through the NFIP or through an insurance company that participates in the NFIP. Flood insurance that provides the same level of coverage as a standard flood insurance policy under the NFIP may be available from private insurers that do not participate in the NFIP, and we must accept a private flood insurance policy that meets the requirements of federal law. You should compare the flood insurance coverage, deductibles, exclusions, conditions and premiums associated with flood insurance policies issued on behalf of the NFIP and policies issued on behalf of private insurance companies, and contact an insurance agent as to the availability, cost, and comparisons of flood insurance coverage.{{/block}}
{{#block "relief" page=1 y=0.66 pt=11}}{{#if community_participating}}Flood insurance coverage under the NFIP is available for the community in which the property is located. Federal disaster relief assistance (usually in the form of a low-interest loan) may be available for damages incurred in excess of your flood insurance if your community's participation in the NFIP is in accordance with NFIP requirements.{{else}}Flood insurance coverage under the NFIP is not available for the property securing the loan because the community in which the property is located does not participate in the NFIP. In addition, if the non-participating community has been identified for at least one year as containing a special flood hazard area, properties located in the community will not be eligible for federal disaster relief assistance in the event of a federally declared flood disaster.{{/if}}{{/block}}
{{#block "escrow" page=2 y=0.05 pt=11}}{{#if escrow_statement_applies}}Escrow requirement for residential loans: federal law may require a lender or its servicer to escrow all premiums and fees for flood insurance that covers any residential building or mobile home securing a loan that is located in an area with special flood hazards. If your lender or servicer escrows flood insurance premiums and fees, they will be paid to the flood insurance provider from the escrow account and your total monthly payment will include the flood insurance portion. {{#if escrow_required}}Your loan will include an escrow account for flood insurance premiums.{{else}}Your loan may be made without an escrow account for flood insurance premiums; if so, you will pay the premiums directly to the insurer.{{/if}}{{else}}Your lender is not a regulated lending institution under the National Flood Insurance Act; flood insurance premiums are escrowed when your loan has an escrow account or when federal law otherwise requires it.{{/if}}{{/block}}
{{#block "timing" page=2 y=0.2 pt=11}}You are receiving this notice a reasonable time before your loan closes so that you can obtain flood insurance: evidence of coverage, applied for and paid at or before closing, is required before the loan can be completed.{{#if scheduled_consummation_date}} Your closing is currently scheduled for {{date scheduled_consummation_date}}.{{/if}} If fewer than {{reasonable_period_days}} days remain before your scheduled closing, we will ask you to acknowledge that you received this notice before signing, and you may ask us to reschedule.{{/block}}
{{#block "acknowledgment" page=2 y=0.35 pt=11 bold}}Acknowledgment: I/we have received this Notice of Special Flood Hazards and Availability of Federal Disaster Relief Assistance. Borrower signature(s) and date: ______________________ ______________________{{/block}}
{{#block "contact" page=2 y=0.85 pt=10}}Questions: {{partner_name}} at {{contact_phone}}. This notice was prepared by an automated system on behalf of {{partner_name}}; it is delivered on every loan secured by property in a special flood hazard area.{{/block}}`;
const FLOOD_NOTICE_RULES: ContentRule[] = [
  DATE_RULE, AUTOMATION,
  R("heading-layout", "42 U.S.C. 4104a(a)(3); 12 CFR 22.9(b) / Appendix A: the notice title", "layout", "heading", "heading on page 1, ≥ 12 pt, bold", { layout: { page: 1, minPt: 12, bold: true } }),
  R("sfha-warning", "42 U.S.C. 4104a(a)(3)(A): a warning that the building is located in a special flood hazard area", "presence", "is or will be located in an area with special flood hazards", "the SFHA warning"),
  R("warning-bold", "Appendix A: the warning stands out", "layout", "warning", "warning block bold", { layout: { page: 1, bold: true } }),
  R("community-zone", "SFHDF FF-206-FY-21-116: community, panel and zone from the determination", "presence", "for the community \\([0-9A-Za-z-]+, map panel [0-9A-Za-z-]+, flood zone [AV][0-9A-Z]*;", "community number, map panel and an A/V zone stated"),
  R("purchase-requirement", "42 U.S.C. 4104a(a)(3)(B): a description of the flood insurance purchase requirements under section 102(b)", "presence", "Under section 102\\(b\\) of the Flood Disaster Protection Act of 1973, flood insurance is required for the term of the loan", "the §102(b) purchase requirement described"),
  R("amount", "42 U.S.C. 4012a(b)(1); B7-3-06: lesser of UPB, NFIP maximum, replacement cost", "presence", "lesser of the outstanding principal balance of the loan, the maximum amount available under the National Flood Insurance Program \\(NFIP\\), or the replacement cost of the building", "the amount statement"),
  R("nfip-availability", "42 U.S.C. 4104a(a)(3)(C): coverage may be purchased under the NFIP", "presence", "Flood insurance coverage under the NFIP may be purchased through an insurance agent", "NFIP availability"),
  R("private-availability", "42 U.S.C. 4104a(a)(3)(C); 4012a(b)(7): also available from private insurers; must be accepted", "presence", "may be available from private insurers that do not participate in the NFIP, and we must accept a private flood insurance policy", "private-insurer availability and acceptance"),
  R("fema-review", "42 U.S.C. 4104b(e): joint request to FEMA to review the determination", "presence", "jointly to request the Administrator of FEMA to review the determination", "FEMA review right"),
  R("disaster-relief-participating", "42 U.S.C. 4104a(a)(3)(D); Appendix A: federal disaster relief statement for a participating community", "presence", "Federal disaster relief assistance \\(usually in the form of a low-interest loan\\) may be available", "disaster relief statement", { when: { "==": [{ var: "community_participating" }, true] } }),
  R("disaster-relief-nonparticipating", "Appendix A: non-participating community warning", "presence", "does not participate in the NFIP", "non-participating warning", { when: { "==": [{ var: "community_participating" }, false] } }),
  R("escrow-statement", "42 U.S.C. 4012a(d); 12 CFR 22.9(b)(4): escrow statement where the escrow requirement applies", "presence", "Escrow requirement for residential loans", "escrow statement when the requirement applies", { when: { "==": [{ var: "escrow_statement_applies" }, true] } }),
  R("reasonable-time", "2022 Interagency Q&A Notice 3: 10 days generally reasonable; 24.5 rule 5 short-period path", "presence", "If fewer than 10 days remain before your scheduled closing, we will ask you to acknowledge", "reasonable-time statement with the 10-day figure"),
  R("acknowledgment-block", "12 CFR 22.9(d): record of receipt — the borrower's acknowledgment", "presence", "Acknowledgment: I/we have received this Notice", "acknowledgment block"),
  R("in-sfha", "24.5 guardrail: the notice is rendered for SFHA determinations only", "data_equality", "in_sfha", "the determination is in an SFHA", { predicate: { "==": [{ var: "in_sfha" }, true] } }),
  R("zone-is-sfha", "B7-3-06: SFHA zones begin with A or V", "data_equality", "flood_zone", "flood zone begins with A or V", { predicate: { matches: ["flood_zone", "^[AV]"] } }),
  R("no-threat", "UDAAP", "absence", "(you must sign today|no other option|we will cancel your application)", "no pressure language"),
];
/** Worked example (rule 5 / T4): Zone AE determination received Tue Oct 6, 2026; the notice e-delivered Wed Oct 7 for the Fri Nov 6 consummation (30 days); escrowed refinance fixture. */
const FLOOD_NOTICE_SAMPLE = { notice_date: "2026-10-07", partner_name: "Partner Bank, N.A.", borrower_names: ["Alex Fixture"], property_address: "4120 N 44th St, Phoenix AZ 85018", loan_number_last4: "0917", community_number: "040051", map_panel: "04013C2210M", flood_zone: "AE", sfhdf_form_version: "FF-206-FY-21-116", in_sfha: true, community_participating: true,
  escrow_statement_applies: true, escrow_required: true, scheduled_consummation_date: "2026-11-06", reasonable_period_days: 10, contact_phone: "1-800-555-0142", language: "en", acknowledgment_required: true };

export const VERSIONS_24_5: VersionInput[] = [
  V("NTC_FDPA_4104A_FLOOD_NOTICE", FLOOD_NOTICE, FLOOD_NOTICE_RULES, FLOOD_NOTICE_SAMPLE, "fdpa.4012a / 42 U.S.C. 4104a(a)(3), 4012a(b)(1), (b)(7), (d); 12 CFR 22.9 and Part 22 Appendix A (model); 2022 Interagency Q&A Notice 3", "24.5 rule 5 — Zone AE variant of the refinance fixture (received Tue Oct 6, 2026; e-signed Wed Oct 7; consummation Fri Nov 6)"),
];
export const OVERRIDES_24_5: Record<string, Partial<NoticeTemplate>> = {
  NTC_FDPA_4104A_FLOOD_NOTICE: { citation: "42 U.S.C. 4104a(a); 12 CFR 22.9 / Part 22 Appendix A (model form); Selling Guide B7-3-06", noticeClass: "disclosures.origination", channelPolicy: "esign_or_mail", separateDocument: true, mayCombineWith: [], retention: "fdpa_life_of_loan", piiLevel: "medium" },
};
