/**
 * Authored template versions for the §13 foreclosure notices: the E-3.4-01
 * expedited-review result (13.2); the state pre-foreclosure notices — NY RPAPL
 * §1304, NJ FFA notice of intention, MA c.244 §35A right to cure, TX §51.002(d)
 * default notice, MD §7-105.1 notice of intent, CA §2923.5 and WA RCW
 * 61.24.031 due-diligence letters, NV NRS 107.5xx and GA §44-14-162.2 — plus
 * the referral advice and reinstatement quote (13.3); the SCRA rights,
 * stay-confirmation and 90-day status-check letters (13.8); and the SCRA rate
 * confirmation, overpayment election and rate-end letters (13.9). Statutory
 * mailings are mail-only (E-SIGN consent never substitutes for certified mail).
 */
import type { ContentRule, VersionInput } from "../registry.ts";
import { V } from "./section01.ts";

const R = (rule_id: string, citation: string, kind: ContentRule["kind"], selector: string, message: string, extra: Partial<ContentRule> = {}): ContentRule => ({ rule_id, citation, kind, selector, severity: "block", message, ...extra });
const DATE_RULE = R("date", "notice date", "presence", "(January|February|March|April|May|June|July|August|September|October|November|December) \\d{1,2}, \\d{4}", "date of the notice");
const BASE = { notice_date: "2026-07-01", account_last4: "1234", borrower_name: "A. Borrower", property_address: "1 Test St, Testville NY 10001", servicer_name: "Supermortgage", servicer_address: "PO Box 1, Testville TX 75001", team_phone: "(800) 555-0199", team_name: "Default Servicing Team B", toll_free: "(800) 555-0100", website: "portal.example.com/help", hud_phone: "(800) 569-4287", cfpb_counselor_url: "consumerfinance.gov/find-a-housing-counselor", upload_url: "portal.example.com/upload" };
const HEAD = (title: string) => `{{#block "heading" page=1 y=0.05 pt=14 bold}}${title}{{/block}}\n{{#block "ref" page=1 y=0.1 pt=11}}{{date notice_date}}. {{borrower_name}}, loan number ending {{account_last4}}. Property: {{property_address}}.{{/block}}`;
const CONTACT = `{{#block "contact" page=1 y=0.85 pt=11}}Contact: {{team_name}}, {{team_phone}} (toll-free {{toll_free}}), {{servicer_address}}, {{website}}. Free housing counseling: HUD {{hud_phone}} · {{cfpb_counselor_url}}.{{/block}}`;
const CONTACT_RULE = R("contact", "12 CFR 1024.40(a); state contact requirements", "presence", "Contact: .*\\(\\d{3}\\) \\d{3}-\\d{4}", "contact block with a telephone number");
const HUD_RULE = R("hud", "counseling referral", "presence", "HUD \\(\\d{3}\\) \\d{3}-\\d{4}", "HUD counseling line");
const NO_THREAT = R("no-threat", "12 CFR 1006.18; state UDAP", "absence", "(arrest|garnish|we will sue you tomorrow)", "no threats");
const MAIL_ONLY_RULE = (cite: string) => R("mail-evidence", cite, "data_equality", "mail_channel", "certified + first-class mailing recorded", { predicate: { "==": [{ var: "mail_channel" }, "certified_and_first_class"] } });
const SCRA_TX = "Assert and protect your rights as a member of the armed forces of the United States. If you are or your spouse is serving on active military duty, including active military duty as a member of the Texas National Guard or the National Guard of another state or as a member of a reserve component of the armed forces of the United States, please send written notice of the active duty military service to the sender of this notice immediately.";

// ------------------------------------------------------------------ 13.2
const EXPEDITED = `${HEAD("Result of the expedited review of your loss mitigation application")}
{{#block "body" page=1 y=0.2 pt=11}}We received your complete application on {{date complete_on}}, {{days_before_sale}} days before the foreclosure sale scheduled for {{date sale_on}}. Fannie Mae's guidelines let us complete an expedited review when an application arrives 15 to 37 days before a sale. {{#if completed}}Result: {{result}}. {{#if offer}}To accept, {{acceptance_steps}} by {{date accept_by}}.{{/if}}{{/if}}{{#if not_completed}}We were not able to complete the review before the sale date; the sale will proceed as scheduled unless you contact us at {{team_phone}} and we tell you otherwise in writing.{{/if}} You may still contact us at any time about other options.{{/block}}
${CONTACT}`;
const EXPEDITED_RULES = [DATE_RULE, CONTACT_RULE, R("window", "E-3.4-01: 15–37 days before sale", "data_range", "days_before_sale", "15 ≤ days before sale ≤ 37", { range: { min: 15, max: 37 } }), R("result-or-inability", "E-3.4-01 'notify the borrower of review results or inability to complete review before sale'", "presence", "(Result: |We were not able to complete the review)", "result or inability stated"), NO_THREAT];
const EXPEDITED_SAMPLE = { ...BASE, complete_on: "2026-10-10", days_before_sale: 24, sale_on: "2026-11-03", completed: true, not_completed: false, result: "you are approved for a Flex Modification trial period plan (see the enclosed Evaluation Notice)", offer: true, acceptance_steps: "make the first trial payment", accept_by: "2026-11-01" };

// ------------------------------------------------------------------ 13.3 state pre-foreclosure notices
const NY1304 = `{{#block "header" page=1 y=0.04 pt=14 bold}}YOU MAY BE AT RISK OF FORECLOSURE. PLEASE READ THE FOLLOWING NOTICE CAREFULLY{{/block}}
{{#block "body" page=1 y=0.12 pt=14}}As of {{date as_of}}, your home loan is {{days_in_default}} days in default. Under New York State Law, we are required to send you this notice to inform you that you are at risk of losing your home. You can cure this default by making the payment of {{money amount_in_default}} dollars by {{date cure_by}}. If you are experiencing financial difficulty, you should know that there are several options available to you that may help you keep your home. Attached to this notice is a list of government approved housing counseling agencies in your area which provide free counseling. You should consider contacting one of these agencies immediately. These agencies specialize in helping homeowners who are facing financial difficulty. Housing counselors can help you assess your financial condition and work with us to explore the possibility of modifying your loan, establishing an easier payment plan for you, or even working out a period of loan forbearance. If you wish, you may also contact us directly at {{team_phone}} and ask to discuss possible options. While we cannot assure that a mutually agreeable resolution is possible, we encourage you to take immediate steps to try to achieve a resolution. The longer you wait, the fewer options you may have. If this matter is not resolved within 90 days from the date this notice was mailed, we may commence legal action against you (or sooner if you cease to live in the dwelling as your primary residence.) If you need further information, please call the New York State Department of Financial Services' toll-free helpline at 1-800-342-3736 or visit the Department's website at www.dfs.ny.gov. IMPORTANT: You have the right to remain in your home until you receive a court order telling you to leave the property. If a foreclosure action is filed against you in court, you still have the right to remain in the home until a court orders you to leave. You legally remain the owner of and are responsible for the property until the property is sold by you or by order of the court at the conclusion of any foreclosure proceedings. This notice is not an eviction notice, and a foreclosure action has not yet been commenced against you.{{/block}}
{{#block "agencies" page=2 y=0.1 pt=14}}Housing counseling agencies serving {{county}} County: {{#each agencies}}{{this}}; {{/each}}New York State Attorney General Homeowner Protection Program hotline: 1-855-HOME-456.{{/block}}
{{#block "language" page=2 y=0.6 pt=14}}Language: {{language}}. Sent in a separate envelope by registered or certified mail and by first-class mail on {{date mailed_on}}.{{/block}}`;
const NY1304_RULES = [R("header", "RPAPL §1304(1)", "presence", "YOU MAY BE AT RISK OF FORECLOSURE", "statutory header"), R("days-amount", "RPAPL §1304(1)", "presence", "is \\d+ days in default", "days in default"), R("cure-amount", "RPAPL §1304(1)", "presence", "payment of \\$[\\d,]+\\.\\d{2} dollars", "amount to cure"), R("90-day", "RPAPL §1304(1)", "presence", "within 90 days from the date this notice was mailed", "90-day statement"), R("agencies-5", "RPAPL §1304(2): at least five housing counseling agencies", "data_range", "agency_count", "≥5 agencies for the county", { range: { min: 5 } }), R("hopp", "RPAPL §1304(2)", "presence", "Homeowner Protection Program hotline", "AG HOPP hotline"), R("dfs", "RPAPL §1304(1)", "presence", "1-800-342-3736", "DFS helpline"), R("occupancy", "RPAPL §1304(1)", "presence", "right to remain in your home", "occupancy statement"), R("14pt", "RPAPL §1304(1): fourteen-point type", "layout", "body", "14-point type", { layout: { minPt: 14 } }), R("separate-envelope", "RPAPL §1304(2)", "presence", "separate envelope by registered or certified mail and by first-class mail", "mailing statement"), MAIL_ONLY_RULE("RPAPL §1304(2)"), R("once-12m", "RPAPL §1304(4): once per 12 months per delinquency", "data_equality", "prior_1304_within_12m", "no §1304 notice in the prior 12 months for this delinquency", { predicate: { "!=": [{ var: "prior_1304_within_12m" }, true] } })];
const NY1304_SAMPLE = { ...BASE, as_of: "2026-07-01", days_in_default: 61, amount_in_default: 851_066n, cure_by: "2026-09-29", county: "Kings", agencies: ["Brooklyn Housing & Family Services", "Neighborhood Housing Services of Brooklyn", "CAMBA Inc.", "Bridge Street Development Corp.", "Cypress Hills Local Development Corp."], agency_count: 5, language: "English", mailed_on: "2026-07-01", mail_channel: "certified_and_first_class", prior_1304_within_12m: false };

const NJ_NOI = `${HEAD("Notice of Intention to Foreclose")}
{{#block "body" page=1 y=0.2 pt=11}}This notice is sent under the New Jersey Fair Foreclosure Act, N.J.S.A. 2A:50-56. (1) The obligation: your mortgage loan dated {{date note_date}} secured by {{property_address}}. (2) The nature of the default: {{default_nature}}. (3) Right to cure: you may cure the default by paying {{money cure_amount}} by {{date cure_by}} (at least 30 days from this notice). (4) Where to pay: {{servicer_address}}. (5) Cure amount and how it may change: the amount may increase by additional payments and charges coming due; call {{team_phone}} for an updated figure. (6) If you do not cure by {{date cure_by}}, we may take steps to terminate your ownership by commencing a foreclosure suit in a court of competent jurisdiction. (7) If a suit is filed you still have the right to cure until the entry of final judgment, with the lender's court costs and attorney fees not exceeding those permitted by the Rules of Court. (8) Contact: {{team_name}}, {{team_phone}}. (9) You may transfer the property to another person subject to the security interest, and the transferee may cure the default. (10) The lender's name and address: {{lender_name}}, {{lender_address}}. (11) Assistance: New Jersey Housing and Mortgage Finance Agency 1-800-NJ-HOUSE; housing counselors HUD {{hud_phone}}. (12) Any right of cure is subject to the terms of the mortgage. (13) The debt: {{money total_debt}} as of {{date as_of}}. (14) If you believe this notice is in error, contact us at once. (15) This notice was mailed by registered or certified mail, return receipt requested, and by regular mail on {{date mailed_on}}.{{/block}}
${CONTACT}`;
const NJ_NOI_RULES = [DATE_RULE, CONTACT_RULE, HUD_RULE, R("fifteen-items", "N.J.S.A. 2A:50-56(c): 15 items", "presence", "\\(15\\) This notice was mailed", "all 15 items present"), R("30-day-cure", "N.J.S.A. 2A:50-56(c)(3)", "presence", "at least 30 days from this notice", "≥30-day cure"), R("cure-amount", "N.J.S.A. 2A:50-56(c)(3)", "presence", "paying \\$[\\d,]+\\.\\d{2} by", "cure amount"), R("cure-until-judgment", "N.J.S.A. 2A:50-56(c)(7)", "presence", "right to cure until the entry of final judgment", "cure right to judgment"), MAIL_ONLY_RULE("N.J.S.A. 2A:50-56(b)")];
const NJ_NOI_SAMPLE = { ...BASE, property_address: "1 Test St, Testville NJ 07001", note_date: "2021-10-01", default_nature: "failure to pay the monthly installments due May 1, 2026 through July 1, 2026", cure_amount: 851_066n, cure_by: "2026-08-05", lender_name: "Fannie Mae (Federal National Mortgage Association)", lender_address: "1100 15th Street NW, Washington, DC 20005", total_debt: 25_851_066n, as_of: "2026-07-01", mailed_on: "2026-07-01", mail_channel: "certified_and_first_class" };

const MA_35A = `${HEAD("Right to Cure Your Mortgage Default — M.G.L. c. 244, §35A")}
{{#block "body" page=1 y=0.2 pt=11}}You have the right to cure the default on your mortgage loan. As of {{date as_of}} the amount required to cure is {{money cure_amount}}, which must be paid by {{date cure_by}} ({{cure_days}} days from this notice). Payments may be made to {{servicer_address}}. This right to cure is granted once during any five-year period. If you do not cure by {{date cure_by}}, we may accelerate the loan and begin foreclosure. The holder of your mortgage is {{holder_name}}; the servicer is {{servicer_name}}, {{team_phone}}. You may be eligible for a loan modification; contact us or a housing counselor (HUD {{hud_phone}}). A copy of this notice has been filed with the Massachusetts Division of Banks. Este aviso es importante: si no lo entiende, busque ayuda para traducirlo. Notice translations are available at {{website}}.{{/block}}
${CONTACT}`;
const MA_35A_RULES = [DATE_RULE, CONTACT_RULE, HUD_RULE, R("cure-90", "M.G.L. c.244 §35A(g): 90-day right to cure", "data_range", "cure_days", "cure period ≥90 days", { range: { min: 90 } }), R("cure-amount", "M.G.L. c.244 §35A(c)", "presence", "amount required to cure is \\$[\\d,]+\\.\\d{2}", "cure amount and date"), R("once-5y", "M.G.L. c.244 §35A(a)", "presence", "once during any five-year period", "five-year statement"), R("dob", "M.G.L. c.244 §35A(c)", "presence", "filed with the Massachusetts Division of Banks", "DOB filing"), R("translation", "M.G.L. c.244 §35A(c)", "presence", "Notice translations are available", "translated-notice legend"), MAIL_ONLY_RULE("M.G.L. c.244 §35A(g)")];
const MA_35A_SAMPLE = { ...BASE, property_address: "1 Test St, Testville MA 02101", as_of: "2026-07-01", cure_amount: 851_066n, cure_by: "2026-09-29", cure_days: 90, holder_name: "Fannie Mae", mail_channel: "certified_and_first_class" };

const TX_51002D = `${HEAD("Notice of Default and Intent to Accelerate")}
{{#block "body" page=1 y=0.2 pt=11}}Your loan is in default for failure to pay the installments due {{first_unpaid_due}} through {{last_unpaid_due}}. To cure the default you must pay {{money cure_amount}} by {{date cure_by}} ({{cure_days}} days from this notice), delivered to {{servicer_address}}. If the default is not cured by that date, the maturity of the debt will be accelerated and the property may be sold at a trustee's sale under Texas Property Code §51.002 after a further notice of sale posted and filed at least 21 days before the sale. This notice is sent by certified mail. ${SCRA_TX}{{/block}}
${CONTACT}`;
const TX_51002D_RULES = [DATE_RULE, CONTACT_RULE, R("cure-20", "Tex. Prop. Code §51.002(d): at least 20 days to cure", "data_range", "cure_days", "≥20 days", { range: { min: 20 } }), R("cure-amount", "Tex. Prop. Code §51.002(d)", "presence", "you must pay \\$[\\d,]+\\.\\d{2} by", "cure amount"), R("scra", "Tex. Prop. Code §51.002(i)", "presence", "Assert and protect your rights as a member of the armed forces", "servicemember statement"), R("certified", "Tex. Prop. Code §51.002(d)", "presence", "sent by certified mail", "certified mail"), MAIL_ONLY_RULE("Tex. Prop. Code §51.002(d)")];
const TX_51002D_SAMPLE = { ...BASE, property_address: "1 Test St, Testville TX 75001", first_unpaid_due: "May 1, 2026", last_unpaid_due: "July 1, 2026", cure_amount: 851_066n, cure_by: "2026-07-22", cure_days: 21, mail_channel: "certified_and_first_class" };

const MD_NOI = `${HEAD("Notice of Intent to Foreclose — Md. Real Prop. §7-105.1")}
{{#block "body" page=1 y=0.2 pt=11}}Secured party: {{holder_name}}. Servicer: {{servicer_name}}, {{team_phone}}. Property: {{property_address}}. Date of default: {{date default_on}}. Total amount required to cure the default as of {{date as_of}}: {{money cure_amount}}. Your loan may be eligible for loss mitigation; a loss mitigation application and instructions are enclosed, and a housing counselor (HUD {{hud_phone}}) can help. We may not file an action to foreclose earlier than the later of 90 days after the default or 45 days after this notice was sent ({{date earliest_filing}}). A copy of this notice has been sent to the Commissioner of Financial Regulation. This notice is sent by certified mail, return receipt requested, and by first-class mail on {{date mailed_on}}.{{/block}}
${CONTACT}`;
const MD_NOI_RULES = [DATE_RULE, CONTACT_RULE, HUD_RULE, R("cure-amount", "Md. Real Prop. §7-105.1(c)", "presence", "required to cure the default as of .* \\$[\\d,]+\\.\\d{2}", "cure amount as of date"), R("45-90", "Md. Real Prop. §7-105.1(b)", "presence", "later of 90 days after the default or 45 days after this notice", "filing timing"), R("lossmit-app", "Md. Real Prop. §7-105.1(c)", "presence", "loss mitigation application and instructions are enclosed", "loss-mit application enclosed"), R("commissioner", "Md. Real Prop. §7-105.1(c)", "presence", "sent to the Commissioner of Financial Regulation", "Commissioner copy"), MAIL_ONLY_RULE("Md. Real Prop. §7-105.1(c)")];
const MD_NOI_SAMPLE = { ...BASE, property_address: "1 Test St, Testville MD 21201", holder_name: "Fannie Mae", default_on: "2026-05-01", as_of: "2026-07-01", cure_amount: 851_066n, earliest_filing: "2026-08-15", mailed_on: "2026-07-01", mail_channel: "certified_and_first_class" };

const CA_2923_5 = `${HEAD("Important information about your mortgage — Cal. Civ. Code §2923.5")}
{{#block "body" page=1 y=0.2 pt=11}}We are contacting you to assess your financial situation and explore options to avoid foreclosure. Please call us toll-free at {{toll_free}}; a person is available to discuss your options. You have the right to request a meeting with us within 14 days. You may also call HUD at {{hud_phone}} to find a HUD-certified housing counseling agency. We have tried to reach you by telephone on {{#each call_attempts}}{{this}}; {{/each}}This letter is sent by first-class mail{{#if certified}} and, because we did not hear from you within two weeks, again by certified mail{{/if}}. No notice of default will be recorded until at least 30 days after we contact you or complete the due-diligence steps the law requires. Information about our loss mitigation options is at {{website}}.{{/block}}
${CONTACT}`;
const CA_2923_5_RULES = [DATE_RULE, CONTACT_RULE, HUD_RULE, R("toll-free", "Cal. Civ. Code §2923.5(e)(2)(A)", "presence", "toll-free at \\(\\d{3}\\) \\d{3}-\\d{4}", "toll-free line"), R("meeting", "Cal. Civ. Code §2923.5(a)(2)", "presence", "request a meeting with us within 14 days", "meeting right"), R("three-calls", "Cal. Civ. Code §2923.5(e)(2)(B): three calls on different days/hours", "data_range", "call_attempt_count", "≥3 call attempts", { range: { min: 3 } }), R("30-day", "Cal. Civ. Code §2923.5(a)(1)", "presence", "at least 30 days after", "30-day statement"), R("website", "Cal. Civ. Code §2923.5(e)(2)(D)", "presence", "loss mitigation options is at", "website")];
const CA_2923_5_SAMPLE = { ...BASE, property_address: "1 Test St, Testville CA 90001", call_attempts: ["June 2, 2026 9:15 am", "June 4, 2026 6:40 pm", "June 9, 2026 12:30 pm"], call_attempt_count: 3, certified: true };

const WA_61_24_031 = `${HEAD("Pre-foreclosure options — RCW 61.24.031")}
{{#block "body" page=1 y=0.2 pt=11}}You must respond within thirty days of the date of this letter. If you do not respond, a notice of default may be issued. You have the right to meet with us in person, by telephone or through a housing counselor to discuss options to avoid foreclosure, including a loan modification, forbearance, a repayment plan, a short sale or a deed in lieu. Call {{toll_free}}, or contact a housing counselor at the Washington Homeownership Hotline 1-877-894-HOME or HUD {{hud_phone}}. If you respond, no notice of default will be issued until at least ninety days after our initial contact, so that we can meet and confer. We have tried to reach you by telephone on {{#each call_attempts}}{{this}}; {{/each}}This letter is sent by first-class mail and by registered or certified mail.{{/block}}
${CONTACT}`;
const WA_61_24_031_RULES = [DATE_RULE, CONTACT_RULE, HUD_RULE, R("30-day-response", "RCW 61.24.031(5)", "presence", "respond within thirty days", "30-day response"), R("meet-confer", "RCW 61.24.031(1)(b)", "presence", "at least ninety days after our initial contact", "90-day meet-and-confer"), R("hotline", "RCW 61.24.031(5)", "presence", "1-877-894-HOME", "Washington hotline"), R("three-calls", "RCW 61.24.031(5)", "data_range", "call_attempt_count", "≥3 call attempts", { range: { min: 3 } }), MAIL_ONLY_RULE("RCW 61.24.031(5)")];
const WA_61_24_031_SAMPLE = { ...BASE, property_address: "1 Test St, Testville WA 98001", call_attempts: ["June 2, 2026 9:15 am", "June 4, 2026 6:40 pm", "June 9, 2026 12:30 pm"], call_attempt_count: 3, mail_channel: "certified_and_first_class" };

const NV_107 = `${HEAD("Notice under NRS 107.500 — options to avoid foreclosure")}
{{#block "body" page=1 y=0.2 pt=11}}Before a notice of default may be recorded, Nevada law requires us to contact you at least 30 days in advance to assess your financial situation and explore options to avoid foreclosure. Your loan is in default; the amount required to reinstate as of {{date as_of}} is {{money reinstatement_amount}}. Options may include a loan modification, forbearance, a repayment plan, a short sale or a deed in lieu. Call {{toll_free}} or write to {{servicer_address}}. You may request a meeting with us and you may be represented by a housing counselor (HUD {{hud_phone}}); Nevada's Foreclosure Mediation Program may be available to you after a notice of default is recorded. Documents you may request: a copy of the note, the deed of trust and the payment history. We have tried to reach you on {{#each call_attempts}}{{this}}; {{/each}}{{/block}}
${CONTACT}`;
const NV_107_RULES = [DATE_RULE, CONTACT_RULE, HUD_RULE, R("30-days", "NRS 107.510(1)", "presence", "at least 30 days in advance", "30-day statement"), R("reinstate", "NRS 107.500(1)", "presence", "reinstate as of .* \\$[\\d,]+\\.\\d{2}", "reinstatement amount"), R("mediation", "NRS 107.086", "presence", "Foreclosure Mediation Program", "mediation program"), R("documents", "NRS 107.500(1)(b)", "presence", "copy of the note, the deed of trust and the payment history", "document rights")];
const NV_107_SAMPLE = { ...BASE, property_address: "1 Test St, Testville NV 89001", as_of: "2026-07-01", reinstatement_amount: 851_066n, call_attempts: ["June 2, 2026", "June 4, 2026", "June 9, 2026"] };

const GA_162_2 = `${HEAD("Notice of Foreclosure Sale — O.C.G.A. §44-14-162.2")}
{{#block "body" page=1 y=0.2 pt=11}}Notice is given that the property at {{property_address}} will be sold at public outcry on {{date sale_on}} (the first Tuesday of the month) between 10 a.m. and 4 p.m. at the {{county}} County courthouse under the power of sale in your security deed. The entity with full authority to negotiate, amend, and modify all terms of the mortgage with the debtor is {{authority_name}}, {{authority_phone}}, {{authority_address}}. This notice is sent no later than 30 days before the date of the proposed sale by registered or certified mail or statutory overnight delivery. The assignment of the security deed has been recorded in the {{county}} County records at Deed Book {{deed_book}}, Page {{deed_page}}.{{/block}}
${CONTACT}`;
const GA_162_2_RULES = [DATE_RULE, CONTACT_RULE, R("authority", "O.C.G.A. §44-14-162.2(a)", "presence", "full authority to negotiate, amend, and modify", "negotiating authority named"), R("30-days", "O.C.G.A. §44-14-162.2(a)", "presence", "no later than 30 days before the date of the proposed sale", "30-day timing"), R("assignment", "O.C.G.A. §44-14-162(b)", "presence", "assignment of the security deed has been recorded", "recorded assignment"), R("sale-days", "O.C.G.A. §44-14-162.2(a)", "data_range", "days_before_sale", "≥30 days before the sale", { range: { min: 30 } })];
const GA_162_2_SAMPLE = { ...BASE, notice_date: "2026-09-01", property_address: "1 Test St, Testville GA 30301", sale_on: "2026-10-06", county: "Fulton", authority_name: "Supermortgage Loss Mitigation", authority_phone: "(800) 555-0199", authority_address: "PO Box 1, Testville TX 75001", deed_book: "61234", deed_page: "455", days_before_sale: 35 };

const REFERRAL_ADVICE = `${HEAD("Your loan has been referred for foreclosure")}
{{#block "body" page=1 y=0.2 pt=11}}On {{date referral_on}} we referred your loan to {{firm_name}}, {{firm_phone}}, to begin foreclosure. This does not end your options: you may reinstate the loan by paying the amount past due plus allowable fees and costs, request a payoff figure, or apply for mortgage assistance at any time (call {{team_phone}} or upload at {{upload_url}}). Foreclosure fees and costs will increase the amount needed to reinstate. {{#if fdcpa_debt_collector}}This communication is from a debt collector.{{/if}}{{/block}}
${CONTACT}`;
const REFERRAL_ADVICE_RULES = [DATE_RULE, CONTACT_RULE, HUD_RULE, R("firm", "13.3 outputs", "presence", "referred your loan to .*\\(\\d{3}\\) \\d{3}-\\d{4}", "firm named with a telephone number"), R("options", "12 CFR 1024.39; E-3.2-08", "presence", "reinstate the loan|apply for mortgage assistance", "options preserved"), NO_THREAT];
const REFERRAL_ADVICE_SAMPLE = { ...BASE, referral_on: "2026-06-30", firm_name: "Test & Partners LLP", firm_phone: "(800) 555-0177", fdcpa_debt_collector: false };

const REINSTATEMENT_QUOTE = `${HEAD("Reinstatement quote")}
{{#block "body" page=1 y=0.2 pt=11}}The amount required to reinstate your loan, good through {{date good_through}}, is {{money total_cents}}: past-due principal and interest {{money delinquent_pi_cents}} ({{installments}} installments), late charges {{money late_charges_cents}}, escrow advances {{money escrow_advances_cents}}, property inspections and preservation {{money corporate_advances_cents}}, attorney fees earned to the {{milestone}} milestone {{money attorney_fees_cents}}, and costs actually incurred {{money costs_cents}}. Funds must be certified and delivered to {{servicer_address}} by {{date good_through}}; amounts received after that date may be insufficient because additional installments and charges will have come due. Full tender before a foreclosure sale will be accepted.{{/block}}
${CONTACT}`;
const REINSTATEMENT_QUOTE_RULES = [DATE_RULE, CONTACT_RULE, R("good-through", "E-3.2-08", "presence", "good through ", "good-through date"), R("itemized", "E-3.2-08; 12 CFR 1024.41(f)", "presence", "past-due principal and interest \\$[\\d,]+\\.\\d{2}", "itemized components"), R("attorney-milestone", "E-5-04: fees earned to the last completed milestone", "presence", "attorney fees earned to the .* milestone", "milestone basis"), R("total-sum", "13.3 rule 4: total equals the sum of components", "data_equality", "total_cents", "total is the sum", { predicate: { "==": [{ var: "total_cents" }, { var: "sum_cents" }] } }), R("tender", "E-3.2-08", "presence", "Full tender before a foreclosure sale will be accepted", "tender statement")];
const REINSTATEMENT_QUOTE_SAMPLE = { ...BASE, good_through: "2026-07-31", total_cents: 1_358_208n, sum_cents: 1_358_208n, delinquent_pi_cents: 852_066n, installments: 6, late_charges_cents: 28_402n, escrow_advances_cents: 310_540n, corporate_advances_cents: 6_000n, milestone: "service complete", attorney_fees_cents: 100_000n, costs_cents: 61_200n };

// ------------------------------------------------------------------ 13.8 SCRA
const SCRA_RIGHTS = `${HEAD("Your rights under the Servicemembers Civil Relief Act")}
{{#block "body" page=1 y=0.2 pt=11}}Our records indicate that you or a co-borrower may be serving on active military duty. The Servicemembers Civil Relief Act (50 U.S.C. §3901 et seq.) provides protections including: a 6% interest-rate cap on obligations incurred before service, on written request with a copy of orders; protection from foreclosure sale or seizure without a court order during service and for one year afterward on pre-service mortgages; and the right to seek a stay of court proceedings. Fannie Mae also allows relief such as forbearance and a Military Indulgence. To tell us about your service, send a copy of your orders or a completed enclosed form to {{servicer_address}} or upload at {{upload_url}}; you may also call {{team_phone}}. We will never ask you to give up these rights.{{/block}}
${CONTACT}`;
const SCRA_RIGHTS_RULES = [DATE_RULE, CONTACT_RULE, R("cap", "50 U.S.C. 3937", "presence", "6% interest-rate cap", "interest cap explained"), R("foreclosure", "50 U.S.C. 3953", "presence", "one year afterward", "foreclosure protection and tail"), R("no-waiver", "D2-3.4-01: never seek consent", "presence", "never ask you to give up these rights", "no waiver solicitation"), R("no-waiver-absence", "D2-3.4-01", "absence", "(sign the enclosed waiver|consent to the sale)", "no consent request")];
const SCRA_RIGHTS_SAMPLE = { ...BASE };

const STAY_CONFIRMATION = `${HEAD("Confirmation: foreclosure stayed under the SCRA")}
{{#block "body" page=1 y=0.2 pt=11}}We confirm that foreclosure of {{property_address}} is stayed while you are on active duty (service began {{date service_begin_on}}{{#if service_end_on}}, expected to end {{date service_end_on}}{{/if}}) and for one year after your service ends{{#if protection_ends_on}} — through {{date protection_ends_on}}{{/if}}. No foreclosure sale will be held during that period without a court order. Late charges assessed since your service began have been waived. We will check in with you about every 90 days; please tell us if your status changes. {{#if cap_applied}}Your interest rate has also been reduced to 6% (see the separate letter).{{/if}}{{/block}}
${CONTACT}`;
const STAY_CONFIRMATION_RULES = [DATE_RULE, CONTACT_RULE, R("stay", "50 U.S.C. 3953(c)", "presence", "stayed while you are on active duty", "stay confirmed"), R("tail", "50 U.S.C. 3953(c): one-year tail", "presence", "for one year after your service ends", "12-month tail"), R("no-sale", "50 U.S.C. 3953(c)", "presence", "No foreclosure sale will be held during that period without a court order", "no-sale statement"), R("late-charges", "D2-3.4-01", "presence", "Late charges assessed since your service began have been waived", "late-charge waiver"), R("90-day", "D2-3.4-01 quarterly contact", "presence", "every 90 days", "quarterly contact")];
const STAY_CONFIRMATION_SAMPLE = { ...BASE, service_begin_on: "2026-03-15", service_end_on: "2027-02-28", protection_ends_on: "2028-02-28", cap_applied: true };

const STATUS_CHECK_90 = `${HEAD("Checking in: your military status")}
{{#block "body" page=1 y=0.2 pt=11}}As part of the relief on your loan we check in about every 90 days. Are you still on active duty? If your service has ended or your orders have changed, please tell us the date by calling {{team_phone}} or uploading updated orders at {{upload_url}}. Your protections continue for one year after your service ends. This is not a request for payment and not a request to waive any right.{{/block}}
${CONTACT}`;
const STATUS_CHECK_90_RULES = [DATE_RULE, CONTACT_RULE, R("question", "D2-3.4-01 quarterly contact", "presence", "Are you still on active duty", "status question"), R("no-payment", "13.8 script", "presence", "not a request for payment", "no payment request"), R("no-waiver", "D2-3.4-01", "presence", "not a request to waive any right", "no waiver")];
const STATUS_CHECK_90_SAMPLE = { ...BASE };

// ------------------------------------------------------------------ 13.9 SCRA interest cap
const RATE_CONFIRMATION = `${HEAD("Your interest rate has been reduced under the SCRA")}
{{#block "body" page=1 y=0.2 pt=11}}We received your written notice and orders on {{date request_on}}. Effective with the payment due {{date effective_due}}, the interest rate on your loan is reduced to 6.000% (from {{note_rate_pct}}%) for the period of your military service and one year after it ends{{#if cap_ends_on}}, currently expected to end {{date cap_ends_on}}{{/if}}. Interest above 6% is forgiven, not deferred. Payments you made at the higher rate since {{date effective_due}} have been recalculated: {{money overpayment_cents}} was overpaid. Your new monthly payment is {{money new_payment_cents}} (principal {{money principal_cents}} + interest {{money interest_cents}}{{#if escrow_cents}} + escrow {{money escrow_cents}}{{/if}}) starting {{date new_payment_due}}. No signature is required. Overpayment options: (1) refund to you, (2) apply to principal, (3) apply toward your next payment{{#if shortfall_cents}} (you would add {{money shortfall_cents}}){{/if}}; tell us your choice within 30 days or we will apply it to principal. Late charges assessed during the period have been waived. Call {{team_phone}} with questions.{{/block}}
${CONTACT}`;
const RATE_CONFIRMATION_RULES = [DATE_RULE, CONTACT_RULE, R("rate", "50 U.S.C. 3937(a)(1); D2-3.4-01", "presence", "reduced to 6\\.000%", "capped rate"), R("effective", "D2-3.4-01: first payment due after entry", "presence", "Effective with the payment due ", "effective date"), R("forgiven", "50 U.S.C. 3937(a)(2)", "presence", "forgiven, not deferred", "forgiveness"), R("new-payment", "D2-3.4-01", "presence", "new monthly payment is \\$[\\d,]+\\.\\d{2}", "new payment amount"), R("no-signature", "D2-3.4-01", "presence", "No signature is required", "no signature"), R("options", "13.9 rule 6; decision 13.9-3", "presence", "\\(1\\) refund to you, \\(2\\) apply to principal, \\(3\\)", "overpayment options"), R("discontinuation", "D2-3.4-01", "presence", "one year after it ends", "discontinuation date basis"), R("sum", "13.9: payment = principal + interest (+ escrow)", "data_equality", "new_payment_cents", "payment equals the components", { predicate: { "==": [{ var: "new_payment_cents" }, { var: "sum_cents" }] } })];
const RATE_CONFIRMATION_SAMPLE = { ...BASE, request_on: "2026-09-10", effective_due: "2026-04-01", note_rate_pct: "7.250", cap_ends_on: "2028-02-28", overpayment_cents: 152_830n, new_payment_cents: 174_173n, sum_cents: 174_173n, principal_cents: 27_870n, interest_cents: 146_303n, escrow_cents: 0n, new_payment_due: "2026-09-01", shortfall_cents: 21_343n };

const OVERPAYMENT_ELECTION = `${HEAD("How would you like your SCRA overpayment applied?")}
{{#block "body" page=1 y=0.2 pt=11}}Your recalculation shows an overpayment of {{money overpayment_cents}}. {{#if defaulted}}We did not hear from you by {{date due}}, so we applied it to your principal balance as our letter explained. If you would prefer a refund instead, call {{team_phone}} within 30 days.{{/if}}{{#if pending}}Please choose by {{date due}}: (1) refund by check, (2) apply to your principal balance, or (3) apply toward your next payment of {{money next_payment_cents}}{{#if shortfall_cents}} (you would add {{money shortfall_cents}}){{/if}}. If we do not hear from you by {{date due}} we will apply it to your principal balance.{{/if}}{{/block}}
${CONTACT}`;
const OVERPAYMENT_ELECTION_RULES = [DATE_RULE, CONTACT_RULE, R("amount", "13.9 rule 6", "presence", "overpayment of \\$[\\d,]+\\.\\d{2}", "overpayment amount"), R("due", "SM_SCRA_OVERPAYMENT_ELECTION_30", "presence", "by [A-Z][a-z]+ \\d{1,2}, \\d{4}", "election deadline"), R("default", "decision 13.9-3", "presence", "apply(ied)? it to your principal balance", "default election disclosed")];
const OVERPAYMENT_ELECTION_SAMPLE = { ...BASE, overpayment_cents: 152_830n, defaulted: false, pending: true, due: "2026-10-15", next_payment_cents: 174_173n, shortfall_cents: 21_343n };

const RATE_END = `${HEAD("Your SCRA interest-rate reduction ends soon")}
{{#block "body" page=1 y=0.2 pt=11}}Your military service ended {{date service_end_on}}. The 6% interest-rate cap continues for one year after that date, through {{date cap_ends_on}}. Starting with the payment due {{date restoration_due}}, your interest rate returns to {{note_rate_pct}}% and your monthly principal and interest payment returns to {{money restored_payment_cents}}{{#if escrow_cents}} plus escrow of {{money escrow_cents}}{{/if}}. If your service has been extended or you re-enter active duty, send us your orders and the cap will continue. Nothing about this change requires your signature.{{/block}}
${CONTACT}`;
const RATE_END_RULES = [DATE_RULE, CONTACT_RULE, R("tail", "50 U.S.C. 3937(a)(1)(A): one year after service", "presence", "one year after that date, through ", "tail end date"), R("restoration", "D2-3.4-01: 'the payment they had before'", "presence", "returns to \\$[\\d,]+\\.\\d{2}", "restored payment"), R("60-days", "13.9: letter ~60 days before restoration", "data_range", "days_before_restoration", "sent ≥30 days before restoration", { range: { min: 30 } }), R("re-entry", "50 U.S.C. 3937", "presence", "send us your orders and the cap will continue", "re-entry statement")];
const RATE_END_SAMPLE = { ...BASE, notice_date: "2027-12-30", service_end_on: "2027-02-28", cap_ends_on: "2028-02-28", restoration_due: "2028-03-01", note_rate_pct: "7.250", restored_payment_cents: 204_653n, escrow_cents: 0n, days_before_restoration: 61 };

export const SECTION_13_VERSIONS: VersionInput[] = [
  V("NTC_FNMA_E3401_EXPEDITED_RESULT", EXPEDITED, EXPEDITED_RULES, EXPEDITED_SAMPLE, "fnma.e3401.2026-09", "E-3.4-01 expedited review result"),
  V("NTC_STATE_PREFC_NY_1304", NY1304, NY1304_RULES, NY1304_SAMPLE, "state.ny.rpapl1304.2026", "RPAPL §1304 (statutory text); 13.3-T4"),
  V("NTC_STATE_PREFC_NJ_NOI", NJ_NOI, NJ_NOI_RULES, NJ_NOI_SAMPLE, "state.nj.ffa.2026", "N.J.S.A. 2A:50-56(c) 15 items"),
  V("NTC_STATE_PREFC_MA_35A", MA_35A, MA_35A_RULES, MA_35A_SAMPLE, "state.ma.35a.2026", "M.G.L. c.244 §35A"),
  V("NTC_STATE_PREFC_TX_51002D", TX_51002D, TX_51002D_RULES, TX_51002D_SAMPLE, "state.tx.51002.2026", "Tex. Prop. Code §51.002(d), (i)"),
  V("NTC_STATE_PREFC_MD_NOI", MD_NOI, MD_NOI_RULES, MD_NOI_SAMPLE, "state.md.7-105_1.2026", "Md. Real Prop. §7-105.1"),
  V("NTC_STATE_PREFC_CA_2923_5_LETTER", CA_2923_5, CA_2923_5_RULES, CA_2923_5_SAMPLE, "state.ca.2923_5.2026", "Cal. Civ. Code §2923.5 due-diligence letter"),
  V("NTC_STATE_PREFC_WA_61_24_031_LETTER", WA_61_24_031, WA_61_24_031_RULES, WA_61_24_031_SAMPLE, "state.wa.61_24_031.2026", "RCW 61.24.031 pre-foreclosure options letter"),
  V("NTC_STATE_PREFC_NV_107_5XX", NV_107, NV_107_RULES, NV_107_SAMPLE, "state.nv.107_5xx.2026", "NRS 107.500–107.560"),
  V("NTC_STATE_PREFC_GA_162_2", GA_162_2, GA_162_2_RULES, GA_162_2_SAMPLE, "state.ga.44-14-162_2.2026", "O.C.G.A. §44-14-162.2 [PARTIALLY VERIFIED]"),
  V("NTC_SM_FC_REFERRAL_ADVICE", REFERRAL_ADVICE, REFERRAL_ADVICE_RULES, REFERRAL_ADVICE_SAMPLE, "sm.foreclosure.2026-09", "13.3 outputs (optional advice letter)"),
  V("NTC_SM_FC_REINSTATEMENT_QUOTE", REINSTATEMENT_QUOTE, REINSTATEMENT_QUOTE_RULES, REINSTATEMENT_QUOTE_SAMPLE, "sm.foreclosure.2026-09", "E-3.2-08 reinstatement; 13.3 rule 4 worked example"),
  V("NTC_FNMA_D23401_SCRA_RIGHTS", SCRA_RIGHTS, SCRA_RIGHTS_RULES, SCRA_RIGHTS_SAMPLE, "fnma.d23401.2026-09", "D2-3.4-01 SCRA rights letter (policy)"),
  V("NTC_SCRA_3953_STAY_CONFIRMATION", STAY_CONFIRMATION, STAY_CONFIRMATION_RULES, STAY_CONFIRMATION_SAMPLE, "scra.3953.2026", "50 U.S.C. 3953 stay confirmation; 13.8-T3"),
  V("NTC_FNMA_D23401_SCRA_STATUS_CHECK_90", STATUS_CHECK_90, STATUS_CHECK_90_RULES, STATUS_CHECK_90_SAMPLE, "fnma.d23401.2026-09", "D2-3.4-01 quarterly status check"),
  V("NTC_SCRA_3937_RATE_CONFIRMATION", RATE_CONFIRMATION, RATE_CONFIRMATION_RULES, RATE_CONFIRMATION_SAMPLE, "scra.3937.2026", "D2-3.4-01 rate confirmation; 13.9 worked example"),
  V("NTC_SCRA_3937_OVERPAYMENT_ELECTION", OVERPAYMENT_ELECTION, OVERPAYMENT_ELECTION_RULES, OVERPAYMENT_ELECTION_SAMPLE, "scra.3937.2026", "13.9 rule 6 / decision 13.9-3"),
  V("NTC_SCRA_3937_RATE_END", RATE_END, RATE_END_RULES, RATE_END_SAMPLE, "scra.3937.2026", "13.9-T3 end-date letter"),
];
