/**
 * §19.3 authored notice versions (V(code, source, rules, sample, ruleSet, formBasis) from ./section01.ts;
 * see ./section13.ts) and per-code channel/combination overrides. Spread by ./section19.ts.
 *
 * These are outbound corporate notices to Fannie Mae under Servicing Guide A2-1-01 (technology-provider change,
 * contract event, contract copies) and the LL-2026-04 disclosure response — prepared by the agent, signed and
 * sent by the responsible officer through the channel fixed at onboarding (letter + email to the account team,
 * open decision 3). No borrower content; no consumer E-SIGN consent is involved, so email is permitted.
 */
import type { ContentRule, NoticeTemplate, VersionInput } from "../registry.ts";
import { V } from "./section01.ts";

const R = (rule_id: string, citation: string, kind: ContentRule["kind"], selector: string, message: string, extra: Partial<ContentRule> = {}): ContentRule => ({ rule_id, citation, kind, selector, severity: "block", message, ...extra });
const A2101 = "Servicing Guide A2-1-01, Additional Servicer Duties and Responsibilities for Certain Servicers (12/17/2025)";
const DATE_RULE = R("date", "notice date", "presence", "(January|February|March|April|May|June|July|August|September|October|November|December) \\d{1,2}, \\d{4}", "date of the notice");
const OFFICER_RULE = R("officer-signed", "19.3 escalations: every Fannie Mae notice → officer; guardrail: the agent cannot send a Fannie Mae notice", "data_equality", "signer_role", "signed and sent by the responsible officer", { predicate: { "==": [{ var: "signer_role" }, "officer"] } });
const SIGNATURE_RULE = R("signature", "19.3 integrations: signed and sent by the responsible officer through the channel fixed at onboarding", "presence", "Signed and sent by .+ \\(officer\\)", "officer signature line");
const A4101_RULE = R("a4-1-01", "A2-1-01: 'in addition to, not in lieu of, the servicer's obligations to notify Fannie Mae under Selling Guide A4-1-01'", "presence", "in addition to, not in lieu of", "A4-1-01 reservation");
const ENTITY_RULE = R("entity", "19.3 rule 1: the partner and Supermortgage are tested separately", "data_equality", "entity", "entity is partner or supermortgage", { predicate: { in: [{ var: "entity" }, ["partner", "supermortgage"]] } });
const BASE = { notice_date: "2026-11-02", entity: "partner", entity_name: "Partner Bank, N.A.", entity_role: "master servicer", servicer_number: "12345-000-1", fnma_contact: "Fannie Mae, Servicer Relationship Management (Lender Contract notice address), 1100 15th Street NW, Washington, DC 20005", officer_name: "J. Officer", officer_title: "Chief Servicing Officer", signer_role: "officer", channel: "letter and email to the Fannie Mae account team" };
const HEAD = (title: string) => `{{#block "heading" page=1 y=0.05 pt=14 bold}}${title}{{/block}}
{{#block "ref" page=1 y=0.1 pt=11}}{{date notice_date}}. To: {{fnma_contact}}. From: {{entity_name}} ({{entity_role}}; Fannie Mae seller/servicer number {{servicer_number}}). Re: Servicing Guide A2-1-01, Additional Servicer Duties and Responsibilities for Certain Servicers.{{/block}}`;
const SIGN = `{{#block "signature" page=1 y=0.85 pt=11}}This notice is in addition to, not in lieu of, our obligations to notify Fannie Mae under Selling Guide A4-1-01, Maintaining Seller/Servicer Eligibility. Signed and sent by {{officer_name}}, {{officer_title}} (officer), by {{channel}} on {{date notice_date}}.{{/block}}`;

// ------------------------------------------------------------------ NTC_FNMA_A2101_TECH_PROVIDER_CHANGE_180
const CHANGE_180 = `${HEAD("Notice of intent to change a third-party technology provider — 180 days' prior written notice")}
{{#block "body" page=1 y=0.2 pt=11}}{{entity_name}} relies on a third-party technology provider for the performance of critical servicing functions and gives Fannie Mae not less than 180 days' prior written notice of its intent to change that provider. Current provider: {{provider_from}}. Intended provider: {{provider_to}}. Critical servicing functions affected: {{#each critical_functions}}{{this}}; {{/each}}. Planned cutover date: {{date planned_cutover}}, {{days_notice}} days after this notice; no cutover will occur before {{date earliest_cutover}}. Continuity of technology service from the original provider: {{provider_from}} will continue to provide the technology service, and our contract with {{provider_from}} remains in force, until the transfer of critical servicing functions is complete, so that there is no interruption to borrowers or to Fannie Mae. Transition plan: upon Fannie Mae's written request we will provide our transition plan describing the steps we are undertaking to ensure an orderly transfer of critical servicing functions to the new technology service provider.{{/block}}
${SIGN}`;
const CHANGE_180_RULES = [DATE_RULE, ENTITY_RULE, R("180-days", `${A2101}: 'not less than 180 days' prior written notice to Fannie Mae of its intent to change such third-party technology provider'`, "presence", "not less than 180 days' prior written notice", "180-day statement"),
  R("notice-period", "FNMA_A2101_TECH_PROVIDER_CHANGE_NOTICE_180: earliest cutover = notice date + 180 calendar days", "data_range", "days_notice", "planned cutover ≥ 180 days after the notice", { range: { min: 180 } }),
  R("providers", "19.3 outputs: provider from/to", "presence", "Current provider: .+\\. Intended provider: .+\\.", "provider from/to"), R("functions", "A2-1-01: critical servicing functions", "presence", "Critical servicing functions affected: .+; ", "critical functions listed"),
  R("function-count", "19.3 data model: tech_provider_changes.critical_functions", "data_range", "critical_function_count", "at least one critical servicing function", { range: { min: 1 } }),
  R("continuity", `${A2101}: 'account for continuity of technology service from the original third-party technology service provider'`, "presence", "Continuity of technology service from the original provider", "continuity statement"),
  R("plan-offer", `${A2101}: 'together with, upon Fannie Mae's written request, the servicer's transition plan'`, "presence", "upon Fannie Mae's written request we will provide our transition plan", "transition plan offered"),
  R("orderly-transfer", `${A2101}: 'orderly transfer of critical servicing functions'`, "presence", "orderly transfer of critical servicing functions", "orderly-transfer language"), A4101_RULE, SIGNATURE_RULE, OFFICER_RULE];
// worked example 4: notice sent Mon 2026-11-02 → earliest permissible cutover Sat 2027-05-01; a May 3 cutover is 182 days out
const CHANGE_180_SAMPLE = { ...BASE, provider_from: "Supermortgage Servicing LLC (subservicer and servicing platform)", provider_to: "NextServ Platform Inc.", critical_functions: ["mortgage loan payment processing", "remitting, accounting and reporting to Fannie Mae", "servicing solutions to borrowers in need (loss mitigation)", "borrower statements and notices"], critical_function_count: 4, planned_cutover: "2027-05-03", earliest_cutover: "2027-05-01", days_notice: 182 };

// ------------------------------------------------------------------ NTC_FNMA_A2101_CONTRACT_EVENT_5BD
const EVENT_5BD = `${HEAD("Written notice of termination, breach or impairment of rights under a technology-provider contract — within 5 business days")}
{{#block "body" page=1 y=0.2 pt=11}}Pursuant to Servicing Guide A2-1-01, {{entity_name}} gives written notice, within 5 business days after its occurrence, of the following event under its contract with a third-party technology provider for critical servicing functions ("termination, breach, or impairment of rights by servicer or the technology provider of or under such contract"). Event: {{event_kind}} — {{event_description}}. Party: {{party}}. Date of occurrence: {{date occurred_on}}. Contract: {{contract_description}} dated {{date contract_date}} between {{servicer_party}} and {{provider_name}}. Critical servicing functions covered: {{#each critical_functions}}{{this}}; {{/each}}. This notice is due {{date due_on}} (end of day Eastern Time) and is sent {{business_days_after}} Fannie Mae business day(s) after the occurrence. Status and remediation: {{remediation}}. Continuity of critical servicing functions: {{continuity_statement}}.{{/block}}
${SIGN}`;
const EVENT_5BD_RULES = [DATE_RULE, ENTITY_RULE, R("quote", `${A2101}: 'within 5 business days after its occurrence, written notice to Fannie Mae of any termination, breach, or impairment of rights by servicer or the technology provider of or under such contract'`, "presence", "termination, breach, or impairment of rights by servicer or the technology provider of or under such contract", "statutory event language"),
  R("within-5bd", A2101, "presence", "within 5 business days after its occurrence", "5-business-day statement"), R("event-kind", "FNMA_A2101_CONTRACT_EVENT_NOTICE_5BD: kind ∈ termination, breach, impairment", "data_equality", "event_kind", "event is a termination, breach or impairment", { predicate: { in: [{ var: "event_kind" }, ["termination", "breach", "impairment"]] } }),
  R("occurrence-date", "19.3 data model: contract_events.occurred_at", "presence", "Date of occurrence: (January|February|March|April|May|June|July|August|September|October|November|December) \\d{1,2}, \\d{4}", "occurrence date"),
  R("timely", "FNMA_A2101_CONTRACT_EVENT_NOTICE_5BD: +5 business_days_fannie_et (end of day ET)", "data_range", "business_days_after", "sent within 5 Fannie Mae business days", { range: { min: 0, max: 5 } }),
  R("continuity", "19.3 edge case: continuing full service until cutover ('continuity of technology service from the original … provider')", "presence", "Continuity of critical servicing functions: .+", "continuity statement"), A4101_RULE, SIGNATURE_RULE, OFFICER_RULE];
// worked example 5: termination notice Wed 2026-12-23 → BD1 Thu 24, [Fri 25], BD2 Mon 28, BD3 Tue 29, BD4 Wed 30, BD5 Thu 31 → due 2026-12-31; sent Wed Dec 30 (BD4)
const EVENT_5BD_SAMPLE = { ...BASE, notice_date: "2026-12-30", event_kind: "termination", event_description: "notice of termination of the technology-provider addendum effective 2027-06-30", party: "the technology provider (Supermortgage Servicing LLC)", occurred_on: "2026-12-23", contract_description: "Subservicing Agreement and Technology-Provider Addendum", contract_date: "2026-01-15", servicer_party: "Partner Bank, N.A.", provider_name: "Supermortgage Servicing LLC", critical_functions: ["mortgage loan payment processing", "remitting, accounting and reporting to Fannie Mae", "servicing solutions to borrowers in need"], due_on: "2026-12-31", business_days_after: 4, remediation: "a replacement technology provider is being selected; a 180-day change notice will follow and a transition plan is being prepared", continuity_statement: "Supermortgage Servicing LLC continues to perform all critical servicing functions under the addendum until cutover, which will not occur earlier than 180 days after the change notice" };

// ------------------------------------------------------------------ NTC_FNMA_A2101_CONTRACT_COPIES_5BD (cover + copy)
const COPIES_5BD = `${HEAD("Copy of a notice sent to the servicer under a technology-provider contract — within five business days")}
{{#block "body" page=1 y=0.2 pt=11}}Servicing Guide A2-1-01 requires that, in all contracts with third-party technology providers for critical servicing functions, the servicer ensure Fannie Mae is provided within five business days with copies of any termination, notice of default, breach or non-performance or any notice of impairment of rights, in each case sent to the servicer. {{entity_name}} accordingly encloses a copy of the {{copy_kind}} sent to {{sent_to}} by {{sent_by}} on {{date sent_on}}. Enclosure: {{copy_description}} (document {{copy_document_id}}, {{copy_pages}} page(s)). Contract: {{contract_description}}. Copies are due {{date due_on}} (end of day Eastern Time); this cover and the enclosed copy are sent {{business_days_after}} Fannie Mae business day(s) after the notice was sent. {{#if event_notice_sent}}The related written notice of termination, breach or impairment of rights was sent on {{date event_notice_on}}.{{/if}}{{#if attorney_review}} Counsel is confirming within the five-business-day window whether the enclosed notice constitutes a notice of default; this copy is provided in the meantime.{{/if}}{{/block}}
${SIGN}`;
const COPIES_5BD_RULES = [DATE_RULE, ENTITY_RULE, R("quote", `${A2101}: 'ensure Fannie Mae is provided within five business days with copies of any termination, notice of default, breach or non-performance or any notice of impairment of rights, in each case sent to the servicer'`, "presence", "copies of any termination, notice of default, breach or non-performance or any notice of impairment of rights, in each case sent to the servicer", "clause language"),
  R("enclosure", "19.3 outputs: NTC_FNMA_A2101_CONTRACT_COPIES_5BD (cover + copy)", "presence", "Enclosure: .+ \\(document [A-Za-z0-9_.-]+, \\d+ page\\(s\\)\\)", "the copy is enclosed"), R("copy-attached", "FNMA_A2101_CONTRACT_COPIES_5BD: satisfied by `fnma_notices.sent{a2101_copies_5bd}` with the copy attached", "data_equality", "copy_document_id", "copy document attached", { predicate: { present: "copy_document_id" } }),
  R("copy-kind", "FNMA_A2101_CONTRACT_COPIES_5BD: kind ∈ termination, default_notice, breach_notice, non_performance_notice, impairment_notice", "data_equality", "copy_kind", "copy is one of the five notice kinds", { predicate: { in: [{ var: "copy_kind" }, ["termination", "notice of default", "breach notice", "non-performance notice", "notice of impairment of rights"]] } }),
  R("direction", "FNMA_A2101_CONTRACT_COPIES_5BD: direction = sent_to_servicer", "data_equality", "direction", "notice was sent to the servicer", { predicate: { "==": [{ var: "direction" }, "sent_to_servicer"] } }),
  R("timely", "FNMA_A2101_CONTRACT_COPIES_5BD: +5 business_days_fannie_et from the sent date", "data_range", "business_days_after", "sent within five Fannie Mae business days", { range: { min: 0, max: 5 } }), A4101_RULE, SIGNATURE_RULE, OFFICER_RULE];
// worked example 5: notice of default sent to the partner Fri 2026-11-20 → Mon 23, Tue 24, Wed 25, [Thu 26 Thanksgiving], Fri 27, Mon 30 → copies due Mon 2026-11-30; sent Wed Nov 25 (BD3)
const COPIES_5BD_SAMPLE = { ...BASE, notice_date: "2026-11-25", copy_kind: "notice of default", sent_to: "Partner Bank, N.A. (the servicer)", sent_by: "Supermortgage Servicing LLC (technology provider)", sent_on: "2026-11-20", copy_description: "Notice of default — non-payment of technology-service fees under the Technology-Provider Addendum", copy_document_id: "doc-nod-2026-11-20", copy_pages: 2, direction: "sent_to_servicer", contract_description: "Subservicing Agreement and Technology-Provider Addendum dated January 15, 2026", due_on: "2026-11-30", business_days_after: 3, event_notice_sent: true, event_notice_on: "2026-11-25", attorney_review: true };

// ------------------------------------------------------------------ NTC_FNMA_LL2026_04_DISCLOSURE
const LL2026_04 = `{{#block "heading" page=1 y=0.05 pt=14 bold}}Lender Letter LL-2026-04 — disclosure of AI/ML use in response to Fannie Mae's request{{/block}}
{{#block "ref" page=1 y=0.1 pt=11}}{{date notice_date}}. To: {{fnma_contact}}. From: {{entity_name}} ({{entity_role}}; Fannie Mae seller/servicer number {{servicer_number}}). Re: your request dated {{date request_on}} under Lender Letter LL-2026-04 (effective August 6, 2026); response due {{date due_on}}.{{/block}}
{{#block "body" page=1 y=0.2 pt=11}}{{entity_name}} promptly discloses the types of AI/ML used, the purpose and manner for such use, the safeguards implemented to mitigate risks, and the other information requested. 1. Types of AI/ML used: {{#each ai_types}}{{this}}; {{/each}}. 2. Purpose and manner of use, by agent: {{#each agents}}{{name}} — purpose: {{purpose}}; manner: {{manner}}; risk tier: {{risk_tier}}; {{/each}}. 3. Safeguards implemented to mitigate risks: {{#each safeguards}}{{this}}; {{/each}}. 4. Subcontractor and vendor use of AI/ML is managed under controls no less protective than our own: {{vendor_flowdown}}. 5. Governance: written policies covering the development, implementation, use, maintenance and risk measurement of AI/ML are transparent and communicated to appropriate personnel and are reviewed at least annually by the designated owner(s), {{policy_owner}} (last review {{date policy_reviewed_on}}); the program complies with the Information Security and Business Resiliency Supplement. 6. Model/agent inventory export: {{inventory_document_id}} ({{inventory_count}} systems, with model and prompt versions, evaluation results and human touchpoints).{{/block}}
{{#block "signature" page=1 y=0.85 pt=11}}Signed and sent by {{officer_name}}, {{officer_title}} (officer), by {{channel}} on {{date notice_date}}. Further information will be provided promptly upon request.{{/block}}`;
const LL2026_04_RULES = [DATE_RULE, ENTITY_RULE, R("quote", "LL-2026-04: 'Upon request by Fannie Mae, the seller/servicer must promptly disclose the types of AI/ML used, the purpose and manner for such use, the safeguards … implemented to mitigate risks, and such other information as Fannie Mae may require'", "presence", "types of AI/ML used, the purpose and manner for such use, the safeguards implemented to mitigate risks", "statutory disclosure scope"),
  R("types", "19.3 rule 10: AI types (LLM agents; voice AI; ML scoring if any)", "presence", "1\\. Types of AI/ML used: .+; ", "types listed"), R("type-count", "19.3 rule 10", "data_range", "ai_type_count", "at least one AI/ML type", { range: { min: 1 } }),
  R("purposes", "19.3 rule 10: purposes by agent, manner of use (tool allowlists, human touchpoints)", "presence", "2\\. Purpose and manner of use, by agent: .+ — purpose: .+; manner: .+; risk tier: .+; ", "purpose and manner per agent"),
  R("safeguards", "19.3 rule 10: safeguards (evaluation suites, monitoring, bias testing 19.4, decision records, vendor clauses)", "presence", "3\\. Safeguards implemented to mitigate risks: .+; ", "safeguards listed"),
  R("flowdown", "LL-2026-04: manage 'subcontractor and vendor use of AI/ML that is no less protective'", "presence", "no less protective", "vendor flow-down statement"), R("annual-review", "LL-2026-04: designated owner(s) reviewing 'at least annually'", "presence", "reviewed at least annually by the designated owner", "annual review statement"),
  R("supplement", "LL-2026-04: comply with the Information Security and Business Resiliency Supplement", "presence", "Information Security and Business Resiliency Supplement", "Supplement reference"),
  R("inventory", "19.3 rule 10: model/agent inventory export", "presence", "inventory export: [A-Za-z0-9_.-]+ \\(\\d+ systems", "inventory export attached"), R("inventory-attached", "19.3 data model: ai_systems (LL-2026-04 inventory)", "data_equality", "inventory_document_id", "inventory document attached", { predicate: { present: "inventory_document_id" } }),
  R("inventory-count", "19.3 data model: ai_systems", "data_range", "inventory_count", "at least one system in the inventory", { range: { min: 1 } }),
  R("timely", "FNMA_LL2026_04_DISCLOSURE_PROMPT_5BD: +5 business_days_fannie_et (policy for 'promptly')", "data_range", "business_days_after", "sent within 5 Fannie Mae business days of the request", { range: { min: 0, max: 5 } }), SIGNATURE_RULE, OFFICER_RULE];
// T10: request received Mon 2026-10-05 → Tue 6, Wed 7, Thu 8, Fri 9, [Mon 12 Columbus Day], Tue 13 → due 2026-10-13 (docs/AUDIT-NOTES.md); sent Fri Oct 9 (BD4)
const LL2026_04_SAMPLE = { ...BASE, notice_date: "2026-10-09", entity: "supermortgage", entity_name: "Supermortgage Servicing LLC", entity_role: "subservicer", servicer_number: "26789-000-2", request_on: "2026-10-05", due_on: "2026-10-13", business_days_after: 4, ai_types: ["large-language-model agents (servicing workflows)", "voice AI (inbound call handling)", "ML scoring (none in production)"], ai_type_count: 3, agents: [{ name: "lossmit-underwriter", purpose: "loss mitigation eligibility and offer preparation (12.x)", manner: "tool allowlist; officer/lossmit_reviewer approve every offer; decision records", risk_tier: "high_consequential" }, { name: "security-records", purpose: "records, vendor and contract custody (19.x)", manner: "read/draft tools only; officer signs every Fannie Mae notice", risk_tier: "medium" }], safeguards: ["pre-deploy evaluation suites (SM_AI_SYSTEM_EVAL_BEFORE_DEPLOY)", "production monitoring dashboards", "quarterly fair-servicing bias testing (19.4)", "agent decision records on every act", "vendor clauses: no training on inputs/outputs, zero retention, US processing"], vendor_flowdown: "the AI model provider is a Tier 1 vendor with executed NO_TRAINING_ON_DATA, ZERO_RETENTION and US_PROCESSING clauses and an LL-2026-04 governance attestation", policy_owner: "Chief Information Security Officer and Chief Servicing Officer", policy_reviewed_on: "2026-08-20", inventory_document_id: "doc-ai-inventory-2026-10-09", inventory_count: 12 };

export const VERSIONS_19_3: VersionInput[] = [
  V("NTC_FNMA_A2101_TECH_PROVIDER_CHANGE_180", CHANGE_180, CHANGE_180_RULES, CHANGE_180_SAMPLE, "19.3@notices.v1", "Servicing Guide A2-1-01 (12/17/2025; Guide edition Aug. 12, 2026): 180 days' prior written notice of intent to change a third-party technology provider; worked example 4 (notice 2026-11-02 → earliest cutover 2027-05-01)"),
  V("NTC_FNMA_A2101_CONTRACT_EVENT_5BD", EVENT_5BD, EVENT_5BD_RULES, EVENT_5BD_SAMPLE, "19.3@notices.v1", "Servicing Guide A2-1-01: written notice within 5 business days of any termination, breach, or impairment of rights; worked example 5 (termination 2026-12-23 → due 2026-12-31)"),
  V("NTC_FNMA_A2101_CONTRACT_COPIES_5BD", COPIES_5BD, COPIES_5BD_RULES, COPIES_5BD_SAMPLE, "19.3@notices.v1", "Servicing Guide A2-1-01 contract clause: copies of any termination, notice of default, breach or non-performance or notice of impairment of rights sent to the servicer within five business days; worked example 5 (default notice Fri 2026-11-20 → due Mon 2026-11-30)"),
  V("NTC_FNMA_LL2026_04_DISCLOSURE", LL2026_04, LL2026_04_RULES, LL2026_04_SAMPLE, "19.3@notices.v1", "Lender Letter LL-2026-04 (Apr. 8, 2026; effective Aug. 6, 2026): prompt disclosure of AI/ML types, purpose and manner, safeguards and inventory on request; T10 (request 2026-10-05 → due 2026-10-13, Columbus Day excluded)"),
];
export const OVERRIDES_19_3: Record<string, Partial<NoticeTemplate>> = {
  NTC_FNMA_A2101_TECH_PROVIDER_CHANGE_180: { noticeClass: "fnma_corporate_notices", channelPolicy: "electronic_ok_without_esign", citation: "Servicing Guide A2-1-01 (180 days' prior written notice); open decision 3: letter + email to the Fannie Mae account team", separateDocument: true, retention: "fnma_reporting_7y", piiLevel: "low" },
  NTC_FNMA_A2101_CONTRACT_EVENT_5BD: { noticeClass: "fnma_corporate_notices", channelPolicy: "electronic_ok_without_esign", citation: "Servicing Guide A2-1-01 (written notice within 5 business days of termination, breach or impairment); Selling Guide A4-1-01", separateDocument: true, retention: "fnma_reporting_7y", piiLevel: "low" },
  NTC_FNMA_A2101_CONTRACT_COPIES_5BD: { noticeClass: "fnma_corporate_notices", channelPolicy: "electronic_ok_without_esign", citation: "Servicing Guide A2-1-01 contract clause (copies within five business days)", separateDocument: false, mayCombineWith: ["NTC_FNMA_A2101_CONTRACT_EVENT_5BD"], retention: "fnma_reporting_7y", piiLevel: "low" },
  NTC_FNMA_LL2026_04_DISCLOSURE: { noticeClass: "fnma_corporate_notices", channelPolicy: "electronic_ok_without_esign", citation: "Lender Letter LL-2026-04 (prompt disclosure on request); Information Security and Business Resiliency Supplement", separateDocument: true, retention: "fnma_reporting_7y", piiLevel: "low" },
};
