/**
 * §9.7 timer overrides (process-owned; the §9 section-level overrides in ./timers.ts run first and these win the
 * merge — see src/domain/bankruptcy/timers-14-1.ts for the pattern). One `reg.override(code, { trigger?, satisfied |
 * evaluator, anchorField?, offset?, why })` per 9.7 registry row whose trigger/satisfied column names an event the
 * platform spells differently or a condition the column grammar drops; `why` quotes the spec. Wired by
 * src/domain/timer-overrides.ts. The emitters are src/domain/insurance/ops-9-7.ts (called by the 9.7 tools in
 * src/app/tools/section09.ts and by the inbound feeds this process consumes); src/kernel/events/match.ts compares
 * conditions as exact strings on payload fields, so every conditioned field below is one those emitters carry.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_9_7(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // ---- B-5-01 proof of loss: "within the time period specified in the insurance policy" — borrower or servicer (mortgagee clause)
  o("FNMA_B501_PROOF_OF_LOSS_POLICY", { satisfied: "`claim.proof_of_loss.filed{filed_by∈{borrower, servicer}}`", why: "§9.7 timer table: satisfied by '`claim.proof_of_loss.filed` (borrower or servicer)' — fileProofOfLoss ingests the borrower's filing (portal upload / carrier acknowledgment) or the servicer's own filing under the mortgagee clause (B-5-01: 'if contact with the borrower is lost … file under the mortgagee clause'); the anchor `loss_date` and the 60-day default come from the section override." });
  // ---- rule 4: contents / ALE "without delay" — the deposit that carries a contents designation opens the 2-BD clock
  o("INS_CLAIM_CONTENTS_RELEASE_2BD", { trigger: "`claim.proceeds.deposited{contents_ale_cents>0}`", anchorField: "deposited_on", satisfied: "`claim.funds.released{kind=contents_ale}`", why: "§9.7 timer table: trigger '`claim.proceeds.deposited` with contents/ALE portion', anchor 'deposit', satisfied by '`claim.disbursement.released` kind contents_ale' — depositProceeds carries the adjuster's contents/ALE designation as `contents_ale_cents` (a deposit with none arms nothing), and the platform's release event is `claim.funds.released{kind}` (releaseProceeds; the same spelling the section already uses for INS_CLAIM_INITIAL_RELEASE_5BD). Rule 4: 'released to the borrower \"without delay\" (2 business days policy) even when the instrument is one check — deposit, then disburse' (T4: Monday deposit → Wednesday)." });
  // ---- policy: deposit + repair intent known → initial release within 5 BD (the section's trigger; the anchor is the deposit date)
  o("INS_CLAIM_INITIAL_RELEASE_5BD", { anchorField: "deposited_on", why: "§9.7 timer table: anchor 'deposit' — depositProceeds carries `deposited_on` (the ET civil date of the custodial deposit) alongside `repair_intent_known`, the section override's trigger condition." });
  // ---- rule 9: Form 176 within 5 business days of learning of the damage (abandoned / FC-scheduled) OR of the decision not to repair
  o("FNMA_B501_FORM176_ABANDONED_5BD", { trigger: "`claim.form176.required{cause∈{damage_learned, no_repair_decision}}`", anchorField: "learned_on", why: "§9.7 timer table: trigger 'learning of damage (abandoned/FC-scheduled, intends to repair) or of decision not to repair', anchor 'learning date' — the grammar holds one trigger, so reportClaim (damage learned on an abandoned or FC-scheduled property) and recordRepairDecision (the later decision not to repair) both emit `claim.form176.required{cause, learned_on}`; B-5-01: 'submit Form 176 within five business days of learning of the damage' / 'of learning of the decision' (T5: 2027-03-08 → 2027-03-15). Satisfied by `claim.form176.sent` (sendForm176, a `fnma_portal_operator` act)." });
  // ---- rule 9: short sale — remit at closing (CRS 332); the platform's remittance instruction event (5.2 rails)
  o("FNMA_B501_REMIT_SHORTSALE_332_0", { anchorField: "closed_on", satisfied: "`remittances.instructed{crs_code=332}`", why: "§9.7 timer table: trigger `shortsale.closed`, anchor 'closing date', satisfied by '`remittance.sent` code 332' — the 5.2 remittance rail's event is `remittances.instructed{crs_code}` (as the section already uses for FNMA_B501_REMIT_PROCEEDS_REOGRAM_30 and 16.2 for code 001); remit332 emits it with `crs_code=332`; ingestShortSaleClosing carries `closed_on` from the settlement statement (B-5-01: 'short sale — remit the remaining proceeds at closing via CRS remittance code 332')." });
  // ---- rule 9: REOgram confirmed → remit within 30 days, anchored on the confirmation date 15.1 carries
  o("FNMA_B501_REMIT_PROCEEDS_REOGRAM_30", { anchorField: "confirmed_at", why: "§9.7 timer table: anchor 'confirmation date' — 15.1's `reogram.confirmed` carries `confirmed_at` (the P360 confirmation instant; its ET civil date anchors the 30 calendar days; T6: 2027-05-03 → 2027-06-02)." });
  // ---- rule 9: proceeds received after the REOgram → wired within 10 fannie_et BD of receipt (not of deposit)
  o("FNMA_B501_WIRE_POSTREOGRAM_PROCEEDS_10BD", { anchorField: "received_on", why: "§9.7 timer table: anchor 'receipt' — depositProceeds carries `received_on` (the instrument's receipt date) with the section override's `reogram_confirmed=true` condition; remit332 emits `claim.proceeds.wired` for the post-REOgram wire (T6: received 2027-06-10 → 2027-06-25 on the fannie_et calendar, Juneteenth observed Friday 2027-06-18 skipped)." });
  // ---- policy: draw request → inspection ordered within 3 BD, anchored on the request date
  o("INS_CLAIM_INSPECTION_ORDER_3BD", { anchorField: "requested_on", why: "§9.7 timer table: anchor 'request' — requestDraw (the borrower's portal / call / contractor-invoice draw request, or the 30-day progress-check due) carries `requested_on`; satisfied by orderRepairInspection's `property.inspection.ordered{kind=repair}`." });
  // ---- F-1-05: repair-inspection cost on a current loan → 15.2 claim within 365 days; the claim submission is 15.2's event
  o("FNMA_F105_INSURED_LOSS_INSPECT_CLAIM_365", { anchorField: "incurred_on", satisfied: "`expense_claim.status_changed{status=submitted}`", why: "§9.7 timer table: trigger 'inspection cost incurred (current loan)', anchor 'cost date', satisfied by '15.2 claim filed' — recordRepairInspection emits `property.inspection.cost_incurred{delinquent, incurred_on}` from the vendor's report and invoice; 15.2's submission event is `expense_claim.status_changed{status=submitted}` (submitClaim / bulk upload), the platform's spelling of 'claim filed' (F-1-05: 'claims for current loans within one year of the cost'; $60/inspection cap)." });
  // ---- D1-3-01 (owned by 13.x): the damage determination on a disaster-impacted loan in pre-referral review → submission within 5 days
  o("FNMA_D1301_DISASTER_FC_APPROVAL_5", { anchorField: "determined_on", why: "§9.7 timer table: trigger 'disaster impact determination / pre-referral review complete', anchor '—' — reportClaim emits `disaster.impact.determined{foreclosure_prereferral, determined_on}` when the loss is tied to a declared disaster (D1-3-01: 'determine damage (borrower information or inspection)'); the anchor is that determination date; satisfied by `fnma.disaster_fc_approval.submitted`, which portalTaskCompleted appends only when the Fannie Mae submission carries this process's claim date, status and expected/received disbursements ('submission within 5 days; contents include insurance-claim date, status and expected/received disbursements — Section 13')." });
}
