/**
 * §16.4 timer overrides: for every 16.4 registry row whose trigger/anchor/"Satisfied by" column is prose (or a bare
 * token the pattern grammar would read as a truthy payload key — `{deactivation_paid_in_full}`, `{deactivation}`),
 * a `reg.override(code, { satisfied | evaluator, trigger?, offset?, anchorField?, why })`
 * (see src/domain/foreclosure/timers.ts applyForeclosureSatisfiedOverrides for the pattern).
 * Called from this section's timers.ts after the section-level overrides, so these win the merge.
 *
 * Every trigger and satisfier below names an event with a real emitter and the payload fields the pattern
 * conditions on: the 16.4 tool (src/app/tools/section16-4.ts checkDeactivationEligibility ops) appends
 * `mers.deactivation.submit_requested|requested|eligible|multi_county_warning|reversal_needed`,
 * `mers.txn.accepted{txn_type, min, accepted_at, enote, paper_note_return_required}`, `mers.snapshot.verified{status}`,
 * `enote.status.paid_off{status}`; the 1.5 ack ingestion (src/domain/transfers/inbound.ts recordMersAcknowledgement)
 * appends `mers.txn.accepted{txn_type}` for a batch built from the 16.4 prepared rows; the Notice Registry
 * (src/notices/service.ts) appends `notice.sent{template}` when the F-1-09 letter is mailed; 16.2 postPayoff appends
 * `loan.paid_in_full{payoff_date}` (its payload must also carry `enote` for the eNote row to arm — a 16.2 change).
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_16_4(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  o("SM_MERS_NO_DEACTIVATE_BEFORE_RELEASE_GATE", { trigger: "`mers.deactivation.submit_requested`", evaluator: "16.4.allCountiesRecorded", satisfied: "`mers.deactivation.requested`", why: "§16.4 timer table: not_before_gate on deactivation submit — `release_tasks.status ∈ {recorded, third_party_recorded}` for all counties; breach: block. The tool appends `mers.deactivation.submit_requested` on every prepare/submit attempt *before* asserting the registered evaluator (the 16.3 `lien_release.execution_requested` → `16.3.lpoaRecordedForState` pattern), so a blocked attempt arms the gate instance with the evaluator closed on its facts and logs `mers.deactivation.refused` + `command.refused` (T2); the prepared transaction's `mers.deactivation.requested` (state eligible → prepared) satisfies it. Rule 1 makes the evaluator strict: no release task at all is no recording evidence (closed), and a `third_party_recorded` task opens the gate only after the recorded third-party instrument is verified against the land records (`third_party_verified`); evaluators-16-4.ts \"16.4.allCountiesRecorded\" over ops-16-4.ts releaseRecordedGate — the same predicate the tool refuses on." });
  o("MERS_PROC_PAID_IN_FULL_DEACTIVATE_60", { trigger: "`mers.deactivation.eligible`", anchorField: "last_recorded_at", satisfied: "`mers.txn.accepted{txn_type=deactivation_paid_in_full}`", why: "§16.4 timer table: `lien_release.recorded` (last county), anchor recorded_at, +60 calendar days, satisfied by the accepted Paid-in-Full deactivation ack. The registry's bare `{deactivation_paid_in_full}` would parse as a truthy payload key; the ack carries `txn_type` (16.4 ingestMersAck op and 1.5 recordMersAcknowledgement alike), so the satisfier is `mers.txn.accepted{txn_type=deactivation_paid_in_full}`. 16.3 emits one `lien_release.recorded` per county with no last-county marker, so the row arms on the state-machine transition awaiting_release → eligible (`mers.deactivation.eligible{last_recorded_at}`), which checkDeactivationEligibility appends once per (min, txn_type, effective_date) when every county's recording evidence is in — T3: the 60-day timer anchors on 11/10 while the 10/26 recording raises `mers.deactivation.multi_county_warning` (conservative due 12/25) instead of a premature instance; T1: 10/26 → 12/25. Breach sev-1; QA finding; `officer` (partner) notified (Rule 7 exposure)." });
  o("SM_MERS_DEACTIVATE_TARGET_5BD", { trigger: "`mers.deactivation.eligible`", anchorField: "last_recorded_at", satisfied: "`mers.txn.accepted{txn_type=deactivation_paid_in_full}`", why: "§16.4 timer table: 'same' as MERS_PROC_PAID_IN_FULL_DEACTIVATE_60 — the accepted Paid-in-Full deactivation ack (`mers.txn.accepted{txn_type=deactivation_paid_in_full}`); policy target +5 BD (servicer) from the last recording, armed by the same `mers.deactivation.eligible{last_recorded_at}` transition (10/26 → 11/02; 11/10 → 11/18 across Veterans Day). Breach sev-3." });
  o("SM_MERS_DEACTIVATION_VERIFY_3BD", { trigger: "`mers.txn.accepted{txn_type=deactivation_paid_in_full}`", anchorField: "accepted_at", satisfied: "`mers.snapshot.verified{status=inactive}`", why: "§16.4 timer table: `mers.txn.accepted{deactivation}` → post-acceptance snapshot `status = inactive` with the Paid-in-Full reason within +3 BD of accepted_at. The bare `{deactivation}` would be a truthy key check; the ack's `txn_type=deactivation_paid_in_full` is the condition. The snapshotMins op (rule 4, T1) appends `mers.snapshot.verified{min, status=inactive, reason}`; the 1.5 post-transfer snapshot event carries no `status` and does not satisfy this row. Spec-internal discrepancy: 16.4-T1 says 'by 10/29' (3 BD from the 10/26 recording) while this row anchors accepted_at (ack accepted 10/27 → 10/30); the engine keeps the row's anchor and the worked example's 10/28 snapshot satisfies both. Breach sev-3; resubmit/inquiry." });
  o("SM_ENOTE_PAIDOFF_STATUS_2BD", { trigger: "`loan.paid_in_full{enote=true}`", anchorField: "payoff_date", satisfied: "`enote.status.paid_off{status∈{requested, confirmed}}`", why: "§16.4 timer table (policy; F-1-09 'update the MERS eRegistry'): `loan.paid_in_full{enote}` → the eRegistry 'Paid Off' status change requested/confirmed within +2 BD of the payoff date (16.2 `loan.paid_in_full{payoff_date}`; its payload must carry `enote` — 16.2 postPayoff). The requestENoteStatus op writes the `mers_eregistry_transactions` row (change_status_paid_off, status requested → accepted/rejected/confirmed) and appends `enote.status.paid_off{status}`; a reject does not satisfy. T5: payoff Fri 10/16 → by Tue 10/20. Breach sev-2." });
  o("SM_ENOTE_PAPER_COPY_10BD", { trigger: "`mers.txn.accepted{txn_type=deactivation_paid_in_full, enote=true, paper_note_return_required=true}`", anchorField: "accepted_at", satisfied: "`notice.sent{template=NTC_ENOTE_PAPER_COPY}`", why: "§16.4 timer table (policy; F-1-09): `mers.txn.accepted{deactivation}` on an eNote in a paper-return state → `NTC_ENOTE_PAPER_COPY` mailed with the marked copy within +10 BD of accepted_at. The ingestMersAck op stamps the loan facts (`enote`, `paper_note_return_required` from `jurisdiction_rules.release.paper_note_return_required`) on the ack event, so only an eNote in a paper-return state arms the row; the satisfier is the platform's mailing event `notice.sent{template=NTC_ENOTE_PAPER_COPY}` (Notice Registry, mail_only), which the printENoteCopy op and 16.3 notifyBorrower{op=enote_paper_copy} both produce — the op also records the `enote.paper_copy.sent` loan event (Outputs). Spec-internal discrepancy: 16.4-T5's 'mailed by 11/09' is 10 BD from the 10/26 recording — enoteOverlay reports it as the policy `mail_by` and this row's date (10/27 → 11/10) as `timer_due_on`; acceptance follows recording, so the policy date is never later than the timer. Breach sev-2." });
  o("SM_MERS_DEACT_REVERSAL_5BD", { trigger: "`mers.deactivation.reversal_needed`", anchorField: "reversal_needed_on", satisfied: "`mers.txn.accepted{txn_type=deactivation_reversal}`", why: "§16.4 timer table: `payoff.reversed` *after deactivation* → reversal transaction accepted within +5 BD of the reversal. 16.2's `payoff.reversed` carries no deactivation qualifier (a payoff reversed before the release records cancels eligibility — nothing to reverse, edge cases), so the row arms on the state-machine transition to `reversal_needed` (`mers.deactivation.reversal_needed{min, reversal_needed_on, cause}`), which the reversal op appends only when a documented cause meets an accepted deactivation (rule 6); anchor = the payoff-reversal date. Satisfied by the accepted reversal ack (`mers.txn.accepted{txn_type=deactivation_reversal}`); the reactivated snapshot then closes the reversal (`mers.deactivation.reversed`). T6: 10/28 → 11/04. Breach sev-2; `officer`." });
}
