/**
 * §16.3 timer overrides: for every 16.3 registry row whose trigger, anchor or "Satisfied by" column is
 * prose (or names a payload field no emitter produces), a `reg.override(code, { trigger?, anchorField?,
 * offset?, satisfied | evaluator, why })` (see src/domain/foreclosure/timers.ts). Called from this
 * section's timers.ts after the section-level overrides, so these win the merge.
 *
 * Arming: 16.2's `loan.paid_in_full` (src/app/tools/section16-2.ts postPayoff) carries
 * `{ settlement_id, payoff_date, remittance_type, escrowed, autodraft, mi_active, … }` — no state, no
 * mortgagee kind, no recording path. The spec's first 16.3 step is "`loan.paid_in_full` → open
 * `release_tasks`": src/app/tools/section16-3.ts releaseReactors_16_3 performs it on that very event (state
 * from the event or the loans/properties rows) and, like the agent's selectReleaseInstrument for a task it
 * opens first, emits `lien_release.task_opened{state, mortgagee_kind, recording_path, original_note_required,
 * payoff_on, funds_received_on, md_delivery_anchor, statutory_release_due, submit_by}` — the state-keyed
 * rows arm from that event with the computed anchors (src/domain/payoff/ops-16-3.ts taskOpenedPayload), so
 * the sev-1 statutory clock exists the moment the payoff posts. Satisfaction names events the 16.3 tools
 * (src/app/tools/section16-3.ts) or the Notice Registry (`notice.sent{template=…}`) emit; the statutory
 * clock waits on the `lien_release.*{statutory_duty=satisfied}` family (recorded, or delivered where the
 * statute is satisfied by delivery).
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_16_3(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // ---- statutory and policy clocks from payoff
  o("STATE_LIEN_RELEASE_DEADLINE", { trigger: "`lien_release.task_opened`", anchorField: "statutory_release_due", offset: "0", satisfied: "`lien_release.*{statutory_duty=satisfied}`", why: "§16.3 timer table: per `jurisdiction_rules.release.deadline_days` from the payoff date (calendar days; no weekend roll-forward — rule 6, decision 3). Trigger: the spec's `loan.paid_in_full` carries no state, so src/app/tools/section16-3.ts releaseReactors_16_3 opens the `release_tasks` row from that event itself (Inputs: '`loan.paid_in_full` → open `release_tasks`') and its synchronous `lien_release.task_opened{state, statutory_release_due, …}` arms this clock on the computed anchor (ops-16-3.ts statutoryDeadline: OH 10/16 + 90 = 2027-01-14) with no agent action; the agent's selectReleaseInstrument refreshes the row (`lien_release.task_updated`, no re-arming). Satisfied by: the registry column names `lien_release.recorded` *or* `delivered` where the statute is satisfied by delivery (MA G.L. c.183 §55; MD Real Prop. §7-106) — and for a CA deed of trust the beneficiary's §2941(b)(1)(A) duty is delivery to the trustee — so the one engine pattern is the family `lien_release.*` carrying `statutory_duty=satisfied`: submitRecording puts it on `lien_release.recorded` (op=recorded / trustee_recorded, hashed image), on `lien_release.delivered{to=settlement_agent}` for MA/MD (op=settlement_agent_delivery with evidence) and on `lien_release.delivered_to_trustee` for CA (op=trustee_delivery with evidence; ops-16-3.ts statutoryDutyEvent); every other lien_release event carries no such field. The instance is *satisfied* by that event (timer history shows satisfied, never cancelled) and the recording monitor SM_RECORDING_CONFIRM_30 continues. Breach: sev-1, `penalty_exposure_cents` computed (computePenaltyExposure, off the row and this instance's status), `officer` notice; F-1-09 penalty never passed through." });
  o("SM_RELEASE_PREPARE_5BD", { anchorField: "payoff_date", why: "§16.3 timer table: `loan.paid_in_full` → `lien_release.prepared` within +5 servicer business days of the payoff date (`payoff_date` on 16.2's event; WE1: Fri 10/16 → Fri 10/23). runReleaseChecklist emits `lien_release.prepared` on a passed checklist (rule 3)." });
  o("SM_RELEASE_EXECUTE_3BD", { satisfied: "`lien_release.executed`", why: "§16.3 timer table: `lien_release.prepared` (anchor prepared_at) → `lien_release.executed` within +3 BD (signing_officer SLA; WE1: 10/23 → 10/28). scheduleNotarySession op=completed emits `lien_release.executed` from the RON/e-sign platform's completion evidence; routeForExecution op=fnma_returned emits it for the Fannie Mae path. Breach sev-2; reassign officer." });
  o("SM_RELEASE_SUBMIT_21", { trigger: "`lien_release.task_opened`", anchorField: "submit_by", offset: "0", why: "§16.3 timer table: +21 calendar days from payoff *or `deadline − 7` when shorter* — the computed anchor `submit_by = min(payoff + 21, statutory deadline − 7)` on `lien_release.task_opened` (ops-16-3.ts openReleaseTask: OH 11/06; MD 10/16 + 7 − 7 = 10/16). Satisfied by `lien_release.submitted` (submitRecording). Breach sev-2." });
  // ---- state statutory clocks (state-keyed filters on the task-opened event)
  o("MD_RP_7106_RELEASE_DELIVERY_7", { trigger: "`lien_release.task_opened{state=MD}`", anchorField: "md_delivery_anchor", satisfied: "`lien_release.delivered{state=MD, to=settlement_agent, evidence_document_id present}`", why: "§16.3 timer table: 'executed release delivered to the disbursing settlement agent' within +7 calendar days of receipt of certified funds/wire *(or clearance)* — `md_delivery_anchor` on the task-opened event is the receipt date for a wire/certified funds and the clearance date for other paper (ops-16-3.ts fundsAnchor from `funds_kind` / `funds_cleared_on`; an unknown kind or a clearance not yet known keeps the earliest date, receipt, flagged `funds_anchor_basis`) (WE3: wire Fri 10/16 → due Fri 10/23); submitRecording op=settlement_agent_delivery emits `lien_release.delivered` only with a delivery-evidence document (rule 6: 'delivery with evidence satisfies the timer'); the same event satisfies STATE_LIEN_RELEASE_DEADLINE (statutory_duty=satisfied) and recording stays monitored by SM_RECORDING_CONFIRM_30 (Md. Real Prop. §7-106). Breach sev-1." });
  o("NJ_46_18_112_RIGHT_TO_DEMAND_NOTICE_10", { trigger: "`lien_release.task_opened{state=NJ, mortgagee_kind=nonbank}`", anchorField: "payoff_on", satisfied: "`notice.sent{template=NTC_NJ_CANCELLATION_RIGHT}`", why: "§16.3 timer table: nonbank mortgagee → '`NTC_NJ_CANCELLATION_RIGHT` sent (or cancellation already submitted)' within +10 calendar days of payoff (T6: 10/16 → 10/26) — the Notice Registry's `notice.sent{template=…}` event from notifyBorrower op=nj_cancellation_right (N.J.S.A. 46:18-11.2). Breach sev-2." });
  o("CA_CC2941_TRUSTEE_DELIVERY_30", { trigger: "`lien_release.task_opened{state=CA, recording_path=trustee_third_party}`", anchorField: "payoff_on", satisfied: "`lien_release.delivered_to_trustee{state=CA, evidence_document_id present}`", why: "§16.3 timer table: CA deed of trust with a third-party trustee → 'note, DOT and reconveyance request delivered to trustee (or substitution+reconveyance recorded)' within +30 calendar days of payoff, no roll-forward (WE2: 10/16 → Sun 11/15) — submitRecording op=trustee_delivery emits the courier delivery evidence with `statutory_duty=satisfied` — the beneficiary's §2941(b)(1)(A) duty is met by delivery, so the same event satisfies STATE_LIEN_RELEASE_DEADLINE (Cal. Civ. Code §2941(b)(1)); the substitution variant records directly (recording_path=direct), never arms this row, and an auto-opened task whose selection later turns out to be the substitution variant has this instance retired by selectReleaseInstrument. Breach sev-1 ($500 forfeiture, §2941(d))." });
  o("CA_CC2941_TRUSTEE_RECORD_21", { anchorField: "delivered_on", satisfied: "`trustee.reconveyance.recorded{state=CA}`", why: "§16.3 timer table: delivery to trustee (`lien_release.delivered_to_trustee`, anchor the trustee's receipt = `delivered_on` of the evidence) → 'reconveyance recorded' within +21 calendar days (WE2: 10/28 → 11/18) — submitRecording op=trustee_recorded ingests the recorded reconveyance and emits `trustee.reconveyance.recorded` (and `lien_release.recorded` for the statutory clock, borrower notice and 16.4) (Cal. Civ. Code §2941(b)(1)(B)). Breach: chase trustee; sev-2." });
  o("NY_RPAPL1921_NOTE_RETURN_45", { trigger: "`lien_release.note_return_requested{state=NY}`", anchorField: "requested_on", satisfied: "`lien_release.note_returned{state=NY}`", why: "§16.3 timer table: borrower/designee request for the note and mortgage (notifyBorrower op=note_return_requested emits `lien_release.note_return_requested{state, requested_on}`) → 'originals delivered' within +45 calendar days of the request — notifyBorrower op=note_returned emits `lien_release.note_returned` with the NTC_NOTE_RETURNED cover letter (N.Y. RPAPL §1921). Breach sev-1." });
  // ---- originals (Form 2009)
  o("FNMA_F110_FORM2009_CUSTODY_REQUEST_1BD", { trigger: "`lien_release.task_opened{original_note_required=true}`", anchorField: "payoff_on", why: "§16.3 timer table: `loan.paid_in_full{original_note_required}` → `custody.documents.requested` within +1 BD of payoff (WE2: Fri 10/16 → Mon 10/19) — `original_note_required` is computed on the task-opened event from `jurisdiction_rules.release` (CA trustee, CO, MD, NY on request, recorder demand; rule 2); requestCustodyDocuments emits `custody.documents.requested` (F-1-10 Form 2009). Breach sev-2." });
  o("SM_CUSTODY_DOCS_RETURN_10BD", { why: "§16.3 timer table: `custody.documents.requested` (anchor `sent_at` on the event) → `custody.documents.received` within +10 BD (custodian SLA UNVERIFIED; decision 5) — requestCustodyDocuments op=received ingests the custodian's return and emits `custody.documents.received`. Breach: chase; lost-document path (rule 2)." });
  // ---- Fannie Mae execution path
  o("FNMA_A2104_SEND_FOR_EXECUTION_2BD", { satisfied: "`lien_release.sent_for_execution{path=fnma}`", why: "§16.3 timer table: 'e-mailed/mailed to SF CPM Documents with loan number, reason, return label' within +2 BD of prepared_at — routeForExecution emits `lien_release.sent_for_execution{path=fnma}` once the package (loan number, reason, executable document, cover letter, return label) leaves (A2-1-04; F-1-10; F-4-02). Breach sev-2." });
  o("SM_FNMA_EXECUTION_RETURN_15BD", { satisfied: "`fnma.execution.returned`", why: "§16.3 timer table: 'executed document returned' within +15 BD of sending to SF CPM (turnaround UNVERIFIED; decision 5) — routeForExecution op=fnma_returned ingests the returned executed document and emits `fnma.execution.returned` (and `lien_release.executed`). Breach: chase SF CPM; `officer`." });
  o("SM_LPOA_RECORDED_GATE", { satisfied: "`lien_release.executed{signatory_path=lpoa_attorney_in_fact}`", why: "§16.3 timer table: not-before gate 'execution under LPOA' — routeForExecution emits `lien_release.execution_requested{path=lpoa}` and asserts the registered evaluator `16.3.lpoaRecordedForState` over the `lpoas` rows for the state (`lpoas.status=recorded`, scope covering release/satisfaction; ops-16-3.ts lpoaGate); closed → block and fall back to `fnma_execution` (T5: SF CPM within 2 BD). The gate closes on the LPOA execution event." });
  // ---- recording and borrower notice
  o("SM_ERECORD_REJECT_FIX_2BD", { trigger: "`lien_release.rejected`", anchorField: "rejected_on", satisfied: "`lien_release.submitted{resubmission=true}`", why: "§16.3 timer table: `erecord.rejected` (the vendor's reject reason ingested by handleRecorderReject, which emits `lien_release.rejected{rejected_on, reject_code, fix_by}`) → 'resubmitted' within +2 BD — submitRecording emits `lien_release.submitted{resubmission=true}` for attempt > 1 of the corrected package (rule 5); the statutory deadline is unchanged (16.3-T7). Breach sev-2." });
  o("SM_RECORDING_CONFIRM_30", { why: "§16.3 timer table: `lien_release.submitted` (anchor `submitted_at` on the event) → `lien_release.recorded` within +30 calendar days (T8: 10/26 → 11/25) — submitRecording op=recorded ingests the recorder's acceptance (eRecord webhook or paper return) with the recorded image and emits `lien_release.recorded`. Breach: chase recorder/vendor; sev-2." });
  o("SM_BORROWER_RELEASE_NOTICE_5BD", { satisfied: "`notice.sent{template=NTC_LIEN_RELEASE_RECORDED}`", why: "§16.3 timer table: `lien_release.recorded` (anchor recorded_at) → '`NTC_LIEN_RELEASE_RECORDED` sent with the recorded image' within +5 BD (WE1: recorded Mon 10/26 → due Mon 11/02; sent Tue 10/27) — the Notice Registry's `notice.sent{template=…}` event; 'with the recorded image' is enforced before the send by the template's `image` block rule (recorded_image_attached must be true, src/notices/authored/section16-3.ts) and notifyBorrower's RECORDED_IMAGE_REQUIRED guardrail (Fla. Stat. §701.04(2) makes it mandatory in FL — sev-1 there, sev-3 elsewhere)." });
  // ---- penalty non-pass-through
  o("SM_RELEASE_PENALTY_NONPASS_GATE", { satisfied: "`fee.posted{kind=release_penalty, charge_target=corporate_expense}`", why: "§16.3 timer table: not-before gate on 'any fee/penalty posting' — computePenaltyExposure op=post emits `fee.posting_requested{kind=release_penalty, charge_target}` and asserts the registered evaluator `16.3.penaltyNeverPassedThrough` (facts: penalty_charge_target); only `corporate_expense` posts (Dr release_penalty_expense) and emits `fee.posted`; borrower / loan / Fannie Mae claim targets are refused (F-1-09: 'must not pass on to the borrower or to Fannie Mae any penalty fee')." });
}
