/**
 * §17.4 timer overrides: for every 17.4 registry row whose trigger/satisfied column is prose, or names an event the
 * platform spells differently, a `reg.override(code, { trigger?, satisfied | evaluator, anchorField?, offset?, why })`
 * (see src/domain/foreclosure/timers.ts applyForeclosureSatisfiedOverrides for the pattern). Called from this section's
 * timers.ts after the section-level overrides (this file wins the merge).
 *
 * Event names follow the spec's Events list — `case.handoff.inventoried/packaged/delivered/acked/deficient/resolved`,
 * `lossmit.forwarded_post_transfer`, `attorney.instruction.sent/acked` — which the 17.4 tools (src/app/tools/section17-4.ts)
 * emit: `inventoryOpenCases` → inventoried (with the T−1 handoff facts), `packageCase` op package/deliver/ack/deficient/resolve
 * (and the batch-level packaged/acked roll-ups on the batch the row was armed on), `completePreTransferAction`
 * hold_instruction/counsel_ack/smdu_status/retained_request, `forwardPostTransfer` op receive/forward/ack. Cross-process
 * satisfactions name the emitting process's own event: 16.1 `payoff.statement.sent`, cashiering `payment.applied{source=trial_held_funds}`,
 * 12.x `notice.sent{template}`.
 *
 * Subjects: the engine satisfies an instance only from an event on the same subject (src/kernel/timers/engine.ts sameSubject), and a
 * loan-less event arms on its aggregate. 17.1's `transfer.loan_list.attested` lands on {kind: transfer_batch} with no `transfer_date` in
 * its payload (ops-17-1.ts attestLoanList: version, attested_by, attested_on, loan_count), so the two rows the registry anchors on
 * `transfer_date` from the attestation — SM_LOSSMIT_HANDOFF_FILE_14, SM_LOSSMIT_PRE_T_WORKDOWN_T1 — arm on the batch-level
 * `case.handoff.inventoried{scope=batch}` that `inventoryOpenCases` emits for the attestation (spec Inputs: "`transfer.loan_list.attested`
 * (17.1) → open-case inventory") on {kind: batch, id: batch_id} — the same aggregate 17.3's `transfer.cutover.frozen` (SM_LOSSMIT_HANDOFF_FILE_1)
 * lands on — carrying `transfer_date` and `attested_on`. All three are satisfied by 17.4's batch-level events (`scope=batch`, emitted on that
 * aggregate once the roll-up over `case_handoffs` holds), never by a per-case event on a loan.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_17_4(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // ---- handoff file deliverables (batch subject) ----------------------------------------
  o("SM_LOSSMIT_HANDOFF_FILE_14", { trigger: "`case.handoff.inventoried{scope=batch}`", anchorField: "transfer_date", satisfied: "`case.handoff.acked{scope=batch, stage=preliminary, deliverable_kind∈{D21, D34}}`",
    why: "§17.4 timer table: trigger `transfer.loan_list.attested`, anchor `transfer_date`, −14 calendar days; 'preliminary case inventory + loss-mit file delivered (`deliverable.acked{D21/D34 preliminary}`)'. 17.1's attested event carries no transfer_date (ops-17-1.ts attestLoanList payload) and lands on its own aggregate, so the row arms on the batch-level inventory the attestation triggers (spec Inputs: attested → open-case inventory), `case.handoff.inventoried{scope=batch, batch_id, transfer_date, attested_on}` on {batch}. 17.3's deliverable plan has no preliminary D21/D34 run (ops-17-3.ts: D21/D34 as of T−1), so the transferee's acknowledgment of the preliminary D21 (workout status) / D34 (open-case handoff) is recorded by `packageCase{op=ack, stage=preliminary, deliverable_kind}` (preliminaryHandoffAck: as_of before T, kind ∈ D21/D34) as `case.handoff.acked{scope=batch, stage=preliminary, deliverable_kind}` on the batch the inventory armed." });
  o("SM_LOSSMIT_HANDOFF_FILE_1", { satisfied: "`case.handoff.acked{scope=batch, stage=final, all_cases=true}`",
    why: "§17.4 timer table: 'final case packages acked (`case_handoffs.acked`)' — armed by 17.3's `transfer.cutover.frozen{batch_id, transfer_date}` on {batch, batch_id}; `packageCase{op=ack}` emits the per-case `case.handoff.acked{scope=case}` on the loan and, once every handed-off case of the batch is acked (batchHandoffRollup over `case_handoffs`; retained NoE/RFI/complaint cases excluded), the batch-level `case.handoff.acked{scope=batch, stage=final, all_cases=true}` on that batch aggregate — 'final case packages', plural." });
  o("SM_LOSSMIT_PRE_T_WORKDOWN_T1", { trigger: "`case.handoff.inventoried{scope=batch}`", anchorField: "transfer_date", satisfied: "`case.handoff.packaged{scope=batch, lossmit=true, pre_transfer_workdown=documented}`",
    why: "§17.4 timer table: trigger `transfer.loan_list.attested`, anchor `transfer_date`, −1 servicer BD; 'every 12.x action due in [T, T+10 federal BD] either completed before T or documented in TO-03/04/05 as not sent with the unexpired period'. Armed on the batch-level inventory the attestation triggers (see SM_LOSSMIT_HANDOFF_FILE_14: 17.1's attested payload has no transfer_date), so 'every' is a batch fact: `packageCase{op=package}` derives each case's `pre_transfer_workdown` from `workdownEvidence` (the open 12.x actions on the COB T−1 snapshot and whether their TO-03/04/05 check passed — checks are always recomputed from the snapshot; a caller-supplied `checks` input is refused) and emits the batch-level packaged event once every loss-mit case of the batch is packaged with its work-down documented (batchHandoffRollup)." });
  // ---- 12.x clocks that continue to T (Supermortgage's breach if due before T) ------------
  o("REGX_1024_41B2_ACK_5", { anchorField: "received_date", satisfied: "`notice.sent{template∈{NTC_REGX_41B2_ACK_INCOMPLETE, NTC_REGX_41B2_ACK_COMPLETE}}`",
    why: "§17.4 timer table: trigger '`lossmit.application.received` before T', anchor received_at — 12.1's intake (src/app/tools/section12.ts) spells the receipt date `received_date` on `lossmit.application.received{application_id, status, received_date}`; 'ack sent by Supermortgage (before T)' is the §1024.41(b)(2)(i)(B) notice pair of 12.1; if unsent at T, TO-03 records 'not sent; period unexpired' and the transferee's (k)(2)(i) 10-day clock is disclosed (exported, not satisfied). 'Before T' needs no trigger condition: after T the loan is transferred_out and no 12.1 intake runs on it (business rule: Supermortgage never evaluates, acknowledges or decides anything on a transferred loan — post-T submissions are `lossmit.document.received` receipts, below)." });
  o("REGX_1024_41H_APPEAL_DETERMINATION_30", { anchorField: "appeal_received_at", satisfied: "`notice.sent{template∈{NTC_REGX_41H4_APPEAL_GRANTED, NTC_REGX_41H4_APPEAL_DENIED}}`",
    why: "§17.4 timer table: trigger '`lossmit.appeal.received` before T', anchor 'appeal date' — the platform's `lossmit.appeal.received` (src/domain/transfers/inbound.ts appealReceived) carries it as `appeal_received_at`; 'appeal determination sent before T, else handed off ((k)(4))' is the §1024.41(h)(4) determination pair of 12.3; the handed-off case exports REGX_1024_41K4_APPEAL_DETERMINATION_30 in the deadline table instead." });
  o("FNMA_F1_27_TRIAL_PAYMENT_EOM", { trigger: "`case.handoff.inventoried{trial_payment_due_before_transfer=true}`", anchorField: "trial_due_date", offset: "last day of that month", satisfied: "`payment.applied{source=trial_held_funds}`",
    why: "§17.4 timer table: trigger 'trial payment due before T' (the inventory flags the unpaid trial installment due before T), anchor 'last day of due month'; 'payment received (incl. via 17.2 forwarding with receipt date)' — cashiering applies a trial payment as `payment.applied{source=trial_held_funds, credited_as_of}` (src/domain/cashiering/ops.ts emitContractualApplication; 12.8 FNMA_F122 keys on the same event), the credited_as_of carrying the Supermortgage receipt date for a forwarded misdirected payment (F-1-27)." });
  // ---- post-transfer forwarding ---------------------------------------------------------
  o("SM_LOSSMIT_POST_T_FORWARD_1", { trigger: "`lossmit.document.received{loan_status=transferred_out}`", anchorField: "received_at", satisfied: "`lossmit.forwarded_post_transfer{transferee_ack=true}`",
    why: "§17.4 timer table: trigger '`lossmit.document.received` / `lossmit.appeal.received` / `lossmit.offer.accepted/rejected` on a transferred loan' (spec Inputs: `lossmit.document.received{loan.status='transferred_out'}`) — `forwardPostTransfer{op=receive}` records every post-transfer submission addressed to Supermortgage (kind ∈ lossmit_document/appeal/acceptance/rejection/…) as one `lossmit.document.received{kind, loan_status=transferred_out, received_at}` receipt, never as a 12.x intake event that would start Supermortgage's own clocks on a transferred loan; anchor received_at; satisfied by '`post_transfer_forwardings.forwarded_at` with the transferee's ack' — `{op=forward}` emits `lossmit.forwarded_post_transfer{transferee_ack}` and `{op=ack}` re-emits it with transferee_ack=true when the transferee's acknowledgment arrives (comments 41(k)(1)(i)-1, (k)(4)-1, (k)(5)-1)." });
  o("SM_LOSSMIT_HOLD_INSTRUCTIONS_T1", { trigger: "`case.handoff.inventoried{hold_instruction_required=true}`", satisfied: "`attorney.instruction.acked`",
    why: "§17.4 timer table: trigger '`case_handoffs.inventoried{fc_active or gates open}`' — `inventoryFlags` sets hold_instruction_required = fc_active ∨ gates_open (open foreclosure hold, pending complete application or appeal, delinquency inside the 120-day period), so a loss-mit case with an open gate and no foreclosure case arms it too; satisfied by '`attorney.instruction.acked` (hold/proceed/file transfer)' — `completePreTransferAction{action=counsel_ack}` records the firm's acknowledgment — refused unless the actor holds the `attorney` role and names the firm (COUNSEL_ACK_BY_FIRM; spec: 'counsel instructions are sent by the agent and acknowledged by the firm'; Integrations: attorney-network acknowledgments, 2 BD per 13.6) — so the agent cannot satisfy its own hold-instruction deadline." });
  // ---- 16.1 / 4.x clocks that continue: armed from the inventory of listed loans' open cases ----
  o("SM_PAYOFF_REQUEST_OPEN_7BD", { trigger: "`case.handoff.inventoried{case_kind=payoff, opened_before_transfer=true}`", anchorField: "received_at", satisfied: "`payoff.statement.sent`",
    why: "§17.4 timer table: trigger 'payoff request received before T', anchor received_at — spec Inputs: the attestation → 'open-case inventory across `cases` (… payoff, noe, rfi, complaint …) for listed loans'; `inventoryOpenCases` emits `case.handoff.inventoried{case_kind=payoff, opened_before_transfer, received_at}` for the open payoff request of a listed loan (16.1's own `payoff.request.received` starts 16.1's REGZ row; this row is the transferor's continuation of it for the listed loan). Satisfied by 'statement sent before T' — 16.1 `sendNotice`'s `payoff.statement.sent` (the event that satisfies 7.6 REGZ_1026_36C3_PAYOFF_STMT_7BD); the forwarded branch is `completePreTransferAction{action=payoff_request}`, which emits `payoff.request.forwarded{receipt_date, requester_told_on}`, exports the 7-BD clock to the transferee in the deadline table and closes Supermortgage's instance with reason forwarded_to_transferee (not transfer_out, so the transferor-continues gate allows it)." });
  o("SM_NOE_RFI_OPEN_RETAINED", { trigger: "`case.handoff.inventoried{case_kind∈{noe, rfi, complaint}, opened_before_transfer=true}`", evaluator: "17.4.retainedCaseOwnership", satisfied: "`case.response.sent{owner=supermortgage, copy_to_transferee=true}`",
    why: "§17.4 timer table: trigger '`case.noe/rfi/complaint.opened` before T' — state machine 'Special: `retained` for NoE/RFI/complaint cases received before T'; `inventoryOpenCases` emits `case.handoff.inventoried{case_kind∈{noe, rfi, complaint}, opened_before_transfer=true, case_owner=supermortgage}` for them (3.x's generic `case.opened` carries neither the kind nor the before-T fact). Gate = the section evaluator `17.4.retainedCaseOwnership` over the emitted `case_owner` fact ('Supermortgage remains owner; 4.1/4.2 clocks unchanged'); closed by 'responses sent by Supermortgage; copy to transferee' — `completePreTransferAction{action=retained_request}` emits `case.response.sent{owner=supermortgage, copy_to_transferee=true}` with the transferee's copy." });
  // ---- other case types handed off with the same engine --------------------------------
  o("SM_SMDU_CASE_HANDOFF_T0", { trigger: "`case.handoff.inventoried{smdu_case_id present}`", anchorField: "transfer_date", offset: "0", satisfied: "`smdu.case.status_reported{handoff_current=true}`",
    why: "§17.4 timer table: deadline — trigger '`case_handoffs.inventoried{smdu_case_id present}`' (spec Events: `case.handoff.inventoried`, emitted by `inventoryOpenCases` with the SMDU case id and the transfer_date), anchor `transfer_date`, offset 0, breach sev 1 → `fnma_portal_operator`; satisfied by 'SMDU case status current through T-1 (trial payments reported) and, for servicer-number changes, the Fannie Mae request package filed (`human_portal_task`) [UNVERIFIED mechanics]' — `completePreTransferAction{action=smdu_status}` reports status through T−1 only (NO_SMDU_REPORTING_AFTER_T) and emits `smdu.case.status_reported{status_reported_through, handoff_current}` with handoff_current=true only when `smduHandoff` finds the status current through T−1 and the request package filed where a servicer-number change requires it (else the `human_portal_task` for the fnma_portal_operator)." });
  o("SM_CASE_HANDOFF_ACK_2BD", { trigger: "`case.handoff.delivered`", satisfied: "`case.handoff.acked`",
    why: "§17.4 timer table: '`case_handoffs.delivered` → +2 business_days_servicer (contract) → `case_handoffs.acked`' — `packageCase{op=deliver}` emits `case.handoff.delivered{delivered_at}` and `{op=ack}` emits `case.handoff.acked` (spec Events list)." });
  o("SM_CASE_HANDOFF_DEFICIENCY_5BD", { trigger: "`case.handoff.deficient`", satisfied: "`case.handoff.resolved`",
    why: "§17.4 timer table: '`case_handoffs.deficient` → +5 business_days_servicer → `case_handoffs.resolved`' — `packageCase` emits `case.handoff.deficient{deficiencies, raised_at}` when a TO-* check fails without a documented deficiency (or op=deficient on the transferee's exception) and `{op=resolve}` emits `case.handoff.resolved` when Supermortgage cures within 5 BD." });
  o("SM_BK_HANDOFF_T1", { trigger: "`case.handoff.inventoried{bk_active=true}`", satisfied: "`case.handoff.packaged{case_type=bankruptcy, trustee_notice_sent=true, debtor_counsel_notice_sent=true, counsel_instructed=true}`",
    why: "§17.4 timer table: trigger '`case_handoffs.inventoried{bk_active}`'; 'trustee/debtor-counsel notices sent (17.3) and counsel instructed on pending 3002.1/POC/MFR items with due dates' (open question 3 default: 'trustee and debtor-counsel letters before T from 14.x templates') — `packageCase` derives trustee_notice_sent / debtor_counsel_notice_sent / counsel_instructed from `bankruptcyHandoff` over the snapshot's dated evidence (each on or before T−1 BD), never from input booleans." });
  o("SM_FC_SALE_WINDOW_HANDOFF", { trigger: "`case.handoff.inventoried{sale_within_45_days=true}`", satisfied: "`case.handoff.delivered{case_type=foreclosure, sale_within_45_days=true}`",
    why: "§17.4 timer table: trigger '`case_handoffs.inventoried{fc sale date ≤ T+45}`' (`inventoryFlags.sale_within_45_days`); 'bidding instructions/hold status and (g) analysis delivered to transferee and counsel' — the foreclosure package (TO-11 gates, hold instruction, bid instructions) delivered by `packageCase{op=deliver}` for a sale ≤ T+45." });
  o("SM_CLAIM_HANDOFF_T1", { trigger: "`case.handoff.inventoried{claim_open=true}`", satisfied: "`case.handoff.delivered{case_type∈{insurance_claim, mi_claim}}`",
    why: "§17.4 timer table: trigger '`case_handoffs.inventoried{insurance_claim or mi_claim open}`'; 'claim file, loss-draft balance, inspection schedule and insurer/MI contacts delivered' — the claim package delivery by `packageCase{op=deliver}` (9.x/10.x/15.3)." });
  o("SM_SII_PENDING_HANDOFF_T1", { trigger: "`case.handoff.inventoried{sii_pending=true}`", satisfied: "`case.handoff.delivered{case_type=sii}`",
    why: "§17.4 timer table: trigger '`case_handoffs.inventoried{sii pending}`'; 'request date, documents received and the §1024.36(i) response status delivered' — the SII package delivery; the transferee's confirmation clock continues from the original request." });
  o("SM_FPI_CYCLE_HANDOFF_T1", { trigger: "`case.handoff.inventoried{fpi_cycle_open=true}`", satisfied: "`case.handoff.delivered{case_type=fpi}`",
    why: "§17.4 timer table: trigger '`case_handoffs.inventoried{fpi notice cycle open}`'; '§1024.37 notice dates, proof of mailing and placement status delivered (9.x)' — the FPI cycle package delivery." });
  // REGX_1024_41_TRANSFEROR_CONTINUES_GATE keeps the section-level `17.4.noTransferOutCancellationBeforeTransferDate` gate (src/app/evaluators.ts); the tool-side
  // enforcement is `completePreTransferAction{action=cancel_timer}` (NO_TRANSFER_OUT_CANCEL), which resolves the loan's armed instance by id or code and refuses the
  // cancellation with reason transfer_out before T. REGX_1024_41G_DUAL_TRACK_GATE (13.2), REGX_1024_41C1_EVAL_30 (13.2), REGX_1024_41K2_NO_FIRST_FILING_GATE and
  // FNMA_LL_2026_01_FORBEARANCE_CUMULATIVE_12M (1.7) are other processes' rows that 17.4 exports in TO-11/TO-08 (deadlineTable); their triggers stay their owners'.
}
