// 31.1 Licensing, approvals, and the partner boundary
// spec/sections/31-cross-cutting-licensing-and-approvals-ai-governance-and-fair/31-1-licensing-approvals-and-the-partner-boundary.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("31.1-T1: Given the AZ fixture on Mon Oct 5, 2026 with partner `AZ_MORTGAGE_BANKER` approved, MLO `AZ_MLO` approved and sponsored, SM `AZ_MORTGAGE_BROKER` approved and two SM underwriters holding `AZ_MLO`, when `application.started{AZ}` fires, then `SM_LICENSE_STATE_GATE` is open and the `underwriting_reviewer` router accepts only those two SM underwriters or partner employees.", { todo: true });
test("31.1-T2: Given the OH fixture on Mon Oct 19, 2026 with SM's Ohio letter of exemption approved 2026-07-01, then `processor_license_required(OH) = exemption_letter` is satisfied, SM employees without MLO licenses may clear conditions, and each clearance records the supervising MLO of record.", { todo: true });
test("31.1-T3: Given a Georgia lead on Tue Oct 6, 2026 with `license_requirements(GA, processing_underwriting_entity).verification_status = unverified`, then the gate blocks, no quote or application is created, `licensing.gate.blocked{GA, matrix_unverified}` is emitted and a sev-1 `officer` escalation exists.", { todo: true });
test("31.1-T4: Given MLO Chen with no CE logged by Thu Dec 31, 2026, then on Fri Jan 1, 2027 her license is `terminated_expired`, `assignable = false`, her 14 in-flight applications are reassigned and logged, and disclosures already delivered are unchanged; given she reinstates Mon Feb 15, 2027, she is assignable again.", { todo: true });
test("31.1-T5: Given MLO Ramirez completes 8 CE hours (3/2/2) Wed Dec 16, 2026 and renewal is requested Dec 17, then `NMLS_RENEWAL_1101_1231` is satisfied and `expires_at` becomes 2027-12-31 on approval.", { todo: true });
test("31.1-T6: Given HFS $150,000,000.00, IRLC pipeline $200,000,000.00, fallout 30 %, prior-year originations $1,400,000,000.00 for Q4 2026, then `origination_liquidity_required_cents = 1_450_000_00` and the inputs are due to 18.3 by Fri Jan 8, 2027; given prior-year originations $900,000,000.00, the component is 0.", { todo: true });
test("31.1-T7: Given `fnma_approvals{partner, emortgage_special_approval}` granted Fri Oct 23, 2026, then the Nov 6 refinance closing may be scheduled `ron` with an eNote; given the approval arrives Nov 9, the Nov 6 closing is scheduled `hybrid` and `closing.enote_default` is overridden with reason `emortgage_gate_closed`.", { todo: true });
test("31.1-T8: Given `tsp_certification{du}` not yet granted on Mon Oct 5, 2026, when the `fnma-du` adapter is invoked in production under partner scope, then the call is refused with `tsp_gate_closed` and a `fnma_portal_operator` task with the prepared DU file is created.", { todo: true });
test("31.1-T9: Given a request to set `origination.warehouse_legal_form = purchase_at_settlement` without an `officer` + `attorney` decision record, then the change is rejected; with the record, the change is applied and 26.3/27.1 receive `config.changed` (table-funding consequences flagged).", { todo: true });
test("31.1-T10: Given the agent attempts `licenses.upsert{status=approved}` with no evidence document or NMLS record, then the write is refused.", { todo: true });
test("31.1-T11: Given a state page change detected for Ohio on 2027-03-01, then the OH rows degrade to `partially_verified`, a counsel task opens, and the state stays open (no processor-rule change) until counsel decides.", { todo: true });
test("31.1-T12: Given SM's employee is proposed as `mlo_of_record` for an AZ application, then the roster refuses (`employer = sm` with no SM-sponsored AZ MLO license and `ai_intake_position = assisted_required`).", { todo: true });
test("31.1-T13: Given `license.status.changed{to=suspended}` for the partner's Texas license on Tue Nov 10, 2026, then 18.4's `org.change.recorded{material}` is emitted and readiness for TX closes immediately (in-flight TX files escalate to `officer`).", { todo: true });
