// 31.2 AI governance, model risk, and fair-lending controls for AI underwriting, pricing, and adverse action
// spec/sections/31-cross-cutting-licensing-and-approvals-ai-governance-and-fair/31-2-ai-governance-model-risk-and-fair-lending-controls-for-ai-un.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("31.2-T1: Given `underwriter` v3.1 (prompt change, `substantial=true`) registered Mon Nov 9, 2026 with no approved `pre_deployment`/`material_modification` assessment, when deployment is requested, then `SM_O122_ORIGINATION_AI_DEPLOY_GATE` blocks and `ai_system.deploy.blocked` is emitted; given assessment approved Nov 12, eval pass Nov 13, bias tests pass Nov 13, partner notified Nov 13 and Colorado card delivered Nov 16, then deployment on Tue Nov 17, 2026 succeeds.", { todo: true });
test("31.2-T2: Given the October 2026 underwriting population (153/180 vs 558/620), when the monthly run executes on Nov 15, 2026, then the finding shows AIR 0.944, z \u22121.878, p \u2248 0.060, flag `screen`; given the pooled Aug\u2013Oct population (470/540 vs 1,680/1,860), then z \u22122.200, p \u2248 0.028, flag `significant`, and with adjusted OR 0.91 and a 3.3-pp gap the flag is not `material` and no review clock opens.", { todo: true });
test("31.2-T3: Given the October 2026 counteroffer population (31/220 vs 52/610) with adjusted OR 1.48 (CI 1.05\u20132.09), then the finding is `material`, a `fair_lending_reviews` row opens Mon Nov 16, 2026 with `SM_O122_FAIR_LENDING_REVIEW_30D` due Wed Dec 16, 2026, and the review cannot close without a corrective action or a justification memo approved by an `officer`.", { todo: true });
test("31.2-T4: Given 25 sampled October adverse actions with 24 matching replays, then `RA_REASON_ACCURACY` = 0.96, a corrective action is required, the mismatched borrower receives a corrected statement of reasons within 5 business days, and the November sample is 100 %.", { todo: true });
test("31.2-T5: Given the Q3 2026 pricing-exception counts (22/140 vs 41/190), then AIR 0.728 \u2192 `screen`, z \u22121.340, p \u2248 0.180 \u2192 not `significant`; the finding is pooled to the 12-month window and every exception carries a reason code.", { todo: true });
test("31.2-T6: Given a Colorado consumer's application on Tue Jan 5, 2027 and no acknowledged developer card for `underwriter` v3.1, then the application is routed to the human path and `CO_SB26_189_1702_DEVELOPER_DOCS_GATE` reports blocked; given cards acknowledged Dec 15, 2026, the gate is open and the 21.6 artifacts apply.", { todo: true });
test("31.2-T7: Given an `agent_runs.inputs_manifest` containing `language_preference` for a pricing decision, then the leakage test fails, the run is quarantined, `pricing` is `restricted` for `pricing_quote` until re-tested, and a sev-1 review opens.", { todo: true });
test("31.2-T8: Given the model provider ships a new model version on Wed Dec 2, 2026 without notice, then the golden-set eval detects drift, high-risk decision kinds are `restricted` within the `SM_O122_DRIFT_ALERT_REVIEW_2BD` window (due Fri Dec 4), and a 19.3 vendor-SLA breach is logged.", { todo: true });
test("31.2-T9: Given `jurisdiction_rules.ai_governance.ca_admt.applicability_position = applies` and no live California pre-use notice on Jan 1, 2027, then California applications are routed to the human path until `CA_CPPA_7200_ADMT_READINESS_20270101` is satisfied.", { todo: true });
test("31.2-T10: Given a Fannie Mae LL-2026-04 disclosure request received Mon Oct 5, 2026, then the response package (types, purposes, manner, safeguards, inventory export) is compiled from the Q3 pack and an `officer` task exists with the 19.3 due date Mon Oct 12, 2026.", { todo: true });
test("31.2-T11: Given a reviewer approving 100 % of 40 denial recommendations with median review time 45 seconds in a month, then `UW_REVIEWER_OVERRIDE_RATE`/time metrics flag the reviewer, `ca_substantially_replaces_human` is set true for the affected system until retraining is evidenced, and the partner is notified in the pack.", { todo: true });
test("31.2-T12: Given the annual policy review not completed by the anniversary of the last review, then 19.3's `FNMA_LL2026_04_POLICY_REVIEW_365` breaches sev 2 and the next pack carries the exception.", { todo: true });
test("31.2-T13: Given AI off, then the human path produces `agent_decisions` rows with `human_involvement_level = decided_by_human` and the monthly monitor runs on them unchanged.", { todo: true });
