/**
 * §31.2 timer overrides (process-owned; applied after every section's so they win the merge — see
 * src/domain/bankruptcy/timers-14-1.ts for the pattern). One `reg.override(code, { trigger?, satisfied | evaluator,
 * anchorField?, offset?, why })` per 31.2 registry row whose trigger/satisfied column names an event the platform
 * spells differently or a condition the column grammar drops; `why` quotes the spec. A code the servicing spec
 * (sections 1–19) owns is never overridden here — reference it (`FNMA_LL2026_04_POLICY_REVIEW_365`,
 * `FNMA_LL2026_04_DISCLOSURE_PROMPT_5BD`, `SM_AI_SYSTEM_EVAL_BEFORE_DEPLOY`, `SM_AI_BIAS_TEST_*`); 21.6 owns
 * `CO_SB26_189_1703_RECORDS_3Y`, `_1704_ADVERSE_EXPLANATION_30`, `_1705_HUMAN_REVIEW_30`. Wired by src/domain/timer-overrides.ts.
 *
 * Emitters live in src/app/tools/section31-2.ts (the `qc-audit` / `compliance-sentinel` tools over the pure rules in
 * ./ops-31-2.ts): `ai_system.registered` / `ai_system.changed{domain=origination, substantial, co_covered, change_date}`
 * (inventory.upsert — the shared 19.3 inventory events, carried with origination context), `ai_system.assessed{kind,
 * approved, completed_at}` (assess.draft), `ai_system.deploy.approved` / `ai_system.deploy.blocked` and
 * `ai_governance.path.routed{gate, path}` (gate.evaluate), `ai_system.partner_notified` and `co_admt.material_update.notified`
 * (cards.render / inventory.upsert), `co_admt.developer_docs.delivered{acknowledged}` (cards.render),
 * `jurisdiction_rules.ai_governance.updated{ca_admt_applicability_position, ca_admt_applies_from}` and
 * `ca_admt.readiness.confirmed` / `ca_cppa.attestation.filed` (inventory.upsert), `fair_lending.run.completed{scope, period,
 * all_scopes, kind, controls}`, `fair_lending.finding.flagged{flag, flagged_at}`, `fair_lending.review.closed`,
 * `fair_lending.complaint.received{opened_at}` / `fair_lending.complaint.triaged` (monitor.run), `reason_accuracy.sample.completed
 * {accuracy}` (reasons.replay), `ai.monitor.drift_detected{metric, detected_at}` (eval.run) / `ai.monitor.drift_disposed
 * {disposition}` (drift.watch), `ai_governance.pack.issued{period}` (pack.compile). The schedule ticks are the platform's:
 * `period.month_end{month_end}` / `period.quarter_end{quarter_end}` (18.1 / 18.7 / 5.x emit them).
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_31_2(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // ---- deploy pipeline (T1): a condition-shaped not_before gate over the ai_systems row; the approval record closes it
  o("SM_O122_ORIGINATION_AI_DEPLOY_GATE", { trigger: "`ai_system.changed{domain=origination}`", evaluator: "31.2.originationDeployGate", satisfied: "`ai_system.deploy.approved`",
    why: "§31.2 timer table: not_before_gate on '`ai_system.changed` / `ai_system.registered` (origination)' — inventory.upsert appends the shared 19.3 `ai_system.changed{domain=origination}` for every origination version (a new system's initial version included; `origination:true` on the payload supplies the origination context the engine requires for a §20–31 timer); offset '`ai_impact_assessments{pre_deployment or material_modification}.approved` ∧ 19.3 `SM_AI_SYSTEM_EVAL_BEFORE_DEPLOY` open ∧ 19.4 `SM_AI_BIAS_TEST_PRE_DEPLOY` open (high-risk) ∧ `partner_notified_at` set ∧ (CO covered: `co_docs_delivered_to_deployer_at` set)' → evaluators-31-2 originationDeployGate; satisfied 'gate open → `deployed`' = `ai_system.deploy.approved` from gate.evaluate{op=deploy}; breach 'deploy blocked; `ai_system.deploy.blocked`' (T1: v3.1 blocked Nov 9, deployed Tue Nov 17, 2026)." });
  // ---- annual reassessment: recurring from the assessment's completed_at; a new approved `annual` assessment satisfies and re-arms
  o("SM_O122_AI_ASSESSMENT_ANNUAL_365", { trigger: "`ai_system.assessed{approved=true, kind∈{pre_deployment, material_modification, annual}}`", anchorField: "completed_at", offset: "+365 calendar_days", satisfied: "`ai_system.assessed{approved=true, kind=annual}`",
    why: "§31.2 timer table: trigger '`ai_impact_assessments.completed_at`' (a column, finding E43) → the event assess.draft{op=approve} appends when an officer approves an assessment, `ai_system.assessed{kind, approved=true, completed_at}`; anchor completed_at; '+365 `calendar_days`'; satisfied by 'new `annual` assessment approved'; breach 'sev 2 → `officer`; system flagged in the pack' (LL-2026-04 'risk management activities'; rule 2 next_due_at = +365 days)." });
  // ---- version-change notice to the partner (open question 5: 10 creditor business days before deployment)
  o("SM_O122_MODEL_CHANGE_NOTICE_TO_PARTNER_10BD", { trigger: "`ai_system.changed{substantial=true, domain=origination}`", anchorField: "change_date", offset: "+10 business_days_creditor", satisfied: "`ai_system.partner_notified`",
    why: "§31.2 timer table: trigger `ai_system.changed{substantial=true}` (origination systems — the 19.4 servicing change event shares the name and the `substantial`/`change_date` fields), anchor 'change decision date' = payload `change_date`, '+10 `business_days_creditor` [contract default] (before deployment)', satisfied by `ai_system.partner_notified` (inventory.upsert{op=partner_notified} / cards.render); breach 'deploy gate stays closed' — originationDeployGate requires partner_notified_at (T1: notified Nov 13, 2026)." });
  // ---- Colorado developer duties (T6): per-application gate for a Colorado consumer on/after 2027-01-01; the routing record (ADMT or human path) answers it
  o("CO_SB26_189_1702_DEVELOPER_DOCS_GATE", { trigger: "`application.received{property_state=CO}`", evaluator: "31.2.coDeveloperDocsGate", satisfied: "`ai_governance.path.routed{gate=CO_SB26_189_1702_DEVELOPER_DOCS_GATE}`",
    why: "§31.2 timer table: not_before_gate on '`ai_system{materially_influences_consequential_decision, co_admt_role ∈ developer, both}` used for a Colorado consumer on/after 2027-01-01' — the use begins with 21.1's `application.received{property_state=CO}` (the event 21.6's Colorado clocks also key on); offset 'technical documentation delivered to the deployer (partner) and acknowledged' → evaluators-31-2 coDeveloperDocsGate over the ai_systems row (`co_docs_delivered_to_deployer_at`, `co_docs_acknowledged_at`; cards.render appends `co_admt.developer_docs.delivered{acknowledged}`); satisfied 'gate open' — gate.evaluate{op=co_docs} records `ai_governance.path.routed{gate, path∈{admt, human_path}}` for the application; breach 'Colorado applications routed to the human path (`underwriting_reviewer` decides without the ADMT's material influence) until delivered; sev 1' (T6: Jan 5, 2027 → human path without an acknowledged card; cards acknowledged Dec 15, 2026 → open)." });
  o("CO_SB26_189_1702_MATERIAL_UPDATE_NOTICE", { trigger: "`ai_system.changed{substantial=true, co_covered=true}`", anchorField: "change_date", offset: "+10 business_days_creditor", satisfied: "`co_admt.material_update.notified`",
    why: "§31.2 timer table: trigger '`ai_system.changed{substantial=true}` for a CO-covered system' (payload `co_covered` = materially_influences_consequential_decision ∧ co_admt_role ∈ developer/both), anchor 'change decision date' = `change_date`, offset 'before deployment (policy: same 10 `business_days_creditor`)', satisfied by `co_admt.material_update.notified` (cards.render{op=material_update}: 'Every substantial=true change ships an updated card before deployment', rule 11; 6-1-1702 'notify deployers of material updates'); breach 'deploy gate closed for CO consumers'." });
  // ---- California ADMT (T9): one-time global gate from the jurisdiction position; the readiness confirmation closes it; the two CPPA deadlines anchor on the applies-from date
  o("CA_CPPA_7200_ADMT_READINESS_20270101", { trigger: "`jurisdiction_rules.ai_governance.updated{ca_admt_applicability_position=applies}`", anchorField: "ca_admt_applies_from", evaluator: "31.2.caAdmtReadinessGate", satisfied: "`ca_admt.readiness.confirmed{preuse_notice_live=true, optout_route_live=true, access_procedure_live=true}`",
    why: "§31.2 timer table: not_before_gate (one-time) on '`jurisdiction_rules.ai_governance.ca_admt.applicability_position = applies`' (a config flag, finding E43) → inventory.upsert{op=jurisdiction} appends `jurisdiction_rules.ai_governance.updated{ca_admt_applicability_position, ca_admt_applies_from}`; anchor 2027-01-01 = `ca_admt_applies_from`; offset 'CA pre-use notice variant live, opt-out/human-appeal route live, access-request procedure live before 2027-01-01' → evaluators-31-2 caAdmtReadinessGate; satisfied when inventory.upsert{op=ca_readiness} confirms all three live; breach 'CA applications routed to the human path until live; sev 1' (gate.evaluate{op=ca_readiness} routes the application)." });
  o("CA_CPPA_7150_RISK_ASSESSMENT_20271231", { trigger: "`jurisdiction_rules.ai_governance.updated{ca_admt_applicability_position=applies}`", anchorField: "ca_admt_applies_from", offset: "Dec 31", satisfied: "`ai_system.assessed{kind=ca_cppa_risk_assessment, approved=true}`",
    why: "§31.2 timer table: deadline (if applicable) on the same position; 'assessments for processing begun before 2026-01-01 complete by 2027-12-31 (§7155(b) per the CPPA FSOR)' — anchored on `ca_admt_applies_from` (2027-01-01) the next Dec 31 is 2027-12-31; satisfied by '`ai_impact_assessments{ca_cppa_risk_assessment}`' = assess.draft{op=approve, kind=ca_cppa_risk_assessment}; breach sev 2." });
  o("CA_CPPA_7157_ATTESTATION_20280401", { trigger: "`jurisdiction_rules.ai_governance.updated{ca_admt_applicability_position=applies}`", anchorField: "ca_admt_applies_from", offset: "Apr 1 following year", satisfied: "`ca_cppa.attestation.filed`",
    why: "§31.2 timer table: deadline (if applicable) on the same position; '2028-04-01 first submission/attestation (CPPA announcement 9/23/2025; §7157(a))' — anchored on `ca_admt_applies_from` (2027-01-01), Apr 1 of the following year = 2028-04-01; satisfied by 'filing evidence' = inventory.upsert{op=ca_attestation} appending `ca_cppa.attestation.filed{document_id}`; breach 'sev 1 → `officer`'." });
  // ---- monitoring cadence: the platform's month-end / quarter-end ticks arm the recurring rows; the run events close them
  o("SM_O122_FAIR_LENDING_MONITOR_MONTHLY", { trigger: "`period.month_end`", anchorField: "month_end", offset: "15th of the following month", satisfied: "`fair_lending.run.completed{all_scopes=true}`",
    why: "§31.2 timer table: recurring on 'schedule', anchor '15th of month', 'monthly for the prior month (underwriting, pricing, exceptions, steering, valuation, fraud holds, triggers)' — the month-end tick (`period.month_end{month_end}`, 18.1's scheduler) arms the run for that month, due the 15th of the following month; satisfied by '`fair_lending.run.completed` for every scope' — monitor.run sets `all_scopes=true` on the run that completes the last of the seven monthly scopes for the period; breach 'sev 2 → `officer`' (T2: October 2026 run executes Nov 15, 2026)." });
  o("SM_O122_FAIR_LENDING_REGRESSION_QUARTERLY", { trigger: "`period.quarter_end`", anchorField: "quarter_end", offset: "+20 calendar_days", satisfied: "`fair_lending.run.completed{kind=regression, controls=true}`",
    why: "§31.2 timer table: recurring on 'quarter-end', anchor 'quarter-end + 20 `calendar_days`', 'quarterly (with controls; pooled windows)', satisfied by 'run completed' — monitor.run{kind=regression} with the logistic controls (rule 5) appends `fair_lending.run.completed{kind=regression, controls=true}`; breach sev 2." });
  o("SM_O122_FAIR_LENDING_REVIEW_30D", { trigger: "`fair_lending.finding.flagged{flag=material}`", anchorField: "flagged_at", offset: "+30 calendar_days", satisfied: "`fair_lending.review.closed`",
    why: "§31.2 timer table: trigger `fair_lending.finding.flagged{material}` (= `flag=material`), anchor `flagged_at`, '+30 `calendar_days`', satisfied by '`fair_lending.review.closed` (corrective action approved or legitimate justification documented)' — monitor.run{op=close_review} refuses without an officer disposition and one of the two (reviewMayClose); breach 'sev 1 → `officer` (both entities); system to `monitored{remediation}`' (T3: flagged Mon Nov 16, 2026 → due Wed Dec 16, 2026)." });
  o("SM_O122_REASON_ACCURACY_SAMPLE_MONTHLY", { trigger: "`period.month_end`", anchorField: "month_end", offset: "+10 calendar_days", satisfied: "`reason_accuracy.sample.completed{accuracy>=0.98}`",
    why: "§31.2 timer table: recurring on 'month-end', anchor '+10 `calendar_days`', 'monthly; sample ≥ 25 adverse actions or 100 % if fewer; recompute principal reasons from the decision record', satisfied by '`reason_accuracy.sample.completed{accuracy ≥ 0.98}`' (reasons.replay); breach '< 0.98 → corrective action; < 0.95 → `underwriting_reviewer` 100 % re-review of the month's notices; sev 1' (T4: 24/25 = 0.96 → corrective action, November at 100 %)." });
  o("SM_O122_PRICING_EXCEPTION_REVIEW_MONTHLY", { trigger: "`period.month_end`", anchorField: "month_end", offset: "+10 calendar_days", satisfied: "`fair_lending.run.completed{scope=pricing_exceptions}`",
    why: "§31.2 timer table: recurring on 'month-end', anchor '+10 `calendar_days`', 'monthly review of `pricing_exception_reviews` (25.1) by dimension', satisfied by 'review completed' = the `pricing_exceptions` scope of monitor.run (rule 6: reason-code mix, AIR/z by dimension); breach sev 2 (T5: Q3 2026 AIR 0.728 → screen, pooled to 12 months)." });
  // ---- complaints alleging discrimination: 4.x's `case.complaint.opened` carries its flags inside `flags[]` (no `fair_lending_flag` field the grammar can test); qc-audit's intake records the fair-lending complaint with the case's opened_at
  o("SM_O122_COMPLAINT_FL_TRIAGE_5BD", { trigger: "`fair_lending.complaint.received`", anchorField: "opened_at", offset: "+5 business_days_creditor", satisfied: "`fair_lending.complaint.triaged{disposition∈{finding_linked, decision_rereview, no_pattern}}`",
    why: "§31.2 timer table: trigger '`case.complaint.opened{fair_lending_flag=true}` (servicing 4.x's complaint-case event)' — 4.5's payload carries the discrimination flag inside `flags[]` (section04.ts OFFICER_ROUTE), which the pattern grammar cannot test, so monitor.run{op=complaint_intake} records the flagged case as `fair_lending.complaint.received{case_id, opened_at}` with the 4.x case's own opened_at as the anchor; '+5 `business_days_creditor`'; satisfied by 'triage decision recorded (link to a finding or a decision re-review)' = monitor.run{op=complaint_triage} → `fair_lending.complaint.triaged{disposition}`; breach sev 2 (edge case: the file's decision record is re-reviewed by a different reviewer)." });
  o("SM_O122_DRIFT_ALERT_REVIEW_2BD", { trigger: "`ai.monitor.drift_detected{metric}`", anchorField: "detected_at", offset: "+2 business_days_creditor", satisfied: "`ai.monitor.drift_disposed{disposition∈{benign, restrict, roll_back}}`",
    why: "§31.2 timer table: trigger `ai.monitor.drift_detected{metric}` (eval.run: golden-set deltas beyond tolerance), anchor `detected_at`, '+2 `business_days_creditor`', satisfied by 'disposition recorded (benign / restrict / roll back)' = drift.watch → `ai.monitor.drift_disposed{disposition}`; breach 'sev 1; auto-restrict on a second unreviewed alert' (T8: Wed Dec 2 → Fri Dec 4, 2026; high-risk decision kinds restricted meanwhile)." });
  o("SM_O122_GOVERNANCE_PACK_QUARTERLY", { trigger: "`period.quarter_end`", anchorField: "quarter_end", offset: "+30 calendar_days", satisfied: "`ai_governance.pack.issued`",
    why: "§31.2 timer table: recurring on 'quarter-end', anchor '+30 `calendar_days`', 'quarterly (`PACK_AI_GOVERNANCE` to the partner)', satisfied by `ai_governance.pack.issued{period}` (pack.compile); breach sev 2 (rule 12; T10 answers Fannie Mae from the latest pack)." });
}
