/**
 * §31.1 timer overrides (process-owned; applied after every section's so they win the merge — see
 * src/domain/bankruptcy/timers-14-1.ts for the pattern). One `reg.override(code, { trigger?, satisfied | evaluator,
 * anchorField?, offset?, why })` per 31.1 registry row whose trigger/satisfied column names an event the platform
 * spells differently or a condition the column grammar drops; `why` quotes the spec. A code the servicing spec
 * (sections 1–19) owns is never overridden here — reference it. Wired by src/domain/timer-overrides.ts.
 *
 * Emitters live in src/domain/governance/ops-31-1.ts (the `compliance-sentinel` licensing persona); every 31.1 payload
 * carries `source: "origination"` (or an applicationId) so the origination-side rows arm (engine isOriginationContext).
 * The three gates are condition-shaped and evaluator-backed (evaluators-31-1.ts); each closes on the generic
 * `licensing.gate.opened{gate=<code>}` the ops emit after the predicate passes. Referenced, never redefined: 18.4
 * `FNMA_A4102_FORM582_FYE_90` / `_AFS_FYE_90` / `_ORG_CHANGE_5BD` / `FNMA_A4103_*`; 18.3 `FHFA_ELIG_QUARTERLY_TEST`,
 * `FNMA_A4102_FORM1002_*`, `FNMA_A4101_SERVICE_ONE_LOAN_DEC31`; 19.3 `FNMA_A2101_*`, `FNMA_A2107_FORM101_INCEPTION_GATE`,
 * `FNMA_LL2026_04_DISCLOSURE_PROMPT_5BD`; 25.1 `SM_O61_LICENSE_CHECK_REFRESH_30`; 20.3 `SM_MLO_PREAPP_TERMS_REVIEW_1BH`.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_31_1(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // Row 1 / T1, T3: the state-readiness predicate at every command the row names; armed per application from 21.1's `application.started` (the other moments — 20.2 solicitation, 20.3 lead, 21.1 MLO request, issueLE, lock — call assertStateGate, which emits the same opened/blocked events).
  o("SM_LICENSE_STATE_GATE", { trigger: "`application.started`", evaluator: "31.1.stateReadinessGate", satisfied: "`licensing.gate.opened{gate=SM_LICENSE_STATE_GATE}`",
    why: "§31.1 timer table: not_before_gate on '`campaign.approved{states}` and `marketing.touch.queued{state}` (20.2) / `lead.created{state}` (20.3) / `application.started{state}` and `escalation.opened{role=mlo_of_record, state}` (21.1) / the `issueLE{state}` and `lock{state}` commands', offset 'state readiness `open` (rules above) at command time', satisfied by 'gate open', breach 'command refused; `licensing.gate.blocked`; sev 1 → `officer` (partner) for a missing partner license, `officer` (SM) for a missing SM credential; borrower told only that the partner does not lend in that state' — rule 1: open(S) = partner_company_ok ∧ branch_ok ∧ mlo_available ∧ sm_processing_ok ∧ matrix_ok ∧ ai_position_ok (ops-31-1.ts stateReadiness / assertStateGate; T3: GA `matrix_unverified` blocks, no quote, no application)." });
  // Row 2: the nightly Consumer Access/B2B pull; the scheduler's daily tick starts each cycle and the completed sync closes it (recurring re-arm from the sync itself).
  o("SM_O121_NMLS_SYNC_DAILY", { trigger: "`schedule.tick{cadence=daily, job=nmls_sync}`", anchorField: "date", offset: "+1 calendar_days", satisfied: "`nmls.sync.completed`",
    why: "§31.1 timer table: recurring on 'schedule', anchor 'daily 02:00 ET', '1 `calendar_days`', satisfied by '`licenses.last_nmls_sync_at` refreshed for every active row (feeds 25.1 `license_checks`)', breach 'sync stale > 3 days → all affected licenses treated as `not_found` by 25.1; sev 2' — ops-31-1.ts nightlySyncTick emits the tick; syncNmls refreshes every row with an NMLS id and emits `nmls.sync.completed` (nmlsSyncStale: > 3 days fail-closed)." });
  // Row 3 / T5: Nov 1 opens the window per renewable licence; Dec 31 end of day ET is the NMLS deadline; the NMLS approval (`license.renewed`) closes it and re-arms next year's.
  o("NMLS_RENEWAL_1101_1231", { trigger: "`license.renewal.window.opened`", offset: "Dec 31", satisfied: "`license.renewed`",
    why: "§31.1 timer table: deadline (recurring annually) on 'Nov 1 (window open)', anchor 'Dec 31 of the year', '0 `calendar_days` (end of day ET on Dec 31; NMLS deadline)', satisfied by '`license.renewed` for every `licenses` row with NMLS annual renewal', breach 'license → `terminated_expired` Jan 1; state readiness `closed`; assignments reassigned; sev 1 → holder's `officer`; warnings at Nov 1, Dec 1, Dec 15' — NMLS Annual Renewal Overview: 'The annual renewal period in NMLS begins on November 1 and ends on December 31 each year'; ops-31-1.ts openRenewalWindow emits one `license.renewal.window.opened` per row (T5: Ramirez requested Dec 17, approved Jan 4, 2027 → `expires_at` 2027-12-31)." });
  // Row 4 / T4: Jan 1 `license.expired{expired_on}` → to the last day of February; reinstatement closes it.
  o("NMLS_REINSTATEMENT_0101_0228", { anchorField: "expired_on", offset: "last day of next month", satisfied: "`license.reinstated`",
    why: "§31.1 timer table: deadline on '`license.expired` (missed renewal)', anchor 'Jan 1', 'to last day of February (`calendar_days`)', satisfied by `license.reinstated`, breach 're-application required; sev 1' — NMLS: 'reinstatement period from January 1 through the end of February'; ops-31-1.ts expireUnrenewed puts `expired_on` (Jan 1) on the payload so the due date is Feb 28/29 (T4: Chen expires Fri Jan 1, 2027, reinstates Mon Feb 15, 2027)." });
  // Row 5 / T5: each individual licensee's 8-hour CE clock for the renewal year, anchored on the year's Dec 31 (`ce_deadline`); the completion event carries next year's deadline so the recurring re-arm lands on Dec 31 of the following year, not the same one.
  o("SAFE_1008_107_MLO_CE_8H_1231", { trigger: "`license.renewal.window.opened{individual=true}`", anchorField: "ce_deadline", offset: "same day", satisfied: "`license.ce.completed{hours>=8}`",
    why: "§31.1 timer table: deadline (recurring annually) on 'each `mlo_roster` member / SM individual licensee', anchor 'Dec 31', '−0 `calendar_days` (policy target Dec 1)', satisfied by '`license.ce.completed{hours ≥ 8; 3 fed law, 2 ethics, 2 nontraditional}`', breach 'renewal cannot be requested; member `assignable = false` from Jan 1; sev 2' — 12 CFR 1008.107: 'at least 8 hours of education approved by the NMLSR' (3 federal law, 2 ethics, 2 nontraditional); ops-31-1.ts recordCeCompletion validates 3/2/2 and emits `hours` with `ce_deadline` = Dec 31 next year (T5: Ramirez 8 h on Wed Dec 16, 2026)." });
  // Row 6: every approved licence's expiry, warned 90 days ahead (then 60/30 by the breach ladder); the renewal request is the continuation evidence.
  o("SM_LICENSE_EXPIRY_WARN_90", { trigger: "`license.status.changed{to=approved}`", anchorField: "expires_at", offset: "-90 calendar_days", satisfied: "`license.renewal.requested`",
    why: "§31.1 timer table: deadline (warnings) on 'any `licenses.expires_at`/`bond_expires_at`', anchor 'expiry', '−90/−60/−30 `calendar_days`', satisfied by 'renewal/bond continuation evidence', breach 'sev 3 → 2 → 1' — ops-31-1.ts changeLicenseStatus puts `expires_at` on every `license.status.changed{to=approved}` (initial approval, renewal, reinstatement) so each term's warning arms at expiry − 90 days; requestRenewal emits the continuation evidence (NTC_INTERNAL_LICENSE_EXPIRY_WARN carries the warning)." });
  // Row 7 / T7: 26.2's `closing.scheduled{enote=true}` asks whether the partner may close with an eNote; the predicate is evaluator-backed and the opened event closes it; a closed gate falls the closing back to hybrid.
  o("FNMA_A2_1_01_EMORTGAGE_APPROVAL_GATE", { evaluator: "31.1.emortgageApprovalGate", satisfied: "`licensing.gate.opened{gate=FNMA_A2_1_01_EMORTGAGE_APPROVAL_GATE}`",
    why: "§31.1 timer table: not_before_gate on '`closing.scheduled{enote=true}` (26.2)', '`fnma_approvals{partner, emortgage_special_approval} = active` **and** `mers_eregistry_addendum active` for partner and SM **and** `enote_warehouse_agreement active` (SM)', satisfied by 'gate open', breach 'closing falls back to `hybrid`/`wet` (paper note) with `closing.enote_default` overridden; sev 2' — Selling Guide A2-1-01: sellers 'may not sell or service these loan types unless they obtain the applicable special approval'; ops-31-1.ts emortgageGate / decideClosingNoteForm (T7: approval Fri Oct 23, 2026 → Nov 6 RON + eNote; approval Nov 9 → hybrid, `closing.enote_default` overridden `emortgage_gate_closed`)." });
  // Row 8 / T8: every production Fannie Mae call under partner scope names its product; certification + Technology Manager assignment + Form 101 open it; otherwise the adapter refuses and a fnma_portal_operator task carries the prepared file.
  o("FNMA_TSP_PRODUCTION_CERT_GATE", { trigger: "`integration.production_call.requested{product}`", evaluator: "31.1.tspProductionCertGate", satisfied: "`licensing.gate.opened{gate=FNMA_TSP_PRODUCTION_CERT_GATE}`",
    why: "§31.1 timer table: not_before_gate on 'any production Fannie Mae call under partner scope, per `product`', '`tsp_certification{product} = granted` **and** `tm_tsp_product_assignment{product} = active` **and** 19.3 `FNMA_A2107_FORM101_INCEPTION_GATE` open', satisfied by 'gate open', breach 'adapter refuses; `fnma_portal_operator` fallback where a UI exists (00b-orig Part (b)); sev 2' — 00a-fnma §3: TSPs 'must complete integration testing and receive certification in the integration environment before moving TSP product to production'; ops-31-1.ts requestProductionCall emits the request and refuses `tsp_gate_closed` (T8: `fnma-du` on Mon Oct 5, 2026 before the Fri Jan 15, 2027 DU certification)." });
  // Row 9 / T6: quarter-end + 5 Fannie Mae ET business days; the computed inputs close it (Q4 2026: Dec 31 → Fri Jan 8, 2027, Jan 1 excluded).
  o("FNMA_A4_1_01_ORIG_LIQUIDITY_INPUTS_QBD5", { anchorField: "quarter_end", satisfied: "`eligibility.orig_inputs.computed`",
    why: "§31.1 timer table: deadline on `quarter.closed`, anchor 'quarter-end', '+5 `business_days_fannie_et`', satisfied by '`eligibility.orig_inputs.computed` delivered to 18.3 before its `FHFA_ELIG_QUARTERLY_TEST` (BD10)', breach 'sev 2 → `officer`; 18.3 test flagged incomplete' — A4-1-01 (08/05/2026) origination liquidity 0.5 % of HFS + fallout-adjusted IRLC pipeline for non-depositories originating > $1 billion in the most recent four quarters; ops-31-1.ts closeQuarter puts `quarter_end` on the trigger; computeOrigInputs emits the satisfying event (T6: $1,450,000.00 due Fri Jan 8, 2027)." });
  // Row 10: the Jan 1 scheduler tick opens the reconciliation-only clock to Jan 31; the year's re-attestation of `origination_liquidity_applies` closes it.
  o("FNMA_A4_1_01_ANNUAL_ORIGINATION_1B_0131", { trigger: "`schedule.tick{cadence=annual, job=origination_1b_reconciliation}`", anchorField: "date", offset: "Jan 31", satisfied: "`eligibility.origination_1b.reattested`",
    why: "§31.1 timer table: recurring (reconciliation only) on 'Jan 1', anchor 'Jan 31', offset 'annual', satisfied by '`origination_liquidity_applies` re-attested for the year — the operative test is quarterly: A4-1-01 (08/05/2026) applies origination liquidity to non-depositories that \"originate greater than $1 billion … in the most recent four-quarter period\", so the flag is recomputed from the trailing four quarters at every `quarter.closed` inside `FNMA_A4_1_01_ORIG_LIQUIDITY_INPUTS_QBD5`', breach 'sev 3' — ops-31-1.ts annualReconciliationTick / reattestOrigination1B (verification report 31.1 items 1–2)." });
  // Row 11: SM's audited financials received start the partner's annual A3-3-01 review clock; the officer-approved review closes and re-arms it.
  o("FNMA_A3_3_01_TPO_ANNUAL_FINANCIAL_REVIEW_365", { trigger: "`tpo.financials.received`", anchorField: "received_on", offset: "+365 calendar_days", satisfied: "`tpo.review.completed{kind=annual_financial_statements}`",
    why: "§31.1 timer table: recurring on 'SM audited financials received', anchor 'last review', '365 `calendar_days`', satisfied by '`tpo.review.completed{annual_financial_statements}` approved by partner `officer`', breach 'sev 2 (partner program gap)' — A3-3-01: 'Annual review of the third-party originator's financial statements'; ops-31-1.ts receiveTpoFinancials / completeTpoReview (rule 9: SM FYE Dec 31 → AFS by Mar 31, 2027 → partner review by Apr 30, 2027 [policy])." });
  // Row 12: quarter-end + 30 days (policy) for the quarterly performance package; the quarterly review closes it (keyed to the quarter, as the trigger is).
  o("FNMA_A3_3_01_TPO_QUARTERLY_PERFORMANCE_90", { trigger: "`quarter.closed`", anchorField: "quarter_end", offset: "+30 calendar_days", satisfied: "`tpo.review.completed{kind=quarterly_performance}`",
    why: "§31.1 timer table: recurring on 'quarter-end', anchor 'quarter-end', '+30 `calendar_days` **[policy]**', satisfied by '`tpo.review.completed{quarterly_performance}`', breach 'sev 3' — A3-3-01: 'Quarterly review of the performance of loans originated by the third-party originator'; ops-31-1.ts closeQuarter (`quarter.closed{period, quarter_end}`) and completeTpoReview{quarterly_performance} on the same quarter subject (rule 9: Q4 2026 package by Jan 30, 2027)." });
  // Row 13: the SM approval file opens the licensing re-verification cycle; each re-verification review closes and re-arms it.
  o("FNMA_A3_3_01_TPO_LICENSE_REVERIFY_365", { trigger: "`tpo.approval_file.opened`", anchorField: "opened_on", offset: "+365 calendar_days", satisfied: "`tpo.review.completed{kind=licensing_reverification}`",
    why: "§31.1 timer table: recurring on 'SM approval file', anchor 'last reverification', '365 `calendar_days`', satisfied by '`tpo.review.completed{licensing_reverification}` (SM licenses + individual licenses summary)', breach 'sev 2' — A3-3-01: 'A method for verifying, and periodically reverifying, a third-party originator's compliance with applicable laws, licensing, and qualifications' (no period stated — 365 is policy); ops-31-1.ts openTpoApprovalFile / completeTpoReview." });
  // Row 14 / T11: counsel's verification date anchors the annual re-verification of each state's rows; a fresh verification closes and re-arms it.
  o("SM_O121_MATRIX_REVERIFY_365", { trigger: "`jurisdiction.licensing.verified{state}`", anchorField: "verified_at", offset: "+365 calendar_days", satisfied: "`jurisdiction.licensing.verified`",
    why: "§31.1 timer table: recurring on '`license_requirements.verified_at`' (a column, not an event — the platform event is counsel's `jurisdiction.licensing.verified{state, verified_at}`), anchor 'verified_at', '365 `calendar_days`', satisfied by 'new counsel verification (`jurisdiction.licensing.verified`)', breach 'row degrades to `partially_verified`; sev 3 (state stays open unless a change is detected)' — ops-31-1.ts verifyMatrixRow; detectStatePageChange degrades and opens the counsel task (T11)." });
  // Row 15: the memo's issue date anchors the annual review of each state's written AI-intake position; a re-issued memo closes and re-arms it.
  o("SM_O121_AI_POSITION_REVIEW_365", { trigger: "`ai_intake.position.issued{state}`", anchorField: "issued_at", offset: "+365 calendar_days", satisfied: "`ai_intake.position.issued`",
    why: "§31.1 timer table: recurring on '`ai_intake_legal_positions.issued_at`' (a column — the platform event is `ai_intake.position.issued{state, issued_at}`), anchor 'issued_at', '365 `calendar_days`', satisfied by 'memo re-issued', breach 'position degrades to `unresolved` → gate closes for *new* applications in that state only if the position was `autonomous_permitted…`; `assisted_required` never closes' — open question 4; ops-31-1.ts issueAiIntakePosition / effectiveAiPosition." });
}
