/**
 * §31.3 timer overrides (process-owned; applied after every section's so they win the merge — see
 * src/domain/bankruptcy/timers-14-1.ts for the pattern). One `reg.override(code, { trigger?, satisfied | evaluator,
 * anchorField?, offset?, why })` per 31.3 registry row whose trigger/satisfied column names an event the platform
 * spells differently or a condition the column grammar drops; `why` quotes the spec. A code the servicing spec
 * (sections 1–19) owns is never overridden here — reference it. Wired by src/domain/timer-overrides.ts.
 *
 * Every not-before gate whose row says "gate opens" / "disposal blocked" is evaluator-backed (19.1's pattern): the row
 * carries no due instant, the disposal command asserts the gate over the object's facts (ops-31-3.ts
 * `assertOriginationGatesOpen` / `timerGate`) and the engine never breaches it. The registry merge recomputes
 * `anchorField` from the anchor column on every override, so rows with a computed anchor pass it explicitly. The
 * schedule rows' triggers are the origination `schedule.tick{job}` events ops-31-3.ts `originationScheduleTicks`
 * emits with `source=origination` (origination-defined timers arm only on events that carry origination context).
 * The trigger events other origination processes emit are consumed by `records.anchor` (ops-31-3.ts ANCHOR_EVENTS):
 * 21.6's action names, 26.2's `closing.consummated` / `enote.signed`, 22.6's `party.screened`, 28.3's
 * `hmda.lar.accepted{signed_at}`, 28.4's `sar.filed` / `ofac.property.blocked`.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_31_3(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // ---- Reg Z §1026.25 disposal gates (condition-shaped; asserted by the disposal command; never a clock that breaches)
  o("REGZ_1026_25C1I_LE_RETENTION_3Y", { trigger: "`disclosure.le.delivered`", anchorField: "consummation_date", evaluator: "31.3.regZLeGateOpen", why: "§31.3 timer table: `disclosure.le.delivered` (per LE version) → later of `consummation_date`, `disclosure_required_at`, `action_required_at` + 3 years; 'gate opens' / 'disposal blocked' (12 CFR 1026.25(c)(1)(i): 'three years after the later of the date of consummation, the date disclosures are required to be made, or the date the action is required to be taken')." });
  o("REGZ_1026_25C1II_CD_RETENTION_5Y", { anchorField: "consummation_date", evaluator: "31.3.regZCdGateOpen", why: "§31.3 timer table: `closing.consummated` (26.2) → `consummation_date` + 5 years; 'gate opens' / 'disposal blocked' (12 CFR 1026.25(c)(1)(ii): 'five years after consummation'; the partner retains servicing, so SM holds the CD for both)." });
  o("REGZ_1026_25C2_LOCOMP_RETENTION_3Y", { anchorField: "paid_on", evaluator: "31.3.regZLoCompGateOpen", why: "§31.3 timer table: `lo_comp.paid` (ops-31-3.ts recordLoCompPaid — the `lo_comp_record` write) → payment/receipt date + 3 years; 'gate opens' / 'disposal blocked' (12 CFR 1026.25(c)(2): 'three years after the date of receipt or payment')." });
  o("REGZ_1026_25C3_ATR_RETENTION_3Y", { anchorField: "consummation_date", evaluator: "31.3.regZAtrGateOpen", why: "§31.3 timer table: `closing.consummated` → `consummation_date` + 3 years; 'gate opens' / 'disposal blocked' (12 CFR 1026.25(c)(3): 'three years after consummation')." });
  // ---- Reg B / Reg C / Reg X / OFAC / BSA gates
  o("REGB_1002_12B_APPLICATION_RETENTION_25M", { trigger: "`notice.adverse_action.sent`", anchorField: "regb_action_notified_at", evaluator: "31.3.regBApplicationGateOpen", why: "§31.3 timer table: `notice.adverse_action.sent` / `noia.sent` / `application.withdrawn` / `decision.issued{kind=approved_not_accepted}` (21.6's names) / `loan.funded` (approval notified) → `regb_action_notified_at` + 25 months, extended while `enforcement_notice.received` until `investigation.closed` ((b)(4)); the engine arms on the first alternative and `records.anchor` (ops-31-3.ts ANCHOR_EVENTS) sets the anchor from every one of them; 'gate opens' / 'disposal blocked' (12 CFR 1002.12(b)(1), (b)(4))." });
  o("HMDA_1003_5_LAR_RETENTION_3Y", { anchorField: "signed_at", evaluator: "31.3.hmdaLarGateOpen", why: "§31.3 timer table (owned here; 28.3 references): `hmda.lar.accepted` (28.3; the officer's `signed_at` completes the submission) → `signed_at` + 3 years; 'gate opens' / 'disposal blocked' (12 CFR 1003.5(a)(1)(i): retain the submitted register 'for at least three years'; verification report S2 item 6 re-keyed from the non-existent `hmda.lar.submitted`)." });
  o("RESPA_1024_15D_AFBA_RETENTION_5Y", { anchorField: "executed_on", evaluator: "31.3.respaAfbaGateOpen", why: "§31.3 timer table: `afba.executed` (ops-31-3.ts recordAfbaExecuted — the `afba_disclosure` write) → execution date + 5 years; 'gate opens' / 'disposal blocked' (12 CFR 1024.15(d): 'retained for 5 years after the date of execution')." });
  o("RESPA_1024_14H_S8_RETENTION_5Y", { trigger: "`record.enrolled{record_type∈{msa_agreement, referral_fee_record}}`", anchorField: "document_date", evaluator: "31.3.respaS8GateOpen", why: "§31.3 timer table: 'MSA/referral-fee document created' — the Section 8 record's enrolment (`record.enrolled{record_type}`, ops-31-3.ts enrollRecord for the `msa_agreement` / `referral_fee_record` types) → document date + 5 years; 'gate opens' / 'disposal blocked' (12 CFR 1024.14(h) [PARTIALLY VERIFIED])." });
  o("OFAC_501_601_RETENTION_10Y", { anchorField: "transaction_date", evaluator: "31.3.ofacGateOpen", why: "§31.3 timer table: `party.screened{result}` (22.6) / `ofac.property.blocked` / `ofac.transaction.rejected` (28.4) → transaction date + 10 years; for blocked property the anchor is unset (gate closed) until 28.4 records `ofac.report.submitted{unblocking}` (31 CFR 501.601: 'for the period of time that such property is blocked and for at least 10 years after the date such property is unblocked'); 'gate opens' / 'disposal blocked'." });
  o("BSA_1029_320C_SAR_RETENTION_5Y", { anchorField: "filed_on", evaluator: "31.3.sarGateOpen", why: "§31.3 timer table: `sar.filed` (28.4) → filing date + 5 years; 'gate opens' / 'disposal blocked' (31 CFR 1029.320(c): 'five years from the date of filing the SAR')." });
  // ---- Fannie Mae ownership / E-SIGN
  o("FNMA_B8_8_02_ENOTE_SIGNING_RECORDS_LIFE_PLUS_7Y", { anchorField: "liquidated_on", evaluator: "31.3.enoteSigningRecordsGateOpen", why: "§31.3 timer table: `enote.signed` (26.2) → later of `loan.liquidated` / `servicing.transferred_out` + 7 years, permanent while the loan is active; 'gate opens' / 'disposal blocked' (Selling Guide B8-8-02: signing records 'for the life of the loan plus seven years')." });
  o("ESIGN_7001_CONSENT_EVIDENCE_LIFE", { trigger: "`consent.granted{kind=esign}`", anchorField: "relationship_ended_on", evaluator: "31.3.esignConsentGateOpen", why: "§31.3 timer table: `consent.granted{esign}` (20.2/20.3 spell the consent `kind`) → end of the customer relationship, then the loan-file class; 'gate opens with the loan file' / 'disposal blocked' (15 U.S.C. 7001(c), (d); class `esign_consent_life`)." });
  // ---- schedules (origination additions to 19.1's): the purge sweep with the disposal run, the quarterly PII access review, the weekly data-use scan
  o("SM_O123_UNFUNDED_FILE_PURGE_SWEEP_MONTHLY", { trigger: "`schedule.tick{job=denied_withdrawn_purge_sweep}`", offset: "monthly", satisfied: "`disposal_run.executed{origination_unfunded=true}`", why: "§31.3 timer table: schedule (first Sunday, 'monthly (with 19.1's disposal run)') — ops-31-3.ts originationScheduleTicks emits `schedule.tick{job=denied_withdrawn_purge_sweep, source=origination}`; 'eligible unfunded objects included in the attested run' — executeUnfundedPurgeRun's `disposal_run.executed{origination_unfunded=true}` after the officer attestation (rule 5); breach sev 3." });
  o("SM_O123_PII_ACCESS_REVIEW_90", { trigger: "`schedule.tick{job=pii_access_review}`", offset: "quarterly", why: "§31.3 timer table: quarter-end → quarterly certification of principals with `applicant_demographics` / `credit_reports.raw` access (originationScheduleTicks emits the quarter-end tick); satisfied by `access_review.completed{scope=orig_pii}` (ops-31-3.ts completePiiAccessReview; uncertified access revoked); breach sev 1." });
  o("SM_O123_FANNIE_DATA_USE_SCAN_WEEKLY", { trigger: "`schedule.tick{job=fannie_data_use_scan}`", offset: "weekly", satisfied: "`fannie_data_use.scan.completed`", why: "§31.3 timer table: schedule → weekly 'scan of analytics/marketing/training datasets for Fannie Mae Data or credit data' — ops-31-3.ts scanFannieDataUse emits `fannie_data_use.scan.completed`; any hit → `fannie_data.use.violation_detected` and a sev-1 incident (Technology Guide / FCRA §604(f))." });
  // ---- vendor gates (fail closed at order time; evaluated inside the adapter layer)
  o("GLBA_1016_13_SERVICE_PROVIDER_CONTRACT_GATE", { trigger: "`vendor.order.requested{vendor_class}`", evaluator: "31.3.glbaServiceProviderContractGateOpen", why: "§31.3 timer table: `vendor.order.requested{vendor_class}` / any NPI transfer to a nonaffiliated third party → open only when the executed `contract_clauses{GLBA_1016_13_USE_LIMIT}` = present for the vendor **and** the partner's initial privacy notice is delivered or scheduled per §1016.4; breach 'order refused; `vendor.flowdown.blocked`; sev 1 → `officer`' (12 CFR 1016.13(a)(1); ops-31-3.ts checkVendorOrder)." });
  o("SM_O123_VENDOR_FLOWDOWN_GATE", { trigger: "`vendor.order.requested{vendor_class}`", evaluator: "31.3.vendorFlowdownGateOpen", why: "§31.3 timer table: 'same' trigger as the §1016.13 gate → open only when every `vendor_flowdown_requirements.required_clause_codes` for the class is `present` (or `deviation` with attorney sign-off); 'order refused' otherwise (rule 9; `assertGateOpen(SM_O123_VENDOR_FLOWDOWN_GATE)` inside every integrations/* adapter)." });
  // ---- deadlines: PII access anomaly disposition, legal hold within one hour
  o("SM_O123_PII_ACCESS_ANOMALY_1H", { anchorField: "detected_at", satisfied: "`pii.access.anomaly.dispositioned{disposition∈{benign, incident_opened}}`", why: "§31.3 timer table: `pii.access.anomaly` (bulk read, unexpected principal, off-purpose code — ops-31-3.ts logPiiAccess) → detected_at + 1 hour; 'disposition (benign / incident opened)' — dispositionPiiAnomaly's `pii.access.anomaly.dispositioned{disposition}` (an incident opens `security.incident.opened{domain=origination}` in 19.2's tables); breach: auto-revoke principal; sev 1." });
  o("SM_O123_LEGAL_HOLD_ON_TRIGGER_1H", { trigger: "`legal_hold.trigger.detected{reason}`", anchorField: "detected_at", satisfied: "`legal_hold.placed`", why: "§31.3 timer table: 'complaint (discrimination/UDAAP), regulator inquiry, CO AG notice, litigation, QC self-report, incident touching the application' — every trigger is recorded as `legal_hold.trigger.detected{reason}` (ops-31-3.ts detectHoldTrigger) → trigger + 1 hour; satisfied by `legal_hold.placed` (placeOriginationHold, reason `origination_*`, which also arms 19.1's SM_LEGAL_HOLD_REVIEW_180); breach sev 1." });
}
