/**
 * §19.3 timer overrides: for every 19.3 registry row whose trigger/anchor/"Satisfied by" column the
 * grammar cannot execute, a `reg.override(code, { trigger?, satisfied? | evaluator, offset?, anchorField?, why })`
 * (see src/domain/foreclosure/timers.ts applyForeclosureSatisfiedOverrides for the pattern).
 * Called from this section's timers.ts after the section-level overrides, so these win the merge.
 *
 * Every trigger and satisfying event named here is one the 19.3 tools (src/app/tools/section19-3.ts) emit, or an
 * input event the spec assigns to another process:
 *  - `notices.draft` records the contract event / Fannie Mae request and appends `contract_event.occurred{…}` (with the
 *    classification flags) or `fnma.request.received{kind}` (+ `fnma.data_return.directed` for a data-return demand);
 *  - `fnma_notices.recordSent` (officer) appends `fnma_notices.sent{kind, copy_document_id}`, `fnma.request.responded{kind}`,
 *    `tech_provider.change.notice_sent`, `form101.submitted` / `form101.acknowledged` / `form101.termination_submitted`
 *    and `data_return.certified{certified_by_role=officer}`;
 *  - `vendors.setStatus` appends `vendor.approved{reassessment_due}`, `tech_provider.change.cutover` (officer, after
 *    `assertGateOpen`) and `contract.expiry.resolved{resolution=offboarding}`; `vendors.assess` appends
 *    `vendor_assessment.completed{reassessment_due}`; `contracts.extractClauses` appends `contract.executed{expires_at}` /
 *    `contract.expiry.resolved{resolution=renewed}`; `portfolio.count` appends `portfolio_threshold_snapshot.written`;
 *    `portal_task.create` appends `form582.third_party_package.delivered{…}`;
 *  - the five input clocks: `contracts.extractClauses` (an executed `subservicing_agreement` with `effective_from`) appends
 *    `subservicing.arrangement.effective` (FNMA_A2107_FORM101_INCEPTION_GATE); `notices.draft` recording a termination under
 *    the subservicing agreement / technology-provider addendum appends `subservicing.arrangement.terminated{termination_effective_on}`
 *    (FNMA_A2107_FORM101_TERMINATION_5BD) and, under Supermortgage's own SSA / TSP schedule, `fnma.data_return.directed{source}`;
 *    `portal_task.create{task=integration_compliance}` appends `integration.noncompliance.detected{detected_at}` and, on the
 *    operator's completion, `integration.compliance.restored` (the daily `portfolio.count` sweep writes the day-120 disablement);
 *    `vendors.assess{op=incident}` / `{op=incident_notice}` append `vendor.incident.reported` (occurring at `vendor_aware_at`) and
 *    `vendor.incident.notice_received{sla_met}`; `ai_systems.upsert{policy}` (officer) appends `ai.policy.approved` and
 *    `ai_policy.reviewed{signed_by_owner=true}`.
 * The Form 582 package clock arms from `period.fiscal_year_end` (18.4 arms its own Form 582 clocks from the same event;
 * nothing emits a `form582.cycle.opened`): Form 582 is due FYE + 90, so "Form 582 due date − 30 days" = FYE + 60.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_19_3(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // ---- 180-day change gate (T2) — condition-shaped: cutover_on ≥ notice_sent_at + 180 calendar days; the cutover itself closes the instance
  o("FNMA_A2101_TECH_PROVIDER_CHANGE_NOTICE_180", { anchorField: "notice_sent_at", evaluator: "19.3.cutoverGateOpen", satisfied: "`tech_provider.change.cutover`", why: "§19.3 timer table: not_before_gate — `tech_provider.change.notice_sent` (recorded by `fnma_notices.recordSent{kind=a2101_change_180}` with `notice_sent_at`, `earliest_cutover_at`) opens +180 calendar days later; 'cutover command blocked; sev-1 if a cutover is attempted early' — `vendors.setStatus{cutover_on}` asserts `assertGateOpen` (A2-1-01 'not less than 180 days' prior written notice'); worked example 4: 2026-11-02 → 2027-05-01." });
  // ---- 5-BD event notice and copies (T3, T4): the trigger carries the rule-5 classification (`fnma_notice_required`, `copies_required`), the anchor is the occurrence/sent date
  o("FNMA_A2101_CONTRACT_EVENT_NOTICE_5BD", { trigger: "`contract_event.occurred{fnma_notice_required=true}`", anchorField: "occurred_on", satisfied: "`fnma_notices.sent{kind=a2101_event_5bd}`", why: "§19.3 timer table: `contract_event.occurred{kind ∈ termination, breach, impairment; contract.kind ∈ tech_provider}` → +5 `business_days_fannie_et` (end of day ET) — `classifyContractEvent` sets `fnma_notice_required` for every termination/breach/impairment event under a technology contract for critical servicing functions, including the partner's own breach and the ambiguous notices ('default to notify; attorney confirms within the 5-BD window'); satisfied by the officer-recorded `fnma_notices.sent{kind=a2101_event_5bd}` (A2-1-01). Worked example 5: Wed 2026-12-23 → Thu 2026-12-31." });
  o("FNMA_A2101_CONTRACT_COPIES_5BD", { trigger: "`contract_event.occurred{direction=sent_to_servicer, kind∈{termination, default_notice, breach_notice, non_performance_notice, impairment_notice}}`", anchorField: "occurred_on", satisfied: "`fnma_notices.sent{kind=a2101_copies_5bd, copy_document_id present}`", why: "§19.3 timer table: `contract_event.occurred{direction=sent_to_servicer; kind ∈ termination, default_notice, breach_notice, non_performance_notice, impairment_notice}` → copies to Fannie Mae +5 `business_days_fannie_et` from the sent date; 'satisfied by `fnma_notices.sent{a2101_copies_5bd}` with the copy attached' (A2-1-01 contract clause). T3: Fri 2026-11-20 → Mon 2026-11-30 EOD ET; a copy sent Dec 1 breaches sev-1 → officer." });
  // ---- Fannie Mae requests (T5, T10): `notices.draft{request_kind}` records the request and emits `fnma.request.received{kind}`
  o("FNMA_A2101_TRANSITION_PLAN_ON_REQUEST_10BD", { trigger: "`fnma.request.received{kind=transition_plan}`", satisfied: "`fnma_notices.sent{kind=transition_plan}`", why: "§19.3 timer table: `fnma.request.received{transition_plan}` → the transition plan +10 `business_days_fannie_et` (policy; Guide: 'upon Fannie Mae's written request'); satisfied by the officer-recorded `fnma_notices.sent{kind=transition_plan}`. T5: 2027-01-12 → 2027-01-27 (MLK Day excluded)." });
  o("FNMA_LL2026_04_DISCLOSURE_PROMPT_5BD", { trigger: "`fnma.request.received{kind=ll2026_04_disclosure}`", satisfied: "`fnma_notices.sent{kind=ll2026_04_disclosure}`", why: "§19.3 timer table: 'response sent' — the LL-2026-04 disclosure package (types, purposes, safeguards, inventory export) recorded by `fnma_notices.recordSent` after the officer signs; +5 `business_days_fannie_et` is the policy reading of 'promptly' (LL-2026-04). T10: 2026-10-05 → 2026-10-13 (Columbus Day excluded; docs/AUDIT-NOTES.md)." });
  o("FNMA_SUPP_PROGRAM_REQUEST_10BD", { satisfied: "`fnma.request.responded{kind∈{supplement_program, audit}}`", why: "§19.3 timer table: 'response sent' — `fnma_notices.recordSent{request_kind}` answering the Supplement-program or audit request emits `fnma.request.responded{kind}` (Supplement supply-chain section; policy 10 BD)." });
  // ---- Form 101 gate (T8): evaluator-backed so adapters can assertGate it; the officer's `fnma_notices.recordSent{kind=form101, acknowledgement_document_id}` emits `form101.acknowledged`
  o("FNMA_A2107_FORM101_INCEPTION_GATE", { evaluator: "19.3.form101Active", why: "§19.3 timer table: not_before_gate — `subservicing.arrangement.effective` (the executed subservicing agreement ingested by `contracts.extractClauses{kind=subservicing_agreement, effective_from}`, aggregated on the arrangement's Form 101 authorization) arms it; Form 101 `active` (Fannie Mae acknowledgement) before any Fannie Mae application access under the partner's servicer numbers; satisfied by `form101.acknowledged` on the same authorization; breach: 'Fannie Mae adapters refuse to run under partner scope' → `form101_inactive` (A2-1-07; Form TR101)." });
  // ---- Form 101 at termination (T9): the arrangement's termination is a `termination` contract event under the subservicing agreement / addendum; the clock runs from the termination's effective date (registry anchor 'termination date')
  o("FNMA_A2107_FORM101_TERMINATION_5BD", { anchorField: "termination_effective_on", why: "§19.3 timer table: `subservicing.arrangement.terminated` → +5 `business_days_fannie_et` from the 'termination date' (policy; A2-1-07 'at termination') — `notices.draft` recording a termination under the subservicing agreement / technology-provider addendum appends the event with `termination_effective_on` (the notice may occur months before the termination takes effect); satisfied by `form101.termination_submitted` from `fnma_notices.recordSent{kind=form101_termination}`. T9: effective Wed 2027-06-30 → Thu 2027-07-08 (July 5 observed excluded)." });
  // ---- LL-2026-04 annual policy review: the section-level override arms it on `ai.policy.approved` (annual); the owner's signed review closes it
  o("FNMA_LL2026_04_POLICY_REVIEW_365", { anchorField: "approved_on", satisfied: "`ai_policy.reviewed{signed_by_owner=true}`", why: "§19.3 timer table: 'policy approval' → annual; satisfied by '`ai_policy.reviewed` (owner)' — `ai_systems.upsert{policy}` (officer = the designated owner) appends `ai.policy.approved{approved_on}` and `ai_policy.reviewed{signed_by_owner=true}` (LL-2026-04: designated owner(s) reviewing 'at least annually'; DOC_AI_GOVERNANCE_POLICY annual review record); the tool closes the running instance and re-arms from the review (kernel recurring re-arm defect, see section19-3.ts)." });
  // ---- data return / destruction (edge case 'Supermortgage's own exit'; Technology Guide termination clause)
  o("FNMA_TECHGUIDE_TERMINATION_RETURN_DESTROY_30D", { trigger: "`fnma.data_return.directed`", anchorField: "termination_date", satisfied: "`data_return.certified{certified_by_role=officer}`", why: "§19.3 timer table: `ssa.terminated` / `schedule.terminated` / `fnma.data_return.directed` → +30 calendar days (policy) — one executable trigger: `fnma.data_return.directed{source ∈ ssa_terminated, schedule_terminated, fnma_request, form101_termination}` emitted by `notices.draft` (a `data_return` request; a `termination` contract event under Supermortgage's own `ssa` / `integration_agreement` — the SSA and the TSP schedule) and by `fnma_notices.recordSent{kind=form101_termination}` (the arrangement's termination); satisfied by `data_return.certified` from `fnma_notices.recordSent{kind=data_return_cert}` — 'have a duly authorized officer … certify' (Technology Guide)." });
  // ---- vendor reassessment cadence (T12): anchor = the last assessment's next-due date, carried on `vendor.approved` and `vendor_assessment.completed`
  o("FNMA_SUPP_VENDOR_REASSESSMENT", { anchorField: "reassessment_due", offset: "0", why: "§19.3 timer table: `vendor.approved` → Tier 1: 365 days; Tier 2: 730; Tier 3: 1095 from the last assessment (policy, risk-based) — `reassessment(tier, assessed_on)` computes `reassessment_due`, carried on `vendor.approved` (vendors.setStatus) and on the satisfying `vendor_assessment.completed` (vendors.assess) so the recurring clock re-arms; breach sev-2, Tier 1 overdue > 60 days → officer (`vendorReassessment`). T12: 2026-03-01 → 2027-03-01, officer 2027-04-30. `vendors.assess` records the satisfaction of the running instance and arms the next cycle itself (the kernel's recurring re-arm loops on same-subject satisfaction — see section19-3.ts)." });
  // ---- vendor incident SLA: "notice received" — the vendor's written incident notice against its contractual SLA (24 h default) from the vendor's awareness
  o("SM_VENDOR_INCIDENT_NOTICE_SLA", { anchorField: "vendor_aware_at", satisfied: "`vendor.incident.notice_received`", why: "§19.3 timer table: `vendor.incident.reported` → contract SLA (24 h default) from the vendor's awareness as reported — `vendors.assess{op=incident}` appends the event *occurring at* `vendor_aware_at` (the engine adds hour offsets to the event's own instant), so the +24 h clock lands at awareness + SLA; 'notice received' — `vendors.assess{op=incident_notice}` logs the vendor's written notice against `vendor_incidents` (`sla_met`, `hours_to_notice`); a miss is logged as a vendor SLA breach (`vendor.sla_breach.logged`) and feeds a triggered reassessment (`vendor.assessment.due`) (mandatory clause INCIDENT_NOTICE_24H)." });
  // ---- contract expiry warnings: armed at expires_at − 180 (sev-3; `contractExpiryWarnings` lists the −90/−30 legs) from the executed contract's own expiry
  o("SM_CONTRACT_EXPIRY_WARNING_180", { anchorField: "expires_at", offset: "−180 calendar_days", satisfied: "`contract.expiry.resolved{resolution∈{renewed, offboarding}}`", why: "§19.3 timer table: `contract.executed` (contracts.extractClauses ingesting the executed agreement with `expires_at`) → warnings at expires_at − 180 / − 90 / − 30 days (sev-3/2/1); 'renewal or offboarding started' — `contract.expiry.resolved{resolution=renewed}` when an amendment extends `expires_at`, `{resolution=offboarding}` when `vendors.setStatus` moves the vendor to offboarding (A2-1-01 Overview: orderly transfer upon termination or expiration); the tools close the running instance themselves before appending the resolution (kernel recurring re-arm defect, see section19-3.ts)." });
  // ---- daily threshold monitor: "snapshot written"
  o("SM_PORTFOLIO_THRESHOLD_MONITOR_DAILY", { satisfied: "`portfolio_threshold_snapshot.written`", why: "§19.3 timer table: 'snapshot written' — `portfolio.count` writes the `portfolio_threshold_snapshots` row (entity, as_of, loan_count, year_max, a2101_regime_active) with the count basis each day at 06:00 ET (A2-1-01 20,000-loan test); `portfolio.count` closes the day's tick instance itself before appending the snapshot event (kernel recurring re-arm defect, see section19-3.ts)." });
  // ---- Form 582 third-party package (T14): Form 582 due − 30 days = FYE + 60; "package delivered to 18.4"
  o("FNMA_582_THIRD_PARTY_PACKAGE_30D", { trigger: "`period.fiscal_year_end`", offset: "+60 calendar_days", satisfied: "`form582.third_party_package.delivered{supplement_attestation_document_id present}`", why: "§19.3 timer table: `form582.cycle.opened` (18.4) → 'Form 582 due date − 30 days' — 18.4 arms FNMA_A4102_FORM582_FYE_90 from `period.fiscal_year_end` (Form 582 due FYE + 90), so the package clock arms from the same event at FYE + 60; satisfied when `portal_task.create{task=form_582_upload, package}` hands the contractors/third-parties list, subservicing confirmation, Supplement attestation and LL-2026-04 summary to 18.4 (`form582ThirdPartyPackage`). T14: FYE 2026-12-31 → Form 582 due 2027-03-31 → package by 2027-03-01." });
}
