/**
 * §19.2 timer overrides: for every 19.2 registry row whose trigger, anchor or "Satisfied by"
 * column the event grammar cannot execute, a `reg.override(code, { trigger?, anchorField?, offset?,
 * satisfied | evaluator, why })` (see src/domain/foreclosure/timers.ts applyForeclosureSatisfiedOverrides
 * for the pattern). Called from this section's timers.ts after the section-level overrides, so these win.
 *
 * Why the registry text needs help (verified against src/kernel/events/match.ts):
 *   - `{S1,S2}` / `{S1}` / `{lost_media}` parse as bare truthy fields, never as `severity` / `category`;
 *   - `{fannie_mae_supplement}` / `{partner}` / `{nydfs}` / `{ftc}` likewise parse as truthy fields, so the
 *     spec's `incident.notice.sent{recipient}` event (data model `incident_notices.recipient`) must be spelled
 *     `{recipient=…}`; the two NYDFS 500.17(c) sends to the same recipient are told apart by `template_code`;
 *   - `consumer_count≥500` uses a comparator the grammar lacks (`>=`), and nested braces swallow the list;
 *   - the FTC anchor column is prose ("discovered_at (first day known; …)"), so `anchorField` is set explicitly;
 *   - "with/before consumer notices" is the NY consumer due date: discovered_at + 30 calendar days.
 *   - the credential row is one registry code for two periods ("`_90D` / `_365D` … 90 / 365 calendar days"), so its
 *     anchor is the computed `reset_due` the reset event carries (90 for a human Fannie Mae credential, 365 for a
 *     Fannie Mae System ID — ops-19-2.ts credentialReset) with offset 0, the way SM_VULN_REMEDIATION_SLA is anchored;
 *   - the platform spells the board report `board.report.delivered{kind=security}` (the 19.4 fair-servicing row shares
 *     the cycle on that event), where the registry column says `board_report.delivered`;
 *   - the annual all-account certification is the registry's own `access_review.completed{scope=all}` — it both
 *     re-arms and closes the row, like the other "last completion" rows;
 *   - a documented "not an incident" decision closes SM_NYDFS_DETERMINATION_48H (its second satisfier) but must not
 *     start the 72-hour NYDFS clock, so the 500.17(a) trigger is conditioned on `cybersecurity_incident=true`.
 * Producers of the trigger and satisfying events live in ./ops-19-2.ts (the security-program lifecycle: officer
 * sends, signatures and filings, CISO determinations and reviews, scan/print-mail/restore ingestion, the Sentinel)
 * and the 19.2 tools (src/app/tools/section19-2.ts), which call the same functions.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_19_2(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // ---- identification clocks (Supplement 36 h / Form 101 36 h / partner 24 h / NYDFS determination 48 h / lost media / post-incident)
  o("FNMA_SUPP_INCIDENT_NOTICE_36H", { satisfied: "`incident.notice.sent{recipient=fannie_mae_supplement}`", why: "§19.2 timer table: `incident.notice.sent{fannie_mae_supplement}` — the officer's send to privacy_office@fanniemae.com recorded in `incident_notices` (recipient=fannie_mae_supplement); the registry spelling parses as a bare field (Supplement: 'no later than 36 hours after identification')." });
  o("FNMA_FORM101_DATA_INCIDENT_NOTICE_36H", { trigger: "`security.incident.identified{severity∈{S1,S2}, fnma_application_data=true}`", anchorField: "identified_at", satisfied: "`incident.notice.sent{recipient=fannie_mae_form101}`", why: "§19.2 timer table: 'same, where Fannie Mae application Data involved' → S1/S2 identification with application Data; 'notices to Fannie Mae **and** partner' — the one Form 101 written notice is addressed to Fannie Mae and the Master Subscriber (NTC_FNMA_FORM101_INCIDENT rule both-recipients; Form 101 12/9/2025: 'notify Fannie Mae and Master Subscriber in writing … no later than 36 hours')." });
  o("SM_PARTNER_INCIDENT_NOTICE_24H", { trigger: "`security.incident.identified{severity∈{S1,S2}}`", satisfied: "`incident.notice.sent{recipient=partner}`", why: "§19.2 timer table: `security.incident.identified{S1,S2}` (registry braces parse as bare fields) → +24 hours [contract default]; satisfied by `incident.notice.sent{partner}` — the officer's contractual notice to the partner." });
  o("SM_NYDFS_DETERMINATION_48H", { trigger: "`security.incident.identified{severity∈{S1,S2}}`", satisfied: "`security.incident.determined`", why: "§19.2 timer table: `security.incident.identified{S1,S2}` → +48 hours [policy]; satisfied by `security.incident.determined` or the documented \"not an incident\" decision — both are `security.incident.determined` events, told apart by `cybersecurity_incident` (incident.scope prong (1) → true; ops-19-2.ts determineNotAnIncident → false) (rule 1: prong (1) is met the moment any FTC or state-regulator notice becomes required, so scoping must complete inside this clock)." });
  o("FNMA_SUPP_LOST_MEDIA_NOTICE_36H", { trigger: "`security.incident.identified{category=lost_media}`", satisfied: "`incident.notice.sent{recipient=fannie_mae_supplement}`", why: "§19.2 timer table: `security.incident.identified{lost_media}` → +36 hours; 'notice sent' — lost/stolen media is reported to Fannie Mae in the Supplement incident notice for that incident (Supplement: lost/stolen media within 36 hours)." });
  o("FNMA_SUPP_SEC_FILING_COPY_36H", { satisfied: "`incident.notice.sent{recipient=fannie_mae_supplement, kind=sec_filing_copy}`", why: "§19.2 timer table: 'notice sent' — copy of the SEC filing to Fannie Mae within 36 hours of filing; `kind` distinguishes the filing copy from the incident notice to the same recipient (Supplement; n/a unless public)." });
  o("FNMA_SUPP_POST_INCIDENT_ASSESSMENT", { trigger: "`security.incident.identified{severity=S1}`", anchorField: "identified_at", satisfied: "`independent_assessment.completed`", why: "§19.2 timer table: `security.incident.identified{S1}` (registry brace parses as a bare field) → engage +10 business_days_servicer (ops-19-2.ts postIncidentAssessmentClocks); complete +90 calendar days from identified_at [policy]; satisfied by `independent_assessment.completed` on the incident (ops-19-2.ts completeIndependentAssessment scope=incident, aggregated on the incident so only that incident's assessment closes it) — the Supplement's assessment 'upon the occurrence of any Cybersecurity Incident'." });
  // ---- NYDFS 500.17(a)/(c)
  o("NYDFS_500_17A_INCIDENT_NOTICE_72H", { trigger: "`security.incident.determined{cybersecurity_incident=true}`", anchorField: "determined_at", satisfied: "`incident.notice.sent{recipient=nydfs, template_code=NTC_NYDFS_500_17A}`", why: "§19.2 timer table: `security.incident.determined` → +72 hours from determined_at (23 NYCRR 500.17(a): 'no event later than 72 hours after determining that a cybersecurity incident has occurred') — conditioned on `cybersecurity_incident=true` so the CISO's documented 'not an incident' decision (which closes SM_NYDFS_DETERMINATION_48H) never starts this clock; satisfied by `incident.notice.sent{nydfs}` (portal) — the officer's DFS portal submission of the 500.17(a) payload." });
  o("NYDFS_500_17C_EXTORTION_PAYMENT_NOTICE_24H", { satisfied: "`incident.notice.sent{recipient=nydfs, template_code=NTC_NYDFS_500_17C_EXTORTION_24H}`", why: "§19.2 timer table: 'notice sent' — extortion payment notice to the superintendent within 24 hours (23 NYCRR 500.17(c)); told apart from the 30-day explanation by its template." });
  o("NYDFS_500_17C_EXTORTION_EXPLANATION_30D", { satisfied: "`incident.notice.sent{recipient=nydfs, template_code=NTC_NYDFS_500_17C_EXTORTION_30D}`", why: "§19.2 timer table: 'written explanation sent' — the 30-day written description of why payment was necessary, alternatives and diligence (23 NYCRR 500.17(c); spec output `NTC_NYDFS_500_17C_EXTORTION_30D`)." });
  // ---- FTC 314.4(j) and NY GBL §899-aa clocks from `discovered_at`
  o("FTC_314_4J_NOTIFICATION_EVENT_30D", { trigger: "`security.incident.scoped{unencrypted_customer_info_acquired∈{yes,presumed}, consumer_count>=500}`", anchorField: "discovered_at", satisfied: "`incident.notice.sent{recipient=ftc}`", why: "§19.2 timer table: `security.incident.scoped{unencrypted_customer_info_acquired∈{yes,presumed}, consumer_count≥500}` (grammar: `>=`) → +30 calendar days from `discovered_at` (first day known; the anchor never moves when the count is corrected later — 19.2-T4); satisfied by `incident.notice.sent{ftc}` (16 CFR 314.4(j))." });
  o("STATE_BREACH_CONSUMER_NOTICE_NY_30D", { satisfied: "`consumer_notices.mailed{state=NY, all_residents=true}`", why: "§19.2 timer table: '`consumer_notices.mailed` for all NY residents' — the print-mail completion for every affected NY resident (ops-19-2.ts consumerNoticesMailed) (N.Y. Gen. Bus. Law §899-aa(2): within thirty days after discovery)." });
  o("STATE_BREACH_REGULATOR_NOTICE_NY", { anchorField: "discovered_at", offset: "+30 calendar_days", satisfied: "`incident.state_regulator_notices.sent{state=NY}`", why: "§19.2 timer table: anchor discovered_at, 'with/before consumer notices (AG, DOS, State Police, DFS)' = the NY consumer due date, discovered_at + 30 calendar days; 'notices sent' — the composite send once all four regulators are notified (ops-19-2.ts stateRegulatorNoticesComplete) (N.Y. Gen. Bus. Law §899-aa(8)(a); DFS for Part 500 covered entities)." });
  o("STATE_BREACH_CRA_NOTICE_NY_5000", { anchorField: "discovered_at", offset: "+30 calendar_days", satisfied: "`incident.notice.sent{recipient=cras}`", why: "§19.2 timer table: `ny_residents > 5000` → 'with consumer notices' = discovered_at + 30 calendar days; 'CRA notice sent' — consumer reporting agencies notified of timing, content and distribution when more than 5,000 NY residents are notified at one time (N.Y. Gen. Bus. Law §899-aa(8)(b))." });
  // ---- vulnerability SLA and control program
  o("SM_VULN_REMEDIATION_SLA", { anchorField: "remediation_due", offset: "0", satisfied: "`vulnerability.remediated`", why: "§19.2 timer table: critical internet-facing 72 h; critical 7 d; high 30 d; medium 90 d; low 180 d [policy] — the computed anchor `remediation_due` is carried on `vulnerability.detected` by ops-19-2.ts ingestVulnerabilityScan (weekly scan ingestion, CTL-SEC-04); 'satisfied by `vulnerability.remediated` or approved exception' — both close as `vulnerability.remediated{disposition∈{remediated, approved_exception}}` (exceptVulnerability requires the Qualified Individual's `control_exceptions.approved` on the log)." });
  o("NYDFS_500_16D_BACKUP_RESTORE_TEST_365", { trigger: "`backup_restore_test.passed`", why: "§19.2 timer table: schedule → annual from the last test that passed (policy: quarterly automated restore); a failed quarterly restore neither satisfies nor restarts the clock — it is a `failed` control result with a sev-1 and a BCP exception (ops-19-2.ts backupRestoreTest; 19.2-T13) (23 NYCRR 500.16(d))." });
  o("FNMA_TECHGUIDE_CREDENTIAL_RESET_90D", { anchorField: "reset_due", offset: "0", satisfied: "`identity.credential.reset{fnma_credentials=true}`", why: "§19.2 timer table: '`FNMA_TECHGUIDE_CREDENTIAL_RESET_90D` / `_365D` … 90 / 365 calendar days' — one registry code for both periods, so the row is anchored on the computed `reset_due` the reset event carries (Technology Guide: 'every 90 calendar days for individuals and … every 365 calendar days for systems' — ops-19-2.ts credentialReset / credentialResetClock: human → reset_at + 90, fnma_system_id → reset_at + 365) with offset 0; 'reset event' — the next `identity.credential.reset{fnma_credentials=true}` (vault.rotateSecret / the IdP mirror) closes and re-arms it; at breach the credential is auto-disabled and a sev-1 raised (sentinelSweep; CTL-SEC-02 credentialAgeControlTest) (19.2-T11)." });
  o("FNMA_SUPP_TRAINING_365", { satisfied: "`personnel.training.completed{course=security_awareness}`", why: "§19.2 timer table: 'completion' — annual security-awareness training completion (covering data retention) per person (Supplement)." });
  o("FNMA_SUPP_FIREWALL_RULE_REVIEW_90", { satisfied: "`firewall_rule_review.completed`", why: "§19.2 timer table: 'review completed' — quarterly firewall-rule review on a defined frequency (Supplement; policy)." });
  o("FNMA_SUPP_WIRELESS_REVIEW_365", { satisfied: "`wireless_review.completed`", why: "§19.2 timer table: 'review completed' — annual wireless review (Supplement)." });
  o("NYDFS_500_12_MFA_COMPENSATING_REVIEW_365", { satisfied: "`control_exception.reviewed{control=CTL-SEC-01}`", why: "§19.2 timer table: 'review' — the CISO's annual review of a compensating control approved in lieu of MFA; the exception expires if not reviewed (23 NYCRR 500.12(b))." });
  // ---- program evidence rows whose registry spelling differs from the platform's
  o("FNMA_SUPP_INDEPENDENT_ASSESSMENT_365", { trigger: "`independent_assessment.completed{scope=program}`", offset: "annual", satisfied: "`independent_assessment.completed{scope=program}`", why: "§19.2 timer table: schedule → annual from last completion; satisfied by `independent_assessment.completed` — the program-wide assessment (scope=program, ops-19-2.ts completeIndependentAssessment) runs the annual clock; an incident-scoped one closes FNMA_SUPP_POST_INCIDENT_ASSESSMENT on its incident instead (Supplement: 'upon the occurrence of any Cybersecurity Incident … and at least annually … by a qualified independent auditor')." });
  o("FTC_314_4I_BOARD_REPORT_365", { satisfied: "`board.report.delivered{kind=security}`", why: "§19.2 timer table: satisfied by `board_report.delivered` — the platform spells the 314.4(i) report `board.report.delivered{kind=security}` (the trigger this section's timers.ts already uses, shared with §19.4 SM_FAIR_SERVICING_BOARD_REPORT_365 'annual with the 19.2 board cycle'); ops-19-2.ts deliverBoardReport (16 CFR 314.4(i); NYDFS 500.4)." });
  o("FNMA_SUPP_ACCESS_CERT_365", { trigger: "`access_review.completed{scope=all}`", satisfied: "`access_review.completed{scope=all}`", why: "§19.2 timer table: schedule → annual from last completion, all human and system accounts; satisfied by `access_review.completed{scope=all}` — the same certification (data model access_reviews.scope=all; Supplement: 'reviewed and certified by the entitlement owner or user manager at least annually') re-arms and closes the row (ops-19-2.ts completeAccessReview)." });
  o("SM_PRIV_ACCESS_REVIEW_90", { satisfied: "`access_review.completed{scope=privileged}`", why: "§19.2 timer table: quarter end → quarterly [policy]; satisfied by `access_review.completed{scope=privileged}` (ops-19-2.ts completeAccessReview)." });
  o("FNMA_SUPP_PENTEST_ANNUAL_365", { satisfied: "`pen_test.completed`", why: "§19.2 timer table: annual independent third-party penetration test from last report (ops-19-2.ts completePenTest; also FTC 314.4(d)(2)(i), NYDFS 500.5(a)(1))." });
  o("FTC_314_4D2_VULN_ASSESSMENT_180", { satisfied: "`vulnerability_assessment.completed`", why: "§19.2 timer table: every 6 months from last report (+ after material change) (ops-19-2.ts completeVulnerabilityAssessment; 16 CFR 314.4(d)(2)(ii))." });
  o("FTC_314_4B_RISK_ASSESSMENT_365", { satisfied: "`risk_assessment.approved`", why: "§19.2 timer table: annual from last approval [policy; rule says 'periodically'] (ops-19-2.ts approveRiskAssessment; 16 CFR 314.4(b))." });
  o("FNMA_SUPP_ATTESTATION_ANNUAL", { satisfied: "`supplement_attestation.signed`", why: "§19.2 timer table: `supplement_attestation.signed` (Supermortgage officer) delivered to partner for Form 582 (18.4) — ops-19-2.ts signSupplementAttestation." });
  o("NYDFS_500_17B_ANNUAL_CERT_APR15", { satisfied: "`nydfs_certification.filed`", why: "§19.2 timer table: `nydfs_certification.filed` by Apr 15 (23 NYCRR 500.17(b)) — ops-19-2.ts fileNydfsCertification (rule 11: the control results dictate certification vs acknowledgment)." });
  o("FNMA_SUPP_BCP_TEST_365", { satisfied: "`bcp_exercise.completed`", why: "§19.2 timer table: `bcp_exercise.completed` — annual tabletop + DR failover (ops-19-2.ts completeBcpExercise; NYDFS 500.16(c))." });
  o("SM_INCIDENT_ROOT_CAUSE_30D", { anchorField: "recovered_at", satisfied: "`lessons_learned.published`", why: "§19.2 timer table: `security.incident.recovered` (ops-19-2.ts transitionIncident carries `recovered_at`) → +30 calendar days; satisfied by `lessons_learned.published` (publishLessonsLearned)." });
  o("NYDFS_500_17C_EXTORTION_PAYMENT_NOTICE_24H", { anchorField: "paid_at", why: "§19.2 timer table: `extortion.payment.made` (ops-19-2.ts recordExtortionPayment — an officer act; the agent may not pay or negotiate) → +24 hours from the payment time; 'notice sent' — `incident.notice.sent{recipient=nydfs, template_code=NTC_NYDFS_500_17C_EXTORTION_24H}` (23 NYCRR 500.17(c))." });
  o("FNMA_SUPP_SEC_FILING_COPY_36H", { anchorField: "filed_at", why: "§19.2 timer table: `sec.filing.made` (ops-19-2.ts recordSecFiling) → +36 hours from the filed time; 'notice sent' — the copy of the filing to Fannie Mae, `incident.notice.sent{recipient=fannie_mae_supplement, kind=sec_filing_copy}` (Supplement; n/a unless public)." });
  // ---- one-time gate
  o("FNMA_TECHGUIDE_TLS_CIPHER_CUTOFF", { evaluator: "19.2.tlsProfileEcdheGcmOnly", why: "§19.2 timer table: 'CTL-SEC-03 passes with the ECDHE-GCM-only profile before the date' — a gate on the current cipher inventory, closed while any non-ECDHE-GCM cipher is enabled (Technology Guide; research/00b Oct. 23, 2026 cutoff)." });
}
