// 21.1 Conversational URLA/1003 intake, application data capture, and the MLO-of-record touchpoint
// spec/sections/21-application-urla-initial-disclosures-intent-to-proceed-rate/21-1-conversational-urla-1003-intake-application-data-capture-and.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("21.1-T1: Given a voice interview on Mon Oct 5, 2026 where the sixth item (loan amount $560,000) is stated at 10:41 MST, when the agent processes the utterance, then `trid_received_at` = 2026-10-05T10:41 MST, `application.trid_received` is emitted once, and 21.2's `REGZ_1026_19E1_LE_3BD` shows due date Thu Oct 8, 2026.", { todo: true });
test("21.1-T2: Given a prefilled property address from servicing data, when the borrower has not yet confirmed it, then `six_items.property_address.submitted_at` is null and `trid_received` is not emitted even if the other five items are submitted.", { todo: true });
test("21.1-T3: Given a telephone application where the applicant declines ethnicity and race, when the record is saved, then `declined_*` are true, `visual_observation_used=false`, and any attempt to write ethnicity/race values is rejected by the constraint.", { todo: true });
test("21.1-T4: Given a web application where the applicant selects \"Asian\" and \"White\", when saved, then both values persist and the FIG \"more than one race\" handling is available to 28.3.", { todo: true });
test("21.1-T5: Given two applicants on Mon Oct 19, 2026 where B has not affirmed joint intent, when 22.2 requests a credit pull for B, then `SM_O21_JOINT_INTENT_GATE` blocks it; after B's affirmation at 20:31 EDT the pull proceeds; the affirmation artifact id differs from the accuracy-attestation artifact id.", { todo: true });
test("21.1-T6: Given no SCIF presented to borrower B, when 23.1 attempts `du.submit`, then `SM_O21_SCIF_PRESENT_GATE` blocks; after `scif_forms.presented_at` is set (even with all answers blank), the submission proceeds.", { todo: true });
test("21.1-T7: Given `ai_intake_mode='assisted'` and no MLO of record assigned, when the agent attempts to display a specific rate/fee scenario, then the `SAFE_1008_103_MLO_OF_RECORD_GATE` prevents the `particular_terms_presented` utterance and the agent falls back to general explanations; once the MLO is assigned and approves at 14:02 on Oct 5, the scenario displays with the MLO attribution.", { todo: true });
test("21.1-T8: Given an application-stage escalation opened Fri Oct 9, 2026 at 16:00, when no MLO decision exists by end of creditor day Tue Oct 13, 2026 (Mon Oct 12 is a federal holiday and the calendar `creditor` marks it closed), then `SM_O21_MLO_REVIEW_SLA_1BD` breaches, the package is reassigned, and an `escalations` sev-2 row exists.", { todo: true });
test("21.1-T9: Given a `started` application with last activity Mon Oct 5, 2026 and no `received` transition, when the sweep runs on Wed Nov 4, 2026, then the application is `abandoned` and purged per the pre-application retention rule; the same file with `received` set is retained 25 months.", { todo: true });
test("21.1-T10: Given the interview transcript contains the agent asking about childbearing plans, when `compliance-sentinel` scans, then a sev-1 escalation is opened and the prompt version is quarantined.", { todo: true });
test("21.1-T11: Given an Arizona married applicant applying individually, when the 1003 is rendered, then the spouse appears only as `non_borrowing_spouse` for the security instrument and no credit data are requested from the spouse.", { todo: true });
test("21.1-T12: Given the MLO of record's NMLS status changes to \"inactive\" on Wed Oct 7, 2026, when the nightly feed loads, then the gate closes, the LE issuance in 21.2 is blocked until reassignment, and the reassignment is logged with the new NMLSR ID before any LE renders.", { todo: true });
