// 21.4 Intent to proceed, fee collection, and rate lock (lock confirmation, revised LE on lock, extensions, relocks, float-down, lock-to-commitment linkage)
// spec/sections/21-application-urla-initial-disclosures-intent-to-proceed-rate/21-4-intent-to-proceed-fee-collection-and-rate-lock-lock-confirma.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("21.4-T1: Given LE v1 with `effective_receipt_date` 2026-10-05 and no intent, when `orderAppraisal` ($650) is called Mon Oct 5, 2026 18:00 MST, then the gate refuses with `closed_no_intent`, no card token is captured, and `fee_gate_checks` records the attempt.", { todo: true });
test("21.4-T2: Given the same LE, when the borrower taps \"I want to proceed\" Tue Oct 6, 2026 09:14 MST, then `intent_records.valid=true`, `REGZ_1026_19E2_INTENT_FEE_GATE` opens at 09:14, and an `orderAppraisal` at 09:20 succeeds with `fee.imposed` $650.00.", { todo: true });
test("21.4-T3: Given no LE yet, when the credit-report fee is collected Oct 5 10:50 with a vendor invoice of $68.50, then the gate result is `exempt_credit_report` and the collected amount is capped at $68.50; a \"processing fee\" of $250 attempted at the same time is refused with `closed_no_receipt`.", { todo: true });
test("21.4-T4: Given a lock executed Wed Oct 7, 2026 10:19 MST with calendar `creditor` closed on Mon Oct 12, then `REGZ_1026_19E3IVD_LOCK_REVISED_LE_3BD` is due Tue Oct 13, 2026 23:59 MST; with the partner open on Oct 12 the due date is Mon Oct 12.", { todo: true });
test("21.4-T5: Given a 45-day lock executed Oct 7, then `expires_on` = Sat Nov 21 \u2192 rolled to Mon Nov 23, 2026 and `expires_at` = 2026-11-23 17:00 MST, displayed on LE v2 as \"11/23/2026 at 5:00 p.m. MST\"; `rate_set_date` = 2026-10-07.", { todo: true });
test("21.4-T6: Given a lock request at 6.125 %/100.000 with a stale rate sheet (superseded 2 minutes earlier), when the agent runs guardrails, then the lock is not executed, the quote is refreshed, and a new MLO escalation is opened; the MLO's approval of the old quote is rejected as `quote_expired`.", { todo: true });
test("21.4-T7: Given the CD was provided Mon Nov 2, 2026 and the borrower locks Tue Nov 3 at 6.250 % with $700.00 points, then no `disclosure.le.revised` is produced; a `changed_circumstances{kind='rate_lock', reflected_on='cd'}` row is created; 25.2 receives the terms; and the borrower was warned before execution that the closing may move to Mon Nov 9.", { todo: true });
test("21.4-T8: Given the closing slips from Nov 6 to Tue Dec 1, 2026 because the appraisal was late (`delay_attribution='lender_agent'`), then the lock is extended 8 days at 6.125 % with `extension_payer='lender_delay'`, fee $700.00 borne by the lender, no consumer charge and no revised LE/CD change for the fee.", { todo: true });
test("21.4-T9: Given the same slip requested by the borrower on Fri Nov 13, then `extension_payer='borrower'`, `changed_circumstances{kind='borrower_request'}` is inserted, and \u2014 because the CD was provided Nov 2 \u2014 the fee is reflected on a corrected CD (25.2) rather than a revised LE.", { todo: true });
test("21.4-T10: Given a New York property, a lock on Mon Oct 26 expiring Wed Nov 25, 2026, then the \u00a738.6(b)(4) notice window is Tue Oct 27\u2013Fri Nov 6 (creditor calendar; Veterans Day closed) and `NTC_NY_3NYCRR_38_6_LOCK_EXPIRY_NOTICE` is sent inside it (a send on Mon Nov 9 would be only 11 business days before expiry and fails the gate); the confirmation carries applicant and lender signature blocks and `state_agreement_variant='NY'`.", { todo: true });
test("21.4-T11: Given a best-efforts commitment executed for a lock lineage, when a relock creates version 2, then exactly one open commitment remains, `lock.relocked` triggers the 29.1 key-data update, and a second `commit` call for the same lineage is refused by the adapter.", { todo: true });
test("21.4-T12: Given the application is denied Fri Oct 23, 2026 after a lock with a $500 NY lock-in fee, then `lock.cancelled{lender_declination}`, the fee is refunded (ledger reversal) and 29.1 records fallout with `pair_off_expected=false`.", { todo: true });
