// 21.5 Changed circumstances, revised Loan Estimates, and tolerance management (good-faith baseline, 4-business-day rule, resets, cure)
// spec/sections/21-application-urla-initial-disclosures-intent-to-proceed-rate/21-5-changed-circumstances-revised-loan-estimates-and-tolerance-m.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("21.5-T1: Given the 21.2 fee set, when `fee.baseline.set` fires, then classes derive as: appraisal/credit/flood/tax service `zero` (cannot shop); title/settlement/endorsements `ten_percent` (on-list, non-affiliate); recording `ten_percent`; prepaid interest/escrow `unlimited`; lender credit `zero`; and `limit_cents` for the bucket = 205,150.", { todo: true });
test("21.5-T2: Given the appraisal changes $650 \u2192 $850 on Tue Oct 20, 2026 14:30 MST with basis (A)(3) evidence, then `revised_le_due_at` = Fri Oct 23, 2026 23:59 MST, the baseline resets to 85,000 cents on `evaluated_valid`, and LE v3 delivered Oct 21 satisfies `REGZ_1026_19E4_REVISED_LE_3BD`.", { todo: true });
test("21.5-T3: Given the same $850 with narrative \"AMC rate card increase Oct 15\", then `valid=false`, no reset, and the CD-stage test yields `cure_required` $200.00 applied as a lender credit on the CD.", { todo: true });
test("21.5-T4: Given bucket baseline 186,500 cents and CD actuals title 115,000, settlement 70,000, endorsements 15,000, recording 7,000, CPL 7,500 (new, baseline 0), then `actual_sum` = 214,500, `excess` = 9,350 cents and the CD carries a $93.50 cure.", { todo: true });
test("21.5-T5: Given a bucket baseline of 186,505 cents, then `limit_cents` = 205,155 (floor of 205,155.5) and the reset `threshold_cents` = 18,651 (ceil of 18,650.5).", { todo: true });
test("21.5-T6: Given the purchase fixture bucket baseline 222,000 and a Nov 9 fee sheet moving recording 15,000 \u2192 18,000 and settlement 55,000 \u2192 60,000, then `increase` = 8,000 < 22,200 \u2192 `exceeds=false`, no baseline reset, and the CD test passes with actual 230,000 \u2264 244,200.", { todo: true });
test("21.5-T7: Given consummation Fri Nov 6, 2026, then `latest_receipt` for a revised LE = Mon Nov 2, 2026; a revised LE mailed Fri Oct 30 (deemed received Tue Nov 3: Sat 31, Mon 2, Tue 3) fails the gate and the engine routes the change to the CD; a revised LE e-delivered and viewed Fri Oct 30 passes.", { todo: true });
test("21.5-T8: Given the CD was delivered Mon Nov 2, 2026, when a valid changed circumstance is recorded Tue Nov 3, then `issueRevisedLE` is refused, `reflected_on='corrected_cd'`, 25.2 receives the estimate, and the 3-day clock (due Fri Nov 6) is satisfied by the corrected CD delivered Nov 4.", { todo: true });
test("21.5-T9: Given a $200.00 excess discovered by post-closing QC on Fri Nov 20, 2026 for a loan consummated Fri Nov 6, then `REGZ_1026_19F2V_TOLERANCE_REFUND_60` is due Tue Jan 5, 2027, the refund is sent by ACH by that date, and 25.2's corrected CD is delivered or mailed by that date; a refund sent Jan 6 breaches.", { todo: true });
test("21.5-T10: Given the lender credit baseline \u2212$2,617 and a CD showing \u2212$2,417, then `shortfall` = 20,000 cents and the cure restores the credit to at least \u2212$2,617.", { todo: true });
test("21.5-T11: Given the borrower first indicates intent Thu Oct 22, 2026 09:00 after the Oct 20 5:00 p.m. expiration, then basis (E) is recorded, all baselines reset to Oct 22 estimates on LE v2 due Tue Oct 27, and the 21.4 fee gate opens on Oct 22 regardless.", { todo: true });
test("21.5-T12: Given a valid changed circumstance whose revised LE is delivered one creditor business day late, then the timer breach withdraws the reset, the CD-stage test uses the original baseline, and the excess is cured \u2014 with an incident record for the exam file.", { todo: true });
