// 21.6 Application-status decisions: notice of incompleteness, withdrawal, counteroffer, denial/adverse action (ECOA + FCRA), and HMDA action-taken recording
// spec/sections/21-application-urla-initial-disclosures-intent-to-proceed-rate/21-6-application-status-decisions-notice-of-incompleteness-withdr.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("21.6-T1: Given `application_date` Mon Oct 5, 2026, then `REGB_1002_9_DECISION_30` is due Wed Nov 4, 2026 23:59 MST; a denial notice sent Mon Oct 26 satisfies it; a notice sent Thu Nov 5 breaches and is logged as an incident.", { todo: true });
test("21.6-T2: Given a Refer with Caution recommendation with `decision_factors` `dti_max_50` failed (51.3 %) and `credit_delinquent` failed, when the agent selects reasons, then the notice states \"Excessive obligations in relation to income\" and \"Delinquent past or present credit obligations with others\" and never the string \"Refer with Caution\"; HMDA denial codes 1 and 3.", { todo: true });
test("21.6-T3: Given a denial recommendation without a reviewer decision, when `deliverNotice` is called, then it is refused; after `underwriting_reviewer` approval the notice sends and `adverse_actions.approved_by_reviewer_at` is set before `sent_at`.", { todo: true });
test("21.6-T4: Given two applicants with representative scores 712 (Experian/Fair Isaac V2) and 688, then two notices issue, each with only that applicant's score, range 300\u2013850, \u2264 4 key factors (5 if inquiries), score date and provider, the three CRAs' contact blocks, and the FTC address in the ECOA notice.", { todo: true });
test("21.6-T5: Given an NOIA sent Tue Oct 27, 2026 with a 14-day period, then `response_due_on` = Tue Nov 10, 2026; with no response, on Wed Nov 11 the file closes with HMDA code 5 and `action_taken_date` 2026-11-11 and no Reg B notice is required.", { todo: true });
test("21.6-T6: Given a C-4 combined counteroffer notice sent Tue Nov 3, 2026 expiring Wed Nov 18 with no acceptance, then no second notice is sent, HMDA code 3 on the original terms with date 2026-11-18 and reason 4; `REGB_1002_9_COUNTEROFFER_90` (due Mon Feb 1, 2027) is marked satisfied by the combined notice.", { todo: true });
test("21.6-T7: Given a counteroffer notice without combined content sent Fri Oct 30, 2026 and no acceptance, then an adverse action notice must be sent by Thu Jan 28, 2027 (policy: at the counteroffer's own expiry) and HMDA code 3 is recorded with that notice date.", { todo: true });
test("21.6-T8: Given the borrower says \"I'm going with another lender\" by voice on Fri Oct 16, 2026 before any decision, then `withdrawals.express=true`, HMDA code 4 with date 2026-10-16, no Reg B notice, and 21.4 cancels the lock as `borrower_withdrawal`.", { todo: true });
test("21.6-T9: Given 21 days of silence on an incomplete file with no NOIA sent, then the agent may not record a withdrawal; it must send the NOIA by day 30 or deny for incompleteness (only if data is insufficient).", { todo: true });
test("21.6-T10: Given a Colorado property and a denial decided Tue Jan 12, 2027 materially influenced by the underwriting ADMT, then `CO_SB26_189_1704_ADVERSE_EXPLANATION_30` is due Thu Feb 11, 2027, the notice sent Jan 14 carries the ADMT role description, human-review and correction instructions, and a human-review request on Jan 20 is completed by a different reviewer by Fri Feb 19, 2027.", { todo: true });
test("21.6-T11: Given the same facts with a decision dated Tue Dec 15, 2026, then no Colorado timer is created (act applies to decisions on or after Jan 1, 2027) while the ECOA/FCRA notice is unchanged.", { todo: true });
test("21.6-T12: Given an LLM-drafted borrower explanation containing \"applicants from your area usually don't qualify\", then the discouragement check blocks the send and routes to `compliance-sentinel`; the notice text (taxonomy only) is unaffected.", { todo: true });
test("21.6-T13: Given a conditional approval whose only open condition is a clear title that the seller cannot deliver by the contract deadline and the borrower cancels, then HMDA code 2 with `action_taken_date` = the approval expiration date, not code 3.", { todo: true });
