/**
 * §21.3 timer overrides (process-owned; applied after every section's so they win the merge — see
 * src/domain/bankruptcy/timers-14-1.ts for the pattern). One `reg.override(code, { trigger?, satisfied | evaluator,
 * anchorField?, offset?, why })` per 21.3 registry row whose trigger/satisfied column names an event the platform
 * spells differently or a condition the column grammar drops; `why` quotes the spec. A code the servicing spec
 * (sections 1–19) owns is never overridden here — reference it. Wired by src/domain/timer-overrides.ts.
 *
 * Grammar conventions (src/kernel/events/match.ts holds ONE dotted pattern per column):
 * - every way a companion rule is discharged — delivered (in person / portal / e-mail), placed in the mail (vendor
 *   proof) or carried on an LE inside the window — is the one event `CompanionDisclosureService` appends next to the
 *   spec's own channel events: `disclosure.companion.issued{rule_code, via∈{delivered, mailed, le}}`;
 * - the seven condition-shaped gates (ARM, score-notice consummation, AfBA referral, NY/NJ/FL pre-application, AZ
 *   fee agreement) are evaluator-backed and satisfied by the spec's own opening events;
 * - "same creditor business day" is the `same day` offset (end of the anchor day); the row's own `due_at` is computed
 *   at 23:59 in the creditor's zone by `companionDueAt`.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_21_3(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  o("REGX_1024_20_HCL_3BD", { anchorField: "application_received_at", satisfied: "`disclosure.companion.issued{rule_code=REGX_1024_20}`", why: "§21.3 timer table: trigger `application.received` (policy anchor), anchor `application_received_at` (creditor time zone), '+3 `business_days_creditor`, end of day', satisfied by '`disclosure.companion.delivered{hcl}` (in person/portal) or `.mailed{hcl}` with a list whose `hud_snapshot_at` ≥ delivery − 30 `calendar_days`' — §1024.20(a)(1) 'not later than three business days after … receives an application'; `CompanionDisclosureService.deliver` refuses a stale or short list (rule 3) before appending the spec's channel event and one `disclosure.companion.issued{rule_code=REGX_1024_20}` for either channel; (a)(5) denial/withdrawal before `due_at` cancels with reason (no breach)." });
  o("REGZ_1026_19G_TOOLKIT_3BD", { trigger: "`application.trid_received{transaction_type=purchase}`", anchorField: "trid_application_date", satisfied: "`disclosure.companion.issued{rule_code=REGZ_1026_19G}`", why: "§21.3 timer table: trigger '`application.trid_received` when `transaction_type='purchase'`', anchor `trid_application_date`, '+3 `business_days_creditor`, end of day', satisfied by '`disclosure.companion.delivered{toolkit}` / `.mailed{toolkit}` (edition = current registry asset)' — §1026.19(g)(1)(i) and (g)(1)(iii)(A) (refinances exempt: `exempt{refinance_no_toolkit}`, no timer); `deliver` refuses any edition but 2026-08; `onDecisionIssued` cancels with `denied_within_period` before `due_at`." });
  o("REGB_1002_14_APPRAISAL_NOTICE_3BD", { anchorField: "application_received_at", satisfied: "`disclosure.companion.issued{rule_code=REGB_1002_14A2}`", why: "§21.3 timer table: trigger `application.received` (first lien on a dwelling), anchor `application_received_at`, '+3 `business_days_creditor`, end of day (policy unit — Reg B defines none)', satisfied by '`disclosure.le.delivered`/`.mailed` (initial LE with the (m)(1) block) dated ≤ `due_at` → `satisfied_by_le`; else `disclosure.companion.delivered{regb_appraisal_notice}` / `.mailed`' — rule 4: `markSatisfiedByLE` emits `disclosure.companion.satisfied_by_le` and the issued event with `via=le` only when `le_out ≤ due_at`; the standalone C-9 notice (`deliver`) emits it with `via=delivered|mailed`; at `due_at − 4h` without an LE `standaloneRegBNoticeDue` requires the standalone notice." });
  o("REGZ_1026_35C5_HPML_APPRAISAL_NOTICE_3BD", { anchorField: "determined_at", satisfied: "`disclosure.companion.issued{rule_code=REGZ_1026_35C5}`", why: "§21.3 timer table: trigger `compliance.hpml.determined{is_hpml=true}` (23.4), anchor 'determination timestamp', '+3 `business_days_creditor`', satisfied by 'any prior `regb_appraisal_notice` row in `satisfied_by_le`/`delivered` state (compliance with §1002.14(a)(2) satisfies (c)(5)) — else the standalone notice' — `ingestHpmlDetermination` marks the (c)(5) row satisfied at creation from the prior Reg B row (issued `via=le`) or requires the standalone notice the same day (issued `via=delivered|mailed`)." });
  o("REGZ_1026_19B_ARM_DISCLOSURE_GATE", { evaluator: "21.3.armDisclosureGate", satisfied: "`arm.disclosures.delivered`", why: "§21.3 timer table: not_before_gate on `application.arm_interest.recorded`, 'opens when `NTC_REGZ_1026_19B_CHARM` and `NTC_REGZ_1026_19B_ARM_PROGRAM{plan}` are delivered electronically on/with the application (§1026.19(c)) or in person; for `channel='telephone'` the gate is provisional until delivery', blocks the ARM 1003 sections, 21.4's `impose_fee` and `issueLE` for an ARM product — condition-shaped: `armDisclosureGate` facts {arm_interest_recorded, charm_out_at, program_out_at}; `deliver` of the second of the two documents appends the spec's `arm.disclosures.delivered{fnma_plan_number}`." });
  o("REGZ_1026_19B_ARM_DISCLOSURE_3BD", { why: "§21.3 timer table: trigger '`application.arm_interest.recorded{channel='telephone'}`' (21.1 maps its `voice` intake channel through `armChannelFrom`), anchor `application_received_at` (conservative; the event's own date when absent), '+3 `business_days_creditor`', satisfied by `arm.disclosures.delivered` (delivered or placed in the mail) — §1026.19(b) telephone/intermediary exception; a mailing on the fourth business day breaches (sev 1) and the gate stays closed to fees and the ARM LE until the mailing proof exists." });
  o("FCRA_609G_SCORE_NOTICE_1BD", { anchorField: "received_at", satisfied: "`score_disclosure.delivered{all_borrowers_covered=true}`", why: "§21.3 timer table: trigger `credit.report.received` (22.2; bridged by `ingestCreditReport` until the credit adapter lands), anchor 'report received timestamp', '+1 `business_days_creditor`, end of day' (policy implementing §609(g)(1)(A) 'as soon as reasonably practicable'), satisfied by '`score_disclosure.delivered` for that borrower (§609(g) + H-3 together)' — one report event may carry several borrowers, so the clock is satisfied by the delivery that covers the last scored borrower (`all_borrowers_covered=true`)." });
  o("REGV_1022_74D_SCORE_NOTICE_CONSUMMATION_GATE", { evaluator: "21.3.scoreNoticeGate", satisfied: "`score_disclosure.delivered{all_borrowers_covered=true}`", why: "§21.3 timer table: not_before_gate on `credit.report.received` (created closed), 'opens when every borrower with a score has `score_disclosure.delivered` (or `.mailed`)', '`consummate` (26.x) and CD scheduling (25.2) blocked via `assertGateOpen`; sev 1' — §1022.74(d)(3) 'in any event at or before consummation'; `scoreNoticeGate` facts {scored_borrowers, covered_borrowers}; the delivery covering the last scored borrower carries `all_borrowers_covered=true`." });
  o("REGX_1024_15_AFBA_REFERRAL_GATE", { trigger: "`referral.requested{afba_required=true}`", evaluator: "21.3.afbaReferralGate", satisfied: "`referral.recorded{afba_gate=open}`", why: "§21.3 timer table: not_before_gate on '`referral.requested{provider}` where `affiliate_relationships` matches the referring party', 'opens when `afba.disclosure.delivered{referral_id}` exists dated ≤ the referral (or ≤ `application_received_at` for a required provider)', 'the referral/order command is refused … sev 2' — §1024.15(b)(1) 'no later than the time of each referral or, if the lender requires use of a particular provider, the time of loan application'; `requestReferral` appends `referral.requested{afba_required}` and, once `afbaReferralGate` opens, the spec's `referral.recorded{afba_gate=open}`." });
  o("SM_O23_PRIVACY_INITIAL_3BD", { anchorField: "application_received_at", why: "§21.3 timer table: policy deadline on `application.received`, anchor `application_received_at`, '+3 `business_days_creditor`', satisfied by '`privacy.initial_notice.delivered` (written or electronic with acknowledgment as a step)' — §1016.9(b)(1) delivery methods; `deliver` refuses an oral-only explanation (§1016.9(d), `ORAL_NOT_DELIVERY`) and appends `privacy.initial_notice.delivered{channel, edition}` on a written/electronic delivery; 25.4's `GLBA_1016_4_INITIAL_PRIVACY_GATE` remains the legal gate (referenced, never redefined)." });
  o("NY_3NYCRR_38_3_PREAPP_DISCLOSURE_GATE", { evaluator: "21.3.nyPreappDisclosureGate", satisfied: "`state_notice.acknowledged{code=NY_3NYCRR_38_3}`", why: "§21.3 timer table: not_before_gate on '`application.started` with property state NY (or `lead.qualified` when NY is known)', 'opens on `state_notice.acknowledged{NY_3NYCRR_38_3}` (e-signature/confirm button or signed copy)', 'blocks `application.received` transition (taking the application) and every `impose_fee` command incl. the credit-report fee' — 3 NYCRR 38.3 'prior to taking an application or collecting an application fee, credit report fee or property appraisal fee'; `recordAcknowledgment` appends the spec's event with `code`; a non-NY application's instance is cancelled `state_not_applicable`." });
  o("NJ_3_1_16_3_FEE_DISCLOSURE_GATE", { evaluator: "21.3.njFeeDisclosureGate", satisfied: "`state_notice.acknowledged{code=NJ_3_1_16_3}`", why: "§21.3 timer table: not_before_gate on '`application.started` with property state NJ', 'opens on `state_notice.acknowledged{NJ_3_1_16_3}` (written acknowledgment)', 'blocks every `impose_fee` incl. the credit-report fee and third-party reimbursements' — N.J.A.C. 3:1-16.3 'shall be acknowledged in writing by the borrower'." });
  o("AZ_ARS_6_946C_FEE_AGREEMENT_GATE", { evaluator: "21.3.azFeeAgreementGate", satisfied: "`state_notice.acknowledged{code=AZ_ARS_6_946C}`", why: "§21.3 timer table: not_before_gate on '`application.received` with property state AZ', 'opens when `NTC_AZ_ARS_6_946C_FEE_AGREEMENT` is signed by the borrower(s) and the partner (e-signature)', 'blocks `impose_fee` for any fee before consummation (21.4 consults)' — A.R.S. §6-946(C) 'The parties shall sign the written agreement'; the e-signature is recorded through `recordAcknowledgment{method=esignature}`." });
  o("TX_7TAC_57_200_SML_NOTICE_AT_APPLICATION", { offset: "same day", anchorField: "application_received_at", satisfied: "`state_notice.delivered{code=TX_7TAC_57_200}`", why: "§21.3 timer table: trigger '`application.received` with property state TX', anchor `application_received_at`, 'same creditor business day, end of day', satisfied by '`state_notice.delivered{TX_7TAC_57_200}` with retained delivery evidence' — 7 TAC §57.200 'at the time the mortgage banker … receives the initial application'; the column grammar has no 'same creditor business day' form, so the offset is `same day` (the row's `due_at` is 23:59 creditor time from `companionDueAt(anchor, 0)`)." });
  o("MA_MGL_184_17B_ATTORNEY_STATEMENT_AT_APPLICATION", { offset: "same day", anchorField: "application_received_at", satisfied: "`state_notice.delivered{code=MA_184_17B}`", why: "§21.3 timer table: trigger '`application.received` with property state MA', anchor `application_received_at`, 'same creditor business day', satisfied by 'statements rendered in the 1003 package in ≥ 2-point-larger type and `state_notice.delivered{MA_184_17B}`' — M.G.L. c. 184 §17B 'A printed copy of the above statements shall be given to the mortgagor at the time of making the application'; the 2-point-larger type is a layout rule on NTC_MA_MGL_184_17B_ATTORNEY_STATEMENT." });
  o("CA_21CCR_7114_FAIR_LENDING_NOTICE_AT_APPLICATION", { offset: "same day", anchorField: "application_received_at", satisfied: "`state_notice.delivered{code=CA_21CCR_7114}`", why: "§21.3 timer table: trigger '`application.received` with property state CA', anchor `application_received_at`, 'same creditor business day; acknowledgment requested', satisfied by '`state_notice.delivered{CA_21CCR_7114}`; acknowledgment tracked separately (non-blocking)' — 21 CCR §7114 'upon the submission of a written application'." });
  o("CA_CIV_1632_5_TRANSLATED_LE_3BD", { trigger: "`application.trid_received{property_state=CA, interview_language∈{es, zh, tl, vi, ko}}`", anchorField: "trid_application_date", satisfied: "`state_notice.delivered{code=CA_CIV_1632_5}`", why: "§21.3 timer table: trigger '`application.trid_received` where `interview_language ∈ {es, zh, tl, vi, ko}` and the negotiation was conducted primarily in that language (21.1 `interview_sessions`) and property state CA', anchor `trid_application_date`, '+3 `business_days_creditor`', satisfied by '`state_notice.delivered{CA_CIV_1632_5}` (DFPI translated LE matching LE v1); re-issued on each revised LE (21.5 hook)' — Civ. Code §1632.5 'no later than three business days after receipt of the written application'; `onLeRevised` creates the same-day row for each revised LE." });
  o("FL_69B_124_013_ANTI_COERCION_AT_APPLICATION", { evaluator: "21.3.flAntiCoercionGate", satisfied: "`state_notice.acknowledged{code=FL_69B_124_013}`", why: "§21.3 timer table (verification report item 39, corrected 2026-09-11): not_before_gate on '`application.started` with property state FL (or `lead.qualified` when FL is known)', 'opens on `state_notice.acknowledged{FL_69B_124_013}` (borrower-signed copy retained, per R. 69B-124.002)', 'blocks the `application.received` transition (formal application) and every `impose_fee` command for FL; sev 2' — R. 69B-124.002 'when negotiations for a loan begin, and prior to any formal application for loan or the payment of any fees'." });
}
