/**
 * §21.6 timer overrides (process-owned; applied after every section's so they win the merge — see
 * src/domain/bankruptcy/timers-14-1.ts for the pattern). One `reg.override(code, { trigger?, satisfied | evaluator,
 * anchorField?, offset?, why })` per 21.6 registry row whose trigger/satisfied column names an event the platform
 * spells differently or a condition the column grammar drops; `why` quotes the spec. A code the servicing spec
 * (sections 1–19) owns is never overridden here — reference it. Wired by src/domain/timer-overrides.ts.
 *
 * Emitters live in src/domain/application/ops-21-6.ts (the `underwriter` agent's rules): `application.completion.checked
 * {outstanding, checkpoint_day, application_date}` (computeCompletion), `decision.recommended{kind, recommended_on}`
 * (recommendDisposition), `decision.reviewed{outcome, kind, decided_on, after_conditional_approval, co_admt_applies}`
 * (reviewDecision), `decision.issued{kind, sent_on, consequential}` (deliverAdverseNotice / deliverNoia / recordWithdrawal /
 * closeIncomplete / approvals), `notice.adverse_action.sent`, `noia.sent{sent_on}` / `noia.responded`, `counteroffer.resolved
 * {outcome}` (acceptCounteroffer / the C-4 combined notice / deliverAdverseAfterCounteroffer), `co_admt.explanation.sent`,
 * `co_admt.human_review.requested` / `.completed`, `co_admt.correction.requested` / `.completed`, `co_admt.preuse_notice.delivered`
 * (recordPreuseNoticeDelivered — 20.3/21.1 call it at the point of interaction). `application.received{application_date}` is
 * 21.1's (receiveApplication). Referenced, never redefined: none of the servicing codes.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_21_6(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // Rule 1 / T1: 20.3's registry row is the registry owner of this code (trigger `application.received`, +30 calendar_days, satisfied cell "21.6"); the spec assigns the decision — and therefore the satisfier — to 21.6, which supplies it here. The notification of action taken is `decision.issued{kind}`: sent by deliverAdverseNotice (denial/counteroffer notice), deliverNoia (written NOIA), recordWithdrawal, closeIncomplete and the approval paths of recommendDisposition.
  o("REGB_1002_9_DECISION_30", { trigger: "`application.received`", anchorField: "application_date", offset: "+30 calendar_days", satisfied: "`decision.issued{kind∈{approval, conditional_approval, counteroffer, denial, incomplete, withdrawal, file_closed_incomplete, approved_not_accepted}}`",
    why: "§21.6 timer table: trigger '`application.received` (conservative anchor) — re-anchored later only if `completed_application_at` is set earlier by policy (never later than the conservative date)', anchor `application_date`, '+30 `calendar_days`, end of day creditor time zone', satisfied by '`decision.issued{conditional_approval|approval|counteroffer|denial}` with the notice sent, or `noia.sent`, or `application.withdrawn`', breach 'sev 1 → `compliance-sentinel` + partner `officer`; notice issues immediately; incident record; QC self-identification'. 20.3's row (trigger `application.received`, +30 calendar_days, satisfied '21.6') is the registry owner; 21.6 owns the decision and supplies the satisfier: ops-21-6 emits `decision.issued{kind}` at the notification of action taken for every kind (the NOIA path emits kind=incomplete from deliverNoia; the withdrawal path kind=withdrawal from recordWithdrawal), so 22.1/22.2/23.2/23.3 (and later 20.3) count this unit. 21.1's receiveApplication emits `application.received{application_date}` (§1002.9(a)(1)(i) — T1: Mon Oct 5 + 30 = Wed Nov 4, 2026; onDecisionClockBreached logs the incident)." });
  // Rule 1 / T9: arms at the agent's day-20 completion checkpoint while any regularly-obtained item is outstanding; a written NOIA (kind=incomplete) or any decision notice satisfies it — an oral request alone never does (comment 9(c)(3)-1).
  o("REGB_1002_9_NOIA", { trigger: "`application.completion.checked{outstanding=true, checkpoint_day>=20}`", anchorField: "application_date", offset: "+30 calendar_days", satisfied: "`decision.issued{kind∈{incomplete, denial, counteroffer, approval, conditional_approval}}`",
    why: "§21.6 timer table: trigger '`application.received` when any regularly-obtained item is outstanding at day 20 (agent checkpoint)', anchor `application_date`, '+30 `calendar_days`', satisfied by '`noia.sent` (written; an oral request alone does not satisfy — comment 9(c)(3)-1) or a decision notice'. computeCompletion emits the checkpoint fact `application.completion.checked{outstanding, checkpoint_day, application_date}`; deliverNoia emits `noia.sent{written=true}` together with `decision.issued{kind=incomplete}` — the single satisfier that also covers 'a decision notice' (§1002.9(c)(1): within 30 days notify of action taken or of the incompleteness)." });
  // Rule 1 / T5: the designated period (default 14, ≥ 10 by policy) is on the NOIA; the engine's default is the 14-day policy period anchored on `sent_on`; the actual `response_due_on` travels on the payload.
  o("REGB_1002_9C2_NOIA_RESPONSE", { trigger: "`noia.sent{written=true}`", anchorField: "sent_on", offset: "+14 calendar_days", satisfied: "`noia.responded{all_items=true}`",
    why: "§21.6 timer table: trigger `noia.sent`, anchor '`sent_at` date', '+`designated_period_days` `calendar_days` (default 14; ≥ 10 by policy)', satisfied by '`noia.responded` (all items) → decision clock resumes with `REGB_1002_9_DECISION_30` re-anchored to `responded_at`', breach 'on expiry: `application.closed_incomplete`; HMDA code 5 with `action_taken_date` = expiry date or closure date; no further Reg B notice required'. deliverNoia computes `response_due_on = sent_on + designated_period_days` (T5: Tue Oct 27 + 14 → Tue Nov 10, 2026) and refuses periods under 10 days; respondNoia emits `noia.responded{all_items}`; closeIncomplete writes HMDA 5 on Wed Nov 11." });
  // Rule 1 / T6–T7: 90 days from the counteroffer notice (`decision.issued{kind=counteroffer}` carries `sent_on`); one resolving event for the three outcomes the column lists.
  o("REGB_1002_9_COUNTEROFFER_90", { trigger: "`decision.issued{kind=counteroffer}`", anchorField: "sent_on", offset: "+90 calendar_days", satisfied: "`counteroffer.resolved{outcome∈{accepted, combined_notice_sent, adverse_action_sent}}`",
    why: "§21.6 timer table: trigger '`decision.issued{counteroffer}` (notice sent)', anchor 'notice `sent_at` date', '+90 `calendar_days`', satisfied by '`counteroffer.accepted` (express acceptance or use), or `notice.adverse_action.sent` (if `combined_notice=false`), or nothing further if `combined_notice=true` (comment 9(a)(1)-6)', breach 'sev 1 → `compliance-sentinel`; adverse action notice issues; HMDA \"denied on original terms\"'. The three outcomes are one `counteroffer.resolved{outcome}` fact: acceptCounteroffer (with `counteroffer.accepted`), deliverAdverseNotice with the combined C-4 notice (T6: sent Tue Nov 3 → due Mon Feb 1, 2027, satisfied by the combined notice), deliverAdverseAfterCounteroffer (T7: sent Fri Oct 30 → adverse notice by Thu Jan 28, 2027)." });
  // Worked example 1: recommendation Fri Oct 23 → SLA Tue Oct 27 (2 creditor business days); the cap `decision_due − 3` (Nov 1) is applied by reviewerSlaDue and carried as `sla_due_on` on the payload.
  o("SM_UNDERWRITING_REVIEWER_SLA_2BD", { trigger: "`decision.recommended{kind∈{denial, counteroffer, incomplete}}`", anchorField: "recommended_on", offset: "+2 business_days_creditor", satisfied: "`decision.reviewed{outcome∈{approved, returned}}`",
    why: "§21.6 timer table: trigger '`decision.recommended{denial|counteroffer|incomplete}`', anchor 'recommendation time', '+2 `business_days_creditor` (capped so that `decision_due_at − 3 calendar_days` is never passed)', satisfied by 'reviewer approval/return', breach 'escalate to partner `officer`; the 30-day clock is never breached for want of review — the reviewer queue is re-prioritised by `decision_due_at`'. recommendDisposition opens the `underwriting_reviewer` escalation and emits `decision.recommended{kind, recommended_on, sla_due_on}`; reviewDecision (the reviewer's own act) emits `decision.reviewed{outcome}`." });
  // Policy: the decision is taken at the reviewer's approval (`decided_on`); a denial after a prior conditional approval must be noticed within 5 creditor business days.
  o("SM_ADVERSE_NOTICE_5BD", { trigger: "`decision.reviewed{outcome=approved, kind=denial, after_conditional_approval=true}`", anchorField: "decided_on", offset: "+5 business_days_creditor", satisfied: "`notice.adverse_action.sent`",
    why: "§21.6 timer table: trigger '`decision.issued{denial}` after a prior conditional approval (decision later than the completed-application clock)', anchor `decided_at`, '+5 `business_days_creditor`', satisfied by `notice.adverse_action.sent`, breach 'sev 2 → `compliance-sentinel`'. The decision is taken when the `underwriting_reviewer` approves it (T3: `approved_by_reviewer_at` precedes `sent_at`), so the clock anchors on the approval's `decided_on` carried by `decision.reviewed{after_conditional_approval}`; deliverAdverseNotice emits `notice.adverse_action.sent` (edge case: counteroffer accepted, then denied later on a new factor → notice within the policy 5 business days)." });
  // T10/T11: only a Colorado consumer whose decision is materially ADMT-influenced and dated on/after 2027-01-01 (`co_admt_applies=true` computed by coDutiesApply) arms it; T11's Dec 15, 2026 decision carries co_admt_applies=false and never arms.
  o("CO_SB26_189_1704_ADVERSE_EXPLANATION_30", { trigger: "`decision.reviewed{outcome=approved, kind∈{denial, counteroffer}, co_admt_applies=true}`", anchorField: "decided_on", offset: "+30 calendar_days", satisfied: "`co_admt.explanation.sent`",
    why: "§21.6 timer table: trigger '`decision.issued{denial|counteroffer}` for a Colorado consumer/property when the decision was materially influenced by a covered ADMT, decisions on/after 2027-01-01 (`rule_sets.co.sb26_189.effective_from`)', anchor '`decided_at` date', '+30 `calendar_days`', satisfied by '`co_admt.explanation.sent` (embedded in the adverse action/counteroffer notice or standalone `NTC_CO_SB26_189_ADMT_NOTICE{adverse_outcome_explanation}`)', breach 'sev 1 → `compliance-sentinel`; explanation sent; AG cure-period tracking (60 days on notice of violation)'. 6-1-1704(3): 'within thirty days after making the decision' — the decision is made at the reviewer's approval (`decision.reviewed{decided_on, co_admt_applies}`; T10: Tue Jan 12 → Thu Feb 11, 2027); deliverAdverseNotice emits `co_admt.explanation.sent` when the explanation is embedded (sent Jan 14), sendAdmtExplanation when standalone." });
  // T10: a human-review or correction request → written outcome by a different reviewer within the policy 30 days (Jan 20 → Fri Feb 19, 2027).
  o("CO_SB26_189_1705_HUMAN_REVIEW_30", { trigger: "`co_admt.human_review.requested`", anchorField: "requested_on", offset: "+30 calendar_days", satisfied: "`co_admt.human_review.completed{written_outcome=true}`",
    why: "§21.6 timer table: trigger '`co_admt.human_review.requested` or `co_admt.correction.requested`', anchor 'request date', '+30 `calendar_days`', satisfied by '`co_admt.human_review.completed` / `co_admt.correction.completed` with a written outcome', breach 'sev 2 → `officer`; outcome still delivered' (6-1-1705(1)(a)(ii) 'meaningful human review and reconsideration … to the extent commercially reasonable' — no statutory period; 30 days is policy). requestHumanReview emits `co_admt.human_review.requested{requested_on}` (a correction request emits `co_admt.correction.requested` — the same 30-day policy, tracked on the adverse_actions.co_admt row); completeHumanReview refuses the approving reviewer and emits `co_admt.human_review.completed{written_outcome}`." });
  // Owned here (20.3/21.1 assert it at the point of interaction; the earlier 20.3 name `CO_6_1_1704_ADMT_PREUSE_NOTICE_GATE` is retired): a condition-shaped gate over the Colorado facts, closed by the pre-use notice delivery.
  o("CO_SB26_189_1704_PREUSE_NOTICE_GATE", { trigger: "`application.received{property_state=CO}`", evaluator: "21.6.coPreuseNoticeGate", satisfied: "`co_admt.preuse_notice.delivered{variant=pre_use}`",
    why: "§21.6 timer table: not_before_gate on 'first interaction where `consumer_state = CO` or `property_state = CO` and the calendar date ≥ 2027-01-01 (`rule_sets.co.sb26_189.effective_from`; policy delivery from Dec 1, 2026 per 20.3 open question 4)', '6-1-1704: \"prior to a deployer using a covered ADMT to materially influence a consequential decision, the deployer shall provide a clear and conspicuous notice\" — `NTC_CO_SB26_189_ADMT_NOTICE{pre_use}` delivered (point-of-interaction line + public notice URL) before any ADMT-influenced eligibility/pricing output', satisfied by `co_admt.preuse_notice.delivered`, breach 'ADMT-influenced outputs withheld; human path; sev 1 → `compliance-sentinel` if an output was produced first'. 21.6 owns the gate and the template (20.3's row references it '(per 21.6)'); 21.1's `application.received{property_state}` is the first origination fact that names the state; evaluators-21-6 coPreuseNoticeGate over {property_state, consumer_state, interaction_on, preuse_notice_delivered}; recordPreuseNoticeDelivered emits the closing event for 20.3/21.1." });
  // Retention (not a deadline): a gate that opens 3 years after the consequential decision — disposal of `co_admt_3y` records is refused while it is closed.
  o("CO_SB26_189_1703_RECORDS_3Y", { trigger: "`decision.issued{consequential=true}`", evaluator: "21.6.coRecordsRetentionElapsed",
    why: "§21.6 timer table: retention (not a timer) on 'every consequential decision', anchor `decided_at`, '3 years', 'retention class `co_admt_3y`' (6-1-1703: records 'not less than three years after the date of a consequential decision'; 31.2: developer records anchor on their creation date). Every `decision.issued{consequential=true}` (denials, counteroffers, approvals — ops-21-6) arms the gate; evaluators-21-6 coRecordsRetentionElapsed opens it at `decided_on + 3 years` and never under a legal hold (17.3/19.1 retention purge asserts it)." });
}
