/**
 * §21.2 timer overrides (process-owned; applied after every section's so they win the merge — see
 * src/domain/bankruptcy/timers-14-1.ts for the pattern). One `reg.override(code, { trigger?, satisfied | evaluator,
 * anchorField?, offset?, why })` per 21.2 registry row whose trigger/satisfied column names an event the platform
 * spells differently or a condition the column grammar drops; `why` quotes the spec. Wired by src/domain/timer-overrides.ts.
 *
 * Grammar conventions (src/kernel/events/match.ts holds ONE dotted pattern per column):
 * - "`disclosure.le.delivered` (esign_portal/in_person) or `disclosure.le.mailed`" becomes the one event
 *   `LoanEstimateService.deliver` (ops-21-2.ts) appends in both branches next to the spec's own channel events:
 *   `disclosure.le.issued{le_version, channel, in_person, issued_on}`;
 * - the 7-SBD gate is condition-shaped (open on/after the earliest consummation date or on a §1026.19(e)(1)(v) waiver),
 *   asserted by `assertGateOpen` through the evaluator and satisfied by the spec's `gate.le_7sbd.opened`;
 * - the mailbox derivation arms only when the channel is not in person (`in_person=false`);
 * - the MLO SLA arms on the platform's `escalation.created` (src/app/escalations.ts) carrying `stage=le_terms`.
 * `REGZ_1026_19E1_LE_3BD` is first named by 20.3 (the registry's owning row: "+3 business_days_creditor", satisfied by
 * "21.2"); this process supplies the satisfying event, so the override lands on that code (one code, one definition).
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_21_2(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  o("REGZ_1026_19E1_LE_3BD", { anchorField: "trid_application_date", satisfied: "`disclosure.le.issued{le_version=1}`", why: "§21.2 timer table: trigger `application.trid_received`, anchor `trid_application_date` (creditor time zone), offset '+3 `business_days_creditor`, end of day', satisfied by '`disclosure.le.delivered` (esign_portal/in_person) or `disclosure.le.mailed` with vendor mailing evidence' — §1026.19(e)(1)(iii)(A) 'deliver or place in the mail … not later than the third business day after the creditor receives the consumer's application'; `LoanEstimateService.deliver` emits the spec's channel event and one `disclosure.le.issued{le_version=1}` for either channel (a mailed LE needs the print vendor's mailing-date proof before the event is appended); `le_due_at` itself is computed at 23:59 in the creditor's own zone by `leDueAt`." });
  o("REGZ_1026_19E1III_LE_7SBD_GATE", { trigger: "`disclosure.le.issued{le_version=1}`", anchorField: "issued_on", evaluator: "21.2.le7sbdGateOpen", satisfied: "`gate.le_7sbd.opened`", why: "§21.2 timer table: not_before_gate, trigger '`disclosure.le.delivered`/`.mailed` (initial LE)', anchor 'delivery/mailing date', offset 'earliest consummation = anchor + 7 `business_days_regz_specific`', satisfied 'gate open on that date', waiver 'only via (e)(1)(v) written emergency statement recorded on `consents` kind `trid_7day_waiver`' — comment 19(e)(1)(iii)-2: 'consummation may occur on or after Tuesday, June 9, the seventh business day following delivery or mailing'; condition-shaped, asserted by `assertGateOpen` (26.x consummation, 25.2 CD scheduling) through `le7sbdGate`; `openGateIfDue` / `recordEmergencyWaiver` emit `gate.le_7sbd.opened{earliest_consummation_date, waived}` (the spec's own event) when the gate opens." });
  o("REGZ_1026_19E1IV_LE_MAILBOX_3SBD", { trigger: "`disclosure.le.issued{in_person=false}`", anchorField: "issued_on", offset: "+3 business_days_regz_specific", satisfied: "`disclosure.le.received`", why: "§21.2 timer table: trigger '`disclosure.le.delivered`/`.mailed` when channel ≠ in_person', anchor 'delivery/mailing date', offset '+3 `business_days_regz_specific` → `deemed_receipt_date`', satisfied by '`disclosure.le.received` with evidence (earlier) or the deemed date' — §1026.19(e)(1)(iv): 'the consumer is considered to have received the disclosures three business days after they are delivered or placed in the mail'; `recordReceipt` (authenticated view / acknowledgement / e-signature) and the `deemReceived` sweep both append `disclosure.le.received{evidence}`; in-person delivery arms nothing." });
  o("REGZ_1026_37A13_COSTS_EXPIRE_10BD", { trigger: "`disclosure.le.issued{le_version=1}`", anchorField: "issued_on", offset: "+10 business_days_creditor, 17:00 MT", why: "§21.2 timer table: trigger '`disclosure.le.delivered`/`.mailed`', anchor 'delivery/mailing date', offset '+10 `business_days_creditor`, 5:00 p.m. creditor time (or a longer period the creditor specifies)', satisfied by `intent.to_proceed.received` (21.4) — §1026.37(a)(13)(ii) / §1026.19(e)(3)(iv)(E); the column grammar reads '5:00 p.m.' as 05:00 ET, so the hour is stated as 17:00 Mountain (the fixture partner's creditor time; the exact instant in the creditor's own zone, e.g. America/Phoenix 17:00 MST = 00:00Z, is `closingCostsExpireAt` on the issued event and the LE row); `closingCostsExpirationField` blanks the LE field once intent arrives inside the period (comment 37(a)(13)-4)." });
  o("SM_O22_MLO_LE_REVIEW_SLA_1BD", { trigger: "`escalation.created{kind=mlo_of_record, stage=le_terms}`", offset: "+1 business_days_creditor", satisfied: "`disclosure.le.mlo_reviewed{decision∈{approved, returned}}`", why: "§21.2 timer table: trigger '`escalation.opened{role=mlo_of_record, stage=le_terms}`', anchor `opened_at`, offset '+1 `business_days_creditor` but never later than `le_due_at` − 2 hours', satisfied by '`mlo_reviews.decision`' — the platform's escalation event is `escalation.created{kind, stage}` (src/app/escalations.ts; `openMloReview` carries `stage=le_terms` and the capped `sla_due_at` computed by `mloReviewSlaDueAt`); `mloDecision` appends `disclosure.le.mlo_reviewed{decision}` for an approval or a return, and `disclosure.le.mlo_approved` on approval." });
}
