/**
 * §24.2 timer overrides (process-owned; applied after every section's so they win the merge — see
 * src/domain/bankruptcy/timers-14-1.ts for the pattern). One `reg.override(code, { trigger?, satisfied | evaluator,
 * anchorField?, offset?, why })` per 24.2 registry row whose trigger/satisfied column names an event the platform
 * spells differently or a condition the column grammar drops; `why` quotes the spec. A code the servicing spec
 * (sections 1–19) owns is never overridden here — reference it. Wired by src/domain/timer-overrides.ts.
 *
 * Every 24.2 event (src/domain/property/ops-24-2.ts) carries `applicationId`, so these rows arm only under origination
 * context (src/kernel/timers/engine.ts isOriginationContext). Business-day unit for §1002.14 and §1026.35(c)(6):
 * `business_days_creditor` (spec "Unit decision"). REGZ_1026_35C_HPML_APPRAISAL_COPY_3BD keeps the semantics 23.4
 * (src/domain/underwriting/timers-23-4.ts) gave it — trigger `compliance.hpml.determined{is_hpml=true,
 * appraisal_rules_apply=true}`, evaluator 23.4.hpmlAppraisalCopy3bd (ops-24-2.ts re-exports the same gate function),
 * satisfied `valuation.copy.delivered` — this file runs after 23.4's and restates them so the row is owned here.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_24_2(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  o("SM_UCDP_SUBMIT_SLA_1BD", { trigger: "`valuation.received`", anchorField: "received_at", offset: "+1 `business_days_creditor`", satisfied: "`valuation.ucdp.submitted{both_gses=true}`",
    why: "§24.2 timer table: deadline on '`valuation.received` / `valuation.revision.received`' (24.1's receipt event; a revision re-arms through ops-24-2.ts recordRevisionReceived's `valuation.revision.received` — one trigger per row, receipt is the canonical one), anchor `received_at`, +1 `business_days_creditor`; satisfied by '`valuation.ucdp.submitted` (both GSEs)' — recordUcdpSubmitted stamps `both_gses=true` when fnma and fhlmc were both submitted (R1: 'Submit to both GSEs within 1 business day'); breach: sev 3; DI outage → portal fallback." });
  o("SM_APPRAISAL_REVIEW_SLA_2BD", { trigger: "`valuation.ucdp.result.received`", anchorField: "result_at", offset: "+2 `business_days_creditor`", satisfied: "`valuation.review.completed`",
    why: "§24.2 timer table: deadline on `valuation.ucdp.result.received` (recordUcdpResult, one per GSE SSR), anchor `result_at` (the SSR timestamp), +2 `business_days_creditor`; satisfied by `valuation.review.completed` (recordReviewCompleted); breach: sev 2 → `valuation` agent re-run; lock risk to 21.4." });
  o("REGB_1002_14_APPRAISAL_COPY_PROMPT_7", { trigger: "`valuation.review.completed{review_status=accepted}`", anchorField: "completion_at", offset: "+7 `calendar_days`", satisfied: "`valuation.copy.delivered`",
    why: "§24.2 timer table: deadline on '`valuation.review.completed{accepted}` (= completion)' — the accepted review sets `completion_at` (comment 14(a)(1)-4: the later of the last version received and the reviewed-and-accepted moment), +7 `calendar_days` ('promptly upon completion'; policy target +1 `business_days_creditor` — the copy engine schedules the package the same day, R5: e-delivered Fri Oct 16 10:45); satisfied by '`valuation.copy.delivered{version}`' (recordCopyDelivered carries `version`); breach: sev 1 at day 8 → `officer` notified; corrective delivery." });
  o("REGB_1002_14_APPRAISAL_COPY_3BD_GATE", { trigger: "`closing.scheduled`", evaluator: "24.2.regbCopy3bdGate", satisfied: "`valuation.copy.delivered{is_final_version=true}`",
    why: "§24.2 timer table: not_before_gate on `consummate`, trigger '`closing.scheduled` / any new version' (26.2's scheduling event; a new version re-runs the copy engine and the evaluator is re-asserted at `consummate` over the latest version), anchor `consummation_at`; offset 'latest version provided ≥ 3 `business_days_creditor` before consummation (copy day + 3 → earliest consummation)' — evaluator 24.2.regbCopy3bdGate (ops-24-2.ts regBCopyGate: copy Tue Nov 3 → Fri Nov 6 open; Wed Nov 4 → Mon Nov 9 proposed); satisfied by '`valuation.copy.delivered` for `is_final_version` or valid waiver + copy at/before consummation'; breach: block `consummate`; propose new date." });
  o("REGB_1002_14_WAIVER_3BD_GATE", { trigger: "`valuation.copy.waiver.requested`", evaluator: "24.2.waiver3bdGate", satisfied: "`valuation.copy.waived`",
    why: "§24.2 timer table: not_before_gate on `valuation.copy.waived`, trigger 'borrower waiver statement' — recordWaiverRequested's `valuation.copy.waiver.requested{statement_channel, obtained_at, consummation_at_when_obtained}` (the dated affirmative oral or written statement, comment 14(a)(1)-6), anchor `consummation_at`; offset 'waiver obtained ≥ 3 `business_days_creditor` before consummation' — evaluator 24.2.waiver3bdGate (waiverDecision: recorded Wed Nov 4 for Fri Nov 6 refused; Tue Nov 3 accepted, copies still due at or before consummation); satisfied by '`consents{regb_1002_14_timing_waiver}` dated in time' — recordCopyWaived's `valuation.copy.waived{consent_id, consent_kind=regb_1002_14_timing_waiver}`; breach: waiver refused; the copy gate governs." });
  o("REGB_1002_14_COPY_NOT_CONSUMMATED_30", { trigger: "`valuation.not_consummated.determined`", anchorField: "determination_at", offset: "+30 `calendar_days`", satisfied: "`notice.sent{template=NTC_REGB_1002_14_COPY_NOT_CONSUMMATED}`",
    why: "§24.2 timer table: deadline on '`application.withdrawn` / `decision.issued{kind ∈ denial, approved_not_accepted}` / `application.closed_incomplete` (21.6) / `funding.cancelled{reason}` (26.3)' — four causes, one row: ops-24-2.ts recordNotConsummated folds each into `valuation.not_consummated.determined{cause, decision_kind, determination_at}` (the creditor's determination that consummation will not occur), anchor `determination_at`, +30 `calendar_days` (§1002.14(a)(1); R8: denial Fri Oct 30 → Sun Nov 29, scheduled Fri Nov 27); satisfied by '`notice.sent{template=NTC_REGB_1002_14_COPY_NOT_CONSUMMATED}` (shared Notice Registry event)'; breach: sev 1." });
  o("REGZ_1026_35C_HPML_APPRAISAL_COPY_3BD", { trigger: "`compliance.hpml.determined{is_hpml=true, appraisal_rules_apply=true}`", evaluator: "23.4.hpmlAppraisalCopy3bd", satisfied: "`valuation.copy.delivered`",
    why: "§24.2 timer table: not_before_gate on `consummate`, trigger '`hpml_determinations{is_hpml, not exempt}`' — 23.4's `compliance.hpml.determined{is_hpml=true, appraisal_rules_apply=true}` (`appraisal_rules_apply = is_hpml ∧ ¬qm ∧ loan_amount > $34,200`, R7), anchor `consummation_at`; offset 'every written appraisal (incl. second) provided ≥ 3 `business_days_creditor` before consummation; no waiver' — evaluator 23.4.hpmlAppraisalCopy3bd (hpmlAppraisalCopyGate, re-exported by ops-24-2.ts: Wed Nov 18 → copies by Fri Nov 13); satisfied by '`valuation.copy.delivered` for all HPML appraisals' (recordCopyDelivered with `hpml=true`); breach: block `consummate`. Semantics kept from timers-23-4.ts; owned here." });
  o("REGZ_1026_35C_HPML_COPY_NOT_CONSUMMATED_30", { trigger: "`valuation.not_consummated.determined{hpml_appraisal_rules_apply=true}`", anchorField: "determination_at", offset: "+30 `calendar_days`", satisfied: "`valuation.copy.delivered{hpml=true}`",
    why: "§24.2 timer table: deadline 'as above, not consummated' — the same `valuation.not_consummated.determined` carrying `hpml_appraisal_rules_apply=true` (R8: Reg B and, if HPML, §1026.35(c)(6)(ii)(B)), anchor `determination_at`, +30 `calendar_days`; satisfied by 'delivery' — recordCopyDelivered's `valuation.copy.delivered{hpml=true}` for the not-consummated package; breach: sev 1." });
  o("FNMA_B4_1_1_06_UCDP_SUCCESSFUL_GATE", { trigger: "`valuation.review.completed`", evaluator: "24.2.ucdpSuccessfulGate", satisfied: "`valuation.ucdp.result.received{gse=fnma, status=successful}`",
    why: "§24.2 timer table: not_before_gate on `submitDelivery` (29.4), trigger `valuation.review.completed`; offset 'final version `ucdp_status = successful` for Fannie Mae, Doc File ID stored' — evaluator 24.2.ucdpSuccessfulGate over the final version's Fannie Mae SSR status and Doc File ID (B4-1.1-06: 'the final version of the report that was utilized in making the underwriting decision must be submitted through the UCDP' and 'receive a Successful status'); satisfied by '`ucdp_submissions.status = successful`' — recordUcdpResult's `valuation.ucdp.result.received{gse=fnma, status=successful}` (a resubmission after an override or correction); breach: block delivery (29.4)." });
  o("SM_ROV_SCREEN_SLA_2BD", { trigger: "`rov.requested`", anchorField: "requested_at", offset: "+2 `business_days_creditor`", satisfied: "`rov.screened`",
    why: "§24.2 timer table: deadline on `rov.requested` (recordRovRequested), anchor `requested_at`, +2 `business_days_creditor` (R6: received Tue Oct 20 → due Thu Oct 22); satisfied by '`rov.screened` + SME decision' — recordRovScreened's `rov.screened{screen_result, sme_escalation_id}` (the SME escalation to `underwriting_reviewer` is opened with the complete screen); breach: sev 2." });
  o("FNMA_B4_1_3_12_ROV_TURNTIME_5BD", { trigger: "`rov.forwarded`", anchorField: "sent_to_appraiser_at", offset: "+5 `business_days_creditor`", satisfied: "`rov.response.received`",
    why: "§24.2 timer table: deadline on `rov.forwarded` (recordRovForwarded, the standardized template-locked appraiser communication), anchor `sent_to_appraiser_at`, +5 `business_days_creditor` (the policy's 'turn-time expectation', B4-1.3-12; R6: Wed Oct 21 → Wed Oct 28: Oct 22, 23, 26, 27, 28); satisfied by `rov.response.received` (recordRovResponse: the revised report with commentary); breach: AMC escalation; borrower status update." });
  o("FNMA_B4_1_3_12_ROV_CLOSING_GATE", { trigger: "`closing.consummated`", evaluator: "24.2.rovClosingGate",
    why: "§24.2 timer table: not_before_gate (window closes) on `closing.consummated` (26.2), offset 'no borrower ROV after consummation' — evaluator 24.2.rovClosingGate (rovClosingGate: B4-1.3-12 'After a loan has closed, an ROV request is no longer allowed to be submitted by the borrower'); no satisfying event (the window never reopens; a lender-initiated ROV remains possible); breach: request rejected with explanation (screenRov `post_closing_rejected`)." });
  o("SM_CU_HIGH_RISK_REVIEW_1BD", { trigger: "`valuation.cu.scored{enhanced_review_required=true}`", anchorField: "scored_at", offset: "+1 `business_days_creditor`", satisfied: "`valuation.review.enhanced.recorded`",
    why: "§24.2 timer table: deadline on '`valuation.cu.scored{score ≥ 4.0 or overvaluation flag}`' — recordCuScored computes `enhanced_review_required = cu_score ≥ 4.0 ∨ cu_flags.overvaluation` (cuReviewTier, R2) so the disjunction the column grammar cannot express becomes one field, anchor `scored_at`, +1 `business_days_creditor`; satisfied by 'enhanced review record' — recordEnhancedReview's `valuation.review.enhanced.recorded{comparable_reanalysis}` (T12: the record includes a comparable re-analysis and `rw_relief_property_value = false`); breach: sev 2." });
}
