/**
 * §21.6 process-owned tools — bus tools for 21.6 defined with `defineTools("21.6", <agent>, defs)` from
 * ../tools.ts. Every tool string must be one spec/registry/agents.json names for 21.6; src/app/tools.test.ts refuses
 * the rest. Spread by ./index.ts.
 *
 * The `underwriter` agent runs in application scope (ctx.applicationId; the decision file is the `application_decisions`
 * document in the entity store, keyed by the application id; rows are mirrored as `decisions` / `adverse_actions` / `noias` /
 * `withdrawals` / `hmda_records` documents for 28.3 and the console). Every act goes through the pure rules in
 * src/domain/application/ops-21-6.ts. Guardrails encode the spec's sentences: never a denial, counteroffer or NOIA without
 * `reviewer_decided_at`; never a reason outside the taxonomy or a DU message / internal standard / score cutoff / prohibited
 * basis; never another applicant's score; never a discouraging statement; never silence as a withdrawal; never HMDA code 4
 * without an express withdrawal; the reviewer's decision is the `underwriting_reviewer`'s own act. The Colorado tools the
 * paragraph names (`sendAdmtExplanation`, `routeHumanReview`, `processCorrectionRequest`) are ops of assembleStateOverlays /
 * deliverNotice (agents.json names twelve tools for 21.6).
 */
import { defineTools, compute, decision, never, needsRole, str, flag, num, type ToolDef, type ToolInput, type ToolRuntime } from "../tools.ts";
import type { CommandContext } from "../commands.ts";
import { plainDate as D } from "../../kernel/calendar/date.ts";
import type { Recipient } from "../../notices/channel.ts";
import { cancelLock as cancelLock21_4, type Lock, type CancelReason } from "../../domain/application/ops-21-4.ts";
import { type DecisionFile, type DecisionFactor, type FcraBlock, type PrincipalReason, type ScoreInput, newDecisionFile, computeCompletion, trackDecisionClock, onDecisionClockBreached, recommendDisposition, selectPrincipalReasons, assembleFcraBlock, assembleStateOverlays, reviewDecision, adverseNoticePayloads, counterofferNoticePayload, noiaNoticePayload, deliverAdverseNotice, deliverNoia, deliverAdverseAfterCounteroffer, blockDiscouragingExplanation, recordHmdaAction, hmdaActionFor, recordWithdrawal, respondNoia, closeIncomplete, acceptCounteroffer, expireCounteroffer, recordConditionalApproval, conditionalApprovalFallout, requestHumanReview, completeHumanReview, sendAdmtExplanation, recordPreuseNoticeDelivered, silenceAssessment, decisionRecord, decisionOf, civilDate, PROHIBITED_REASON_PATTERNS, NOTICE_CODES_21_6, RULE_SET_VERSION_21_6 } from "../../domain/application/ops-21-6.ts";

const KIND = "application_decisions";
/** Missing-input guard: a tool executed without its subject refuses with a RangeError (never a TypeError). */
const need = (i: ToolInput, ...keys: string[]): void => { const gaps = keys.filter((k) => i[k] === undefined || i[k] === null || i[k] === ""); if (gaps.length) throw new RangeError(`21.6 tool needs ${gaps.join(", ")}`); };
const appId = (i: ToolInput, ctx: CommandContext): string => { const id = str(i, "application_id") || ctx.applicationId || ""; if (!id) throw new RangeError("21.6 tool needs application_id (or an application-scoped command context)"); return id; };
/** The decision file: opened from the application facts on first use (`partner_name`, `partner_address`, `application_date`, `property_state`, `applicants`). */
const load = (i: ToolInput, ctx: CommandContext, rt: ToolRuntime): DecisionFile => {
  const id = appId(i, ctx); const r = rt.store.get(KIND, id); if (r) return r.data as unknown as DecisionFile;
  need(i, "partner_name", "partner_address", "application_date", "property_state", "applicants");
  return newDecisionFile({ application_id: id, partner_name: str(i, "partner_name"), partner_address: str(i, "partner_address"), federal_agency: (i.federal_agency as "ftc" | "cfpb" | undefined) ?? "ftc", creditor_time_zone: str(i, "creditor_time_zone") || "America/New_York", application_date: str(i, "application_date"), property_state: str(i, "property_state"), consumer_state: (i.consumer_state as string | undefined) ?? null,
    applicants: i.applicants as DecisionFile["applicants"], ...(i.admt_materially_influenced !== undefined ? { admt_materially_influenced: flag(i, "admt_materially_influenced") } : {}), lock_id: (i.lock_id as string | undefined) ?? null, original_terms: (i.original_terms as DecisionFile["original_terms"] | undefined) ?? null });
};
const save = (rt: ToolRuntime, ctx: CommandContext, f: DecisionFile): DecisionFile => {
  const rec = rt.store.put(KIND, f.application_id, f as unknown as Record<string, unknown>, ctx.actor, ctx.now).data as unknown as DecisionFile;
  for (const d of f.decisions) rt.store.put("decisions", d.decision_id, d as unknown as Record<string, unknown>, ctx.actor, ctx.now);
  for (const a of f.adverse_actions) rt.store.put("adverse_actions", a.adverse_action_id, a as unknown as Record<string, unknown>, ctx.actor, ctx.now);
  for (const n of f.noias) rt.store.put("noias", n.noia_id, n as unknown as Record<string, unknown>, ctx.actor, ctx.now);
  for (const w of f.withdrawals) rt.store.put("withdrawals", w.withdrawal_id, w as unknown as Record<string, unknown>, ctx.actor, ctx.now);
  if (f.hmda && rt.store.get("hmda_records", f.application_id)?.data.action_taken !== f.hmda.action_taken) rt.store.put("hmda_records", f.application_id, { application_id: f.application_id, ...f.hmda }, ctx.actor, ctx.now);
  return rec;
};
const at = (i: ToolInput, ctx: CommandContext, key = "at"): string => str(i, key) || ctx.now;
const recipients = (f: DecisionFile, applicantId?: string): Recipient[] => f.applicants.filter((a) => !applicantId || a.id === applicantId).map((a) => ({ partyId: a.id, name: a.name, mailingAddress: a.mailing_address, ...(a.email ? { email: a.email } : {}), ...(a.esign_consent ? { consent: { party_id: a.id, classes: ["origination_decisions"], disclosure_version: "esign-2026-09", status: "active", consented_on: D("2026-10-05"), soft_bounces_30d: 0 } as NonNullable<Recipient["consent"]> } : {}) }));
const fcraBlocks = (i: ToolInput): FcraBlock[] => (Array.isArray(i.fcra_blocks) ? (i.fcra_blocks as FcraBlock[]) : Array.isArray(i.score_payloads) ? (i.score_payloads as ScoreInput[]).map(assembleFcraBlock) : []);
const noticeIds = (i: ToolInput, f: DecisionFile): Record<string, string> => { const ids = (i.notice_ids as Record<string, string> | undefined) ?? {}; if (Object.keys(ids).length) return ids; if (typeof i.notice_id === "string") return Object.fromEntries(f.applicants.map((a) => [a.id, i.notice_id as string])); return ids; };
const hasProhibited = (s: unknown): boolean => typeof s === "string" && PROHIBITED_REASON_PATTERNS.some((p) => p.test(s));

export const TOOLS_21_6: readonly ToolDef[] = defineTools("21.6", "underwriter", [
  // Rule 1: legal completion (§1002.2(f)) from the regularly-obtained items; the day-20 checkpoint fact arms REGB_1002_9_NOIA while anything is outstanding.
  { name: "computeCompletion", kind: "write", handler: compute((i, ctx, rt) => { const f = load(i, ctx, rt); const r = computeCompletion(ctx.events, f, { received: (i.received as Parameters<typeof computeCompletion>[2]["received"] | undefined) ?? {}, as_of: at(i, ctx, "as_of") }); save(rt, ctx, r.file);
      return { completed_application_at: r.completed_application_at, outstanding: r.outstanding, checkpoint_day: r.checkpoint_day, decision_due_on: r.file.decision_due_on, binding_clock: "conservative", noia_checkpoint_reached: r.checkpoint_day >= 20 && r.outstanding.length > 0 }; }) },
  // Rule 1 / T1: the conservative 30-day clock, the 90-day counteroffer clock, the Colorado explanation clock; `op=breach` logs the incident (sev 1 → compliance-sentinel + officer); `op=silence` is the T9 assessment (never a withdrawal).
  { name: "trackDecisionClock", kind: "act", handler: compute((i, ctx, rt) => { const f = load(i, ctx, rt); const now = at(i, ctx, "now");
      if (i.op === "breach") { const r = onDecisionClockBreached(ctx.events, rt.escalations, f, now); return { incident_id: r.incident_id, escalation_id: r.escalation.id, escalated_to: r.escalated_to, severity: 1 }; }
      if (i.op === "silence") return silenceAssessment(f, now);
      return trackDecisionClock(f, now); }) },
  // Rules 3–4 / state machine: the disposition from the factor results (never the DU message); adverse kinds open the `underwriting_reviewer` escalation with the one-screen package; 22.1's `needs_list.noia.recommended` payload is accepted as `noia_recommendation`.
  { name: "recommendDisposition", kind: "act", handler: compute((i, ctx, rt) => { need(i, "decision_id"); const f = load(i, ctx, rt); const rec = i.noia_recommendation as { missing?: { request_id?: string; doc_class: string; reason_text: string }[]; response_period_days?: number } | undefined;
      const missing = (i.missing_items as { item: string; description: string }[] | undefined) ?? rec?.missing?.map((m) => ({ item: m.doc_class, description: m.reason_text })) ?? [];
      const r = recommendDisposition(ctx.events, rt.escalations, f, { decision_id: str(i, "decision_id"), factors: (i.factors as DecisionFactor[] | undefined) ?? [], du_recommendation: (i.du_recommendation as Parameters<typeof recommendDisposition>[3]["du_recommendation"]) ?? null, data_verified_and_resubmitted: flag(i, "data_verified_and_resubmitted"), counteroffer_terms: (i.counteroffer_terms as Parameters<typeof recommendDisposition>[3]["counteroffer_terms"]) ?? null, missing_items: missing, at: at(i, ctx), ...(i.data_sufficient !== undefined ? { data_sufficient: flag(i, "data_sufficient") } : {}) });
      save(rt, ctx, r.file); return { decision_id: r.decision.decision_id, kind: r.kind, basis_component: r.decision.basis_component, escalation_id: r.escalation?.id ?? null, sla_due_on: r.sla_due_on, decision_due_on: r.file.decision_due_on, disposition: r.file.disposition }; }),
    guardrails: [never("DU_MESSAGE_NOT_A_REASON", "21.6 rule 4 / B3-2-11: DU recommendations and messages are inputs, never reasons", (i) => Array.isArray(i.factors) && (i.factors as DecisionFactor[]).some((x) => hasProhibited(x.description) || hasProhibited(x.rule_id)), "a factor described by a DU message, an internal standard, a score cutoff or a prohibited basis is refused"),
      never("SILENCE_NOT_A_DISPOSITION", "21.6 rule 8 / T9: 'no response for 21 days' is not a withdrawal — NOIA (if incomplete) or approval expiry", (i) => flag(i, "silence_as_withdrawal"), "silence is never recorded as a withdrawal; send the NOIA by day 30 or deny for incompleteness only where the data are insufficient")] },
  // Rule 3: the principal reasons from the failed factors — ordered by materiality, at most four, every principal factor, automatic factors always, taxonomy text only.
  { name: "selectPrincipalReasons", kind: "read", handler: compute((i) => { need(i, "factors"); const reasons = selectPrincipalReasons(i.factors as DecisionFactor[], { ...(i.max !== undefined ? { max: num(i, "max") } : {}), reviewer_signed_other_text: flag(i, "reviewer_signed_other_text") });
      return { principal_reasons: reasons, hmda_denial_codes: [...new Set(reasons.map((r) => r.hmda_denial_code))].slice(0, 4), count: reasons.length }; }),
    guardrails: [never("REASON_OUTSIDE_TAXONOMY", "21.6 guardrails: never state a reason that is not a failed factor in decision_factors; the renderer refuses free text outside the taxonomy except other_specific with reviewer sign-off", (i) => typeof i.free_text === "string" && !flag(i, "reviewer_signed_other_text"), "free-text reasons need the underwriting_reviewer's sign-off"),
      never("PROHIBITED_REASON", "12 CFR 1002.9(b)(2); comments 9(b)(2)-4/-9; §1002.4(b)", (i) => hasProhibited(i.free_text), "'DU Refer with Caution', 'internal standards', a score cutoff or a prohibited basis is never a reason")] },
  // Rule 5: one FCRA block per applicant from 22.2's score-disclosure payload (only that applicant's representative score, ≤ 4 key factors or 5 with inquiries, score date, provider, every CRA that furnished a report).
  { name: "assembleFcraBlock", kind: "read", handler: compute((i) => { if (Array.isArray(i.score_payloads)) return { fcra_blocks: (i.score_payloads as ScoreInput[]).map(assembleFcraBlock) }; need(i, "borrower_id", "scores", "range", "date", "score_model"); return { fcra_blocks: [assembleFcraBlock(i as unknown as ScoreInput)] }; }),
    guardrails: [never("ONE_APPLICANTS_SCORE", "21.6 guardrails: never disclose one applicant's score to another (FCRA duties run to each consumer; Reg V §1022.75(c) analogue)", (i) => flag(i, "include_other_applicants") || flag(i, "share_representative_score"), "each applicant's notice carries only that applicant's score")] },
  // Rule 7: the Federal agency block and the Colorado ADMT content; `op=human_review_request|correction_request|human_review_complete|correction_complete|preuse_delivered` are the SB 26-189 routes (routeHumanReview / processCorrectionRequest).
  { name: "assembleStateOverlays", kind: "act", handler: compute((i, ctx, rt) => { const when = at(i, ctx);
      if (i.op === "preuse_delivered") { need(i, "application_id", "notice_id", "state"); const e = recordPreuseNoticeDelivered(ctx.events, { application_id: appId(i, ctx), notice_id: str(i, "notice_id"), delivered_at: when, state: str(i, "state"), public_notice_url: str(i, "public_notice_url") || "https://partner.example/colorado-admt-notice" }, ctx.actor); return { delivered: true, event_id: e.id, template: NOTICE_CODES_21_6.co_admt, variant: "pre_use" }; }
      const f = load(i, ctx, rt);
      if (i.op === "human_review_request" || i.op === "correction_request") { need(i, "decision_id"); const r = requestHumanReview(ctx.events, f, { decision_id: str(i, "decision_id"), requested_at: when, kind: i.op === "correction_request" ? "correction" : "human_review", request_text: (i.request_text as string | undefined) ?? null }); save(rt, ctx, r.file); return { due_on: r.due_on, kind: i.op }; }
      if (i.op === "human_review_complete" || i.op === "correction_complete") { need(i, "decision_id", "outcome"); const r = completeHumanReview(ctx.events, f, { decision_id: str(i, "decision_id"), kind: i.op === "correction_complete" ? "correction" : "human_review", reviewer: ctx.actor, completed_at: when, outcome: str(i, "outcome"), data_changed: flag(i, "data_changed") }); save(rt, ctx, r.file); return { completed: true, redecision_required: r.redecision_required, reviewer_id: ctx.actor.id }; }
      const decided_on = typeof i.decided_on === "string" ? D(i.decided_on) : civilDate(when, f.creditor_time_zone);
      const o = assembleStateOverlays(f, decided_on, { preuse_notice_id: (i.preuse_notice_id as string | undefined) ?? null });
      return { federal_agency: o.federal_agency, colorado_consumer: o.colorado_consumer, co_duties_apply: o.co_duties_apply, explanation_due_on: o.co_admt?.explanation_due_on ?? null, admt_role_description: o.admt_role_description, human_review_instructions: o.human_review_instructions, correction_instructions: o.correction_instructions, overlays: o.overlays }; }),
    guardrails: [needsRole("SECOND_REVIEWER_IS_HUMAN", "21.6 rule 7: human review is performed by an underwriting_reviewer different from the one who approved the decision (6-1-1705(1)(a)(ii))", (i) => i.op === "human_review_complete" || i.op === "correction_complete", ["underwriting_reviewer"], "the Colorado human review is a named underwriting_reviewer's own act")] },
  // Automation class (b): every denial, counteroffer and NOIA is approved by the `underwriting_reviewer` (`op=decide` is the reviewer's own act; the escalation itself opens in recommendDisposition); `op=officer` re-prioritises a clock at risk.
  { name: "openReviewerEscalation", kind: "act", handler: compute((i, ctx, rt) => { const f = load(i, ctx, rt); const when = at(i, ctx);
      if (i.op === "decide") { need(i, "decision_id", "outcome"); const r = reviewDecision(ctx.events, rt.escalations, f, { decision_id: str(i, "decision_id"), outcome: str(i, "outcome") as "approved" | "returned", reviewer: ctx.actor, at: when, changes: (i.changes as Parameters<typeof reviewDecision>[3]["changes"]) ?? [], notes: (i.notes as string | undefined) ?? null }); save(rt, ctx, r.file); return { decision_id: r.decision.decision_id, outcome: r.decision.reviewer_outcome, reviewer_id: r.decision.reviewer_id, reviewer_decided_at: r.decision.reviewer_decided_at, decided_at: r.decision.decided_at }; }
      if (i.op === "officer") { const e = rt.escalations.open({ kind: "officer", applicationId: f.application_id, payload: { reason: "decision_clock_at_risk", decision_due_on: f.decision_due_on, at_risk_on: trackDecisionClock(f, when).at_risk_on } }, ctx.actor); return { escalation_id: e.id, owner_role: e.ownerRole }; }
      need(i, "decision_id"); const d = decisionOf(f, str(i, "decision_id")); if (d.reviewer_escalation_id) return { escalation_id: d.reviewer_escalation_id, owner_role: "underwriting_reviewer", sla_due_on: d.reviewer_sla_due_on, already_open: true };
      const e = rt.escalations.open({ kind: "underwriting_reviewer", applicationId: f.application_id, payload: { decision_id: d.decision_id, kind: d.kind, factors: d.decision_factors } }, ctx.actor); save(rt, ctx, { ...f, decisions: f.decisions.map((x) => (x.decision_id === d.decision_id ? { ...x, reviewer_escalation_id: e.id } : x)) }); return { escalation_id: e.id, owner_role: e.ownerRole, sla_due_on: d.reviewer_sla_due_on, already_open: false }; }),
    guardrails: [needsRole("REVIEWER_DECIDES", "21.6 automation class (b): the underwriting_reviewer must approve every denial, counteroffer and NOIA before the notice issues (baseline §8.2; LL-2026-04)", (i) => i.op === "decide", ["underwriting_reviewer"], "the review decision is the underwriting_reviewer's own act")] },
  // Rules 3, 5, 6, 7: per-applicant rendering through the Notice Registry — `NTC_REGB_1002_9_ADVERSE_ACTION` (one per applicant, FCRA block individualised), `NTC_REGB_1002_9_COUNTEROFFER` (C-4) or `NTC_REGB_1002_9_NOIA` (C-6) by the decision's kind.
  { name: "renderNotice", kind: "act", handler: compute((i, ctx, rt) => { need(i, "decision_id"); const f = load(i, ctx, rt); const svc = rt.notices; if (!svc) throw new RangeError("the Notice Registry is not wired into this runtime"); const d = decisionOf(f, str(i, "decision_id")); const asOf = D(str(i, "as_of") || ctx.now.slice(0, 10)); const notice_date = typeof i.notice_date === "string" ? D(i.notice_date) : civilDate(ctx.now, f.creditor_time_zone);
      if (d.kind === "incomplete") { need(i, "noia_id", "items_needed"); const noia = { noia_id: str(i, "noia_id"), application_id: f.application_id, decision_id: d.decision_id, items_needed: i.items_needed as { item: string; description: string }[], designated_period_days: i.designated_period_days !== undefined ? num(i, "designated_period_days") : 14, sent_at: null, sent_on: null, response_due_on: null, oral_request_at: (i.oral_request_at as string | undefined) ?? null, responded_at: null, closed_at: null };
        const n = svc.render({ templateCode: NOTICE_CODES_21_6.noia, loanId: ctx.loanId, recipients: recipients(f, (f.applicants.find((a) => a.primary) ?? f.applicants[0]!).id), payload: noiaNoticePayload(f, noia, notice_date), asOf }); return { template: NOTICE_CODES_21_6.noia, notice_ids: { [(f.applicants.find((a) => a.primary) ?? f.applicants[0]!).id]: n.id }, checklist_passed: n.checklist.passed }; }
      if (d.kind === "counteroffer") { const payload = counterofferNoticePayload(f, { decision_id: d.decision_id, notice_date, fcra_blocks: fcraBlocks(i), combined_notice: i.combined_notice !== false, reviewer_signed_other_text: flag(i, "reviewer_signed_other_text") }); const primary = f.applicants.find((a) => a.primary) ?? f.applicants[0]!;
        const n = svc.render({ templateCode: NOTICE_CODES_21_6.counteroffer, loanId: ctx.loanId, recipients: recipients(f, primary.id), payload, asOf }); return { template: NOTICE_CODES_21_6.counteroffer, notice_ids: { [primary.id]: n.id }, combined_notice: i.combined_notice !== false, checklist_passed: n.checklist.passed }; }
      const out: Record<string, string> = {}; let passed = true;
      for (const p of adverseNoticePayloads(f, { decision_id: d.decision_id, notice_date, fcra_blocks: fcraBlocks(i), reviewer_signed_other_text: flag(i, "reviewer_signed_other_text") })) { const n = svc.render({ templateCode: NOTICE_CODES_21_6.adverse_action, loanId: ctx.loanId, recipients: recipients(f, p.applicant_id), payload: p.payload, asOf }); out[p.applicant_id] = n.id; passed = passed && n.checklist.passed; }
      return { template: NOTICE_CODES_21_6.adverse_action, notice_ids: out, per_applicant: Object.keys(out).length, checklist_passed: passed }; }),
    guardrails: [never("REASON_OUTSIDE_TAXONOMY", "21.6 guardrails: the renderer refuses free text outside the taxonomy", (i) => hasProhibited(i.free_text) || (typeof i.free_text === "string" && !flag(i, "reviewer_signed_other_text")), "borrower-facing reason text comes from rule_sets.ecoa_reasons only")] },
  // T3 / T12 / rule 6: the notice sends only after the reviewer's decision (`approved_by_reviewer_at` precedes `sent_at`); the LLM's borrower explanation passes the §1002.4(b) discouragement check first; `op=noia`, `op=after_counteroffer`, `op=admt_explanation` (sendAdmtExplanation) are the other sends.
  { name: "deliverNotice", kind: "act", handler: compute(async (i, ctx, rt) => { need(i, "decision_id"); const f = load(i, ctx, rt); const when = at(i, ctx, "sent_at"); const ids = noticeIds(i, f);
      if (typeof i.borrower_explanation === "string") { const b = blockDiscouragingExplanation(ctx.events, rt.escalations, f, { decision_id: str(i, "decision_id"), text: i.borrower_explanation, at: when, prompt_version: (i.prompt_version as string | undefined) ?? ctx.run?.promptVersion ?? null }); if (b.blocked) return { sent: false, blocked: true, findings: b.findings, routed_to: "compliance-sentinel", escalation_id: b.escalation!.id, notice_text_affected: false }; }
      const send = async () => { if (!rt.notices) return; for (const id of new Set(Object.values(ids))) { try { await rt.notices.send(id, (i.channel_context as Parameters<NonNullable<ToolRuntime["notices"]>["send"]>[1] | undefined) ?? {}); } catch (e) { if (!(e instanceof RangeError && /^no notice /.test(e.message))) throw e; } } };   // an id the registry did not render is a document id from the print path (evidence retained by 21.3's delivery machinery)
      if (i.op === "noia") { need(i, "noia_id", "items_needed"); const primary = (f.applicants.find((a) => a.primary) ?? f.applicants[0]!).id; const r = deliverNoia(ctx.events, f, { decision_id: str(i, "decision_id"), noia_id: str(i, "noia_id"), sent_at: when, notice_id: ids[primary] ?? str(i, "notice_id"), items_needed: i.items_needed as { item: string; description: string }[], ...(i.designated_period_days !== undefined ? { designated_period_days: num(i, "designated_period_days") } : {}), oral_request_at: (i.oral_request_at as string | undefined) ?? null }); await send(); save(rt, ctx, r.file); return { sent: true, noia_id: r.noia.noia_id, sent_on: r.noia.sent_on, response_due_on: r.noia.response_due_on, disposition: r.file.disposition }; }
      if (i.op === "after_counteroffer") { const r = deliverAdverseAfterCounteroffer(ctx.events, f, { decision_id: str(i, "decision_id"), sent_at: when, notice_ids: ids }); await send(); save(rt, ctx, r.file); return { sent: true, hmda: r.hmda, disposition: r.file.disposition }; }
      if (i.op === "admt_explanation") { need(i, "notice_id"); const r = sendAdmtExplanation(ctx.events, f, { decision_id: str(i, "decision_id"), notice_id: str(i, "notice_id"), sent_at: when }); await send(); save(rt, ctx, r.file); return { sent: true, template: NOTICE_CODES_21_6.co_admt, variant: "adverse_outcome_explanation" }; }
      const r = deliverAdverseNotice(ctx.events, f, { decision_id: str(i, "decision_id"), sent_at: when, notice_ids: ids, fcra_blocks: fcraBlocks(i), combined_notice: i.combined_notice !== false, co_explanation_embedded: i.co_explanation_embedded !== false, ...(typeof i.expires_on === "string" ? { expires_on: D(i.expires_on) } : {}), reviewer_signed_other_text: flag(i, "reviewer_signed_other_text") }); await send(); save(rt, ctx, r.file);
      return { sent: true, kind: r.decision.kind, approved_by_reviewer_at: r.adverse_action.approved_by_reviewer_at, sent_at: r.adverse_action.sent_at, combined_notice: r.decision.combined_notice, hmda: r.file.hmda, disposition: r.file.disposition, co_explanation_sent_at: r.adverse_action.co_admt?.explanation_sent_at ?? null, lock_cancellation_reason: r.decision.kind === "denial" ? "lender_declination" : null }; }),
    guardrails: [never("REVIEWER_REQUIRED", "21.6 guardrails: never send a denial, counteroffer or NOIA without reviewer_decided_at", (i) => i.reviewer_decided_at === null || flag(i, "skip_reviewer"), "the underwriting_reviewer's approval precedes every adverse notice"),
      never("NEVER_DISCOURAGE", "12 CFR 1002.4(b): never a statement that would cause a reasonable person to believe the creditor would deny or grant less favorable terms because of a prohibited-basis characteristic", (i) => flag(i, "discouraging_statement"), "the borrower-facing explanation is refused; the taxonomy notice text is unaffected")] },
  // Rule 2: the same-transaction HMDA write for a terminal disposition (28.3's store): action taken, date and denial reasons from the mapping; code 4 never without `withdrawals.express=true`.
  { name: "recordHmdaAction", kind: "write", handler: compute((i, ctx, rt) => { const f = load(i, ctx, rt); if (i.op === "map") { need(i, "case"); return hmdaActionFor(i.case as Parameters<typeof hmdaActionFor>[0]); }
      if (f.hmda && !i.case) return { ...f.hmda, already_recorded: true };
      need(i, "case"); const fields = hmdaActionFor(i.case as Parameters<typeof hmdaActionFor>[0]); const r = recordHmdaAction(ctx.events, f, fields, at(i, ctx), (i.decision_id as string | undefined) ?? null); save(rt, ctx, r.file); return { ...fields, already_recorded: false }; }),
    guardrails: [never("HMDA_4_NEEDS_EXPRESS_WITHDRAWAL", "21.6 guardrails / comment 4(a)(8)(i)-5: never report HMDA code 4 without an express withdrawal", (i) => { const c = i.case as { kind?: string; express?: boolean } | undefined; return c?.kind === "withdrawal" && c.express !== true; }, "code 4 requires withdrawals.express=true")] },
  // Rule 9 (21.4): denial or closure → `lock.cancelled{lender_declination}`; withdrawal → `lock.cancelled{borrower_withdrawal}`; both without pair-off (C2-1.2-02) — 21.4's cancelLock over the `locks` document.
  { name: "cancelLock", kind: "act", handler: compute((i, ctx, rt) => { const f = load(i, ctx, rt); const lock_id = str(i, "lock_id") || f.lock_id || ""; if (!lock_id) throw new RangeError("21.6 cancelLock needs lock_id (or a lock on the decision file)");
      const lock = rt.store.require("locks", lock_id).data as unknown as Lock;
      const reason: CancelReason = (str(i, "reason") as CancelReason) || (f.disposition === "withdrawn" || f.disposition === "closed_incomplete" || f.disposition === "approved_not_accepted" ? "borrower_withdrawal" : "lender_declination");
      const r = cancelLock21_4(ctx.events, ctx.ledger, lock, { reason, at: at(i, ctx), lock_fee_ledger_set_id: (i.lock_fee_ledger_set_id as string | undefined) ?? null, detail: `21.6 ${f.disposition}` }, ctx.actor); rt.store.put("locks", r.lock.lock_id, { ...r.lock }, ctx.actor, ctx.now);
      return { lock_id: r.lock.lock_id, reason, status: r.lock.status, refund_set_id: r.refund?.id ?? null, pair_off: false }; }),
    guardrails: [never("WITHDRAWAL_REASON_NEEDS_EXPRESS", "21.6 rule 8/9: a lock is cancelled as borrower_withdrawal only on an express withdrawal (or the borrower-class fallout of a closed-incomplete file)", (i) => str(i, "reason") === "borrower_withdrawal" && flag(i, "silence"), "silence is never a withdrawal")] },
  // The decision row / agent decision record and the borrower-driven state changes: `op=withdrawal` (T8), `noia_response`, `close_incomplete` (T5), `counteroffer_accept`, `counteroffer_expire` (T6/T7), `conditional_approval`, `fallout` (T13), default = the `agent_decisions` record.
  { name: "writeDecision", kind: "write", handler: compute((i, ctx, rt) => { const f = load(i, ctx, rt); const when = at(i, ctx);
      switch (i.op) {
        case "withdrawal": { need(i, "withdrawal_id", "statement_text", "channel"); const r = recordWithdrawal(ctx.events, f, { withdrawal_id: str(i, "withdrawal_id"), statement_text: str(i, "statement_text"), channel: str(i, "channel"), received_at: when, evidence_document_id: (i.evidence_document_id as string | undefined) ?? null }); save(rt, ctx, r.file); return { express: r.withdrawal.express, received_on: r.withdrawal.received_on, hmda: r.hmda, regb_notice_required: false, lock_cancellation_reason: r.lock_cancellation_reason, disposition: r.file.disposition }; }
        case "noia_response": { need(i, "noia_id"); const r = respondNoia(ctx.events, f, { noia_id: str(i, "noia_id"), responded_at: when, all_items: i.all_items !== false }); save(rt, ctx, r.file); return { responded_at: r.noia.responded_at, decision_due_on: r.decision_due_on }; }
        case "close_incomplete": { need(i, "noia_id"); const r = closeIncomplete(ctx.events, f, { noia_id: str(i, "noia_id"), as_of: when }); save(rt, ctx, r.file); return { closed_on: r.closed_on, hmda: r.hmda, regb_notice_required: false, disposition: r.file.disposition }; }
        case "counteroffer_accept": { need(i, "decision_id"); const r = acceptCounteroffer(ctx.events, f, { decision_id: str(i, "decision_id"), accepted_at: when, method: str(i, "method") || "esignature" }); save(rt, ctx, r.file); return { disposition: r.file.disposition, accepted_at: when }; }
        case "counteroffer_expire": { need(i, "decision_id"); const r = expireCounteroffer(ctx.events, f, { decision_id: str(i, "decision_id"), as_of: when }); save(rt, ctx, r.file); return { second_notice_required: r.second_notice_required, adverse_notice_due_on: r.adverse_notice_due_on, policy_send_on: r.policy_send_on, hmda: r.hmda, disposition: r.file.disposition }; }
        case "conditional_approval": { need(i, "approved_on", "expires_on", "open_conditions"); const next = recordConditionalApproval(f, { approved_on: str(i, "approved_on"), expires_on: str(i, "expires_on"), open_conditions: i.open_conditions as Parameters<typeof recordConditionalApproval>[1]["open_conditions"] }); save(rt, ctx, next); return { disposition: next.disposition, open_conditions: next.conditional_approval!.open_conditions }; }
        case "fallout": { need(i, "reason"); const r = conditionalApprovalFallout(ctx.events, f, { as_of: when, reason: str(i, "reason"), express_withdrawal: flag(i, "express_withdrawal"), withdrawal_statement: (i.withdrawal_statement as string | undefined) ?? null, reasons: (i.reasons as PrincipalReason[] | undefined) ?? [] }); save(rt, ctx, r.file); return { hmda: r.hmda, disposition: r.file.disposition }; }
        default: { need(i, "decision_id", "rationale"); const record = decisionRecord(f, str(i, "decision_id"), { rationale: str(i, "rationale"), confidence: i.confidence !== undefined ? num(i, "confidence") : 1, model_version: str(i, "model_version") || ctx.run?.modelVersion || "unversioned", prompt_version: str(i, "prompt_version") || ctx.run?.promptVersion || "unversioned" });
          decision()({ ...i, agent: "underwriter", action: `21.6 ${f.disposition}`, rule_set_version: RULE_SET_VERSION_21_6, subject: { kind: "application", id: f.application_id } }, ctx); rt.store.put("agent_decision_records", str(i, "decision_id"), record, ctx.actor, ctx.now); return { recorded: true, record }; }
      } }),
    guardrails: [never("SILENCE_NOT_WITHDRAWAL", "21.6 guardrails: never treat silence as withdrawal (comment 4(a)(8)(i)-5)", (i) => i.op === "withdrawal" && (flag(i, "silence") || str(i, "statement_text") === "" && i.statement_text !== undefined), "a withdrawal is recorded only from the borrower's express statement, captured verbatim")] },
]);
