/**
 * §24.5 process-owned tools — bus tools for 24.5 defined with `defineTools("24.5", <agent>, defs)` from
 * ../tools.ts. Every tool string must be one spec/registry/agents.json names for 24.5; src/app/tools.test.ts refuses
 * the rest. Spread by ./index.ts.
 *
 * The `title-closing` agent runs in application scope (ctx.applicationId or `application_id`). Rows live in the entity
 * store under `flood_determinations`, `insurance_requirements`, `insurance_policies`, `insurance_evidence`,
 * `insurance_deficiencies` and `escrow_line_seeds` (every write is a new version — the servicing tables 9.1/9.6 own are
 * written with the 24.5 columns at funding); every act goes through the pure rules in src/domain/property/ops-24-5.ts,
 * which append the events the 24.5 timers and the downstream processes (25.2, 26.1, 26.3, 29.3, 30.2, 30.3, 30.4,
 * servicing 9.1/9.6) consume. Guardrails encode the spec's sentences: never mark a policy adequate without the
 * carrier-rating check and mortgagee-clause check; never accept an NFIP policy without evidence of application and
 * premium at or before closing; never skip the notice on an SFHA loan; never set SFC 180 when any residential structure
 * is in an SFHA; never override the $50,000 / 5% / $2,500 tests; the partner `officer` for B7-3-05 "contact Fannie Mae"
 * peril questions and rating exceptions (SLA 2 business_days_creditor); `human_agent` on request.
 */
import { defineTools, compute, never, needsRole, str, flag, cents, noticeOps, type ToolDef, type ToolInput, type ToolRuntime } from "../tools.ts";
import type { CommandContext } from "../commands.ts";
import { plainDate as D, type PlainDate } from "../../kernel/calendar/date.ts";
import { addBusinessDays, creditor } from "../../kernel/calendar/business.ts";
import { orderFloodDetermination, receiveFloodDetermination, deliveryFloodData, deliverFloodNotice, acknowledgeFloodNotice, floodNoticePayload, floodNoticeGate, computeInsuranceRequirements, requestEvidence, receiveEvidence, confirmWithCarrier, carrierRatingTest, checkMortgageeClause, verifyHazardPolicy, verifyFloodCoverage, evaluateRcbap, verifyProjectInsurance, openDeficiency, clearDeficiency, floodRequirement, floodCoverageGate, hazardEvidenceGate, projectInsuranceGate, lolEnrolledGate, seedEscrowLines, handOffToServicing, writeDecision, civilDate, NOTICE_TEMPLATE, OFFICER_SLA_BUSINESS_DAYS, SFHDF_CONFIG_DEFAULT,
  type FloodDeterminationRecord, type SfhdfResult, type SfhdfConfig, type InsuranceRequirement, type RequirementInput, type EvidenceIntake, type EvidenceKind, type EvidenceRecipient, type OrigHazardPolicy, type OrigPolicyRow, type DeficiencyRow, type OrigDeficiencyKind, type FloodPolicyEvidence, type ProjectInsuranceInput, type EscrowSeedInput, type GateOutcome, type NoticeChannel } from "../../domain/property/ops-24-5.ts";
import type { CarrierRating } from "../../domain/insurance/hazard.ts";

const need = (i: ToolInput, ...keys: string[]): void => { const gaps = keys.filter((k) => i[k] === undefined || i[k] === null || i[k] === ""); if (gaps.length) throw new RangeError(`24.5 tool needs ${gaps.join(", ")}`); };
const appId = (i: ToolInput, ctx: CommandContext): string => { const id = str(i, "application_id") || ctx.applicationId || ""; if (!id) throw new RangeError("24.5 tool needs application_id (or an application-scoped command context)"); return id; };
const at = (i: ToolInput, ctx: CommandContext, key = "at"): string => str(i, key) || ctx.now;
const obj = <T>(i: ToolInput, key: string): T => { const f = i[key]; if (!f || typeof f !== "object") throw new RangeError(`24.5 tool needs ${key}`); return f as T; };
const dateOrNull = (v: unknown): PlainDate | null => (typeof v === "string" && v ? D(v.slice(0, 10)) : null);
const centsOrNull = (v: unknown): bigint | null => (v === undefined || v === null || v === "" ? null : cents(v));
const partnerOf = (i: ToolInput, rt: ToolRuntime, id: string): { legal_name: string; aliases?: readonly string[] } => { const p = i.partner as { legal_name?: string; aliases?: string[] } | undefined; const app = rt.store.get("applications", id)?.data; return { legal_name: p?.legal_name || (typeof app?.partner_legal_name === "string" ? app.partner_legal_name : "") || "[Partner]", ...(p?.aliases ? { aliases: p.aliases } : {}) }; };
const latest = <T>(rt: ToolRuntime, kind: string, applicationId: string, where: (d: Record<string, unknown>) => boolean = () => true): (T & { id?: string }) | null => { const rows = rt.store.list(kind, (d) => d.application_id === applicationId && where(d)); const r = rows.at(-1); return r ? ({ ...(r.data as unknown as T), id: r.id }) : null; };
const put = (rt: ToolRuntime, ctx: CommandContext, kind: string, id: string, row: object) => rt.store.put(kind, id, row as unknown as Record<string, unknown>, ctx.actor, ctx.now).data;
const determination = (rt: ToolRuntime, id: string): FloodDeterminationRecord => { const d = latest<FloodDeterminationRecord>(rt, "flood_determinations", id); if (!d) throw new RangeError("no flood_determinations row for the application (orderFloodDetermination first)"); return d; };
const openDefs = (rt: ToolRuntime, id: string, kinds: readonly string[]): string[] => rt.store.list("insurance_deficiencies", (d) => d.application_id === id && d.resolved_at === null && kinds.includes(String(d.kind))).map((r) => String(r.data.kind));
const sfhdfCfg = (i: ToolInput): SfhdfConfig => ({ ...SFHDF_CONFIG_DEFAULT, ...((i.sfhdf_config as Partial<SfhdfConfig> | undefined) ?? {}) });
const ratingsOf = (i: ToolInput, key = "ratings"): CarrierRating[] => (Array.isArray(i[key]) ? (i[key] as CarrierRating[]) : []);
const hazardPolicy = (i: ToolInput): OrigHazardPolicy => { const p = obj<Record<string, unknown>>(i, "policy"); need(p as ToolInput, "policy_id", "coverage_dwelling_cents", "coverage_basis", "coverage_form", "deductible_cents", "mortgagee_clause_text", "effective_date", "expiration_date", "evidence_document_id");
  return { ...(p as unknown as OrigHazardPolicy), policy_kind: (p.policy_kind as OrigHazardPolicy["policy_kind"] | undefined) ?? "hazard", coverage_dwelling_cents: cents(p.coverage_dwelling_cents), deductible_cents: cents(p.deductible_cents), first_year_premium_cents: cents(p.first_year_premium_cents), ratings: Array.isArray(p.ratings) ? (p.ratings as CarrierRating[]) : [], named_insureds: Array.isArray(p.named_insureds) ? (p.named_insureds as string[]) : [], evidence_kind: (p.evidence_kind as EvidenceKind | undefined) ?? "declarations", effective_date: D(String(p.effective_date)), expiration_date: D(String(p.expiration_date)),
    per_peril_deductibles: Array.isArray(p.per_peril_deductibles) ? (p.per_peril_deductibles as { peril: string; cents?: unknown; pct?: string }[]).map((d) => ({ peril: d.peril, ...(d.cents !== undefined ? { cents: cents(d.cents) } : {}), ...(d.pct !== undefined ? { pct: String(d.pct) } : {}) })) : [], premium_paid_through: dateOrNull(p.premium_paid_through) }; };
const floodPolicy = (i: ToolInput): FloodPolicyEvidence => { const p = obj<Record<string, unknown>>(i, "policy"); need(p as ToolInput, "policy_id", "building_coverage_cents", "deductible_cents", "mortgagee_clause_text", "evidence_document_id");
  return { ...(p as unknown as FloodPolicyEvidence), nfip: p.nfip !== false, building_coverage_cents: cents(p.building_coverage_cents), deductible_cents: cents(p.deductible_cents), applied_on: dateOrNull(p.applied_on), premium_paid_on: dateOrNull(p.premium_paid_on), effective_date: dateOrNull(p.effective_date), expiration_date: dateOrNull(p.expiration_date), annual_premium_cents: centsOrNull(p.annual_premium_cents), evidence_kind: (p.evidence_kind as EvidenceKind | undefined) ?? "flood_declarations", ...(Array.isArray(p.ratings) ? { ratings: p.ratings as CarrierRating[] } : {}) }; };
const gateFacts = (rt: ToolRuntime, id: string, i: ToolInput): Record<string, GateOutcome> => {
  const d = latest<FloodDeterminationRecord>(rt, "flood_determinations", id); const hz = latest<OrigPolicyRow>(rt, "insurance_policies", id, (r) => r.kind === "hazard"); const fl = latest<OrigPolicyRow>(rt, "insurance_policies", id, (r) => r.kind === "flood");
  const projectType = str(i, "project_type") || (typeof rt.store.get("applications", id)?.data.project_type === "string" ? String(rt.store.get("applications", id)!.data.project_type) : "detached");
  const projectVerified = rt.store.list("project_insurance_verifications", (r) => r.application_id === id && r.pass === true).length > 0;
  return { FDPA_4104A_FLOOD_NOTICE_GATE: (() => { const r = floodNoticeGate({ in_sfha: d?.in_sfha ?? false, consummation_date: dateOrNull(i.consummation_date) ?? dateOrNull(i.scheduled_consummation_date), effective_receipt_date: d?.notice_effective_receipt_date ?? null, short_period_reason: d?.notice_short_period_reason ?? null, acknowledged_on: d?.notice_acknowledged_at ? civilDate(d.notice_acknowledged_at) : null, purchase_contract_signed_after_determination_without_notice: flag(i, "purchase_contract_signed_after_determination_without_notice") }); return r.open ? { open: true } : { open: false, reason: r.reason ?? "closed" }; })(),
    FNMA_B7_3_06_FLOOD_COVERAGE_GATE: floodCoverageGate({ in_sfha: d?.in_sfha ?? false, flood_status: d?.status ?? null, flood_coverage_verified: fl?.status === "verified" || d?.status === "coverage_verified", open_flood_deficiencies: openDefs(rt, id, ["flood_none", "flood_insufficient", "flood_deductible", "nfip_not_applied_paid_at_closing", "private_flood_terms"]) }),
    FNMA_B7_3_02_HAZARD_EVIDENCE_GATE: hazardEvidenceGate({ hazard_status: hz?.status ?? null, effective_date: hz?.effective_date ?? null, disbursement_date: dateOrNull(i.disbursement_date), transaction_type: str(i, "transaction_type") || null, premium_paid_at_closing: hz?.premium_paid_at_closing ?? false, premium_on_cd: flag(i, "premium_on_cd"), rule_set: hz?.rule_set ?? null }),
    FNMA_B7_3_03_PROJECT_INSURANCE_GATE: projectInsuranceGate({ project_type: projectType, project_insurance_verified: projectVerified, open_project_deficiencies: openDefs(rt, id, ["master_lapse", "unit_policy_missing", "master_rcv_undocumented", "master_coverage_short", "master_form", "ho6_insufficient", "ho6_deductible_excess", "liability_missing", "fidelity_missing"]) }),
    FDPA_4012A_LOL_ENROLLED_GATE: lolEnrolledGate({ lol_purchased: d?.lol_purchased ?? false, lol_contract_linked: (d?.lol_contract_linked ?? false) || flag(i, "lol_contract_linked"), loan_id: str(i, "loan_id") || ctx_loan(i) || null, determination_present: !!d?.determination_date }) };
};
const ctx_loan = (i: ToolInput): string => str(i, "loan_id");
const SKIP_CHECKS = (i: ToolInput): boolean => flag(i, "skip_rating_check") || flag(i, "skip_mortgagee_check") || flag(i, "mark_adequate_without_checks");
const OVERRIDE_TESTS = (i: ToolInput): boolean => flag(i, "override_master_tests") || flag(i, "override_deductible_tests") || flag(i, "override_50000_cap") || flag(i, "override_ho6_deductible");

export const TOOLS_24_5: readonly ToolDef[] = defineTools("24.5", "title-closing", [
  // Inputs: the SFHDF ordered with the title order, life-of-loan always, after 21.4's `order_flood` fee gate (checkFeeGate result passed as fee_gate_result); the `flood` adapter is used when wired (idempotent by property).
  { name: "orderFloodDetermination", kind: "act", handler: compute(async (i, ctx, rt) => { const id = appId(i, ctx); need(i, "property_id", "address_hash");
      const r = orderFloodDetermination(ctx.events, { application_id: id, property_id: str(i, "property_id"), address_hash: str(i, "address_hash"), ordered_at: at(i, ctx, "ordered_at"), lol: true, fee_gate_result: (i.fee_gate_result as string | undefined) ?? null, vendor_id: (i.vendor_id as string | undefined) ?? null, ...(typeof i.sfhdf_form_version === "string" ? { sfhdf_form_version: i.sfhdf_form_version } : {}) }, ctx.actor, sfhdfCfg(i));
      put(rt, ctx, "flood_determinations", r.record.determination_id, r.record);
      const port = rt.ports.flood; let vendor: unknown = null;
      if (port && typeof i.address === "string") { const det = await port.orderDetermination(str(i, "property_id"), i.address, ctx.now); await port.enrollLifeOfLoan(det.certificateId); vendor = det; }
      return { determination_id: r.record.determination_id, status: r.record.status, lol: true, event: r.event.type, vendor }; }),
    guardrails: [never("FEE_GATE_BEFORE_FLOOD_ORDER", "21.4 fee gate precedes the flood order (`order_flood`); 12 CFR 1026.19(e)(2)(i)(A): no fee before intent to proceed", (i) => typeof i.fee_gate_result === "string" && i.fee_gate_result.startsWith("closed"), "the flood determination is ordered only after intent to proceed and the fee receipt (21.4 checkFeeGate order_flood)")] },
  // Rule 1 / T9 / T10: the vendor's determination_result parsed into the 24.5 outcome (SFHA per structure, SFC 180, non-participating → ineligible with a collateral reason); `op=delivery_data` for 29.3.
  { name: "parseSFHDF", kind: "act", ruleSetVersion: "fdpa.4012a", handler: compute((i, ctx, rt) => { const id = appId(i, ctx);
      if (i.op === "delivery_data") return deliveryFloodData(determination(rt, id));
      const sfhdf = obj<SfhdfResult>(i, "sfhdf"); const rec = determination(rt, id);
      const r = receiveFloodDetermination(ctx.events, rec, { ...sfhdf, map_date: dateOrNull(sfhdf.map_date), lol_purchased: sfhdf.lol_purchased !== false, sfhdf_form_version: sfhdf.sfhdf_form_version || SFHDF_CONFIG_DEFAULT.form_version }, at(i, ctx, "received_at"), ctx.actor, sfhdfCfg(i));
      put(rt, ctx, "flood_determinations", r.record.determination_id, r.record);
      if (r.stop) rt.escalations.open({ kind: "officer", ownerRole: "officer", applicationId: id, severity: "sev3", payload: { reason: r.stop.reason_code, basis: r.stop.basis, statement_text: r.stop.statement_text, notify: r.stop.notify, sla: `+${OFFICER_SLA_BUSINESS_DAYS} business_days_creditor` } }, ctx.actor);
      return { determination_id: r.record.determination_id, status: r.record.status, zone: r.record.zone, in_sfha: r.record.in_sfha, sfc_180: r.record.sfc_180, notice_required: r.record.notice_required, special_feature_codes: r.parsed.special_feature_codes, stop: r.stop, events: [r.event.type, ...(r.stop_event ? [r.stop_event.type] : [])] }; }),
    guardrails: [never("SFC_180_NEVER_IN_SFHA", "24.5 guardrails: 'never set SFC 180 when any residential structure is in an SFHA'; B7-3-06 SFC 180 'No Flood Insurance — Not a Special Flood Hazard Area'", (i) => flag(i, "force_sfc_180") || flag(i, "set_sfc_180"), "SFC 180 is derived from the SFHDF structures — it is never set by hand")] },
  // Rule 5: the NTC_FDPA_4104A_FLOOD_NOTICE payload from the determination (rendered through the Notice Registry when wired) — never skipped on an SFHA loan.
  { name: "renderFloodNotice", kind: "act", handler: compute((i, ctx, rt) => { const id = appId(i, ctx); const d = determination(rt, id); need(i, "borrower_names", "property_address");
      const payload = floodNoticePayload(d, { notice_date: dateOrNull(i.notice_date) ?? D(ctx.now.slice(0, 10)), partner_name: partnerOf(i, rt, id).legal_name, borrower_names: i.borrower_names as string[], property_address: str(i, "property_address"), loan_number_last4: str(i, "loan_number_last4") || id.slice(-4), escrow_required: flag(i, "escrow_required"), escrow_statement_applies: i.escrow_statement_applies === undefined ? true : flag(i, "escrow_statement_applies"), contact_phone: str(i, "contact_phone") || "1-800-555-0142", scheduled_consummation_date: dateOrNull(i.scheduled_consummation_date), language: str(i, "language") || "en" });
      if (!rt.notices) return { template_code: NOTICE_TEMPLATE, payload, rendered: false, esign_consent_scope: "flood_notice" };
      return { template_code: NOTICE_TEMPLATE, rendered: true, notice: noticeOps("render")({ template_code: NOTICE_TEMPLATE, payload, recipients: i.recipients, as_of: String(payload.notice_date) }, ctx, rt), esign_consent_scope: "flood_notice" }; }),
    guardrails: [never("FLOOD_NOTICE_NEVER_SKIPPED", "24.5 guardrails: 'never skip the notice on an SFHA loan (even where the statute may not literally bind the partner)'; 42 U.S.C. 4104a", (i) => flag(i, "skip_notice"), "the flood notice is delivered on every SFHA loan")] },
  // Rule 5 / T4: delivery with the effective-receipt computation (e-sign same day; mailbox rule for mail); `op=acknowledge` records the borrower's acknowledgment (short-period path with a reason).
  { name: "deliverNotice", kind: "act", handler: compute((i, ctx, rt) => { const id = appId(i, ctx); const d = determination(rt, id);
      if (i.op === "acknowledge") { const r = acknowledgeFloodNotice(ctx.events, d, { acknowledged_at: at(i, ctx, "acknowledged_at"), method: (i.method as "esign" | "wet" | "portal" | undefined) ?? "esign", short_period_reason: (i.short_period_reason as string | undefined) ?? null, before_signing: i.before_signing === undefined ? true : flag(i, "before_signing") }, ctx.actor); put(rt, ctx, "flood_determinations", d.determination_id, r.record); return { acknowledged_at: r.record.notice_acknowledged_at, effective_receipt_date: r.record.notice_effective_receipt_date, event: r.event.type }; }
      need(i, "channel", "notice_document_id");
      const r = deliverFloodNotice(ctx.events, d, { delivered_at: at(i, ctx, "delivered_at"), channel: str(i, "channel") as NoticeChannel, notice_document_id: str(i, "notice_document_id"), notice_id: (i.notice_id as string | undefined) ?? null, esign_confirmed_at: (i.esign_confirmed_at as string | undefined) ?? null, scheduled_consummation_date: dateOrNull(i.scheduled_consummation_date), esign_consent_scope: (i.esign_consent_scope as string | undefined) ?? null }, ctx.actor);
      put(rt, ctx, "flood_determinations", d.determination_id, r.record);
      if (i.notice_id && rt.notices) noticeOps("send")({ notice_id: i.notice_id, channel_context: i.channel_context }, ctx, rt);
      return { effective_receipt_date: r.effective_receipt_date, days_before_consummation: r.gate.days_before_consummation, reasonable_period_ok: r.gate.open, earliest_consummation: r.gate.earliest_consummation, status: r.record.status, event: r.event.type }; }),
    guardrails: [never("FLOOD_NOTICE_NEVER_SKIPPED", "24.5 guardrails: 'never skip the notice on an SFHA loan'", (i) => flag(i, "skip_notice"), "the flood notice is delivered on every SFHA loan")] },
  // Rule 1: the requirement record (9.1's engine) at DU findings / project review / flood determination; arms SM_INSURANCE_EVIDENCE_REQUEST_3BD.
  { name: "computeInsuranceRequirements", kind: "act", ruleSetVersion: "fnma.insurance.2026-08", handler: compute((i, ctx, rt) => { const id = appId(i, ctx); const f = obj<Record<string, unknown>>(i, "facts"); const prop = f.property as RequirementInput["property"] | undefined; const hz = f.hazard as { coverage_dwelling_cents: unknown; excludes_wind?: boolean } | undefined; if (!prop || !hz) throw new RangeError("24.5 computeInsuranceRequirements facts need property and hazard");
      const d = latest<FloodDeterminationRecord>(rt, "flood_determinations", id); const fl = f.flood as { rcv_improvements_cents?: unknown; note_amount_cents: unknown; in_sfha?: boolean } | undefined;
      const r = computeInsuranceRequirements(ctx.events, { application_id: id, computed_from: (f.computed_from as RequirementInput["computed_from"] | undefined) ?? "du_findings", computed_at: at(i, ctx, "computed_at"), property: { ...prop, units: Number(prop.units), master_per_unit_deductible_cents: centsOrNull(prop.master_per_unit_deductible_cents), ho6_restoration_estimate_cents: centsOrNull(prop.ho6_restoration_estimate_cents) }, hazard: { coverage_dwelling_cents: cents(hz.coverage_dwelling_cents), excludes_wind: hz.excludes_wind === true },
        flood: fl ? { in_sfha: fl.in_sfha ?? d?.in_sfha ?? false, rcv_improvements_cents: centsOrNull(fl.rcv_improvements_cents), note_amount_cents: cents(fl.note_amount_cents) } : null, fidelity: (f.fidelity as RequirementInput["fidelity"]) ?? null }, ctx.actor);
      put(rt, ctx, "insurance_requirements", r.requirement.requirement_id, r.requirement); return { requirement: r.requirement, event: r.event.type }; }) },
  // Rule 9 / SM_INSURANCE_EVIDENCE_REQUEST_3BD: the request to the borrower's agent / carrier / HOA (automation disclosed; 2-business-day follow-ups).
  { name: "requestEvidence", kind: "act", handler: compute((i, ctx, rt) => { const id = appId(i, ctx); need(i, "kinds"); const req = latest<InsuranceRequirement>(rt, "insurance_requirements", id); if (!req) throw new RangeError("no insurance_requirements row (computeInsuranceRequirements first)");
      const r = requestEvidence(ctx.events, req, { requested_at: at(i, ctx, "requested_at"), to: (i.to as EvidenceRecipient | undefined) ?? "borrower_agent", kinds: i.kinds as EvidenceKind[], channel: (i.channel as "email" | "portal" | "vendor" | "phone" | undefined) ?? "email", language: (i.language as string | undefined) ?? null }, ctx.actor); return { followup_due_on: r.followup_due_on, on_time_deadline: r.on_time_deadline, event: r.event.type }; }) },
  // Integrations (`insurance-tracking` adapter shared with 9.1): EOI extraction with field-level confidence; < 0.90 on any critical field → carrier confirmation required.
  { name: "extractEvidence", kind: "write", handler: compute((i, ctx, rt) => { const id = appId(i, ctx); need(i, "kind", "document_id");
      const r = receiveEvidence(ctx.events, { application_id: id, kind: str(i, "kind") as EvidenceKind, document_id: str(i, "document_id"), received_at: at(i, ctx, "received_at"), fields: (i.fields as Record<string, unknown> | undefined) ?? {}, confidence: (i.confidence as EvidenceIntake["confidence"] | undefined) ?? {}, policy_id: (i.policy_id as string | undefined) ?? null }, ctx.actor);
      put(rt, ctx, "insurance_evidence", r.evidence.evidence_id, r.evidence); return { evidence_id: r.evidence.evidence_id, status: r.evidence.status, confirmation_required: r.evidence.confirmation_required, event: r.event.type }; }) },
  // B7-3-01 / T12: the one-agency rating test (AM Best ≥ B, Demotech ≥ A, S&P/KBRA ≥ BBB) with the FAIR-plan / mortgage-impairment relief (a read).
  { name: "lookupCarrierRating", kind: "read", handler: compute((i) => { need(i, "ratings"); return carrierRatingTest(ratingsOf(i), { fair_plan: flag(i, "fair_plan"), fair_plan_only_coverage_available: i.fair_plan_only_coverage_available === undefined ? true : flag(i, "fair_plan_only_coverage_available"), mortgage_impairment_relief: flag(i, "mortgage_impairment_relief") }); }) },
  // Rule 4 (9.1) / edge: carrier or agent confirmation of low-confidence fields (AI voice / e-mail, disclosed) — never assumed.
  { name: "confirmWithCarrier", kind: "act", handler: compute((i, ctx, rt) => { const id = appId(i, ctx); need(i, "evidence_id", "fields_confirmed"); const ev = rt.store.get("insurance_evidence", str(i, "evidence_id"))?.data as unknown as EvidenceIntake | undefined; if (!ev || ev.application_id !== id) throw new RangeError(`no insurance_evidence ${str(i, "evidence_id")} for the application`);
      const r = confirmWithCarrier(ctx.events, ev, { confirmed_at: at(i, ctx, "confirmed_at"), confirmed_via: (i.confirmed_via as "carrier_api" | "agent_call" | "vendor" | "email" | undefined) ?? "agent_call", fields_confirmed: i.fields_confirmed as string[], contact: (i.contact as string | undefined) ?? null }, ctx.actor); put(rt, ctx, "insurance_evidence", ev.evidence_id, r.evidence); return { evidence_id: ev.evidence_id, status: r.evidence.status, event: r.event.type }; }) },
  // Rule 2 / T1–T3, T8, T12: hazard (default) or unit-owner adequacy → `insurance_policies` row verified/deficient; `op=project` rule 3 (master / HO-6 / liability / fidelity); `op=rcbap` the 80% rule.
  { name: "evaluateAdequacy", kind: "act", ruleSetVersion: "fnma.insurance.2026-08", moneyFields: ["coverage_dwelling_cents", "deductible_cents"], handler: compute((i, ctx, rt) => { const id = appId(i, ctx); const op = (i.op as string | undefined) ?? "hazard";
      if (op === "rcbap") { const f = obj<Record<string, unknown>>(i, "facts"); need(f as ToolInput, "units", "rcv_building_cents", "rcbap_coverage_cents", "unit_upb_cents"); return evaluateRcbap({ units: Number(f.units), rcv_building_cents: cents(f.rcv_building_cents), rcbap_coverage_cents: cents(f.rcbap_coverage_cents), unit_rcv_share_cents: centsOrNull(f.unit_rcv_share_cents), unit_upb_cents: cents(f.unit_upb_cents), supplemental_unit_policy_cents: centsOrNull(f.supplemental_unit_policy_cents) }); }
      if (op === "project") { const f = obj<ProjectInsuranceInput>(i, "facts"); if (!f.master || !f.application_date || !f.project_type) throw new RangeError("24.5 evaluateAdequacy op=project facts need application_date, project_type and master");
        const m = f.master; const norm: ProjectInsuranceInput = { ...f, application_id: id, application_date: D(String(f.application_date)), units_total: Number(f.units_total ?? 0), master: { ...m, rcv_cents: cents(m.rcv_cents), coverage_cents: cents(m.coverage_cents), deductible_cents: cents(m.deductible_cents), per_unit_deductible_cents: centsOrNull(m.per_unit_deductible_cents) }, ho6: f.ho6 ? { ...f.ho6, coverage_cents: cents(f.ho6.coverage_cents), deductible_cents: cents(f.ho6.deductible_cents), restoration_estimate_cents: centsOrNull(f.ho6.restoration_estimate_cents) } : null, liability: f.liability ? { ...f.liability, coverage_cents: cents(f.liability.coverage_cents) } : null, fidelity: f.fidelity ? { ...f.fidelity, coverage_cents: cents(f.fidelity.coverage_cents) } : null, fidelity_need_cents: centsOrNull(f.fidelity_need_cents) };
        const r = verifyProjectInsurance(ctx.events, norm, at(i, ctx, "verified_at"), ctx.actor); put(rt, ctx, "project_insurance_verifications", `piv-${id}-${rt.store.list("project_insurance_verifications").length + 1}`, { application_id: id, ...r.outcome, verified_at: at(i, ctx, "verified_at") }); for (const e of r.events) if (e.type === "insurance.deficiency.opened") put(rt, ctx, "insurance_deficiencies", String(e.payload.deficiency_id), { deficiency_id: e.payload.deficiency_id, application_id: id, policy_id: e.payload.policy_id, kind: e.payload.kind, stage: "origination", detected_at: e.payload.detected_at, resolved_at: null, resolution: null }); return { ...r.outcome, events: r.events.map((e) => e.type) }; }
      const p = hazardPolicy(i); const title = Array.isArray(i.title_holders) ? (i.title_holders as string[]) : p.named_insureds;
      if (flag(i, "contact_fannie_mae_peril")) rt.escalations.open({ kind: "officer", ownerRole: "officer", applicationId: id, payload: { reason: "B7-3-05: exposure to a peril not among the required perils — contact Fannie Mae", peril: i.peril ?? null, sla: `+${OFFICER_SLA_BUSINESS_DAYS} business_days_creditor` } }, ctx.actor);
      const r = verifyHazardPolicy(ctx.events, { application_id: id, policy: p, title_holders: title, partner: partnerOf(i, rt, id), evidence_confirmed: i.evidence_confirmed === undefined ? true : flag(i, "evidence_confirmed"), transaction_type: (i.transaction_type as "purchase" | "refinance" | undefined) ?? "refinance", disbursement_date: dateOrNull(i.disbursement_date), verified_at: at(i, ctx, "verified_at") }, ctx.actor);
      put(rt, ctx, "insurance_policies", r.row.policy_id, r.row); for (const e of r.events) if (e.type === "insurance.deficiency.opened") put(rt, ctx, "insurance_deficiencies", String(e.payload.deficiency_id), { deficiency_id: e.payload.deficiency_id, application_id: id, policy_id: r.row.policy_id, kind: e.payload.kind, stage: "origination", detected_at: e.payload.detected_at, resolved_at: null, resolution: null });
      return { policy_id: r.row.policy_id, status: r.status, deficiencies: r.deficiencies, tests: r.adequacy.tests, hazard_deductible_max_cents: r.adequacy.hazard_deductible_max_cents, deductible_pct: r.adequacy.deductible_pct, mortgagee_clause_check: r.adequacy.mortgagee_clause_check, rating: r.adequacy.rating, events: r.events.map((e) => e.type) }; }),
    guardrails: [never("ADEQUACY_NEEDS_RATING_AND_CLAUSE_CHECKS", "24.5 guardrails: 'never mark a policy adequate without the carrier-rating check and mortgagee-clause check'; B7-3-01 / B7-3-08", SKIP_CHECKS, "adequacy always runs the carrier-rating and mortgagee-clause tests"),
      never("MASTER_HO6_TESTS_NEVER_OVERRIDDEN", "24.5 guardrails: 'never override the $50,000/5%/$2,500 tests'; B7-3-03 / B7-3-04", OVERRIDE_TESTS, "the $50,000 per-unit, 5% and $2,500 tests cannot be overridden"),
      needsRole("RATING_EXCEPTION_IS_OFFICER", "24.5 escalations: `officer` for rating exceptions (SLA 2 business_days_creditor); B7-3-01 FAIR plan only when the only coverage available", (i) => flag(i, "rating_exception_approved") || flag(i, "fair_plan_acknowledged"), ["officer"], "a rating exception / FAIR-plan acknowledgment is the partner officer's")] },
  // Rule 7 / T8 (B7-3-08): the mortgagee-clause text test — partner + "its successors and/or assigns" + c/o Supermortgage, MERS absent, ATIMA optional (a read).
  { name: "checkMortgageeClause", kind: "read", handler: compute((i, ctx, rt) => { need(i, "clause_text"); return checkMortgageeClause(str(i, "clause_text"), partnerOf(i, rt, str(i, "application_id") || ctx.applicationId || "")); }) },
  // Rule 9: a deficiency row (stage origination) + ptf condition; `op=clear` with cured / waived_by_policy (officer acknowledgment) / withdrawn.
  { name: "openDeficiency", kind: "act", handler: compute((i, ctx, rt) => { const id = appId(i, ctx);
      if (i.op === "clear") { need(i, "deficiency_id", "resolution"); const row = rt.store.get("insurance_deficiencies", str(i, "deficiency_id"))?.data as unknown as DeficiencyRow | undefined; if (!row || row.application_id !== id) throw new RangeError(`no insurance_deficiencies ${str(i, "deficiency_id")} for the application`);
        const r = clearDeficiency(ctx.events, row, { resolved_at: at(i, ctx, "resolved_at"), resolution: str(i, "resolution") as "cured" | "waived_by_policy" | "withdrawn", evidence_document_id: (i.evidence_document_id as string | undefined) ?? null, officer_acknowledged_by: (i.officer_acknowledged_by as string | undefined) ?? null }, ctx.actor); put(rt, ctx, "insurance_deficiencies", row.deficiency_id, r.row); return { deficiency_id: row.deficiency_id, resolution: r.row.resolution, event: r.event.type }; }
      need(i, "kind"); const r = openDeficiency(ctx.events, { application_id: id, policy_id: (i.policy_id as string | undefined) ?? null, kind: str(i, "kind") as OrigDeficiencyKind, opened_at: at(i, ctx, "opened_at"), basis: (i.basis as Record<string, unknown> | undefined) ?? {}, condition: (i.condition as "ptf" | "ptd" | undefined) ?? "ptf" }, ctx.actor); put(rt, ctx, "insurance_deficiencies", r.row.deficiency_id, r.row); return { deficiency_id: r.row.deficiency_id, kind: r.row.kind, condition: r.row.condition, event: r.event.type }; }),
    guardrails: [needsRole("WAIVED_BY_POLICY_IS_OFFICER", "24.5 rule 9: waived_by_policy (FAIR plan / state cap) with `officer` acknowledgment", (i) => i.op === "clear" && str(i, "resolution") === "waived_by_policy" && !i.officer_acknowledged_by, ["officer"], "a policy waiver of an insurance deficiency needs the partner officer")] },
  // Rule 4 / T5: min(RCV, NFIP max, note amount) and the NFIP deductible cap (default op); `op=verify` the NFIP/private evidence against the closing date (44 CFR 61.11) → `flood.coverage.verified`.
  { name: "computeFloodAmount", kind: "act", ruleSetVersion: "nfip.44cfr61.2026", moneyFields: ["rcv_improvements_cents", "note_amount_cents"], handler: compute((i, ctx, rt) => {
      if (i.op === "verify") { const id = appId(i, ctx); need(i, "closing_date"); const d = determination(rt, id); const req = latest<InsuranceRequirement>(rt, "insurance_requirements", id);
        const amount = req?.flood_required_amount_cents ?? (i.rcv_improvements_cents !== undefined && i.note_amount_cents !== undefined ? floodRequirement({ rcv_improvements_cents: cents(i.rcv_improvements_cents), note_amount_cents: cents(i.note_amount_cents), units: Number(i.units ?? 1) }).flood_required_amount_cents : null); if (amount === null) throw new RangeError("no flood requirement on file (computeInsuranceRequirements, or pass rcv_improvements_cents and note_amount_cents)");
        const r = verifyFloodCoverage(ctx.events, d, floodPolicy(i), { flood_required_amount_cents: amount, flood_deductible_max_cents: req?.flood_deductible_max_cents ?? floodRequirement({ rcv_improvements_cents: amount, note_amount_cents: amount }).flood_deductible_max_cents }, { closing_date: D(str(i, "closing_date")), partner: partnerOf(i, rt, id), transaction_type: (i.transaction_type as "purchase" | "refinance" | undefined) ?? "refinance", verified_at: at(i, ctx, "verified_at") }, ctx.actor);
        put(rt, ctx, "flood_determinations", d.determination_id, r.record); put(rt, ctx, "insurance_policies", r.row.policy_id, r.row); for (const e of r.events) if (e.type === "insurance.deficiency.opened") put(rt, ctx, "insurance_deficiencies", String(e.payload.deficiency_id), { deficiency_id: e.payload.deficiency_id, application_id: id, policy_id: r.row.policy_id, kind: e.payload.kind, stage: "origination", detected_at: e.payload.detected_at, resolved_at: null, resolution: null });
        return { policy_id: r.row.policy_id, status: r.row.status, pass: r.adequacy.pass, deficiencies: r.adequacy.deficiencies, tests: r.adequacy.tests, required_cents: r.adequacy.required_cents, flood_status: r.record.status, events: r.events.map((e) => e.type) }; }
      need(i, "rcv_improvements_cents", "note_amount_cents"); return floodRequirement({ rcv_improvements_cents: cents(i.rcv_improvements_cents), note_amount_cents: cents(i.note_amount_cents), units: Number(i.units ?? 1) }); }),
    guardrails: [never("NFIP_NEEDS_APPLICATION_AND_PREMIUM_AT_CLOSING", "24.5 guardrails: 'never accept an NFIP policy without evidence of application and premium at or before closing'; 44 CFR 61.11(b)", (i) => flag(i, "accept_without_premium_evidence") || flag(i, "waive_premium_evidence"), "an NFIP policy is accepted only with the application and premium presentment at or before closing")] },
  // Timers table: every 24.5 gate over the stored rows (notice timing, flood coverage, hazard evidence, project insurance, LOL enrolment) — a read the consummate / disburse / boarding commands assert.
  { name: "evaluateGates", kind: "read", handler: compute((i, ctx, rt) => { const id = appId(i, ctx); const gates = gateFacts(rt, id, i); return { gates, all_open: Object.values(gates).every((g) => g.open), closed: Object.entries(gates).filter(([, g]) => !g.open).map(([k, g]) => ({ gate: k, reason: g.reason })) }; }) },
  // Rule 8 / T11: hazard / flood / HO-6 lines for 30.3 with the waivability rule (12 CFR 22.5 for a regulated lending institution; §1026.35(b) HPML; 24.5-Q3 otherwise); `op=handoff` the 9.1/9.6 rows at loan.funded (FDPA_4012A_LOL_ENROLLED_GATE).
  { name: "seedEscrowLines", kind: "act", handler: compute((i, ctx, rt) => { const id = appId(i, ctx);
      if (i.op === "handoff") { need(i, "loan_id"); const d = determination(rt, id); const policies = rt.store.list("insurance_policies", (r) => r.application_id === id).map((r) => r.data as unknown as OrigPolicyRow);
        const r = handOffToServicing(ctx.events, { application_id: id, loan_id: str(i, "loan_id"), funded_at: at(i, ctx, "funded_at"), determination: d, policies, lol_contract_linked: flag(i, "lol_contract_linked"), vendor_party_id: (i.vendor_party_id as string | undefined) ?? null }, ctx.actor);
        put(rt, ctx, "flood_determinations", d.determination_id, { ...d, loan_id: str(i, "loan_id"), lol_contract_linked: flag(i, "lol_contract_linked") }); return { flood_row: r.flood_row, policy_rows: r.policy_rows.map((p) => p.policy_id), gate: r.gate, warning: r.warning, event: r.event?.type ?? null }; }
      const d = latest<FloodDeterminationRecord>(rt, "flood_determinations", id); const pol = (kind: "hazard" | "flood" | "ho6") => { const p = (i[kind] as Record<string, unknown> | undefined) ?? (latest<OrigPolicyRow>(rt, "insurance_policies", id, (r) => r.kind === kind) as Record<string, unknown> | null); return p ? { policy_id: String(p.policy_id), policy_number: (p.policy_number as string | undefined) ?? null, annual_premium_cents: cents(p.annual_premium_cents ?? p.first_year_premium_cents), premium_paid_through: dateOrNull(p.premium_paid_through), paid_at_closing: p.paid_at_closing === true || p.premium_paid_at_closing === true } : null; };
      const r = seedEscrowLines(ctx.events, { application_id: id, escrowed: flag(i, "escrowed"), hpml: flag(i, "hpml"), regulated_lending_institution: flag(i, "regulated_lending_institution"), in_sfha: i.in_sfha === undefined ? d?.in_sfha ?? false : flag(i, "in_sfha"), borrower_flood_escrow_election: (i.borrower_flood_escrow_election as "escrow" | "waive" | null | undefined) ?? null, master_blanket_covers_unit: flag(i, "master_blanket_covers_unit"), hazard: pol("hazard"), flood: pol("flood"), ho6: pol("ho6") } as EscrowSeedInput, at(i, ctx, "seeded_at"), ctx.actor);
      put(rt, ctx, "escrow_line_seeds", `els-${id}-${rt.store.list("escrow_line_seeds").length + 1}`, { application_id: id, lines: r.lines, escrow_established: r.escrow_established, seeded_at: at(i, ctx, "seeded_at") }); return { lines: r.lines, escrow_established: r.escrow_established, event: r.event.type }; }),
    guardrails: [never("FLOOD_ESCROW_NOT_WAIVABLE_RLI_HPML", "24.5 rule 8 / 12 CFR 22.5 / §1026.35(b): the flood line is not waivable when the partner is a regulated lending institution or the loan is an HPML", (i) => flag(i, "waive_flood_line") && (flag(i, "regulated_lending_institution") || flag(i, "hpml")), "flood premiums are escrowed for a regulated lending institution or an HPML — the line cannot be waived")] },
  // AI agent design: the decision record {application_id, determination, notice, requirements, evidence[], adequacy_results, deficiencies, gates, rationale, rule_set_version, model_version}.
  { name: "writeDecision", kind: "act", handler: compute((i, ctx, rt) => { const id = appId(i, ctx);
      const d = writeDecision({ application_id: id, determination: latest<FloodDeterminationRecord>(rt, "flood_determinations", id), requirement: latest<InsuranceRequirement>(rt, "insurance_requirements", id), evidence: rt.store.list("insurance_evidence", (r) => r.application_id === id).map((r) => r.data as unknown as EvidenceIntake), policies: rt.store.list("insurance_policies", (r) => r.application_id === id).map((r) => r.data as unknown as OrigPolicyRow), deficiencies: rt.store.list("insurance_deficiencies", (r) => r.application_id === id).map((r) => r.data as unknown as DeficiencyRow), gates: gateFacts(rt, id, i), model_version: str(i, "model_version") || ctx.run?.modelVersion || "unversioned", prompt_version: str(i, "prompt_version") || ctx.run?.promptVersion || "unversioned", ...(typeof i.confidence === "number" ? { confidence: i.confidence } : {}), ...(typeof i.rationale === "string" && i.rationale ? { rationale: i.rationale } : {}) });
      ctx.decide({ agent: "title-closing", action: "24.5.insurance_flood", rationale: d.rationale, ruleSetVersion: d.rule_set_version, applicationId: id, loanId: ctx.loanId, subject: { kind: "application", id }, ruleCode: "24.5", confidence: d.confidence, modelVersion: d.model_version, promptVersion: d.prompt_version }); return d; }) },
]);

/** Officer SLA for rating exceptions / B7-3-05 questions, from the escalation date. */
export const officerSlaDue = (on: PlainDate): PlainDate => addBusinessDays(on, OFFICER_SLA_BUSINESS_DAYS, creditor);
