/**
 * §21.1 process-owned tools — bus tools for 21.1 defined with `defineTools("21.1", <agent>, defs)` from
 * ../tools.ts. Every tool string must be one spec/registry/agents.json names for 21.1; src/app/tools.test.ts refuses
 * the rest. Spread by ./index.ts.
 *
 * The `intake` agent runs in application scope (ctx.applicationId; the intake record is the `applications` document in
 * the entity store, keyed by the application id). Every act goes through the pure rules in
 * src/domain/application/ops-21-1.ts, which append the events the timers and the downstream processes (21.2, 22.x, 23.1,
 * 28.3) consume. Guardrails encode the spec's sentences: never infer demographics; never a §1002.5-prohibited question;
 * never a prefill treated as submitted; never a qualification statement; never particular terms outside the flag mode;
 * never continue when the borrower asks for a human; the MLO of record (a human) decides the review package.
 */
import { defineTools, compute, decision, never, needsRole, guard, str, flag, type ToolDef, type ToolInput, type ToolRuntime } from "../tools.ts";
import type { CommandContext } from "../commands.ts";
import { plainDate as D } from "../../kernel/calendar/date.ts";
import { type IntakeApplication, type SafeClassification, type MloRosterEntry, type SixItemKey, newIntakeApplication, startInterview, discloseAi, requestHumanAgent, receiveApplication, captureSixItem, confirmPrefill, offerPrefill, detectSixItems, validateUlad, askDemographics, presentScif, affirmJointIntent, addBorrower, nonBorrowingSpouse, assignMlo, reassignMlo, openMloReview, decideMloReview, loadNmlsFeed, renderForm1003, requestESign, logSafeActivity, indicativeQuotePayment, recordArmInterest, intakeComplete, scanTranscript, reportProhibitedInquiry, gateFacts, leDueDate, SAFE_CLASSIFICATIONS, SIX_ITEMS, PROHIBITED_INQUIRIES, SCIF_TEMPLATE, APPENDIX_B_STATEMENT, DEFAULT_AI_INTAKE_MODE } from "../../domain/application/ops-21-1.ts";

const KIND = "applications";
/** Missing-input guard: a tool executed without its subject refuses with a RangeError (never a TypeError). */
const need = (i: ToolInput, ...keys: string[]): void => { const gaps = keys.filter((k) => i[k] === undefined || i[k] === null || i[k] === ""); if (gaps.length) throw new RangeError(`21.1 tool needs ${gaps.join(", ")}`); };
const appId = (i: ToolInput, ctx: CommandContext): string => { const id = str(i, "application_id") || ctx.applicationId || ""; if (!id) throw new RangeError("21.1 tool needs application_id (or an application-scoped command context)"); return id; };
const load = (i: ToolInput, ctx: CommandContext, rt: ToolRuntime): IntakeApplication => { const id = appId(i, ctx); const r = rt.store.get(KIND, id); if (!r) throw new RangeError(`no application ${id} in the entity store (startInterview opens it)`); return r.data as unknown as IntakeApplication; };
const save = (rt: ToolRuntime, ctx: CommandContext, app: IntakeApplication): IntakeApplication => rt.store.put(KIND, app.id, app as unknown as Record<string, unknown>, ctx.actor, ctx.now).data as unknown as IntakeApplication;
const at = (i: ToolInput, ctx: CommandContext, key = "at"): string => str(i, key) || ctx.now;
/** The feature flag `origination.ai_mlo_intake` from the entity store (`feature_flags`), a `flags` input, or the default "assisted". */
const aiIntakeMode = (i: ToolInput, rt: ToolRuntime): string => { const fromInput = (i.flags as Record<string, unknown> | undefined)?.["origination.ai_mlo_intake"]; if (typeof fromInput === "string") return fromInput; const row = rt.store.get("feature_flags", "origination.ai_mlo_intake"); return typeof row?.data.value === "string" ? row.data.value : DEFAULT_AI_INTAKE_MODE; };
const roster = (i: ToolInput, rt: ToolRuntime): readonly MloRosterEntry[] => (Array.isArray(i.roster) ? (i.roster as MloRosterEntry[]) : rt.store.list("mlo_roster").map((r) => r.data as unknown as MloRosterEntry));
const PROHIBITED_FIELDS = new Set(["religion", "childbearing_plans", "childbearing", "family_planning", "national_origin", "race", "color", "sex", "ethnicity", "gender"]);
const HUMAN_REQUEST = /\b(talk|speak) to (a|an) (human|person|agent|representative)\b|\breal person\b/i;
const asAnswers = (i: ToolInput) => (i.answers as Parameters<typeof presentScif>[3]["answers"] | undefined) ?? null;

export const TOOLS_21_1: readonly ToolDef[] = defineTools("21.1", "intake", [
  // Opens (or resumes) the interview on the application the runtime created (`application.started` is the runtime's event); `ai_intake_mode` snapshots the feature flag at start.
  { name: "startInterview", kind: "act", handler: compute((i, ctx, rt) => { const id = appId(i, ctx);
      let app = rt.store.get(KIND, id)?.data as unknown as IntakeApplication | undefined;
      if (!app) { need(i, "partner_name", "intake_channel"); app = newIntakeApplication({ id, partner_name: str(i, "partner_name"), partner_nmlsr_id: (i.partner_nmlsr_id as string | undefined) ?? null, intake_channel: str(i, "intake_channel"), started_at: at(i, ctx, "started_at"), creditor_time_zone: str(i, "creditor_time_zone") || "America/New_York", interview_language: str(i, "interview_language") || "en-US", property_state: (i.property_state as string | undefined) ?? null, property_address: (i.property_address as string | undefined) ?? null, transaction_type: (i.transaction_type as string | undefined) ?? null, occupancy: (i.occupancy as string | undefined) ?? null, ai_intake_mode: aiIntakeMode(i, rt), borrowers: (i.borrowers as { id: string; legal_name: string }[] | undefined) ?? [] }); }
      need(i, "session_id");
      const r = startInterview(ctx.events, app, { session_id: str(i, "session_id"), channel: str(i, "channel") || app.intake_channel, started_at: at(i, ctx, "started_at"), model_version: str(i, "model_version") || (ctx.run?.modelVersion ?? "unversioned"), prompt_version: str(i, "prompt_version") || (ctx.run?.promptVersion ?? "unversioned") });
      return { application: save(rt, ctx, r.app), session: r.session, ai_intake_mode: r.app.ai_intake_mode, next: "discloseAI" }; }),
    guardrails: [never("AUTONOMOUS_NEEDS_LEGAL_POSITION", "21.1 rule 8: `autonomous` is prohibited unless 31.1 records a written legal position for the state", (i) => ((i.flags as Record<string, unknown> | undefined)?.["origination.ai_mlo_intake"] === "autonomous") && !flag(i, "written_legal_position"), "origination.ai_mlo_intake=autonomous without a written legal position for the state")] },
  // Baseline addendum §8 item 10: the AI disclosure opens every voice/chat session (20.3's NTC_SM_AI_INTERACTION_DISCLOSURE); the evidence is the utterance id / screen acknowledgement.
  { name: "discloseAI", kind: "act", handler: compute((i, ctx, rt) => { need(i, "session_id", "utterance_id"); const app = load(i, ctx, rt); const r = discloseAi(ctx.events, app, { session_id: str(i, "session_id"), utterance_id: str(i, "utterance_id"), at: at(i, ctx), state: (i.state as string | undefined) ?? null }); save(rt, ctx, r.app); return { ai_disclosure_utterance_id: r.app.ai_disclosure_utterance_id, given_at: r.event.occurredAt }; }) },
  // Rule 1/2: a borrower-stated field. `field=credit_request` records the Reg B request (`received`); a six-item field is captured with `source=borrower_stated` and the six-item detector runs; a human request hands the session over.
  { name: "captureField", kind: "write", handler: compute((i, ctx, rt) => { need(i, "field"); const app0 = load(i, ctx, rt); const field = str(i, "field"); const when = at(i, ctx);
      if (app0.intake_channel !== "web" && app0.intake_channel !== "human_agent" && !app0.ai_disclosure_utterance_id) throw new RangeError("the AI disclosure precedes the first substantive question (discloseAI first)");
      if (field === "human_request" || (typeof i.value === "string" && HUMAN_REQUEST.test(i.value))) { need(i, "session_id"); const r = requestHumanAgent(ctx.events, app0, { session_id: str(i, "session_id"), at: when }); const esc = rt.escalations.open({ kind: "human_agent", applicationId: app0.id, payload: { reason: "borrower_request", session_id: str(i, "session_id") } }, ctx.actor); save(rt, ctx, r.app); return { status: r.app.status, escalation_id: esc.id, captured: false }; }
      if (field === "credit_request") { need(i, "transaction_type", "occupancy"); const r = receiveApplication(ctx.events, app0, { at: when, transaction_type: str(i, "transaction_type"), occupancy: str(i, "occupancy"), property_state: (i.property_state as string | undefined) ?? null, property_address: (i.property_address as string | undefined) ?? null, ...(i.identity_verified !== undefined ? { identity_verified: flag(i, "identity_verified") } : {}), ...(i.esign_consent_active !== undefined ? { esign_consent_active: flag(i, "esign_consent_active") } : {}), ...(i.e_delivery !== undefined ? { e_delivery: flag(i, "e_delivery") } : {}) }); save(rt, ctx, r.app); return { status: r.app.status, application_date: r.application_date, hmda_application_date: r.app.hmda_application_date, received: !!r.event }; }
      if (field === "arm_interest") { need(i, "fnma_plan_number"); const r = recordArmInterest(ctx.events, app0, { fnma_plan_number: str(i, "fnma_plan_number"), at: when }); save(rt, ctx, r.app); return { arm_interest_recorded: true, emitted: !!r.event }; }
      if ((SIX_ITEMS as readonly string[]).includes(field)) { need(i, "value"); const r = captureSixItem(ctx.events, app0, { item: field as SixItemKey, value: i.value as string | bigint, at: when, ...(typeof i.borrower_id === "string" ? { borrower_id: i.borrower_id } : {}) }); save(rt, ctx, r.app); return { item: field, submitted_at: when, source: "borrower_stated", six_items_complete: r.trid.complete, missing: r.trid.missing, trid_received_at: r.trid.trid_received_at, trid_emitted: r.trid.emitted }; }
      const v = validateUlad(field, i.value); if (!v.valid) throw new RangeError(v.reason!);
      if (field === "borrower") { need(i, "borrower_id", "legal_name"); const r = addBorrower(ctx.events, app0, { id: str(i, "borrower_id"), legal_name: str(i, "legal_name"), borrower_role: str(i, "borrower_role") || "borrower", marital_status: (i.marital_status as string | undefined) ?? null, citizenship_status: (i.citizenship_status as string | undefined) ?? null, at: when, legal_presence_evidence_document_id: (i.legal_presence_evidence_document_id as string | undefined) ?? null, legal_presence_expires_on: (i.legal_presence_expires_on as string | undefined) ?? null }); save(rt, ctx, r.app); return { borrower: r.borrower, joint_intent_required: r.event.payload.joint_intent_required }; }
      if (field === "non_borrowing_spouse") { need(i, "applicant_id", "spouse_id", "spouse_name"); const r = nonBorrowingSpouse(ctx.events, app0, { applicant_id: str(i, "applicant_id"), spouse_id: str(i, "spouse_id"), spouse_name: str(i, "spouse_name"), at: when }); save(rt, ctx, r.app); return { required: r.required, spouse: r.spouse }; }
      const rec = save(rt, ctx, { ...app0, last_activity_at: when } as IntakeApplication); ctx.events.append({ type: "application.field.captured", applicationId: rec.id, actor: ctx.actor, payload: { application_id: rec.id, field, borrower_id: i.borrower_id ?? null, valid: true } }); return { field, valid: true, captured_at: when }; }),
    guardrails: [never("REGB_1002_5_PROHIBITED_INQUIRY", "21.1 rule 5 (§1002.5): the interview never asks about religion, race, color, sex or national origin outside the monitoring questions, never about childbearing intentions (§1002.5(d)(3))", (i) => PROHIBITED_FIELDS.has(str(i, "field").toLowerCase()) || PROHIBITED_INQUIRIES.some((p) => typeof i.question === "string" && p.pattern.test(i.question)), "prohibited inquiry under Reg B §1002.5 — demographic questions are asked only through askDemographics (Section 8 monitoring)"),
      never("PREFILL_NOT_SUBMITTED", "21.1 guardrails: never treat a prefilled field as submitted (open question 2; CFPB TRID guide)", (i) => str(i, "source") === "prefill" || str(i, "source") === "prefill_unconfirmed" || flag(i, "prefilled"), "a prefilled value is a suggestion: confirmPrefill records the borrower's item-level confirmation"),
      never("NEVER_DISCOURAGE", "21.1 guardrails: never discourage an applicant (§1002.4(b))", (i) => flag(i, "discouraging_statement"), "statements that would discourage a reasonable person from applying are refused")] },
  // Rule 1: a prefilled item (20.1 servicing data) becomes a submission only on the borrower's explicit confirmation; `op=offer` stages the suggestion with submitted_at=null.
  { name: "confirmPrefill", kind: "write", handler: compute((i, ctx, rt) => { need(i, "item"); const app0 = load(i, ctx, rt); const item = str(i, "item") as SixItemKey;
      if (i.op === "offer") { if (!str(i, "on_file_value_hash")) need(i, "value"); const app = offerPrefill(app0, item, (i.value as string | bigint | undefined) ?? "", { on_file_value_hash: str(i, "on_file_value_hash") || null }); save(rt, ctx, app); return { item, submitted_at: null, source: "prefill_unconfirmed", ...(str(i, "on_file_value_hash") ? { on_file: true } : {}) }; }
      const r = confirmPrefill(ctx.events, app0, { item, at: at(i, ctx), ...(i.value !== undefined ? { value: i.value as string | bigint } : {}), ...(typeof i.borrower_id === "string" ? { borrower_id: i.borrower_id } : {}) }); save(rt, ctx, r.app);
      return { item, submitted_at: r.event.payload.submitted_at, source: "borrower_confirmed_prefill", six_items_complete: r.trid.complete, missing: r.trid.missing, trid_received_at: r.trid.trid_received_at, trid_emitted: r.trid.emitted }; }),
    guardrails: [guard("EXPLICIT_CONFIRMATION", "21.1 rule 1: 'A prefilled item counts as submitted only at the borrower's explicit confirmation'", (i) => (i.op !== "offer" && i.confirmed === false ? "the borrower has not confirmed this item — it is not submitted" : undefined))] },
  // Rule: every field validated against the ULAD (MISMO 3.4 B324) enumerations as it goes; a read.
  { name: "validateULAD", kind: "read", handler: compute((i) => { need(i, "field"); return validateUlad(str(i, "field"), i.value); }) },
  // Rule 2: six-item detection → `trid_received_at` = max(submitted_at), `application.trid_received` once; 21.2's LE clock (+3 business_days_creditor) reads the anchor from the payload.
  { name: "detectSixItems", kind: "act", handler: compute((i, ctx, rt) => { const app0 = load(i, ctx, rt); const r = detectSixItems(ctx.events, app0, at(i, ctx)); save(rt, ctx, r.app);
      return { complete: r.complete, missing: r.missing, emitted: r.emitted, trid_received_at: r.trid_received_at, trid_application_date: r.trid_application_date, le_due: r.trid_application_date ? leDueDate(D(r.trid_application_date)) : null, six_items: r.app.six_items }; }) },
  // Rule 3: Reg C App. B — the instruction-2 statement is read/shown, multi-select ethnicity/race with disaggregated sub-categories, declines recorded; never populated from name, voice, accent or image.
  { name: "askDemographics", kind: "write", handler: compute((i, ctx, rt) => { need(i, "borrower_id", "collection_method"); const app0 = load(i, ctx, rt);
      const r = askDemographics(ctx.events, app0, str(i, "borrower_id"), { collection_method: str(i, "collection_method"), ethnicity: (i.ethnicity as string[] | undefined) ?? null, race: (i.race as string[] | undefined) ?? null, sex: (i.sex as string | undefined) ?? null, declined_ethnicity: flag(i, "declined_ethnicity"), declined_race: flag(i, "declined_race"), declined_sex: flag(i, "declined_sex"), visual_observation_used: flag(i, "visual_observation_used"), collected_at: at(i, ctx, "collected_at"), inferred_from: (i.inferred_from as string | undefined) ?? null });
      save(rt, ctx, r.app); return { statement_given: APPENDIX_B_STATEMENT, row: r.row, all_borrowers: r.all_borrowers, gate: gateFacts(r.app) }; }),
    guardrails: [never("DEMOGRAPHICS_NEVER_INFERRED", "21.1 guardrails: never infer or record demographic data from anything but the borrower's answers (Reg C App. B; rule 3)", (i) => !!i.inferred_from || str(i, "source") === "inference" || str(i, "source") === "surname" || str(i, "source") === "image" || str(i, "source") === "voice", "demographic information comes only from the applicant's own answers — never from name, voice, accent or image"),
      never("VISUAL_OBSERVATION_REMOTE", "21.1 rule 3 / App. B instruction 10: visual observation or surname collection only for in-person applications; `video` is not in person (open question 3)", (i) => flag(i, "visual_observation_used") && str(i, "collection_method") !== "in_person", "visual_observation_used is lawful only when collection_method=in_person")] },
  // Rule 6: Form 1103 presented to every borrower after Section 1 (NTC_FNMA_1103_SCIF, English + five translations); blank answers are `not_answered`, never a condition.
  { name: "presentSCIF", kind: "act", handler: compute((i, ctx, rt) => { need(i, "borrower_id"); const app0 = load(i, ctx, rt);
      let rendered_document_id = (i.rendered_document_id as string | undefined) ?? null;
      if (!rendered_document_id && rt.notices && Array.isArray(i.recipients) && i.payload) { const n = rt.notices.render({ templateCode: SCIF_TEMPLATE, loanId: ctx.loanId, recipients: i.recipients as Parameters<typeof rt.notices.render>[0]["recipients"], payload: i.payload as Record<string, unknown>, asOf: D(str(i, "as_of") || ctx.now.slice(0, 10)) }); rendered_document_id = n.id; }
      const r = presentScif(ctx.events, app0, str(i, "borrower_id"), { language_edition: str(i, "language_edition") || "english", presented_at: at(i, ctx, "presented_at"), rendered_document_id, answers: asAnswers(i), completed_at: (i.completed_at as string | undefined) ?? null });
      save(rt, ctx, r.app); return { scif: r.scif, all_borrowers: r.all_borrowers, template: SCIF_TEMPLATE }; }),
    guardrails: [never("SCIF_NEVER_SKIPPED", "21.1 guardrails: never skip the SCIF; LL-2022-03 / B2-2-06 'Lenders are required to present the Supplemental Consumer Information Form (Form 1103) to the borrower'", (i) => flag(i, "skip"), "the SCIF is mandatory to present (optional for the borrower to answer)"),
      never("SCIF_ANSWER_NOT_A_CONDITION", "21.1 rule 6: a blank answer is stored as not_answered and is never followed up as a condition", (i) => flag(i, "require_answer"), "the borrower is not required to select any language option (Form 1103)")] },
  // Rule 4 / §1002.7(d): joint intent evidenced by a method distinct from the accuracy attestation, before any credit report for that borrower.
  { name: "affirmJointIntent", kind: "write", handler: compute((i, ctx, rt) => { need(i, "borrower_id", "method", "evidence_id"); const app0 = load(i, ctx, rt); const r = affirmJointIntent(ctx.events, app0, { borrower_id: str(i, "borrower_id"), method: str(i, "method"), evidence_id: str(i, "evidence_id"), at: at(i, ctx) }); save(rt, ctx, r.app); return { borrower_id: str(i, "borrower_id"), affirmed_at: r.event.payload.affirmed_at, evidence_id: str(i, "evidence_id"), all_borrowers: r.all_borrowers, gate: gateFacts(r.app) }; }),
    guardrails: [never("JOINT_INTENT_DISTINCT_ARTIFACT", "Reg B comment 7(d)(1)-3: 'The method used to establish intent must be distinct from the means used by individuals to affirm the accuracy of information'", (i) => !!str(i, "evidence_id") && str(i, "evidence_id") === str(i, "accuracy_attestation_id"), "the joint-intent affirmation cannot reuse the Section 6 accuracy attestation artifact"),
      never("NOTE_SIGNATURE_NOT_INTENT", "Reg B comment 7(d)(1)-3: 'Signatures on a promissory note may not be used to show intent to apply for joint credit'", (i) => str(i, "method") === "note_signature" || str(i, "method") === "joint_financial_statement", "a note signature or joint financial statement is not evidence of joint intent")] },
  // Rule 7: at `application.received` the partner's licensed MLO for the property state with the lowest open queue (NMLS active per the nightly feed); `op=nmls_feed` loads the nightly status file; `op=reassign` after a status loss.
  { name: "assignMLO", kind: "act", handler: compute((i, ctx, rt) => { const app0 = load(i, ctx, rt); const when = at(i, ctx);
      if (i.op === "nmls_feed") { need(i, "feed"); const r = loadNmlsFeed(ctx.events, app0, i.feed as Parameters<typeof loadNmlsFeed>[2], when); save(rt, ctx, r.app); return { changed: r.changed, gate_open: r.gate_open, nmls_status: r.app.mlo_nmls_status }; }
      if (i.op === "reassign") { const r = reassignMlo(ctx.events, rt.escalations, app0, { roster: roster(i, rt), at: when, reason: (str(i, "reason") as "sla_breach" | "nmls_inactive" | "other") || "other" }); save(rt, ctx, r.app); return { previous_mlo_of_record_id: r.previous, mlo_of_record_id: r.mlo.mlo_id, nmlsr_id: r.mlo.nmlsr_id, escalation_id: r.escalation.id, gate: gateFacts(r.app) }; }
      const r = assignMlo(ctx.events, app0, { roster: roster(i, rt), at: when }); save(rt, ctx, r.app); return { mlo_of_record_id: r.mlo.mlo_id, nmlsr_id: r.mlo.nmlsr_id, mlo_name: r.mlo.name, state: r.app.property_state, mlo_review_state: r.app.mlo_review_state }; }),
    guardrails: [never("MLO_NMLS_ACTIVE", "21.1 operational prerequisites: NMLS Consumer Access status verified before assignment; rule 7", (i) => str(i, "nmls_status") === "inactive", "an MLO whose NMLS status is not active cannot be the MLO of record")] },
  // Rule 7 / §1026.36(g): the initial 1003 (1/2021) with the MLO of record's name and NMLSR ID in Section 9; a non-borrowing spouse appears for the security instrument only.
  { name: "renderForm1003", kind: "act", handler: compute((i, ctx, rt) => { const app0 = load(i, ctx, rt); const f = renderForm1003(app0); const app = save(rt, ctx, { ...app0, initial_1003_document_id: f.document_id, initial_1003_data_hash: f.data_hash }); rt.store.put("documents", f.document_id, { kind: "urla_1003_initial", application_id: app.id, sha256: f.data_hash, urla_form_version: f.urla_form_version, retention_class: "fnma_loan_file_life_plus_4y" }, ctx.actor, ctx.now); ctx.events.append({ type: "application.initial_1003.rendered", applicationId: app.id, actor: ctx.actor, payload: { application_id: app.id, document_id: f.document_id, data_hash: f.data_hash, urla_form_version: f.urla_form_version, ulad_version: f.ulad_version, originator_nmlsr_id: f.section_9_loan_originator.originator_nmlsr_id } }); return f; }) },
  // E-SIGN 7001(c): the borrower personally e-signs the initial 1003 under the 20.3 consent scoped to application documents; the accuracy attestation is Section 6's artifact.
  { name: "requestESign", kind: "act", handler: compute((i, ctx, rt) => { need(i, "borrower_id", "document_id", "accuracy_attestation_id"); const app0 = load(i, ctx, rt);
      const r = requestESign(ctx.events, app0, { borrower_id: str(i, "borrower_id"), document_id: str(i, "document_id"), data_hash: str(i, "data_hash") || app0.initial_1003_data_hash || "", signed_at: at(i, ctx, "signed_at"), consent: (i.consent as Parameters<typeof requestESign>[2]["consent"] | undefined) ?? null, accuracy_attestation_id: str(i, "accuracy_attestation_id"), audit: { ...(typeof i.ip === "string" ? { ip: i.ip } : {}), ...(typeof i.authentication_result === "string" ? { authentication_result: i.authentication_result } : {}) } });
      save(rt, ctx, r.app); const done = r.all_borrowers ? intakeComplete(ctx.events, r.app, at(i, ctx, "signed_at")) : null; if (done) save(rt, ctx, done.app);
      return { borrower_id: str(i, "borrower_id"), signed_at: r.event.payload.signed_at, all_borrowers: r.all_borrowers, intake_complete: done?.ok ?? false, blocking: done?.blocking ?? [] }; }),
    guardrails: [never("INITIAL_1003_PERSONALLY_SIGNED", "Selling Guide B1-1-01: the initial Form 1003 must be personally signed by the borrower (no power of attorney)", (i) => flag(i, "power_of_attorney"), "the initial 1003 is e-signed by the borrower personally; an attorney-in-fact signs only the closing documents 26.1 allows")] },
  // Escalations: `mlo_of_record` (application-stage package; opens SM_O21_MLO_REVIEW_SLA_1BD), `human_agent`, `licensed_specialist` (jurisdiction_rules), `compliance-sentinel` (prohibited inquiry → sev 1 + prompt quarantine); `op=decide` is the MLO of record's own act.
  { name: "openEscalation", kind: "act", handler: compute((i, ctx, rt) => { const app0 = load(i, ctx, rt); const when = at(i, ctx);
      if (i.op === "decide") { need(i, "escalation_id", "decision"); const r = decideMloReview(ctx.events, app0, { escalation_id: str(i, "escalation_id"), decision: str(i, "decision") as "approved" | "returned", decided_at: when, by: ctx.actor, notes: (i.notes as string | undefined) ?? null }); save(rt, ctx, r.app); rt.escalations.complete(str(i, "escalation_id"), ctx.actor, ...(typeof i.evidence_document_id === "string" ? [i.evidence_document_id] : [])); return { review: r.review, mlo_review_state: r.app.mlo_review_state, gate: gateFacts(r.app) }; }
      if (i.op === "compliance_scan") { need(i, "session_id", "transcript"); const session = app0.interview_sessions.find((s) => s.session_id === str(i, "session_id")); const scan = scanTranscript(i.transcript as Parameters<typeof scanTranscript>[0], str(i, "prompt_version") || session?.prompt_version || "unversioned"); const r = reportProhibitedInquiry(ctx.events, rt.escalations, app0, scan, str(i, "session_id"), when); return { findings: scan.findings, severity: scan.severity, quarantined_prompt_version: scan.quarantine_prompt_version, escalation_id: r.escalation?.id ?? null }; }
      const kind = str(i, "kind") || "mlo_of_record";
      if (kind === "mlo_of_record") { const r = openMloReview(ctx.events, rt.escalations, app0, { stage: (str(i, "stage") as "application") || "application", opened_at: when, package_document_id: (i.package_document_id as string | undefined) ?? null }); save(rt, ctx, r.app); return { escalation_id: r.escalation.id, owner_role: r.escalation.ownerRole, stage: r.review.stage, sla_due: r.sla_due }; }
      if (kind !== "human_agent" && kind !== "licensed_specialist") throw new RangeError(`escalation kind ${kind} is not one of mlo_of_record/human_agent/licensed_specialist (compliance findings go through op=compliance_scan)`);
      const e = rt.escalations.open({ kind, applicationId: app0.id, payload: { reason: i.reason ?? null, state: app0.property_state } }, ctx.actor); return { escalation_id: e.id, owner_role: e.ownerRole }; }),
    guardrails: [needsRole("MLO_DECIDES_REVIEW", "21.1 automation class (b): the only human is the `mlo_of_record` (SAFE Act attribution and review) — the review package is approved/returned by the MLO of record", (i) => i.op === "decide", ["mlo_of_record"], "the stage review decision is the MLO of record's own act")] },
  // Rule 8 / App. A: every utterance/screen classified; particular terms only under the flag mode with the MLO attribution (assisted) — otherwise the fallback is a general explanation; a qualification statement is never made.
  { name: "logSafeActivity", kind: "write", handler: compute((i, ctx, rt) => { need(i, "utterance_id", "classification"); const app0 = load(i, ctx, rt); const classification = str(i, "classification") as SafeClassification;
      if (!SAFE_CLASSIFICATIONS.includes(classification)) throw new RangeError(`classification ${classification} is not one of ${SAFE_CLASSIFICATIONS.join("/")}`);
      const r = logSafeActivity(ctx.events, app0, { utterance_id: str(i, "utterance_id"), classification, at: at(i, ctx), written_legal_position: flag(i, "written_legal_position"), scenario_approved_by_mlo: flag(i, "scenario_approved_by_mlo") }); save(rt, ctx, r.app);
      const quote = r.permission.allowed && classification === "particular_terms_presented" && i.loan_amount_cents !== undefined && typeof i.rate_pct === "string" ? indicativeQuotePayment(BigInt(String(i.loan_amount_cents)), i.rate_pct, Number(i.term_months ?? 360)) : null;
      return { presented: r.permission.allowed, classification: r.entry.classification, presented_under_mlo_id: r.entry.presented_under_mlo_id, attribution: r.permission.attribution, fallback: r.permission.fallback, gate: r.permission.gate, reason: r.permission.reason, quote }; }),
    guardrails: [never("NEVER_STATE_QUALIFICATION", "21.1 guardrails: never tell a borrower they do or do not qualify (App. A (b)(2)(iv) underwriting communications are 23.x's; eligibility statements before DU are prohibited)", (i) => str(i, "classification") === "underwriting_communication" || flag(i, "qualification_statement"), "the agent explains the process (App. A (b)(2)(v)) and never states a qualification conclusion"),
      never("NO_NEGOTIATION", "12 CFR 1008.103(c)(2)(B): negotiating terms is the MLO of record's act, never the AI's", (i) => str(i, "classification") === "negotiation", "an AI is not 'an individual' under the SAFE Act: negotiation of terms is refused; the MLO of record responds to a rate/fee request")] },
  // The agent's decision record (`agent_decisions`) with rule_set_version / model_version / prompt_version / rationale / confidence.
  { name: "writeDecision", kind: "write", handler: decision() },
]);
