/**
 * §24.3 process-owned tools — bus tools for 24.3 defined with `defineTools("24.3", <agent>, defs)` from
 * ../tools.ts. Every tool string must be one spec/registry/agents.json names for 24.3; src/app/tools.test.ts refuses
 * the rest. Spread by ./index.ts.
 *
 * The `valuation` agent runs in application scope (ctx.applicationId or `application_id`). Rows live in the entity
 * store under `property_eligibility_reviews`, `project_reviews`, `escrow_holdbacks` and `mh_verifications` (every
 * write is a new version — the Postgres tables are append-only); every act goes through the pure rules in
 * src/domain/property/ops-24-3.ts, which append the events the 24.3 timers and the downstream processes (23.1, 25.2,
 * 26.3, 29.3, 30.2, servicing 3.x) consume. Guardrails encode the spec's sentences: never mark a project eligible with
 * an unreviewed in-window inspection report; never treat a special assessment tied to a safety/habitability repair as
 * routine; never release holdback funds without accepted evidence; never key CPM itself (fnma_portal_operator, UI-only);
 * never waive a safety-related repair; PERS submissions and exception requests are the partner `officer`'s.
 */
import { defineTools, compute, never, needsRole, guard, str, flag, cents, type ToolDef, type ToolInput, type ToolRuntime } from "../tools.ts";
import type { CommandContext } from "../commands.ts";
import type { EscalationKind } from "../escalations.ts";
import { plainDate as D, type PlainDate } from "../../kernel/calendar/date.ts";
import { resolveRules, classifyProperty, runPropertyChecks, runPropertyEligibility, routeCondition, planRepairs, assertHoldbackEligible, computeHoldback, establishHoldback, fundHoldback, acceptCompletionEvidence, releaseFinalDraw, sweepHoldbacks, acceptRepairCompletion, startProjectReview, runProjectEligibility, runProjectTests, selectReviewType, prepareCpmSheet, recordCpmStatus, checkProjectValidity, requestProjectDocs, receiveProjectDocs, classifyInspection, inspectionsInWindow, verifyMh, writeDecision, consummateGate, readValuationRatings, civilDate, HoldbackRefused, CpmRefused, SA_CRITICAL_REASON,
  type PropertyFacts, type ProjectFacts, type ProjectReview, type EscrowHoldback, type Deficiency, type CompletionEvidence, type CpmSnapshot, type MhFacts, type ValuationRatings, type PropertyEligibilityReview, type ConditionRating, type QualityRating, type InspectionReport, type ProjectDoc, type Repair } from "../../domain/property/ops-24-3.ts";

const need = (i: ToolInput, ...keys: string[]): void => { const gaps = keys.filter((k) => i[k] === undefined || i[k] === null || i[k] === ""); if (gaps.length) throw new RangeError(`24.3 tool needs ${gaps.join(", ")}`); };
const appId = (i: ToolInput, ctx: CommandContext): string => { const id = str(i, "application_id") || ctx.applicationId || ""; if (!id) throw new RangeError("24.3 tool needs application_id (or an application-scoped command context)"); return id; };
const at = (i: ToolInput, ctx: CommandContext, key = "at"): string => str(i, key) || ctx.now;
const dateOf = (i: ToolInput, key: string, fallback?: PlainDate): PlainDate => { const v = str(i, key); if (v) return D(v); if (fallback) return fallback; throw new RangeError(`24.3 tool needs ${key}`); };
const rulesFor = (i: ToolInput, ctx: CommandContext, rt: ToolRuntime) => { const fromApp = rt.store.get("applications", str(i, "application_id") || ctx.applicationId || "")?.data.application_date; const d = str(i, "application_date") || (typeof fromApp === "string" ? fromApp : "") || ctx.now.slice(0, 10); return resolveRules(D(d)); };
const facts = <T>(i: ToolInput, key = "facts"): T => { const f = i[key]; if (!f || typeof f !== "object") throw new RangeError(`24.3 tool needs ${key}`); return f as T; };
const latest = <T>(rt: ToolRuntime, kind: string, applicationId: string): (T & { id?: string }) | null => { const rows = rt.store.list(kind, (d) => d.application_id === applicationId); const r = rows.at(-1); return r ? ({ ...(r.data as unknown as T), id: r.id }) : null; };
const put = (rt: ToolRuntime, ctx: CommandContext, kind: string, id: string, row: object) => rt.store.put(kind, id, row as unknown as Record<string, unknown>, ctx.actor, ctx.now).data;
const defs = (i: ToolInput, key = "deficiencies"): Deficiency[] => (Array.isArray(i[key]) ? (i[key] as Deficiency[]).map((d) => ({ ...d, ...(d.estimate_cents !== undefined && d.estimate_cents !== null ? { estimate_cents: cents(d.estimate_cents) } : {}) })) : []);
const ratingsFrom = (i: ToolInput): ValuationRatings | null => (i.ratings && typeof i.ratings === "object" ? { condition_rating: ((i.ratings as Record<string, unknown>).condition_rating as ConditionRating | undefined) ?? null, quality_rating: ((i.ratings as Record<string, unknown>).quality_rating as QualityRating | undefined) ?? null, as_is_or_subject_to: ((i.ratings as Record<string, unknown>).as_is_or_subject_to as "as_is" | "subject_to" | undefined) ?? null, valuation_id: ((i.ratings as Record<string, unknown>).valuation_id as string | undefined) ?? null, deficiencies: defs(i.ratings as ToolInput) } : null);
/** agents.json escalates_to: the fnma_portal_operator's work item is the kernel's `human_portal_task` (owner role fnma_portal_operator). */
const ESCALATION_KIND: Record<string, EscalationKind> = { appraiser: "appraiser", fnma_portal_operator: "human_portal_task", human_agent: "human_agent", licensed_specialist: "licensed_specialist", officer: "officer" };
const SAFETY_WAIVER = (i: ToolInput): boolean => flag(i, "waive_safety_repairs") || flag(i, "waive_safety_repair") || (Array.isArray(i.deficiencies) && (i.deficiencies as Deficiency[]).some((d) => d.safety_related && (d as unknown as Record<string, unknown>).path === "holdback"));

export const TOOLS_24_3: readonly ToolDef[] = defineTools("24.3", "valuation", [
  // R1: property_class from the 1003 interview, title and the appraisal (a read — the classification never writes).
  { name: "classifyProperty", kind: "read", handler: compute((i) => { need(i, "units", "property_type"); const f = { ...(i as unknown as PropertyFacts), units: Number(i.units) }; return { property_class: classifyProperty(f), units: f.units, property_type: f.property_type }; }) },
  // R1 + R2: every B2-3 / B4-1.3 check with the dated rule set; ratings from 24.1/24.2's events unless passed; a new `property_eligibility_reviews` row; emits property.eligibility.completed / property.repair.required.
  { name: "runPropertyEligibility", kind: "act", ruleSetVersion: "fnma.selling.2026-09-02", handler: compute((i, ctx, rt) => { const id = appId(i, ctx); const f = facts<PropertyFacts>(i); if (typeof f.units !== "number" || !f.property_type) throw new RangeError("24.3 runPropertyEligibility facts need units and property_type");
      const rules = rulesFor(i, ctx, rt); const ratings = i.ratings === undefined ? undefined : ratingsFrom(i);
      const r = runPropertyEligibility(ctx.events, { application_id: id, facts: f, ...(ratings !== undefined ? { ratings } : {}), ...(typeof i.transaction_type === "string" ? { transaction_type: i.transaction_type as "purchase" | "limited_cash_out" | "cash_out" } : {}), completion: (i.completion as Parameters<typeof runPropertyEligibility>[1]["completion"]) ?? null, rules }, at(i, ctx));
      put(rt, ctx, "property_eligibility_reviews", r.review.review_id, r.review); return { review: r.review, events: r.events.map((e) => e.type), rule_set_version: rules.rule_set_version }; }),
    guardrails: [never("SAFETY_REPAIR_NEVER_WAIVED", "24.3 guardrails: 'never waive a safety-related repair'; B4-1.3-05: safety, soundness or structural items 'are repaired before delivery'", SAFETY_WAIVER, "a safety-related deficiency is completed before sale — it is never waived or postponed into a holdback")] },
  // R2: C1–C4 pass; C5 as-is unless safety items; C6 ineligible until repaired to ≥ C5; Q6 safety items repaired (a pure read over the ratings).
  { name: "routeCondition", kind: "read", handler: compute((i) => { need(i, "condition_rating"); return routeCondition({ condition_rating: str(i, "condition_rating") as ConditionRating, quality_rating: (i.quality_rating as QualityRating | undefined) ?? null, as_is_or_subject_to: (i.as_is_or_subject_to as "as_is" | "subject_to" | undefined) ?? null, deficiencies: defs(i), completion: (i.completion as Parameters<typeof routeCondition>[0]["completion"]) ?? null }); }),
    guardrails: [never("SAFETY_REPAIR_NEVER_WAIVED", "24.3 guardrails: 'never waive a safety-related repair'", SAFETY_WAIVER, "a safety-related deficiency cannot be waived")] },
  // R2 / R5: each deficiency → complete_before_sale | holdback | none; `op=complete` accepts a Completion Report / alternative for one item (the two delivery gates).
  { name: "planRepairs", kind: "act", handler: compute((i, ctx) => {
      if (i.op === "complete") { need(i, "item", "evidence"); const ev = i.evidence as CompletionEvidence; const r = acceptRepairCompletion(ctx.events, { application_id: appId(i, ctx), item: str(i, "item"), safety_related: flag(i, "safety_related"), evidence: { ...ev, received_at: ev.received_at || at(i, ctx) }, loan_id: (i.loan_id as string | undefined) ?? ctx.loanId ?? null }, at(i, ctx), ctx.actor); if (!r.accepted) throw new RangeError(r.reason); return { accepted: true, reason: r.reason, events: r.events.map((e) => e.type) }; }
      need(i, "deficiencies"); const plan = planRepairs(defs(i), { subject_to: flag(i, "subject_to") }); return { repairs: plan, holdback_items: plan.filter((r) => r.path === "holdback").map((r) => r.item), before_sale_items: plan.filter((r) => r.path === "complete_before_sale").map((r) => r.item) }; }),
    guardrails: [never("SAFETY_REPAIR_NEVER_WAIVED", "24.3 guardrails: 'never waive a safety-related repair'; B4-1.2-05 postponed improvements never include safety items", SAFETY_WAIVER, "safety items cannot be postponed — they must be complete before sale")] },
  // R3: `op=compute` (default) the 120% / fixed-price arithmetic and the 180-day due date; `op=establish` the row + holdback.established (+ funding lines when loan_id and the prepurchase T&I account are known); `op=complete` accepts evidence; `op=release` the final draw; `op=sweep` the day-180 overdue sweep.
  { name: "computeHoldback", kind: "act", moneyFields: ["estimate_cents", "contract_cents", "escrow_cents"], handler: compute((i, ctx, rt) => {
      const op = (i.op as string | undefined) ?? "compute";
      if (op === "compute") { need(i, "estimate_cents", "note_date"); return computeHoldback({ estimate_cents: cents(i.estimate_cents), fixed_price_contract: flag(i, "fixed_price_contract"), contract_cents: i.contract_cents !== undefined ? cents(i.contract_cents) : null, note_date: dateOf(i, "note_date") }); }
      const id = appId(i, ctx);
      if (op === "establish") { need(i, "estimate_cents", "note_date", "items"); const items = defs(i, "items"); assertHoldbackEligible(items);
        const r = establishHoldback(ctx.events, { application_id: id, loan_id: (i.loan_id as string | undefined) ?? ctx.loanId ?? null, kind: (i.kind as EscrowHoldback["kind"] | undefined) ?? "postponed_existing_minor", items, estimate_cents: cents(i.estimate_cents), fixed_price_contract: flag(i, "fixed_price_contract"), contract_cents: i.contract_cents !== undefined ? cents(i.contract_cents) : null, note_date: dateOf(i, "note_date"), custodial_account_id: (i.custodial_account_id as string | undefined) ?? null, funded_at: (i.funded_at as string | undefined) ?? null, rules: rulesFor(i, ctx, rt) }, at(i, ctx), ctx.actor);
        let entry_set_id: string | null = null; const loanId = r.holdback.loan_id; if (loanId && typeof i.prepurchase_ti_account_id === "string") entry_set_id = fundHoldback(ctx.ledger, r.holdback, loanId, i.prepurchase_ti_account_id, civilDate(at(i, ctx, "funded_at")), at(i, ctx, "funded_at"), r.event.id).id;
        put(rt, ctx, "escrow_holdbacks", r.holdback.holdback_id, r.holdback); return { holdback: r.holdback, entry_set_id, event: r.event.type }; }
      const hb = (typeof i.holdback_id === "string" ? (rt.store.get("escrow_holdbacks", i.holdback_id)?.data as unknown as EscrowHoldback | undefined) : undefined) ?? latest<EscrowHoldback>(rt, "escrow_holdbacks", id); if (!hb && op !== "sweep") throw new RangeError("no escrow_holdbacks row for the application (op=establish first)");
      if (op === "complete") { need(i, "evidence"); const ev = i.evidence as CompletionEvidence; const r = acceptCompletionEvidence(ctx.events, hb!, { ...ev, received_at: ev.received_at || at(i, ctx) }, at(i, ctx), ctx.actor); put(rt, ctx, "escrow_holdbacks", r.holdback.holdback_id, r.holdback); return { holdback: r.holdback, final_draw_due_on: r.final_draw_due_on }; }
      if (op === "release") { const r = releaseFinalDraw(ctx.events, hb!, { released_at: at(i, ctx, "released_at"), loan_id: (i.loan_id as string | undefined) ?? ctx.loanId ?? null, ledger: typeof i.prepurchase_ti_account_id === "string" ? ctx.ledger : null, prepurchase_ti_account_id: (i.prepurchase_ti_account_id as string | undefined) ?? null }, ctx.actor); put(rt, ctx, "escrow_holdbacks", r.holdback.holdback_id, r.holdback); return { holdback: r.holdback, entry_set_id: r.entry_set?.id ?? null }; }
      if (op === "sweep") { const rows = rt.store.list("escrow_holdbacks").map((r) => r.data as unknown as EscrowHoldback); const r = sweepHoldbacks(ctx.events, rt.escalations, rows, dateOf(i, "today", civilDate(ctx.now)), at(i, ctx), ctx.actor); for (const h of r.overdue) put(rt, ctx, "escrow_holdbacks", h.holdback_id, h); return { overdue: r.overdue.map((h) => h.holdback_id), escalation_ids: r.escalation_ids }; }
      throw new RangeError(`computeHoldback op ${op} is not one of compute/establish/complete/release/sweep`); }),
    guardrails: [never("HOLDBACK_RELEASE_NEEDS_EVIDENCE", "24.3 guardrails: 'never release holdback funds without accepted evidence'; B4-1.2-05: after 'Form 1004D or an acceptable completion alternative' the 'lender must release the final draw'", (i) => i.op === "release" && (flag(i, "without_evidence") || flag(i, "force")), "the final draw is released only after accepted completion evidence"),
      never("SAFETY_ITEM_NOT_POSTPONABLE", "24.3 guardrails: 'never waive a safety-related repair'; B4-1.2-05 postponed improvements are contract items that never affect safety, soundness, structural integrity or the occupancy permit", (i) => i.op === "establish" && Array.isArray(i.items) && (i.items as Deficiency[]).some((d) => d.safety_related), "a safety-related item cannot enter a holdback — complete before sale")] },
  // Integrations: HOA / management-company outreach for the questionnaire (Form 1076 optional) and its equivalents; `op=receive` records intake (docs_as_of arms SM_PROJECT_DOCS_AGE_120).
  { name: "requestProjectDocs", kind: "act", handler: compute((i, ctx) => { const id = appId(i, ctx);
      if (i.op === "receive") { need(i, "documents"); const docs = (i.documents as ProjectDoc[]).map((d) => ({ ...d, dated: D(String(d.dated)) })); const r = receiveProjectDocs(ctx.events, id, docs, at(i, ctx), ctx.actor); return { docs_as_of: r.docs_as_of, received: docs.length }; }
      need(i, "documents"); const e = requestProjectDocs(ctx.events, id, i.documents as ProjectDoc["kind"][], at(i, ctx), { hoa_contact: (i.hoa_contact as string | undefined) ?? null, channel: (i.channel as "email" | "portal" | "vendor" | undefined) ?? "email", actor: ctx.actor }); return { requested: e.payload.documents, event: e.type }; }) },
  // Integrations: extraction of questionnaire / budget / reserve study / inspection fields into `project_reviews` with confidence and page references; inspection reports are classified (critical or routine) and marked reviewed.
  { name: "extractProjectData", kind: "write", handler: compute((i, ctx, rt) => { const id = appId(i, ctx); need(i, "fields");
      const fields = i.fields as Record<string, unknown>; const reports = Array.isArray(i.inspection_reports) ? (i.inspection_reports as InspectionReport[]).map((r) => ({ ...r, date: D(String(r.date)), reviewed: r.reviewed ?? true, critical: classifyInspection({ ...r, date: D(String(r.date)) }).critical })) : [];
      const prior = latest<ProjectReview>(rt, "project_reviews", id); const row = { ...(prior ?? { project_review_id: `pr-${id}`, application_id: id, status: "pending_docs" }), extracted: fields, extraction_confidence: (i.confidence as Record<string, number> | undefined) ?? {}, page_references: (i.page_references as Record<string, string> | undefined) ?? {}, inspection_reports: reports, extracted_at: at(i, ctx) };
      put(rt, ctx, "project_reviews", (prior as { project_review_id?: string } | null)?.project_review_id ?? `pr-${id}`, row); return { fields: Object.keys(fields), inspection_reports: reports.map((r) => ({ date: r.date, critical: r.critical, reviewed: r.reviewed })) }; }) },
  // R4: every B4-2.1-03 / B4-2.2-01 / -02 test with the dated rule set; `op=start` opens the review (3-year look-back); `op=validity` checks B4-2.1-01 at the note date; `op=consummate` the consummate guard; `op=tests` a dry run.
  { name: "runProjectEligibility", kind: "act", ruleSetVersion: "fnma.selling.2026-09-02", handler: compute((i, ctx, rt) => { const id = appId(i, ctx); const rules = rulesFor(i, ctx, rt); const op = (i.op as string | undefined) ?? "run";
      if (op === "consummate") { need(i, "note_date"); const pr = latest<ProjectReview>(rt, "project_reviews", id); const pe = latest<PropertyEligibilityReview>(rt, "property_eligibility_reviews", id); return consummateGate({ property_result: pe?.result ?? null, project_review: pr && pr.review_type ? pr : null, note_date: dateOf(i, "note_date"), repairs: (pe?.repairs ?? []) as Repair[], safety_repairs_completed: flag(i, "safety_repairs_completed"), safety_repairs_scheduled_before_delivery: flag(i, "safety_repairs_scheduled_before_delivery") }); }
      const f = facts<ProjectFacts>(i); if (typeof f.units_total !== "number" || !f.project_type) throw new RangeError("24.3 runProjectEligibility facts need project_type and units_total");
      const norm: ProjectFacts = { ...f, inspection_reports: (f.inspection_reports ?? []).map((r) => ({ ...r, date: D(String(r.date)) })) };
      if (op === "tests") { const sel = selectReviewType(norm, rules); return { selection: sel, ...runProjectTests(norm, rules, civilDate(at(i, ctx)), sel), rule_set_version: rules.rule_set_version }; }
      let review = latest<ProjectReview>(rt, "project_reviews", id);
      if (op === "start" || !review || !review.review_type) { const s = startProjectReview(ctx.events, { application_id: id, facts: norm, rules, started_at: at(i, ctx), ...(review?.project_review_id ? { project_review_id: review.project_review_id } : {}) }); review = { ...(review ?? {}), ...s.review }; put(rt, ctx, "project_reviews", review.project_review_id, review); if (op === "start") return { review, selection: s.selection, started: !!s.event }; }
      if (op === "validity") { need(i, "note_date"); const v = checkProjectValidity(ctx.events, review, dateOf(i, "note_date"), at(i, ctx), ctx.actor); if (v.event) put(rt, ctx, "project_reviews", v.review.project_review_id, v.review); return { valid: v.valid, reason: v.reason, status: v.review.status, expires_at: v.review.expires_at }; }
      const r = runProjectEligibility(ctx.events, review, norm, rules, at(i, ctx), ctx.actor); put(rt, ctx, "project_reviews", r.review.project_review_id, r.review);
      return { review: r.review, selection: r.selection, result: r.tests.result, reserve: r.tests.reserve, ineligible_reasons: r.tests.ineligible_reasons, unreviewed_inspections: r.tests.unreviewed_inspections, events: r.events.map((e) => e.type), rule_set_version: rules.rule_set_version }; }),
    guardrails: [never("SPECIAL_ASSESSMENT_NEVER_ROUTINE", "24.3 guardrails: 'never treat a special assessment tied to a safety/habitability repair as routine'; B4-2.1-03: 'If the special assessment is associated with a critical repair and the issue is not remediated, the project is ineligible'", (i) => flag(i, "treat_assessment_as_routine") || flag(i, "override_special_assessment"), SA_CRITICAL_REASON + " — the assessment cannot be reclassified as routine"),
      never("UNREVIEWED_INSPECTION_NEVER_ELIGIBLE", "24.3 guardrails: 'never mark a project eligible with an unreviewed in-window inspection report'; B4-2.1-03 three-year look-back", (i) => flag(i, "skip_inspection_review") || flag(i, "mark_eligible") && Array.isArray((i.facts as ProjectFacts | undefined)?.inspection_reports) && inspectionsInWindow(((i.facts as ProjectFacts).inspection_reports ?? []).map((r) => ({ ...r, date: D(String(r.date)) })), D(str(i, "at").slice(0, 10) || "2026-09-02")).some((r) => !r.reviewed), "an in-window inspection report must be obtained and reviewed before the project can be eligible")] },
  // Integrations (CPM, UI-only): the AI-prepared certification sheet with source-document references, queued to the fnma_portal_operator (SLA 1 business_days_creditor); the agent never keys CPM.
  { name: "prepareCpmSheet", kind: "act", handler: compute((i, ctx, rt) => { const id = appId(i, ctx); const review = latest<ProjectReview>(rt, "project_reviews", id); if (!review || !review.review_type) throw new RangeError("no project review to certify (runProjectEligibility first)"); const f = facts<ProjectFacts>(i);
      const sheet = prepareCpmSheet(review, f, (i.source_refs as Record<string, string> | undefined) ?? {}); const esc = rt.escalations.open({ kind: "human_portal_task", ownerRole: "fnma_portal_operator", applicationId: id, payload: { task: "cpm_certification", project_review_id: review.project_review_id, sheet: sheet.fields, sla: sheet.sla, ui_only: true } }, ctx.actor); return { sheet, escalation_id: esc.id, operator_role: sheet.operator_role }; }),
    guardrails: [never("CPM_NEVER_KEYED_BY_AGENT", "24.3 guardrails: 'never key CPM itself'; Consolidated Technology Guide / 00b-orig F10: CPM is UI-only", (i) => flag(i, "submit_to_cpm") || flag(i, "key_cpm") || str(i, "op") === "submit", "the agent prepares the certification sheet; the fnma_portal_operator keys CPM under partner credentials")] },
  // Integrations (CPM, UI-only) / T12: the operator records the CPM IDs, status and expiry (Unavailable → ineligible regardless of the lender's analysis; certified → the review completes and the validity clocks arm).
  { name: "recordCpmResult", kind: "act", humanOnly: true, humanRoles: ["fnma_portal_operator"], handler: compute((i, ctx, rt) => { const id = appId(i, ctx); need(i, "cpm_status"); const review = latest<ProjectReview>(rt, "project_reviews", id); if (!review || !review.review_type) throw new RangeError("no project review for the CPM record (runProjectEligibility first)");
      const snap: CpmSnapshot = { cpm_status: str(i, "cpm_status") as CpmSnapshot["cpm_status"], cpm_project_id: (i.cpm_project_id as string | undefined) ?? null, cpm_phase_id: (i.cpm_phase_id as string | undefined) ?? null, cpm_certification_id: (i.cpm_certification_id as string | undefined) ?? null, cpm_cert_expires_on: typeof i.cpm_cert_expires_on === "string" ? D(i.cpm_cert_expires_on) : null, note_date: typeof i.note_date === "string" ? D(i.note_date) : null, comments: (i.comments as string | undefined) ?? null };
      const r = recordCpmStatus(ctx.events, review, snap, ctx.actor, at(i, ctx)); put(rt, ctx, "project_reviews", r.review.project_review_id, r.review); return { review: r.review, result: r.review.result, status: r.review.status, expires_at: r.review.expires_at, project_type_code: r.review.project_type_code, events: r.events.map((e) => e.type) }; }),
    guardrails: [needsRole("CPM_NEVER_KEYED_BY_AGENT", "24.3 guardrails: 'never key CPM itself' — CPM certification entry is the fnma_portal_operator's (UI-only); 'A lender's certification and related entries are visible only to the lender that certified the project/phase.'", () => true, ["fnma_portal_operator"], "CPM results are recorded by the fnma_portal_operator who keyed them")] },
  // R6 / T9: the manufactured-housing verification set → `mh_verifications` row, SFC 859 for MH Advantage, `mh.verification.completed{result}`.
  { name: "verifyMh", kind: "act", handler: compute((i, ctx, rt) => { const id = appId(i, ctx); const f = facts<MhFacts>(i); if (!Array.isArray(f.hud_label_numbers) || !f.width || !f.occupancy) throw new RangeError("24.3 verifyMh facts need hud_label_numbers, width and occupancy");
      const r = verifyMh(ctx.events, id, { ...f, built_on: f.built_on ? D(String(f.built_on)) : null }, at(i, ctx), rulesFor(i, ctx, rt), ctx.actor); put(rt, ctx, "mh_verifications", r.verification.verification_id, r.verification); return { verification: r.verification, result: r.verification.result, special_feature_codes: r.verification.special_feature_codes }; }) },
  // AI agent design: the decision record {application_id, property_class, checks[], condition_route, repairs[], holdback, project{…}, rule_set_version (dated switches shown), model_version, prompt_version, rationale, confidence}.
  { name: "writeDecision", kind: "act", ruleSetVersion: "fnma.selling.2026-09-02", handler: compute((i, ctx, rt) => { const id = appId(i, ctx); const rules = rulesFor(i, ctx, rt);
      const d = writeDecision({ application_id: id, property: latest<PropertyEligibilityReview>(rt, "property_eligibility_reviews", id), project: (() => { const p = latest<ProjectReview>(rt, "project_reviews", id); return p && p.review_type ? p : null; })(), holdback: latest<EscrowHoldback>(rt, "escrow_holdbacks", id), rules, model_version: str(i, "model_version") || ctx.run?.modelVersion || "unversioned", prompt_version: str(i, "prompt_version") || ctx.run?.promptVersion || "unversioned", ...(typeof i.confidence === "number" ? { confidence: i.confidence } : {}), ...(typeof i.rationale === "string" && i.rationale ? { rationale: i.rationale } : {}) });
      ctx.decide({ agent: "valuation", action: "24.3.eligibility", rationale: d.rationale, ruleSetVersion: d.rule_set_version, applicationId: id, loanId: ctx.loanId, subject: { kind: "application", id }, ruleCode: "24.3", confidence: d.confidence, modelVersion: d.model_version, promptVersion: d.prompt_version }); return d; }) },
  // Escalations: fnma_portal_operator (CPM; SLA 1 business_days_creditor), officer (PERS submissions and exception requests; SLA 5 BD), licensed_specialist (state-licensed reviewer), human_agent on request, appraiser (completion reports).
  { name: "fileEscalation", kind: "act", handler: compute((i, ctx, rt) => { need(i, "kind"); const role = str(i, "kind"); const kind = ESCALATION_KIND[role]; if (!kind) throw new RangeError(`24.3 escalates to ${Object.keys(ESCALATION_KIND).join("/")}, not ${role}`);
      const sla = role === "fnma_portal_operator" ? "+1 business_days_creditor" : role === "officer" ? "+5 business_days_creditor" : null;
      const e = rt.escalations.open({ kind, ownerRole: role, applicationId: appId(i, ctx), ...(ctx.loanId ? { loanId: ctx.loanId } : {}), ...(typeof i.severity === "string" ? { severity: i.severity } : {}), payload: { reason: str(i, "reason") || null, sla, ...((i.payload as Record<string, unknown> | undefined) ?? {}) } }, ctx.actor); return { escalation_id: e.id, kind: e.kind, owner_role: e.ownerRole, sla }; }),
    guardrails: [guard("PERS_IS_OFFICER_REQUEST", "24.3 automation class: 'officer for project-ineligibility exceptions requested from Fannie Mae (PERS)'", (i) => (str(i, "reason") === "pers_submission" && str(i, "kind") !== "officer" ? "PERS submissions and exception requests go to the partner officer" : undefined))] },
]);

export { HoldbackRefused, CpmRefused };
