/**
 * §20.3 process-owned tools — bus tools for 20.3 defined with `defineTools("20.3", <agent>, defs)` from
 * ../tools.ts. Every tool string must be one spec/registry/agents.json names for 20.3; src/app/tools.test.ts refuses
 * the rest. Spread by ./index.ts.
 *
 * The `intake` agent (with `borrower-comms`) runs the pre-application conversation over the `leads` aggregate
 * (src/domain/leads-pricing/ops-20-3.ts; the lead lives in the entity store under `leads`, quotes under 20.4's
 * `pricing_quotes`, 20.1 opportunities under `refi_opportunities`). The seven registry tools carry the paragraph's
 * longer list as `op`s: deliverDisclosure (start / deliver / co_preuse / are_you_human / transfer_to_human),
 * authenticate (otp / portal_login / auth_script / request_onfile), captureConsent (esign capture + demonstration,
 * tcpa informational, credit_authorization), orderSoftPull (order / receive), explainProgram (criteria / general_rates /
 * screen / communicate_decline / demographics / prequal request / provide_information / issue_letter / record_trid_item /
 * convert / request_decision / decision_record), getBenefit, requestQuote (request_review / review / present / expire).
 * Guardrails encode the spec's sentences: no substantive exchange before disclosure; no on-file data before L2; no soft
 * pull without authorization; no decline language; no particular terms before MLO review; no demographic/marital/
 * childbearing questions; no document requests before the LE; no promises; truthful "are you human?"; the review is the
 * `mlo_of_record`'s act; a spoken E-SIGN "yes" is void.
 *
 * DELTA-11 / DELTA-13 (32.14, the anonymous minute): explainProgram gains `set_fact` (one rule-6 fact → `lead.goal.set` /
 * `lead.state.set` / `lead.estimate.set`; anything else L0_FACTS_ONLY), `next_step`, `link_party` (`lead.linked{party_id}`),
 * `show_range` (rule 7's published range as an advertisement through 20.2's checklist → `lead.range.shown`, or
 * `{range: null, refused: RANGE_CONTENT_CHECK}`), `defer_intent` (`intent.deferred`) and `close` (`lead.closed{reason}`).
 */
import { createHash, randomUUID } from "node:crypto";
import { defineTools, compute, never, needsRole, str, flag, type ToolDef, type ToolInput, type ToolRuntime } from "../tools.ts";
import type { CommandContext } from "../commands.ts";
import { completeHumanTransfer } from "../../domain/leads-pricing/ops-20-3.ts";   // 32.13 T-X-08 delta: `human.transfer.completed`
import { plainDate as D } from "../../kernel/calendar/date.ts";
import type { PricingQuote, MloReview } from "../../domain/leads-pricing/ops-20-4.ts";
import { activeSheetAt, type RateSheet } from "../../domain/leads-pricing/ops-20-4.ts";
import { type Lead, type LeadChannel, type InteractionChannel, type AuthMethod, type TridItemKey, type TridSource, type BenefitInput, IntakeRefused, createLead, startInteraction, deliverDisclosure, answerQuestion, answerAreYouHuman, transferToHuman, coPreuseNoticeRequired, deliverCoPreuseNotice, authenticate, requestOnFileData,
  informationalTcpaConsent, captureEsignConsent, completeEsignDemonstration, esignBeforeLeGate, esignGateFacts, leChannelFor, captureCreditAuthorization, orderSoftPull, receiveSoftPull, explainProgram, generalRateRange, screenUtterance, communicateDecline, requestDemographics, preApplicationCheck,
  requestPrequalification, provideInformation, issuePrequalLetter, prequalLetterPayload, issuePreapprovalLetter, preapprovalLetterPayload, PREAPPROVAL_LETTER_TEMPLATE, type PrequalKind, recordTridItem, convertToApplication, requestDecision, expireLead, getBenefit, assignMlo, requestTermsReview, completeMloReview, presentTerms, leadDecisionRecord, PREQUAL_LETTER_TEMPLATE, civilDate,
  setFact, linkParty, showRange, deferIntent, closeLead, rangeAdvertisement, nextEntryStep, entryFacts, assertL0Fact, l0ProhibitedKeys, transactionTypeOf, GOAL_TRANSACTION_TYPES, PROGRAM_MAX_LTV_PCT, type EntryFact, type EntryTransactionType, type ContractStatus, type EntryOccupancy } from "../../domain/leads-pricing/ops-20-3.ts";

/** Missing-input guard: a tool executed without its subject refuses with a RangeError (never a TypeError). */
const need = (i: ToolInput, ...keys: string[]): void => { const gaps = keys.filter((k) => i[k] === undefined || i[k] === null || i[k] === ""); if (gaps.length) throw new RangeError(`20.3 tool needs ${gaps.join(", ")}`); };
const at = (i: ToolInput, ctx: CommandContext, key = "at"): string => str(i, key) || ctx.now;
const cents = (v: unknown): bigint => (typeof v === "bigint" ? v : BigInt(String(v ?? "0").replace(/[^0-9-]/g, "") || "0"));
const loadLead = (i: ToolInput, rt: ToolRuntime): Lead => { need(i, "lead_id"); const r = rt.store.get("leads", str(i, "lead_id")); if (!r) throw new RangeError(`no lead ${str(i, "lead_id")} in the entity store (deliverDisclosure{op=create} first)`); return r.data as unknown as Lead; };
const saveLead = (rt: ToolRuntime, ctx: CommandContext, lead: Lead): Lead => rt.store.put("leads", lead.lead_id, lead as unknown as Record<string, unknown>, ctx.actor, ctx.now).data as unknown as Lead;
const loadQuote = (i: ToolInput, rt: ToolRuntime): PricingQuote => { need(i, "quote_id"); const q = (i.quote as PricingQuote | undefined) ?? (rt.store.get("pricing_quotes", str(i, "quote_id"))?.data as unknown as PricingQuote | undefined); if (!q) throw new RangeError(`no pricing quote ${str(i, "quote_id")} (20.4 priceQuote first)`); return q; };
const summary = (lead: Lead): Record<string, unknown> => ({ lead_id: lead.lead_id, status: lead.status, assurance_level: lead.assurance_level, application_id: lead.application_id, trid_application_at: lead.trid_application_at, expires_on: lead.expires_on });
const textOf = (i: ToolInput): string => [str(i, "text"), str(i, "draft"), str(i, "question")].join(" ");
/** DELTA-11: the `set_fact` input `{fact: {kind, …}}` (or `{step, value}`) → one typed rule-6 fact; cents arrive as decimal strings; the tile ids (buy / lower_rate / cash_out) map onto transaction types. */
const entryFactIn = (i: ToolInput): EntryFact => {
  const f = (i.fact && typeof i.fact === "object" && !Array.isArray(i.fact) ? i.fact : {}) as Record<string, unknown>;
  const value = (i.value && typeof i.value === "object" && !Array.isArray(i.value) ? i.value : {}) as Record<string, unknown>;
  const kind = assertL0Fact(String(f["kind"] ?? i.step ?? "")); const s = (k: string): string => String(f[k] ?? value[k] ?? (typeof i.value === "string" ? i.value : "")).trim();
  const c = (k: string): string | null => { const v = f[k] ?? value[k]; return v === undefined || v === null || v === "" ? null : String(cents(v)); };
  switch (kind) {
    case "goal": { const g = s("transaction_intent") || s("goal") || s("transaction_type"); return { kind, transaction_intent: ((GOAL_TRANSACTION_TYPES as Record<string, EntryTransactionType>)[g] ?? g) as EntryTransactionType }; }
    case "contract": return { kind, contract_status: s("contract_status") as ContractStatus };
    case "occupancy": return { kind, occupancy: s("occupancy") as EntryOccupancy };
    case "state": return { kind, consumer_state: s("consumer_state") || s("state") };
    case "estimate": return { kind, value_estimate_cents: c("value_estimate_cents"), stated_existing_balance_cents: c("stated_existing_balance_cents"), price_range_cents: c("price_range_cents"), down_payment_cents: c("down_payment_cents") };
  }
};

export const TOOLS_20_3: readonly ToolDef[] = defineTools("20.3", "intake", [
  // Rule 1 / T1, T9, T11, rule 12: the first-contact disclosure (state variant), the Colorado pre-use line, the truthful "are you human?" answer and the warm transfer.
  { name: "deliverDisclosure", kind: "act", handler: compute((i, ctx, rt) => { const op = str(i, "op") || "deliver"; const when = at(i, ctx);
      if (op === "create") { need(i, "lead_id", "partner_id", "partner_name", "channel"); const r = createLead(ctx.events, { lead_id: str(i, "lead_id"), partner_id: str(i, "partner_id"), partner_name: str(i, "partner_name"), channel: str(i, "channel") as LeadChannel, at: when, source_touch_id: (i.source_touch_id as string | undefined) ?? null, opportunity_id: (i.opportunity_id as string | undefined) ?? null, loan_id: (i.loan_id as string | undefined) ?? null, party_id: (i.party_id as string | undefined) ?? null, prospect: (i.prospect as Lead["prospect"] | undefined) ?? null, consumer_state: (i.consumer_state as string | undefined) ?? null, property_state: (i.property_state as string | undefined) ?? null, transaction_intent: (i.transaction_intent as Lead["transaction_intent"] | undefined) ?? "undecided", time_zone: str(i, "time_zone") || "America/New_York", mlo_time_zone: str(i, "mlo_time_zone") || str(i, "time_zone") || "America/New_York" });
        saveLead(rt, ctx, r.lead); return { ...summary(r.lead), event_id: r.event.id }; }
      let lead = loadLead(i, rt);
      if (op === "start") { need(i, "interaction_id", "channel"); const r = startInteraction(ctx.events, lead, { interaction_id: str(i, "interaction_id"), channel: str(i, "channel") as InteractionChannel, started_at: when, ai: i.ai !== false, agent_run_id: (i.agent_run_id as string | undefined) ?? null }); saveLead(rt, ctx, r.lead);
        const co = coPreuseNoticeRequired(r.lead, civilDate(when, r.lead.time_zone)); return { ...summary(r.lead), interaction_id: r.interaction.interaction_id, ai: r.interaction.ai, state_rules_applied: r.interaction.state_rules_applied, disclosure_required: r.interaction.ai, co_preuse_notice: co, event_id: r.event.id }; }
      if (op === "co_preuse") { need(i, "notice_id", "public_notice_url"); const r = deliverCoPreuseNotice(ctx.events, lead, { at: when, notice_id: str(i, "notice_id"), public_notice_url: str(i, "public_notice_url") }); saveLead(rt, ctx, r.lead); return { ...summary(r.lead), text: r.text, gate_required: r.gate_required, event_id: r.event.id }; }
      if (op === "are_you_human") { need(i, "interaction_id"); const r = answerAreYouHuman(ctx.events, lead, { interaction_id: str(i, "interaction_id"), at: when }); saveLead(rt, ctx, r.lead); return { ...summary(r.lead), answer: r.answer, relogged_event_id: r.relogged.id }; }
      if (op === "transfer_to_human") { need(i, "interaction_id"); const r = transferToHuman(ctx.events, rt.escalations, lead, { interaction_id: str(i, "interaction_id"), at: when, reason: str(i, "reason") || "consumer_request", terms_to_be_discussed: flag(i, "terms_to_be_discussed") }); saveLead(rt, ctx, r.lead); return { ...summary(r.lead), escalation_id: r.escalation.id, owner_role: r.escalation.ownerRole, sla_seconds: r.sla_seconds }; }
      // 32.13 T-X-08 / SQ-30 (delta): the person joined — `human.transfer.completed`; the escalation closes under the joiner's own role when it was opened in this scope
      if (op === "human_joined") { need(i, "interaction_id", "human_agent_id"); const r = completeHumanTransfer(ctx.events, lead, { interaction_id: str(i, "interaction_id"), at: when, human_agent_id: str(i, "human_agent_id"), human_agent_name: str(i, "human_agent_name") || null, escalation_id: str(i, "escalation_id") || null }); saveLead(rt, ctx, r.lead);
        let escalation_completed = false; if (str(i, "escalation_id") && ctx.actor.kind === "human") { try { rt.escalations.complete(str(i, "escalation_id"), ctx.actor); escalation_completed = true; } catch { escalation_completed = false; } }
        return { ...summary(r.lead), interaction_id: str(i, "interaction_id"), human_agent_id: str(i, "human_agent_id"), escalation_completed, event_id: r.event.id }; }
      if (op === "answer") { need(i, "interaction_id", "question"); const r = answerQuestion(ctx.events, lead, { interaction_id: str(i, "interaction_id"), question: str(i, "question"), at: when, substantive: i.substantive !== false }); saveLead(rt, ctx, r.lead); return { ...summary(r.lead), allowed: true }; }
      need(i, "interaction_id"); const r = deliverDisclosure(ctx.events, lead, { interaction_id: str(i, "interaction_id"), at: when, notice_id: (i.notice_id as string | undefined) ?? null, ...(str(i, "version") ? { version: str(i, "version") } : {}), ...(str(i, "reason") ? { reason: str(i, "reason") as "first_contact" } : {}) }); lead = saveLead(rt, ctx, r.lead);
      return { ...summary(lead), text: r.text, state_variant: r.state_variant, consent_id: r.consent.consent_id, version: r.consent.version, event_ids: r.events.map((e) => e.id) }; }),
    guardrails: [never("TRUTHFUL_ARE_YOU_HUMAN", "20.3 rule 1 / guardrails: truthful answer to \"are you human?\" (Utah request rule; UDAAP)", (i) => str(i, "op") === "are_you_human" && flag(i, "claim_human"), "the assistant never claims to be a person"),
      never("HUMAN_PATH_ALWAYS_OPEN", "20.3 rule 12: \"person\" at any time → warm transfer to a human_agent (SLA 10 s per 11.1)", (i) => str(i, "op") === "transfer_to_human" && flag(i, "deny_transfer"), "a request for a person is never refused")] },
  // Rule 2 / T2: L1 OTP for prospects, L2 portal login / 4.x script for existing borrowers; on-file loan/servicing data is withheld below L2.
  { name: "authenticate", kind: "act", handler: compute((i, ctx, rt) => { const lead = loadLead(i, rt); const when = at(i, ctx); const op = str(i, "op") || "authenticate";
      if (op === "request_onfile") { need(i, "what"); const r = requestOnFileData(ctx.events, lead, { what: str(i, "what"), at: when, ...(str(i, "interaction_id") ? { interaction_id: str(i, "interaction_id") } : {}), onfile: () => (i.onfile as Record<string, unknown> | undefined) ?? {} }); saveLead(rt, ctx, r.lead); return { ...summary(r.lead), provided: r.provided }; }
      need(i, "method"); const r = authenticate(ctx.events, lead, { method: str(i, "method") as AuthMethod, at: when, evidence: (i.evidence as Record<string, unknown> | undefined) ?? {} }); saveLead(rt, ctx, r.lead); return { ...summary(r.lead), level: r.level, event_id: r.event.id }; }),
    guardrails: [never("NO_ONFILE_DATA_BEFORE_L2", "20.3 rule 2 / SM_LEAD_AUTH_BEFORE_DISCLOSURE_GATE: on-file loan data may be discussed only at L2 (portal login or the 4.x authentication script); a claimed identity is never an authentication", (i) => str(i, "op") === "request_onfile" && flag(i, "bypass_authentication"), "on-file data is withheld until assurance_level ≥ L2 (sev 2 if bypassed)")] },
  // Rule 8 / 10 / 2 / T3, T8: E-SIGN via the 7.4 flow with the origination scopes (a spoken "yes" is void), informational TCPA consent from the number given, the soft-pull credit authorization.
  { name: "captureConsent", kind: "act", handler: compute((i, ctx, rt) => { const lead = loadLead(i, rt); const when = at(i, ctx); need(i, "kind"); const kind = str(i, "kind");
      if (kind === "esign") { const op = str(i, "op") || "capture";
        if (op === "demonstrate") { need(i, "consent_id"); const r = completeEsignDemonstration(ctx.events, lead, { consent_id: str(i, "consent_id"), link_opened_at: (i.link_opened_at as string | undefined) ?? null, token_entered_at: (i.token_entered_at as string | undefined) ?? null, token_ok: flag(i, "token_ok"), ...(str(i, "ip") ? { ip: str(i, "ip") } : {}), ...(str(i, "user_agent") ? { user_agent: str(i, "user_agent") } : {}) }); saveLead(rt, ctx, r.lead);
          return { ...summary(r.lead), consent_id: r.consent.consent_id, status: r.consent.status, scope: r.consent.scope, verified: r.verified, reason: r.reason, le_channel: leChannelFor(r.lead, r.consent.party_id), gate: esignBeforeLeGate(esignGateFacts(r.lead)) }; }
        need(i, "consent_id", "scopes", "disclosure_version", "captured_via"); const r = captureEsignConsent(ctx.events, lead, { consent_id: str(i, "consent_id"), ...(str(i, "party_id") ? { party_id: str(i, "party_id") } : {}), scopes: i.scopes as string[], captured_via: str(i, "captured_via") as "portal" | "ai_chat_link" | "voice", disclosure_version: str(i, "disclosure_version"), clicked_at: when, ...(str(i, "ip") ? { ip: str(i, "ip") } : {}), ...(str(i, "user_agent") ? { user_agent: str(i, "user_agent") } : {}) }); saveLead(rt, ctx, r.lead);
        return { ...summary(r.lead), consent_id: r.consent.consent_id, status: r.consent.status, scope: r.consent.scope, verification_email: "NTC_ESIGN_VERIFICATION_EMAIL" }; }
      if (kind === "tcpa_voice" || kind === "tcpa_sms") { need(i, "consent_id", "number"); const r = informationalTcpaConsent(ctx.events, lead, { consent_id: str(i, "consent_id"), kind, number: str(i, "number"), at: when, ...(str(i, "party_id") ? { party_id: str(i, "party_id") } : {}) }); saveLead(rt, ctx, r.lead); return { ...summary(r.lead), consent_id: r.consent.consent_id, scope: r.consent.scope, marketing: false, pewc_flow: "20.2" }; }
      if (kind === "credit_authorization") { need(i, "authorization_id", "text_version", "channel"); const r = captureCreditAuthorization(ctx.events, lead, { authorization_id: str(i, "authorization_id"), kind: (str(i, "authorization_kind") || "soft_prequal") as "soft_prequal" | "hard_application", ...(str(i, "party_id") ? { party_id: str(i, "party_id") } : {}), text_version: str(i, "text_version"), signature_kind: (str(i, "signature_kind") || "esign_click_typed_name") as "esign_click_typed_name" | "wet_ink", captured_at: when, channel: str(i, "channel") as InteractionChannel, evidence: (i.evidence as Record<string, unknown> | undefined) ?? {}, end_user: str(i, "end_user") || "partner", consumer_initiated: i.consumer_initiated !== false, consumer_entered_identity: i.consumer_entered_identity !== false }); saveLead(rt, ctx, r.lead);
        return { ...summary(r.lead), authorization_id: r.authorization.authorization_id, kind: r.authorization.kind, permissible_purpose: r.authorization.permissible_purpose, end_user: r.authorization.end_user, text_version_hash: r.authorization.text_version_hash, trid_ssn_for_credit: r.lead.trid_items.ssn_for_credit.present }; }
      throw new RangeError(`captureConsent kind ${kind} is not one of esign/tcpa_voice/tcpa_sms/credit_authorization`); }),
    guardrails: [never("ESIGN_7001C6_ORAL_CONSENT_VOID", "15 U.S.C. 7001(c)(6); 20.3 rule 8: a chat/voice \"yes\" never counts — the link is sent instead", (i) => str(i, "kind") === "esign" && str(i, "captured_via") === "voice", "an oral communication or a recording of one is not an electronic record for E-SIGN consent; send NTC_ESIGN_VERIFICATION_EMAIL"),
      never("MARKETING_PEWC_ONLY_VIA_20_2", "20.3 rule 10: marketing PEWC only through the 20.2 written flow", (i) => (str(i, "kind") === "tcpa_voice" || str(i, "kind") === "tcpa_sms") && flag(i, "marketing"), "a number given in the inquiry is prior express consent for informational contact about that inquiry only"),
      never("END_USER_IS_PARTNER", "15 U.S.C. 1681b(a)(3)(A); 20.3 data model: end_user = partner", (i) => str(i, "kind") === "credit_authorization" && str(i, "end_user") !== "" && str(i, "end_user") !== "partner", "the partner is the FCRA end user of every consumer report")] },
  // Rule 2 / 9 / T3: FCRA_1681B_A3_SOFT_PULL_PURPOSE_GATE — no soft pull without the consumer's soft_prequal authorization; the report links to it; a freeze is explained, never inferred against.
  { name: "orderSoftPull", kind: "act", handler: compute((i, ctx, rt) => { const lead = loadLead(i, rt); const when = at(i, ctx); const op = str(i, "op") || "order";
      if (op === "receive") { need(i, "report_id"); const r = receiveSoftPull(ctx.events, lead, { report_id: str(i, "report_id"), received_at: when, representative_score: i.representative_score === undefined || i.representative_score === null ? null : Number(i.representative_score), ...(str(i, "score_model") ? { score_model: str(i, "score_model") as "classic_fico" | "vantagescore_4" } : {}), frozen: flag(i, "frozen"), fraud_alert: flag(i, "fraud_alert") }); saveLead(rt, ctx, r.lead);
        return { ...summary(r.lead), report_id: r.report.report_id, authorization_id: r.report.authorization_id, tier: r.tier, frozen: r.report.frozen, freeze_instructions: r.freeze_instructions }; }
      const r = orderSoftPull(ctx.events, lead, { at: when, requested_by: (str(i, "requested_by") || "consumer") as "consumer" | "agent" }); saveLead(rt, ctx, r.lead); return { ...summary(r.lead), authorization_id: r.authorization_id, idempotency_key: r.authorization_id, event_id: r.event.id }; }),
    guardrails: [never("FCRA_1681B_A3_SOFT_PULL_PURPOSE_GATE", "15 U.S.C. 1681b(a)(3)(A); 20.3 guardrails: no soft pull without authorization (sev 1 if bypassed)", (i) => flag(i, "bypass_authorization"), "the pull needs credit_authorizations(kind=soft_prequal) captured by the consumer at ≥ L1 with end_user=partner"),
      never("NO_PRESCREEN", "20.1 / 15 U.S.C. 1681b(c): a soft pull to select borrowers is a prescreen — never here", (i) => str(i, "requested_by") === "agent" && !flag(i, "consumer_request_logged"), "the request must be consumer-initiated and logged")] },
  // Rule 3 / 4 / 5 / 6 / T5, T6, T12: information-giving (criteria, general rate ranges), the decline classifier, the loud-failing communicateDecline, no demographics at lead stage, prequalification and the letter, six-item recording and the conversion.
  { name: "explainProgram", kind: "act", handler: compute((i, ctx, rt) => { const op = str(i, "op") || "criteria"; const when = at(i, ctx);
      if (op === "criteria") return explainProgram({ transaction_type: (str(i, "transaction_type") || "limited_cash_out") as "purchase" | "limited_cash_out" | "cash_out", ...(str(i, "occupancy") ? { occupancy: str(i, "occupancy") } : {}) });
      if (op === "general_rates") { const sheet = (i.sheet as RateSheet | undefined) ?? activeSheetAt(rt.store.list("rate_sheets").map((r) => r.data as unknown as RateSheet), when); if (!sheet) throw new RangeError("no rate sheet in force (20.4 publishRateSheet) — general information only, no figures"); return generalRateRange(sheet, str(i, "product_code") || "FRM30"); }
      if (op === "demographics") { const lead = loadLead(i, rt); return requestDemographics(lead); }
      const lead = loadLead(i, rt);
      // DELTA-11 (32.14 S1): one rule-6 fact per call → `lead.goal.set` / `lead.state.set` / `lead.estimate.set`; anything else L0_FACTS_ONLY (guardrail + domain), nothing written
      if (op === "set_fact") { const r = setFact(ctx.events, lead, entryFactIn(i), when); saveLead(rt, ctx, r.lead); const tt = transactionTypeOf(r.lead);
        return { ...summary(r.lead), step: r.step, next_step: r.next_step, facts: entryFacts(r.lead), ...(r.step === "estimate" && tt ? { max_ltv_pct: PROGRAM_MAX_LTV_PCT[tt] } : {}), event_id: r.event.id }; }
      if (op === "next_step") return { ...summary(lead), next_step: nextEntryStep(lead), facts: entryFacts(lead) };
      // DELTA-11 (32.14 S3): the L1 link at verify — `lead.linked{party_id}`; the lead is linked, never copied
      if (op === "link_party") { need(i, "party_id"); const r = linkParty(ctx.events, lead, { party_id: str(i, "party_id"), at: when, method: str(i, "method") || null, session_id: str(i, "session_id") || null }); saveLead(rt, ctx, r.lead); return { ...summary(r.lead), party_id: r.lead.party_id, event_id: r.event.id }; }
      // DELTA-11 (32.14 S2): rule 7's published range as an advertisement (APR beside each rate, the not-a-commitment footer) through 20.2's checklist → `lead.range.shown`, or `{range: null, refused: RANGE_CONTENT_CHECK}`
      if (op === "show_range") { const sheet = (i.sheet as RateSheet | undefined) ?? activeSheetAt(rt.store.list("rate_sheets").map((r) => r.data as unknown as RateSheet), when); if (!sheet) throw new RangeError("no rate sheet in force (20.4 publishRateSheet) — general information only, no figures");
        const partner_nmlsr_id = str(i, "partner_nmlsr_id") || String(rt.store.get("partners", lead.partner_id)?.data["nmlsr_id"] ?? "");
        const ad = rangeAdvertisement(sheet, { product_code: str(i, "product_code") || "FRM30", partner_name: lead.partner_name, partner_nmlsr_id, at: when, time_zone: lead.time_zone, ...(i.representative_loan_cents !== undefined && i.representative_loan_cents !== null ? { representative_loan_cents: cents(i.representative_loan_cents) } : {}) });
        const checklist_run_id = str(i, "checklist_run_id") || randomUUID();
        rt.store.put("content_checklist_runs", checklist_run_id, { checklist_run_id, lead_id: lead.lead_id, rate_sheet_id: sheet.rate_sheet_id, product_code: ad.product_code, channel: "portal", campaign_kind: "general_advertising", text: ad.text, checklist: ad.checklist, failures: [...ad.failures], passes: ad.passes, apr_source: ad.apr_source, representative_loan_cents: String(ad.representative_loan_cents), at: when }, ctx.actor, ctx.now);
        const range = { product_code: ad.product_code, product_label: ad.product_label, low_pct: ad.low_pct, high_pct: ad.high_pct, apr_low_pct: ad.apr_low_pct, apr_high_pct: ad.apr_high_pct, apr_source: ad.apr_source, rate_sheet_id: sheet.rate_sheet_id, text: ad.text, checklist_run_id, personal_terms: false as const };
        if (!ad.passes) return { ...summary(lead), range: null, refused: "RANGE_CONTENT_CHECK", failures: [...ad.failures], checklist_run_id, checklist: ad.checklist, event_id: null };
        const r = showRange(ctx.events, lead, { at: when, product_code: range.product_code, rate_sheet_id: range.rate_sheet_id, low_pct: range.low_pct, high_pct: range.high_pct, apr_low_pct: range.apr_low_pct, apr_high_pct: range.apr_high_pct, apr_source: range.apr_source, checklist_run_id }); saveLead(rt, ctx, r.lead);
        return { ...summary(r.lead), range, refused: null, failures: [], checklist_run_id, checklist: ad.checklist, event_id: r.event.id }; }
      // DELTA-13 (32.14 S4): "Not yet" — `intent.deferred`; nothing ordered, pulled or converted
      if (op === "defer_intent") { const r = deferIntent(ctx.events, lead, { at: when, reason: str(i, "reason") || null }); saveLead(rt, ctx, r.lead); return { ...summary(r.lead), deferred: true, ordered: false, pulled: false, document: null, event_id: r.event.id }; }
      // 31.1 closed a state on the lead (32.14 S1 (i)) or the consumer walked away: `lead.closed{reason}` → closed_lost
      if (op === "close") { need(i, "reason"); const r = closeLead(ctx.events, lead, { at: when, reason: str(i, "reason") }); saveLead(rt, ctx, r.lead); return { ...summary(r.lead), closed_reason: r.lead.closed_reason, event_id: r.event.id }; }
      if (op === "screen") { need(i, "interaction_id", "draft"); const pre = preApplicationCheck(str(i, "draft")); if (!pre.allowed) throw new IntakeRefused(pre.findings[0]!.code.toUpperCase(), `${pre.findings[0]!.citation}: "${pre.findings[0]!.excerpt}" is never asked before application`);
        const r = screenUtterance(ctx.events, lead, { interaction_id: str(i, "interaction_id"), draft: str(i, "draft"), at: when, ...(i.value_cents !== undefined ? { value_cents: cents(i.value_cents) } : {}), ...(i.max_ltv_pct !== undefined ? { max_ltv_pct: Number(i.max_ltv_pct) } : {}) }); saveLead(rt, ctx, r.lead); return { ...summary(r.lead), blocked: r.blocked, matches: r.matches, delivered_text: r.delivered_text, regb_decline_risk_flag: false }; }
      if (op === "communicate_decline") return communicateDecline(ctx.events, lead, { at: when, ...(str(i, "interaction_id") ? { interaction_id: str(i, "interaction_id") } : {}) });
      if (op === "request_prequal") { need(i, "prequal_id"); const r = requestPrequalification(ctx.events, lead, { prequal_id: str(i, "prequal_id"), at: when, ...(str(i, "kind") === "preapproval" ? { kind: "preapproval" as PrequalKind } : {}), stated_income_cents: i.stated_income_cents === undefined ? null : cents(i.stated_income_cents), stated_assets_cents: i.stated_assets_cents === undefined ? null : cents(i.stated_assets_cents), value_estimate_cents: i.value_estimate_cents === undefined ? null : cents(i.value_estimate_cents), loan_amount_range_cents: Array.isArray(i.loan_amount_range_cents) ? [cents((i.loan_amount_range_cents as unknown[])[0]), cents((i.loan_amount_range_cents as unknown[])[1])] : null }); saveLead(rt, ctx, r.lead); return { ...summary(r.lead), prequal_id: r.prequal.prequal_id, basis: r.prequal.basis, ltv_estimate: r.prequal.ltv_estimate }; }
      if (op === "provide_information") { const r = provideInformation(ctx.events, lead, { at: when, ...(i.program_fit ? { program_fit: i.program_fit as Record<string, unknown> } : {}) }); saveLead(rt, ctx, r.lead); return { ...summary(r.lead), prequal_id: r.prequal.prequal_id, outcome: r.prequal.outcome }; }
      if (op === "issue_letter") { need(i, "letter_document_id"); const r = issuePrequalLetter(ctx.events, lead, { at: when, letter_document_id: str(i, "letter_document_id"), notice_id: (i.notice_id as string | undefined) ?? null }); saveLead(rt, ctx, r.lead);
        return { ...summary(r.lead), prequal_id: r.prequal.prequal_id, outcome: r.prequal.outcome, template: PREQUAL_LETTER_TEMPLATE, is_preapproval: r.is_preapproval, hmda_record_created: r.hmda_record_created, payload: prequalLetterPayload(r.lead, r.prequal, { prepared_on: D(when.slice(0, 10)), consumer_name: str(i, "consumer_name") || "[Consumer name]", partner_nmlsr_id: str(i, "partner_nmlsr_id") || "[NMLSR ID]" }) }; }
      if (op === "issue_preapproval_letter") {   // DELTA-01: the Reg C preapproval program — the letter after DU on a TBD property (32.3 P8; 23.1 TBD casefile; 28.3 preapproval=1)
        need(i, "du_casefile_id", "approved_amount_cents", "valid_until", "letter_document_id");
        const r = issuePreapprovalLetter(ctx.events, lead, { at: when, du_casefile_id: str(i, "du_casefile_id"), approved_amount_cents: cents(i.approved_amount_cents), valid_until: D(str(i, "valid_until")), letter_document_id: str(i, "letter_document_id"), application_id: str(i, "application_id") || ctx.applicationId || null, quote_id: str(i, "quote_id") || null, decision_id: str(i, "decision_id") || null, product: str(i, "product") || "30-year fixed", prequal_id: str(i, "prequal_id") || null }); saveLead(rt, ctx, r.lead);
        const payload = preapprovalLetterPayload(r.lead, r.prequal, { prepared_on: D(when.slice(0, 10)), consumer_name: str(i, "consumer_name") || "[Consumer name]", partner_nmlsr_id: str(i, "partner_nmlsr_id") || "[NMLSR ID]", product: str(i, "product") || "30-year fixed", ...(Array.isArray(i.general_conditions) ? { general_conditions: (i.general_conditions as unknown[]).map(String) } : {}) });
        const notice = rt.notices ? rt.notices.render({ templateCode: PREAPPROVAL_LETTER_TEMPLATE, ...(r.lead.application_id ? { applicationId: r.lead.application_id } : {}), ...(ctx.loanId ? { loanId: ctx.loanId } : {}), recipients: [], payload, asOf: D(when.slice(0, 10)), renderedDocumentId: str(i, "letter_document_id") }) : null;
        const text = notice?.rendered.text ?? null; const letterId = str(i, "letter_document_id"); const applicationId = r.lead.application_id; const partnerId = r.lead.partner_id; const leadId = r.lead.lead_id; const pq = r.prequal;
        // the rendered letter as a documents row the borrower can open, and the prequalifications row (0113 columns) when the lead's rows exist in the tables (20.3 keeps the lead in the entity store)
        const deferWrite = rt.services["deferWrite"] as ((fn: (q: { query: (sql: string, params?: unknown[]) => Promise<unknown> }) => Promise<void>) => void) | undefined;
        if (deferWrite && text !== null && /^[0-9a-f-]{36}$/i.test(letterId)) deferWrite(async (q) => {
          await q.query(`INSERT INTO documents (id, kind, sha256, byte_size, storage_uri, mime_type, application_id, retention_class, metadata) VALUES ($1, 'rendered_notice', $2, $3, $4, 'text/plain', $5, 'life_of_loan_plus_4y', $6::jsonb) ON CONFLICT (id) DO NOTHING`,
            [letterId, createHash("sha256").update(text).digest("hex"), Buffer.byteLength(text), `notice://${PREAPPROVAL_LETTER_TEMPLATE}/${letterId}`, applicationId, JSON.stringify({ title: "Preapproval letter", template: PREAPPROVAL_LETTER_TEMPLATE, notice_id: notice?.id ?? null, text, prequal_id: pq.prequal_id, valid_until: pq.valid_until })]);
          const partnerRow = (await q.query(`SELECT 1 FROM parties WHERE id::text = $1`, [partnerId])) as unknown[]; const partnerExists = Array.isArray(partnerRow) ? partnerRow.length > 0 : true;
          if (partnerExists && /^[0-9a-f-]{36}$/i.test(leadId)) {
            await q.query(`INSERT INTO leads (lead_id, partner_id, channel, party_id, transaction_intent, status, last_activity_at, expires_at, retention_class, application_id) VALUES ($1, $2, 'organic', $3, 'purchase', 'prequalified', $4, $5::date, 'regb_25m', $6) ON CONFLICT (lead_id) DO NOTHING`, [leadId, partnerId, r.lead.party_id, when, r.lead.expires_on, applicationId === leadId ? applicationId : null]);
            await q.query(`INSERT INTO prequalifications (prequal_id, lead_id, requested_at, basis, kind, du_casefile_id, approved_amount_cents, valid_until, outcome, letter_document_id, retention_class) VALUES ($1::uuid, $2, $3, $4, 'preapproval', $5, $6, $7::date, 'letter_issued', $8, 'regb_25m') ON CONFLICT (prequal_id) DO NOTHING`, [/^[0-9a-f-]{36}$/i.test(pq.prequal_id) ? pq.prequal_id : letterId, leadId, pq.requested_at, pq.basis, pq.du_casefile_id, String(pq.approved_amount_cents), pq.valid_until, letterId]);
          }
        });
        return { ...summary(r.lead), prequal_id: r.prequal.prequal_id, kind: "preapproval", outcome: r.prequal.outcome, template: PREAPPROVAL_LETTER_TEMPLATE, is_preapproval: true, hmda_preapproval_program: true, approved_amount_cents: String(r.prequal.approved_amount_cents), valid_until: r.prequal.valid_until, du_casefile_id: r.prequal.du_casefile_id, letter_document_id: letterId, notice_id: notice?.id ?? null, rendered_text: text, payload, event_id: r.event.id }; }
      if (op === "record_trid_item") { need(i, "item", "source", "value"); const r = recordTridItem(ctx.events, lead, { item: str(i, "item") as TridItemKey, source: str(i, "source") as TridSource, at: when, value: typeof i.value === "bigint" ? i.value : str(i, "value") }); saveLead(rt, ctx, r.lead); return { ...summary(r.lead), complete: r.complete, missing: r.missing, trid_application_at: r.trid_application_at }; }
      if (op === "convert" || op === "request_decision") { need(i, "transaction_type", "occupancy"); const c = { at: when, transaction_type: str(i, "transaction_type") as "purchase" | "limited_cash_out" | "cash_out", occupancy: str(i, "occupancy"), ...(str(i, "creditor_time_zone") ? { creditor_time_zone: str(i, "creditor_time_zone") } : {}), ...(str(i, "borrower_name") ? { borrower_name: str(i, "borrower_name") } : {}), ...(str(i, "ssn_for_credit") ? { ssn_for_credit: str(i, "ssn_for_credit") } : {}) };
        const r = op === "convert" ? convertToApplication(ctx.events, lead, c) : requestDecision(ctx.events, lead, c); saveLead(rt, ctx, r.lead); return { ...summary(r.lead), application_id: r.application.id, application_date: r.application_date, trid_application_date: r.trid_application_date, le_due_on: r.le_due_on, decision_due_on: r.decision_due_on, next: "21.1 (1003 interview, demographic request) / 21.2 (LE) / 21.6 (decision)" }; }
      if (op === "expire") { need(i, "on"); const r = expireLead(ctx.events, lead, { on: D(str(i, "on")) }); saveLead(rt, ctx, r.lead); return { ...summary(r.lead), purged: r.purged, retained: r.retained }; }
      if (op === "decision_record") { need(i, "interaction_id"); return leadDecisionRecord(lead, str(i, "interaction_id"), str(i, "rationale") || "intake decision record"); }
      throw new RangeError(`explainProgram op ${op} is not one of criteria/general_rates/screen/communicate_decline/demographics/set_fact/next_step/link_party/show_range/defer_intent/close/request_prequal/provide_information/issue_letter/issue_preapproval_letter/record_trid_item/convert/request_decision/expire/decision_record`); }),
    guardrails: [never("L0_FACTS_ONLY", "20.3 rule 6 / 32.14 guardrails: no name, contact, income, SSN or prohibited inquiry on a lead without a party", (i) => str(i, "op") === "set_fact" && l0ProhibitedKeys(i).length > 0, "only goal, contract status, occupancy, state and the consumer's own estimates are lead facts before a session — nothing was written"),
      never("REGB_1002_2F_NO_PREQUAL_DECLINE_GATE", "12 CFR 1002.2(f) comment 2(f)-3; 20.3 rule 3: the agent may never say the consumer does not qualify, would be denied or cannot get the loan — communicateDecline exists only to fail loudly and route to conversion", (i) => str(i, "op") === "communicate_decline" && flag(i, "force"), "a decline is 21.6's adverse action after application.received — never an intake utterance"),
      never("NO_DEMOGRAPHIC_AT_LEAD", "12 CFR 1002.5(b), 1002.13; HMDA App. B; 20.3 rule 6: demographic information is requested only at application (21.1)", (i) => str(i, "op") === "demographics" || /\b(race|ethnicity|national origin|religion|gender)\b/i.test(textOf(i)), "the §1002.13 request exists only in 21.1 — unavailable at lead stage"),
      never("NO_MARITAL_CHILDBEARING_INQUIRY", "12 CFR 1002.5(d)(1)–(3); 20.3 rule 6", (i) => /\b(divorc|widow|pregnan|plan(?:ning)? (?:to have|on) (?:children|kids)|alimony|child support|separate maintenance)/i.test(textOf(i)), "marital status beyond married/unmarried/separated, childbearing and alimony/child-support questions are never asked pre-application"),
      never("NO_DOCUMENTS_BEFORE_LE", "12 CFR 1026.19(e)(2)(iii); 20.3 rule 6", (i) => /\b(upload|send|provide|attach)\b.*\b(pay ?stubs?|w-?2s?|tax returns?|bank statements?)\b/i.test(textOf(i)), "no document requests before the Loan Estimate"),
      never("NO_PROMISES", "20.3 guardrails: no promises (\"guaranteed\", \"pre-approved\")", (i) => /\b(guaranteed|pre-?approved)\b/i.test(textOf(i)), "no promise language in any utterance"),
      never("NO_PREAPPROVAL_PROGRAM", "12 CFR 1003.2(b)(2); 20.3 rule 4 / open question 2: prequalification letters only", (i) => str(i, "op") === "issue_letter" && flag(i, "as_preapproval"), "a prequalification letter is never a written commitment after comprehensive analysis (no HMDA preapproval record)")] },
  // Rule 3 / worked example 1: the 20.1 benefit numbers for a subserviced borrower are on-file data — L2 first; figures come from the engine, never the model.
  { name: "getBenefit", kind: "read", handler: compute((i, _ctx, rt) => { const lead = loadLead(i, rt);
      const opp = (i.opportunity as BenefitInput | undefined) ?? (lead.opportunity_id ? (rt.store.get("refi_opportunities", lead.opportunity_id)?.data as unknown as BenefitInput | undefined) : undefined); if (!opp) throw new RangeError(`no refi_opportunities row ${lead.opportunity_id ?? "(none)"} for lead ${lead.lead_id} (20.1 emitOfferReady; or pass opportunity)`);
      const b = getBenefit(lead, { ...opp, existing_upb_or_amount_cents: cents(opp.existing_upb_or_amount_cents), candidate_amount_cents: cents(opp.candidate_amount_cents), borrower_paid_costs_cents: cents(opp.borrower_paid_costs_cents ?? 0n) });
      return { ...b, current_pi_cents: String(b.current_pi_cents), new_pi_cents: String(b.new_pi_cents), pi_delta_cents: String(b.pi_delta_cents), same_term_pi_cents: String(b.same_term_pi_cents), same_term_delta_cents: String(b.same_term_delta_cents), borrower_paid_costs_cents: String(b.borrower_paid_costs_cents), not_a_commitment: true }; }),
    guardrails: [never("NO_ONFILE_DATA_BEFORE_L2", "20.3 rule 2 / SM_LEAD_AUTH_BEFORE_DISCLOSURE_GATE: the 20.1 payload is on-file servicing data — L2 borrowers only", (i) => flag(i, "bypass_authentication"), "on-file data is withheld until assurance_level ≥ L2")] },
  // Rule 7 / T7: 20.4's personalized quote asks for the MLO review (`terms.presentation.requested` → SM_MLO_PREAPP_TERMS_REVIEW_1BH); the review is the mlo_of_record's act; the presentation names the MLO; the AI never negotiates.
  { name: "requestQuote", kind: "act", handler: compute((i, ctx, rt) => { let lead = loadLead(i, rt); const when = at(i, ctx); const op = str(i, "op") || "request_review";
      if (str(i, "mlo_of_record_id")) { need(i, "mlo_name", "mlo_nmlsr_id"); lead = saveLead(rt, ctx, assignMlo(lead, { mlo_of_record_id: str(i, "mlo_of_record_id"), name: str(i, "mlo_name"), nmlsr_id: str(i, "mlo_nmlsr_id"), ...(str(i, "mlo_time_zone") ? { time_zone: str(i, "mlo_time_zone") } : {}) })); }
      if (op === "assign_mlo") return { ...summary(lead), mlo_of_record_id: lead.mlo_of_record_id, mlo_name: lead.mlo_name, mlo_nmlsr_id: lead.mlo_nmlsr_id };
      if (op === "request_review") { const q = loadQuote(i, rt); const r = requestTermsReview(ctx.events, lead, q, { requested_at: when }); saveLead(rt, ctx, r.lead); return { ...summary(r.lead), quote_id: q.quote_id, requested_at: when, due_at: r.due_at, timer: "SM_MLO_PREAPP_TERMS_REVIEW_1BH", event_id: r.event.id, general_rates_available: true }; }
      if (op === "review") { need(i, "quote_id", "review_id", "outcome"); const r = completeMloReview(ctx.events, lead, { quote_id: str(i, "quote_id"), review_id: str(i, "review_id"), outcome: str(i, "outcome") as "approved" | "returned", completed_at: when, by: ctx.actor, notes: (i.notes as string | undefined) ?? null }); saveLead(rt, ctx, r.lead); rt.store.put("mlo_reviews", r.review.review_id, r.review as unknown as Record<string, unknown>, ctx.actor, ctx.now); return { ...summary(r.lead), review: r.review, event_id: r.event.id }; }
      if (op === "present") { const q = loadQuote(i, rt); const review = (i.mlo_review as MloReview | undefined) ?? (str(i, "review_id") ? (rt.store.get("mlo_reviews", str(i, "review_id"))?.data as unknown as MloReview | undefined) : undefined) ?? null;
        const r = presentTerms(ctx.events, lead, q, review, { at: when }); saveLead(rt, ctx, r.lead); rt.store.put("pricing_quotes", r.quote.quote_id, r.quote as unknown as Record<string, unknown>, ctx.actor, ctx.now); return { ...summary(r.lead), quote_id: r.quote.quote_id, status: r.quote.status, attribution: r.attribution, text: r.text }; }
      if (op === "negotiate") throw new IntakeRefused("NO_NEGOTIATION", "the AI never negotiates (no counter-proposals on rate/points); requests to negotiate route to the mlo_of_record (deliverDisclosure{op=transfer_to_human, terms_to_be_discussed=true})");
      throw new RangeError(`requestQuote op ${op} is not one of assign_mlo/request_review/review/present/negotiate`); }),
    guardrails: [needsRole("MLO_REVIEW_IS_MLO_ACT", "SAFE Act / Reg H App. A; 20.3 automation class (b): presenting particular loan terms goes through the mlo_of_record under origination.ai_mlo_intake=assisted", (i) => str(i, "op") === "review", ["mlo_of_record"], "the terms review is the mlo_of_record's act"),
      never("NO_PARTICULAR_TERMS_BEFORE_MLO_REVIEW", "20.3 rule 7 / guardrails: no particular terms before MLO review (SM_MLO_PREAPP_TERMS_REVIEW_1BH)", (i) => str(i, "op") === "present" && flag(i, "skip_review"), "personalized terms are presented only after mlo.review.completed{approved}; general rate-sheet ranges remain available"),
      never("NO_NEGOTIATION", "20.3 rule 7: the AI never negotiates (no counter-proposals on rate/points)", (i) => str(i, "op") === "negotiate" || flag(i, "counter_proposal"), "requests to negotiate route to the mlo_of_record")] },
]);
