/**
 * §17.4 tools — loss-mit in-flight transfer (`lossmit-underwriter`). The spec's tool
 * strings verbatim via `defineTools("17.4", "lossmit-underwriter", defs)` (see section13.ts).
 * Guardrails encode the spec's sentences: the agent never rushes a determination to beat T,
 * no denial/appeal determination issues before T without a `lossmit_reviewer` approval record
 * (a record the reviewer wrote through `lossmit_reviewer{op=approve}`; reviewer ≠ evaluator, §1024.41(h)(3)),
 * nothing issues on or after T on a transferred loan (the day taken from the bus clock when the
 * caller omits `today`), Supermortgage never evaluates, acknowledges or decides anything on a
 * transferred loan, no 12.x/13.x/14.x/4.x timer is cancelled with reason `transfer_out` before T,
 * SMDU status is reported through T−1 only, a pre-T negotiation that is MLO activity needs a
 * `licensed_specialist`, counsel's acknowledgment is the firm's (`attorney` role, firm named), the
 * TO-* checks are computed from the snapshot and never asserted by the caller, and a case is
 * packaged only when every TO-* check passes or its deficiency is documented — otherwise it goes
 * `deficient` (5-BD cure). Spread by ./section17.ts.
 *
 * Events (spec Outputs): `case.handoff.inventoried/packaged/delivered/acked/deficient/resolved` (per case on the loan,
 * `scope=case`; per batch on {kind: batch, id: batch_id}, `scope=batch`, for the rows 17.1/17.3 arm on the batch),
 * `lossmit.document.received{loan_status=transferred_out}` (the post-transfer receipt that arms the 1-BD forwarding row),
 * `lossmit.forwarded_post_transfer`, `attorney.instruction.sent/acked`, `smdu.case.status_reported`, `case.closed{reason=transferred_out}`.
 */
import { defineTools, compute, escalate, decision, never, needsRole, guard, str, flag, cents, type ToolDef, type ToolInput } from "../tools.ts";
import type { CommandContext } from "../commands.ts";
import { plainDate as D, addDays, type PlainDate } from "../../kernel/calendar/date.ts";
import { addBusinessDays, servicer } from "../../kernel/calendar/business.ts";
import { inventoryScope, inventoryFlags, handoffChecks, deadlineTable, workdownWindow, workdownEvidence, packageEvidence, cancelTimerRequest, postTransferForwarding, postTransferReceipt, preTransferDetermination, foreclosureHoldHandoff, counselAcknowledgment, bankruptcyHandoff, trialPaymentHandoff, retainedRequest, payoffRequestHandoff, handoffTransition, smduHandoff, negotiationIsMloActivity, borrowerRequestsHuman, batchHandoffRollup, preliminaryHandoffAck, type CaseSnapshot, type CaseType, type ForwardKind, type HandoffStatus, type HandoffRow, type DeterminationOutcome } from "../../domain/transfers/ops-17-4.ts";

const need = (i: ToolInput, ...keys: string[]): void => { for (const k of keys) if (i[k] === undefined || i[k] === null || i[k] === "") throw new RangeError(`${k} is required`); };
const date = (i: ToolInput, k: string): PlainDate => { need(i, k); return D(str(i, k)); };
const optDate = (i: ToolInput, k: string): PlainDate | null => (i[k] === undefined || i[k] === null || i[k] === "" ? null : D(str(i, k)));
/** The civil date an action happens on: the caller's `today` or the bus clock — never absent, so "after T" can always be measured. */
const todayOf = (i: ToolInput, ctx: { now: string }): PlainDate => optDate(i, "today") ?? D(ctx.now.slice(0, 10));
const snapshot = (i: ToolInput): CaseSnapshot => ((i.snapshot as CaseSnapshot | undefined) ?? { case_type: (str(i, "case_type") || "lossmit") as CaseType });
const loanOf = (i: ToolInput, ctx: CommandContext): string => str(i, "loan_id") || ctx.loanId;
const strings = (i: ToolInput, k: string): string[] => (Array.isArray(i[k]) ? (i[k] as unknown[]).map(String).filter(Boolean) : []);
/** The batch aggregate the batch-subject rows live on — the aggregate 17.3's `transfer.cutover.frozen` lands on (section17-3.ts batchAgg). */
const batchAgg = (batchId: string) => ({ kind: "batch", id: batchId });
const ADVERSE = /^(denial|appeal_denied)$/;
const FORWARD_KINDS: readonly ForwardKind[] = ["lossmit_document", "appeal", "acceptance", "rejection", "correspondence", "counsel_notice", "trustee_payment", "insurer_check", "other"];
/** Actions of `completePreTransferAction` that issue something on the loan (a counsel instruction keyed to Supermortgage's gates, a borrower notice) — refused on or after T. Forwarding, the retained NoE/RFI answer, the counsel acknowledgment, the SMDU report and the payoff hand-off are post-T or T−1 duties measured by their own rules. */
const ISSUING_ACTIONS = new Set(["hold_instruction", "send_notice", "acknowledge"]);
const AGENT = "lossmit-underwriter";
const CANCELLABLE = new Set(["armed", "breached"]);

/** No adverse determination issues before T without a reviewer record; the reviewer must not be the evaluator. */
const REVIEWER_GATE = needsRole("DENIAL_NEEDS_REVIEWER", "17.4 escalations: `lossmit_reviewer` for any denial/appeal determination issued before T (Colorado AI Act, LL-2026-04)", (i) => ADVERSE.test(str(i, "outcome")) && !str(i, "reviewer_approval_id"), ["lossmit_reviewer"], "an adverse determination cannot issue without a lossmit_reviewer approval record — hand off undetermined instead");
const REVIEWER_SEPARATION = guard("REVIEWER_SEPARATION", "17.4 escalations: reviewer ≠ evaluator per §1024.41(h)(3)", (i, ctx) => { const evaluator = str(i, "evaluator_id") || ctx.actor.id; const reviewer = str(i, "op") === "approve" ? ctx.actor.id : str(i, "reviewer_id"); return reviewer && reviewer === evaluator ? "the reviewer must be a different person from the evaluator" : undefined; });
const REVIEWER_APPROVES = needsRole("REVIEWER_APPROVAL_IS_HUMAN", "17.4 state machine: determinations before T need `lossmit_reviewer`", (i) => str(i, "op") === "approve", ["lossmit_reviewer"], "only a lossmit_reviewer writes an approval record");
const NOTHING_AFTER_T = guard("NOTHING_ISSUED_AFTER_T", "17.4 integrations: print-mail — notices issued before T only; nothing issued after T on transferred loans", (i, ctx) => { const issuing = i.action === undefined || ISSUING_ACTIONS.has(str(i, "action")); const T = str(i, "transfer_date"); return issuing && T && todayOf(i, ctx) >= T ? "nothing issues on or after the transfer date; forward to the transferee" : undefined; });
/** Work-down rule: a determination proposed before its evaluation is complete is rushed to beat T — refused; the case is handed off with the unexpired period in TO-04 instead. */
const NEVER_RUSH = never("NEVER_RUSH_DETERMINATION", "17.4 work-down rule: never rushes a determination to beat T at the expense of the evaluation quality", (i) => i.evaluation_complete === false, "complete the evaluation or hand off with the unexpired period documented in TO-03/04/05");
const NO_SMDU_AFTER_T = never("NO_SMDU_REPORTING_AFTER_T", "17.4 outputs: workout status via SMDU through T-1; none after", (i) => str(i, "action") === "smdu_status" && Boolean(str(i, "status_reported_through")) && Boolean(str(i, "transfer_date")) && str(i, "status_reported_through") >= str(i, "transfer_date"), "SMDU status is reported through T−1 only; the transferee reports from T");
const NEVER_EVALUATE_TRANSFERRED = never("NEVER_EVALUATE_TRANSFERRED", "17.4 business rules: Supermortgage never evaluates, acknowledges or decides anything on a transferred loan", (i) => flag(i, "evaluate") || flag(i, "acknowledge") || flag(i, "decide") || ["outcome", "determination", "decision", "evaluation", "ack_sent_at", "determination_sent_at", "reasonable_date"].some((k) => i[k] !== undefined && i[k] !== null && i[k] !== ""), "forward with the receipt timestamp only — no evaluation, acknowledgment or decision travels with a post-transfer forwarding");
const NO_TRANSFER_OUT_CANCEL = guard("REGX_1024_41_TRANSFEROR_CONTINUES_GATE", "17.4 timer table: no 12.x/13.x/14.x/4.x timer on a listed loan may be cancelled or waived with reason `transfer_out` before `transfer_date`", (i, ctx) => (str(i, "action") === "cancel_timer" && str(i, "reason") === "transfer_out" && (!str(i, "transfer_date") || todayOf(i, ctx) < str(i, "transfer_date")) ? "the transferor's clocks run until T — refused" : undefined));
/** The hold/proceed/file-transfer acknowledgment is the firm's: entered by the `attorney` role naming the firm — the agent cannot acknowledge its own instruction. */
const COUNSEL_ACK_BY_FIRM = needsRole("COUNSEL_ACK_BY_FIRM", "17.4 state machine: counsel instructions are sent by the agent and acknowledged by the firm (attorney-network acknowledgments, 2 BD per 13.6)", (i) => str(i, "action") === "counsel_ack", ["attorney"], "the firm's acknowledgment is recorded by the attorney-network side");
const MLO_ACTIVITY = needsRole("MLO_ACTIVITY_NEEDS_LICENSED_SPECIALIST", "17.4 escalations: `licensed_specialist` where a pre-T negotiation is MLO activity", (i) => negotiationIsMloActivity({ outcome: str(i, "outcome") as DeterminationOutcome, terms_negotiated: flag(i, "terms_negotiated") }), ["licensed_specialist"], "negotiating modification terms with the borrower is MLO activity — a licensed_specialist conducts the negotiation");
/** TO-* results are measured over the COB T−1 snapshot (handoffChecks); a caller-supplied `checks` array would let the packager assert its own work-down state. */
const CHECKS_NOT_ASSERTED = never("CHECKS_NOT_ASSERTED", "17.4 state machine: `packaged` = all TO-* pass or deficiencies documented — the TO-* results are computed from the snapshot, never supplied", (i) => (str(i, "op") || "package") === "package" && i.checks !== undefined, "drop `checks`: runHandoffChecks/packageCase compute TO-01..TO-15 from the snapshot; document a failed check with `deficiencies_documented`");

/** `human_agent` on borrower request — opened alongside the action, never instead of it. */
function humanOnRequest(i: ToolInput, ctx: CommandContext, rt: Parameters<ToolDef["handler"]>[2]): void { const h = borrowerRequestsHuman({ borrower_requests_human: flag(i, "borrower_requests_human") }); if (h) rt.escalations.open({ kind: "human_agent", loanId: loanOf(i, ctx), payload: { reason: h.reason, case_id: str(i, "case_id") || null } }, ctx.actor); }
const HANDOFF_STATUSES: readonly HandoffStatus[] = ["inventoried", "packaged", "delivered", "acked", "deficient", "resolved"];
/** `case_handoffs.status` holds the migration's enum; the per-case machine state (snapshot, closed_transferred, retained…) lives on `cases.handoff_status`. */
const tableStatus = (s: HandoffStatus): HandoffStatus => (HANDOFF_STATUSES.includes(s) ? s : s === "closed_transferred" ? "acked" : "inventoried");
/** The batch's `case_handoffs` rows as the roll-up sees them (the machine state from `cases.handoff_status`, the work-down state from the row). */
function batchRows(rt: Parameters<ToolDef["handler"]>[2], batchId: string): HandoffRow[] {
  return rt.store.list("case_handoffs", (d) => String(d.batch_id ?? "") === batchId).map((r) => ({ case_id: r.id, case_type: String(r.data.case_type) as CaseType, status: ((rt.store.get("cases", r.id)?.data.handoff_status as HandoffStatus | undefined) ?? (r.data.status as HandoffStatus)), pre_transfer_workdown: (r.data.pre_transfer_workdown as "documented" | "undocumented" | null | undefined) ?? null }));
}

export const TOOLS_17_4: readonly ToolDef[] = defineTools("17.4", AGENT, [
  { name: "inventoryOpenCases", kind: "act", handler: compute((i, ctx, rt) => { need(i, "batch_id", "transfer_date", "attested_on"); const T = date(i, "transfer_date"); const attested = date(i, "attested_on"); const now = todayOf(i, ctx); const batchId = str(i, "batch_id");
      // the inventory is over the attested loan list (spec Inputs: `transfer.loan_list.attested` → open-case inventory … for listed loans) — never "every case"
      const listed = new Set(strings(i, "listed_loan_ids")); if (!listed.size) throw new RangeError("listed_loan_ids (the attested loan list) is required");
      type Row = Record<string, unknown> & { case_id?: unknown; loan_id?: unknown; snapshot?: CaseSnapshot; case_type?: unknown };
      const rows: { case_id: string; data: Row }[] = Array.isArray(i.cases) ? (i.cases as Row[]).map((c) => ({ case_id: String(c.case_id ?? ""), data: c })) : rt.store.list("cases").map((r) => ({ case_id: r.id, data: r.data as Row }));
      const out: { case_id: string; loan_id: string; scope: ReturnType<typeof inventoryScope>; flags: ReturnType<typeof inventoryFlags> }[] = [];
      for (const { case_id, data: d } of rows) {
        if (!case_id) throw new RangeError("every case needs a case_id");
        const loanId = String(d.loan_id ?? "") || ctx.loanId; const s: CaseSnapshot = d.snapshot ?? { case_type: String(d.case_type ?? "lossmit") as CaseType };
        const openedOn = D(String(d.opened_on ?? attested)); const scope = inventoryScope({ listed: listed.has(loanId), case_type: s.case_type, opened_on: openedOn, closed_on: d.closed_on ? D(String(d.closed_on)) : null, attested_on: attested, denial_sent_on: d.denial_sent_on ? D(String(d.denial_sent_on)) : null, appeal_received_on: d.appeal_received_on ? D(String(d.appeal_received_on)) : null, today: now });
        if (!scope.in_scope) continue;
        const flags = inventoryFlags(s, T);
        const rec = rt.store.put("case_handoffs", case_id, { case_id, loan_id: loanId, batch_id: batchId, case_type: s.case_type, snapshot_as_of: ctx.now, checklist: [], deadline_table: [], status: "inventoried" }, ctx.actor, ctx.now);
        rt.store.put("cases", case_id, { loan_id: loanId, case_type: s.case_type, handoff_status: scope.handoff_status, owner_after_transfer: scope.owner_after_transfer, snapshot: s }, ctx.actor, ctx.now);
        ctx.events.append({ type: "case.handoff.inventoried", loanId, aggregate: { kind: "case_handoffs", id: rec.id }, actor: ctx.actor, payload: { scope: "case", case_id, batch_id: batchId, transfer_date: T, attested_on: attested, opened_on: openedOn, opened_before_transfer: openedOn < T, received_at: s.received_at ?? openedOn, case_owner: scope.owner_after_transfer, pending: scope.pending, history_delivered: scope.history_delivered, handoff_status: scope.handoff_status, owner_after_transfer: scope.owner_after_transfer, ...flags } });
        out.push({ case_id, loan_id: loanId, scope, flags });
      }
      // the batch-level inventory: the attestation's consequence on the batch aggregate — arms SM_LOSSMIT_HANDOFF_FILE_14 (T−14) and SM_LOSSMIT_PRE_T_WORKDOWN_T1 (T−1 BD) on `transfer_date`
      ctx.events.append({ type: "case.handoff.inventoried", aggregate: batchAgg(batchId), actor: ctx.actor, payload: { scope: "batch", batch_id: batchId, transfer_date: T, attested_on: attested, listed_loans: listed.size, cases: out.length, lossmit_cases: out.filter((c) => c.flags.lossmit).length, retained_cases: out.filter((c) => c.flags.retained).length, preliminary_file_due: addDays(T, -14), workdown_due: addBusinessDays(T, -1, servicer) } });
      return out; }) },
  { name: "runHandoffChecks", kind: "act", handler: compute((i, ctx, rt) => { need(i, "case_id", "transfer_date"); const T = date(i, "transfer_date"); const checks = handoffChecks(snapshot(i), T);
      for (const c of checks) rt.store.put("lossmit_handoff_checks", `${str(i, "case_id")}-${c.check_code}-${ctx.now}`, { case_id: str(i, "case_id"), check_code: c.check_code, result: c.result, evidence_document_id: str(i, "evidence_document_id") || null, at: ctx.now }, ctx.actor, ctx.now);
      if (rt.store.get("case_handoffs", str(i, "case_id"))) rt.store.put("case_handoffs", str(i, "case_id"), { checklist: checks }, ctx.actor, ctx.now);
      return { case_id: str(i, "case_id"), checks, deficiencies: checks.filter((c) => c.result === "fail").map((c) => c.check_code) }; }) },
  { name: "exportDeadlineTable", kind: "read", handler: compute((i) => { need(i, "case_id", "transfer_date"); const T = date(i, "transfer_date"); const s = snapshot(i);
      const workdown = Array.isArray(i.actions) ? workdownWindow({ transfer_date: T, actions: i.actions as { code: string; due: PlainDate; completed_on?: PlainDate | null; documented_check?: "TO-03" | "TO-04" | "TO-05" | null }[] }) : workdownEvidence(s, T, handoffChecks(s, T));
      return { case_id: str(i, "case_id"), transfer_date: T, rows: deadlineTable(s, T), workdown }; }) },
  { name: "completePreTransferAction", kind: "act", handler: compute((i, ctx, rt) => { need(i, "case_id", "action", "transfer_date"); const T = date(i, "transfer_date"); const now = todayOf(i, ctx); const action = str(i, "action"); const loanId = loanOf(i, ctx); humanOnRequest(i, ctx, rt);
      switch (action) {
        case "cancel_timer": { need(i, "timer_code", "reason"); const r = cancelTimerRequest({ listed: i.listed !== false, reason: str(i, "reason"), today: now, transfer_date: T, timer_code: str(i, "timer_code") }); if (!r.allowed) { ctx.events.append({ type: "command.refused", loanId, actor: ctx.actor, payload: { gate: r.gate, refusal: r.refusal } }); return r; }
          // the instance is resolved on the loan by id or code — cancelling nothing is an error, not a silent no-op (TimerEngine.cancel ignores unknown ids)
          const targets = ctx.timers.forSubject("loan", loanId).filter((t) => CANCELLABLE.has(t.status) && (str(i, "timer_id") ? t.id === str(i, "timer_id") : t.code === str(i, "timer_code")));
          if (!targets.length) throw new RangeError(`no armed ${str(i, "timer_code")} instance on loan ${loanId}${str(i, "timer_id") ? ` with id ${str(i, "timer_id")}` : ""}`);
          for (const t of targets) ctx.timers.cancel(t.id, str(i, "reason"), ctx.actor); return { ...r, cancelled_timer_ids: targets.map((t) => t.id) }; }
        case "hold_instruction": { need(i, "sale_on"); const r = foreclosureHoldHandoff({ transfer_date: T, sale_on: date(i, "sale_on"), complete_received_on: optDate(i, "complete_received_on"), reasonable_date: optDate(i, "reasonable_date"), earliest_unpaid_due: optDate(i, "earliest_unpaid_due"), instruction_sent_on: optDate(i, "instruction_sent_on") ?? now, counsel_acked_on: optDate(i, "counsel_acked_on"), firm_changes: flag(i, "firm_changes"), today: now });
          ctx.events.append({ type: "attorney.instruction.sent", loanId, actor: ctx.actor, payload: { case_id: str(i, "case_id"), kind: r.instruction.kind, ground: r.ground, due: r.hold_instruction_due, both_firms: r.instruction.both_firms, firm_id: str(i, "firm_id") || null, ack_required: true } }); if (r.escalation) rt.escalations.open({ kind: "officer", loanId, severity: "sev1", payload: { reason: r.escalation.reason } }, ctx.actor); return r; }
        case "counsel_ack": { need(i, "acked_on", "firm_id", "ack_reference"); const r = counselAcknowledgment({ transfer_date: T, kind: (str(i, "kind") || "HOLD") as "HOLD", acked_on: date(i, "acked_on"), instruction_sent_on: optDate(i, "instruction_sent_on") });
          ctx.events.append({ type: "attorney.instruction.acked", loanId, actor: ctx.actor, payload: { case_id: str(i, "case_id"), kind: str(i, "kind") || "HOLD", acked_on: str(i, "acked_on"), firm_id: str(i, "firm_id"), ack_reference: str(i, "ack_reference"), acked_by: ctx.actor.id, on_time: r.on_time, due: r.due } }); return r; }
        case "bankruptcy_handoff": { const r = bankruptcyHandoff({ transfer_date: T, pending_items: (i.pending_items as Parameters<typeof bankruptcyHandoff>[0]["pending_items"] | undefined) ?? [], counsel_instructed_on: optDate(i, "counsel_instructed_on"), trustee_notice_sent_on: optDate(i, "trustee_notice_sent_on"), debtor_counsel_notice_sent_on: optDate(i, "debtor_counsel_notice_sent_on"), today: now }); if (r.escalation) rt.escalations.open({ kind: "attorney", loanId, severity: "sev1", payload: { reason: r.escalation.reason } }, ctx.actor); return r; }
        case "trial_payment": { need(i, "due_on"); const r = trialPaymentHandoff({ due_on: date(i, "due_on"), received_on: optDate(i, "received_on"), transfer_date: T, amount_cents: i.amount_cents === undefined ? null : cents(i.amount_cents), trial_amount_cents: i.trial_amount_cents === undefined ? null : cents(i.trial_amount_cents), forwarded_on: optDate(i, "forwarded_on") });
          if (r.misdirected && i.forwarded_on !== undefined) { const rec = rt.store.put("post_transfer_forwardings", str(i, "id") || `fwd-${loanId}-trial-${str(i, "due_on")}`, { loan_id: loanId, kind: "other", received_at: r.receipt_date, forwarded_at: str(i, "forwarded_on"), transferee_ack_at: optDate(i, "transferee_ack_on"), document_id: str(i, "document_id") || null }, ctx.actor, ctx.now); ctx.events.append({ type: "lossmit.trial_payment.forwarded", loanId, aggregate: { kind: "post_transfer_forwardings", id: rec.id }, actor: ctx.actor, payload: { case_id: str(i, "case_id"), due_on: str(i, "due_on"), receipt_date: r.receipt_date, forward_by: r.forward_by, forwarded_on: str(i, "forwarded_on"), on_time: r.forwarded_on_time } }); if (r.forwarded_on_time === false) rt.escalations.open({ kind: "officer", loanId, severity: "sev1", payload: { reason: `trial payment received ${r.receipt_date} forwarded ${str(i, "forwarded_on")} after ${r.forward_by}: the receipt date still protects the borrower — transferee notified in writing` } }, ctx.actor); }
          return r; }
        case "retained_request": { need(i, "received_on"); const r = retainedRequest({ kind: (str(i, "kind") || "noe") as "noe" | "rfi" | "complaint", received_on: date(i, "received_on"), transfer_date: T, ...(str(i, "assertion_type") ? { assertion_type: str(i, "assertion_type") as "b1" } : {}), sale_date: optDate(i, "sale_date"), ...(str(i, "concerns") ? { concerns: str(i, "concerns") as "own_servicing" } : {}) });
          const sent = optDate(i, "response_sent_on");
          if (sent && r.owner === "supermortgage") { need(i, "transferee_copy_document_id"); ctx.events.append({ type: "case.response.sent", loanId, actor: ctx.actor, payload: { case_id: str(i, "case_id"), kind: r.gate === "SM_NOE_RFI_OPEN_RETAINED" ? str(i, "kind") || "noe" : null, owner: "supermortgage", response_sent_on: sent, response_due: r.response_due, on_time: sent <= r.response_due, copy_to_transferee: true, transferee_copy_document_id: str(i, "transferee_copy_document_id") } }); return { ...r, response_sent_on: sent, response_on_time: sent <= r.response_due, transferee_copy_document_id: str(i, "transferee_copy_document_id") }; }
          return r; }
        case "payoff_request": { need(i, "received_on"); const r = payoffRequestHandoff({ received_on: date(i, "received_on"), transfer_date: T, statement_sent_on: optDate(i, "statement_sent_on"), forwarded_on: optDate(i, "forwarded_on"), requester_told_on: optDate(i, "requester_told_on"), today: now }); if (r.refusal) throw new RangeError(r.refusal);
          if (r.outcome === "forwarded_to_transferee") { ctx.events.append({ type: "payoff.request.forwarded", loanId, actor: ctx.actor, payload: { case_id: str(i, "case_id"), receipt_date: str(i, "received_on"), forwarded_on: str(i, "forwarded_on"), forward_by: r.forward_by, requester_told_on: str(i, "requester_told_on") || null, transferee_due: r.due, on_time: r.on_time } }); for (const t of ctx.timers.forSubject("loan", loanId)) if (t.code === "SM_PAYOFF_REQUEST_OPEN_7BD" && CANCELLABLE.has(t.status)) ctx.timers.cancel(t.id, "forwarded_to_transferee", ctx.actor); }
          if (r.breach) rt.escalations.open({ kind: "officer", loanId, severity: "sev1", payload: { reason: r.breach.reason } }, ctx.actor); return r; }
        case "smdu_status": { need(i, "smdu_case_id"); const r = smduHandoff({ smdu_case_id: str(i, "smdu_case_id"), status_reported_through: optDate(i, "status_reported_through"), transfer_date: T, servicer_number_change: flag(i, "servicer_number_change"), fnma_request_package_filed: flag(i, "fnma_request_package_filed") });
          // the SMDU status snapshot through T−1 (trial payments reported) — `handoff_current=true` only when smduHandoff finds it current and the request package filed where a servicer-number change requires it (SM_SMDU_CASE_HANDOFF_T0)
          ctx.events.append({ type: "smdu.case.status_reported", loanId, actor: ctx.actor, payload: { case_id: str(i, "case_id"), smdu_case_id: str(i, "smdu_case_id"), status_reported_through: optDate(i, "status_reported_through"), transfer_date: T, current_through_t1: r.current_through_t1, servicer_number_change: flag(i, "servicer_number_change"), request_package_required: r.request_package_required, request_package_filed: flag(i, "fnma_request_package_filed"), handoff_current: r.ok, unverified_mechanics: true } });
          if (r.portal_task) rt.escalations.open({ kind: "human_portal_task", ownerRole: r.portal_task.owner_role, loanId, payload: { reason: r.portal_task.reason } }, ctx.actor); return r; }
        default: throw new RangeError(`action ${action} is not one of cancel_timer/hold_instruction/counsel_ack/bankruptcy_handoff/trial_payment/retained_request/payoff_request/smdu_status`);
      } }),
    guardrails: [NO_TRANSFER_OUT_CANCEL, NOTHING_AFTER_T, NO_SMDU_AFTER_T, COUNSEL_ACK_BY_FIRM] },
  { name: "draftDetermination", kind: "act", handler: compute((i, ctx, rt) => { need(i, "case_id", "outcome", "transfer_date", "complete_at"); const T = date(i, "transfer_date"); const caseId = str(i, "case_id"); const outcome = str(i, "outcome") as DeterminationOutcome; const evaluatorId = str(i, "evaluator_id") || ctx.actor.id;
      // The approval record is the one the reviewer wrote through `lossmit_reviewer{op=approve}` for this case and outcome — a bare id proves nothing.
      const approvalId = str(i, "reviewer_approval_id"); const rec = approvalId ? rt.store.get("lossmit_reviewer_approvals", approvalId)?.data : undefined;
      const lookup = !approvalId ? "none" : !rec ? "not_found" : String(rec.case_id) !== caseId || String(rec.outcome) !== outcome || (rec.evaluator_id && String(rec.evaluator_id) !== evaluatorId) ? "mismatch" : "verified";
      const r = preTransferDetermination({ outcome, proposed_on: todayOf(i, ctx), transfer_date: T, complete_at: date(i, "complete_at"), evaluator_id: evaluatorId, reviewer_approval: lookup === "verified" ? { reviewer_id: String(rec!.reviewer_id), approved_on: D(String(rec!.approved_on)), record_id: approvalId } : null, ai_proposed: ctx.actor.kind !== "human", ...(typeof i.evaluation_complete === "boolean" ? { evaluation_complete: i.evaluation_complete } : {}) });
      if (r.escalation) rt.escalations.open({ kind: r.escalation.kind === "lossmit_reviewer" ? "lossmit_reviewer" : "officer", loanId: loanOf(i, ctx), ...(r.escalation.severity ? { severity: r.escalation.severity } : {}), payload: { case_id: caseId, outcome, reason: r.escalation.reason, approval_lookup: lookup } }, ctx.actor);
      return { case_id: caseId, ...r, approval_lookup: lookup, draft_only: !r.can_issue }; }),
    humanRoles: ["ops_analyst", "officer", "lossmit_reviewer", "licensed_specialist", "human_agent", "attorney", "fnma_portal_operator"], guardrails: [NEVER_RUSH, REVIEWER_GATE, REVIEWER_SEPARATION, NOTHING_AFTER_T, MLO_ACTIVITY] },
  { name: "lossmit_reviewer", kind: "act", handler: compute((i, ctx, rt) => { const op = str(i, "op") || "request";
      if (op === "request") return escalate("lossmit_reviewer")(i, ctx, rt);
      if (op !== "approve") throw new RangeError(`op ${op} is not one of request/approve`);
      need(i, "case_id", "outcome", "evaluator_id"); const id = str(i, "approval_id") || `rev-${str(i, "case_id")}-${ctx.now}`; const approvedOn = optDate(i, "approved_on") ?? D(ctx.now.slice(0, 10));
      const rec = rt.store.put("lossmit_reviewer_approvals", id, { case_id: str(i, "case_id"), outcome: str(i, "outcome"), evaluator_id: str(i, "evaluator_id"), reviewer_id: ctx.actor.id, reviewer_role: ctx.actor.role ?? null, approved_on: approvedOn, escalation_id: str(i, "escalation_id") || null, evidence_document_id: str(i, "evidence_document_id") || null }, ctx.actor, ctx.now);
      if (str(i, "escalation_id")) rt.escalations.complete(str(i, "escalation_id"), ctx.actor, str(i, "evidence_document_id") || undefined);
      ctx.events.append({ type: "lossmit.determination.reviewed", loanId: loanOf(i, ctx), aggregate: { kind: "lossmit_reviewer_approvals", id }, actor: ctx.actor, payload: { case_id: str(i, "case_id"), outcome: str(i, "outcome"), approval_id: id, reviewer_id: ctx.actor.id, evaluator_id: str(i, "evaluator_id"), approved_on: approvedOn } });
      return { approval_id: id, ...rec.data }; }),
    guardrails: [REVIEWER_APPROVES, REVIEWER_SEPARATION] },
  { name: "packageCase", kind: "act", handler: compute((i, ctx, rt) => { const op = str(i, "op") || "package";
      if (op === "ack" && str(i, "stage") === "preliminary") {   // the transferee's acknowledgment of the preliminary D21/D34 (batch-level; SM_LOSSMIT_HANDOFF_FILE_14) — no case, the batch
        need(i, "batch_id", "transfer_date", "deliverable_kind", "ack_reference", "acked_on", "acked_by"); const r = preliminaryHandoffAck({ transfer_date: date(i, "transfer_date"), deliverable_kind: str(i, "deliverable_kind"), acked_on: date(i, "acked_on"), as_of: optDate(i, "as_of") }); if (r.refusal) throw new RangeError(r.refusal);
        ctx.events.append({ type: "case.handoff.acked", aggregate: batchAgg(str(i, "batch_id")), actor: ctx.actor, payload: { scope: "batch", stage: "preliminary", batch_id: str(i, "batch_id"), deliverable_kind: r.deliverable_kind, ack_reference: str(i, "ack_reference"), acked_by: str(i, "acked_by"), acked_on: str(i, "acked_on"), as_of: optDate(i, "as_of"), due: r.due, on_time: r.on_time } }); return r; }
      need(i, "case_id", "transfer_date"); const T = date(i, "transfer_date"); const caseId = str(i, "case_id"); const loanId = loanOf(i, ctx); const now = todayOf(i, ctx);
      const existing = rt.store.get("case_handoffs", caseId)?.data; const agg = { kind: "case_handoffs", id: caseId }; const batchId = str(i, "batch_id") || String(existing?.batch_id ?? "");
      const s: CaseSnapshot = (i.snapshot as CaseSnapshot | undefined) ?? (rt.store.get("cases", caseId)?.data.snapshot as CaseSnapshot | undefined) ?? snapshot(i); const caseType = (existing?.case_type as CaseType | undefined) ?? s.case_type;
      const from0 = (str(i, "from_status") || (rt.store.get("cases", caseId)?.data.handoff_status as HandoffStatus | undefined) || (existing?.status as HandoffStatus | undefined) || "snapshot") as HandoffStatus;
      const move = (from: HandoffStatus, to: HandoffStatus, extra: Record<string, unknown>): Record<string, unknown> => { const t = handoffTransition(from, to); if (!t.ok) throw new RangeError(t.refusal!); const rec = rt.store.put("case_handoffs", caseId, { case_id: caseId, loan_id: loanId, case_type: caseType, status: tableStatus(to), ...extra }, ctx.actor, ctx.now); rt.store.put("cases", caseId, { handoff_status: to, ...(to === "closed_transferred" ? { transferred_out_at: ctx.now } : {}) }, ctx.actor, ctx.now); return rec.data; };
      switch (op) {
        case "package": {
          const checks = handoffChecks(s, T); const ev = packageEvidence(s, T, checks);   // TO-* always measured over the snapshot (CHECKS_NOT_ASSERTED)
          const documented = new Set(strings(i, "deficiencies_documented")); const undocumented = ev.deficiencies.filter((c) => !documented.has(c));
          const from = from0 === "inventoried" || from0 === "pre_transfer_active" ? "snapshot" : from0;   // the package op takes the COB T−1 snapshot
          if (undocumented.length) { const row = move(from, "deficient", { batch_id: batchId || null, snapshot_as_of: str(i, "snapshot_as_of") || ctx.now, checklist: checks, deadline_table: deadlineTable(s, T), deficiencies: undocumented, pre_transfer_workdown: ev.pre_transfer_workdown }); ctx.events.append({ type: "case.handoff.deficient", loanId, aggregate: agg, actor: ctx.actor, payload: { scope: "case", case_id: caseId, case_type: caseType, deficiencies: undocumented, raised_at: ctx.now, transfer_date: T } });
            if (now >= addBusinessDays(T, -1, servicer)) rt.escalations.open({ kind: "officer", loanId, severity: "sev2", payload: { case_id: caseId, reason: `deficiencies that cannot be cured before T: ${undocumented.join(", ")}` } }, ctx.actor); return { ...row, deficiencies: undocumented, cure_by: addBusinessDays(D(ctx.now.slice(0, 10)), 5, servicer) }; }
          const row = move(from, "packaged", { batch_id: batchId || null, snapshot_as_of: str(i, "snapshot_as_of") || ctx.now, checklist: checks, deadline_table: deadlineTable(s, T), package_document_id: str(i, "package_document_id") || null, sale_within_45_days: ev.sale_within_45_days, pre_transfer_workdown: ev.pre_transfer_workdown, deficiencies: ev.deficiencies });
          ctx.events.append({ type: "case.handoff.packaged", loanId, aggregate: agg, actor: ctx.actor, payload: { scope: "case", case_id: caseId, batch_id: batchId || null, case_type: caseType, lossmit: ev.lossmit, pre_transfer_workdown: ev.pre_transfer_workdown, workdown_undocumented: ev.workdown.undocumented, deficiencies_documented: ev.deficiencies, sale_within_45_days: ev.sale_within_45_days, ...(caseType === "bankruptcy" ? { trustee_notice_sent: ev.trustee_notice_sent, debtor_counsel_notice_sent: ev.debtor_counsel_notice_sent, counsel_instructed: ev.counsel_instructed, bk_items_flagged: ev.bankruptcy?.flagged ?? [] } : {}) } });
          if (ev.workdown.escalation) rt.escalations.open({ kind: "officer", loanId, severity: "sev2", payload: { case_id: caseId, reason: ev.workdown.escalation.reason } }, ctx.actor);
          // batch roll-up (SM_LOSSMIT_PRE_T_WORKDOWN_T1): every loss-mit case of the batch packaged with its work-down documented — measured over the rows, emitted on the batch aggregate the inventory armed
          const roll = batchId ? batchHandoffRollup(batchRows(rt, batchId)) : null;
          if (roll?.workdown_documented) ctx.events.append({ type: "case.handoff.packaged", aggregate: batchAgg(batchId), actor: ctx.actor, payload: { scope: "batch", batch_id: batchId, lossmit: true, pre_transfer_workdown: "documented", lossmit_cases: roll.lossmit, lossmit_packaged: roll.lossmit_packaged, transfer_date: T } });
          return { ...row, evidence: ev, batch_rollup: roll }; }
        case "deliver": { const row = move(from0, "delivered", { delivered_at: str(i, "delivered_at") || ctx.now, package_document_id: str(i, "package_document_id") || existing?.package_document_id || null }); ctx.events.append({ type: "case.handoff.delivered", loanId, aggregate: agg, actor: ctx.actor, payload: { scope: "case", case_id: caseId, case_type: caseType, delivered_at: row.delivered_at, sale_within_45_days: flag(i, "sale_within_45_days") || existing?.sale_within_45_days === true || inventoryFlags(s, T).sale_within_45_days, recipient: str(i, "recipient") || "transferee", package_document_id: row.package_document_id, ack_due: addBusinessDays(D(String(row.delivered_at).slice(0, 10)), 2, servicer) } }); return row; }
        case "ack": { need(i, "ack_reference", "acked_by"); const row = move(from0, "acked", { acked_at: str(i, "acked_at") || ctx.now, ack_reference: str(i, "ack_reference"), acked_by: str(i, "acked_by") }); ctx.events.append({ type: "case.handoff.acked", loanId, aggregate: agg, actor: ctx.actor, payload: { scope: "case", case_id: caseId, batch_id: batchId || null, case_type: caseType, stage: "final", acked_at: row.acked_at, ack_reference: str(i, "ack_reference"), acked_by: str(i, "acked_by") } });
          // batch roll-up (SM_LOSSMIT_HANDOFF_FILE_1): every handed-off case of the batch acked → the batch-level final ack on the aggregate 17.3's cutover freeze armed
          const roll = batchId ? batchHandoffRollup(batchRows(rt, batchId)) : null;
          if (roll?.all_acked) ctx.events.append({ type: "case.handoff.acked", aggregate: batchAgg(batchId), actor: ctx.actor, payload: { scope: "batch", stage: "final", all_cases: true, batch_id: batchId, handed_off: roll.handed_off, acked: roll.acked, transfer_date: T } });
          return { ...row, batch_rollup: roll }; }
        case "deficient": { need(i, "deficiencies"); const defs = strings(i, "deficiencies"); const row = move(from0, "deficient", { deficiencies: defs }); ctx.events.append({ type: "case.handoff.deficient", loanId, aggregate: agg, actor: ctx.actor, payload: { scope: "case", case_id: caseId, case_type: caseType, deficiencies: defs, raised_at: ctx.now, transfer_date: T } }); return { ...row, cure_by: addBusinessDays(D(ctx.now.slice(0, 10)), 5, servicer) }; }
        case "resolve": { need(i, "cure_document_id"); const row = move(from0, "resolved", { resolved_at: ctx.now, cure_document_id: str(i, "cure_document_id") }); ctx.events.append({ type: "case.handoff.resolved", loanId, aggregate: agg, actor: ctx.actor, payload: { scope: "case", case_id: caseId, case_type: caseType, resolved_at: ctx.now, cure_document_id: str(i, "cure_document_id") } }); return row; }
        case "close": { const row = move(from0, "closed_transferred", {}); ctx.events.append({ type: "case.closed", loanId, aggregate: agg, actor: ctx.actor, payload: { case_id: caseId, case_type: caseType, reason: "transferred_out", release_reason: "transfer_out", transferred_out_at: ctx.now } }); return { ...row, handoff_status: "closed_transferred" }; }
        default: throw new RangeError(`op ${op} is not one of package/deliver/ack/deficient/resolve/close`);
      } }),
    guardrails: [CHECKS_NOT_ASSERTED,
      never("WORKDOWN_UNDOCUMENTED", "17.4 timer table SM_LOSSMIT_PRE_T_WORKDOWN_T1: every 12.x action due in [T, T+10 federal BD] completed before T or documented in TO-03/04/05", (i) => Array.isArray(i.actions) && Boolean(str(i, "transfer_date")) && !workdownWindow({ transfer_date: D(str(i, "transfer_date")), actions: i.actions as { code: string; due: PlainDate }[] }).ok, "document the unexpired period for every action left to the transferee")] },
  { name: "forwardPostTransfer", kind: "act", handler: compute((i, ctx, rt) => { const op = str(i, "op") || "forward"; humanOnRequest(i, ctx, rt);
      if (op === "ack") { need(i, "forwarding_id", "transferee_ack_on"); const prev = rt.store.require("post_transfer_forwardings", str(i, "forwarding_id")).data; if (!prev.forwarded_at) throw new RangeError(`forwarding ${str(i, "forwarding_id")} has not been forwarded yet`); const rec = rt.store.put("post_transfer_forwardings", str(i, "forwarding_id"), { transferee_ack_at: str(i, "transferee_ack_on") }, ctx.actor, ctx.now);
        ctx.events.append({ type: "lossmit.forwarded_post_transfer", loanId: String(prev.loan_id), aggregate: { kind: "post_transfer_forwardings", id: rec.id }, actor: ctx.actor, payload: { kind: prev.kind, receipt_date: prev.received_at, forwarded_at: prev.forwarded_at, transferee_ack: true, transferee_ack_at: str(i, "transferee_ack_on"), stage: "acked" } }); return rec.data; }
      if (op === "receive") {   // the post-transfer submission addressed to Supermortgage: one receipt event (arms SM_LOSSMIT_POST_T_FORWARD_1 on received_at), never a 12.x intake
        need(i, "loan_id", "kind", "received_on", "transfer_date"); const kind = str(i, "kind") as ForwardKind; if (!FORWARD_KINDS.includes(kind)) throw new RangeError(`kind ${kind} is not one of ${FORWARD_KINDS.join("/")}`);
        const r = postTransferReceipt({ kind, received_on: date(i, "received_on"), transfer_date: date(i, "transfer_date"), loan_status: (str(i, "loan_status") || "transferred_out") as "transferred_out", acceptance_deadline: optDate(i, "acceptance_deadline") }); if (r.refusal) throw new RangeError(r.refusal);
        const rec = rt.store.put("post_transfer_forwardings", str(i, "id") || `fwd-${str(i, "loan_id")}-${kind}-${ctx.now}`, { loan_id: str(i, "loan_id"), kind, received_at: r.received_at, forwarded_at: null, transferee_ack_at: null, document_id: str(i, "document_id") || null }, ctx.actor, ctx.now);
        ctx.events.append({ type: r.event, loanId: str(i, "loan_id"), aggregate: { kind: "post_transfer_forwardings", id: rec.id }, actor: ctx.actor, payload: { forwarding_id: rec.id, kind, loan_status: r.loan_status, received_at: r.received_at, forward_by: r.forward_by, urgent_same_day: r.urgent_same_day, forward_on: r.forward_on, document_id: str(i, "document_id") || null } });
        return { forwarding_id: rec.id, ...rec.data, forward_by: r.forward_by, urgent_same_day: r.urgent_same_day, forward_on: r.forward_on }; }
      if (op !== "forward") throw new RangeError(`op ${op} is not one of receive/forward/ack`);
      const prior = str(i, "forwarding_id") ? rt.store.require("post_transfer_forwardings", str(i, "forwarding_id")).data : null;   // forwarding a recorded receipt: the loan, kind and receipt date are the receipt's
      if (prior) { for (const [k, v] of [["loan_id", prior.loan_id], ["kind", prior.kind], ["received_on", prior.received_at]] as const) if (i[k] !== undefined && String(i[k]) !== String(v)) throw new RangeError(`${k} ${String(i[k])} does not match receipt ${str(i, "forwarding_id")} (${String(v)})`); }
      const loanId = prior ? String(prior.loan_id) : str(i, "loan_id"); const kind = (prior ? String(prior.kind) : str(i, "kind")) as ForwardKind; const receivedOn = prior ? D(String(prior.received_at)) : date(i, "received_on");
      need(i, "transfer_date"); if (!loanId) throw new RangeError("loan_id is required"); if (!FORWARD_KINDS.includes(kind)) throw new RangeError(`kind ${kind} is not one of ${FORWARD_KINDS.join("/")}`);
      const forwardedOn = optDate(i, "forwarded_on") ?? todayOf(i, ctx);
      const r = postTransferForwarding({ kind, received_on: receivedOn, transfer_date: date(i, "transfer_date"), loan_status: (str(i, "loan_status") || "transferred_out") as "transferred_out", acceptance_deadline: optDate(i, "acceptance_deadline"), forwarded_on: forwardedOn, transferee_ack_on: optDate(i, "transferee_ack_on") });
      if (r.refusal) throw new RangeError(r.refusal);
      const rec = rt.store.put("post_transfer_forwardings", str(i, "forwarding_id") || str(i, "id") || `fwd-${loanId}-${kind}-${ctx.now}`, { loan_id: loanId, kind, received_at: r.receipt_date, forwarded_at: forwardedOn, transferee_ack_at: optDate(i, "transferee_ack_on"), document_id: str(i, "document_id") || (prior?.document_id as string | null | undefined) || null }, ctx.actor, ctx.now);
      ctx.events.append({ type: "lossmit.forwarded_post_transfer", loanId, aggregate: { kind: "post_transfer_forwardings", id: rec.id }, actor: ctx.actor, payload: { kind, receipt_date: r.receipt_date, forward_by: r.forward_by, forwarded_at: forwardedOn, urgent_same_day: r.urgent_same_day, transferee_ack: r.satisfied, stage: r.satisfied ? "acked" : "forwarded" } });
      if (r.breach) rt.escalations.open({ kind: "officer", loanId, severity: "sev1", payload: { reason: r.breach.reason } }, ctx.actor); return { forwarding_id: rec.id, ...rec.data, ...r }; }),
    guardrails: [NEVER_EVALUATE_TRANSFERRED] },
  // Decision record (spec AI agent design): {case_id, handoff_status, checks, actions_before_T, deadline_table, forwarded_items, rationale, reviewer, model_version, rule_set_version} — the subject is the case.
  { name: "writeDecision", kind: "act", handler: compute((i, ctx) => { need(i, "case_id", "handoff_status", "rationale", "rule_set_version", "model_version");
      const record = { case_id: str(i, "case_id"), handoff_status: str(i, "handoff_status"), checks: Array.isArray(i.checks) ? i.checks : [], actions_before_T: strings(i, "actions_before_T"), deadline_table: Array.isArray(i.deadline_table) ? i.deadline_table : [], forwarded_items: strings(i, "forwarded_items"), rationale: str(i, "rationale"), reviewer: str(i, "reviewer") || null, model_version: str(i, "model_version"), rule_set_version: str(i, "rule_set_version") };
      const out = decision()({ ...i, action: str(i, "action") || `case.handoff.${record.handoff_status}`, subject: { kind: "case", id: record.case_id }, rationale: record.rationale, rule_set_version: record.rule_set_version }, ctx);
      return { ...(out as Record<string, unknown>), record }; }) },
]);
