/**
 * §21.3 process-owned tools — bus tools for 21.3 defined with `defineTools("21.3", <agent>, defs)` from
 * ../tools.ts. Every tool string must be one spec/registry/agents.json names for 21.3; src/app/tools.test.ts refuses
 * the rest. Spread by ./index.ts.
 *
 * The `disclosure` agent's companion tools ride `CompanionDisclosureService` (src/domain/application/ops-21-3.ts),
 * wired into the runtime as `services.companion`: `planCompanionPackage` (rule 2 — every rule evaluated on
 * `application.received`), `evaluateExemptions` (Toolkit/SDS/ARM/AfBA reasons), `generateCounselingList` (rule 3),
 * `selectBookletEdition` (rule 5 — Toolkit 2026-08 / CHARM 2020-06, EN + ES courtesy copy), `renderScoreDisclosure`
 * (rule 6 — one consumer per document), `renderArmProgramDisclosure` (rule 7 — (i)–(xii), $10,000 illustration),
 * `evaluateAfBA` (rule 8 — relationship inventory, required-use exceptions, referral gate), `evaluateStateMatrix`
 * (rule 10), `renderNotice` (payload for the kind's Notice Registry code; SDS never), `assertConsent` (E-SIGN scope
 * `disclosures` before any electronic delivery), `deliver` / `recordReceipt` / `recordAcknowledgment` (state
 * machine), `markSatisfiedByLE` (rule 4), `setTimers` (the plan's clocks next to the engine's instances) and
 * `writeDecision` (the decision record).
 *
 * Guardrails encode the spec's "never" sentences: never mark a rule satisfied without a delivery/mailing/
 * acknowledgment event or an LE row inside the window; never deliver a counseling list obtained more than 30 days
 * earlier, with fewer than ten agencies, or generated from the property zip while a current-address zip exists;
 * never include one borrower's score in another borrower's notice; never alter the Toolkit or CHARM beyond (g)(2)
 * changes; never present consumer-specific ARM rates in the program disclosure; never require use of an affiliated
 * provider outside the three §1024.15(b)(2) exceptions; never treat an oral explanation as delivery of the privacy
 * notice; never issue an SDS on a forward loan; never deliver electronically without a prior valid consent; never
 * let a state gate be bypassed by a `human_agent` without a logged reason.
 */
import { defineTools, compute, decision, never, service, str, num, flag, type ToolDef, type ToolInput, type ToolRuntime } from "../tools.ts";
import { CompanionDisclosureService, toolkitRequirement, toolkitEditions, evaluateStateMatrix, afbaRelationship, afbaReferralGate, validateRequiredUse, markAffiliates, armIllustration, armProgramDisclosure, counselingListPayload, afbaStatementPayload, companionDueAt, TOOLKIT_EDITION, CHARM_EDITION, PRIVACY_EDITION, REQUIRED_USE_SERVICES, HCL_AGENCY_COUNT, HCL_MAX_AGE_DAYS, NOTICE_CODES, SDS_SCOPE, type CompanionKind, type CompanionChannel, type HudSnapshot, type AffiliateRelationship, type LeOut, type PlanInput, type Borrower } from "../../domain/application/ops-21-3.ts";
import { consentValidFor, isElectronic, DELIVERY_CHANNELS, type EsignConsent, type DeliveryChannel, type Provider } from "../../domain/application/ops-21-2.ts";
import { plainDate as D } from "../../kernel/calendar/date.ts";

const need = (i: ToolInput, ...keys: string[]): void => { for (const k of keys) if (i[k] === undefined || i[k] === null || i[k] === "") throw new RangeError(`${k} is required`); };
const svcOf = (rt: ToolRuntime): CompanionDisclosureService => service<CompanionDisclosureService>(rt, "companion");
const opt = (i: ToolInput, k: string): string | null => (typeof i[k] === "string" && i[k] !== "" ? (i[k] as string) : null);
const consentOf = (i: ToolInput): EsignConsent | null => (i.consent && typeof i.consent === "object" ? (i.consent as EsignConsent) : null);
const electronic = (i: ToolInput): boolean => i.channel === "esign_portal" || i.channel === "email";
const locator = (i: ToolInput): { disclosure_id?: string; kind?: CompanionKind; rule_code?: string; application_borrower_id?: string | null; le_version?: number } => ({
  ...(opt(i, "disclosure_id") ? { disclosure_id: opt(i, "disclosure_id")! } : {}), ...(opt(i, "kind") ? { kind: opt(i, "kind") as CompanionKind } : {}), ...(opt(i, "rule_code") ? { rule_code: opt(i, "rule_code")! } : {}),
  ...(i.application_borrower_id !== undefined ? { application_borrower_id: (i.application_borrower_id as string | null) ?? null } : {}), ...(i.le_version !== undefined ? { le_version: num(i, "le_version") } : {}) });
const bigint = (v: unknown, what: string): bigint => { if (typeof v === "bigint") return v; if (typeof v === "number" && Number.isInteger(v)) return BigInt(v); if (typeof v === "string" && /^-?\d+$/.test(v)) return BigInt(v); throw new RangeError(`${what} must be integer cents`); };
const rels = (i: ToolInput): AffiliateRelationship[] => (Array.isArray(i.affiliate_relationships) ? (i.affiliate_relationships as AffiliateRelationship[]) : []);
const yyyymm = (iso: string): string => iso.slice(0, 7);

const STATE_GATE_BYPASS = never("STATE_GATE_BYPASS_UNLOGGED", "21.3 guardrails: never let a state gate be bypassed by a `human_agent` without a logged reason (3 NYCRR 38.3; N.J.A.C. 3:1-16.3; A.R.S. §6-946(C); R. 69B-124.002)", (i) => flag(i, "bypass_state_gate") && !str(i, "reason"), "a state pre-application/fee gate may only be bypassed with a logged reason");
const NO_ESIGN = never("NO_ESIGN_CONSENT", "21.3 guardrails: never deliver electronically without a prior valid consent (15 U.S.C. 7001(c); §1016.9(b)(1)(iii); §1026.19(b) delivered electronically on/with the application)", (i) => electronic(i) && !consentValidFor(consentOf(i), typeof i.at === "string" ? (i.at as string) : new Date().toISOString()).ok, "electronic delivery needs an unrevoked E-SIGN consent scoped to disclosures obtained before delivery");

export const TOOLS_21_3: readonly ToolDef[] = defineTools("21.3", "disclosure", [
  { name: "planCompanionPackage", kind: "act", handler: compute((i, _c, rt) => { need(i, "application_id", "application_received_at", "transaction_type", "borrowers");
      const borrowers = i.borrowers as Borrower[]; if (!Array.isArray(borrowers) || !borrowers.length) throw new RangeError("borrowers must be a non-empty array");
      const plan: PlanInput = { application_id: str(i, "application_id"), application_received_at: str(i, "application_received_at"), transaction_type: str(i, "transaction_type"), borrowers, property_state: opt(i, "property_state"), property_zip5: opt(i, "property_zip5"), interview_language: opt(i, "interview_language"),
        ...(i.first_lien_dwelling !== undefined ? { first_lien_dwelling: i.first_lien_dwelling === true } : {}), ...(i.privacy_edition !== undefined ? { privacy_edition: str(i, "privacy_edition") } : {}), le_servicing_intent: "service" };
      const r = svcOf(rt).planCompanionPackage(plan);
      return { package: r.package, rows: r.rows.map((x) => ({ disclosure_id: x.disclosure_id, kind: x.kind, rule_code: x.rule_code, timer_code: x.timer_code, required: x.required, exemption_reason: x.exemption_reason, anchor_at: x.anchor_at, due_at: x.due_at, status: x.status })), state_matrix: { state: r.matrix.state, rows: r.matrix.rows.map((x) => x.rule_code), confidence: r.matrix.confidence } }; }),
    guardrails: [never("SERVICING_INTENT", "21.3 rule 11 / 21.2 §1026.37(m)(6): the LE's servicing statement is always `service`; the SDS row references it", (i) => i.le_servicing_intent !== undefined && i.le_servicing_intent !== "service", "the servicing intent referenced by the SDS exemption row is always `service`"), STATE_GATE_BYPASS] },
  { name: "evaluateExemptions", kind: "read", handler: compute((i) => { const tt = opt(i, "transaction_type") ?? "purchase"; const tk = toolkitRequirement(tt, i.residential_1_4 !== false); const reverse = tt === "reverse";
      return { toolkit: { required: tk.required, exemption_reason: tk.exemption_reason, edition: tk.edition }, sds: { required: reverse, exemption_reason: reverse ? null : "reverse_only", scope: SDS_SCOPE }, hcl: { required: !reverse, exemption_reason: reverse ? "reverse_only" : null },
        arm: { required: flag(i, "arm_interest"), exemption_reason: flag(i, "arm_interest") ? null : "fixed_rate" }, afba: { required: rels(i).length > 0 && flag(i, "affiliate_referral"), exemption_reason: rels(i).length > 0 && flag(i, "affiliate_referral") ? null : "no_affiliate_referral", inventory: rels(i).length },
        hpml: { required: flag(i, "is_hpml"), exemption_reason: flag(i, "is_hpml") ? null : "not_hpml" }, regb_appraisal_notice: { required: i.first_lien_dwelling !== false, exemption_reason: i.first_lien_dwelling !== false ? null : "state_not_applicable" } }; }) },
  { name: "generateCounselingList", kind: "act", handler: compute((i, ctx, rt) => { need(i, "application_id", "hud"); const hud = i.hud as HudSnapshot; if (!hud || !Array.isArray(hud.agencies)) throw new RangeError("hud must be a HUD snapshot {snapshot_at, centroid, agencies[]}");
      const r = svcOf(rt).generateCounselingList(str(i, "application_id"), { hud, at: opt(i, "at") ?? ctx.now, borrower_id: opt(i, "borrower_id") });
      return { list_id: r.list.list_id, disclosure_id: r.row.disclosure_id, zip_used: r.list.zip_used, zip_source: r.list.zip_source, hud_snapshot_at: r.list.hud_snapshot_at, agency_count: r.list.agencies.length, accompanying_language_version: r.list.accompanying_language_version, status: r.row.status }; }),
    guardrails: [never("HCL_SHORT_LIST", "12 CFR 1024.20(a)(1); 80 FR 22091: the list carries exactly ten HUD-approved agencies", (i) => Array.isArray((i.hud as HudSnapshot | undefined)?.agencies) && (i.hud as HudSnapshot).agencies.length < HCL_AGENCY_COUNT, `the HUD data must yield at least ${HCL_AGENCY_COUNT} agencies`),
      never("HCL_PROPERTY_ZIP_WITH_CURRENT", "21.3 guardrails: never generate the list from the property zip while a current-address zip exists (§1024.20(a)(1); 80 FR 22091 'zip code of the loan applicant's current address')", (i) => i.zip_source === "property_address_overseas" && /^\d{5}$/.test(str(i, "current_address_zip5")), "the applicant's current-address zip is the list's zip"),
      never("HCL_STALE_DATA", `12 CFR 1024.20(a)(1): the list must be obtained no earlier than ${HCL_MAX_AGE_DAYS} days before it is provided`, (i) => typeof (i.hud as HudSnapshot | undefined)?.snapshot_at === "string" && typeof i.deliver_at === "string" && (Date.parse(i.deliver_at as string) - Date.parse((i.hud as HudSnapshot).snapshot_at)) / 86_400_000 > HCL_MAX_AGE_DAYS, "regenerate the list from fresh HUD data before delivery")] },
  { name: "selectBookletEdition", kind: "read", handler: compute((i) => { const tt = opt(i, "transaction_type"); const tk = tt ? toolkitRequirement(tt, i.residential_1_4 !== false) : null;
      return { toolkit: { edition: TOOLKIT_EDITION, languages: toolkitEditions(opt(i, "interview_language")), required: tk?.required ?? null, exemption_reason: tk?.exemption_reason ?? null, unaltered: true, partner_cover_permitted: true }, charm: { edition: CHARM_EDITION, languages: toolkitEditions(opt(i, "interview_language")), unaltered: true }, privacy: { edition: opt(i, "privacy_edition") ?? PRIVACY_EDITION } }; }),
    guardrails: [never("BOOKLET_ALTERED", "12 CFR 1026.19(g)(2); 21.3 guardrails: never alter the Toolkit or CHARM beyond (g)(2) changes", (i) => (i.toolkit_edition !== undefined && i.toolkit_edition !== TOOLKIT_EDITION) || (i.charm_edition !== undefined && i.charm_edition !== CHARM_EDITION) || flag(i, "altered_content"), `the Toolkit edition in force is ${TOOLKIT_EDITION} and the CHARM edition ${CHARM_EDITION}, delivered unchanged`)] },
  { name: "renderScoreDisclosure", kind: "act", handler: compute((i, _c, rt) => { need(i, "application_id", "application_borrower_id", "lender"); const l = i.lender as { name?: string; nmlsr_id?: string; address?: string }; if (!l.name || !l.nmlsr_id || !l.address) throw new RangeError("lender needs name, nmlsr_id and address");
      return svcOf(rt).renderScoreDisclosure(str(i, "application_id"), str(i, "application_borrower_id"), { name: l.name, nmlsr_id: l.nmlsr_id, address: l.address }); }),
    guardrails: [never("CROSS_BORROWER_SCORE", "12 CFR 1022.75(c); 21.3 guardrails: never include one borrower's score in another borrower's notice", (i) => Array.isArray(i.include_borrower_ids) && (i.include_borrower_ids as unknown[]).some((b) => b !== i.application_borrower_id), "a score notice carries exactly one consumer's scores")] },
  { name: "renderArmProgramDisclosure", kind: "act", handler: compute((i, ctx) => { need(i, "fnma_plan_number"); const ill = armIllustration(str(i, "fnma_plan_number"), opt(i, "initial_rate_pct") ?? "5.875", opt(i, "illustration_as_of") ?? yyyymm(ctx.now), i.term_months !== undefined ? num(i, "term_months") : 360);
      return armProgramDisclosure(str(i, "fnma_plan_number"), ill, { discounted: flag(i, "discounted") }); }),
    guardrails: [never("CONSUMER_SPECIFIC_RATE", "SAFE Act App. A (b)(2)(i); 21.3 guardrails: never present consumer-specific ARM rates in the program disclosure", (i) => i.consumer_rate_pct !== undefined || i.consumer_margin_pct !== undefined || flag(i, "consumer_specific"), "the program disclosure carries program-level information only; particular terms are 21.2/21.4 under the MLO of record")] },
  { name: "evaluateAfBA", kind: "act", handler: compute((i, ctx, rt) => { need(i, "provider_party_id", "service"); validateRequiredUse(str(i, "service"), flag(i, "required_use"));
      if (opt(i, "application_id")) { const r = svcOf(rt).requestReferral(str(i, "application_id"), { referring_party_id: opt(i, "referring_party_id") ?? "partner", provider_party_id: str(i, "provider_party_id"), provider_name: opt(i, "provider_name") ?? str(i, "provider_party_id"), service: str(i, "service"), at: opt(i, "at") ?? ctx.now, source_process: opt(i, "source_process") ?? "21.2", required_use: flag(i, "required_use") });
        return { referral: r.referral, gate: r.gate, afba_disclosure_id: r.afba_row?.disclosure_id ?? null, afba_required: r.referral.afba_required }; }
      const on = D(opt(i, "on") ?? ctx.now.slice(0, 10)); const rel = afbaRelationship(rels(i), (i.referring_party_ids as string[] | undefined) ?? ["partner", "sm"], str(i, "provider_party_id"), on);
      const providers = Array.isArray(i.providers) ? markAffiliates((i.providers as Provider[]).map((p) => ({ ...p, estimated_fee_cents: bigint(p.estimated_fee_cents ?? 0n, `${p.name} estimated_fee_cents`) })), rels(i), (i.referring_party_ids as string[] | undefined) ?? ["partner", "sm"], on) : [];
      const gate = afbaReferralGate({ afba_required: rel !== null, disclosure_out_at: opt(i, "disclosure_out_at"), referred_at: opt(i, "referred_at") ?? ctx.now, required_provider: flag(i, "required_use"), application_received_at: opt(i, "application_received_at") });
      return { afba_required: rel !== null, relationship: rel, gate, providers, statement: rel ? afbaStatementPayload(rel, { referring_party_name: opt(i, "referring_party_name") ?? "the lender", applicant_name: opt(i, "applicant_name") ?? "", service: str(i, "service"), on, lender_name: opt(i, "lender_name") ?? "" }) : null }; }),
    guardrails: [never("REQUIRED_USE_OUTSIDE_1024_15B2", "12 CFR 1024.15(b)(2); 21.3 guardrails: never require use of an affiliated provider outside the three exceptions (attorney, credit reporting agency, appraiser)", (i) => flag(i, "required_use") && !!str(i, "service") && !REQUIRED_USE_SERVICES.includes(str(i, "service")), `required use is permitted only for ${REQUIRED_USE_SERVICES.join("/")}`)] },
  { name: "evaluateStateMatrix", kind: "read", handler: compute((i) => { const m = evaluateStateMatrix({ property_state: opt(i, "property_state"), interview_language: opt(i, "interview_language") });
      return { state: m.state, confidence: m.confidence, federal_only: m.federal_only, rows: m.rows.map((r) => ({ rule_code: r.rule_code, trigger: r.trigger, armed_on: r.armed_on, notice_code: r.notice_code, acknowledgment: r.acknowledgment, blocking: r.blocking, timer_code: r.timer_code, blocks: [...r.blocks], confidence: r.confidence })), pre_application_gates: m.pre_application_gates.map((r) => r.timer_code) }; }) },
  { name: "renderNotice", kind: "act", handler: compute((i, ctx, rt) => { need(i, "application_id", "kind"); const svc = svcOf(rt); const app = str(i, "application_id"); const kind = str(i, "kind") as CompanionKind;
      if (kind === "sds") throw new RangeError(`${NOTICE_CODES.sds} is never rendered on a forward loan (scope ${SDS_SCOPE}; §1024.33(a))`);
      const lender = (i.lender as { name?: string; nmlsr_id?: string; address?: string } | undefined) ?? {}; const lenderName = lender.name ?? opt(i, "lender_name") ?? ""; const nmlsr = lender.nmlsr_id ?? opt(i, "lender_nmlsr_id") ?? "";
      let payload: Record<string, unknown>;
      if (kind === "hcl") { const l = svc.counselingList(app); if (!l) throw new RangeError(`no counseling list for ${app} — generateCounselingList first`); payload = counselingListPayload(l, { applicant_name: opt(i, "applicant_name") ?? "", lender_name: lenderName, lender_nmlsr_id: nmlsr, application_id: app }); }
      else if (kind === "credit_score_notice" || kind === "rbp_notice") { need(i, "application_borrower_id"); payload = svc.renderScoreDisclosure(app, str(i, "application_borrower_id"), { name: lenderName, nmlsr_id: nmlsr, address: lender.address ?? "" }); }
      else if (kind === "arm_program") { need(i, "fnma_plan_number"); const ill = armIllustration(str(i, "fnma_plan_number"), opt(i, "initial_rate_pct") ?? "5.875", opt(i, "illustration_as_of") ?? yyyymm(ctx.now)); payload = { ...armProgramDisclosure(str(i, "fnma_plan_number"), ill, { discounted: flag(i, "discounted") }), lender_name: lenderName }; }
      else if (kind === "afba") { const rel = (i.relationship as AffiliateRelationship | undefined) ?? rels(i)[0]; if (!rel) throw new RangeError("afba needs the affiliate relationship"); payload = afbaStatementPayload(rel, { referring_party_name: opt(i, "referring_party_name") ?? lenderName, applicant_name: opt(i, "applicant_name") ?? "", service: opt(i, "service") ?? rel.services[0] ?? "", on: D(opt(i, "on") ?? ctx.now.slice(0, 10)), lender_name: lenderName }); }
      else { const row = svc.find(app, { kind, ...(opt(i, "rule_code") ? { rule_code: opt(i, "rule_code")! } : {}) }); if (!row) throw new RangeError(`no ${kind} row for ${app}`); payload = { application_id: app, disclosure_id: row.disclosure_id, rule_code: row.rule_code, notice_code: row.notice_code, asset_version: row.asset_version, language_edition: row.language_edition, due_at: row.due_at, lender_name: lenderName, lender_nmlsr_id: nmlsr, ...((i.payload as Record<string, unknown> | undefined) ?? {}) }; }
      const template_code = opt(i, "template_code") ?? NOTICE_CODES[kind] ?? svc.find(app, { kind })?.notice_code ?? null;
      const notice = template_code && rt.notices ? rt.notices.render({ templateCode: template_code, loanId: ctx.loanId, recipients: (i.recipients as never[] | undefined) ?? [], payload, asOf: D(ctx.now.slice(0, 10)) }) : null;
      return { template_code, payload, notice_id: notice?.id ?? null, rendered: notice !== null }; }),
    guardrails: [never("SDS_NEVER_ISSUED", "12 CFR 1024.33(a); 21.3 rule 11: never issue an SDS on a forward loan (scope reverse_only)", (i) => i.kind === "sds" || i.template_code === "NTC_REGX_1024_33A_SDS", "the RESPA Servicing Disclosure Statement is reverse-mortgage-only; the LE's servicing statement is the forward-loan disclosure"),
      never("CROSS_BORROWER_SCORE", "12 CFR 1022.75(c); 21.3 guardrails: never include one borrower's score in another borrower's notice", (i) => (i.kind === "credit_score_notice" || i.kind === "rbp_notice") && Array.isArray(i.include_borrower_ids) && (i.include_borrower_ids as unknown[]).some((b) => b !== i.application_borrower_id), "a score notice carries exactly one consumer's scores"),
      never("CONSUMER_SPECIFIC_RATE", "SAFE Act App. A (b)(2)(i); 21.3 guardrails: never present consumer-specific ARM rates in the program disclosure", (i) => i.kind === "arm_program" && (i.consumer_rate_pct !== undefined || flag(i, "consumer_specific")), "the program disclosure carries program-level information only")] },
  { name: "assertConsent", kind: "read", handler: compute((i, ctx) => { need(i, "channel"); const ch = str(i, "channel") as CompanionChannel; const at = opt(i, "at") ?? ctx.now;
      if (ch === "oral") return { ok: false, channel: ch, reason: "an oral explanation is not a delivery channel (§1016.9(d))" };
      if (!DELIVERY_CHANNELS.includes(ch as DeliveryChannel)) throw new RangeError(`channel ${ch} is not one of ${DELIVERY_CHANNELS.join("/")}`);
      if (!isElectronic(ch as DeliveryChannel)) return { ok: true, channel: ch, consent_required: false };
      const c = consentValidFor(consentOf(i), at); return { ok: c.ok, channel: ch, consent_required: true, consent_id: c.ok ? consentOf(i)!.id : null, ...(c.reason ? { reason: c.reason } : {}), scope: "disclosures" }; }) },
  { name: "deliver", kind: "act", handler: compute((i, ctx, rt) => { need(i, "application_id", "channel");
      const row = svcOf(rt).deliver(str(i, "application_id"), { ...locator(i), channel: str(i, "channel") as CompanionChannel, at: opt(i, "at") ?? ctx.now, consent: consentOf(i), mailing_proof_id: opt(i, "mailing_proof_id"), asset_version: opt(i, "asset_version"), rendered_document_id: opt(i, "rendered_document_id"), with_le_disclosure_id: opt(i, "with_le_disclosure_id") });
      return { disclosure_id: row.disclosure_id, kind: row.kind, rule_code: row.rule_code, status: row.status, delivered_at: row.delivered_at, mailed_at: row.mailed_at, mailing_proof_id: row.mailing_proof_id, delivery_channel: row.delivery_channel, asset_version: row.asset_version }; }),
    guardrails: [NO_ESIGN, never("ORAL_NOT_DELIVERY", "12 CFR 1016.9(d); 21.3 guardrails: never treat an oral explanation as delivery of the privacy notice", (i) => i.channel === "oral", "reading a notice aloud is not delivery; mail or deliver electronically under consent"),
      never("SDS_NEVER_ISSUED", "12 CFR 1024.33(a); 21.3 rule 11: never issue an SDS on a forward loan", (i) => i.kind === "sds", "the RESPA Servicing Disclosure Statement is reverse-mortgage-only"),
      never("BOOKLET_ALTERED", "12 CFR 1026.19(g)(2); 21.3 guardrails: never alter the Toolkit or CHARM beyond (g)(2) changes", (i) => (i.kind === "toolkit" && i.asset_version !== undefined && i.asset_version !== TOOLKIT_EDITION) || (i.kind === "charm" && i.asset_version !== undefined && i.asset_version !== CHARM_EDITION), `deliver the CFPB PDFs unchanged (Toolkit ${TOOLKIT_EDITION}, CHARM ${CHARM_EDITION})`),
      never("HCL_PROPERTY_ZIP_WITH_CURRENT", "21.3 guardrails: never deliver a list generated from the property zip while a current-address zip exists", (i) => i.kind === "hcl" && i.zip_source === "property_address_overseas" && /^\d{5}$/.test(str(i, "current_address_zip5")), "regenerate from the applicant's current-address zip"), STATE_GATE_BYPASS] },
  { name: "recordReceipt", kind: "act", handler: compute((i, _c, rt) => { need(i, "application_id", "at", "borrower_id", "evidence");
      const row = svcOf(rt).recordReceipt(str(i, "application_id"), { ...locator(i), at: str(i, "at"), borrower_id: str(i, "borrower_id"), evidence: str(i, "evidence") as "authenticated_view" | "acknowledgement" | "esignature" | "courier" });
      return { disclosure_id: row.disclosure_id, kind: row.kind, status: row.status, received_at: row.received_at }; }) },
  { name: "recordAcknowledgment", kind: "act", handler: compute((i, _c, rt) => { need(i, "application_id", "at", "borrower_id", "method", "evidence_id");
      const row = svcOf(rt).recordAcknowledgment(str(i, "application_id"), { ...locator(i), at: str(i, "at"), borrower_id: str(i, "borrower_id"), method: str(i, "method") as "esignature" | "confirm_button" | "signed_copy" | "portal_step", evidence_id: str(i, "evidence_id") });
      return { disclosure_id: row.disclosure_id, kind: row.kind, status: row.status, acknowledged_at: row.acknowledged_at, acknowledgment_evidence_id: row.acknowledgment_evidence_id }; }),
    guardrails: [STATE_GATE_BYPASS, never("ACK_WITHOUT_EVIDENCE", "21.3 guardrails: never mark a rule satisfied without a delivery/mailing/acknowledgment event", (i) => i.evidence_id === "" || flag(i, "assume_acknowledged"), "an acknowledgment needs the e-signature, confirm-button or signed-copy evidence id")] },
  { name: "markSatisfiedByLE", kind: "act", handler: compute((i, _c, rt) => { need(i, "application_id", "le_disclosure_id"); if (!opt(i, "delivered_at") && !opt(i, "mailed_at")) throw new RangeError("the LE's delivered_at or mailed_at is required (rule 4: le_out = min(delivered_at, mailed_at))");
      const le: LeOut = { disclosure_id: str(i, "le_disclosure_id"), delivered_at: opt(i, "delivered_at"), mailed_at: opt(i, "mailed_at"), ...(i.le_version !== undefined ? { le_version: num(i, "le_version") } : {}) };
      const r = svcOf(rt).markSatisfiedByLE(str(i, "application_id"), le); return { disclosure_id: r.regb.disclosure_id, status: r.regb.status, satisfied_by_disclosure_id: r.regb.satisfied_by_disclosure_id, satisfied_by_le: r.satisfied_by_le, le_out: r.le_out, due_at: r.regb.due_at }; }),
    guardrails: [never("SATISFIED_WITHOUT_EVIDENCE", "21.3 guardrails: never mark a rule satisfied without a delivery/mailing/acknowledgment event or an LE row inside the window (§1002.14(a)(2); comment 37(m)(1)-1)", (i) => flag(i, "force_satisfied") || (!!str(i, "le_disclosure_id") && !opt(i, "delivered_at") && !opt(i, "mailed_at")), "only an LE actually delivered or placed in the mail on or before the Reg B due date is the appraisal notice")] },
  { name: "setTimers", kind: "read", handler: compute((i, ctx, rt) => { need(i, "application_id"); const app = str(i, "application_id"); const svc = svcOf(rt); const engine = ctx.timers.forSubject("application", app);
      const rows = svc.rowsFor(app).map((r) => ({ disclosure_id: r.disclosure_id, rule_code: r.rule_code, timer_code: r.timer_code, anchor_event: r.anchor_event, anchor_at: r.anchor_at, calendar: r.calendar_code, due_at: r.due_at, required: r.required, status: r.status, standalone_issue_by: r.standalone_issue_by, engine: engine.filter((t) => t.code === r.timer_code).map((t) => ({ id: t.id, status: t.status, due_date: t.dueDate ?? null, note: t.note ?? null })) }));
      const anchor = opt(i, "anchor_at"); const preview = anchor ? { anchor_at: anchor, due: [0, 1, 3].map((n) => ({ business_days: n, ...companionDueAt(anchor, n, svc.calendar) })) } : null;
      return { application_id: app, calendar: svc.calendar, rows, preview }; }) },
  { name: "writeDecision", kind: "write", handler: decision() },
]);
