/**
 * §9 tools — insurance and property protection (9.1–9.9). Tool strings are
 * verbatim from each process's Agents paragraph; guardrails encode the
 * "cannot"/"never" sentences and the human touchpoints. Agent:
 * `insurance-property` throughout.
 */
import { defineTools, escalate, compute, never, needsRole, humanWhen, noticeOps, port, guard, cents, str, num, flag, data, type ToolDef, type ToolInput } from "../tools.ts";
import { hasRole } from "../roles.ts";
import { reportClaim, depositProceeds, releaseProceeds, sendForm176, remit332 } from "../../domain/insurance/ops-9-7.ts";
import { ingestLpiCancelAck, lpiRemovalSet, lpiRefundPaymentSet, officerBreachRisk } from "../../domain/insurance/ops-9-5.ts";
import { plainDate as D, addDays, type PlainDate } from "../../kernel/calendar/date.ts";
import { evaluateAdequacy, verifyPolicy, type HazardPolicy, type Deficiency } from "../../domain/insurance/hazard.ts";
import { reasonableBasis, escrowGuard, reminderVariant, premiumQuote, lpiCoverage, renewalClocks, renewalNoticeAllowed, renewalChargeAllowed, renewalCharge, gapChargeDecision, chargeDecision, fpiClocks, type BasisKind, type EvidenceRow } from "../../domain/insurance/fpi.ts";
import { cancellation, type CancellationInput } from "../../domain/insurance/refund.ts";
import { floodRequired, floodRequiredAmount, floodAdequate, privatePolicyAcceptable, placementAllowed, floodNoticeClocks, type FloodRequirementInput, type PrivatePolicyInput } from "../../domain/insurance/flood.ts";
import { lossDraftTrack, initialRelease, releaseLimit, thirdPartyReleaseAllowed, remoteInspectionAcceptable, notRebuildableDisposition, form176Due, reogramRemitDue, workoutEvaluationRequired, type ReleaseInput, type ReleaseKind, type ReleaseCheck } from "../../domain/insurance/lossdraft.ts";
import { inspectionWindow, inspectionMode, inspectionSuspended, inspectionType, nextInspectionWindow, pfpipTaskDue, pfpipPermission, inspectionOrderAllowed, fnmaDaysDelinquent, INSURED_LOSS_REPAIR_INSPECTION_CAP, type ExceptionInput } from "../../domain/insurance/inspection.ts";
import { evaluateScope, bidPackage, photosFresh, preservationMode, type WorkItem } from "../../domain/insurance/preservation.ts";
import { vacancyConfirmed, pfpipSubmission, vacantRegistration, placementConfig, refundTimeline } from "../../domain/insurance/ops.ts";
import { inspectionSweep, recordInspectionResult, occupancyUpdated, pfpipChangeReported } from "../../domain/insurance/ops-9-8.ts";
import { postingPlaced, conditionDiscovered, workCompleted, reviewPhotos, parsePhotos, type ConditionItem } from "../../domain/insurance/ops-9-9.ts";
import { RULE_SET_9_1 } from "../../domain/insurance/ops-9-1.ts";
import { recordDeterminationResult } from "../../domain/insurance/ops-9-6.ts";

const need = (i: ToolInput, ...keys: string[]): void => { for (const k of keys) if (i[k] === undefined || i[k] === null || i[k] === "") throw new RangeError(`${k} is required`); };
const date = (i: ToolInput, k: string): PlainDate => { need(i, k); return D(str(i, k)); };
const optDate = (i: ToolInput, k: string): PlainDate | null => (typeof i[k] === "string" && i[k] !== "" ? D(str(i, k)) : null);
const rows = <T>(i: ToolInput, k: string): T[] => { const v = i[k]; if (!Array.isArray(v)) throw new RangeError(`${k} must be an array`); return v as T[]; };
const A = "insurance-property";
/** 9.7 rule 1 / inputs: the claim report from any channel (also reused by 9.8 inspection findings and 9.9 preservation) — reportClaim (ops-9-7.ts) emits `insurance.claim.reported` and the rule-9 / D1-3-01 events that arm the 9.7 clocks. */
const openClaim: Omit<ToolDef, "process" | "agent"> = { name: "openClaim", kind: "write", handler: compute((i, ctx, rt) => { need(i, "loan_id"); const loanId = str(i, "loan_id"); const id = str(i, "id") || `claim-${ctx.now}`;
    const r = reportClaim({ events: ctx.events, actor: ctx.actor, loanId, now: ctx.now }, { claim_id: id, policy_id: (i.policy_id as string | undefined) ?? null, loss_date: optDate(i, "loss_date"), loss_cause: str(i, "loss_cause") || null, fnma_days_delinquent: num(i, "fnma_days_delinquent") || 0, abandoned: flag(i, "abandoned"), fc_sale_scheduled: flag(i, "fc_sale_scheduled"), rebuildable: (str(i, "rebuildable") || "unknown") as "yes" | "no" | "unknown", intends_to_repair: typeof i.intends_to_repair === "boolean" ? i.intends_to_repair : null, learned_on: optDate(i, "learned_on"), reported_on: optDate(i, "reported_on"), disaster_event_id: (i.disaster_event_id as string | undefined) ?? null, foreclosure_prereferral: flag(i, "foreclosure_prereferral") });
    const rec = rt.store.put("insurance_claims", id, { loan_id: loanId, policy_id: (i.policy_id as string | undefined) ?? null, case_type: "insurance_claim", track: r.track, uninsured: r.uninsured, status: "intake", loss_date: optDate(i, "loss_date"), loss_cause: str(i, "loss_cause") || null, property_status: r.property_status, disaster_event_id: (i.disaster_event_id as string | undefined) ?? null, reported_at: ctx.now, track_determined_at: ctx.now, proof_of_loss_due: r.proof_of_loss_due, form176_due: r.form176_due }, ctx.actor, ctx.now);
    return { id: rec.id, track: r.track, uninsured: r.uninsured, workout_evaluation_required: r.workout_evaluation_required, property_status: r.property_status, proof_of_loss_due: r.proof_of_loss_due, form176_due: r.form176_due, form176_cause: r.form176_cause, disaster_fc_approval_due: r.disaster_fc_approval_due, events: r.events }; }) };
const notifyCarrierVacancy: Omit<ToolDef, "process" | "agent"> = { name: "notifyCarrierVacancy", kind: "act", handler: compute((i, ctx) => { need(i, "loan_id", "vacancy_on"); ctx.events.append({ type: "insurance.carrier.vacancy_notified", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { vacancy_on: str(i, "vacancy_on") } }); return { notified: true, coverage_review: "vacancy endorsement or LPI vacant-property coverage (9.1 rule 6)" }; }) };

// ---- 9.1 -------------------------------------------------------------------------
const holders = (i: ToolInput): string[] => (Array.isArray(i.title_holders) ? (i.title_holders as string[]) : []);
/** The policy under review, with an officer's rating waiver applied as the documented mortgage-impairment exception (B7-3-01). */
const policyOf = (i: ToolInput): HazardPolicy | undefined => { const p = i.policy; if (!p || typeof p !== "object") return undefined; return flag(i, "waive_rating_failure") ? { ...(p as HazardPolicy), rating_exception: "mortgage_impairment" } : (p as HazardPolicy); };
/** Would recordDeficiency leave the policy with no deficiency — i.e. mark it `verified`? */
const wouldVerify = (i: ToolInput): boolean => { const p = policyOf(i); try { return p ? evaluateAdequacy(p, holders(i)).pass : Array.isArray(i.deficiencies) && i.deficiencies.length === 0; } catch { return false; } };
const p91 = defineTools("9.1", A, [
  { name: "recordDeficiency", kind: "write", handler: compute((i, ctx, rt) => { need(i, "loan_id"); const p = policyOf(i); const verification = p ? verifyPolicy(p, holders(i), typeof i.evidence_id === "string" && i.evidence_id !== "") : null; const defs = verification ? verification.adequacy.deficiencies : rows<Deficiency>(i, "deficiencies");
      if (p) rt.store.put("insurance_policies", str(i, "policy_id") || `pol-${str(i, "loan_id")}`, { loan_id: str(i, "loan_id"), status: verification!.status, last_known_coverage_cents: verification!.last_known_coverage_cents, evidence_document_id: (i.evidence_id as string | undefined) ?? null, rating_waived_by: flag(i, "waive_rating_failure") ? `${ctx.actor.kind}:${ctx.actor.id}` : null }, ctx.actor, ctx.now);
      if (defs.length === 0) { if (verification?.status === "verified") ctx.events.append({ type: "insurance.policy.verified", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { policy_id: str(i, "policy_id") || `pol-${str(i, "loan_id")}`, evidence_id: str(i, "evidence_id"), verified_at: ctx.now, expiration_date: optDate(i, "expiration_date"), term: str(i, "term") || "initial", last_known_coverage_cents: verification.last_known_coverage_cents, deductible_pct: verification.adequacy.deductible_pct, rule_set: RULE_SET_9_1 } });   // arms FNMA_B202_POLICY_ANNUAL_VERIFY_365 / INS_EXPIRATION_WATCH_60; satisfies INS_EXPIRATION_LAPSE_1
        return { id: null, status: verification?.status ?? "verified", deficiencies: [], lpi_curable: false, last_known_coverage_cents: verification?.last_known_coverage_cents ?? null }; }
      const rec = rt.store.put("insurance_deficiencies", str(i, "id") || `def-${ctx.now}`, { loan_id: str(i, "loan_id"), deficiencies: defs, evidence_id: (i.evidence_id as string | undefined) ?? null, status: "open" }, ctx.actor, ctx.now);
      ctx.events.append({ type: "insurance.deficiency.detected", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { deficiency_id: rec.id, deficiencies: defs, detected_at: ctx.now, notice_template: "INS_DEFICIENCY_NOTICE" } });   // FNMA_B202_INSUFFICIENCY_NOTICE_5BD anchors on detected_at
      return { id: rec.id, status: "deficient", deficiencies: defs, lpi_curable: verification?.adequacy.lpi_curable ?? null, last_known_coverage_cents: null }; }),
    guardrails: [never("VERIFIED_NEEDS_EVIDENCE", "9.1 guardrail: the agent cannot mark a policy `verified` without a confirmed evidence record", (i) => wouldVerify(i) && !i.evidence_id, "an adequacy PASS becomes `verified` only with a confirmed evidence record (evidence_id); otherwise the policy stays pending_verification"),
      needsRole("RATING_WAIVER_OFFICER", "9.1 guardrail: a rating failure is waived only by an officer under documented mortgage-impairment cover", (i) => flag(i, "waive_rating_failure"), ["officer"], "rating waivers are officer decisions with mortgage-impairment cover documented")] },
  { name: "requestEscrowLineUpdate", kind: "write", handler: compute((i, ctx) => { need(i, "loan_id", "new_premium_cents"); const escrowedCurrent = flag(i, "escrowed") && num(i, "regx_days_delinquent") <= 30; const ev = ctx.events.append({ type: "escrow.line.update_requested", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { line: "hazard", premium_cents: cents(i.new_premium_cents) } });
      if (flag(i, "ask_borrower_to_pay")) ctx.events.append({ type: "insurance.premium.demanded", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { premium_cents: cents(i.new_premium_cents) } });
      return { ...ev, payer: escrowedCurrent ? "escrow — 3.7 pays/advances the renewal (§1024.17(k)(1)–(2))" : "borrower", borrower_demand: flag(i, "ask_borrower_to_pay") }; }),
    guardrails: [never("NO_PREMIUM_DEMAND_ESCROWED_CURRENT", "9.1 guardrail: cannot ask an escrowed current borrower to pay a premium", (i) => flag(i, "escrowed") && num(i, "regx_days_delinquent") <= 30 && flag(i, "ask_borrower_to_pay"), "the servicer pays the renewal from escrow (3.7)")] },
  { name: "openCase", kind: "write", handler: compute((i, ctx, rt) => { need(i, "loan_id", "case_type"); const rec = rt.store.put("cases", str(i, "id") || `case-${ctx.now}`, { loan_id: str(i, "loan_id"), case_type: str(i, "case_type"), status: "open" }, ctx.actor, ctx.now); return { id: rec.id, case_type: str(i, "case_type") }; }) },
]);
// ---- 9.2: assessReasonableBasis / checkEscrowGuard live in ./section9-2.ts (TOOLS_9_2, over the 9.2 case service) ----
// ---- 9.3 -------------------------------------------------------------------------
const p93 = defineTools("9.3", A, [
  { name: "selectReminderVariant", kind: "read", handler: compute((i) => reminderVariant(rows<EvidenceRow>(i, "evidence"), date(i, "lapse_start"), date(i, "as_of"))), guardrails: [never("DETERMINISTIC_VARIANT", "9.3 guardrail: variant selection is deterministic from evidence records — the model cannot override", (i) => typeof i.override_variant === "string", "the variant is derived from evidence rows only")] },
  { name: "quoteLpi", kind: "read", handler: compute((i) => { need(i, "coverage_cents"); const q = premiumQuote(i.carrier_quote_cents === undefined || i.carrier_quote_cents === null ? null : cents(i.carrier_quote_cents), cents(i.coverage_cents), str(i, "table_rate_pct") || "0"); return { ...q, traced_to: q.is_estimate ? `rate_table:${str(i, "rate_table_version") || "current"}` : `carrier_quote:${str(i, "quote_id") || "unknown"}` }; }),
    guardrails: [never("COST_TRACES_TO_RECORD", "9.3 guardrail: the cost figure must trace to a quote/rate-table record", (i) => flag(i, "manual_figure"), "no hand-entered premiums")] },
]);
// ---- 9.4 -------------------------------------------------------------------------
const renewalOf = (i: ToolInput) => renewalClocks(date(i, "placement_effective"), optDate(i, "t2"));
const p94 = defineTools("9.4", A, [
  { name: "reviewLpiCoverage", kind: "read", handler: compute((i) => ({ ...lpiCoverage({ last_known_cents: i.last_known_cents === undefined ? null : cents(i.last_known_cents), rcv_cents: cents(i.rcv_cents), upb_cents: cents(i.upb_cents), state_cap_cents: i.state_cap_cents === undefined ? null : cents(i.state_cap_cents), ...(flag(i, "vacant") ? { vacant: true } : {}) }), clocks: renewalOf(i) })),
    guardrails: [never("ONE_NOTICE_PER_YEAR", "9.4 guardrail: one notice per year (§1024.37(e)(5))", (i) => flag(i, "send_notice") && !renewalNoticeAllowed(i.last_notice as { mailed: PlainDate; anniversary: PlainDate } | null ?? null, D(str(i, "anniversary") || "2000-01-01"), D(str(i, "today") || "2000-01-01")), "a renewal notice was already mailed for this anniversary")] },
  { name: "quoteLpiRenewal", kind: "read", handler: compute((i) => { need(i, "coverage_cents"); const q = premiumQuote(i.carrier_quote_cents === undefined || i.carrier_quote_cents === null ? null : cents(i.carrier_quote_cents), cents(i.coverage_cents), str(i, "table_rate_pct") || "0");
      const rc = i.placement_effective ? renewalCharge(date(i, "placement_effective"), optDate(i, "t2"), q) : null;
      const gap = rc && i.gap_days !== undefined ? gapChargeDecision(num(i, "gap_days"), rc.daily_rate, flag(i, "lpi_prompt_charge_prohibited")) : null;
      return { ...q, charge_on: rc?.charge_on ?? null, term: rc?.term ?? null, daily_rate: rc ? rc.daily_rate.toFixed(6) : null, gap_charge: gap }; }),
    guardrails: [never("NO_CHARGE_BEFORE_GATE", "9.4 guardrail: no charge before the gate — rule 2: renewal charge date = max(A, t2 + 45) (§1024.37(e)(1)(i))", (i) => { if (!flag(i, "assess_charge")) return false; if (!i.placement_effective || !i.today) return true; return !renewalChargeAllowed(renewalOf(i), date(i, "today")).allowed; }, "the renewal charge waits for max(anniversary, MS-3(D) mailed + 45); without a mailed notice date and today's date the gate cannot be shown open"),
      never("GAP_CHARGE_JURISDICTION", "9.4 guardrail: gap charges only where the jurisdiction rule permits (§1024.37(e)(1)(iii) 'if not prohibited by State or other applicable law')", (i) => flag(i, "assess_gap_charge") && flag(i, "lpi_prompt_charge_prohibited"), "`lpi_prompt_charge_prohibited` — open a new 9.2 cycle instead (rule 4)")] },
]);
// ---- 9.5 -------------------------------------------------------------------------
const cancelInput = (i: ToolInput): CancellationInput => ({ terms: rows(i, "terms"), borrower_coverage_start: date(i, "borrower_coverage_start"), borrower_coverage_end: i.borrower_coverage_end ? D(str(i, "borrower_coverage_end")) : null, evidence_received_on: date(i, "evidence_received_on"), borrower_paid_cents: cents(i.borrower_paid_cents), ...(i.deadline_days === 30 ? { deadline_days: 30 as const } : {}) });
const trackOf = (i: ToolInput): "regx_hazard" | "fdpa_flood" => (str(i, "track") === "fdpa_flood" || i.deadline_days === 30 || str(i, "kind") === "flood" ? "fdpa_flood" : "regx_hazard");
const p95 = defineTools("9.5", A, [
  { name: "evaluateEvidence", kind: "write", handler: compute((i, ctx) => { need(i, "evidence_id"); const ok = flag(i, "continuous_coverage_shown") && flag(i, "written"); ctx.events.append({ type: "insurance.evidence.evaluated", loanId: ctx.loanId, actor: ctx.actor, payload: { evidence_id: str(i, "evidence_id"), kind: str(i, "kind") || "hazard", outcome: ok ? "confirmed" : "rejected" } }); return { outcome: ok ? "confirmed" : "rejected", reason: ok ? null : "evidence must be written and show continuous compliant coverage" }; }) },
  { name: "computeOverlapRefund", kind: "read", handler: compute((i) => cancellation(cancelInput(i))) },
  { name: "requestLpiCancel", kind: "act", handler: compute(async (i, ctx, rt) => { need(i, "binding_id", "cancelled_on"); const loanId = str(i, "loan_id") || ctx.loanId; const r = await port(rt, "lpi").cancel(str(i, "binding_id"), str(i, "cancelled_on"), ctx.now);
      // `request` is the registry anchor ("request") of INS_FPI_CARRIER_REFUND_RECON_45 (45 calendar days to reconcile the carrier's refund_advice).
      ctx.events.append({ type: "fpi.lpi.cancel_requested", loanId, actor: ctx.actor, payload: { binding_id: str(i, "binding_id"), effective: str(i, "cancelled_on"), track: trackOf(i), request: ctx.now.slice(0, 10), reason: str(i, "reason") || "borrower_coverage" } });
      // The servicer cancels on its own books at the borrower-coverage date; the carrier's ack reconciles later (9.5 state machine; INS_FPI_CARRIER_REFUND_RECON_45).
      ctx.events.append({ type: "fpi.lpi.cancelled", loanId, actor: ctx.actor, payload: { binding_id: str(i, "binding_id"), effective: str(i, "cancelled_on"), track: trackOf(i), on_books: true, carrier_ack: "pending" } });
      // A cancel ack that already carries the carrier's refund figure is the refund_advice — reconcile it now (ops-9-5); otherwise the 45-day clock waits for the advice.
      const carrier = ingestLpiCancelAck({ events: ctx.events, actor: ctx.actor, ledger: ctx.ledger, escalations: rt.escalations }, { loan_id: loanId, binding: r, received_on: D(ctx.now.slice(0, 10)), ...(typeof i.fnma_claim_paid === "boolean" ? { fnma_claim_paid: i.fnma_claim_paid } : {}) });
      return { binding: r, cancelled_on_books: true, effective: str(i, "cancelled_on"), carrier_refund: carrier }; }),
    guardrails: [never("NO_CANCELLATION_FEE", "9.5 guardrail: cannot charge a cancellation fee", (i) => cents(i.fee_cents) > 0n, "no cancellation fee")] },
  { name: "postRefund", kind: "write", moneyFields: ["refund_cents"], handler: compute((i, ctx) => { const r = cancellation(cancelInput(i)); const posted = i.refund_cents === undefined ? r.refund_cents : cents(i.refund_cents); const loanId = str(i, "loan_id") || ctx.loanId;
      // Rule 3(a)/6: the removal is a balanced reversal set linked to the original LPI charge (Cr corporate_advances / Dr lpi_refund_expense pending carrier reimbursement; escrowed: the 3.7 reversal) — never an edit of `lpi_charges`.
      const set = r.removed_cents > 0n && ctx.ledger ? ctx.ledger.post(lpiRemovalSet({ loan_id: loanId, removed_cents: r.removed_cents, effective: r.cancellation_effective, escrowed: flag(i, "escrowed"), ...(typeof i.custodial_ti === "string" ? { custodial_ti: i.custodial_ti } : {}), ...(typeof i.ledger_set_id === "string" ? { original_set_id: i.ledger_set_id } : {}), ...(typeof i.binding_id === "string" ? { binding_id: i.binding_id } : {}) }), ctx.now) : null;
      ctx.events.append({ type: "fpi.refund.posted", loanId, actor: ctx.actor, payload: { removed_cents: r.removed_cents, retained_cents: r.retained_cents, refund_cents: posted, still_due_cents: r.still_due_cents, overlap_days: r.overlap_days, cancellation_effective: r.cancellation_effective, deadline: r.deadline, root_cause: r.root_cause, escrowed: flag(i, "escrowed"), ledger_set_id: set?.id ?? null, binding_id: (i.binding_id as string | undefined) ?? null } });
      return { removed_cents: r.removed_cents, retained_cents: r.retained_cents, refund_cents: posted, still_due_cents: r.still_due_cents, root_cause: r.root_cause, ledger_set_id: set?.id ?? null, ledger: set ? set.lines.map((l) => `${l.amountCents > 0n ? "Dr" : "Cr"} ${l.account.account} ${l.amountCents > 0n ? l.amountCents : -l.amountCents}`) : ["Cr corporate_advances", "Dr lpi_refund_expense"] }; }),
    guardrails: [never("REFUND_NOT_BELOW_CALCULATOR", "9.5 guardrail: cannot reduce a refund below the calculator's figure", (i) => { try { return i.refund_cents !== undefined && cents(i.refund_cents) < cancellation(cancelInput(i)).refund_cents; } catch { return false; } }, "the calculator's figure is the floor")] },
  { name: "payRefund", kind: "act", moneyFields: ["refund_cents"], handler: compute((i, ctx, rt) => { need(i, "refund_cents", "rail"); const loanId = str(i, "loan_id") || ctx.loanId; const track = trackOf(i); const paidOn = D(ctx.now.slice(0, 10));
      const cancelledOnBooks = flag(i, "lpi_cancelled") || (loanId !== undefined && ctx.events.byLoan(loanId).some((e) => e.type === "fpi.lpi.cancelled" && (!i.binding_id || (e.payload as { binding_id?: unknown }).binding_id === i.binding_id)));
      // 9.5 escalations: `officer` at day 12 if unpaid is a breach-risk report, not a bar on paying — the agent still pays (automation class "a"; §1024.37(g) day 15).
      const evidenceOn = typeof i.evidence_received_on === "string" && i.evidence_received_on !== "" ? D(i.evidence_received_on) : Number.isFinite(num(i, "days_since_evidence")) ? D(addDays(paidOn, -num(i, "days_since_evidence"))) : null;
      const risk = evidenceOn ? officerBreachRisk({ events: ctx.events, actor: ctx.actor, escalations: rt.escalations }, { loan_id: loanId, evidence_received_on: evidenceOn, today: paidOn, paid: false, ...(track === "fdpa_flood" ? { deadline_days: 30 as const } : {}), ...(typeof i.binding_id === "string" ? { binding_id: i.binding_id } : {}) }) : null;
      // Rule 3(b): money out (ACH/check) against the credit balance the removal left on the loan; escrow/account credits move no cash.
      const setInput = lpiRefundPaymentSet({ loan_id: loanId, refund_cents: cents(i.refund_cents), effective: paidOn, rail: str(i, "rail"), escrowed: flag(i, "escrowed"), ...(typeof i.binding_id === "string" ? { binding_id: i.binding_id } : {}) });
      const set = setInput && ctx.ledger ? ctx.ledger.post(setInput, ctx.now) : null;
      ctx.events.append({ type: "fpi.refund.paid", loanId, actor: ctx.actor, payload: { refund_cents: cents(i.refund_cents), rail: str(i, "rail"), track, paid_on: paidOn, binding_id: (i.binding_id as string | undefined) ?? null, ledger_set_id: set?.id ?? null } });
      // §1024.37(g)(1)–(2) / 42 U.S.C. 4012a(e)(3): the clock is satisfied only when both legs are done — cancellation on the books AND the refund paid/credited.
      if (cancelledOnBooks) ctx.events.append({ type: "fpi.lpi.cancelled_and_refunded", loanId, actor: ctx.actor, payload: { track, refund_cents: cents(i.refund_cents), rail: str(i, "rail"), binding_id: (i.binding_id as string | undefined) ?? null, paid_on: paidOn } });
      return { paid: true, rail: str(i, "rail"), paid_on: paidOn, lpi_cancelled_on_books: cancelledOnBooks, ledger_set_id: set?.id ?? null, breach_risk_reported: risk?.reported ?? false, timer_satisfied: cancelledOnBooks ? (track === "fdpa_flood" ? "FDPA_4012A_E3_FLOOD_LPI_TERMINATE_REFUND_30" : "REGX_1024_37G_FPI_CANCEL_REFUND_15") : null }; }),
    guardrails: [never("NEVER_WAIT_FOR_CARRIER", "9.5 guardrail: cannot wait for the carrier — the borrower is refunded by day 15", (i) => flag(i, "wait_for_carrier_refund"), "the borrower refund is independent of the carrier's")] },
  { name: "notifyBorrower", kind: "act", handler: noticeOps("render_send") },
]);
// ---- 9.6 -------------------------------------------------------------------------
const p96 = defineTools("9.6", A, [
  { name: "orderDetermination", kind: "act", handler: compute(async (i, ctx, rt) => { need(i, "property_id", "address"); const det = await port(rt, "flood").orderDetermination(str(i, "property_id"), str(i, "address"), ctx.now);
      // The vendor's determination_result is a life-of-loan message: ops-9-6 records the order, ingests the SFHDF (`flood.determination.received`, `flood.coverage.required|not_required`) and beats the FLOOD_LOL_HEARTBEAT_35 clock.
      const r = recordDeterminationResult({ events: ctx.events, actor: ctx.actor }, { loan_id: str(i, "loan_id") || ctx.loanId, vendor_id: str(i, "vendor_id") || "flood", received_at: ctx.now, determination: det, property_id: str(i, "property_id"), ...(i.structures ? { structures: i.structures as FloodRequirementInput } : {}), ...(typeof i.participating === "boolean" ? { participating: i.participating } : {}), ...(typeof i.cbrs_opa === "boolean" ? { cbrs_opa: i.cbrs_opa } : {}) });
      return { ...det, coverage_required: r.coverage_required ?? null, private_only: r.private_only ?? null, heartbeat_due: r.heartbeat_due }; }),
    guardrails: [never("NO_NFHL_ONLY", "9.6 guardrail: no reliance on FEMA NFHL alone", (i) => str(i, "source") === "nfhl_only", "order a vendor SFHDF; NFHL alone is not a determination")] },
  { name: "evaluateStructures", kind: "read", handler: compute((i) => { const f = i.structures as FloodRequirementInput | undefined; if (!f) throw new RangeError("structures is required"); return { ...floodRequired(f), reasoning: f.principal_structure_in_sfha ? "principal structure in the SFHA" : f.detached_security_structure_in_sfha ? "detached security structure in the SFHA" : f.cbrs_opa ? "CBRS/OPA" : "no security structure in the SFHA (B7-3-06 table)" }; }) },
  { name: "computeFloodRequirement", kind: "read", handler: compute((i) => { need(i, "rcv_cents", "upb_cents"); const req = floodRequiredAmount(cents(i.rcv_cents), cents(i.upb_cents)); return { required_cents: req, ...(i.policy_amount_cents !== undefined ? floodAdequate(cents(i.policy_amount_cents), cents(i.rcv_cents), cents(i.upb_cents), cents(i.deductible_cents)) : {}) }; }),
    guardrails: [never("AMOUNT_NOT_ABOVE_MINIMUM", "9.6 guardrail: the placed amount never exceeds the rule-2 minimum unless the borrower elects", (i) => i.place_cents !== undefined && i.rcv_cents !== undefined && cents(i.place_cents) > floodRequiredAmount(cents(i.rcv_cents), cents(i.upb_cents)) && !flag(i, "borrower_elected"), "place the rule-2 minimum"),
      // A placement with no notice date at all is the case the guardrail exists for (42 U.S.C. §4012a(e)(1)–(2): notice, then 45 days): refused, not waved through.
      never("NO_PLACEMENT_BEFORE_45", "9.6 guardrail: no placement before t0 + 45", (i) => flag(i, "place") && (typeof i.notice_mailed_on !== "string" || i.notice_mailed_on === "" || !placementAllowed(floodNoticeClocks(D(str(i, "notice_mailed_on")), null), D(str(i, "today") || "2000-01-01"), flag(i, "sufficient_evidence"))), "the 45-day notice period has not run (an INS_FLOOD_FPI_NOTICE_45 mailing date and today's date must show the 45th day reached)")] },
  { name: "evaluatePrivateFloodPolicy", kind: "read", handler: compute((i) => { const p = i.policy as PrivatePolicyInput | undefined; if (!p) throw new RangeError("policy is required"); return privatePolicyAcceptable(p); }) },
]);
// ---- 9.7 -------------------------------------------------------------------------
const release = (i: ToolInput): ReleaseInput => ({ total_cents: cents(i.total_cents), upb_cents: cents(i.upb_cents), accrued_interest_cents: cents(i.accrued_interest_cents), advances_cents: cents(i.advances_cents), track: (str(i, "track") || "current_lt31") as ReleaseInput["track"] });
const SIZED: readonly string[] = ["initial", "progress", "final"];
const releaseCheck = (i: ToolInput): ReleaseCheck => ({ kind: str(i, "kind") as ReleaseKind, release: release(i), initial_cents: i.initial_cents === undefined ? null : cents(i.initial_cents), released_so_far_cents: cents(i.released_so_far_cents), inspected: flag(i, "inspected"), final_inspection: flag(i, "final_inspection"), ...(typeof i.pct_complete === "string" ? { pct_complete: i.pct_complete } : {}) });
const p97 = defineTools("9.7", A, [
  openClaim,
  { name: "computeReleaseSchedule", kind: "read", handler: compute((i) => { need(i, "total_cents"); const r = release(i); const init = initialRelease(r); return { initial: init, progress: r.track === "delinquent_31plus" ? "≤ 25% of total per inspected increment; final inspection before the last release" : "cumulative ≤ initial + pct_complete × remainder", contents_ale: "released within 2 business days", workout_evaluation_required: workoutEvaluationRequired(r.track) }; }) },
  { name: "requestEndorsement", kind: "act", handler: compute((i, ctx) => { need(i, "instrument_id"); ctx.events.append({ type: "claim.instrument.endorsement_requested", loanId: ctx.loanId, actor: ctx.actor, payload: { instrument_id: str(i, "instrument_id"), dual_control: cents(i.amount_cents) >= 5_000_000n } }); return { borrower_endorses_first: true, servicer_endorsement: "signing_officer under the LPOA", dual_control: cents(i.amount_cents) >= 5_000_000n }; }),
    guardrails: [needsRole("LPOA_SIGNING_OFFICER", "9.7 human touchpoint: the signing officer endorses physical instruments under the LPOA", (i) => flag(i, "endorse"), ["signing_officer"], "endorsement is a signing-officer act")] },
  { name: "depositInstrument", kind: "act", moneyFields: ["amount_cents"], handler: compute((i, ctx) => { need(i, "instrument_id", "amount_cents"); const r = depositProceeds({ events: ctx.events, actor: ctx.actor, loanId: str(i, "loan_id") || ctx.loanId, now: ctx.now }, { claim_id: str(i, "claim_id") || null, instrument_id: str(i, "instrument_id"), amount_cents: cents(i.amount_cents), contents_ale_cents: cents(i.contents_ale_cents), repair_intent_known: flag(i, "repair_intent_known"), reogram_confirmed: flag(i, "reogram_confirmed"), received_on: optDate(i, "received_on"), deposited_at: str(i, "deposited_at") || null }); return { deposited: true, ...r }; }) },
  { name: "releaseFunds", kind: "act", moneyFields: ["amount_cents"], handler: compute((i, ctx) => { need(i, "amount_cents", "kind"); const k = str(i, "kind") as ReleaseKind; const r = releaseProceeds({ events: ctx.events, actor: ctx.actor, loanId: str(i, "loan_id") || ctx.loanId, now: ctx.now }, { claim_id: str(i, "claim_id") || null, kind: k, amount_cents: cents(i.amount_cents), payee_kind: str(i, "payee_kind") || "borrower", basis: SIZED.includes(k) && i.total_cents !== undefined ? releaseLimit(releaseCheck(i)).basis : null, inspection_id: str(i, "inspection_id") || null }); return { released_cents: r.released_cents, kind: r.kind, released_on: r.released_on }; }),
    guardrails: [never("FORMULA_INPUTS_REQUIRED", "9.7 guardrail: releases cannot exceed formula limits — a sized release (initial/progress/final) is checked against the B-5-01 formula, so it must carry the formula inputs (total proceeds, UPB, accrued interest, advances, track)", (i) => SIZED.includes(str(i, "kind")) && (i.total_cents === undefined || i.upb_cents === undefined), "total_cents and upb_cents are required to size an initial/progress/final release"),
      never("RELEASE_WITHIN_FORMULA", "9.7 guardrail: releases cannot exceed formula limits (B-5-01 initial/progress/final by track)", (i) => { if (!SIZED.includes(str(i, "kind")) || i.total_cents === undefined) return false; const l = releaseLimit(releaseCheck(i)); return l.cents !== null && cents(i.amount_cents) > l.cents; }, "the release exceeds the formula limit"),
      guard("OFFICER_COAPPROVAL_100K", "9.7 open decision 2 (default): officer co-approval ≥ $100,000 per release (policy, not regulatory)", (i, ctx) => (cents(i.amount_cents) >= 10_000_000n && !str(i, "officer_approval_id") && !hasRole(ctx.actor, ["officer"]) ? "a release of $100,000 or more needs a recorded officer co-approval (officer_approval_id) or an officer actor" : undefined)),
      never("INSPECTION_REQUIRED", "9.7 guardrail: no release without the required inspection — delinquent track: inspection before every progress release and a final inspection before the last (B-5-01)", (i) => { const k = str(i, "kind"); if (k !== "progress" && k !== "final") return false; const l = releaseLimit(releaseCheck(i)); return l.refused === "INSPECTION_REQUIRED" || l.refused === "FINAL_INSPECTION_REQUIRED"; }, "a progress release on a delinquent loan needs an inspection; the last release needs the final inspection"),
      never("NO_NETTING", "9.7 guardrail: no netting of servicer expenses", (i) => flag(i, "net_servicer_expenses"), "servicer expenses are never netted from proceeds"),
      never("THIRD_PARTY_NEEDS_FNMA_APPROVAL", "9.7 guardrail: no third-party fee payment without a recorded Fannie Mae approval", (i) => str(i, "payee_kind") === "third_party" && !thirdPartyReleaseAllowed(flag(i, "fnma_approval_recorded")), "Form 176 approval required")] },
  { name: "orderRepairInspection", kind: "act", handler: compute((i, ctx) => { need(i, "loan_id"); ctx.events.append({ type: "property.inspection.ordered", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { kind: "repair", cap_cents: INSURED_LOSS_REPAIR_INSPECTION_CAP } }); return { ordered: true, cap_cents: INSURED_LOSS_REPAIR_INSPECTION_CAP }; }) },
  { name: "verifyRemoteInspection", kind: "read", handler: compute((i) => { const m = i.media as { app_captured: boolean; gps: boolean; timestamp: boolean; hash: boolean } | undefined; if (!m) throw new RangeError("media is required"); const ok = remoteInspectionAcceptable(m); return { acceptable: ok, fallback: ok ? null : "order a vendor inspection ($60 cap)" }; }) },
  { name: "prepareForm176", kind: "write", handler: compute((i, ctx, rt) => { need(i, "loan_id", "learned_on"); const loanId = str(i, "loan_id"); const id = str(i, "package_id") || `f176-${loanId}-${ctx.now}`; const due = form176Due(date(i, "learned_on")); const reason = str(i, "reason") || "abandoned_intends_to_repair"; const claimId = str(i, "claim_id") || null;
      if (flag(i, "submit")) { const s = sendForm176({ events: ctx.events, actor: ctx.actor, loanId, now: ctx.now }, { claim_id: claimId, package_id: id, reason, sent_on: optDate(i, "sent_on") }); const rec = rt.store.put("form_176_packages", id, { loan_id: loanId, claim_id: claimId, due, status: "sent", reason: s.reason, sent_on: s.sent_on, sent_by: `${ctx.actor.kind}:${ctx.actor.id}`, send_by: "fnma_portal_operator" }, ctx.actor, ctx.now); return { id: rec.id, ...rec.data }; }
      const rec = rt.store.put("form_176_packages", id, { loan_id: loanId, claim_id: claimId, due, status: "draft", reason, send_by: "fnma_portal_operator", contents: ["loan, property, damage and claim data", "photos", "adjuster estimate", "business justification"] }, ctx.actor, ctx.now); return { id: rec.id, ...rec.data }; }),
    guardrails: [needsRole("PORTAL_OPERATOR_SENDS", "9.7 human touchpoint: fnma_portal_operator sends Form 176/uploads", (i) => flag(i, "submit"), ["fnma_portal_operator"], "the agent prepares; the portal operator submits")] },
  { name: "remitProceeds332", kind: "act", moneyFields: ["amount_cents"], handler: compute((i, ctx) => { need(i, "amount_cents"); if (!str(i, "reogram_confirmed_on") && !str(i, "shortsale_closed_on")) throw new RangeError("reogram_confirmed_on or shortsale_closed_on is required"); return remit332({ events: ctx.events, actor: ctx.actor, loanId: str(i, "loan_id") || ctx.loanId, now: ctx.now }, { claim_id: str(i, "claim_id") || null, amount_cents: cents(i.amount_cents), reogram_confirmed_on: optDate(i, "reogram_confirmed_on"), shortsale_closed_on: optDate(i, "shortsale_closed_on"), received_on: optDate(i, "received_on"), net_servicer_fees: flag(i, "net_servicer_fees") }); }),
    guardrails: [never("NO_NETTING_332", "9.7 rule 9: never net servicer fees from remitted proceeds", (i) => flag(i, "net_servicer_fees"), "remit gross proceeds")] },
  { name: "applyToUpb", kind: "act", moneyFields: ["proceeds_cents"], handler: compute((i, ctx) => { need(i, "proceeds_cents", "payoff_cents"); const d = notRebuildableDisposition(cents(i.proceeds_cents), cents(i.payoff_cents)); ctx.events.append({ type: "payment.curtailment", loanId: ctx.loanId, actor: ctx.actor, payload: { amount_cents: d.curtailment_cents, source: "loss_draft_not_rebuildable" } }); return d; }) },
  { name: "openWorkoutEvaluation", kind: "write", handler: compute((i, ctx, rt) => { need(i, "loan_id"); const loanId = str(i, "loan_id"); const track = str(i, "track") || "delinquent_31plus"; const rec = rt.store.put("cases", str(i, "case_id") || `wo-${loanId}-${ctx.now}`, { loan_id: loanId, claim_id: str(i, "claim_id") || null, case_type: "lossmit_evaluation", trigger: "loss_draft_delinquent_track", track, status: "open", reviewer_on_denial: "lossmit_reviewer" }, ctx.actor, ctx.now); ctx.events.append({ type: "claim.workout_evaluation.opened", loanId, actor: ctx.actor, payload: { case_id: rec.id, claim_id: str(i, "claim_id") || null, track, basis: "D2-3.1-01 via B-5-01 (≥ 31 days delinquent, abandoned or FC-scheduled)" } }); return { id: rec.id, case_type: "lossmit_evaluation", track }; }) },
  { name: "escalate", kind: "act", handler: escalate("officer"), decision: (i) => ({ action: "escalate", rationale: str(i, "reason") || "claim escalation" }) },
]);
// ---- 9.8 -------------------------------------------------------------------------
/** Delinquency day for the order gate: an explicit `day`, else computed from `earliest_unpaid_due` and `today`. */
const dayOf = (i: ToolInput): number => (i.day !== undefined ? num(i, "day") : typeof i.earliest_unpaid_due === "string" && typeof i.today === "string" ? fnmaDaysDelinquent(D(str(i, "earliest_unpaid_due")), D(str(i, "today"))) : NaN);
const p98 = defineTools("9.8", A, [
  { name: "computeInspectionSchedule", kind: "write", handler: compute((i, ctx) => { const w = inspectionWindow(date(i, "earliest_unpaid_due")); const e = i.exception as ExceptionInput | undefined; const mode = inspectionMode({ conventional_first_lien: i.conventional_first_lien !== false, recourse: flag(i, "recourse"), enrolled: flag(i, "enrolled"), fnma_rejected: flag(i, "fnma_rejected") });
      // the daily inspection_sweep (build spec inputs): advances the schedule and announces day 90 once per episode (`delinquency.day90.reached` arms FNMA_D2210_INSPECT_ORDER_DAY90 / _COMPLETE_DAY120 / FNMA_P360_PFPIP_SUBMIT_DAY90) — ops-9-8.ts
      const s = i.today !== undefined ? inspectionSweep({ events: ctx.events, actor: ctx.actor, loanId: str(i, "loan_id") || ctx.loanId, now: ctx.now }, { earliest_unpaid_due: date(i, "earliest_unpaid_due"), today: date(i, "today"), mode, exception: e ?? null, fnma_inspection_seen: flag(i, "fnma_inspection_seen"), closed: flag(i, "closed") }) : null;
      return { ...w, mode, suspended: s ? s.suspended : e ? inspectionSuspended(e, date(i, "today")) : false, next: s ? s.next : i.last_completed ? nextInspectionWindow(D(str(i, "last_completed"))) : null, ...(s ? { day: s.day, state: s.state, last_completed: s.last_completed, backstop_order: s.backstop_order, day90_reached: s.day90_event !== null } : {}) }; }) },
  { name: "orderInspection", kind: "act", handler: compute((i, ctx) => { need(i, "loan_id", "type"); ctx.events.append({ type: "property.inspection.ordered", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { type: str(i, "type"), purpose: str(i, "purpose") || "delinquency", day: Number.isFinite(dayOf(i)) ? dayOf(i) : null } }); return { ordered: true, type: str(i, "type"), day: Number.isFinite(dayOf(i)) ? dayOf(i) : null, instruction: "inspectors never discuss the debt" }; }),
    guardrails: [never("NO_ORDER_BEFORE_DAY90", "9.8 guardrail: no order before day 90 except vacancy checks (D2-2-10; FNMA_D2210_INSPECT_ORDER_DAY90)", (i) => !inspectionOrderAllowed(str(i, "purpose") || "delinquency", dayOf(i)).allowed, "the first inspection is ordered on or after the 90th day of delinquency counted from the earliest unpaid due date; vacancy checks have no day-90 floor"),
      never("INTERIOR_NEEDS_VACANCY_AND_ENTRY", "9.8 guardrail: no interior inspection without confirmed vacancy and a permitted-entry jurisdiction rule", (i) => str(i, "type") === "interior" && !(flag(i, "vacancy_confirmed") && flag(i, "interior_entry_allowed")), "interior inspections need confirmed vacancy and permitted entry"),
      never("CURBSIDE_NEEDS_REASON", "9.8 guardrail: curbside only with a recorded reason", (i) => str(i, "type") === "curbside" && !i.legal_constraint_reason, "record the legal-constraint/danger reason")] },
  { name: "evaluateInspectionResult", kind: "write", handler: compute((i, ctx) => { need(i, "result"); const r = i.result as { indicators: string[]; certification_signed: boolean; photos: number }; const vacant = r.indicators.filter((x) => /utilities_off|mail_piling|no_furnishings|neighbor_vacant|posting_unanswered/.test(x)).length >= 2;
      // a completed vendor result (Form 30 data + photos) is recorded as `property.inspection.completed` (ops-9-8 recordInspectionResult: closes the day-120 / 20–35-day / interior-monthly / vacancy-ASAP / pre-sale clocks); classification alone leaves the store untouched
      const recorded = i.completed_on !== undefined ? recordInspectionResult({ events: ctx.events, actor: ctx.actor, loanId: str(i, "loan_id") || ctx.loanId, now: ctx.now }, { inspection_id: i.inspection_id, type: i.type, purpose: str(i, "purpose") || "delinquency", completed_on: i.completed_on, occupancy_result: i.occupancy_result ?? (vacant ? "vacant" : "occupied_unknown"), certification_signed: r.certification_signed, report_document_id: i.report_document_id, photos: i.photos ?? Array.from({ length: r.photos || 0 }, (_, n) => `photo-${n + 1}`), cost_cents: i.cost_cents, ordered_by: i.ordered_by, legal_constraint_reason: i.legal_constraint_reason, condition: i.condition }) : null;
      return { occupancy: vacant ? (r.certification_signed ? "vacant" : "vacancy_suspected") : "occupied", confidence: vacant ? 0.9 : 0.8, type_next: inspectionType({ vacant, interior_entry_allowed: flag(i, "interior_entry_allowed"), legal_constraint_reason: (i.legal_constraint_reason as string | undefined) ?? null }), ...(recorded ? { recorded: true, initial: recorded.initial, next_window: recorded.next_window, vacancy: recorded.vacancy, reimbursable: recorded.reimbursable, cap_cents: recorded.cap_cents } : {}) }; }) },
  { name: "updateOccupancy", kind: "write", handler: compute((i, ctx, rt) => { need(i, "loan_id", "occupancy"); if (str(i, "occupancy") === "vacant") { const v = vacancyConfirmed({ inspected_on: date(i, "inspected_on"), certification_signed: flag(i, "certification_signed"), pfpip: flag(i, "pfpip"), earliest_unpaid_due: optDate(i, "earliest_unpaid_due") }); rt.store.put("properties", str(i, "loan_id"), { occupancy_status: "vacant" }, ctx.actor, ctx.now);
      ctx.events.append({ type: "property.vacancy_confirmed", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { inspected_on: str(i, "inspected_on"), certification_signed: true, pfpip: flag(i, "pfpip"), earliest_unpaid_due: optDate(i, "earliest_unpaid_due"), pfpip_exception_submit_on: v.pfpip_exception_submit_on, ftv_date: str(i, "ftv_date") || str(i, "inspected_on") } });
      // T3: "PFPIP occupancy updated within 2 business days" — the occupancy change is a status change the program record must follow (ops-9-8 pfpipChangeReported arms FNMA_P360_PFPIP_STATUS_SYNC_2BD; updatePfpip closes it)
      if (flag(i, "pfpip")) pfpipChangeReported({ events: ctx.events, actor: ctx.actor, loanId: str(i, "loan_id"), now: ctx.now }, { change: "occupancy", changed_on: date(i, "inspected_on"), pfpip_enrolled: true, detail: "occupancy → vacant (signed inspection report)" }); return v; }
      const u = occupancyUpdated({ events: ctx.events, actor: ctx.actor, loanId: str(i, "loan_id"), now: ctx.now }, { occupancy: str(i, "occupancy"), on: optDate(i, "inspected_on") ?? optDate(i, "on") ?? D(ctx.now.slice(0, 10)), source: str(i, "source") || null });   // vacancy_suspected → `property.vacancy_suspected` (FNMA_D2210_VACANCY_INSPECT_ASAP_3BD)
      rt.store.put("properties", str(i, "loan_id"), { occupancy_status: str(i, "occupancy") }, ctx.actor, ctx.now); return { occupancy: str(i, "occupancy"), confirm_by: u.confirm_by }; }),
    guardrails: [never("VACANT_NEEDS_CERTIFICATION", "9.8 guardrail: the agent cannot mark occupancy `vacant` without a signed certification", (i) => str(i, "occupancy") === "vacant" && !flag(i, "certification_signed"), "a signed inspector certification is required")] },
  notifyCarrierVacancy,
  { name: "submitPfpip", kind: "act", handler: compute((i, ctx) => { const r = pfpipSubmission({ earliest_unpaid_due: date(i, "earliest_unpaid_due"), package: data(i) }); if (!r.complete) throw new RangeError(`PFPIP package missing: ${r.missing_fields.join(", ")}`); ctx.events.append({ type: "p360.pfpip.submitted", loanId: str(i, "loan_id") || ctx.loanId, actor: ctx.actor, payload: { task_due: r.task_due, day90_on: r.day90_on, method: str(i, "method") || "human_portal_task", exception: str(i, "exception") || null } }); return r; }) },
  { name: "updatePfpip", kind: "act", handler: compute((i, ctx) => { need(i, "loan_id", "change"); ctx.events.append({ type: "p360.pfpip.updated", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { change: str(i, "change"), due: pfpipTaskDue(date(i, "changed_on")) } }); return { updated: true, due: pfpipTaskDue(date(i, "changed_on")), permission: pfpipPermission({ bankruptcy_active: flag(i, "bankruptcy_active"), preserve_allowed: i.preserve_allowed !== false }) }; }) },
  { name: "reconcilePfpip", kind: "write", handler: compute((i, ctx) => { const ours = rows<{ loan_id: string; status: string }>(i, "platform"); const theirs = rows<{ loan_id: string; status: string }>(i, "fnma_report"); const deltas = ours.filter((o) => theirs.find((t) => t.loan_id === o.loan_id)?.status !== o.status).map((o) => ({ loan_id: o.loan_id, platform: o.status, fnma: theirs.find((t) => t.loan_id === o.loan_id)?.status ?? null, action: "update" }));
      for (const o of ours) ctx.events.append({ type: "p360.pfpip.reconciled", loanId: o.loan_id, actor: ctx.actor, payload: { platform: o.status, fnma: theirs.find((t) => t.loan_id === o.loan_id)?.status ?? null, in_sync: !deltas.some((d) => d.loan_id === o.loan_id) } });
      // rule 8: "deltas become updates" — each delta is a change the program record must follow within 2 BD (ops-9-8 pfpipChangeReported → FNMA_P360_PFPIP_STATUS_SYNC_2BD; updatePfpip closes it)
      for (const d of deltas) pfpipChangeReported({ events: ctx.events, actor: ctx.actor, loanId: d.loan_id, now: ctx.now }, { change: "reconciliation_delta", changed_on: optDate(i, "reconciled_on") ?? D(ctx.now.slice(0, 10)), pfpip_enrolled: true, detail: `platform ${d.platform} vs Fannie Mae ${d.fnma ?? "none"}` });
      return { deltas, in_sync: deltas.length === 0, reconciled: ours.length }; }) },
  { name: "openPreservation", kind: "write", handler: compute((i, ctx, rt) => { need(i, "loan_id"); const rec = rt.store.put("preservation_cases", `pp-${str(i, "loan_id")}`, { loan_id: str(i, "loan_id"), mode: preservationMode({ pfpip: flag(i, "pfpip"), permission: str(i, "permission"), chapter13_active: flag(i, "chapter13_active") }), status: "open" }, ctx.actor, ctx.now); return { id: rec.id, ...rec.data }; }) },
  openClaim,
  { name: "sendNotice", kind: "act", handler: noticeOps("render_send") },
]);
// ---- 9.9 -------------------------------------------------------------------------
const HAZMAT = /paint|chemical|tire|medicine|pharmaceutical|propane|asbestos|biohazard/i;
const photoDates = (i: ToolInput): PlainDate[] => (Array.isArray(i.photos) ? (i.photos as { taken_on?: unknown }[]).filter((p) => typeof p?.taken_on === "string").map((p) => D(String(p.taken_on))) : []);
const p99 = defineTools("9.9", A, [
  { name: "buildInitialScope", kind: "read", handler: compute((i) => { const flags = rows<string>(i, "condition_flags"); const items: WorkItem[] = []; const add = (kind: WorkItem["kind"], qty: number, cost: bigint, measure?: number) => items.push({ kind, qty, unit_cost_cents: cost, ...(measure !== undefined ? { measure } : {}) });
      if (flags.includes("lock_change")) add("lock_change", 1, 6000n); const w = flags.filter((f) => f === "broken_window").length; if (w) add("boarding", w, 18500n); if (flags.includes("lawn")) add("yard_initial", 1, 15000n); const cy = num(i, "debris_cy"); if (cy > 0) add("debris", cy, 5000n, cy); if (flags.includes("winterization")) add("winterization", 1, 22000n); add("posting", 1, 5000n);
      return { work_items: items, ...evaluateScope(items) }; }),
    guardrails: [never("NO_ENTRY_WITHOUT_VACANCY", "9.9 guardrail: no entry unless vacancy is confirmed (signed certification) and entry is permitted for the jurisdiction", (i) => !(flag(i, "vacancy_confirmed") && flag(i, "entry_permitted")), "confirmed vacancy and permitted entry are prerequisites")] },
  { name: "checkAllowables", kind: "read", handler: compute((i) => evaluateScope(rows<WorkItem>(i, "items"))) },
  { name: "orderWork", kind: "act", moneyFields: ["cost_cents"], handler: compute((i, ctx) => { need(i, "loan_id"); const s = evaluateScope(rows<WorkItem>(i, "items")); const pctx = { events: ctx.events, actor: ctx.actor, loanId: str(i, "loan_id"), now: ctx.now };
      // the conditions this order answers (inspection flags, vendor field report) are recorded first — ops-9-9 conditionDiscovered arms FNMA_PPM_WINDOW_DOOR_REPAIR_3 / FNMA_PPM_YARD_REBID_15 / FNMA_PPM_OVER_ALLOWABLE_BID_15 on `discovered_on`
      const conditions = Array.isArray(i.conditions) ? (i.conditions as Record<string, unknown>[]).map((c) => conditionDiscovered(pctx, { item: c.item, discovered_on: c.discovered_on, after_initial_securing: c.after_initial_securing, measure: c.measure, estimate_cents: c.estimate_cents, source: c.source })) : [];
      ctx.events.append({ type: "preservation.work.ordered", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { kind: str(i, "kind") || "initial_services", total_cents: s.total_cents, items: s.items, conditions: conditions.map((c) => c.item) } }); return { ordered: true, total_cents: s.total_cents, prior_approval_required: s.prior_approval_required, conditions: conditions.map(({ event: _e, ...c }) => c) }; }),
    guardrails: [never("NO_OVER_ALLOWABLE_WITHOUT_APPROVAL", "9.9 guardrail: no over-allowable work without a Fannie Mae approval record except Matrix-permitted BATF", (i) => { try { return evaluateScope(rows<WorkItem>(i, "items")).items.some((x) => x.disposition === "stop_and_bid") && !i.fnma_approval_id; } catch { return false; } }, "stop and bid; order only with the approval record"),
      never("NO_BORROWER_CHARGE_PFPIP", "9.9 guardrail: costs never charged to the borrower on PFPIP loans or where the contract/state law prohibits", (i) => flag(i, "charge_borrower") && (flag(i, "pfpip") || flag(i, "charge_prohibited")), "preservation costs are not borrower charges here"),
      never("NEUTRAL_POSTING", "9.9 guardrail: neutral postings", (i) => /debt|delinquen|foreclos|owe/i.test(str(i, "posting_text")), "postings carry contact information only"),
      // the order dispatches the vendor to enter: the same entry guardrail as buildInitialScope (confirmed vacancy = signed certification; entry permitted by jurisdiction_rules.prefc_entry_rules)
      never("NO_ENTRY_WITHOUT_VACANCY", "9.9 guardrail: no entry unless vacancy is confirmed (signed certification) and entry is permitted for the jurisdiction", (i) => !(flag(i, "vacancy_confirmed") && flag(i, "entry_permitted")), "confirmed vacancy and permitted entry are prerequisites to ordering entry/securing work"),
      // Matrix debris rule: "hazardous items excluded (paint, chemicals, tires, medicine, propane)" — specialty bids by licensed contractors, never a debris line
      never("NO_HAZARDOUS_MATERIALS", "9.9 guardrail: no hazardous-material handling outside the allowable list", (i) => { try { return rows<WorkItem & { hazardous?: unknown; materials?: unknown }>(i, "items").some((it) => it.hazardous === true || (Array.isArray(it.materials) && it.materials.some((m) => HAZMAT.test(String(m))))); } catch { return false; } }, "paint, chemicals, tires, medicine and propane are excluded from debris removal — specialty bid by a licensed contractor")] },
  // the vendor's reports through the `preservation` adapter, QC'd and recorded by ops-9-9: op=posting → `preservation.posting.placed` (arms FNMA_PPM_POST_NOTICE_SECURE_7); op=condition → `preservation.condition.discovered`;
  // default with `kind` → `preservation.work.completed` (+ `preservation.initial.completed` for kind=initial_services: closes FNMA_PPM_INITIAL_SECURE_14 / POST_NOTICE_SECURE_7; item=roof_tarp arms FNMA_PPM_ROOF_TARP_60); default without `kind` → photo QC only
  { name: "reviewCompletion", kind: "write", handler: compute((i, ctx) => { const pctx = { events: ctx.events, actor: ctx.actor, loanId: str(i, "loan_id") || ctx.loanId, now: ctx.now }; const op = String(i.op ?? "review");
      if (op === "posting") { const { event: _e, ...p } = postingPlaced(pctx, { posted_on: i.posted_on, expires_on: i.expires_on, ftv_date: i.ftv_date, projected_securing_date: i.projected_securing_date, servicer_contact: i.servicer_contact, vendor_contact: i.vendor_contact, text: i.text, photo_document_id: i.photo_document_id }); return { op, posted: true, ...p }; }
      if (op === "condition") { const { event: _e, ...c } = conditionDiscovered(pctx, { item: i.item, discovered_on: i.discovered_on, after_initial_securing: i.after_initial_securing, measure: i.measure, estimate_cents: i.estimate_cents, source: i.source, photo_document_ids: i.photo_document_ids }); return { op, recorded: true, ...c }; }
      if (i.kind !== undefined && i.kind !== null && i.kind !== "") { const { events: _ev, ...w } = workCompleted(pctx, { kind: i.kind, item: i.item, completed_on: i.completed_on, photos: i.photos, haul_away_evidence: i.haul_away_evidence, cost_cents: i.cost_cents, batf: i.batf, invoice_document_id: i.invoice_document_id, work_order_id: i.work_order_id, ftv_date: i.ftv_date, reason: i.reason, submitted_on: i.submitted_on }); return { recorded: true, ...w }; }
      return reviewPhotos(parsePhotos(rows(i, "photos")), flag(i, "haul_away_evidence"), date(i, "submitted_on")); }) },
  { name: "prepareBid", kind: "write", handler: compute((i, ctx, rt) => { need(i, "loan_id", "discovered_on"); const submittedOn = optDate(i, "submitted_on") ?? D(ctx.now.slice(0, 10)); const pkg = bidPackage(date(i, "discovered_on"), photoDates(i), submittedOn);
      // the over-allowable condition the bid answers is recorded on discovery (ops-9-9 conditionDiscovered → `preservation.condition.discovered{over_allowable=true, discovered_on}` arms FNMA_PPM_OVER_ALLOWABLE_BID_15: HomeTracker bid within 15 days; 15.2's HomeTracker ingestion closes it)
      const CONDITION_OF: Partial<Record<WorkItem["kind"], ConditionItem>> = { debris: "debris", grass_cut: "grass_over_12in", roof_patch: "roof_damage" };
      const pctx = { events: ctx.events, actor: ctx.actor, loanId: str(i, "loan_id"), now: ctx.now };
      const discovered = (Array.isArray(i.items) ? (i.items as WorkItem[]) : []).filter((it) => evaluateScope([it]).prior_approval_required).map((it) => { const { event: _e, ...c } = conditionDiscovered(pctx, { item: CONDITION_OF[it.kind] ?? "other", discovered_on: i.discovered_on, after_initial_securing: i.after_initial_securing, measure: it.measure, estimate_cents: CONDITION_OF[it.kind] === "debris" ? undefined : BigInt(it.qty) * it.unit_cost_cents, over_allowable: true, source: "prepareBid" }); return c; });
      const rec = rt.store.put("preservation_bids", `bid-${str(i, "loan_id")}-${ctx.now}`, { loan_id: str(i, "loan_id"), form: "1095", items: i.items ?? [], conditions: discovered.map((c) => c.item), discovery_date: str(i, "discovered_on"), due: pkg.due, channel: pkg.channel, photos_fresh: pkg.photos_fresh, submit_via: "HomeTracker (fnma_portal_operator)", status: "pending" }, ctx.actor, ctx.now);
      // HomeTracker is portal-only (Consolidated Technology Guide): the agent prepares the package; `fnma_portal_operator` submits it.
      const task = rt.escalations.open({ kind: pkg.human_task, loanId: str(i, "loan_id"), payload: { portal: "HomeTracker", form_1095: true, bid_id: rec.id, due: pkg.due, items: i.items ?? [], photos_taken_on: photoDates(i), photos_fresh: pkg.photos_fresh, fallback: "Form 1095 by e-mail to property_preservation@fanniemae.com if the loan is not in HomeTracker" } }, ctx.actor);
      return { id: rec.id, ...rec.data, human_task_id: task.id, human_task_kind: task.kind, owner_role: task.ownerRole }; }),
    // freshness is judged at the submission date the package names, else today — a bid prepared on stale photos is refused rather than sent to the portal operator with photos_fresh=false
    guardrails: [guard("BID_PHOTOS_FRESH", "9.9 rule 3 (PPM): bids carry date-stamped photos ≤ 30 days old", (i, ctx) => { const on = optDate(i, "submitted_on") ?? D(ctx.now.slice(0, 10)); return photoDates(i).some((p) => !photosFresh(p, on)) ? "retake the dated photos before submitting the bid" : undefined; })] },
  { name: "fileRegistration", kind: "act", moneyFields: ["fee_cents"], handler: compute((i, ctx) => { const r = i.rule as { within_days: number; renewal_months: number | null } | undefined; if (!r) throw new RangeError("rule is required"); const reg = vacantRegistration({ trigger_on: date(i, "trigger_on"), rule: r, fee_cents: cents(i.fee_cents), filed_on: optDate(i, "filed_on") }); ctx.events.append({ type: "preservation.registration.filed", loanId: ctx.loanId, actor: ctx.actor, payload: { file_by: reg.file_by, filed_at: reg.filed_on, renew_on: reg.renew_on, fee_cents: reg.fee_claim_cents } }); return reg; }) },
  notifyCarrierVacancy,
  openClaim,
]);

export const SECTION_09_TOOLS: readonly ToolDef[] = [...p91, ...p93, ...p94, ...p95, ...p96, ...p97, ...p98, ...p99];
export const placementScreen = placementConfig;
export const fpiClockCheck = fpiClocks;
export const chargeGate = chargeDecision;
export const refundClock = refundTimeline;
