/**
 * §26.2 process-owned tools — bus tools for 26.2 defined with `defineTools("26.2", <agent>, defs)` from
 * ../tools.ts. Every tool string must be one spec/registry/agents.json names for 26.2; src/app/tools.test.ts refuses
 * the rest. Spread by ./index.ts.
 *
 * The `closer` (title-closing agent) runs in application scope. Every act goes through the pure rules in
 * src/domain/closing/ops-26-2.ts, which append the events the timers and 26.3 / 26.4 / 27.1 / 29.x / 30.2 consume.
 * Entity-store kinds mirror migration 0094: closings, signing_sessions, enotes, mers_transactions, recordings,
 * custody_records, eclosing_eligibility, consents, documents. Ports: the eClosing/RON platform and the MERS eRegistry
 * (ops-26-2.ts ports with fakes, under rt.services "26.2.ron" / "26.2.eregistry"), the eVault (rt.ports.evault — the
 * Location's Authoritative Copy), the eRecording vendor (rt.ports.erecording — county coverage). Guardrails encode the
 * spec's sentences: never open a session with a closed gate; never require electronic records or RON of any borrower;
 * never apply, complete or "assist" a signature or notarial act; never accept a KBA/credential override; never register
 * an eNote whose hash does not match the eVault copy; never fund-related actions before the audit trail is on file;
 * never convert a paper note to an eNote; never submit a recording with a handwritten instrument change; never disable
 * the paper fallback; never a notary outside the state of the act; never treat GA/MS (or any unlisted state) as
 * RON-eligible without counsel confirmation.
 */
import { defineTools, compute, decision, never, needsRole, str, flag, cents, service, type ToolDef, type ToolInput, type ToolRuntime } from "../tools.ts";
import type { CommandContext } from "../commands.ts";
import { plainDate as D, type PlainDate } from "../../kernel/calendar/date.ts";
import { FakeEvault } from "../../infra/integrations/custody.ts";
import { type Closing, type SigningSession, type ENote, type Recording, type CustodyRecord, type EclosingEligibility, type ClosingEsignConsent, type ClosingTypeInput, type PreSessionFacts, type ExecutedDocument, type KbaAttempt, type IdentityMethod, type ERegistryPort26, type RonPlatformPort, type SessionFailure, FakeERegistry26, FakeRonPlatform, RULE_SET_VERSION_26_2, NOTICE_CLOSING_APPOINTMENT, SM_ORG_ID, FNMA_RON_STATES, RETENTION_ENOTE_SIGNING, decideClosingType, ronStateAuthCheck, agentEclosingEligible, runPreSessionChecks, esignConsentCheck, scheduleClosing, applyReleaseEvent, recordEligibilityCheck, verifyConsent, passPreSessionChecks, openSigningSession, proofIdentity, startSession, signDocument, completeNotarialAct, createENote, tamperSeal, validateAuthoritativeCopy, registerENote, setSecuredParty, reverseRegistration, ingestAuditTrail, reviewExecution, recordExecutionReview, openRecording, submitERecording, handleRecordingReject, dispatchPaperRecording, confirmCountyReceipt, confirmRecording, seedCustodyRecord, trackPaperNote, failSession, rescheduleClosing, closingGateFacts, assertSecuredPartyBeforeAdvance, assertAuditTrailOnFile, deliveryIndicators, electronicLoanFile, sha256 } from "../../domain/closing/ops-26-2.ts";
import type { ClosingType } from "../../domain/closing/ops-26-1.ts";
import type { HpmlRow } from "../../domain/underwriting/ops-23-4.ts";

/** Missing-input guard: a tool executed without its subject refuses with a RangeError (never a TypeError). */
const need = (i: ToolInput, ...keys: string[]): void => { const gaps = keys.filter((k) => i[k] === undefined || i[k] === null || i[k] === ""); if (gaps.length) throw new RangeError(`26.2 tool needs ${gaps.join(", ")}`); };
const at = (i: ToolInput, ctx: CommandContext, key = "at"): string => str(i, key) || ctx.now;
const obj = (i: ToolInput, k: string): Record<string, unknown> => { const v = i[k]; if (!v || typeof v !== "object") throw new RangeError(`26.2 tool needs ${k} (object)`); return v as Record<string, unknown>; };
const arr = <T>(i: ToolInput, k: string): T[] => (Array.isArray(i[k]) ? (i[k] as T[]) : []);
const put = <T>(rt: ToolRuntime, ctx: CommandContext, kind: string, id: string, v: T): T => rt.store.put(kind, id, v as unknown as Record<string, unknown>, ctx.actor, ctx.now).data as unknown as T;
const loadClosing = (i: ToolInput, rt: ToolRuntime): Closing => { need(i, "closing_id"); const r = rt.store.get("closings", str(i, "closing_id")); if (!r) throw new RangeError(`no closing ${str(i, "closing_id")} (runPreSessionChecks op=schedule opens it)`); return r.data as unknown as Closing; };
const loadSession = (i: ToolInput, rt: ToolRuntime, c: Closing): SigningSession => { const id = str(i, "session_id") || c.session_ids.at(-1) || ""; const r = rt.store.get("signing_sessions", id); if (!r) throw new RangeError(`no signing_session ${id || "(none)"} (openSigningSession first)`); return r.data as unknown as SigningSession; };
const loadENote = (rt: ToolRuntime, c: Closing): ENote => { const r = rt.store.list("enotes", (d) => d.closing_id === c.closing_id).at(-1); if (!r) throw new RangeError(`no eNote for closing ${c.closing_id} (monitorSession op=enote_created seeds it)`); return r.data as unknown as ENote; };
const loadRecording = (i: ToolInput, rt: ToolRuntime): Recording => { need(i, "recording_id"); const r = rt.store.get("recordings", str(i, "recording_id")); if (!r) throw new RangeError(`no recording ${str(i, "recording_id")} (submitERecording op=open first)`); return r.data as unknown as Recording; };
const eligibilityRows = (i: ToolInput, rt: ToolRuntime): EclosingEligibility[] => (Array.isArray(i.eligibility) ? (i.eligibility as EclosingEligibility[]) : rt.store.list("eclosing_eligibility").map((r) => r.data as unknown as EclosingEligibility));
const consentOf = (i: ToolInput, rt: ToolRuntime, c: Closing): ClosingEsignConsent | null => (i.consent && typeof i.consent === "object" ? (i.consent as ClosingEsignConsent) : (rt.store.list("consents", (d) => d.application_id === c.application_id && d.kind === "esign").at(-1)?.data as unknown as ClosingEsignConsent | undefined) ?? null);
const eregistry = (rt: ToolRuntime): ERegistryPort26 => { try { return service<ERegistryPort26>(rt, "26.2.eregistry"); } catch { const f = new FakeERegistry26(); (rt.services as Record<string, unknown>)["26.2.eregistry"] = f; return f; } };
const ronPlatform = (rt: ToolRuntime): RonPlatformPort => { try { return service<RonPlatformPort>(rt, "26.2.ron"); } catch { const f = new FakeRonPlatform(); (rt.services as Record<string, unknown>)["26.2.ron"] = f; return f; } };
const evault = (rt: ToolRuntime) => rt.ports.evault ?? (() => { const f = new FakeEvault(); (rt.ports as Record<string, unknown>).evault = f; return f; })();
const ronInput = (i: ToolInput, c: Pick<Closing, "state" | "county_fips" | "tx_50a6">, rows: readonly EclosingEligibility[], agentId: string): ClosingTypeInput => ({
  state: c.state, county_fips: c.county_fips, tx_50a6: c.tx_50a6, enote_eligible: i.enote_eligible !== false, proposed_closing_type: (str(i, "proposed_closing_type") as ClosingType) || "ron", borrower_election: (i.borrower_election as ClosingType | undefined) ?? null,
  signers: arr(i, "signers"), county_accepts_ron_instruments: i.county_accepts_ron_instruments !== false, title_no_ron_exception: i.title_no_ron_exception !== false, agent: (i.agent as EclosingEligibility | undefined) ?? rows.find((r) => r.settlement_agent_party_id === agentId) ?? null,
  ron_provider_available: i.ron_provider_available !== false, notary: (i.notary as ClosingTypeInput["notary"] | undefined) ?? null, counsel_confirmation: (i.counsel_confirmation as ClosingTypeInput["counsel_confirmation"] | undefined) ?? null, in_person_enotarization_valid: i.in_person_enotarization_valid !== false,
  ...(i.consent_withdrawn !== undefined ? { consent_withdrawn: flag(i, "consent_withdrawn") } : {}), ...(i.session_failure !== undefined ? { session_failure: flag(i, "session_failure") } : {}) });
const unlistedWithoutCounsel = (i: ToolInput): boolean => { const st = str(i, "state") || (typeof i.closing === "object" && i.closing ? String((i.closing as Record<string, unknown>).state ?? "") : ""); return !!st && !FNMA_RON_STATES.includes(st) && str(i, "proposed_closing_type") === "ron" && flag(i, "treat_as_ron_eligible") && !i.counsel_confirmation; };

export const TOOLS_26_2: readonly ToolDef[] = defineTools("26.2", "title-closing", [
  // Pre-appointment: `op=schedule` decides the closing type (26.1 profile + borrower election), stamps 23.4's HPML fields and emits `closing.scheduled` (the trigger every §22–§26 / 30.3 gate keys on); `op=upstream` folds 26.1's release/acknowledgment in; default `op=check` runs every gate (23.3 CTC, 21.2 LE 7-SBD, 25.2 CD 3-SBD, 25.3 package, 22.6 fraud hold, 25.1, 25.4, 24.2, VVOE, MI, lock, E-SIGN consent) → `closing.pre_session_checks.passed`.
  { name: "runPreSessionChecks", kind: "act", handler: compute((i, ctx, rt) => {
      if (i.op === "schedule") { need(i, "closing_id", "application_id", "scheduled_at", "state", "settlement_agent_party_id", "transaction_type"); const rows = eligibilityRows(i, rt);
        const d = decideClosingType(ronInput(i, { state: str(i, "state"), county_fips: (i.county_fips as string | undefined) ?? null, tx_50a6: flag(i, "tx_50a6") }, rows, str(i, "settlement_agent_party_id")));
        const r = scheduleClosing(ctx.events, { closing_id: str(i, "closing_id"), application_id: str(i, "application_id"), scheduled_at: str(i, "scheduled_at"), time_zone: str(i, "time_zone") || "America/New_York", decision: d, state: str(i, "state"), county_fips: (i.county_fips as string | undefined) ?? null, transaction_type: str(i, "transaction_type") as Closing["transaction_type"], tx_50a6: flag(i, "tx_50a6"), rescindable: i.rescindable !== false, dry_state: flag(i, "dry_state"), settlement_agent_party_id: str(i, "settlement_agent_party_id"), notary_party_id: (i.notary_party_id as string | undefined) ?? null, ron_provider_party_id: (i.ron_provider_party_id as string | undefined) ?? null, location_type: (i.location_type as Closing["location_type"] | undefined) ?? null, hpml: (i.hpml as HpmlRow | undefined) ?? null, document_set_id: (i.document_set_id as string | undefined) ?? null, at: at(i, ctx) });
        put(rt, ctx, "closings", r.closing.closing_id, r.closing); return { closing_id: r.closing.closing_id, closing_type: d.closing_type, note_form: d.note_form, reasons: d.reasons, location_required: d.location_required, event_id: r.event.id, is_hpml: r.closing.is_hpml, scheduled_note_date: r.closing.scheduled_note_date }; }
      const c = loadClosing(i, rt);
      if (i.op === "upstream") { need(i, "event"); const next = put(rt, ctx, "closings", c.closing_id, applyReleaseEvent(c, i.event as Parameters<typeof applyReleaseEvent>[1])); return { closing_id: c.closing_id, execution_status: next.execution_status, document_set_id: next.document_set_id, documents_released_at: next.documents_released_at, instructions_acknowledged_at: next.instructions_acknowledged_at }; }
      const f = (i.facts as Partial<PreSessionFacts> | undefined) ?? {}; const now = at(i, ctx);
      const facts: PreSessionFacts = { closing_type: c.closing_type, requested_on: D(c.scheduled_note_date), consent: consentOf(i, rt, c), ctc: f.ctc ?? { ctc_issued: false, checklist_passed: false, decision_status: "active" }, le: f.le ?? {}, cd: f.cd ?? {}, signing_package: f.signing_package ?? [], rescindable: c.rescindable, fraud_hold: f.fraud_hold ?? null, compliance_consummate_gate_open: f.compliance_consummate_gate_open === true, instructions_acknowledged: !!c.instructions_acknowledged_at || f.instructions_acknowledged === true, tx_50a6: c.tx_50a6, documents_released: !!c.documents_released_at || f.documents_released === true, vvoe_within_10bd: f.vvoe_within_10bd === true, mi_commitment_valid: f.mi_commitment_valid !== false, lock_valid_through_closing: f.lock_valid_through_closing !== false, privacy_notice_gate_open: f.privacy_notice_gate_open !== false, state_notice_gate_open: f.state_notice_gate_open !== false, appraisal_copy_gate_open: f.appraisal_copy_gate_open !== false };
      const r = runPreSessionChecks(facts, now); if (!r.passed) return { closing_id: c.closing_id, passed: false, blocking: r.blocking, checked: r.checked };
      const p = passPreSessionChecks(ctx.events, c, r, now); put(rt, ctx, "closings", c.closing_id, p.closing); return { closing_id: c.closing_id, passed: true, blocking: [], checked: r.checked, execution_status: p.closing.execution_status }; }),
    guardrails: [never("TX_50A6_OFFICE_ONLY", "§50(a)(6)(N) / 7 TAC §153.15: a TX 50(a)(6) closing occurs only at a permanent office of the lender, an attorney or a title company — never remote", (i) => i.op === "schedule" && flag(i, "tx_50a6") && (str(i, "location_type") === "remote" || str(i, "location_type") === "homestead"), "TX 50(a)(6): lender/attorney/title-company office only"),
      never("NEVER_REQUIRE_ELECTRONIC", "A2-4.1-03: a lender may not require a borrower to use remote notarization and under no circumstances may a borrower be required to use electronic records", (i) => flag(i, "require_electronic") || flag(i, "require_ron"), "the paper option is always offered; the borrower's election governs"),
      never("UNLISTED_STATE_NEEDS_COUNSEL", "26.2 guardrails / decision 26.2-Q4: never treat Georgia/Mississippi (or any unlisted state) as RON-eligible without counsel confirmation", unlistedWithoutCounsel, "no RON until Fannie Mae lists the state or partner counsel issues a written 'expressly permits' opinion")] },
  // Business rule "Closing-type decision": ron → ipen → hybrid → wet from 26.1's profile, the borrower's election, the RON matrix, the agent's eligibility and every signer's consent; TX 50(a)(6) → wet at a permitted office; the note is single-method.
  { name: "decideClosingType", kind: "read", handler: compute((i, _c, rt) => { need(i, "state", "settlement_agent_party_id"); const d = decideClosingType(ronInput(i, { state: str(i, "state"), county_fips: (i.county_fips as string | undefined) ?? null, tx_50a6: flag(i, "tx_50a6") }, eligibilityRows(i, rt), str(i, "settlement_agent_party_id"))); return { ...d, ron: { eligible: d.ron.eligible, refusals: d.ron.refusals, counsel_confirmed: d.ron.counsel_confirmed, statute: d.ron.rule.ron_statute_cite } }; }),
    guardrails: [never("UNLISTED_STATE_NEEDS_COUNSEL", "26.2 guardrails: never treat an unlisted state as RON-eligible without counsel confirmation", unlistedWithoutCounsel, "Fannie Mae's list plus a counsel 'expressly permits' opinion govern")] },
  // E-SIGN §101(c): consent scoped to the closing package, unwithdrawn, hardware/software demonstration and paper option on record → `closing.consent.verified` (SM_O72_ESIGN_CONSENT_CLOSING_GATE); refused otherwise (offer the wet path).
  { name: "verifyEsignConsent", kind: "act", handler: compute((i, ctx, rt) => { const c = loadClosing(i, rt); const consent = consentOf(i, rt, c); const r = verifyConsent(ctx.events, c, consent, at(i, ctx)); return { closing_id: c.closing_id, open: r.open, reason: r.reason, consent_id: consent?.consent_id ?? null, offer_wet_path: !r.open, event_id: r.event?.id ?? null }; }),
    guardrails: [never("CONSENT_NEVER_ASSUMED", "E-SIGN 15 U.S.C. 7001(c)(1)(A): affirmative consent, never implied or assumed", (i) => flag(i, "assume_consent"), "consent is a captured record with the §101(c) statements")] },
  // SM_O72_RON_STATE_AUTH_GATE + SM_O72_AGENT_ECLOSING_ELIGIBLE_GATE: the RON matrix (Fannie Mae list / counsel opinion, county, title, notary in state, not TX 50(a)(6)) and the 24.4 eligibility row → `closing.eligibility.checked{check, result}`.
  { name: "checkRonEligibility", kind: "act", handler: compute((i, ctx, rt) => { const c = loadClosing(i, rt); const rows = eligibilityRows(i, rt); const now = at(i, ctx);
      const ron = ronStateAuthCheck(ronInput(i, c, rows, c.settlement_agent_party_id)); const agent = agentEclosingEligible(rows, c.settlement_agent_party_id, c.county_fips, c.closing_type);
      const e1 = recordEligibilityCheck(ctx.events, c, "ron_state_auth", { eligible: ron.eligible, refusals: ron.refusals }, now); const e2 = recordEligibilityCheck(ctx.events, c, "agent_eclosing", agent, now);
      return { closing_id: c.closing_id, ron_eligible: ron.eligible, ron_refusals: ron.refusals, counsel_confirmed: ron.counsel_confirmed, agent_eligible: agent.eligible, agent_reason: agent.reason, downgrade_to: agent.downgrade_to, offered_alternatives: ron.eligible ? [] : ["ipen", "hybrid", "wet"], event_ids: [e1.id, e2.id] }; }),
    guardrails: [never("UNLISTED_STATE_NEEDS_COUNSEL", "26.2 guardrails: never treat an unlisted state as RON-eligible without counsel confirmation", unlistedWithoutCounsel, "no RON without Fannie Mae's list or a counsel opinion")] },
  // Notary network: commission verified, physically located in the state of the notarial act (A2-4.1-03), not blocked by a prior KBA failure within 24 hours; records the assignment on the closing.
  { name: "assignNotary", kind: "act", handler: compute((i, ctx, rt) => { const c = loadClosing(i, rt); need(i, "notary_party_id", "commission_state", "physical_location_state");
      if (c.closing_type === "ron" && (str(i, "commission_state") !== c.state || str(i, "physical_location_state") !== c.state)) throw new RangeError(`RON notary must be commissioned and physically located in ${c.state}`);
      if (!flag(i, "commission_verified")) throw new RangeError("notary commission not verified (state SOS lookup)");
      const blocked = rt.store.list("signing_sessions", (d) => d.closing_id === c.closing_id && d.retake_blocked_notary_party_id === str(i, "notary_party_id") && typeof d.retake_blocked_until === "string" && (d.retake_blocked_until as string) > at(i, ctx));
      if (blocked.length) throw new RangeError(`notary ${str(i, "notary_party_id")} blocked until ${String(blocked[0]!.data.retake_blocked_until)} after the KBA failure (1 TAC §87.70)`);
      const next = put(rt, ctx, "closings", c.closing_id, { ...c, notary_party_id: str(i, "notary_party_id") }); ctx.events.append({ type: "closing.notary.assigned", applicationId: c.application_id, actor: ctx.actor, occurredAt: at(i, ctx), payload: { application_id: c.application_id, closing_id: c.closing_id, notary_party_id: str(i, "notary_party_id"), commission_state: str(i, "commission_state"), physical_location_state: str(i, "physical_location_state") } });
      return { closing_id: c.closing_id, notary_party_id: next.notary_party_id, mode: c.closing_type }; }),
    guardrails: [never("NOTARY_IN_STATE", "A2-4.1-03: the notary public must be licensed and physically located in the state in which the notarial act is performed", (i) => flag(i, "out_of_state_notary"), "never a notary outside the state of the notarial act")] },
  // Opens the platform session for the signer group (never with a closed gate; pre-session checks within 24 hours; 26.1 release and TX acknowledgment on file) → `closing.session.created`.
  { name: "openSigningSession", kind: "act", handler: compute(async (i, ctx, rt) => { const c = loadClosing(i, rt); const session_id = str(i, "session_id") || `SES-${c.closing_id}-${c.session_ids.length + 1}`;
      const platform = c.closing_type === "wet" ? null : (await ronPlatform(rt).createSession({ closing_id: c.closing_id, mode: c.closing_type === "ron" ? "ron" : c.closing_type === "ipen" ? "ipen" : "esign_only", signer_party_ids: arr<string>(i, "signer_party_ids"), notary_party_id: (i.notary as { party_id?: string } | undefined)?.party_id ?? c.notary_party_id, scheduled_at: c.scheduled_at }, at(i, ctx))).platform_session_ref;
      const r = openSigningSession(ctx.events, c, { session_id, at: at(i, ctx), signer_party_ids: arr<string>(i, "signer_party_ids"), notary: (i.notary as Parameters<typeof openSigningSession>[2]["notary"] | undefined) ?? null, platform_session_ref: platform, consent_record_id: (i.consent_record_id as string | undefined) ?? null, ...(i.signer_physical_location ? { signer_physical_location: i.signer_physical_location as Record<string, { state: string; country: string }> } : {}) });
      put(rt, ctx, "closings", c.closing_id, r.closing); put(rt, ctx, "signing_sessions", session_id, r.session); return { closing_id: c.closing_id, session_id, mode: r.session.mode, status: r.session.status, platform_session_ref: platform, recording_custodian: r.session.recording_custodian, recording_retention_years: r.session.recording_retention_years }; }),
    guardrails: [never("GATE_CLOSED", "26.2 guardrails: the agent may never open a session with a closed gate", (i) => flag(i, "gate_closed") || (Array.isArray(i.closed_gates) && (i.closed_gates as unknown[]).length > 0), "every pre-session gate must be open"),
      never("NEVER_REQUIRE_RON", "A2-4.1-03: a lender may not require a borrower to use remote notarization and must have other notary options available", (i) => flag(i, "require_ron"), "other notary options are always available")] },
  // Reads platform webhooks, never acting as notary or signer: `op` ∈ identity | start | sign | notarial_act | enote_created | fail | reschedule | advance_check — identity proofing (KBA per jurisdiction), consummation at the final note signature, notarial acts (last → audit-trail gate; security instrument → recording clock), session failure (identity → wet/IPEN reschedule), 27.1's advance check.
  { name: "monitorSession", kind: "act", handler: compute((i, ctx, rt) => { const c = loadClosing(i, rt); const op = str(i, "op") || "status"; const now = at(i, ctx);
      if (op === "status") { const ss = rt.store.list("signing_sessions", (d) => d.closing_id === c.closing_id).map((r) => r.data); return { closing_id: c.closing_id, execution_status: c.execution_status, consummation_at: c.consummation_at, sessions: ss.map((s) => ({ session_id: s.session_id, status: s.status, failure_reason: s.failure_reason })) }; }
      if (op === "enote_created") { need(i, "closing_document_id", "min", "partner_org_id"); const e = createENote(c, { enote_id: str(i, "enote_id") || `EN-${c.closing_id}`, closing_document_id: str(i, "closing_document_id"), min: str(i, "min"), partner_org_id: str(i, "partner_org_id"), ...(typeof i.location_org_id === "string" ? { location_org_id: i.location_org_id } : {}) }); put(rt, ctx, "enotes", e.enote_id, e); return { enote_id: e.enote_id, status: e.status, controller_org_id: e.controller_org_id, location_org_id: e.location_org_id, delegatee_org_id: e.delegatee_org_id }; }
      if (op === "advance_check") { const e = rt.store.list("enotes", (d) => d.closing_id === c.closing_id).at(-1)?.data as unknown as ENote | undefined; assertSecuredPartyBeforeAdvance(e ?? null, c.note_form); return { closing_id: c.closing_id, advance_allowed: true, secured_party_org_id: e?.secured_party_org_id ?? null }; }
      if (op === "reschedule") { need(i, "scheduled_at", "closing_type"); const r = rescheduleClosing(ctx.events, c, { at: now, scheduled_at: str(i, "scheduled_at"), closing_type: str(i, "closing_type") as ClosingType, reason: str(i, "reason") || "reschedule" }); put(rt, ctx, "closings", c.closing_id, r.closing); return { closing_id: c.closing_id, closing_type: r.closing.closing_type, execution_status: r.closing.execution_status, scheduled_note_date: r.closing.scheduled_note_date }; }
      const s = loadSession(i, rt, c);
      if (op === "identity") { need(i, "party_id", "method", "notary_party_id"); const r = proofIdentity(ctx.events, c, s, { party_id: str(i, "party_id"), method: str(i, "method") as IdentityMethod, credential_type: (i.credential_type as string | undefined) ?? null, credential_analysis_result: (i.credential_analysis_result as "pass" | "fail" | undefined) ?? null, kba_attempts: arr<KbaAttempt>(i, "kba_attempts"), vendor: (i.vendor as string | undefined) ?? null, evidence_document_id: (i.evidence_document_id as string | undefined) ?? null, at: now, notary_party_id: str(i, "notary_party_id"), ...(i.notary_refused !== undefined ? { notary_refused: flag(i, "notary_refused") } : {}) });
        put(rt, ctx, "signing_sessions", s.session_id, r.session); if (r.session.status === "failed") put(rt, ctx, "closings", c.closing_id, { ...c, execution_status: "session_failed" });
        return { session_id: s.session_id, party_id: str(i, "party_id"), result: r.record.result, status: r.session.status, failure_reason: r.session.failure_reason, kba: r.kba, retake_blocked_until: r.session.retake_blocked_until, reschedule_proposal: r.session.reschedule_proposal }; }
      if (op === "start") { const r = startSession(ctx.events, c, s, now); put(rt, ctx, "closings", c.closing_id, r.closing); put(rt, ctx, "signing_sessions", s.session_id, r.session); return { session_id: s.session_id, status: r.session.status, started_at: r.session.started_at }; }
      if (op === "sign") { need(i, "closing_document_id", "kind", "signer_party_id", "signature_method"); const r = signDocument(ctx.events, c, s, { closing_document_id: str(i, "closing_document_id"), kind: str(i, "kind"), signer_party_id: str(i, "signer_party_id"), signed_at: str(i, "signed_at") || now, signature_method: str(i, "signature_method") as "wet" | "esign" | "esign_ron" | "esign_ipen", required_note_signers: arr<string>(i, "required_note_signers"), single_record: i.single_record !== false, action_taken: i.action_taken !== false, hpml: (i.hpml as HpmlRow | undefined) ?? null });
        put(rt, ctx, "closings", c.closing_id, r.closing); put(rt, ctx, "signing_sessions", s.session_id, r.session);
        if (r.closing.consummation_at && !c.consummation_at) { const cd = rt.store.get("closing_documents", str(i, "closing_document_id")); if (cd) put(rt, ctx, "closing_documents", str(i, "closing_document_id"), { ...cd.data, signed_document_id: str(i, "signed_document_id") || `SIGNED-${str(i, "closing_document_id")}`, execution_status: "signed" }); }
        return { session_id: s.session_id, consummation_at: r.closing.consummation_at, consummation_on: r.closing.consummation_on, note_date: r.closing.note_date, note_fully_signed: r.consummation?.note_fully_signed ?? null, ancillaries_after_midnight: r.consummation?.ancillaries_after_midnight ?? [], status: r.session.status }; }
      if (op === "notarial_act") { need(i, "closing_document_id", "kind", "act_type", "notary_party_id"); const r = completeNotarialAct(ctx.events, c, s, { closing_document_id: str(i, "closing_document_id"), kind: str(i, "kind"), act_type: str(i, "act_type") as "acknowledgment" | "jurat", completed_at: str(i, "completed_at") || now, certificate_indicates_communication_technology: flag(i, "certificate_indicates_communication_technology"), recordable: flag(i, "recordable"), last: flag(i, "last"), notary_party_id: str(i, "notary_party_id"), ...(i.connectivity_lost !== undefined ? { connectivity_lost: flag(i, "connectivity_lost") } : {}) });
        put(rt, ctx, "closings", c.closing_id, r.closing); put(rt, ctx, "signing_sessions", s.session_id, r.session); const cd = rt.store.get("closing_documents", str(i, "closing_document_id")); if (cd && !flag(i, "connectivity_lost")) put(rt, ctx, "closing_documents", str(i, "closing_document_id"), { ...cd.data, execution_status: "notarized" });
        return { session_id: s.session_id, status: r.session.status, event: r.event.type, recording_anchor: (r.event.payload as { recording_anchor?: boolean }).recording_anchor ?? false, erecord_due: (r.event.payload as { erecord_due?: string | null }).erecord_due ?? null }; }
      if (op === "fail") { need(i, "reason"); const r = failSession(ctx.events, c, s, { at: now, reason: str(i, "reason") as SessionFailure, proposal: arr<ClosingType>(i, "proposal").length ? arr<ClosingType>(i, "proposal") : ["wet", "ipen"] }); put(rt, ctx, "closings", c.closing_id, r.closing); put(rt, ctx, "signing_sessions", s.session_id, r.session); return { session_id: s.session_id, status: r.session.status, failure_reason: r.session.failure_reason, reschedule_proposal: r.session.reschedule_proposal }; }
      throw new RangeError(`unknown op ${op}`); }),
    guardrails: [never("PLATFORM_NEVER_SIGNS", "26.2 state machine: only the signer applies a signature; only the notary performs the notarial act; the platform records, never signs — the agent may never apply, complete or 'assist' a signature or notarial act", (i) => flag(i, "apply_signature") || flag(i, "complete_notarial_act") || flag(i, "assist_signature") || (i.op === "sign" && str(i, "signer_party_id") === "title-closing"), "signatures and notarial acts are the signer's and the notary's own acts"),
      never("NO_KBA_OVERRIDE", "1 TAC §87.70 / A2-4.1-03: the agent may never accept a KBA or credential-analysis override; SM never overrides a notary's refusal", (i) => flag(i, "kba_override") || flag(i, "credential_override") || flag(i, "override_notary_refusal"), "identity proofing results stand as the vendor and the notary recorded them"),
      never("NO_PARTIAL_NOTE_SIGNATURES", "26.2 integrations: SM never accepts partial signatures on the note — the eNote is re-presented whole", (i) => i.op === "sign" && flag(i, "partial_note"), "the eNote is signed whole or re-presented")] },
  // Location role: the Authoritative Copy is stored in / read from the eVault (rt.ports.evault), its hash validated against the platform seal → `enote.authoritative_copy.validated{hash_match}`; `op=seal` first records the platform's seal (`enote.tamper_sealed`, arming the MERS 1-BD clock).
  { name: "validateAuthoritativeCopy", kind: "act", handler: compute(async (i, ctx, rt) => { const c = loadClosing(i, rt); const e = loadENote(rt, c); const now = at(i, ctx);
      if (i.op === "seal") { need(i, "seal_hash", "signing_completed_at"); const r = tamperSeal(ctx.events, c, e, { tamper_sealed_at: str(i, "tamper_sealed_at") || now, seal_hash: str(i, "seal_hash"), signing_completed_at: str(i, "signing_completed_at"), authoritative_copy_ref: (i.authoritative_copy_ref as string | undefined) ?? null }); put(rt, ctx, "enotes", e.enote_id, r.enote); put(rt, ctx, "closings", c.closing_id, { ...c, execution_status: "sealed" });
        const cd = rt.store.get("closing_documents", e.closing_document_id); if (cd) put(rt, ctx, "closing_documents", e.closing_document_id, { ...cd.data, execution_status: "tamper_sealed" });
        return { enote_id: e.enote_id, tamper_sealed_at: r.enote.tamper_sealed_at, registration_anchor_date: r.due.anchor_date, registration_due_at: r.due.due_at, registration_target_at: r.due.target_at }; }
      let copyHash = (i.evault_copy_hash as string | undefined) ?? null; let status: "intact" | "tampered" | "missing" = (i.evault_status as "intact" | "tampered" | "missing" | undefined) ?? "intact";
      if (typeof i.authoritative_copy === "string") { const stored = await evault(rt).store(i.authoritative_copy, { contentType: "application/xml", retentionClass: RETENTION_ENOTE_SIGNING }, now); copyHash = stored.sha256; status = await evault(rt).verify(stored.sha256); }
      else if (copyHash && rt.ports.evault) { const v = await rt.ports.evault.verify(copyHash); status = v; }
      const r = validateAuthoritativeCopy(ctx.events, c, e, { evault_copy_hash: copyHash, evault_status: status, at: now }); put(rt, ctx, "enotes", e.enote_id, r.enote);
      return { enote_id: e.enote_id, gate_open: r.gate.open, hash_match: r.gate.hash_match, reason: r.gate.reason, evault_copy_hash: copyHash, tamper_seal_hash: e.tamper_seal_hash, code: "SM_O72_ENOTE_LOCATION_GATE" }; }),
    guardrails: [never("PAPER_NEVER_CONVERTED", "A2-4.1-03: paper notes may not be converted into eNotes", (i) => flag(i, "convert_paper_to_enote"), "a paper note is never converted into an eNote")] },
  // Digitally signed Registration XML (Controller = partner Org ID; Location = SM/vendor eVault; Delegatee for Transfers = SM; Servicing Agent = SM; the 26.1 MIN) — refused while SM_O72_ENOTE_LOCATION_GATE is closed; acceptance → `enote.registered` (MERS_PROC_ENOTE_REGISTER_1BD / SM_O72_ENOTE_SAME_DAY_REGISTER), rejection → `enote.registration.rejected` (fix and resubmit within the window).
  { name: "registerENote", kind: "act", handler: compute(async (i, ctx, rt) => { const c = loadClosing(i, rt); const e = loadENote(rt, c);
      const r = await registerENote(ctx.events, eregistry(rt), c, e, { at: at(i, ctx), ...(typeof i.signing_key_id === "string" ? { signing_key_id: i.signing_key_id } : {}), ...(i.unsigned !== undefined ? { unsigned: flag(i, "unsigned") } : {}) });
      put(rt, ctx, "enotes", e.enote_id, r.enote); put(rt, ctx, "mers_transactions", r.txn.id, r.txn);
      if (!r.ack.accepted) { rt.escalations.open({ kind: "officer", applicationId: c.application_id, payload: { reason: "enote_registration_rejected", error_codes: r.ack.error_codes, min: e.min, registration_due_at: e.registration_due_at, sla: "before registration_due_at" } }, ctx.actor); }
      else if (r.on_time === false) rt.escalations.open({ kind: "officer", applicationId: c.application_id, payload: { reason: "emortgage_registration_late", severity: 1, min: e.min, registered_at: r.enote.registered_at, registration_due_at: e.registration_due_at, remediation: "memo; Fannie Mae eMortgage Group contact (B8-8-02 'could render loan ineligible')" } }, ctx.actor);
      return { enote_id: e.enote_id, min: e.min, accepted: r.ack.accepted, txn_id: r.ack.txn_id, error_codes: r.ack.error_codes, registered_at: r.enote.registered_at, registration_due_at: e.registration_due_at, on_time: r.on_time, controller_org_id: e.controller_org_id, location_org_id: e.location_org_id, delegatee_org_id: e.delegatee_org_id }; }),
    guardrails: [never("HASH_MUST_MATCH", "26.2 guardrails: never register an eNote whose hash does not match the eVault copy (SM_O72_ENOTE_LOCATION_GATE)", (i) => flag(i, "hash_mismatch") || flag(i, "skip_location_gate"), "the Registration XML is not sent until the Authoritative Copy hash is validated"),
      needsRole("EREGISTRY_NOT_DELEGATED", "26.2 automation class (b): the `signing_officer` submits eRegistry transactions the partner has not delegated to SM", (i) => flag(i, "partner_not_delegated"), ["signing_officer"], "an undelegated eRegistry transaction is the signing officer's act")] },
  // Change Data naming SM's Org ID as Secured Party before any warehouse advance → `enote.secured_party.set` (SM_O72_SECURED_PARTY_BEFORE_ADVANCE_GATE; 27.1 checks it); `op=advance_check` is 27.1's refusal path (`secured_party_missing`).
  { name: "setSecuredParty", kind: "act", handler: compute(async (i, ctx, rt) => { const c = loadClosing(i, rt); const e = rt.store.list("enotes", (d) => d.closing_id === c.closing_id).at(-1)?.data as unknown as ENote | undefined;
      if (i.op === "advance_check") { assertSecuredPartyBeforeAdvance(e ?? null, c.note_form); return { closing_id: c.closing_id, advance_allowed: true, secured_party_org_id: e?.secured_party_org_id ?? null }; }
      if (!e) throw new RangeError(`no eNote for closing ${c.closing_id}`);
      const r = await setSecuredParty(ctx.events, eregistry(rt), c, e, { at: at(i, ctx), ...(typeof i.secured_party_org_id === "string" ? { secured_party_org_id: i.secured_party_org_id } : {}) }); put(rt, ctx, "enotes", e.enote_id, r.enote); put(rt, ctx, "mers_transactions", r.txn.id, r.txn);
      return { enote_id: e.enote_id, min: e.min, accepted: r.ack.accepted, secured_party_org_id: r.enote.secured_party_org_id, secured_party_set_at: r.enote.secured_party_set_at, error_codes: r.ack.error_codes, code: "SM_O72_SECURED_PARTY_BEFORE_ADVANCE_GATE" }; }),
    guardrails: [never("SECURED_PARTY_IS_SM", "26.2 capacity: SM becomes Secured Party when it advances on the warehouse line — never another party's Org ID from this runtime", (i) => typeof i.secured_party_org_id === "string" && i.secured_party_org_id !== SM_ORG_ID, `Secured Party = SM (${SM_ORG_ID})`)] },
  // Registration Reversal after a replacement eNote registers (B8-8-02), on rescission (25.3; after the Secured Party release — decision 26.2-Q6) or unwind (26.3) → `enote.registration.reversed`.
  { name: "reverseRegistration", kind: "act", handler: compute(async (i, ctx, rt) => { const c = loadClosing(i, rt); const e = loadENote(rt, c); need(i, "reason");
      const r = await reverseRegistration(ctx.events, eregistry(rt), c, e, { at: at(i, ctx), reason: str(i, "reason") as "redraw_replacement" | "rescission" | "unwind" | "data_error", replacement_registered: flag(i, "replacement_registered") }); put(rt, ctx, "enotes", e.enote_id, r.enote); for (const t of r.txns) put(rt, ctx, "mers_transactions", t.id, t);
      if (str(i, "reason") === "rescission" || str(i, "reason") === "unwind") put(rt, ctx, "closings", c.closing_id, { ...c, execution_status: "voided" });
      return { enote_id: e.enote_id, min: e.min, registration_status: r.enote.registration_status, transactions: r.txns.map((t) => ({ id: t.id, txn_type: t.txn_type, result: t.result })), reversed: r.enote.registration_status === "reversed" }; }),
    guardrails: [needsRole("REVERSAL_NOT_DELEGATED", "26.2 automation class (b): eRegistry transactions the partner has not delegated are the `signing_officer`'s", (i) => flag(i, "partner_not_delegated"), ["signing_officer"], "an undelegated Registration Reversal is the signing officer's act")] },
  // The tamper-sealed audit trail (hash-verified; RON recording reference and retention custodian) → `closing.audit_trail.received` (SM_O72_AUDIT_TRAIL_BEFORE_FUNDING_GATE); `op=funding_check` is 26.3's refusal path for `funding.authorize`.
  { name: "ingestAuditTrail", kind: "act", handler: compute((i, ctx, rt) => { const c = loadClosing(i, rt); const s = loadSession(i, rt, c);
      if (i.op === "funding_check") { assertAuditTrailOnFile(s, c.closing_type, str(i, "command") || "funding.authorize"); return { closing_id: c.closing_id, session_id: s.session_id, funding_allowed: true, audit_trail_received_at: s.audit_trail_received_at }; }
      need(i, "document_id", "audit_trail_hash", "platform_hash");
      const r = ingestAuditTrail(ctx.events, c, s, { at: at(i, ctx), document_id: str(i, "document_id"), audit_trail_hash: str(i, "audit_trail_hash"), platform_hash: str(i, "platform_hash"), recording_ref: (i.recording_ref as string | undefined) ?? null, journal_ref: (i.journal_ref as string | undefined) ?? null });
      put(rt, ctx, "closings", c.closing_id, r.closing); put(rt, ctx, "signing_sessions", s.session_id, r.session); rt.store.put("documents", str(i, "document_id"), { kind: "ron_audit_trail", application_id: c.application_id, sha256: str(i, "audit_trail_hash"), retention_class: RETENTION_ENOTE_SIGNING, metadata: { session_id: s.session_id, recording_ref: r.session.recording_ref, recording_custodian: r.session.recording_custodian, recording_retention_years: r.session.recording_retention_years } }, ctx.actor, ctx.now);
      return { closing_id: c.closing_id, session_id: s.session_id, audit_trail_received_at: r.session.audit_trail_received_at, audit_trail_hash: r.session.audit_trail_hash, recording_custodian: r.session.recording_custodian, recording_retention_years: r.session.recording_retention_years, retention_class: RETENTION_ENOTE_SIGNING, gate_open: true }; }),
    guardrails: [never("NO_FUNDING_BEFORE_AUDIT_TRAIL", "26.2 guardrails: never fund-related actions before the audit trail is on file (SM_O72_AUDIT_TRAIL_BEFORE_FUNDING_GATE)", (i) => flag(i, "authorize_funding_without_audit_trail"), "funding.authorize waits for closing.audit_trail.received")] },
  // Post-signing review (SM_O72_POST_SIGNING_REVIEW_4H): signatures/attribution, name variances (→ affidavit), notarial certificates, witnesses, POA form, MIN, no handwritten changes (→ re-draw), H-8/CD/TX receipts, eNote and audit-trail hashes, recording readiness → `closing.execution_review.passed|failed`.
  { name: "reviewExecution", kind: "act", handler: compute((i, ctx, rt) => { const c = loadClosing(i, rt); const docs = arr<ExecutedDocument>(i, "documents"); if (!docs.length) throw new RangeError("26.2 tool needs documents (executed set)");
      const s = rt.store.list("signing_sessions", (d) => d.closing_id === c.closing_id).at(-1)?.data as unknown as SigningSession | undefined;
      const r = reviewExecution(docs, s?.audit_trail_hash ? { audit_trail_hash: s.audit_trail_hash, platform_hash: (i.platform_hash as string | undefined) ?? s.audit_trail_hash } : null); const rec = recordExecutionReview(ctx.events, c, r, at(i, ctx)); put(rt, ctx, "closings", c.closing_id, rec.closing);
      let escalation_id: string | null = null; if (!r.passed) escalation_id = rt.escalations.open({ kind: "settlement_agent", applicationId: c.application_id, payload: { reason: "execution_defects", defects: r.defects, redraw: r.redraw, sla: "same day" } }, ctx.actor).id;
      let redraw_scheduled = false; if (r.redraw && c.document_set_id) { ctx.events.append({ type: "closing.redraw.requested", applicationId: c.application_id, actor: ctx.actor, occurredAt: at(i, ctx), payload: { application_id: c.application_id, closing_id: c.closing_id, set_id: c.document_set_id, reason: r.redraw.reason, documents: r.redraw.documents } }); redraw_scheduled = true; }
      return { closing_id: c.closing_id, passed: r.passed, defects: r.defects, funding_blocked: r.funding_blocked, redraw: r.redraw, redraw_scheduled, name_affidavits: r.name_affidavits, escalation_id, execution_status: rec.closing.execution_status }; }),
    guardrails: [needsRole("DEFECT_WAIVER_OFFICER", "26.2 escalations: waiver of an execution defect is the `officer`'s decision", (i) => Array.isArray(i.waive_defects) && (i.waive_defects as unknown[]).length > 0, ["officer"], "an execution-defect waiver is the partner officer's decision")] },
  // eRecording (PRIA 2.4.2; Model 2 image+index default): `op=open` creates the package row from the anchor (notarial act / loan.funded); default submits it (accepted for processing) → `recording.submitted` (SM_O72_ERECORD_SUBMIT_1BD); `op=confirm` records instrument number / timestamp / gap_days → `recording.confirmed`.
  { name: "submitERecording", kind: "act", handler: compute(async (i, ctx, rt) => { const c = loadClosing(i, rt); const now = at(i, ctx);
      if (i.op === "open") { need(i, "recording_id", "closing_document_id", "county", "anchor_date"); const covered = rt.ports.erecording ? await rt.ports.erecording.countyCovered(c.state, str(i, "county")) : i.county_covered !== false;
        const r = openRecording(c, { recording_id: str(i, "recording_id"), closing_document_id: str(i, "closing_document_id"), channel: covered ? "erecording" : "paper", vendor: covered ? (str(i, "vendor") || "simplifile") : null, submitter_party_id: str(i, "submitter_party_id") || c.settlement_agent_party_id, state: c.state, county: str(i, "county"), county_fips: (i.county_fips as string | undefined) ?? c.county_fips, anchor_date: D(str(i, "anchor_date")), ...(typeof i.pria_model === "string" ? { pria_model: i.pria_model as Recording["pria_model"] } : {}), date_of_policy: typeof i.date_of_policy === "string" ? D(i.date_of_policy) : null });
        put(rt, ctx, "recordings", r.recording_id, r); return { recording_id: r.recording_id, channel: r.channel, county_covered: covered, anchor_date: r.anchor_date, due_date: r.due_date, pria_model: r.pria_model }; }
      const r = loadRecording(i, rt);
      if (i.op === "confirm") { need(i, "instrument_number"); const x = confirmRecording(ctx.events, c, r, { at: now, instrument_number: str(i, "instrument_number"), book_page: (i.book_page as string | undefined) ?? null, recording_fee_cents: i.recording_fee_cents === undefined ? null : cents(i.recording_fee_cents), recorded_image_document_id: (i.recorded_image_document_id as string | undefined) ?? null, date_of_policy: typeof i.date_of_policy === "string" ? D(i.date_of_policy) : null }); put(rt, ctx, "recordings", r.recording_id, x.recording);
        const all = rt.store.list("recordings", (d) => d.closing_id === c.closing_id).map((d) => d.data as unknown as Recording); if (all.every((q) => q.recorded_at)) put(rt, ctx, "closings", c.closing_id, { ...c, execution_status: c.execution_status === "funded" ? "recorded" : c.execution_status });
        return { recording_id: r.recording_id, recorded_at: x.recording.recorded_at, instrument_number: x.recording.instrument_number, gap_days: x.recording.gap_days, covered_risk_14_applies: (x.event.payload as { covered_risk_14_applies: boolean }).covered_risk_14_applies }; }
      const x = submitERecording(ctx.events, c, r, { at: now, package_ref: str(i, "package_ref") || `PKG-${r.recording_id}-${r.resubmitted_count + 1}`, ...(i.instrument_altered !== undefined ? { instrument_altered: flag(i, "instrument_altered") } : {}), ...(i.resubmission !== undefined ? { resubmission: flag(i, "resubmission") } : {}) }); put(rt, ctx, "recordings", r.recording_id, x.recording);
      return { recording_id: r.recording_id, status: x.recording.status, submitted_at: x.recording.submitted_at, package_ref: x.recording.package_ref, resubmitted_count: x.recording.resubmitted_count, on_time: D(now.slice(0, 10)) <= r.due_date }; }),
    guardrails: [never("NO_ALTERED_INSTRUMENT", "26.2 guardrails: never submit a recording with a handwritten instrument change", (i) => flag(i, "instrument_altered"), "an altered instrument is re-drawn (26.1), never recorded")] },
  // County rejection (reason taxonomy → cure action) → `recording.rejected` (SM_O72_RECORDING_REJECT_CURE_2BD: +2 creditor business days); `settlement_agent` escalation same day.
  { name: "handleRecordingReject", kind: "act", handler: compute((i, ctx, rt) => { const c = loadClosing(i, rt); const r = loadRecording(i, rt); need(i, "reason");
      const x = handleRecordingReject(ctx.events, c, r, { at: at(i, ctx), reason: str(i, "reason") }); put(rt, ctx, "recordings", r.recording_id, x.recording);
      const esc = rt.escalations.open({ kind: "settlement_agent", applicationId: c.application_id, payload: { reason: "recording_rejected", rejection_reason: str(i, "reason"), cure: x.cure, cure_due: x.cure_due, recording_id: r.recording_id, sla: "same day" } }, ctx.actor);
      return { recording_id: r.recording_id, status: x.recording.status, rejection_reason: str(i, "reason"), cure: x.cure, cure_due: x.cure_due, escalation_id: esc.id, code: "SM_O72_RECORDING_REJECT_CURE_2BD" }; }) },
  // Unavailable county / uncured rejection → paper package by tracked courier → `recording.paper_fallback` (SM_O72_PAPER_FALLBACK_5BD) + `recording.submitted{channel=paper}`; the open cure timer is cancelled; `op=county_receipt` → `recording.county_receipt.confirmed`.
  { name: "dispatchPaperRecording", kind: "act", handler: compute((i, ctx, rt) => { const c = loadClosing(i, rt); const r = loadRecording(i, rt); const now = at(i, ctx);
      if (i.op === "county_receipt") { const x = confirmCountyReceipt(ctx.events, c, r, { at: now, evidence_document_id: (i.evidence_document_id as string | undefined) ?? null }); put(rt, ctx, "recordings", r.recording_id, x.recording); return { recording_id: r.recording_id, county_receipt_at: x.recording.county_receipt_at }; }
      need(i, "tracking_ref"); const x = dispatchPaperRecording(ctx.events, c, r, { at: now, tracking_ref: str(i, "tracking_ref"), ...(i.county_turnaround_days !== undefined ? { county_turnaround_days: Number(i.county_turnaround_days) } : {}) }); put(rt, ctx, "recordings", r.recording_id, x.recording);
      for (const t of ctx.timers.byCode("SM_O72_RECORDING_REJECT_CURE_2BD")) if (t.status === "armed" && t.applicationId === c.application_id) ctx.timers.cancel(t.id, "paper fallback dispatched instead of a resubmission", ctx.actor);
      return { recording_id: r.recording_id, status: x.recording.status, tracking_ref: str(i, "tracking_ref"), county_receipt_due: x.due, expected_recording_date: x.expected_recording_date, code: "SM_O72_PAPER_FALLBACK_5BD" }; }),
    guardrails: [never("PAPER_FALLBACK_NEVER_DISABLED", "26.2 guardrails: never disable the paper fallback — county acceptance is per-county configuration with a paper fallback, never an assumption", (i) => flag(i, "disable_paper_fallback"), "the paper fallback always exists")] },
  // Courier tracking for the paper note: `op=shipped` (pickup scan with tracking_ref → `custody.paper_note.shipped`, SM_O72_PAPER_NOTE_HANDOFF_1BD) and `op=received` (custodian receipt → `custody.paper_note.received`, 26.4's anchor); the chain shows settlement_agent → courier → custodian.
  { name: "trackPaperNote", kind: "act", handler: compute((i, ctx, rt) => { const c = loadClosing(i, rt); const k = rt.store.get("custody_records", c.closing_id)?.data as unknown as CustodyRecord | undefined; if (!k) throw new RangeError(`no custody_record for closing ${c.closing_id} (seedCustodyRecord first)`); need(i, "tracking_ref");
      const r = trackPaperNote(ctx.events, c, k, { at: at(i, ctx), op: (str(i, "op") as "shipped" | "received") || "shipped", tracking_ref: str(i, "tracking_ref"), ...(typeof i.courier_party_id === "string" ? { courier_party_id: i.courier_party_id } : {}), evidence_document_id: (i.evidence_document_id as string | undefined) ?? null }); put(rt, ctx, "custody_records", c.closing_id, r.custody);
      return { closing_id: c.closing_id, note_location: r.custody.note_location, chain: r.custody.chain, original_received_at: r.custody.original_received_at, handoff_due: r.custody.handoff_due, on_time: (r.event.payload as { on_time?: boolean }).on_time ?? null }; }),
    guardrails: [never("PAPER_NEVER_CONVERTED", "A2-4.1-03: paper notes may not be converted into eNotes", (i) => flag(i, "convert_paper_to_enote"), "the paper note ships to the custodian; it is never converted")] },
  // Paper note (wet or hybrid paper note): `custody_records` seeded `note_location=settlement_agent` at signing with the handoff due date (default custodian: the partner's Form 2017 FCC as SM's bailee).
  { name: "seedCustodyRecord", kind: "act", handler: compute((i, ctx, rt) => { const c = loadClosing(i, rt); need(i, "custodian_party_id"); const r = seedCustodyRecord(ctx.events, c, { at: at(i, ctx), custodian_party_id: str(i, "custodian_party_id"), ...(typeof i.settlement_agent_party_id === "string" ? { settlement_agent_party_id: i.settlement_agent_party_id } : {}) }); put(rt, ctx, "custody_records", c.closing_id, r.custody); return { closing_id: c.closing_id, note_form: "paper", note_location: r.custody.note_location, chain: r.custody.chain, handoff_due: r.custody.handoff_due }; }),
    guardrails: [never("PAPER_NEVER_CONVERTED", "A2-4.1-03: paper notes may not be converted into eNotes", (i) => flag(i, "convert_paper_to_enote"), "a custody record is for a paper note that stays paper")] },
  // The agent's decision record per session decision and per registration: {closing_id, session_ids, closing_type, closing_type_reasons, gates_checked, eligibility, identity_results (method/result only), consummation_at, tamper_sealed_at, registration, secured_party, audit_trail_hash, execution_review, recordings, custody_chain, rationale, rule_set_version, model_version, prompt_version, confidence}; `op=delivery` returns the ULDD indicators and the electronic loan file for 29.3 / 30.2.
  { name: "writeDecision", kind: "write", ruleSetVersion: RULE_SET_VERSION_26_2, handler: compute((i, ctx, rt) => {
      if (i.op === "delivery") { const c = loadClosing(i, rt); const ss = rt.store.list("signing_sessions", (d) => d.closing_id === c.closing_id).map((r) => r.data as unknown as SigningSession); const e = (rt.store.list("enotes", (d) => d.closing_id === c.closing_id).at(-1)?.data as unknown as ENote | undefined) ?? null; const recs = rt.store.list("recordings", (d) => d.closing_id === c.closing_id).map((r) => r.data as unknown as Recording); const mers = rt.store.list("mers_transactions", (d) => d.application_id === c.application_id).map((r) => r.data as unknown as import("../../domain/closing/ops-26-2.ts").MersTransaction);
        return { closing_id: c.closing_id, indicators: deliveryIndicators(c, e, ss, recs.find((r) => r.recorded_at) ?? null), loan_file: electronicLoanFile(c, ss, e, mers, recs), notice: NOTICE_CLOSING_APPOINTMENT }; }
      if (i.op === "gate_facts") { const c = loadClosing(i, rt); const s = rt.store.list("signing_sessions", (d) => d.closing_id === c.closing_id).at(-1)?.data as unknown as SigningSession | undefined; const e = rt.store.list("enotes", (d) => d.closing_id === c.closing_id).at(-1)?.data as unknown as ENote | undefined; return closingGateFacts(c, s ?? null, e ?? null, consentOf(i, rt, c), eligibilityRows(i, rt)); }
      const c = typeof i.closing_id === "string" ? (rt.store.get("closings", i.closing_id)?.data as unknown as Closing | undefined) : undefined;
      const record = { closing_id: c?.closing_id ?? str(i, "closing_id") ?? null, session_ids: c?.session_ids ?? [], closing_type: c?.closing_type ?? null, closing_type_reasons: arr<string>(i, "closing_type_reasons"), gates_checked: arr<string>(i, "gates_checked"), eligibility: (i.eligibility as unknown) ?? null, identity_results: arr<{ party_id: string; method: string; result: string }>(i, "identity_results").map((x) => ({ party_id: x.party_id, method: x.method, result: x.result })), consummation_at: c?.consummation_at ?? null, tamper_sealed_at: (i.tamper_sealed_at as string | undefined) ?? null, registration: (i.registration as unknown) ?? null, secured_party: (i.secured_party as unknown) ?? null, audit_trail_hash: (i.audit_trail_hash as string | undefined) ?? null, execution_review: (i.execution_review as unknown) ?? null, recordings: arr(i, "recordings"), custody_chain: arr(i, "custody_chain"), rationale: str(i, "rationale"), rule_set_version: str(i, "rule_set_version") || RULE_SET_VERSION_26_2, model_version: str(i, "model_version") || ctx.run?.modelVersion || "n/a", prompt_version: str(i, "prompt_version") || ctx.run?.promptVersion || "n/a", confidence: typeof i.confidence === "number" ? i.confidence : ctx.run?.confidence ?? null, record_hash: "" };
      const record_hash = sha256(JSON.stringify({ ...record, record_hash: undefined }));
      return decision()({ ...i, agent: "title-closing", action: str(i, "action") || "closer.decision", rationale: record.rationale || `26.2 ${str(i, "action") || "decision"}`, rule_set_version: record.rule_set_version, ...(c ? { subject: { kind: "closing", id: c.closing_id }, application_id: c.application_id } : {}), decision_record: { ...record, record_hash } }, ctx); }),
    guardrails: [never("NO_PII_IN_IDENTITY_RESULTS", "26.2 decision record: identity_results carry no PII beyond method/result", (i) => Array.isArray(i.identity_results) && (i.identity_results as Record<string, unknown>[]).some((x) => "ssn" in x || "dob" in x || "credential_number" in x), "identity results are method/result only")] },
]);
