/**
 * §20.2 process-owned tools — bus tools for 20.2 defined with `defineTools("20.2", <agent>, defs)` from
 * ../tools.ts. Every tool string must be one spec/registry/agents.json names for 20.2; src/app/tools.test.ts refuses
 * the rest. Spread by ./index.ts.
 *
 * The `intake` agent orchestrates campaigns and touches over the deterministic rules in
 * src/domain/leads-pricing/ops-20-2.ts: campaigns (`marketing_campaigns`), creatives (`marketing_creatives`, the MAP
 * archive), touches (`marketing_touches`), scrubs (`dnc_scrubs`), suppressions (`marketing_suppressions`) and the
 * marketing consents (`consents`, 7.4) live in the entity store under those names. The paragraph's longer tool list
 * (`sendSms`/`sendEmail`/`queueMail`, `recordResponse`, `recordSuppression`, `writeDecision`) is implemented as `op`
 * switches of the seven registered names. Guardrails encode the spec's sentences: never dial a number without a
 * passing gate record; never use an artificial voice without PEWC; never state "pre-approved," "guaranteed," or a
 * rate not on the current sheet; never reference investors; never pressure; the partner `officer` approves creatives
 * and campaigns and alone pauses/ends them; human click-to-dial is a human act of the `mlo_of_record` team.
 */
import { defineTools, compute, never, needsRole, humanWhen, str, flag, PortUnavailable, type ToolDef, type ToolInput, type ToolRuntime } from "../tools.ts";
import type { CommandContext } from "../commands.ts";
import { plainDate as D, type PlainDate } from "../../kernel/calendar/date.ts";
import type { Recipient } from "../../notices/channel.ts";
import { type Campaign, type Creative, type Touch, type TouchFacts, type TouchInput, type Channel, type CampaignKind, type MarketingConsent, type DncScrub, type Suppression, type PlanInput, type VoiceScript, type SignatureKind, type SuppressionKind,
  FORBIDDEN_VARIABLE_RE, REFI_OFFER_TEMPLATE, AI_VOICE_IDENT_TEMPLATE, RULE_SET_VERSION_20_2, checkGates, assertGateOpen, runContentChecklist, checklistFailures, renderCreative, validateVariablesSchema, noInvestorReference, ratesNotOnSheet, marketingContentPresent,
  createCampaign, approveCampaign, approveCreative, launchCampaign, pauseCampaign, endCampaign, supersedeCreative, verifyMapArchive, isRefusal, planChannels, scheduleTouch, sendTouch, placeCall, recordResponse, recordSuppression, receiveSmsStop, captureMarketingConsent, confirmInterimConsent, expireInterimConsent, completeDncScrub, expireSuppression, quietHoursCheck } from "../../domain/leads-pricing/ops-20-2.ts";

/** Missing-input guard: a tool executed without its subject refuses with a RangeError (never a TypeError). */
const need = (i: Record<string, unknown>, ...keys: string[]): void => { const gaps = keys.filter((k) => i[k] === undefined || i[k] === null || i[k] === ""); if (gaps.length) throw new RangeError(`20.2 tool needs ${gaps.join(", ")}`); };
const obj = (i: ToolInput, k: string): Record<string, unknown> => { const v = i[k]; if (!v || typeof v !== "object" || Array.isArray(v)) throw new RangeError(`20.2 tool needs ${k} (an object)`); return v as Record<string, unknown>; };
const at = (i: ToolInput, ctx: CommandContext, key = "at"): string => str(i, key) || ctx.now;
const arr = <T>(v: unknown): T[] => (Array.isArray(v) ? (v as T[]) : []);
const rows = <T>(rt: ToolRuntime, kind: string): T[] => rt.store.list(kind).map((r) => r.data as unknown as T);
const put = <T extends object>(rt: ToolRuntime, ctx: CommandContext, kind: string, id: string, v: T): T => rt.store.put(kind, id, v as unknown as Record<string, unknown>, ctx.actor, ctx.now).data as unknown as T;
const load = <T>(rt: ToolRuntime, kind: string, id: string): T => { const r = rt.store.get(kind, id); if (!r) throw new RangeError(`no ${kind} ${id} in the entity store`); return r.data as unknown as T; };
/** The touch facts from the tool input: the touch itself is validated; the evidence lists default to the store's rows for the party. */
function toTouchFacts(rt: ToolRuntime, raw: Record<string, unknown>): TouchFacts {
  const t = raw.touch; if (!t || typeof t !== "object") throw new RangeError("20.2 facts need touch {touch_id, campaign_id, campaign_kind, creative_id, channel, party_id, destination, queued_at, time_zones}");
  const touch = t as Record<string, unknown>;
  need(touch, "touch_id", "campaign_id", "campaign_kind", "creative_id", "channel", "party_id", "destination", "queued_at");
  need(raw, "partner_name");
  const party = String(touch.party_id);
  const ti: TouchInput = { touch_id: String(touch.touch_id), campaign_id: String(touch.campaign_id), campaign_kind: String(touch.campaign_kind) as CampaignKind, creative_id: String(touch.creative_id), channel: String(touch.channel) as Channel, party_id: party,
    loan_id: (touch.loan_id as string | null | undefined) ?? null, lead_id: (touch.lead_id as string | null | undefined) ?? null, opportunity_id: (touch.opportunity_id as string | null | undefined) ?? null, destination: String(touch.destination), destination_id: (touch.destination_id as string | null | undefined) ?? null,
    line_type: (touch.line_type as TouchInput["line_type"] | undefined) ?? null, queued_at: String(touch.queued_at), time_zones: arr<string>(touch.time_zones), state: (touch.state as string | null | undefined) ?? null };
  const creative = (raw.creative as Creative | null | undefined) ?? rt.store.get("marketing_creatives", ti.creative_id)?.data as unknown as Creative | undefined ?? null;
  return { touch: ti, partner_name: String(raw.partner_name),
    consents: raw.consents !== undefined ? arr<MarketingConsent>(raw.consents) : rows<MarketingConsent>(rt, "consents").filter((c) => c.party_id === party),
    scrubs: raw.scrubs !== undefined ? arr<DncScrub>(raw.scrubs) : rows<DncScrub>(rt, "dnc_scrubs"),
    suppressions: raw.suppressions !== undefined ? arr<Suppression>(raw.suppressions) : rows<Suppression>(rt, "marketing_suppressions").filter((s) => s.party_id === party),
    on_national_registry: raw.on_national_registry === true, ebr: (raw.ebr as TouchFacts["ebr"]) ?? null, creative, rendered_text: (raw.rendered_text as string | null | undefined) ?? creative?.rendered_text ?? null,
    ...(typeof raw.rate_sheet_current === "boolean" ? { rate_sheet_current: raw.rate_sheet_current } : {}), flags: (raw.flags as TouchFacts["flags"]) ?? { prescreen_enabled: false }, prescreen: (raw.prescreen as TouchFacts["prescreen"]) ?? null,
    ...(typeof raw.partner_licensed_in_state === "boolean" ? { partner_licensed_in_state: raw.partner_licensed_in_state } : {}), state_quiet_window: (raw.state_quiet_window as TouchFacts["state_quiet_window"]) ?? null, state_rules_applied: arr<string>(raw.state_rules_applied), history: (raw.history as TouchFacts["history"]) ?? null };
}
const textOf = (i: ToolInput): string => String(i.text ?? i.template ?? i.opening_text ?? (i.script as { opening_text?: unknown } | undefined)?.opening_text ?? "");
const schemaOf = (i: ToolInput): string[] => arr<string>(i.variables_schema);
const saysPreapprovedOrGuaranteed = (i: ToolInput): boolean => /\bpre-?approved\b|\bpreapproval\b|\bguarantee[ds]?\b/i.test(textOf(i));
const referencesInvestor = (i: ToolInput): boolean => textOf(i) !== "" && !noInvestorReference(textOf(i));
const pressures = (i: ToolInput): boolean => /\blimited[- ]time\b|\bact now\b|\btoday only\b|\blast chance\b/i.test(textOf(i)) && i.sheet_validity_stated !== true;
const offSheetRate = (i: ToolInput): boolean => Array.isArray(i.sheet_rates_pct) && ratesNotOnSheet(textOf(i), i.sheet_rates_pct as string[]).length > 0;
const OFFICER = ["officer"];

export const TOOLS_20_2: readonly ToolDef[] = defineTools("20.2", "intake", [
  // Rule 1 / worked example 1: the channel plan for an offer_ready opportunity (or organic lead) — every channel gated, the human click-to-dial alternative at 10:30 local when AI voice lacks PEWC; campaign lifecycle ops for the partner `officer`.
  { name: "planChannels", kind: "act", handler: compute((i, ctx, rt) => { const op = str(i, "op") || "plan"; const when = at(i, ctx);
      if (op === "create_campaign") { need(i, "campaign_id", "partner_id", "kind", "channels", "selection_rule_set"); const c = createCampaign({ campaign_id: str(i, "campaign_id"), partner_id: str(i, "partner_id"), program_id: (i.program_id as string | null | undefined) ?? null, kind: str(i, "kind") as CampaignKind, channels: arr<Channel>(i.channels), selection_rule_set: str(i, "selection_rule_set"), creative_ids: arr<string>(i.creative_ids) }); return put(rt, ctx, "marketing_campaigns", c.campaign_id, c); }
      if (op === "approve_campaign") { need(i, "campaign_id"); const c = load<Campaign>(rt, "marketing_campaigns", str(i, "campaign_id")); const creatives = rows<Creative>(rt, "marketing_creatives"); const r = approveCampaign(ctx.events, c, { approved_by: `${ctx.actor.kind}:${ctx.actor.id}`, at: when, creatives, flags: (i.flags as { prescreen_enabled?: boolean } | undefined) ?? (rt.store.get("feature_flags", "marketing.prescreen_enabled")?.data.value === true ? { prescreen_enabled: true } : { prescreen_enabled: false }) }, ctx.actor); if (isRefusal(r)) return { campaign_id: c.campaign_id, status: c.status, refused: true, reason: r.reason, detail: r.detail ?? null }; return put(rt, ctx, "marketing_campaigns", c.campaign_id, r); }
      if (op === "launch" || op === "pause" || op === "end") { need(i, "campaign_id"); const c = load<Campaign>(rt, "marketing_campaigns", str(i, "campaign_id")); const r = op === "launch" ? launchCampaign(ctx.events, c, when, ctx.actor) : op === "pause" ? pauseCampaign(ctx.events, c, when, ctx.actor) : (need(i, "last_disseminated_on"), endCampaign(ctx.events, c, { at: when, last_disseminated_on: D(str(i, "last_disseminated_on")) }, ctx.actor)); return put(rt, ctx, "marketing_campaigns", c.campaign_id, r); }
      if (op === "verify_archive") { need(i, "creative_id", "archive", "archive_until"); const c = load<Creative>(rt, "marketing_creatives", str(i, "creative_id")); const a = obj(i, "archive"); const r = verifyMapArchive(ctx.events, c, { rendered_variants: arr(a.rendered_variants), prompt_version: (a.prompt_version as string | null | undefined) ?? null, product_list: arr<string>(a.product_list), retained_through: D(String(a.retained_through ?? "")) }, { archive_until: D(str(i, "archive_until")), at: when }, ctx.actor); return { creative_id: c.creative_id, complete: r.complete, missing: r.missing, event_id: r.event.id }; }
      need(i, "campaign_id", "party_id", "destinations", "facts");
      const campaign = (i.campaign as Campaign | undefined) ?? load<Campaign>(rt, "marketing_campaigns", str(i, "campaign_id"));
      const creatives = arr<Creative>(i.creatives).length ? arr<Creative>(i.creatives) : rows<Creative>(rt, "marketing_creatives").filter((c) => c.campaign_id === campaign.campaign_id);
      const facts = obj(i, "facts"); need(facts, "partner_name");
      const party = str(i, "party_id");
      const p: PlanInput = { campaign, creatives, party_id: party, loan_id: (i.loan_id as string | null | undefined) ?? null, lead_id: (i.lead_id as string | null | undefined) ?? null, opportunity_id: (i.opportunity_id as string | null | undefined) ?? null, at: when, time_zones: arr<string>(i.time_zones), state: (i.state as string | null | undefined) ?? null, destinations: obj(i, "destinations") as PlanInput["destinations"],
        facts: { partner_name: String(facts.partner_name), consents: facts.consents !== undefined ? arr<MarketingConsent>(facts.consents) : rows<MarketingConsent>(rt, "consents").filter((c) => c.party_id === party), scrubs: facts.scrubs !== undefined ? arr<DncScrub>(facts.scrubs) : rows<DncScrub>(rt, "dnc_scrubs"), suppressions: facts.suppressions !== undefined ? arr<Suppression>(facts.suppressions) : rows<Suppression>(rt, "marketing_suppressions").filter((s) => s.party_id === party),
          on_national_registry: facts.on_national_registry === true, ebr: (facts.ebr as TouchFacts["ebr"]) ?? null, ...(typeof facts.rate_sheet_current === "boolean" ? { rate_sheet_current: facts.rate_sheet_current } : {}), flags: (facts.flags as TouchFacts["flags"]) ?? { prescreen_enabled: false }, prescreen: (facts.prescreen as TouchFacts["prescreen"]) ?? null, ...(typeof facts.partner_licensed_in_state === "boolean" ? { partner_licensed_in_state: facts.partner_licensed_in_state } : {}), state_quiet_window: (facts.state_quiet_window as TouchFacts["state_quiet_window"]) ?? null, state_rules_applied: arr<string>(facts.state_rules_applied), history: (facts.history as TouchFacts["history"]) ?? null },
        ...(str(i, "touch_id_prefix") ? { touch_id_prefix: str(i, "touch_id_prefix") } : {}) };
      const plan = planChannels(ctx.events, p, ctx.actor);
      return { opportunity_id: plan.opportunity_id, party_id: plan.party_id, plan_on: plan.plan_on, ebr: plan.ebr, entries: plan.entries.map((e) => ({ channel: e.channel, permitted: e.permitted, reason: e.reason, scheduled_for: e.scheduled_for, local: e.local, alternative_for: e.alternative_for ?? null, gates: e.check.gates.map((g) => ({ code: g.code, result: g.result })), legal_basis: e.check.legal_basis })), touches: plan.touches }; }),
    guardrails: [needsRole("CAMPAIGN_APPROVAL_IS_OFFICER", "20.2 automation class (b): creatives and the objective selection rule need partner compliance approval (partner `officer` or delegated compliance reviewer)", (i) => str(i, "op") === "approve_campaign", OFFICER, "campaign approval is the partner officer's act"),
      needsRole("PAUSE_END_IS_HUMAN", "20.2 state machine: humans can only `pause`/`end` campaigns and approve creatives", (i) => str(i, "op") === "pause" || str(i, "op") === "end", OFFICER, "pausing or ending a campaign is the partner officer's act"),
      never("NO_PRESCREEN_WHILE_FLAG_OFF", "20.2 rule 9: prescreening disabled by default (`marketing.prescreen_enabled=false`); no consumer-report adapter is wired to campaigns", (i) => str(i, "op") === "create_campaign" && str(i, "kind") === "prescreen" && i.prescreen_list !== undefined, "a prescreen list cannot be attached to a campaign; the flag gates approval (T11)")] },
  // Timers table: every gate for one queued touch with its legal basis (consent id + disclosure hash, EBR basis, scrub id, local time/tz, creative hash, checklist results).
  { name: "checkGates", kind: "read", handler: compute((i, _ctx, rt) => { need(i, "facts"); const c = checkGates(toTouchFacts(rt, obj(i, "facts"))); return { touch_id: c.touch_id, channel: c.channel, pass: c.pass, suppression_reason: c.suppression_reason, reschedule_to: c.reschedule_to, gates: c.gates, legal_basis: c.legal_basis, ebr: c.ebr, quiet_hours: { permitted: c.quiet_hours.permitted, reason: c.quiet_hours.reason, window: c.quiet_hours.window, checks: c.quiet_hours.checks } }; }) },
  // `assertGateOpen`: the named gate must read pass (or not applicable) for the touch; a closed gate is a typed refusal naming the basis.
  { name: "assertGateOpen", kind: "read", handler: compute((i, _ctx, rt) => { need(i, "code"); if (str(i, "code") === "TCPA_64_1200_C1_QUIET_HOURS_GATE" && i.at !== undefined && i.facts === undefined) { const q = quietHoursCheck({ at: str(i, "at"), time_zones: arr<string>(i.time_zones), channel: (str(i, "channel") as Channel) || "ai_voice", state_window: (i.state_window as { open: string; close: string } | null | undefined) ?? null }); if (!q.permitted) throw new RangeError(`GATE_CLOSED TCPA_64_1200_C1_QUIET_HOURS_GATE: ${q.reason}; reschedule to ${q.reschedule_to?.date} ${q.reschedule_to?.local_time} ${q.reschedule_to?.tz}`); return { code: str(i, "code"), result: "pass", basis: { window: q.window, checks: q.checks } }; }
      need(i, "facts"); const c = checkGates(toTouchFacts(rt, obj(i, "facts"))); const g = assertGateOpen(c, str(i, "code")); return { code: g.code, result: g.result, basis: g.basis, touch_id: c.touch_id }; }) },
  // Rule 4, 7 / T7, T8: approved templates only, the variable schema enforced (no investor variable), the rendered variant hashed for the MAP archive; `approve` is the partner officer's act; `supersede` anchors the 24-month retention.
  { name: "renderCreative", kind: "act", handler: compute((i, ctx, rt) => { const op = str(i, "op") || "render"; const when = at(i, ctx);
      if (op === "approve") { need(i, "creative_id", "campaign_kind"); const c = load<Creative>(rt, "marketing_creatives", str(i, "creative_id")); const r = approveCreative(ctx.events, c, { approved_by: `${ctx.actor.kind}:${ctx.actor.id}`, at: when, campaign_kind: str(i, "campaign_kind") as CampaignKind, checklist_input: { ...(i.amortization ? { amortization: str(i, "amortization") as "fixed" | "arm" } : {}), sheet_rates_pct: (i.sheet_rates_pct as string[] | null | undefined) ?? null, sheet_validity_stated: flag(i, "sheet_validity_stated"), state: (i.state as string | null | undefined) ?? null, state_text: (i.state_text as string | null | undefined) ?? null, other_lender_names: arr<string>(i.other_lender_names), optout_offer_seconds: (i.optout_offer_seconds as number | null | undefined) ?? null } }, ctx.actor); put(rt, ctx, "marketing_creatives", c.creative_id, c); if (isRefusal(r)) return { creative_id: c.creative_id, status: c.status, refused: true, reason: r.reason, detail: r.detail ?? null, checklists: c.checklists }; return { creative_id: c.creative_id, status: r.status, approved_by: r.approved_by, approved_at: r.approved_at, content_hash: r.content_hash, checklists: r.checklists }; }
      if (op === "supersede") { need(i, "creative_id", "superseded_by", "last_disseminated_on"); const c = load<Creative>(rt, "marketing_creatives", str(i, "creative_id")); const r = supersedeCreative(ctx.events, c, { superseded_by: str(i, "superseded_by"), at: when, last_disseminated_on: D(str(i, "last_disseminated_on")) }, ctx.actor); put(rt, ctx, "marketing_creatives", c.creative_id, r.creative); return { creative_id: c.creative_id, status: r.creative.status, archive_until: r.archive_until, event_id: r.event.id }; }
      need(i, "template", "variables", "variables_schema");
      const r = renderCreative(str(i, "template"), obj(i, "variables"), schemaOf(i));
      if (str(i, "creative_id")) { const existing = rt.store.get("marketing_creatives", str(i, "creative_id"))?.data as unknown as Creative | undefined;
        const c: Creative = existing ? { ...existing, rendered_text: r.text, content_hash: r.content_hash, status: existing.status === "approved" && existing.content_hash !== r.content_hash ? "draft" : existing.status } : { creative_id: str(i, "creative_id"), campaign_id: str(i, "campaign_id"), channel: (str(i, "channel") as Channel) || "email", template_code: str(i, "template_code") || REFI_OFFER_TEMPLATE, template_version: str(i, "template_version") || "1.0.0", content_hash: r.content_hash, rate_sheet_id: (i.rate_sheet_id as string | null | undefined) ?? null, variables_schema: schemaOf(i), checklists: null, status: "draft", approved_by: null, approved_at: null, superseded_by: null, prompt_version: (i.prompt_version as string | null | undefined) ?? null, disseminated_from: null, disseminated_to: null, rendered_text: r.text };
        put(rt, ctx, "marketing_creatives", c.creative_id, c); }
      return { text: r.text, content_hash: r.content_hash, variables_used: r.variables_used, no_investor_reference: r.no_investor_reference }; }),
    guardrails: [never("NEVER_REFERENCE_INVESTORS", "20.2 rule 7 / B2-1.3-04: creatives cannot merge any investor field; the template variable schema has no such variable", (i) => (str(i, "op") || "render") === "render" && !validateVariablesSchema(schemaOf(i)).ok, "the variables schema names an investor field (investor_name / pool / MBS); B2-1.3-04 investor blindness"),
      never("NEVER_STATE_PREAPPROVED_OR_GUARANTEED", "20.2 guardrails: never state \"pre-approved,\" \"guaranteed\" (MAP (q)/(r))", saysPreapprovedOrGuaranteed, "the template says pre-approved / guaranteed"),
      never("NEVER_PRESSURE", "20.2 guardrails: never pressure (\"limited time\" only when true and stated in the sheet's validity terms)", pressures, "\"limited time\" language without the sheet's validity terms"),
      needsRole("CREATIVE_APPROVAL_IS_OFFICER", "20.2 state machine: humans can only pause/end campaigns and approve creatives — partner `officer` or delegated compliance reviewer (SLA 3 BD)", (i) => str(i, "op") === "approve", OFFICER, "creative approval is the partner officer's act")] },
  // Rule 4 / T7: the Reg Z §1026.24, MAP, state, B2-1.3-04, TCPA (b) and CAN-SPAM checklists over a creative's text — a pure computation.
  { name: "runContentChecklist", kind: "read", handler: compute((i) => { need(i, "text", "channel", "campaign_kind"); const c = runContentChecklist({ text: str(i, "text"), channel: str(i, "channel") as Channel, campaign_kind: str(i, "campaign_kind") as CampaignKind, ...(i.amortization ? { amortization: str(i, "amortization") as "fixed" | "arm" } : {}), sheet_rates_pct: (i.sheet_rates_pct as string[] | null | undefined) ?? null, sheet_validity_stated: flag(i, "sheet_validity_stated"), state: (i.state as string | null | undefined) ?? null, state_text: (i.state_text as string | null | undefined) ?? null, other_lender_names: arr<string>(i.other_lender_names), optout_offer_seconds: (i.optout_offer_seconds as number | null | undefined) ?? null }); const failures = checklistFailures(c); return { checklists: c, failures, pass: failures.length === 0, can_approve: failures.length === 0 }; }) },
  // State machine: queued → suppressed | scheduled → sent; plus the paragraph's `sendEmail`/`sendSms`/`queueMail`, `recordResponse`, `recordSuppression`, the STOP keyword, consent capture and the scrub job as ops.
  { name: "scheduleTouch", kind: "act", handler: compute(async (i, ctx, rt) => { const op = str(i, "op") || "schedule"; const when = at(i, ctx);
      if (op === "send") { need(i, "touch_id"); const t = load<Touch>(rt, "marketing_touches", str(i, "touch_id"));
        if (t.channel === "ai_voice" || t.channel === "human_voice") throw new RangeError(`touch ${t.touch_id} is a voice touch; use placeCall`);
        let notice_id: string | null = null; let content_hash: string | null = (i.content_hash as string | null | undefined) ?? null;
        if (t.channel === "email" || t.channel === "mail" || t.channel === "portal") { const svc = rt.notices; if (!svc) throw new PortUnavailable("notices"); need(i, "payload", "recipient");
          const rc = obj(i, "recipient"); const recipient: Recipient = { partyId: t.party_id, name: String(rc.name ?? ""), mailingAddress: (rc.mailing_address as string | null | undefined) ?? null, ...(typeof rc.email === "string" ? { email: rc.email } : {}), ...(t.channel === "portal" ? { portalUser: true } : {}) };
          const n = svc.render({ templateCode: str(i, "template_code") || REFI_OFFER_TEMPLATE, ...(t.loan_id ? { loanId: t.loan_id } : {}), recipients: [recipient], payload: obj(i, "payload"), asOf: D(when.slice(0, 10)) });
          const sent = await svc.send(n.id, { ...(t.channel === "mail" ? { stateMandatedMail: true } : {}), ...(t.channel === "portal" ? { preferPortal: true } : {}) }); notice_id = sent.id; content_hash = sent.payloadHash; }
        else { need(i, "text"); if (marketingContentPresent(str(i, "text")) && !noInvestorReference(str(i, "text"))) throw new RangeError("SMS text references an investor"); content_hash = content_hash ?? null; }
        const r = sendTouch(ctx.events, t, { sent_at: when, notice_id, content_hash }, ctx.actor); put(rt, ctx, "marketing_touches", t.touch_id, r.touch); return { touch_id: t.touch_id, outcome: r.touch.outcome, sent_at: r.touch.sent_at, notice_id, content_hash, event_id: r.event.id }; }
      if (op === "record_response") { need(i, "touch_id", "campaign_id", "party_id", "kind", "channel"); const r = recordResponse(ctx.events, { touch_id: str(i, "touch_id"), campaign_id: str(i, "campaign_id"), party_id: str(i, "party_id"), loan_id: (i.loan_id as string | null | undefined) ?? ctx.loanId ?? null, opportunity_id: (i.opportunity_id as string | null | undefined) ?? null, kind: str(i, "kind") as Parameters<typeof recordResponse>[1]["kind"], channel: str(i, "channel") as Channel, received_at: when, consent_ids: arr<string>(i.consent_ids), text: (i.text as string | null | undefined) ?? null, ...(str(i, "time_zone") ? { time_zone: str(i, "time_zone") } : {}) }, ctx.actor); return { received_on: r.received_on, inquiry: r.inquiry, ebr: r.ebr, lead_created_by: "20.3", event_ids: r.events.map((e) => e.id) }; }
      if (op === "record_suppression") { need(i, "suppression_id", "kind", "party_id", "channel_received"); const r = recordSuppression(ctx.events, { suppression_id: str(i, "suppression_id"), kind: str(i, "kind") as SuppressionKind, party_id: str(i, "party_id"), loan_id: (i.loan_id as string | null | undefined) ?? ctx.loanId ?? null, phone_number_id: (i.phone_number_id as string | null | undefined) ?? null, email_id: (i.email_id as string | null | undefined) ?? null, address_id: (i.address_id as string | null | undefined) ?? null, requested_at: str(i, "requested_at") || when, channel_received: str(i, "channel_received"), source_touch_id: (i.source_touch_id as string | null | undefined) ?? null, processed_at: when, ...(str(i, "time_zone") ? { time_zone: str(i, "time_zone") } : {}) }, ctx.actor); put(rt, ctx, "marketing_suppressions", r.suppression.suppression_id, r.suppression); return { ...r.suppression, event_ids: r.events.map((e) => e.id) }; }
      if (op === "expire_suppression") { need(i, "suppression_id"); const s = load<Suppression>(rt, "marketing_suppressions", str(i, "suppression_id")); const r = expireSuppression(ctx.events, s, when, ctx.actor); return { suppression_id: s.suppression_id, expired: r.expired, honor_until: s.honor_until }; }
      if (op === "receive_sms") { need(i, "loan_id", "phone_number_id", "party_id", "text", "suppression_id"); const r = receiveSmsStop(ctx.events, { loan_id: str(i, "loan_id"), phone_number_id: str(i, "phone_number_id"), party_id: str(i, "party_id"), text: str(i, "text"), received_at: str(i, "received_at") || when, suppression_id: str(i, "suppression_id"), source_touch_id: (i.source_touch_id as string | null | undefined) ?? null }, ctx.actor); if (r.suppression) put(rt, ctx, "marketing_suppressions", r.suppression.suppression_id, r.suppression); for (const c of rows<MarketingConsent>(rt, "consents")) if (r.ingestion.revoked && c.kind === "tcpa_sms" && c.party_id === str(i, "party_id")) put(rt, ctx, "consents", c.consent_id, { ...c, status: "withdrawn" }); return { revoked: r.ingestion.revoked, keyword: r.ingestion.keyword, committed_by: r.ingestion.committed_by, confirmation: r.ingestion.confirmation, confirmation_text: r.confirmation_text, confirmation_marketing_free: r.confirmation_marketing_free, suppression_id: r.suppression?.suppression_id ?? null, event_ids: r.events.map((e) => e.id) }; }
      if (op === "capture_consent") { need(i, "consent_id", "party_id", "kinds", "phone_number", "partner_name", "signature_kind", "disclosure_version", "disclosure_text", "elements"); const e = obj(i, "elements"); const r = captureMarketingConsent(ctx.events, { consent_id: str(i, "consent_id"), party_id: str(i, "party_id"), loan_id: (i.loan_id as string | null | undefined) ?? ctx.loanId ?? null, kinds: arr<"tcpa_voice" | "tcpa_sms">(i.kinds), phone_number: str(i, "phone_number"), partner_name: str(i, "partner_name"), signature_kind: str(i, "signature_kind") as SignatureKind, captured_at: str(i, "captured_at") || when, disclosure_version: str(i, "disclosure_version"), disclosure_text: str(i, "disclosure_text"), elements: { authorizes_atds_or_artificial_voice: e.authorizes_atds_or_artificial_voice === true, not_condition_of_purchase: e.not_condition_of_purchase === true }, national_dnc_written_permission: flag(i, "national_dnc_written_permission"), evidence: (i.evidence as Record<string, unknown> | undefined) ?? {} }, ctx.actor); for (const c of r.consents) put(rt, ctx, "consents", c.consent_id, c); return { consents: r.consents, event_ids: r.events.map((e2) => e2.id) }; }
      if (op === "confirm_consent" || op === "expire_consent") { need(i, "consent_id"); const c = load<MarketingConsent>(rt, "consents", str(i, "consent_id")); const r = op === "confirm_consent" ? (need(i, "signature_kind"), confirmInterimConsent(ctx.events, c, { confirmed_at: when, signature_kind: str(i, "signature_kind") as Exclude<SignatureKind, "voice_recording_interim"> }, ctx.actor)) : expireInterimConsent(ctx.events, c, when, ctx.actor); put(rt, ctx, "consents", c.consent_id, r.consent); return { consent_id: c.consent_id, status: r.consent.status, written_consent: r.consent.written_consent }; }
      if (op === "complete_scrub") { need(i, "scrub_id", "file_hash"); const r = completeDncScrub(ctx.events, { scrub_id: str(i, "scrub_id"), source: (str(i, "source") as DncScrub["source"]) || "ftc_registry", obtained_at: str(i, "obtained_at") || when, numbers_checked: Number(i.numbers_checked ?? 0), hits: Number(i.hits ?? 0), file_hash: str(i, "file_hash"), ...(str(i, "time_zone") ? { time_zone: str(i, "time_zone") } : {}) }, ctx.actor); put(rt, ctx, "dnc_scrubs", r.scrub.scrub_id, r.scrub); return { ...r.scrub, event_id: r.event.id }; }
      need(i, "facts"); const facts = toTouchFacts(rt, obj(i, "facts"));
      const r = scheduleTouch(ctx.events, facts, { ...(str(i, "scheduled_for") ? { scheduled_for: str(i, "scheduled_for") } : {}), agent_decision_id: (i.agent_decision_id as string | null | undefined) ?? null }, ctx.actor);
      put(rt, ctx, "marketing_touches", r.touch.touch_id, r.touch);
      return { touch_id: r.touch.touch_id, channel: r.touch.channel, outcome: r.touch.outcome, suppression_reason: r.touch.suppression_reason, scheduled_for: r.touch.scheduled_for, scheduled_local: r.touch.scheduled_local, gates: r.check.gates.map((g) => ({ code: g.code, result: g.result, basis: g.basis })), legal_basis: r.check.legal_basis, event_ids: r.events.map((e) => e.id) }; }),
    guardrails: [never("NEVER_STATE_PREAPPROVED_OR_GUARANTEED", "20.2 guardrails: never state \"pre-approved,\" \"guaranteed\"", saysPreapprovedOrGuaranteed, "outbound text says pre-approved / guaranteed"),
      never("NEVER_REFERENCE_INVESTORS", "20.2 guardrails / B2-1.3-04: never reference investors", referencesInvestor, "outbound text references an investor"),
      never("NEVER_A_RATE_OFF_THE_SHEET", "20.2 guardrails: never state a rate not on the current sheet", offSheetRate, "the text states a rate that is not on the current rate sheet"),
      never("NEVER_PRESSURE", "20.2 guardrails: never pressure (\"limited time\" only when true and stated in the sheet's validity terms)", pressures, "\"limited time\" language without the sheet's validity terms"),
      never("NO_MARKETING_IN_STOP_CONFIRMATION", "47 CFR 64.1200(a)(12) / T5: exactly one confirmation text with no marketing content", (i) => str(i, "op") === "send_confirmation" && marketingContentPresent(str(i, "text")), "the revocation confirmation text carries marketing content")] },
  // §64.1200(b) / TSR §310.4(d) / T2: AI voice only under a passing gate record with PEWC — the (b) identification first, the opt-out within 2 s, automation disclosed; human click-to-dial is the `mlo_of_record` team's act.
  { name: "placeCall", kind: "act", handler: compute((i, ctx, rt) => { need(i, "touch_id", "channel", "script"); const t = load<Touch>(rt, "marketing_touches", str(i, "touch_id"));
      if (t.channel !== str(i, "channel")) throw new RangeError(`touch ${t.touch_id} is ${t.channel}, not ${str(i, "channel")}`);
      const s = obj(i, "script"); need(s, "opening_text", "callback_number");
      const script: VoiceScript = { opening_text: String(s.opening_text), ident_at_s: Number(s.ident_at_s ?? 0), optout_offer_at_s: Number(s.optout_offer_at_s ?? Number.POSITIVE_INFINITY), callback_number: String(s.callback_number), prompt_version: (s.prompt_version as string | null | undefined) ?? null, ai_disclosure_first: s.ai_disclosure_first === true };
      const r = placeCall(ctx.events, t, script, { placed_at: at(i, ctx, "placed_at"), ...(str(i, "outcome") ? { outcome: str(i, "outcome") as "answered_ai" | "answered_human" | "voicemail_no_message" | "bounced" } : {}), call_recording_id: (i.call_recording_id as string | null | undefined) ?? null, transcript_id: (i.transcript_id as string | null | undefined) ?? null }, ctx.actor);
      put(rt, ctx, "marketing_touches", t.touch_id, r.touch); const contact = put(rt, ctx, "contacts", `contact:${t.touch_id}`, r.contact);
      return { touch_id: t.touch_id, mode: r.mode, outcome: r.touch.outcome, ident_played_first: r.ident_played_first, optout_offered_within_s: r.optout_offered_within_s, ident_template: AI_VOICE_IDENT_TEMPLATE, tsr_310_4d: r.tsr_310_4d, contact, event_id: r.event.id }; }),
    guardrails: [never("NO_DIAL_WITHOUT_GATE_RECORD", "20.2 guardrails: never dial a number without a passing gate record", (i) => i.gate_record !== undefined && (i.gate_record as { pass?: unknown }).pass !== true, "the gate record passed in does not read pass; placeCall also refuses a touch whose stored gates are not all pass"),
      never("NO_ARTIFICIAL_VOICE_WITHOUT_PEWC", "20.2 guardrails / 47 CFR 64.1200(a)(2)-(3): never use an artificial voice without PEWC", (i) => str(i, "channel") === "ai_voice" && i.pewc_consent_id !== undefined && !i.pewc_consent_id, "an AI-voice call needs the PEWC consent id on its legal basis"),
      never("VOICE_MODEL_NEVER_CLAIMS_TO_BE_A_PERSON", "20.2 edge cases: voice-model says \"I am a person\" — prohibited output (prompt guard + post-call transcript scan)", (i) => /\bI am a (?:person|human)\b|\bI'm a real person\b/i.test(textOf(i)), "the script claims to be a person; escalate to officer and move the number to human-only"),
      humanWhen("HUMAN_CLICK_TO_DIAL", "20.2 open question 2: human click-to-dial marketing calls by partner-employed/sponsored staff under the `mlo_of_record` team (no ATDS, no artificial voice)", (i) => str(i, "channel") === "human_voice", "a human_voice touch is dialed by the mlo_of_record team, never by the agent")],
    ruleSetVersion: RULE_SET_VERSION_20_2 },
]);
