/**
 * §20.1 process-owned tools — bus tools for 20.1 defined with `defineTools("20.1", <agent>, defs)` from
 * ../tools.ts. Every tool string must be one spec/registry/agents.json names for 20.1; src/app/tools.test.ts refuses
 * the rest. Spread by ./index.ts.
 *
 * The `intake` agent runs the deterministic pipeline of src/domain/leads-pricing/ops-20-1.ts over the entity store:
 * `partner_programs` (economics), `refi_universe` (rows of the investor-blind view `v_refi_universe` — the SERVICING
 * portfolio, never a copy), `refi_gate_facts` (29.4's purchase date, the last decline, the offer history — read by the
 * gates only), `refi_opportunities`, `refi_trigger_runs`, `fair_lending_extracts`, `jurisdiction_rules`, and 20.4's
 * `rate_sheets` / `llpa_tables` / `sm_cost_schedules` / `fee_schedules` for pricing. Guardrails encode the spec's
 * sentences: cannot read investor fields (enforced by the view and refused on input), cannot pull credit, cannot
 * contact the borrower (20.2/20.3 do), cannot override a suppression (partner `officer` only, never for a Fannie
 * Mae-ownership reason), cannot construct a cash-out candidate without a borrower request; the `officer` approves the
 * selection rule set and acknowledges recapture-window requests.
 */
import { defineTools, compute, decision, never, needsRole, cents, str, flag, type ToolDef, type ToolInput, type ToolRuntime } from "../tools.ts";
import type { CommandContext } from "../commands.ts";
import type { Actor } from "../../kernel/events/index.ts";
import { plainDate as D, type PlainDate } from "../../kernel/calendar/date.ts";
import { type RateSheet, type LlpaTable, type SmCostSchedule, type FeeSchedule, type QuoteContext, type TransactionType, activeSheetAt } from "../../domain/leads-pricing/ops-20-4.ts";
import { type PartnerProgram, type RefiRuleSet, type UniverseLoan, type GateFacts, type RefiOpportunity, type FairLendingExtract, type JurisdictionRefiRule, type PipelineContext, type CandidateSchedule, type DemographicCategory, type LoanLookupPort,
  DEFAULT_PROGRAM, SM_REFI_RULE_SET_V1, MA_183_28C, NO_GATE_FACTS, INVESTOR_FIELDS, PROHIBITED_SELECTION_FIELDS, RefiRefused,
  loadUniverse, staticCheckRuleSet, assertGlbaUse, buildCandidate, priceCandidate, computeBenefit, fireRule, borrowerInterestRule, checkGates, assertGateOpen, evaluateLoan, runTrigger, requestOpportunity, markOfferReady, recordOffered, engageOpportunity, convertOpportunity, declineOpportunity, expireOpportunity, overrideSuppression, fnmaOwnershipCheck, assessPremiumRecapture, writeFairLendingExtract, decisionRecord, defaultSchedule, monthsBetween, explainBenefit, benefitDisclosurePayload } from "../../domain/leads-pricing/ops-20-1.ts";

/** Missing-input guard: a tool executed without its subject refuses with a RangeError (never a TypeError). */
const need = (i: ToolInput, ...keys: string[]): void => { const gaps = keys.filter((k) => i[k] === undefined || i[k] === null || i[k] === ""); if (gaps.length) throw new RangeError(`20.1 tool needs ${gaps.join(", ")}`); };
const at = (i: ToolInput, ctx: CommandContext, key = "at"): string => str(i, key) || ctx.now;
const asOf = (i: ToolInput, ctx: CommandContext): PlainDate => D(str(i, "as_of_date") || at(i, ctx).slice(0, 10));
const rec = (v: unknown): Record<string, unknown> => (v && typeof v === "object" && !Array.isArray(v) ? (v as Record<string, unknown>) : {});
const investorKeys = (o: Record<string, unknown>): string[] => Object.keys(o).filter((k) => INVESTOR_FIELDS.includes(k));
const prohibitedKeys = (o: Record<string, unknown>): string[] => Object.keys(o).filter((k) => PROHIBITED_SELECTION_FIELDS.includes(k));
const readsInvestor = (i: ToolInput): boolean => investorKeys(i).length > 0 || investorKeys(rec(i.loan)).length > 0 || investorKeys(rec(i.where)).length > 0 || (Array.isArray(i.columns) && (i.columns as unknown[]).some((c) => INVESTOR_FIELDS.includes(String(c))));
const readsProhibited = (i: ToolInput): boolean => prohibitedKeys(i).length > 0 || prohibitedKeys(rec(i.loan)).length > 0 || prohibitedKeys(rec(i.where)).length > 0;
const pullsCredit = (i: ToolInput): boolean => flag(i, "credit_pull") || flag(i, "consumer_report") || flag(i, "soft_pull") || str(i, "score_source") === "consumer_report" || str(i, "score_source") === "soft_pull";
const contactsBorrower = (i: ToolInput): boolean => flag(i, "send") || flag(i, "contact_borrower") || flag(i, "call") || flag(i, "sms") || flag(i, "email") || str(i, "channel") !== "";
const money = (v: bigint | null | undefined): string | null => (v === null || v === undefined ? null : String(v));

// ---- store readers
const program = (i: ToolInput, rt: ToolRuntime): PartnerProgram => { const id = str(i, "program_id"); const rows = rt.store.list("partner_programs").map((r) => r.data as unknown as PartnerProgram); const p = id ? rows.find((r) => r.program_id === id) : rows[0]; if (!p) throw new RangeError(id ? `no partner program ${id}` : "no partner_programs row (register one with loadUniverse{op=register_program})"); return p; };
const ruleSet = (i: ToolInput, rt: ToolRuntime): RefiRuleSet => { const inline = i.rule_set as RefiRuleSet | undefined; if (inline) return inline; const r = rt.store.get("refi_rule_sets", str(i, "rule_set_version") || SM_REFI_RULE_SET_V1.version); return (r?.data as unknown as RefiRuleSet | undefined) ?? SM_REFI_RULE_SET_V1; };
const universe = (i: ToolInput, rt: ToolRuntime): UniverseLoan[] => (Array.isArray(i.loans) ? (i.loans as UniverseLoan[]) : rt.store.list("refi_universe").map((r) => r.data as unknown as UniverseLoan));
const loanRow = (i: ToolInput, rt: ToolRuntime): UniverseLoan => { if (i.loan && typeof i.loan === "object") return i.loan as UniverseLoan; need(i, "loan_id"); const r = rt.store.get("refi_universe", str(i, "loan_id")); if (!r) throw new RangeError(`no v_refi_universe row for loan ${str(i, "loan_id")}`); return r.data as unknown as UniverseLoan; };
const gateFacts = (rt: ToolRuntime, loanIds: readonly string[]): Record<string, GateFacts> => Object.fromEntries(loanIds.map((id) => [id, (rt.store.get("refi_gate_facts", id)?.data as unknown as GateFacts | undefined) ?? NO_GATE_FACTS]));
const factsFor = (i: ToolInput, rt: ToolRuntime, loanId: string): GateFacts => ((i.gate_facts as GateFacts | undefined) ?? gateFacts(rt, [loanId])[loanId] ?? NO_GATE_FACTS);
const jurisdiction = (i: ToolInput, rt: ToolRuntime): Record<string, JurisdictionRefiRule | undefined> => { const inline = i.jurisdiction_rules as Record<string, JurisdictionRefiRule> | undefined; if (inline) return inline; const rows = rt.store.list("jurisdiction_rules"); const out: Record<string, JurisdictionRefiRule | undefined> = {}; for (const r of rows) { const rule = (r.data.refi_borrower_interest_rule as JurisdictionRefiRule | undefined) ?? ((r.data.rules as Record<string, unknown> | undefined)?.refi_borrower_interest_rule as JurisdictionRefiRule | undefined); if (rule) out[String(r.data.state ?? r.id)] = rule; } if (!Object.keys(out).length) out.MA = MA_183_28C; return out; };
const pricingCtx = (i: ToolInput, rt: ToolRuntime, when: string): QuoteContext => {
  const inline = i.pricing as QuoteContext | undefined; if (inline) return inline;
  const sheets = rt.store.list("rate_sheets").map((r) => r.data as unknown as RateSheet); const id = str(i, "rate_sheet_id");
  const sheet = id ? sheets.find((s) => s.rate_sheet_id === id) : activeSheetAt(sheets, when); if (!sheet) throw new RangeError(`no rate sheet in force at ${when} (20.4 publishRateSheet first; run skipped, sev 3)`);
  const tables = rt.store.list("llpa_tables").flatMap((r) => (r.data.tables as LlpaTable[] | undefined) ?? []); if (!tables.length) throw new RangeError("no llpa_tables loaded (20.4 loadLlpaTable)");
  const costs = rt.store.list("sm_cost_schedules").map((r) => r.data as unknown as SmCostSchedule); const cost = (str(i, "cost_schedule_id") ? costs.find((c) => c.cost_schedule_id === str(i, "cost_schedule_id")) : costs.find((c) => c.transaction_type === "limited_cash_out")) ?? costs[0]; if (!cost) throw new RangeError("no sm_cost_schedules row (20.4 buildFeeItems{op=cost_schedule})");
  const fee = rt.store.list("fee_schedules").map((r) => r.data as unknown as FeeSchedule).find((f) => f.fee_schedule_id === str(i, "fee_schedule_id")) ?? null;
  return { sheet, tables, cost_schedule: cost, fee_schedule: fee };
};
const pipeline = (i: ToolInput, ctx: CommandContext, rt: ToolRuntime): PipelineContext => { const when = at(i, ctx); return { program: program(i, rt), rule_set: ruleSet(i, rt), pricing: pricingCtx(i, rt, when), jurisdiction_rules: jurisdiction(i, rt), as_of: asOf(i, ctx), at: when, run_id: str(i, "run_id") || null, ...(i.schedule ? { schedule: i.schedule as CandidateSchedule } : {}) }; };
const loadOpp = (i: ToolInput, rt: ToolRuntime): RefiOpportunity => { if (i.opportunity && typeof i.opportunity === "object") return i.opportunity as RefiOpportunity; need(i, "opportunity_id"); const r = rt.store.get("refi_opportunities", str(i, "opportunity_id")); if (!r) throw new RangeError(`no refi opportunity ${str(i, "opportunity_id")}`); return r.data as unknown as RefiOpportunity; };
const saveOpp = (rt: ToolRuntime, ctx: CommandContext, o: RefiOpportunity): RefiOpportunity => rt.store.put("refi_opportunities", o.opportunity_id, o as unknown as Record<string, unknown>, ctx.actor, ctx.now).data as unknown as RefiOpportunity;
const bumpFacts = (rt: ToolRuntime, ctx: CommandContext, loanId: string, patch: Partial<GateFacts>): void => { const cur = gateFacts(rt, [loanId])[loanId]!; rt.store.put("refi_gate_facts", loanId, { ...cur, ...patch }, ctx.actor, ctx.now); };
const summary = (o: RefiOpportunity): Record<string, unknown> => ({ opportunity_id: o.opportunity_id, loan_id: o.loan_id, status: o.status, trigger_kind: o.trigger_kind, as_of_date: o.as_of_date, suppression_reasons: o.suppression_reasons, present_same_term_first: o.present_same_term_first, note_rate: o.candidate_terms?.note_rate ?? null, pi_cents: money(o.candidate_terms?.pi_cents), loan_amount_cents: money(o.candidate_terms?.loan_amount_cents), cash_back_cents: money(o.candidate_terms?.cash_back_cents), ltv: o.candidate_terms?.ltv ?? null,
  rate_delta_bps: o.benefit_metrics?.rate_delta_bps ?? null, pi_delta_cents: money(o.benefit_metrics?.pi_delta_cents), npv_cents: money(o.benefit_metrics?.npv_cents), lifetime_interest_delta_cents: money(o.benefit_metrics?.lifetime_interest_delta_cents), seven_year_total_cost_delta_cents: money(o.benefit_metrics?.seven_year_total_cost_delta_cents), gates: o.gates, requires_fnma_ownership_check: o.eligibility_prescreen?.requires_fnma_ownership_check ?? null, fnma_owned: o.eligibility_prescreen?.fnma_owned ?? null, alternatives: o.alternatives, officer_acknowledgment_required: o.officer_acknowledgment_required, lead_id: o.lead_id, application_id: o.application_id });

export const TOOLS_20_1: readonly ToolDef[] = defineTools("20.1", "intake", [
  // Rules 1, 6, 7 / T5: the investor-blind universe under the partner program's GLBA purpose tag; `op=static_check` runs the column allowlist check, `op=approve_rule_set` is the partner officer's act, `op=register_program` stores the economics.
  { name: "loadUniverse", kind: "read", handler: compute((i, ctx, rt) => { const op = str(i, "op") || "load"; const when = at(i, ctx);
      if (op === "register_program") { const p: PartnerProgram = { ...DEFAULT_PROGRAM, ...rec(i.program) } as PartnerProgram; assertGlbaUse(p); rt.store.put("partner_programs", p.program_id, p as unknown as Record<string, unknown>, ctx.actor, ctx.now); return { program_id: p.program_id, product_owner: p.product_owner, purpose: `partner_program:${p.program_id}` }; }
      if (op === "static_check") { const r = staticCheckRuleSet(ruleSet(i, rt)); return { ...r, rule_set_version: ruleSet(i, rt).version }; }
      if (op === "approve_rule_set") { const rs: RefiRuleSet = { ...(i.rule_set as RefiRuleSet | undefined ?? SM_REFI_RULE_SET_V1), approved_by: `${ctx.actor.kind}:${ctx.actor.id}`, reviewed_by_compliance: flag(i, "reviewed_by_compliance") }; staticCheckRuleSet(rs); rt.store.put("refi_rule_sets", rs.version, rs as unknown as Record<string, unknown>, ctx.actor, ctx.now); return { rule_set_version: rs.version, approved_by: rs.approved_by, columns: rs.referenced_columns.length }; }
      if (op === "load_row") { const row = i.row as UniverseLoan | undefined; if (!row) throw new RangeError("loadUniverse{op=load_row} needs row (a v_refi_universe row)"); if (investorKeys(row as unknown as Record<string, unknown>).length) throw new RefiRefused("investor_field_visible", "a v_refi_universe row never carries investor fields"); rt.store.put("refi_universe", row.loan_id, row as unknown as Record<string, unknown>, ctx.actor, ctx.now); if (i.gate_facts) rt.store.put("refi_gate_facts", row.loan_id, { ...NO_GATE_FACTS, ...rec(i.gate_facts) }, ctx.actor, ctx.now); return { loan_id: row.loan_id, purpose: `partner_program:${program(i, rt).program_id}` }; }
      const p = program(i, rt); const rows = universe(i, rt); const r = loadUniverse(p, ruleSet(i, rt), rows, gateFacts(rt, rows.map((x) => x.loan_id)), asOf(i, ctx), (str(i, "path") as "proactive" | "borrower_request") || "proactive");
      return { purpose: r.purpose, as_of_date: asOf(i, ctx), loans_in_universe: r.loans_in_universe, included: r.included.map((l) => l.loan_id), excluded: r.excluded, snapshot_at: when, view: "v_refi_universe", investor_blind: true }; }),
    guardrails: [never("NO_INVESTOR_FIELDS", "20.1 rule 7 / guardrails: cannot read investor fields (enforced by the view `v_refi_universe`: no investor_id, fnma_loan_number, pool_number, remittance_type, mbs_flag, sfc_codes)", readsInvestor, "the trigger's read model is investor-blind; investor fields are never a selection input (B2-1.3-04)"),
      never("NO_PROHIBITED_BASIS", "20.1 rule 8: prohibited selection inputs — ZIP/census tract, language preference, age/DOB, name, applicant_demographics, credit score", readsProhibited, "selection inputs are limited to note rate, UPB, remaining term, product, occupancy, LTV estimate, state, delinquency status, MI status, consent/suppression flags"),
      never("NO_CREDIT_PULL", "20.1 guardrails / FCRA §1681b(c): cannot pull credit — the trigger uses no consumer reports (a soft pull to select borrowers is a prescreen)", pullsCredit, "the representative score on file is an estimate (score_source=origination_file); the real pull occurs after the consumer initiates (20.3)"),
      needsRole("OFFICER_APPROVES_RULE_SET", "20.1 operational prerequisites: objective selection rule set `sm.refi_trigger.v1` approved by the partner `officer`", (i) => str(i, "op") === "approve_rule_set", ["officer"], "the selection rule set is approved by the partner officer (and reviewed by compliance-sentinel)")] },
  // Rule 2: the LCOR candidate (30-year by default; a term equal to the remaining term on request), loan amount, cash back under the SEL-2025-08 cap, LTV and the prescreen; cash-out only on borrower request.
  { name: "buildCandidate", kind: "read", handler: compute((i, ctx, rt) => { const loan = loanRow(i, rt); const sched = (i.schedule as CandidateSchedule | undefined) ?? defaultSchedule(asOf(i, ctx));
      const r = buildCandidate(loan, { transaction_type: (str(i, "transaction_type") as TransactionType) || "limited_cash_out", ...(i.term_months !== undefined ? { term_months: Number(i.term_months) } : {}), schedule: sched, as_of: asOf(i, ctx), borrower_request: flag(i, "borrower_request"), ...(i.cash_out_requested_cents !== undefined ? { cash_out_requested_cents: cents(i.cash_out_requested_cents) } : {}) });
      const c = r.candidate; return { loan_id: loan.loan_id, transaction_type: c.transaction_type, term_months: c.term_months, payoff_estimate_cents: String(c.payoff_estimate_cents), per_diem_cents: String(c.per_diem_cents), payoff_days: c.payoff_days, prepaid_interest_cents: String(c.prepaid_interest_cents), prepaid_days: c.prepaid_days, loan_amount_cents: String(c.loan_amount_cents), rounded_to_thousand: c.rounded_to_thousand, cash_back_cents: String(c.cash_back_cents), cash_back_cap_cents: String(c.cash_back_cap_cents), ltv: c.ltv, value_source: c.value_source, schedule: c.schedule, prescreen: r.prescreen }; }),
    guardrails: [never("NO_CASH_OUT_WITHOUT_REQUEST", "20.1 guardrails / rule 2: cannot construct a cash-out candidate without a borrower request (cash-out candidates only on borrower request, never proactively)", (i) => str(i, "transaction_type") === "cash_out" && !flag(i, "borrower_request"), "a cash-out candidate needs borrower_request=true (refi.opportunity.requested)"),
      never("NO_INVESTOR_FIELDS", "20.1 rule 7: the candidate is built from the investor-blind snapshot", readsInvestor, "investor fields are never read")] },
  // Rule 3: 20.4's pass-through solve on the candidate (`priceCandidate(loan_snapshot, product, lock_days)`), idempotent on (run_id, loan_id, product); the agent never chooses the rate.
  { name: "priceCandidate", kind: "act", handler: compute((i, ctx, rt) => { const loan = loanRow(i, rt); const when = at(i, ctx); const sched = (i.schedule as CandidateSchedule | undefined) ?? defaultSchedule(asOf(i, ctx));
      const built = buildCandidate(loan, { transaction_type: (str(i, "transaction_type") as TransactionType) || "limited_cash_out", ...(i.term_months !== undefined ? { term_months: Number(i.term_months) } : {}), schedule: sched, as_of: asOf(i, ctx), borrower_request: flag(i, "borrower_request") });
      const r = priceCandidate(ctx.events, pricingCtx(i, rt, when), loan, built.candidate, { run_id: str(i, "run_id") || `adhoc-${asOf(i, ctx)}`, quoted_at: when }, ctx.actor);
      return { loan_id: loan.loan_id, quote_id: r.quote.quote_id, outcome: r.quote.outcome, note_rate: r.quote.note_rate, pi_cents: money(r.candidate.pi_cents), llpa_cents: String(r.quote.llpa_cents), third_party_costs_cents: String(r.quote.third_party_costs_cents), lender_credit_cents: String(r.quote.lender_credit_cents), solve_trace: r.quote.solve_trace.map((t) => ({ ...t, premium_cents: String(t.premium_cents), net_cents: String(t.net_cents) })), loan_amount_cents: String(r.candidate.loan_amount_cents), cash_back_cents: String(r.candidate.cash_back_cents), rate_sheet_id: r.quote.rate_sheet_id, llpa_table_id: r.quote.llpa_table_id }; }),
    guardrails: [never("NO_CREDIT_PULL", "20.1 guardrails: cannot pull credit — pricing uses the origination-file score as an estimate", pullsCredit, "score_source is origination_file until the consumer initiates (20.3)"),
      never("NEVER_CHOOSES_THE_RATE", "20.1 AI agent design: the LLM never chooses the rate, the amount or the fire decision (those are code)", (i) => i.note_rate !== undefined || i.manual_rate !== undefined || i.override_price !== undefined, "the note rate is 20.4's pass-through solve over the active sheet")] },
  // Rule 4 / rule 5: the benefit metrics for a priced opportunity (or from inline metrics) and the fire decision; `op=fire_rule` evaluates the fire rule over supplied metrics (T8); `op=explain` returns the disclosure payload (rule 10).
  { name: "computeBenefit", kind: "read", handler: compute((i, ctx, rt) => { const op = str(i, "op") || "metrics";
      if (op === "fire_rule") { const m = rec(i.metrics); need(m as ToolInput, "rate_delta_bps", "npv_cents", "seven_year_total_cost_delta_cents", "lifetime_interest_delta_cents", "same_term_npv_cents"); const p = { ...DEFAULT_PROGRAM, ...rec(i.program) } as PartnerProgram;
        return fireRule({ rate_delta_bps: Number(m.rate_delta_bps), npv_cents: cents(m.npv_cents), seven_year_total_cost_delta_cents: cents(m.seven_year_total_cost_delta_cents), lifetime_interest_delta_cents: cents(m.lifetime_interest_delta_cents), same_term_npv_cents: cents(m.same_term_npv_cents) }, p, { prescreen_ok: i.prescreen_ok !== false, state_rule_ok: i.state_rule_ok !== false, suppression_reasons: Array.isArray(i.suppression_reasons) ? (i.suppression_reasons as string[]) : [] }); }
      const o = loadOpp(i, rt);
      if (op === "explain") { if (!o.candidate_terms || !o.benefit_metrics) throw new RangeError(`opportunity ${o.opportunity_id} is not priced`); return { opportunity_id: o.opportunity_id, explanation_text: explainBenefit({ existing: o.existing_terms, candidate: o.candidate_terms, metrics: o.benefit_metrics, present_same_term_first: o.present_same_term_first }), benefit_disclosure: benefitDisclosurePayload({ existing: o.existing_terms, candidate: o.candidate_terms, metrics: o.benefit_metrics, present_same_term_first: o.present_same_term_first }) }; }
      if (o.benefit_metrics) { const m = o.benefit_metrics; return { opportunity_id: o.opportunity_id, ...Object.fromEntries(Object.entries(m).map(([k, v]) => [k, typeof v === "bigint" ? String(v) : v])) }; }
      const loan = loanRow({ ...i, loan_id: o.loan_id }, rt); const built = buildCandidate(loan, { schedule: o.candidate_terms?.schedule ?? defaultSchedule(o.as_of_date), as_of: o.as_of_date }); const priced = priceCandidate(null, pricingCtx(i, rt, at(i, ctx)), loan, built.candidate, { run_id: o.run_id ?? "adhoc", quoted_at: at(i, ctx) });
      const m = computeBenefit(loan, priced.candidate, priced.quote, program(i, rt)); return { opportunity_id: o.opportunity_id, ...Object.fromEntries(Object.entries(m).map(([k, v]) => [k, typeof v === "bigint" ? String(v) : v])) }; }) },
  // Rule (state) / worked example 3 / T6: the borrower's-interest determination for a jurisdiction with `refi_borrower_interest_rule`; records `refi.borrower_interest.determined{pass, factors}` on the opportunity.
  { name: "checkStateRule", kind: "act", handler: compute((i, ctx, rt) => { const when = at(i, ctx); const rules = jurisdiction(i, rt);
      need(i, "existing_consummation_date", "candidate_consummation_date", "property_state");
      const o = i.opportunity_id || i.opportunity ? loadOpp(i, rt) : null;
      const d = borrowerInterestRule({ property_state: str(i, "property_state"), existing_consummation_date: D(str(i, "existing_consummation_date")), candidate_consummation_date: D(str(i, "candidate_consummation_date")), rules, pi_delta_cents: cents(i.pi_delta_cents ?? o?.benefit_metrics?.pi_delta_cents), borrower_paid_costs_cents: cents(i.borrower_paid_costs_cents ?? o?.benefit_metrics?.borrower_paid_costs_cents), rate_delta_bps: Number(i.rate_delta_bps ?? o?.benefit_metrics?.rate_delta_bps ?? 0), breakeven_months: (i.breakeven_months as number | null | undefined) ?? o?.benefit_metrics?.breakeven_months ?? null, arm_to_fixed: flag(i, "arm_to_fixed"), bona_fide_need: flag(i, "bona_fide_need"), court_order: flag(i, "court_order"), ...(i.cash_proceeds_cents !== undefined ? { cash_proceeds_cents: cents(i.cash_proceeds_cents) } : {}) });
      const loanId = str(i, "loan_id") || o?.loan_id || ctx.loanId; const oppId = o?.opportunity_id ?? str(i, "opportunity_id") ?? null;
      const event = d.applies ? ctx.events.append({ type: "refi.borrower_interest.determined", actor: ctx.actor, occurredAt: when, ...(loanId ? { loanId } : {}), ...(oppId ? { aggregate: { kind: "refi_opportunity", id: oppId } } : {}), payload: { opportunity_id: oppId, pass: d.pass, factors: d.factors, months_since_consummation: d.months_since_consummation, rule: d.rule, property_state: str(i, "property_state"), origination: true, source: "origination" } }) : null;
      if (o) saveOpp(rt, ctx, { ...o, state_determination: d, eligibility_prescreen: o.eligibility_prescreen ? { ...o.eligibility_prescreen, state_rule_ok: d.pass } : null, ...(d.applies && !d.pass ? { status: "suppressed", suppression_reasons: [...o.suppression_reasons, "state_rule_failed"] } : {}) });
      if (d.applies && !d.pass && flag(i, "borrower_insists")) rt.escalations.open({ kind: "licensed_specialist", ...(loanId ? { loanId } : {}), payload: { opportunity_id: oppId, reason: "state_rule_failed_borrower_insists", rule: d.rule } }, ctx.actor);
      return { applies: d.applies, months_since_consummation: d.months_since_consummation, pass: d.pass, factors: d.factors, rule: d.rule, offer_allowed: !d.applies || d.pass, event_id: event?.id ?? null }; }),
    guardrails: [never("STATE_RULE_NEVER_SILENTLY_CONVERTS", "20.1 edge cases: a state borrower's-interest failure blocks the offer, never silently converts", (i) => flag(i, "convert_on_failure") || flag(i, "skip_state_rule"), "a failed state rule refuses the offer; the licensed_specialist / partner counsel escalation is the only path when the borrower insists")] },
  // Timer table: every gate the opportunity is subject to (recapture window, cooldown, frequency cap, cash-out seasoning ×2, MA borrower's interest) with status and opening date; `op=assess_recapture` records the window closing (`premium_recapture.assessed`).
  { name: "checkGates", kind: "read", handler: compute((i, ctx, rt) => { const loan = loanRow(i, rt); const facts = factsFor(i, rt, loan.loan_id); const sched = (i.schedule as CandidateSchedule | undefined) ?? defaultSchedule(asOf(i, ctx));
      if (str(i, "op") === "assess_recapture") { const r = assessPremiumRecapture(ctx.events, loan, facts, at(i, ctx), ctx.actor, program(i, rt).premium_recapture_suppression_days); return { loan_id: loan.loan_id, open: r.open, opens_on: r.opens_on, event_id: r.event?.id ?? null }; }
      const o = i.opportunity_id ? loadOpp(i, rt) : null;
      const gates = checkGates({ path: (str(i, "path") as "proactive" | "borrower_request") || "proactive", transaction_type: (str(i, "transaction_type") as TransactionType) || "limited_cash_out", as_of: asOf(i, ctx), program: program(i, rt), facts, loan, schedule: sched, state_determination: o?.state_determination ?? null });
      return { loan_id: loan.loan_id, as_of_date: asOf(i, ctx), gates, months_since_consummation: monthsBetween(loan.consummation_date, sched.consummation_date) }; }),
    guardrails: [never("NO_INVESTOR_FIELDS", "20.1 rule 7: `fnma_purchase_date` is exposed only to the recapture gate (which suppresses, never selects)", readsInvestor, "gate facts never include investor identity")] },
  // `assertGateOpen`: refuses (`gate_closed:<code>`) when the named gate is closed for the loan / opportunity — the guard 20.2 (solicitation) and 23.2/25.1 (cash-out) call before acting.
  { name: "assertGateOpen", kind: "read", handler: compute((i, ctx, rt) => { need(i, "code"); const loan = loanRow(i, rt); const facts = factsFor(i, rt, loan.loan_id); const o = i.opportunity_id ? loadOpp(i, rt) : null;
      const gates = checkGates({ path: (str(i, "path") as "proactive" | "borrower_request") || "proactive", transaction_type: (str(i, "transaction_type") as TransactionType) || "limited_cash_out", as_of: asOf(i, ctx), program: program(i, rt), facts, loan, schedule: (i.schedule as CandidateSchedule | undefined) ?? defaultSchedule(asOf(i, ctx)), state_determination: o?.state_determination ?? null });
      const g = assertGateOpen(gates, str(i, "code")); return { code: g.code, status: g.status, opens_on: g.opens_on }; }) },
  // The agent's decision record (`agent_decisions`) with rule_set_version / model_version / prompt_version / rationale / confidence; the opportunity's metrics and gates are its evidence.
  { name: "writeDecision", kind: "write", handler: compute((i, ctx, rt) => { const o = i.opportunity_id || i.opportunity ? loadOpp(i, rt) : null;
      if (o) { const d = decisionRecord(o, { model_version: str(i, "model_version") || ctx.run?.modelVersion || "n/a", prompt_version: str(i, "prompt_version") || ctx.run?.promptVersion || "n/a", ...(typeof i.confidence === "number" ? { confidence: i.confidence } : {}) });
        ctx.decide({ agent: ctx.actor.id, action: d.fire ? "refi.opportunity.fire" : "refi.opportunity.no_offer", rationale: d.rationale, ruleSetVersion: d.rule_set_version, loanId: o.loan_id, subject: { kind: "refi_opportunity", id: o.opportunity_id }, ruleCode: "20.1 rules 1–9", confidence: d.confidence, modelVersion: d.model_version, promptVersion: d.prompt_version });
        saveOpp(rt, ctx, { ...o, decision_id: `dec-${o.opportunity_id}` }); return { recorded: true, opportunity_id: o.opportunity_id, fire: d.fire, rationale: d.rationale, inputs_hash: d.inputs_hash }; }
      return decision()(i, ctx); }) },
  // State machine: `op=run` executes the daily pipeline (rules 1–9; SM_REFI_TRIGGER_DAILY → `refi.trigger.run_completed`), `op=offer_ready` emits `refi.opportunity.offer_ready` for a priced opportunity, `op=request` is the borrower-request path, `op=offered|engaged|converted|declined|expired|fnma_lookup` record the transitions, `op=override` is the partner officer's act.
  { name: "emitOfferReady", kind: "act", handler: compute((i, ctx, rt) => { const op = str(i, "op") || "offer_ready"; const when = at(i, ctx);
      if (op === "run") { need(i, "run_id"); const p = pipeline(i, ctx, rt); const rows = universe(i, rt);
        const r = runTrigger(ctx.events, p, { run_id: str(i, "run_id"), trigger_kind: (str(i, "trigger_kind") as "scheduled" | "rate_move") || "scheduled", loans: rows, gate_facts: gateFacts(rt, rows.map((x) => x.loan_id)), prior_opportunities: rt.store.list("refi_opportunities").map((x) => x.data as unknown as RefiOpportunity), prior_extracts: rt.store.list("fair_lending_extracts").map((x) => x.data as unknown as FairLendingExtract), ...(i.demographics ? { demographics: i.demographics as Record<string, DemographicCategory> } : {}), agent_run_id: ctx.run?.runId ?? null }, ctx.actor);
        for (const o of r.opportunities) if (!r.reused.includes(o.opportunity_id)) saveOpp(rt, ctx, o);
        if (r.extract_written) rt.store.put("fair_lending_extracts", r.extract.document_id, { ...r.extract, event: null } as unknown as Record<string, unknown>, ctx.actor, ctx.now);
        rt.store.put("refi_trigger_runs", r.run.run_id, r.run as unknown as Record<string, unknown>, ctx.actor, ctx.now);
        return { run_id: r.run.run_id, as_of_date: r.run.as_of_date, loans_in_universe: r.run.loans_in_universe, loans_evaluated: r.run.loans_evaluated, opportunities_detected: r.run.opportunities_detected, suppressed_by_reason: r.run.suppressed_by_reason, reused: r.reused, fair_lending_extract_document_id: r.run.fair_lending_extract_document_id, extract_written: r.extract_written, opportunities: r.opportunities.map(summary) }; }
      if (op === "request") { const loan = loanRow(i, rt); const p = pipeline(i, ctx, rt);
        const r = requestOpportunity(ctx.events, p, loan, factsFor(i, rt, loan.loan_id), { requested_at: when, ...(str(i, "transaction_type") ? { transaction_type: str(i, "transaction_type") as TransactionType } : {}), ...(i.cash_out_requested_cents !== undefined ? { cash_out_requested_cents: cents(i.cash_out_requested_cents) } : {}), free_text: str(i, "free_text"), bona_fide_need: flag(i, "bona_fide_need"), officer_acknowledged: flag(i, "officer_acknowledged") }, rt.escalations, ctx.actor);
        saveOpp(rt, ctx, r.opportunity); if (r.escalation === null && flag(i, "human_agent")) rt.escalations.open({ kind: "human_agent", loanId: loan.loan_id, payload: { opportunity_id: r.opportunity.opportunity_id, reason: "borrower_request" } }, ctx.actor);
        return { ...summary(r.opportunity), escalation_id: r.escalation?.id ?? null, escalation_kind: r.escalation?.kind ?? null, recapture_estimate_cents: money(r.recapture_estimate?.premium_cents) }; }
      if (op === "evaluate") { const loan = loanRow(i, rt); const p = pipeline(i, ctx, rt); const r = evaluateLoan(ctx.events, p, loan, factsFor(i, rt, loan.loan_id), { trigger_kind: (str(i, "trigger_kind") as "scheduled" | "rate_move" | "borrower_request") || "scheduled", path: (str(i, "path") as "proactive" | "borrower_request") || "proactive", ...(str(i, "transaction_type") ? { transaction_type: str(i, "transaction_type") as TransactionType } : {}) }, ctx.actor); saveOpp(rt, ctx, r.opportunity); return summary(r.opportunity); }
      const o = loadOpp(i, rt);
      if (op === "offer_ready") { const next = markOfferReady(ctx.events, o, when, ctx.actor); saveOpp(rt, ctx, next); return summary(next); }
      if (op === "offered") { const touch = (i.touch as Parameters<typeof recordOffered>[2] | undefined) ?? ctx.events.all().find((e) => e.type === "marketing.touch.sent" && (e.payload as { opportunity_id?: unknown }).opportunity_id === o.opportunity_id); if (!touch) throw new RangeError("emitOfferReady{op=offered} needs 20.2's marketing.touch.sent{opportunity_id} (touch)"); const r = recordOffered(ctx.events, o, touch, ctx.actor); saveOpp(rt, ctx, r.opportunity); bumpFacts(rt, ctx, o.loan_id, { offered_at: [...(factsFor(i, rt, o.loan_id).offered_at), touch.occurredAt] }); return summary(r.opportunity); }
      if (op === "engaged") { const lead = (i.lead as Parameters<typeof engageOpportunity>[2] | undefined) ?? ctx.events.all().find((e) => e.type === "lead.created" && (e.payload as { opportunity_id?: unknown }).opportunity_id === o.opportunity_id); if (!lead) throw new RangeError("emitOfferReady{op=engaged} needs 20.3's lead.created{opportunity_id} (lead)"); const r = engageOpportunity(ctx.events, o, lead, ctx.actor); saveOpp(rt, ctx, r.opportunity); return summary(r.opportunity); }
      if (op === "converted") { need(i, "application_id"); const r = convertOpportunity(ctx.events, o, { application_id: str(i, "application_id"), at: when }, ctx.actor); saveOpp(rt, ctx, r.opportunity); return summary(r.opportunity); }
      if (op === "declined") { const r = declineOpportunity(ctx.events, o, { declined_at: when, reason: (i.reason as string | undefined) ?? null }, ctx.actor); saveOpp(rt, ctx, r.opportunity); bumpFacts(rt, ctx, o.loan_id, { declined_on: (r.event.payload as { declined_on: PlainDate }).declined_on }); return { ...summary(r.opportunity), cooldown_until: r.cooldown_until }; }
      if (op === "expired") { const r = expireOpportunity(ctx.events, o, when, ctx.actor); if (r.event) saveOpp(rt, ctx, r.opportunity); return { ...summary(r.opportunity), expired: r.event !== null }; }
      if (op === "fnma_lookup") { const port = (rt.services.fnma_loan_lookup as LoanLookupPort | undefined) ?? (i.port as LoanLookupPort | undefined); if (!port) throw new RangeError("emitOfferReady{op=fnma_lookup} needs the Fannie Mae Loan Lookup port (services.fnma_loan_lookup)"); const r = fnmaOwnershipCheck(ctx.events, o, port, when, ctx.actor); saveOpp(rt, ctx, r.opportunity); return { ...summary(r.opportunity), selection_unchanged: true }; }
      if (op === "override") { need(i, "reason"); const r = overrideSuppression(ctx.events, o, { by: ctx.actor, reason: str(i, "reason"), at: when }); saveOpp(rt, ctx, r.opportunity); return summary(r.opportunity); }
      throw new RangeError(`emitOfferReady op ${op} is not one of run/request/evaluate/offer_ready/offered/engaged/converted/declined/expired/fnma_lookup/override`); }),
    guardrails: [never("NO_BORROWER_CONTACT", "20.1 guardrails: cannot contact the borrower (20.2/20.3 do, after consent gates) — `refi.opportunity.offer_ready` is the hand-off, never a touch", contactsBorrower, "the intake trigger never sends, calls, texts or emails; 20.2 solicits after TCPA/CAN-SPAM gates"),
      needsRole("OFFICER_OVERRIDES_SUPPRESSION", "20.1 state machine / guardrails: `suppressed` may only be overridden to `offer_ready` by the partner `officer` with a logged reason; the agent cannot override a suppression", (i) => str(i, "op") === "override", ["officer"], "a suppression override is the partner officer's act with a logged reason"),
      never("NO_INVESTOR_OVERRIDE_REASON", "20.1 state machine: never for a Fannie Mae-ownership reason (B2-1.3-04)", (i) => str(i, "op") === "override" && /fannie|fnma|investor|mbs|pool/i.test(str(i, "reason")), "a suppression is never overridden because of who owns the loan"),
      needsRole("OFFICER_ACKNOWLEDGES_RECAPTURE", "20.1 timer table (FNMA_C1_1_01_PREMIUM_RECAPTURE_120): borrower-request path allowed with `officer` acknowledgment of the recapture cost", (i) => str(i, "op") === "request" && flag(i, "officer_acknowledged"), ["officer"], "the recapture acknowledgment is the partner officer's"),
      never("NO_CASH_OUT_WITHOUT_REQUEST", "20.1 guardrails: cannot construct a cash-out candidate without a borrower request", (i) => str(i, "transaction_type") === "cash_out" && str(i, "op") !== "request", "cash-out only through emitOfferReady{op=request} (refi.opportunity.requested)"),
      never("LOOKUP_AFTER_ENGAGED_ONLY", "20.1 integrations: Loan Lookup only after `engaged` and only when `requires_fnma_ownership_check=true` — never a selection input", (i) => str(i, "op") === "run" && (flag(i, "loan_lookup") || flag(i, "fnma_ownership")), "the B2-1.3-02 ownership check is an eligibility fact after engagement (op=fnma_lookup)")] },
  // Rule 8: the fair-lending extract to 31.2 — counts by HMDA demographic category where available (under the applicant_demographics access log), no PII; written once per run (T10).
  { name: "writeFairLendingExtract", kind: "act", handler: compute((i, ctx, rt) => { need(i, "run_id"); const p = program(i, rt); const as_of = asOf(i, ctx);
      const prior = rt.store.list("fair_lending_extracts").map((x) => x.data as unknown as FairLendingExtract).find((x) => x.program_id === p.program_id && x.as_of_date === as_of);
      if (prior) return { document_id: prior.document_id, run_id: prior.run_id, written: false, reason: "already written for this as_of_date", universe: prior.universe, offers: prior.offers, by_category: prior.by_category };
      const opps = rt.store.list("refi_opportunities", (d) => d.program_id === p.program_id && d.as_of_date === as_of).map((x) => x.data as unknown as RefiOpportunity);
      const r = writeFairLendingExtract(ctx.events, { run_id: str(i, "run_id"), program_id: p.program_id, as_of_date: as_of, at: at(i, ctx), opportunities: opps, universe: universe(i, rt).filter((l) => l.status === "active"), demographics: (i.demographics as Record<string, DemographicCategory> | undefined) ?? {} }, ctx.actor);
      rt.store.put("fair_lending_extracts", r.document_id, { ...r, event: null } as unknown as Record<string, unknown>, ctx.actor, ctx.now);
      if (typeof i.disparity_threshold === "number" && Object.values(r.by_category).some((c) => c.universe > 0 && Number(c.offer_rate) < Number(i.disparity_threshold))) rt.escalations.open({ kind: "officer", payload: { run_id: r.run_id, reason: "fair_lending_disparity", extract_document_id: r.document_id, consumer: "31.2" } }, ctx.actor);
      return { document_id: r.document_id, run_id: r.run_id, written: true, universe: r.universe, offers: r.offers, suppressed: r.suppressed, by_category: r.by_category, access_log: r.access_log, event_id: r.event?.id ?? null }; }),
    guardrails: [never("NO_PII_IN_EXTRACT", "20.1 integrations: 31.2 fair-lending monitor — counts by category; no PII", (i) => flag(i, "include_pii") || flag(i, "include_names"), "the extract carries counts only"),
      never("NO_PROHIBITED_BASIS", "20.1 rule 8: demographic categories come from hmda_records under the applicant_demographics access log, never from the selection inputs", (i) => flag(i, "use_for_selection"), "the extract monitors outcomes; it never feeds selection")] },
]);
export const INTAKE_ACTOR: Actor = { kind: "agent", id: "intake" };
