/**
 * §24.6 process-owned tools — bus tools for 24.6 defined with `defineTools("24.6", <agent>, defs)` from
 * ../tools.ts. Every tool string must be one spec/registry/agents.json names for 24.6; src/app/tools.test.ts refuses
 * the rest. Spread by ./index.ts.
 *
 * The `title-closing` agent runs in application scope (ctx.applicationId or `application_id`). Rows live in the
 * entity store under `mi_quotes`, `mi_certificates`, `hpa_disclosures` and `mi_initial_schedules` (every write is a
 * new version); every act goes through the pure rules in src/domain/property/ops-24-6.ts, which append the events
 * the 24.6 timers and the downstream processes (21.2/21.5, 25.2, 26.1, 29.3/29.4, 30.2/30.4 → 10.x) consume. The
 * insurers' adapters are the optional runtime service `mi_origination` (MiOriginationPort); without it the caller
 * passes the insurer responses in the input (sandbox / replay). Guardrails encode the spec's sentences: never derive
 * a premium from an internal rate table; never select the minimum-coverage option without the recorded election
 * and the LLPA in pricing; never render an HPA schedule from anything but the final note terms; never activate
 * before the note date or deliver without `active`; never place a financed premium on a cash-out or above the loan
 * limit; never use an insurer absent from the approved list; coverage-option policy exceptions are the `officer`'s.
 */
import { defineTools, compute, never, needsRole, str, num, flag, cents, type ToolDef, type ToolInput, type ToolRuntime } from "../tools.ts";
import type { CommandContext } from "../commands.ts";
import type { EscalationKind } from "../escalations.ts";
import { plainDate as D, type PlainDate } from "../../kernel/calendar/date.ts";
import { computeLtvRounded, lookupCoverage, lookupMinCoverageLlpa, compareMiPlans, receiveQuotes, selectPlan, submitOrder, parseCommitment, receiveCommitment, verifyCertificateMatchesTerms, recordTermsVerified, revalue, cancelPreClosing, expireCommitment, buildInitialAmortizationSchedule, computeHpaDates, projectedPaymentsMi, renderHpaDisclosure, deliverHpaDisclosure, renderLpmiDisclosure, requestActivation, confirmActivation, remitPremium, seedMiPolicy, evaluateGates, gateFactsOf, writeDecision, financedSinglePremiumPlan, isApprovedInsurer, isLpmi, civilDate, LOAN_LIMIT_2026_1_UNIT_CENTS, RULE_SET_SELLING, RULE_SET_LLPA, MiRefused,
  type MiCertificate, type MiQuote, type QuoteInput, type HpaDisclosure, type InitialSchedule, type HpaDates, type LtvComputation, type CoverageLookup, type MinCoverageLlpa, type MiOriginationPort, type PremiumPlan, type CoverageOption, type TransactionType, type Product, type Occupancy, type ScoreModel, type GateFacts, type CommitmentRaw, type GATES_24_6 } from "../../domain/property/ops-24-6.ts";
import type { ScheduleVersion } from "../../domain/pmi/schedule.ts";

const need = (i: ToolInput, ...keys: string[]): void => { const gaps = keys.filter((k) => i[k] === undefined || i[k] === null || i[k] === ""); if (gaps.length) throw new RangeError(`24.6 tool needs ${gaps.join(", ")}`); };
const appId = (i: ToolInput, ctx: CommandContext): string => { const id = str(i, "application_id") || ctx.applicationId || ""; if (!id) throw new RangeError("24.6 tool needs application_id (or an application-scoped command context)"); return id; };
const at = (i: ToolInput, ctx: CommandContext, key = "at"): string => str(i, key) || ctx.now;
const dateOf = (i: ToolInput, key: string, fallback?: PlainDate): PlainDate => { const v = str(i, key); if (v) return D(v); if (fallback) return fallback; throw new RangeError(`24.6 tool needs ${key}`); };
const optCents = (i: ToolInput, key: string): bigint | null => (i[key] === undefined || i[key] === null || i[key] === "" ? null : cents(i[key]));
const latest = <T>(rt: ToolRuntime, kind: string, applicationId: string, where: (d: Record<string, unknown>) => boolean = () => true): (T & { id?: string }) | null => { const rows = rt.store.list(kind, (d) => d.application_id === applicationId && where(d)); const r = rows.at(-1); return r ? ({ ...(r.data as unknown as T), id: r.id }) : null; };
const put = (rt: ToolRuntime, ctx: CommandContext, kind: string, id: string, row: object) => rt.store.put(kind, id, row as unknown as Record<string, unknown>, ctx.actor, ctx.now).data;
const port = (rt: ToolRuntime): MiOriginationPort | null => (rt.services.mi_origination as MiOriginationPort | undefined) ?? null;
const liveCert = (rt: ToolRuntime, i: ToolInput, id: string): MiCertificate => { const c = (typeof i.certificate_id === "string" ? (rt.store.get("mi_certificates", i.certificate_id)?.data as unknown as MiCertificate | undefined) : undefined) ?? latest<MiCertificate>(rt, "mi_certificates", id, (d) => !["cancelled_pre_closing", "declined"].includes(String(d.status))) ?? latest<MiCertificate>(rt, "mi_certificates", id); if (!c) throw new RangeError("no mi_certificates row for the application (recordPlanElection first)"); return c; };
const liveDisclosure = (rt: ToolRuntime, id: string, kind?: string): HpaDisclosure | null => latest<HpaDisclosure>(rt, "hpa_disclosures", id, (d) => (kind ? d.kind === kind : true));
const ltvOf = (i: ToolInput): LtvComputation => { need(i, "loan_amount_cents", "appraised_value_cents", "transaction_type"); return computeLtvRounded({ loan_amount_cents: cents(i.loan_amount_cents), transaction_type: str(i, "transaction_type") as TransactionType, sales_price_cents: optCents(i, "sales_price_cents"), appraised_value_cents: cents(i.appraised_value_cents), financed_premium_cents: optCents(i, "financed_premium_cents") }); };
const coverageOf = (i: ToolInput, ltvPct: number): CoverageLookup => { need(i, "product", "term_months"); return lookupCoverage({ ltv_pct_rounded: ltvPct, product: str(i, "product") as Product, term_months: num(i, "term_months"), homeready: flag(i, "homeready"), ...(i.standard_mh !== undefined ? { standard_mh: flag(i, "standard_mh") } : {}), ...(typeof i.coverage_option === "string" ? { coverage_option: i.coverage_option as CoverageOption } : {}) }); };
const llpaOf = (i: ToolInput, ltvPct: number, loan: bigint): MinCoverageLlpa | null => (typeof i.score_model === "string" && i.representative_score !== undefined ? lookupMinCoverageLlpa({ score_model: i.score_model as ScoreModel, representative_score: num(i, "representative_score"), ltv_pct_rounded: ltvPct, loan_amount_cents: loan }) : null);
const scheduleOf = (rt: ToolRuntime, i: ToolInput, id: string): InitialSchedule => { const row = latest<InitialSchedule & { schedule: ScheduleVersion }>(rt, "mi_initial_schedules", id); if (row) return row; need(i, "note_amount_cents", "note_rate_pct", "term_months", "first_payment_due"); return buildInitialAmortizationSchedule({ note_amount_cents: cents(i.note_amount_cents), note_rate_pct: str(i, "note_rate_pct"), term_months: num(i, "term_months"), first_payment_due: dateOf(i, "first_payment_due") }); };
const datesOf = (i: ToolInput, s: InitialSchedule, originalValue: bigint): HpaDates => computeHpaDates({ schedule: s.schedule, original_value_cents: originalValue, term_months: s.term_months, first_payment_due: s.first_payment_due });
const quotesOf = (rt: ToolRuntime, i: ToolInput, id: string): MiQuote[] => (Array.isArray(i.quotes) ? (i.quotes as MiQuote[]) : rt.store.list("mi_quotes", (d) => d.application_id === id).map((r) => r.data as unknown as MiQuote));
/** agents.json escalates_to for title-closing: the external MI underwriter is tracked as a settlement_agent-class party; the rest are kernel roles. */
const ESCALATION_KIND: Record<string, EscalationKind> = { officer: "officer", underwriting_reviewer: "underwriting_reviewer", human_agent: "human_agent", settlement_agent: "settlement_agent" };
const FINANCED_ON_CASH_OUT = (i: ToolInput): boolean => (str(i, "premium_plan") === "financed_single" || str(i, "plan") === "financed_single") && str(i, "transaction_type") === "cash_out";
const FINANCED_OVER_LIMIT = (i: ToolInput): boolean => (str(i, "premium_plan") === "financed_single" || str(i, "plan") === "financed_single") && i.note_amount_cents !== undefined && cents(i.note_amount_cents) > (i.loan_limit_cents !== undefined ? cents(i.loan_limit_cents) : LOAN_LIMIT_2026_1_UNIT_CENTS);
const INSURER_OFF_LIST = (i: ToolInput): boolean => (typeof i.mi_company_code === "string" && i.mi_company_code !== "" && !isApprovedInsurer(i.mi_company_code)) || (Array.isArray(i.quotes) && (i.quotes as { mi_company_code?: unknown }[]).some((q) => typeof q.mi_company_code === "string" && !isApprovedInsurer(q.mi_company_code)));
const INTERNAL_RATE_TABLE = (i: ToolInput): boolean => flag(i, "use_internal_rate_table") || flag(i, "derive_premium_internally") || str(i, "rate_source") === "internal_table";

export const TOOLS_24_6: readonly ToolDef[] = defineTools("24.6", "title-closing", [
  // R1 / T1: B2-1.2-01 — value basis (lower of price / appraisal; appraisal for a refinance), truncate to two decimals, round up to the whole percent; gross LTV with a financed premium.
  { name: "computeLtvRounded", kind: "read", handler: compute((i) => ltvOf(i)) },
  // R2 / T2 / T12: B7-1-02 table keyed by product/term, HomeReady, standard MH and band; the minimum option only where the table shows a * value.
  { name: "lookupCoverage", kind: "read", handler: compute((i) => { need(i, "ltv_pct_rounded"); return coverageOf(i, num(i, "ltv_pct_rounded")); }) },
  // R2 / T3: LLPA Matrix minimum-MI grids (Classic FICO / VantageScore 4.0 shifted one band); the LLPA goes to pricing (20.x/21.4) in addition to every other LLPA.
  { name: "lookupMinCoverageLlpa", kind: "read", ruleSetVersion: RULE_SET_LLPA, handler: compute((i) => { need(i, "score_model", "representative_score", "ltv_pct_rounded", "loan_amount_cents"); return lookupMinCoverageLlpa({ score_model: str(i, "score_model") as ScoreModel, representative_score: num(i, "representative_score"), ltv_pct_rounded: num(i, "ltv_pct_rounded"), loan_amount_cents: cents(i.loan_amount_cents) }); }) },
  // R3 / SM_MI_QUOTE_1BD: MISMO 3.5 rate quotes from ≥ 2 approved insurers through the adapters (or the responses passed in); each priced from its own rate; `mi_quotes` rows; mi.quote.received.
  { name: "requestMiQuotes", kind: "act", handler: compute(async (i, ctx, rt) => { const id = appId(i, ctx); need(i, "loan_amount_cents"); const loan = cents(i.loan_amount_cents);
      let inputs: readonly QuoteInput[] = Array.isArray(i.quotes) ? (i.quotes as QuoteInput[]) : [];
      const p = port(rt); if (!inputs.length && p) { need(i, "coverage_pct"); inputs = await p.rateQuote({ application_id: id, loan_amount_cents: loan, coverage_pct: num(i, "coverage_pct"), coverage_option: (i.coverage_option as CoverageOption | undefined) ?? "standard", plans: (i.plans as PremiumPlan[] | undefined) ?? ["bpmi_monthly", "bpmi_single", "financed_single", "lpmi_monthly"], insurers: (i.insurers as string[] | undefined) ?? ["06", "01", "33", "43", "38", "44"], facts: (i.facts as Record<string, unknown> | undefined) ?? {} }); }
      if (!inputs.length) throw new RangeError("24.6 requestMiQuotes needs quotes (insurer responses) or the mi_origination service");
      const r = receiveQuotes(ctx.events, { application_id: id, loan_amount_cents: loan, quotes: inputs, loan_id: ctx.loanId ?? null }, at(i, ctx), ctx.actor);
      for (const q of r.quotes) put(rt, ctx, "mi_quotes", q.quote_id, { ...q, loan_amount_cents: loan });   // the loan amount the insurer priced (32.6: the plan election is recorded on the quote's own basis)
      return { quotes: r.quotes, insurers: r.insurers, multiple_insurers: r.insurers.length >= 2, single_insurer_fallback: r.insurers.length < 2, event: r.event.type }; }),
    guardrails: [never("PREMIUM_NEVER_FROM_INTERNAL_TABLE", "24.6 guardrails: 'never derive a premium from an internal rate table'; rule 3: 'rates from the insurer's quote'", INTERNAL_RATE_TABLE, "premiums come from the insurer's quote response, never an internal rate table"),
      never("INSURER_NOT_APPROVED", "24.6 guardrails: 'never use an insurer absent from the approved list'; B7-1-01 (July 2025 list)", INSURER_OFF_LIST, "the insurer is not on Fannie Mae's approved list")] },
  // R4: the plan comparison presented to the borrower (standard vs minimum with the LLPA and break-even; monthly vs single vs financed vs LPMI) — never steering.
  { name: "compareMiPlans", kind: "read", handler: compute((i, ctx, rt) => { const quotes = quotesOf(rt, i, str(i, "application_id") || ctx.applicationId || ""); if (!quotes.length) throw new RangeError("24.6 compareMiPlans needs quotes (requestMiQuotes first)");       const llpa = i.llpa && typeof i.llpa === "object" ? (i.llpa as MinCoverageLlpa) : typeof i.score_model === "string" && i.loan_amount_cents !== undefined && i.ltv_pct_rounded !== undefined ? llpaOf(i, num(i, "ltv_pct_rounded"), cents(i.loan_amount_cents)) : null;
      return compareMiPlans({ quotes, llpa }); }) },
  // R4 / T3 / T7: the borrower's / partner's recorded election → `mi_certificates` (plan_selected) + mi.plan.selected; `op=financed` prices the financed single-premium plan; `op=revalue` re-runs the LTV after a value change (T11); `op=cancel` / `op=expire` the pre-closing exits.
  { name: "recordPlanElection", kind: "act", ruleSetVersion: RULE_SET_SELLING, moneyFields: ["loan_amount_cents", "sales_price_cents", "appraised_value_cents"], handler: compute((i, ctx, rt) => { const id = appId(i, ctx); const op = (i.op as string | undefined) ?? "elect";
      if (op === "financed") { need(i, "loan_amount_cents", "rate_bps", "value_basis_cents", "transaction_type", "product", "term_months"); return financedSinglePremiumPlan({ loan_amount_cents: cents(i.loan_amount_cents), rate_bps: num(i, "rate_bps"), value_basis_cents: cents(i.value_basis_cents), transaction_type: str(i, "transaction_type") as TransactionType, product: str(i, "product") as Product, term_months: num(i, "term_months"), homeready: flag(i, "homeready"), ...(i.max_ltv_pct !== undefined ? { max_ltv_pct: num(i, "max_ltv_pct") } : {}), ...(i.loan_limit_cents !== undefined ? { loan_limit_cents: cents(i.loan_limit_cents) } : {}), note_rate_pct: str(i, "note_rate_pct") || null }); }
      if (op === "revalue") { const c = liveCert(rt, i, id); need(i, "product", "term_months"); const r = revalue(ctx.events, c, { loan_amount_cents: i.loan_amount_cents !== undefined ? cents(i.loan_amount_cents) : (() => { throw new RangeError("24.6 tool needs loan_amount_cents"); })(), sales_price_cents: optCents(i, "sales_price_cents"), appraised_value_cents: cents(i.appraised_value_cents), transaction_type: str(i, "transaction_type") as TransactionType, product: str(i, "product") as Product, term_months: num(i, "term_months"), homeready: flag(i, "homeready") }, at(i, ctx), ctx.actor); if (r.event) put(rt, ctx, "mi_certificates", c.certificate_id, r.certificate); return { ...r, certificate: r.certificate.certificate_id, event: r.event?.type ?? null }; }
      if (op === "cancel") { const c = liveCert(rt, i, id); need(i, "reason"); const r = cancelPreClosing(ctx.events, c, str(i, "reason"), at(i, ctx), ctx.actor); put(rt, ctx, "mi_certificates", c.certificate_id, r.certificate); return { status: r.certificate.status, event: r.event.type }; }
      if (op === "expire") { const c = liveCert(rt, i, id); const r = expireCommitment(ctx.events, c, at(i, ctx), ctx.actor); put(rt, ctx, "mi_certificates", c.certificate_id, r.certificate); return { status: r.certificate.status, event: r.event.type }; }
      need(i, "quote_id", "units", "occupancy"); const quote = (rt.store.get("mi_quotes", str(i, "quote_id"))?.data as unknown as MiQuote | undefined) ?? (i.quote as MiQuote | undefined); if (!quote) throw new RangeError(`no mi_quotes row ${str(i, "quote_id")}`);
      const ltv = ltvOf(i); const coverage = coverageOf({ ...i, coverage_option: quote.coverage_option }, ltv.ltv_pct_rounded); const llpa = quote.coverage_option === "minimum" ? llpaOf(i, ltv.ltv_pct_rounded, cents(i.loan_amount_cents)) : null;
      const election = i.election && typeof i.election === "object" ? (i.election as { by: "borrower" | "partner"; recorded_at: string }) : null;
      const r = selectPlan(ctx.events, { application_id: id, quote, election, llpa, ltv, coverage, units: num(i, "units"), occupancy: str(i, "occupancy") as Occupancy, transaction_type: str(i, "transaction_type") as TransactionType, loan_id: ctx.loanId ?? null }, at(i, ctx), ctx.actor);
      put(rt, ctx, "mi_certificates", r.certificate.certificate_id, r.certificate); put(rt, ctx, "mi_quotes", quote.quote_id, { ...quote, selected: true, selected_at: at(i, ctx) });
      return { certificate: r.certificate, coverage, llpa, ltv, event: r.event.type }; }),
    guardrails: [never("MIN_COVERAGE_NEEDS_ELECTION_AND_LLPA", "24.6 guardrails: 'never select the minimum-coverage option without the recorded borrower/partner election and the LLPA in pricing'", (i) => str(i, "coverage_option") === "minimum" && (!i.election || typeof i.score_model !== "string"), "the minimum-coverage option needs the recorded election and the score model for its LLPA"),
      never("FINANCED_MI_CASH_OUT", "24.6 guardrails: 'never place a financed premium on a cash-out'; B7-1-04 loan purposes", FINANCED_ON_CASH_OUT, "a financed premium cannot be placed on a cash-out refinance"),
      never("FINANCED_MI_OVER_LOAN_LIMIT", "24.6 guardrails: 'never place a financed premium … above the loan limit'; B7-1-04", FINANCED_OVER_LIMIT, "the gross loan amount with the financed premium exceeds the Fannie Mae loan limit"),
      needsRole("COVERAGE_OPTION_POLICY_EXCEPTION", "24.6 escalations: `officer` for coverage-option policy exceptions and master-policy questions", (i) => flag(i, "coverage_option_policy_exception"), ["officer"], "coverage-option policy exceptions are the partner officer's")] },
  // R8 / SM_MI_ORDER_2BD / T10: delegated (DU Approve/Eligible + partner authority) or non-delegated (full package; external underwriter follow-up 2 business_days_creditor); mi.ordered.
  { name: "submitMiOrder", kind: "act", handler: compute(async (i, ctx, rt) => { const id = appId(i, ctx); need(i, "order_type"); const c = liveCert(rt, i, id);
      const r = submitOrder(ctx.events, c, { order_type: str(i, "order_type") as "delegated" | "non_delegated", du_reliance: flag(i, "du_reliance"), du_casefile_id: str(i, "du_casefile_id") || null, du_recommendation: str(i, "du_recommendation") || null }, at(i, ctx), ctx.actor);
      const p = port(rt); const ack = p ? await p.submitOrder({ application_id: id, mi_company_code: c.mi_company_code, order_type: r.certificate.order_type!, du_casefile_id: r.certificate.du_casefile_id, quote_id: c.quote_id ?? "", package: (i.package as Record<string, unknown> | undefined) ?? {} }) : null;
      put(rt, ctx, "mi_certificates", c.certificate_id, r.certificate);
      const esc = r.external_underwriter_followup ? rt.escalations.open({ kind: "settlement_agent", ownerRole: "settlement_agent", applicationId: id, payload: { task: "mi_underwriter_decision", insurer: c.mi_company_code, sla: r.external_underwriter_followup.sla, due: r.external_underwriter_followup.due, external: true } }, ctx.actor) : null;
      return { certificate: r.certificate, order_ack: ack, external_underwriter_followup: r.external_underwriter_followup, escalation_id: esc?.id ?? null, event: r.event.type }; }),
    guardrails: [never("INSURER_NOT_APPROVED", "24.6 guardrails: 'never use an insurer absent from the approved list'; B7-1-01", INSURER_OFF_LIST, "the insurer is not on Fannie Mae's approved list")] },
  // R8: normalise the insurer's commitment / certificate (or decline) and record it — `committed` + mi.commitment.received (+ mi.certificate.issued), or `declined` → underwriting_reviewer before any adverse action.
  { name: "parseCommitment", kind: "act", handler: compute(async (i, ctx, rt) => { const id = appId(i, ctx); const p = port(rt);
      const raw = (i.response as CommitmentRaw | undefined) ?? (typeof i.decision === "string" ? (i as unknown as CommitmentRaw) : p ? await p.getCommitment({ application_id: id, mi_company_code: str(i, "mi_company_code") || liveCert(rt, i, id).mi_company_code, order_id: str(i, "order_id") || null }) : null);
      if (!raw) throw new RangeError("24.6 parseCommitment needs the insurer response (decision, commitment_number, …) or the mi_origination service");
      const parsed = parseCommitment(raw); if (i.op === "parse") return parsed;
      const c = liveCert(rt, i, id); const r = receiveCommitment(ctx.events, c, parsed, at(i, ctx), ctx.actor); put(rt, ctx, "mi_certificates", c.certificate_id, r.certificate);
      const esc = r.escalation ? rt.escalations.open({ kind: "underwriting_reviewer", ownerRole: "underwriting_reviewer", applicationId: id, payload: { reason: r.escalation.reason, insurer: c.mi_company_code, decline_reason: r.certificate.decline_reason } }, ctx.actor) : null;
      return { parsed, certificate: r.certificate, events: r.events.map((e) => e.type), escalation_id: esc?.id ?? null }; }) },
  // State-machine guard committed → docs_ready: coverage ≥ B7-1-02 for the FINAL LTV, plan = CD, SFCs, commitment valid at the note date; records the verification.
  { name: "verifyCertificateMatchesTerms", kind: "act", ruleSetVersion: RULE_SET_SELLING, handler: compute((i, ctx, rt) => { const id = appId(i, ctx); need(i, "loan_amount_cents", "value_basis_cents", "product", "term_months", "premium_plan_on_cd", "note_date"); const c = liveCert(rt, i, id);
      const check = verifyCertificateMatchesTerms(c, { loan_amount_cents: cents(i.loan_amount_cents), value_basis_cents: cents(i.value_basis_cents), product: str(i, "product") as Product, term_months: num(i, "term_months"), homeready: flag(i, "homeready"), ...(i.standard_mh !== undefined ? { standard_mh: flag(i, "standard_mh") } : {}), premium_plan_on_cd: str(i, "premium_plan_on_cd") as PremiumPlan, note_date: dateOf(i, "note_date") });
      if (!check.matches) return { ...check, status: c.status };
      const next = recordTermsVerified(c, check, at(i, ctx), dateOf(i, "note_date")); put(rt, ctx, "mi_certificates", c.certificate_id, next); return { ...check, status: next.status }; }) },
  // R5: the immutable initial amortization schedule from the FINAL note terms (10.2's buildSchedule) → `mi_initial_schedules` row with its hash; 21.2/25.2 read the MI termination column from it.
  { name: "buildInitialAmortizationSchedule", kind: "act", handler: compute((i, ctx, rt) => { const id = appId(i, ctx); need(i, "note_amount_cents", "note_rate_pct", "term_months", "first_payment_due");
      const s = buildInitialAmortizationSchedule({ note_amount_cents: cents(i.note_amount_cents), note_rate_pct: str(i, "note_rate_pct"), term_months: num(i, "term_months"), first_payment_due: dateOf(i, "first_payment_due") });
      put(rt, ctx, "mi_initial_schedules", `sched-${id}`, { application_id: id, ...s, built_at: at(i, ctx) });
      const mi = i.monthly_premium_cents !== undefined && i.original_value_cents !== undefined ? projectedPaymentsMi({ termination_payment_n: datesOf(i, s, cents(i.original_value_cents)).termination_payment_n, monthly_premium_cents: cents(i.monthly_premium_cents), term_months: s.term_months }).columns : null;
      return { schedule_hash: s.schedule_hash, pi_cents: s.pi_cents, rows: s.schedule.rows.length, first_row: s.schedule.rows[0], last_row: s.schedule.rows.at(-1), projected_payments_mi_columns: mi }; }),
    guardrails: [never("HPA_SCHEDULE_FINAL_TERMS_ONLY", "24.6 guardrails: 'never render an HPA schedule from anything but the final note terms'; 12 U.S.C. 4901(5)", (i) => flag(i, "preliminary_terms") || flag(i, "estimated_terms") || str(i, "terms_basis") === "estimate", "the initial amortization schedule is built from the final note terms only")] },
  // R5 / T5: §4901(2)/(18)/(7) dates from the initial schedule (10.2/10.3 calculators): cancellation (80%), termination (78%), midpoint → first of the following month; the LPMI-equivalent termination date.
  { name: "computeHpaDates", kind: "read", handler: compute((i, ctx, rt) => { need(i, "original_value_cents"); const s = scheduleOf(rt, i, str(i, "application_id") || ctx.applicationId || ""); return { ...datesOf(i, s, cents(i.original_value_cents)), schedule_hash: s.schedule_hash, pi_cents: s.pi_cents }; }) },
  // §4903(a)(1) / T5 / T6 / T12: render the initial disclosure (fixed: schedule + notice; ARM: notice; non-HPA: the Fannie Mae-only variant; LPMI: nothing) → `hpa_disclosures` + hpa.initial_disclosure.rendered; `op=deliver` records delivery at consummation (delivered_at = consummation_at).
  { name: "renderHpaDisclosure", kind: "act", handler: compute((i, ctx, rt) => { const id = appId(i, ctx); const c = liveCert(rt, i, id);
      if (i.op === "deliver") { need(i, "consummation_at"); const d = liveDisclosure(rt, id, c.hpa_disclosure_kind && c.hpa_disclosure_kind !== "fnma_only" && c.hpa_disclosure_kind !== "lpmi_commitment" ? c.hpa_disclosure_kind : undefined); if (!d || d.kind === "lpmi_commitment") throw new RangeError("no rendered HPA initial disclosure to deliver (render first)"); const r = deliverHpaDisclosure(ctx.events, d, str(i, "consummation_at"), ctx.actor, ctx.loanId ?? null); put(rt, ctx, "hpa_disclosures", d.disclosure_id, r.disclosure); return { disclosure_id: d.disclosure_id, delivered_at: r.disclosure.delivered_at, event: r.event.type }; }
      need(i, "product", "partner_name", "borrower_name", "property_address"); const s = scheduleOf(rt, i, id); const dates = datesOf(i, s, c.original_value_cents);
      const r = renderHpaDisclosure(ctx.events, c, { product: str(i, "product") as Product, initial: s, dates, partner_name: str(i, "partner_name"), borrower_name: str(i, "borrower_name"), property_address: str(i, "property_address"), loan_number: str(i, "loan_number") || null, notice_id: str(i, "notice_id") || null, amortization_schedule_document_id: str(i, "amortization_schedule_document_id") || null }, at(i, ctx), ctx.actor);
      put(rt, ctx, "mi_certificates", c.certificate_id, r.certificate); if (r.rendered) put(rt, ctx, "hpa_disclosures", r.disclosure.disclosure_id, r.disclosure);
      return r.rendered ? { rendered: true, variant: r.variant, disclosure_id: r.disclosure.disclosure_id, notice_code: r.disclosure.notice_code, cancellation_date: dates.cancellation_date, termination_date: dates.termination_date, midpoint_termination_date: dates.midpoint_termination_date, schedule_rows: r.variant === "initial_fixed" ? s.schedule.rows.length : 0, status: r.certificate.status, event: r.event.type } : { rendered: false, variant: r.variant, reason: r.reason, fnma_only_payload: r.fnma_only_payload, status: r.certificate.status, event: r.event?.type ?? null }; }),
    guardrails: [never("HPA_SCHEDULE_FINAL_TERMS_ONLY", "24.6 guardrails: 'never render an HPA schedule from anything but the final note terms'", (i) => flag(i, "preliminary_terms") || flag(i, "estimated_terms") || str(i, "terms_basis") === "estimate", "the HPA disclosure is rendered from the final note terms only")] },
  // §4905(c) / T8: NTC_HPA_4905_LPMI delivered with / before the conditional-approval letter → `hpa_disclosures` (lpmi_commitment) + hpa.lpmi_disclosure.delivered; SFC 019.
  { name: "renderLpmiDisclosure", kind: "act", handler: compute((i, ctx, rt) => { const id = appId(i, ctx); need(i, "delivered_at", "partner_name", "borrower_name", "property_address"); const c = liveCert(rt, i, id); const s = scheduleOf(rt, i, id); const dates = datesOf(i, s, c.original_value_cents);
      const r = renderLpmiDisclosure(ctx.events, c, { delivered_at: str(i, "delivered_at"), commitment_letter_issued_at: str(i, "commitment_letter_issued_at") || null, dates, partner_name: str(i, "partner_name"), borrower_name: str(i, "borrower_name"), property_address: str(i, "property_address"), lpmi_rate_adjustment_pct: str(i, "lpmi_rate_adjustment_pct") || null, notice_id: str(i, "notice_id") || null }, ctx.actor);
      put(rt, ctx, "mi_certificates", c.certificate_id, r.certificate); put(rt, ctx, "hpa_disclosures", r.disclosure.disclosure_id, r.disclosure);
      return { disclosure_id: r.disclosure.disclosure_id, notice_code: r.disclosure.notice_code, delivered_at: r.disclosure.delivered_at, lpmi_equiv_termination_date: dates.lpmi_equiv_termination_date, sfc_codes: r.certificate.sfc_codes, status: r.certificate.status, event: r.event.type }; }) },
  // R10 / SM_MI_ACTIVATE_1BD / T9: activation request at the note date (mi.activation.requested, confirm by +1 business_days_creditor); `op=confirm` records the insurer's confirmation with effective date = note date → `active` (mi.activated).
  { name: "requestActivation", kind: "act", handler: compute(async (i, ctx, rt) => { const id = appId(i, ctx); const c = liveCert(rt, i, id);
      if (i.op === "confirm") { need(i, "activation_effective_date"); const r = confirmActivation(ctx.events, c, { activation_effective_date: dateOf(i, "activation_effective_date"), certificate_number: str(i, "certificate_number") || null, first_premium_due_date: typeof i.first_premium_due_date === "string" ? D(i.first_premium_due_date) : null }, at(i, ctx, "confirmed_at") || at(i, ctx), ctx.actor); put(rt, ctx, "mi_certificates", c.certificate_id, r.certificate); return { status: r.certificate.status, activation_effective_date: r.certificate.activation_effective_date, certificate_number: r.certificate.certificate_number, event: r.event.type }; }
      need(i, "note_date"); const r = requestActivation(ctx.events, c, { note_date: dateOf(i, "note_date"), loan_id: str(i, "loan_id") || ctx.loanId || null }, at(i, ctx), ctx.actor); put(rt, ctx, "mi_certificates", c.certificate_id, r.certificate);
      const p = port(rt); const ack = p ? await p.activate({ mi_company_code: c.mi_company_code, certificate_number: c.certificate_number, commitment_number: c.commitment_number, note_date: dateOf(i, "note_date") }) : null;
      return { status: r.certificate.status, confirm_by: r.confirm_by, insurer_ack: ack, event: r.event.type }; }),
    guardrails: [never("ACTIVATE_BEFORE_NOTE_DATE", "24.6 guardrails: 'never activate before the note date'", (i) => typeof i.note_date === "string" && typeof i.at === "string" && i.at.slice(0, 10) < i.note_date, "activation is requested on or after the note date")] },
  // R10 / SM_MI_UPFRONT_REMIT_10: upfront (single / split / financed) premiums remitted within the master-policy window; LPMI as the partner's corporate obligation (27.2); nothing for monthly BPMI (10.x from the first payment).
  { name: "remitPremium", kind: "act", moneyFields: ["amount_cents"], handler: compute(async (i, ctx, rt) => { const id = appId(i, ctx); const c = liveCert(rt, i, id);
      const r = remitPremium(ctx.events, c, { remitted_at: at(i, ctx, "remitted_at"), amount_cents: optCents(i, "amount_cents"), funded_on: typeof i.funded_on === "string" ? D(i.funded_on) : null }, ctx.actor); put(rt, ctx, "mi_certificates", c.certificate_id, r.certificate);
      const p = port(rt); const ack = p && c.certificate_number ? await p.remitPremium({ mi_company_code: c.mi_company_code, certificate_number: c.certificate_number, amount_cents: r.amount_cents, remitted_at: r.certificate.remitted_at! }) : null;
      return { amount_cents: r.amount_cents, ledger_bucket: r.ledger_bucket, remittance: ack, event: r.event.type }; }) },
  // Gates: FNMA_B7_1_01_MI_COMMITMENT_BEFORE_DOCS_GATE, SM_MI_COMMITMENT_EXPIRY_GATE, HPA_4903_INITIAL_DISCLOSURE_GATE, HPA_4905C_LPMI_DISCLOSURE_GATE, FNMA_B7_1_01_MI_ACTIVE_BEFORE_DELIVERY_GATE over the certificate + disclosure rows; `op=consummate` / `op=generate_docs` / `op=submit_delivery` refuse when their gates are closed.
  { name: "evaluateGates", kind: "read", handler: compute((i, ctx, rt) => { const id = str(i, "application_id") || ctx.applicationId || ""; const c = id ? latest<MiCertificate>(rt, "mi_certificates", id, (d) => !["cancelled_pre_closing", "declined"].includes(String(d.status))) : null; const d = id ? liveDisclosure(rt, id) : null;
      const extra = (i.facts as Partial<GateFacts> | undefined) ?? {}; const f = gateFactsOf(c, { ...(i.mi_required !== undefined ? { mi_required: flag(i, "mi_required") } : c ? {} : { mi_required: false }), ...(typeof i.consummation_at === "string" ? { consummation_at: i.consummation_at, consummation_on: civilDate(i.consummation_at) } : {}), ...(typeof i.commitment_letter_issued_at === "string" ? { commitment_letter_issued_at: i.commitment_letter_issued_at } : {}), ...(i.required_coverage_pct !== undefined ? { required_coverage_pct: num(i, "required_coverage_pct") } : {}), ...extra }, d);
      const only = i.op === "consummate" ? (["SM_MI_COMMITMENT_EXPIRY_GATE", "HPA_4903_INITIAL_DISCLOSURE_GATE"] as const) : i.op === "generate_docs" ? (["FNMA_B7_1_01_MI_COMMITMENT_BEFORE_DOCS_GATE"] as const) : i.op === "submit_delivery" ? (["FNMA_B7_1_01_MI_ACTIVE_BEFORE_DELIVERY_GATE"] as const) : i.op === "approval_letter" ? (["HPA_4905C_LPMI_DISCLOSURE_GATE"] as const) : undefined;
      const r = evaluateGates(f, only as readonly (keyof typeof GATES_24_6)[] | undefined);
      if (only && !r.all_open) throw new MiRefused("GATE_CLOSED", `24.6 ${r.closed.join(", ")}`, `${String(i.op)} refused: ${r.closed.map((g) => r.results[g]!.reason).join("; ")}`);
      return { ...r, facts: f }; }) },
  // 30.4 → 10.1: the `mi_policies` payload boarded from the certificate (HPA dates from the same schedule; not_applicable_midpoint_only for non-HPA loans; lpmi_equiv_termination_date for LPMI).
  { name: "seedMiPolicy", kind: "act", handler: compute((i, ctx, rt) => { const id = appId(i, ctx); need(i, "loan_id"); const c = liveCert(rt, i, id); const s = scheduleOf(rt, i, id); const dates = datesOf(i, s, c.original_value_cents);
      const seed = seedMiPolicy(c, { loan_id: str(i, "loan_id"), dates, term_months: s.term_months, sales_price_cents: optCents(i, "sales_price_cents"), appraised_value_cents: optCents(i, "appraised_value_cents"), schedule_hash: s.schedule_hash, consummation_date: typeof i.consummation_date === "string" ? D(i.consummation_date) : null });
      put(rt, ctx, "mi_policy_seeds", `seed-${id}`, { ...seed, seeded_at: at(i, ctx) }); return seed; }),
    guardrails: [never("DELIVER_WITHOUT_ACTIVE", "24.6 guardrails: 'never … deliver without `active`'; 30.2 OB-009", (i) => flag(i, "skip_activation") || flag(i, "force_without_activation"), "the policy is boarded only from an activated (or activation-requested) certificate")] },
  // AI agent design: the decision record {application_id, ltv_raw, ltv_rounded, gross_ltv_rounded, coverage_required_pct, coverage_option, llpa_bps, quotes[], election, order{}, certificate{}, hpa{}, gates, rationale, rule_set_version, model_version}.
  { name: "writeDecision", kind: "act", ruleSetVersion: RULE_SET_SELLING, handler: compute((i, ctx, rt) => { const id = appId(i, ctx); const c = liveCert(rt, i, id); const ltv = ltvOf(i); const coverage = coverageOf({ ...i, coverage_option: c.coverage_option }, ltv.ltv_pct_rounded); const llpa = c.coverage_option === "minimum" ? llpaOf(i, ltv.ltv_pct_rounded, cents(i.loan_amount_cents)) : null;
      const sched = latest<InitialSchedule & { schedule: ScheduleVersion }>(rt, "mi_initial_schedules", id); const dates = sched ? datesOf(i, sched, c.original_value_cents) : null; const gates = evaluateGates(gateFactsOf(c, {}, liveDisclosure(rt, id))).results;
      const d = writeDecision({ certificate: c, ltv, coverage, llpa, quotes: quotesOf(rt, i, id), dates, gates, model_version: str(i, "model_version") || ctx.run?.modelVersion || "unversioned", prompt_version: str(i, "prompt_version") || ctx.run?.promptVersion || "unversioned", ...(typeof i.confidence === "number" ? { confidence: i.confidence } : {}), ...(typeof i.rationale === "string" && i.rationale ? { rationale: i.rationale } : {}) });
      ctx.decide({ agent: "title-closing", action: "24.6.mortgage_insurance", rationale: d.rationale, ruleSetVersion: d.rule_set_version, applicationId: id, loanId: ctx.loanId, subject: { kind: "application", id }, ruleCode: "24.6", confidence: d.confidence, modelVersion: d.model_version, promptVersion: d.prompt_version }); return d; }) },
]);

/** Escalation kinds the 24.6 tools open (agents.json escalates_to ∩ the process's needs). */
export const ESCALATION_KINDS_24_6 = ESCALATION_KIND;
export { MiRefused, isLpmi };
