/**
 * §9 tools — insurance and property protection (9.1–9.9). Tool strings are
 * verbatim from each process's Agents paragraph; guardrails encode the
 * "cannot"/"never" sentences and the human touchpoints. Agent:
 * `insurance-property` throughout.
 */
import { defineTools, escalate, compute, never, needsRole, humanWhen, noticeOps, port, cents, str, num, flag, data, type ToolDef, type ToolInput } from "../tools.ts";
import { plainDate as D, type PlainDate } from "../../kernel/calendar/date.ts";
import { evaluateAdequacy, type HazardPolicy, type Deficiency } from "../../domain/insurance/hazard.ts";
import { reasonableBasis, escrowGuard, reminderVariant, premiumQuote, lpiCoverage, renewalClocks, renewalNoticeAllowed, chargeDecision, fpiClocks, type BasisKind, type EvidenceRow } from "../../domain/insurance/fpi.ts";
import { cancellation, type CancellationInput } from "../../domain/insurance/refund.ts";
import { floodRequired, floodRequiredAmount, floodAdequate, privatePolicyAcceptable, placementAllowed, floodNoticeClocks, type FloodRequirementInput, type PrivatePolicyInput } from "../../domain/insurance/flood.ts";
import { lossDraftTrack, initialRelease, progressReleaseCurrent, progressReleaseDelinquent, thirdPartyReleaseAllowed, remoteInspectionAcceptable, notRebuildableDisposition, form176Due, reogramRemitDue, type ReleaseInput } from "../../domain/insurance/lossdraft.ts";
import { inspectionWindow, inspectionMode, inspectionSuspended, inspectionType, nextInspectionWindow, pfpipTaskDue, pfpipPermission, type ExceptionInput } from "../../domain/insurance/inspection.ts";
import { evaluateScope, bidDue, photosFresh, preservationMode, type WorkItem } from "../../domain/insurance/preservation.ts";
import { vacancyConfirmed, pfpipSubmission, vacantRegistration, placementConfig, refundTimeline } from "../../domain/insurance/ops.ts";

const need = (i: ToolInput, ...keys: string[]): void => { for (const k of keys) if (i[k] === undefined || i[k] === null || i[k] === "") throw new RangeError(`${k} is required`); };
const date = (i: ToolInput, k: string): PlainDate => { need(i, k); return D(str(i, k)); };
const rows = <T>(i: ToolInput, k: string): T[] => { const v = i[k]; if (!Array.isArray(v)) throw new RangeError(`${k} must be an array`); return v as T[]; };
const A = "insurance-property";
const openClaim: Omit<ToolDef, "process" | "agent"> = { name: "openClaim", kind: "write", handler: compute((i, ctx, rt) => { need(i, "loan_id"); const track = lossDraftTrack({ fnma_days_delinquent: num(i, "fnma_days_delinquent") || 0, abandoned: flag(i, "abandoned"), fc_sale_scheduled: flag(i, "fc_sale_scheduled"), rebuildable: (str(i, "rebuildable") || "unknown") as "yes" | "no" | "unknown" });
    const rec = rt.store.put("insurance_claims", str(i, "id") || `claim-${ctx.now}`, { loan_id: str(i, "loan_id"), policy_id: (i.policy_id as string | undefined) ?? null, case_type: "insurance_claim", track, uninsured: !i.policy_id }, ctx.actor, ctx.now);
    ctx.events.append({ type: "claim.activity.recorded", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { claim_id: rec.id, track } }); return { id: rec.id, track, uninsured: !i.policy_id }; }) };
const notifyCarrierVacancy: Omit<ToolDef, "process" | "agent"> = { name: "notifyCarrierVacancy", kind: "act", handler: compute((i, ctx) => { need(i, "loan_id", "vacancy_on"); ctx.events.append({ type: "insurance.carrier.vacancy_notified", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { vacancy_on: str(i, "vacancy_on") } }); return { notified: true, coverage_review: "vacancy endorsement or LPI vacant-property coverage (9.1 rule 6)" }; }) };

const p91 = defineTools("9.1", A, [
  { name: "recordDeficiency", kind: "write", handler: compute((i, ctx, rt) => { need(i, "loan_id"); const p = i.policy as HazardPolicy | undefined; const result = p ? evaluateAdequacy(p, Array.isArray(i.title_holders) ? (i.title_holders as string[]) : []) : null; const defs = result ? result.deficiencies : rows<Deficiency>(i, "deficiencies");
      const rec = rt.store.put("insurance_deficiencies", str(i, "id") || `def-${ctx.now}`, { loan_id: str(i, "loan_id"), deficiencies: defs, evidence_id: (i.evidence_id as string | undefined) ?? null, status: "open" }, ctx.actor, ctx.now); return { id: rec.id, deficiencies: defs, lpi_curable: result?.lpi_curable ?? null }; }),
    guardrails: [never("VERIFIED_NEEDS_EVIDENCE", "9.1 guardrail: the agent cannot mark a policy `verified` without a confirmed evidence record", (i) => str(i, "status") === "verified" && !i.evidence_id, "verification needs a confirmed evidence record"),
      needsRole("RATING_WAIVER_OFFICER", "9.1 guardrail: a rating failure is waived only by an officer under documented mortgage-impairment cover", (i) => flag(i, "waive_rating_failure"), ["officer"], "rating waivers are officer decisions with mortgage-impairment cover documented")] },
  { name: "requestEscrowLineUpdate", kind: "write", handler: compute((i, ctx) => { need(i, "loan_id", "new_premium_cents"); return ctx.events.append({ type: "escrow.line.update_requested", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { line: "hazard", premium_cents: cents(i.new_premium_cents) } }); }),
    guardrails: [never("NO_PREMIUM_DEMAND_ESCROWED_CURRENT", "9.1 guardrail: cannot ask an escrowed current borrower to pay a premium", (i) => flag(i, "escrowed") && num(i, "regx_days_delinquent") <= 30 && flag(i, "ask_borrower_to_pay"), "the servicer pays the renewal from escrow (3.7)")] },
  { name: "openCase", kind: "write", handler: compute((i, ctx, rt) => { need(i, "loan_id", "case_type"); const rec = rt.store.put("cases", str(i, "id") || `case-${ctx.now}`, { loan_id: str(i, "loan_id"), case_type: str(i, "case_type"), status: "open" }, ctx.actor, ctx.now); return { id: rec.id, case_type: str(i, "case_type") }; }) },
]);
const p92 = defineTools("9.2", A, [
  { name: "assessReasonableBasis", kind: "read", handler: compute((i) => { need(i, "kind"); return { reasonable_basis: reasonableBasis(str(i, "kind") as BasisKind, i.deficiency as Deficiency | undefined), kind: str(i, "kind") }; }),
    guardrails: [never("NO_NOTICE_WITHOUT_BASIS", "9.2 guardrail: no notice without a recorded basis", (i) => flag(i, "send_notice") && !i.basis_evidence_id, "record the reasonable-basis evidence first")] },
  { name: "checkEscrowGuard", kind: "read", handler: compute((i) => ({ guard: escrowGuard(flag(i, "escrowed"), num(i, "regx_days_delinquent") || 0, (i.cancellation_reason as "nonpayment" | "underwriting" | "other" | null | undefined) ?? null) })) },
]);
const p93 = defineTools("9.3", A, [
  { name: "selectReminderVariant", kind: "read", handler: compute((i) => reminderVariant(rows<EvidenceRow>(i, "evidence"), date(i, "lapse_start"), date(i, "as_of"))), guardrails: [never("DETERMINISTIC_VARIANT", "9.3 guardrail: variant selection is deterministic from evidence records — the model cannot override", (i) => typeof i.override_variant === "string", "the variant is derived from evidence rows only")] },
  { name: "quoteLpi", kind: "read", handler: compute((i) => { need(i, "coverage_cents"); const q = premiumQuote(i.carrier_quote_cents === undefined || i.carrier_quote_cents === null ? null : cents(i.carrier_quote_cents), cents(i.coverage_cents), str(i, "table_rate_pct") || "0"); return { ...q, traced_to: q.is_estimate ? `rate_table:${str(i, "rate_table_version") || "current"}` : `carrier_quote:${str(i, "quote_id") || "unknown"}` }; }),
    guardrails: [never("COST_TRACES_TO_RECORD", "9.3 guardrail: the cost figure must trace to a quote/rate-table record", (i) => flag(i, "manual_figure"), "no hand-entered premiums")] },
]);
const p94 = defineTools("9.4", A, [
  { name: "reviewLpiCoverage", kind: "read", handler: compute((i) => ({ ...lpiCoverage({ last_known_cents: i.last_known_cents === undefined ? null : cents(i.last_known_cents), rcv_cents: cents(i.rcv_cents), upb_cents: cents(i.upb_cents), state_cap_cents: i.state_cap_cents === undefined ? null : cents(i.state_cap_cents), ...(flag(i, "vacant") ? { vacant: true } : {}) }), clocks: renewalClocks(date(i, "placement_effective"), i.t2 ? D(str(i, "t2")) : null) })),
    guardrails: [never("ONE_NOTICE_PER_YEAR", "9.4 guardrail: one notice per year (§1024.37(e)(5))", (i) => flag(i, "send_notice") && !renewalNoticeAllowed(i.last_notice as { mailed: PlainDate; anniversary: PlainDate } | null ?? null, D(str(i, "anniversary") || "2000-01-01"), D(str(i, "today") || "2000-01-01")), "a renewal notice was already mailed for this anniversary")] },
  { name: "quoteLpiRenewal", kind: "read", handler: compute((i) => premiumQuote(i.carrier_quote_cents === undefined || i.carrier_quote_cents === null ? null : cents(i.carrier_quote_cents), cents(i.coverage_cents), str(i, "table_rate_pct") || "0")), guardrails: [never("NO_CHARGE_BEFORE_GATE", "9.4 guardrail: no charge before the gate", (i) => flag(i, "assess_charge") && !flag(i, "gate_open"), "the renewal charge waits for the 45-day gate")] },
]);
const cancelInput = (i: ToolInput): CancellationInput => ({ terms: rows(i, "terms"), borrower_coverage_start: date(i, "borrower_coverage_start"), borrower_coverage_end: i.borrower_coverage_end ? D(str(i, "borrower_coverage_end")) : null, evidence_received_on: date(i, "evidence_received_on"), borrower_paid_cents: cents(i.borrower_paid_cents), ...(i.deadline_days === 30 ? { deadline_days: 30 as const } : {}) });
const p95 = defineTools("9.5", A, [
  { name: "evaluateEvidence", kind: "write", handler: compute((i, ctx) => { need(i, "evidence_id"); const ok = flag(i, "continuous_coverage_shown") && flag(i, "written"); ctx.events.append({ type: "insurance.evidence.evaluated", loanId: ctx.loanId, actor: ctx.actor, payload: { evidence_id: str(i, "evidence_id"), outcome: ok ? "confirmed" : "rejected" } }); return { outcome: ok ? "confirmed" : "rejected", reason: ok ? null : "evidence must be written and show continuous compliant coverage" }; }) },
  { name: "computeOverlapRefund", kind: "read", handler: compute((i) => cancellation(cancelInput(i))) },
  { name: "requestLpiCancel", kind: "act", handler: compute(async (i, ctx, rt) => { need(i, "binding_id", "cancelled_on"); const r = await port(rt, "lpi").cancel(str(i, "binding_id"), str(i, "cancelled_on"), ctx.now); ctx.events.append({ type: "fpi.lpi.cancel_requested", loanId: ctx.loanId, actor: ctx.actor, payload: { binding_id: str(i, "binding_id") } }); return r; }),
    guardrails: [never("NO_CANCELLATION_FEE", "9.5 guardrail: cannot charge a cancellation fee", (i) => cents(i.fee_cents) > 0n, "no cancellation fee")] },
  { name: "postRefund", kind: "write", moneyFields: ["refund_cents"], handler: compute((i, ctx) => { const r = cancellation(cancelInput(i)); const posted = i.refund_cents === undefined ? r.refund_cents : cents(i.refund_cents); ctx.events.append({ type: "fpi.refund.posted", loanId: ctx.loanId, actor: ctx.actor, payload: { removed_cents: r.removed_cents, refund_cents: posted } }); return { removed_cents: r.removed_cents, refund_cents: posted, ledger: ["Cr corporate_advances", "Dr lpi_refund_expense"] }; }),
    guardrails: [never("REFUND_NOT_BELOW_CALCULATOR", "9.5 guardrail: cannot reduce a refund below the calculator's figure", (i) => { try { return i.refund_cents !== undefined && cents(i.refund_cents) < cancellation(cancelInput(i)).refund_cents; } catch { return false; } }, "the calculator's figure is the floor")] },
  { name: "payRefund", kind: "act", moneyFields: ["refund_cents"], handler: compute((i, ctx) => { need(i, "refund_cents", "rail"); ctx.events.append({ type: "fpi.refund.paid", loanId: ctx.loanId, actor: ctx.actor, payload: { refund_cents: cents(i.refund_cents), rail: str(i, "rail") } }); return { paid: true, rail: str(i, "rail") }; }),
    guardrails: [never("NEVER_WAIT_FOR_CARRIER", "9.5 guardrail: cannot wait for the carrier — the borrower is refunded by day 15", (i) => flag(i, "wait_for_carrier_refund"), "the borrower refund is independent of the carrier's"), humanWhen("OFFICER_DAY_12", "9.5 escalations: officer at day 12 if unpaid", (i) => num(i, "days_since_evidence") >= 12 && !flag(i, "paid"), "breach-risk report to the officer")] },
  { name: "notifyBorrower", kind: "act", handler: noticeOps("render_send") },
]);
const p96 = defineTools("9.6", A, [
  { name: "orderDetermination", kind: "act", handler: compute(async (i, ctx, rt) => { need(i, "property_id", "address"); return port(rt, "flood").orderDetermination(str(i, "property_id"), str(i, "address"), ctx.now); }),
    guardrails: [never("NO_NFHL_ONLY", "9.6 guardrail: no reliance on FEMA NFHL alone", (i) => str(i, "source") === "nfhl_only", "order a vendor SFHDF; NFHL alone is not a determination")] },
  { name: "evaluateStructures", kind: "read", handler: compute((i) => { const f = i.structures as FloodRequirementInput | undefined; if (!f) throw new RangeError("structures is required"); return { ...floodRequired(f), reasoning: f.principal_structure_in_sfha ? "principal structure in the SFHA" : f.detached_security_structure_in_sfha ? "detached security structure in the SFHA" : f.cbrs_opa ? "CBRS/OPA" : "no security structure in the SFHA (B7-3-06 table)" }; }) },
  { name: "computeFloodRequirement", kind: "read", handler: compute((i) => { need(i, "rcv_cents", "upb_cents"); const req = floodRequiredAmount(cents(i.rcv_cents), cents(i.upb_cents)); return { required_cents: req, ...(i.policy_amount_cents !== undefined ? floodAdequate(cents(i.policy_amount_cents), cents(i.rcv_cents), cents(i.upb_cents), cents(i.deductible_cents)) : {}) }; }),
    guardrails: [never("AMOUNT_NOT_ABOVE_MINIMUM", "9.6 guardrail: the placed amount never exceeds the rule-2 minimum unless the borrower elects", (i) => i.place_cents !== undefined && i.rcv_cents !== undefined && cents(i.place_cents) > floodRequiredAmount(cents(i.rcv_cents), cents(i.upb_cents)) && !flag(i, "borrower_elected"), "place the rule-2 minimum"),
      never("NO_PLACEMENT_BEFORE_45", "9.6 guardrail: no placement before t0 + 45", (i) => flag(i, "place") && typeof i.notice_mailed_on === "string" && !placementAllowed(floodNoticeClocks(D(str(i, "notice_mailed_on")), null), D(str(i, "today") || "2000-01-01"), flag(i, "sufficient_evidence")), "the 45-day notice period has not run")] },
  { name: "evaluatePrivateFloodPolicy", kind: "read", handler: compute((i) => { const p = i.policy as PrivatePolicyInput | undefined; if (!p) throw new RangeError("policy is required"); return privatePolicyAcceptable(p); }) },
]);
const release = (i: ToolInput): ReleaseInput => ({ total_cents: cents(i.total_cents), upb_cents: cents(i.upb_cents), accrued_interest_cents: cents(i.accrued_interest_cents), advances_cents: cents(i.advances_cents), track: (str(i, "track") || "current_lt31") as ReleaseInput["track"] });
const p97 = defineTools("9.7", A, [
  openClaim,
  { name: "computeReleaseSchedule", kind: "read", handler: compute((i) => { need(i, "total_cents"); const r = release(i); const init = initialRelease(r); return { initial: init, progress: r.track === "delinquent_31plus" ? "≤ 25% of total per inspected increment; final inspection before the last release" : "cumulative ≤ initial + pct_complete × remainder", contents_ale: "released within 2 business days" }; }) },
  { name: "requestEndorsement", kind: "act", handler: compute((i, ctx) => { need(i, "instrument_id"); ctx.events.append({ type: "claim.instrument.endorsement_requested", loanId: ctx.loanId, actor: ctx.actor, payload: { instrument_id: str(i, "instrument_id"), dual_control: cents(i.amount_cents) >= 5_000_000n } }); return { borrower_endorses_first: true, servicer_endorsement: "signing_officer under the LPOA", dual_control: cents(i.amount_cents) >= 5_000_000n }; }),
    guardrails: [needsRole("LPOA_SIGNING_OFFICER", "9.7 human touchpoint: the signing officer endorses physical instruments under the LPOA", (i) => flag(i, "endorse"), ["signing_officer"], "endorsement is a signing-officer act")] },
  { name: "depositInstrument", kind: "act", moneyFields: ["amount_cents"], handler: compute((i, ctx) => { need(i, "instrument_id", "amount_cents"); ctx.events.append({ type: "claim.proceeds.deposited", loanId: ctx.loanId, actor: ctx.actor, payload: { instrument_id: str(i, "instrument_id"), amount_cents: cents(i.amount_cents), account: "custodial_ti_loss_draft" } }); return { deposited: true, account: "custodial_ti_loss_draft", escrow_event: "loss_draft" }; }) },
  { name: "releaseFunds", kind: "act", moneyFields: ["amount_cents"], handler: compute((i, ctx) => { need(i, "amount_cents", "kind"); ctx.events.append({ type: "claim.funds.released", loanId: ctx.loanId, actor: ctx.actor, payload: { kind: str(i, "kind"), amount_cents: cents(i.amount_cents) } }); return { released_cents: cents(i.amount_cents), kind: str(i, "kind") }; }),
    guardrails: [never("RELEASE_WITHIN_FORMULA", "9.7 guardrail: releases cannot exceed formula limits", (i) => { if (str(i, "kind") === "initial" && i.total_cents !== undefined) return cents(i.amount_cents) > initialRelease(release(i)).cents; if (str(i, "kind") === "progress" && i.total_cents !== undefined) { const r = release(i); return r.track === "delinquent_31plus" ? cents(i.amount_cents) > progressReleaseDelinquent(r.total_cents, cents(i.released_so_far_cents), flag(i, "inspected"), flag(i, "final_inspection")).cents : cents(i.amount_cents) > progressReleaseCurrent(r.total_cents, cents(i.initial_cents), cents(i.released_so_far_cents), str(i, "pct_complete") || "0"); } return false; }, "the release exceeds the formula limit"),
      never("INSPECTION_REQUIRED", "9.7 guardrail: no release without the required inspection", (i) => str(i, "kind") === "progress" && str(i, "track") === "delinquent_31plus" && !flag(i, "inspected"), "a progress release on a delinquent loan needs an inspection"),
      never("NO_NETTING", "9.7 guardrail: no netting of servicer expenses", (i) => flag(i, "net_servicer_expenses"), "servicer expenses are never netted from proceeds"),
      never("THIRD_PARTY_NEEDS_FNMA_APPROVAL", "9.7 guardrail: no third-party fee payment without a recorded Fannie Mae approval", (i) => str(i, "payee_kind") === "third_party" && !thirdPartyReleaseAllowed(flag(i, "fnma_approval_recorded")), "Form 176 approval required")] },
  { name: "orderRepairInspection", kind: "act", handler: compute((i, ctx) => { need(i, "loan_id"); ctx.events.append({ type: "property.inspection.ordered", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { kind: "repair", cap_cents: 6000n } }); return { ordered: true, cap_cents: 6000n }; }) },
  { name: "verifyRemoteInspection", kind: "read", handler: compute((i) => { const m = i.media as { app_captured: boolean; gps: boolean; timestamp: boolean; hash: boolean } | undefined; if (!m) throw new RangeError("media is required"); const ok = remoteInspectionAcceptable(m); return { acceptable: ok, fallback: ok ? null : "order a vendor inspection ($60 cap)" }; }) },
  { name: "prepareForm176", kind: "write", handler: compute((i, ctx, rt) => { need(i, "loan_id", "learned_on"); const rec = rt.store.put("form_176_packages", `f176-${str(i, "loan_id")}-${ctx.now}`, { loan_id: str(i, "loan_id"), due: form176Due(date(i, "learned_on")), status: "draft", send_by: "fnma_portal_operator" }, ctx.actor, ctx.now); return { id: rec.id, ...rec.data }; }),
    guardrails: [needsRole("PORTAL_OPERATOR_SENDS", "9.7 human touchpoint: fnma_portal_operator sends Form 176/uploads", (i) => flag(i, "submit"), ["fnma_portal_operator"], "the agent prepares; the portal operator submits")] },
  { name: "remitProceeds332", kind: "act", moneyFields: ["amount_cents"], handler: compute((i, ctx) => { need(i, "amount_cents", "reogram_confirmed_on"); ctx.events.append({ type: "remittances.instructed", loanId: ctx.loanId, actor: ctx.actor, payload: { crs_code: "332", amount_cents: cents(i.amount_cents) } }); return { crs_code: "332", amount_cents: cents(i.amount_cents), due: reogramRemitDue(date(i, "reogram_confirmed_on")) }; }),
    guardrails: [never("NO_NETTING_332", "9.7 rule 9: never net servicer fees from remitted proceeds", (i) => flag(i, "net_servicer_fees"), "remit gross proceeds")] },
  { name: "applyToUpb", kind: "act", moneyFields: ["proceeds_cents"], handler: compute((i, ctx) => { need(i, "proceeds_cents", "payoff_cents"); const d = notRebuildableDisposition(cents(i.proceeds_cents), cents(i.payoff_cents)); ctx.events.append({ type: "payment.curtailment", loanId: ctx.loanId, actor: ctx.actor, payload: { amount_cents: d.curtailment_cents, source: "loss_draft_not_rebuildable" } }); return d; }) },
  { name: "openWorkoutEvaluation", kind: "write", handler: compute((i, ctx, rt) => { need(i, "loan_id"); const rec = rt.store.put("cases", `wo-${str(i, "loan_id")}-${ctx.now}`, { loan_id: str(i, "loan_id"), case_type: "lossmit_evaluation", trigger: "loss_draft_delinquent_track" }, ctx.actor, ctx.now); return { id: rec.id }; }) },
  { name: "escalate", kind: "act", handler: escalate("officer"), decision: (i) => ({ action: "escalate", rationale: str(i, "reason") || "claim escalation" }) },
]);
const p98 = defineTools("9.8", A, [
  { name: "computeInspectionSchedule", kind: "read", handler: compute((i) => { const w = inspectionWindow(date(i, "earliest_unpaid_due")); const e = i.exception as ExceptionInput | undefined; return { ...w, mode: inspectionMode({ conventional_first_lien: i.conventional_first_lien !== false, recourse: flag(i, "recourse"), enrolled: flag(i, "enrolled"), fnma_rejected: flag(i, "fnma_rejected") }), suspended: e ? inspectionSuspended(e, date(i, "today")) : false, next: i.last_completed ? nextInspectionWindow(D(str(i, "last_completed"))) : null }; }) },
  { name: "orderInspection", kind: "act", handler: compute((i, ctx) => { need(i, "loan_id", "type"); ctx.events.append({ type: "property.inspection.ordered", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { type: str(i, "type"), purpose: str(i, "purpose") || "delinquency" } }); return { ordered: true, type: str(i, "type"), instruction: "inspectors never discuss the debt" }; }),
    guardrails: [never("NO_ORDER_BEFORE_DAY90", "9.8 guardrail: no order before day 90 except vacancy checks", (i) => num(i, "day") < 90 && str(i, "purpose") !== "vacancy_confirmation", "the first inspection is ordered at day 90"),
      never("INTERIOR_NEEDS_VACANCY_AND_ENTRY", "9.8 guardrail: no interior inspection without confirmed vacancy and a permitted-entry jurisdiction rule", (i) => str(i, "type") === "interior" && !(flag(i, "vacancy_confirmed") && flag(i, "interior_entry_allowed")), "interior inspections need confirmed vacancy and permitted entry"),
      never("CURBSIDE_NEEDS_REASON", "9.8 guardrail: curbside only with a recorded reason", (i) => str(i, "type") === "curbside" && !i.legal_constraint_reason, "record the legal-constraint/danger reason")] },
  { name: "evaluateInspectionResult", kind: "read", handler: compute((i) => { need(i, "result"); const r = i.result as { indicators: string[]; certification_signed: boolean; photos: number }; const vacant = r.indicators.filter((x) => /utilities_off|mail_piling|no_furnishings|neighbor_vacant|posting_unanswered/.test(x)).length >= 2; return { occupancy: vacant ? (r.certification_signed ? "vacant" : "vacancy_suspected") : "occupied", confidence: vacant ? 0.9 : 0.8, type_next: inspectionType({ vacant, interior_entry_allowed: flag(i, "interior_entry_allowed"), legal_constraint_reason: (i.legal_constraint_reason as string | undefined) ?? null }) }; }) },
  { name: "updateOccupancy", kind: "write", handler: compute((i, ctx, rt) => { need(i, "loan_id", "occupancy"); if (str(i, "occupancy") === "vacant") { const v = vacancyConfirmed({ inspected_on: date(i, "inspected_on"), certification_signed: flag(i, "certification_signed"), pfpip: flag(i, "pfpip") }); rt.store.put("properties", str(i, "loan_id"), { occupancy_status: "vacant" }, ctx.actor, ctx.now); ctx.events.append({ type: "property.vacancy_confirmed", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { inspected_on: str(i, "inspected_on") } }); return v; } rt.store.put("properties", str(i, "loan_id"), { occupancy_status: str(i, "occupancy") }, ctx.actor, ctx.now); return { occupancy: str(i, "occupancy") }; }),
    guardrails: [never("VACANT_NEEDS_CERTIFICATION", "9.8 guardrail: the agent cannot mark occupancy `vacant` without a signed certification", (i) => str(i, "occupancy") === "vacant" && !flag(i, "certification_signed"), "a signed inspector certification is required")] },
  notifyCarrierVacancy,
  { name: "submitPfpip", kind: "act", handler: compute((i, ctx) => { const r = pfpipSubmission({ earliest_unpaid_due: date(i, "earliest_unpaid_due"), package: data(i) }); if (!r.complete) throw new RangeError(`PFPIP package missing: ${r.missing_fields.join(", ")}`); ctx.events.append({ type: "pfpip.submitted", loanId: ctx.loanId, actor: ctx.actor, payload: { task_due: r.task_due } }); return r; }) },
  { name: "updatePfpip", kind: "act", handler: compute((i, ctx) => { need(i, "loan_id", "change"); ctx.events.append({ type: "pfpip.record.updated", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { change: str(i, "change"), due: pfpipTaskDue(date(i, "changed_on")) } }); return { updated: true, due: pfpipTaskDue(date(i, "changed_on")), permission: pfpipPermission({ bankruptcy_active: flag(i, "bankruptcy_active"), preserve_allowed: i.preserve_allowed !== false }) }; }) },
  { name: "reconcilePfpip", kind: "write", handler: compute((i) => { const ours = rows<{ loan_id: string; status: string }>(i, "platform"); const theirs = rows<{ loan_id: string; status: string }>(i, "fnma_report"); const deltas = ours.filter((o) => theirs.find((t) => t.loan_id === o.loan_id)?.status !== o.status).map((o) => ({ loan_id: o.loan_id, platform: o.status, fnma: theirs.find((t) => t.loan_id === o.loan_id)?.status ?? null, action: "update" })); return { deltas, in_sync: deltas.length === 0 }; }) },
  { name: "openPreservation", kind: "write", handler: compute((i, ctx, rt) => { need(i, "loan_id"); const rec = rt.store.put("preservation_cases", `pp-${str(i, "loan_id")}`, { loan_id: str(i, "loan_id"), mode: preservationMode({ pfpip: flag(i, "pfpip"), permission: str(i, "permission"), chapter13_active: flag(i, "chapter13_active") }), status: "open" }, ctx.actor, ctx.now); return { id: rec.id, ...rec.data }; }) },
  openClaim,
  { name: "sendNotice", kind: "act", handler: noticeOps("render_send") },
]);
const p99 = defineTools("9.9", A, [
  { name: "buildInitialScope", kind: "read", handler: compute((i) => { const flags = rows<string>(i, "condition_flags"); const items: WorkItem[] = []; const add = (kind: WorkItem["kind"], qty: number, cost: bigint, measure?: number) => items.push({ kind, qty, unit_cost_cents: cost, ...(measure !== undefined ? { measure } : {}) });
      if (flags.includes("lock_change")) add("lock_change", 1, 6000n); const w = flags.filter((f) => f === "broken_window").length; if (w) add("boarding", w, 18500n); if (flags.includes("lawn")) add("yard_initial", 1, 15000n); const cy = num(i, "debris_cy"); if (cy > 0) add("debris", cy, 5000n, cy); if (flags.includes("winterization")) add("winterization", 1, 22000n); add("posting", 1, 5000n);
      return { work_items: items, ...evaluateScope(items) }; }),
    guardrails: [never("NO_ENTRY_WITHOUT_VACANCY", "9.9 guardrail: no entry unless vacancy is confirmed (signed certification) and entry is permitted for the jurisdiction", (i) => !(flag(i, "vacancy_confirmed") && flag(i, "entry_permitted")), "confirmed vacancy and permitted entry are prerequisites")] },
  { name: "checkAllowables", kind: "read", handler: compute((i) => evaluateScope(rows<WorkItem>(i, "items"))) },
  { name: "orderWork", kind: "act", moneyFields: ["cost_cents"], handler: compute((i, ctx) => { need(i, "loan_id"); const s = evaluateScope(rows<WorkItem>(i, "items")); ctx.events.append({ type: "preservation.work.ordered", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { total_cents: s.total_cents } }); return { ordered: true, total_cents: s.total_cents, prior_approval_required: s.prior_approval_required }; }),
    guardrails: [never("NO_OVER_ALLOWABLE_WITHOUT_APPROVAL", "9.9 guardrail: no over-allowable work without a Fannie Mae approval record except Matrix-permitted BATF", (i) => { try { return evaluateScope(rows<WorkItem>(i, "items")).items.some((x) => x.disposition === "stop_and_bid") && !i.fnma_approval_id; } catch { return false; } }, "stop and bid; order only with the approval record"),
      never("NO_BORROWER_CHARGE_PFPIP", "9.9 guardrail: costs never charged to the borrower on PFPIP loans or where the contract/state law prohibits", (i) => flag(i, "charge_borrower") && (flag(i, "pfpip") || flag(i, "charge_prohibited")), "preservation costs are not borrower charges here"),
      never("NEUTRAL_POSTING", "9.9 guardrail: neutral postings", (i) => /debt|delinquen|foreclos|owe/i.test(str(i, "posting_text")), "postings carry contact information only")] },
  { name: "reviewCompletion", kind: "read", handler: compute((i) => { const photos = rows<{ stage: string; taken_on: string }>(i, "photos"); const stages = new Set(photos.map((p) => p.stage)); const missing = ["before", "during", "after"].filter((s) => !stages.has(s)); return { complete: missing.length === 0 && flag(i, "haul_away_evidence"), missing, fresh: photos.every((p) => photosFresh(D(p.taken_on), date(i, "submitted_on"))) }; }) },
  { name: "prepareBid", kind: "write", handler: compute((i, ctx, rt) => { need(i, "loan_id", "discovered_on"); const rec = rt.store.put("preservation_bids", `bid-${str(i, "loan_id")}-${ctx.now}`, { loan_id: str(i, "loan_id"), form: "1095", items: i.items ?? [], due: bidDue(date(i, "discovered_on")), submit_via: "HomeTracker (fnma_portal_operator)" }, ctx.actor, ctx.now); return { id: rec.id, ...rec.data }; }) },
  { name: "fileRegistration", kind: "act", moneyFields: ["fee_cents"], handler: compute((i, ctx) => { const r = i.rule as { within_days: number; renewal_months: number | null } | undefined; if (!r) throw new RangeError("rule is required"); const reg = vacantRegistration({ trigger_on: date(i, "trigger_on"), rule: r, fee_cents: cents(i.fee_cents) }); ctx.events.append({ type: "preservation.registration.filed", loanId: ctx.loanId, actor: ctx.actor, payload: { file_by: reg.file_by, fee_cents: reg.fee_claim_cents } }); return reg; }) },
  notifyCarrierVacancy,
  openClaim,
]);

export const SECTION_09_TOOLS: readonly ToolDef[] = [...p91, ...p92, ...p93, ...p94, ...p95, ...p96, ...p97, ...p98, ...p99];
export const placementScreen = placementConfig;
export const fpiClockCheck = fpiClocks;
export const chargeGate = chargeDecision;
export const refundClock = refundTimeline;
