/**
 * §26.4 process-owned tools — bus tools for 26.4 defined with `defineTools("26.4", "post-closing", defs)` from
 * ../tools.ts. Every tool string must be one spec/registry/agents.json names for 26.4; src/app/tools.test.ts refuses
 * the rest. Spread by ./index.ts.
 *
 * The registry extracts two strings from the agent paragraph — `computeMersAnchor` and `registerMin` (the extractor stops
 * at the MERS-adapter argument list) — so the whole paragraph rides on them: `computeMersAnchor` is the read side
 * (anchor / assignments / shipment plan / follow-up schedule / certification and endorsement gates / decision record) and
 * `registerMin` is the act side whose `op` switches over registration (register | pre_close | update_interim_funder |
 * reverse | deactivate | record_assignment), endorsement and custody (ensure_endorsement | prepare_shipment | track_shipment |
 * ingest_trust_receipt | open_trace | handle_lost_note | decide_lost_note | open_custodian_exception | cure_custodian_exception |
 * exception_breach), trailing documents (expect_trailing_documents | open_trailing_document | receive_trailing_document |
 * close_trailing_document | waive_trailing_document | follow_up | sweep | ingest_recorded_image | review_recorded_instrument |
 * request_rerecording | ingest_final_policy | review_final_policy | request_policy_correction | record_corrected_policy),
 * custody reconciliation (daily_enote_check | open_reconciliation | reconcile_eregistry | reconcile_mers_system), the cancelled-loan
 * trail (void_collateral) and the decision row (write_decision). Every act goes through the pure rules in
 * src/domain/closing/ops-26-4.ts, which append the events the 26.4 timers arm on. Entity-store kinds mirror migration 0096:
 * mers_registrations, note_endorsements, note_custody_shipments, lost_note_affidavits, recorded_instrument_reviews,
 * final_policy_reviews, trailing_documents, custody_records, mers_transactions. Guardrails encode the paragraph: never signs
 * an endorsement/allonge/assignment/LNA; never an Investor other than the partner pre-purchase or SM as Servicer; never SM or
 * Fannie Mae as endorsee; never a shipment without a bailee letter / to an unlisted address / a copy for an original; never
 * closes without a passed review; never waives (officer); never a Transfer of Control; never converts an eNote to paper.
 */
import { defineTools, compute, decision, never, needsRole, port, cents, str, flag, type ToolDef, type ToolInput, type ToolRuntime } from "../tools.ts";
import type { CommandContext } from "../commands.ts";
import type { Actor } from "../../kernel/events/index.ts";
import { plainDate as D, type PlainDate } from "../../kernel/calendar/date.ts";
import type { EscalationKind } from "../escalations.ts";
import {
  SM_ORG_ID, FANNIE_MAE_ORG_ID, RULE_SETS, PostClosingRefused, computeMersAnchor, registrationTimeliness, draftRegistration, validateRegistration, registerMin, preCloseRegisterMin, updateMinInterimFunder, submitMinReversal, deactivateMin,
  ensureEndorsement, endorsementText, decideAssignments, recordAssignmentExecuted, assignmentPopulationCheck, shipmentPlan, prepareShipment, trackShipment, ingestTrustReceipt, openTrace, handleLostNote, decideLostNote, lnaComplete,
  recordCustodianException, cureCustodianException, custodyCertifiable, custodianExceptionBreach, expectTrailingDocuments, openTrailingDocument, receiveTrailingDocument, closeTrailingDocument, waiveTrailingDocument, followUp, followupSchedule, sweepTrailingDocuments,
  ingestRecordedImage, reviewRecordedInstrument, recordRecordedInstrumentReview, requestRerecording, ingestFinalPolicy, reviewFinalPolicy, recordFinalPolicyReview, requestPolicyCorrection, recordCorrectedPolicy,
  dailyEnoteHashCheck, openMonthlyReconciliation, reconcileEregistry, reconcileMersSystem, voidCollateral, decisionRecord,
  type MersAnchor, type MersAnchorInput, type MersRegistration, type NoteEndorsement, type NoteFacts, type NoteShipment, type LostNoteAffidavit, type CustodyState, type TrailingDocument, type TrailingProfile, type RecordedImageInput, type RecordedInstrumentReview, type FinalPolicyInput, type FinalPolicyExpectations, type FinalPolicyReview,
  type EnoteCustodyFacts, type EregistryReconRow, type MersReconRow, type ScanKind, type CustodianExceptionCode, type LnaDecision, type TrailingKind, type EndorsementMethod,
} from "../../domain/closing/ops-26-4.ts";

// ---- helpers ------------------------------------------------------------------
const need = (i: Record<string, unknown>, ...keys: string[]): void => { for (const k of keys) if (i[k] === undefined || i[k] === null || i[k] === "") throw new RangeError(`${k} is required`); };
const obj = (i: ToolInput, k: string): Record<string, unknown> => { const v = i[k]; if (!v || typeof v !== "object") throw new RangeError(`${k} is required`); return v as Record<string, unknown>; };
const optObj = (i: ToolInput, k: string): Record<string, unknown> | null => (i[k] && typeof i[k] === "object" ? (i[k] as Record<string, unknown>) : null);
const date = (v: unknown, what: string): PlainDate => { if (typeof v !== "string" || !v) throw new RangeError(`${what} is required`); return D(v.slice(0, 10)); };
const optDate = (v: unknown): PlainDate | null => (typeof v === "string" && v ? D(v.slice(0, 10)) : null);
const optStr = (v: unknown): string | null => (typeof v === "string" && v ? v : null);
const at = (i: ToolInput, ctx: CommandContext, k = "at"): string => str(i, k) || ctx.now;
const tz = (i: ToolInput): string => str(i, "time_zone") || "America/New_York";
const ser = (v: unknown): unknown => (typeof v === "bigint" ? String(v) : Array.isArray(v) ? v.map(ser) : v && typeof v === "object" ? Object.fromEntries(Object.entries(v as Record<string, unknown>).map(([k, x]) => [k, ser(x)])) : v);
const K = { registrations: "mers_registrations", endorsements: "note_endorsements", shipments: "note_custody_shipments", lnas: "lost_note_affidavits", siReviews: "recorded_instrument_reviews", policyReviews: "final_policy_reviews", trailing: "trailing_documents", custody: "custody_records", txns: "mers_transactions", documents: "documents" } as const;
const put = (rt: ToolRuntime, ctx: CommandContext, kind: string, id: string, data: unknown): void => { rt.store.put(kind, id, ser(data) as Record<string, unknown>, ctx.actor, ctx.now); };
const appId = (i: ToolInput, ctx: CommandContext): string => { const a = str(i, "application_id") || ctx.applicationId || ""; if (!a) throw new RangeError("application_id is required"); return a; };
const keys = (i: ToolInput, ctx: CommandContext) => ({ application_id: appId(i, ctx), loan_id: optStr(i.loan_id) ?? (ctx.loanId || null) });
const anchorInput = (i: ToolInput): MersAnchorInput => { need(i, "transaction_type", "state", "note_date"); return { transaction_type: str(i, "transaction_type") as MersAnchorInput["transaction_type"], state: str(i, "state"), escrow_state: flag(i, "escrow_state"), note_date: date(i.note_date, "note_date"), funding_date: optDate(i.funding_date), assignment_executed_on: optDate(i.assignment_executed_on), ...(i.mom_available !== undefined ? { mom_available: i.mom_available === true } : {}) }; };
function registrationOf(rt: ToolRuntime, i: ToolInput): MersRegistration { need(i, "min"); const r = rt.store.get(K.registrations, str(i, "min")); if (!r) throw new RangeError(`no mers_registration ${str(i, "min")}`); return r.data as unknown as MersRegistration; }
function registrationOrDraft(rt: ToolRuntime, i: ToolInput, ctx: CommandContext): MersRegistration {
  need(i, "min"); const cur = rt.store.get(K.registrations, str(i, "min")); if (cur) return cur.data as unknown as MersRegistration;
  need(i, "partner_org_id"); const anchor = (optObj(i, "anchor") as unknown as MersAnchor | null) ?? computeMersAnchor(anchorInput(i));
  return draftRegistration({ min: str(i, "min"), application_id: appId(i, ctx), loan_id: optStr(i.loan_id), state: str(i, "state") || "", anchor, partner_org_id: str(i, "partner_org_id"), ...(optStr(i.investor_org_id) ? { investor_org_id: str(i, "investor_org_id") } : {}), ...(optStr(i.servicer_org_id) ? { servicer_org_id: str(i, "servicer_org_id") } : {}), ...(optStr(i.subservicer_org_id) ? { subservicer_org_id: str(i, "subservicer_org_id") } : {}),
    custodian_org_id: optStr(i.custodian_org_id), interim_funder_org_id: optStr(i.interim_funder_org_id), security_instrument_document_id: optStr(i.security_instrument_document_id), mers_rider: flag(i, "mers_rider"), assignment_to_mers_document_id: optStr(i.assignment_to_mers_document_id), ...(optStr(i.channel) ? { channel: str(i, "channel") as MersRegistration["channel"] } : {}) });
}
const txnRow = (rt: ToolRuntime, ctx: CommandContext, r: MersRegistration, kind: string, batchOn: PlainDate, status: string, response: unknown): void => put(rt, ctx, K.txns, `${r.min}:${kind}:${batchOn}`, { min: r.min, application_id: r.application_id, loan_id: r.loan_id, txn_type: kind, effective_date: batchOn, submitted_at: ctx.now, submitted_by_org_id: r.servicer_org_id, channel: r.channel, status, mers_response: response });
function noteFacts(i: ToolInput): NoteFacts { const n = obj(i, "note"); need(n, "note_date", "note_amount_cents", "property_address", "property_state", "partner_legal_name"); return { borrower_names: Array.isArray(n.borrower_names) ? (n.borrower_names as string[]) : [], note_date: date(n.note_date, "note.note_date"), note_amount_cents: cents(n.note_amount_cents), property_address: String(n.property_address), property_state: String(n.property_state), partner_legal_name: String(n.partner_legal_name) }; }
function endorsementOf(rt: ToolRuntime, i: ToolInput): NoteEndorsement | null {
  const e = optObj(i, "endorsement") ?? (str(i, "endorsement_id") ? rt.store.get(K.endorsements, str(i, "endorsement_id"))?.data ?? null : null); if (!e) return null;
  const id = e.allonge_identifiers as Record<string, unknown> | null | undefined;
  return { ...(e as unknown as NoteEndorsement), endorsement_text: String(e.endorsement_text ?? endorsementText(String(e.partner_legal_name ?? ""))), chain: Array.isArray(e.chain) ? (e.chain as NoteEndorsement["chain"]) : [], allonge_identifiers: id ? { borrower_names: (id.borrower_names as string[]) ?? [], note_date: date(id.note_date, "allonge.note_date"), note_amount_cents: cents(id.note_amount_cents), property_address: String(id.property_address ?? "") } : null };
}
function shipmentOf(rt: ToolRuntime, i: ToolInput): NoteShipment { need(i, "shipment_id"); const r = rt.store.get(K.shipments, str(i, "shipment_id")); if (!r) throw new RangeError(`no note_custody_shipment ${str(i, "shipment_id")}`); return r.data as unknown as NoteShipment; }
function trailingRows(rt: ToolRuntime, applicationId: string): TrailingDocument[] { return rt.store.list(K.trailing, (d) => d.application_id === applicationId).map((r) => r.data as unknown as TrailingDocument); }
function trailingOf(rt: ToolRuntime, i: ToolInput, ctx: CommandContext): TrailingDocument { const id = str(i, "trailing_document_id") || (str(i, "kind") ? `${appId(i, ctx)}:${str(i, "kind")}` : ""); if (!id) throw new RangeError("trailing_document_id (or kind) is required"); const r = rt.store.get(K.trailing, id); if (!r) throw new RangeError(`no trailing_document ${id}`); return r.data as unknown as TrailingDocument; }
function custodyOf(rt: ToolRuntime, i: ToolInput): CustodyState { need(i, "custody_record_id"); const r = rt.store.get(K.custody, str(i, "custody_record_id")); return { custody_record_id: str(i, "custody_record_id"), holder_role: ((r?.data.holder_role as CustodyState["holder_role"] | undefined) ?? (str(i, "holder_role") as CustodyState["holder_role"]) ?? "fcc_bailee"), custodian_exception_codes: (r?.data.custodian_exception_codes as string[] | undefined) ?? [], custodian_exception_cured_at: (r?.data.custodian_exception_cured_at as string | null | undefined) ?? null, certified_at: (r?.data.certified_at as string | null | undefined) ?? null }; }
const openEsc = (rt: ToolRuntime, ctx: CommandContext, kind: EscalationKind, ownerRole: string, severity: string, k: { application_id: string; loan_id: string | null }, payload: Record<string, unknown>) => rt.escalations.open({ kind, ownerRole, severity, applicationId: k.application_id, ...(k.loan_id ? { loanId: k.loan_id } : {}), payload }, ctx.actor);
const op = (i: ToolInput): string => str(i, "op");
const REGISTER_OPS = new Set(["", "register", "pre_close"]);

export const TOOLS_26_4: readonly ToolDef[] = defineTools("26.4", "post-closing", [
  // Read side: MERS anchor (rule 1), assignments (rule 3), the wet-note shipment plan (rule 4 / 27.1 arithmetic), the follow-up cadence, gates and the decision record.
  { name: "computeMersAnchor", kind: "read", handler: compute((i, ctx, rt) => {
      switch (op(i)) {
        case "assignments": need(i, "state"); return decideAssignments({ state: str(i, "state"), ...(i.mom_available !== undefined ? { mom_available: i.mom_available === true } : {}), ...(i.originator_is_servicer !== undefined ? { originator_is_servicer: i.originator_is_servicer === true } : {}) });
        case "assignment_population": return { offending: assignmentPopulationCheck((Array.isArray(i.rows) ? i.rows : rt.store.list("closing_documents").map((r) => ({ application_id: String(r.data.application_id ?? ""), state: String(r.data.state ?? ""), kind: String(r.data.kind ?? "") }))) as { application_id: string; state: string; kind: string }[]) };
        case "shipment_plan": return shipmentPlan(date(i.advance_date, "advance_date"));
        case "followup_schedule": return { dates: followupSchedule(date(i.due_at, "due_at"), date(i.through, "through")) };
        case "endorsement_gate": return ensureEndorsement(endorsementOf(rt, i), noteFacts(i));
        case "certification_gate": return custodyCertifiable(custodyOf(rt, i));
        case "lna_complete": return lnaComplete(obj(i, "lna") as unknown as LostNoteAffidavit);
        case "timeliness": { const r = registrationOf(rt, i); return registrationTimeliness(r, date(i.accepted_on, "accepted_on")); }
        case "decision_record": return decisionRecord({ application_id: appId(i, ctx), loan_id: optStr(i.loan_id), min: optStr(i.min), anchor: (optObj(i, "anchor") as unknown as MersAnchor | null) ?? null, action: str(i, "action") || "computeMersAnchor", rationale: str(i, "rationale"), ...(typeof i.confidence === "number" ? { confidence: i.confidence } : {}) });
        default: { const a = computeMersAnchor(anchorInput(i)); void ctx; return { ...a, rule_set: RULE_SETS.mers, policy_version: RULE_SETS.policy }; }
      }
    }) },
  // Act side: every MERS System transaction, the endorsement gate and shipment chain, custodian exceptions, the trailing-document engine, reconciliations, the cancelled-loan trail and the decision row — see the header for the `op` list.
  { name: "registerMin", kind: "act", ruleSetVersion: `${RULE_SETS.mers}+${RULE_SETS.fnma}+${RULE_SETS.policy}`, handler: compute(async (i, ctx, rt) => {
      const k = () => keys(i, ctx);
      switch (op(i)) {
        case "": case "register": {
          need(i, "min", "partner_org_id"); const r = registrationOrDraft(rt, i, ctx); const g = { partner_org_id: str(i, "partner_org_id"), purchased: flag(i, "purchased"), ...(i.mom_language_present !== undefined ? { mom_language_present: i.mom_language_present === true } : {}) };
          if (flag(i, "validate_only")) return validateRegistration(r, g);
          const res = await registerMin(ctx.events, port(rt, "mers"), r, g, { submitted_at: at(i, ctx, "submitted_at"), time_zone: tz(i) });
          put(rt, ctx, K.registrations, r.min, res.registration); txnRow(rt, ctx, r, "registration", res.batch_on, res.accepted ? "accepted" : "rejected", res.registration.mers_response);
          if (res.accepted && res.registration.loan_id) put(rt, ctx, "loans", res.registration.loan_id, { min: r.min, mers_registered_at: res.registration.registered_at });
          if (!res.accepted) openEsc(rt, ctx, "sev3", "post-closing", "sev3", k(), { reason: "mers_registration_rejected", min: r.min, codes: res.codes, action: "cure and resubmit the same day; the MERS deadline does not extend", registration_due_at: r.registration_due_at });
          return { min: r.min, accepted: res.accepted, codes: res.codes, batch_on: res.batch_on, batch_ref: res.batch_ref, status: res.registration.status, timeliness: res.timeliness, registration: ser(res.registration) };
        }
        case "pre_close": { need(i, "min", "partner_org_id"); const r = registrationOrDraft(rt, i, ctx); const res = preCloseRegisterMin(ctx.events, r, { partner_org_id: str(i, "partner_org_id") }, { at: at(i, ctx), time_zone: tz(i), enabled: flag(i, "pre_closing_registration") }); put(rt, ctx, K.registrations, r.min, res.registration); if (res.event) txnRow(rt, ctx, r, "pre_closing_registration", D(at(i, ctx).slice(0, 10)), "accepted", null); return { min: r.min, status: res.registration.status, skipped_reason: res.skipped_reason }; }
        case "update_interim_funder": { need(i, "min", "advance_id", "advance_funded_at", "advance_date"); const r = registrationOf(rt, i); const res = await updateMinInterimFunder(ctx.events, port(rt, "mers"), r, { advance_id: str(i, "advance_id"), advance_funded_at: str(i, "advance_funded_at"), advance_date: date(i.advance_date, "advance_date"), time_zone: tz(i), submitted_at: optStr(i.submitted_at) }); put(rt, ctx, K.registrations, r.min, res.registration); if (!res.already_set) txnRow(rt, ctx, r, "min_update_interim_funder", res.batch_on, "accepted", null); return { min: r.min, interim_funder_org_id: res.registration.interim_funder_org_id, batch_on: res.batch_on, due_on: res.due_on, on_time: res.on_time, already_set: res.already_set }; }
        case "reverse": { need(i, "min", "reason"); const r = registrationOf(rt, i); const res = await submitMinReversal(ctx.events, port(rt, "mers"), r, { reason: str(i, "reason"), submitted_at: at(i, ctx, "submitted_at"), time_zone: tz(i), due_on: optDate(i.due_on) ?? D(at(i, ctx, "submitted_at").slice(0, 10)) }); put(rt, ctx, K.registrations, r.min, res.registration); txnRow(rt, ctx, r, "registration_reversal", res.batch_on, "accepted", null); return { min: r.min, status: res.registration.status, batch_on: res.batch_on, on_time: res.on_time }; }
        case "deactivate": { need(i, "min", "reason"); const r = registrationOf(rt, i); const res = await deactivateMin(ctx.events, port(rt, "mers"), r, { reason: str(i, "reason"), submitted_at: at(i, ctx, "submitted_at"), time_zone: tz(i) }); put(rt, ctx, K.registrations, r.min, res.registration); txnRow(rt, ctx, r, "deactivation", res.batch_on, "accepted", null);
          const t = ctx.timers as unknown as { byCode(code: string): readonly { id: string; status: string; applicationId?: string }[]; cancel(id: string, reason: string, actor?: Actor): void }; let retired: string | null = null;
          for (const x of t.byCode("SM_O74_MIN_REVERSAL_2BD")) if ((x.status === "armed" || x.status === "breached") && x.applicationId === r.application_id) { t.cancel(x.id, `funded-then-unwound loan: MIN ${r.min} deactivated (${str(i, "reason")}) instead of reversed`, ctx.actor); retired = x.id; }
          return { min: r.min, status: res.registration.status, batch_on: res.batch_on, retired_reversal_timer_id: retired }; }
        case "record_assignment": { need(i, "state", "document_id", "executed_at", "signing_officer_party_id"); return recordAssignmentExecuted(ctx.events, k(), { state: str(i, "state"), document_id: str(i, "document_id"), executed_at: str(i, "executed_at"), time_zone: tz(i), signing_officer_party_id: str(i, "signing_officer_party_id") }); }
        // ---- endorsement and custody chain
        case "ensure_endorsement": { const e = endorsementOf(rt, i); if (e) put(rt, ctx, K.endorsements, e.id, e); const g = ensureEndorsement(e, noteFacts(i)); if (g.escalation) openEsc(rt, ctx, "signing_officer", "signing_officer", "sev3", k(), { reason: "endorsement_cure", detail: g.reason, route: g.route, sla: "2 business_days_creditor" }); return g; }
        case "prepare_shipment": { const s = obj(i, "shipment"); need(s, "shipment_id", "custody_record_id", "from_party_id", "to_party_id", "to_role", "carrier", "tracking_ref"); const e = endorsementOf(rt, i);
          const res = prepareShipment(ctx.events, k(), { shipment: { shipment_id: String(s.shipment_id), custody_record_id: String(s.custody_record_id), from_party_id: String(s.from_party_id), to_party_id: String(s.to_party_id), to_role: String(s.to_role) as NoteShipment["to_role"], bailee_letter_id: optStr(s.bailee_letter_id), carrier: String(s.carrier), tracking_ref: String(s.tracking_ref), contents: (Array.isArray(s.contents) ? s.contents : []) as NoteShipment["contents"], time_zone: tz(i) }, address_on_closing_instructions: flag(i, "address_on_closing_instructions"), endorsement: e, note: noteFacts(i), requested_at: at(i, ctx) });
          put(rt, ctx, K.shipments, res.shipment.shipment_id, res.shipment); if (e) put(rt, ctx, K.endorsements, e.id, e);
          if (res.gate.escalation) openEsc(rt, ctx, "signing_officer", "signing_officer", "sev3", k(), { reason: "replacement_allonge_or_endorsement", detail: res.gate.reason, route: res.gate.route, shipment_id: res.shipment.shipment_id, sla: "2 business_days_creditor" });
          return { shipment_id: res.shipment.shipment_id, status: res.shipment.status, to_role: res.shipment.to_role, gate: res.gate, refusal: res.refusal }; }
        case "track_shipment": { need(i, "scan_kind", "scan_at"); const s = shipmentOf(rt, i); const res = trackShipment(ctx.events, k(), s, { kind: str(i, "scan_kind") as ScanKind, at: str(i, "scan_at"), location: optStr(i.location), code: optStr(i.code) }); put(rt, ctx, K.shipments, s.shipment_id, res.shipment); if (res.shipment.status === "in_transit" || res.shipment.status === "delivered") put(rt, ctx, K.custody, s.custody_record_id, { holder_role: res.shipment.status === "in_transit" ? "courier" : s.to_role, chain_last: { tracking_ref: s.tracking_ref, at: str(i, "scan_at") } }); return { shipment_id: s.shipment_id, status: res.shipment.status, transit_due_on: res.transit_due_on, trust_receipt_due_on: res.trust_receipt_due_on }; }
        case "ingest_trust_receipt": { need(i, "receipt_id", "received_at", "trust_receipt_document_id"); const s = shipmentOf(rt, i); const res = ingestTrustReceipt(ctx.events, k(), s, { receipt_id: str(i, "receipt_id"), received_at: str(i, "received_at"), trust_receipt_document_id: str(i, "trust_receipt_document_id"), custodian_loan_id: optStr(i.custodian_loan_id), advance_id: optStr(i.advance_id) }); put(rt, ctx, K.shipments, s.shipment_id, res.shipment); put(rt, ctx, K.custody, s.custody_record_id, { holder_role: res.holder_role, holding_for_party_id: "sm", trust_receipt_document_id: str(i, "trust_receipt_document_id"), custodian_loan_id: optStr(i.custodian_loan_id), original_received_at: str(i, "received_at"), bailee_letter_id: s.bailee_letter_id }); return { shipment_id: s.shipment_id, status: res.shipment.status, holder_role: res.holder_role, collateral_status: "secured_possession" }; }
        case "open_trace": { const s = shipmentOf(rt, i); const res = openTrace(ctx.events, k(), s, { at: at(i, ctx), claim_ref: optStr(i.claim_ref) }); put(rt, ctx, K.shipments, s.shipment_id, res.shipment); openEsc(rt, ctx, "settlement_agent", "settlement_agent", "sev3", k(), { reason: "shipment_attestation", shipment_id: s.shipment_id, tracking_ref: s.tracking_ref, sla: "2 business_days" }); return { shipment_id: s.shipment_id, status: res.shipment.status, lost_determination_on: res.lost_determination_on }; }
        case "handle_lost_note": { need(i, "lna_id"); const s = shipmentOf(rt, i); const res = handleLostNote(ctx.events, k(), s, { determined_at: at(i, ctx), search_evidence_document_ids: (Array.isArray(i.search_evidence_document_ids) ? i.search_evidence_document_ids : []) as string[], courier_claim_ref: optStr(i.courier_claim_ref), lna_id: str(i, "lna_id") }); put(rt, ctx, K.shipments, s.shipment_id, res.shipment); put(rt, ctx, K.lnas, res.lna.id, res.lna); put(rt, ctx, K.custody, s.custody_record_id, { lost_note: true, holder_role: "courier" }); openEsc(rt, ctx, "officer", "officer", "sev1", k(), { reason: "lost_note_decision", lna_id: res.lna.id, decision_due_on: res.decision_due_on, default: "re_execute + LNA for the lost original", sla: "2 business_days" }); return { lna_id: res.lna.id, status: res.shipment.status, decision_due_on: res.decision_due_on, warehouse_effect: res.lna.warehouse_effect }; }
        case "decide_lost_note": { need(i, "lna_id", "decision"); const l = rt.store.get(K.lnas, str(i, "lna_id"))?.data as unknown as LostNoteAffidavit | undefined; if (!l) throw new RangeError(`no lost_note_affidavit ${str(i, "lna_id")}`); const res = decideLostNote(ctx.events, k(), l, { decision: str(i, "decision") as Exclude<LnaDecision, "pending">, decided_by: ctx.actor, decided_at: at(i, ctx), borrower_can_reexecute: flag(i, "borrower_can_reexecute"), rationale: str(i, "rationale") }); put(rt, ctx, K.lnas, l.id, res.lna); if (res.lna.decision !== "lna") openEsc(rt, ctx, "human_agent", "human_agent", "sev3", k(), { reason: "borrower_reexecution_outreach", lna_id: l.id }); openEsc(rt, ctx, "signing_officer", "signing_officer", "sev2", k(), { reason: res.lna.decision === "re_execute" ? "replacement_note_package" : "lna_execution", lna_id: l.id, sla: "2 business_days_creditor" }); return { lna_id: l.id, decision: res.lna.decision }; }
        case "record_lna": { need(i, "lna_id"); const l = rt.store.get(K.lnas, str(i, "lna_id"))?.data as unknown as LostNoteAffidavit | undefined; if (!l) throw new RangeError(`no lost_note_affidavit ${str(i, "lna_id")}`); const out: LostNoteAffidavit = { ...l, lna_document_id: optStr(i.lna_document_id) ?? l.lna_document_id, executed_by_party_id: optStr(i.executed_by_party_id) ?? l.executed_by_party_id, notarized_at: optStr(i.notarized_at) ?? l.notarized_at, indemnity_text_ok: i.indemnity_text_ok === undefined ? l.indemnity_text_ok : flag(i, "indemnity_text_ok"), note_description_ok: i.note_description_ok === undefined ? l.note_description_ok : flag(i, "note_description_ok"), note_copy_attached: i.note_copy_attached === undefined ? l.note_copy_attached : flag(i, "note_copy_attached"), fnma_position: (optStr(i.fnma_position) as LostNoteAffidavit["fnma_position"] | null) ?? l.fnma_position, replacement_note_document_id: optStr(i.replacement_note_document_id) ?? l.replacement_note_document_id, replacement_note_signed_at: optStr(i.replacement_note_signed_at) ?? l.replacement_note_signed_at };
          const c = lnaComplete(out); const cured: LostNoteAffidavit = { ...out, warehouse_effect: c.complete || !!out.replacement_note_document_id ? "cured" : out.warehouse_effect }; put(rt, ctx, K.lnas, l.id, cured); if (out.lna_document_id && out.lna_document_id !== l.lna_document_id) ctx.events.append({ type: "note.lna.executed", applicationId: k().application_id, actor: ctx.actor, payload: { application_id: k().application_id, lna_id: l.id, executed_by_party_id: out.executed_by_party_id, notarized_at: out.notarized_at, complete: c.complete, missing: c.missing } }); if (out.replacement_note_document_id && out.replacement_note_document_id !== l.replacement_note_document_id) ctx.events.append({ type: "note.reexecuted", applicationId: k().application_id, actor: ctx.actor, payload: { application_id: k().application_id, lna_id: l.id, replacement_note_document_id: out.replacement_note_document_id, signed_at: out.replacement_note_signed_at, legend: "REPLACEMENT NOTE — original lost; this note replaces and does not add to the obligation" } }); return { lna_id: l.id, ...c, warehouse_effect: cured.warehouse_effect }; }
        case "open_custodian_exception": { need(i, "custody_record_id", "code", "notice_document_id"); const c = custodyOf(rt, i); const res = recordCustodianException(ctx.events, k(), c, { code: str(i, "code") as CustodianExceptionCode, recorded_at: at(i, ctx, "recorded_at"), time_zone: tz(i), notice_document_id: str(i, "notice_document_id"), advance_id: optStr(i.advance_id), description: optStr(i.description) }); put(rt, ctx, K.custody, c.custody_record_id, res.custody); if (res.cure_owner === "signing_officer") openEsc(rt, ctx, "signing_officer", "signing_officer", "sev3", k(), { reason: "custodian_exception_cure", code: str(i, "code"), cure_due_on: res.cure_due_on, sla: "2 business_days_creditor" }); return { custody_record_id: c.custody_record_id, codes: res.custody.custodian_exception_codes, cure_due_on: res.cure_due_on, cure_owner: res.cure_owner, certifiable: custodyCertifiable(res.custody) }; }
        case "cure_custodian_exception": { need(i, "custody_record_id", "code", "evidence_document_id", "evidence_kind"); const c = custodyOf(rt, i); const res = cureCustodianException(ctx.events, k(), c, { code: str(i, "code") as CustodianExceptionCode, cured_at: at(i, ctx, "cured_at"), time_zone: tz(i), evidence_document_id: str(i, "evidence_document_id"), evidence_kind: str(i, "evidence_kind"), delivered_by: ctx.actor, advance_id: optStr(i.advance_id) }); put(rt, ctx, K.custody, c.custody_record_id, res.custody); return { custody_record_id: c.custody_record_id, codes: res.custody.custodian_exception_codes, certifiable: custodyCertifiable(res.custody) }; }
        case "exception_breach": { need(i, "custody_record_id"); const c = custodyOf(rt, i); const res = custodianExceptionBreach(ctx.events, k(), c, at(i, ctx)); const ids = res.escalations.map((e) => openEsc(rt, ctx, e.kind, e.owner_role, e.severity, k(), { reason: "custodian_exception_uncured", codes: c.custodian_exception_codes, blocks: "custody.certified (29.4)" }).id); return { custody_record_id: c.custody_record_id, escalation_ids: ids, certifiable: custodyCertifiable(c) }; }
        // ---- trailing documents
        case "expect_trailing_documents": { need(i, "funded_on", "note_date", "state", "note_form"); const rec = optObj(i, "recording"); const p: TrailingProfile = { application_id: appId(i, ctx), loan_id: optStr(i.loan_id) ?? (ctx.loanId || null), funded_on: date(i.funded_on, "funded_on"), note_date: date(i.note_date, "note_date"), state: str(i, "state"), note_form: str(i, "note_form") as "enote" | "paper", ltv_pct: Number(i.ltv_pct ?? 0), flood_lol_on_file: flag(i, "flood_lol_on_file"), recording: rec ? { channel: String(rec.channel) as "erecording" | "paper", recorded_on: optDate(rec.recorded_on), submitted_on: optDate(rec.submitted_on), recording_turnaround_days: rec.recording_turnaround_days === undefined ? null : Number(rec.recording_turnaround_days) } : null, poa_recording_required: flag(i, "poa_recording_required"), subordination_required: flag(i, "subordination_required"), cema: flag(i, "cema"), tx_50a6: flag(i, "tx_50a6"), aol: flag(i, "aol"), prior_lien_release_informational: flag(i, "prior_lien_release_informational") };
          const res = expectTrailingDocuments(ctx.events, p, at(i, ctx)); for (const r of res.rows) put(rt, ctx, K.trailing, r.id, r); return { rows: res.rows.map((r) => ({ id: r.id, kind: r.kind, status: r.status, due_at: r.due_at, expected_from: r.expected_from })) }; }
        case "open_trailing_document": { const r = trailingOf(rt, i, ctx); const rec = obj(i, "recording"); const res = openTrailingDocument(ctx.events, r, { recording: { channel: String(rec.channel) as "erecording" | "paper", recorded_on: optDate(rec.recorded_on), submitted_on: optDate(rec.submitted_on), recording_turnaround_days: rec.recording_turnaround_days === undefined ? null : Number(rec.recording_turnaround_days) }, note_date: date(i.note_date ?? r.anchor_on, "note_date") }, at(i, ctx)); put(rt, ctx, K.trailing, r.id, res.row); return { id: r.id, status: res.row.status, due_at: res.row.due_at }; }
        case "receive_trailing_document": { need(i, "document_id"); const r = trailingOf(rt, i, ctx); const res = receiveTrailingDocument(ctx.events, r, { document_id: str(i, "document_id"), received_at: at(i, ctx, "received_at"), from_party_id: optStr(i.from_party_id) }); put(rt, ctx, K.trailing, r.id, res.row); return { id: r.id, status: res.row.status }; }
        case "close_trailing_document": { const r = trailingOf(rt, i, ctx); const res = closeTrailingDocument(ctx.events, trailingRows(rt, r.application_id), r, at(i, ctx)); put(rt, ctx, K.trailing, r.id, res.row); if (res.file_complete && r.loan_id) put(rt, ctx, "loans", r.loan_id, { collateral_file_complete_at: at(i, ctx) }); return { id: r.id, status: res.row.status, file_complete: res.file_complete }; }
        case "waive_trailing_document": { need(i, "reason"); const r = trailingOf(rt, i, ctx); const res = waiveTrailingDocument(ctx.events, r, { by: ctx.actor, reason: str(i, "reason"), at: at(i, ctx) }); put(rt, ctx, K.trailing, r.id, res.row); return { id: r.id, status: res.row.status, waived_by: res.row.waived_by }; }
        case "follow_up": { need(i, "channel", "to_party_id"); const r = trailingOf(rt, i, ctx); const res = followUp(ctx.events, r, { at: at(i, ctx), channel: str(i, "channel") as "portal" | "email" | "phone" | "vendor_api", to_party_id: str(i, "to_party_id"), response: optStr(i.response) }); put(rt, ctx, K.trailing, r.id, res.row); return { id: r.id, attempts: res.row.followups.length, next_at: res.row.followups.at(-1)!.next_at }; }
        case "sweep": { need(i, "today"); const rows = trailingRows(rt, appId(i, ctx)); const res = sweepTrailingDocuments(ctx.events, rows, date(i.today, "today"), at(i, ctx)); const esc = res.escalate_120.length ? openEsc(rt, ctx, "officer", "officer", "sev2", k(), { reason: "trailing_documents_open_120_days", kinds: res.escalate_120.map((r) => r.kind), qc_flag: "28.2" }) : null; for (const r of res.escalate_120) put(rt, ctx, K.trailing, r.id, { ...r, escalation_id: esc?.id ?? r.escalation_id, blocks: [...new Set([...r.blocks, "qc_file"])] }); return { overdue: res.overdue.map((e) => e.payload.kind), escalate_120: res.escalate_120.map((r) => r.kind), certified_copy_180: res.certified_copy_180.map((r) => r.kind), escalation_id: esc?.id ?? null, qc_flagged: res.escalate_120.length > 0 }; }
        case "ingest_recorded_image": { need(i, "recording_id", "document_id", "received_at"); const r = trailingOf(rt, { ...i, kind: str(i, "kind") || "recorded_security_instrument" }, ctx); const res = ingestRecordedImage(ctx.events, r, { recording_id: str(i, "recording_id"), document_id: str(i, "document_id"), received_at: str(i, "received_at"), time_zone: tz(i), certified_copy: flag(i, "certified_copy"), instrument_number: optStr(i.instrument_number) }); put(rt, ctx, K.trailing, r.id, res.row); put(rt, ctx, K.documents, str(i, "document_id"), { kind: "recorded_instrument", application_id: r.application_id, retention_class: "fnma_loan_file_life_plus_4y" }); return { id: r.id, status: res.row.status, review_due_on: res.review_due_on }; }
        case "review_recorded_instrument": { const img = obj(i, "image") as unknown as RecordedImageInput; need(img as unknown as Record<string, unknown>, "recording_id", "recorded_image_document_id"); const r = trailingOf(rt, { ...i, trailing_document_id: img.trailing_document_id ?? str(i, "trailing_document_id"), kind: str(i, "kind") || "recorded_security_instrument" }, ctx); const review = reviewRecordedInstrument({ ...img, trailing_document_id: r.id }); const res = recordRecordedInstrumentReview(ctx.events, r, review, { reviewed_at: at(i, ctx), time_zone: tz(i), title_underwriter_party_id: optStr(i.title_underwriter_party_id) }); put(rt, ctx, K.siReviews, res.review.id, res.review); put(rt, ctx, K.trailing, r.id, res.row); if (res.review.result === "defect") openEsc(rt, ctx, "settlement_agent", "settlement_agent", "sev3", k(), { reason: "recorded_instrument_defect", defect_kind: res.review.defect_kind, cure: res.review.cure, cure_due_on: res.cure_due_on }); if (res.review.result === "pass" && r.loan_id && img.instrument_number) put(rt, ctx, "loans", r.loan_id, { recorded_instrument_number: img.instrument_number }); return { review_id: res.review.id, result: res.review.result, defect_kind: res.review.defect_kind, cure: res.review.cure, checks: res.review.checks, cure_due_on: res.cure_due_on, title_underwriter_notified_at: res.review.title_underwriter_notified_at, status: res.row.status }; }
        case "request_rerecording": { need(i, "review_id", "package_ref"); const rv = rt.store.get(K.siReviews, str(i, "review_id"))?.data as unknown as RecordedInstrumentReview | undefined; if (!rv) throw new RangeError(`no recorded_instrument_review ${str(i, "review_id")}`); const r = trailingOf(rt, { ...i, trailing_document_id: rv.trailing_document_id }, ctx); const res = requestRerecording(ctx.events, r, rv, { submitted_at: at(i, ctx), time_zone: tz(i), package_ref: str(i, "package_ref"), ...(i.borrower_session_required !== undefined ? { borrower_session_required: flag(i, "borrower_session_required") } : {}) }); put(rt, ctx, K.siReviews, rv.id, res.review); return { review_id: rv.id, cure: rv.cure, cure_submitted_at: res.review.cure_submitted_at }; }
        case "ingest_final_policy": { need(i, "title_order_id", "document_id", "received_at"); const r = trailingOf(rt, { ...i, kind: str(i, "kind") || "final_title_policy" }, ctx); const res = ingestFinalPolicy(ctx.events, r, { title_order_id: str(i, "title_order_id"), document_id: str(i, "document_id"), received_at: str(i, "received_at"), time_zone: tz(i), from_party_id: optStr(i.from_party_id), policy_number: optStr(i.policy_number) }); put(rt, ctx, K.trailing, r.id, res.row); put(rt, ctx, K.documents, str(i, "document_id"), { kind: "final_title_policy", application_id: r.application_id, retention_class: "fnma_loan_file_life_plus_4y" }); return { id: r.id, status: res.row.status, review_due_on: res.review_due_on }; }
        case "review_final_policy": { const p = obj(i, "policy"); const x = obj(i, "expectations"); need(p, "title_order_id", "policy_kind", "policy_number", "date_of_policy", "insured_text", "amount_cents"); need(x, "partner_legal_name", "original_principal_cents", "originated_on"); const rec = obj(x, "recording");
          const r = trailingOf(rt, { ...i, trailing_document_id: optStr(p.trailing_document_id) ?? str(i, "trailing_document_id"), kind: str(i, "kind") || "final_title_policy" }, ctx);
          const input: FinalPolicyInput = { title_order_id: String(p.title_order_id), trailing_document_id: r.id, policy_kind: String(p.policy_kind) as FinalPolicyInput["policy_kind"], policy_number: String(p.policy_number), date_of_policy: String(p.date_of_policy), insured_text: String(p.insured_text), amount_cents: cents(p.amount_cents), schedule_a: (p.schedule_a as FinalPolicyInput["schedule_a"] | undefined) ?? { vesting_match: false, legal_description_match: false, instrument_number: null, recorded_on: null }, schedule_b: (p.schedule_b as FinalPolicyInput["schedule_b"] | undefined) ?? { expected_removed: [], present: [], new_exceptions: [] }, endorsements_issued: (p.endorsements_issued as string[] | undefined) ?? [], creditors_rights_exclusion_present: p.creditors_rights_exclusion_present === true, gap_exception_present: p.gap_exception_present === true };
          const exp: FinalPolicyExpectations = { partner_legal_name: String(x.partner_legal_name), original_principal_cents: cents(x.original_principal_cents), recording: { instrument_number: String(rec.instrument_number ?? ""), recorded_on: date(rec.recorded_on, "expectations.recording.recorded_on") }, required_endorsements: (x.required_endorsements as string[] | undefined) ?? [], tx_50a6: x.tx_50a6 === true, originated_on: date(x.originated_on, "expectations.originated_on") };
          const review = reviewFinalPolicy(input, exp); const res = recordFinalPolicyReview(ctx.events, r, review, { reviewed_at: at(i, ctx), time_zone: tz(i), underwriter_party_id: str(i, "underwriter_party_id") || "title_underwriter" }); put(rt, ctx, K.policyReviews, res.review.id, res.review); put(rt, ctx, K.trailing, r.id, res.row); if (res.review.result === "pass" && r.loan_id) put(rt, ctx, "loans", r.loan_id, { title_policy_number: review.policy_number });
          return { review_id: res.review.id, result: res.review.result, defects: res.review.defects, insured_ok: res.review.insured_ok, amount_ok: res.review.amount_ok, endorsements_ok: res.review.endorsements_ok, status: res.row.status, correction_requested_at: res.review.correction_requested_at, next_followup_on: res.row.followups.at(-1)?.next_at ?? null }; }
        case "request_policy_correction": { need(i, "review_id", "underwriter_party_id"); const rv = rt.store.get(K.policyReviews, str(i, "review_id"))?.data as unknown as FinalPolicyReview | undefined; if (!rv) throw new RangeError(`no final_policy_review ${str(i, "review_id")}`); const r = trailingOf(rt, { ...i, trailing_document_id: rv.trailing_document_id }, ctx); const res = requestPolicyCorrection(ctx.events, r, { ...rv, amount_cents: cents(rv.amount_cents) }, { requested_at: at(i, ctx), time_zone: tz(i), underwriter_party_id: str(i, "underwriter_party_id") }); put(rt, ctx, K.policyReviews, rv.id, res.review); put(rt, ctx, K.trailing, r.id, res.row); return { review_id: rv.id, next_followup_on: res.row.followups.at(-1)!.next_at }; }
        case "record_corrected_policy": { need(i, "review_id", "corrected_policy_document_id"); const rv = rt.store.get(K.policyReviews, str(i, "review_id"))?.data as unknown as FinalPolicyReview | undefined; if (!rv) throw new RangeError(`no final_policy_review ${str(i, "review_id")}`); const r = trailingOf(rt, { ...i, trailing_document_id: rv.trailing_document_id }, ctx); const res = recordCorrectedPolicy(ctx.events, r, { ...rv, amount_cents: cents(rv.amount_cents) }, { corrected_policy_document_id: str(i, "corrected_policy_document_id"), received_at: at(i, ctx, "received_at") }); put(rt, ctx, K.policyReviews, rv.id, res.review); put(rt, ctx, K.trailing, r.id, res.row); return { review_id: rv.id, status: res.row.status }; }
        // ---- eNote custody and reconciliations
        case "daily_enote_check": { const f = obj(i, "enote"); need(f, "enote_id", "min", "evault_hash", "eregistry_hash", "controller_org_id", "location_org_id"); const facts: EnoteCustodyFacts = { enote_id: String(f.enote_id), min: String(f.min), evault_hash: String(f.evault_hash), eregistry_hash: String(f.eregistry_hash), controller_org_id: String(f.controller_org_id), location_org_id: String(f.location_org_id), secured_party_org_id: optStr(f.secured_party_org_id), delegatee_org_id: optStr(f.delegatee_org_id), unexpected_notifications: (f.unexpected_notifications as string[] | undefined) ?? [] };
          const res = dailyEnoteHashCheck(ctx.events, k(), facts, { checked_at: at(i, ctx), advance_id: optStr(i.advance_id) }); const esc = res.escalation ? openEsc(rt, ctx, res.escalation.kind, "officer", res.escalation.severity, k(), { reason: "evault_eregistry_hash_mismatch", min: facts.min, enote_id: facts.enote_id, collateral_status: "defect", delivery_request_blocked: true }) : null; put(rt, ctx, "enotes", facts.enote_id, { min: facts.min, authoritative_copy_hash_verified_at: res.ok ? at(i, ctx) : null, custody_defect: !res.ok }); return { ok: res.ok, delivery_request_blocked: res.delivery_request_blocked, escalation_id: esc?.id ?? null, collateral_status: res.ok ? "secured_control" : "defect" }; }
        case "open_reconciliation": { need(i, "scope", "as_of"); const e = openMonthlyReconciliation(ctx.events, str(i, "scope") as "eregistry" | "mers_system", date(i.as_of, "as_of"), at(i, ctx)); return { scope: str(i, "scope"), as_of: e.payload.as_of, event_id: e.id }; }
        case "reconcile_eregistry": { need(i, "as_of"); const rows = (Array.isArray(i.rows) ? i.rows : []) as EregistryReconRow[]; const res = reconcileEregistry(ctx.events, rows, { as_of: date(i.as_of, "as_of"), at: at(i, ctx) }); for (const r of rows) put(rt, ctx, "enotes", r.min, { min: r.min, custody_reconciled_at: at(i, ctx) }); const esc = res.variances.length ? openEsc(rt, ctx, "officer", "officer", "sev2", { application_id: str(i, "application_id") || "population", loan_id: null }, { reason: "eregistry_reconciliation_variances", variances: res.variances }) : null; return { variances: res.variances.length, variance_rows: res.variances, escalation_id: esc?.id ?? null }; }
        case "reconcile_mers_system": { need(i, "as_of"); const rows = (Array.isArray(i.rows) ? i.rows : []) as MersReconRow[]; const res = reconcileMersSystem(ctx.events, rows, { as_of: date(i.as_of, "as_of"), at: at(i, ctx) }); for (const r of rows) { const cur = rt.store.get(K.registrations, r.min); if (cur) put(rt, ctx, K.registrations, r.min, { last_reconciled_at: at(i, ctx), reconciliation_variances: res.variances.filter((v) => v.min === r.min).map((v) => v.field) }); } const esc = res.variances.length ? openEsc(rt, ctx, "officer", "officer", "sev2", { application_id: str(i, "application_id") || "population", loan_id: null }, { reason: "mers_system_reconciliation_variances", variances: res.variances, cure_due_on: res.cure_due_on }) : null; return { variances: res.variances.length, variance_rows: res.variances, cure_due_on: res.cure_due_on, escalation_id: esc?.id ?? null }; }
        // ---- cancelled / unwound loans
        case "void_collateral": { need(i, "cause", "event_at", "note_form"); const reg = optStr(i.min) ? rt.store.get(K.registrations, str(i, "min"))?.data as unknown as MersRegistration | undefined : undefined; const rec = optObj(i, "recording");
          const plan = voidCollateral(ctx.events, { application_id: appId(i, ctx), loan_id: optStr(i.loan_id) ?? (ctx.loanId || null), cause: str(i, "cause") as "rescission_exercised" | "funding_cancelled" | "funding_unwound", event_at: str(i, "event_at"), time_zone: tz(i), funded: flag(i, "funded"), registration: reg ? { min: reg.min, status: reg.status } : null, note_form: str(i, "note_form") as "enote" | "paper", holder_role: (optStr(i.holder_role) as CustodyState["holder_role"] | null), recording: rec ? { recorded: rec.recorded === true, instrument_number: optStr(rec.instrument_number) } : null, trailing: trailingRows(rt, appId(i, ctx)) });
          for (const r of plan.rows) put(rt, ctx, K.trailing, r.id, r); if (optStr(i.custody_record_id)) put(rt, ctx, K.custody, str(i, "custody_record_id"), { holder_role: plan.note_action === "none" ? "released" : "released_pending", release_action: plan.note_action });
          const esc = plan.note_action === "form_2009_release_officer" ? openEsc(rt, ctx, "officer", "officer", "sev2", k(), { reason: "note_release_form_2009", action: plan.officer_actions[0], min: reg?.min ?? null }) : null;
          return { min_action: plan.min_action, reversal_due_on: plan.reversal_due_on, batch_on: plan.batch_on, note_action: plan.note_action, enote_action: plan.enote_action, release_tracked: plan.release_tracked, waived: plan.waived, officer_actions: plan.officer_actions, officer_escalation_id: esc?.id ?? null }; }
        case "write_decision": return decision()(i, ctx);
        default: throw new RangeError(`unknown op ${op(i)}`);
      }
    }),
    guardrails: [
      never("INVESTOR_NOT_PARTNER", "B8-7-01: a seller/servicer registering before delivery 'names itself as the investor' — never any other Investor before purchase", (i) => REGISTER_OPS.has(op(i)) && !flag(i, "purchased") && !!str(i, "investor_org_id") && !!str(i, "partner_org_id") && str(i, "investor_org_id") !== str(i, "partner_org_id"), "the Investor at registration is the partner's Org ID (Fannie Mae only after purchase)"),
      never("SM_NEVER_SERVICER", "26.4 guardrails: never register a MIN on an Org ID other than the partner's — SM is Subservicer / Interim Funder, never Servicer or Investor", (i) => REGISTER_OPS.has(op(i)) && (str(i, "servicer_org_id") === SM_ORG_ID || str(i, "investor_org_id") === SM_ORG_ID), `Servicer = partner Org ID; SM (${SM_ORG_ID}) is named only as Subservicer / Interim Funder`),
      never("INVESTOR_FNMA_BEFORE_PURCHASE", "B8-7-01: Fannie Mae is named as investor only for a registration after purchase", (i) => REGISTER_OPS.has(op(i)) && !flag(i, "purchased") && str(i, "investor_org_id") === FANNIE_MAE_ORG_ID, "Investor = Fannie Mae only after purchase (30.1 verifies the update)"),
      never("NEVER_SIGNS", "26.4 guardrails: never signs or applies an endorsement, allonge, assignment, LNA or affidavit — the partner's signing_officer does", (i) => flag(i, "apply_signature") || flag(i, "sign_allonge") || flag(i, "execute_assignment") || flag(i, "execute_lna") || flag(i, "apply_facsimile_outside_authority_file"), "a facsimile endorsement is rendered only from the partner's authority file; every wet signature is the signing_officer's"),
      never("ENDORSEE_NEVER_SM_OR_FNMA", "B8-3-04 / 26.4 rule 2: endorsement in blank without recourse — never names SM or Fannie Mae as endorsee", (i) => /supermortgage|fannie mae|federal national/i.test(str(i, "endorsee")) || (op(i) === "ensure_endorsement" && str(i, "endorsee") !== "" && str(i, "endorsee").toLowerCase() !== "blank"), "exactly one blank endorsement by the partner"),
      never("SHIP_WITHOUT_BAILEE_LETTER", "26.4 rule 4: never ship a paper note without a bailee letter (27.1 SM_WH_BAILEE_LETTER_GATE)", (i) => op(i) === "prepare_shipment" && !!optObj(i, "shipment") && ["fcc_bailee", "sm_designated_custodian"].includes(String(optObj(i, "shipment")!.to_role ?? "")) && !optObj(i, "shipment")!.bailee_letter_id, "the FCC holds for SM only under a bailee letter and the 9-313(c) acknowledgment"),
      never("SHIP_TO_UNLISTED_ADDRESS", "26.4 rule 4: never ship to an address not on the closing instructions", (i) => op(i) === "prepare_shipment" && !!optObj(i, "shipment") && !flag(i, "address_on_closing_instructions"), "the destination is the address the closing instructions designate"),
      never("COPY_NOT_ORIGINAL", "26.4 rule 4: never accept a copy in place of the original", (i) => flag(i, "accept_copy"), "the original note (or the eNote's Authoritative Copy) is the collateral"),
      never("CLOSE_WITHOUT_PASSED_REVIEW", "26.4 guardrails: never close a trailing document without a passed review", (i) => op(i) === "close_trailing_document" && flag(i, "force_close"), "closed requires recorded_instrument_reviews / final_policy_reviews result = pass"),
      needsRole("WAIVER_OFFICER_ONLY", "26.4 guardrails: never waive a document (`officer` only, with a reason)", (i) => op(i) === "waive_trailing_document" && str(i, "reason") !== "loan_cancelled", ["officer"], "a trailing-document waiver is the partner officer's decision"),
      needsRole("LNA_DECISION_OFFICER", "26.4 rule 5: the lost-note decision (re-execute / LNA / both) is the officer's", (i) => op(i) === "decide_lost_note", ["officer"], "re-execution first; LNA alone needs the officer and the FCC/Fannie Mae certifiability confirmation"),
      needsRole("NOTE_RELEASE_OFFICER", "26.4 rule 10: a Form 2009-content release request retrieving a note from the FCC is signed by the partner officer", (i) => op(i) === "release_note", ["officer"], "the note release is the officer's act"),
      never("NEVER_TRANSFER_OF_CONTROL", "26.4 guardrails: never submits an eRegistry Transfer of Control (29.4 / partner authority)", (i) => op(i) === "transfer_of_control" || flag(i, "transfer_of_control"), "Transfer of Control and Location to Fannie Mae is 29.4's delivery step under the partner's authority"),
      never("NEVER_ENOTE_TO_PAPER", "26.4 rule 9: SM never converts an eNote to paper (Controller's right; Fannie Mae's after purchase)", (i) => flag(i, "convert_enote_to_paper"), "papering out an eNote is the Controller's decision"),
    ] },
]);

export type { EndorsementMethod, TrailingKind, PostClosingRefused };
