/**
 * §30.1 process-owned tools — bus tools for 30.1 defined with `defineTools("30.1", <agent>, defs)` from
 * ../tools.ts. Every tool string is one spec/registry/agents.json names for 30.1 (`investor-reporting`); the
 * paragraph's `boarding` / `custodial-recon` / `post-closing` acts (applyPurchaseUpdate, versionLoanTerms,
 * finalizeCustodyRecord, scheduleCustodialTransfer, executeBookTransfer, matchBankFeed, buildMersBatch, submitMersBatch,
 * snapshotMins, verifyERegistry) run as `op`s of submitBatch / pollFeedback over the same ops-30-1.ts functions, so
 * the agents share one pipeline and one decision schema (AI-off path: the same commands from the ops console).
 * Spread by ./index.ts. Guardrails encode the paragraph: no acceptance without a parsed Fannie Mae response; money
 * variances never adopted without a PPA package and an `officer` approval record; Interim Funder removal only after
 * `warehouse.advance.repaid` is bank-matched; no TOB ever; `human_agent` never.
 */
import { defineTools, compute, escalate, decision, never, needsRole, port, cents, str, flag, type ToolDef, type ToolInput, type ToolRuntime } from "../tools.ts";
import type { CommandContext } from "../commands.ts";
import { plainDate as D, type PlainDate } from "../../kernel/calendar/date.ts";
import type { Cents } from "../../kernel/money/index.ts";
import {
  purchaseUpdate, recordInvestorPositionSeed, seedInvestorPosition, ptrConsistency, purchaseAdviceReceived, establishmentCheck, firstLarGate, firstLarProjection, submitFirstLar, acceptFirstLar, nextCycleNoPayment, paymentLar,
  purchaseMonthInterestDeduction, purchaseMonthRemittance, escrowSetupPlan, sendEscrowSetupEvents, ackEscrowSetup, scheduleCustodialTransfers, executeBookTransfer, matchBankFeed, depositDueOn, proceedsReceived,
  interimFunderRemovalTxn, isTob, recordMinUpdateAck, verifyMersInvestor, advanceRepaid, verifyENote, enoteCommandGate, finalizeCustodyRecord, preparePpaPackage, adoptFnmaFigure, resolveVariance,
  investorSetupStatus, completeInvestorSetup, postPurchaseSetupLine, setupDecisionRecord, onLoanPurchased, onProceedsReceived, openVariances,
  type PurchaseAdvice, type PurchaseLoan, type InvestorPositionSeed, type RemittanceType, type EstablishmentSource, type EscrowCategoryBalance, type CustodialTransferRow, type MinUpdateTxn, type SetupFacts, type VarianceKind, type NoteForm,
} from "../../domain/orig-boarding/ops-30-1.ts";

const need = (i: ToolInput, ...keys: string[]): void => { for (const k of keys) if (i[k] === undefined || i[k] === null || i[k] === "") throw new RangeError(`${k} is required`); };
const loanOf = (i: ToolInput, ctx: CommandContext): string => { const id = str(i, "loan_id") || ctx.loanId; if (!id) throw new RangeError("loan_id is required"); return id; };
const appOf = (i: ToolInput): string | null => (typeof i.application_id === "string" && i.application_id ? i.application_id : null);
const date = (i: ToolInput, k: string): PlainDate => { need(i, k); return D(str(i, k)); };
const optDate = (i: ToolInput, k: string): PlainDate | null => (i[k] === undefined || i[k] === null || i[k] === "" ? null : D(str(i, k)));
const rec = (i: ToolInput, k: string): Record<string, unknown> => { const v = i[k]; if (!v || typeof v !== "object") throw new RangeError(`${k} is required`); return v as Record<string, unknown>; };
const adviceOf = (r: Record<string, unknown>): PurchaseAdvice => ({ advice_id: String(r.advice_id ?? ""), fnma_loan_number: String(r.fnma_loan_number ?? ""), fnma_servicer_number: String(r.fnma_servicer_number ?? ""), lender_loan_number: String(r.lender_loan_number ?? ""),
  advice_date: D(String(r.advice_date ?? r.purchase_date ?? "")), purchase_date: D(String(r.purchase_date ?? "")), remittance_type: String(r.remittance_type ?? "AA") as RemittanceType, pass_through_rate: String(r.pass_through_rate ?? ""), note_rate_pct: String(r.note_rate_pct ?? ""),
  servicing_fee_bps: Number(r.servicing_fee_bps ?? NaN), interest_adjustment_cents: cents(r.interest_adjustment_cents), net_proceeds_cents: cents(r.net_proceeds_cents) });
const loanRow = (r: Record<string, unknown>, loanId: string, app: string | null): PurchaseLoan => ({ loan_id: loanId, application_id: app, servicing_loan_number: String(r.servicing_loan_number ?? ""), original_upb_cents: cents(r.original_upb_cents), ...(r.principal_paid_cents !== undefined ? { principal_paid_cents: cents(r.principal_paid_cents) } : {}),
  first_payment_date: D(String(r.first_payment_date ?? "")), note_rate_pct: String(r.note_rate_pct ?? ""), commitment_remittance_type: String(r.commitment_remittance_type ?? "AA") as RemittanceType, escrowed: r.escrowed !== false, note_form: (r.note_form === "enote" ? "enote" : "paper") as NoteForm, mers_registered: r.mers_registered !== false, min: typeof r.min === "string" ? r.min : null });
const positionOf = (r: Record<string, unknown>, loanId: string): InvestorPositionSeed => ({ loan_id: loanId, fnma_lpi_date: D(String(r.fnma_lpi_date ?? "")), fnma_actual_upb_cents: cents(r.fnma_actual_upb_cents), remittance_type: String(r.remittance_type ?? "AA") as RemittanceType, fnma_ptr: String(r.fnma_ptr ?? ""), participation_pct: "100.000000", source: "purchase_advice", as_of: D(String(r.as_of ?? "")) });
const factsOf = (i: ToolInput): SetupFacts => ({ escrowed: i.escrowed !== false, escrow_events_on: i.escrow_events_on !== false, note_form: i.note_form === "enote" ? "enote" : "paper", mers_registered: i.mers_registered !== false });
const transferRow = (r: Record<string, unknown>): CustodialTransferRow => ({ id: String(r.id ?? ""), loan_id: String(r.loan_id ?? ""), kind: String(r.kind ?? "ti_escrow_balance") as CustodialTransferRow["kind"], amount_cents: cents(r.amount_cents), from_account_id: String(r.from_account_id ?? ""), to_account_id: String(r.to_account_id ?? ""),
  proceeds_received_at: String(r.proceeds_received_at ?? ""), due_on: D(String(r.due_on ?? "")), due_at: String(r.due_at ?? ""), transferred_at: (r.transferred_at as string | null | undefined) ?? null, bank_reference: (r.bank_reference as string | null | undefined) ?? null, ledger_entry_id: (r.ledger_entry_id as string | null | undefined) ?? null, bank_matched_on: r.bank_matched_on ? D(String(r.bank_matched_on)) : null });
const storeRow = (rt: ToolRuntime, row: CustodialTransferRow, ctx: CommandContext): void => { rt.store.put("custodial_transfers", row.id, { ...row, amount_cents: String(row.amount_cents) }, ctx.actor, ctx.now); };
const credits = (i: ToolInput): { amountCents: Cents; bankReference: string; text: string }[] => (Array.isArray(i.credits) ? (i.credits as Record<string, unknown>[]).map((c) => ({ amountCents: cents(c.amountCents ?? c.amount_cents), bankReference: String(c.bankReference ?? c.bank_reference ?? ""), text: String(c.text ?? "") })) : []);
const minTxn = (r: Record<string, unknown>): MinUpdateTxn => ({ txnId: String(r.txnId ?? ""), min: String(r.min ?? ""), type: "min_update_other", subtype: "interim_funder_removed", effectiveDate: D(String(r.effectiveDate ?? "")), orgId: String(r.orgId ?? ""), field: "interim_funder", from_org_id: String(r.from_org_id ?? r.orgId ?? ""), to_org_id: null });

export const TOOLS_30_1: readonly ToolDef[] = defineTools("30.1", "investor-reporting", [
  // Rules 1–3, 6, 13 (`boarding`'s applyPurchaseUpdate + versionLoanTerms): the idempotent purchase update from 27.2's matched advice.
  { name: "matchPurchaseAdvice", kind: "write", moneyFields: ["pass_through_rate", "servicing_fee_bps", "interest_adjustment_cents", "net_proceeds_cents"], handler: compute((i, ctx, rt) => {
      const loanId = loanOf(i, ctx); const app = appOf(i);
      const loan = loanRow(rec(i, "loan"), loanId, app); const advice = adviceOf(rec(i, "advice"));
      const r = purchaseUpdate(ctx.events, { loan, advice, now: ctx.now, actor: ctx.actor });
      if (r.ok && r.loan_patch) { rt.store.put("loans", loanId, r.loan_patch, ctx.actor, ctx.now); rt.store.put("loan_terms", `${loanId}:2`, { loan_id: loanId, ...r.loan_terms_v2 }, ctx.actor, ctx.now); }
      return { ok: r.ok, replayed: r.replayed, variance: r.variance, loan: r.loan_patch, loan_terms_v2: r.loan_terms_v2, position: r.position ? { ...r.position, fnma_actual_upb_cents: String(r.position.fnma_actual_upb_cents) } : null, idempotency_key: r.idempotency_key, ptr: ptrConsistency(advice.note_rate_pct, advice.pass_through_rate, advice.servicing_fee_bps), advice_event_id: purchaseAdviceReceived(ctx.events, loanId)?.id ?? null,
        purchase_month: { ...purchaseMonthRemittance(advice.purchase_date), interest_deduction: purchaseMonthInterestDeduction(loan.original_upb_cents, advice.pass_through_rate, advice.purchase_date, seedInvestorPosition(loan, advice).fnma_lpi_date) } }; }),
    guardrails: [never("REMITTANCE_TYPE_OVERWRITE", "30.1 rule 3 / C1-3-01: a remittance type on the advice that differs from the commitment is a position_variance, never a silent overwrite", (i) => flag(i, "overwrite_remittance_type"), "the commitment record is the evidence; open the variance instead"),
      never("PARTNER_SERVICER_NUMBER", "30.1 rule 2: every Fannie Mae submission carries the partner's fnma_servicer_number; SM's own servicer number is never used for partner loans", (i) => flag(i, "use_sm_servicer_number"), "use the partner's 9-digit seller/servicer number")] },
  // Rule 12: the establishment check (LSDU position / Connect Loan Activity Summary / Servicing Platform position) against the seed; establishment_lag → Investor Reporting Representative package.
  { name: "checkFnmaEstablishment", kind: "write", handler: compute(async (i, ctx, rt) => {
      const loanId = loanOf(i, ctx); need(i, "expected", "purchase_date");
      const expected = positionOf(rec(i, "expected"), loanId); const source = (str(i, "source") || "lsdu_position") as EstablishmentSource;
      let found = i.found === true; let observed = i.observed ? rec(i, "observed") : null;
      if (i.found === undefined && rt.ports.lsdu) { const tb = await port(rt, "lsdu").trialBalance([str(i, "fnma_loan_number")]); const row = tb[str(i, "fnma_loan_number")]; found = !!row; observed = row ? { fnma_lpi_date: row.lpi, fnma_upb_cents: row.upb_cents, fnma_remittance_type: row.remittance_type.replace("/", ""), fnma_ptr: row.ptr_pct } : null; }
      const r = establishmentCheck(ctx.events, { loan_id: loanId, application_id: appOf(i), checked_at: str(i, "checked_at") || ctx.now, source, found, observed: observed ? { fnma_lpi_date: observed.fnma_lpi_date ? D(String(observed.fnma_lpi_date)) : null, fnma_upb_cents: cents(observed.fnma_upb_cents), fnma_remittance_type: String(observed.fnma_remittance_type ?? "AA") as RemittanceType, fnma_ptr: String(observed.fnma_ptr ?? "") } : null, expected, purchase_date: date(i, "purchase_date"), ...(i.upb_tolerance_cents !== undefined ? { upb_tolerance_cents: cents(i.upb_tolerance_cents) } : {}), agent_run_id: ctx.run?.runId ?? null, actor: ctx.actor });
      rt.store.put("fnma_establishment_checks", `${loanId}:${r.row.checked_at}`, { ...r.row, fnma_upb_cents: r.row.fnma_upb_cents === null ? null : String(r.row.fnma_upb_cents), variance: r.row.variance ? { ...r.row.variance, upb_diff_cents: String(r.row.variance.upb_diff_cents) } : null }, ctx.actor, ctx.now);
      if (r.status === "established") rt.store.put("loans", loanId, { fnma_established_at: r.established_at, investor_setup_status: "established" }, ctx.actor, ctx.now);
      if (r.portal_package) rt.escalations.open({ kind: "human_portal_task", ownerRole: "fnma_portal_operator", severity: "sev-2", loanId, payload: { reason: "establishment_lag", package: r.portal_package } }, ctx.actor);
      for (const v of r.variances) if (v.money) rt.escalations.open({ kind: "officer", severity: "sev-2", loanId, payload: { reason: "position_variance", variance: v } }, ctx.actor);
      return { status: r.status, established_at: r.established_at, lar_held: r.lar_held, variances: r.variances, portal_package: r.portal_package, row: { ...r.row, fnma_upb_cents: r.row.fnma_upb_cents === null ? null : String(r.row.fnma_upb_cents), variance: r.row.variance ? { ...r.row.variance, upb_diff_cents: String(r.row.variance.upb_diff_cents) } : null } }; }),
    guardrails: [never("ESTABLISHED_FROM_RESPONSE_ONLY", "30.1 state machine: transitions to established are made only from parsed Fannie Mae responses", (i) => flag(i, "assume_established"), "the establishment check reads Fannie Mae's position; it is never assumed")] },
  // Rule 1: the `investor_loan_positions` seed (5.1's table; source='purchase_advice').
  { name: "seedInvestorPosition", kind: "write", handler: compute((i, ctx, rt) => {
      const loanId = loanOf(i, ctx); const loan = loanRow(rec(i, "loan"), loanId, appOf(i)); const advice = adviceOf(rec(i, "advice"));
      const r = recordInvestorPositionSeed(ctx.events, { loan, advice, now: ctx.now, actor: ctx.actor });
      rt.store.put("investor_loan_positions", loanId, { ...r.position, fnma_actual_upb_cents: String(r.position.fnma_actual_upb_cents) }, ctx.actor, ctx.now);
      return { ...r.position, fnma_actual_upb_cents: String(r.position.fnma_actual_upb_cents), event_id: r.event.id }; }) },
  // Rule 5 / 7: projections — first_lar (acquisition month), payment_none (the cycle after), payment_lar (a posted contractual payment), escrow_setup (LL-2026-05 Setup events with the deadline basis).
  { name: "projectEvent", kind: "write", handler: compute((i, ctx) => {
      const loanId = loanOf(i, ctx); const op = str(i, "op") || "first_lar";
      switch (op) {
        case "first_lar": { need(i, "servicer_number", "fnma_loan_number", "position", "purchase_date", "established_at"); const pr = firstLarProjection({ servicer_number: str(i, "servicer_number"), fnma_loan_number: str(i, "fnma_loan_number"), position: positionOf(rec(i, "position"), loanId), purchase_date: date(i, "purchase_date"), established_at: date(i, "established_at") });
          const gate = firstLarGate(ctx.events, loanId); return { ...pr, payload: { ...pr.payload, upb_cents: String(pr.payload.upb_cents), interest_cents: "0", principal_cents: "0", nib_cents: "0", other_fees_cents: "0" }, held: gate.held, hold_reasons: gate.reasons, target_at: new Date(pr.clocks.target_at_ms).toISOString(), hard_deadline_at: new Date(pr.clocks.hard_deadline_at_ms).toISOString() }; }
        case "payment_none": { need(i, "month_of", "servicer_number", "fnma_loan_number", "position"); const pr = nextCycleNoPayment({ month_of: date(i, "month_of"), servicer_number: str(i, "servicer_number"), fnma_loan_number: str(i, "fnma_loan_number"), sequence: Number(i.sequence ?? 2), position: positionOf(rec(i, "position"), loanId) });
          return { event_type: pr.event_type, record: pr.lar?.record ?? null, due_on: pr.due_on, submit_by: new Date(pr.submit_by_ms).toISOString(), sweep_run: new Date(pr.sweep_run_ms).toISOString() }; }
        case "payment_lar": { need(i, "servicer_number", "fnma_loan_number", "prior_upb_cents", "prior_lpi_date", "note_rate_pct", "ptr_pct", "payment_cents", "processed_at"); const pl = paymentLar({ servicer_number: str(i, "servicer_number"), fnma_loan_number: str(i, "fnma_loan_number"), prior_upb_cents: cents(i.prior_upb_cents), prior_lpi_date: date(i, "prior_lpi_date"), note_rate_pct: str(i, "note_rate_pct"), ptr_pct: str(i, "ptr_pct"), payment_cents: cents(i.payment_cents), processed_at: str(i, "processed_at"), open_periods: Array.isArray(i.open_periods) ? (i.open_periods as string[]) : [] });
          return { record: pl.lar.record, fields: pl.lar.fields, activity_period: pl.activity_period, due_on: pl.due_on, due_at: new Date(pl.due_at_ms).toISOString(), new_upb_cents: String(pl.new_upb_cents), new_lpi_date: pl.new_lpi_date, remittance_cents: String(pl.remittance.remittance_cents), fnma_interest_cents: String(pl.remittance.fnma_interest_cents), principal_cents: String(pl.remittance.principal_cents), servicing_fee_cents: String(pl.remittance.servicing_fee_cents), crs: pl.crs }; }
        case "escrow_setup": { need(i, "purchase_date"); const cats = (Array.isArray(i.categories) ? (i.categories as Record<string, unknown>[]) : []).map((c): EscrowCategoryBalance => ({ category: String(c.category ?? "ti") as EscrowCategoryBalance["category"], balance_cents: cents(c.balance_cents) }));
          const plan = escrowSetupPlan({ loan_id: loanId, escrowed: i.escrowed !== false, flag_on: i.escrow_events_on !== false, categories: cats, purchase_date: date(i, "purchase_date"), visibility_observed_on: optDate(i, "visibility_observed_on") });
          return { ...plan, events: plan.events.map((e) => ({ ...e, amount_cents: String(e.amount_cents), balance_cents: String(e.balance_cents) })), target_at: new Date(plan.target_at_ms).toISOString(), deadline_at: plan.deadline_at_ms === null ? null : new Date(plan.deadline_at_ms).toISOString() }; }
        default: throw new RangeError(`projectEvent op ${op} is not one of first_lar/payment_none/payment_lar/escrow_setup`);
      } }),
    guardrails: [never("NO_LAR_WITH_OPEN_VARIANCE", "30.1 rules 3, 12: no LAR is projected/submitted while a position_variance is open — resolved through a PPA/Loan Data Change package (or the commitment record) first", (i) => flag(i, "submit") && flag(i, "variance_open"), "resolve the position_variance before the first LAR"),
      never("NO_ACCEPT_WITHOUT_RESPONSE", "30.1 guardrail: no agent may mark an event accepted without a parsed Fannie Mae response", (i) => str(i, "set_status") === "accepted", "acceptance is written by pollFeedback from the parsed response only")] },
  // Submissions: lar (investor.first_lar.submitted), escrow_setup (escrow.setup_event.sent), custodial_transfer (custodial-recon's scheduleCustodialTransfer/executeBookTransfer), mers_min_update (post-closing's buildMersBatch/submitMersBatch), custody_finalize (boarding's finalizeCustodyRecord).
  { name: "submitBatch", kind: "act", handler: compute(async (i, ctx, rt) => {
      const loanId = loanOf(i, ctx); const app = appOf(i); const op = str(i, "op") || "lar";
      switch (op) {
        case "lar": { need(i, "servicer_number", "fnma_loan_number", "position", "purchase_date", "established_at"); const pr = firstLarProjection({ servicer_number: str(i, "servicer_number"), fnma_loan_number: str(i, "fnma_loan_number"), position: positionOf(rec(i, "position"), loanId), purchase_date: date(i, "purchase_date"), established_at: date(i, "established_at") });
          let submission_id = str(i, "submission_id"); const channel = (str(i, "channel") || "lsdu_b2b") as "lsdu_b2b" | "lsdu_upload" | "lsdu_single";
          if (!submission_id && rt.ports.lsdu && !firstLarGate(ctx.events, loanId).held) submission_id = (await port(rt, "lsdu").submitLarFile([{ fnmaLoanNumber: str(i, "fnma_loan_number"), record: pr.lar.record.replace(/\r$/, ""), eventId: `first-lar-${loanId}`, sequence: 1 }], ctx.now)).submissionId;
          const r = submitFirstLar(ctx.events, { loan_id: loanId, application_id: app, projection: pr, submission_id: submission_id || `sub-${loanId}-first-lar`, channel, now: ctx.now, actor: ctx.actor });
          if (!r.ok) throw new RangeError(`${r.code}: ${r.reasons.join("; ")}`); return { submitted: true, submission_id: submission_id || `sub-${loanId}-first-lar`, record: pr.lar.record, late_vs_target: r.late_vs_target, event_id: r.event.id }; }
        case "escrow_setup": { need(i, "purchase_date"); const cats = (Array.isArray(i.categories) ? (i.categories as Record<string, unknown>[]) : []).map((c): EscrowCategoryBalance => ({ category: String(c.category ?? "ti") as EscrowCategoryBalance["category"], balance_cents: cents(c.balance_cents) }));
          const plan = escrowSetupPlan({ loan_id: loanId, escrowed: i.escrowed !== false, flag_on: i.escrow_events_on !== false, categories: cats, purchase_date: date(i, "purchase_date"), visibility_observed_on: optDate(i, "visibility_observed_on") });
          const events = sendEscrowSetupEvents(ctx.events, { loan_id: loanId, application_id: app, plan, submission_id: str(i, "submission_id") || `se-${loanId}-setup`, now: ctx.now, actor: ctx.actor });
          return { sent: events.length, deadline_basis: plan.deadline_basis, deadline_at: plan.deadline_at_ms === null ? null : new Date(plan.deadline_at_ms).toISOString(), event_ids: events.map((e) => e.id) }; }
        case "custodial_transfer": { need(i, "proceeds_received_at", "balances", "fnma_ti_account_id", "fnma_pi_account_id"); const b = rec(i, "balances");
          const r = scheduleCustodialTransfers(ctx.events, { loan_id: loanId, application_id: app, proceeds_received_at: str(i, "proceeds_received_at"), balances: { ti_escrow_balance_cents: cents(b.ti_escrow_balance_cents), ti_buydown_funds_cents: cents(b.ti_buydown_funds_cents), pi_prepurchase_collections_cents: cents(b.pi_prepurchase_collections_cents) }, fnma_ti_account_id: str(i, "fnma_ti_account_id"), fnma_pi_account_id: str(i, "fnma_pi_account_id"), actor: ctx.actor });
          onProceedsReceived(ctx.timers, loanId, { pi_prepurchase_collections_cents: cents(b.pi_prepurchase_collections_cents) });
          for (const row of r.rows) storeRow(rt, row, ctx);
          return { due_on: r.due_on, rows: r.rows.map((x) => ({ ...x, amount_cents: String(x.amount_cents) })) }; }
        case "book_transfer": { const row = transferRow(rec(i, "row")); need(i, "transferred_at"); const r = executeBookTransfer(ctx.ledger, ctx.events, row, { application_id: app, transferred_at: str(i, "transferred_at"), bank_reference: str(i, "bank_reference") || null, actor: ctx.actor });
          storeRow(rt, r.row, ctx); return { ledger_entry_id: r.set.id, late: r.late, row: { ...r.row, amount_cents: String(r.row.amount_cents) } }; }
        case "mers_min_update": { need(i, "min", "repaid_on"); const repaid = advanceRepaid(ctx.events, loanId);
          const r = interimFunderRemovalTxn({ min: str(i, "min"), repaid_on: date(i, "repaid_on"), bank_matched: flag(i, "bank_matched") || repaid?.bank_matched === true, ...(str(i, "sm_org_id") ? { sm_org_id: str(i, "sm_org_id") } : {}) });
          if (isTob(r.txn)) throw new RangeError("NO_TOB: 30.1 never submits a Transfer of Beneficial Rights");
          let batch_id = str(i, "batch_id") || `mers-${r.batch_on}`; let results: readonly { txnId: string; status: string }[] = [];
          if (rt.ports.mers) { const out = await port(rt, "mers").submitBatch([{ txnId: r.txn.txnId, min: r.txn.min, type: r.txn.type, effectiveDate: r.txn.effectiveDate, orgId: r.txn.orgId }], ctx.now); batch_id = out.batchId; results = out.results; }
          ctx.events.append({ type: "mers.batch.submitted", loanId, ...(app ? { applicationId: app } : {}), actor: ctx.actor, payload: { batch_id, batch_on: r.batch_on, txn: { ...r.txn }, tob: false, application_id: app, source: "origination" } });
          return { batch_id, batch_on: r.batch_on, txn: r.txn, results }; }
        case "custody_finalize": { need(i, "certified_on"); const r = finalizeCustodyRecord(ctx.events, { loan_id: loanId, application_id: app, note_form: i.note_form === "enote" ? "enote" : "paper", certification_status: str(i, "certification_status") === "qualified_cert" ? "qualified_cert" : "certified", custodian_party_id: str(i, "custodian_party_id") || null, certified_on: date(i, "certified_on"), now: ctx.now, actor: ctx.actor });
          rt.store.put("custody_records", loanId, { ...r.record }, ctx.actor, ctx.now); return { ...r.record, event_id: r.event.id }; }
        default: throw new RangeError(`submitBatch op ${op} is not one of lar/escrow_setup/custodial_transfer/book_transfer/mers_min_update/custody_finalize`);
      } }),
    guardrails: [never("NO_TOB", "30.1 guardrail: no TOB is ever submitted (B8-7-01: the investor update is Fannie Mae's action)", (i) => /tob/i.test(str(i, "txn_type")) || flag(i, "tob"), "SM never submits a Transfer of Beneficial Rights; verify Fannie Mae's update instead"),
      never("INTERIM_FUNDER_AFTER_REPAID", "30.1 guardrail: the Interim Funder removal is submitted only after warehouse.advance.repaid is bank-matched", (i) => str(i, "op") === "mers_min_update" && i.bank_matched === false, "wait for 27.2's bank-matched repayment"),
      never("NO_HUMAN_AGENT", "30.1 escalations: human_agent never (no borrower contact in 30.1)", (i) => str(i, "escalate_to") === "human_agent", "30.1 produces no borrower-facing artifact")] },
  // Fannie Mae / MERS / eRegistry / bank responses, parsed: lar → investor.first_lar.accepted; escrow_setup → investor_events.acked; mers_ack → warehouse.interim_funder.removed; mers_snapshot → mers.investor.fnma_verified; eregistry → enote.post_purchase.verified; bank_feed → custodial.prepurchase_funds.transferred; setup → loan.reporting_active.
  { name: "pollFeedback", kind: "write", handler: compute((i, ctx, rt) => {
      const loanId = loanOf(i, ctx); const app = appOf(i); const op = str(i, "op") || "lar";
      switch (op) {
        case "lar": { need(i, "submission_id", "fnma_response_id"); const r = acceptFirstLar(ctx.events, { loan_id: loanId, application_id: app, submission_id: str(i, "submission_id"), fnma_response_id: str(i, "fnma_response_id"), accepted_at: str(i, "accepted_at") || ctx.now, escrow_setup_required: i.escrow_setup_required !== false, actor: ctx.actor });
          rt.store.put("loans", loanId, { investor_setup_status: r.status }, ctx.actor, ctx.now); return { status: r.status, event_ids: r.events.map((e) => e.id) }; }
        case "escrow_setup": { need(i, "category", "fnma_response_id"); const r = ackEscrowSetup(ctx.events, { loan_id: loanId, application_id: app, category: str(i, "category"), fnma_response_id: str(i, "fnma_response_id"), status: (str(i, "status") || "accepted") as "accepted" | "accepted_warning" | "rejected", message: str(i, "message") || null, acked_at: str(i, "acked_at") || ctx.now });
          if (r.every_category) rt.store.put("loans", loanId, { investor_setup_status: "escrow_setup_acked" }, ctx.actor, ctx.now); return { every_category: r.every_category, acked: r.acked, expected: r.expected, event_id: r.event.id }; }
        case "mers_ack": { need(i, "txn", "batch_id"); const r = recordMinUpdateAck(ctx.events, { loan_id: loanId, application_id: app, txn: minTxn(rec(i, "txn")), batch_id: str(i, "batch_id"), accepted: i.accepted !== false, reject_reason: str(i, "reject_reason") || null, acked_at: str(i, "acked_at") || ctx.now });
          if (r.removed) rt.store.put("mers_transactions", `${str(i, "batch_id")}:${str(i, "min") || rec(i, "txn").min}`, { subtype: "interim_funder_removed", status: "accepted" }, ctx.actor, ctx.now); return { removed: r.removed, qa_finding: r.qa_finding, event_ids: r.events.map((e) => e.id) }; }
        case "mers_snapshot": { need(i, "min", "snapshot", "snapshot_on", "purchase_date", "partner_org_id"); const s = rec(i, "snapshot");
          const r = verifyMersInvestor(ctx.events, { loan_id: loanId, application_id: app, min: str(i, "min"), snapshot: { investor_org_id: String(s.investor_org_id ?? ""), servicer_org_id: String(s.servicer_org_id ?? ""), subservicer_org_id: (s.subservicer_org_id as string | null | undefined) ?? null, interim_funder_org_id: (s.interim_funder_org_id as string | null | undefined) ?? null, ...(typeof s.status === "string" ? { status: s.status } : {}) }, snapshot_on: date(i, "snapshot_on"), purchase_date: date(i, "purchase_date"), partner_org_id: str(i, "partner_org_id"), ...(str(i, "fnma_investor_org_id") ? { fnma_investor_org_id: str(i, "fnma_investor_org_id") } : {}), actor: ctx.actor });
          if (r.partner_query) rt.escalations.open({ kind: "sev3", ownerRole: "ops_analyst", loanId, payload: { reason: "mers_investor_not_fnma", partner_query: r.partner_query } }, ctx.actor);
          return { verified: r.verified, problems: r.problems, due_on: r.due_on, partner_query: r.partner_query, w016_closed: r.w016_closed }; }
        case "eregistry": { need(i, "inquiry"); const q = rec(i, "inquiry");
          const r = verifyENote(ctx.events, { loan_id: loanId, application_id: app, inquiry: { controller_org_id: String(q.controller_org_id ?? ""), location_org_id: String(q.location_org_id ?? ""), master_servicer_org_id: (q.master_servicer_org_id as string | null | undefined) ?? null, secured_party_org_id: (q.secured_party_org_id as string | null | undefined) ?? null }, inquiry_at: str(i, "inquiry_at") || ctx.now, actor: ctx.actor });
          if (!r.verified) rt.escalations.open({ kind: "sev2", ownerRole: "ops_analyst", loanId, payload: { reason: "enote_post_purchase_mismatch", mismatches: r.mismatches, blocked_commands: ["payoff", "modification"] } }, ctx.actor);
          return { verified: r.verified, mismatches: r.mismatches, gate: enoteCommandGate(ctx.events, loanId) }; }
        case "bank_feed": { const row = transferRow(rec(i, "row")); const r = matchBankFeed(ctx.events, row, { application_id: app, credits: credits(i), matched_at: str(i, "matched_at") || ctx.now, actor: ctx.actor });
          if (r.matched) storeRow(rt, row, ctx); return { matched: r.matched, credit: r.credit ? { ...r.credit, amountCents: String(r.credit.amountCents) } : null }; }
        case "setup": { const r = completeInvestorSetup(ctx.events, { loan_id: loanId, application_id: app, facts: factsOf(i), now: ctx.now, actor: ctx.actor });
          if (r.event) rt.store.put("loans", loanId, { investor_setup_status: "reporting_active" }, ctx.actor, ctx.now); return { status: r.progress.status, pending: r.progress.pending, reporting_active: r.event !== null }; }
        case "status": return { ...investorSetupStatus(ctx.events, loanId, factsOf(i)), sentinel_line: postPurchaseSetupLine(ctx.events, loanId, ctx.timers.forSubject("loan", loanId).map((t) => ({ code: t.code, status: t.status, ...(t.dueDate ? { dueDate: t.dueDate } : {}) }))), open_variances: openVariances(ctx.events, loanId), enote_gate: enoteCommandGate(ctx.events, loanId), proceeds_event_id: proceedsReceived(ctx.events, loanId)?.id ?? null, deposit_due_on: proceedsReceived(ctx.events, loanId) ? depositDueOn(proceedsReceived(ctx.events, loanId)!.occurredAt) : null };
        default: throw new RangeError(`pollFeedback op ${op} is not one of lar/escrow_setup/mers_ack/mers_snapshot/eregistry/bank_feed/setup/status`);
      } }),
    guardrails: [never("NO_ACCEPT_WITHOUT_RESPONSE", "30.1 guardrail: no agent may mark an event accepted without a parsed Fannie Mae response", (i) => ["lar", "escrow_setup"].includes(str(i, "op") || "lar") && flag(i, "assume_accepted"), "acceptance is written from the parsed feedback (fnma_response_id) only"),
      never("MERS_VERIFY_NOT_CORRECT", "30.1 rule 9: the investor field is verified from the MERS snapshot, never self-corrected; Fannie Mae's update never appearing is a partner query, not a TOB", (i) => str(i, "op") === "mers_snapshot" && flag(i, "self_correct"), "keep W-016 open and send the partner query package")] },
  // Corrections: ppa_package (rule 12 — the PPA/Loan Data Change package for a money variance), adopt_fnma_figure (refused without the officer approval record + PPA package; officer-only), resolve_variance (evidence), lar81 (rule 6: only when the delivered identifier differs), timer_cancel_inapplicable (onLoanPurchased).
  { name: "createCorrection", kind: "write", moneyFields: ["adopted_value"], handler: compute((i, ctx, rt) => {
      const loanId = loanOf(i, ctx); const app = appOf(i); const op = str(i, "op") || "ppa_package";
      switch (op) {
        case "ppa_package": { need(i, "opened_event_id", "kind"); const r = preparePpaPackage(ctx.events, { loan_id: loanId, application_id: app, opened_event_id: str(i, "opened_event_id"), kind: str(i, "kind") as VarianceKind, evidence_document_ids: Array.isArray(i.evidence_document_ids) ? (i.evidence_document_ids as string[]) : [], now: ctx.now, actor: ctx.actor });
          rt.escalations.open({ kind: "human_portal_task", ownerRole: "fnma_portal_operator", loanId, payload: { reason: "ppa_loan_data_change", package_id: r.package_id } }, ctx.actor); return { package_id: r.package_id, event_id: r.event.id }; }
        case "adopt_fnma_figure": { need(i, "opened_event_id", "adopted_value"); const r = adoptFnmaFigure(ctx.events, { loan_id: loanId, application_id: app, opened_event_id: str(i, "opened_event_id"), ppa_package_id: str(i, "ppa_package_id") || null, officer_approval_id: str(i, "officer_approval_id") || null, adopted_value: str(i, "adopted_value"), now: ctx.now, actor: ctx.actor });
          if (!r.ok) throw new RangeError(`${r.code}: ${r.reason}`); return { resolved: true, event_id: r.event.id }; }
        case "resolve_variance": { need(i, "opened_event_id", "resolution"); const e = resolveVariance(ctx.events, { loan_id: loanId, application_id: app, opened_event_id: str(i, "opened_event_id"), resolution: str(i, "resolution") as "commitment_confirmed" | "fnma_adjusted" | "lar81_filed" | "closed_manual", evidence_document_ids: Array.isArray(i.evidence_document_ids) ? (i.evidence_document_ids as string[]) : [], now: ctx.now, actor: ctx.actor }); return { resolved: true, event_id: e.id }; }
        case "lar81": { need(i, "delivered_identifier", "servicing_loan_number"); if (str(i, "delivered_identifier") === str(i, "servicing_loan_number")) throw new RangeError("LAR 81 is a correction path only: the delivered Lender Loan Number already equals servicing_loan_number (rule 6)");
          return { record_type: "81", channel: "5.1", from: str(i, "delivered_identifier"), to: str(i, "servicing_loan_number"), variance_kind: "lender_loan_id" }; }
        case "timer_cancel_inapplicable": { const loan = loanRow(rec(i, "loan"), loanId, app); return onLoanPurchased(ctx.timers, loan, { escrow_events_on: i.escrow_events_on !== false }); }
        default: throw new RangeError(`createCorrection op ${op} is not one of ppa_package/adopt_fnma_figure/resolve_variance/lar81/timer_cancel_inapplicable`);
      } }),
    guardrails: [never("MONEY_VARIANCE_EVIDENCE", "30.1 guardrail: money-field variances (UPB, LPI, PTR, escrow balance) are never corrected to Fannie Mae's values without evidence — a PPA package and officer approval are required", (i) => str(i, "op") === "adopt_fnma_figure" && (!str(i, "ppa_package_id") || !str(i, "officer_approval_id")), "attach the PPA package id and the officer's approval record"),
      needsRole("OFFICER_ADOPTS_FNMA_FIGURE", "30.1 guardrail: money variances are officer decisions", (i) => str(i, "op") === "adopt_fnma_figure", ["officer"], "adopting Fannie Mae's money figure is an officer act")] },
  // Portal-only islands (LSDU single LAR/upload, Servicing Platform CSV, Connect pulls, Loan Delivery status, Investor Reporting Representative package): a human_portal_task for fnma_portal_operator with the AI-prepared package.
  { name: "openPortalTask", kind: "act", handler: escalate("human_portal_task"), decision: (i) => ({ action: "openPortalTask", rationale: str(i, "reason") || "fnma_portal_operator: UI-only Fannie Mae step" }),
    guardrails: [never("NO_HUMAN_AGENT", "30.1 escalations: human_agent never (no borrower contact in 30.1)", (i) => str(i, "kind") === "human_agent" || str(i, "owner_role") === "human_agent", "30.1 has no borrower-facing step")] },
  { name: "recordDecision", kind: "write", handler: compute((i, ctx) => { decision()(i, ctx); return { recorded: true, ...(i.include_record ? { record: setupDecisionRecord(ctx.events, loanOf(i, ctx), null) } : {}) }; }), decision: (i) => ({ action: str(i, "action") || "recordDecision", rationale: str(i, "rationale") }) },
]);
