/**
 * §29.4 process-owned tools — bus tools for 29.4 defined with `defineTools("29.4", "secondary", defs)` from ../tools.ts.
 * Every tool string is one spec/registry/agents.json names for 29.4; src/app/tools.test.ts refuses the rest. Spread by
 * ./index.ts. The handlers are thin: the rules live in src/domain/secondary/ops-29-4.ts (DeliveryService — the runtime
 * service `delivery-29-4`); the store keeps `deliveries` (29.3/29.4, migration 0105) and 29.4's children (0106:
 * delivery_operator_tasks, custodian_certifications, wire_instructions, purchase_advices, post_purchase_adjustments) as
 * projections. Guardrails encode the AI-design sentences: the agent never operates a Fannie Mae UI or scripts a browser,
 * never accepts a status without evidence, never approves a wire instruction (SM warehouse org) without a human
 * `fnma_portal_operator` in that org, never files a PPA or remedy payment without the partner `officer` where money
 * moves, never changes the eNote Controller without the Delegatee authorization on file, never releases SM's warehouse
 * interest before proceeds are confirmed received, and never marks relief `confirmed_by_fnma` without a Fannie Mae report.
 * 29.3's DeliveryBuildService (`delivery-29-3`, when wired) is told `markSubmitted` on the submit evidence and
 * `supersede(…, "loan_delivery_fatal_edit")` on a fatal non-3000-series edit.
 */
import { defineTools, compute, decision, never, needsRole, cents, str, num, flag, type ToolDef, type ToolInput, type ToolRuntime } from "../tools.ts";
import type { CommandContext } from "../commands.ts";
import { plainDate as D, type PlainDate } from "../../kernel/calendar/date.ts";
import type { ERegistryPort } from "../../domain/warehouse/ops-27-1.ts";
import {
  DeliveryService, operatorTaskDue, expectedDates, recomputeOnReceipt, recomputeOnCertification, lpiWindow, loanAgeCheck, seasonedCheck, custodianReceiptDeadline, receiptPlan, renderInstructionSheet, baileeNameCheck, wireGate, expectedProceeds, reconcileProceeds, warehouseSlipCostCents, advanceCents, evaluateRelief, preparePpa, remedyPlan, adviceLagCheck, CARRIER_PICKUP_HHMM_MT, mtInstant, etDate, REQUIRED_EVIDENCE,
  type DeliveryInput, type WireInstruction, type PurchaseAdviceInput, type CapturedEdit, type ReliefComponent, type ReliefFacts, type PpaAttribute, type CertificationKind, type RemittanceType, type NoteForm, type DataRevision, type CustodyMode,
} from "../../domain/secondary/ops-29-4.ts";

type Rt = ToolRuntime; type Ctx = CommandContext;
const need = (i: ToolInput, ...keys: string[]): void => { const gaps = keys.filter((k) => i[k] === undefined || i[k] === null || i[k] === ""); if (gaps.length) throw new RangeError(`29.4 tool needs ${gaps.join(", ")}`); };
const at = (i: ToolInput, k: string, ctx: Ctx): string => (typeof i[k] === "string" && i[k] ? String(i[k]) : ctx.now);
const optStr = (i: ToolInput, k: string): string | null => (typeof i[k] === "string" && i[k] ? String(i[k]) : null);
const optDate = (i: ToolInput, k: string): PlainDate | null => (optStr(i, k) ? D(str(i, k)) : null);
const obj = (i: ToolInput, k: string): Record<string, unknown> => ((i[k] as Record<string, unknown> | undefined) ?? {});
const list = <T>(i: ToolInput, k: string): T[] => (Array.isArray(i[k]) ? (i[k] as T[]) : []);
const services = new WeakMap<Rt, DeliveryService>();
/** The runtime service `delivery-29-4`; built over the unit of work (with 27.1's eRegistry fake from `warehouse` when wired) if the runtime has not wired it. */
const svcOf = (rt: Rt, ctx: Ctx): DeliveryService => {
  const wired = rt.services["delivery-29-4"]; if (wired instanceof DeliveryService) return wired;
  let s = services.get(rt);
  if (!s) { const wh = rt.services["warehouse"] as { registry?: ERegistryPort } | undefined; s = new DeliveryService({ events: ctx.events, clock: ctx.clock, escalations: rt.escalations, ...(wh?.registry ? { registry: wh.registry } : {}) }); services.set(rt, s); (rt.services as Record<string, unknown>)["delivery-29-4"] = s; }
  return s;
};
/** 29.3's build service when the runtime wires it (`delivery-29-3`): `markSubmitted` / `supersede` are its hooks. */
const build = (rt: Rt): { markSubmitted(id: string): void; supersede(id: string, reason: string): unknown } | null => { const b = rt.services["delivery-29-3"] as { markSubmitted?: unknown; supersede?: unknown } | undefined; return b && typeof b.markSubmitted === "function" && typeof b.supersede === "function" ? (b as { markSubmitted(id: string): void; supersede(id: string, reason: string): unknown }) : null; };
const deliveryId = (i: ToolInput, svc: DeliveryService, ctx: Ctx): string => { const id = optStr(i, "delivery_id"); if (id) return id; const r = ctx.loanId ? svc.byLoan(ctx.loanId) : null; if (!r) throw new RangeError("29.4 tool needs delivery_id"); return r.delivery_id; };
const project = (rt: Rt, ctx: Ctx, kind: string, id: string, row: Record<string, unknown>): void => { rt.store.put(kind, id, row, ctx.actor, ctx.now); };
const view = (svc: DeliveryService, id: string) => { const r = svc.get(id); return { ...r, upb_cents: String(r.upb_cents) }; };
const wireOf = (i: ToolInput): WireInstruction => { const w = obj(i, "wire"); return { wire_instruction_id: String(w.wire_instruction_id ?? ""), partner_id: String(w.partner_id ?? "partner-1"), payee_code: String(w.payee_code ?? ""), receiver_type: (w.receiver_type as WireInstruction["receiver_type"] | undefined) ?? "warehouse_lender", warehouse_lender_org_id: (w.warehouse_lender_org_id as string | undefined) ?? null, letter_type: (w.letter_type as WireInstruction["letter_type"] | undefined) ?? "bailee", bailee_letter_name: (w.bailee_letter_name as string | undefined) ?? null, status: (w.status as WireInstruction["status"] | undefined) ?? "pending", form_482_document_id: (w.form_482_document_id as string | undefined) ?? null, form_482_signed_by: (w.form_482_signed_by as string | undefined) ?? null, fnma_confirmation_call_at: null, approved_by_warehouse_at: null, approved_by_operator_id: null }; };
const adviceOf = (i: ToolInput): PurchaseAdviceInput => { const a = obj(i, "advice"); const c = (k: string): bigint => cents(a[k]); return { ...(typeof a.purchase_advice_id === "string" ? { purchase_advice_id: a.purchase_advice_id } : {}), fnma_loan_number: String(a.fnma_loan_number ?? ""), advice_date: D(String(a.advice_date ?? "")), purchase_date: D(String(a.purchase_date ?? "")), commitment_id_fnma: String(a.commitment_id_fnma ?? ""), payee_code: String(a.payee_code ?? ""), remittance_type: (a.remittance_type as RemittanceType | undefined) ?? "actual_actual", pass_through_rate: String(a.pass_through_rate ?? ""), servicing_fee_rate: String(a.servicing_fee_rate ?? "0.250"), price: String(a.price ?? ""), upb_cents: c("upb_cents"), principal_proceeds_cents: c("principal_proceeds_cents"), interest_adjustment_cents: c("interest_adjustment_cents"), llpa_total_cents: c("llpa_total_cents"), llpa_lines: ((a.llpa_lines as { code: string; pct: string; cents: unknown }[] | undefined) ?? []).map((l) => ({ code: String(l.code), pct: String(l.pct), cents: cents(l.cents) })), fees: ((a.fees as { kind: string; cents: unknown }[] | undefined) ?? []).map((f) => ({ kind: String(f.kind), cents: cents(f.cents) })), net_proceeds_cents: c("net_proceeds_cents"), wire_reference: (a.wire_reference as string | undefined) ?? null, source: (a.source as "api" | "connect_report" | undefined) ?? "api", raw_payload_document_id: (a.raw_payload_document_id as string | undefined) ?? null, received_at: String(a.received_at ?? "") }; };
const NO_UI = never("NO_FNMA_UI_AUTOMATION", "29.4 AI design / Consolidated Technology Guide: the agent never operates a Fannie Mae UI, never scripts a browser", (i) => flag(i, "script_browser") || flag(i, "automate_ui") || flag(i, "operate_ui"), "Loan Delivery import/submit/revise are human fnma_portal_operator acts with captured evidence");
const NO_STATUS_WITHOUT_EVIDENCE = never("STATUS_WITHOUT_EVIDENCE", "29.4 AI design: never accepts a status without evidence (`status_source` is always an evidence class)", (i) => flag(i, "accept_without_evidence") || (typeof i.op === "string" && ["purchase_error", "cancel_certification", "certified"].includes(i.op) && !optStr(i, "evidence_document_id") && !optStr(i, "notice_document_id")), "a Loan Delivery / custodian status is set only from an operator capture, a custodian notice, a Connect report, the Purchase Advice API or an eVault event");

export const TOOLS_29_4: readonly ToolDef[] = defineTools("29.4", "secondary", [
  // R2 / T1 / T5: register the delivery (29.3's row) and its wire instruction; take the frozen package; open the import_and_submit task (or request the 29.1 extension first).
  { name: "openOperatorTask", kind: "act", handler: compute((i, ctx, rt) => {
      const svc = svcOf(rt, ctx);
      if (i.op === "register") {
        need(i, "delivery_id", "loan_id", "application_id", "commitment_id_fnma", "commitment_expires_on", "note_form", "upb_cents", "note_rate", "pass_through_rate", "commitment_price", "disbursement_date", "first_payment_date");
        const input: DeliveryInput = { delivery_id: str(i, "delivery_id"), loan_id: str(i, "loan_id"), application_id: str(i, "application_id"), partner_id: str(i, "partner_id") || "partner-1", seller_loan_number: str(i, "seller_loan_number"), commitment_id_fnma: str(i, "commitment_id_fnma"), commitment_expires_on: D(str(i, "commitment_expires_on")), note_form: str(i, "note_form") as NoteForm, upb_cents: cents(i.upb_cents), note_rate: str(i, "note_rate"), pass_through_rate: str(i, "pass_through_rate"), servicing_fee_rate: str(i, "servicing_fee_rate") || "0.250", commitment_price: str(i, "commitment_price"), remittance_type: (optStr(i, "remittance_type") as RemittanceType | null) ?? "actual_actual", disbursement_date: D(str(i, "disbursement_date")), first_payment_date: D(str(i, "first_payment_date")),
          ...(i.enote_indicator !== undefined ? { enote_indicator: flag(i, "enote_indicator") } : {}), min: optStr(i, "min"), custodian_fin: optStr(i, "custodian_fin"), custodian_party_id: optStr(i, "custodian_party_id"), bailee_letter_id: optStr(i, "bailee_letter_id"), wire_instruction_id: optStr(i, "wire_instruction_id"), payee_code: optStr(i, "payee_code"), ...(i.commitment_closed !== undefined ? { commitment_closed: flag(i, "commitment_closed") } : {}), ...(optDate(i, "lpi_due_date") ? { lpi_due_date: D(str(i, "lpi_due_date")) } : {}) };
        const r = svc.register(input); if (i.wire) { const w = svc.registerWire(wireOf(i)); project(rt, ctx, "wire_instructions", w.wire_instruction_id, { ...w }); }
        project(rt, ctx, "deliveries", r.delivery_id, view(svc, r.delivery_id)); return view(svc, r.delivery_id);
      }
      const id = deliveryId(i, svc, ctx);
      if (i.op === "frozen") { need(i, "package_id", "sha256"); const r = svc.onPackageFrozen(id, { package_id: str(i, "package_id"), sha256: str(i, "sha256"), file_name: str(i, "file_name") || `${str(i, "package_id")}.xml`, frozen_at: at(i, "frozen_at", ctx) }); project(rt, ctx, "deliveries", id, view(svc, id)); return { delivery_id: id, package_id: r.package_id, sha256: r.package_sha256, frozen_at: r.frozen_at }; }
      if (i.op === "superseded" || i.op === "cancelled") { need(i, "package_id"); const out = svc.onPackageSuperseded(id, { package_id: str(i, "package_id"), reason: str(i, "reason") || "package_superseded", at: at(i, "at", ctx) }); for (const t of out.cancelled) project(rt, ctx, "delivery_operator_tasks", t.task_id, { ...t }); return { cancelled_task_ids: out.cancelled.map((t) => t.task_id) }; }
      if (i.op === "commitment_closed") { const r = svc.get(id); r.commitment_closed = true; if (optDate(i, "expires_on")) r.commitment_expires_on = D(str(i, "expires_on")); project(rt, ctx, "deliveries", id, view(svc, id)); return { delivery_id: id, commitment_closed: true, commitment_expires_on: r.commitment_expires_on }; }
      const out = svc.openOperatorTask({ delivery_id: id, at: at(i, "at", ctx), ...(Array.isArray(i.pre_justified_warnings) ? { pre_justified_warnings: i.pre_justified_warnings as string[] } : {}), ...(i.gate_facts ? { gate_facts: obj(i, "gate_facts") } : {}), fraud_hold: (i.fraud_hold as { fraud_hold: boolean; reason?: string | null } | undefined) ?? null });
      if (out.task) project(rt, ctx, "delivery_operator_tasks", out.task.task_id, { ...out.task }); if (out.warehouse_task) project(rt, ctx, "delivery_operator_tasks", out.warehouse_task.task_id, { ...out.warehouse_task });
      return { task_id: out.task?.task_id ?? null, escalation_id: out.escalation_id, sla_due_at: out.task?.sla_due_at ?? null, extension_requested: out.extension_requested, plan: out.plan, sheet: out.sheet, warehouse_task_id: out.warehouse_task?.task_id ?? null }; }),
    guardrails: [NO_UI, never("COMMITMENT_CLOSED_FIRST", "PE–WL FAQ Q26 / 29.4 edge case: the operator task waits on commitment.status = closed", (i) => i.commitment_closed === false && i.op === undefined, "best-efforts commitments appear in Loan Delivery once moved to closed status (29.1)")] },
  // The one-page instruction sheet (commitment number, payee code, Receiver Type / Letter Type, Bailee Letter Name, eNote indicator, expected edits, the four evidence items, the hash attestation).
  { name: "renderInstructionSheet", kind: "act", handler: compute((i, ctx, rt) => {
      const svc = svcOf(rt, ctx); const id = deliveryId(i, svc, ctx); const r = svc.get(id); need({ ...i, package_id: r.package_id, sha256: r.package_sha256 }, "package_id", "sha256");
      const w = i.wire ? wireOf(i) : svc.wire(r.wire_instruction_id); if (!w) throw new RangeError("29.4 tool needs a wire instruction (wire_instruction_id or wire)");
      return renderInstructionSheet({ package_id: r.package_id!, file_name: r.package_file_name ?? `${r.package_id}.xml`, sha256: r.package_sha256!, commitment_id_fnma: r.commitment_id_fnma, wire: w, enote_indicator: r.enote_indicator, ...(Array.isArray(i.pre_justified_warnings) ? { pre_justified_warnings: i.pre_justified_warnings as string[] } : {}) }); }),
    guardrails: [NO_UI] },
  // Task design (3)–(5): the evidence parser — four evidence items + hash attestation + captured values compared to the package; a blocked path with a reason code; fatal 3000-series edits go to 29.1 (no rebuild), other fatals supersede 29.3's package.
  { name: "parseOperatorEvidence", kind: "write", handler: compute((i, ctx, rt) => {
      need(i, "task_id", "operator_id"); const svc = svcOf(rt, ctx);
      const out = svc.completeOperatorTask({ task_id: str(i, "task_id"), operator_id: str(i, "operator_id"), evidence: list<{ kind: string; document_id: string }>(i, "evidence"), hash_confirmed: flag(i, "hash_confirmed"), captured_state: obj(i, "captured_state"), edits: list<CapturedEdit>(i, "edits"), ...(Array.isArray(i.pre_justified_warnings) ? { pre_justified_warnings: i.pre_justified_warnings as string[] } : {}), at: at(i, "at", ctx) });
      project(rt, ctx, "delivery_operator_tasks", out.task.task_id, { ...out.task }); project(rt, ctx, "deliveries", out.task.delivery_id, view(svc, out.task.delivery_id));
      const b = build(rt);
      if (b) { try { if (out.submission) b.markSubmitted(out.task.delivery_id); else if (out.blocked === "unexpected_edit" && list<CapturedEdit>(i, "edits").some((e) => e.severity === "fatal")) b.supersede(out.task.delivery_id, "loan_delivery_fatal_edit"); } catch { /* the 29.3 row may not exist in this runtime */ } }
      return { task_id: out.task.task_id, outcome: out.task.outcome, blocked: out.blocked, submitted: out.submission?.type ?? null, fnma_loan_number: svc.get(out.task.delivery_id).fnma_loan_number, expected: out.expected, relief: out.relief.map((r) => ({ component: r.component, delivered_with_conditions_met: r.delivered_with_conditions_met, status: r.status })) }; }),
    guardrails: [NO_UI, NO_STATUS_WITHOUT_EVIDENCE, never("EVIDENCE_LIST_REQUIRED", "29.4 T1: the task cannot be marked complete without the four evidence items and hash_confirmed = true", (i) => i.mark_complete === true && (!Array.isArray(i.evidence) || REQUIRED_EVIDENCE.some((k) => !(i.evidence as { kind: string }[]).some((e) => e.kind === k)) || !flag(i, "hash_confirmed")), "import result, Edit History CSV, loan-record print and Wire Details capture plus the hash attestation")] },
  // Loan Delivery / custodian states observed from evidence (never commanded): purchase error, Cancel Certification, withdrawal, LPI re-anchoring, custodian loan-number chain, wires (listed / Form 482 / payee activation), the C2-2-03 breach chain, LQC requests, relief confirmations.
  { name: "observeStatus", kind: "write", handler: compute((i, ctx, rt) => {
      const svc = svcOf(rt, ctx); const id = deliveryId(i, svc, ctx); const when = at(i, "at", ctx); const done = () => { project(rt, ctx, "deliveries", id, view(svc, id)); return view(svc, id); };
      switch (i.op ?? "read") {
        case "read": return view(svc, id);
        case "purchase_error": need(i, "evidence_document_id"); { const r = svc.purchaseErrorObserved({ delivery_id: id, edit_codes: list<string>(i, "edit_codes"), evidence_document_id: str(i, "evidence_document_id"), at: when }); done(); return { event: r.event.type, resubmit_due_on: r.resubmit_due_on }; }
        case "cancel_certification": need(i, "reason", "operator_id", "evidence_document_id"); svc.cancelCertification({ delivery_id: id, reason: str(i, "reason"), operator_id: str(i, "operator_id"), evidence_document_id: str(i, "evidence_document_id"), at: when }); return done();
        case "withdraw": need(i, "reason"); svc.withdraw({ delivery_id: id, reason: str(i, "reason"), at: when }); return done();
        case "payment_posted": need(i, "installment_due"); { const w = svc.onPaymentPosted(id, D(str(i, "installment_due")), when); done(); return w; }
        case "custodian_loan_number": need(i, "custodian_op"); return { event: svc.custodianLoanNumber({ delivery_id: id, op: str(i, "custodian_op") as "requested" | "responded" | "recorded", evidence_document_id: optStr(i, "evidence_document_id"), at: when }).type };
        case "wire_listed": need(i, "wire_instruction_id"); { const r = svc.wireListed({ wire_instruction_id: str(i, "wire_instruction_id"), delivery_id: id, at: when }); project(rt, ctx, "delivery_operator_tasks", r.task.task_id, { ...r.task }); return { task_id: r.task.task_id, event: r.event.type }; }
        case "form_482": need(i, "form_482_op", "wire_instruction_id"); { const e = svc.form482({ delivery_id: id, op: str(i, "form_482_op") as "submitted" | "activated", wire_instruction_id: str(i, "wire_instruction_id"), form_482_document_id: optStr(i, "form_482_document_id"), signed_by_role: optStr(i, "signed_by_role") ?? (ctx.actor.kind === "human" ? ctx.actor.role ?? null : null), beneficiary_changed: flag(i, "beneficiary_changed"), funding_approver_approved: flag(i, "funding_approver_approved"), at: when }); const w = svc.wire(str(i, "wire_instruction_id")); if (w) project(rt, ctx, "wire_instructions", w.wire_instruction_id, { ...w }); return { event: e.type, ...e.payload }; }
        case "security_breach": need(i, "breach_op", "detail"); return { event: svc.securityBreach({ delivery_id: id, op: str(i, "breach_op") as "detected" | "notified" | "confirmed", detail: str(i, "detail"), at: when }).type };
        case "lqc": need(i, "lqc_op", "request_id"); return { event: svc.lqc({ delivery_id: id, op: str(i, "lqc_op") as "requested" | "responded", request_id: str(i, "request_id"), stated_due_on: optDate(i, "stated_due_on"), document_ids: list<string>(i, "document_ids"), at: when }).type };
        case "relief_confirmed": need(i, "component", "fnma_report_id"); return svc.confirmRelief({ delivery_id: id, component: str(i, "component") as ReliefComponent, fnma_report_id: str(i, "fnma_report_id"), at: when });
        case "relief_lost": need(i, "component", "finding"); return svc.loseRelief({ delivery_id: id, component: str(i, "component") as ReliefComponent, finding: str(i, "finding"), qc_case_id: optStr(i, "qc_case_id"), at: when });
        default: throw new RangeError(`observeStatus op ${String(i.op)} is not one of read/purchase_error/cancel_certification/withdraw/payment_posted/custodian_loan_number/wire_listed/form_482/security_breach/lqc/relief_confirmed/relief_lost`);
      } }),
    guardrails: [NO_UI, NO_STATUS_WITHOUT_EVIDENCE, never("RELIEF_CONFIRM_NEEDS_FNMA_REPORT", "29.4 AI design: never marks relief confirmed_by_fnma without a Fannie Mae report", (i) => i.op === "relief_confirmed" && !optStr(i, "fnma_report_id"), "relief is confirmed only by Fannie Mae's relief reports (A2-3.2-02)"),
      needsRole("FORM_482_OFFICER", "C2-2-07 / 29.4 capacity: the partner's officer signs Forms 482/360", (i) => i.op === "form_482" && i.form_482_op === "submitted" && !optStr(i, "signed_by_role"), ["officer"], "a Form 482 submission is the partner officer's act")] },
  // C2-2-02: the custodian package is tendered to the overnight carrier (first-morning service) the same day as the data submission; op=plan gives the pickup cutoff for the submission day.
  { name: "scheduleShipment", kind: "act", handler: compute((i, ctx, rt) => {
      const svc = svcOf(rt, ctx);
      if (i.op === "plan") { need(i, "submitted_at"); const d = etDate(str(i, "submitted_at")); return { ship_on: d, pickup_cutoff_at: mtInstant(d, CARRIER_PICKUP_HHMM_MT), first_morning_service: true, expected: expectedDates(str(i, "submitted_at")) }; }
      const id = deliveryId(i, svc, ctx); need(i, "carrier", "tracking_number", "tendered_at");
      const r = svc.recordShipment({ delivery_id: id, carrier: str(i, "carrier"), tracking_number: str(i, "tracking_number"), tendered_at: str(i, "tendered_at"), first_morning_service: i.first_morning_service !== false, package_document_ids: list<string>(i, "package_document_ids"), ...(optStr(i, "custody_mode") ? { custody_mode: str(i, "custody_mode") as CustodyMode } : {}), at: at(i, "at", ctx) });
      project(rt, ctx, "custodian_certifications", r.certification.certification_id, { ...r.certification }); return { certification_id: r.certification.certification_id, event: r.event.type, same_day_as_submit: r.same_day_as_submit }; }) },
  // Carrier tracking → receipt (recomputed expectations); custodian notices → certification / data revisions (R4).
  { name: "trackShipment", kind: "write", handler: compute((i, ctx, rt) => {
      const svc = svcOf(rt, ctx); const id = deliveryId(i, svc, ctx); const when = at(i, "at", ctx); const keep = (cid: string) => { const c = svc.certifications.find((x) => x.certification_id === cid); if (c) project(rt, ctx, "custodian_certifications", cid, { ...c }); project(rt, ctx, "deliveries", id, view(svc, id)); };
      switch (i.op ?? "received") {
        case "received": need(i, "received_at"); { const r = svc.recordReceipt({ delivery_id: id, received_at: str(i, "received_at"), at: when }); keep(r.certification.certification_id); return { certification_id: r.certification.certification_id, ...r.recompute }; }
        case "certified": need(i, "certified_at", "certification_kind"); { const r = svc.recordCertification({ delivery_id: id, certified_at: str(i, "certified_at"), certification_kind: str(i, "certification_kind") as CertificationKind, ...(optStr(i, "bailee_validation") ? { bailee_validation: str(i, "bailee_validation") as "n/a" | "passed" | "failed" } : {}), bailee_letter_name_used: optStr(i, "bailee_letter_name_used"), notice_document_id: optStr(i, "notice_document_id") ?? optStr(i, "evidence_document_id"), at: when }); keep(r.certification.certification_id); return { certification_id: r.certification.certification_id, purchase_ready_at: svc.get(id).purchase_ready_at, expected_purchase_date: r.expected_purchase_date, loan_age: r.loan_age }; }
        case "data_revision_received": need(i, "revision"); { const rev = obj(i, "revision"); const r = svc.dataRevisionReceived({ delivery_id: id, revision: { field: String(rev.field ?? ""), custodian_value: String(rev.custodian_value ?? ""), seller_value: String(rev.seller_value ?? ""), editable_by_custodian: rev.editable_by_custodian !== false } satisfies DataRevision, notice_document_id: optStr(i, "notice_document_id"), at: when }); keep(r.certification.certification_id); return { certification_id: r.certification.certification_id, response_due_on: r.response_due_on }; }
        case "data_revision_prepare": need(i, "field", "note"); { const n = obj(i, "note"); const r = svc.prepareDataRevisionResponse({ delivery_id: id, field: str(i, "field"), note: { value: String(n.value ?? ""), page_ref: String(n.page_ref ?? "") }, at: when }); project(rt, ctx, "delivery_operator_tasks", r.task.task_id, { ...r.task }); return { ...r.decision, task_id: r.task.task_id, response_due_on: r.response_due_on }; }
        case "data_revision_responded": need(i, "field", "operator_id", "evidence_document_id"); { const r = svc.recordDataRevisionResponse({ delivery_id: id, field: str(i, "field"), accepted: flag(i, "accepted"), operator_id: str(i, "operator_id"), evidence_document_id: str(i, "evidence_document_id"), at: when }); project(rt, ctx, "deliveries", id, view(svc, id)); return { event: r.event.type, edit_observed: r.edit_observed?.type ?? null, reviews: r.reviews.map((e) => (e.payload as { process: string }).process) }; }
        default: throw new RangeError(`trackShipment op ${String(i.op)} is not one of received/certified/data_revision_received/data_revision_prepare/data_revision_responded`);
      } }),
    guardrails: [NO_STATUS_WITHOUT_EVIDENCE] },
  // E-2-01 with the `post-closing` agent: cover letter, bailee letter (27.1) listing the loan, note endorsed in blank by the partner's signing_officer, POA / name affidavit / riders where applicable — Form 2004A only when SM waives its bailee wire instructions.
  { name: "prepareCustodianPackage", kind: "act", handler: compute((i, ctx, rt) => {
      const svc = svcOf(rt, ctx); const id = deliveryId(i, svc, ctx); const r = svc.get(id);
      if (r.note_form === "enote") return { delivery_id: id, custody_mode: "evault_auto", documents: [], note: "eNote: Fannie Mae is the custodian (A3-3-04); eDelivery via requestEnoteTransfer — no paper package, no bailee letter" };
      need(i, "note_document_id", "endorsement_signing_officer");
      const docs: { kind: string; document_id: string | null; required: boolean }[] = [{ kind: "cover_letter", document_id: `doc-cover-${id}`, required: true }, { kind: "original_note_endorsed_in_blank", document_id: str(i, "note_document_id"), required: true }, { kind: "bailee_letter", document_id: r.bailee_letter_id, required: !!r.bailee_letter_id }, { kind: "power_of_attorney", document_id: optStr(i, "poa_document_id"), required: flag(i, "poa_used") }, { kind: "name_affidavit", document_id: optStr(i, "name_affidavit_document_id"), required: flag(i, "aka_signature") }, { kind: "note_modification_originals", document_id: optStr(i, "modification_document_id"), required: flag(i, "note_modified") }, { kind: "form_2004a", document_id: optStr(i, "form_2004a_document_id"), required: flag(i, "form_2004a_used") }];
      const missing = docs.filter((d) => d.required && !d.document_id).map((d) => d.kind);
      return { delivery_id: id, custody_mode: (optStr(i, "custody_mode") as CustodyMode | null) ?? "shipped_package", documents: docs.filter((d) => d.required || d.document_id), missing, complete: missing.length === 0, endorsed_by: str(i, "endorsement_signing_officer"), deed_of_trust_copy_required: false, min_on_note: !!r.min, ship_with_instructions: "overnight, first morning delivery (C2-2-02)" }; }),
    guardrails: [never("ENDORSEMENT_BY_SIGNING_OFFICER", "E-2-01 / 29.4 escalations: note endorsement / allonge by the partner's signing_officer before shipment", (i) => i.endorsed_by_agent === true, "the original note is endorsed in blank by the partner's signing_officer, never by the agent")] },
  // C1-2-04 (eVault adapter shared with 1.4): eDelivery to Fannie Mae's eVault; Transfer of Control and Location with a same-day effective date (SM as Secured Party approves under the eNote Control Transfer and Custodial Agreement); completion from the eRegistry notification.
  { name: "requestEnoteTransfer", kind: "act", handler: compute(async (i, ctx, rt) => {
      const svc = svcOf(rt, ctx); const id = deliveryId(i, svc, ctx);
      const r = await svc.requestEnoteTransfer({ delivery_id: id, op: (optStr(i, "op") as "edeliver" | "transfer" | "completed" | null) ?? "transfer", ...(optDate(i, "effective_date") ? { effective_date: D(str(i, "effective_date")) } : {}), at: at(i, "at", ctx), ...(optStr(i, "transfer_id") ? { transfer_id: str(i, "transfer_id") } : {}), ...(optStr(i, "partner_org_id") ? { partner_org_id: str(i, "partner_org_id") } : {}), ...(optStr(i, "master_servicer_org_id") ? { master_servicer_org_id: str(i, "master_servicer_org_id") } : {}), ...(i.delegatee_on_file !== undefined ? { delegatee_on_file: flag(i, "delegatee_on_file") } : {}), document_ids: list<string>(i, "document_ids") });
      project(rt, ctx, "deliveries", id, view(svc, id)); return { event: r.event.type, gate: r.gate, accepted: r.accepted, ...r.event.payload }; }),
    guardrails: [never("ENOTE_CONTROLLER_NEEDS_DELEGATEE", "29.4 AI design: never changes the eNote Controller without the partner's authorization on file (Delegatee for Transfers)", (i) => i.delegatee_on_file === false, "a Transfer of Control needs the partner's Delegatee for Transfers authorization on file")] },
  // R5 / T7: the platform pre-check (byte comparison of the entered Letter Name to `bailee_letters.letter_name` letterhead text) prepares the SM-org task; a human fnma_portal_operator in SM's warehouse org approves (Pending → Active).
  { name: "approveWarehouseWire", kind: "act", handler: compute((i, ctx, rt) => {
      need(i, "entered_letter_name", "letterhead_text");
      if (i.op === "precheck") return baileeNameCheck(str(i, "entered_letter_name"), str(i, "letterhead_text"));
      const svc = svcOf(rt, ctx); const id = deliveryId(i, svc, ctx); need(i, "wire_instruction_id");
      const r = svc.approveWarehouseWire({ wire_instruction_id: str(i, "wire_instruction_id"), delivery_id: id, entered_letter_name: str(i, "entered_letter_name"), letterhead_text: str(i, "letterhead_text"), operator_id: str(i, "operator_id") || ctx.actor.id, ...(ctx.actor.kind === "human" ? { operator_role: ctx.actor.role ?? "" } : {}), at: at(i, "at", ctx) });
      project(rt, ctx, "wire_instructions", r.wire.wire_instruction_id, { ...r.wire }); return { ...r.check, status: r.wire.status, event: r.event?.type ?? null, blocked: !r.check.matches }; }),
    guardrails: [needsRole("WAREHOUSE_WIRE_HUMAN_OPERATOR", "29.4 AI design: never approves a wire instruction (SM warehouse org) without a human fnma_portal_operator in that org", (i) => i.op !== "precheck", ["fnma_portal_operator"], "the agent prepares the SM-org task; the approval click is the operator's")] },
  // R1 / R2: the pure calculators — expected dates from a submission, recomputation on receipt/certification, the LPI window / loan age / seasoning, the custodian receipt deadline and the operator task plan.
  { name: "computeExpectedDates", kind: "read", handler: compute((i) => {
      switch (i.op ?? "expected") {
        case "expected": need(i, "submitted_at"); return expectedDates(str(i, "submitted_at"));
        case "receipt": need(i, "received_at"); return recomputeOnReceipt(str(i, "received_at"));
        case "certification": need(i, "certified_at"); return recomputeOnCertification(str(i, "certified_at"));
        case "lpi": need(i, "first_payment_date"); { const w = lpiWindow(D(str(i, "first_payment_date")), optDate(i, "last_paid_installment_due")); return { ...w, ...(optDate(i, "purchase_ready_at") ? { loan_age: loanAgeCheck(D(str(i, "first_payment_date")), D(str(i, "purchase_ready_at"))) } : {}), seasoned: seasonedCheck(D(str(i, "first_payment_date")), optDate(i, "purchase_date"), D(str(i, "today") || etDate(new Date().toISOString()))) }; }
        case "receipt_deadline": need(i, "expires_on"); return custodianReceiptDeadline(D(str(i, "expires_on")));
        case "plan": need(i, "frozen_at", "expires_on"); return receiptPlan(str(i, "frozen_at"), D(str(i, "expires_on")));
        case "operator_due": need(i, "frozen_at"); return operatorTaskDue(str(i, "frozen_at"));
        case "wire_gate": return wireGate(i.wire ? wireOf(i) : null, flag(i, "warehouse_task_open"));
        case "advice_lag": need(i, "purchase_ready_on", "today"); return adviceLagCheck(D(str(i, "purchase_ready_on")), D(str(i, "today")), flag(i, "advice_received"));
        default: throw new RangeError(`computeExpectedDates op ${String(i.op)} is not one of expected/receipt/certification/lpi/receipt_deadline/plan/operator_due/wire_gate/advice_lag`);
      } }) },
  // Purchase Advice Sellers API (daily pull) / Connect report: idempotent ingest → purchase date, Purchased and Funded, `loan.purchased` once (30.1/5.x/25.4 consume); op=lag opens the Connect download task after two business days without an advice (T14).
  { name: "ingestPurchaseAdvice", kind: "write", handler: compute((i, ctx, rt) => {
      const svc = svcOf(rt, ctx); const id = deliveryId(i, svc, ctx);
      if (i.op === "lag") { need(i, "today"); const r = svc.adviceLag({ delivery_id: id, today: D(str(i, "today")), at: at(i, "at", ctx) }); for (const t of [r.task, r.breach_check]) if (t) project(rt, ctx, "delivery_operator_tasks", t.task_id, { ...t }); return { ...r.check, task_id: r.task?.task_id ?? null, breach_check_task_id: r.breach_check?.task_id ?? null }; }
      need(i, "advice");
      const r = svc.ingestPurchaseAdvice({ delivery_id: id, advice: adviceOf(i), at: at(i, "at", ctx) });
      project(rt, ctx, "purchase_advices", r.advice.purchase_advice_id, { ...r.advice, upb_cents: String(r.advice.upb_cents), principal_proceeds_cents: String(r.advice.principal_proceeds_cents), interest_adjustment_cents: String(r.advice.interest_adjustment_cents), llpa_total_cents: String(r.advice.llpa_total_cents), net_proceeds_cents: String(r.advice.net_proceeds_cents) }); project(rt, ctx, "deliveries", id, view(svc, id));
      return { purchase_advice_id: r.advice.purchase_advice_id, replayed: r.replayed, purchase_date: svc.get(id).purchase_date, acquisition_date: svc.get(id).acquisition_date, loan_purchased_emitted: r.purchased !== null, loan_delivery_status: svc.get(id).loan_delivery_status }; }),
    guardrails: [never("RELEASE_BEFORE_PROCEEDS", "29.4 AI design: never releases SM's warehouse interest before proceeds are confirmed received (C2-2-03 / 27.2)", (i) => flag(i, "release_warehouse_interest"), "the bailee release is 27.2's act on proceeds receipt, never a delivery-side assertion"),
      NO_STATUS_WITHOUT_EVIDENCE] },
  // R3: the tie-out against the platform's expected range (30/360 and act/365 until 27.2 fixes the day count); 27.2 receives `purchase_advice.reconciled{variance_cents}`; a Fannie Mae-error variance becomes the officer's adjustment-request package inside 27.2's 30-day clock. op=expected / op=slip_cost are the pure calculators.
  { name: "reconcileProceeds", kind: "write", handler: compute((i, ctx, rt) => {
      if (i.op === "expected") { need(i, "upb_cents", "price", "pass_through_rate", "purchase_date", "lpi_due_date"); return expectedProceeds({ upb_cents: cents(i.upb_cents), price: str(i, "price"), pass_through_rate: str(i, "pass_through_rate"), purchase_date: D(str(i, "purchase_date")), lpi_due_date: D(str(i, "lpi_due_date")), ...(optStr(i, "remittance_type") ? { remittance_type: str(i, "remittance_type") as RemittanceType } : {}), llpa_total_cents: cents(i.llpa_total_cents), fees_cents: cents(i.fees_cents) }); }
      if (i.op === "slip_cost") { need(i, "advance_cents", "all_in_rate_bps"); return { cost_cents: warehouseSlipCostCents(cents(i.advance_cents), num(i, "all_in_rate_bps"), i.days === undefined ? 1 : num(i, "days")), advance_cents: cents(i.advance_cents), borne_by: "sm" }; }
      if (i.op === "tie_out") { need(i, "advice", "expected"); const e = obj(i, "expected"); const a = adviceOf(i); return reconcileProceeds(a, { principal_proceeds_cents: cents(e.principal_proceeds_cents), interest: { days: Number(e.interest_days ?? 0), prepaid: e.prepaid !== false, cents_30_360: cents(e.interest_30_360_cents), cents_act_365: cents(e.interest_act_365_cents) }, llpa_total_cents: cents(e.llpa_total_cents), fees_cents: cents(e.fees_cents), expected_net_low_cents: cents(e.expected_net_low_cents), expected_net_high_cents: cents(e.expected_net_high_cents), expected_net_cents: cents(e.expected_net_cents ?? e.expected_net_low_cents) }); }
      const svc = svcOf(rt, ctx); const id = deliveryId(i, svc, ctx); need(i, "llpa_expected_cents");
      const r = svc.reconcile({ delivery_id: id, ...(optStr(i, "purchase_advice_id") ? { purchase_advice_id: str(i, "purchase_advice_id") } : {}), llpa_expected_cents: cents(i.llpa_expected_cents), ...(i.fees_expected_cents !== undefined ? { fees_expected_cents: cents(i.fees_expected_cents) } : {}), at: at(i, "at", ctx) });
      const a = svc.advices.find((x) => x.delivery_id === id); if (a) project(rt, ctx, "purchase_advices", a.purchase_advice_id, { expected_net_proceeds_cents: String(a.expected_net_proceeds_cents), variance_cents: String(a.variance_cents), reconciled_at: a.reconciled_at });
      return { ...r.reconciliation, variance_cents: String(r.reconciliation.variance_cents), decomposition: r.reconciliation.decomposition.map((d) => ({ ...d, cents: String(d.cents) })), expected_net_low_cents: String(r.expected.expected_net_low_cents), expected_net_high_cents: String(r.expected.expected_net_high_cents), escalation_id: r.escalation_id, event: r.event.type }; }),
    guardrails: [never("ADJUSTMENT_REQUEST_NEEDS_OFFICER", "29.4 escalations: the officer receives the adjustment-request package for any variance > $1,000; the request to Fannie Mae is the officer's act", (i) => flag(i, "file_adjustment_request") && !optStr(i, "officer_approval_id"), "an adjustment request is filed only with the officer's approval escalation completed")] },
  // R7 / T12: per-component conditions at submission (op default: pure; op=book writes the rows on the delivery); confirmations only from Fannie Mae's relief reports; QC findings (28.2) lose.
  { name: "evaluateRelief", kind: "write", handler: compute((i, ctx, rt) => {
      const components = list<ReliefComponent>(i, "components"); const facts = obj(i, "facts") as ReliefFacts;
      if (i.op === undefined || i.op === "evaluate") { need(i, "components"); return evaluateRelief(components, { ...facts, ...(typeof facts.close_by_date === "string" ? { close_by_date: D(facts.close_by_date) } : {}), ...(typeof facts.consummation_date === "string" ? { consummation_date: D(facts.consummation_date) } : {}) }); }
      const svc = svcOf(rt, ctx); const id = deliveryId(i, svc, ctx);
      if (i.op === "book") { need(i, "components"); return svc.bookRelief(svc.get(id), components, facts, at(i, "at", ctx)).map((r) => ({ relief_id: r.relief_id, component: r.component, delivered_with_conditions_met: r.delivered_with_conditions_met, status: r.status })); }
      if (i.op === "confirm") { need(i, "component", "fnma_report_id"); return svc.confirmRelief({ delivery_id: id, component: str(i, "component") as ReliefComponent, fnma_report_id: str(i, "fnma_report_id"), at: at(i, "at", ctx) }); }
      if (i.op === "lost") { need(i, "component", "finding"); return svc.loseRelief({ delivery_id: id, component: str(i, "component") as ReliefComponent, finding: str(i, "finding"), qc_case_id: optStr(i, "qc_case_id"), at: at(i, "at", ctx) }); }
      throw new RangeError(`evaluateRelief op ${String(i.op)} is not one of evaluate/book/confirm/lost`); }),
    guardrails: [never("RELIEF_CONFIRM_NEEDS_FNMA_REPORT", "29.4 AI design: never marks relief confirmed_by_fnma without a Fannie Mae report", (i) => i.op === "confirm" && !optStr(i, "fnma_report_id"), "relief is confirmed only by Fannie Mae's relief reports (A2-3.2-02)")] },
  // R8 / T11: seller-initiated PPA (18-month LLPA lookback, $100 minimum, the LSDU .csv and document names, 10-BD processing); LSDU upload is the operator's act with the officer where money moves; op=plan is the pure calculator.
  { name: "preparePpa", kind: "write", handler: compute((i, ctx, rt) => {
      const attrs = list<PpaAttribute>(i, "attributes");
      if (i.op === "plan") { need(i, "fnma_loan_number", "acquisition_date", "discovered_on"); return preparePpa({ fnma_loan_number: str(i, "fnma_loan_number"), acquisition_date: D(str(i, "acquisition_date")), discovered_on: D(str(i, "discovered_on")), attributes: attrs, expected_llpa_delta_cents: cents(i.expected_llpa_delta_cents), submitted_on: optDate(i, "submitted_on") }); }
      const svc = svcOf(rt, ctx); const id = deliveryId(i, svc, ctx); const when = at(i, "at", ctx);
      if (i.op === undefined || i.op === "open") { need(i, "attributes"); const r = svc.openPpa({ delivery_id: id, discovered_at: at(i, "discovered_at", ctx), attributes: attrs, expected_llpa_delta_cents: cents(i.expected_llpa_delta_cents), initiated_by: (optStr(i, "initiated_by") as "seller" | "fnma_lqc" | null) ?? "seller", at: when }); project(rt, ctx, "post_purchase_adjustments", r.ppa.ppa_id, { ...r.ppa, expected_llpa_delta_cents: String(r.ppa.expected_llpa_delta_cents), plan: { ...r.ppa.plan, expected_llpa_delta_cents: String(r.ppa.plan.expected_llpa_delta_cents) } }); return { ppa_id: r.ppa.ppa_id, status: r.ppa.status, repricing_eligible: r.ppa.repricing_eligible, repricing_due_on: r.ppa.plan.repricing_due_on, llpa_draft_expected: r.ppa.plan.llpa_draft_expected, csv_rows: r.ppa.plan.csv_rows, document_names: r.ppa.plan.document_names }; }
      need(i, "ppa_id");
      const r = svc.ppaStatus({ delivery_id: id, ppa_id: str(i, "ppa_id"), op: str(i, "op") as "submitted" | "processed" | "closed" | "declined", operator_id: str(i, "operator_id") || ctx.actor.id, officer_approval_id: optStr(i, "officer_approval_id"), notification_report_document_id: optStr(i, "notification_report_document_id"), ...(i.llpa_draft_or_refund_cents !== undefined ? { llpa_draft_or_refund_cents: cents(i.llpa_draft_or_refund_cents) } : {}), at: when });
      project(rt, ctx, "post_purchase_adjustments", r.ppa.ppa_id, { status: r.ppa.status, lsdu_submitted_at: r.ppa.lsdu_submitted_at, llpa_draft_or_refund_cents: r.ppa.llpa_draft_or_refund_cents === null ? null : String(r.ppa.llpa_draft_or_refund_cents) });
      return { ppa_id: r.ppa.ppa_id, status: r.ppa.status, event: r.event.type, processing_expected_on: r.processing_expected_on }; }),
    guardrails: [NO_UI, never("PPA_MONEY_NEEDS_OFFICER", "29.4 AI design: never files a PPA … without the partner officer's approval where money moves", (i) => i.op === "submitted" && flag(i, "llpa_draft_expected") && !optStr(i, "officer_approval_id"), "an LLPA draft/refund moves money — the partner officer approves the PPA first")] },
  // R9 / T13: the remedy execution plan (60-day payment, collateral return by Form 2009-equivalent or eNote Transfer of Control, servicing 5.6's LAR 65/67, no 27.1 re-advance without the facility flag); 28.2 owns the case and the appeal ladder.
  { name: "prepareRemedyPackage", kind: "act", handler: compute((i, ctx, rt) => {
      need(i, "demand_on");
      if (i.op === "plan") return remedyPlan({ demand_on: D(str(i, "demand_on")), paid_on: optDate(i, "paid_on"), note_form: (optStr(i, "note_form") as NoteForm | null) ?? "paper", liquidated: flag(i, "liquidated"), arm_modification_feature: flag(i, "arm_modification_feature"), flags: obj(i, "flags") });
      const svc = svcOf(rt, ctx); const id = deliveryId(i, svc, ctx); need(i, "repurchase_id");
      const r = svc.remedy({ delivery_id: id, repurchase_id: str(i, "repurchase_id"), demand_on: D(str(i, "demand_on")), paid_on: optDate(i, "paid_on"), officer_approval_document_id: optStr(i, "officer_approval_document_id"), liquidated: flag(i, "liquidated"), arm_modification_feature: flag(i, "arm_modification_feature"), flags: obj(i, "flags"), at: at(i, "at", ctx) });
      return { ...r.plan, collateral_event: r.collateral?.type ?? null, lar_action_code: r.lar?.action_code ?? null, lar_due_at: r.lar?.due_ms ? new Date(r.lar.due_ms).toISOString() : null, lar_blocked: r.lar?.blocked ?? null, readvance_event: r.readvance?.type ?? null, case_owner: "28.2" }; }),
    guardrails: [needsRole("REMEDY_PAYMENT_OFFICER", "29.4 AI design / A2-3.2-01: never files a remedy payment without the partner officer's approval", (i) => flag(i, "officer_approved"), ["officer"], "the officer authorizes the repurchase / make-whole payment in the escalation"),
      never("READVANCE_NEEDS_FACILITY_FLAG", "29.4 T13 / R9: the platform blocks any 27.1 re-advance unless the facility flag warehouse.repurchase_advance is on", (i) => flag(i, "readvance") && obj(i, "flags")["warehouse.repurchase_advance"] !== true, "SM's warehouse does not re-fund a repurchase by default")] },
  { name: "writeDecision", kind: "write", handler: decision() },
]);
