/**
 * §12 tools — loss mitigation (`lossmit-underwriter`). Every tool string is
 * the spec's verbatim; 12.3 names none (its agent runs on the 12.2 bus) and
 * 12.7 names no agent (its two registry lookups run under the same agent as
 * 12.6). Guardrails encode the "cannot"/"never" sentences on conditions the
 * handler can observe (the store, the calculator's own output, the clock):
 * no classification the rules engine did not make, no ack after the clock
 * without an escalation, no denial/appeal/adverse notice without the human
 * reviewer, no term breaching a gate or lacking its Reg X basis, no
 * hand-entered NIB or offer terms, no FEMA basis without a registry match,
 * no relocation with a contribution, no funding over a settlement finding.
 */
import { defineTools, escalate, compute, never, needsRole, noticeOps, port, read, write, readWrite, log, timerOps, ledgerPost, cents, str, num, flag, type ToolDef, type ToolInput } from "../tools.ts";
import { plainDate as D, endOfMonth, type PlainDate } from "../../kernel/calendar/date.ts";
import type { CommandContext } from "../commands.ts";
import type { ToolRuntime } from "../tools.ts";
import { addBusinessDays, federal } from "../../kernel/calendar/business.ts";
import { classify, ackDue, completeness, protectionTier, type Requirement } from "../../domain/lossmit/application.ts";
import { hierarchyWalk, tier, evaluationDeadlines, reviewerRequired, rankingReasonAllowed, type Option } from "../../domain/lossmit/evaluation.ts";
import { forbearanceTerm, forbearanceTermDates, repaymentTerms, repaymentPlan } from "../../domain/lossmit/plans.ts";
import { screen, nib, type DeferralFacts } from "../../domain/lossmit/deferral.ts";
import { waterfall, type WaterfallInputs } from "../../domain/lossmit/flexmod.ts";
import { contribution, netProceeds, negotiated, type ContributionFacts } from "../../domain/lossmit/liquidation.ts";
import { intake_12_1 } from "./section12-1.ts";
import { rfaFlow, nprmRfa, denialNoticeContent, referralGate, repaymentBrpGate, repaymentExtension, capStructure, capRetest, deferralLedger, forbearanceActivation, forbearanceBasisGate, mirLookup, delegationRouting, settlementReview, liquidationHolds, shortSaleClosingClock, type RegxBasis } from "../../domain/lossmit/ops.ts";
import { forbearanceOps_12_4, contactsOps_12_4, exceptionRequestOps_12_4, statusCodeOps_12_4, feesSuppressOps_12_4, emitTermCreate_12_4 } from "./section12-4.ts";
import { evaluationOps_12_2, timerOps_12_2, afterDenialSent } from "./section12-2.ts";
import { appealOps_12_3 } from "./section12-3.ts";
import { inboundOps_12_9, INBOUND_OPS_12_9 } from "./section12-9.ts";
import { repaymentPlanOps, statusReportOps, termCreate, buildSchedule, type RepaymentEnv } from "../../domain/lossmit/ops-12-5.ts";
import { offerDeferral, completeDeferral, assertDeferralCompletable } from "../../domain/lossmit/ops-12-6.ts";

const need = (i: ToolInput, ...keys: string[]): void => { for (const k of keys) if (i[k] === undefined || i[k] === null || i[k] === "") throw new RangeError(`${k} is required`); };
const date = (i: ToolInput, k: string): PlainDate => { need(i, k); return D(str(i, k)); };
const optDate = (i: ToolInput, k: string): PlainDate | null => (i[k] === undefined || i[k] === null || i[k] === "" ? null : D(str(i, k)));
const AGENT = "lossmit-underwriter";
/** Every adverse or human-signed determination — denials, ineligibility, closures, plan failures and the 12.3 appeal determinations — carries a recorded `lossmit_reviewer` approval before the notice renders (12.2 guardrail; 12.3 "cannot issue a notice before the human decision"; §1024.41(h)(3)). */
const REVIEWER_TEMPLATES = /DENIAL|INELIGIBLE|DECLINE|ADVERSE|INCOMPLETE_CLOSED|DUPLICATIVE|TPP_FAILED|REPAY_FAILED|FORB_TERMINATION|APPEAL_DENIED|APPEAL_GRANTED|APPEAL_INELIGIBLE/;
const REVIEWER_GATE = needsRole("DENIAL_NEEDS_REVIEWER", "12.2/12.3 guardrail: no denial, adverse or appeal-determination notice without the human reviewer's recorded decision", (i) => REVIEWER_TEMPLATES.test(str(i, "template_code")) && !i.reviewer_approval_id, ["lossmit_reviewer"], "record the lossmit_reviewer approval id first");
const TEMPLATE_ONLY = never("TEMPLATE_TEXT_ONLY", "12.x guardrail: borrower-facing text only from templates", (i) => typeof i.free_text === "string" && i.free_text.length > 0, "no free-text legal statements");
const timers = (): Omit<ToolDef, "process" | "agent"> => ({ name: "timers.*", kind: "act", handler: timerOps() });
/** Offer-bearing §12 templates: Evaluation Notices that open a borrower response window (§1024.41(e)(1); D2-2-05 14 days; NY 419.7(g)). */
const OFFER_TEMPLATE = /OFFER|SS_ELIGIBILITY/;
const latestEvaluation = (rt: ToolRuntime, loanId: string) => rt.store.list("lossmit_evaluations", (d) => d.loan_id === loanId).at(-1) ?? null;
/**
 * Every §12 notice goes through the Notice Registry; when an offer template is actually sent, the handler also emits
 * `lossmit.offer.sent{template, kind=offer, option, tier, state, provided_at}` — the trigger of the acceptance clocks
 * (`REGX_1024_41E1_ACCEPT_14/7`, `NY_419_7G_ACCEPT_30`, 11.5's `FNMA_D2205_ACCEPT_14`). "Provides the offer" = the send
 * date (12.2 rule 7); tier/state come from the caller or the loan's latest evaluation record.
 */
const sendNotice = async (mode: "render_send" | "send", i: ToolInput, ctx: CommandContext, rt: ToolRuntime): Promise<unknown> => {
  const r = (await noticeOps(mode)(i, ctx, rt)) as { id: string; status?: string; templateCode?: string };
  const code = str(i, "template_code") || r.templateCode || "";
  if (OFFER_TEMPLATE.test(code) && r.status === "sent") {
    const loanId = (i.loan_id as string | undefined) ?? ctx.loanId; const ev = latestEvaluation(rt, loanId);
    ctx.events.append({ type: "lossmit.offer.sent", loanId, actor: ctx.actor, payload: { notice_id: r.id, template: code, kind: "offer", option: str(i, "option") || (ev?.data.option as string | undefined) || null, tier: str(i, "tier") || (ev?.data.tier as string | undefined) || null, state: str(i, "state") || (ev?.data.state as string | undefined) || null, evaluation_id: ev?.id ?? null, provided_at: ctx.now.slice(0, 10), principal_residence: i.principal_residence === undefined ? null : flag(i, "principal_residence"), in_foreclosure: i.in_foreclosure === undefined ? null : flag(i, "in_foreclosure") } });
  }
  return r;
};
const noticeTool = (): Omit<ToolDef, "process" | "agent"> => ({ name: "notice.render_send", kind: "act", handler: compute((i, ctx, rt) => sendNotice("render_send", i, ctx, rt)), guardrails: [REVIEWER_GATE, TEMPLATE_ONLY] });
const PLAN_END_STATUSES = new Set(["terminated", "expired", "completed", "failed"]);
const PLAN_END_OPS: Record<string, string> = { end: "", terminate: "terminated", expire: "expired", complete: "completed", fail: "failed" };
/**
 * 12.4/12.5 `workout_plan.*` lifecycle beyond activation — one event vocabulary for the plan timers:
 *  - op=offer   → `workout_plan.offered{kind, offer_date, regx_short_term, application_complete}` (Evaluation Notice / (c)(2)(iii) terms-notice clocks);
 *  - op=end | terminate | expire | complete | fail (or status ∈ {terminated, expired, completed, failed})
 *               → `workout_plan.ended{status, kind, term_end, ended_on, qrpc, deferral_eligible, flex_eligible, disaster, start_days_delinquent, failed_month_end}`
 *                 (releases `REGX_1024_41C2III_PERFORMANCE_HOLD`; arms the post-plan solicitation and incentive clocks);
 *  - op=close   → `workout_plan.closed{kind, closed_reason}` (the disposition that satisfies `FNMA_D23201_FORB_EXPIRY_DISPOSITION`).
 * Returns undefined when the op is an activation, so the caller's term/activation path runs.
 */
const planLifecycle = (kind: "forbearance" | "repayment_plan", i: ToolInput, ctx: CommandContext, rt: ToolRuntime): unknown => {
  const today = ctx.now.slice(0, 10); const loanId = str(i, "loan_id"); const prefix = kind === "forbearance" ? "wp" : "rp";
  if (i.op === "offer") {
    const offerDate = str(i, "offered_on") || today; const rec = rt.store.put("workout_plans", str(i, "id") || `${prefix}-${loanId}-offer-${offerDate}`, { loan_id: loanId, kind, status: "offered", offered_on: offerDate, requested_months: num(i, "requested_months") || num(i, "term_months") || null, regx_short_term: i.regx_short_term === undefined ? null : flag(i, "regx_short_term"), application_complete: i.application_complete === undefined ? null : flag(i, "application_complete"), disaster: flag(i, "disaster") }, ctx.actor, ctx.now);
    ctx.events.append({ type: "workout_plan.offered", loanId, actor: ctx.actor, payload: { plan_id: rec.id, kind, offer_date: offerDate, regx_short_term: rec.data.regx_short_term, application_complete: rec.data.application_complete, disaster: flag(i, "disaster") } }); return rec.data;
  }
  const opStatus = typeof i.op === "string" ? PLAN_END_OPS[i.op] : undefined;
  if (opStatus !== undefined || PLAN_END_STATUSES.has(str(i, "status"))) {
    const status = opStatus || str(i, "status"); if (!PLAN_END_STATUSES.has(status)) throw new RangeError(`op=end needs status ∈ {${[...PLAN_END_STATUSES].join(", ")}}`);
    need(i, "id"); const plan = rt.store.require("workout_plans", str(i, "id")); const endedOn = str(i, "ended_on") || str(i, "terminated_on") || today;
    const rec = rt.store.put("workout_plans", plan.id, { status, terminated_reason: str(i, "terminated_reason") || null, ended_on: endedOn, qrpc: flag(i, "qrpc"), deferral_eligible: flag(i, "deferral_eligible"), flex_eligible: flag(i, "flex_eligible"), ...(i.disaster !== undefined ? { disaster: flag(i, "disaster") } : {}) }, ctx.actor, ctx.now);
    ctx.events.append({ type: "workout_plan.ended", loanId, actor: ctx.actor, payload: { plan_id: plan.id, kind: (plan.data.kind as string | undefined) ?? kind, plan_kind: (plan.data.kind as string | undefined) ?? kind, status, terminated_reason: rec.data.terminated_reason, term_end: (plan.data.term_end as string | undefined) ?? null, ended_on: endedOn, failed_month_end: endOfMonth(D(endedOn)), qrpc: flag(i, "qrpc"), deferral_eligible: flag(i, "deferral_eligible"), flex_eligible: flag(i, "flex_eligible"), disaster: rec.data.disaster === true, start_days_delinquent: Number(i.start_days_delinquent ?? plan.data.start_days_delinquent ?? 0) } }); return rec.data;
  }
  if (i.op === "close") {
    need(i, "id", "closed_reason"); const plan = rt.store.require("workout_plans", str(i, "id")); const rec = rt.store.put("workout_plans", plan.id, { status: "closed", closed_reason: str(i, "closed_reason"), closed_on: today }, ctx.actor, ctx.now);
    ctx.events.append({ type: "workout_plan.closed", loanId, actor: ctx.actor, payload: { plan_id: plan.id, kind: (plan.data.kind as string | undefined) ?? kind, closed_reason: str(i, "closed_reason"), closed_on: today } }); return rec.data;
  }
  return undefined;
};
/** D2-3.3-01 contribution gates read from the tool input (12.9 rule 3): housing ratio, BRP, PCS, legal prohibition. */
const contributionFacts = (i: ToolInput): ContributionFacts => ({ ...(i.housing_ratio_pct === undefined ? {} : { housing_ratio_pct: i.housing_ratio_pct as string | number | null }), ...(i.brp_complete === undefined ? {} : { brp_complete: flag(i, "brp_complete") }), pcs_servicemember: flag(i, "pcs_servicemember"), prohibited_by_law: flag(i, "contribution_prohibited_by_law") });
const contributionOf = (i: ToolInput) => contribution(cents(i.reserves_cents), cents(i.piti_cents), cents(i.deficiency_cents), contributionFacts(i));
const statusReport = (): Omit<ToolDef, "process" | "agent"> => ({ name: "fnma.status_code.report", kind: "act", handler: compute((i, ctx) => { need(i, "loan_id", "status_code"); return ctx.events.append({ type: "investor.status_code.reported", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { status_code: str(i, "status_code"), effective_date: str(i, "effective_date") || null, reporting_month: str(i, "reporting_month") || null } }); }) });
const smduSubmitPoll = (): Omit<ToolDef, "process" | "agent"> => ({ name: "smdu.case.submit/poll", kind: "act", handler: compute(async (i, ctx, rt) => { const smdu = port(rt, "smdu") as unknown as { submit?: (c: Record<string, unknown>) => Promise<unknown>; poll?: (id: string) => Promise<unknown> }; if (i.op === "poll") { need(i, "case_id"); return smdu.poll ? smdu.poll(str(i, "case_id")) : { case_id: str(i, "case_id"), status: "unknown" }; } need(i, "loan_id", "workout"); const r = smdu.submit ? await smdu.submit({ loan_id: str(i, "loan_id"), workout: str(i, "workout"), servicer_number: str(i, "partner_servicer_number"), package: i.package ?? null }) : { submitted: true }; const submittedOn = ctx.now.slice(0, 10); const caseId = (r as { case_id?: string } | null)?.case_id ?? str(i, "case_id") ?? null;
    // D2-3.2-04/-05: a deferral is *completed* when the case is submitted into Fannie Mae's servicing solutions system — this event is that completion for the 12.6/12.7 agreement, entry, election and incentive clocks.
    ctx.events.append({ type: "smdu.case.submitted", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { workout: str(i, "workout"), submitted_on: submittedOn, case_id: caseId || null, disaster: str(i, "workout") === "disaster_payment_deferral" || flag(i, "disaster"), campaign_id: str(i, "campaign_id") || null } }); return r; }),
  guardrails: [never("SERVICER_NUMBER_REQUIRED", "12.2 guardrail: every SMDU submission carries the partner servicer number", (i) => i.op !== "poll" && !str(i, "partner_servicer_number"), "set partner_servicer_number")] });
const valuationOrderGet = (): Omit<ToolDef, "process" | "agent"> => ({ name: "valuation.order/get", kind: "act", handler: compute((i, ctx, rt) => { if (i.op === "get") return rt.store.get("valuations", str(i, "id"))?.data ?? null; need(i, "loan_id", "kind"); const rec = rt.store.put("valuations", str(i, "id") || `val-${str(i, "loan_id")}-${ctx.now.slice(0, 10)}`, { loan_id: str(i, "loan_id"), kind: str(i, "kind"), ordered_on: ctx.now.slice(0, 10), status: "ordered" }, ctx.actor, ctx.now); ctx.events.append({ type: "valuation.ordered", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { valuation_id: rec.id, kind: str(i, "kind") } }); return rec.data; }) });
const orderGet = (name: string, store: string, eventType: string): Omit<ToolDef, "process" | "agent"> => ({ name, kind: "act", handler: compute((i, ctx, rt) => { if (i.op === "get") return rt.store.get(store, str(i, "id"))?.data ?? null; need(i, "loan_id"); const rec = rt.store.put(store, str(i, "id") || `${store}-${str(i, "loan_id")}-${ctx.now.slice(0, 10)}`, { loan_id: str(i, "loan_id"), ordered_on: ctx.now.slice(0, 10), status: "ordered" }, ctx.actor, ctx.now); ctx.events.append({ type: eventType, loanId: str(i, "loan_id"), actor: ctx.actor, payload: { id: rec.id } }); return rec.data; }) });
const holdsSet = (name: string): Omit<ToolDef, "process" | "agent"> => ({ name, kind: "write", handler: compute((i, ctx, rt) => { need(i, "loan_id", "kind"); const op = i.op === "release" ? "released" : "active"; const rec = rt.store.put("foreclosure_holds", str(i, "id") || `hold-${str(i, "loan_id")}-${str(i, "kind")}`, { loan_id: str(i, "loan_id"), kind: str(i, "kind"), status: op, from: str(i, "from") || ctx.now.slice(0, 10), reason: str(i, "reason") || null }, ctx.actor, ctx.now); ctx.events.append({ type: op === "released" ? "foreclosure_holds.closed" : "foreclosure_holds.opened", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { kind: str(i, "kind"), hold_id: rec.id } }); return rec.data; }),
  guardrails: [never("RELEASE_NEEDS_REASON", "12.2/12.3: holds release only with a recorded reason (reviewer confirmation on appeals)", (i) => i.op === "release" && !str(i, "reason"), "set reason")] });
const attorneyInstruct = (): Omit<ToolDef, "process" | "agent"> => ({ name: "attorney.instruct", kind: "act", handler: compute((i, ctx) => { need(i, "loan_id", "instruction"); return ctx.events.append({ type: "attorney.instruction.sent", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { instruction: str(i, "instruction"), due_by: addBusinessDays(D(ctx.now.slice(0, 10)), 1, federal), ack_required: true } }); }) });
const erecording = (): Omit<ToolDef, "process" | "agent"> => ({ name: "erecording.submit", kind: "act", handler: compute((i, ctx, rt) => { need(i, "loan_id", "document_id"); const p = port(rt, "erecording") as unknown as { submit?: (packageId: string, now: string) => Promise<unknown> } | undefined; ctx.events.append({ type: "erecording.submitted", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { document_id: str(i, "document_id"), package_id: str(i, "package_id") || str(i, "document_id"), officer_signature_date: str(i, "officer_signature_date") || null } }); return p?.submit ? p.submit(str(i, "package_id") || str(i, "document_id"), ctx.now) : { submitted: true }; }),
  guardrails: [needsRole("SIGNING_OFFICER_EXECUTES", "12.6/12.8: a recordable agreement is executed by signing_officer", (i) => !str(i, "officer_signature_date"), ["signing_officer"], "the executed agreement carries officer_signature_date")] });
const ACK_TEMPLATES = new Set(["NTC_REGX_41B2_ACK_COMPLETE", "NTC_REGX_41B2_ACK_INCOMPLETE"]);

// ---- 12.1 acknowledge application ---------------------------------------------
const p121 = defineTools("12.1", AGENT, [
  { name: "lossmit.application.open/update", kind: "write", handler: compute((i, ctx, rt) => { need(i, "loan_id"); const ext = intake_12_1(i, ctx, rt); if (ext !== undefined) return ext; const kind = classify({ has_evaluative_info: flag(i, "has_evaluative_info"), confidence: Number(i.confidence ?? 1) }); const received = optDate(i, "received_on") ?? D(ctx.now.slice(0, 10));
      if (kind === "rfa_only" && i.op !== "update") { const r = rfaFlow({ utterance: str(i, "utterance"), has_evaluative_info: false, confidence: Number(i.confidence ?? 1), state: str(i, "state") }); ctx.events.append({ type: "lossmit.rfa.received", loanId: str(i, "loan_id"), actor: ctx.actor, payload: r }); if (str(i, "regime") === "2024nprm") { const n = nprmRfa({ regime: "2024nprm", rfa_on: received, sale_on: optDate(i, "sale_on"), oral: flag(i, "oral") }); return { ...r, classification: kind, nprm: n }; } return { ...r, classification: kind }; }
      const id = str(i, "id") || `lma-${str(i, "loan_id")}-${received}`; const prev = i.op === "update" ? rt.store.get("lossmit_applications", id) : undefined; const saleOn = optDate(i, "sale_on") ?? (prev?.data.foreclosure_sale_date_at_receipt ? D(String(prev.data.foreclosure_sale_date_at_receipt)) : null);
      const rec = rt.store.put("lossmit_applications", id, { loan_id: str(i, "loan_id"), status: str(i, "status") || (prev ? String(prev.data.status) : "incomplete"), received_on: received, ack_due: ackDue(received).due_on, regime: str(i, "regime") || "2013", ...(str(i, "state") ? { state: str(i, "state") } : {}), foreclosure_sale_date_at_receipt: saleOn, protection_tier: protectionTier(received, saleOn).protection_tier, ...((i.changes as Record<string, unknown> | undefined) ?? {}) }, ctx.actor, ctx.now);
      ctx.events.append({ type: i.op === "update" ? "lossmit.application.status_changed" : "lossmit.application.received", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { application_id: rec.id, status: rec.data.status, received_date: received, state: (rec.data.state as string | undefined) ?? null, protection_tier: rec.data.protection_tier } });
      // 12.1 state machine → the (c)/(f)(2)/(g) lifecycle events: `facially_complete` (all listed items in) and `completed` (verified; `complete_at` for (c), `deemed_complete_date` for (d)–(h)); payload carries the 12.1 `protection_tier`, the 12.2 tier and the loan facts other sections' gates key on (13.2 CA dual-track, 11.5 income-doc staleness, 12.9 marketing hold).
      const status = String(rec.data.status); const today = ctx.now.slice(0, 10);
      if (status === "complete" || status === "facially_complete") {
        const completeAt = optDate(i, "complete_on") ?? D(today); const facialAt = optDate(i, "facially_complete_on") ?? (prev?.data.facially_complete_at ? D(String(prev.data.facially_complete_at)) : completeAt); const pt = protectionTier(received, saleOn);
        rt.store.put("lossmit_applications", rec.id, status === "complete" ? { complete_at: completeAt, facially_complete_at: facialAt, deemed_complete_date: optDate(i, "deemed_complete_on") ?? facialAt } : { facially_complete_at: facialAt }, ctx.actor, ctx.now);
        ctx.events.append({ type: status === "complete" ? "lossmit.application.completed" : "lossmit.application.facially_complete", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { application_id: rec.id, status, received_date: received, complete_at: completeAt, complete_date: completeAt, deemed_complete_date: optDate(i, "deemed_complete_on") ?? facialAt, facially_complete_at: facialAt, protection_tier: pt.protection_tier, tier: tier(completeAt, saleOn), days_before_sale: pt.days_before_sale, sale_on: saleOn, state: str(i, "state") || (rec.data.state as string | undefined) || null, first_lien: i.first_lien === undefined ? null : flag(i, "first_lien"), owner_occupied: i.owner_occupied === undefined ? null : flag(i, "owner_occupied"), principal_residence: i.principal_residence === undefined ? null : flag(i, "principal_residence"), path: str(i, "path") || null, third_party_item_outstanding: flag(i, "third_party_item_outstanding"), oldest_income_document_date: str(i, "oldest_income_document_date") || null, disaster: flag(i, "disaster") } });
      }
      return rec.data; }),
    // The classification is the rules engine's (`classify`: any evaluative information, or confidence <0.80, is an application); a model-proposed `classify_as` that disagrees is refused rather than honoured.
    guardrails: [never("RFA_CONFIDENCE_FLOOR", "12.1 guardrail: may not classify an RFA as not-an-application when confidence <0.80", (i) => typeof i.classify_as === "string" && i.classify_as !== classify({ has_evaluative_info: flag(i, "has_evaluative_info"), confidence: Number(i.confidence ?? 1) }), "the classification is the rules engine's: confidence below 0.80 or any evaluative information → application")] },
  { name: "documents.classify_extract", kind: "read", handler: compute((i, ctx, rt) => { need(i, "document_id"); const ai = (rt.services.documentAi as { classify?: (id: string) => Promise<unknown> } | undefined); if (!ai?.classify || flag(i, "ai_unavailable")) return rt.escalations.open({ kind: "human_portal_task", loanId: (i.loan_id as string | undefined) ?? ctx.loanId, payload: { checklist: "12.1 completeness determination", document_id: str(i, "document_id"), reason: "document AI unavailable" } }, ctx.actor); return ai.classify(str(i, "document_id")); }) },
  { name: "requirements.compute", kind: "read", handler: compute((i) => { const reqs = (i.requirements as Requirement[] | undefined) ?? []; return { ...completeness(reqs), already_in_file: reqs.filter((r) => r.status === "received" || r.status === "verified").map((r) => r.item) }; }),
    guardrails: [never("NO_RE_REQUEST", "12.1 guardrail: never asks for documents already in the file", (i) => { const reqs = (i.requirements as Requirement[] | undefined) ?? []; const ask = (i.request_items as string[] | undefined) ?? []; return ask.some((a) => reqs.some((r) => r.item === a && r.status !== "missing" && r.status !== "stale")); }, "drop items already received/verified"),
      never("WAIVER_NEEDS_CATALOG_RULE", "12.1 guardrail: may not mark an item waived without a catalog waiver rule", (i) => Array.isArray(i.waive_items) && (i.waive_items as unknown[]).length > 0 && !str(i, "catalog_waiver_rule"), "cite the lossmit_requirement_catalog waiver rule")] },
  { name: "calendar.federal_bd", kind: "read", handler: compute((i) => ({ date: addBusinessDays(date(i, "from"), num(i, "n") || 5, federal), calendar: "federal" })) },
  // The (b)(2) acknowledgment is compared with the clock the handler stored on the application: past `ack_due` it renders only with an escalation id (12.1 guardrail; 12.1-T12).
  { name: "notice.render_send", kind: "act", handler: compute((i, ctx, rt) => { const code = str(i, "template_code"); if (ACK_TEMPLATES.has(code)) { const app = str(i, "application_id") ? rt.store.get("lossmit_applications", str(i, "application_id")) : rt.store.list("lossmit_applications", (d) => d.loan_id === ((i.loan_id as string | undefined) ?? ctx.loanId)).at(-1); const due = app ? String(app.data.ack_due ?? "") : ""; const today = str(i, "as_of") || ctx.now.slice(0, 10); if (due && today > due && !str(i, "escalation_id")) throw new RangeError(`NO_LATE_ACK_WITHOUT_ESCALATION: the acknowledgment clock ${due} has passed (today ${today}); open the officer sev-1 escalation and cite escalation_id (12.1 guardrail)`); } return noticeOps("render_send")(i, ctx, rt); }),
    guardrails: [REVIEWER_GATE, TEMPLATE_ONLY, never("NO_LATE_ACK_WITHOUT_ESCALATION", "12.1 guardrail: never issues an ack after the clock without an escalations row", (i) => flag(i, "ack_after_deadline") && !str(i, "escalation_id"), "open the officer sev-1 escalation first")] },
  { name: "contacts.log", kind: "write", handler: log("contacts", "contact.attempted") },
  { name: "timers.start", kind: "act", handler: timerOps() },
  holdsSet("foreclosure_holds.set"),
  statusReport(),
  { name: "sii.lookup", kind: "read", handler: read("sii_records") },
  { name: "transfer.lossmit_file.get", kind: "read", handler: read("transfer_lossmit_files") },
]);

// ---- 12.2 complete-application evaluation ---------------------------------------
const p122 = defineTools("12.2", AGENT, [
  // `lossmit.evaluation.*` covers the 12.2 lifecycle: op=start (queued/gathering → `lossmit.evaluation.started`), op=third_party_received (`lossmit.third_party_item.received`), the decision (default; `lossmit.evaluation.decided`) and op=offer_response — the borrower's acceptance/rejection from the Intake Router's `lossmit.offer.response.received` (4.1), recorded on `lossmit_offers` and emitted as `lossmit.offer.responded{response, option, accepted_via, tier}` (satisfies the (e)(1)/NY/E-3.4-01 acceptance clocks; arms the 12.6 entry/LAR clocks when a deferral is accepted).
  { name: "lossmit.evaluation.*", kind: "write", handler: compute((i, ctx, rt) => { need(i, "loan_id"); const today = ctx.now.slice(0, 10);
      const appeal = appealOps_12_3(i, ctx, rt); if (appeal !== undefined) return appeal;   // op=appeal_* — the 12.3 appeal lifecycle (section12-3.ts over ops-12-3.ts; 12.3 registers no tool of its own)
      const owned = evaluationOps_12_2(i, ctx, rt); if (owned !== undefined) return owned;   // third_party_request / draft / review / trial_payment_received / acceptance_items_received / smdu_decision / deemed_rejection (section12-2.ts)
      if (i.op === "start") { const items = (i.third_party_items as string[] | undefined) ?? []; const rec = rt.store.put("lossmit_evaluations", str(i, "id") || `eval-${str(i, "application_id") || str(i, "loan_id")}`, { loan_id: str(i, "loan_id"), application_id: str(i, "application_id") || null, status: items.length ? "gathering_third_party" : "evaluating", started_at: ctx.now, basis: str(i, "basis") || "complete_application", third_party_items: items, ...(str(i, "state") ? { state: str(i, "state") } : {}), ...(str(i, "option") ? { option: str(i, "option") } : {}), ...(str(i, "complete_on") ? { complete_at: str(i, "complete_on") } : {}) }, ctx.actor, ctx.now);
        ctx.events.append({ type: "lossmit.evaluation.started", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { evaluation_id: rec.id, application_id: rec.data.application_id, basis: rec.data.basis, third_party_items: items.length > 0, items, state: (rec.data.state as string | undefined) ?? null, complete_at: (rec.data.complete_at as string | undefined) ?? null, option: (rec.data.option as string | undefined) ?? null, criteria: str(i, "criteria") || null, started_on: today } }); return rec.data; }
      if (i.op === "third_party_received") { need(i, "item"); const ev = str(i, "id") ? rt.store.require("lossmit_evaluations", str(i, "id")) : latestEvaluation(rt, str(i, "loan_id")); const pending = ((ev?.data.third_party_items as string[] | undefined) ?? []).filter((x) => x !== str(i, "item")); if (ev) rt.store.put("lossmit_evaluations", ev.id, { third_party_items: pending, ...(pending.length ? {} : { status: "evaluating" }) }, ctx.actor, ctx.now);
        return ctx.events.append({ type: "lossmit.third_party_item.received", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { evaluation_id: ev?.id ?? null, item: str(i, "item"), received_on: str(i, "received_on") || today, items_outstanding: pending.length } }); }
      if (i.op === "offer_response") { need(i, "response"); const response = str(i, "response"); if (response !== "accepted" && response !== "rejected") throw new RangeError("response must be accepted or rejected"); const ev = str(i, "evaluation_id") ? rt.store.require("lossmit_evaluations", str(i, "evaluation_id")) : latestEvaluation(rt, str(i, "loan_id")); const option = str(i, "option") || (ev?.data.option as string | undefined) || "";
        const rec = rt.store.put("lossmit_offers", str(i, "offer_id") || `offer-${str(i, "loan_id")}-${option || "option"}`, { loan_id: str(i, "loan_id"), evaluation_id: ev?.id ?? null, option: option || null, status: response, accepted_via: str(i, "accepted_via") || null, responded_on: str(i, "responded_on") || today, ...(response === "accepted" ? { accepted_at: ctx.now } : {}) }, ctx.actor, ctx.now);
        ctx.events.append({ type: "lossmit.offer.responded", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { offer_id: rec.id, evaluation_id: ev?.id ?? null, option: option || null, response, accepted_via: rec.data.accepted_via, responded_on: rec.data.responded_on, tier: str(i, "tier") || (ev?.data.tier as string | undefined) || null, state: str(i, "state") || (ev?.data.state as string | undefined) || null, disaster: option === "disaster_payment_deferral" || flag(i, "disaster") } }); return rec.data; }
      need(i, "application_id"); const complete = date(i, "complete_on"); const t = tier(complete, optDate(i, "sale_on")); const provided = optDate(i, "provided_on") ?? complete;
      const dl = evaluationDeadlines(complete, provided, t, str(i, "state") || undefined); const outcome = str(i, "outcome") || "pending";
      const rec = rt.store.put("lossmit_evaluations", str(i, "id") || `eval-${str(i, "application_id")}`, { loan_id: str(i, "loan_id"), application_id: str(i, "application_id"), tier: t, outcome, decision_due: dl.decision_due, accept_by: dl.accept_by, window_days: dl.window_days, grace_days: dl.grace_days, deemed_rejected_on: dl.deemed_rejected_on, appeal_rights: dl.appeal_rights, reviewer_required: reviewerRequired({ denial: outcome === "denied", ineligible: outcome === "ineligible", duplicative: flag(i, "duplicative"), discretionary_c2ii: flag(i, "discretionary_c2ii"), reg_b_adverse: flag(i, "reg_b_adverse") }), source: str(i, "source") || "rules_engine", ...(str(i, "state") ? { state: str(i, "state") } : {}), ...(str(i, "option") ? { option: str(i, "option") } : {}), status: "decided", decided_at: ctx.now }, ctx.actor, ctx.now);
      ctx.events.append({ type: "lossmit.evaluation.decided", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { evaluation_id: rec.id, outcome, tier: t, option: (rec.data.option as string | undefined) ?? null, state: (rec.data.state as string | undefined) ?? null, decided_on: today } }); return rec.data; }),
    guardrails: [never("ENGINE_OUTPUT_ONLY", "12.2 guardrail: outcomes must equal the rules engine/SMDU output", (i) => str(i, "source") === "model", "the model may not override a decision"),
      never("ACCEPTANCE_NEEDS_EVIDENCE", "12.2 rule 7 / D2-2-05: acceptance is verbal, written, by payment or portal — record how", (i) => i.op === "offer_response" && str(i, "response") === "accepted" && !str(i, "accepted_via"), "set accepted_via ∈ {verbal, written, payment, portal}"),
      never("CATALOG_REASON_CODES", "12.2 guardrail: reason codes only from the catalog", (i) => typeof i.reason_code === "string" && !/^(FNMA|REGX|SM)_[A-Z0-9_]+$/.test(str(i, "reason_code")), "use a catalog reason code")] },
  { name: "hierarchy.walk", kind: "read", handler: compute((i) => hierarchyWalk({ can_reinstate: flag(i, "can_reinstate"), hardship_temporary_unresolved: flag(i, "hardship_temporary_unresolved"), can_afford_repayment: flag(i, "can_afford_repayment"), deferral_eligible: flag(i, "deferral_eligible"), flexmod_eligible: flag(i, "flexmod_eligible"), liquidation_requested: flag(i, "liquidation_requested"), ...(str(i, "liquidation_option") ? { liquidation_option: str(i, "liquidation_option") as "short_sale" | "mortgage_release" } : {}), ...(i.liquidation_eligible === undefined ? {} : { liquidation_eligible: flag(i, "liquidation_eligible") }) })) },
  smduSubmitPoll(),
  { name: "valuation.order", kind: "act", handler: valuationOrderGet().handler },
  { name: "mi.decision.get", kind: "read", handler: read("mi_decisions") },
  { name: "credit.report.pull", kind: "act", handler: compute((i, ctx, rt) => { need(i, "loan_id", "permissible_purpose"); const p = rt.services.creditBureau as { pull?: (r: Record<string, unknown>) => Promise<unknown> } | undefined; ctx.events.append({ type: "credit.report.pulled", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { purpose: str(i, "permissible_purpose") } }); return p?.pull ? p.pull({ loan_id: str(i, "loan_id") }) : { pulled: true }; }) },
  // A denial renders through the template and is then checked against its own rendered text (names Fannie Mae, quotes the criterion, states the other criteria were not evaluated); a hierarchy-ranking reason is refused unless the offered option outranks the denied one (comment 41(d)-1; 12.2-T3/T4).
  { name: "notice.render_send", kind: "act", handler: compute((i, ctx, rt) => { const code = str(i, "template_code"); if (code.includes("DENIAL")) { const ranking = (i.ranking_reason as { offered: Option; denied: Option } | undefined) ?? null; const pre = denialNoticeContent({ investor: str(i, "investor") || "Fannie Mae", option: str(i, "option"), criterion: str(i, "criterion"), reviewer_approval_id: (i.reviewer_approval_id as string | undefined) ?? null, ranking_reason: ranking }); if (!pre.mailing_allowed) throw new RangeError(pre.refusal!); const rendered = noticeOps("render")(i, ctx, rt) as { id: string; rendered: { text: string } }; const post = denialNoticeContent({ investor: str(i, "investor") || "Fannie Mae", option: str(i, "option"), criterion: str(i, "criterion"), reviewer_approval_id: (i.reviewer_approval_id as string | undefined) ?? null, ranking_reason: ranking, rendered_text: rendered.rendered.text }); if (!post.mailing_allowed) throw new RangeError(post.refusal!); return afterDenialSent(i, ctx, rt, noticeOps("send")({ ...i, notice_id: rendered.id }, ctx, rt)); } return sendNotice("render_send", i, ctx, rt); }),
    guardrails: [REVIEWER_GATE, TEMPLATE_ONLY,
      // Offer terms must arrive with the SMDU decision or calculator run that produced them; a `terms` object without either is hand-entered.
      never("OFFER_TERMS_FROM_CALCULATOR", "12.2 guardrail: no offer terms outside SMDU-returned or calculator-produced values", (i) => (i.terms !== undefined || flag(i, "terms_hand_entered")) && !str(i, "smdu_decision_id") && !str(i, "calculator_run_id"), "terms come from SMDU (smdu_decision_id) or the calculator (calculator_run_id)"),
      never("RANKING_REASON_ORDER", "12.2 rule 5 / comment 41(d)-1: a hierarchy-ranking reason only when the offered option outranks the denied one", (i) => { const r = i.ranking_reason as { offered: Option; denied: Option } | undefined; return r !== undefined && !rankingReasonAllowed(r.offered, r.denied); }, "state the specific criterion instead of the ranking")] },
  holdsSet("foreclosure_holds.set/release"),
  attorneyInstruct(),
  { ...timers(), handler: timerOps_12_2() },   // + op=lapse: the not_before_gate sweep (`timer.lapsed{code}` satisfies CA_CIV_2923_6E_NOD_NOS_HOLD_31)
  { name: "escalation.file", kind: "act", handler: escalate("lossmit_reviewer") },
]);

// ---- 12.4 forbearance plan --------------------------------------------------------
const p124 = defineTools("12.4", AGENT, [
  { name: "workout_plan.*", kind: "write", handler: compute((i, ctx, rt) => { need(i, "loan_id"); const life = planLifecycle("forbearance", i, ctx, rt); if (life !== undefined) return life; const ops124 = forbearanceOps_12_4(i, ctx, rt); if (ops124 !== undefined) return ops124; if (i.op === "referral_check") return referralGate({ plan_status: str(i, "plan_status") as "active", terminated_reason: (i.terminated_reason as "failed_terms" | undefined) ?? null, terminated_on: optDate(i, "terminated_on"), today: D(ctx.now.slice(0, 10)) });
      const term = forbearanceTerm({ requested_months: num(i, "requested_months") || 0, cumulative_months: num(i, "cumulative_months") || 0, months_delinquent_at_start: num(i, "months_delinquent_at_start") || 0, mbs_months_to_maturity: (i.mbs_months_to_maturity as number | undefined) ?? null, combined_months: num(i, "combined_months") || 0 });
      const start = date(i, "start_on"); const dates = forbearanceTermDates(start, term.months);
      // 12.4 rule 2 / T3: past the sixth forborne payment the plan is not Reg X short-term and activates only on a recorded basis.
      const basis = forbearanceBasisGate({ forborne_months_before: num(i, "cumulative_months") || 0, term_months: term.months, regx_basis: (i.regx_basis as RegxBasis | undefined) ?? null }); if (!basis.allowed) throw new RangeError(basis.refusal!);
      const act = forbearanceActivation({ offered_on: optDate(i, "offered_on") ?? D(ctx.now.slice(0, 10)), term_start: dates.start, term_end: dates.end }); emitTermCreate_12_4(i, ctx, term, dates);
      const rec = rt.store.put("workout_plans", str(i, "id") || `wp-${str(i, "loan_id")}-${start}`, { loan_id: str(i, "loan_id"), kind: "forbearance", status: str(i, "status") || "active", months: term.months, term_start: dates.start, term_end: dates.end, capped_by: term.capped_by ?? null, regx_short_term: basis.regx_short_term, regx_basis: (i.regx_basis as string | undefined) ?? null, evaluation_notice_by: act.evaluation_notice_by, status_09_report_by: act.status_report_by, late_charges_suppressed: true, preexpiry_outreach_begin_by: act.preexpiry_outreach.begin_by, disaster: flag(i, "disaster"), start_days_delinquent: num(i, "start_days_delinquent") || (num(i, "months_delinquent_at_start") || 0) * 30 }, ctx.actor, ctx.now);
      // The −30-day outreach and the expiry disposition are armed by the registry from this event's `term_end` (`FNMA_D23201_FORB_PREEXPIRY_CONTACT_30`, `FNMA_D23201_FORB_EXPIRY_DISPOSITION`); plan ends go through `planLifecycle` and emit `workout_plan.ended`, never a second activation.
      ctx.events.append({ type: "workout_plan.activated", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { plan_id: rec.id, kind: "forbearance", term_start: dates.start, term_end: dates.end, offered_on: act.evaluation_notice_by, regx_short_term: basis.regx_short_term, disaster: flag(i, "disaster") } }); return rec.data; }),
    guardrails: [never("NO_TERM_BREACHING_GATE", "12.4 guardrail: cannot create a term breaching any gate", (i) => num(i, "requested_months") > 3 && !flag(i, "fnma_exception_approved"), "increments are ≤3 months (LL-2026-01) without an exception"),
      never("MITIGATING_CHECK_BEFORE_TERMINATION", "12.4 guardrail: cannot terminate for a missed reduced payment without the mitigating-circumstances check", (i) => str(i, "status") === "terminated" && str(i, "terminated_reason") === "failed_terms" && !flag(i, "mitigating_circumstances_checked"), "log the mitigating-circumstances check first"),
      never("DILIGENCE_SUSPENSION_C2III", "12.4 guardrail: cannot suspend diligence unless the (c)(2)(iii) conditions are met", (i) => flag(i, "suspend_diligence") && !flag(i, "c2iii_conditions_met"), "short-term plan on an incomplete application with the required notice")] },
  { name: "calendar.months", kind: "read", handler: compute((i) => forbearanceTermDates(date(i, "start_on"), num(i, "months") || 1)) },
  { name: "delinquency.project", kind: "read", handler: compute((i) => ({ projected_months_delinquent_at_term_end: (num(i, "months_delinquent") || 0) + (num(i, "term_months") || 0), within_12: (num(i, "months_delinquent") || 0) + (num(i, "term_months") || 0) <= 12 })) },
  noticeTool(),
  // 12.4 ops (schedule, month-end status, exception template, QRPC on outreach, suppression lift) are in ./section12-4.ts over src/domain/lossmit/ops-12-4.ts.
  { name: "fees.suppress", kind: "write", handler: compute(feesSuppressOps_12_4) },
  { name: "fnma.status_code.report", kind: "act", handler: compute(statusCodeOps_12_4) },
  { name: "exception_request.prepare", kind: "act", handler: compute(exceptionRequestOps_12_4),
    guardrails: [needsRole("EXCEPTION_SUBMIT_AUTHORITY", "12.4 prerequisites: the Forbearance Exception Request Template is signed and submitted by `officer` or `fnma_portal_operator` (partner election)", (i) => i.op === "submit", ["officer", "fnma_portal_operator"], "submission of the exception template is a human act")] },
  { name: "contacts.*", kind: "write", handler: compute(contactsOps_12_4) },
  timers(),
]);

// ---- 12.5 repayment plan ----------------------------------------------------------
const p125 = defineTools("12.5", AGENT, [
  { name: "workout_plan.*", kind: "write", handler: compute((i, ctx, rt) => { need(i, "loan_id"); const life = planLifecycle("repayment_plan", i, ctx, rt); if (life !== undefined) return life;
      // 12.5 schedule / row_due / payment / month_end run in ops-12-5.ts (the `workout_plan_schedule.row_due`, `workout_plan.payment.received` and `period.month_end{workout_plan_active}` emitters).
      const env125: RepaymentEnv = { events: ctx.events, store: rt.store, actor: ctx.actor, now: ctx.now }; const own = repaymentPlanOps(env125, i); if (own !== undefined) return own;
      // 12.5 rule 7 / guardrail: an escrow or rate change re-tests the 150% cap on the unchanged installment; a breach re-casts within 12 months with a new notice.
      if (i.op === "contractual_change") { need(i, "id", "new_contractual_cents"); const plan = rt.store.require("workout_plans", str(i, "id")); const r = capRetest({ installment_cents: cents(plan.data.installment_cents), new_contractual_cents: cents(i.new_contractual_cents), plan_months: Number(plan.data.months ?? 0) }); const rec = rt.store.put("workout_plans", plan.id, { contractual_cents: cents(i.new_contractual_cents), total_monthly_cents: r.total_cents, pct_of_contractual: r.pct_of_contractual, cap_retest: { within_cap: r.within_cap, recast: r.recast, on: ctx.now.slice(0, 10) }, ...(r.recast ? { months: r.recast.months, status: "recast_pending_notice" } : {}) }, ctx.actor, ctx.now); ctx.events.append({ type: "workout_plan.cap_retested", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { plan_id: plan.id, within_cap: r.within_cap, recast: r.recast } }); return rec.data; }
      // "plan create/modify/extend" → `workout_plan.term.create{plan_kind=repayment, forbearance_component, …}` arms the four not_before gates before the calculator asserts them (12.5 timer table).
      const planId125 = str(i, "id") || `rp-${str(i, "loan_id")}-${str(i, "start_on")}`;
      const tc = termCreate(env125, { loan_id: str(i, "loan_id"), plan_id: planId125, op: rt.store.get("workout_plans", planId125)?.data.status === "active" ? (num(i, "term_months") > Number(rt.store.get("workout_plans", planId125)!.data.months ?? 0) ? "extend" : "modify") : "create", term_months: num(i, "term_months") || 1, arrears_cents: cents(i.arrears_cents), contractual_cents: cents(i.contractual_cents), fnma_days_delinquent: num(i, "days_delinquent") || 0, brp_complete: flag(i, "brp_complete"), fnma_approval_id: (i.fnma_approval_id as string | undefined) ?? null, forbearance_months: num(i, "forbearance_months") || 0 });
      if (tc.refusals.length) throw new RangeError(tc.refusals[0]!);
      const gate = repaymentBrpGate({ days_delinquent: num(i, "days_delinquent") || 0, term_months: num(i, "term_months") || 0, brp_complete: flag(i, "brp_complete"), qrpc: flag(i, "qrpc") }); if (!gate.allowed) throw new RangeError(gate.refusal!);
      const ext = repaymentExtension({ term_months: num(i, "term_months") || 0, fnma_approval_id: (i.fnma_approval_id as string | undefined) ?? null }); const terms = repaymentTerms(cents(i.arrears_cents), cents(i.contractual_cents), num(i, "term_months") || 1); if (!terms.allowed) throw new RangeError(`expected total ${terms.total_monthly_cents} exceeds 150% of the contractual payment (FNMA_D23202_REPAY_PAYMENT_CAP_150)`);
      // Rule 2 / F-1-16: the schedule rows (last row absorbs the rounding) and the specific cure date = the last row's month end.
      const sched = str(i, "start_on") ? buildSchedule(env125, { loan_id: str(i, "loan_id"), plan_id: planId125, start_on: D(str(i, "start_on")), months: terms.months, contractual_cents: cents(i.contractual_cents), arrears_cents: cents(i.arrears_cents) }) : null;
      const rec = rt.store.put("workout_plans", planId125, { loan_id: str(i, "loan_id"), kind: "repayment_plan", status: ext.status === "extension_pending" ? "extension_pending" : str(i, "status") || "active", months: terms.months, installment_cents: terms.installment_cents, contractual_cents: cents(i.contractual_cents), arrears_cents: cents(i.arrears_cents), total_monthly_cents: terms.total_monthly_cents, pct_of_contractual: terms.pct_of_contractual, f116_package: ext.package, fnma_approval_id: (i.fnma_approval_id as string | undefined) ?? null, disaster: flag(i, "disaster"), start_days_delinquent: num(i, "days_delinquent") || 0, forbearance_months: num(i, "forbearance_months") || 0, ...(sched ? { term_start: str(i, "start_on"), term_end: sched.cure_date, cure_date: sched.cure_date, schedule_rows: sched.rows.length } : {}) }, ctx.actor, ctx.now);
      ctx.events.append({ type: "workout_plan.activated", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { plan_id: rec.id, kind: "repayment_plan", months: terms.months, disaster: flag(i, "disaster") } }); return rec.data; }),
    guardrails: [never("TERM_OVER_12_NEEDS_APPROVAL", "12.5 guardrail: cannot set a term >12 without an approval id", (i) => num(i, "term_months") > 12 && str(i, "status") === "active" && !str(i, "fnma_approval_id"), "the plan stays extension_pending until the approval id is recorded"),
      never("NO_INSTALLMENT_OVERRIDE", "12.5 guardrail: the agent cannot alter installment math", (i) => i.installment_cents !== undefined, "installments come from calc.repayment_schedule"),
      never("CONTRACTUAL_CHANGE_NEEDS_CAP_RETEST", "12.5 guardrail: must re-test the cap on every contractual change", (i) => i.op !== "contractual_change" && (i.changes as Record<string, unknown> | undefined)?.contractual_cents !== undefined, "use op=contractual_change so the 150% cap is re-tested and any re-cast noticed")] },
  { name: "ledger.arrears", kind: "read", handler: compute((i) => { const inst = cents(i.piti_cents) * BigInt(num(i, "unpaid_installments") || 0); const lc = cents(i.late_charge_cents) * BigInt(num(i, "late_charges") || 0); return { installments_cents: inst, late_charges_cents: lc, total_cents: inst + lc }; }) },
  { name: "calc.repayment_schedule", kind: "read", handler: compute((i) => (i.months ? repaymentTerms(cents(i.arrears_cents), cents(i.contractual_cents), num(i, "months")) : repaymentPlan(cents(i.arrears_cents), cents(i.contractual_cents), i.capacity_cents === undefined ? null : cents(i.capacity_cents)))) },
  // Suppression is the plan's mechanical effect; a *waiver* is a money-field write-off and needs an officer (docs/ARCHITECTURE.md §6) with the D2-3.2-02 reason.
  { name: "fees.suppress/waive", kind: "write", handler: compute((i, ctx, rt) => { need(i, "loan_id"); const op = i.op === "waive" ? "waived" : "suppressed"; const rec = rt.store.put("fees", str(i, "fee_id") || `fee-${str(i, "loan_id")}`, { loan_id: str(i, "loan_id"), status: op, reason: str(i, "reason"), by: ctx.actor.id }, ctx.actor, ctx.now); return rec.data; }),
    guardrails: [never("WAIVE_ONLY_ON_COMPLETION", "12.5 guardrail: cannot waive late charges outside the rule", (i) => i.op === "waive" && str(i, "reason") !== "D2-3.2-02", "plan-period charges are waived on completion with reason D2-3.2-02"),
      needsRole("WAIVER_NEEDS_OFFICER", "docs/ARCHITECTURE.md §6: waivers on money fields need an officer", (i) => i.op === "waive", ["officer"], "the agent suppresses; an officer waives")] },
  noticeTool(),
  // 12.5 F-1-21 / F-2-02: op=report (status 12 with effective / completion date), op=incentive_claim ($500), op=ack (the inbound Fannie Mae acknowledgement → `investor.event.accepted{status_code=12}` / `{kind=incentive, workout=repayment_plan}`); any other op is the section's status-code submission.
  { ...statusReport(), handler: compute((i, ctx, rt) => { const own = statusReportOps({ events: ctx.events, store: rt.store, actor: ctx.actor, now: ctx.now }, i); return own !== undefined ? own : statusReport().handler(i, ctx, rt); }) },
  { name: "fnma.f116_package.prepare", kind: "act", handler: compute((i, ctx, rt) => { need(i, "loan_id", "term_months"); const rec = rt.store.put("fnma_exception_requests", str(i, "id") || `f116-${str(i, "loan_id")}`, { loan_id: str(i, "loan_id"), form: "F-1-16", requested_months: num(i, "term_months"), status: "prepared" }, ctx.actor, ctx.now); return rec.data; }) },
  timers(),
]);

// ---- 12.6 payment deferral ----------------------------------------------------------
const p126 = defineTools("12.6", AGENT, [
  // The screen is the 12.6/12.7 "offer/solicit command": it emits `payment_deferral.offer_requested{months_delinquent, disaster}` (the evaluator-backed eligibility, escrow-analysis and contractual-payment gates arm on it) and, on ineligibility, `payment_deferral.screened_ineligible{disaster, reason, next}` (D1-3-01 Flex Mod routing) alongside the reviewer escalation.
  { name: "deferral.screen", kind: "read", handler: compute((i, ctx, rt) => { const f = i.facts as DeferralFacts | undefined; if (!f) throw new RangeError("facts are required"); const s = screen(f); const loanId = (i.loan_id as string | undefined) ?? ctx.loanId; const disaster = Boolean(f.disaster);
      ctx.events.append({ type: "payment_deferral.offer_requested", loanId, actor: ctx.actor, payload: { months_delinquent: f.months_delinquent, disaster, evaluation_date: f.evaluation_date, eligible: s.eligible } });
      if (!s.eligible) { ctx.events.append({ type: "payment_deferral.screened_ineligible", loanId, actor: ctx.actor, payload: { disaster, reason: s.reason, next: s.next, months_delinquent: f.months_delinquent } }); rt.escalations.open({ kind: "lossmit_reviewer", loanId, payload: { determination: "ineligible", reason: s.reason, next: s.next } }, ctx.actor); }
      // A `basis` on an eligible screen is the offer/solicitation decision: ops-12-6.offerDeferral versions `payment_deferrals` and emits `payment_deferral.offered{basis, decided_on}` (arms `FNMA_D2205_EVAL_NOTICE_DEFERRAL_5` on the BRP basis).
      const offer = s.eligible && !disaster && str(i, "basis") ? offerDeferral({ events: ctx.events, store: rt.store, actor: ctx.actor, now: ctx.now }, { loan_id: loanId, deferral_id: str(i, "deferral_id") || null, basis: str(i, "basis"), facts: f, result: s, application_complete: flag(i, "application_complete"), decided_on: optDate(i, "decided_on"), processing_month_elected: flag(i, "processing_month_elected"), recording_required: flag(i, "recording_required") }) : null;
      return { ...s, cap: capStructure({ prior_deferred_months: f.cumulative_deferred_months, requested_months: f.months_delinquent }), ...(offer ? { deferral: offer.deferral } : {}) }; }) },
  // NIB math is code: the breakdown is computed from the installments and third-party advances only and stored; a caller-supplied NIB is refused.
  { name: "ledger.arrears_breakdown", kind: "read", handler: compute((i, ctx, rt) => { const r = deferralLedger({ pi_cents: cents(i.pi_cents), months_deferred: num(i, "months_deferred") || 0, escrow_advances_cents: cents(i.escrow_advances_cents), servicing_advances_cents: cents(i.servicing_advances_cents), late_charges_cents: cents(i.late_charges_cents), pre_deferral_ib_upb_cents: cents(i.pre_deferral_ib_upb_cents), scheduled_ib_upb_cents: cents(i.scheduled_ib_upb_cents) }); const id = str(i, "deferral_ledger_id") || `dl-${(i.loan_id as string | undefined) ?? ctx.loanId}-${ctx.now.slice(0, 10)}`; rt.store.put("deferral_ledgers", id, { loan_id: (i.loan_id as string | undefined) ?? ctx.loanId, nib_cents: r.deferred_principal_cents, ib_upb_cents: r.ib_upb_cents, months_deferred: num(i, "months_deferred") || 0, balanced: r.balanced }, ctx.actor, ctx.now); return { deferral_ledger_id: id, ...r }; }),
    guardrails: [never("NIB_EXCLUDES_LATE_CHARGES", "12.6 guardrail: cannot include late charges or escrow shortage in the NIB — NIB math is code", (i) => i.nib_cents !== undefined || flag(i, "include_late_charges_in_nib") || flag(i, "include_escrow_shortage_in_nib"), "NIB = deferred P&I + eligible advances only, computed here; do not pass nib_cents")] },
  { name: "escrow.analysis.run", kind: "act", handler: compute((i, ctx) => { need(i, "loan_id"); return ctx.events.append({ type: "escrow.analysis.requested", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { reason: "12.6 deferral (B-1-01)" } }); }) },
  // A PAYMENT_DEFERRAL submission *is* the completion (D2-3.2-04): ops-12-6 asserts the contractual-payment / LAR / month-end guards before the case goes in, then emits `payment_deferral.completed` + `payment_deferral.effective{effective_date}` (arms `FNMA_D23204_CUSTODIAN_25`).
  { ...smduSubmitPoll(), name: "smdu.case.submit", handler: compute(async (i, ctx, rt) => { const standard = i.op !== "poll" && str(i, "workout") === "payment_deferral"; const env = { events: ctx.events, store: rt.store, actor: ctx.actor, now: ctx.now }; const gate = { loan_id: str(i, "loan_id"), deferral_id: str(i, "deferral_id") || null, completed_on: optDate(i, "completed_on"), processing_month_elected: flag(i, "processing_month_elected"), lar_acked: flag(i, "lar_acked") };
      if (standard) assertDeferralCompletable(env, gate); const r = await smduSubmitPoll().handler(i, ctx, rt); if (!standard) return r;
      const c = completeDeferral(env, gate); return { ...(r as Record<string, unknown>), deferral: c.deferral, effective_date: c.effective_date, entry_deadline: c.entry_deadline, processing_month: c.processing_month }; }) },
  // The NIB reported to Fannie Mae is read from the stored ledger breakdown, never from the caller.
  { name: "investor.report_contractual_payments", kind: "act", handler: compute((i, ctx, rt) => { need(i, "loan_id", "deferral_ledger_id"); const led = rt.store.require("deferral_ledgers", str(i, "deferral_ledger_id")); if (i.nib_cents !== undefined && cents(i.nib_cents) !== cents(led.data.nib_cents)) throw new RangeError(`NIB_FROM_LEDGER_ONLY: reported NIB ${cents(i.nib_cents)} differs from the ledger breakdown ${cents(led.data.nib_cents)} (12.6 guardrail: NIB math is code)`); return ctx.events.append({ type: "investor.contractual_payments.reported", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { months: Number(led.data.months_deferred ?? 0), nib_cents: cents(led.data.nib_cents), deferral_ledger_id: led.id } }); }),
    guardrails: [never("COMPLETION_NEEDS_ACK", "12.6 guardrail: cannot complete without the LAR/event ack and, where required, the contractual payment", (i) => flag(i, "complete") && (!flag(i, "lar_acked") || (flag(i, "contractual_payment_required") && !flag(i, "contractual_payment_received"))), "wait for the 5.x ack / contractual payment")] },
  noticeTool(),
  // The deferral agreement is a document (D2-3.2-04 model content), not a Notice Registry template: sending it emits `lossmit.agreement.sent{document}` — the event `FNMA_D23204_AGREEMENT_SEND_5` / `FNMA_D23205_AGREEMENT_SEND_5` are satisfied by.
  { name: "esign.send", kind: "act", handler: compute((i, ctx, rt) => { need(i, "loan_id", "document_id"); const p = rt.services.esign as { send?: (d: Record<string, unknown>) => Promise<unknown> } | undefined; ctx.events.append({ type: "esign.sent", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { document_id: str(i, "document_id"), document: str(i, "document") || null } }); if (str(i, "document")) ctx.events.append({ type: "lossmit.agreement.sent", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { document: str(i, "document"), document_id: str(i, "document_id"), channel: "esign", sent_on: ctx.now.slice(0, 10) } }); return p?.send ? p.send({ document_id: str(i, "document_id") }) : { sent: true }; }) },
  erecording(),
  { name: "custodian.deliver", kind: "act", handler: compute((i, ctx) => { need(i, "loan_id", "document"); return ctx.events.append({ type: "custodian.delivery.requested", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { document: str(i, "document"), certified_copy: flag(i, "certified_copy") } }); }) },
  timers(),
]);

// ---- 12.7 disaster payment deferral (no agent named; runs under 12.6's) ---------------
const p127 = defineTools("12.7", AGENT, [
  // A FEMA basis is asserted only against a registry match the handler itself finds; `assert_fema_basis` without a matching IA declaration is refused here, not on a caller-supplied flag.
  { name: "disaster.registry.lookup", kind: "read", handler: compute((i, _c, rt) => { need(i, "county_fips"); const rows = rt.store.list("disaster_registry").filter((r) => r.data.county_fips === str(i, "county_fips") && r.data.fema_ia === true && (!str(i, "disaster_event_id") || r.data.event_id === str(i, "disaster_event_id"))); if (flag(i, "assert_fema_basis") && rows.length === 0) throw new RangeError(`FEMA_BASIS_NEEDS_MATCH: no FEMA Individual Assistance declaration on the registry for county ${str(i, "county_fips")}${str(i, "disaster_event_id") ? ` / ${str(i, "disaster_event_id")}` : ""} (12.7 guardrail)`); return { match: rows.length > 0, events: rows.map((r) => r.data), fema_basis_asserted: flag(i, "assert_fema_basis") && rows.length > 0 }; }),
    guardrails: [never("FEMA_BASIS_NEEDS_MATCH", "12.7 guardrail: cannot assert a FEMA basis without a registry match", (i) => flag(i, "assert_fema_basis") && i.registry_match === false, "look the county up first")] },
  { name: "insurance.claim.get", kind: "read", handler: read("insurance_claims") },
]);

// ---- 12.8 Flex Modification -------------------------------------------------------------
const p128 = defineTools("12.8", AGENT, [
  // An ineligible waterfall result (P&I rule) is a modification denial: it goes to the lossmit_reviewer before any notice (12.8 guardrail 'denials require lossmit_reviewer'; 12.2 reviewer gate on the notice).
  { name: "flexmod.waterfall", kind: "read", handler: compute((i, ctx, rt) => { const w = i.inputs as WaterfallInputs | undefined; if (!w) throw new RangeError("inputs are required"); const mir = mirLookup((i.mir_table as { effective: PlainDate; rate_pct: string }[] | undefined) ?? [{ effective: D("2000-01-01"), rate_pct: w.mir_pct }], optDate(i, "evaluation_on") ?? D(ctx.now.slice(0, 10))); if (mir.refusal) { rt.escalations.open({ kind: "officer", loanId: (i.loan_id as string | undefined) ?? ctx.loanId, payload: { reason: mir.escalation!.reason }, severity: "sev2" }, ctx.actor); throw new RangeError(mir.refusal); } const r = waterfall({ ...w, mir_pct: mir.rate_pct! }); if (!r.eligible) rt.escalations.open({ kind: "lossmit_reviewer", loanId: (i.loan_id as string | undefined) ?? ctx.loanId, payload: { determination: "ineligible", reason: r.reason, pi_cents: r.pi_cents, pre_mod_pi_cents: w.pre_mod_pi_cents } }, ctx.actor); return { ...r, mir_version: { effective: mir.effective, rate_pct: mir.rate_pct } }; }),
    guardrails: [never("LLM_NEVER_COMPUTES_TERMS", "12.8 guardrail: the LLM never computes terms — it calls the waterfall", (i) => i.proposed_terms !== undefined, "terms come only from the waterfall"), never("FRESH_VALUATION", "12.8 guardrail: no TPP offer without a fresh valuation and escrow analysis", (i) => flag(i, "for_tpp_offer") && (num(i, "valuation_age_days") > 90 || !flag(i, "escrow_analysis_done")), "valuation ≤90 days and an escrow analysis first")] },
  valuationOrderGet(),
]);

// ---- 12.9 short sale / Mortgage Release -----------------------------------------------------
const LIQ_FACTS = ["state", "proof_of_funds", "mi_delegated", "interior_bpo_within_90_days", "vacant_secure_confirmed", "transition", "valuation_date", "contribution_required", "fnma_approval_id", "smdu_decision_id"] as const;
const p129 = defineTools("12.9", AGENT, [
  // One event vocabulary for the 12.9 timers: `liquidation.case.status_changed{case_id, kind, status, status_on, …facts}` on every transition, `liquidation.offer.received` for offers, `liquidation.dil.weekly_update.logged` for extension updates.
  { name: "liquidation.case.*", kind: "write", handler: compute((i, ctx, rt) => { need(i, "loan_id"); const today = D(ctx.now.slice(0, 10)); const caseId = str(i, "id") || `liq-${str(i, "loan_id")}`;
      if (i.op === "hold_check") return liquidationHolds({ phase: str(i, "phase") as "listing", approved_on: optDate(i, "approved_on"), state: str(i, "state"), today, requested: str(i, "requested") as "sale" });
      if (i.op === "closing_check") return shortSaleClosingClock({ approved_on: date(i, "approved_on"), funds_received_on: optDate(i, "funds_received_on"), fnma_extension_id: (i.fnma_extension_id as string | undefined) ?? null });
      if (i.op === "offer_received") { const received = optDate(i, "received_on") ?? today; const brpOn = optDate(i, "brp_complete_on"); const later = brpOn && brpOn > received ? brpOn : received; const rec = rt.store.put("shortsale_offers", str(i, "offer_id") || `offer-${caseId}-${received}`, { case_id: caseId, loan_id: str(i, "loan_id"), received_on: received, initial: i.initial !== false, price_cents: cents(i.price_cents), status: "received" }, ctx.actor, ctx.now); ctx.events.append({ type: "liquidation.offer.received", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { case_id: caseId, offer_id: rec.id, received_on: received, initial: i.initial !== false, brp_complete: brpOn !== null || flag(i, "brp_complete"), later_of_brp_and_offer: later, mls_active_date: str(i, "mls_active_date") || null } }); return rec.data; }
      if (i.op === "weekly_update") { need(i, "update"); const rec = rt.store.put("dil_cases", caseId, { case_id: caseId, loan_id: str(i, "loan_id"), last_update_on: today, last_update: str(i, "update") }, ctx.actor, ctx.now); ctx.events.append({ type: "liquidation.dil.weekly_update.logged", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { case_id: caseId, on: today } }); return rec.data; }
      // Inbound records (valuation result, closing proceeds, DIL inspection, relocation disbursement, CA NOD rescission, 13.x sale date) are validated against the case's event stream by ops-12-9.ts and appended as the events the 12.9 timer rows are satisfied/armed by.
      if (INBOUND_OPS_12_9.has(str(i, "op"))) return inboundOps_12_9(i, ctx);
      const changes = (i.changes as Record<string, unknown> | undefined) ?? {}; const facts = Object.fromEntries(LIQ_FACTS.filter((k) => i[k] !== undefined || changes[k] !== undefined).map((k) => [k, i[k] ?? changes[k]]));
      const prior = rt.store.get("liquidation_cases", caseId)?.data;   // a later transition that omits kind/status keeps the case's own (a DIL never flips to a short sale by omission)
      const rec = rt.store.put("liquidation_cases", caseId, { loan_id: str(i, "loan_id"), kind: str(i, "kind") || (prior?.kind as string | undefined) || "short_sale", status: str(i, "status") || (prior?.status as string | undefined) || "open", ...facts, ...changes, ...(str(i, "status") ? { [`${str(i, "status")}_on`]: today } : {}) }, ctx.actor, ctx.now);
      ctx.events.append({ type: "liquidation.case.status_changed", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { case_id: rec.id, kind: rec.data.kind, status: rec.data.status, status_on: today, ...Object.fromEntries(LIQ_FACTS.filter((k) => rec.data[k] !== undefined).map((k) => [k, rec.data[k]])) } }); return rec.data; }),
    guardrails: [never("APPROVAL_FROM_SMDU_ONLY", "12.9 guardrail: no approval outside SMDU's decision/Fannie Mae approval", (i) => str(i, "status") === "approved" && !str(i, "smdu_decision_id") && !str(i, "fnma_approval_id"), "record the SMDU decision or Fannie Mae approval"),
      never("DEED_NEEDS_TITLE_AND_INSPECTION", "12.9 guardrail: no deed acceptance without title verification and inspection", (i) => (str(i, "status") === "deed_accepted" || str(i, "status") === "deed_received") && !(flag(i, "title_verified") && flag(i, "inspection_done")), "order title and inspection first")] },
  { name: "ratio.compute", kind: "read", handler: compute((i) => { const p = cents(i.price_cents), v = cents(i.value_cents); return { ratio_pct: v > 0n ? ((p * 10000n) / v).toString().replace(/(\d{2})$/, ".$1") : null }; }) },
  // Contribution math is code (D2-3.3-01 / 12.9 rule 3): the $10,000-reserves / 40%-ratio triggers and the no-BRP / PCS / prohibited-by-law exclusions are read from the input facts, so `required` is false for a borrower the Guide says is not evaluated.
  { name: "contribution.compute", kind: "read", handler: compute((i) => { const c = contributionOf(i); return { ...c, negotiated: i.offer_cents === undefined || !c.required ? null : negotiated(c.request_cents, cents(i.offer_cents)) }; }),
    guardrails: [never("NO_RELOCATION_WITH_CONTRIBUTION", "12.9 guardrail: no relocation payment when a contribution is required", (i) => flag(i, "relocation_requested") && contributionOf(i).required && !str(i, "fnma_approval_id"), "absent Fannie Mae approval")] },
  valuationOrderGet(),
  orderGet("title.order/get", "title_orders", "title.ordered"),
  orderGet("inspection.order/get", "inspection_orders", "inspection.ordered"),
  smduSubmitPoll(),
  { name: "offer.evaluate", kind: "read", handler: compute((i) => { const np = netProceeds(cents(i.price_cents), { commission: cents(i.commission_cents), prorations: cents(i.prorations_cents), transfer_taxes: cents(i.transfer_taxes_cents), title_settlement: cents(i.title_settlement_cents), seller_attorney: cents(i.seller_attorney_cents), hoa_past_due: cents(i.hoa_past_due_cents), subordinate_liens: cents(i.subordinate_liens_cents), relocation: cents(i.relocation_cents) }); return { ...np, routing: delegationRouting({ reserves_cents: cents(i.reserves_cents), net_proceeds_within_parameters: flag(i, "within_parameters"), mi_non_delegated: flag(i, "mi_non_delegated") }) }; }) },
  noticeTool(),
  // The instruction that actually pays relocation is checked against the case record: a required contribution bars it absent a Fannie Mae approval id (D2-3.3-01; 12.9 rule 3).
  { name: "closing.instructions.send", kind: "act", handler: compute((i, ctx, rt) => { need(i, "loan_id", "closing_agent_id"); const c = rt.store.get("liquidation_cases", str(i, "case_id") || `liq-${str(i, "loan_id")}`); const reloc = cents(i.relocation_cents); if (reloc > 0n && c?.data.contribution_required === true && !str(i, "fnma_approval_id") && !c.data.fnma_approval_id) throw new RangeError(`NO_RELOCATION_WITH_CONTRIBUTION: case ${c.id} requires a cash contribution — relocation assistance is not payable absent Fannie Mae approval (D2-3.3-01; 12.9 guardrail)`); return ctx.events.append({ type: "closing.instructions.sent", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { closing_agent_id: str(i, "closing_agent_id"), relocation_cents: reloc, case_id: c?.id ?? null } }); }),
    guardrails: [never("NO_RELOCATION_WITH_CONTRIBUTION", "12.9 guardrail: no relocation payment when a contribution is required", (i) => cents(i.relocation_cents) > 0n && flag(i, "contribution_required") && !str(i, "fnma_approval_id"), "absent Fannie Mae approval")] },
  // Funding is refused on the review's own finding (borrower paid beyond the incentive) or a related-party buyer, not on a caller-supplied flag.
  { name: "settlement.review", kind: "read", handler: compute((i, ctx, rt) => { const r = settlementReview({ cd_lines: (i.cd_lines as Parameters<typeof settlementReview>[0]["cd_lines"] | undefined) ?? [], relocation_cents: cents(i.relocation_cents) }); const anomaly = r.escalation !== null || flag(i, "related_party_buyer"); if (anomaly) rt.escalations.open({ kind: "fraud_officer", loanId: (i.loan_id as string | undefined) ?? ctx.loanId, payload: { finding: r.finding ?? "related-party buyer", excess_cents: r.excess_cents }, severity: "sev2" }, ctx.actor); ctx.events.append({ type: "liquidation.settlement.reviewed", loanId: (i.loan_id as string | undefined) ?? ctx.loanId, actor: ctx.actor, payload: { funding_blocked: anomaly, finding: r.finding ?? (flag(i, "related_party_buyer") ? "related-party buyer" : null) } }); if (flag(i, "authorize_funding") && anomaly) throw new RangeError(`FUNDING_BLOCKED_ON_ANOMALY: ${r.finding ?? "related-party buyer"} — qc-audit/officer fraud review before funding (12.9 guardrail)`); return { ...r, funding_blocked: anomaly }; }),
    guardrails: [never("FUNDING_BLOCKED_ON_ANOMALY", "12.9 guardrail: settlement anomalies → fraud review before funding", (i) => flag(i, "authorize_funding") && (flag(i, "related_party_buyer") || flag(i, "undisclosed_payment")), "qc-audit/officer fraud review first")] },
  erecording(),
  { name: "lien_release.request", kind: "act", handler: compute((i, ctx) => { need(i, "loan_id"); return ctx.events.append({ type: "lien_release.requested", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { basis: str(i, "basis") || "mortgage_release" } }); }) },
  { name: "mi.claim.prepare", kind: "act", handler: compute((i, ctx, rt) => { need(i, "loan_id"); const rec = rt.store.put("mi_claims", str(i, "id") || `mic-${str(i, "loan_id")}`, { loan_id: str(i, "loan_id"), status: "prepared", kind: str(i, "kind") || "short_sale" }, ctx.actor, ctx.now); return rec.data; }) },
  { name: "reogram.watch", kind: "act", handler: compute((i, ctx) => { need(i, "loan_id"); return ctx.events.append({ type: "reogram.watch.started", loanId: str(i, "loan_id"), actor: ctx.actor, payload: { since: ctx.now } }); }) },
  timers(),
  attorneyInstruct(),
]);

export const SECTION_12_TOOLS: readonly ToolDef[] = [...p121, ...p122, ...p124, ...p125, ...p126, ...p127, ...p128, ...p129];
export const unusedHelpers = { write, readWrite, ledgerPost, nib };
