// 26.1 Closing document generation and closing instructions (uniform instruments, riders, eNote form, MERS MOM language, state variants incl. Texas 50(a)(6) and NY CEMA, buydown agreements, POA/trust documents, final 1003, document QC)
// spec/sections/26-closing-execution-documents-eclosing-ron-funding-and-post-cl/26-1-closing-document-generation-and-closing-instructions-uniform.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("26.1-T1: Given the fixture snapshot ($560,000.00; 6.125%; 360 months), when `computeNoteTerms` runs, then P&I = $3,402.62, first payment Jan 1, 2027, maturity Dec 1, 2056, late charge 5% / 15 days, and `DQC_NOTE_CD_PI` passes against the CD.", { todo: true });
test("26.1-T2: Given an Arizona 1-unit primary refinance with `closing.enote_default=true` and partner eMortgage approval, when `selectDocumentSet` runs, then the set is `{3200e, 3003 (07/2021), final 1003, H-8 \u00d72 per consumer, closing instructions}` with no riders and `closing_type=ron`.", { todo: true });
test("26.1-T3: Given the same loan in Texas as a 50(a)(6) cash-out, then the set uses 3244.1, 3044.1, 3185, FMV acknowledgment, closing receipt, `closing_type=wet`, and any attempt to build an eNote is refused with reason `product_excluded_emortgage`.", { todo: true });
test("26.1-T4: Given a TX application submitted Mon Oct 5, 2026 with the \u00a750(g) notice e-delivered the same day, then `earliest_closing_date` = Sat Oct 17, 2026; with the notice mailed Oct 5 instead, presumed provided Thu Oct 8 \u2192 earliest closing Tue Oct 20, 2026.", { todo: true });
test("26.1-T5: Given a TX closing scheduled Fri Nov 6, 2026 with the CD received Mon Nov 2 and a $35 recording-fee change delivered Thu Nov 5, then `TX_50A6_ITEMIZATION_1BD_GATE` opens Fri Nov 6; a change delivered Fri Nov 6 without an emergency or good-cause consent (7 TAC \u00a7153.13(5)\u2013(6)) moves `earliest_itemization_closing_date` to Sat Nov 7 (a \u00a7153.1(A) business day); with an owner-elected de minimis good-cause consent on file the Fri Nov 6 closing stands.", { todo: true });
test("26.1-T6: Given TX counted fees of $8,000.01 on a $400,000 loan, then `DQC_TX_2PCT` fails and release is refused; at $8,000.00 it passes.", { todo: true });
test("26.1-T7: Given a Michigan mortgage template dated 07/2021 and a PUD rider dated 1/01 in the library, when the set is generated, then `DQC_TEMPLATE_VERSION` fails with reason `revision_mix`.", { todo: true });
test("26.1-T8: Given a Virginia deed of trust with note date July 1, 2026, then only Form 3047 with `mandatory_from \u2264 2026-07-01` (the May 2026 revision) passes the gate; the prior revision fails.", { todo: true });
test("26.1-T9: Given a borrower who is trustee and settlor of a revocable trust and the credit applicant, then the note signature line reads \"individually and as Trustee of the \u2026 Trust under trust instrument dated \u2026\" and the deed of trust carries the settlor acknowledgment paragraph.", { todo: true });
test("26.1-T10: Given a 2-1 buydown at 6.500% on $412,000 funded by the seller, then the schedule computes $516.58 and $264.83 monthly subsidies, total $9,376.92, SFC 009, the note shows 6.500%/$2,604.12, and the agreement carries the \"not relieved of obligation\" clause.", { todo: true });
test("26.1-T11: Given the NMLSR ID on the note differs from the CD's, then `DQC_NMLSR_36G` fails and release is refused.", { todo: true });
test("26.1-T12: Given a Montana property, then Form 3158 is in the set and the closing instructions forbid a post-closing assignment to MERS; given Maine, Form 3749 is rendered for `signing_officer` execution.", { todo: true });
test("26.1-T13: Given a NY CEMA with prior unpaid principal $300,000.00 and new money $60,000.00, then Form 3172 consolidates $360,000.00, the \u00a7255 affidavit states new money $60,000.00, and `closing_type\u2260ron` is not forced but `enote=false`.", { todo: true });
test("26.1-T14: Given a release attempted with `SM_O71_DOC_QC_PASS_GATE` closed, then `releaseToPlatform` is refused and an `escalation` to `officer` exists only if a waiver was requested.", { todo: true });
