// 26.3 Funding authorization and disbursement (funding conditions, wet vs dry states, rescission expiry, wire controls, per-diem interest and interest credits, table-funding analysis, unwind)
// spec/sections/26-closing-execution-documents-eclosing-ron-funding-and-post-cl/26-3-funding-authorization-and-disbursement-funding-conditions-we.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("26.3-T1: Given consummation Fri Nov 6, 2026 (refinance, AZ), when the rescission period is computed and the Fedwire calendar applied, then `rescission_expires_at` = midnight ending Tue Nov 10, `earliest_funding_date` = Thu Nov 12 (Wed Nov 11 Veterans Day excluded), and `disburse` on Nov 11 is refused with `FC_FEDWIRE_DAY = fail` and `REGZ_1026_23_RESCISSION_3SBD_GATE` closed until the 25.3 sweep.", { todo: true });
test("26.3-T2: Given $560,000.00 at 6.125% disbursed Nov 12, 2026, when per-diem is computed under `365_rounded_per_diem`, then `per_diem_cents` = 9,397, `prepaid_days` = 19, `per_diem_interest_cents` = 178,543 ($1,785.43), first payment Jan 1, 2027, `first_payment_latest_allowed_date` = Jan 12, 2027, `lpi_date` = Dec 1, 2026, `maturity_date_expected` = Dec 1, 2056, and the gate passes; the unrounded product $1,785.48 never appears on any artifact.", { todo: true });
test("26.3-T3: Given disbursement Thu Dec 3, 2026 on a note printed with first payment Jan 1, 2027, when `decideInterestMode` runs with a 7-day window, then interest-credit mode is offered with `interest_credit_cents` = 18,794 ($187.94), accrual start Dec 1, first payment Jan 1, 2027 (gate: \u2264 Feb 3 \u2713) and no re-draw; given disbursement Dec 15, then interest credit is refused, prepaid = 17 \u00d7 $93.97 = $1,597.49, first payment Feb 1, 2027 and an 26.1 re-draw (`date_change`) is opened before funding.", { todo: true });
test("26.3-T4: Given disbursement Tue Nov 3, 2026 with interest credit, then `interest_credit_days` = 2, `first_payment_date` = Dec 1, 2026, `lpi_date` = Nov 1, 2026, and the authorization record carries `delivery_window_compressed = true` with the Dec 16, 2026 LPI-45 date handed to 29.4.", { todo: true });
test("26.3-T5: Given the consummated CD shows gross $560,000.00, prepaid interest $1,785.43, escrow deposit $1,665.00 and lender credit $700.00, when the settlement statement requests $557,249.57, then `variance_cents` = 0, `FC_FIGURES_RECONCILED = pass`, and the SM ledger set is Dr `warehouse_advance_receivable` 54,880,000 / Dr `partner_haircut_reserve` 844,957 / Cr `sm_funding_cash` 55,724,957; when the statement requests $557,449.57, then the funding holds with `variance_cents` = 20,000 and an escalation to the settlement agent.", { todo: true });
test("26.3-T6: Given a verified wire record (Nov 3) and an e-mail on Nov 12 07:30 ET from `closer@escrow-c0.com` (domain altered) instructing a new account, when `scoreBecIndicators` runs, then two indicators hit (altered address; changed account at a known beneficiary), `funding.held{bec_indicator}` is emitted, a callback is required to the ALTA-Registry number, and even after a genuine confirmation the earliest release is Fri Nov 13 (no same-day changes); the original verified instructions are the only ones the agent may prepare.", { todo: true });
test("26.3-T7: Given a prepared wire, when the same user who edited the worksheet attempts release, then release is refused (`released_by` must differ from every editor); when a distinct `funding_approver` releases at 09:40 ET, then `funding.wire.released`, IMAD within 30 minutes, and `funding.wire.accepted`; when the IMAD is not received by 10:10 ET, then `SM_O73_WIRE_ACCEPT_30M` breaches and the bank is contacted \u2014 no second wire is prepared.", { todo: true });
test("26.3-T8: Given a wet-state purchase closing Wed Nov 18, 2026 10:05 ET, when the pre-signing subset passes Nov 17 and the wire (value date Nov 18) is accepted at 08:56 ET, then `SM_O73_WET_FUNDS_AT_TABLE_GATE` is satisfied; when the execution review passes 11:40 ET, then the disbursement authorization is sent and `loan.funded{disbursement_date=2026-11-18}` follows the agent's 13:15 ET confirmation; prepaid interest = 13 \u00d7 $71.96 = $935.48 and first payment Jan 1, 2027 (\u2264 Jan 18 \u2713).", { todo: true });
test("26.3-T9: Given a refinance in Virginia with rescission expiring midnight Tue Nov 10, 2026, when the wire is released Thu Nov 12 (Nov 11 a Fedwire holiday), then `VA_55_1_902_REFI_DISBURSE_1BD` (federal-calendar reading) is satisfied; when it is released Fri Nov 13, then the timer breaches and a sev-1 escalation to `officer` records the statutory exposure.", { todo: true });
test("26.3-T10: Given a valid rescission notice received Fri Nov 13 postmarked Tue Nov 10 after the Nov 12 disbursement, when 25.3 records `rescission.exercised`, then 26.3 opens `funding_unwinds{funds_position=disbursed}` with steps (recover escrow deposit; partner repurchase of the advance; void document set; eNote reversal; MIN deactivation; release/reconveyance; de-board; HMDA update), the money steps carry `refund_due_at` = Thu Dec 3, 2026 (25.3), and no step moving money executes without `officer` approval.", { todo: true });
test("26.3-T11: Given consummation Wed Nov 25, 2026, then `rescission_expires_at` = midnight ending Mon Nov 30, `earliest_funding_date` = Tue Dec 1, `interest_mode = none`, prepaid interest $0.00, first payment Jan 1, 2027, and the printed note (first payment Jan 1; maturity Dec 1, 2056) needs no re-draw.", { todo: true });
test("26.3-T12: Given `origination.warehouse_legal_form = secured_loan_to_partner`, when the wire is prepared, then `originator_to_beneficiary_info` names the partner as lender and the partner loan number, no assignment/endorsement to SM exists in `closing_documents`, and the posting target is `warehouse_advance_receivable`; given the flag set to `purchase_at_settlement` without an `officer`+`attorney` decision record (31.1), then `funding.authorized` is refused with reason `table_funding_form_not_approved`.", { todo: true });
test("26.3-T13: Given a dry-state loan whose executed package is not returned by Mon Nov 9 17:00 MST (signing Nov 6), then the funding stays `pending_conditions` with `FC_DOCS_EXECUTED_QC = pending`, the settlement agent is escalated at day 2 and the title underwriter notified at day 5; no wire is ever prepared.", { todo: true });
test("26.3-T14: Given the hazard policy's effective date is Nov 12 and funding slips to Nov 13, when `SM_O73_DATE_RESYNC` runs, then `FC_HAZARD_EVIDENCE` still passes (effective \u2264 disbursement), prepaid interest becomes 18 \u00d7 $93.97 = $1,691.46, the 24.4 payoff good-through is re-tested, and 25.2 is asked whether a corrected CD is due.", { todo: true });
