// 26.4 Post-closing document collection, collateral perfection, and trailing documents (endorsements/allonges, assignments for non-MERS, MERS MOM registration and interim-funder designation, recorded security instrument, final title policy, note custody and shipping to warehouse/document custodian)
// spec/sections/26-closing-execution-documents-eclosing-ron-funding-and-post-cl/26-4-post-closing-document-collection-collateral-perfection-and-t.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("26.4-T1: Given a refinance in Arizona (escrow state) with note date Fri Nov 6, 2026 and funding Thu Nov 12, when the MERS anchor is computed, then `anchor_kind = funding_date`, `registration_due_at` = Thu Nov 19, 2026, `policy_target_at` = Fri Nov 13, and `SM_O74_MOM_REGISTER_TARGET_1BD` is due Mon Nov 9; when the registration is accepted in the Nov 9 batch, then all three are satisfied; when it is first accepted Fri Nov 20, then `MERS_PROC_MOM_REGISTER_7` is breached (sev 1) even though `policy_target_at` breaches earlier.", { todo: true });
test("26.4-T2: Given a purchase in Ohio (non-escrow, wet) with note date Wed Nov 18, 2026, then `anchor_kind = note_date`, `registration_due_at` = Wed Nov 25, 2026; given the same loan in Maine with a Form 3749 assignment executed Nov 18, then `MERS_PROC_NON_MOM_REGISTER_7` is due Nov 25 and `registration_kind = non_mom_assignment`.", { todo: true });
test("26.4-T3: Given a registration payload, when it names any Investor other than the partner's Org ID before purchase, or names SM as Servicer, then `registerMin` refuses the submission; when `warehouse.advance.funded` occurs Thu Nov 12 at 09:40 ET, then Interim Funder = SM is submitted in the Nov 12 batch and `SM_O74_INTERIM_FUNDER_1BD` (due Fri Nov 13) is satisfied.", { todo: true });
test("26.4-T4: Given `endorsement_method = allonge_pre_executed` with an allonge whose note amount reads $560,000.00 and note date Nov 6, 2026, when the shipment is requested, then `SM_O74_ENDORSEMENT_BEFORE_SHIP_GATE` opens; given the allonge shows $565,000.00 (a re-drawn loan amount), then the gate refuses shipment and a replacement allonge escalation goes to `signing_officer`; given `printed_facsimile` in a state with no legal opinion in the authority file, then the gate refuses and the desk route is used.", { todo: true });
test("26.4-T5: Given a paper note shipped Mon Nov 9, 2026 16:10 MST with a pickup scan, when delivery is scanned Tue Nov 10 10:05 ET and the trust receipt arrives 14:30 ET, then `SM_O74_NOTE_TRANSIT_3BD` and `SM_O74_TRUST_RECEIPT_1BD` are satisfied and 27.1 receives `warehouse.note.received` before the Nov 12 advance; given no delivery scan by Fri Nov 13 (3 `business_days_servicer`: Nov 10, 12, 13), then a trace opens, and with no delivery by Tue Nov 17 `note.lost_in_transit` is emitted and `SM_O74_LNA_DECISION_5BD` is due Tue Nov 24.", { todo: true });
test("26.4-T6: Given a wet advance funded Thu Nov 12, 2026 for a paper note, then 27.1's `SM_WH_WET_NOTE_DELIVERY_5BD` due date is Thu Nov 19, 2026 (Nov 13, 16, 17, 18, 19) and 26.4's shipment plan targets delivery by Tue Nov 17; given the purchase fixture funded Wed Nov 18, then the due date is Wed Nov 25 (Thanksgiving excluded).", { todo: true });
test("26.4-T7: Given a deed of trust eRecorded Mon Nov 9, 2026 10:12 MST, then `trailing_documents{recorded_security_instrument}.due_at` = Tue Nov 17 (5 `business_days_creditor`, Veterans Day excluded) and `final_title_policy.due_at` = Fri Jan 8, 2027 (60 calendar days); when the recorded image (15 pages, MIN present, legal description hash equal, RON certificate) is reviewed, then `pass`; when the image lacks the PUD Rider page, then `defect{missing_rider}` with `SM_O74_RERECORD_CURE_10BD` due 10 business days later and the title underwriter notified.", { todo: true });
test("26.4-T8: Given a final policy received Tue Dec 1, 2026 on the 2021 ALTA Loan Policy for $560,000.00 naming the partner ISAOA/ATIMA with Date of Policy Nov 9, 2026, Schedule A matching `recordings`, Schedule B without new exceptions and ALTA 8.1 issued, then `final_policy_reviews.result = pass` and the trailing item closes; given the insured is \"Mortgage Electronic Registration Systems, Inc.\" or the amount is $555,000.00, then `defect` and a correction request with the 30-day follow-up cadence.", { todo: true });
test("26.4-T9: Given a custodian exception `endorser_not_on_resolution` recorded Mon Nov 23, 2026, then `SM_O74_CUSTODIAN_EXCEPTION_CURE_5BD` is due Tue Dec 1, 2026 (Thanksgiving excluded); when the corporate secretary certification is delivered Nov 24, then `custody.exception.cured` and 27.1's defect closes; when nothing is delivered by Dec 1, then sev 2 escalations to `signing_officer` and `officer` fire and the delivery (29.4) cannot certify.", { todo: true });
test("26.4-T10: Given a registered MIN (Nov 9) and a rescission exercised Tue Nov 10, 2026, then `SM_O74_MIN_REVERSAL_2BD` is due Fri Nov 13 (Nov 12, 13 \u2014 Nov 11 excluded), the reversal is submitted in the Nov 12 batch, the recorded deed of trust's release is tracked to recording, and every trailing item is `waived{loan_cancelled}` with no `officer` action except the note release (paper) or none (eNote).", { todo: true });
test("26.4-T11: Given an eNote in SM's eVault with Secured Party = SM, when the daily hash check finds the eVault hash \u2260 the eRegistry hash, then a sev 1 escalation to `officer` opens, 27.1 is told the collateral is `defect`, and no delivery request is prepared; when the monthly reconciliation on Tue Dec 1 finds Controller = Fannie Mae after the Nov 19 purchase and Investor = Fannie Mae on the MERS System, then `mers.reconciliation.completed{variances=0}`.", { todo: true });
test("26.4-T12: Given a Maine loan, then 26.1 renders Form 3749, the `signing_officer` executes it at closing, it is recorded promptly after the mortgage, `recorded_assignment_to_mers` is expected, and no other assignment (intervening, to Fannie Mae) exists on any loan in the population \u2014 a query for `closing_documents.kind` containing \"assignment\" outside Maine returns zero rows.", { todo: true });
test("26.4-T13: Given the trailing-document population for the refinance fixture at Fri Mar 12, 2027 (120 days after Nov 12 funding), when the final policy is still open, then `SM_O74_TRAILING_DOC_ESCALATE_120` fires to `officer`, the QC file is flagged for 28.2, and the follow-up ladder shows at least four logged attempts (Jan 8, Feb 7, Mar 9 cadence plus the initial request).", { todo: true });
