/**
 * §26.4 timer overrides (process-owned; applied after every section's so they win the merge — see
 * src/domain/bankruptcy/timers-14-1.ts for the pattern). One `reg.override(code, { trigger?, satisfied | evaluator,
 * anchorField?, offset?, why })` per 26.4 registry row whose trigger/satisfied column names an event the platform
 * spells differently or a condition the column grammar drops; `why` quotes the spec. A code the servicing spec
 * (sections 1–19) owns is never overridden here — reference it. Wired by src/domain/timer-overrides.ts.
 *
 * Emitters live in src/domain/closing/ops-26-4.ts (the `post-closing` agent runtime): `mers.min.registered{status=active,
 * registration_kind, interim_funder_org_id}` / `.registration_rejected{codes}` / `.updated{field=interim_funder}` / `.reversed` /
 * `.deactivated{reason}` (registerMin, updateMinInterimFunder, submitMinReversal, deactivateMin), `closing.assignment_to_mers
 * .executed{assignment_executed_on}` (recordAssignmentExecuted), `note.shipment.requested` / `note.endorsed{method}` /
 * `note.endorsement.exception` (prepareShipment → recordEndorsementCheck), `note.shipment.in_transit{pickup_scan_on}` /
 * `.delivered{delivered_on}` (trackShipment), `custody.trust_receipt.received` + 27.1's `warehouse.note.received`
 * (ingestTrustReceipt), `note.shipment.trace_opened` / `note.lost_in_transit{determined_on}` / `note.lna.decided{decision}`,
 * `custody.exception.recorded{recorded_on}` / `.cured` (+ 27.1's `warehouse.collateral.defect_recorded{cure_owner}`),
 * `trailing_document.expected{funded_on}` / `.opened` / `.received` / `.reviewed{result}` / `.defect{kind, defect_on}` / `.closed` /
 * `.waived` / `.overdue{last_followup_on}` / `.followup.logged` / `.escalation_120`, `collateral.file.complete`,
 * `recording.image.received{received_on}` / `recording.rerecord.requested`, `title.final_policy.received{received_on}` /
 * `.reviewed{result}` / `.defect` / `.correction_requested`, `mers.reconciliation.opened{scope, as_of}` / `.completed{scope,
 * variances}`, `enote.custody.hash_verified` / `.mismatch` / `.reconciled{scope}`, `collateral.void.opened{event_on}`.
 * Consumed, never redefined: `closing.consummated{anchor_date, note_date}` / `custody.paper_note.shipped{shipped_on}` /
 * `recording.submitted{channel}` / `recording.confirmed{channel}` (26.2), `loan.funded` (26.3), `warehouse.advance.funded
 * {advance_date}` (27.1), `mi.activated` (24.6), `rescission.exercised` (25.3), `funding.cancelled` (26.3). Referenced, not
 * defined: `SM_O72_PAPER_NOTE_HANDOFF_1BD` (26.2), `SM_WH_WET_NOTE_DELIVERY_5BD` / `SM_WH_BAILEE_LETTER_GATE` /
 * `SM_WH_INTERIM_FUNDER_DESIGNATION_7` / `SM_WH_DEFECT_CURE_10BD` (27.1), `SM_WH_INTERIM_FUNDER_RELEASE_2BD` (27.2),
 * `FNMA_B7_1_01_MI_ACTIVE_BEFORE_DELIVERY_GATE` (24.6), the 29.4 custodian rows and the 30.1 investor-update verification.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_26_4(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // ---- MERS registration clocks (rule 1)
  o("MERS_PROC_MOM_REGISTER_7", { anchorField: "anchor_date", satisfied: "`mers.min.registered{status=active}`",
    why: "§26.4 timer table (defined here): deadline on `closing.consummated` (MOM security instrument, paper or eNote), anchor '`anchor_date`: `note_date` for purchase loans outside escrow states; `fundings.funding_date` for refinance loans or loans in escrow states — MERS Procedures Rel. 26.1', +7 calendar_days (end of day 7, local), satisfied by '`mers.min.registered` (status `active`)'. 26.2's consummated payload carries `anchor_date` = the scheduled note date for purchases outside escrow states and null otherwise (the engine then anchors on the consummation day — the conservative provisional deadline); ops-26-4.ts computeMersAnchor recomputes `registration_due_at` from `fundings.funding_date` on `loan.funded` (fixture: Nov 12 funding → Thu Nov 19, 'recomputed for reporting only' per the edge cases) and registerMin appends `mers.min.registered{status=active, registration_kind, interim_funder_org_id, on_time}` from the MERS acknowledgment (30.2 recordMersAcknowledgment appends the same event for a boarding-side acknowledgment). Breach: sev 1 → `officer`; register immediately; MERS QA incident; 27.1 borrowing-base ineligibility." });
  o("SM_O74_MOM_REGISTER_TARGET_1BD", { anchorField: "note_date", satisfied: "`mers.min.registered{status=active}`",
    why: "§26.4 timer table: policy deadline on `closing.consummated`, anchor `note_date`, +1 business_days_creditor ('registration in the next daily batch; always inside `note_date + 7`'), satisfied by `mers.min.registered` — the 18:00 local batch on the note date or the next creditor business day (fixture: Fri Nov 6 note date → Mon Nov 9; Sat/Sun no batch). Breach sev 3; retry next batch; `signing_officer` if the partner's MERS delegation is missing." });
  o("MERS_PROC_NON_MOM_REGISTER_7", { trigger: "`closing.assignment_to_mers.executed`", anchorField: "assignment_executed_on",
    why: "§26.4 timer table (defined here): deadline on 'Assignment to MERS executed (Maine Form 3749; any non-MOM instrument)', anchor `assignment_executed_on`, +7 calendar_days, satisfied by `mers.min.registered{registration_kind=non_mom_assignment}`. The execution of the Form 3749 by the partner's `signing_officer` at closing is recorded by ops-26-4.ts recordAssignmentExecuted as `closing.assignment_to_mers.executed{assignment_executed_on, registration_due_at}` (26.4-T2: executed Wed Nov 18 → due Wed Nov 25). Breach sev 1 → `officer`." });
  o("SM_O74_INTERIM_FUNDER_1BD", { anchorField: "advance_date", satisfied: "`mers.min.updated{field=interim_funder}`",
    why: "§26.4 timer table: deadline on `warehouse.advance.funded` (paper or eNote), anchor 'advance date' (27.1's payload `advance_date`), +1 business_days_servicer (inside 27.1's SM_WH_INTERIM_FUNDER_DESIGNATION_7), satisfied by '`mers.min.updated{field=interim_funder}` = SM Org ID (or set at registration)' — updateMinInterimFunder submits the MIN Update in the same day's 18:00 batch (26.4-T3: advance Thu Nov 12 09:40 ET → Nov 12 batch; due Fri Nov 13) and, when the Interim Funder was already set at registration, appends the same event with `at_registration=true`. Breach sev 2 → post-closing lead; 27.1 notified." });
  o("SM_O74_MIN_REVERSAL_2BD", { trigger: "`collateral.void.opened`", anchorField: "event_on", satisfied: "`mers.min.reversed`",
    why: "§26.4 timer table: deadline on '`funding.cancelled` / `rescission.exercised` before funding on a registered or pre-closing MIN', anchor 'event time', +2 business_days_creditor, satisfied by '`mers.min.reversed` (or `mers.min.deactivated` for a funded-then-unwound loan)'. Both upstream events (26.3 cancelFunding, 25.3 rescission.exercised) are consumed by ops-26-4.ts voidCollateral, which appends `collateral.void.opened{cause, event_on, reversal_due_on, batch_on, min_action}` only when a registered or pre-closing MIN exists — the row arms on that determination (26.4-T10 / worked example 4: rescinded Tue Nov 10 → Nov 12, 13 (Nov 11 excluded) → due Fri Nov 13; reversal in the Thu Nov 12 batch). A funded-then-unwound loan is deactivated (deactivateMin → `mers.min.deactivated{reason}`) and the tool retires this instance with that reason instead of a reversal. Breach sev 2; MERS record inaccurate (B8-7-01)." });
  // ---- endorsement gate and the paper-note custody chain (rules 2, 4, 5)
  o("SM_O74_ENDORSEMENT_BEFORE_SHIP_GATE", { trigger: "`note.shipment.requested`", evaluator: "26.4.endorsementBeforeShipGate", satisfied: "`note.endorsed`",
    why: "§26.4 timer table: not_before_gate on '`custody.paper_note.shipped` request' — '`note_endorsements` present: printed facsimile with the four-document authority file for the property's jurisdiction, or a pre-executed allonge affixed with identifiers matching the note; else route `to_role = endorsement_desk`', satisfied by `note.endorsed`, breach 'shipment to the FCC refused; desk routing used'. prepareShipment appends `note.shipment.requested` on every request and asserts ensureEndorsement (evaluators-26-4.ts endorsementBeforeShipGate over the same facts): open → `note.endorsed{method}`; closed → `note.endorsement.exception` and the endorsement-desk route with a `signing_officer` escalation (26.4-T4: $560,000.00 allonge opens; $565,000.00 re-drawn amount refuses; facsimile without the state's legal opinion refuses)." });
  o("SM_O74_NOTE_PICKUP_SCAN_1BD", { anchorField: "shipped_on", satisfied: "`note.shipment.in_transit`",
    why: "§26.4 timer table: deadline on `custody.paper_note.shipped` (26.2's event; payload `shipped_on` is the property-local day), anchor shipped_at, +1 business_days_servicer, satisfied by 'carrier pickup scan' — trackShipment(kind=pickup) appends `note.shipment.in_transit{pickup_scan_at, pickup_scan_on}` from the carrier tracking API. Breach sev 3; settlement agent contacted." });
  o("SM_O74_NOTE_TRANSIT_3BD", { trigger: "`note.shipment.in_transit`", anchorField: "pickup_scan_on", satisfied: "`note.shipment.delivered`",
    why: "§26.4 timer table: deadline on 'carrier pickup scan', anchor 'scan time', +3 business_days_servicer, satisfied by 'delivery scan at the custodian' — `note.shipment.in_transit{pickup_scan_on}` arms it and trackShipment(kind=delivery) appends `note.shipment.delivered{delivered_on}` (26.4-T5: pickup Mon Nov 9 16:10 MST → Nov 10, 12, 13 → due Fri Nov 13; delivered Tue Nov 10 10:05 ET). Breach: openTrace → `note.shipment.trace_opened`; day 5 without delivery (Tue Nov 17) → handleLostNote → `note.lost_in_transit`." });
  o("SM_O74_TRUST_RECEIPT_1BD", { trigger: "`note.shipment.delivered`", anchorField: "delivered_on", satisfied: "`custody.trust_receipt.received`",
    why: "§26.4 timer table: deadline on 'delivery scan', anchor delivered_at, +1 business_days_servicer, satisfied by '`custody.trust_receipt.received` (`warehouse.note.received`, 27.1)' — ingestTrustReceipt appends both: 26.4's receipt event and 27.1's `warehouse.note.received{collateral_status=secured_possession}` in 27.1's payload shape (fixture: delivered Tue Nov 10 10:05 ET, trust receipt 14:30 ET → secured_possession before the Nov 12 advance). Breach sev 2; custodian contacted; 27.1 `unsecured_wet` continues." });
  o("SM_O74_CUSTODIAN_EXCEPTION_CURE_5BD", { anchorField: "recorded_on",
    why: "§26.4 timer table: deadline on `custody.exception.recorded`, anchor recorded_at (payload `recorded_on`, the custodian's local day), +5 business_days_servicer, satisfied by '`custody.exception.cured` (corrected endorsement/allonge, name affidavit, POA copy, MIN added)' — recordCustodianException / cureCustodianException (26.4-T9: `endorser_not_on_resolution` Mon Nov 23 → Nov 24, 25, 27, 30, Dec 1 (Thanksgiving excluded) → due Tue Dec 1; corporate secretary certification Nov 24 cures). Breach sev 2 → `signing_officer` / `officer` (custodianExceptionBreach); 27.1 SM_WH_DEFECT_CURE_10BD runs in parallel from the `warehouse.collateral.defect_recorded{source=custodian_exception}` the same op appends; 29.4 cannot certify (`custody.certification.blocked`)." });
  o("SM_O74_LNA_DECISION_5BD", { anchorField: "determined_on", satisfied: "`note.lna.decided{decision∈{re_execute, lna, both}}`",
    why: "§26.4 timer table: deadline on '`note.lost_in_transit` (trace failed)', anchor 'determination', +5 business_days_creditor, satisfied by '`lost_note_affidavits.decision` set by `officer` (re-execute preferred)' — handleLostNote appends `note.lost_in_transit{determined_on, decision_due_on}` after the documented search; decideLostNote (officer only; LNA alone only when the borrower cannot or will not re-execute) appends `note.lna.decided{decision}` (26.4-T5: determined Tue Nov 17 → Nov 18, 19, 20, 23, 24 → due Tue Nov 24). Breach sev 1; 27.1 repurchase clock unaffected." });
  // ---- recorded security instrument (rule 6)
  o("SM_O74_RECORDED_SI_ERECORD_5BD", { satisfied: "`recording.image.received`",
    why: "§26.4 timer table: deadline on `recording.confirmed{channel=erecording}` (26.2), anchor recorded_at (an instant — the engine anchors on the event's day: Mon Nov 9 10:12 MST), +5 business_days_creditor, satisfied by `recording.image.received` — ingestRecordedImage appends it with `received_on` (26.4-T7: Nov 10, 12, 13, 16, 17 — Veterans Day excluded → Tue Nov 17). Breach sev 3; vendor/county follow-up." });
  o("SM_O74_RECORDED_SI_PAPER_90", { satisfied: "`recording.image.received`",
    why: "§26.4 timer table: deadline on '`recording.submitted{channel=paper}` / `recording.paper_fallback`' (26.2 appends `recording.submitted{channel=paper}` with every paper fallback), anchor 'submitted date', +90 calendar_days (override: `jurisdiction_rules.recording_turnaround_days` — trailingDueAt applies the county figure to the SOR due date), satisfied by 'recorded original or certified copy received' → ingestRecordedImage's `recording.image.received{certified_copy, original_or_certified=true}`. Breach: follow-up cadence; day 180 → certified-copy request and `officer` (sweepTrailingDocuments)." });
  o("SM_O74_RECORDED_SI_REVIEW_2BD", { anchorField: "received_on",
    why: "§26.4 timer table: deadline on `recording.image.received`, anchor received_at (payload `received_on`), +2 business_days_creditor, satisfied by `trailing_document.reviewed` — recordRecordedInstrumentReview appends `trailing_document.reviewed{kind, result}` from reviewRecordedInstrument's checklist (worked example 1: image 10:20, review 11:05 → pass). Breach sev 3." });
  o("SM_O74_RERECORD_CURE_10BD", { trigger: "`trailing_document.defect{kind=recorded_security_instrument}`", anchorField: "defect_on",
    why: "§26.4 timer table: deadline on `trailing_document.defect{recorded_security_instrument}` — the column's bare token is the document kind, so the trigger conditions on `kind=recorded_security_instrument` — anchor 'defect time' (`defect_on`), +10 business_days_creditor, satisfied by '`recording.rerecord.requested` (corrective instrument/affidavit submitted)' — requestRerecording (26.4-T7 / worked example 3: PUD Rider page missing Thu Nov 19 → Nov 20, 23, 24, 25, 27, 30, Dec 1, 2, 3, 4 → due Fri Dec 4; county correction requested Nov 19; the defect event carries `title_underwriter_notified=true`). Breach sev 2 → `officer`; title underwriter notified." });
  // ---- final title policy (rule 7)
  o("SM_O74_FINAL_TITLE_POLICY_60", { satisfied: "`title.final_policy.received`",
    why: "§26.4 timer table: policy deadline on `recording.confirmed` (insured mortgage; 26.2), anchor recorded_at (the event's day), +60 calendar_days, satisfied by '`title.final_policy.received` (or final AOL)' — ingestFinalPolicy appends it for the policy or the final AOL row (26.4-T7 / T8: recorded Mon Nov 9, 2026 → due Fri Jan 8, 2027; received Tue Dec 1). Breach: follow-up to settlement agent/underwriter every 30 days (SM_O74_TRAILING_DOC_FOLLOWUP_30); day 120 → `officer`; day 180 → underwriter escalation/CPL." });
  o("SM_O74_FINAL_POLICY_REVIEW_2BD", { anchorField: "received_on",
    why: "§26.4 timer table: deadline on `title.final_policy.received`, anchor received_at (payload `received_on`), +2 business_days_creditor, satisfied by `title.final_policy.reviewed` — recordFinalPolicyReview appends `title.final_policy.reviewed{result}` from reviewFinalPolicy (B7-2-03: 2021 ALTA form, insured = partner ISAOA/ATIMA never MERS, amount ≥ original principal $560,000.00, Schedule A = `recordings`, Schedule B without new exceptions, ALTA 8.1 + `required_endorsements`, no creditors'-rights exclusion). Breach sev 3." });
  // ---- follow-up ladder and the 120-day escalation
  o("SM_O74_TRAILING_DOC_FOLLOWUP_30", { trigger: "`trailing_document.overdue`", anchorField: "last_followup_on", satisfied: "`trailing_document.closed`",
    why: "§26.4 timer table: recurring 'every 30 calendar_days' on 'any `trailing_documents.status ∈ {open, defect_open}` past `due_at`', anchor 'last follow-up', satisfied by 'document received/closed'. The 07:00 sweep (sweepTrailingDocuments) appends `trailing_document.overdue{kind, due_at, last_followup_on, next_followup_on}` for each open item past due — the state condition the column names — and the engine re-arms each 30-day instance from it; the item's `trailing_document.closed` (closeTrailingDocument, after a passed review) satisfies it. followUp logs each attempt (portal/vendor API, e-mail, phone) with `next_at` = +30 (26.4-T13: due Jan 8 → Feb 7 → Mar 9, 2027 plus the initial request)." });
  o("SM_O74_TRAILING_DOC_ESCALATE_120", { anchorField: "funded_on", satisfied: "`collateral.file.complete`",
    why: "§26.4 timer table: deadline on `trailing_document.expected`, anchor '`loan.funded` date' (payload `funded_on`), '+120 calendar_days for any open item', satisfied by 'closed' — expectTrailingDocuments appends one `trailing_document.expected{kinds, funded_on}` per loan at `loan.funded`, and the loan-level clock is closed by `collateral.file.complete` (every expected item closed or waived — the only reading of 'closed … for any open item' at the loan level; closeTrailingDocument appends it). Breach (26.4-T13: funded Thu Nov 12, 2026 → Fri Mar 12, 2027 with the final policy open): sev 2 → `officer`; QC file flagged for 28.2 (`qc.file.flagged{process=28.2}`, sweepTrailingDocuments)." });
  o("SM_O74_MI_CERT_ACTIVE_5BD", { anchorField: "note_date",
    why: "§26.4 timer table: deadline (tracks 24.6) on `loan.funded` (LTV > 80%; 26.3's payload carries the origination note date via 30.2 — anchor `note_date` when present, else the funding day), +5 business_days_creditor, satisfied by '`mi.activated` and the activated certificate filed' (24.6 owns activation and appends `mi.activated`; the `mi_certificate` trailing row closes on the filed certificate). Breach: 24.6 escalation; delivery blocked by FNMA_B7_1_01_MI_ACTIVE_BEFORE_DELIVERY_GATE." });
  // ---- monthly reconciliations (rules 9, 11)
  o("SM_O74_EVAULT_EREGISTRY_RECONCILE_MONTHLY", { trigger: "`mers.reconciliation.opened{scope=eregistry}`", anchorField: "as_of", satisfied: "`enote.custody.reconciled{scope=eregistry}`",
    why: "§26.4 timer table: recurring monthly, trigger '—', anchor '1st of month', satisfied by '`enote.custody.reconciled` for every eNote with Location = SM/vendor eVault (hash, Controller, Location, Secured Party match)'. The 1st-of-month schedule is recorded by openMonthlyReconciliation as `mers.reconciliation.opened{scope=eregistry, as_of, source=origination}` (the population-level clock; `source=origination` lets the origination-side row arm without an application id) and reconcileEregistry appends `enote.custody.reconciled{scope=eregistry, variances}` (worked example 1: Tue Dec 1 — Controller/Location = Fannie Mae after the Nov 19 purchase, Secured Party none). Breach/variances → `officer`; MERS QA record." });
  o("SM_O74_MERS_SYSTEM_RECONCILE_MONTHLY", { trigger: "`mers.reconciliation.opened{scope=mers_system}`", anchorField: "as_of", satisfied: "`mers.reconciliation.completed{scope=mers_system}`",
    why: "§26.4 timer table: recurring monthly (MERS QA cadence — UNVERIFIED), trigger '—', anchor '1st of month', satisfied by '`mers.reconciliation.completed` (SOR vs MERS System: status, Servicer, Investor, Interim Funder, Subservicer)' — openMonthlyReconciliation's `mers.reconciliation.opened{scope=mers_system, as_of}` arms it and reconcileMersSystem appends `mers.reconciliation.completed{scope=mers_system, variances, cure_due_on}` (26.4-T11: Tue Dec 1 finds Investor = Fannie Mae after the Nov 19 purchase → variances=0). Variances cured within 10 business_days_servicer (`cure_due_on`); `officer`." });
}
