/**
 * §26.2 timer overrides (process-owned; applied after every section's so they win the merge — see
 * src/domain/bankruptcy/timers-14-1.ts for the pattern). One `reg.override(code, { trigger?, satisfied | evaluator,
 * anchorField?, offset?, why })` per 26.2 registry row whose trigger/satisfied column names an event the platform
 * spells differently or a condition the column grammar drops; `why` quotes the spec. A code the servicing spec
 * (sections 1–19) owns is never overridden here — reference it. Wired by src/domain/timer-overrides.ts.
 *
 * Emitters live in src/domain/closing/ops-26-2.ts (the `closer` runtime of the `title-closing` agent):
 * `closing.scheduled{closing_type, …}` (scheduleClosing), `closing.eligibility.checked{check, result}` (recordEligibilityCheck),
 * `closing.consent.verified` (verifyConsent), `closing.consummated{note_form, consummation_on, …}` / `enote.signed` (signDocument),
 * `closing.notarial_act.completed{last, recording_anchor, anchor_date}` (completeNotarialAct), `enote.tamper_sealed
 * {registration_anchor_date, registration_due_at}` (tamperSeal), `enote.authoritative_copy.validated{hash_match}`
 * (validateAuthoritativeCopy), `enote.registered` / `enote.registration.rejected` (registerENote), `enote.secured_party.set`
 * (setSecuredParty), `enote.registration.reversed` (reverseRegistration), `closing.audit_trail.received` (ingestAuditTrail),
 * `closing.execution_review.passed|failed` (recordExecutionReview), `recording.submitted` / `recording.resubmission.accepted`
 * (submitERecording), `recording.rejected{rejected_on}` (handleRecordingReject), `recording.paper_fallback{fallback_date}` /
 * `recording.county_receipt.confirmed` (dispatchPaperRecording / confirmCountyReceipt), `recording.confirmed` (confirmRecording),
 * `custody.paper_note.shipped{tracking_ref}` / `.received` (trackPaperNote). Referenced, not defined: `MERS_PROC_MOM_REGISTER_7`
 * (26.4), `REGZ_1026_23_RESCISSION_3SBD_GATE` (25.3), `TX_50A6_*` (26.1), `FNMA_B2_1_5_FIRST_PAYMENT_2M` (26.3), `SM_CPL_BEFORE_FUNDING_GATE` (24.4).
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_26_2(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // Row 1 / T1, T2: anchor = local date of the earlier of signing completion and the final seal; +1 federal business day, 23:59 ET; the acceptance closes it.
  o("MERS_PROC_ENOTE_REGISTER_1BD", { anchorField: "registration_anchor_date", offset: "+1 business_days_federal, 23:59 ET", satisfied: "`enote.registered`",
    why: "§26.2 timer table: deadline on `enote.tamper_sealed`, anchor 'the earlier of `signing_completed_at` and `tamper_sealed_at` (local date) — MERS eRegistry Procedures Manual Rel. 16.25: \"no later than one (1) business day after the final tamper sealing of the eNote\"; B8-8-02: \"no later than one business day after signing\"', '+1 `business_days_federal` (MERS defines no unit — SM applies the federal-holiday calendar as the conservative reading; end of that business day, 23:59 ET)', satisfied by '`enote.registered` (eRegistry acceptance with Controller = partner Org ID)', breach 'sev 1 → `officer`; loan flagged `emortgage_registration_late`' — tamperSeal puts `registration_anchor_date` / `registration_due_at` on the payload (T1: sealed Fri Nov 6 14:41 MST → due Mon Nov 9 23:59 ET; T2: Wed Nov 25 → Fri Nov 27, Thanksgiving excluded); registerENote emits the acceptance with `on_time`." });
  // Row 2: SM's operating target — +2 hours from the seal; the same acceptance satisfies it.
  o("SM_O72_ENOTE_SAME_DAY_REGISTER", { offset: "+2 hours", satisfied: "`enote.registered`",
    why: "§26.2 timer table: policy deadline on `enote.tamper_sealed`, anchor `tamper_sealed_at`, '+2 hours', satisfied by `enote.registered`, breach 'retry loop; escalation to `signing_officer` if the partner has not delegated registration; alert on-call' — decision 26.2-Q2: same-day registration is the operating target inside the MERS 1-BD limit (worked example 1: sealed 14:41, accepted 14:46 MST)." });
  // Row 3 / T6: condition-shaped — the eVault copy hash equals the platform seal; the validation event with hash_match=true closes it; registerENote refuses while closed.
  o("SM_O72_ENOTE_LOCATION_GATE", { evaluator: "26.2.enoteLocationGate", satisfied: "`enote.authoritative_copy.validated{hash_match=true}`",
    why: "§26.2 timer table: not_before_gate on `enote.tamper_sealed`, 'Authoritative Copy present in the Location eVault with digital signature validated against the eRegistry hash', satisfied by 'eVault verification event', breach 'registration request not sent' — MERS eRegistry Procedures Rel. 16.25: the Location Participant 'must have procedures in place that ensure it has received a copy of the eNote and has validated the eNote's Digital Signature'; validateAuthoritativeCopy emits `enote.authoritative_copy.validated{hash_match}` (T6: hash ≠ → gate closed, no Registration XML)." });
  // Row 4 / T7: Change Data naming SM as Secured Party before any warehouse advance on an eNote loan (27.1 references it).
  o("SM_O72_SECURED_PARTY_BEFORE_ADVANCE_GATE", { evaluator: "26.2.securedPartyGate", satisfied: "`enote.secured_party.set`",
    why: "§26.2 timer table: not_before_gate on `enote.registered`, '`Change Data` naming SM's Org ID as Secured Party accepted (27.1 references before funding a wet or dry advance on an eNote)', satisfied by `enote.secured_party.set`, breach '`warehouse.advance` refused for eNote loans' — securedPartyGate / assertSecuredPartyBeforeAdvance refuse with `secured_party_missing` (T7); setSecuredParty emits the satisfying event (worked example 1: Mon Nov 9 08:05 MST before the Thu Nov 12 dry-state advance)." });
  // Row 5: E-SIGN §101(c) consent scoped to the closing package for electronic closings; the reaffirmation at session start closes it.
  o("SM_O72_ESIGN_CONSENT_CLOSING_GATE", { trigger: "`closing.scheduled{closing_type∈{ron, ipen, hybrid}}`", evaluator: "26.2.esignConsentGate", satisfied: "`closing.consent.verified`",
    why: "§26.2 timer table: not_before_gate on '`closing.scheduled` (ron/ipen/hybrid)', anchor 'session start', 'valid `consents{kind=esign}` covering the closing package, not withdrawn, hardware/software demonstration on record; paper option offered', satisfied by `closing.consent.verified`, breach 'session cannot open; offer wet path' — 15 U.S.C. 7001(c)(1); A2-4.1-03 'Under no circumstances may a borrower be required to use electronic records'; esignConsentCheck / verifyConsent." });
  // Row 6 / T3, T4: the RON state matrix (Fannie Mae list + counsel confirmation, county, title, agent, notary, not TX 50(a)(6)); the eligibility event closes it.
  o("SM_O72_RON_STATE_AUTH_GATE", { trigger: "`closing.scheduled{closing_type=ron}`", evaluator: "26.2.ronStateAuthGate", satisfied: "`closing.eligibility.checked{check=ron_state_auth, result=eligible}`",
    why: "§26.2 timer table: not_before_gate on `closing.scheduled{ron}`, '`jurisdiction_rules.ron_authorized` and `fnma_listed` (or counsel-confirmed \"expressly permits\" law); county recorder accepts remotely notarized instruments; title underwriter takes no RON exception (CPL/commitment); notary commissioned and physically located in the state of the notarial act; not TX 50(a)(6)', satisfied by 'eligibility check event', breach 'RON refused; IPEN/hybrid/wet offered' — ronStateAuthCheck (T3: TX 50(a)(6) → `product_excluded`; T4: Georgia → `state_not_on_fnma_list` unless a counsel confirmation record exists); recordEligibilityCheck emits `closing.eligibility.checked{check=ron_state_auth, result}`." });
  // Row 7: an eclosing_eligibility row for the settlement agent/county matching the closing type; otherwise the closing type is downgraded.
  o("SM_O72_AGENT_ECLOSING_ELIGIBLE_GATE", { evaluator: "26.2.agentEclosingEligibleGate", satisfied: "`closing.eligibility.checked{check=agent_eclosing, result=eligible}`",
    why: "§26.2 timer table: not_before_gate on `closing.scheduled`, anchor 'session start', '`eclosing_eligibility` row for the settlement agent/county matching `closing_type`', satisfied by 'eligibility event', breach 'closing type downgraded' — agentEclosingEligible over the 24.4-vetted rows (ron_capable / ipen_capable / platforms); recordEligibilityCheck emits `closing.eligibility.checked{check=agent_eclosing, result}`." });
  // Row 8 / T8: armed by the last notarial act; the hash-verified audit trail closes it; 26.3's funding.authorize is refused meanwhile.
  o("SM_O72_AUDIT_TRAIL_BEFORE_FUNDING_GATE", { trigger: "`closing.notarial_act.completed{last=true}`", evaluator: "26.2.auditTrailBeforeFundingGate", satisfied: "`closing.audit_trail.received`",
    why: "§26.2 timer table: not_before_gate on '`closing.notarial_act.completed` (last)', 'tamper-sealed RON/eSign audit trail received and hash-verified; recording reference and retention custodian recorded', satisfied by `closing.audit_trail.received`, breach '`funding.authorize` (26.3) refused' — SEL-2026-05: the lender 'must also retain the RON audit trail as part of the electronic loan file'; completeNotarialAct{last=true}; ingestAuditTrail emits the satisfying event; assertAuditTrailOnFile refuses funding.authorize (T8)." });
  // Row 9: +4 hours from the last required signature within business hours (next creditor business morning for evening sessions); the review pass closes it.
  o("SM_O72_POST_SIGNING_REVIEW_4H", { offset: "+4 hours (rolled to the next creditor business day)", satisfied: "`closing.execution_review.passed`",
    why: "§26.2 timer table: policy deadline on '`closing.consummated` (the last required signature — the event this process emits; no separate `closing.signed` event exists)', anchor 'last signature', '+4 hours (business hours; next morning for evening sessions)', satisfied by `closing.execution_review.passed`, breach 'funding not authorized; `settlement_agent` escalation for defects' — signDocument emits `closing.consummated` at the final note signature (worked example 1: 14:26 MST, review passed 16:20); recordExecutionReview emits the pass/fail (T13: `instrument_altered` fails it)." });
  // Row 10 / T9: dry state / refinance — the security instrument's notarial act anchors it (record-after-signing, decision 26.2-Q3); purchase / wet state — `loan.funded` (26.3), computed by erecordSubmitDue from that event's date.
  o("SM_O72_ERECORD_SUBMIT_1BD", { trigger: "`closing.notarial_act.completed{recording_anchor=true}`", anchorField: "anchor_date", offset: "+1 business_days_creditor", satisfied: "`recording.submitted`",
    why: "§26.2 timer table: policy deadline on 'refinance/dry state: `closing.notarial_act.completed{closing_document_id = security instrument}` (record-after-signing default — decision 26.2-Q3); purchase/wet state: `loan.funded`', anchor 'event date', '+1 `business_days_creditor`', satisfied by '`recording.submitted` (eRecording accepted for processing) or `recording.paper_fallback` with courier tracking', breach 'escalation to `settlement_agent`; sev 2 at +3' — completeNotarialAct sets `recording_anchor=true` and `anchor_date` on the security instrument's act when recordingAnchorKind is notarial_act (T9: Fri Nov 6 → due Mon Nov 9; Tue Nov 10 breaches); submitERecording and dispatchPaperRecording both emit `recording.submitted` (channel erecording / paper)." });
  // Row 11 / T10: +2 creditor business days from the rejection's local date (Veterans Day excluded); the accepted corrected resubmission closes it; a paper fallback cancels it and starts row 12.
  o("SM_O72_RECORDING_REJECT_CURE_2BD", { anchorField: "rejected_on", offset: "+2 business_days_creditor", satisfied: "`recording.resubmission.accepted`",
    why: "§26.2 timer table: deadline on `recording.rejected`, anchor 'rejection time', '+2 `business_days_creditor`', satisfied by 'corrected resubmission accepted', breach 'sev 2 → `officer`; title gap-coverage claim watch' — handleRecordingReject puts `rejected_on` on the payload (T10: Mon Nov 9 10:30 → due Thu Nov 12, Wed Nov 11 Veterans Day not a creditor business day); submitERecording{resubmission} emits `recording.resubmission.accepted`." });
  // Row 12 / T10: +5 creditor business days from the fallback date to confirm county receipt.
  o("SM_O72_PAPER_FALLBACK_5BD", { anchorField: "fallback_date", offset: "+5 business_days_creditor", satisfied: "`recording.county_receipt.confirmed`",
    why: "§26.2 timer table: deadline on `recording.paper_fallback`, anchor 'fallback date', '+5 `business_days_creditor` to confirm county receipt', satisfied by 'county receipt evidence', breach 'sev 2; 26.4 trailing-doc timer continues' — dispatchPaperRecording puts `fallback_date` and the courier `tracking_ref` on the payload; confirmCountyReceipt emits `recording.county_receipt.confirmed`." });
  // Row 13 / T11: the settlement agent ships the original paper note by tracked overnight courier within one creditor business day of the signing date.
  o("SM_O72_PAPER_NOTE_HANDOFF_1BD", { anchorField: "consummation_on", offset: "+1 business_days_creditor", satisfied: "`custody.paper_note.shipped{tracking_ref present}`",
    why: "§26.2 timer table: deadline on '`closing.consummated{note_form=paper}` (wet or hybrid paper note)', anchor 'signing date', '+1 `business_days_creditor` for the settlement agent to ship the original note by tracked overnight courier to the custodian SM designates (default: the partner's Form 2017 FCC acting as SM's bailee — 26.4-Q1/27.1-Q5)', satisfied by '`custody.paper_note.shipped` with tracking', breach 'escalation to `settlement_agent`; funding hold in dry states; 26.4 receipt timer anchored here' — signDocument's `closing.consummated` carries `note_form` and `consummation_on` (T11: Wed Nov 18 → due Thu Nov 19); trackPaperNote{op=shipped} emits the event with `tracking_ref` and the settlement_agent → courier chain." });
}
