/**
 * §26.1 timer overrides (process-owned; applied after every section's so they win the merge — see
 * src/domain/bankruptcy/timers-14-1.ts for the pattern). One `reg.override(code, { trigger?, satisfied | evaluator,
 * anchorField?, offset?, why })` per 26.1 registry row whose trigger/satisfied column names an event the platform
 * spells differently or a condition the column grammar drops; `why` quotes the spec. A code the servicing spec
 * (sections 1–19) owns is never overridden here — reference it. Wired by src/domain/timer-overrides.ts.
 *
 * Emitters live in src/domain/closing/ops-26-1.ts (the `closer` runtime of the `title-closing` agent):
 * `closing.document_set.opened` (openDocumentSet), `closing.data_snapshot.taken` (takeClosingSnapshot),
 * `closing.documents.generated` (generateDocuments), `closing.document_qc.check{rule_code, result}` /
 * `closing.document_qc.passed` / `.failed` (recordDocumentQc), `closing.documents.released` (releaseDocumentSet),
 * `closing.instructions.sent` / `.acknowledged` (sendClosingInstructions / acknowledgeClosingInstructions),
 * `tx.home_equity_review.opened{is_50a6, f2_refinance, application_date, prior_50a6_closing_date}` (openTxHomeEquityReview),
 * `tx.notice_12day.delivered{t0, earliest_closing_date}` (recordTx12DayNotice), `tx.itemization.delivered{received_on}`
 * (recordTxItemization), `tx.f2_notice.delivered{notice_provided_date}` (recordTxF2Notice), `rescission.period.expired
 * {basis=tx_50a6, tx=true}` (expireTxRescission). Consumed, never redefined: `disclosure.cd.delivered/received/corrected`
 * (25.2), `closing.scheduled` / `closing.consummated` (26.2 — the consummated event carries the 26.1 profile flag
 * `tx_50a6`), `decision.issued` (23.3). Referenced, not defined: `REGZ_1026_23_RESCISSION_3SBD_GATE` (25.3),
 * `SM_O61_COMPLIANCE_PASS_CD_GATE` (25.1), `SM_TRUST_POA_REVIEW_GATE` / `SM_CPL_BEFORE_FUNDING_GATE` (24.4),
 * `MERS_PROC_MOM_REGISTER_7` (26.4), `MERS_PROC_ENOTE_REGISTER_1BD` (26.2), `FNMA_B2_1_5_FIRST_PAYMENT_2M` (26.3).
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_26_1(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // Inputs & triggers / timer table row 1: condition-shaped gate over the CTC facts; opened by the set, satisfied by the snapshot.
  o("SM_O71_DOC_GEN_GATE", { evaluator: "26.1.docGenGate",
    why: "§26.1 timer table: not_before_gate on `closing.document_set.opened`, '0 — generation requires: final CD delivered (`disclosure.cd.delivered`), `decision.issued{approval}` with PTD conditions cleared, `SM_TRUST_POA_REVIEW_GATE` open (24.4), `SM_O61_COMPLIANCE_PASS_CD_GATE` open (25.1), `locks.status=active` with expiry ≥ closing date', satisfied by `closing.data_snapshot.taken`, breach '`generateDocuments` refused' — evaluators-26-1.ts docGenGate over the five facts; takeClosingSnapshot refuses while it is closed and emits the satisfying event." });
  // Row 2 / T7, T8: the version test over every template of the set on the scheduled note date; the per-rule QC event satisfies it.
  o("SM_O71_TEMPLATE_VERSION_GATE", { evaluator: "26.1.templateVersionGate", satisfied: "`closing.document_qc.check{rule_code=DQC_TEMPLATE_VERSION, result=pass}`",
    why: "§26.1 timer table: not_before_gate on `closing.documents.generated`, anchor 'scheduled note date', 'every template's `mandatory_from ≤ note_date` and (`retired_after` null or ≥ note_date); all templates share one `revision_date` family (no version mixing)', satisfied by '`document_qc_checks{DQC_TEMPLATE_VERSION}=pass`', breach 'release refused; sev 2 → `officer` if a live template retired' — templateVersionCheck (ops-26-1.ts) is the evaluator; recordDocumentQc emits one `closing.document_qc.check{rule_code, result}` per rule (T7 revision_mix: Michigan 07/2021 + PUD rider 1/01; T8: VA 3047 May 2026 revision mandatory from 2026-07-01)." });
  // Row 3 / T14: all hard rules pass or are officer-waived; satisfied by the set-level pass event.
  o("SM_O71_DOC_QC_PASS_GATE", { evaluator: "26.1.docQcPassGate",
    why: "§26.1 timer table: not_before_gate on `closing.documents.generated`, 'all `document_qc_checks` pass (or waived by `officer` with reason)', satisfied by `closing.document_qc.passed`, breach 'release refused' — docQcPassGate over the checks; releaseDocumentSet refuses with SM_O71_DOC_QC_PASS_GATE_CLOSED and opens an `officer` escalation only when a waiver was requested (T14)." });
  // Row 4: the package is due one creditor business day before the signing start 26.2 schedules (worked example 1: released Thu Nov 5 for the Fri Nov 6 RON session).
  o("SM_O71_DOCS_TO_AGENT_1BD", { anchorField: "scheduled_at", offset: "−1 business_days_creditor",
    why: "§26.1 timer table: policy deadline on `closing.scheduled`, anchor 'scheduled signing start', '−1 `business_days_creditor` (documents and closing instructions delivered to the settlement agent/eClosing platform)', satisfied by `closing.documents.released`, breach 'warning to `closer`; reschedule proposal to 26.2' — 26.2's `closing.scheduled{closing_id, scheduled_at, closing_type, settlement_agent_party_id, notary_party_id}` carries the anchor; releaseDocumentSet emits the satisfying event." });
  // Row 5: acknowledgment mandatory for TX 50(a)(6) (B5-4.1-03), policy elsewhere.
  o("SM_O71_INSTRUCTIONS_ACK_GATE", { evaluator: "26.1.instructionsAckGate",
    why: "§26.1 timer table: not_before_gate on `closing.instructions.sent`, anchor 'signing start', 'acknowledgment by the settlement agent (mandatory for TX 50(a)(6) per B5-4.1-03; policy elsewhere)', satisfied by `closing.instructions.acknowledged`, breach '26.2 signing session may not open (TX); warning elsewhere' — instructionsAckGate closes only for a TX 50(a)(6) set without `acknowledged_at`; acknowledgeClosingInstructions emits the satisfying event." });
  // Row 6 / T4: T0 = later of submission and notice provided (mailed: 7 TAC §153.51 presumption); close on/after T0 + 12 calendar days; the 26.2 consummation event closes the row.
  o("TX_50A6_12DAY_CLOSING_GATE", { trigger: "`tx.notice_12day.delivered`", anchorField: "t0", offset: "+12 calendar_days", satisfied: "`closing.consummated`",
    why: "§26.1 timer table: not_before_gate on '`tx.notice_12day.delivered` and `application.received`', anchor '`T0 = max(application_submitted_date, notice_provided_date)`; if mailed, `notice_provided_date = mailed_date + 3 calendar days excluding Sundays and federal holidays` (7 TAC §153.51 presumption)', 'day 1 = T0 + 1 calendar day; closing allowed on or after day 12 = T0 + 12 `calendar_days`', satisfied by '`closing.consummated` date ≥ `earliest_closing_date`', breach '`consummate` refused; sev 1 if a signing opened earlier' — recordTx12DayNotice puts `t0` and `earliest_closing_date` on the payload (T4: submitted Mon Oct 5, e-delivered same day → Sat Oct 17; mailed → presumed Thu Oct 8 → Tue Oct 20); txConsummationCheck refuses an earlier consummation." });
  // Row 7 / T5: one §153.1(A) business day (= business_days_regz_specific) after the later receipt; a change re-anchors unless a §153.13(5)/(6) consent covers it.
  o("TX_50A6_ITEMIZATION_1BD_GATE", { anchorField: "received_on", offset: "+1 business_days_regz_specific", satisfied: "`closing.consummated`",
    why: "§26.1 timer table: not_before_gate on '`tx.itemization.delivered` (CD or separate itemization) and final-1003 copy delivered', anchor 'receipt date of the later of the two', '+1 business day (`business_days_regz_specific` — identical to 7 TAC §153.1's definition); … any fee/charge change after receipt re-anchors the gate unless an executed owner consent under 7 TAC §153.13(5) (bona fide emergency) or §153.13(6) (\"another good cause\", including the de minimis presumption of §153.13(6)(B) …) exists', satisfied by '`closing.consummated` date ≥ `earliest_itemization_closing_date`', breach '`consummate` refused' — recordTxItemization's `received_on` is the re-anchored receipt date (T5: CD Mon Nov 2 + $35 change Thu Nov 5 → gate opens Fri Nov 6; a Fri Nov 6 change without consent → Sat Nov 7; with the owner's de minimis consent Nov 6 stands)." });
  // Row 8: the review row is the trigger; the anniversary test is condition-shaped (no prior loan → open).
  o("TX_50A6_ONE_YEAR_GATE", { trigger: "`tx.home_equity_review.opened{is_50a6=true}`", evaluator: "26.1.txOneYearGate", satisfied: "`closing.consummated`",
    why: "§26.1 timer table: not_before_gate on '`tx_home_equity_reviews` opened', anchor `prior_50a6_closing_date`, '+1 year (first anniversary; `calendar_days` by anniversary date)', satisfied by 'closing date ≥ anniversary', breach '`generateDocuments` refused (`result=ineligible` until the date)' — openTxHomeEquityReview emits the review row's event with `prior_50a6_closing_date`; txOneYearRule (§50(a)(6)(M)(iii); worked example 2: prior closing Mar 3, 2025 → anniversary Mar 3, 2026 < closing)." });
  // Row 9: TX day 3 with the §153.25 Sunday/holiday extension; 26.3's `disburse` waits for the later of this and 25.3's TILA gate.
  o("TX_50A6_RESCISSION_3D_GATE", { trigger: "`closing.consummated{tx_50a6=true}`", satisfied: "`rescission.period.expired{basis=tx_50a6}`",
    why: "§26.1 timer table: not_before_gate on '`closing.consummated` (TX 50(a)(6))', anchor 'closing date', '+3 `calendar_days`; if day 3 is a Sunday or federal legal public holiday, extend to the next day that is neither (7 TAC §153.25); runs concurrently with `REGZ_1026_23_RESCISSION_3SBD_GATE` (25.3) — `disburse` waits for the later', satisfied by `rescission.period.expired{tx}`, breach '`disburse` refused' — 26.2's consummation event carries the 26.1 profile flag `tx_50a6`; expireTxRescission emits `rescission.period.expired{basis=tx_50a6, tx=true, expires_on}` (closing Fri Nov 6 → Mon Nov 9; Thu Nov 5 → Sun Nov 8 → Mon Nov 9)." });
  // Row 10: the notice clock arms on the review row for a 50(f)(2) refinance (the spec's `application.received` conditioned on that classification); scheduled by the earlier regz-specific count.
  o("TX_50F2_NOTICE_3BD", { trigger: "`tx.home_equity_review.opened{f2_refinance=true}`", anchorField: "application_date", offset: "+3 business_days_regz_specific",
    why: "§26.1 timer table: deadline on '`application.received` (refinance of a 50(a)(6) lien into a non-50(a)(6) loan)', anchor 'application submission date', '+3 business days — for §153.45 the unit is §153.1(B)'s general definition (`business_days_creditor`); SM schedules the notice by `business_days_regz_specific` whenever that yields the earlier date (conservative; the two differ only where a Saturday is counted)', satisfied by `tx.f2_notice.delivered`, breach 'sev 1 → `officer`; the loan cannot close as a 50(f)(2) refinance' — openTxHomeEquityReview{f2_refinance=true} carries `application_date`; txF2NoticeDue keeps the legal (creditor) date alongside; recordTxF2Notice emits the satisfying event." });
  // Row 11: +12 calendar days from the notice provided date (mailed: §153.45 presumption); closed by the consummation event.
  o("TX_50F2_12DAY_CLOSING_GATE", { anchorField: "notice_provided_date", offset: "+12 calendar_days", satisfied: "`closing.consummated`",
    why: "§26.1 timer table: not_before_gate on `tx.f2_notice.delivered`, anchor 'notice provided date (if mailed, mailed date + 3 calendar days excluding Sundays and federal legal public holidays — 7 TAC §153.45 presumption, same as §153.51)', '+12 `calendar_days`', satisfied by 'closing date ≥ notice date + 12', breach '`consummate` refused' — recordTxF2Notice's payload carries `notice_provided_date` and `earliest_closing_date`; txConsummationCheck refuses an earlier closing." });
  // Row 12: the existing 50(a)(6) loan's first anniversary, condition-shaped.
  o("TX_50F2_ONE_YEAR_GATE", { trigger: "`tx.home_equity_review.opened{f2_refinance=true}`", evaluator: "26.1.txF2OneYearGate", satisfied: "`closing.consummated`",
    why: "§26.1 timer table: not_before_gate on 'review opened', anchor 'closing date of the existing 50(a)(6) loan', 'first anniversary', satisfied by 'closing date ≥ anniversary', breach '`generateDocuments` refused' — §50(f)(2)(A) 'the refinance of the debt is not closed before the first anniversary of the date the extension of credit was closed'; txF2OneYearGate over {existing_50a6_closing_date, closing_date}." });
  // `REGZ_1026_19F1_CD_3SBD_GATE` is 25.2's (timers-25-2.ts: trigger `disclosure.cd.received{all_required=true}`, evaluator 25.2.cd3sbdGateOpen, satisfied by `disclosure.cd.consummated`) — referenced here, never overridden; ops-26-1.ts applyUpstreamEvent consumes the receipt date the set must honor (worked example 2: CD received Mon Nov 2 → earliest Thu Nov 5).
}
