/**
 * §26.3 timer overrides (process-owned; applied after every section's so they win the merge — see
 * src/domain/bankruptcy/timers-14-1.ts for the pattern). One `reg.override(code, { trigger?, satisfied | evaluator,
 * anchorField?, offset?, why })` per 26.3 registry row whose trigger/satisfied column names an event the platform
 * spells differently or a condition the column grammar drops; `why` quotes the spec. A code the servicing spec
 * (sections 1–19) owns is never overridden here — reference it. Wired by src/domain/timer-overrides.ts.
 *
 * Every 26.3 event carries `applicationId` (ops-26-3.ts `emit`) so these arm under origination context; the hour/minute
 * clocks anchor on the event instant (`occurredAt` = prepared_at / released_at / accepted_at). Referenced, never
 * redefined: `REGZ_1026_23_RESCISSION_3SBD_GATE`, `SM_O63_SATISFACTION_SWEEP`, `REGZ_1026_23D2_RESCISSION_REFUND_20`
 * (25.3), `TX_50A6_RESCISSION_3D_GATE` (26.1), `SM_WH_ADVANCE_CUTOFF_GATE` (27.1), the 24.4/24.5/24.6/23.3/22.x gates.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_26_3(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  o("FNMA_B2_1_5_FIRST_PAYMENT_2M", { trigger: "`funding.requested`", anchorField: "disbursement_date", evaluator: "26.3.firstPaymentTwoMonthsGate", satisfied: "`funding.conditions.evaluated{first_payment_2m=pass}`",
    why: "§26.3 timer table: not_before_gate (blocks `disburse`; re-evaluated on every date change) on '`funding.requested` and `funding.date.resynced`' (requestFunding / resyncDates append both with `disbursement_date`), anchor `disbursement_date` (scheduled, then actual); the offset is the C2-2-01 rule '`first_payment_date ≤ add_months(disbursement_date, 2)` (calendar months; day-of-month clamped to month end)' — condition-shaped, so the evaluator (firstPaymentTwoMonthsGate) decides; satisfied by '`FC_FIRST_PAYMENT_2M = pass`' — recordConditionsEvaluated carries the item status as `first_payment_2m`; breach: `disburse` refused; 26.1 re-draw of the note/first-payment letter data or interest-credit election (rule 3). Source recorded as C2-2-01 (the ownership-map code is kept because 25.3, 26.1, 26.2, 27.1 and 29.4 reference it)." });
  o("SM_O73_CONDITIONS_EVAL_2BH", { trigger: "`closing.execution_review.passed`", offset: "+2 hours", satisfied: "`funding.conditions.evaluated`",
    why: "§26.3 timer table: deadline (SLA) on '`closing.execution_review.passed` (dry) / `closing.scheduled` − 1 BD (wet)' (26.2 emits the trigger; the wet-state pre-signing run is scheduled by the 07:30 ET funding-calendar job), anchor 'event time', '+2 business hours (`business_days_creditor`, 08:00–18:00 local to the property)' — the grammar has no business-hour unit, so +2 clock hours inside the execution-review window is the conservative reading; satisfied by `funding.conditions.evaluated` (recordConditionsEvaluated); breach: sev 3; agent re-runs; `funding_approver` notified." });
  o("SM_O73_POST_RESCISSION_FUNDING_1BD", { satisfied: "`funding.wire.released`",
    why: "§26.3 timer table: deadline (policy; statutory in VA — see VA_55_1_902_REFI_DISBURSE_1BD) on `rescission.confirmed_not_rescinded` (25.3 confirmNotRescinded, whose occurredAt is the sweep instant after `rescission_expires_at`), '+1 `business_days_federal` (Fedwire day; the sweep completes 08:00 local — 25.3)' — fixture: expiry Tue Nov 10, sweep Wed Nov 11 (Veterans Day, Fedwire closed) → due Thu Nov 12; satisfied by `funding.wire.released` (releaseWire); breach: sev 2 → `funder` lead; borrower informed of the new date; per-diem/first-payment resync (resyncDates)." });
  o("SM_O73_WET_FUNDS_AT_TABLE_GATE", { evaluator: "26.3.wetFundsAtTableGate", satisfied: "`funding.wire.accepted`",
    why: "§26.3 timer table: not_before_gate (daily) on `closing.scheduled{wet}` (26.2), anchor 'signing start', 'wire released with value date = closing date by 10:00 local of the closing (release window opens after `funding_conditions` pre-signing subset passes)' — condition-shaped: wetFundsAtTableGate reads the pre-signing subset, the wire value date and the IMAD instant against signing start; satisfied by '`funding.wire.accepted` before signing start' (acceptWire; T8: IMAD 08:56 ET before the 10:05 ET session); breach: signing proceeds only with the settlement agent's written agreement to hold documents in escrow pending funds (`escalation` to `settlement_agent`); sev 2." });
  o("SM_O73_WIRE_CUTOFF_1300ET", { offset: "same day, 13:00 ET", satisfied: "`funding.wire.released`",
    why: "§26.3 timer table: not_before_gate (daily window; references 27.1 `SM_WH_ADVANCE_CUTOFF_GATE`) on `funding.authorized` (authorizeFunding), 'release by 13:00 ET for same-day value; later → next `business_days_federal`' — a same-day wall-clock deadline (wireCutoff rolls the value date and appends `funding.date.resynced` when release is late); satisfied by `funding.wire.released` (releaseWire); breach: `scheduled_funding_date` rolls; `funding.date.resynced`; borrower/settlement agent notified." });
  o("SM_O73_DUAL_CONTROL_RELEASE_1H", { satisfied: "`funding.wire.released`",
    why: "§26.3 timer table: deadline (SLA) on `funding.wire.prepared` (recordWirePrepared; occurredAt = prepared_at), anchor prepared_at, '+1 hour (business hours)'; satisfied by '`funding.wire.released` or `funding.held`' — the grammar takes one pattern; releaseWire appends the first and a hold (holdFunding → `funding.held`) cancels the release path in domain code; breach: sev 2 → backup `funding_approver`; never auto-release (the agent has no release tool — prepareWire op=release needs the funding_approver)." });
  o("SM_O73_WIRE_ACCEPT_30M", { satisfied: "`funding.wire.accepted{imad}`",
    why: "§26.3 timer table: deadline on `funding.wire.released` (releaseWire; occurredAt = released_at), anchor released_at, '+30 minutes'; satisfied by `funding.wire.accepted{imad}` (acceptWire carries `imad`); breach: bank contact (wireAcceptOverdue → `funding.wire.bank_contacted`); if rejected → correct and re-release under a new wire_id with a new four-eyes check; never a second wire (T7)." });
  o("SM_O73_AGENT_RECEIPT_CONFIRM_2H", { satisfied: "`funding.agent_receipt.confirmed`",
    why: "§26.3 timer table: deadline on `funding.wire.accepted` (acceptWire; occurredAt = accepted_at), anchor accepted_at, '+2 hours (Fedwire hours)'; satisfied by 'settlement agent's receipt confirmation via a verified channel (`funds_received_by_agent_at`)' — confirmAgentReceipt appends `funding.agent_receipt.confirmed{funds_received_by_agent_at, channel}`; breach: trace request to the bank (OMAD); no second wire without `officer` (prepareWire NO_SECOND_WIRE)." });
  o("SM_O73_DISBURSEMENT_CONFIRM_1BD", { anchorField: "value_date", satisfied: "`funding.disbursement.confirmed`",
    why: "§26.3 timer table: deadline on `funding.wire.accepted` (acceptWire carries `value_date`), anchor 'value date', '+1 `business_days_creditor`'; satisfied by '`funding.disbursement.confirmed` (final settlement statement or recording/disbursement confirmation)' — confirmDisbursement appends it with `source` and then `loan.funded`; breach: sev 2 → `settlement_agent` escalation; day 2: recall/return demand and CPL notice to the title underwriter (`officer`)." });
  o("SM_O73_FUNDS_RETURN_2BD", { trigger: "`funding.cancelled{after_wire_accepted=true}`", satisfied: "`funding.wire.returned`",
    why: "§26.3 timer table: deadline on '`funding.cancelled` after `wire_accepted`' — cancelFunding stamps `after_wire_accepted` so only a cancellation with funds already accepted by the beneficiary bank arms the clock, anchor 'cancel time', '+2 `business_days_federal`'; satisfied by '`funding.wire.returned` matched to the advance' (returnWire carries `matched_advance_id`); breach: sev 1 → `officer` (SM and partner); CPL claim; 27.1 defect." });
  o("SM_O73_UNWIND_STEPS_5BD", { satisfied: "`funding.unwind.completed`",
    why: "§26.3 timer table: deadline on `funding.unwind.opened` (openUnwind; occurredAt = opened_at), anchor opened_at, '+5 `business_days_creditor` for every non-money step (void/reverse/release); money steps follow 25.3's 20-day clock' (unwindSteps puts `refund_due_at` on the money steps — REGZ_1026_23D2_RESCISSION_REFUND_20 governs them); satisfied by `funding.unwind.completed` (completeUnwind under officer sign-off when money moved after disbursement); breach: sev 1 → `officer`." });
  o("SM_O73_DATE_RESYNC", { trigger: "`funding.date.change_requested`", offset: "same day", satisfied: "`funding.date.resynced`",
    why: "§26.3 timer table: 'event (not a timer)' on 'any change to `scheduled_funding_date` or `disbursement_date`' — resyncDates appends `funding.date.change_requested{old, new}` and, in the same unit of work, recomputes `earliest_funding_date`, per-diem, `interest_mode`, `first_payment_latest_allowed_date`, `lpi_date`, re-runs `FNMA_B2_1_5_FIRST_PAYMENT_2M`, 24.4 payoff good-through (payoffGoodThroughGate), 24.5 effective-date (hazardEvidenceGate) and 22.3 VVOE checks, then appends `funding.date.resynced` (T14: Nov 12 → Nov 13, prepaid 18 × $93.97 = $1,691.46; 25.2 asked whether a corrected CD is due)." });
  o("VA_55_1_902_REFI_DISBURSE_1BD", { anchorField: "expires_on", offset: "+1 business_days_federal", satisfied: "`funding.wire.released`",
    why: "§26.3 timer table: deadline (jurisdiction override, VA) on `rescission.period.expired` (25.3 expirePeriod, payload `expires_on`), anchor `rescission_expires_at` (its local date `expires_on`), '+1 business day (Va. Code § 55.1-902: \"within one business day after the expiration of the rescission period required under the federal Truth in Lending Act\"; §55.1-900 defines no \"business day\" — read 2026-09-11 — so SM applies `business_days_federal` as the conservative calendar)' — T9: expiry Tue Nov 10 → Nov 11 Fedwire holiday → due Thu Nov 12; satisfied by '`funding.wire.released` with funds at the settlement agent' (releaseWire); breach: sev 1 → `officer`; statutory exposure logged (vaDisbursementCompliance). Armed for every rescindable loan; the funder cancels it outside VA (jurisdiction_rules.wet_settlement_statute)." });
}
