/**
 * Registry overrides for Section 7 (statements, notices, consent, privacy)
 * timers whose spec rows are prose, or whose "Satisfied by" prose the column
 * grammar reads too loosely (a bare `notice.sent` would let any notice on the
 * loan close a deadline). Each override cites the row it encodes. The grammar
 * carries one satisfying pattern per row; where a row lists alternatives the
 * override names the spec's own event family (`privacy.annual*`) or the
 * primary act and says so.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applyNoticeTimerOverrides(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // ---- 7.1 periodic statements / 1098 -------------------------------------
  o("REGZ_1026_41E5IV_BK_TRANSITION_1", { anchorField: "next_statement_due_by", offset: "+1 months (one statement cycle — comment 41(a)(2)-1: the statement cycle is monthly even for bi-weekly loans)", satisfied: "`statement.sent{single_statement_exemption_used=false}`",
    why: "§7.1 timer table: `bankruptcy.status.changed` → anchor 'next `statement_due_by` after the event', offset '1 statement cycle (single-statement exemption)', satisfied by '`statement.sent` in the compliant variant on the following cycle' (§1026.41(e)(5)(iv)(B); 7.1-T5: Oct 5 petition → Nov cycle skippable → Dec cycle statement_due_by 2026-11-20). The grammar read '1 statement cycle' as calendar day 1." });
  o("FNMA_D2_2_03_PAYMENT_REMINDER_20", { anchorField: "due_date", offset: "by the 20th, 23:59 local", satisfied: "`statement.sent{reminder_panel=true}`",
    why: "§7.1 timer table: `payment.cycle.unpaid_day16` → reminder due 20th calendar day 23:59 local of the unpaid due date's month, satisfied by '`statement.sent` with `reminder_panel=true` dated ≤ 20th' (D2-2-03) — a statement without the panel never closes it; the row's alternative (`NTC_FNMA_D2_2_03_PAYMENT_REMINDER` sent, `notice.sent{template=…}`) is the held-statement path the grammar cannot carry as a second pattern (ops.reminderDecision names the satisfying event per path)." });
  o("IRS_1098_EFURNISH_ACCESS_1015", { offset: "Oct 15 following year", satisfied: "`tax_form.1098.access_verified{available=true}`", why: "§7.1 timer table: electronic 1098 must stay accessible through Oct 15 of the following year, 'portal availability check daily' (IRS Pub. 1179) — ops.form1098Cycle names the daily check's event." });
  o("IRS_6050H_1098_FILE_0331", { offset: "Mar 31", why: "§7.1 timer table: `tax_year.closed` → e-file by Mar 31 (IRC §6050H)." });
  o("IRS_6050H_1098_FURNISH_0131", { offset: "Jan 31", why: "§7.1 timer table: `tax_year.closed` → furnish by Jan 31, a calendar deadline (7.1-T13: 'furnished by Jan 31, 2027', a Sunday — no business-day roll) (IRC §6050H)." });
  // ---- 7.2 ARM adjustments -------------------------------------------------
  o("SM_ARM_DUAL_CALC_VERIFY_T0", { evaluator: "7.2.dualCalculationMatches", why: "§7.2 timer table: second engine result must match to the cent before `arm.adjustment.verified`." });
  // ---- 7.3 ARM notices -----------------------------------------------------
  o("REGZ_1026_20D_ESTIMATE_INDEX_15BD", { evaluator: "7.3.indexRecentEnoughForEstimate", why: "§7.3 timer table: index `effective_date` ≥ disclosure date − 15 `business_days_servicer` (§1026.20(d) estimate rule)." });
  o("SM_ARM_INITIAL_SEPARATE_DOC_GATE", { trigger: "`notice.render_requested{template=NTC_REGZ_20D_ARM_INITIAL}`", evaluator: "7.3.separateDocumentEnforced", why: "§7.3 timer table: `notice_templates.separate_document = true` enforced by the composer (own PDF; own first page; may share envelope) on the (d) notice `NTC_REGZ_20D_ARM_INITIAL` (spec/registry/notices.json)." });
  // ---- 7.4 E-SIGN consent --------------------------------------------------
  o("ESIGN_7001C_CONSENT_GATE", { evaluator: "7.4.esignConsentActiveForEveryRecipient", why: "§7.4 timer table: requires `consents(kind=esign, scope ∋ class, status=active)` for every intended recipient (15 U.S.C. §7001(c))." });
  o("ESIGN_7001C1D_RECONSENT_GATE", { trigger: "`hw_sw_requirements.changed{material=true}`", offset: "until consent.esign.reconsented", why: "§7.4 timer table: material hardware/software change → all consents flagged `reconsent_required`; electronic delivery blocked until (C) re-demonstrated (§7001(c)(1)(D))." });
  o("IRS_1098_ECONSENT_GATE", { evaluator: "7.4.irsEstatementConsentActive", why: "§7.4 timer table: requires `consents(kind=irs_estatement, status=active)` (Treas. Reg. §1.6050H-2)." });
  o("SM_EMAIL_BOUNCE_SUSPECT_1BD", { trigger: "`notice.bounced{reason=hard bounce}`", satisfied: "`notice.mailed{satisfies_timer=true}`",
    why: "§7.4 timer table: '`email.bounced` (hard) on a notice' → within +1 `business_days_servicer` 'paper copy mailed; consent `suspect`; re-verification invite' (rule 8). NoticeService records the hard bounce as `notice.bounced{reason=hard bounce}` and the same-day paper fallback's proof of mailing as `notice.mailed{satisfies_timer=true}` (the fallback delivery satisfies the regulatory timer); the consent flag and invitation are the domain's side effects (ops.availabilityEmailBounce)." });
  // ---- 7.5 privacy ---------------------------------------------------------
  o("REGP_1016_8_REVISED_NOTICE_GATE", { trigger: "`privacy_policy.changed{new_sharing=true}`", offset: "until privacy.revised_notice.optout_window_elapsed", satisfied: "`privacy.revised_notice.optout_window_elapsed`",
    why: "§7.5 timer table: 'no sharing under the new practice until the revised notice and any opt-out period are complete', satisfied by '`privacy.revised_notice.sent` (+ opt-out window elapsed)' (§1016.8; worked example: mailed July 1, opt-out through July 31, sharing Aug 1) — the gate closes on the end of the 30-day window that runs from the send date (privacy.policyChange), not on the send itself." });
  o("SM_PARTNER_PRIVACY_ATTESTATION_0131", { trigger: "`period.year_end`", offset: "Jan 31", why: "§7.5 timer table: annual cycle — partner privacy attestation by Jan 31." });
  // ---- 7.6 payoff statements ----------------------------------------------
  o("SM_PAYOFF_STMT_ACCURACY_GATE", { trigger: "`notice.render_requested{template=NTC_REGZ_36C3_PAYOFF_STMT}`", evaluator: "7.6.payoffStatementAccuracy", why: "§7.6 timer table: 16.1 calc version current; no pending unposted payments/reversals older than the cut-off; ARM adjustment (7.2) effective before good-through reflected — on the payoff statement `NTC_REGZ_36C3_PAYOFF_STMT` (spec/registry/notices.json)." });
  // ---- pseudo-trigger rows -----------------------------------------------------
  o("SM_ARM_INDEX_CAPTURE_T45", { trigger: "`arm.schedule.row_created`", why: "§7.2 timer table: `arm_schedule` row → index capture at `change_date` − `lookback_days` (45)." });
  o("REGZ_1026_20C_ADJ_NOTICE_NOT_BEFORE_120", { trigger: "`arm.schedule.row_created`", satisfied: "`arm.adjustment.notice_window_opened{kind=c}`", why: "§7.2 timer table: `arm_schedule` row → not before `first_new_payment_due` − 120 (§1026.20(c)(2)); 'gate opens' is the schedule's window-opened event (arm.noticeWindow)." });
  o("REGZ_1026_20C_ADJ_NOTICE_60", { trigger: "`arm.schedule.row_created`", satisfied: "`notice.sent{template=NTC_REGZ_20C_ARM_ADJ}`", why: "§7.2 timer table: `arm_schedule` row → '`notice.sent` (`NTC_REGZ_20C_ARM_ADJ`)' by `first_new_payment_due` − 60 (§1026.20(c)) — the (c) notice itself, not any notice on the loan." });
  o("REGZ_1026_20C_FREQ_ADJ_NOTICE_25", { trigger: "`arm.schedule.row_created{frequent_adjuster=true}`", satisfied: "`notice.sent{template=NTC_REGZ_20C_ARM_ADJ}`", why: "§7.2 timer table: `arm_schedule` row → the (c) notice `NTC_REGZ_20C_ARM_ADJ` by −25 for frequent adjusters / pre-2015 short look-backs (§1026.20(c)(2))." });
  o("REGZ_1026_20C_FIRST_ADJ_ESTIMATE_25", { satisfied: "`notice.sent{template=NTC_REGZ_20C_ARM_ADJ}`", why: "§7.2 timer table: `loan.boarded` → the (c) notice `NTC_REGZ_20C_ARM_ADJ` by −25 when the first adjustment falls within 60 days of consummation and the (d) disclosure was an estimate (§1026.20(c)(2))." });
  o("FNMA_C2_1_02_BUYDOWN_STEP_NOTICE_90", { satisfied: "`notice.sent{template=NTC_FNMA_C2_1_02_BUYDOWN_STEP_90}`", why: "§7.2 timer table: '`notice.sent` (`NTC_FNMA_C2_1_02_BUYDOWN_STEP_90`)' 90 days before the buydown step (C-2.1-02)." });
  o("FNMA_F1_01_CONVERSION_NOTICE_25", { satisfied: "`notice.sent{template∈NTC_REGZ_20C_ARM_ADJ,NTC_FNMA_C2_1_02_RATE_CHANGE}`", why: "§7.2 timer table: `arm.conversion.elected` → borrower notice 25 days before the new payment (F-1-01): the (c) notice when the conversion changes rate and payment (comment 20(c)-3), otherwise the C-2.1-02 rate/payment-change notice." });
  o("REGZ_1026_20D_INITIAL_NOTICE_NOT_BEFORE_240", { trigger: "`arm.schedule.row_created{initial=true}`", satisfied: "`arm.initial_notice.window_opened`", why: "§7.3 timer table: `arm_schedule` (initial) → not before −240 (§1026.20(d)); 'gate opens' is the spec's `arm.initial_notice.window_opened` at `first_new_payment_due − 240` (7.3 inputs; arm.initialNoticeWindow)." });
  o("REGZ_1026_20D_INITIAL_NOTICE_210", { trigger: "`arm.schedule.row_created{initial=true}`", satisfied: "`notice.sent{template=NTC_REGZ_20D_ARM_INITIAL}`", why: "§7.3 timer table: `arm_schedule` (initial) → '`notice.sent` (`NTC_REGZ_20D_ARM_INITIAL`)' by −210 (§1026.20(d)); the row's alternative `arm.initial_notice.transferor_evidenced` is the transfer-in status path (ops.transferInInitialNotice)." });
  // ---- satisfaction events (spec "Satisfied by" prose → event patterns) ----
  o("REGZ_1026_41E6_CHARGEOFF_NOTICE_30", { satisfied: "`notice.sent{template=NTC_REGZ_41E6_CHARGEOFF_SUSPENSION}`", why: "§7.1 timer table: `NTC_REGZ_41E6_CHARGEOFF_SUSPENSION` sent (§1026.41(e)(6))." });
  o("REGZ_1026_41E3IV_COUPON_DELQ_NOTICE", { satisfied: "`notice.sent{template=NTC_REGZ_41E3IV_COUPON_DELQ_NOTICE}`", why: "§7.1 timer table: `NTC_REGZ_41E3IV_COUPON_DELQ_NOTICE` sent (§1026.41(e)(3)(iv))." });
  o("REGP_1016_4A1_INITIAL_NOTICE_REASONABLE_30", { satisfied: "`notice.sent{template=NTC_REGP_1016_4_INITIAL}`", why: "§7.5 timer table: '`notice.sent` (`NTC_REGP_1016_4_INITIAL`)' within 30 days of the partner's MSR acquisition / an assumption (§1016.4(a)(1), (e)) — the initial privacy notice itself." });
  o("REGP_1016_5A_ANNUAL_NOTICE_12M", { satisfied: "`privacy.annual*`", why: "§7.5 timer table: '`notice.sent` (`NTC_REGP_1016_5_ANNUAL`) or `privacy.annual_exception.applied` with attestation evidence' — both are the spec's `privacy.annual_sent` / `privacy.annual_exception.applied` loan events (7.5 outputs; privacy.annualCycle), matched by the family pattern (§1016.5(a), (e))." });
  o("REGP_1016_5E2II_ANNUAL_AFTER_CHANGE_100", { satisfied: "`notice.sent{template=NTC_REGP_1016_5_ANNUAL}`", why: "§7.5 timer table: '`notice.sent` (annual)' within 100 days of a change that ends the exception without a revised notice (§1016.5(e)(2)(ii))." });
  o("SM_PRIVACY_COPY_ON_REQUEST_5BD", { satisfied: "`notice.sent{template∈NTC_REGP_1016_4_INITIAL,NTC_REGP_1016_5_ANNUAL,NTC_REGP_1016_8_REVISED}`", why: "§7.5 timer table: `privacy_notice.copy_requested` → a copy of the current privacy notice (`NTC_REGP_*`) within 5 `business_days_servicer` (policy)." });
  o("SM_PAYOFF_DELAY_ACK_2BD", { satisfied: "`notice.sent{template=NTC_PAYOFF_REQUEST_ACK_DELAY}`", why: "§7.6 timer table: `NTC_PAYOFF_REQUEST_ACK_DELAY` sent (reasonable-time path)." });
}
