// 22.1 Document intake, classification, extraction, integrity/freshness checks, and the borrower needs-list loop
// spec/sections/22-documents-credit-income-assets-liabilities-identity-and-frau/22-1-document-intake-classification-extraction-integrity-freshnes.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("22.1-T1: (four-month gate, refinance fixture) Given scheduled note date Fri Nov 6, 2026 and a bank statement with `period_end` Jun 30, 2026, when freshness is computed, then `expires_at = Oct 30, 2026`, `freshness_status = expired`, and `assertGateOpen('FNMA_B1_1_03_CREDIT_DOCS_4M')` fails for any decision relying on it; a statement with `period_end` Jul 31, 2026 yields `expires_at = Nov 30, 2026` and `fresh`.", { todo: true });
test("22.1-T2: (consecutive statements rule) Given July and August 2026 statements in the file and note date Dec 7, 2026, when the gate is evaluated, then only the August statement (`expires_at = Dec 31, 2026`) is tested and the gate is open even though the July statement expired Nov 30.", { todo: true });
test("22.1-T3: (paystub floor) Given initial application date Mon Oct 5, 2026, when a paystub with pay date Fri Sept 4, 2026 is classified, then `FNMA_B3_3_2_01_PAYSTUB_30D_GATE` is not satisfied and a request for \"most recent paystub (dated on/after Sept 5, 2026) with year-to-date earnings\" is opened; a paystub dated Fri Oct 2, 2026 with YTD satisfies it.", { todo: true });
test("22.1-T4: (paystub floor not re-based) Given the same application amended on Mon Oct 26, 2026, when the floor is recomputed, then it remains Sept 5, 2026.", { todo: true });
test("22.1-T5: (tax-year table) Given application Oct 5, 2026 and disbursement Fri Jan 15, 2027, when `FNMA_B1_1_03_TAX_YEAR_GATE` is evaluated, then the 2025 return is required and a Form 4868 extension path is rejected; given disbursement Nov 12, 2026 instead, then the 2024 return is acceptable only with extension evidence, the tax-liability comparison and an IRS no-transcript response recorded.", { todo: true });
test("22.1-T6: (arithmetic integrity) Given a paystub with `gross_ytd = 11,250,000` cents and Medicare YTD 150,000 cents, when the battery runs, then `arithmetic = warn` (deviation 13,125 cents > tolerance 816 cents), the document is `flagged`, and a source-obtained VOE/validation report is requested before 22.3 may use the income; with Medicare YTD 163,125 cents the check passes.", { todo: true });
test("22.1-T7: (running balance) Given a bank statement whose transactions do not reconcile to the ending balance, when the battery runs, then `running_balance = fail`, `integrity_status = failed`, an `escalation{role=underwriting_reviewer}` with a 1 `business_days_creditor` SLA is created, and 22.6 opens a fraud case candidate.", { todo: true });
test("22.1-T8: (needs-list SLA with holiday) Given three requests opened Wed Oct 7, 2026, when the borrower uploads Sat Oct 10, 2026, then reminders were sent Oct 9 only, `document.received{request_id}` is logged Oct 10 (satisfying `SM_NEEDS_LIST_BORROWER_RESPONSE_5`), and `SM_NEEDS_LIST_REVIEW_1BD` is due Tue Oct 13, 2026 (Columbus Day Oct 12 closed in calendar `creditor`).", { todo: true });
test("22.1-T9: (DU validation waiver) Given a DU employment validation outcome `validated` for borrower 1 with employer Acme, when the finding is received, then the open `form_1005_voe`/`paystub` requests for that borrower and employer are `waived_by = du_validation` with the submission number, and no needs-list notice mentions them.", { todo: true });
test("22.1-T10: (TRID ordering) Given an application whose LE has not been delivered, when DU opens verification conditions, then the needs-list notice is queued and released only after `disclosure.le.delivered`.", { todo: true });
test("22.1-T11: (e-mail authentication) Given an e-mail attachment from a sender failing DMARC alignment, when ingested, then the document is quarantined (`integrity_status = failed`, `sender_authentication = fail`), no request is satisfied, and the borrower receives a portal-upload prompt.", { todo: true });
test("22.1-T12: (retention transitions) Given a loan funded Thu Nov 12, 2026, when `loan.funded` is processed, then every file document carries `fnma_loan_file_life_plus_4y`, the ATR evidence set also carries `regz_atr_3y`, and a withdrawn application notified Mon Nov 2, 2026 carries `regb_25m` with purge eligibility on Dec 2, 2028.", { todo: true });
