// 22.2 Credit report ordering, credit-score model and merge rules, analysis, freezes/disputes, inquiries, and pre-closing refresh (undisclosed-debt monitoring)
// spec/sections/22-documents-credit-income-assets-liabilities-identity-and-frau/22-2-credit-report-ordering-credit-score-model-and-merge-rules-an.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("22.2-T1: (representative score) Given Borrower A scores 742/751/760 and Borrower B 698/712/705, when computed, then applicable scores are 751 and 705 and `representative_score = 705` with `representative_score_borrower_id = B`.", { todo: true });
test("22.2-T2: (single freeze) Given Borrower B's Experian file is frozen and EFX 698 / TU 705 are returned on a requested tri-merge, when parsed, then the report is `usable`, B's applicable score is 698, `representative_score = 698`, and `credit.freeze.detected` is emitted with a borrower notice offering a lift and re-pull.", { todo: true });
test("22.2-T3: (two freezes) Given freezes at EXP and TU, when parsed, then the report is `freeze_blocked`, `submitDu` is refused, and after `credit.freeze.lifted` on Wed Oct 7, 2026 the re-pull supersedes the Oct 5 report with `expires_at = Feb 7, 2027`.", { todo: true });
test("22.2-T4: (expiry gate) Given `report_date` Oct 5, 2026 and scheduled note date Mon Feb 8, 2027, when `assertGateOpen('FNMA_B1_1_03_CREDIT_REPORT_EXPIRY_4M')` runs, then it fails (expires Feb 5, 2027), `SM_CREDIT_EXPIRY_WARN_21` fired Jan 15, 2027, and a re-pull is scheduled no later than Jan 29, 2027.", { todo: true });
test("22.2-T5: (model invariant) Given `applications.score_model = vantagescore_4`, when an order for Borrower B requests Classic FICO codes, then the order is rejected before transmission; and at delivery `SFC 067` is asserted present.", { todo: true });
test("22.2-T6: (collections by occupancy) Given collections of $3,200.00 and $2,150.00, when occupancy is second home, then a PTF condition \"pay $5,350.00 in full prior to or at closing\" is proposed; when occupancy is one-unit principal residence, then no payoff condition is proposed.", { todo: true });
test("22.2-T7: (waiting period date basis) Given a Chapter 7 discharge Nov 20, 2022 and disbursement Nov 19, 2026, when evaluated, then the loan is not eligible; with disbursement Nov 20, 2026 the lender-confirmed basis passes while DU's report-date test (Oct 5, 2026) is recorded as failing with the written confirmation.", { todo: true });
test("22.2-T8: (inquiry \u2192 new debt) Given qualifying income 1,350,000 cents, obligations 513,000 cents, an inquiry dated Sept 12, 2026 and a borrower-reported new $612.40 monthly payment, when recorded, then `application_liabilities` gains the debt, DTI moves 38.0% \u2192 42.5% (+4.5 points), and 23.1's tolerance check returns \"resubmission required\"; with a $150.00 payment DTI moves to 39.1% and the check returns \"no resubmission required\" while the final submission still includes the debt.", { todo: true });
test("22.2-T9: (pre-closing refresh window) Given consummation Fri Nov 6, 2026, when the refresh is dated Tue Nov 3, 2026 with all alerts resolved, then `SM_CREDIT_REFRESH_PRECLOSE_GATE` is open; dated Mon Nov 2, 2026 \u2192 not open.", { todo: true });
test("22.2-T10: (UDM verified new debt) Given a UDM alert \"new tradeline\" received Thu Oct 29, 2026 that the borrower confirms as a $410.00 installment, when triaged as `verified_new_debt`, then 22.5 recalculates DTI, 23.1 evaluates B3-2-10, and the relief record notes the debt was disclosed before closing.", { todo: true });
test("22.2-T11: (credit-report fee) Given the LE not yet delivered, when the credit-report fee is charged Mon Oct 5, 2026, then the charge is permitted (\u00a71026.19(e)(2)(i)(B)) and the `fee_items` row has `tolerance_class = zero` under \"Services You Cannot Shop For\"; any other fee on that date is refused (21.4 gate).", { todo: true });
test("22.2-T12: (disclosure data) Given the report received Oct 5, 2026, when scores are computed, then 21.3 receives per-borrower payloads containing only that borrower's scores, key factors, range, date and the CRA identity.", { todo: true });
