// 22.3 Income and employment verification (documentation standards, DU validation service, Income Calculator, IRS transcripts, self-employment, rental/other income, VVOE timing)
// spec/sections/22-documents-credit-income-assets-liabilities-identity-and-frau/22-3-income-and-employment-verification-documentation-standards-d.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("22.3-T1: (VVOE window, refinance) Given note date Fri Nov 6, 2026, when the window is computed on calendar `creditor`, then `window_start = Fri Oct 23, 2026`; a VVOE contacted Thu Oct 22 is `within_window = false` and Fri Oct 23 is `true`.", { todo: true });
test("22.3-T2: (VVOE window across Veterans Day, purchase) Given closing Wed Nov 18, 2026, when computed, then `window_start = Tue Nov 3, 2026` (Nov 11 excluded) and the 15-business-day paystub alternative floor is Tue Oct 27, 2026.", { todo: true });
test("22.3-T3: (self-employment verification window) Given note date Nov 6, 2026, when `FNMA_B3_3_1_04_SE_VERIFY_120` is evaluated, then a Secretary-of-State/licensing verification dated Thu Jul 9, 2026 passes and Wed Jul 8, 2026 fails; for closing Nov 18 the floor is Tue Jul 21, 2026.", { todo: true });
test("22.3-T4: (trending, increasing) Given overtime prior year 1,080,000 cents and YTD 855,000 cents over 9 months, when calculated, then `trend = increasing` and `monthly_qualifying_cents = 92,143`.", { todo: true });
test("22.3-T5: (trending, decreasing with stabilization) Given prior year 1,440,000 cents and YTD 855,000 over 9 months with a documented flat run since Apr 1, 2026 totaling 570,000 over 6 months, when calculated, then `trend = decreasing`, `stabilized_since = 2026-04-01`, and `monthly_qualifying_cents = 95,000`; with no stabilization evidence the result is 0 with reason `not_stabilized`.", { todo: true });
test("22.3-T6: (hourly base) Given $32.50/hour and 40 guaranteed hours, when calculated, then `monthly_qualifying_cents = 563,333`; given hours of 28\u201344 with no guaranteed minimum, then the source is reclassified `base_hourly_variable` and R3 applies.", { todo: true });
test("22.3-T7: (Social Security gross-up) Given $2,000.00 SS retirement on the borrower's own record with no tax return, when calculated, then `nontaxable_cents = 30,000`, `gross_up_cents = 7,500`, qualifying 207,500 cents, `continuance_basis = retirement_own_record`.", { todo: true });
test("22.3-T8: (child support continuance) Given $800.00 child support with the child turning 18 on Mar 3, 2029 and note date Nov 6, 2026, when evaluated, then `FNMA_B3_3_1_01_CONTINUANCE_3Y` fails (end Mar 3, 2029 < Nov 6, 2029) and the income is excluded with a written reason; with a child born after Nov 6, 2011 it passes and qualifying = 100,000 cents.", { todo: true });
test("22.3-T9: (rental 75% and experience) Given Form 1007 gross rent $2,400.00 and PITIA $1,650.00 on a purchase, when the borrower has 365 Fair Rental Days on the 2025 Schedule E, then +15,000 cents is added to income; with no management history, `offset_only = true` and 0 is added; with PITIA $2,150.00, 35,000 cents is added to liabilities in both cases.", { todo: true });
test("22.3-T10: (ADU cap) Given total qualifying income 900,000 cents and ADU rent yielding 300,000 cents net, when applied, then ADU income is capped at 270,000 cents on a purchase/LCOR and excluded on a cash-out refinance.", { todo: true });
test("22.3-T11: (Close by Date) Given a DU employment validation with Close by Date Nov 20, 2026, when consummation moves to Nov 23, then `FNMA_B3_2_02_DU_CLOSE_BY_GATE` breaches, a supplemental report or VVOE (window Nov 6\u201323) is required, DU is resubmitted, and the employment relief record is updated.", { todo: true });
test("22.3-T12: (4506-C validity and exemption) Given a 4506-C signed Mon Oct 5, 2026, when validity is computed, then `valid_until = Tue Feb 2, 2027`; given Borrower B's only income is DU-validated, then no 4506-C is required for B and the `consummate` gate passes with A's form alone.", { todo: true });
test("22.3-T13: (Reg B no-discount) Given a part-time base income of $1,800.00/month with 24 months history, when calculated, then the formula id equals the full-time base formula and `regb_check = pass`; any attempt to apply a factor < 1.0 is rejected by the engine.", { todo: true });
test("22.3-T14: (employment offer option 2) Given a purchase closing Nov 18, 2026 with a non-contingent offer starting Mon Feb 15, 2027 and 6 months PITIA reserves, when evaluated, then option 2 is available (start \u2264 Feb 16, 2027) and SFC 707 is queued; with a start of Wed Feb 17, 2027 option 2 is refused.", { todo: true });
test("22.3-T15: (Income Calculator ceiling) Given a calculator result of 812,500 cents for a Schedule C borrower, when the agent's Form 1084 analysis yields 830,000 cents, then qualifying is 812,500 cents and the Findings Report id is attached; a manual override above the ceiling is rejected.", { todo: true });
