// 22.5 Liabilities, debt-to-income, qualifying payment, and debts paid at closing
// spec/sections/22-documents-credit-income-assets-liabilities-identity-and-frau/22-5-liabilities-debt-to-income-qualifying-payment-and-debts-paid.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("22.5-T1: (refinance baseline) Given the refinance fixture inputs (P&I 340,262; taxes 50,000; hazard 12,000; liabilities 53,737; income 1,200,000), when computed, then `obligations = 455,999`, `dti_bps = 3,800`, display 38.00%, `du_cap_ok = true`.", { todo: true });
test("22.5-T2: (undisclosed debt) Given a UDM alert on Tue Oct 20, 2026 verified as a $450.00 auto payment, when `liabilities.changed` fires, then `dti_bps = 4,175`, 23.1's check returns `resubmission_required` (`B3_2_10_DTI_45_OR_3PT`, delta 375 bps), `SM_DU_RESUBMIT_SLA_1BD` due Wed Oct 21, 2026; given a $300.00 payment instead, then `dti_bps = 4,050` and `within_tolerance`.", { todo: true });
test("22.5-T3: (alimony election) Given alimony of $800.00/month under a decree ending 2031, when the income-reduction option is elected, then `income = 1,120,000`, `dti_bps = 4,071`; when not elected, then `obligations = 535,999`, `dti_bps = 4,467`; given the obligation is child support, then the election is refused and `dti_bps = 4,467`.", { todo: true });
test("22.5-T4: (ARM qualifying rates) Given a 5/6 ARM at 5.875% (cap 2%), index 4.30%, margin 2.75%, when computed, then `qualifying_rate_bps = 7,875` and `pi = 406,039`; given a 7/6 ARM at 6.000% not HPML, then 6,000 bps and `pi = 335,748`; given the same loan flagged HPML by 23.4, then 7,050 bps and `pi = 374,452`; given a 2-1 buydown on the fixed purchase loan, then the qualifying P&I is 257,034, not 205,706.", { todo: true });
test("22.5-T5: (student loans) Given a $24,000.00 balance with $0 on the report and no documentation, when the basis is selected, then `qualifying_payment = 24,000` (`student_1pct_balance`) with the amortizing alternative 27,288 recorded; given an IDR statement showing $0.00, then `student_idr_zero_documented` and payment 0; given the report shows $180.00, then 18,000 (`credit_report`).", { todo: true });
test("22.5-T6: (purchase DTI and 50% cap) Given the purchase fixture inputs, when computed, then `obligations = 372,581`, `dti_bps = 4,544`; given added child support of $600.00 with 13 payments remaining, then `dti_bps = 5,275`, `FNMA_B3_6_02_DU_DTI_50_GATE` fails and 23.2 receives `dti.du_cap.exceeded`; given 9 payments remaining and `significantly_affects = false`, then excluded and `dti_bps = 4,544`.", { todo: true });
test("22.5-T7: (debt paid at closing) Given a $1,180.00 revolving balance planned `pay_off_at_closing`, when the plan is evaluated, then the payment (4,500) is excluded, `funds_to_verify` in 22.4 rises by 118,000 cents, no account-closure condition is opened, and `FNMA_B3_6_07_PAYOFF_FUNDS_GATE` opens only when the settlement statement (Wed Nov 18, 2026) shows the payoff; given the settlement statement omits it, then the gate blocks `funding.authorized` and the DTI is recomputed with the payment included.", { todo: true });
test("22.5-T8: (installment \u2264 10 payments) Given an installment loan with 9 payments of $312.37 remaining as of Fri Nov 6, 2026, when evaluated, then excluded (`le_10_payments`); given the closing moves to Mon Oct 26, 2026 with 11 remaining, then re-included; given `significantly_affects = true` (payment 16% of income), then included regardless.", { todo: true });
test("22.5-T9: (IRS installment agreement) Given an approved agreement at $300.00/month with payment evidence and no lien indicated in Franklin County, when evaluated, then included with `payment_basis = irs_agreement` and `dti_bps = 4,910` on the purchase fixture; given only the pending application, then the same inclusion; given a Notice of Federal Tax Lien in the county, then `FNMA_B3_6_05_IRS_AGREEMENT_GATE` routes to 24.4 and the loan cannot finalize until the lien is paid or subordinated.", { todo: true });
test("22.5-T10: (HELOC and revolving 5%) Given a HELOC with a $12,000.00 balance and an interest-only payment of $74.00 on the statement, then 7,400 included; given a HELOC with no required payment, then 0 and no imputed payment; given a card with $3,000.00 and no reported minimum, then 15,000.", { todo: true });
test("22.5-T11: (paid by others / business debt) Given a co-signed auto loan with 12 months' canceled checks from the co-signer and no lates, then excluded; given one 30-day late in the 12 months, then included; given a business loan in the borrower's name with 12 months' company checks but 22.3's cash-flow analysis did not deduct the payment, then included.", { todo: true });
test("22.5-T12: (final consistency) Given CD-final P&I 340,262 and the final DU submission on Tue Nov 3, 2026, when `dti.computed{final}` runs, then its liability set equals the DU submission's and `FNMA_B3_6_01_LIABILITY_RECALC_GATE` is open; given a new liability discovered Thu Nov 5, then the gate closes until a new final version and 23.1 resubmission complete before Fri Nov 6.", { todo: true });
