// 22.6 Identity, fraud, OFAC/AML, Red Flags, occupancy/undisclosed-REO, and non-arm's-length screening
// spec/sections/22-documents-credit-income-assets-liabilities-identity-and-frau/22-6-identity-fraud-ofac-aml-red-flags-occupancy-undisclosed-reo.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("22.6-T1: (IAL2 gate) Given two borrowers on the purchase fixture (Mon Oct 19, 2026), when Borrower A passes document + liveness + face match and Borrower B's session is inconclusive, then `SM_IDENTITY_IAL2_GATE` blocks `submitDu`, `SM_IDENTITY_RETRY_2BD` is due Wed Oct 21, 2026, and a supervised remote session passing Oct 20 opens the gate.", { todo: true });
test("22.6-T2: (SSN discrepancy \u2192 SSA validation \u2192 SFC 162) Given DU returns an SSN issue-date/age message for Borrower B (SSN issued 2019, DOB 1988) that documents cannot resolve, when CBSV returns a match with no death indicator, then `ssn.validated{cbsv_web_service}`, the loan is eligible, and because DU's edit persists `sfc_162_required = true` flows to 29.3; given CBSV returns no match, then `not_validated`, the loan is ineligible and 21.6 receives the decline with `underwriting_reviewer` approval.", { todo: true });
test("22.6-T3: (legal presence at note date) Given Borrower B's EAD expires 2027-03-31 and the note date is Wed Nov 18, 2026, then `FNMA_B2_2_02_LEGAL_PRESENCE_GATE` is open; given the EAD expired 2026-11-01 with a pending renewal receipt and partner policy `legal_presence.pending_renewal_accepted = false`, then the gate blocks `consummate` and a condition opens.", { todo: true });
test("22.6-T4: (OFAC rejected transaction) Given a confirmed SDN match on the seller's LLC member on Wed Nov 4, 2026, when `ofac.match.confirmed{rejected}` fires, then `fraud_hold` blocks `issueCD`/`consummate`/`funding.authorized`, 28.4's \u00a7501.604 timer computes a due date of Thu Nov 19, 2026 (10 `business_days_federal`, Veterans Day excluded), the record carries `retention_class = ofac_records_10y`, and no borrower notice mentions the screening result.", { todo: true });
test("22.6-T5: (OFAC false positive and list version) Given a potential match on \"Maria Lopez\" with a different DOB and nationality, when resolved, then `false_positive_resolved` with both identifiers recorded; given a new SLS list version is published Wed Nov 4 after the Nov 3 screen, then `OFAC_SDN_SCREEN_GATE` requires a re-screen before the Nov 5 pre-consummation check and again before funding Thu Nov 12 if another version appears.", { todo: true });
test("22.6-T6: (fraud alert contact) Given an initial fraud alert with a phone number on the Oct 5, 2026 report, when the AI-voice contact is completed Tue Oct 6 with the borrower's confirmation, then `FCRA_605A_H_ALERT_CONTACT_GATE` is open before the Oct 7 conditional approval; given an extended alert with \"contact by mail only\", then an AI-voice contact does not satisfy the gate and a mailed confirmation with a returned signed statement does.", { todo: true });
test("22.6-T7: (address discrepancy) Given a notice of address discrepancy on Borrower A, when the agent matches the application address to the driver's license and a utility statement, then `address_discrepancy.resolved` and the confirmed address is queued for furnishing at boarding (30.4).", { todo: true });
test("22.6-T8: (occupancy score) Given the purchase-variant signals (rent needed from the retained condo with no lease +3, smaller house +2, DP-3 landlord quote +3), when scored, then 8 \u2192 `inconsistent`, `SM_OCCUPANCY_REO_GATE` blocks CTC and an investigation opens; given only the smaller-house signal (+2), then `consistent`.", { todo: true });
test("22.6-T9: (undisclosed REO) Given a $210,000 mortgage tradeline with no REO entry and a MERS MIN vested in the borrower, when the borrower documents an inherited rental, then `resolved_added_to_reo`, 22.5 adds PITIA $1,640.00, 23.2 recounts financed properties (2), 22.4 adds 2% of the other UPB to reserves, and 23.1 resubmits; given the borrower denies ownership and the deed shows a same-name relative, then `resolved_not_borrower` with the deed as evidence.", { todo: true });
test("22.6-T10: (non-arm's-length new construction) Given a borrower employed by the builder buying a newly constructed second home, when assessed, then `eligible = false` (principal residence only) and the loan is declined or restructured only if the true occupancy is primary with evidence; given the parents' existing home with a gift of equity, then eligible, `value_acceptance_blocked = true` (24.1 orders an appraisal) and 22.4 excludes the gift of equity from the IPC test.", { todo: true });
test("22.6-T11: (investigation \u2192 SAR anchors) Given an altered paystub confirmed Thu Oct 22, 2026 and the investigation concluded Fri Oct 30 with a reasonable basis for misrepresentation, when `sar.candidate.prepared` is sent to the `bsa_officer` by Fri Nov 6 (`SM_SAR_PACKAGE_5BD`), then 28.4's `BSA_1029_320_SAR_30` is due Sun Nov 29, 2026 and `FNMA_A3_4_03_FRAUD_SELF_REPORT_30` Nov 29; given no subject can be identified, then the outer limit is Tue Dec 29, 2026; the borrower-facing decline names \"information provided cannot be verified\" and contains no SAR reference.", { todo: true });
test("22.6-T12: (Red Flags SLA and program log) Given a suspicious-document red flag detected Fri Oct 23, 2026 16:30 MST, when no response is recorded by Mon Oct 26 end of day, then `RED_FLAGS_681_RESPONSE_1BD` breaches (sev 3) and the event appears in the annual ITPP report with its response time.", { todo: true });
test("22.6-T13: (guardrails) Given an adverse-action draft generated after a fraud investigation, when scanned, then any reference to \"SAR\"/\"FinCEN\" is rejected before 21.6 renders the notice; given a request to use `applicant_demographics` fields in the occupancy model, then the tool call is refused and logged.", { todo: true });
