/**
 * §22.6 timer overrides (process-owned; applied after every section's so they win the merge — see
 * src/domain/bankruptcy/timers-14-1.ts for the pattern). One `reg.override(code, { trigger?, satisfied | evaluator,
 * anchorField?, offset?, why })` per 22.6 registry row whose trigger/satisfied column names an event the platform
 * spells differently or a condition the column grammar drops; `why` quotes the spec. A code the servicing spec
 * (sections 1–19) owns is never overridden here — reference it. Wired by src/domain/timer-overrides.ts.
 * The events named here are appended by src/domain/verification/ops-22-6.ts (through src/app/tools/section22-6.ts).
 * Referenced rows — `BSA_1029_320_SAR_30` / `FNMA_A3_4_03_FRAUD_SELF_REPORT_30` / `OFAC_501_60x` (28.4 owns; 22.6 emits
 * their triggers `fraud.suspicious.determined{initial_detection_at}`, `fnma.fraud.reasonable_basis{reasonable_basis_at}`,
 * `ofac.transaction.rejected` / `ofac.property.blocked` as the hand-off and consumes `sar.filed` etc. on the return path)
 * and `FNMA_B1_1_03_CREDIT_DOCS_4M` (22.1 owns) — are never overridden here.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_22_6(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // R1 / T1: a gate over every borrower's identity level, satisfied by the last borrower's identity.verified (all_borrowers_verified=true).
  o("SM_IDENTITY_IAL2_GATE", { trigger: "`application.received`", evaluator: "22.6.identityIal2Gate", satisfied: "`identity.verified{all_borrowers_verified=true}`",
    why: "§22.6 timer table: 'not_before_gate' on `application.received`, offset 'every borrower `identity.verified{ial2_remote_doc_biometric or better}` with an unexpired ID and data match before `submitDu` (first casefile) and re-confirmed (`valid_until ≥ note date`) before `consummate`', satisfied by '`identity.verified` for all borrowers', breach 'blocks `submitDu`; inconclusive → alternative method within `SM_IDENTITY_RETRY_2BD`' — evaluators-22-6.ts `22.6.identityIal2Gate` (ops-22-6 identityIal2Gate); recordIdentityResult emits identity.verified{level, all_borrowers_verified}; T1: A passes Oct 19, B inconclusive → gate closed until B's supervised remote pass Oct 20." });
  // R1 / T1: +2 business_days_creditor from the inconclusive session; the second-method session (supervised remote / in-person notary) satisfies it whatever its outcome (a failure goes to investigation).
  o("SM_IDENTITY_RETRY_2BD", { satisfied: "`identity.second_method.resulted`",
    why: "§22.6 timer table: 'deadline', trigger `identity.inconclusive`, anchor 'event time', '+2 `business_days_creditor`', satisfied by 'second-method result', breach 'sev 3 → `human_agent` assisted session; unresolved → investigation' — recordIdentityResult emits identity.inconclusive{retry_due} and identity.second_method.resulted{method, outcome} for a supervised_remote / in_person_notary session; T1: inconclusive Mon Oct 19, 2026 → due Wed Oct 21, 2026." });
  // R2 / T2: the resolution ladder — documents, else SSA validation (CBSV/eCBSV/SSA-89); ssn.validated carries the method and sfc_162_required; not_validated → ineligible → 21.6.
  o("FNMA_B2_2_01_SSN_VALIDATION_GATE", { trigger: "`ssn.discrepancy.detected`", evaluator: "22.6.ssnValidationGate", satisfied: "`ssn.validated`",
    why: "§22.6 timer table: 'not_before_gate', trigger '`ssn.discrepancy.detected` (DU/LD/credit inconsistency)', offset 'discrepancy resolved with documents, else SSA validation (CBSV/eCBSV/SSA-89) with a `match`; `sfc_162_required` recorded when a discrepancy persists after SSA validation', satisfied by '`ssn.validated` or `resolved_internally`', breach 'blocks `issueCD`/`submitDelivery`; `not_validated` → ineligible → 21.6' (B2-2-01) — resolveSsnDocumentarily emits ssn.validated{method=not_required, resolution=resolved_internally}; recordCbsvResult emits ssn.validated{method=cbsv_web_service, sfc_162_required} or ssn.validation.failed{eligible=false}." });
  // R3 / T3: legal_presence.assessed arms for LPR / non-permanent residents; legal_presence.established (assessment = legally_present) opens it; the anchor is the scheduled note date the assessment carries.
  o("FNMA_B2_2_02_LEGAL_PRESENCE_GATE", { trigger: "`legal_presence.assessed{status_declared∈{non_permanent_resident, lawful_permanent_resident}}`", evaluator: "22.6.legalPresenceGate", anchorField: "scheduled_note_date", satisfied: "`legal_presence.established`",
    why: "§22.6 timer table: 'not_before_gate', trigger '`legal_presence.assessed{non_permanent_resident or lpr}`', anchor `scheduled_note_date`, offset 'evidence in file; `evidence_expires_on ≥ note date` or renewal/extension evidence; assessment `legally_present`', satisfied by '`legal_presence_records.assessment = legally_present`', breach 'blocks `consummate`; `not_established` → 21.6 with `underwriting_reviewer` (Reg B §1002.6(b)(7) rationale required)' (B2-2-02) — assessLegalPresence emits legal_presence.assessed{status_declared, assessment, expires_before_note_date} and legal_presence.established when legally_present; T3: EAD 2027-03-31 ≥ note date Wed Nov 18, 2026 → open; expired 2026-11-01 with pending_renewal_accepted=false → closed, condition opens." });
  // R4 / T4–T5: a repeating gate — every party clear / false-positive-resolved against the latest SLS version; party.screened{all_parties_clear=true} satisfies the instance; a new list version or a party change re-opens it (rescreenRequired).
  o("OFAC_SDN_SCREEN_GATE", { trigger: "`application.received`", evaluator: "22.6.ofacScreenGate", satisfied: "`party.screened{all_parties_clear=true}`",
    why: "§22.6 timer table: 'not_before_gate (repeating)', trigger '`application.received`, every party added/changed, `closing.scheduled`', anchor 'consummation', offset 'every party `clear`/`false_positive_resolved` against a list version published ≤ 1 `business_days_federal` before the screen; final re-screen ≤ 1 `business_days_creditor` before consummation (refinance fixture: Thu Nov 5, 2026; purchase: Tue Nov 17, 2026) and again before `funding.authorized` if a list update is published in between', satisfied by '`party.screened{clear}` for all parties', breach '`match_true` → `fraud.hold.placed`, transaction rejected/property blocked, hand-off to 28.4' (31 CFR 501) — recordPartyScreening emits party.screened{result, list_version, all_parties_clear}; resolveOfacMatch emits ofac.false_positive.resolved / ofac.match.confirmed{rejected|blocked} + ofac.transaction.rejected / ofac.property.blocked (28.4's triggers) + fraud.hold.placed." });
  // R5 / T6: arms on 22.2's credit.fraud_alert.detected; only a contact that meets §1681c-1(h) (specified number, or the extended alert's designated method) is fraud_alert.contact.completed; other attempts are fraud_alert.contact.attempted.
  o("FCRA_605A_H_ALERT_CONTACT_GATE", { trigger: "`credit.fraud_alert.detected`", evaluator: "22.6.fraudAlertContactGate", satisfied: "`fraud_alert.contact.completed`",
    why: "§22.6 timer table: 'not_before_gate', trigger '`credit.fraud_alert.detected` (22.2)', offset 'initial/active-duty alert: reasonable-belief procedures + contact at the specified number (or reasonable steps) before `decision.issued{approval}`; extended alert: contact in person or by the consumer's designated method', satisfied by `fraud_alert.contact.completed`, breach 'blocks `decision.issued{approval}` and `submitDu` for new casefiles; unreachable after 3 attempts over 5 `business_days_creditor` → NOIA path (21.6)' (15 U.S.C. 1681c-1(h)) — 22.2's detectFraudAlerts emits credit.fraud_alert.detected{borrower_id, kind, contact_phone}; recordFraudAlertContact emits fraud_alert.contact.completed when contactSatisfiesGate holds; T6: AI-voice contact at the specified number Tue Oct 6 opens the gate before the Oct 7 conditional approval; an AI-voice call does not satisfy an extended 'contact by mail only' alert, a mailed confirmation with the returned signed statement does." });
  // §1022.82 / T7: the notice of address discrepancy is 22.2's credit.identity_mismatch.detected{fields ∋ address}, which intakeUpstreamSignal turns into address_discrepancy.detected; the (c)(2) resolution satisfies it.
  o("REGV_1022_82_ADDRESS_DISCREPANCY_GATE", { trigger: "`address_discrepancy.detected`", evaluator: "22.6.addressDiscrepancyGate", satisfied: "`address_discrepancy.resolved`",
    why: "§22.6 timer table: 'not_before_gate', trigger 'address-discrepancy notice on the credit report', offset 'reasonable belief formed by one of the (c)(2) methods; confirmed address queued for furnishing at boarding (30.4/8.x)', satisfied by `address_discrepancy.resolved`, breach 'blocks `decision.issued{approval}`' (12 CFR 1022.82) — intakeUpstreamSignal emits address_discrepancy.detected from 22.2's credit.identity_mismatch.detected{fields ∋ address}; resolveAddressDiscrepancy emits address_discrepancy.resolved{confirmed_address, matched_sources, furnish_at_boarding=true}." });
  // R6 / T12: +1 business_days_creditor from the detection timestamp the event carries; the recorded response satisfies it; a breach is sev 3 and shows in the ITPP annual report with its response time.
  o("RED_FLAGS_681_RESPONSE_1BD", { anchorField: "detected_at", satisfied: "`red_flag.responded`",
    why: "§22.6 timer table: 'deadline (policy under the ITPP)', trigger `red_flag.detected`, anchor `detected_at`, '+1 `business_days_creditor`', satisfied by `red_flag.responded`, breach 'sev 3 → agent owner; repeated breaches reported in the annual ITPP report' (16 CFR 681.1(d)(2)(iii)) — logRedFlag emits red_flag.detected{event_id, category, detected_at, response_due_on}; respondRedFlag emits red_flag.responded{response, response_hours, within_sla}; T12: detected Fri Oct 23, 2026 16:30 MST → due Mon Oct 26; no response by end of day → breached (sev 3)." });
  // Fraud tool: a report for every borrower/party with every high-severity alert dispositioned and refreshed ≤ 10 business_days_creditor before consummation; fraud_tool.cleared is the `screening_clear` the column names.
  o("SM_FRAUD_TOOL_CLEAR_GATE", { trigger: "`application.received`", evaluator: "22.6.fraudToolClearGate", satisfied: "`fraud_tool.cleared`",
    why: "§22.6 timer table: 'not_before_gate', trigger '`application.received`; refresh before CTC', offset 'fraud report run for every borrower/party; every high-severity alert dispositioned; refresh ≤ 10 `business_days_creditor` before consummation', satisfied by '`screening_clear`', breach 'blocks `CTC` (23.3 `CTC_NO_OPEN_INVESTIGATION`)' — recordFraudReport emits fraud_tool.report.received{high_open} and fraud_tool.cleared{screening_clear=true} on a clean run; dispositionFraudAlert emits fraud_tool.alert.dispositioned and fraud_tool.cleared when the last high alert is cleared with evidence." });
  // R7–R8 / T8–T9: occupancy consistent (or explanation resolved) and REO clear / resolved; reconcileOccupancyReo emits occupancy_reo.cleared when both hold — the 'events' the column names.
  o("SM_OCCUPANCY_REO_GATE", { trigger: "`application.received`", evaluator: "22.6.occupancyReoGate", satisfied: "`occupancy_reo.cleared`",
    why: "§22.6 timer table: 'not_before_gate', trigger '`application.received`, `valuation.received`, `disclosure.cd.prepared`', offset '`occupancy_assessments.conclusion ∈ {consistent}` (or `needs_explanation` resolved) and `reo_discovery_checks.status ∈ {clear, resolved_*}`', satisfied by 'events', breach 'blocks `CTC`; DU resubmission via 23.1 when occupancy/REO data change' — assessOccupancy emits occupancy.assessed{conclusion, risk_score}; discoverReo / resolveReoDiscrepancy emit reo.discrepancy.detected / .resolved{status}; reconcileOccupancyReo emits occupancy_reo.cleared; T8: signals +3 +2 +3 = 8 → inconsistent → gate closed, investigation opens." });
  // R9 / T10: arms when a relationship exists; the eligible assessment (existing property, or new construction with occupancy = primary) is non_arms_length.eligible.
  o("FNMA_B2_1_3_01_NON_ARMS_LENGTH_GATE", { trigger: "`non_arms_length.assessed{relationship≠none}`", evaluator: "22.6.nonArmsLengthGate", satisfied: "`non_arms_length.eligible`",
    why: "§22.6 timer table: 'not_before_gate', trigger '`non_arms_length.assessed{relationship ≠ none}`', offset 'existing property → eligible; new construction with builder/developer/seller relationship → `occupancy = primary` required; gift of equity → 24.1 blocks value acceptance', satisfied by '`eligible = true`', breach 'restructure (occupancy cannot be changed to fit — that is misrepresentation) or decline via 21.6' (B2-1.3-01) — assessNonArmsLength emits non_arms_length.assessed{relationship, eligible, value_acceptance_blocked} and non_arms_length.eligible when eligible; T10: builder-employed borrower, new construction, second home → eligible=false; parents' existing home with a gift of equity → eligible, value_acceptance_blocked=true." });
  // R10 / T11: +10 business_days_creditor from the opening timestamp; the conclusion satisfies it (fixture: opened Thu Oct 22, 2026 → due Thu Nov 5, 2026).
  o("SM_FRAUD_INVESTIGATION_10BD", { anchorField: "opened_at", satisfied: "`investigation.concluded`",
    why: "§22.6 timer table: 'deadline (policy)', trigger `investigation.opened`, anchor `opened_at`, '+10 `business_days_creditor` (fixture: opened Thu Oct 22, 2026 → due Thu Nov 5, 2026)', satisfied by `investigation.concluded`, breach 'sev 2 → `bsa_officer` notified; the SAR \"initial detection\" anchor is the conclusion date, so the review itself is time-boxed' — openInvestigation emits investigation.opened{opened_at, due_on}; concludeInvestigation emits investigation.concluded{conclusion, sar_candidate, sar_detection_date}." });
  // R10 / T11: +5 business_days_creditor from sar_detection_date (the conclusion date); the package sent to the bsa_officer satisfies it; 28.4's BSA_1029_320_SAR_30 runs from the same date (concludeInvestigation emits its trigger fraud.suspicious.determined{initial_detection_at}).
  o("SM_SAR_PACKAGE_5BD", { trigger: "`investigation.concluded{sar_candidate=true}`", anchorField: "sar_detection_date", satisfied: "`sar.candidate.prepared`",
    why: "§22.6 timer table: 'deadline (policy)', trigger '`investigation.concluded{sar_candidate=true}`', anchor `sar_detection_date`, '+5 `business_days_creditor`', satisfied by '`sar.candidate.prepared` → `escalation{bsa_officer}`', breach 'sev 1 → `officer`; 28.4's `BSA_1029_320_SAR_30` (+30 `calendar_days` from `sar_detection_date`; +60 if no subject) governs filing' (31 CFR 1029.320(b)(3)) — prepareSarPackage emits sar.candidate.prepared{filing_due_on, outer_limit_on, sent_to=bsa_officer}; T11: concluded Fri Oct 30, 2026 → package by Fri Nov 6; SAR due Sun Nov 29 (Tue Dec 29 without a subject)." });
}
