/**
 * §22.5 timer overrides (process-owned; applied after every section's so they win the merge — see
 * src/domain/bankruptcy/timers-14-1.ts for the pattern). One `reg.override(code, { trigger?, satisfied | evaluator,
 * anchorField?, offset?, why })` per 22.5 registry row whose trigger/satisfied column names an event the platform
 * spells differently or a condition the column grammar drops; `why` quotes the spec. A code the servicing spec
 * (sections 1–19) owns is never overridden here — reference it. Wired by src/domain/timer-overrides.ts.
 * Every event named here is appended by src/domain/verification/ops-22-5.ts (through src/app/tools/section22-5.ts):
 * `liability.declared{liability_type}` (declareLiability), `liability.included{payment_basis}` (includeLiability /
 * recordExclusion), `liabilities.changed{tolerance_result}` (notifyTolerance), `dti.computed{stage, du_cap_ok,
 * checked_against_du, remaining_months_recomputed}` (recordDti), `debt_payoff.planned{scheduled_note_date}` /
 * `debt_payoff.evidenced` (planPayoff / evidencePayoff), `liabilities.finalized{du_cap_ok}` (finalizeLiabilities);
 * `document.classified{doc_class}` is 22.1's (classifyDocument); `closing.scheduled{scheduled_note_date}` is 26.2's.
 * Referenced, never redefined: `SM_CREDIT_REFRESH_PRECLOSE_GATE` (22.2 — 22.5 recomputes on `verified_new_debt`),
 * `FNMA_B3_3_1_01_CONTINUANCE_3Y` (22.3), `REGZ_1026_43_QM_DETERMINATION_GATE` (23.4 — the ATR record includes this
 * process's liability set), `FNMA_B3_2_10_DU_FINAL_MATCH_GATE` (23.1). `SM_DU_RESUBMIT_SLA_1BD`: the registry resolves
 * the code to 22.5's row (first origination definition; 23.1 restates it with `du.resubmission.required` → `du.submitted`),
 * so the SLA is armed here by the hand-off event 22.5 emits and retired by the DTI version reconciled to the resubmission.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_22_5(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // R9 / T12: a consistency gate over the final DTI version, opened by the version whose liability set equals the current included set and the final DU submission's; a new liability closes it until a new final version exists.
  o("FNMA_B3_6_01_LIABILITY_RECALC_GATE", { trigger: "`liabilities.changed`", evaluator: "22.5.liabilityRecalcGate", satisfied: "`dti.computed{stage=final}`",
    why: "§22.5 timer table: 'not_before_gate', trigger 'every `liabilities.changed` after `decision.issued` and `closing.scheduled`', offset 'latest `dti_calculations.stage ∈ {final}` with `liability_ids` = current included set, `qp_id` = current terms, computed after the last liability/term change and before `consummate`', satisfied by '`dti.computed{final}` reproduced by the final DU submission (23.1 `FNMA_B3_2_10_DU_FINAL_MATCH_GATE`)', breach 'blocks `consummate` — sev 2; agent recomputes and hands 23.1 the tolerance decision' — evaluators-22-5.ts `22.5.liabilityRecalcGate` (ops-22-5 liabilityRecalcGate); recordDti emits `dti.computed{stage}`; T12: CD-final P&I 340,262 and the final DU submission Tue Nov 3, 2026; a liability discovered Thu Nov 5 closes the gate until a new final version and 23.1 resubmission complete before Fri Nov 6 (B3-6-01: 'the lender must recalculate the borrower's debt-to-income ratio')." });
  // R1 / T6: DU's 50 % ceiling evaluated on every version; the terminal `liabilities.finalized{du_cap_ok=true}` (dti.final with du_cap_ok) retires the instance.
  o("FNMA_B3_6_02_DU_DTI_50_GATE", { trigger: "`dti.computed`", evaluator: "22.5.duDti50Gate", satisfied: "`liabilities.finalized{du_cap_ok=true}`",
    why: "§22.5 timer table: 'not_before_gate', trigger 'every `dti.computed`', offset '`dti_bps ≤ 5000` on the decision-of-record and final versions', satisfied by '`du_cap_ok = true`', breach '`dti.du_cap.exceeded` → 23.2 restructure loop (`ineligible_change` in 23.1); counteroffer/denial via `underwriting_reviewer` (21.6)' — evaluators-22-5.ts `22.5.duDti50Gate` (ops-22-5 duCapGate); checkDuCap emits `dti.du_cap.exceeded`; finalizeLiabilities emits `liabilities.finalized{du_cap_ok}` (B3-6-02: 'For loan casefiles underwritten through DU, the maximum allowable DTI ratio is 50%'); T6: 5,275 bps fails, 4,544 passes." });
  // R5 / T7: armed by the plan, anchored on the scheduled note date the plan carries (from closing.scheduled), opened by the settlement-statement line or a pre-closing payoff/zero-balance statement, retired by `debt_payoff.evidenced`.
  o("FNMA_B3_6_07_PAYOFF_FUNDS_GATE", { anchorField: "scheduled_note_date", evaluator: "22.5.payoffFundsGate", satisfied: "`debt_payoff.evidenced`",
    why: "§22.5 timer table: 'not_before_gate', trigger `debt_payoff.planned`, anchor `closing.scheduled`, offset 'for every excluded-by-payoff liability: verified funds `≥ payoff_amount` in addition to 22.4's cash to close and reserves (`funds_to_verify += Σ payoff_amount`), and at closing the payoff appears on the settlement statement or a pre-closing payoff statement/zero-balance evidence exists', satisfied by `debt_payoff.evidenced`, breach 'blocks `funding.authorized` (26.3) — sev 2; if funds are insufficient the liability is re-included and DTI recomputed' — evaluators-22-5.ts `22.5.payoffFundsGate`; planPayoff emits `debt_payoff.planned{payoff_amount_cents, funds_to_verify_delta_cents, scheduled_note_date}`; evidencePayoff emits `debt_payoff.evidenced` or `debt_payoff.failed` (B3-6-07: 'verified funds must be in addition to any funds required for closing costs and reserves'); T7: $1,180.00 card, settlement statement Wed Nov 18, 2026." });
  // R4 / T8: the ≤ 10-payment rule re-evaluated as of the scheduled note date (nightly job and every closing.scheduled); the DTI version that records the recomputation retires the instance.
  o("FNMA_B3_6_05_10MO_REMAINING_RULE", { trigger: "`closing.scheduled`", anchorField: "scheduled_note_date", evaluator: "22.5.tenMonthRemainingRule", satisfied: "`dti.computed{remaining_months_recomputed=true}`",
    why: "§22.5 timer table: 'not_before_gate (rule evaluated as a gate)', trigger 'nightly and on `closing.scheduled`', anchor `scheduled_note_date`, offset '`remaining_months` recomputed as of the scheduled note date: installment/garnishment/alimony-type obligations with `remaining_months > 10` are included; ≤ 10 excluded unless `significantly_affects`', satisfied by 'recomputation recorded on the DTI version', breach 'a closing move that pushes an excluded debt back over 10 months re-includes it → `liabilities.changed`' — evaluators-22-5.ts `22.5.tenMonthRemainingRule` (ops-22-5 tenMonthRule / tenMonthRemainingRule); recordDti emits `dti.computed{remaining_months_recomputed, scheduled_note_date}` (B3-6-05: 'more than ten monthly payments remaining'); T8: 9 payments of $312.37 as of Fri Nov 6, 2026 excluded; Mon Oct 26, 2026 with 11 remaining re-included." });
  // B3-6-05 legal documents: armed by an alimony-type declaration, opened by the decree/agreement/order confirming the amount, retired by 22.1's classification of that document.
  o("FNMA_B3_6_05_LEGAL_DOC_GATE", { trigger: "`liability.declared{liability_type∈{alimony, child_support, separate_maintenance, equalization_payment}}`", evaluator: "22.5.legalDocGate", satisfied: "`document.classified{doc_class∈{divorce_decree, support_order}}`",
    why: "§22.5 timer table: 'not_before_gate', trigger '`liability.declared{alimony|child_support|separate_maintenance|equalization_payment}`', offset 'decree/agreement/court order in the file confirming the amount', satisfied by '`document.classified{divorce_decree|support_order}`', breach 'blocks `liabilities.finalized` — sev 3' — declareLiability emits `liability.declared{liability_type}`; 22.1's classifyDocument emits `document.classified{doc_class}` for the `divorce_decree` / `support_order` classes; evaluators-22-5.ts `22.5.legalDocGate` (B3-6-05: 'A copy of the divorce decree, separation agreement, court order, or equivalent documentation confirming the amount of the obligation must be obtained and retained in the loan file')." });
  // SEL-2026-05 / T9: armed by the IRS-agreement declaration, opened by the approved agreement + payment evidence (or the pending application) with no lien indicated in the subject county, retired by the inclusion with payment_basis=irs_agreement.
  o("FNMA_B3_6_05_IRS_AGREEMENT_GATE", { trigger: "`liability.declared{liability_type=irs_installment}`", evaluator: "22.5.irsAgreementGate", satisfied: "`liability.included{payment_basis=irs_agreement}`",
    why: "§22.5 timer table: 'not_before_gate', trigger '`liability.declared{irs_installment}` or tax-debt evidence on the credit report/transcripts (22.3)', offset 'approved agreement + evidence of current payments, or the pending application; `tax_lien_indicated = false` (24.4 title search of the subject county); payment included unless paid in full', satisfied by 'evidence linked and payment included', breach 'blocks `liabilities.finalized`; a filed lien → 24.4 payoff/subordination path' — evaluators-22-5.ts `22.5.irsAgreementGate`; includeLiability emits `liability.included{payment_basis}` and refuses (TAX_LIEN_ROUTES_TO_24_4) when a Notice of Federal Tax Lien is indicated (B3-6-05, SEL-2026-05); T9: $300.00/month approved agreement, Franklin County, dti 4,910 bps." });
  // T2: the DU resubmission SLA armed by the tolerance hand-off (`liabilities.changed{tolerance_result=resubmission_required}` — 23.1 decides and resubmits), +1 creditor business day (Tue Oct 20 → Wed Oct 21, 2026), retired by the DTI version reconciled to the resubmission (`dti.computed{checked_against_du=true}`, stage du_submission_n with 23.1's check id / submission id).
  o("SM_DU_RESUBMIT_SLA_1BD", { trigger: "`liabilities.changed{tolerance_result=resubmission_required}`", offset: "+1 business_days_creditor", anchorField: "changed_at", satisfied: "`dti.computed{checked_against_du=true}`",
    why: "§22.5 timer table: 'referenced (23.1)', trigger `liabilities.changed`, breach '23.1 decides resubmission (45%/3-point rule)'; 23.1's row: 'deadline (internal SLA)', +1 `business_days_creditor`, satisfied by `du.submitted` — the registry resolves the code to this (first) row, so it arms on the hand-off event ops-22-5 notifyTolerance emits with `tolerance_result` (B3-2-10: resubmit when the DTI 'exceed[s] 45%, or increase[s] by 3 percentage points or more') and is retired when recordDti records the version checked against the resubmission (`checked_against_du=true`); T2: UDM alert Tue Oct 20, 2026 verified as a $450.00 auto payment → 4,175 bps (+375) → due Wed Oct 21, 2026; $300.00 → 4,050 bps within tolerance (no instance)." });
}
