/**
 * §14.1 timer overrides: for every 14.1 registry row whose "Trigger" or "Satisfied by" column carries a condition the
 * column grammar drops (an " or " alternative, a "with …"/"in a conduit district"/"with no open case" qualifier, a compound
 * "months + days" offset, a "(+3 if mailed)" service adjustment) a `reg.override(code, { trigger?, satisfied?, offset?,
 * anchorField?, evaluator?, why })` with the spec text in `why` (see src/domain/foreclosure/timers.ts
 * applyForeclosureSatisfiedOverrides for the pattern). Called from this section's timers.ts after the section-level
 * overrides, so these win the merge.
 *
 * Conventions the grammar forces (src/kernel/events/match.ts holds ONE dotted pattern per column; conditions are exact
 * string compares on payload fields):
 * - an " A or B " satisfier becomes one resolution event the process emits in both branches (ops-14-1.ts), e.g.
 *   `bankruptcy.notice.verified{result∈{case_opened, rejected}}` — the spec's own events are emitted alongside it;
 * - an " A or B " trigger becomes the one event both causes emit, e.g. `bankruptcy.claims_window.opened` from the verified
 *   petition and from the conversion order (Rule 3002(c): "70 days after the order for relief or entry of an order converting");
 * - "months + days" offsets are computed by `completionClock` (E-2.2-01/-04) and carried on the triggering event as
 *   `completion_due_on`, the row anchoring on it with a same-day offset and arming only when the field is present (the
 *   section already does this for USC_524C4_REAFFIRM_RESCISSION and REGX_1024_39C2_DISCHARGE_WRITTEN_NOTICE);
 * - a "+3 days if served by mail" (Rule 9006(f)) adjustment is folded into a computed anchor (`objection_anchor_on`);
 * - FRBP clocks roll forward under Rule 9006(a)(1)(C) on the court calendar (federal legal holidays) — "rolled forward to the
 *   next federal business day" is the grammar's spelling of `roll_rule=frbp_9006_forward`.
 * Every trigger and satisfier named here is appended to the event store by a tool handler in src/app/tools/section14-1.ts
 * (through the ops-14-1.ts functions that validate the inbound record) — never by a bare literal.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_14_1(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // ---- rule 1: detection and verification
  o("SM_BK_VERIFY_1BD", { satisfied: "`bankruptcy.notice.verified{result∈{case_opened, rejected}}`", why: "§14.1 timer table: satisfied by '`bankruptcy.petition.filed` or `bankruptcy.notice.rejected` (with evidence)' — `verifyNotice` emits both outcomes as one `bankruptcy.notice.verified{result}` alongside the spec's events (a correctly rejected notice must satisfy the 1-BD verification clock, not breach it)." });
  // ---- rule 3: the F-2-01 referral clock arms only for the referral types the row conditions name
  o("FNMA_F2_01_BK_REFERRAL_14", { trigger: "`bankruptcy.petition.filed{referral∈{full, ch11, repeat_filer, cramdown}}`", anchorField: "petition_date", why: "§14.1 timer table: trigger '`bankruptcy.petition.filed` where `fnma_delinquency_status ≥ 60` or open `foreclosure` case, or chapter = 11, or `serial_filer_class ≠ none`, or referral type `cramdown`', anchor 'petition_date (verified)' — `verifyNotice` decides the referral type (`initialReferralType`, rule 3) and carries it on the event; a `poc_only` petition arms no 14-day full-referral clock (14.1-Q3)." });
  // ---- E-2.1-04 counsel SLAs: the workout submission clock runs only where Fannie Mae approval is required
  o("FNMA_E2_1_04_WORKOUT_SUBMIT_10BD", { trigger: "`bankruptcy.workout_proposal.received{approval_required=true}`", anchorField: "received_at", why: "§14.1 timer table: trigger '`bankruptcy.workout_proposal.received` (approval required)', anchor `received_at` — E-2.1-04: proposals are 'submitted to Fannie Mae where approval is required within ten business days after it receives the law firm's initial recommendation'; `workoutProposal` carries `approval_required` (rule 9: §1111(b) elections and cramdown strategy need Fannie Mae approval; E-2.1-09 'seek approval from Fannie Mae … as required')." });
  // ---- rule 5: Rule 3002(c) claims window — petition (ch. 7/12/13) or conversion order; 9006 forward on the court calendar
  o("FRBP_3002C_POC_BAR_70", { trigger: "`bankruptcy.claims_window.opened{chapter∈{7, 12, 13}}`", anchorField: "anchored_on", offset: "70 `calendar_days`, rolled forward to the next federal business day (Fed. R. Bankr. P. 9006(a)(1)(C); `roll_rule=frbp_9006_forward`, `court:<district>`)", why: "§14.1 timer table: trigger '`bankruptcy.petition.filed` (ch. 7/12/13) or `bankruptcy.case.converted`', anchor 'order_for_relief_date / conversion_date', offset '70 `calendar_days`, `roll_rule=frbp_9006_forward`' — Rule 3002(c): the claim is due '70 days after the order for relief or entry of an order converting the case'; `verifyNotice` and `convertCase` both emit `bankruptcy.claims_window.opened{anchored_on}` (rule 10: 'a new 70-day claims window runs from the conversion order')." });
  o("FRBP_3002C7_POC_SUPPLEMENT_120", { trigger: "`bankruptcy.poc.filed{writings_complete=false}`", anchorField: "order_for_relief_date", offset: "120 `calendar_days`, rolled forward to the next federal business day (Fed. R. Bankr. P. 9006(a)(1)(C); `roll_rule=frbp_9006_forward`)", why: "§14.1 timer table: trigger '`bankruptcy.poc.filed` without complete 3001(c)(1)/(d) writings', offset '120 `calendar_days`, 9006 forward' — a claim filed with the note/mortgage writings and perfection evidence attached arms no supplement clock (Rule 3002(c)(7)); `pocSupplementFiled` emits `bankruptcy.poc.supplement.filed`." });
  // ---- Rule 3003(c)(3): Chapter 11 claims follow the court-set bar date carried on the docketed notice
  o("FRBP_3003C3_CH11_BAR_DATE", { trigger: "`bankruptcy.docket.event.received{kind=bar_date_notice, chapter=11}`", anchorField: "bar_date", offset: "0 calendar_days", why: "§14.1 timer table: trigger '`bankruptcy.docket.event.received{bar_date_notice}` (ch. 11)', anchor 'court-set date', offset '0 (date from notice)' — docket events are typed by `kind` (data model `bankruptcy_docket_events.event_type`); `docketEventReceived` parses the bar date from the notice into `bar_date` and the clock is due on that court-set date (Fed. R. Bankr. P. 3003(c)(3))." });
  // ---- rule 2: serial filers (§362(c)(3)–(4)) — the clocks arm only for the classes the spec names
  o("USC_362C3_SERIAL_STAY_30", { trigger: "`bankruptcy.petition.filed{serial_filer_class=one_prior_dismissed_1y}`", anchorField: "petition_date", satisfied: "`bankruptcy.stay.serial_30.resolved{result∈{extended, terminated_362c3}}`", why: "§14.1 timer table: trigger '`bankruptcy.petition.filed` with `serial_filer_class=one_prior_dismissed_1y`'; satisfied by '`bankruptcy.stay.extended` (order) else `bankruptcy.stay.terminated{362c3}` on day 31 with counsel confirmation' — `serialFilerStay` emits the spec's events and one `bankruptcy.stay.serial_30.resolved{result}`; an ordinary filer never arms the 30-day clock (11 U.S.C. §362(c)(3))." });
  o("USC_362C4_NO_STAY_CONFIRM_5BD", { trigger: "`bankruptcy.petition.filed{serial_filer_class=two_plus_prior_dismissed_1y}`", anchorField: "petition_date", satisfied: "`attorney.confirmation{no_stay}`", why: "§14.1 timer table: trigger '`bankruptcy.petition.filed` with `two_plus_prior_dismissed_1y`'; satisfied by '`attorney.confirmation{no_stay}` (written)' — gates stay on until confirmed (11 U.S.C. §362(c)(4); E-2.1-03)." });
  // ---- §521(a)(2)(A): the statement of intention — 30 days from the petition (the statutory default; the 341 meeting, when set earlier, is docketed later)
  o("USC_521A2_SOI_30", { anchorField: "petition_date", why: "§14.1 timer table: trigger '`bankruptcy.petition.filed` (ch. 7)', anchor 'earlier of petition_date + 30 or `meeting_341_at`' — §521(a)(2)(A): the statement is due 'within thirty days after the date of the filing of a petition … or on or before the date of the meeting of creditors, whichever is earlier'; the verified petition carries `petition_date` (the meeting date is not yet known at verification, so the row runs the statutory 30 days rather than falling back to the verification timestamp); `docketEventReceived{meeting_341_scheduled}` records the earlier meeting date as `soi_due_on` for counsel." });
  // ---- rule 9: Form 20 within 1 BD — cramdown or a Chapter 11 petition (E-2.3-03; E-2.2-02)
  o("FNMA_E2_3_03_FORM20_IMMEDIATE_1BD", { trigger: "`bankruptcy.form20.required{cause∈{cramdown, chapter_11}}`", why: "§14.1 timer table: trigger '`bankruptcy.cramdown.requested` or `bankruptcy.petition.filed` (ch. 11)' — `cramdownRequest` (the `fnma.form20.prepare` tool) and the verified Chapter 11 petition (`verifyNotice`) both emit `bankruptcy.form20.required{cause}` next to the spec's own events (rule 9: 'Chapter 11 individual cases: full referral within 14 days, Form 20 within 1 BD'); satisfied by `fnma.form20.submitted`, appended by the officer's `fnma.form20.prepare{submit}`." });
  // ---- E-2.1-06: adequate protection — resolved by counsel's instruction or by confirmation
  o("FNMA_E2_1_06_ADEQUATE_PROTECTION_45", { satisfied: "`bankruptcy.adequate_protection.resolved{result∈{attorney_instructed, plan_confirmed}}`", why: "§14.1 timer table: satisfied by '`attorney.instructed{adequate_protection}` or `plan_confirmed`' — `adequateProtectionCheck` emits one resolution event for either (E-2.1-06: confirmation more than 45 days after the creditors' meeting → instruct counsel to consider a Motion for Adequate Protection Payments)." });
  // ---- rule 8: post-petition 60-day delinquency — the trustee confirmation only in conduit districts
  o("FNMA_E2_2_04_TRUSTEE_STATUS_CONFIRM_5BD", { trigger: "`bankruptcy.postpetition.delinquency.60{conduit_district=true}`", anchorField: "day_60", why: "§14.1 timer table: trigger '`bankruptcy.postpetition.delinquency.60` in a conduit district' — 'In conduit districts the agent confirms status with the trustee within 5 BD (E-2.2-04) before referral'; a direct-pay district arms nothing; `trusteeStatusConfirmed` emits `trustee.status.confirmed`." });
  o("FNMA_E2_1_08_POSTPETITION_60DPD_REFERRAL_14", { anchorField: "day_60", why: "§14.1 timer table: anchor `day_60` — the event's `day_60` is the day after the second unpaid installment's due date; 'The referral must be sent no later than two weeks from the 60th day of delinquency' (E-2.1-08)." });
  // ---- detection source (h): an orphan trustee payment — only with no open case
  o("SM_BK_ORPHAN_TRUSTEE_PAYMENT_2BD", { trigger: "`bankruptcy.orphan_payment.detected{payer_type=trustee, open_case=false}`", anchorField: "received_at", why: "§14.1 timer table: trigger '`payment.received{payer_type=trustee}` with no open case' — the 2.1 `payment.received` event (src/domain/cashiering/service.ts) carries neither `payer_type` nor an open-case fact, so the 14.1 ingestion of a trustee receipt (`orphanTrusteePayment`, called by `bk.ledger.apply_trustee`) validates the voucher against the case store and re-emits it as `bankruptcy.orphan_payment.detected{payer_type=trustee, open_case=false}` (plus a `bankruptcy.notice.received{source=trustee_payment}`); a conduit disbursement on an open case arms nothing." });
  // ---- E-2.2-01 / E-2.2-04 completion timelines: months + two weeks, anchored per the Guide, satisfied by the phase change 14.1 emits
  o("FNMA_E2_2_01_CH7_COMPLETION_2M2W", { trigger: "`bankruptcy.referral.sent{chapter=7, full=true, completion_due_on is not null}`", anchorField: "completion_due_on", offset: "0 calendar_days", satisfied: "`bankruptcy.status.changed{to∈{relief_granted, dismissed, discharged, closed}}`", why: "§14.1 timer table: trigger '`bankruptcy.petition.filed` (ch. 7, ≥60 dpd/in foreclosure) or day-60 referral', anchor 'petition_date or day_60', offset '2 `months` + 14 `calendar_days`', satisfied by 'case completion event' — the full referral (at filing when ≥60 dpd/in foreclosure, else at day 60) carries `completion_due_on` = anchor + 2 months + 14 days computed by `completionClock` (the grammar cannot hold months + days; the row arms only when the field is present so a zero offset never runs from the referral day); E-2.2-01 completion = 'the termination of the automatic stay, the case being dismissed or closed, or … a discharge and the trustee abandons all interest' → `bankruptcy.status.changed{to}` (the generic phase event 14.1 emits)." });
  o("FNMA_E2_2_04_CH13_COMPLETION_5M2W", { trigger: "`bankruptcy.referral.sent{chapter∈{12, 13}, full=true, completion_due_on is not null}`", anchorField: "completion_due_on", offset: "0 calendar_days", satisfied: "`bankruptcy.status.changed{to∈{plan_confirmed, relief_granted, stay_terminated, dismissed, closed}}`", why: "§14.1 timer table: 'as above for ch. 12/13', anchor 'petition_date / day_60 / referral', offset '5 `months` + 14 `calendar_days`', satisfied by 'plan confirmed / stay terminated / dismissed / closed' — E-2.2-04: 'five months and two weeks' 'from the 60th day of delinquency or referral if <60 days delinquent at filing; from the filing if ≥60 days delinquent or in foreclosure'; `completionClock` picks the anchor and the referral event (`referralPackage`, the `attorney.send_package` tool) carries `completion_due_on`." });
  o("FNMA_E2_2_04_POSTCONF_COMPLETION_2M2W", { trigger: "`bankruptcy.postpetition.delinquency.60{plan_confirmed=true, completion_due_on is not null}`", anchorField: "completion_due_on", offset: "0 calendar_days", satisfied: "`bankruptcy.status.changed{to∈{relief_granted, dismissed}}`", why: "§14.1 timer table: trigger '`bankruptcy.postpetition.delinquency.60`', anchor `day_60`, offset '2 `months` + 14 days', satisfied by 'relief/dismissal' — E-2.2-04 post-confirmation 60-day delinquency → 'two months and two weeks'; `mfrReferral` emits the event with `plan_confirmed` and `completion_due_on` = day 60 + 2 months + 14 days." });
  // ---- rule 8: the Rule 4001(a)(3) 14-day stay of the relief order — a condition-shaped gate asserted by `assertGateOpen`, satisfied by its expiry event
  o("FRBP_4001A3_ORDER_STAY_14", { evaluator: "14.1.reliefOrderStayLapsed", satisfied: "`bankruptcy.stay.relief_effective`", why: "§14.1 timer table: `relief_order_entered` → not-before gate of 14 calendar days (9006 forward) unless the order waives; 'expiry → `foreclosure_blocked=false`'; 'attempted foreclosure act before expiry blocked by `assertGateOpen`' — condition-shaped over the order's entry date (Fed. R. Bankr. P. 4001(a)(3)); the daily stay-gate recomputation (`reliefOrderGate`) emits `bankruptcy.stay.relief_effective` once the stay has run, which is the expiry the row is satisfied by." });
  // ---- Rule 4001(d): the agreed-order objection window — the "+3 if mailed under 9006(f)" folds into the anchor
  o("FRBP_4001D_AGREED_ORDER_OBJ_14", { trigger: "`bankruptcy.agreed_order.noticed`", anchorField: "objection_anchor_on", offset: "14 calendar_days", why: "§14.1 timer table: trigger 'agreed order noticed', anchor `mailed_at`, offset '14 `calendar_days` (+3 if mailed under 9006(f))', satisfied by 'order entered' — Rule 4001(d): objections are due '14 days after the notice is mailed'; Rule 9006(f) adds 3 days only for service by mail, so `agreedOrderNoticed` carries `objection_anchor_on` = `mailed_at` (+3 calendar days when `served_by_mail`) and the row runs 14 days from it; satisfied by the docketed `agreed_order_entered` (`docketEventReceived`)." });
  // ---- §1301(c)(2)/(d): the co-debtor relief request — 20 days to object, else granted by operation of law
  o("USC_1301D_CODEBTOR_RELIEF_20", { trigger: "`bankruptcy.codebtor_relief.requested{ground=1301c2}`", anchorField: "filed_at", why: "§14.1 timer table: trigger 'counsel files §1301(c)(2) request', anchor `filed_at`, satisfied by 'objection docketed or auto-termination recorded' — §1301(d): a (c)(2) request (the plan does not propose to pay the claim) 'is granted automatically 20 days after filing absent a written objection'; `codebtorReliefRequested` / `codebtorReliefResolved{result∈{objection_docketed, auto_terminated}}` (the `attorney.send_package/request` and `bk.case.read/write` tools)." });
  // ---- SM_BK_DOCKET_SYNC_1BD: recurring from the opened case; each completed docket lookup re-arms it
  o("SM_BK_DOCKET_SYNC_1BD", { trigger: "`bankruptcy.case.opened`", anchorField: "opened_at", why: "§14.1 timer table: trigger 'open case', anchor 'daily', satisfied by 'docket lookup completed' — the verified petition emits the 7.1 alias `bankruptcy.case.opened` (data model event alias map) which arms the recurring 1-BD docket reconciliation; `docketSyncCompleted` (the `bk.case.read/write{op=docket_sync}` tool) emits `bankruptcy.docket.sync.completed`, and the engine re-arms the recurring row on every satisfaction." });
}
