/**
 * §14.2 timer overrides — applied last (after the §14 section-level overrides in ./timers.ts), so they win the merge.
 * Each `reg.override(code, { trigger?, anchorField?, offset?, satisfied? | evaluator?, why })` encodes the spec's timer row
 * where the registry column grammar cannot: Rule 9006(a) rolls (forward rolls through the offset grammar's "rolled to the
 * next federal business day" = weekends + legal holidays; the backward 21-day roll through a computed anchor, since the step
 * grammar has no backward roll), the anchors the section-level satisfied-only overrides re-derived to null, and the
 * satisfaction events the 14.2 tools actually emit (`bk.change.detect`, `attorney.send_package op=confirm_filed_served`,
 * `bk.fee_items.read/batch op=resolve`; docket papers arrive as 14.1's `bankruptcy.docket.event.received{kind=…}`).
 * See src/domain/foreclosure/timers.ts applyForeclosureSatisfiedOverrides for the pattern.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

const ROLL_FWD = "rolled to the next federal business day";
const CREATED = "`bankruptcy.payment_change_notice.created{in_scope=true}`";

export function applySatisfiedOverrides_14_2(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // ---- (b)(1) payment change: the primary deadline + not-before gate (name retained from 3.2; this row is the 14.2 definition)
  o("BK_3002_1_PAYMENT_CHANGE_21", { trigger: CREATED, anchorField: "deadline_file_serve", offset: "0 calendar_days", satisfied: "`bankruptcy.payment_change_notice.filed_served{timely=true}`",
    why: "§14.2 timer table (Rule 3002.1(b)(1); name retained from 3.2 — the registry carries one row per code, so this override is the definition 3.2's effective-date gate sees too): `payment.change.scheduled` on an in-scope Ch. 13 loan → within 1 BD (SM_BK_PAYMENT_CHANGE_DETECT_1BD) `bk.change.detect` runs the rule-1 scope test and emits `bankruptcy.payment_change_notice.created{in_scope=true}` carrying `deadline_file_serve` = `effective_due_date` − 21 calendar days rolled BACKWARD off a Saturday, Sunday or legal holiday (Rule 9006(a)(1)(C), (a)(5); `paymentChangeDeadline`, `timer.compute_frbp op=payment_change_21`; fixture: due 2026-11-01 → day 21 Sunday 2026-10-11 → Friday 2026-10-09). The offset grammar has no backward roll, so the rolled date is the anchor with offset 0. Satisfied only when the notice is both filed and served by the deadline — the spec column reads '`…filed` and `…served` (both timestamps ≤ deadline)': `attorney.send_package op=confirm_filed_served` emits `bankruptcy.payment_change_notice.filed_served{filed_at, served_at, timely}` with `timely` = both dates ≤ deadline (`timeliness9006`), so an untimely filing never satisfies the gate; the tool then cancels the breached instance with the (b)(3) recomputation recorded (`effective_date_applied`, `payment.change.effective_date.pushed` to 3.2). Breach: gate — the new amount may not be billed on the scheduled date; sev-1; sanctions exposure logged." });
  o("SM_BK_3002_1_TARGET_LEAD_35", { trigger: CREATED, anchorField: "target_file_date", offset: "0 calendar_days", satisfied: "`bankruptcy.filing.package_handed{filing_type=s1_payment_change}`",
    why: "§14.2 timer table: 'same' trigger as BK_3002_1_PAYMENT_CHANGE_21; internal target `effective_due_date` − 35 calendar days stepped back off a closed day (fixture: Sunday 2026-09-27 → Friday 2026-09-25) and carried as `target_file_date` on the created event; satisfied when the filing package is handed to counsel (`attorney.send_package`); sev-3." });
  o("SM_BK_PAYMENT_CHANGE_DETECT_1BD", { satisfied: "`bankruptcy.payment_change_notice.created`", why: "§14.2 timer table: `payment.change.scheduled` → notice row created (`bk.change.detect`) within 1 `business_days_servicer`; sev-3." });
  o("FRBP_3002_1B4_OBJECTION_WINDOW", { trigger: "`bankruptcy.form_410s1.filed_served`", anchorField: "effective_due_date", evaluator: "14.2.noB4MotionBeforeDueDate", satisfied: "`bankruptcy.payment_change_notice.status_changed{status∈{effective, determined}}`",
    why: "§14.2 timer table: `filed_served` (emitted by `attorney.send_package op=confirm_filed_served` for a 410S-1) → monitor through `effective_due_date` − 1 day: the spec's satisfied column 'no (b)(4) motion by the day before the due date → `effective`' is a condition, not a clock, so the row is evaluator-backed (`14.2.noB4MotionBeforeDueDate` over the notice's `objection` facts recorded by `bk.change.detect op=docket_event kind=objection_to_payment_change` / `b4MotionHold`); the platform spells the outcome as `bankruptcy.payment_change_notice.status_changed{status}` (emitted by `bk.change.detect op=effective` on the due date → `effective`, or `op=docket_event kind=order_on_payment_change` → `determined`), which closes the monitor; a motion holds the old amount until the court's order; counsel (Fed. R. Bankr. P. 3002.1(b)(4))." });
  // ---- (c) fees: 180-day preclusion, the 90-day batch cadence and the (e) one-year challenge window
  o("BK_3002_1C_FEE_NOTICE_180", { trigger: "`fee.incurred_postpetition`", anchorField: "incurred_on", offset: `180 calendar_days, ${ROLL_FWD}`, satisfied: "`bankruptcy.fee_notice.filed_served`",
    why: "§14.2 timer table (Rule 3002.1(c); name retained from 2.7): `fee.incurred_postpetition` (appended by `bk.fee_items.read/batch op=incur` for every validated recoverable item — a waived item never arms it) → 410S-2 filed and served within 180 calendar days of `incurred_on`, 9006(a) forward roll (fixture: 2026-10-20 + 180 = Sunday 2027-04-18 → Monday 2027-04-19); satisfied by `bankruptcy.fee_notice.filed_served{fee_item_ids}` (`attorney.send_package op=confirm_filed_served` for an s2_fee_notice). The engine keys instances by loan, so 'covering the item' is enforced by the exposure list, not the timer: `bk.notice.render` refuses a 410S-2 whose lines do not cover every open item on the loan, and `precludeAndWriteOff` reads each item's own `notice_deadline`. Breach: item → `precluded_not_noticed`, written off, sev-2, `officer` for write-offs above $1,000 per case and any late-notice attempt." });
  o("SM_BK_3002_1C_BATCH_90", { trigger: "`fee.incurred_postpetition{first_unnoticed=true}`", anchorField: "incurred_on", offset: `90 calendar_days, ${ROLL_FWD}`, satisfied: "`bankruptcy.filing.filed_served{filing_type=s2_fee_notice}`",
    why: "§14.2 timer table: first un-noticed fee item → 410S-2 within 90 calendar days of the oldest item's `incurred_on`, or immediately when the aggregate reaches $200 (`bankruptcy.fee_batch.threshold_reached`). The trigger is the inbound `fee.incurred_postpetition` the 14.2 module appends when it validates a 2.7/9.x/13.6 item (`bk.fee_items.read/batch op=incur`, `ingestFeeItem`): `first_unnoticed=true` when no other open item exists for the loan, so the oldest item anchors the cadence (a recurring row re-arms on each satisfaction). The spec column is a bare '90 calendar_days'; the filing (CM/ECF by counsel + the mailed debtor copy) cannot complete on a court-closed day, so `feeBatchSchedule` files the next open day and this internal row carries the same 9006(a) forward roll — fixture 14.2-T5: day 90 = Monday 2027-01-18, Birthday of Martin Luther King, Jr. → Tuesday 2027-01-19 (still 90 days before the 180-day preclusion). Satisfied when the 410S-2 is filed and served (`attorney.send_package op=confirm_filed_served` → `bankruptcy.filing.filed_served{filing_type=s2_fee_notice}`); sev-3." });
  o("FRBP_3002_1E_FEE_CHALLENGE_365", { trigger: "`bankruptcy.fee_notice.filed_served`", anchorField: "served_at", offset: `12 months, ${ROLL_FWD}`, satisfied: "`bankruptcy.fee_notice.resolved{result∈{allowed_by_lapse, challenged}}`",
    why: "§14.2 timer table (Rule 3002.1(e)): 410S-2 served → a party in interest's motion within one year after service, 9006(a)(1)(C)/(a)(6) forward roll (fixture: served 2027-01-15 → Saturday 2028-01-15, Sunday, Monday 2028-01-17 MLK Day → Tuesday 2028-01-18 = `challengeDeadline`); lapse → items `allowed_by_lapse` (memo → receivable), motion → `challenged` (`bk.fee_items.read/batch op=resolve` emits `bankruptcy.fee_notice.resolved{result}`)." });
  // ---- (f)/(g) responses: 28 days after service, +3 when served by mail (9006(f)), 9006(a) forward
  const resp = (code: string, kind: string, filingType: string, cite: string) => o(code, { anchorField: "served_at", offset: `+28 calendar_days, ${ROLL_FWD}`, satisfied: `\`bankruptcy.filing.filed_served{filing_type=${filingType}}\``,
    why: `§14.2 timer table (${cite}): docket \`${kind}\` (14.1 docket monitor, served date and method parsed from the certificate of service) → response 28 calendar days after the served date, 9006(a) forward roll; +3 calendar days when the paper was served by mail (Rule 9006(f)) — the row carries the CM/ECF period (trustee and counsel serve through CM/ECF, which adds nothing), the mailed variant is \`responseDue(served_at, by_mail)\` (\`timer.compute_frbp op=response_28\`) recorded as \`bk_status_responses.response_deadline\`, so the engine's clock is never later than the true deadline (fixture: served Friday 2028-03-03 → Friday 2028-03-31; by mail Monday 2028-04-03); satisfied when the ${filingType.replace(/_/g, " ")} is filed and served (\`attorney.send_package op=confirm_filed_served\`); breach sev-1 (Rule 3002.1(h)).` });
  resp("FRBP_3002_1F_STATUS_RESPONSE_28", "motion_410c13_m1", "m1r_status_response", "Rule 3002.1(f), Form 410C13-M1R");
  resp("FRBP_3002_1G3_FINAL_CURE_RESPONSE_28", "trustee_notice_410c13_n", "nr_final_cure_response", "Rule 3002.1(g)(3), Form 410C13-NR filed as a POC supplement; breach: preclusion of any claimed default");
  resp("FRBP_3002_1G4_MOTION_RESPONSE_28", "motion_410c13_m2", "m2r_motion_response", "Rule 3002.1(g)(4), Form 410C13-M2R");
  o("SM_BK_3002_1G1_TRUSTEE_NOTICE_WATCH_45", { trigger: "`bankruptcy.plan.completed`", anchorField: "completed_on", satisfied: "`bankruptcy.docket.event.received{kind=trustee_notice_410c13_n}`",
    why: "§14.2 timer table (Rule 3002.1(g)(1)): `bankruptcy.plan.completed` — appended by `bk.status_response.compute op=plan_completed` when the trustee's completion signal (TFS/EPay final voucher, final report; spec inputs `plan_completed` signals) is validated and the post-petition and arrearage views are frozen and hashed (`planCompletionFreeze`, rule 7) — anchored on `completed_on` → the trustee's Form 410C13-N within 45 calendar days; satisfied when it is docketed (14.1 docket monitor → `bankruptcy.docket.event.received{kind=trustee_notice_410c13_n}`, which also triggers FRBP_3002_1G3_FINAL_CURE_RESPONSE_28); breach: counsel requests the notice / considers an (f) motion; the frozen ledger stays frozen for the response." });
  o("FRBP_3002_1G4_DEBTOR_MOTION_WINDOW_45", { trigger: "`bankruptcy.form_410c13nr.served{g4_window_opens=true}`", anchorField: "served_at", offset: `45 calendar_days, ${ROLL_FWD}`, satisfied: "`bankruptcy.docket.event.received{kind=motion_410c13_m2}`",
    why: "§14.2 timer table (Rule 3002.1(g)(4)): Form 410C13-NR served (`attorney.send_package op=confirm_filed_served` emits `bankruptcy.form_410c13nr.served{served_at, statement}`) → the debtor or trustee may move on Form 410C13-M2 within 45 calendar days after service of the response (9006 forward); the monitor is satisfied by that docketed motion (which triggers FRBP_3002_1G4_MOTION_RESPONSE_28); its lapse means the case closes on the response's facts and the itemized amounts become the only collectible post-case arrears." });
  // ---- relief from stay: the rule ceases "unless the court orders otherwise" — default keep filing (14.2-Q2)
  o("SM_BK_3002_1_RELIEF_CEASE_CHECK", { anchorField: "entered_at", evaluator: "14.2.rule3002_1NoticesCeaseAfterRelief",
    why: "§14.2 timer table: `relief_order_entered` (docket) → gate: counsel confirms whether the court \"orders otherwise\"; default keep filing (b)/(c) notices while the case is open (14.2-Q2) — the gate stays OPEN unless the case is closed or counsel advises the district treats continued notices as improper (`reliefOrderDecision` gate_facts; Rule 3002.1(a): 'Unless the court orders otherwise, the requirements of this rule cease when an order terminating or annulling the automatic stay … becomes effective')." });
}
