// 30.1 Fannie Mae post-purchase servicing setup (servicer number, Fannie Mae loan number, remittance type, first reporting cycle, initial custodial deposits, servicer loan number, MERS/eRegistry post-purchase state, custodian record, Escrow Setup event)
// spec/sections/30-post-purchase-servicing-setup-and-boarding-to-the-subservice/30-1-fannie-mae-post-purchase-servicing-setup-servicer-number-fan.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("30.1-T1: Given a Purchase Advice dated Thu Nov 19, 2026 for the fixture loan, when `purchase_advice.received` is processed, then `loans.fnma_loan_number`, `purchase_date=2026-11-19`, `remittance_type='AA'`, `pass_through_rate=5.875000` and `loan_terms` v2 effective 2026-11-19 exist by 17:00 ET the same day and `SM_FNMA_LOAN_NUMBER_RECORD_T0` is satisfied.", { todo: true });
test("30.1-T2: Given the loan appears in the LSDU position extract on Fri Nov 20, 2026 with LPI 12/2026 and UPB $560,000.00, then `loan.fnma_established` (established_at 2026-11-20), `investor_setup_status='established'`, and the first LAR 96 (`0005600000{`, action 00, action date 112026) is submitted by Mon Nov 23, 2026 20:00 ET.", { todo: true });
test("30.1-T3: Given the first LAR is not accepted by Mon Nov 30, 2026 20:00 ET, then `FNMA_TT96_FIRST_LAR_ACQ_MONTH_BD2` breaches with an `officer` escalation and the Compliance Sentinel report lists it; given acceptance on Nov 23, then the December cycle creates `payment.none` due Tue Dec 22, 2026 20:00 ET.", { todo: true });
test("30.1-T4: Given the flag `investor_reporting.escrow_events=on` and Servicing Platform visibility observed Fri Nov 20, then the T&I Escrow Setup event for $2,062.50 (sequence 1, item \"Set up\") is accepted before Mon Nov 23, 2026 03:00 ET; given visibility observed Thu Nov 19, the deadline is Fri Nov 20 03:00 ET and the decision record shows `deadline_basis='purchase_day_visibility'`.", { todo: true });
test("30.1-T5: Given purchase proceeds bank-matched Fri Nov 20, 2026, then `custodial_transfers{ti_escrow_balance, 206250}` is due Mon Nov 23, 2026 and the T&I bank feed shows the credit; a transfer executed Tue Nov 24 breaches `FNMA_F1_03_TI_DEPOSIT_PROCEEDS_1BD` (sev-1).", { todo: true });
test("30.1-T6: Given `warehouse.advance.repaid` on Fri Nov 20, then a MERS MIN Update removing SM's Interim Funder Org ID is in the Mon Nov 23 batch and accepted; given the MRE snapshot on Fri Dec 4 shows investor = Fannie Mae, then `mers.investor.fnma_verified` and 1.5 `W-016` closes; if not, a partner query package exists on Dec 4.", { todo: true });
test("30.1-T7: Given an eNote loan purchased Nov 19, when the eRegistry inquiry on Nov 20 shows Controller = Fannie Mae, Location = Fannie Mae eVault, Master Servicer = SM Org ID and no Secured Party, then `enote.post_purchase.verified`; given Master Servicer = partner Org ID, then the timer breaches and eNote payoff commands are blocked with reason `enote_master_servicer_mismatch`.", { todo: true });
test("30.1-T8: Given Fannie Mae's position shows UPB $560,000.01, then a `position_variance` (money) opens, the first LAR is held, and the command to adopt Fannie Mae's figure is refused without an `officer` approval record and a PPA package.", { todo: true });
test("30.1-T9: Given the Purchase Advice shows remittance type S/A while the commitment says A/A, then no LAR is projected until the variance is resolved and the decision record cites C1-3-01.", { todo: true });
test("30.1-T10: Given the January payment ($3,402.62) is processed Wed Dec 30, 2026, then the LAR with LPI 0127, UPB `0005594557A`, interest `0000027416G`, principal `0000005442I` is submitted by Thu Dec 31 20:00 ET and a CRS 001 request for $3,285.96 is prepared the same day (5.2).", { todo: true });
test("30.1-T11: Given a non-escrowed loan, then no Escrow Setup event is created and `escrow_setup_acked` is reached on `first_lar_accepted`.", { todo: true });
test("30.1-T12: Given all sub-steps complete by Tue Nov 24, 2026, then `loan.reporting_active` is emitted and `SM_INVESTOR_SETUP_COMPLETE_5BD` (due Fri Nov 27 \u2014 servicer calendar) is satisfied.", { todo: true });
