// 30.2 New-origination boarding onto the Supermortgage servicing platform at funding (origination-to-servicing data mapping, DQ gate, opening ledger, documents, consents, timers seeded, welcome/first-payment communications, no-transfer-notice design)
// spec/sections/30-post-purchase-servicing-setup-and-boarding-to-the-subservice/30-2-new-origination-boarding-onto-the-supermortgage-servicing-pl.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("30.2-T1: Given `loan.funded` for the refinance fixture at 11:40 MST Thu Nov 12, 2026, when boarding runs, then `loans.boarded_at` is the same day, `SM_ORIG_BOARD_T1BD` (due Fri Nov 13 23:59 MST) is satisfied, and `OB-001`\u2026`OB-022` all `pass`.", { todo: true });
test("30.2-T2: Given the signed note ($560,000, 6.125%, 360) and a CD P&I of $3,402.63, when `OB-003` runs, then it fails (recomputed $3,402.62), the loan is `exception`, the defect is routed to 25.2/26.1, and the boarding command is refused until the source record is corrected.", { todo: true });
test("30.2-T3: Given the opening ledger, then `principal` = 56,000,000, `escrow` = 206,250 (matching 30.3's analysis and the CD (g)(3) total), `prepaid_interest` = 178,543 (26.3's cent-rounded per diem \u00d7 19 days), and the entry set balances to zero against `origination_funding_clearing`.", { todo: true });
test("30.2-T4: Given borrower A's E-SIGN consent under disclosure v2.0 (servicing categories listed; demonstration passed) and borrower B's consent under v1.4 (origination only), then A's servicing `consents.scope` includes `periodic_statements` and B's does not; `OW-002` is open for B and B's first-payment letter carries the 7.4 invitation.", { todo: true });
test("30.2-T5: Given first payment due Fri Jan 1, 2027, then `SM_ORIG_FIRST_STATEMENT_LEAD_15` is due Thu Dec 17, 2026 and the first statement shows amount due $4,090.12 (P&I $3,402.62 + escrow $687.50), no past-due, and the late-fee line \"$170.13 after Jan 16, 2027\".", { todo: true });
test("30.2-T6: Given a first-payment letter rendered without the B-1 credit-reporting sentence, then the checklist blocks release; rendered with it and mailed Mon Nov 16, 2026, then a `notices` row with template `NTC_FCRA_1681S2A7_B1` exists and 8.1's negative-information timer is pre-satisfied.", { todo: true });
test("30.2-T7: Given `applicant_demographics` shows \"information not provided\" for race, then `borrower_fair_lending.collected_via='not_provided'` and `OB-013` passes; given a mapping attempt to infer race from surname, then the command is refused.", { todo: true });
test("30.2-T8: Given the purchase fixture funded Wed Nov 18, 2026 with the MIN not yet registered, then the loan boards with `OW-004`, 26.4's 7-day timer is due Wed Nov 25, and `OW-004` clears on the MERS acknowledgment.", { todo: true });
test("30.2-T9: Given a property in a state where SM holds no servicer license, then `OB-020` fails, the loan cannot board, and an `officer` escalation is created.", { todo: true });
test("30.2-T10: Given the servicing loan number allocated at staging, then 29.3's ULDD export carries it as the Lender Loan Number and, after purchase, `fnma_establishment_checks` shows the same identifier (no LAR 81).", { todo: true });
test("30.2-T11: Given the \u00a71024.38(c)(2) compile command for the boarded loan on day 1, then the servicing file (transaction schedule, security-instrument copy, empty contact log, LBDS data-field report, no borrower submissions) is produced within 5 minutes (well inside five days).", { todo: true });
test("30.2-T12: Given a rescindable refinance with `rescission_expires_at` = Nov 10, 2026 23:59:59 MST and a `loan.funded` timestamp of Nov 10 09:00, then `OB-018` fails and boarding is refused (funding itself would have been blocked by 26.3).", { todo: true });
test("30.2-T13: Given the same `loan.funded` event delivered twice, then the second is ignored and no duplicate `loans` row, ledger entry or letter exists.", { todo: true });
test("30.2-T14: Given the loan is not `active` by Thu Dec 24, 2026 because the tax-service match is still open, then `SM_ORIG_ACTIVE_BEFORE_FIRST_DUE_GATE` breaches (sev-1), the Sentinel report lists it, and cashiering still applies the Jan 1 payment.", { todo: true });
