// 30.3 Escrow account establishment at origination: RESPA §1024.17 aggregate analysis, initial deposit, initial escrow statement, CD escrow consistency, waivers, HPML escrow, same-servicer refinance escrow transfer
// spec/sections/30-post-purchase-servicing-setup-and-boarding-to-the-subservice/30-3-escrow-account-establishment-at-origination-respa-1024-17-ag.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("30.3-T1: Given the fixture lines (taxes $3,200 \u00d7 2 with deadlines May 1/Nov 1, hazard renewal $1,850 in Nov; first payment Jan 1, 2027), when the initial analysis runs with a 2-month cushion, then base = $687.50, cushion = $1,375.00, low point \u2212$687.50 (Nov), `target_at_start` = $2,062.50, lowest target = $1,375.00, and the 12-row trial balance matches the table above to the cent.", { todo: true });
test("30.3-T2: Given the same analysis, when CD figures are computed, then (g)(3) shows taxes 4 \u00d7 $533.33 = $2,133.32, insurance 4 \u00d7 $154.17 = $616.68, aggregate adjustment \u2212$687.50, total $2,062.50; (l)(7) shows $8,250.00 / $0.00 / $2,062.50 / $687.50; a CD draft with (g)(3) total $2,062.51 fails `REGZ_1026_38L7_CD_ESCROW_CONSISTENCY_GATE`.", { todo: true });
test("30.3-T3: Given consummation Fri Nov 6, 2026 with the statement in the package, then `escrow.statement.sent{initial}` is dated Nov 6, `initial_statement_delivery_basis='at_settlement'`, and no `REGX_1024_17G_INITIAL_STMT_45` instance remains open; given the package omitted it, then the 3.1 timer is due Mon Dec 21, 2026 and the statement is mailed by then.", { todo: true });
test("30.3-T4: Given the disbursement dates were entered as Oct 1/Mar 1 (due dates) instead of the Nov 1/May 1 deadlines, then the engine's projection uses the `scheduled_pay_date` (deadline-based) and the decision record shows the (c)(2)/(k) basis; the resulting deposit is $2,062.50, not the $2,750.00 an earlier-disbursement projection would produce.", { todo: true });
test("30.3-T5: Given `is_hpml=true`, when a waiver is requested, then it is denied with `HPML_ESCROW_REQUIRED`, the account is established at funding, and `hpml_escrow_min_cancel_date` = 2031-11-06.", { todo: true });
test("30.3-T6: Given the purchase fixture with BPMI monthly $130.47 and LTV 90%, when a waiver is requested, then denied with `MI_MONTHLY` and `PARTNER_POLICY_LTV`, the decision worksheet is stored, and the LE is unchanged.", { todo: true });
test("30.3-T7: Given the refinance borrower (LTV 70%, reserves 9 months, no lates) requests a waiver Oct 7, 2026, then approved by Oct 12 (3 creditor BDs), a revised LE issues under 21.5 with \"Escrow Waiver Fee\" $0.00 (default), and `escrow_lines` are retained inactive for 3.7 monitoring.", { todo: true });
test("30.3-T8: Given a same-servicer refinance with a recorded agreement dated Oct 6 and a prior balance of $1,610.40 after the Nov 10 hazard disbursement, when the prior loan pays off Nov 12, then `escrow_credit_transfers.credited_cents = 161040`, the new loan's `escrow` liability = 206,250 with the borrower's closing escrow funds = $452.10, and no refund check is issued.", { todo: true });
test("30.3-T9: Given no agreement, then 3.5's refund of $1,610.40 is due Fri Dec 11, 2026 and the closing collects $2,062.50.", { todo: true });
test("30.3-T10: Given the agent proposes a hazard-line override to $1,700 without a document, then the command is refused; with a renewal quote document, the override is accepted and a superseding analysis is created with the new figures.", { todo: true });
test("30.3-T11: Given a cushion parameter of 2.5 months, then `REGX_1024_17C5_CUSHION_CAP_GATE` (3.4) blocks approval; given an instrument cushion of 1 month, then cushion = floor(825,000/12) = $687.50 and the deposit = $1,375.00.", { todo: true });
test("30.3-T12: Given the loan funds Nov 12 and is purchased Nov 19 with the escrow-events flag on, then 30.1's Escrow Setup event reports T&I balance $2,062.50 (sequence 1) and the first deposit event on Dec 30 (payment 1) reports +$687.50, balance $2,750.00 (3.7 balance rule).", { todo: true });
test("30.3-T13: Given a biweekly election, then the projection has 26 periods with per-period escrow round_half_up(825,000/26) = $317.31 and the cushion remains $1,375.00.", { todo: true });
