// 30.4 First-90-days servicing hand-off: ownership notice, first statement, first credit and investor cycles, vendor activations, EPD monitoring, servicing file, origination record retention and timer seeding
// spec/sections/30-post-purchase-servicing-setup-and-boarding-to-the-subservice/30-4-first-90-days-servicing-hand-off-ownership-notice-first-stat.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("30.4-T1: Given `loan.boarded` Thu Nov 12, 2026 for the refinance fixture, when the hand-off opens, then 22 `handoff_items` exist, HO-018 is `not_applicable{no_mi}`, HO-010\u2026HO-014 are `pending` with `due_at` null until `loan.purchased`, and `SM_TAX_SERVICE_ACTIVATE_2BD`, `SM_FLOOD_LOL_SERVICING_LINK_2BD`, `SM_INSURANCE_TRACKING_ACTIVATE_2BD` are due Mon Nov 16, 2026, `SM_SERVICING_FILE_COMPILE_TEST_1BD` Fri Nov 13, `SM_ORIG_HANDOFF_CLOSE_90` Wed Feb 10, 2027.", { todo: true });
test("30.4-T2: Given `loan.purchased` Thu Nov 19, 2026, when HO-009 is evaluated, then 25.4's `ownership_transfer_notices.status='expected'` with `due_date=2026-12-19` is mirrored, no `NTC_REGZ_1026_39_OWNERSHIP_TRANSFER` is rendered, the portal explainer is primed the same day, and a borrower-uploaded copy of the Fannie Mae letter on Dec 28 satisfies HO-009 (`evidenced`) and 25.4's evidence timer.", { todo: true });
test("30.4-T3: Given the fixture, when the cycle-1 statement is sent Thu Dec 17, 2026, then reconciliation passes with amount due $4,090.12 (P&I $3,402.62 + escrow $687.50), due date Jan 1, 2027, late fee $170.13 if not received by Jan 16, UPB $560,000.00, escrow balance $2,062.50; given the statement shows $4,090.13, then `SM_FIRST_STATEMENT_RECONCILE_1BD` breaches and 7.1 issues a corrected statement.", { todo: true });
test("30.4-T4: Given the Jan 1, 2027 installment is paid Wed Dec 30, 2026, when cycle 2 runs, then `REGZ_1026_41B_STATEMENT_PROMPT_4` is due Wed Jan 20, 2027 from the Sat Jan 16 courtesy end and no `FNMA_D2_2_03_PAYMENT_REMINDER_20` instance is created; given it is unpaid on Jan 17, then the reminder is due Jan 20 and the late-charge gate opens on the next servicer business day after Sat Jan 16.", { todo: true });
test("30.4-T5: Given boarding Nov 12 with `loan.active` on Nov 13, when the Nov 30 snapshot runs, then the loan appears with Date Opened 11062026, status 11, current balance 000560000, DOFD blank, PHP `BBBBBBBBBBBBBBBBBBBBBBBB`, and HO-007 is satisfied on the 8.1 acknowledgment; given `loan.boarding.warnings_open` with an identity OW rule, then the loan is held to the Dec 31 snapshot with `credit.cycle.held{reason}`.", { todo: true });
test("30.4-T6: Given no payment on the Jan 1 installment, when the daily EPD job runs, then `sm_watch_p1_6_30` is raised Sun Jan 31, 2027 (30 days past due), `fnma_e205_p1_3_60` and `sm_qc_p1_6_60` are raised Tue Mar 2, 2027, `epd.flag.raised` reaches 28.2 (immediate `qc_reviews{kind='epd'}`), and a payment posted Mar 3 that cures Jan 1 clears the 60-day flags with `clear_reason='payment'` while the history rows remain.", { todo: true });
test("30.4-T7: Given installments 1\u20133 paid on time and installment 5 (May 1, 2027) 60 days past due on Jun 30, 2027, then `fnma_e205_p1_3_60` is never raised, `sm_qc_p1_6_60` is raised Jun 30, and the watch closes Sat Jul 31, 2027 (`epd.watch.closed`); given the loan paid off on Apr 15, 2027, then the watch closes that day.", { todo: true });
test("30.4-T8: Given a \u00a71024.36 request received Mon Nov 16, 2026 asking for the payment history, when `compileServicingFile` runs, then the package contains the opening-ledger schedule (principal 56,000,000; escrow 206,250; prepaid interest as an origination charge, not a loan-account transaction), the executed security instrument marked `pending_recorded_copy`, the interaction notes, the data-field report and an empty (v) container, `within_five_days=true` if completed by Sat Nov 21, 2026 23:59; the boarding test on Nov 13 recorded `elapsed_seconds`.", { todo: true });
test("30.4-T9: Given the indexed origination documents, when `classifyRetention` runs, then the LE \u2192 `regz_le_3y` / 2029-11-06, CD \u2192 `regz_cd_5y` / 2031-11-06 (but `retention_until` = the Fannie Mae class value, i.e., null until liquidation), ATR worksheet \u2192 `regz_atr_3y` / 2029-11-06, Reg B notices \u2192 `regb_25m` / 25 months after the notification date, AfBA \u2192 `respa_afba_5y` / 2031-10-05, SFHDF \u2192 `fdpa_life_of_loan`, E-SIGN consents \u2192 `esign_consent_life`; a document with no class blocks `servicing_handoffs.complete` via `SM_ORIG_RETENTION_CLASSIFY_GATE`.", { todo: true });
test("30.4-T10: Given the seeded timers are verified, then the expected set in rule 10 exists with the fixture anchors (Dec 17, Dec 24, Nov 19/Dec 12, Nov 12, Dec 21, Jan 30 2028, May 1/Nov 1 2027, Nov 30 snapshot, Nov 12 2027 reminder, Feb 1 2027 1098, Nov 6 2029 rescission watch); given 3.3's `REGX_1024_17I_ANNUAL_STMT_30` is missing, then the agent creates it with `created_by='O11.4_repair'` and HO-021 records the repair.", { todo: true });
test("30.4-T11: Given the tax-service vendor rejects the contract for an APN mismatch, then the agent re-submits with the 24.4 APN within the same business day; given the second rejection, then sev-2 at Thu Nov 19, 2026 (+5 BD) and 3.7 falls back to direct authority lookup for the May 1, 2027 installment.", { todo: true });
test("30.4-T12: Given the purchase fixture boarded Wed Nov 18, 2026 with `mi_certificates` present, when no insurer activation confirmation exists by Fri Nov 20, then `SM_MI_ACTIVATION_CONFIRM_2BD` breaches sev-1 to the `pmi` agent and partner `officer`, premium remittance is held, and HO-018 shows `breached`; given confirmation Nov 20 with certificate number and first premium due Jan 1, 2027, then `mi_schedules` are seeded and `HPA_4902B_AUTO_TERMINATE_0` = 2035-12-01, `HPA_4902C_MIDPOINT_TERMINATE_0` = 2042-01-01.", { todo: true });
test("30.4-T13: Given all items satisfied by Jan 21, 2027 and the third statement cycle (Feb 20, 2027) sent, when closure runs, then `servicing_handoff.closed{close_basis='all_items_satisfied'}` on Feb 20; given HO-009 still `expected` on Feb 10, then closure requires an `officer` override listing HO-009 and 25.4's timer keeps running.", { todo: true });
test("30.4-T14: Given 118 loans boarded in November 2026, when `CS_BOARDED_ORIGINATIONS_DAILY` runs Thu Dec 3, 2026 06:00 ET, then the report lists the Metro 2 transmission due that day, any vendor rejects, overdue compile tests, and the \u00a71026.39 status distribution; the partner copy contains loan numbers only.", { todo: true });
