// 35.11 Operations stewardship and hosted measurement: the ops steward over cycles, exceptions and the outbox, the daily ops report, and the audit's hosted and persisted columns
// spec/sections/35-operations-runtime/35-11-operations-stewardship-and-hosted-measurement.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("35.11-T1: Given a `cycle_registry` row for `statements` (35.3 rule 2's def) with `next_expected_by` two hours in the past and no `cycle_receipts` row for its period key, when the steward's pass runs, then one `ops_exceptions` row `{source_kind: cycle_registry, source_id: \"statements:<period_key>\", kind: missed_cycle, status: triaged}` exists, `ops.cycle.missed{consecutive_misses: 1}` is logged, `SM_OPS_CYCLE_MISSED_2H` is armed on it, exactly one open `ops_analyst` escalation names the cycle and its runbook, and a second pass in the same minute adds no row, event or escalation.", { todo: true });
test("35.11-T2: Given the exception of T1, when 35.3 emits `cycle.run.completed` for that cycle and period, then `ops.cycle.recovered` is logged, the exception is `resolved` with `resolved_at`, `SM_OPS_CYCLE_MISSED_2H` is `satisfied`, and the `ops_analyst` escalation is still open (the steward completed nothing).", { todo: true });
test("35.11-T3: Given the same cycle misses two consecutive period keys, when the steward detects the second, then `ops.cycle.missed{consecutive_misses: 2}` is logged and the breach action of `SM_OPS_CYCLE_MISSED_2H` opens a `sev1` escalation to `compliance` at its due instant (the timer-probe run of the override), while the first miss's breach opened `sev2` to `ops_analyst`.", { todo: true });
test("35.11-T4: Given an adapter `fnma-lsdu` with four dead outcomes in the last 15 minutes and no successful send in the last hour, when `ops.exceptions.classify` runs on one of its dead messages, then the exception is `adapter_down` with confidence `0.95`, `signals = {D15: 4, S60: 0, A: 5, C: \"timeout\"}` is stored on the triage row, `ops.exception.classified` and `ops.exception.triaged` are logged, `SM_OPS_EXCEPTION_TRIAGE_1BD` is `satisfied` and `SM_OPS_ADAPTER_DOWN_1H` is armed on `classified_at`; no requeue happened.", { todo: true });
test("35.11-T5: Given the adapter of T4 sends one message successfully 20 minutes later, when the steward's pass runs, then the dead message is requeued once with `outbox.requeued{by: \"agent:qc-audit\", auto: true, reason: \"adapter_recovered\"}`, `ops_exceptions.auto_requeues = 1`, the exception is `resolved` when `integration.message.sent` follows and `SM_OPS_ADAPTER_DOWN_1H` is `satisfied`; given instead no success within an hour, then the clock breaches with a `sev2` `ops_analyst` escalation naming the adapter and `D15`.", { todo: true });
test("35.11-T6: Given a dead message with `failure_kind = http_5xx` and three successful sends of its adapter in the last hour, when classified, then it is `transient` with confidence `0.90` and is requeued automatically once; given it dies again, then the second `integration.message.dead` adds a triage row `escalated`, no second automatic requeue happens (`AUTO_REQUEUE_CAP_1`), and the exception is `assigned` to `ops_analyst`; given a hand requeue by an `ops_analyst` through 34.4, then 34.4 counts it as `requeue_no: 1` — the automatic one was not a hand requeue.", { todo: true });
test("35.11-T7: Given a dead message with `failure_kind = validation` and `attempts = 5`, when classified, then it is `poison` with confidence `0.95`, `ops.exceptions.requeue{op: auto}` is refused `CONFIDENCE_FLOOR_0_85`-or-kind (the refusal names `poison`), a `requeue_proposed` triage row exists and the exception is `assigned` to `ops_analyst` with `ops.exception.assigned` logged; given an unclassifiable error, then `needs_person` with confidence `0.50` and the same assignment.", { todo: true });
test("35.11-T8: Given open `sev1`–`sev4` escalations, breached timers and dead units on the fixture, when the steward's pass runs ten times, then every escalation that was open is still open, every breached timer is still `breached` and no `escalation.completed` event carries an agent actor (contract test: `src/domain/operations-runtime/stewardship.ts` contains no call to any escalation completion or timer write; the guard `NEVER_COMPLETES_A_BREACH` refuses an input naming `escalation_id` with `complete`).", { todo: true });
test("35.11-T9: Given the day's state on the fixture, when `ops.report` runs twice with nothing changed, then one `ops_daily_reports` row exists for `(nonprod, <as_of_date>)` with every column of the Data model populated (counts and codes only; no payload, name or e-mail in the JSON), its `sha256` equals the sha256 of the canonical JSON, `ops.report.run_completed{changed: true}` then `{changed: false}` are logged, and `SM_OPS_REPORT_DAILY` is `satisfied` and re-armed for the next day; given one more dead message, then a third run appends a newer row with a different hash.", { todo: true });
test("35.11-T10: Given 61 overrides over 340 decisions on day 1 and 52 over 310 on day 2 for a T1 agent, when the two days' reports run, then `ai_monitoring_metrics` holds `override_rate = 0.1794` and `0.1677` for those days, `recordOverrideRate` was called with each, the agent is AI-off after day 2 with a reason naming `17.9%, 16.8%`, and `ai.kill_switch.tripped{metric: override_rate}` is logged; given day 1 were 48 over 400 (`0.1200`), then nothing trips; given a day with zero decisions, then `decision_volume = 0`, a null rate, and the null day does not count as out of band.", { todo: true });
test("35.11-T11: Given three FAKE approvals (`actor_id` starting `FAKE:`) on the day, when the report runs under `ENVIRONMENT = nonprod`, then `fake_approvals = 3`, `fake_roles` lists the roles and no escalation exists; when the same day is reported under `ENVIRONMENT = production`, then `ops.fake_in_production{count: 3}` is logged, one exception `{kind: fake_in_production}` exists and exactly one `sev1` escalation to `compliance` is open, and a second report run that day opens no second one.", { todo: true });
test("35.11-T12: Given any tool of this process, when its input carries a money-shaped key (`amount_cents`, `waive`, `entry_set`, `refund`) or an escalation completion, then the command is refused `NO_MONEY_FIELD` or `NEVER_COMPLETES_A_BREACH` before any read, nothing is written, and the ledger and money columns before and after every stewardship route are identical in a contract test.", { todo: true });
test("35.11-T13: Given the registry, when `ops.runbook.read{timer_code: \"SM_OPS_ADAPTER_DOWN_1H\"}` runs, then the reply carries the code, kind, trigger, anchor, offset, satisfied event, the breach text verbatim from the registry row, `owner_role: ops_analyst`, `severity: 2`, `process: 35.11` and this file's path; `{cycle_code}` returns the `cycle_registry` row with `expected_by_rule`; an unknown code is refused `UNKNOWN_CODE`.", { todo: true });
test("35.11-T14: Given `PROBE_DATABASE_URL` reachable, when `audit.hosted.run{target: probe}` runs, then `supermortgage_probe` was dropped, created and migrated to the newest file under `db/migrations`, every `ALL_TOOLS` pair was posted with `{}` over HTTP as its own agent, no result is `errored`, the only `not_wired` results are tools of the service keys `boarding`, `orig-boarding` and `tolerance-21-5`, a `hosted_probe_runs` row and `docs/audit/hosted.json` carry `migration_head` equal to that newest file and one result per pair, and `audit.hosted.run_completed` is logged with the four counts summing to `tools_total`.", { todo: true });
test("35.11-T15: Given a tool whose bus guard refuses the empty input (a typed `code`), when the probe classifies it `refused_typed`, then the probe database's row counts of `loan_events`, `entity_records`, `ledger_lines`, `timers`, `escalations` and `agent_decisions` are identical before and after that call (the unit of work rolled back); given a tool that answers 500, then it is `errored` and the run's `errored` count is above zero and T14 fails by name.", { todo: true });
test("35.11-T16: Given `docs/audit/hosted.json` whose `migration_head` is `0136_du_preflight_results.sql` while the newest file is later, when `tools/audit.py --check` runs, then the brief prints `hosted: not measured (stale: 0136_du_preflight_results.sql vs <newest>)`, no exec total is compared and the exit code is 0; given a current `hosted.json` whose `hosted` total is one below `exec_totals.hosted.built`, then `--check` exits 1 naming `hosted`; given a process in `done` but not in `exec_done` with `hosted` below its `tools`, then `--check` exits 0; given a process in `exec_done` that drops below `hosted = tools` or `persisted = tables`, then `--check` exits 1 naming the process.", { todo: true });
test("35.11-T17: Given `supermortgage_test` migrated and the journey files run under the journey lock, when `audit.persisted.count` runs, then `persisted_measurements` has one row per manifest table with `post_migrate_count`, `after_journey_count` and `delta`, `notice_templates` and `ai_systems` are `seeded_only` (delta 0, not counted), `loans`, `loan_events`, `payments`, `ledger_lines`, `timers`, `notices` and `applications` are `persisted`, a manifest table absent from the database is `missing_ddl`, `docs/audit/persisted.json` carries the run's `migration_head`, and `audit.persisted.run_completed{tables_with_rows}` equals the count of `persisted` verdicts.", { todo: true });
test("35.11-T18: Given the §35 journeys have run (35.5's daily cashiering year, 35.6's closing and funding, 35.9's default timeline, 35.10's refinance close) and the two lifecycle tests, when the persisted count runs, then `sections_complete` includes 2, 7 and 16 (every table those journeys declare as `expected` is `persisted` and `projection_gaps` for each is 0), every `expected` table with verdict `untouched` is listed in the run's output with the journey step that should have written it, and `docs/audit/COVERAGE.md` shows `hosted` and `persisted` columns on every process row and two exec totals lines after the six unit totals.", { todo: true });
