// 35.1 Persistence seam and the typed record
// spec/sections/35-operations-runtime/35-1-persistence-seam-and-the-typed-record.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("35.1-T1: Given loan with UPB $248,310.55 at 6.500%, fixed P&I $1,612.34 and escrow payment $432.78, when 2.1 posts a conforming payment of $2,045.12 through the bus against Postgres, then one `payments` row exists with `amount_cents = 204512`, `retention = 'life_of_loan_plus_4y'` and the version's idempotency key, three `payment_allocations` rows carry `amount_cents` 134502 (interest, from 248,310.55 × 6.5% ÷ 12 = 1,345.015479 → $1,345.02), 26732 (principal, $267.32) and 43278 (escrow, $432.78) with 2.1's `rule_ref` and the balanced set's `ledger_entry_set_id`, their sum is 204512, the version's UPB after is 24804323 ($248,043.23), the `entity_records` version and the typed rows carry identical values field by field, and one `entity_projections` row per version names `payments`/`payment_allocations`, `phase = commit` and the command's first event.", { todo: true });
test("35.1-T2: Given a global `rate_sheets` row at version 3, when two commands each carry `expected_versions: [{rate_sheets, <id>, 3}]` and both write version 4, then the first commits and the second is refused `STALE_RECORD{kind: rate_sheets, id, expected: 3, current: 4}` with HTTP 409, and the refused command left no `loan_events` row, no `entity_records` row, no `agent_decisions` row and no ledger line (counts before and after are equal); given a command with no declared expectation whose commit collides on `entity_records`' primary key, then the same `STALE_RECORD` is returned and the transaction is rolled back whole.", { todo: true });
test("35.1-T3: Given a loan whose `entity_records` hold 500 versions across 40 kinds including 12 versions of one `payments` row and 6 of one `counterparty_notifications` row, when any command runs, then the entity hydration issued exactly three queries (scoped latest, `HISTORY_KINDS` in full, global latest — asserted by a query-counting `Db`), the store holds one version of each non-history kind and every version of the two history kinds, `payments.history` (section02.ts:114) returns 12 versions in order, and 17.3's first-version gate (section17-3.ts:95) reads the first `counterparty_notifications` version's `status`.", { todo: true });
test("35.1-T4: Given a tool whose handler writes a `payments` version, whose projector inserts the typed row, and which then throws, when the command runs, then the response is the tool's error, `payments` has no new row, `entity_records` and `entity_projections` have no new row, `loan_events` has no new event, and the next command on the same loan hydrates a `boarding` adapter whose maps equal those before the failed command (a hydrating adapter is rebuilt from the record, so a failed command cannot leave state in a Map).", { todo: true });
test("35.1-T5: Given two `Runtime` instances A and B over one database and a third `Runtime` acting as the sweep job, when A runs 25.2 `prepareCd` for an application, B runs 25.2 `deliverCd` for the same disclosure id, and the sweep runtime deems an LE received on its mailbox-rule day, then B never answers `no CD`, the CD B delivered is the CD A prepared (same `disclosure_id`, `data_hash` and `cd_version`), the sweep's deeming was performed by `LoanEstimateService.deemReceived` on a hydrated instance (no hand-appended `disclosure.le.deemed_received` exists in src/runtime/origination.ts: contract test greps the file for the literal), and every stateful key in `originationServices` (`cd-25-2`, `delivery-29-3`, `delivery-29-4`, `secondary`, `tolerance`, `companion`, `orig-boarding`) yields a fresh instance per command whose state after `hydrate` equals the state the instance that wrote the events held.", { todo: true });
test("35.1-T6: Given one loan and two 2.1 posts of $2,045.12 started concurrently from two connections, when both commit, then the second waited on `pg_advisory_xact_lock(hashtext('uow'), hashtext(loan_id))` (its transaction start is after the first's commit), the ledger holds two balanced sets, the loan's UPB after equals the start minus both principal portions, no unique violation and no `STALE_RECORD` occurred; given two different loans posted concurrently, then their transaction windows overlap (neither waited).", { todo: true });
test("35.1-T7: Given twelve armed timers past due and two sweeps started concurrently, when both finish, then one `sweep_runs` row is `completed` and one is `skipped{lease_held}` with `sweep.run_skipped{holder}` logged, exactly twelve `timer.breached` events and twelve escalations exist (never twenty-four), the completed run's `passes` names every pass with a duration, `sweep.run_completed{run_id, as_of_date}` is logged once, and `SM_SWEEP_HEARTBEAT_DAILY` is satisfied by it and re-armed for the next day on the global subject.", { todo: true });
test("35.1-T8: Given a queued FAKE `printMail` message and a queued message whose FAKE adapter is scripted to fail, when sweeps run at +0, +60 s, +180 s, +420 s, +900 s and +1,800 s (the `DEFAULT_RETRY` backoff instants), then the first message is `sent` on the first sweep with one `outbox_dispatches{attempt_no: 1, outcome: acked}` row and `integration.message.sent`, the failing message has five `outbox_dispatches` rows with `next_attempt_at` at the backoff instants and is `dead` after the fifth with `integration.message.dead{attempts: 5}`, a `human_portal_tasks` row and `SM_OUTBOX_DEAD_LETTER_REVIEW_1BD` armed; and when 34.4 requeues it and the adapter is un-scripted, then the next drain sends it and the clock is satisfied.", { todo: true });
test("35.1-T9: Given the hosted runtime, when `POST /v1/loans/{id}/tools/1.1/runValidation`, `POST /v1/applications/{id}/tools/30.2/snapshotOrigination` and `POST /v1/applications/{id}/tools/25.1/runToleranceTest{checkpoint: cd}` are called, then none answers 501 `not_wired`, the 25.1 result carries `delegated_to: \"21.5\"` and the `tolerance_test_id` of a `tolerance_tests` row 21.5's own tool (`21.5 runToleranceTest`) would have written for the same inputs, and `rt.services[\"tolerance-21-5\"] === rt.services[\"tolerance\"]` in a unit harness.", { todo: true });
test("35.1-T10: Given a decoded transfer tape of three loans, when `1.1 boardLoan` runs on the bus for the batch, then the transaction wrote `transfer_batches`, `properties`, `loans`, `borrowers`, `loan_borrowers`, `loan_terms`, `transfer_batch_loans`, `boarding_validations`, `parties` (transferor and servicer, found-or-inserted) and `custodial_accounts` (P&I and T&I, found-or-inserted) with the same columns `POST /v1/transfers/batches` writes (a row-by-row comparison against a batch boarded through the route on a second database), the events, the 1.6 opening ledger sets, the armed timers, one escalation per hard exception, the global `transfer_batches` entity row and one `agent_decisions` row; and `boardTransferBatch` in src/runtime/transfers.ts refuses with `SEED_ONLY` under `ENVIRONMENT=production`.", { todo: true });
test("35.1-T11: Given a command that writes a kind with no authored projector (`fee_gate_checks`) and one with a projector (`locks`), when the daily verify runs at 06:00 ET, then `locks` has its typed row and `entity_projections` row, `fee_gate_checks` has neither and one `projection_gaps{reason: no_projector, versions_unprojected: 1}` row names it, `record.gaps` lists it under `no_projector`, one `projection_runs{outcome: completed}` row and `projection.run_completed{gaps: 1, mismatches: 0}` exist, and `SM_PROJECTION_LAG_DAILY` is satisfied and re-armed; given the next day passes with no run, then the clock breaches and one sev 3 `ops_analyst` escalation names `SM_PROJECTION_LAG_DAILY`.", { todo: true });
test("35.1-T12: Given a store id `fees-3` written on two loans and a projector for `fees` authored afterwards, when `record.replay{kind: fees}` runs twice, then the first run minted two `entity_keys` rows (one per scope) with distinct uuids, wrote two `fees` rows keyed by those uuids and one `entity_projections{phase: replay}` row per version and logged `record.replayed{rows}`; the second run wrote zero rows and zero events and its decision record says `rows_written: 0`; and both JSON versions still carry the id `fees-3`.", { todo: true });
test("35.1-T13: Given the projected rows of worked example A, when a test's UPDATE of `payment_allocations` is refused by its trigger and the test instead UPDATEs `payments.amount_cents` to 204513 and the verify runs, then one `projection_mismatches{column_name: amount_cents, is_money: true, json_value: '204512', row_value: '204513'}` row exists, `projection.mismatch_found{is_money: true}` is logged, one sev 1 `ciso` escalation names the row ids and the owning process 2.1, the run wrote no correction (`payments.amount_cents` is still 204513 and no `record.replayed` event exists), and the run's `outcome` is `completed`.", { todo: true });
test("35.1-T14: Given an application with 80 events across 21.2, 21.4, 21.5, 25.2 and 29.1, when `record.snapshot{service_key: cd-25-2}` writes a `service_snapshots` row at `through_sequence = N` and six more 25.2 commands run, then the next command's `cd-25-2` instance hydrated from the snapshot plus the events after N and its `state_sha256` equals the hash of an instance hydrated by full replay; and given the snapshot's `state` is tampered with, then hydration discards it, replays in full, logs `service.snapshot.written` for a fresh one and opens a sev 2 `ciso` escalation.", { todo: true });
test("35.1-T15: Given a money-field change proposed by the agent — `record.replay{kind: payments, overrides: {amount_cents: …}}` or any typed-row write that names a `*_cents` column not equal to the JSON version's — when no `officer` approval record exists, then the command is refused `NO_MONEY_FIELD_CHANGE` and nothing is written; and the seam's own tools (`record.project`, `record.replay`, `record.verify`, `record.snapshot`, `outbox.dispatch`) are absent from every money-field allowlist in `spec/registry/agents.json` (contract test).", { todo: true });
