// 35.3 Cycles, jobs and receipts: the planner, the jobs table, `cycles.run_unit` on the bus and the registry of every scheduled cycle
// spec/sections/35-operations-runtime/35-3-cycles-jobs-and-receipts.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("35.3-T1: Given two sweeps started within the same minute against one database, when both call `cycles.plan`, then exactly one holds `pg_try_advisory_lock(35_003)` and appends `cycles.plan.run_completed`, the other appends `cycles.plan.skipped{holder}` and its remaining passes still run, and after the holder's dedicated client ends `pg_locks` shows no advisory lock with key 35003.", { todo: true });
test("35.3-T2: Given a window with the `statements` cycle due for 12 loans and `cashiering_daily` due for the 100-loan fixture book, when `cycles.plan` runs twice for the same `as_of`, then `cycle_runs` has one row per `(cycle_code, period_key)`, `jobs` has exactly 112 rows with distinct `idempotency_key`s, `cycle.run.opened` was appended once per run, and the second pass appended no `cycle.run.opened` and inserted no row.", { todo: true });
test("35.3-T3: Given one run of 100 queued units, when three executors claim concurrently with `FOR UPDATE SKIP LOCKED LIMIT 20` until the queue is empty, then every unit has exactly one `job_events{done}` row and one `agent_decisions` row naming the owner agent, no `unit_id` appears in two executors' claim logs, `cycle_runs.units_done = 100`, and one `cycle_receipts` row exists.", { todo: true });
test("35.3-T4: Given a unit whose runner throws on every call, when the planner and executor run across four sweeps, then the job records attempts 1, 2, 3 with `run_after` 60 s and 120 s after the first two failures, the third failure appends `job.unit.dead{attempts: 3}`, `SM_JOB_DEAD_2H` is armed on the job, one escalation exists to the registry row's `escalation_role` naming `cycle_code`, `period_key` and `unit_id`, `cycle_runs.status` is still `running`, and no receipt was emitted.", { todo: true });
test("35.3-T5: Given a run of 3 units, when the last unit's `UPDATE … RETURNING` reports the counters full, then one `cycle_receipts` row and one pair of events (the cycle's receipt literal and `cycle.run.completed`) exist; given the executor is stopped between the unit's commit and the receipt transaction, when the next planner pass reconciles, then the same single receipt row exists with `emitted_by = planner:<run_id>` and the events were appended once; given both race, then the unique key on `cycle_receipts.run_id` yields one row and one pair of events.", { todo: true });
test("35.3-T6: Given `ledger.period.closed{period_key: 2026-09}` has been appended and `investor_reporting_periods.closed{period_key: 2026-09}` has not, when the planner runs, then the `form_496_monthly` job for `2026-09:<account>:A/A` is `blocked` and never claimed; when `investor_reporting_periods.closed{period_key: 2026-09}` is appended, then the next pass unblocks it (`job_events{unblocked}`) and the unit runs 6.3's chain.", { todo: true });
test("35.3-T7: Given 10,000 armed timers due at or before `now`, when the breach pass runs, then it uses 20 transactions of at most 500 timers each, every one of the 10,000 has exactly one `timer.breached` event and one escalation, and a second pass started concurrently breaches none of them twice (the `FOR UPDATE SKIP LOCKED` page).", { todo: true });
test("35.3-T8: Given the demo clock at 2026-10-01 12:00 ET and the fixture book, when `POST /v1/demo/advance {days: 3}` runs, then `cycles.plan.run_completed` was appended three times with `as_of_date` 2026-10-02, 2026-10-03 and 2026-10-04, `cycle_runs` holds one `cashiering_daily` and one `delinquency_counters` run per day with `period_key` equal to that day and `demo_offset_ms` equal to the step's `demo_clock.offset_ms`, every receipt of day N precedes day N+1's `cycle.run.opened` in `loan_events.sequence`, and every `jobs.lease_until` written during the advance is within 5 minutes of the wall-clock `real_now`, not of `demo_now`.", { todo: true });
test("35.3-T9: Given loan L with UPB $248,310.55, note rate 6.500%, P&I $1,612.34, escrow payment $432.78, an installment due 2026-10-01 unpaid past the 15-day grace and a late charge assessed at 5% of P&I, when the `statements` unit for `(L, 2026-10-01)` runs through `cycles.run_unit` on 2026-10-17, then the statement's late charge is $80.62, its interest portion $1,345.02, its principal portion $267.32 and its amount due $2,125.74, `statement.sent` and `job.unit.done` share one transaction (one `loan_events` batch), the decision names `disclosures`, exactly one `notices` row exists for `(L, 2026-10-01)` after a second plan and a second `cycles.run_unit` of the same job (refused `JOB_NOT_CLAIMABLE`), and the receipt reads `units_total 1, units_done 1`.", { todo: true });
test("35.3-T10: Given a job claimed with `lease_until` 5 minutes ahead by an executor that then stops heartbeating, when `now()` passes `lease_until` and the planner runs, then the job is `queued` again, `job.lease.expired{holder, attempt: 1}` is appended, `attempts` is 1, and a second executor's claim runs it to `done` with `attempt: 2`; given the demo clock is advanced 30 days while the first lease is live, then the lease is not expired by the advance.", { todo: true });
test("35.3-T11: Given a def registered with `expected_by_rule: same_day 23:59 ET` and no run ever, when the planner runs the next morning, then no `timers` row names the cycle (the engine arms only on a trigger event), `cycle_registry.overdue_since` is set to the first pass after 23:59 ET, `cycles.registry{op: list}` returns the row first with `next_expected_by` and `overdue_since`, and no escalation was opened by this process (35.11 opens it).", { todo: true });
test("35.3-T12: Given a run opened at 2026-10-01 12:00 ET with one unit `blocked` on an event that never arrives, when the sweep runs at 2026-10-02 12:01 ET, then `SM_CYCLE_RUN_STALLED_1D` breaches with one `ops_analyst` escalation whose payload names `cycle_code`, `period_key`, `units_done 0` and `units_total 1`; when the event arrives and the unit completes, then `cycle.run.completed` satisfies the clock as `satisfied_late` and the escalation is completable through 34.4 with the disposition `completed_late`.", { todo: true });
test("35.3-T13: Given `cycles.run_unit` is called with an `input` carrying `state`, `custodial`, any `*_cents` key or `changes`, then it is refused `NO_CLIENT_STATE` before any row or event is written; given `jobs.requeue{op: requeue}` on a dead job by an actor `{kind: \"agent\"}`, then `ROLE_REQUIRED{ops_analyst}` and the job stays `dead`; given an `ops_analyst` requeues it with a reason, then `job.unit.resolved` is appended, the decision names the person and the reason, and the ledger and every money column are byte-identical before and after every 35.3 tool call in a contract test over all nine tools.", { todo: true });
test("35.3-T14: Given `SM_CYCLE_PLANNER_DAILY` armed on the global subject by the first `cycles.plan.run_completed`, when a day passes with `cycles.plan` never completing (every pass `cycles.plan.skipped` because a test holds key 35003), then the clock breaches at 23:59 ET with one `ops_analyst` escalation and 35.1's `SM_SWEEP_HEARTBEAT_DAILY` did not breach; when the lock is released and a pass completes, then the clock is satisfied and re-armed for the next day and only one armed global instance of the code exists.", { todo: true });
test("35.3-T15: Given the planner's last pass was on 2026-09-30 and the demo clock steps to 2026-10-01, when the first pass of October runs, then exactly one `ledger.month.ended{period_key: 2026-09, period_end: 2026-09-30}` exists on the global subject, a second October pass appends none, and 35.4's `SM_CLOSE_PERIOD_OPEN_BD1` is armed on it.", { todo: true });
test("35.3-T16: Given the registered bus pair (`35.3`, `cycles.run_unit`) and a `metro2_monthly` job for `2026-09`, when it runs, then 8.1's snapshot builder is invoked with `as_of_date 2026-09-30` under the actor `{agent, credit-reporting}`, `credit.cycle.snapshot_completed` is appended by 8.1's own code (credit-reporting/ops.ts:214-218) in the same transaction as `job.unit.done`, no `(8.1, *)` bus pair was needed, and the decision record's `prompt_version` is `35.3-v1` with `subject_kind metro2_monthly`.", { todo: true });
