// 35.7 Operating roles, identity and the FAKE handover: a person for every kernel role, credentials that cannot be self-asserted on `/v1`, reviewer-role disjointness, the role queues and the handover board
// spec/sections/35-operations-runtime/35-7-operating-roles-identity-and-the-fake-handover.md
// One node:test per T-id, named exactly as the spec. `todo: true` = not implemented yet (tools/audit.py does not
// count it). Implement by replacing the todo line with a real test; never edit the name.
import { test } from "node:test";

test("35.7-T1: Given a fresh database, when every file under db/migrations is applied, then five new base tables exist (`to_regclass` non-null for `role_grants`, `role_queue_snapshots`, `role_handovers`, `breakglass_uses`, `api_principals`) and the base-table count (public + restricted_fl, the query of db.test.ts:40-46) equals the count taken just before this process's migration file plus 5 (776 at HEAD through 0137; the absolute number depends on which §35 migrations precede it and is never asserted), `staff_users.reviewer_roles` exists with a CHECK whose literal list equals `HUMAN_ROLES` from src/app/roles.ts (twenty-two words, no `admin`), the three disjointness CHECKs exist, and every 34.1 T-id (`34.1-T1` … `34.1-T8`) passes unchanged.", { todo: true });
test("35.7-T2: Given an active staff user holding `officer`, when an `admin` calls `roles.grant{role: qc_officer}` for that user, then it is refused `ROLE_DISJOINT{role: qc_officer, conflicts_with: [officer]}` and no `role_grants` row exists; given a direct `UPDATE staff_users SET reviewer_roles = '{qc_officer}'` on the same row, then Postgres raises the CHECK; given an active `ops_analyst` with no conflicting role, when the same grant is confirmed by a different `compliance` member within 10 minutes, then one `role_grants{action: grant, confirmed_by}` row, `role.granted`, an `identities` row with `privileged = true` and `entitlements.reviewer_roles = [qc_officer]`, and an `agent_decisions` row naming both people exist.", { todo: true });
test("35.7-T3: Given a staff principal issued to person P who holds `mlo_of_record`, when `POST /v1/applications/{id}/tools/20.3/requestQuote` is sent under P's bearer with no body `actor`, then the command runs as `{human, <P.staff_user_id>, mlo_of_record}` and the event's `actor_id` is P's id; when the body carries `actor: {kind: human, id: <another id>, role: mlo_of_record}`, then 403 `NO_SELF_ASSERTED_ACTOR` and nothing ran; when a service principal sends `actor: {kind: human, …}`, then 403 `NO_HUMAN_ROLE_ON_SERVICE_PRINCIPAL`; when the shared `API_TOKEN` is presented with `ENVIRONMENT=production`, then 403 `SHARED_TOKEN_REFUSED_IN_PRODUCTION`, and outside production the same request is honoured and its `staff_actions` row reads `surface = v1, source = shared_token`.", { todo: true });
test("35.7-T4: Given officers A and B with their own principals and a 5.2 custodial advance transfer of $260,000.00 (26,000,000 cents, greater than the $250,000.00 threshold), when A submits it with `approvedBy: {kind: human, id: B, role: officer}` in the body, then it is refused `APPROVER_NOT_SELF_ASSERTED`; when A submits it without an approver, then it is refused `APPROVER_DISTINCT` with a `request_id`; when B calls `roles.approve{request_id}` under B's principal, then `dual_control.approved{requested_by: A, approved_by: B}` is logged and the transfer commits with `agent_decisions.approved_by = B` and `approved_role = officer`; when A calls `roles.approve` on A's own request, then `APPROVER_DISTINCT`; given the same transfer for $249,999.99 (24,999,999 cents), then A alone commits it and `approved_by = A`.", { todo: true });
test("35.7-T5: Given a 3.7 payee remittance change for an existing payee of $10,000.01 (1,000,001 cents), when one `officer` submits it, then `APPROVER_DISTINCT` until a second officer's `roles.approve`; given the same change for exactly $10,000.00 (1,000,000 cents), then one officer commits it; given a new payee for $500.00, then two officers are required whatever the amount.", { todo: true });
test("35.7-T6: Given the fixture book with two open `attorney` escalations, one 35.6 step in `waiting_human{funding_approver}` and a pending terms review, under `INTEGRATIONS=fake` with the FAKE set on, when the daily `roles.queue_scan` unit runs through `cycles.run_unit`, then twenty-two `role_queue_snapshots` rows exist for the scan with `attorney = {open_items: 2, holders: 0, fake: false, status: unstaffed}`, `funding_approver = {open_items: 1, fake: true, status: fake}` and `mlo_of_record = {open_items: 1, fake: true, status: fake}`, exactly one `role.queue.unstaffed{role: attorney}` is logged and `SM_ROLE_QUEUE_UNSTAFFED_1BD` is armed on `{environment, role: attorney}` with the due date one servicer business day after `detected_at`; a second scan the same day logs no second event and arms no second clock; when `roles.grant{role: attorney}` activates for a person, then `role.staffed{cause: grant}` satisfies the clock.", { todo: true });
test("35.7-T7: Given `FAKE_REVIEWERS=off` and no holder of `funding_approver`, when a 26.3 wire waits for release for two sweeps, then nothing approves it, `roles.queue` shows `funding_approver` as `unstaffed` and `handover.board` shows the FAKE off for every role; given `ENVIRONMENT=production`, `INTEGRATIONS=fake` and `FAKE_REVIEWERS` unset, then the environment's FAKE set is empty (`fakeReviewerRolesFromEnv` returns `[]`), the reviewers' tick approves nothing, and the board shows `NO_FAKE_IN_PRODUCTION` as the reason.", { todo: true });
test("35.7-T8: Given nonprod with a holder of `funding_approver` who signed in within 30 days, when `compliance` calls `handover.enable{role: funding_approver}` and a different `admin` confirms the `request_id` within 10 minutes, then `role_handovers{action: enabled, requested_by, confirmed_by, holders, pending_items}` and `handover.enabled` exist, `FakeReviewers.fills(\"funding_approver\")` is false on a second `Runtime` over the same database while the other five roles are still filled, and the console marks no `funding_approver` row \"— FAKE reviewer\"; when the requester confirms their own request, then `TWO_PERSON_HANDOVER`; when no confirmation arrives in 10 minutes, then `handover.request.expired` and the FAKE still fills the role.", { todo: true });
test("35.7-T9: Given nonprod where nobody holds `settlement_agent` and the only `qc_officer` holder last signed in 45 days ago, when `handover.plan` runs, then its rows read `settlement_agent: HANDOVER_NEEDS_HOLDER{missing: holder}` and `qc_officer: HANDOVER_NEEDS_HOLDER{missing: signed_in_30d}`, `handover.enable` for either is refused with the same code, and after a `settlement_agent` grant and a fresh `qc_officer` sign-in both rows read `ready` with the holders' ids and the open-item counts.", { todo: true });
test("35.7-T10: Given person P granted `underwriting_reviewer` in `reviewer_roles`, when P's session calls `POST /ops/api/tools/21.6/openReviewerEscalation` with `x-staff-role: underwriting_reviewer`, then the command commits with `actor = {human, <P.staff_user_id>, underwriting_reviewer}`, a `staff_actions` row carries `command = 21.6 openReviewerEscalation`, `role.exercised{grant_id}` is logged once (the second act logs none) and satisfies `SM_ROLE_GRANT_DORMANT_30D`; given a session that holds no such role, then 403 `ROLE_REQUIRED{underwriting_reviewer}` before any read (no `loan_events` row, no `agent_decisions` row).", { todo: true });
test("35.7-T11: Given a grant of `lossmit_reviewer` with no `role.exercised` for 30 calendar days, when the sweep's breach pass runs, then `SM_ROLE_GRANT_DORMANT_30D` breaches into one sev 3 `compliance` escalation naming the grant, the grant is still active, the board flags it `dormant`, and the next 34.1 access review's `keep` for that user without a `rationale` naming the grant is refused `DORMANT_GRANT_NEEDS_RATIONALE` while a `keep` with one succeeds and is recorded.", { todo: true });
test("35.7-T12: Given an active `compliance` member C who holds no reviewer role, when C calls `roles.breakglass{role: attorney, subject: {loan_id: L}, reason}`, then `role_grants{action: breakglass, expires_at = used_at + 4 hours}`, a `breakglass_uses` row, `role.breakglass.used` and an armed `SM_ROLE_BREAKGLASS_REVIEW_1BD` exist; an `attorney` act by C on loan L commits and the same act on loan M is `ROLE_DENIED`; after 4 hours the act on L is `ROLE_DENIED` and `role.revoked{cause: breakglass_expired}` is logged; `roles.breakglass{role: qc_officer}` is refused `NO_BREAKGLASS_INDEPENDENT_ROLE`; a review by C is refused `APPROVER_DISTINCT`, a review by another `compliance` member logs `role.breakglass.reviewed` and satisfies the clock.", { todo: true });
test("35.7-T13: Given an `admin` issues a staff principal for P with `scopes: {loans: [L1]}`, then the response carries the token once, `api_principals.token_hash` is its sha-256 and no column holds the token; a `/v1` command on L1 under it runs and on L2 answers 403 `PRINCIPAL_SCOPE`; after `principals.revoke` the next request is 401 `PRINCIPAL_REVOKED`; five presentations of the revoked token within an hour log one `principal.refused{count: 5}` and open one sev 2 `ciso` escalation, and a sixth opens no second one that hour; every request wrote a `staff_actions` row with `principal_id` and `surface = v1` and none contains the token.", { todo: true });
test("35.7-T14: Given P holds `officer` in `roles`, `fnma_portal_operator` in `reviewer_roles`, an open session and an active principal, when an `admin` runs 34.1's `staff.disable` on P, then in the same transaction a `role_grants{action: revoke, cause: disabled}` row exists for `fnma_portal_operator`, the session and the principal are revoked, `identities.entitlements` for P is empty, and the next queue scan counts P among no role's holders.", { todo: true });
test("35.7-T15: Given the nonprod fixture after T6 and T8, when `handover.board` runs, then it lists exactly twenty-two roles with status, holders, signed-in-within-30-days, dormant grants, FAKE on/off with the `enabled` instant for `funding_approver`, open items and the oldest wait, last exercised and today's FAKE approvals, the FAKE-approval total equals the sum of `approved` in the day's reviewers' reports (`FakeReviewerReport.actions`), and no field of the payload is an e-mail, a phone or a token (a contract test over every string in the response).", { todo: true });
test("35.7-T16: Given the first `role.queue.scan_completed{as_of_date: D}` on the global subject, then `SM_HANDOVER_BOARD_DAILY` is armed for D + 1 calendar day at 06:30 America/New_York through the `subject: \"global\"` override in src/domain/operations-runtime/timers-35-7.ts; the next day's completion satisfies and re-arms it; a day with no completion breaches it into one sev 3 `compliance` escalation, and `npm run spec:lint -- --verbose` lists the code as armable and satisfiable.", { todo: true });
test("35.7-T17: Given any command of this process (`roles.*`, `principals.*`, `handover.*`), then no ledger line and no `*_cents` column of any table changed (counts and sums before and after every tool in a contract test are identical), no section timer was satisfied, extended or cancelled by it, and every action tool wrote one `agent_decisions` row naming the person and one `staff_actions` row.", { todo: true });
