/**
 * §35.5 timer overrides (process-owned; applied after every section's so they win the merge — see
 * src/domain/bankruptcy/timers-14-1.ts for the pattern). One `reg.override(code, { trigger?, satisfied | evaluator,
 * anchorField?, offset?, why })` per 35.5 registry row whose trigger/satisfied column names an event the platform
 * spells differently or a condition the column grammar drops; `why` quotes the spec. A code the servicing spec
 * (sections 1–19) owns is never overridden here — reference it. Wired by src/domain/timer-overrides.ts.
 *
 * 35.5's recurring clocks (SM_CASHIERING_DAILY_RECEIPT_1D, SM_LOCKBOX_FILE_EXPECTED_1BD, SM_ACH_FILE_BUILD_1BD) are global: each is armed by a per-day (or per-run) completion receipt on
 * the global subject, not by a loan or application aggregate, so each takes the cited `subject: "global"` override
 * on the src/domain/partner-book/timers-33-2.ts precedent (SM_PARTNER_BOOK_REVIEW_DAILY). The deadline rows take the
 * anchor-field spellings of the events that actually arm them (`boarded_at`, `returned_on`, `effective_on`), the
 * reprojection clock the `loan_terms.*` prefix for its three spellings, and the two lockbox clocks a `sha256 present`
 * condition so 2.1's and 6.1's own `lockbox.batch.received` (deposit clocks) never arm a posting clock nothing satisfies.
 *
 * Emitters (real path, non-test source): src/domain/operations-runtime/boarding-writes.ts (`installment.schedule.written`,
 * `loan.servicing_config.written` in both boarding transactions), installments.ts (`installment.schedule.reprojected`),
 * cashiering-cycle.ts (`cashiering.daily.run_completed`), lockbox.ts (`lockbox.batch.received{sha256}`, `lockbox.batch.posted`),
 * ach.ts (`ach.file.built`, `ach.return.actioned`; `ach.return.received` is 2.3's, src/domain/cashiering/ops.ts handleReturn).
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_35_5(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // Timer table rows `SM_INSTALLMENT_SCHEDULE_AT_BOARD_0` and `SM_LOAN_SERVICING_CONFIG_AT_BOARD_0`: anchor `boarded_on` — 1.1's and 30.2's `loan.boarded` payloads carry `boarded_at` (src/domain/boarding/service.ts board(); src/domain/orig-boarding/ops-30-2.ts board()), an instant the resolver dates on its ET civil day.
  o("SM_INSTALLMENT_SCHEDULE_AT_BOARD_0", { anchorField: "boarded_at",
    why: "§35.5 timer table row `SM_INSTALLMENT_SCHEDULE_AT_BOARD_0`: deadline on `loan.boarded`, anchor `boarded_on`, offset '0', satisfied by `installment.schedule.written`, breach 'sev 1 → `officer` (a boarded loan has no schedule: 2.1 cannot post, 2.7 cannot test, 11.1 cannot count; the boarding transaction should have refused)'. Rule 1: '`installments.write` runs inside the same unit of work as `loan.boarded` … `installment.schedule.written` satisfies `SM_INSTALLMENT_SCHEDULE_AT_BOARD_0` in the same commit' — src/domain/operations-runtime/boarding-writes.ts appendBoardingWritten on both paths (transfers.ts boardTransferBatch, section01.ts boardLoan, origination.ts fundApplication). The boarded event carries `boarded_at` (an instant), not `boarded_on`; the anchor is that instant's civil date." });
  o("SM_LOAN_SERVICING_CONFIG_AT_BOARD_0", { anchorField: "boarded_at",
    why: "§35.5 timer table row `SM_LOAN_SERVICING_CONFIG_AT_BOARD_0`: deadline on `loan.boarded`, anchor `boarded_on`, offset '0', satisfied by `loan.servicing_config.written`, breach 'sev 2 → `compliance` (a boarded loan has no time zone, jurisdiction or servicer profile: every day count and notice would fall back to a constant, which rule 9 forbids)'. Rule 9: '`servicing_config.write` runs at `loan.boarded` in the boarding transaction … `loan.servicing_config.written` satisfies `SM_LOAN_SERVICING_CONFIG_AT_BOARD_0`' — src/domain/operations-runtime/servicing-config.ts appendConfigWritten through boarding-writes.ts on both paths. `boarded_at` is the event's spelling of the boarding instant." });
  // Timer table row `SM_INSTALLMENT_REPROJECT_1BD`: one clock, three spellings of the trigger — the registry row keeps the first; the override arms on the `loan_terms.*` prefix, which at HEAD names exactly 2.4's `loan_terms.activated` (src/domain/cashiering/ops.ts activateReamortizedTerms), 7.2's `loan_terms.version.activated` (src/domain/notices/ops-7-2.ts makeEffective, correctAdjustment) and 3.6's / 12.8's `loan_terms.versioned` (src/domain/escrow/ops-3-6.ts, src/domain/lossmit/ops-12-8.ts) — a closed list (installments.ts REPROJECT_TRIGGERS) the unit consumes.
  o("SM_INSTALLMENT_REPROJECT_1BD", { trigger: "`loan_terms.*`", anchorField: "effective_on",
    why: "§35.5 timer table row `SM_INSTALLMENT_REPROJECT_1BD`: deadline on '`loan_terms.activated` / `loan_terms.version.activated` / `loan_terms.versioned`', anchor `activated_on`, offset '+1 business_days_servicer', satisfied by `installment.schedule.reprojected`, breach 'sev 2 → `officer` (terms changed and the schedule still shows the old P&I / rate: statements and drafts would state the wrong amount)'; the table's note: '`SM_INSTALLMENT_REPROJECT_1BD` arms on three spellings of one fact — 2.4's `loan_terms.activated`, 7.2's `loan_terms.version.activated` and 3.6/12.8's `loan_terms.versioned` — through a cited override in `src/domain/operations-runtime/timers-35-5.ts` that lists all three as triggers … `activated_on` is the event's `effective_from` / `effective_on` / `effective_date`'. The registry holds one trigger pattern per code, so the override names the `loan_terms.*` prefix (src/kernel/timers/registry.ts triggeredBy honours a trailing `*`); the anchor is 2.4's and 7.2's `effective_on` (3.6's `effective_from` and 12.8's `effective_date` fall to the event's own civil date). Satisfied by src/domain/operations-runtime/installments.ts reprojectSchedule (`installments.reproject`, run by the cashiering unit on the first pass after the terms event)." });
  // Timer table rows `SM_LOCKBOX_FILE_EXPECTED_1BD` and `SM_LOCKBOX_BATCH_POSTED_1BD` trigger on `lockbox.batch.received`, a literal 2.1 (src/domain/cashiering/ops-2-1.ts LockboxIntake.receiveBatch, payload `file_hash`) and 6.1 (src/domain/custodial/ops-6-1.ts ingestLockboxBatch, payload `received_on`) also emit for their own clocks; 35.5's ingest (src/domain/operations-runtime/lockbox.ts) is the batch that carries `sha256` and `receipt_date`, and only that batch owns a posting clock.
  o("SM_LOCKBOX_BATCH_POSTED_1BD", { trigger: "`lockbox.batch.received{sha256 present}`", anchorField: "receipt_date",
    why: "§35.5 timer table row `SM_LOCKBOX_BATCH_POSTED_1BD`: deadline on `lockbox.batch.received`, anchor `receipt_date`, offset '+1 business_days_servicer', satisfied by `lockbox.batch.posted`, breach 'sev 2 → `officer` (an item is neither posted nor in 6.5's suspense one business day after receipt: a credit-as-of-receipt exposure, §1026.36(c)(1))'. Rule 7: '`lockbox.batch.received{lockbox_id, batch_id, receipt_date, items, control_total_cents, sha256}` … once every item is a payment or a suspense item, `lockbox.batch.posted` (satisfying `SM_LOCKBOX_BATCH_POSTED_1BD`)' — src/domain/operations-runtime/lockbox.ts. The `sha256 present` condition keeps 2.1's and 6.1's own `lockbox.batch.received` (deposit clocks, no posting step) from arming a posting clock nothing satisfies." });
  // Timer table row `SM_ACH_RETURN_ACTIONED_1BD`: anchor `received_on` — 2.3's `ach.return.received` (src/domain/cashiering/ops.ts handleReturn, driven by 35.5's `ach.return.action` through 2.3's `autodraft.read/write{op=return}`) spells the return settlement date `returned_on`.
  o("SM_ACH_RETURN_ACTIONED_1BD", { anchorField: "returned_on",
    why: "§35.5 timer table row `SM_ACH_RETURN_ACTIONED_1BD`: deadline on `ach.return.received`, anchor `received_on`, offset '+1 business_days_federal', satisfied by `ach.return.actioned`, breach 'sev 2 → `officer` (a return is unactioned: the payment stands credited on a returned item, or the retry window is slipping)'. Rule 8: 'each return matched to its `ach_entries` row by trace number and written as `ach_returns` with `ach.return.received{code}` (2.3's literal); `ach.return.action` then applies 2.3 rule 7 … `ach.return.actioned` satisfies `SM_ACH_RETURN_ACTIONED_1BD`' — src/domain/operations-runtime/ach.ts. 2.3's payload carries the return's settlement date as `returned_on` (src/domain/cashiering/ops.ts:174); the anchor is that date." });
  // Timer table row 1: a recurring global clock — the environment day's, re-armed by each completion (timers-33-2.ts precedent).
  o("SM_CASHIERING_DAILY_RECEIPT_1D", { anchorField: "as_of_date", subject: "global",
    why: "§35.5 timer table row `SM_CASHIERING_DAILY_RECEIPT_1D`: recurring on `cashiering.daily.run_completed`, anchor `as_of_date`, offset '+1 calendar_days', satisfied by `cashiering.daily.run_completed`, breach 'sev 2 → `officer` (no whole-book cashiering run completed for a calendar day; 35.4's `eod_cutoff` cannot receipt)' — 'Trigger & frequency: Per loan at `loan.boarded` (both paths) and at every `loan_terms.activated`; daily for the whole book (the `cashiering_daily` cycle of 35.3); daily on the lockbox file, the ACH file build and the NACHA return file'. The receipt is one global event per environment-day (or per run for the 90-day drill), not a loan's or an application's, so the clock is the platform's: armed on the global subject (subject: \"global\") by the first completion, satisfied by the next completion and re-armed for the one after (anchor as_of_date + the row's offset) — the timers-33-2.ts precedent for a recurring global clock (SM_PARTNER_BOOK_REVIEW_DAILY)." });
  // Timer table row 2: a recurring global clock — the environment day's, re-armed by each completion (timers-33-2.ts precedent).
  o("SM_LOCKBOX_FILE_EXPECTED_1BD", { anchorField: "receipt_date", subject: "global", trigger: "`lockbox.batch.received{sha256 present}`", satisfied: "`lockbox.batch.received{sha256 present}`",
    why: "§35.5 timer table row `SM_LOCKBOX_FILE_EXPECTED_1BD`: recurring on `lockbox.batch.received`, anchor `receipt_date`, offset '+1 business_days_servicer', satisfied by `lockbox.batch.received`, breach 'sev 2 → `officer` (no remittance file by 10:00 local on a servicer business day: SFTP, PGP or the bank — items may be waiting uncredited)' — 'Trigger & frequency: Per loan at `loan.boarded` (both paths) and at every `loan_terms.activated`; daily for the whole book (the `cashiering_daily` cycle of 35.3); daily on the lockbox file, the ACH file build and the NACHA return file'. The receipt is one global event per environment-day (or per run for the 90-day drill), not a loan's or an application's, so the clock is the platform's: armed on the global subject (subject: \"global\") by the first completion, satisfied by the next completion and re-armed for the one after (anchor receipt_date + the row's offset) — the timers-33-2.ts precedent for a recurring global clock (SM_PARTNER_BOOK_REVIEW_DAILY)." });
  // Timer table row 3: a recurring global clock — the environment day's, re-armed by each completion (timers-33-2.ts precedent).
  o("SM_ACH_FILE_BUILD_1BD", { anchorField: "as_of_date", subject: "global",
    why: "§35.5 timer table row `SM_ACH_FILE_BUILD_1BD`: recurring on `ach.file.built`, anchor `as_of_date`, offset '+1 business_days_federal', satisfied by `ach.file.built`, breach 'sev 2 → `officer` (no ACH file built by 14:00 ET on a banking day: tomorrow's drafts will miss their settlement date and C-1.1-03's penalty-free window)' — 'Trigger & frequency: Per loan at `loan.boarded` (both paths) and at every `loan_terms.activated`; daily for the whole book (the `cashiering_daily` cycle of 35.3); daily on the lockbox file, the ACH file build and the NACHA return file'. The receipt is one global event per environment-day (or per run for the 90-day drill), not a loan's or an application's, so the clock is the platform's: armed on the global subject (subject: \"global\") by the first completion, satisfied by the next completion and re-armed for the one after (anchor as_of_date + the row's offset) — the timers-33-2.ts precedent for a recurring global clock (SM_PARTNER_BOOK_REVIEW_DAILY)." });
}
