/**
 * §35.12 timer overrides (process-owned; applied after every section's so they win the merge — see
 * src/domain/bankruptcy/timers-14-1.ts for the pattern). One `reg.override(code, { trigger?, satisfied | evaluator,
 * anchorField?, offset?, why })` per 35.12 registry row whose trigger/satisfied column names an event the platform
 * spells differently or a condition the column grammar drops; `why` quotes the spec. A code the servicing spec
 * (sections 1–19) owns is never overridden here — reference it. Wired by src/domain/timer-overrides.ts.
 *
 * 35.12's recurring clocks (SM_PROD_POSTURE_DAILY, SM_PROD_RESTORE_DRILL_90D, SM_PROD_PARALLEL_RUN_DAILY) are global: each is armed by a per-day (or per-run) completion receipt on
 * the global subject, not by a loan or application aggregate, so each takes the cited `subject: "global"` override
 * on the src/domain/partner-book/timers-33-2.ts precedent (SM_PARTNER_BOOK_REVIEW_DAILY). The deadline rows of 35.12
 * parse and arm from the registry as written and need no override.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_35_12(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // Timer table row 1: a recurring global clock — the environment day's, re-armed by each completion (timers-33-2.ts precedent).
  o("SM_PROD_POSTURE_DAILY", { anchorField: "as_of_date", subject: "global",
    why: "§35.12 timer table row `SM_PROD_POSTURE_DAILY`: recurring on `posture.check.run_completed`, anchor `as_of_date`, offset '+1 calendar_days', satisfied by `posture.check.run_completed`, breach 'sev 2 → `ciso` (no posture run today: the environment is unmeasured)' — 'Trigger & frequency: On every deploy (`posture.record` is the last step of `.github/workflows/deploy.yml`, before the smoke); the posture check daily at 05:30 America/New_York as a 35.3 cycle (`posture.check`, global scope) and on every manifest; the nonprod data scan daily at 05:45 America/New_York; the restore drill every 90 calendar days; the parallel-run reconciliation daily at 21:00 America/New_York for 28 consecutive days; the go-live checklist on demand and the attestation once per environment'. The receipt is one global event per environment-day (or per run for the 90-day drill), not a loan's or an application's, so the clock is the platform's: armed on the global subject (subject: \"global\") by the first completion, satisfied by the next completion and re-armed for the one after (anchor as_of_date + the row's offset) — the timers-33-2.ts precedent for a recurring global clock (SM_PARTNER_BOOK_REVIEW_DAILY)." });
  // Timer table row 2: a recurring global clock — the environment day's, re-armed by each completion (timers-33-2.ts precedent).
  o("SM_PROD_RESTORE_DRILL_90D", { anchorField: "completed_at", subject: "global",
    why: "§35.12 timer table row `SM_PROD_RESTORE_DRILL_90D`: recurring on `backup.restore_drill.passed`, anchor `completed_at`, offset '+90 calendar_days', satisfied by `backup.restore_drill.passed`, breach 'sev 1 → `ciso` (the quarterly restore was not proven; 19.2's annual clock still runs)' — 'Trigger & frequency: On every deploy (`posture.record` is the last step of `.github/workflows/deploy.yml`, before the smoke); the posture check daily at 05:30 America/New_York as a 35.3 cycle (`posture.check`, global scope) and on every manifest; the nonprod data scan daily at 05:45 America/New_York; the restore drill every 90 calendar days; the parallel-run reconciliation daily at 21:00 America/New_York for 28 consecutive days; the go-live checklist on demand and the attestation once per environment'. The receipt is one global event per environment-day (or per run for the 90-day drill), not a loan's or an application's, so the clock is the platform's: armed on the global subject (subject: \"global\") by the first completion, satisfied by the next completion and re-armed for the one after (anchor completed_at + the row's offset) — the timers-33-2.ts precedent for a recurring global clock (SM_PARTNER_BOOK_REVIEW_DAILY)." });
  // Timer table row 3: a recurring global clock — the environment day's, re-armed by each completion (timers-33-2.ts precedent).
  o("SM_PROD_PARALLEL_RUN_DAILY", { anchorField: "as_of_date", subject: "global",
    why: "§35.12 timer table row `SM_PROD_PARALLEL_RUN_DAILY`: recurring on `parallel_run.day.reconciled`, anchor `as_of_date`, offset '+1 calendar_days', satisfied by `parallel_run.day.reconciled`, breach 'sev 2 → `officer` (a parallel-run day was not reconciled; the clean-week count resets)' — 'Trigger & frequency: On every deploy (`posture.record` is the last step of `.github/workflows/deploy.yml`, before the smoke); the posture check daily at 05:30 America/New_York as a 35.3 cycle (`posture.check`, global scope) and on every manifest; the nonprod data scan daily at 05:45 America/New_York; the restore drill every 90 calendar days; the parallel-run reconciliation daily at 21:00 America/New_York for 28 consecutive days; the go-live checklist on demand and the attestation once per environment'. The receipt is one global event per environment-day (or per run for the 90-day drill), not a loan's or an application's, so the clock is the platform's: armed on the global subject (subject: \"global\") by the first completion, satisfied by the next completion and re-armed for the one after (anchor as_of_date + the row's offset) — the timers-33-2.ts precedent for a recurring global clock (SM_PARTNER_BOOK_REVIEW_DAILY)." });
}
