/**
 * §18.6 timer satisfaction overrides: for every 18.6 registry row whose "Satisfied by"
 * column is prose, a `reg.override(code, { satisfied | evaluator, trigger?, offset?, anchorField?, why })`
 * (see src/domain/foreclosure/timers.ts applyForeclosureSatisfiedOverrides for the pattern).
 * Called from this section's timers.ts after the section-level overrides.
 *
 * Every 18.6 row is a deadline/recurring clock with a calendar offset, so each is satisfied by an event the
 * attestation module emits (the `attestation_packages.status` transitions of the state machine — src/app/tools/section18-6.ts
 * `attestation_package.transition` over ops-18-6.ts packageTransition — the §6.3 reconciling-item resolution, or the partner
 * notice) rather than by an evaluator, which would replace the offset.
 *
 * Triggers: the five FYE rows arm on `attestation.cycle.opened` — the attestation module's own event at the FYE of a program's
 * assessment period (rule 18.6-4: the issuer's PSA year may differ from Supermortgage's fiscal year), never on the corporate
 * `period.fiscal_year_end` of §18.4/§19 (whose Form 582 / AFS / ISBR clocks a cycle must not arm, and which would arm once per
 * program). The FYE rows anchor on the payload's `fye`, so a cycle opened after year-end still counts from year-end.
 * The (2)(vii) row arms on `regab.reconciling_item.opened{regab_applicable=true}` — the Reg AB view of §6.3's
 * `reconciliation_item.opened` derived by the 18.6 reactor (section18-6.ts attestationReactors_18_6 over ops-18-6.ts
 * classifyReconItem) — keyed to the *item* (`regab_reconciling_item` aggregate), never to the custodial account: the timer engine
 * satisfies every open clock on the satisfying event's subject, so an account-keyed clock would let one item's resolution satisfy
 * every other item's clock on that account. §6.3's `reconciliation_item.resolved` is therefore re-keyed to the item by the same
 * reactor (`regab.reconciling_item.resolved`, ops-18-6.ts reconItemResolvedView), which is what satisfies the row.
 *
 * `TimerRegistry.override` re-derives `anchorField` from the raw anchor column ("FYE", "item date" → null), so a per-process
 * override must restate the computed anchor the section-level override set or the clock silently collapses to the event date.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_18_6(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  o("REGAB_1122_ASSESSMENT_PSA_DUE", { trigger: "`attestation.cycle.opened{regab_applicable=true}`", anchorField: "psa_assessment_due", offset: "0", satisfied: "`attestation.package.delivered{kind=regab_1122_assessment}`", why: "§18.6 timer table: trigger 'fiscal year-end (when `regab_applicable`)' — the attestation cycle's own FYE event per program (rule 18.6-4: the issuer's PSA year, not the corporate `period.fiscal_year_end`); anchor FYE, offset 'per PSA (default FYE + 60 days UNVERIFIED); warning at FYE + 30' — the cycle event carries the computed PSA date (`psa_assessment_due`, ops-18-6 regAbClocks: FYE + 60 unless the PSA says otherwise) and the warning at FYE + 30 (raised by `attestation.warning.check`, ops-18-6 assessmentWarning); satisfied by 'assessment + attestation delivered' — the 1122 package reaches `delivered` only after `attestation_received` (state machine), so its delivery event carries both (17 CFR 229.1122(a)–(b); Instruction 3)." });
  o("REGAB_1123_STATEMENT_PSA_DUE", { trigger: "`attestation.cycle.opened{regab_applicable=true}`", anchorField: "psa_statement_due", offset: "0", satisfied: "`attestation.package.delivered{kind=regab_1123_statement}`", why: "§18.6 timer table: FYE (partner as servicer) → officer statement per PSA (default FYE + 60) — the attestation cycle's FYE event with the computed anchor `psa_statement_due`; satisfied by 'officer statement delivered' — the Item 1123 statement / sub-certification package delivered to the partner's officer (17 CFR 229.1123; rule 18.6-5)." });
  o("SM_SOC1_TYPE2_ANNUAL", { trigger: "`attestation.cycle.opened`", anchorField: "fye", why: "§18.6 timer table: trigger 'fiscal year', anchor FYE, 'report issued by FYE + 75 days' — arms on the attestation cycle's FYE event for every book (open question 1: SOC 1 Type II from year one) anchored on the payload `fye` (FYE + 75 = 2027-03-16 for FYE 2026-12-31 even when the cycle is opened in January); satisfied by `attestation.report.received{soc1}` (`attestation_report.receive` with kind soc1_type2)." });
  o("SM_ATTEST_EVIDENCE_COMPILE_FYE_15", { trigger: "`attestation.cycle.opened`", anchorField: "fye", satisfied: "`attestation.package.status_changed{status=evidence_compiled}`", why: "§18.6 timer table: trigger FYE, anchor FYE, 15 calendar days — the attestation cycle's FYE event anchored on its `fye` payload; '`control_evidence` complete for all matrix rows' — `planned → evidence_compiled` is refused unless every in-scope control_matrix row has a `control_evidence` row for the package period whose latest generation is complete at its frequency (ops-18-6 evidenceCompleteness over the stores; rule 18.6-4; packageTransition REGAB_EVIDENCE_INCOMPLETE)." });
  o("SM_ATTEST_MANAGEMENT_ASSERTION_FYE_45", { trigger: "`attestation.cycle.opened`", anchorField: "fye", satisfied: "`attestation.package.status_changed{status=assertion_signed, signed_by_role=officer}`", why: "§18.6 timer table: trigger FYE, anchor FYE, 45 calendar days — the attestation cycle's FYE event anchored on its `fye` payload (18.6-T2: assertion due 2027-02-14); 'assertion signed by `officer`' — the `assertion_signed` transition is refused without an officer signature record (18.6-T7; packageTransition REGAB_ASSERTION_SIGNATURE_RECORD / REGAB_AGENT_NEVER_SIGNS: the agent never signs or asserts)." });
  o("SM_MATERIAL_NONCOMPLIANCE_PARTNER_1BD", { satisfied: "`partner.notified{reason=material_noncompliance}`", why: "§18.6 timer table: 'partner notified' — the `partner.notified` event with reason `material_noncompliance` (18.6 `partner.notify` tool) within 1 business day of `material_noncompliance.determined` (rule 18.6-3: disclosed in the assessment and to the partner within 1 BD)." });
  o("REGAB_1122_2VII_RECON_ITEMS_90", { trigger: "`regab.reconciling_item.opened{regab_applicable=true}`", anchorField: "item_date", satisfied: "`regab.reconciling_item.resolved{status∈{cleared, posted, funded}}`", why: "§18.6 timer table: custodial reconciling item aged (item date) → resolved within 90 calendar days; §6.3's `reconciliation_item.opened` carries no Reg AB fields and sits on the custodial-account aggregate, so the 18.6 reactor derives `regab.reconciling_item.opened{item_id, account_id, item_date=first_seen_on, program_id, regab_applicable}` from it on a per-item aggregate `regab_reconciling_item` (ops-18-6 classifyReconItem) — one clock per item, so resolving one item never satisfies another item's clock on the same account (18.6-T4: an item aged 91 days is always a breach); Item 1122(d)(2)(vii) covers 'all ABS bank accounts', so only items on accounts of a `regab_applicable` program start the Reg AB clock (18.6-T1: no REGAB_* timers for a Fannie Mae book); satisfied by 'item resolved (Section 6.3)' — §6.3's `reconciliation_item.resolved{item_id, status}` re-keyed to the item by the same reactor (ops-18-6 reconItemResolvedView) as `cleared`/`posted`/`funded`; breached → the reactor records the control exception for 1122(d)(2)(vii) (18.6-T4)." });
}
