/**
 * §18.1 timer satisfaction overrides: for every 18.1 registry row whose "Satisfied by"
 * column is prose, a `reg.override(code, { satisfied | evaluator, trigger?, offset?, anchorField?, why })`
 * (see src/domain/foreclosure/timers.ts applyForeclosureSatisfiedOverrides for the pattern).
 * Called from this section's timers.ts after the section-level overrides, so these win the merge.
 * Every event named here is one src/domain/qc-audit/ops-18-1.ts emits: signCycle, reportDelivered,
 * vendorTestCompleted, populationFinding / moneyRederiveFinding / findingTransition, capaCompletion,
 * completeCapa, effectivenessCheck, consumerRemediation, qcResultsDelivered, annualPolicyReview,
 * aiDisclosureRequest, sendAiDisclosure, approveVersion, deployVersion (carries `impact_assessment_due`),
 * monitoringReviewed, impactAssessmentCompleted, isbrAttestationSigned, planApproved and afsReceived — and the trigger
 * emitters: `qcScheduleTicks` (`schedule.tick{business_day=3}`, `period.month_end`, `period.fiscal_year_end{csbs_audit_required}`),
 * `onboardVendor` (`vendor.onboarded`), `validateFinding` / `rejectFinding` (`qc.finding.validated{remediation_cents_total}`),
 * `proposeVersion` (`ai.version.proposed`), `approvePolicy` (`ai.policy.approved`) and `qcResultsRequestReceived`
 * (`fnma.request.received{kind=qc_results}`); `appendQcEvent` is the one write path behind all of them.
 * 18-1.spec.test.ts drives every armable row through the real TimerEngine from those events, satisfies it in-engine and
 * checks the kernel's re-arm of each recurring row lands on the next period (the anchor fields the satisfying events carry).
 *
 * Not in spec/registry/timers.json (so not overridable here): `SM_QC_CAPA_SEV2_30` / `SM_QC_CAPA_SEV3_90` — the
 * spec's timer table folds them into the `SM_QC_CAPA_SEV1_10BD` row ("10 BD / 30 / 90 calendar days") and the
 * process's Timers attribute lists only the sev-1 code; `capaDueOn` computes the 30/90-day clocks until the
 * registry carries their rows.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_18_1(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // ---- cycle, reports, vendors, validation ---------------------------------------------------
  o("FNMA_A4101_QC_CYCLE_MONTHLY", { anchorField: "cycle_clock_opens_on", offset: "+17 business_days_servicer", satisfied: "`qc.cycle.signed`", why: "§18.1 timer table: calendar BD3 → close by BD20 (`business_days_servicer`), satisfied by `qc.cycle.signed` — `signCycle` emits it only for officer:qc_officer (state machine: `signed` by `officer:qc_officer`); breach sev-2 → officer:qc_officer (A4-1-01). Trigger: the scheduler's `schedule.tick{cadence=monthly, business_day=3}` (`qcScheduleTicks`) carrying `cycle_clock_opens_on` = the BD3 date, so BD3 + 17 BD = BD20 (`monthlyCycleWindow`). The row is recurring, so the kernel re-arms it from `qc.cycle.signed`: that event carries `cycle_clock_opens_on` = the next cycle's BD3, never the signature date." });
  o("FNMA_A4101_QC_REPORT_SENIOR_MGMT_MONTHLY", { trigger: "`qc.cycle.signed`", anchorField: "signed_at", offset: "+5 business_days_servicer", satisfied: "`qc.report.delivered{audience=senior_management}`", why: "§18.1 timer table: `qc.cycle.signed` → senior-management report within 5 business days, satisfied by `qc.report.delivered{senior_management}` — `reportDelivered` emits `qc.report.delivered{audience=senior_management}` only with delivery evidence (T5: Fri 2026-09-04 before Labor Day → due Mon 2026-09-14, 'satisfies on delivery evidence'); breach sev-2 (A4-1-01 'report comprehensive results of all testing to the senior management')." });
  o("SM_QC_REPORT_PARTNER_MONTHLY", { trigger: "`qc.cycle.signed`", anchorField: "signed_at", offset: "+5 business_days_servicer", satisfied: "`qc.report.delivered{audience=partner}`", why: "§18.1 timer table: `qc.cycle.signed` → partner report (PDF + JSON) within 5 business days, satisfied by `qc.report.delivered{partner}` — `reportDelivered{audience=partner}` with the SFTP/portal delivery evidence; missed delivery → breach sev-2 (subservicing agreement)." });
  o("FNMA_A4101_VENDOR_QC_TEST_ANNUAL", { trigger: "`vendor.onboarded`", anchorField: "onboarded_on", offset: "+12 months", satisfied: "`qc.vendor_test.completed`", why: "§18.1 timer table: `vendor.onboarded` then annually (anniversary) → 12 months, warning at 75% (9 months), satisfied by `qc.vendor_test.completed` per active vendor — `vendorTestCompleted` emits it with the Vendor QC Test Report; `vendorAnnualClock` (T6: onboarded 2026-03-15 → warn 2026-12-15, breach 2027-03-15); breach sev-1 → officer (A4-1-01 'annual QC tests … all outsourcing firms and third-party vendors')." });
  o("SM_QC_FINDING_VALIDATE_5BD", { trigger: "`qc.finding.opened`", anchorField: "opened_at", offset: "+5 business_days_servicer", satisfied: "`qc.finding.*{status∈{validated, rejected}}`", why: "§18.1 timer table: `qc.finding.opened` → `qc.finding.validated`/`rejected` within 5 business days — both finding kinds emit `qc.finding.opened{opened_at}`: `populationFinding` (rule B tolerance, level=population) and `moneyRederiveFinding` (rule C / T2 subject-level money finding, level=subject); `findingTransition` lets only officer:qc_officer validate or reject (rejection with rationale; findings are never deleted), and either decision (`qc.finding.validated{status=validated}` / `qc.finding.rejected{status=rejected}`) satisfies; breach sev-3." });
  // ---- CAPA clocks ------------------------------------------------------------------------
  o("SM_QC_CAPA_SEV1_10BD", { trigger: "`qc.finding.validated{severity=sev1_consumer_harm_or_fnma_breach}`", anchorField: "validated_at", offset: "+10 business_days_servicer", satisfied: "`qc.finding.capas_completed`", why: "§18.1 timer table: `qc.finding.validated` → 'all CAPAs `completed`' within 10 BD for sev-1 (30 / 90 calendar days for sev-2 / sev-3 are `SM_QC_CAPA_SEV2_30` / `SM_QC_CAPA_SEV3_90`, `capaDueOn`); `capaCompletion` emits `qc.finding.capas_completed` when the last CAPA on the finding completes; breach → sev-1 escalation to `officer`, sev-1 also to the partner (T4: validated 2026-10-01 → due 2026-10-16, Columbus Day; docs/AUDIT-NOTES.md)." });
  o("SM_QC_CAPA_EFFECTIVENESS_NEXT_CYCLE", { trigger: "`qc.capa.completed`", anchorField: "next_cycle_close_on", offset: "0", satisfied: "`qc.capa.effectiveness_tested{result=pass}`", why: "§18.1 timer table: CAPA completed → 'effectiveness test pass' at the next cycle close — `completeCapa` emits `qc.capa.completed{next_cycle_close_on}` (BD20 of the following month, `nextCycleCloseOn`) as the computed anchor; `effectivenessCheck` re-runs the rule against its tolerance and emits `qc.capa.effectiveness_tested{result}` — a `fail` reopens the finding instead of satisfying the timer." });
  o("SM_QC_CONSUMER_REMEDIATION_30", { trigger: "`qc.finding.validated{remediation_cents_total>0}`", anchorField: "validated_at", offset: "+30 calendar_days", satisfied: "`qc.remediation.completed{refunds_posted=true, notices_sent=true}`", why: "§18.1 timer table: finding with `remediation_cents_total>0` validated → 'refunds posted + notices sent' within 30 calendar days (rule C: correcting ledger set posted by the owning agent, corrected notice from the Notice Registry; T2: CAPA `refund` with the 30-day timer); `consumerRemediation` emits `qc.remediation.completed` when both halves are evidenced; breach sev-1." });
  // ---- Fannie Mae requests / external audit ------------------------------------------------
  o("FNMA_A4101_FNMA_QC_RESULTS_REQUEST_10BD", { trigger: "`fnma.request.received{kind=qc_results}`", anchorField: "received_at", offset: "+10 business_days_servicer", satisfied: "`fnma.request.delivered{kind=qc_results}`", why: "§18.1 timer table: `fnma.request.received{qc_results}` → 'package delivered (18.2)' per the request, default 10 business days (A4-1-01: 'Results of the QC tests must be provided to Fannie Mae upon request'; 'comprehensive results of all testing and evidence of correction actions taken available for review upon Fannie Mae's request'); the officer-signed package leaves as a `human_portal_task` and `qcResultsDelivered` records `fnma.request.delivered{kind=qc_results}`." });
  o("FNMA_LL202604_AI_DISCLOSURE_REQUEST_5BD", { trigger: "`fnma.request.received{kind=ai_disclosure}`", anchorField: "received_at", offset: "+5 business_days_servicer", satisfied: "`ai.disclosure.sent{signed_by_designation=ai_governance_owner}`", why: "§18.1 timer table: `fnma.request.received{ai_disclosure}` → `ai.disclosure.sent` within 5 business days (LL-2026-04 'promptly disclose the types of AI/ML used, the purpose and manner for such use, the safeguards'; internal SLA) — `aiDisclosureRequest` logs the request, `aiDisclosurePackage` assembles it from the inventory, `sendAiDisclosure` emits `ai.disclosure.sent` only when signed by officer:ai_governance_owner and delivered by fnma_portal_operator (T9: received 2026-11-02 → by 2026-11-09); breach sev-1 → officer." });
  o("CSBS_EXTERNAL_AUDIT_ANNUAL", { trigger: "`period.fiscal_year_end{csbs_audit_required=true}`", anchorField: "csbs_clock_fye", offset: "+12 months", satisfied: "`afs.received{audit_opinion=true}`", why: "§18.1 timer table: fiscal year-end (when ≥2,000 loans in ≥2 states, `csbsExternalAudit`) → 'AFS with audit opinion received (18.7)' within 12 months — `afsReceived` records the audited financial statements and emits `afs.received{audit_opinion=true}` only when the auditor's opinion is on the AFS (CSBS Model Prudential Standards: external audit); breach sev-2. Trigger: the 18.1 scheduler's `period.fiscal_year_end` (`qcScheduleTicks`) carries `csbs_audit_required` from `csbsExternalAudit` (≥ 2,000 loans in ≥ 2 states) and `csbs_clock_fye` = the FYE; `afs.received` carries `csbs_clock_fye` = the next FYE so the recurring row re-arms at next FYE + 12 months, not 12 months after receipt." });
  // ---- AI governance (LL-2026-04, Colorado) -------------------------------------------------
  o("SM_AI_EVAL_GATE", { evaluator: "18.1.aiEvalGatePassed", why: "§18.1 timer table: `ai.version.proposed` → not-before gate 'until `ai_evaluations.pass` for all mandatory suites + approval'; `deployVersion` asserts `18.1.aiEvalGatePassed` over the version's suites and `approved_by` (rule D.3; T7: a prompt-injection failure keeps the version `evaluated`), satisfied by `ai.version.approved` from `approveVersion` (officer:ai_governance_owner)." });
  o("FNMA_LL202604_AI_POLICY_REVIEW_ANNUAL", { trigger: "`ai.policy.approved`", anchorField: "approved_at", offset: "+12 months", satisfied: "`ai.policy.reviewed{signed_by_owner=true}`", why: "§18.1 timer table: policy approved → review every 12 months, warning 60 days; satisfied by `ai.policy.reviewed` signed by owner — `annualPolicyReview` emits it only for officer:ai_governance_owner (LL-2026-04 'owner(s) that implements, maintains and reviews the policies and procedures at least annually'); breach sev-1." });
  o("SM_AI_MONITORING_REVIEW_MONTHLY", { trigger: "`period.month_end`", anchorField: "monitoring_clock_month_end", offset: "+5 business_days_servicer", satisfied: "`ai.monitoring.reviewed`", why: "§18.1 timer table: calendar, anchor BD5, monthly — the review of a month's `ai_monitoring_metrics` (rule D.5: 'daily; reviewed monthly') is due on BD5 of the following month, so the row arms on `period.month_end` with +5 `business_days_servicer` (month-end 2026-09-30 → due Wed 2026-10-07 = BD5; the section-level `schedule.tick{business_day=5}` + 'monthly' encoding put the due date a month *after* BD5). Satisfied by `ai.monitoring.reviewed` — `monitoringReviewed` emits it for the AI governance owner or the QC officer naming the month and the systems reviewed; breach sev-2. Anchor `monitoring_clock_month_end`: the scheduler's `period.month_end` carries the month-end (`qcScheduleTicks`), and the review event carries the *next* month-end, so the kernel's re-arm of this recurring row lands on the next BD5 rather than 5 BD after the review." });
  o("CO_AI_ACT_IMPACT_ASSESSMENT_ANNUAL", { trigger: "`ai_system.deployed{risk_tier=T1_consequential, change_kind∈{new, major}}`", anchorField: "impact_assessment_due", offset: "0", satisfied: "`ai.impact_assessment.completed`", why: "§18.1 timer table: T1 system deployed → impact assessment within 12 months, and within 90 days of a `major` change [PARTIALLY VERIFIED — Colorado SB 24-205 cadence]. The registry's `risk_tier ∈ {T1_consequential, …}` (data model), so the trigger is `risk_tier=T1_consequential`; `deployVersion` runs `impactAssessmentClock` and emits `ai_system.deployed{risk_tier, change_kind, deployed_at, impact_assessment_due}` — the computed anchor this row reads (new: deployed_at + 12 months; major: + 90 days, or the earlier open due; minor: carried forward, and the trigger pattern does not arm); `impactAssessmentCompleted` emits `ai.impact_assessment.completed{impact_assessment_due}` which satisfies and re-arms the recurring row 12 months out; breach sev-1." });
  o("FNMA_ISBR_ANNUAL_ATTESTATION", { trigger: "`period.fiscal_year_end`", anchorField: "isbr_clock_fye", offset: "+90 calendar_days", satisfied: "`isbr.attestation.signed{signed_by_role=officer}`", why: "§18.1 timer table: program approved → annual attestation aligned to the Form 582 window (FYE + 90), satisfied by `isbr.attestation.signed` by `officer` — `isbrAttestationSigned` emits it only for a corporate officer (ISBR Supplement 'written attestation executed by a duly authorized corporate officer'); Section 19 owns the evidence, 18.1 tracks; breach sev-1. Anchor `isbr_clock_fye`: the fiscal year-end on the scheduler's tick (`qcScheduleTicks`; a tick without the field anchors on its own date, the FYE) and the *next* fiscal year-end on `isbr.attestation.signed`, so the recurring row re-arms at next FYE + 90 and never 90 days after the signature." });
  o("FNMA_A4101_QC_PLAN_REAPPROVAL_ANNUAL", { trigger: "`qc.plan.approved{initial=true}`", anchorField: "approved_at", offset: "+12 months", satisfied: "`qc.plan.approved`", why: "§18.1 timer table: plan approved → re-approval every 12 months, satisfied by `qc.plan.approved` (new version) — `planApproved` emits it once the officer-approved plan is signed and accepted by the partner (Operational prerequisites: `QC-PLAN-2026.1`); breach sev-2. The first approval (`initial=true`, no `supersedes_version`) arms the recurring row; a re-approval (`initial=false`) satisfies it and the kernel re-arms from its `approved_at` — with a bare `qc.plan.approved` trigger the same re-approval would arm the clock a second time." });
}
