/**
 * §18.5 timer satisfaction overrides: for every 18.5 registry row whose "Satisfied by"
 * column is prose or shorthand, a `reg.override(code, { satisfied | evaluator, trigger?, offset?, anchorField?, why })`
 * (see src/domain/foreclosure/timers.ts applyForeclosureSatisfiedOverrides for the pattern).
 * Called from this section's timers.ts after the section-level overrides.
 *
 * Every row here is deadline-shaped, so each keeps its parsed offset and gains a dotted
 * satisfaction event that the fraud module actually emits (the event shapes are the
 * `*Event` builders in ./ops-18-5.ts: caseStatusChangedEvent, fraudPartnerNotifiedEvent,
 * determinationRecordedEvent, fraudReportFiledEvent, leReferralDecidedEvent,
 * coveredLossDiscoveredEvent, selfReportRequiredEvent) or, for the Section 19 row 18.5
 * co-files, the event Section 19 itself emits (ops-19-2.ts incidentNoticeSent, which
 * cyberIncidentNoticeEvent wraps) — never an evaluator, which would replace the offset.
 * `anchorField` is always passed explicitly: registry.override re-derives it from the raw
 * anchor column otherwise, which would clobber a section-level anchor (e.g. `identified_at`).
 * The one offset override (FNMA_A4222_LAWFIRM_FRAUD_2BD) puts a Fannie Mae deadline on
 * Fannie Mae's calendar: the column's bare "2 business days" would otherwise parse as
 * `business_days_servicer`, letting a servicer-only closure extend a Fannie Mae deadline.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_18_5(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  o("SM_FRAUD_TRIAGE_2BD", { anchorField: "opened_at", satisfied: "`fraud.case.status_changed{status=triaged}`", why: "§18.5 timer table: 'triaged' — the state machine's `flagged → triaged (score/priority)` transition by `qc-audit` (caseStatusChangedEvent) within 2 business days of `fraud.case.opened` (openFraudCase, anchor `opened_at`); breach sev-3." });
  o("SM_FRAUD_DUE_DILIGENCE_15", { anchorField: "opened_at", satisfied: "`fraud.determination.recorded`", why: "§18.5 timer table: `fraud.case.opened` → `fraud.determination.recorded` (determinationRecordedEvent — the officer's act under a determination role, any determination) within 15 calendar days of `opened_at`; breach 'sev-2 → `officer:fraud_officer` (protects the 30-day window)' — the registry's role parser reads only bare backticked roles, so the colon-qualified role leaves the row's escalateTo empty; breachEscalation reads `officer:fraud_officer` from the engine's own breach (its breachText is this column) and routes it to the `fraud_officer` escalation (T3)." });
  o("FNMA_A3403_FRAUD_REPORT_30", { trigger: "`fraud.determination.recorded{reasonable_basis=true}`", anchorField: "determination_at", satisfied: "`fraud.report.filed{channel=lqc_self_report, lqc_reference present}`", why: "§18.5 timer table: `fraud.determination.recorded{reasonable_basis}` → '`fraud.report.filed{lqc_self_report}` with LQC reference' within 30 calendar days of `determination_at` (A3-4-03 'must notify Fannie Mae within 30 days using the self-report functionality in Loan Quality Connect'); internal target day 20 (rule 4). The registry shorthand `{lqc_self_report}` would read as a truthy field of that name — the filing is `fraud_reports.channel = lqc_self_report` (fraudReportFiledEvent, officer-signed) and must carry the captured `lqc_reference` (reportFilingOutcome refuses a filing without one); a filing after the due date is `satisfied_late` (T2); breach sev-1 → `officer` + partner." });
  o("SM_FRAUD_PARTNER_NOTIFY_1BD", { trigger: "`fraud.*{partner_notice_leg∈{open, determination}}`", satisfied: "`partner.notified{kind=fraud_case, evidence_document_id present}`", why: "§18.5 timer table: '`fraud.case.opened` with score ≥ 60, and again at determination' → 'partner notified (evidence)' within 1 business day of the event (subservicing agreement, sev-1 contract). Both legs are real spec events carrying `partner_notice_leg`: openFraudCase sets `open` on `fraud.case.opened` only when the score is ≥ 60 (P1/P2), determinationRecordedEvent sets `determination` on `fraud.determination.recorded` (rule 4 worked example: 2026-10-06 and 2026-10-15; partnerNoticeLegs). Satisfied only by an evidenced notice (fraudPartnerNotifiedEvent → `fraud_cases.partner_notified_at`)." });
  o("FNMA_A3201_OFAC_MATCH_24H", { satisfied: "`fraud.report.filed{channel=ethics_email_ofac}`", why: "§18.5 timer table: `ofac.match.confirmed` (anchor: the confirmation timestamp — the event's own instant) → '`fraud.report.filed{ethics_email_ofac}`' within 24 clock hours (A3-2-01 'within 24 hours'; weekends count, T4). The registry shorthand `{ethics_email_ofac}` would read as a truthy field of that name — the filing is `fraud_reports.channel = ethics_email_ofac` (fraudReportFiledEvent; content per ofacEthicsNotice: borrower name, Fannie Mae loan number, servicer contact); breach sev-1 → `officer`; OFAC blocking per 31 CFR 501 (Section 19)." });
  o("FNMA_A4222_LAWFIRM_FRAUD_2BD", { anchorField: "discovered_on", offset: "+2 business_days_fannie_et", satisfied: "`fraud.report.filed{channel=fnma_legal_email}`", why: "§18.5 timer table: 'Fannie Mae Legal email evidenced' — the officer-signed `FRAUD-LAWFIRM-2BD-v1` email recorded in `fraud_reports` with channel `fnma_legal_email` within 2 business days of `lawfirm.fraud.alleged` (payload `discovered_on`; lawFirmFraudEscalation) (A4-2.2-02 'actual or alleged fraud' by a law firm; Section 13 co-owner, 18.5 co-files). The column's bare '2 business days' parses as `business_days_servicer`; a Fannie Mae deadline counts on Fannie Mae's calendar (`business_days_fannie_et`, as fraud.ts lawFirmFraudNoticeDue defaults), so a servicer-only closure never extends it (T5)." });
  o("FNMA_A3201_BREACH_SELF_REPORT_60", { trigger: "`fraud.self_report.required{basis∈{count_over_500, pct_over_1, repurchase_risk_not_remediable_60}}`", anchorField: "self_report_anchor_on", satisfied: "`fraud.report.filed{channel=lqc_self_report, kind=breach_self_report}`", why: "§18.5 timer table: `qc.finding.validated{population ≥ 500 loans or ≥ 1% of prior-year deliveries}` or `repurchase_risk_breach.determined` → 'LQC self-report filed' within 60 calendar days (A3-2-01). The grammar carries one trigger per row and cannot express the two-event 'or' with its population-or-percentage predicate, so this process listens to both spec events and publishes `fraud.self_report.required` (selfReportRequiredEvent) with the computed anchor `self_report_anchor_on` = later of quarter-end and discovery (QC-finding leg) or the determination (repurchase-risk leg); satisfied by the LQC self-report recorded in `fraud_reports` (channel `lqc_self_report`, kind `breach_self_report`); breach sev-1." });
  o("SM_FRAUD_LE_REFERRAL_DECISION_10BD", { trigger: "`fraud.determination.recorded{reasonable_basis=true, le_referral_candidate=true}`", anchorField: "determination_at", satisfied: "`fraud.le_referral.decided{decision∈{refer, not_refer}}`", why: "§18.5 timer table: '`reasonable_basis` determination with loss/exposure > $25,000 or identity theft/employee dishonesty' (leReferralDecision sets `le_referral_candidate` on determinationRecordedEvent from the exposure and the determined scheme — `scheme_code` identity_theft / employee_dishonesty or an employee subject; a screening hit or identity mismatch flag alone is neither) → '`attorney` decision recorded (refer / not refer with reason)' within 10 business days of `determination_at` (leReferralDecidedEvent: attorney only, reason required when not referring); a `refer` decision is followed by `fraud.referral.sent{law_enforcement}`; breach sev-2." });
  o("SM_FRAUD_CARRIER_NOTICE_IMMEDIATE", { anchorField: "discovered_on", satisfied: "`fraud.report.filed{channel=carrier}`", why: "§18.5 timer table: 'employee dishonesty / covered loss discovered' — `fraud.covered_loss.discovered` (coveredLossDiscoveredEvent, payload `discovered_on`; an employee-dishonesty determination discovers it through employeeDishonestyFollowUp, rule 7) → 'carrier notice evidenced' — the officer-signed carrier claim package recorded in `fraud_reports` with channel `carrier` (fraudReportFiledEvent) within 1 business day (fidelity bond/E&O event, A3-5-04; policy 'immediate' / 'as soon as practicable' terms UNVERIFIED); breach sev-1." });
  o("FNMA_ISBR_CYBER_INCIDENT_36H", { anchorField: "identified_at", satisfied: "`incident.notice.sent{recipient=fannie_mae_supplement}`", why: "§18.5 timer table: 'incident identified (incl. BEC behind a payoff-diversion)' (`security.incident.identified`, anchor `identified_at` — Section 19 convention, kept explicitly here) → 'notice to privacy_office@fanniemae.com' within 36 clock hours (ISBR Supplement; business-email compromise reportable 'regardless of impact'). The notice is Section 19's: 19.2 records the officer's send to privacy_office@fanniemae.com as `incident_notices.recipient = fannie_mae_supplement` and emits `incident.notice.sent{recipient=fannie_mae_supplement}` (ops-19-2.ts incidentNoticeSent — the same event that closes 19.2's FNMA_SUPP_INCIDENT_NOTICE_36H), so that one send closes both rows; cyberIncidentNoticeEvent wraps that builder to link the fraud case. Section 19 owns the incident, 18.5 co-files when fraud rides on the compromise; breach sev-1." });
}
