/**
 * §18.2 timer overrides: for every 18.2 registry row whose trigger / anchor / "Satisfied by" column is prose, a
 * `reg.override(code, { trigger?, satisfied | evaluator, offset?, anchorField?, why })` (see
 * src/domain/foreclosure/timers.ts applyForeclosureTimerOverrides for the pattern). Called from this section's
 * timers.ts after the section-level overrides, so these win the merge. Every trigger and satisfying event named here
 * is appended to the event store by a real code path — an ops-18-2 event-store function (ingestExamNotice,
 * ingestExamRequest, recordInternalNotification, recordPackageApproval, recordSubmission, ingestExamFinding,
 * recordRemediationPlanApproval, recordFindingResponse, ingestRemedyDemand, ingestLitigationNotice) or the bus tool
 * that calls it (src/app/tools/section18-2.ts: documents.compile_pdf, its `op=approve`, letters.render `op=release`,
 * cases.create{qc_finding}), or ./ops-18-1.ts qcResultsDelivered; 18-2.spec.test.ts arms and satisfies each row
 * through the TimerEngine by those paths.
 *
 * Two rows use a computed anchor with offset 0 because their offset column is a condition, not a clock (the pattern
 * FNMA_SCR_FINDING_RESPONSE_AS_STATED already follows): FNMA_A2401_REVIEW_FILE_30 is due on the rule-4 `due_at` the
 * notice event carries (notification + 30 CD or the shorter/longer period Fannie Mae states — the row's own
 * "`due_at` override"), SM_EXAM_PACKAGE_OFFICER_REVIEW_3BD on the `approve_by` = min(assembled + 3 BD, due − 1 BD)
 * the assembled event carries. Both therefore breach in TimerEngine.evaluate. The 50 %/80 % warning columns have no
 * kernel kind: they are the request rows' warn_50_at/warn_80_at, fired by ops-18-2 examDeadlineSweep.
 *
 * Note: `TimerRegistry.override` re-parses `anchorField` from the raw anchor column on every call, so an override
 * that does not pass `anchorField` silently drops one set earlier — every row here passes it explicitly.
 */
import type { TimerRegistry } from "../../kernel/timers/registry.ts";

export function applySatisfiedOverrides_18_2(reg: TimerRegistry): void {
  const o = reg.override.bind(reg);
  // ---- intake and scoping ------------------------------------------------------------------
  o("FNMA_A2401_REVIEW_FILE_30", { trigger: "`exam.notice.received{source=fnma_lqc, review_type=servicing_review}`", anchorField: "due_at", offset: "0", satisfied: "`exam.request.submitted{channel=fnma_lqc, lqc_confirmation_id present, remaining_open_requests=0}`", why: "§18.2 timer table: `exam.notice.received{fnma_lqc, servicing_review}` (Inputs: `source ∈ {fnma_lqc, …}`) → '30 calendar days (or the shorter/longer period stated; `due_at` override)' — the notice event carries `due_at` = notification + 30 CD (A2-4-01) or the period Fannie Mae states (rule 4; ops-18-2 examClocks18_2/noticeEvent), so the row is due on that date, not on a fixed +30 that a shorter stated period would overshoot; rule 4's prior-business-day internal target rides on the same event; 'warning at 50% and 80%' = the request rows' warn_50_at/warn_80_at fired by examDeadlineSweep (no kernel warning kind); satisfied by `exam.request.submitted` with LQC confirmation — the `lqc_confirmation_id` the `fnma_portal_operator` records (integrations) — on the submission that leaves no request of the review open; breach sev-1 → `officer` + partner, compensatory-fee exposure logged." });
  o("SM_EXAM_INTERNAL_NOTIFY_2BD", { trigger: "`exam.contact.received`", anchorField: "received_at", satisfied: "`exam.notice.acknowledged{partner_notified=true, officer_notified=true}`", why: "§18.2 timer table: 'any examiner contact' → partner + officer notified within 2 business days of receipt (operational prerequisites: the exam response protocol's 2-business-day internal notification of any Fannie Mae/regulator contact). The pattern grammar names one event type, so every intake path records the contact as `exam.contact.received`: the LQC e-mail / letter notice (ops-18-2 scopeNotice emits noticeContactEvent alongside `exam.notice.received`), phone/portal/e-mail/partner-forward contacts (examinerContact). `exam.notice.acknowledged` exists only once both are notified, recorded against the contact on record (ops-18-2 recordInternalNotification)." });
  o("SM_EXAM_SCOPE_5BD", { anchorField: "received_at", satisfied: "`exam.scoped`", why: "§18.2 timer table: `exam.notice.received` → `exams.status=scoped` within 5 business days of receipt — the state-machine transition received → scoped once the notice is parsed into `exam_requests` with taxonomy nodes and loan lists (rule 1; ops-18-2 scopeNotice emits `exam.scoped`)." });
  o("EXAM_REQUEST_DUE_AS_STATED", { anchorField: "due_at", satisfied: "`exam.request.submitted{submission_evidence present}`", why: "§18.2 timer table: each `exam.request.received` item — the spec's Inputs: 'each document/information request item with due date', so scopeNotice emits one per loan file (subject: the loan) and examRequestReceived one per letter item (T7: a CFPB 10-business-day deadline resolved over the federal holiday) — is due on the letter's stated date (`exam_requests.due_at`, offset 0) and is satisfied by 'submission evidence' — the confirmation/tracking recorded on that item's `exam.request.submitted` (submissionRecorded refuses without it); 'warning 50%/80%' = the row's warn_50_at/warn_80_at fired by examDeadlineSweep, which drafts the extension request at 80 % without a package (rule 5)." });
  // ---- production and officer review ------------------------------------------------------
  o("SM_EXAM_PACKAGE_OFFICER_REVIEW_3BD", { trigger: "`exam.package.assembled`", anchorField: "approve_by", offset: "0", satisfied: "`exam.package.approved{approved_by_role=officer}`", why: "§18.2 timer table (not_before_gate + deadline): package assembled → 'package must sit ≥1 BD for review and be approved ≥1 BD before due; officer has 3 BD'. Deadline half: computed anchor `approve_by` = min(assembled + 3 BD, due − 1 BD), stamped on `exam.package.assembled` by ops-18-2 packageAssembled (packageReviewWindow), offset 0 — so TimerEngine.evaluate breaches it (sev-2; examDeadlineSweep drafts the extension request, rule 5). Not-before half: `review_opens_on` = assembled + 1 BD on the same event, asserted by officerApproval and the bus guardrails — an approval before it is refused. Satisfied by the officer's approval — the `officer` actor's act on the package on record (ops-18-2 recordPackageApproval behind `documents.compile_pdf op=approve`), stamped on `exam_productions.approved_by_officer_id`/`approved_at`; the LQC upload task (`human_portal_task.create`) is refused until that approval is on record for the manifest it carries." });
  // ---- findings and remediation -----------------------------------------------------------
  o("FNMA_SCR_FINDING_RESPONSE_AS_STATED", { anchorField: "response_due_stated", offset: "0", satisfied: "`exam.finding.responded{response_document_id present}`", why: "§18.2 timer table: `exam.finding.received` → 'response submitted' by the letter's stated date (Servicing Compliance Review; default 30 calendar days per open question 3) — computed anchor `response_due_stated` on the event (ops-18-2 examFindingReceived), satisfied by the officer-signed EXAM-RESP-v1 letter recorded on `exam_findings.response_document_id` (ops-18-2 recordFindingResponse behind `letters.render op=release`; the finding itself is ingested by ingestExamFinding behind `cases.create{qc_finding}`)." });
  o("SM_EXAM_REMEDIATION_PLAN_15BD", { anchorField: "received_at", satisfied: "`exam.remediation_plan.approved{qc_finding_case_id present, approved_by_role=officer}`", why: "§18.2 timer table: `exam.finding.received` → 'remediation plan approved (CAPA set in 18.1)' within 15 business days of receipt — the mirrored `qc_finding` case reaches `capa_assigned` (18.1 state machine: root cause required first) with the officer's approval — the `officer` actor's act on a finding on record (ops-18-2 recordRemediationPlanApproval; rule 6; T5)." });
  o("FNMA_A4101_FNMA_QC_RESULTS_REQUEST_10BD", { anchorField: "received_at", satisfied: "`fnma.request.delivered{kind=qc_results}`", why: "§18.2 timer table (18.1 row): 'QC results request → delivered' within 10 BD default — QC results, policies and 'examples of the application' delivered on request (Selling Guide A4-1-01; records access item 4; ops-18-1 qcResultsDelivered emits the event)." });
  // ---- litigation hold -------------------------------------------------------------------
  o("SM_EXAM_LITIGATION_HOLD", { trigger: "`exam.notice.received{source∈{litigation_discovery, subpoena}}`", evaluator: "18.2.litigationHoldReleased", why: "§18.2 timer table: `exam.notice.received{litigation_discovery}` or subpoena → not-before gate 'until released by counsel', no due date; the retention purge job feeds the hold into the platform's retention gate as the `legal_hold` fact (17.3 retentionFloorElapsed refuses on it) and is refused while the gate is closed — only an `attorney` release opens it (ops-18-2 ingestLitigationNotice appends the arming notice; retentionPurge / legalHoldFacts / litigationHoldReleased; T8; audit: RESPA-litigation production set)." });
}
